Node.d.ts Decompose  class EventEmitter w/ _static
DefinitelyTyped/DefinitelyTyped pull request #11095
Opened 2016-09-07 19:54 UTC by BurtHarris

This decomposition is to allow declaration of circular definition of EventEmitter in module events, per docs at https://nodejs.org/dist/latest-v6.x/docs/api/events.html#events_class_eventemitter,.   

See issue #10968 for related discussion.

2016-09-07 21:20 UTC, BurtHarris commented
For some strange reason, declaring EventEmitter as an interface was generating CI errors.

2016-09-07 22:49 UTC, hriss95 commented
Looking good. Will try to see if it is possible to leave as NodeJs.EventEmitter as an interface next thing in the morning, although you are right about it being a class and being declared as such reasonable.

2016-09-08 09:30 UTC, hriss95 commented
Hi @BurtHarris , I think that keeping NodeJS.EventEmitter declared as a class is reasonable. Also, I am generally a little bit confused by the previous notion of having EventEmitter defined in the NodeJS namespace and then being extended in "events" module. Being inspired by the solution I gave to issue #11085 by creating pull request #11086, I thought of giving a different approach to how to refactor the "events" module which does not need declaring anything outside the module:
```
declare module "events" {
    class internal extends NodeJS.EventEmitter {
        addListener(event: string, listener: Function): this;
        on(event: string, listener: Function): this;
        once(event: string, listener: Function): this;
        prependListener(event: string, listener: Function): this;
        prependOnceListener(event: string, listener: Function): this;
        removeListener(event: string, listener: Function): this;
        removeAllListeners(event?: string): this;
        setMaxListeners(n: number): this;
        getMaxListeners(): number;
        listeners(event: string): Function[];
        emit(event: string, ...args: any[]): boolean;
        eventNames(): string[];
        listenerCount(type: string): number;
    }
    namespace internal {

        class EventEmitter extends internal {}
        function listenerCount(emitter: EventEmitter, event: string): number; // deprecated
        var defaultMaxListeners: number;
    }

    export = internal;
}
```

This should work in the exact same way as what you have done. Let me know what your thoughts are about it.

2016-09-08 16:45 UTC, BurtHarris commented
@hriss95, The reason I did it this was was should avoid having two different places where the EventEmitter members are defined.   Issue #10815, captured it.

2016-09-08 18:46 UTC, hriss95 commented
@BurtHarris Ah, yes, I forgot the initial reason of you doing this. Well, as I said, it looks good and since mine is not resolving the syncing problem, there is no other option but to do what you did. :+1:

2016-09-09 15:31 UTC, vvakame commented
umm... I think #10888 is not so good.
`NodeJS` should be ghost namespace. but It becomes concrete namespace now.
I loved http://goo.gl/XwwAbz this pattern.

cc/ @RyanCavanaugh

2016-09-09 18:15 UTC, BurtHarris commented
@vvakame, I think I understand your comment, but find very little online detailing the concept of a "ghost namespace".  Are you aware of any detail?

I interpret your input to mean that the only class definition should be in module "events", which makes good sense to me.   I'll try to see if I can come up with an alternate version that works that way.

2016-09-09 18:39 UTC, BurtHarris commented
No luck with several attempts to define the class in module "events" and then export an interface from NodeJS  *based on it* .   Of course it's possible to go back to defining parallel interface in NodeJS, but that's exactly what I was hoping to avoid.

2016-10-03 17:59 UTC, mhegazy requested changes

2016-10-03 17:59 UTC, mhegazy commented on node/node.d.ts
> +    interface EventEmitter_Static {
you do not need a new interface. just add these as static members on the class:

```ts
 static EventEmitter: typeof EventEmitter;
 /** @deprecated */
 static listenerCount(emitter: EventEmitter, event: string): number;
 static defaultMaxListeners: number;
```

2016-10-03 17:59 UTC, mhegazy commented on node/node.d.ts
> +    export = EventEmitter;
```ts
export = NodeJS.EventEmitter
```

2016-10-03 17:59 UTC, mhegazy commented on node/node.d.ts
> +    export = EventEmitter;
this should work in TS 2.0 as you would expect.

2016-10-03 19:14 UTC, BurtHarris commented on node/node.d.ts
> +    export = EventEmitter;
I'll take a look at this in the next couple of days...

2016-11-03 22:32 UTC, jramsay commented on node/node.d.ts
> +    export = EventEmitter;
@BurtHarris: can you update the PR to address @mhegazy's comments?  Thanks!

2016-11-04 18:14 UTC, BurtHarris commented on node/node.d.ts
> +    export = EventEmitter;
I'm kind of deep into to  many things.   Unfortunately many of them non-technical but important.   I'll try to find some time this weekend.

2016-11-16 23:06 UTC, minestarks commented
@BurtHarris please let me know if you plan to make the requested changes, otherwise I'll close out the PR as it's been untouched for a while.

2016-11-22 04:01 UTC, BurtHarris commented
@mhegazy, sorry family commitments will prevent me from spending much time on this in the near to mid term.

2016-11-28 18:04 UTC, paulvanbrenk commented
Going to close this, you can re-open later. 

Thanks!

2016-11-28 18:04 UTC, closed without merging