Add justifyContent to CssProperties
DefinitelyTyped/DefinitelyTyped pull request #11268
Opened 2016-09-16 11:33 UTC by ligaz

`justifyContent` was missing from CssProperties and this PR adds it. More information about it [here](https://facebook.github.io/react-native/docs/layout-props.html#justifycontent).

2016-09-19 06:23 UTC, vvakame commented
We can't get response from author. please ping me after 3 days. I'll merge this PR.

2016-09-19 22:54 UTC, vsiao commented
You linked to react-native docs. Did you mean to contribute to `react-native.d.ts` instead?

2016-09-19 22:59 UTC, vsiao commented on react/react.d.ts
> +        * Aligns children in the main direction. For example, if children are flowing vertically, justifyContent controls how they align vertically. It works like justify-content in CSS (default: fle
this doc comment doesn't make sense outside of the context of React Native (it doesn't just *work* like `justify-content` in CSS, it literally *is* `justify-content`). can you use language from https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content instead?

style nits: `*` should be aligned, and line-length under 100 chars please

2016-09-19 22:59 UTC, vsiao commented on react/react.d.ts
> +        justifyContent?: 'flex-start' | 'flex-end' | 'center' | 'space-between' | 'space-around';
double quotes, please

2016-09-19 22:59 UTC, vsiao requested changes

2016-09-20 04:45 UTC, ligaz commented
Thanks @vsiao. Your comments are addressed.

2016-09-20 05:16 UTC, vsiao commented on react/react.d.ts
> +        */
super tiny nit, sorry—the asterisks should be aligned:

```ts
/**
 *
 */
```

2016-09-20 05:16 UTC, vsiao commented
looks good after fixing the small nit, thanks! 👍

2016-09-20 05:52 UTC, ligaz commented
Done.

2016-09-20 13:49 UTC, merged

2016-09-20 15:27 UTC, serut commented
```
const styleAddAttribute = {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center"
}
[...]

return (
     <div style={styleAddAttribute}>
     </div>
);
```
raises this error : 
```
ERROR in ./web_modules/view/components/src/CardActionsComponent.tsx
(78,12): error TS2322: Type '{ display: string; flexDirection: string; justifyContent: string; }' is not assignable to type 'CSSProperties'.
  Types of property 'justifyContent' are incompatible.
    Type 'string' is not assignable to type '"center" | "flex-start" | "flex-end" | "space-between" | "space-around"'.
```
I tryed the following type, but without success
`: { [id: string]: React.CSSProperties }`

2016-09-20 18:22 UTC, ligaz commented
Hey @serut,

Have you tried with:
```tsx
const styleAddAttribute = {
      display: "flex",
      flexDirection: "row",
      justifyContent: "center"
} as React.CSSProperties;

[...]

return (
     <div style={styleAddAttribute}>
     </div>
);
```

2016-09-20 19:36 UTC, vsiao commented
I think declaring with a type annotation would be preferable:
```ts
const styleAddAttribute: React.CSSProperties = ...
```

2016-09-21 04:52 UTC, ligaz commented
I'm more a fan of type inference but I guess this is a personal preference.

2016-09-21 08:22 UTC, serut commented
Thanks @vsiao & @ligaz, it works.

2016-09-21 17:37 UTC, vsiao commented
@ligaz: `as React.CSSProperties` isn't type inference either. By using a type assertion you're essentially downcasting. So it's more dangerous than a type annotation.

2016-09-22 05:13 UTC, ligaz commented
@vsiao I was referring to the assignment operator type inference. In your case you are specifying the type on the variable whereas in mine the type if inferred from the right side.

2016-09-25 18:04 UTC, rlmckenney commented
This change broke a bunch of code that was previously working fine. :-(  

However, the solutions offered above work. Thanks!  

One point of clarification ... the declarative approach only works if you are defining a single style object.  However for the common pattern of using a compound object, we have to use the `as React.CssProperties` approach.  See example ...

```javascript
 const style = {
    outer: {
      padding: '40px 65px',
    } as React.CSSProperties,
    inner: {
      padding: '0 0',
      display: 'flex',
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      alignContent: 'flex-start'
    } as React.CSSProperties,
 }
```

2016-09-26 04:47 UTC, ligaz commented
Hey @rlmckenney,

Can you please give an example of the code that this change broke?

2016-09-26 17:21 UTC, rlmckenney commented
Hi @ligaz ,

All I meant was that previously I had lots of code similar to the above example but _without_ the `as React.CSSProperties` modifier.  Those would then be referenced in a component declaration like:
```js
<div style={style.inner}> ... content ... </div>
```
These worked perfectly well before this update.  Now I have to explicitly apply the `as React.CSSProperties` modifier, or it will raise an error like:

```
error TS2322: Type '{ display: string; flexDirection: string; justifyContent: string; }' is not assignable to type 'CSSProperties'.
  Types of property 'justifyContent' are incompatible.
    Type 'string' is not assignable to type '"center" | "flex-start" | "flex-end" | "space-between" | "space-around"'.
```

I don't mind the extra specificity.  It was just a surprise that something that was working suddenly started throwing errors and it took a while to track down the cause and solution.