Add FeatureLayers and GeoJSON layers to leaflet.d.ts
DefinitelyTyped/DefinitelyTyped pull request #11393
Opened 2016-09-22 03:38 UTC by sigh71

2016-09-22 18:00 UTC, alejo90 commented on leaflet/leaflet.d.ts
> +        coordsToLatLng: (coords: number[]) => LatLng;
The parameter's type can be more specific: `[number, number] | [number, number, number]`

2016-09-22 18:02 UTC, alejo90 commented on leaflet/leaflet.d.ts
> +        options: TooltipOptions;
I couldn't find this on the docs.

2016-09-22 18:03 UTC, alejo90 commented on leaflet/leaflet.d.ts
> +        options: MapOptions;
Couldn't find this one on the docs either.

2016-09-22 18:05 UTC, alejo90 requested changes
First of all, thanks for the help. There are a couple of minor issues but other than that, it looks great. Also, make sure your next commit passes the CI tests.

2016-10-03 18:17 UTC, mhegazy commented
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2016-10-03 18:17 UTC, closed without merging