Add stackLabels property into HighchartsAxisOptions interface
DefinitelyTyped/DefinitelyTyped pull request #11513
Opened 2016-09-26 15:21 UTC by cyrilgandon

Add stackLabels property into HighchartsAxisOptions interface

- Documentation: http://api.highcharts.com/highcharts/yAxis.stackLabels

Note that this is a property that only exists on yAxis. Maybe further work is too split yAxis and xAxis propertis in two different interface by sharing maybe a base interface.

2016-09-28 13:01 UTC, vvakame commented
We can't get response from author. please ping me after 3 days. I'll merge this PR.

2016-10-11 12:47 UTC, baltie commented on highcharts/highcharts.d.ts
> +        style?: Object;
This should be the HighchartsCSSObject, not Object.

2016-10-11 12:48 UTC, baltie requested changes
Please change the style type. Apart from that, this looks fine.

2016-10-11 13:06 UTC, cyrilgandon commented
Yes, of course, I used an example on another style property, and I got the `Object`. But most of the time it is `HighchartsCSSObject` which is far better. Thank you I've done the update.
I will try to find the time to change all the `Object` to `HighchartsCSSObject` where it make sense on another PR.

2016-10-12 08:07 UTC, baltie commented
@cyrilgandon Thank you! :)
@dt-bot LGTM :+1:

2016-10-12 08:16 UTC, baltie approved these changes

2016-10-12 13:37 UTC, vvakame commented
@cyrilgandon please resolve conflict.

2016-10-13 06:25 UTC, cyrilgandon commented
@vvakame : conflicts have been resolved.

2016-10-13 06:38 UTC, cyrilgandon commented
@baltie : I think I have made a little error, I plan to use TypeScript2.0 and the @types typings, and I just realised that the master branch is for legacy typings, I should have made a PR on the types-2.0 branch instead.
So I'm going to send another PR for that!

2016-10-13 13:39 UTC, baltie commented
@cyrilgandon Unless I'm very mistaken, I think changes are merged periodically from master to the types-2.0 branch, so a separate PR for types-2.0 should be unnecessary.

2016-10-13 13:50 UTC, cyrilgandon commented
@baltie : that's what is was supposed to be at the beginning of types-2.0, but I read that's that will not be the case.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/10711

> The merge from master to types-2.0 is manual, so "bad" merges in that direction shouldn't be happening. If you see this happen, let us know.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11210

>We can merge master into types-2.0, but We can't reverse it before TypeScript 2.0 stable release.
If we merge PR into master and types-2.0 branch both. Merge operation require veeeeery high calories.
I want to avoid it.

If you look at the history, the last merged happens a long time ago, so I don't want to depend on future decision, moreover, for me at least, it is not clear what  will happen to master and types-2.0.
In doubt, I have made the PR on the types-2.0

2016-10-13 14:07 UTC, baltie commented
@cyrilgandon Hm, I think we read that differently. As I understood what I've been reading, there is a merge performed manually by Microsoft engineers periodically. Also, the last merge from master to types-2.0 for highcharts (and a lot of other libraries at that point) were done by @mhegazy eight days ago. Which I think was the last one before the merge that happened yesterday my local time.

@vvakame Do you have any insight, should we make separate types-2.0 PRs? Also, I think a lot of this confusion would be avoided if the contributing.md file were updated with information about this. :)

2016-10-16 13:21 UTC, merged

2016-10-16 13:29 UTC, vvakame commented
sorry, I don't have good insight.
I think `types-2.0` have a lot of different from `master` branch.
Microsoft team is resolving it by a human power.