Update typescript definition for selectize to 0.12.13
DefinitelyTyped/DefinitelyTyped pull request #11570
Opened 2016-09-28 15:20 UTC by naBausch

case 2. Improvement to existing type definition.
- https://github.com/selectize/selectize.js/blob/master/docs/api.md#methods_other

2016-09-28 15:27 UTC, adidahiya requested changes

2016-09-28 15:27 UTC, adidahiya commented on selectize/selectize.d.ts
> +// Definitions by: Natali Bausch <https://github.com/naBausch>
please include your name on the above line, in a list, like this:

```
 // Definitions by: Adi Dahiya <https://github.com/adidahiya>, Natali Bausch <https://github.com/naBausch>
```

2016-09-28 15:27 UTC, adidahiya commented on selectize/selectize.d.ts
> +
minor: extra newline

2016-09-28 15:27 UTC, adidahiya commented on selectize/selectize.d.ts
> +        updatePlaceholder: () => void;
for consistency, I think this should be written as:

```ts
updatePlaceholder(): void;
```

also, are you sure the return type is void? I know the docs don't say, but how does it work at runtime?

2016-09-28 16:28 UTC, naBausch commented on selectize/selectize.d.ts
> +// Definitions by: Natali Bausch <https://github.com/naBausch>
Done 👍

2016-09-28 16:29 UTC, naBausch commented on selectize/selectize.d.ts
> +
Done 👍

2016-09-28 16:30 UTC, naBausch commented
@adidahiya thanks for your feedback please see the updated version

2016-09-28 17:46 UTC, adidahiya approved these changes

2016-09-28 17:46 UTC, adidahiya commented
thanks, lgtm @naBausch 👍

2016-09-30 12:09 UTC, merged

2016-09-30 15:00 UTC, jantimon commented
How do we trigger a new release for https://www.npmjs.com/package/@types/selectize ?