Add missing Valdr typings for validation results and constraints
DefinitelyTyped/DefinitelyTyped pull request #11636
Opened 2016-09-30 15:37 UTC by christophercr

Add ValdrValidationResult and ValdrConstraints typings

2016-10-03 19:36 UTC, christophercr commented
Hi @ilbertz, could you have a look on these changes to see whether they can be merged?

Thanks!

2016-10-03 19:51 UTC, mhegazy requested changes

2016-10-03 19:51 UTC, mhegazy commented on valdr-message/valdr-message.d.ts
> +﻿// Type definitions for valdr.js v1.1.5+ (valdr-message)
this version number is used by other tools, e.g. publisher for @types. so please keep this to numbers.

2016-10-03 19:51 UTC, mhegazy commented on valdr/valdr.d.ts
> +﻿// Type definitions for valdr.js v1.1.5+
same here.

2016-10-03 22:14 UTC, christophercr commented
Sorry for that. I've changed it.

Thanks for your review.

2016-10-04 20:22 UTC, ilbertz approved these changes
Looks good.

2016-10-04 20:58 UTC, merged

2016-10-04 20:58 UTC, mhegazy commented
thanks @ilbertz for the review.