Add seamless-immutable type definition file
DefinitelyTyped/DefinitelyTyped pull request #11717
Opened 2016-10-04 22:03 UTC by alex3165

case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

2016-10-04 23:11 UTC, mhegazy requested changes

2016-10-04 23:11 UTC, mhegazy commented on seamless-immutable/seamless.d.ts
> +// Project: https://github.com/rtfeldman/seamless-immutable
the file name should be `seamless-immutable\seamless-immutable.d.ts`

2016-10-04 23:11 UTC, mhegazy commented on seamless-immutable/seamless.d.ts
> +// Copyright (c) 2016, Richard Feldman
For legal reasons, we can not have different licence text for packages. all packages use the MIT licence under: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE

2016-10-04 23:11 UTC, mhegazy commented on seamless-immutable/seamless.d.ts
> +// Copyright (c) 2016, Richard Feldman
So we will not be able to accept this PR as long as it has this specialized licence text.

2016-10-04 23:11 UTC, mhegazy commented on seamless-immutable/seamless.d.ts
> +    update(property: string, updaterFunction: (value: any, additionalParameter1: any) => any, arg1: any): ImmutableObject<T>;
I would recommend changing these into one signature with rest args:

```ts
update(property: string, updaterFunction: (value: any, ...additionalParamters: any[]) => any, ...additionalArguments: any[]): ImmutableObject<T>;
```

2016-10-04 23:11 UTC, mhegazy commented on seamless-immutable/seamless.d.ts
> +    without(property: string): ImmutableObject<any>;
this is already covered by `without(...properties: string[]): ImmutableObject<any>;`

2016-10-05 09:35 UTC, alex3165 commented
@mhegazy Thank you for your advice I have made the changes.

2016-10-05 20:21 UTC, mhegazy approved these changes

2016-10-05 20:21 UTC, mhegazy commented
thanks. can you please address the failing CI tests.

2016-10-06 16:08 UTC, alex3165 commented
@mhegazy Fixed

2016-10-06 17:17 UTC, merged

2017-05-18 12:10 UTC, toranb commented
Anyone have an example app using this w/ TS 2x ? Just looking around for some samples to see how you would import and use use something like `SI.ImmutableObject` with ES2015+ syntax and TS 2