Add types definition for jstz (jsTimezoneDetect)
DefinitelyTyped/DefinitelyTyped pull request #11716
Opened 2016-10-04 21:55 UTC by olamothe

case 1. Add a new type definition.
- [X] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [X] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

Original jsTimezoneDetect project repository : https://bitbucket.org/pellepim/jstimezonedetect

2016-10-04 23:04 UTC, mhegazy commented on jstz/jstz.d.ts
> +declare module "jstz" {
the module name on npm is "jstimezonedetect". also the file name should be changed to `jstimezonedetect`

2016-10-04 23:05 UTC, mhegazy requested changes
Please change the file name and the module name.

2016-10-05 13:15 UTC, olamothe commented on jstz/jstz.d.ts
> +declare module "jstz" {
Ahh, both are available on npm (jstz and jstimezonedetect), but you are right that jstz is an unofficial fork.

This is why I was confused.

I renamed everything to jstimezonedetect.

2016-10-05 20:44 UTC, merged

2016-10-05 20:44 UTC, mhegazy commented
thanks!