Add Leadfoot typings
DefinitelyTyped/DefinitelyTyped pull request #11733
Opened 2016-10-05 15:29 UTC by rogierschouten

2016-10-05 15:31 UTC, rogierschouten commented
Note these typings were taken from https://github.com/theintern/intern/blob/master/typings/leadfoot/leadfoot.d.ts

The dojo typings were modified to make the leadfoot typings work.  Dojo is a client-side library but leadfoot uses a small part of it (its promises) on the server-side. This means that the typings for Dojo and Node must co-exist.  To this end I removed the globals from the Dojo typings.  I think in types-2.0, having globals is no longer the way to go anyway, right?

2016-10-05 20:50 UTC, mhegazy commented
@vansimke can you review this change

2016-10-05 20:50 UTC, mhegazy commented on leadfoot/tsconfig.json
> +		"../node/index.d.ts",
do not include files outside the module. use `/// <reference types="node" />` instead

2016-10-05 20:50 UTC, mhegazy requested changes
Please remove the `../` references form the tsconfig.json file

2016-10-06 06:57 UTC, rogierschouten commented
@mhegazy done, thank you

2016-10-06 16:41 UTC, mhegazy approved these changes

2016-11-06 15:52 UTC, merged