resemblejs typings did not work at all
DefinitelyTyped/DefinitelyTyped pull request #11764
Opened 2016-10-06 09:33 UTC by rogierschouten

2016-10-06 16:50 UTC, mhegazy requested changes

2016-10-06 16:50 UTC, mhegazy commented on resemblejs/index.d.ts
> +declare module "resemblejs" {
use [UMD modules](http://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#umd) instead. 

Consider making it:

```ts
// Type definitions for Resemble.js v1.3.0
// Project: http://huddle.github.io/Resemble.js/
// Definitions by: Tim Perry <https://github.com/pimterry>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

export = Resemble;
export as namespace resemble;

/**
 * Retrieve basic analysis for a single image (add compareTo to compare with another).
 */
declare function Resemble(image: string | ImageData): Resemble.ResembleAnalysis;

declare namespace Resemble {
  /**
   * Set the resemblance image output style
   */
  function outputSettings(settings: OutputSettings): typeof Resemble;

  interface OutputSettings {
    errorColor: {
      red: number;
      green: number;
      blue: number;
    };
    errorType: string;
    transparency: number;
    largeImageThreshold: number;
  }

  interface ResembleAnalysis {
    /**
     * Run the analysis on this image and get the result
     */
    onComplete(callback: (result: ResembleAnalysisResult) => void): void;

    /**
     * Compare this image to another image, to get resemblance data
     */
    compareTo(fileData: string | ImageData): ResembleComparison;
  }

  interface ResembleAnalysisResult {
    red: number;
    green: number;
    blue: number;
    brightness: number;
  }

  interface ResembleComparison {
    /**
     * Run the analysis and get the comparison result
     */
    onComplete(callback: (result: ResembleComparisonResult) => void): void;

    ignoreNothing(): ResembleComparison;
    ignoreAntialiasing(): ResembleComparison;
    ignoreColors(): ResembleComparison;
    repaint(): ResembleComparison;

  }

  interface ResembleComparisonResult {
    /**
     * Do the two images have the same dimensions?
     */
    isSameDimensions: boolean;

    /**
     * The difference in width and height between the dimensions of the two compared images
     */
    dimensionDifference: {
      width: number;
      height: number;
    };

    /**
     * Get a data URL for the comparison image
     */
    getImageDataUrl(): string;

    /**
     * The percentage of pixels which do not match between the images
     */
    misMatchPercentage: number;

    diffBounds: {
      top: number;
      left: number;
      bottom: number;
      right: number;
    };

    analysisTime: number;
  }
}
```

2016-10-07 07:54 UTC, rogierschouten commented
@mhegazy done!

2016-10-07 18:43 UTC, mhegazy commented
I have a fix for the failing CI tests in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11835

2016-10-07 18:43 UTC, mhegazy approved these changes

2016-10-08 20:00 UTC, mhegazy commented
@rogierschouten there are new CI test failures that require attention.

2016-10-19 14:59 UTC, rogierschouten commented
This has been fixed. Merge?

2016-11-17 19:12 UTC, merged