Add typings for jcanvas
DefinitelyTyped/DefinitelyTyped pull request #11778
Opened 2016-10-06 12:38 UTC by rogierschouten

http://projects.calebevans.me/jcanvas/

2016-10-06 17:02 UTC, mhegazy requested changes

2016-10-06 17:02 UTC, mhegazy commented on jcanvas/index.d.ts
> +export = jcanvas;
this is not going to augment JQuery. i assuming this is what you want, `$("..").drawText` if so, then do not think this works, you need to keep it global for this to work.

2016-10-07 07:30 UTC, rogierschouten commented on jcanvas/index.d.ts
> +export = jcanvas;
We are currently using this module like below, and that works.  I've been fiddling with it for ages and this is the only way I got it to work.  What is it that you propose to change?

```
import jQuery = require("jquery");
(window as any).$ = jQuery;
(window as any).jQuery = jQuery;
import jcanvas = require("jcanvas");
jcanvas(jQuery, window);
```

2016-10-07 07:37 UTC, rogierschouten commented on jcanvas/index.d.ts
> +export = jcanvas;
Oh I get what you mean. Let's discard this PR I may enter a new one when I have the time.

2016-10-07 07:37 UTC, closed without merging