Add typings for ldapjs.
DefinitelyTyped/DefinitelyTyped pull request #11783
Opened 2016-10-06 13:42 UTC by rogierschouten

2016-10-06 17:07 UTC, mhegazy requested changes

2016-10-06 17:07 UTC, mhegazy commented on ldapjs/index.d.ts
> +declare module 'ldapjs' {
remove the `declare module "ldapjs" {`

2016-10-07 08:03 UTC, rogierschouten commented
@mhegazy done.

2016-10-07 18:44 UTC, mhegazy approved these changes

2016-10-07 18:45 UTC, mhegazy commented
I have a fix for the failing CI tests in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11835

2016-10-08 17:33 UTC, merged