Add typings for url-join.
DefinitelyTyped/DefinitelyTyped pull request #11784
Opened 2016-10-06 13:48 UTC by rogierschouten

2016-10-06 17:08 UTC, mhegazy requested changes

2016-10-06 17:08 UTC, mhegazy commented on url-join/index.d.ts
> +declare module "url-join" {
please remove `declare module "url-join" `

2016-10-06 17:12 UTC, mhegazy commented on url-join/index.d.ts
> +declare module "url-join" {
I should add that there is nothing wrong with your declaration per se. the difference here is when using `declare module "url-join"` you are declaring a **global** module called `url-join`, this means that there can only be one version of  it at a time, and if two components depend on two versions of `url-join` an error will be shown. 
if however, you remove `declare module` part, it stays within its scope, and thus multiple versions of this declaration can co-exist as they do not step on each other in the global scope.
Thanks for the numerous contributions!

2016-10-07 08:05 UTC, rogierschouten commented
@mhegazy done.

2016-10-07 18:45 UTC, mhegazy commented
I have a fix for the failing CI tests in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11835

2016-10-07 18:45 UTC, mhegazy approved these changes

2016-10-08 17:33 UTC, merged