Add typings for simplesmtp.
DefinitelyTyped/DefinitelyTyped pull request #11780
Opened 2016-10-06 13:10 UTC by rogierschouten

2016-10-06 17:05 UTC, mhegazy requested changes

2016-10-06 17:05 UTC, mhegazy commented on simplesmtp/index.d.ts
> +declare module "simplesmtp" {
do not use the external module declaration, just remove `declare module "simplesmtp" {` and everything should still work.

2016-10-07 07:26 UTC, rogierschouten commented
@mhegazy  done!

2016-10-07 17:04 UTC, mhegazy approved these changes
Thanks!

2016-10-07 18:44 UTC, mhegazy commented
I have a fix for the failing CI tests in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11835

2016-10-08 17:33 UTC, merged