Change checkbox.cascade to string
DefinitelyTyped/DefinitelyTyped pull request #11793
Opened 2016-10-06 16:37 UTC by rdogmartin

$.jstree.defaults.checkbox.cascade is a string, not a boolean. See https://www.jstree.com/api/#/?f=$.jstree.defaults.checkbox.cascade

2016-10-06 17:49 UTC, mhegazy requested changes

2016-10-06 17:49 UTC, mhegazy commented on jstree/jstree.d.ts
> +    cascade: '';
you mean `string` right?

2016-10-06 18:12 UTC, AdaskoTheBeAsT commented
Hi,

indeed there should be string

cascade: string;

Best regards

Adam

2016-11-16 23:35 UTC, minestarks commented
Thanks for the contribution @rdogmartin . This PR is getting stale so I plan to close it out in a couple of days if the requested changes aren't made.

2016-11-17 15:26 UTC, closed without merging