Update to Electron 1.4.3
DefinitelyTyped/DefinitelyTyped pull request #11794
Opened 2016-10-06 17:12 UTC by miniak

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

2016-10-06 20:31 UTC, rhysd commented on github-electron/github-electron.d.ts
> +		on(event: 'new-window', listener: (event: Event & { newGuest?: BrowserWindow },
Type definition of `event` looks adhoc.  Should we define new type extending `Event`?

```typescript
interface NewWindowListenerEvent extends Event {
    newGuest?: BrowserWindow;
}
```

2016-10-13 09:09 UTC, miniak commented on github-electron/github-electron.d.ts
> +		on(event: 'new-window', listener: (event: Event & { newGuest?: BrowserWindow },
done

2016-10-13 22:32 UTC, rhysd requested changes

2016-10-13 22:32 UTC, rhysd commented on electron/github-electron.d.ts
> +		resize(options: {
Is `options` mandatory?  If it can be omitted, `options?` is more  suitable.

2016-10-13 22:45 UTC, miniak commented on electron/github-electron.d.ts
> +		resize(options: {
https://github.com/electron/electron/blob/master/docs/api/native-image.md#imageresizeoptions

According to the documentation it's not optional.

2016-10-14 06:01 UTC, rhysd commented on electron/github-electron.d.ts
> +		resize(options: {
Oh, I see. Thanks.

2016-10-14 06:01 UTC, rhysd commented
LGTM :+1:

2016-10-14 22:23 UTC, merged