Updated AngularJs orderBy definition to version 1.5.8
DefinitelyTyped/DefinitelyTyped pull request #11790
Opened 2016-10-06 15:20 UTC by Venthe

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

2016-10-06 15:36 UTC, thorn0 commented
This type of the added `comparator` parameter isn't `(v1: T, v2: T) => number`. Please read the documentation https://docs.angularjs.org/api/ng/filter/orderBy
Also please use spaces for indentation, don't mix them with tabs.

2016-10-06 17:07 UTC, Venthe commented
I blame N++ for tabs :)

Done.

2016-10-06 17:08 UTC, thorn0 commented
The type of the `comparator` parameter is still wrong.

2016-10-06 17:23 UTC, Venthe commented
@thorn0 could you clarify? I'm not used to write in either JS or TS. As far as I can tell, it is OK now, or it was even better before. It does not help if you tell me "You've done it wrong, do it again" because I will not do it again, and this typing will be out of date as it was before. I've tried to fix it one more time.

2016-10-06 17:27 UTC, Venthe commented on angularjs/angular.d.ts
> -        value: any;
It's a revert

2016-10-06 18:06 UTC, thorn0 commented
Filters, in particular this one, are used almost exclusively in templates, which unfortunately aren't type checked at all. Do you have a real-life use case for these type definitions?

2016-10-06 18:17 UTC, Venthe commented
Yes I do – I had to use It at my work to override string comparator for grid, to include accented letters.

 

To achieve that, I had to skip angular.d.ts interface for angular’s filter entirely and set it to any – which is obviously a no go.

 

I’ve used comparator like this

Comp(val:any, val2:any) : number {

val=val.value; // Object really is {value, type, id}

val2=val2.value;

 

//Code for intl comparator which returns -1,0,1

}

 

And I really don’t have much more experience in TS, so even if I want to write a good code here, I’m kind of stumbling around in unknown regions for me :)

 

From: Georgii Dolzhykov [mailto:notifications@github.com] 
Sent: Thursday, October 6, 2016 8:07 PM
To: DefinitelyTyped/DefinitelyTyped <DefinitelyTyped@noreply.github.com>
Cc: Venthe <jacek.b.lipiec@gmail.com>; Author <author@noreply.github.com>
Subject: Re: [DefinitelyTyped/DefinitelyTyped] Updated AngularJs orderBy definition to version 1.5.8 (#11790)

 

Filters, in particular this one, are used almost exclusively in templates, which unfortunately aren't type checked at all. Do you have a real-life use case for these type definitions?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11790#issuecomment-252042501> , or mute the thread <https://github.com/notifications/unsubscribe-auth/ABm9WqxX2kf51OOJ0s9WfjVeiDr2ABxdks5qxTi5gaJpZM4KQEiP> .  <https://github.com/notifications/beacon/ABm9WpYQ18z_ALCr-qOZoqA1RUjB8JGyks5qxTi5gaJpZM4KQEiP.gif>

2016-10-06 20:09 UTC, aciccarello requested changes
Looks like it's coming along. Also should add test with simple compare function.

2016-10-06 20:09 UTC, aciccarello commented on angularjs/angular.d.ts
> +    }
Shouldn't these have the types `any`, `string`, and `number` respectively?

2016-10-06 20:09 UTC, aciccarello commented on angularjs/angular.d.ts
> +        (value1: IFilterOrderByObject, value2: IFilterOrderByObject): number;
It might be helpful to document the expected return numbers in a jsdoc comment.

2016-10-06 20:18 UTC, thorn0 commented on angularjs/angular.d.ts
> +    }
`value` is a return value of one of the predicates (including the 'dummy predicate', see the docs). Different predicates can return values of different types. Also predicates can be expressions (strings), not functions. So I don't think it's possible to think of something better than `any` here.

2016-10-06 21:10 UTC, thorn0 commented on angularjs/angular.d.ts
> +    }
We could probably type the `predicates` parameter as `(string | ((value: T) => U))[] | (value: T) => U | string` if type arguments could be inferred to be union types in the cases like `[x => 1, x => 'a']`. But unfortunately the inference [doesn't work like this](http://stackoverflow.com/questions/39905523/why-isnt-the-type-argument-inferred-as-a-union-type).

2016-10-07 08:51 UTC, Venthe commented
I do not know how to write tests like used here, so if anyone would be willing to help me, I'm open.

2016-11-16 23:33 UTC, minestarks commented
@Venthe simple -- add some sample code that uses your type definition changes to angular-tests.ts file in this directory. If the code compiles the tests pass.

2016-11-30 01:17 UTC, paulvanbrenk commented
This PR seems abandoned, please re-opeon when you made the requested changes.

2016-11-30 01:17 UTC, closed without merging