Add typings for sass-graph
DefinitelyTyped/DefinitelyTyped pull request #11801
Opened 2016-10-06 19:07 UTC by marvinhagemeister

case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

2016-10-06 19:47 UTC, mhegazy requested changes

2016-10-06 19:47 UTC, mhegazy commented on sass-graph/sass-graph.d.ts
> +// Type definitions for sass-graph
please add a version. see http://definitelytyped.org/guides/contributing.html#header

2016-10-06 20:33 UTC, marvinhagemeister commented on sass-graph/sass-graph.d.ts
> +// Type definitions for sass-graph
Oh sorry, I should've seen that earlier. The version is now added. Thanks for the quick review!

2016-10-06 21:18 UTC, merged

2016-10-07 06:12 UTC, marvinhagemeister commented
Thanks for merging!

2016-10-12 15:48 UTC, marvinhagemeister commented
@mhegazy Just curious, how often is this repos synched with the packages on npm?