Fix for hs-base64 typings
DefinitelyTyped/DefinitelyTyped pull request #11842
Opened 2016-10-07 22:42 UTC by ssougnez

Improvement to existing type definition.
- Fix applied in the context of the following issue: https://github.com/dankogai/js-base64/issues/38

The old version was causing an issue with webpack (because of duplicate
identifier). This update fix this issue.

2016-10-07 23:51 UTC, mhegazy requested changes
This change will not work as intended in the master branch. do you mind submitting this PR to https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0 branch instead.

2016-10-07 23:51 UTC, mhegazy commented on js-base64/js-base64.d.ts
> +// Type definitions for js-base64 v2.1.9
duplicate header. please remove.

2016-10-08 03:09 UTC, DenisCarriere requested changes

2016-10-08 03:09 UTC, DenisCarriere commented on js-base64/js-base64-test.ts
> +import { Base64 } from './js-base64'
This is not how to import the module.

Keep the original test case 
```javascript
import { Base64 } from 'js-base64'
```

2016-10-08 03:09 UTC, DenisCarriere commented on js-base64/js-base64.d.ts
> +export declare var Base64: Base64Static;
You need to export a module, not a `var`

2016-10-08 03:12 UTC, DenisCarriere commented
@ssougnez this PR does not improve anything, it breaks it.

2016-10-08 10:11 UTC, ssougnez commented
Hi,

I think I should have modified the files for @types (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0) and not the ones of this branch because for TypeScript 2.0, the definition are already broken... You can delete the changes I made here and I'll try to fix the definitions in types (and I'll try to use a module as well :p)

2016-10-08 13:57 UTC, DenisCarriere commented
Well the definition is not broken, it's simply not updated to the typescript 2.0 branch. The newest  commit should of fixed your issue with Angular.

2016-10-08 17:53 UTC, closed without merging