Updating typings for latest changes to fuzzaldrin-plus
DefinitelyTyped/DefinitelyTyped pull request #11865
Opened 2016-10-09 09:06 UTC by mdahamiwal

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url https://github.com/jeancroy/fuzzaldrin-plus/tree/master/src
  

- [ ] it has been reviewed by a DefinitelyTyped member.

2016-10-10 16:25 UTC, mdahamiwal commented
@vvakame , can you add someone to review it, Thanks :)

2016-10-12 10:29 UTC, mdahamiwal commented
@andy-ms , can you review this change? Thanks

2016-10-16 05:28 UTC, jkillian requested changes
I also recommend not merging this until fuzzaldrin-plus publishes a new release. When it is released, you'll have to change a version number as part of this PR to match the newly released version.

2016-10-16 05:28 UTC, JKillian commented on fuzzaldrin-plus/index.d.ts
> +export interface QueryOptions {
I understand that the `I` prefix might not be needed, but I'd recommend not changing this, simply for the sake of backward compatibility. No reason to make users using these typings have to change their code.

2016-10-17 16:59 UTC, mdahamiwal commented on fuzzaldrin-plus/index.d.ts
> +export interface QueryOptions {
@JKillian, I understand your point but my understanding is that _types-2.0_ branch is meant for future typings (that they would be merged to master) and only the ones in _master_ is available to TSD. Is there a distinction here on when should we put something in _master_ vs other branches in this repository? Are Devs taking dependency on typings available on non-master branches?

2016-11-16 23:51 UTC, minestarks commented on fuzzaldrin-plus/index.d.ts
> +export interface QueryOptions {
@mdahamiwal that's not quite accurate. types-2.0 types are published to @types and are meant to be used by the TypeScript 2.0 compiler. So unfortunately yes, you do need to worry about backwards compatibility. See the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md) for clarification.

2016-11-17 18:17 UTC, minestarks commented
@JKillian @mdahamiwal This PR is rather stale and sounds like there is some unresolved discussion. Should it be merged? If no further comments I plan to close it out in a couple of days.

2016-11-19 01:03 UTC, JKillian commented
Well, it shouldn't be merged yet, because this reflects new changes that aren't in a released version of `fuzzaldrin-plus` yet. Once that library releases a new version, then it'd be time to consider this in more detail

2016-11-29 15:20 UTC, mdahamiwal commented
@minestarks, we just released a new version of the lib that matches the typing changes in this PR. So we should be Ok to merge this. Is there a way to keep older version typings as well ? I see some details in readme to name older version like <lib>-<version>.d.ts, will that be taken care by the typing publisher? How do we do it for other libraries that are widely used like Jquery for instance?

2016-11-29 15:28 UTC, andy-ms commented
Why not directly [bundle](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)  types with your package? That way you don't have to worry about keeping DefinitelyTyped in sync, and users don't have to install two different packages.
As for publishing multiple versions, this isn't yet a feature that we support.

2016-11-30 06:36 UTC, mdahamiwal commented
Thanks, that would make more sense, will move d.ts to actual repository.I am fine with abandoning this PR.

2016-12-27 21:04 UTC, andy-ms commented
Best of luck. Be sure to notify us when you've done so, so we can deprecate `@types/fuzzaldrin-plus`.

2016-12-27 21:04 UTC, closed without merging