Update definition for leaflet 1.0
DefinitelyTyped/DefinitelyTyped pull request #12016
Opened 2016-10-16 02:10 UTC by haoliangyu

Improvement to existing type definition.

* Add definition for `L.DomEvent.on()` ([source](https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.js#L23))

* Add definition for `L.DomEvent.off()` ([source](https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.js#L49))

* Add definition for `L.DomEvent.disableScrollPropagation()` ([source](https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.js#L172))

* Add definition for `L.DomEvent.disableClickPropagation()` ([source](https://github.com/Leaflet/Leaflet/blob/master/src/dom/DomEvent.js#L179))

All tests passed!

2016-10-18 15:17 UTC, alejo90 requested changes
Thanks for the help @haoliangyu. We just need a couple of changes to accurately represent the API.

2016-10-18 15:17 UTC, alejo90 commented on leaflet/leaflet.d.ts
> +        export function on(el: HTMLElement, types: string | Object, fn: Function, context?: any): typeof DomEvent;
This should be split into two functions:

```
export function on(el: HTMLElement, types: string, context?: Object): typeof DomEvent;
export function on(el: HTMLElement, eventMap: {[eventName: string]: Function}, context?: Object): typeof DomEvent;
```

http://leafletjs.com/reference-1.0.0.html#domevent

2016-10-18 15:17 UTC, alejo90 commented on leaflet/leaflet.d.ts
> +        export function off(el: HTMLElement, types: string | Object, fn: Function, context?: any): typeof DomEvent;
Needs to be split; same as `on`.

2016-10-19 00:53 UTC, haoliangyu commented
@alejo90 I have made the adjustment according to your suggestions.

2016-10-19 17:38 UTC, alejo90 commented
👍

2016-10-25 10:25 UTC, merged