Webgme types
DefinitelyTyped/DefinitelyTyped pull request #12166
Opened 2016-10-21 15:51 UTC by phreed

case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
     It appears that the `types-2.0` branch follows a slightly different naming convention i.e. index.d.ts
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.
     For webgme there are several tests files which are referenced by webgme-tests.ts

This PR includes a previously submitted, verified but un-merged PR for N3.

2016-10-25 13:52 UTC, vvakame commented
*n3/index.d.ts*

Checklist

* [X] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/n3 - https://github.com/RubenVerborgh/N3.js#readme
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (n3-tests.ts or n3-tests.tsx)
* [ ] pass the Travis CI test?

------

*webgme/index.d.ts*

Checklist

* [ ] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/webgme
  * http://bower.io/search/?q=webgme
  * others?
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (webgme-tests.ts or webgme-tests.tsx)
* [ ] pass the Travis CI test?

2016-10-25 13:54 UTC, vvakame commented
@zhengbli @andy-ms could you review this PR?

2016-10-25 14:35 UTC, ghost requested changes

2016-10-25 14:35 UTC, andy-ms commented on n3/n3-tests.ts
> +/**
Don't need this comment

2016-10-25 14:35 UTC, andy-ms commented on n3/n3-tests.ts
> +                foaf: "http://xmlns.com/foaf/0.1",
The type you're testing here is `{ [key: string]: string; }`, so no need to be so detailed.

2016-10-25 14:35 UTC, andy-ms commented on n3/n3-tests.ts
> +function test_doc_rdf_to_triples_2() {
The type you're testing here is `{ format?: string, prefixes?: string[] }`. So you don't need to test it on 5 different strings, but you should pass prefixes.

2016-10-25 14:35 UTC, andy-ms commented on n3/tsconfig.json
> +        "strictNullChecks": false,
Set this to `true`.

2016-10-25 14:35 UTC, andy-ms commented on webgme/tsconfig.json
> +        "n3-tests.ts"
webgme-tests

2016-10-25 14:35 UTC, andy-ms commented on webgme/metadata.json
> +{
What's this for?

2016-10-25 14:35 UTC, andy-ms commented on webgme/webgme-blob.d.ts
> +
It would be better to just have 3 files: `index.d.ts`, `webgme-tests.ts`, and `tsconfig.json`.

2016-10-25 14:35 UTC, andy-ms commented on webgme/metadata.json
> +{
The tests won't actually be run, so there's no need for test data.

2016-10-25 14:35 UTC, andy-ms commented on n3/index.d.ts
> +// Type definitions for N3 v0.8.1
No need to include a patch version.

2016-10-25 14:35 UTC, andy-ms commented on n3/index.d.ts
> +/// <reference path="../node/index.d.ts" />
Use `reference types`.

2016-10-25 14:35 UTC, andy-ms commented on n3/index.d.ts
> +declare module "n3" {
Since this definition consists only of `declare module`, just remove this wrapper. You'll also need to add `declare` in front of `namespace N3`.

2016-10-25 14:35 UTC, andy-ms commented on n3/index.d.ts
> +/**
No need for this comment.

2016-10-25 14:35 UTC, andy-ms commented on n3/n3-tests.ts
> +/**
No need for this comment.

2016-10-25 14:35 UTC, andy-ms commented on n3/n3-tests.ts
> +            prefixes: {
The type you're testing is `{ [key: string]: string] }`. No need to be so detailed.

2016-10-25 14:35 UTC, andy-ms commented on n3/n3-tests.ts
> +    var parser1 = N3.Parser({ format: 'N-Triples' });
The type you're testing is `{ format?: string, prefixes?: string[] }`. No need to test on 5 different format strings. But you should include a test with prefixes.

2016-10-25 14:35 UTC, andy-ms commented on n3/tsconfig.json
> +        "strictNullChecks": false,
Try with this set to `true`.

2016-10-25 14:35 UTC, andy-ms commented on webgme/tsconfig.json
> +        "n3-tests.ts"
webgme-tests

2016-10-25 14:35 UTC, andy-ms commented on webgme/index.d.ts
> +/**
No need for this comment

2016-10-25 14:35 UTC, andy-ms commented on webgme/index.d.ts
> +// Type definitions for webgme v2.6.0
Try doing it with only 3 files: `index.d.ts`, `tsconfig.json`, `webgme-tests.d.ts`

2016-10-25 14:35 UTC, andy-ms commented on webgme/index.d.ts
> +// Generated by typings
Is this generated code?

2016-10-25 14:35 UTC, andy-ms commented on webgme/index.d.ts
> +// Source: https://raw.githubusercontent.com/phreed/typed-npm-webgme/master/webgme.d.ts
Broken link, and these comments are not needed.

2016-10-25 14:35 UTC, andy-ms commented on webgme/webgme-blob.d.ts
> +    export interface Util { }
An empty interface is equivalent to the `{}` type. Implementing it adds no information.

2016-10-25 14:35 UTC, andy-ms commented on webgme/webgme-client-tests.ts
> +
This file appears incomplete.

2016-10-25 14:35 UTC, andy-ms commented on webgme/webgme-core.d.ts
> +        addMetadataHash: {
This is an unusual way of writing a method with several overloads. Why not just `addMetadataHash(...): void; addMetadataHash(...): Promise<MetadataHash>`?

2016-10-26 17:00 UTC, phreed commented on n3/n3-tests.ts
> +/**
Do I need `/// <reference types="node" />`?
I make use of `fs` and `stream` from nodejs.

2016-10-26 18:12 UTC, phreed commented on n3/tsconfig.json
> +        "strictNullChecks": false,
done. 
And fixed a couple of errors.

2016-10-26 18:12 UTC, phreed commented on webgme/metadata.json
> +{
The import in `webgme-plugin-blob-tests.ts` requires the file be present.
    import MetaDataStr = require("text!metadata.json");

2016-10-26 18:15 UTC, andy-ms commented on webgme/metadata.json
> +{
I'm wary about including any wildcard import declarations in DefinitelyTyped at all. If `webgme` itself doesn't define a loader for `text!*` imports, that shouldn't be part of the typings. The tests could just use `const MetaDataStr = "";`.

2016-10-26 18:18 UTC, phreed commented on n3/n3-tests.ts
> +                foaf: "http://xmlns.com/foaf/0.1",
For this test I am copying the code from the project `[README.md](https://github.com/RubenVerborgh/N3.js/blob/master/README.md)` with as few changes as possible.
I plan to create a separate set of tests that are more idiomatic typescript.
Is there some reason to make them less "real"?

2016-10-26 18:27 UTC, phreed commented on webgme/metadata.json
> +{
ok, I will make that change.

2016-10-26 18:31 UTC, andy-ms commented on n3/n3-tests.ts
> +                foaf: "http://xmlns.com/foaf/0.1",
I guess it's OK if it's just copied. Just didn't want you doing unnecessary work.

2016-10-26 19:14 UTC, andy-ms commented on n3/n3-tests.ts
> +/**
Be sure to remove these comments when you're done.

2016-10-26 19:14 UTC, andy-ms commented on webgme/webgme-core.d.ts
> +// Generated by typings
If this is not generated code, remove this comment.

2016-10-26 19:14 UTC, andy-ms commented on webgme/webgme-v1.d.ts
> +declare module "webgme/v1" {
"webgme/v1" doesn't seem to be an actual module. If these are deprecated you could just not include them.

2016-10-26 21:01 UTC, phreed commented on webgme/webgme-core.d.ts
> +// Generated by typings
It is not generated (but it was), comment removed.

2016-10-26 21:03 UTC, andy-ms commented on webgme/tsconfig.json
> +        "strictNullChecks": false,
Set this to `true`

2016-11-06 15:39 UTC, merged