Fusioncharts typings
DefinitelyTyped/DefinitelyTyped pull request #12177
Opened 2016-10-22 12:32 UTC by shivarajkv

case 1. Add a new type definition.
- [ ] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [ ] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [ ] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

case 2. Improvement to existing type definition.
- documentation or source code reference which provides context for the suggested changes.  url http://api.jquery.com/html .
  - it has been reviewed by a DefinitelyTyped member.

2016-10-25 11:29 UTC, shivarajkv commented
@zhengbli Have I missed something? Is **Revision needed** mean that something wrong with the code? Do I have to update something in the code?

2016-10-25 15:31 UTC, vvakame commented
:eyes:

2016-10-25 18:23 UTC, zhengbli commented
I have left a comment regarding using `{}` instead of `Object` type. By `Revision needed` I meant for you to address the comment in your code. Thanks.

2016-10-25 18:27 UTC, zhengbli requested changes

2016-10-25 18:29 UTC, shivarajkv commented on fusioncharts/fusioncharts.d.ts
> +        dataSource?: string | Object;
May I know why we need to use `{}` instead of Object. Thanks in advance.

2016-10-25 18:34 UTC, zhengbli commented on fusioncharts/fusioncharts.d.ts
> +        dataSource?: string | Object;
Because with `{}` you won't inherit the properties from global `Object` type that you don't want and may have side effects.

2016-10-25 18:39 UTC, zhengbli approved these changes

2016-10-26 04:52 UTC, shivarajkv commented
@vvakame @zhengbli  can this be merged now?

2016-10-26 05:00 UTC, merged