react-css-modules: augment react's HTMLAttributes interface
DefinitelyTyped/DefinitelyTyped pull request #12184
Opened 2016-10-23 14:05 UTC by skirsdeda

case 2. Improvement to existing type definition.
  - makes `styleName` property recognized on all React elements.
  - not yet reviewed.

Type checking works as expected but TS complains about line 33: Exports and export assignments are not permitted in module augmentations. This happens after adding "import from 'react'". Couldn't find the right way to fix this unfortunately. Maybe someone can help with this.

2016-10-23 18:13 UTC, KostyaEsmukov requested changes
👍, except that the build is failing

2016-10-23 19:35 UTC, skirsdeda commented
@KostyaEsmukov any ideas how to circumvent this export error (TS2666). I tried many things but unsuccessfully.

2016-10-23 19:49 UTC, skirsdeda commented
As far as I understand it, TS thinks that 'react-css-module' is being augmented although it is simply declared while 'react' is the one actually being augmented. As I mentioned, this happens after adding "import from 'react'" which is required for augmentation to work.

2016-10-24 13:08 UTC, KostyaEsmukov commented
@skirsdeda Yes, I think that CssModule declarations should be moved to the top level, because module augmentations don't allow to introduce new types. I might try this out tomorrow.

2016-10-25 14:36 UTC, vvakame commented on react-css-modules/index.d.ts
>  declare module 'react-css-modules' {
You should remove this block.
https://github.com/Microsoft/types-publisher#fields-in-datadefinitionsjson
see `ModuleAugmentation`.

2016-10-25 14:58 UTC, skirsdeda commented on react-css-modules/index.d.ts
>  declare module 'react-css-modules' {
What do you mean by "this block"?

2016-10-25 15:01 UTC, KostyaEsmukov commented on react-css-modules/index.d.ts
>  declare module 'react-css-modules' {
The `declare module 'react-css-modules'` one. Just move declarations inside to the upper level. It should work.

2016-10-25 15:07 UTC, KostyaEsmukov commented
BTW, @skirsdeda, could you please switch on the `strictNullChecks` option in the `tsconfig.json` at once?

2016-10-25 15:18 UTC, skirsdeda commented
after moving to top-level I had to add 'declare' to ```module CSSModules``` and ```let CSSModules: CSSModules;```. Also ```import from 'react'``` doesn't seem to be necessary any more.

2016-10-26 16:33 UTC, KostyaEsmukov approved these changes
👍, LGTM

BTW, some other examples of react module augmentation (just for the reference):
[react-addons-linked-state-mixin](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a385e8b4b76bb37fb2dbe6cd0e44dc32935db5fc/react-addons-linked-state-mixin/index.d.ts)
[react-addons-transition-group](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a385e8b4b76bb37fb2dbe6cd0e44dc32935db5fc/react-addons-transition-group/index.d.ts)
[react-addons-update](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a385e8b4b76bb37fb2dbe6cd0e44dc32935db5fc/react-addons-update/index.d.ts)

2016-11-01 13:10 UTC, skirsdeda commented
@vvakame Can this be merged now?

2016-11-02 13:27 UTC, vvakame commented
@skirsdeda Could you fix Travis CI failed?

2016-11-02 13:28 UTC, KostyaEsmukov commented
@vvakame It's not failing anymore.
https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/170486286

2016-11-02 15:16 UTC, merged

2016-11-02 15:16 UTC, vvakame commented
wow, sorry!

2016-11-02 15:17 UTC, KostyaEsmukov commented
👍 Thanks

2016-11-09 21:48 UTC, emzero commented
Can someone point to an example of how to actually import and use the CSSModules function?

If I do
`import * as CSSModules from "react-css-modules"`

`CSSModules` ends up being an object with a `default` property that is actually the function decorator.

How to properly import it without getting that default prop? I see there's no default export in the definition file.
Don't we just need a function? Why can't be a default export?

2016-12-15 08:13 UTC, mcrawshaw commented
I agree @emzero, it should be the default export.  The test file for this typings conflicts with the  documentation from the actual library.  From the doco:
```import CSSModules from 'react-css-modules'```

2016-12-15 09:24 UTC, KostyaEsmukov commented
The transpiled `index.js` shipped in the npm `react-css-modules` package contains the line:
```
module.exports = exports['default'];
```
so the object exported is actually the function decorator, not an object with a `default` property.

How can we make it a default export in this case?
If anyone have an idea how to workaround this -- please make a PR.

2016-12-15 15:31 UTC, emzero commented
We just need to change the export to a default export. See [this](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12844#issuecomment-267263737)