Fix older compatible functions on the aws-lambda context on the Types 2.0 branch
DefinitelyTyped/DefinitelyTyped pull request #12188
Opened 2016-10-23 18:12 UTC by StefH

Improvement to existing type definition on the **Types 2.0 branch** : Fix older compatible functions on the aws-lambda context.

For details see : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11924

2016-10-25 14:20 UTC, vvakame commented
@zhengbli What's mean `Revision needed` in this case?

2016-10-25 18:25 UTC, zhengbli requested changes

2016-10-25 18:26 UTC, zhengbli commented
I didn't realize the new "code review" feature of github needs an extra "submit" steps ....

2016-10-26 05:47 UTC, StefH commented on aws-lambda/index.d.ts
> +declare namespace AWSLambda {
Code is changed.

2016-10-26 05:47 UTC, StefH commented
Review comments are processed, please check.

2016-10-28 13:56 UTC, vvakame commented
conflict occured. could you resolve it?

2016-10-28 14:14 UTC, StefH commented
@vvakame very strange that there is a conflict because I'm the only editor for those files.
Or did you or @zhengbli already update my files after code-review?

2016-11-01 12:12 UTC, vvakame commented
@zhengbli gentle ping

2016-11-01 23:08 UTC, zhengbli approved these changes

2016-11-01 23:09 UTC, merged

2016-11-01 23:09 UTC, zhengbli commented
Thanks @StefH !