Add Dropbox zxcvbn typings
DefinitelyTyped/DefinitelyTyped pull request #12227
Opened 2016-10-25 11:18 UTC by DanielMcAssey

case 1. Add a new type definition.
- [x] checked compilation succeeds with `--target es6` and `--noImplicitAny` options.
- [x] has correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)
- [x] has a [test file](http://definitelytyped.org/guides/contributing.html#tests) with the suffix of  `-tests.ts` or `-tests.tsx`.

2016-10-25 15:29 UTC, vvakame commented
*zxcvbn/index.d.ts*

Checklist

* [X] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?
  * https://www.npmjs.com/package/zxcvbn - https://github.com/dropbox/zxcvbn#readme
* [X] has a [test file](http://definitelytyped.org/guides/contributing.html#tests)? (zxcvbn-tests.ts or zxcvbn-tests.tsx)
* [ ] pass the Travis CI test?

2016-10-25 15:30 UTC, vvakame commented
Can anyone review this PR?

2016-10-25 18:32 UTC, mhegazy requested changes

2016-10-25 18:32 UTC, mhegazy commented on zxcvbn/index.d.ts
> +declare function zxcvbn(password: string, userInputs?: Array<string>): zxcvbnResult;
From the documentation this file is a module, see https://github.com/dropbox/zxcvbn#node--npm--meteorjs. i.e. `import zxcvbn = require("zxcvbn");` should work.

to make this happen you need to add

```ts
export = zxcvbn;   // make it a module
export as namespace zxcvbn; // make sure there is a global function called zxcvbn as well
```

2016-10-25 18:37 UTC, mhegazy commented on zxcvbn/index.d.ts
> +declare function zxcvbn(password: string, userInputs?: Array<string>): zxcvbnResult;
also i would another test file for the `require` case.

```ts
// zxcvbn-module-tests.ts

import zxcvbn = require("zxcvbn");
let resultOne = zxcvbn('123456');
let resultWithInput = zxcvbn('123456', ['abc']);
```

2016-11-17 19:38 UTC, minestarks commented
@DanielMcAssey Thanks for your contribution. Do you plan to make the requested changes? As this PR is rather old I plan to close it out in a couple of days if no further changes.

2016-11-30 23:00 UTC, paulvanbrenk commented
Closing this pr as it seems abandoned. Please re-open after you created the requested changes.

2016-11-30 23:00 UTC, closed without merging