Plugins can accept object as options
DefinitelyTyped/DefinitelyTyped pull request #12380
Opened 2016-10-31 13:51 UTC by lukefx

Please fill in this template.

- [X] Prefer to make your PR against the `types-2.0` branch.
- [X] The package does not provide its own types, and you can not add them.
- [X] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If adding a new definition:
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Run `tsc` without errors.
- [X] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header.

If changing an existing definition:
- [X] Provide a URL to  documentation or source code which provides context for the suggested changes: [https://github.com/selectize/selectize.js/blob/master/docs/plugins.md#list-with-options](https://github.com/selectize/selectize.js/blob/master/docs/plugins.md#list-with-options)
- [ ] Increase the version number in the header if appropriate.

2016-10-31 17:51 UTC, adidahiya requested changes

2016-10-31 17:51 UTC, adidahiya commented on selectize/index.d.ts
> +        plugins?: string[] | Object;
please be more specific and define this interface. `Object` is too broad of a type.

2016-10-31 23:12 UTC, lukefx commented on selectize/index.d.ts
> +        plugins?: string[] | Object;
It's almost impossibile, every plugins can have different key for properties...

````
$('select').selectize({
    plugins: {
        'plugin_a': { /* ... */ },
        'plugin_b': { /* ... */ }
    }
});```

2016-11-01 13:55 UTC, vvakame commented on selectize/index.d.ts
> +        plugins?: string[] | Object;
use `any` instead of `Object` at least.

2016-11-30 23:51 UTC, paulvanbrenk commented
This PR seems abandoned, please re-open when you made the requested changes.

2016-11-30 23:51 UTC, closed without merging