Types 2.0
DefinitelyTyped/DefinitelyTyped pull request #12602
Opened 2016-11-10 13:45 UTC by aliib

Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] The package does not provide its own types, and you can not add them.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to  documentation or source code which provides context for the suggested changes: http://electron.atom.io/docs/api/net/
- [x] Increase the version number in the header if appropriate.

2016-11-10 22:04 UTC, yuit commented
@aliib  Thank you for your contribution. The build break is fix in this PR #12594 . I will let you know once that merge and you should update your PR

2016-11-14 18:43 UTC, andy-ms commented
@aliib Please merge the latest `types-2.0` to fix tests.

2016-11-15 03:24 UTC, rhysd requested changes

2016-11-15 03:24 UTC, rhysd commented on electron/index.d.ts
> +        net: Electron.Net;
nit: Indentation is wrong.

2016-11-15 03:24 UTC, rhysd commented on electron/index.d.ts
> +		request(options : string | RequestOptions, callback?: (response: IncomingMessage) => void): ClientRequest
nit: semicolon is missing

2016-11-15 03:24 UTC, rhysd commented on electron/index.d.ts
> +	interface Net extends NodeJS.EventEmitter {
Is it correct that `Net` instance extends `EventEmitter`? I couldn't find that in document.

2016-11-15 03:25 UTC, rhysd commented
@aliib I'm sorry for catching this late. Please check my comments.

2016-11-15 08:50 UTC, aliib commented
ok, thanls @rhysd

2016-11-15 15:55 UTC, rhysd commented on electron/index.d.ts
> +	interface Net extends NodeJS.EventEmitter {
I got it. I'm not against referring to implementation. Thanks.

2016-11-15 15:56 UTC, rhysd approved these changes

2016-11-15 15:56 UTC, rhysd commented
Looks good :+1:

2016-11-15 17:18 UTC, merged