Add type definitions for smtp-server.
DefinitelyTyped/DefinitelyTyped pull request #12637
Opened 2016-11-12 17:03 UTC by markisme

- [ x ] The package does not provide its own types.
- [ x ] match the npm package name.
- [ x ] Run `tsc` without errors.
- [ x ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

2016-11-14 19:10 UTC, ghost requested changes
Needs a `tsconfig.json`. See the [README](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package).

2016-11-14 19:10 UTC, andy-ms commented on smtp-server/package.json
> +{
Shouldn't need this file.

2016-11-14 19:10 UTC, andy-ms commented on smtp-server/smtp-server.d.ts
> +export interface SMTPCommands {
An empty interface is equivalent to `{}`. Also, this doesn't seem to be used.

2016-11-14 19:10 UTC, andy-ms commented on smtp-server/smtp-server.d.ts
> +    method: string;//'PLAIN', 'LOGIN' or 'XOAUTH2'
You can use a string union: `"PLAIN" | "LOGIN" | "XOAUTH2"`

2016-11-14 19:10 UTC, andy-ms commented on smtp-server/smtp-server.d.ts
> +    name?: string;//optional hostname of the server.
Why not use a JSDoc comment for this? `/** Optional hostname of the server. */` on a line above it. JSDoc comments are used for an editor to provide info on hover, while this comment will be ignored.

2016-11-14 19:10 UTC, andy-ms commented on smtp-server/smtp-server.d.ts
> +// Definitions: https://github.com/markisme/smtp-server.git
This should be `// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped`.

2016-11-14 19:10 UTC, andy-ms commented on smtp-server/smtp-server.d.ts
> +        'SIZE'?: number,
Quotes should be unnecessary here.

2016-11-14 19:11 UTC, andy-ms commented
@markisme Please rebase onto the latest `types-2.0` to fix tests.

2016-11-15 15:56 UTC, markisme commented
@andy-ms thanks very much, i will fix that as soon.😁

2016-11-20 04:56 UTC, markisme commented
Maybe fixed.
Checklist

- [x] is correct [naming convention](http://definitelytyped.org/guides/contributing.html#naming-the-file)?

  - https://www.npmjs.com/package/smtp-server
  - http://bower.io/search/?q=smtp-server
  - others?

 

- [x] has a test file? (smtp-server-tests.ts or smtp-server-tests.tsx)
- [x] pass the Travis CI test?

2016-11-21 14:52 UTC, andy-ms commented
Could you re-target this for `types-2.0` instead of `master`?

2016-11-22 02:39 UTC, markisme commented
@andy-ms Did I need to reopen a PR on `types-2.0`?

2016-11-22 21:58 UTC, sandersn commented
Yes, unless

2016-11-22 21:58 UTC, closed without merging