Add animate.IAnimateService
DefinitelyTyped/DefinitelyTyped pull request #12738
Opened 2016-11-17 03:33 UTC by ersimont

Please fill in this template.

- [X] Prefer to make your PR against the `types-2.0` branch.
- [X] Test the change in your own code.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [X] Provide a URL to  documentation or source code which provides context for the suggested changes: https://docs.angularjs.org/api/ngMock/service/$animate
- [ ] Increase the version number in the header if appropriate.

2016-11-23 19:09 UTC, sandersn requested changes

2016-11-23 19:09 UTC, sandersn commented on angular-mocks/index.d.ts
> +      closeAndFlush();
What is `closeAndFlush`'s return type? I guess it should be void, right? Right now it's implicitly any, which causes CI to fail.

2016-11-23 19:16 UTC, sandersn approved these changes

2016-11-23 19:16 UTC, merged

2016-11-25 00:49 UTC, ersimont commented on angular-mocks/index.d.ts
> +      closeAndFlush();
Absolutely right. Sorry and thank you.