Fix for cassandra-driver Row #12662
DefinitelyTyped/DefinitelyTyped pull request #12750
Opened 2016-11-17 15:07 UTC by mrgleba

Please fill in this template.

- [ ] Prefer to make your PR against the `types-2.0` branch.
- [X ] Test the change in your own code.
- [X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [X ] Provide a URL to  documentation or source code which provides context for the suggested changes: https://github.com/datastax/nodejs-driver/blob/master/lib/types/row.js
- [ ] Increase the version number in the header if appropriate.

2016-11-23 19:58 UTC, sandersn requested changes

2016-11-23 19:58 UTC, sandersn commented on cassandra-driver/cassandra-driver.d.ts
> +      get(columnName: string|number):any;
Why switch to `any` here?  Can you add a test case that would not work with a string-indexed object?

2016-11-24 07:22 UTC, mrgleba commented
The previous signature was simply invalid:
 - get returns (based on either a column position or a column name) the
value and not a dictionary of values
 - analogously values returns (as name suggests) an array of values and not
an array of dictionaries.

This PR is not a change in logic, it's a bug fix.

Cheers!

2016-11-23 20:58 GMT+01:00 Nathan Shively-Sanders <notifications@github.com>
:

> *@sandersn* requested changes on this pull request.
> ------------------------------
>
> In cassandra-driver/cassandra-driver.d.ts
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12750#pullrequestreview-9935398>
> :
>
> > @@ -375,8 +375,9 @@ declare module "cassandra-driver" {
>      }
>
>      interface Row {
> -      get(columnName: string|number): { [key:string]:any; };
> -      values(): Array<{ [key:string]:any; }>;
> +      get(columnName: string|number):any;
>
> Why switch to any here? Can you add a test case that would not work with
> a string-indexed object?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12750#pullrequestreview-9935398>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AF7wGfKTGPJgNRLjJ-9VveBI4pSIQDokks5rBJrbgaJpZM4K1al2>
> .
>

2016-11-24 15:41 UTC, sandersn approved these changes

2016-11-24 15:41 UTC, merged