Update react-select.d.ts
DefinitelyTyped/DefinitelyTyped pull request #12816
Opened 2016-11-20 17:17 UTC by mayerwin

Typescript supported way for nested classes as per http://stackoverflow.com/questions/13495107/any-way-to-declare-a-nest-class-structure-in-typescript. Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12302

- [x] Test the change in your own code.

- [ ] Increase the version number in the header if appropriate.
Should be reviewed first to ensure PR has no adverse side effect.

2016-11-20 18:39 UTC, giladgray requested changes

2016-11-20 18:39 UTC, giladgray commented on react-select/react-select.d.ts
> +declare namespace ReactSelectNameSpace {
:-1: _but why!_ this is a significant API break for all consumers (granted just a string rename but still) for which I see no benefit. 

do other packages include the word "NameSpace" in their namespace names? I doubt it.

2016-11-21 02:01 UTC, mayerwin commented
How is that an API break, since the namespace is not exported? If I understand typings correctly it should only matter within the definition file itself. Anyway I rechecked and this namespace name change was no longer needed with the final implementation (at some point it was the only way to make export of the nested ReactSelect.Creatable class work). Let me revert this change and it should be all right (unless there is an issue you noticed with the rest of the commit).

2016-11-24 00:27 UTC, sandersn commented
@giladgray is this ready to go in now?

2016-12-01 00:26 UTC, merged