Leaflet - Add missing L.ImageOverlay methods and missing L.Draggable class
DefinitelyTyped/DefinitelyTyped pull request #13050
Opened 2016-12-01 20:27 UTC by danzel

Please fill in this template.

- [x] Prefer to make your PR against the `types-2.0` branch.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Leaflet/Leaflet/blob/master/src/dom/Draggable.js
https://github.com/Leaflet/Leaflet/pull/5158
- [ ] Increase the version number in the header if appropriate.

2016-12-03 20:39 UTC, alejo90 requested changes
Thanks for your contribution. We just need a formatting fix and the replacement of `var` with `let` or `const`.

2016-12-03 20:39 UTC, alejo90 commented on leaflet/leaflet-tests.ts
> +var draggable = new L.Draggable(elementToDrag);
Please replace `var` with `const` or `let`.

2016-12-03 20:39 UTC, alejo90 commented on leaflet/index.d.ts
> +	    getElement(): HTMLImageElement;
Can you please fix the indentation for these two lines.

2016-12-04 04:10 UTC, danzel commented
Done.

2016-12-04 15:54 UTC, alejo90 commented
👍

2016-12-13 23:17 UTC, alejo90 commented
@andy-ms @vvakame

2016-12-13 23:20 UTC, merged