add process.cpuUsage() method
DefinitelyTyped/DefinitelyTyped pull request #13358
Opened 2016-12-15 13:04 UTC by a8775

As in NodeJS documentation:
[https://nodejs.org/dist/latest-v7.x/docs/api/process.html#process_process_cpuusage_previousvalue](https://nodejs.org/dist/latest-v7.x/docs/api/process.html#process_process_cpuusage_previousvalue)

2016-12-15 17:33 UTC, mhegazy requested changes

2016-12-15 17:33 UTC, mhegazy commented on node/index.d.ts
> +        cpuUsage(previousValue?: [number, number]): [number, number];
from the documentation, this function returns an object and not a tuple. it should be defined as 
```ts
cpuUsage(previousValue?: { user: number, system: number }): { user: number, system: number };
```

2016-12-16 09:44 UTC, a8775 commented
@mhegazy you are right, it's my fault. Thank you for your attention!

I'm just thinking now that it could be better to make it in similar way as it's with MemoryUsage:

```
interface CpuUsage {
    user: number;
    system: number;
}

cpuUsage(previousValue?: CpuUsage): CpuUsage;
```

If it's ok. I will change my PR.

2016-12-27 09:41 UTC, horiuchi approved these changes

2016-12-27 09:41 UTC, merged

2016-12-27 09:41 UTC, horiuchi commented
@a8775 Thanks!