[angular-ui-router] Added description of `redirectTo`
DefinitelyTyped/DefinitelyTyped pull request #13495
Opened 2016-12-21 17:40 UTC by matiishyn

Hey guys, plz review my PR
I'm using UI-Router 1.0.0-beta.3. And the `redirectTo` property is missing in the `IState` interface.
![image](https://cloud.githubusercontent.com/assets/3661065/21399652/bbcd7ba8-c7ac-11e6-8f0e-483b4dc35761.png)

This state hook is described in [migration guide](https://ui-router.github.io/guide/ng1/migrate-to-1_0#state-hook-redirectto) and here's a [documentation ](https://ui-router.github.io/docs/latest/interfaces/state.statedeclaration.html#redirectto)

Please fill in this template.
- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

2016-12-21 17:53 UTC, matiishyn commented
Looks like tests are failing. But they were failing even before my changes.
Can someone take a look please

2016-12-22 06:46 UTC, DanielRosenwasser requested changes

2016-12-22 06:46 UTC, DanielRosenwasser commented on angular-ui-router/index.d.ts
> +            redirectTo?: String | Function | IState;
Use `string | Function | IState` (notice the lowercase `string`).

2016-12-22 06:47 UTC, DanielRosenwasser requested changes

2016-12-22 06:47 UTC, DanielRosenwasser commented on angular-ui-router/index.d.ts
> +// Definitions by: Ivan Matiishyn <https://github.com/matiishyn>
Add yourself to the previous line, separated by a comma

2016-12-22 09:38 UTC, matiishyn commented
Thank you @DanielRosenwasser for your review!
I've fixed what you mentioned

2016-12-22 09:57 UTC, DanielRosenwasser approved these changes

2016-12-22 09:59 UTC, merged

2016-12-22 09:59 UTC, DanielRosenwasser commented
Thanks!

2016-12-22 10:05 UTC, matiishyn commented
thank you @DanielRosenwasser !
Do you know, when the NPM package will be updated?