add mongo-oplog typings
DefinitelyTyped/DefinitelyTyped pull request #13560
Opened 2016-12-27 06:20 UTC by FinalDes

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `npm run lint -- package-name` if a `tslint.json` is present.

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Run `tsc` without errors.
- [ ] Include the required [files](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package) and header. Base these on the README, *not* on an existing project.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.

2016-12-27 19:19 UTC, andy-ms commented
Please use `npm run new-package -- mongo-oplog` to generate a correct package structure. `tslint.json` should be simply `{ "extends": "../tslint.json" }`.

2016-12-28 16:03 UTC, ghost requested changes
Needs tests.
There are some things I didn't comment on because the linter will catch them, so be sure to run that.

2016-12-28 16:03 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +// TypeScript Version: 2.1
This should be the *last* line.

2016-12-28 16:03 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +    tail(): any; // return promise
Use `tail(): Promise<Foo>` where `Foo` is the type of the awaited value.

2016-12-28 16:03 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +    on(type: string, callback: (doc: any) => void): any; // return eventemitter3
Instead of `/// <reference types="eventemitter3" />`, use `import EventEmitter = require("eventemitter3")` and then `on(...): EventEmitter`.

2016-12-28 16:03 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +    export = MongoOplog;
If the module export value is a function, use [this](http://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html) pattern: `declare function MongoOplog`, then have `declare namespace MongoOplog { interface OplogTrigger { ... } }` and finally `export = MongoOplog` (with no `declare module` wrapper).

2016-12-28 16:03 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +export function MongoOplog(url: string, filter: any): OplogTrigger;
According to the documentation, the second parameter is [`options`](https://github.com/cayasso/mongo-oplog#mongooploguri-options).

2016-12-30 05:33 UTC, FinalDes commented on mongo-oplog/index.d.ts
> +    on(type: string, callback: (doc: any) => void): any; // return eventemitter3
throw new Error("Debug Failure. False expression: " + (message || "") + verboseDebugString);

2016-12-30 14:21 UTC, ghost reviewed
Remember to lint

2016-12-30 14:21 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +declare module "mongo-oplog" {
Remove this wrapper and just write `export = MongoOplog;` on the top-level.

2016-12-30 14:21 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +// Definitions by: [FinalDes] <[https://github.com/FinalDes]>
Remove `[]` from header

2016-12-30 14:22 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +    on(type: string, callback: (doc: any) => void): any; // return eventemitter3
?

2016-12-30 14:26 UTC, FinalDes commented on mongo-oplog/index.d.ts
> +    on(type: string, callback: (doc: any) => void): any; // return eventemitter3
when put the import statement, it will throw the error when compile it. @andy-ms

2016-12-30 14:39 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +    on(type: string, callback: (doc: any) => void): any; // return eventemitter3
Works for me in `typescript@next`, `typescript@2.0`, and `typescript@2.1`. What version are you using?

2017-01-02 06:29 UTC, FinalDes commented on mongo-oplog/index.d.ts
> +declare module "mongo-oplog" {
not working when try to import the packages @andy-ms

2017-01-02 08:57 UTC, FinalDes commented on mongo-oplog/index.d.ts
> +    on(type: string, callback: (doc: any) => void): any; // return eventemitter3
typescript@2.1.4

2017-01-02 12:57 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +    on(type: string, callback: (doc: any) => void): any; // return eventemitter3
Works for me with that version. Make sure you're running just `tsc` (in the `mongo-oplog` directory) and not `tsc mongo-oplog-tests.ts`. If you're still getting an error, what is it?

2017-01-02 12:58 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +declare module "mongo-oplog" {
Works for me. What error are you getting?

2017-01-02 12:58 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +// TypeScript Version: 2.1
Also, I'm able to compile this just fine with `typescript@2.0`.

2017-01-02 13:01 UTC, andy-ms commented on mongo-oplog/index.d.ts
> +// Type definitions for [cayasso/mongo-oplog]
Use `// Type definitions for mongo-oplog 2.0`. (Assuming these types are for the most recent version of the package).

2017-01-18 03:57 UTC, mhegazy commented
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-01-18 03:57 UTC, closed without merging