[pg] Add query config variants to all query methods
DefinitelyTyped/DefinitelyTyped pull request #13570
Opened 2016-12-27 17:03 UTC by calebmer

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `npm run lint -- package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/brianc/node-pg-pool/blob/ab70f579234cb51f7508cb18d09ff6d4e6944948/index.js#L130, https://github.com/brianc/node-postgres/blob/f6c40b9331c90d794d5fcbb1d4ae2f28eabd4d42/lib/client.js#L326, https://github.com/brianc/node-postgres/blob/f6c40b9331c90d794d5fcbb1d4ae2f28eabd4d42/lib/query.js#L19, https://github.com/brianc/node-postgres/blob/f6c40b9331c90d794d5fcbb1d4ae2f28eabd4d42/lib/utils.js#L124-L138
- [x] Increase the version number in the header if appropriate.

2016-12-27 17:23 UTC, pspeter3 requested changes

2016-12-27 17:23 UTC, pspeter3 commented on pg/index.d.ts
> +    query(config: QueryConfig): Promise<QueryResult>;
This does not seem correct based on the link for the pool

2017-01-18 04:21 UTC, mhegazy commented
@calebmer can you please respond to the review comment?

2017-02-04 00:34 UTC, bowdenk7 commented
This PR has unaddressed comments and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-02-04 00:34 UTC, closed without merging