Do not use `Node` and `NodeList` in rx-lite defintions
DefinitelyTyped/DefinitelyTyped pull request #13737
Opened 2017-01-04 21:07 UTC by mhegazy

- Do not use the DOM types `Node` and `NodeList` and instead define `DOMEventTarget`
- Also adds NodeEventTarget support

Please see https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/fromevent.js for implementation details. 

Fixes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/13733

2017-01-04 21:40 UTC, Igorbek requested changes

2017-01-04 21:40 UTC, Igorbek commented on rx-lite/index.d.ts
> +        fromEvent<T>(element: ArrayLike<DOMEventTarget> | DOMEventTarget | NodeEventTarget| NativeEventTarget, eventName: string, selector?: (arguments: any[]) => T): Observable<T>;
I know this was before, but it seems the `selector` should be of type `(...args: any[]) => T`, according to the implementation https://github.com/Reactive-Extensions/RxJS/blob/master/src/core/linq/observable/fromeventpattern.js#L14
Same with `fromEventPattern`

2017-01-04 22:59 UTC, mhegazy commented
@Igorbek any more comments?

2017-01-05 17:19 UTC, ghost approved these changes

2017-01-05 17:36 UTC, merged