@node, @mongodb modules, Readable stream interface
DefinitelyTyped/DefinitelyTyped pull request #13836
Opened 2017-01-07 23:49 UTC by hinell

Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:
If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: see issue here #13782 
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

## Description
`node/` 
The return types of next`Readable` interface's  methods were changed to `this` type according to their officially declared api: `pause()`,`resume()`,`pipe()`,`unpipe()`
`ConsoleConstructor` and its tests were added

`mongodb/`
'Readable'-dependent types were reconciled with changed `node/index.d.ts` api

2017-01-07 23:56 UTC, CaselIT commented
Hi, could you remove the remove the methods in mongodb, since they have been mistakenly been added there? We should use the one on the parent class.

Thanks

2017-01-08 00:00 UTC, hinell commented
>could you remove the remove the methods in mongodb
@CaselIT What the methods?

2017-01-08 00:02 UTC, CaselIT requested changes
The `setEncoding` can be removed from mongodb since it's a parent class method.
Marked the methods below

2017-01-08 00:02 UTC, CaselIT commented on mongodb/index.d.ts
> +    setEncoding(encoding: string): this;
This

2017-01-08 00:02 UTC, CaselIT commented on mongodb/index.d.ts
> +    setEncoding(encoding: string): this;
this

2017-01-08 00:02 UTC, CaselIT commented on mongodb/index.d.ts
> +    setEncoding(encoding: string): this;
This

2017-01-08 00:15 UTC, hinell commented
@CaselIT Have done.

2017-01-08 00:17 UTC, CaselIT commented
Thanks. That should avoid future problems of the same type.
👍 on the mongodb part

2017-01-08 00:21 UTC, hinell commented
@CaselIT Yep. At least on the `mongodb` side. But what about those thousandth others modules? :smirk:

2017-01-08 00:24 UTC, CaselIT commented
Well I guess someone will review it.

2017-01-08 01:41 UTC, andy-ms commented
Travis is slow because it tests everything depending on `node`, which is a lot! And it looks like it found something.

2017-01-12 15:07 UTC, hinell commented
Revision is needed guys.
@andy-ms
@RyanCavanaugh
@minestarks
@paulvanbrenk
@sandersn
@maghis
@zhengbli
@yuit
@zjiekai
@yortus
@xiemaisi
@rogierschouten
@rakatyal
@mhegazy
@iainmcgin
@horiuchi
@HerringtonDarkholme
@jefff
@Flarna
@icopp
@a8775

2017-01-14 18:02 UTC, hinell commented
bump

2017-01-14 18:05 UTC, rogierschouten commented
:+1: on the node part

2017-01-14 18:14 UTC, Flarna approved these changes
looks fine

2017-01-14 18:47 UTC, hinell commented
@rogierschouten 
@Flarna 
Thanks guys.

2017-01-18 01:37 UTC, mhegazy commented
@andy-ms any comments?

2017-01-18 16:11 UTC, ghost approved these changes

2017-01-18 17:17 UTC, TonyPythoneer commented
@hinell Could you resolve the conflict? thx.

2017-01-19 13:43 UTC, hinell commented
Well, seems like this #13968 PR has broken all stuff here. 
@andy-ms Your assistance needed.

2017-01-19 14:42 UTC, andy-ms commented
Should be fixed in `master` now.

2017-02-04 02:03 UTC, merged