[js-quantities] fix export
DefinitelyTyped/DefinitelyTyped pull request #13969
Opened 2017-01-12 17:45 UTC by nevir

js-quantities builds a UMD module that [does not include a `default` export](https://github.com/gentooboontoo/js-quantities#node).  This fixes the typings for folk that aren't using `allowSyntheticDefaultExports`

Please fill in this template.

- [ ] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-01-12 17:57 UTC, wrummler commented
Please update the tests file `js-quantities-tests.ts` to work with the proposed change (also so that the CI build passes). Otherwise LGTM.

2017-01-12 18:52 UTC, wrummler commented
I think you'll need to use `import = require()` as described [in the TS handbook](http://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require):

> When importing a module using `export =`, TypeScript-specific `import let = require("module")` must be used to import the module.

2017-01-14 22:54 UTC, hinell requested changes
Seems this definition breaks the [common mistakes rule](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).

2017-01-14 22:54 UTC, hinell commented on js-quantities/index.d.ts
> +export = Qty;
I think it's better here  to declare a module and then to update the tests according to a changed API.
```ts
declare module 'js-quantities' {
    export interface QtyInstance extends Qty.Qty {}
    export const Qty: Qty.Type;
    export default Qty;
}
```
And use it like this
```ts
import * as quantities from "js-quantities";
let Qty = quantities.Qty;
let qtyCopy: quantities.QtyInstance;

```

2017-02-04 02:12 UTC, bowdenk7 commented
Thanks for your contribution. This PR has failing CI tests and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-02-04 02:12 UTC, closed without merging