[mongoose] capped types fix
DefinitelyTyped/DefinitelyTyped pull request #13995
Opened 2017-01-13 16:04 UTC by maxsh8x

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://mongoosejs.com/docs/guide.html#capped

2017-01-13 18:08 UTC, TonyPythoneer commented on mongoose/v3/index.d.ts
> +    capped?: boolean|number|Object;
object is not good. Please refer this type of { size: 1024, max: 1000, autoIndexId: true }.

2017-01-13 18:20 UTC, TonyPythoneer requested changes
Please improve it.

2017-01-13 19:19 UTC, maxsh8x commented
@TonyPythoneer done

2017-01-14 07:16 UTC, TonyPythoneer commented on mongoose/v3/index.d.ts
> +    capped?: boolean|number|CappedOptions;
It should improve format.
```
capped?: boolean | number | CappedOptions;
```

2017-01-14 07:17 UTC, TonyPythoneer requested changes
Please improve format.

2017-01-14 12:08 UTC, maxsh8x commented
@TonyPythoneer format has been improved

2017-01-14 12:22 UTC, TonyPythoneer commented
Hello @horiuchi 
Would you review this?

2017-01-14 15:58 UTC, merged

2017-01-14 15:58 UTC, horiuchi commented
@maxsh8x Thanks!
@TonyPythoneer Thank you for your reviewing!