Add types for https://github.com/jaredhanson/passport-anonymous
DefinitelyTyped/DefinitelyTyped pull request #14016
Opened 2017-01-14 08:41 UTC by 0x6368656174

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-01-17 22:02 UTC, mhegazy commented on passport-anonymous/passport-anonymous-tests.ts
> +import login = require("passport-anonymous");
The test should have a more content, something like:

```ts
import * as passport from "passport";
import  { Strategy } from "passport-anonymous";

passport.use(new Strategy());
```

2017-01-17 22:04 UTC, mhegazy requested changes

2017-01-17 22:04 UTC, mhegazy commented on passport-anonymous/index.d.ts
> +declare class Strategy implements passport.Strategy {
this does not look accurate.. see https://github.com/jaredhanson/passport-anonymous/blob/master/lib/index.js#L15


the module should have `export = Strategy` at the bottom, and `Strategy` should have a static member `static Strategy: typeof Strategy`

2017-01-18 01:15 UTC, 0x6368656174 commented on passport-anonymous/passport-anonymous-tests.ts
> +import login = require("passport-anonymous");
fix

2017-01-18 01:18 UTC, 0x6368656174 commented on passport-anonymous/index.d.ts
> +declare class Strategy implements passport.Strategy {
I did it like other passport packages:
- passport-beam: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/passport-beam/index.d.ts#L12-L16
- passport-facebook: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/passport-facebook/index.d.ts#L32-L37
- passport-http: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/passport-http/index.d.ts#L45-L51
- passport-local: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/passport-local/index.d.ts#L37-L44
- passport-google-oauth: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/passport-google-oauth/index.d.ts#L65-L70
- others....

2017-01-18 06:40 UTC, merged