[passport] Fix serializeUser and deserializeUser
DefinitelyTyped/DefinitelyTyped pull request #14079
Opened 2017-01-18 07:49 UTC by enaeseth

As these functions are currently typed, there's no way for the serialize or deserialize callbacks to fail and only pass an error back to Passport.

- [ ] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jaredhanson/passport/blob/v0.3.2/README.md#sessions
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-01-18 17:57 UTC, mhegazy requested changes

2017-01-18 17:57 UTC, mhegazy commented on passport/index.d.ts
> +            serializeUser<TUser, TID>(fn: (user: TUser, done: (err: any, id?: TID) => void) => void): void;
callbacks should not have optional arguments. you will either call it with 2 arguments or not.

2017-01-18 18:18 UTC, mhegazy commented
@enaeseth can you elaborate on why you need optional properties here?

2017-01-18 18:23 UTC, enaeseth commented
@mhegazy oh, I'm just trying to describe the library as-is. The `done` callback isn't user code, it's passed in by the library and the docs [show those callbacks being called with one argument](https://github.com/jaredhanson/passport/blob/v0.3.2/README.md#strategies) to indicate an error to the library.

If you want the typing to be stricter than the underlying library, I can change it to… `TUser | null`, I guess?

2017-01-18 21:06 UTC, mhegazy commented
From the code you shared, `done` can be called with 1 or 2 arguments. `done` is an argument to the function, and and it is OK to pass a function that requires 1 argument to a caller that will call it with 2, i.e. it is ok for a function to ignore parameters. the opposite is not true though, you can not call a function with two required parameters with only 1. 

From the documentation, this should be:
```ts
 done: (err: null | SomeErrorType, id: boolean | undefined) => void)
```

2017-01-18 22:07 UTC, enaeseth commented
The code I linked to is [already in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cd4debea25a280da0808d4ff2ca5a4bdb34bd28b/passport-local/index.d.ts#L34), where the `done` callback is declared as:

```typescript
done: (error: any, user?: any, options?: IVerifyOptions) => void
```

I'm sorry to be a stickler, but I really do think this is correct as written. Calling an `(err, result) => void` callback with one argument to indicate failure is a very common pattern in node.js-style asynchronicity, and this signature matches how the passport family of packages is already typed.

But if we continue to disagree, I won't push back further. The type you proposed is too specific – `err` must be `any` – but I'll make `id: TID | undefined` and `user: TUser | undefined`.

2017-01-18 22:09 UTC, enaeseth commented
…meanwhile, do you know why the `koa-passport` is failing? Those async functions have been in its tests for awhile.

2017-01-20 18:18 UTC, andy-ms commented
It succeeds on `master`, so try merging in the latest `master` to your branch.

2017-02-04 01:53 UTC, bowdenk7 commented
Not sure if this is resolved or not @mhegazy

2017-02-04 02:32 UTC, enaeseth commented
sorry, it's not. I'll either merge master in or rebase, and it should then pass tests

2017-02-04 02:48 UTC, bowdenk7 commented
thanks!

2017-02-07 21:58 UTC, hinell commented on passport/index.d.ts
> +            serializeUser<TUser, TID>(fn: (user: TUser, done: (err: any, id?: TID) => void) => void): void;
Here we go.

2017-02-07 21:58 UTC, hinell commented
@enaeseth [You have to read this](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Do's%20and%20Don'ts.md#optional-parameters-in-callbacks)

2017-02-07 22:00 UTC, hinell commented on passport/index.d.ts
> +            deserializeUser<TUser, TID>(fn: (id: TID, done: (err: any, user?: TUser) => void) => void): void;
The same here.

2017-02-07 22:00 UTC, hinell requested changes

2017-02-07 22:00 UTC, hinell commented on passport/index.d.ts
> +            deserializeUser<TUser, TID>(fn: (id: TID, done: (err: any, user?: TUser) => void) => void): void;
The same here.

2017-02-07 23:16 UTC, enaeseth commented on passport/index.d.ts
> +            deserializeUser<TUser, TID>(fn: (id: TID, done: (err: any, user?: TUser) => void) => void): void;
There's two callbacks in the lines you highlighted:

- `fn`: this is a user-provided callback which will be called by the library. this is the kind of callback described in the Handbook section you linked, and it has no optional parameters.
- `done`: this is a *library*-provided callback which will be called by user code. my argument is that this is a different case; it's not the same kind of callback, it's a method of the library which is dynamically provided to user code. and it's perfectly fine to have optional parameters on functions provided by libraries.

a well-known example of this is Express middleware – middleware functions accept a `next` callback [provided by Express](https://github.com/expressjs/express/blob/master/lib/router/index.js#L178) that is called with no arguments to indicate “ok, invoke the next handler” or can be called with an error to indicate failure.

and those functions are [typed in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/express-serve-static-core/index.d.ts#L22) with `err` as an optional parameter:

```ts
interface NextFunction {
    (err?: any): void;
}
```

I appreciate the effort you all put in to review pull requests and ensure that the types in DefinitelyTyped really are high-quality. this is a non-obvious distinction and I'm trying to help clarify your guidelines. I'd be happy to submit a pull request to TypeScript-Handbook to distinguish these two kinds of callback functions.

2017-02-08 09:11 UTC, hinell approved these changes

2017-02-09 01:12 UTC, aozgaa commented
Thanks for the change and explanation @enaseth

2017-02-09 01:12 UTC, merged