types(jasminewd): add new typings for jasminewd
DefinitelyTyped/DefinitelyTyped pull request #14126
Opened 2017-01-19 20:13 UTC by cnishina

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `tsc` without errors.

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis` set to `true`.

2017-01-19 21:04 UTC, sjelin requested changes

2017-01-19 21:04 UTC, sjelin commented on jasminewd/index.d.ts
> +// This is jasminewd's internal version of @types/jasminewd2.  If you need types
no it isn't :smile:

2017-01-19 21:05 UTC, cnishina commented on jasminewd/index.d.ts
> +// This is jasminewd's internal version of @types/jasminewd2.  If you need types
Removed comment.

2017-01-19 21:10 UTC, mhegazy requested changes

2017-01-19 21:10 UTC, mhegazy commented on jasminewd/index.d.ts
> +// Type definitions for jasminewd2 0.1.1
please add a [tslint.json](https://github.com/DefinitelyTyped/DefinitelyTyped#lint), it should catch issues like this header version being invalid.

2017-01-19 22:24 UTC, cnishina commented on jasminewd/index.d.ts
> +// Type definitions for jasminewd2 0.1.1
Moving the folder to jasminewd2. The published npm is "jasminewd2" however, the project is called "jasminewd"

2017-01-19 22:50 UTC, cnishina commented
Removed tslint check:

```
  interface AsyncCustomMatcherFactory {
      (util: MatchersUtil, customEqualityTesters: CustomEqualityTester[]): AsyncCustomMatcher;
  }
```

This causes the tslint to be unhappy. It recommends changing this to a function.

@sjelin for review and comment.

2017-01-19 23:09 UTC, sjelin requested changes
test `addMatchers` and it should be good

2017-01-19 23:29 UTC, mhegazy commented
> Removed tslint check:

do not remove the tslint.json, just disable the rule in the config file.

2017-01-19 23:45 UTC, cnishina commented
Hmmm... I'm not sure how to do this. Could you point me to the right documentation?

2017-01-19 23:54 UTC, cnishina commented
@mhegazy I added tslint.json back. I'm not sure how to do disable the tslint from the config (I'm guessing this is done in tsconfig). Could you point me to the right documentation?

2017-01-20 00:12 UTC, mhegazy commented
change your tslint file to:

```ts
{
    "extends": "../tslint.json",
    "rules": {
        "callable-types": false
    }
}
```

2017-01-20 00:15 UTC, sjelin requested changes
Minor stuff

2017-01-20 00:15 UTC, sjelin commented on jasminewd2/jasminewd2-tests.ts
> +                pass: actual.isDisplayed()
I'd prefer you put a `Promise<boolean>` here to make the test more explicit

2017-01-20 00:15 UTC, sjelin commented on jasminewd2/jasminewd2-tests.ts
> +      jasmine.addMatchers(matchers);
For completeness, add:
```ts
jasmine.getEnv().addMatchers(matchers);
jasmine.getEnv().currentSpec.addMatchers(matchers);
```

2017-01-23 23:24 UTC, cnishina commented on jasminewd2/jasminewd2-tests.ts
> +                pass: actual.isDisplayed()
Done.

2017-01-23 23:24 UTC, cnishina commented on jasminewd2/jasminewd2-tests.ts
> +      jasmine.addMatchers(matchers);
Done.

2017-01-23 23:40 UTC, cnishina commented
@mhegazy Updated the tslint. Please review.

2017-01-24 00:56 UTC, mhegazy approved these changes

2017-01-24 00:59 UTC, merged