add cannon,rsvp,wonder-commonlib,wonder-frp dts file
DefinitelyTyped/DefinitelyTyped pull request #14163
Opened 2017-01-21 13:17 UTC by yyc-git

Please fill in this template.

- [ ] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-01-21 21:07 UTC, mhegazy requested changes

2017-01-21 21:07 UTC, mhegazy commented on cannon/tsconfig.json
> +        "strictNullChecks": false,
`true` instead. applies to other config files as well.

2017-01-21 21:07 UTC, mhegazy commented on cannon/index.d.ts
> +
Please add a tslint.json, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#lint

2017-01-21 21:07 UTC, mhegazy commented on cannon/index.d.ts
> +declare module CANNON {
Missing header. also applies to other files.

just run `npm run new-package cannon`

seee https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#create-a-new-package

A header looks like:

```ts
// Type definitions for cannon <version>
// Project: https://github.com/beatgammit/base64-js
// Definitions by: YYC <https://github.com/yyc-git>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
```

2017-01-22 01:56 UTC, yyc-git commented
Hello! I have pass the ci, please check and merge the request! 
Thanks very much!

2017-01-22 23:12 UTC, yyc-git commented on cannon/index.d.ts
> +
please  pass!

2017-01-23 02:27 UTC, mhegazy commented
Thanks for the updates, can you please also add the `tslint.json`, and fix the lint warning you will get. see: https://github.com/DefinitelyTyped/DefinitelyTyped#lint

2017-01-23 03:41 UTC, yyc-git commented
Nice to see your reply!
The lint warn is difficult to fix, so can i not add the tslint.json?please?

2017-01-23 03:42 UTC, yyc-git commented
Please merge the request so that I can get the dts from npm~

2017-01-23 08:21 UTC, merged

2017-01-23 08:21 UTC, horiuchi commented
👍

2017-01-23 08:22 UTC, yyc-git commented
Thanks very much!