js-md5 - add ArrayBuffer parameter
DefinitelyTyped/DefinitelyTyped pull request #14167
Opened 2017-01-22 01:07 UTC by mwmccarthy

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/emn178/js-md5#example>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-01-24 22:23 UTC, mwmccarthy commented
There are some other changes I wanted to make to this also because I'm not sure what's going on, but I wanted to check first to see what I might be missing. It looks like these definitions expect the String prototype to have been modified in some way? And what does this module have to do with JQuery?

2017-01-25 01:56 UTC, DanielRosenwasser commented
@tigerxy any idea why were these overloads originally added? The source code doesn't seem to indicate that JQuery or String's prototype get modified.

@emn178 do you know if this was ever the behavior of js-md5? Sorry for pestering you.

2017-01-25 02:19 UTC, emn178 commented
jQuery and prototype methods are not included in js-md5. Please remove.

2017-01-25 07:20 UTC, DanielRosenwasser commented
Thanks a bunch for the response @emn178!

So @mwmccarthy, feel free to remove the augmentations and remove the `/// <types ...>`.

Then, I'd wrap the interfaces in a

```ts
declare namespace md5 {
    // ... interfaces go here
}
```

and replace the

```ts
declare module "js-md5" {
     export = md5;
 }
declare var md5: md5;
```

with the following:

```tsd
declare var md5: md5.md5;
export = md5;
```

Currently this `.d.ts` is not super accurate with the library itself. I think we'd welcome a rewrite.

2017-01-25 12:09 UTC, mwmccarthy commented
@DanielRosenwasser, thanks I'll rewrite it as you suggest. I appreciate the feedback.

2017-01-25 21:03 UTC, DanielRosenwasser requested changes

2017-01-25 21:03 UTC, DanielRosenwasser commented on js-md5/js-md5-tests.ts
> +import * as md5 from "js-md5";
Last update - can you switch this to `import md5 = require("md5")`

2017-01-25 21:05 UTC, mwmccarthy commented on js-md5/js-md5-tests.ts
> +import * as md5 from "js-md5";
Absolutely. Should I do something with the version number too? It looks like the travis build doesn't like it for some reason.

2017-01-25 21:07 UTC, DanielRosenwasser commented on js-md5/js-md5-tests.ts
> +import * as md5 from "js-md5";
Yes! Didn't catch that, can you switch that to v0.4 if that's the correct version?

2017-01-25 21:18 UTC, mwmccarthy commented on js-md5/js-md5-tests.ts
> +import * as md5 from "js-md5";
Should be good to go.

2017-02-04 02:31 UTC, merged