msgpack: add module declaration
DefinitelyTyped/DefinitelyTyped pull request #14181
Opened 2017-01-23 06:02 UTC by yohei1126

- [ ] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes:https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14180

2017-01-25 01:48 UTC, DanielRosenwasser requested changes

2017-01-25 01:48 UTC, DanielRosenwasser commented on msgpack/index.d.ts
> +declare module "msgpack" {
The appropriate fix is to replace this with

```ts
export = msgpack;
```

If `msgpack` is also available in as a global in the browser (it doesn't look like it is, but I'm not sure), then it'd be

```ts
export = msgpack;
export as namespace
```

2017-02-04 02:34 UTC, bowdenk7 commented
@yohei1126 can you address the comments and refresh the PR?

2017-02-04 04:14 UTC, yohei1126 commented
fix it. please check.

2017-02-04 04:20 UTC, yohei1126 commented
sorry, it broke the build.

2017-02-17 20:43 UTC, zhengbli commented
@yohei1126 any updates on this one?

2017-02-18 05:36 UTC, yohei1126 commented
@DanielRosenwasser  Do you know the solution for this build failure? 
https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/198251240

```
Error in msgpack
Command failed: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../typescript-installs/2.0/node_modules/typescript/lib/tsc.js 
msgpack-tests.ts(3,14): error TS2304: Cannot find name 'msgpack'.
msgpack-tests.ts(4,1): error TS2304: Cannot find name 'msgpack'.
msgpack-tests.ts(6,20): error TS2304: Cannot find name 'msgpack'.
msgpack-tests.ts(7,1): error TS2304: Cannot find name 'msgpack'.
msgpack-tests.ts(15,41): error TS2304: Cannot find name 'MsgPackUploadOption'.
msgpack-tests.ts(16,40): error TS2304: Cannot find name 'MsgPackUploadOption'.
msgpack-tests.ts(16,69): error TS2304: Cannot find name 'MsgPackCallbackResult'.
msgpack-tests.ts(18,45): error TS2304: Cannot find name 'MsgPackUploadOption'.
msgpack-tests.ts(18,74): error TS2304: Cannot find name 'MsgPackCallbackResult'.
msgpack-tests.ts(19,1): error TS2304: Cannot find name 'msgpack'.
msgpack-tests.ts(24,41): error TS2304: Cannot find name 'MsgPackDownloadOption'.
msgpack-tests.ts(25,40): error TS2304: Cannot find name 'MsgPackDownloadOption'.
msgpack-tests.ts(25,71): error TS2304: Cannot find name 'MsgPackCallbackResult'.
msgpack-tests.ts(27,44): error TS2304: Cannot find name 'MsgPackDownloadOption'.
msgpack-tests.ts(27,75): error TS2304: Cannot find name 'MsgPackCallbackResult'.
msgpack-tests.ts(28,1): error TS2304: Cannot find name 'msgpack'.
Error: There was a test failure.
    at Object.<anonymous> (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:90:9)
    at next (native)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/test-runner.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
npm ERR! Test failed.  See above for more details.
```

2017-02-18 07:51 UTC, DanielRosenwasser commented
Yes, `msgpack` is being used as a global.

So either you'll need to import `msgpack` from those files:

```ts
import msgpack = require("msgpack");
```

or if it truly can be used as a global (i.e. in the browser, you can just write `msgpack` and it'll work), then you'll need to add

```ts
export as namespace msgpack;
```

to the bottom of your file.

2017-02-18 10:03 UTC, yohei1126 commented
thanks! I will try it later.

2017-02-18 11:41 UTC, yohei1126 commented
there is still the same issue.

```
Testing msgpack
	Running: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../typescript-installs/2.0/node_modules/typescript/lib/tsc.js 
	msgpack-tests.ts(15,41): error TS2304: Cannot find name 'MsgPackUploadOption'.
msgpack-tests.ts(16,40): error TS2304: Cannot find name 'MsgPackUploadOption'.
msgpack-tests.ts(16,69): error TS2304: Cannot find name 'MsgPackCallbackResult'.
msgpack-tests.ts(18,45): error TS2304: Cannot find name 'MsgPackUploadOption'.
msgpack-tests.ts(18,74): error TS2304: Cannot find name 'MsgPackCallbackResult'.
msgpack-tests.ts(24,41): error TS2304: Cannot find name 'MsgPackDownloadOption'.
msgpack-tests.ts(25,40): error TS2304: Cannot find name 'MsgPackDownloadOption'.
msgpack-tests.ts(25,71): error TS2304: Cannot find name 'MsgPackCallbackResult'.
msgpack-tests.ts(27,44): error TS2304: Cannot find name 'MsgPackDownloadOption'.
msgpack-tests.ts(27,75): error TS2304: Cannot find name 'MsgPackCallbackResult'.
	Running: node /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/tester/../../typescript-installs/2.1/node_modules/typescript/lib/tsc.js 
	msgpack-tests.ts(15,41): error TS2304: Cannot find name 'MsgPackUploadOption'.
msgpack-tests.ts(16,40): error TS2304: Cannot find name 'MsgPackUploadOption'.
msgpack-tests.ts(16,69): error TS2304: Cannot find name 'MsgPackCallbackResult'.
msgpack-tests.ts(18,45): error TS2304: Cannot find name 'MsgPackUploadOption'.
msgpack-tests.ts(18,74): error TS2304: Cannot find name 'MsgPackCallbackResult'.
msgpack-tests.ts(24,41): error TS2304: Cannot find name 'MsgPackDownloadOption'.
msgpack-tests.ts(25,40): error TS2304: Cannot find name 'MsgPackDownloadOption'.
msgpack-tests.ts(25,71): error TS2304: Cannot find name 'MsgPackCallbackResult'.
msgpack-tests.ts(27,44): error TS2304: Cannot find name 'MsgPackDownloadOption'.
msgpack-tests.ts(27,75): error TS2304: Cannot find name 'MsgPackCallbackResult'.
```

2017-03-01 21:59 UTC, jramsay commented
@DanielRosenwasser: the following works but I'm not sure it is the correct guidance.  I've seen this pattern used elsewhere - is the correct fix here to wrap all interfaces in index.d.ts with:

 declare namespace msgpack { ...}

and then at the bottom of the file:

declare var msgpack: msgpack.MsgPackStatic;
export = msgpack;
export as namespace msgpack;

Then in msgpack-tests.ts prepend namespace interfaces with msgpack.
ex:   before: (xhr: XMLHttpRequest, option: msgpack.MsgPackUploadOption) => { },

2017-03-21 22:55 UTC, DanielRosenwasser commented on msgpack/index.d.ts
>  declare var msgpack: MsgPackStatic;
Correct thing to do here is wrap the entire thing in a namespace named `msgpack`, then keep this variable around with the following type:

```ts
declare var msgpack: msgpack.MsgPackStatic;
```

and then everything should work again.

2017-03-23 01:55 UTC, yohei1126 commented
@DanielRosenwasser All checks on CI  has passed. Could you please review the code again.

2017-03-24 00:16 UTC, ogis-onishi commented on msgpack/index.d.ts
>  declare var msgpack: MsgPackStatic;
I fixed it. Please check.

2017-03-24 16:19 UTC, sandersn commented
I believe @DanielRosenwasser is attending a conference right now and will be able to review the new changes in a few days.

2017-03-24 22:09 UTC, andy-ms commented
We've recently updated the repository structure.
All packages are now in a `types` subdirectory.
Please rebase this pull request onto the latest `master` branch.

2017-03-25 09:58 UTC, yohei1126 commented
@andy-ms  Thanks. I did it.

2017-03-27 01:58 UTC, ogis-onishi commented
@DanielRosenwasser Could you check it today if possible?

2017-03-27 01:59 UTC, yohei1126 commented
@DanielRosenwasser Could you check it today if possible?

2017-03-27 22:41 UTC, sandersn commented
Looks good to me.

2017-03-27 22:41 UTC, merged