add typescript module export to suport import * as SimpleMDE from 'si…
DefinitelyTyped/DefinitelyTyped pull request #14186
Opened 2017-01-23 10:14 UTC by doxiaodong

…mplemde'

Please fill in this template.

- [ x] Make your PR against the `master` branch.
- [ x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x ] Test the change in your own code. (Compile and run.)
- [ x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ x ] Run `tsc` without errors.
- [ x ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-01-25 01:44 UTC, DanielRosenwasser requested changes

2017-01-25 01:44 UTC, DanielRosenwasser commented on simplemde/index.d.ts
> +}
The appropriate change is to write

```ts
export = SimpleMDE;
export as namespace SimpleMDE;
```

2017-01-25 02:14 UTC, doxiaodong commented on simplemde/index.d.ts
> +}
ok, thanks

2017-01-25 02:14 UTC, DanielRosenwasser approved these changes

2017-01-30 18:33 UTC, merged

2017-02-13 15:17 UTC, doxiaodong commented
publish this? @DanielRosenwasser