add sub module export
DefinitelyTyped/DefinitelyTyped pull request #14190
Opened 2017-01-23 12:20 UTC by doxiaodong

* add sub module export
* egg
```
import * as md5 from 'crypto-js/md5'
import * as sha1 from 'crypto-js/sha1'
...
```
* the export list is dependent on https://github.com/brix/crypto-js/tree/3.1.4#usage-without-requirejs

Please fill in this template.

- [ x ] Make your PR against the `master` branch.
- [ x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x ] Test the change in your own code. (Compile and run.)
- [ x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ x ] Run `tsc` without errors.
- [ x ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-01-23 21:09 UTC, misak113 commented
👍

2017-01-24 03:21 UTC, doxiaodong commented
@misak113 , is it possible to merge with https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/cryptojs/index.d.ts? I don't think it's necessary to have two types of `crypto-js`

2017-01-24 08:56 UTC, misak113 commented
Probably yes however it is not under my privileges. Correct name based on npm registry is this crypto-js.

2017-01-25 01:43 UTC, DanielRosenwasser requested changes

2017-01-25 01:43 UTC, DanielRosenwasser commented on crypto-js/index.d.ts
> -export as namespace CryptoJS;
This isn't the appropriate fix. These should be restored.

Then, each of the below modules that you've declared should have their own declaration file in the directory that import the necessary types from `index.d.ts` and export whatever they usually do.

So, for instance, you should have a `core.d.ts` in the `crypto-js` directory.

2017-01-25 05:50 UTC, doxiaodong commented on crypto-js/index.d.ts
> -export as namespace CryptoJS;
I create `aes.d.ts`, and it works fine
```
import { AES } from './index'
export = AES;

```
But when I create `enc-base64.d.ts`, it throw `Cannot find namespace 'enc'`, how to fix it?
```
import { enc } from './index'
export = enc.Base64;
```

2017-01-25 07:17 UTC, doxiaodong commented
@DanielRosenwasser , hello, thanks for review.

2017-01-25 07:25 UTC, DanielRosenwasser commented
Thanks so much for putting the time in for this! I know that I've asked for a lot at this moment, but it'd be greatly appreciated if you had some basic tests for a few of these (i.e. just importing a few, utilizing the functionality, etc.)

2017-01-25 08:09 UTC, doxiaodong commented
@DanielRosenwasser , I just copy `crypto-js-tests.ts` to `test/submodule-tests.ts`,  and use submodule api.

2017-01-29 05:35 UTC, DanielRosenwasser approved these changes

2017-01-29 05:35 UTC, merged