GreenSock TweenMax fix RoughEase
DefinitelyTyped/DefinitelyTyped pull request #14193
Opened 2017-01-23 14:08 UTC by lucap86

Please fill in this template.

- [x ] Make your PR against the `master` branch.
- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <https://greensock.com/docs/#/HTML5/GSAP/Easing/RoughEase/config/>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-01-25 07:27 UTC, DanielRosenwasser requested changes

2017-01-25 07:27 UTC, DanielRosenwasser commented on greensock/index.d.ts
> +    public config(steps: RoughEaseConfig): RoughEase;
And also, can you make it optional?

2017-01-25 13:52 UTC, lucap86 commented on greensock/index.d.ts
> +    public config(steps: RoughEaseConfig): RoughEase;
make it optional should be enough..
isnt'it?

2017-01-30 09:27 UTC, lucap86 commented
@DanielRosenwasser can you please unlock pull request ?
as I said before, make it optional should be enough
@ProbablePrime has done the job in  commit #8826814f37249f56ccd08d19d578ed20b4bf2a24

2017-02-04 03:10 UTC, bowdenk7 commented
@DanielRosenwasser not sure what's going on here. Can you resolve?

2017-02-05 00:40 UTC, ProbablePrime commented
Personally i'd say close this and defer to my branch. Otherwise you'd have to merge this then mine.

2017-02-08 21:32 UTC, aozgaa commented
Let's wait on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14332, and if that fails then take this smaller change.

2017-03-06 19:55 UTC, minestarks commented
Closing since it looks like the work is already done in commit 8826814f37249f56ccd08d19d578ed20b4bf2a24

2017-03-06 19:55 UTC, closed without merging

2018-03-15 12:38 UTC, ste-vg commented
commit 8826814 didn't include the `RoughEaseConfig` change to the steps type.