MetisMenu: add missing types for 2.6.1
DefinitelyTyped/DefinitelyTyped pull request #14215
Opened 2017-01-24 14:20 UTC by denisname

Add events types, preventDefault properties, and 'dispose' option.

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
* [Events](https://github.com/onokumus/metisMenu/blob/master/README.md#events)
* [PreventDefault](https://github.com/onokumus/metisMenu/blob/master/README.md#preventdefault)
* [Dispose](https://github.com/onokumus/metisMenu/blob/master/README.md#dispose)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-01-30 18:25 UTC, DanielRosenwasser requested changes

2017-01-30 18:25 UTC, DanielRosenwasser commented on metismenu/index.d.ts
> +// Type definitions for metisMenu 2.6.1
Can you truncate this to 2.6?

2017-01-30 18:25 UTC, DanielRosenwasser commented on metismenu/index.d.ts
>  // Definitions by: onokums <https://github.com/onokumus/>
Would you be willing to add yourself as an author to this declaration file?

2017-01-30 18:27 UTC, DanielRosenwasser commented
The declarations look solid. I'll pull these in soon!

Just as a heads up, GitHub isn't recognizing the email address you used for your commits. Feel free to rebase and change the author, or just register the email address with GitHub.

If you don't care, we can just pull the commits in after the feedback is addressed.

2017-01-31 11:59 UTC, denisname commented
I didn't understand the problem about the email very well.
Github knows my email, and I got all notifications.

I use GitHub private address:
```
$ git config user.email
denisname@users.noreply.github.com
```
Is this related?

2017-02-02 16:06 UTC, denisname commented
I just updated code for MetisMenu 2.6.2:
* The property `doubleTapToGo` was deprecated and is gone in 2.6.2.
* As 2.6.2 is not backward compatible with previous versions, I set back exact version in the header.

2017-02-04 02:44 UTC, merged