add types of node-zookeeper-client
DefinitelyTyped/DefinitelyTyped pull request #14235
Opened 2017-01-25 15:35 UTC by plantain-00

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-01-26 02:20 UTC, DanielRosenwasser requested changes

2017-01-26 02:20 UTC, DanielRosenwasser commented on node-zookeeper-client/index.d.ts
> +// Type definitions for Jasmine 2.5
This doesn't look like Jasmine 2.5

2017-01-26 02:20 UTC, DanielRosenwasser commented on node-zookeeper-client/tsconfig.json
> +        "strictNullChecks": false,
Can you ensure that this is authored for `strictNullChecks`?

2017-01-26 02:20 UTC, DanielRosenwasser commented on node-zookeeper-client/node-zookeeper-client-tests.ts
> +    var state = client.getState();
If these are block-scoped, might as well use `let` instead of `var`.

2017-01-26 02:20 UTC, DanielRosenwasser commented on node-zookeeper-client/index.d.ts
> +export class Transaction {
The top level `index.js` file doesn't actually export the constructor, so this should be an `interface`.

2017-01-26 02:20 UTC, DanielRosenwasser commented on node-zookeeper-client/index.d.ts
> +export class Client extends EventEmitter {
I don't see an export for `Client`, so this should probably be an interface.

2017-01-26 11:25 UTC, plantain-00 commented
@DanielRosenwasser Can you see this?

2017-01-27 21:32 UTC, DanielRosenwasser approved these changes

2017-01-27 21:32 UTC, merged

2017-01-27 21:32 UTC, DanielRosenwasser commented
Thank you!