(validator.js) Add missing options to isInt method
DefinitelyTyped/DefinitelyTyped pull request #14233
Opened 2017-01-25 12:19 UTC by kacepe

Missing options:
`allow_leading_zeroes`: https://github.com/chriso/validator.js/blob/master/src/lib/isInt.js#L13
`lt`: https://github.com/chriso/validator.js/blob/master/src/lib/isInt.js#L20
`gt`: https://github.com/chriso/validator.js/blob/master/src/lib/isInt.js#L21

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/chriso/validator.js/blob/master/src/lib/isInt.js
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-01-25 12:26 UTC, tgfjt commented on validator/index.d.ts
>  // Type definitions for validator.js v5.7.0
It seems to be 6.2.1? 👍

2017-01-25 12:33 UTC, kacepe commented on validator/index.d.ts
>  // Type definitions for validator.js v5.7.0
I think yes, but I didn't make more changes to increase version number. I want to do it in the evening.

2017-01-25 18:22 UTC, DanielRosenwasser requested changes

2017-01-25 18:22 UTC, DanielRosenwasser commented on validator/index.d.ts
> +// Type definitions for validator.js v6.2.1
This version number should only be `major.minor` - can you add a tslint.json with the following content?

```json
{ "extends": "../tslint.json" }
```

2017-01-25 19:51 UTC, kacepe commented on validator/index.d.ts
> +// Type definitions for validator.js v6.2.1
Sure, done.

2017-01-25 20:11 UTC, kacepe commented on validator/index.d.ts
> +// Type definitions for validator.js v6.2.1
It isn't pass a test with this.

2017-01-25 21:05 UTC, DanielRosenwasser requested changes

2017-01-25 21:05 UTC, DanielRosenwasser commented on validator/index.d.ts
> +// Type definitions for validator.js v6.2.1
Weird (@mhegazy?) - anyway, can you just switch this to `v6.2`? After that we can pull this in.

2017-01-26 08:19 UTC, kacepe commented on validator/index.d.ts
> +// Type definitions for validator.js v6.2.1
@DanielRosenwasser done

2017-02-04 03:19 UTC, merged