knex: reference correct Promise implementation
DefinitelyTyped/DefinitelyTyped pull request #14240
Opened 2017-01-25 17:52 UTC by jeffkenney

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tgriesser/knex/blob/master/src/client.js#L1
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-01-25 18:25 UTC, DanielRosenwasser requested changes

2017-01-25 18:25 UTC, DanielRosenwasser commented on knex/index.d.ts
> +import * as Promise from "bluebird";
Can you switch these to

```ts
import events = require("events");
import Promise = require("bluebird");
```

2017-01-25 20:06 UTC, jeffkenney commented
Hey @DanielRosenwasser ,

I made the requested changes. As a quick aside, why is `import Promise = require('bluebird');` preferred over `import * as Promise from 'bluebird';`?

2017-01-25 20:15 UTC, DanielRosenwasser commented
Technically per the ES spec, a namespace import is not constructable, callable, etc. Using the `import x = require('foo')` syntax accurately models that this is a CommonJS import.

2017-01-25 20:15 UTC, DanielRosenwasser approved these changes

2017-01-25 20:15 UTC, DanielRosenwasser requested changes

2017-01-25 20:15 UTC, DanielRosenwasser commented on knex/knex-tests.ts
> +import * as Promise from 'bluebird';
Sorry about this - can you change this to `import x = require("foo")` here as well please?

2017-01-25 22:45 UTC, jeffkenney commented
@DanielRosenwasser,
Tests file updated; thanks for the explanation.

Are the following methods then the best practices for imports?

```typescript
// from commonjs modules using `module.exports`
import x = require('y');
```

```typescript
// from es6 modules using `export default`
import x from 'y';
```

```typescript
// from es6 modules with named exports
import * as x from 'y';
x.a();
// or
import { a } from 'y';
a();
```

2017-01-26 02:22 UTC, DanielRosenwasser commented
@jeffkenney yes, I'd say that's accurate. Thanks for the changes!

2017-01-26 02:22 UTC, DanielRosenwasser approved these changes

2017-01-26 02:22 UTC, merged