Steed - add type definition
DefinitelyTyped/DefinitelyTyped pull request #14263
Opened 2017-01-26 14:42 UTC by Paul-Isache

If adding a new definition:
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.

2017-01-26 20:54 UTC, DanielRosenwasser requested changes

2017-01-26 20:54 UTC, DanielRosenwasser commented on steed/index.d.ts
> +}
These interfaces aren't publicly available, so can you wrap them in a `declare namespace steed { /*...*/ }`? Then make the below

```ts
declare const steed: steed.Steed;
```

2017-01-26 20:54 UTC, DanielRosenwasser commented on steed/index.d.ts
> +declare module "steed" {
Unwrap this to the top level as `export = steed`

2017-01-26 20:54 UTC, DanielRosenwasser commented on steed/steed-tests.ts
> +steed.map(['file1', 'file2', 'file3'], fs.stat, function (err:Error, results:Array<fs.Stats>) { });
The package doesn't seem to be exported as a global - please import it.

2017-01-26 20:54 UTC, DanielRosenwasser commented on steed/steed-tests.ts
> +import fs = require("fs");
Please don't bring in `fs` and `process` if the original file doesn't use them.

2017-01-27 21:36 UTC, DanielRosenwasser commented
Just as a heads up, the email on these commits isn't registered with GitHub - if you need to rebase and fixup the author, or register the email you used with GitHub, you migth want to do that. If you don't care much, i can just merge it in.

2017-01-28 05:13 UTC, Paul-Isache commented
You can merge it. There is an issue with my account on my laptop and on the future I will try and fix it, but for now si good

2017-01-29 05:11 UTC, DanielRosenwasser approved these changes

2017-01-29 05:12 UTC, merged

2017-01-29 05:12 UTC, DanielRosenwasser commented
Thanks!