archiver: add file definition
DefinitelyTyped/DefinitelyTyped pull request #14265
Opened 2017-01-26 15:59 UTC by deerawan

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/archiverjs/node-archiver/blob/38ff225bdcf0ad4ff1e6395212922498d1f2e270/examples/express.js#L28
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-01-26 20:49 UTC, DanielRosenwasser requested changes

2017-01-26 20:49 UTC, DanielRosenwasser commented on archiver/index.d.ts
> +        file(source: string, name: nameInterface): void;
`name`  should be called `data`, and should have a type named `EntryData` - so you'll need to export an interface that reflects the following type: https://archiverjs.com/docs/global.html#EntryData

2017-02-17 20:55 UTC, zhengbli commented
@deerawan can you update according to the review? Thanks!

2017-03-01 22:09 UTC, jramsay commented
@deerawan:  Thanks for your contribution. This PR has unaddressed comments and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs.  If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-03-01 22:09 UTC, closed without merging