Pino - update pretty formatter option
DefinitelyTyped/DefinitelyTyped pull request #14262
Opened 2017-01-26 14:39 UTC by Paul-Isache

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pinojs/pino/blob/master/docs/API.md#user-content-parameters-1

2017-01-26 23:55 UTC, DanielRosenwasser requested changes

2017-01-26 23:55 UTC, DanielRosenwasser commented on pino/index.d.ts
> +interface IPinoLog {
Move this into the namespace so it can be referenced.

2017-01-27 04:10 UTC, psnider commented on pino/index.d.ts
> +    function pretty(opts?: {timeTransOnly?: boolean, levelFirst?: boolean, formatter?: (log: IPinoLog) => string}): stream.Transform;
The [documentation](https://github.com/pinojs/pino/blob/master/docs/API.md#pretty) states:
> formatter (function): a custom function to format the line, is passed the JSON object as an argument and should return a string value.

and the proposed change doesn't seem to agree.
I think ```formatter?: (log: {}) => string``` should work.

2017-01-27 06:19 UTC, Paul-Isache commented on pino/index.d.ts
> +    function pretty(opts?: {timeTransOnly?: boolean, levelFirst?: boolean, formatter?: (log: IPinoLog) => string}): stream.Transform;
I have created the interface to have a better look on the object that is passed to the function.

2017-01-27 06:21 UTC, Paul-Isache commented on pino/index.d.ts
> +interface IPinoLog {
I moved the interface inside the namespace

2017-01-28 14:53 UTC, Paul-Isache commented
I have made the changes. Is it possible to have another look and maybe merge it?

2017-01-28 15:43 UTC, psnider commented on pino/index.d.ts
> +    function pretty(opts?: {timeTransOnly?: boolean, levelFirst?: boolean, formatter?: (log: IPinoLog) => string}): stream.Transform;
I think the IPinoLog interface isn't quite correct, and I don't think it is required.
When I run pretty(), and JSON.stringify the passed object, I find:
> time: number

I still prefer the simple typing of **{}** as in my suggestion.

Also keep in mind that there will be many more fields in the object, that is, all of those that are dynamically added from the type to be logged.

@DanielRosenwasser 
There used to be a guideline for writing declarations that advised against typing parts of the interface that aren't documented, but I can no longer find this.
The type of the argument to *formatter* is only documented as an object, or **{}**

2017-01-29 05:20 UTC, merged