New Typing Files for forever-monitor
DefinitelyTyped/DefinitelyTyped pull request #14275
Opened 2017-01-26 18:56 UTC by shuntksh

Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-01-26 21:01 UTC, DanielRosenwasser reviewed
The problem with how this is structured is that the other entities are not exported at all, however, you want to use the `export =` syntax because the original module is a CommonJS module.

I would suggest revising this as follows:

```
declare namespace forever {
    export class Monitor {
        // ...
    }

    export interface SpawnWith {
        // ...
    }

    export const version: string
}

export = forever;
```

2017-01-26 21:01 UTC, DanielRosenwasser commented on forever-monitor/index.d.ts
> +export default forever;
This only creates a type that is importable as a default, not a value.

2017-01-26 21:01 UTC, DanielRosenwasser commented on forever-monitor/index.d.ts
> +interface spawnWith {
Capitalize type names please.

2017-01-26 21:05 UTC, DanielRosenwasser requested changes

2017-01-26 21:05 UTC, DanielRosenwasser commented on forever-monitor/index.d.ts
> +interface parserArgs {
Where is this used?

2017-01-26 21:05 UTC, DanielRosenwasser commented on forever-monitor/index.d.ts
> +    Monitor: Monitor;
Is this a `Monitor`? Or is its type `typeof Monitor`?

2017-01-27 03:48 UTC, shuntksh commented on forever-monitor/index.d.ts
> +    Monitor: Monitor;
This would be class itself not typeof class. So new forever.Monitor(args...); is the actual usage.

2017-01-27 03:54 UTC, shuntksh commented
@DanielRosenwasser Thank you for your great suggestion. I quickly tried to reorganize the typing with namespace model as you suggested. Updated typings also worked as expected, however, now test is failing due to "export-just-namespace" warning:

```bash
Error in forever-monitor
Command failed: node /Workspace/_forked/DefinitelyTyped/node_modules/tslint/lib/index.js/../tslint-cli.js --format stylish index.d.ts

index.d.ts
96:1  export-just-namespace  Instead of `export =`-ing a namespace, use the body of the namespace as the module body.
```

Do I have to declare another object / interface inside the namespace and export it instead like below?

```ts
declare namespace Forever {
    interface forever {
       // some typing
    }
}
declare const forever: Forever.forever;
export = forever;
```

2017-01-27 18:11 UTC, shuntksh commented
@DanielRosenwasser I also tried flat-export model to avoid lint-ing error around exporting namespace. And fixed points you mentioned in review with adding few more test cases to test file. Can you take a look?

2017-01-27 20:41 UTC, DanielRosenwasser approved these changes

2017-01-27 20:41 UTC, DanielRosenwasser commented
Sorry about that advice, our lint rules aren't big on it. Looks good now though, thanks!

2017-01-27 20:41 UTC, merged

2017-04-24 13:41 UTC, janwo commented
@shuntksh It might be great having types of the forever module to call `startServer` properly. 👍