[React] Allow SFC to return null
DefinitelyTyped/DefinitelyTyped pull request #14284
Opened 2017-01-27 00:39 UTC by yuit

Please fill in this template.

- [] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: Bug: https://github.com/Microsoft/TypeScript/issues/11566
documentation: https://github.com/facebook/react/pull/5884
- [] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-01-27 00:41 UTC, DanielRosenwasser requested changes
Can you add a test for this?

2017-01-27 00:41 UTC, DanielRosenwasser commented on react/index.d.ts
>              render(): JSX.Element | null;
Looks like this should just be changed to `JSX.Element` if I'm not mistaken.

2017-01-27 16:32 UTC, yuit commented on react/index.d.ts
>              render(): JSX.Element | null;
Yep!

2017-01-30 21:08 UTC, DanielRosenwasser approved these changes

2017-01-30 22:11 UTC, merged

2017-01-30 22:11 UTC, DanielRosenwasser commented
Thank you Yui!

2017-01-31 04:02 UTC, JakeGinnivan commented
This causes a bunch of issues with anything which takes a `React.Element<any>` as an argument. For instance:

```
import { mount } from 'enzyme'
import MyComponent from './my-component'

mount(<MyComponent />) // Will not compile because null | Element is not assignable to React.Element<any>
```

This patch appears to completely break usage of JSX

2017-01-31 10:41 UTC, shiftkey commented
Seconding what @JakeGinnivan found. `@types/react@15.0.5` seems to have affected any uses of `renderIntoDocument`.

Rough repro:

```ts
import * as React from 'react'
import * as TestUtils from 'react-addons-test-utils'

class App extends React.Component<IAppProps, IAppState> {
   // ...
}

TestUtils.renderIntoDocument(<App />)   
```

Output:
```
error TS2345: Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any>'.
  Type 'null' is not assignable to type 'ReactElement<any>'.
```

2017-02-01 11:02 UTC, bbenezech commented
@DanielRosenwasser can you revert this PR? It basically broke all react setups.
@yuit I think `Test the change in your own code. (Compile and run.)` is actually the most important part.

2017-02-01 14:06 UTC, r00ger commented
enzyme's `shallow`, `mount` and `render` are broken
```ts
export function shallow<P, S>(node: ReactElement<P>, options?: ShallowRendererProps): ShallowWrapper<P, S>;
```
Obviously
```
Argument of type 'Element' is not assignable to parameter of type 'ReactElement<any>'.
  Type 'null' is not assignable to type 'ReactElement<any>'.
```

2017-02-01 19:50 UTC, vutran commented
I'm also experience these non-assignable warnings with my jest/react-test-renderer setups.

2017-02-03 03:48 UTC, levrik commented
I'm currently using `@types/react@15.0.4` with that piece of code to bypass the issue fixed by this PR without inventing the other problems:
```typescript
import * as React from 'react';

interface StatelessComponent<P> extends React.StatelessComponent<P> {
  (props: P & { children?: React.ReactNode }, context?: any): React.ReactElement<any> | null;
}

export default StatelessComponent;
```

2017-02-05 11:51 UTC, begincalendar commented
@yuit has made the changes.
@RyanCavanaugh has been requested to review this, but didn't get a chance to before it was merged.
@DanielRosenwasser has reviewed and merged this PR.

The React typing changes in this PR were brought about because of this [issue](https://github.com/Microsoft/TypeScript/issues/11566), with the specifics of the change coming from @RyanCavanaugh in this [comment](https://github.com/Microsoft/TypeScript/issues/11566#issuecomment-253306155).

Handling the return of `null` from class components was easily handled in this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/10611).

It appears as if handling the return of `null` from stateless function components is not as simple as @yuit thought it might be (given that the added test case did not prevent the regression).
@RyanCavanaugh you should be able to attest to this; that work is also required by TypeScript to make it happen.

Regardless, as this has been merged and people above have brought to light, it has caused lots of (seemingly unintended) breaking changes.

Given that work is required in this project and in TypeScript, how are we to proceed?

2017-02-07 01:04 UTC, DanielRosenwasser commented
Hi all, I apologize for the inconvenience this may have caused and the delay (DefinitelyTyped gets a lot of traffic and it's hard to keep track of messages). I've discussed this with @yuit and we're going to revert the PR.

2017-02-07 01:13 UTC, yuit commented
@JakeGinnivan @shiftkey @bbenezech @r00ger @vutran @cwmoo740 @levrik @begincalendar sorry for this inconvenience of this incorrect change. I have a PR that will revert the change for now (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14476)

2017-02-07 02:46 UTC, begincalendar commented
@DanielRosenwasser @yuit We're only human, mistakes will be made.

I just wanted this to get the attention it needed and lay out an explanation for everyone affected.

Thank you for the work you do.

2017-02-07 19:44 UTC, DanielRosenwasser commented
Update: We're looking into republishing - until that point, the last known good install for `@types/react` was 15.0.4.

2017-02-09 03:10 UTC, afc163 commented
Problem is resolved in `@types/react@15.0.8`, Thx! :handshake:

2017-04-28 07:42 UTC, tkrotoff commented
TypeScript 2.3 has been released and it should include all the needed fixes for this PR to be merged again