Added Notification methods to Service Worker API
DefinitelyTyped/DefinitelyTyped pull request #14287
Opened 2017-01-27 06:42 UTC by SteffenJahr

Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present. 
=> **My code doesn't raise any lint conditions but there were "errors" before that I can't fix: `void-return  Use the 'void' type for return types only. Otherwise, use 'undefined'.`**

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification and https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/getNotifications
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-01-27 07:55 UTC, SteffenJahr commented
@tristancaron Can you please review :) dt-bot seems not to work here :)

2017-01-30 18:22 UTC, DanielRosenwasser requested changes

2017-01-30 18:22 UTC, DanielRosenwasser commented on service_worker_api/index.d.ts
> +    data: any;
Should these all be optional?

2017-01-31 21:06 UTC, SteffenJahr commented on service_worker_api/index.d.ts
> +    data: any;
Thank you for your feedback. I have updated the PR.

2017-02-05 14:07 UTC, SteffenJahr commented on service_worker_api/index.d.ts
> +    data: any;
Can you please review again @DanielRosenwasser :)

2017-02-07 09:39 UTC, SteffenJahr commented
Can you please review again @DanielRosenwasser :) I have updated the ServiceWorkerNotificationOptions to make all properties optional.

2017-02-07 21:48 UTC, aozgaa commented on service_worker_api/index.d.ts
> +     * actions: An array of actions to display in the notification. The members of the array should be an object
Can you transfer the descriptions of the properties to their declarations in the `ServiceWorkerNotificationOptions` interface?

2017-02-07 21:49 UTC, aozgaa commented on service_worker_api/service_worker_api-tests.ts
> +    registration.showNotification('Notification Sample', <ServiceWorkerNotificationOptions>{
Since the properties are optional, do you need the type assertion?

2017-02-07 21:51 UTC, aozgaa commented on service_worker_api/index.d.ts
> +    dir?: string;
Can you make the type `'auto' | 'ltr' | 'rtl'`?

2017-02-10 21:26 UTC, SteffenJahr commented
@aozgaa Thank you for your feedback. I have updated the commit and also amended the options a little bit. I also updated the tests and removed the type assertion because you are right and I don't need it.

2017-02-17 20:56 UTC, zhengbli commented
@DanielRosenwasser further comments on this one?

2017-02-26 14:15 UTC, SteffenJahr commented
@zhengbli @DanielRosenwasser Any news here?

2017-03-01 22:15 UTC, merged