Update applicationInsights-js - v1.0.7
DefinitelyTyped/DefinitelyTyped pull request #14302
Opened 2017-01-27 17:55 UTC by kamilszostak

Please fill in this template.

- [ ] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-01-30 18:14 UTC, DanielRosenwasser requested changes

2017-01-30 18:14 UTC, DanielRosenwasser commented on applicationinsights-js/index.d.ts
> +// Type definitions for ApplicationInsights-JS v1.0.7
Can you restrict this to the MAJOR.MINOR version?

2017-01-30 18:14 UTC, DanielRosenwasser commented
Can you also add a `tslint.json` containing  `{ "extends": "../tslint.json" }` in the directory?

2017-02-07 22:14 UTC, aozgaa commented on applicationinsights-js/index.d.ts
> +         * @param id    unique id, this is used by the backend o correlate server requests. Use Util.newId() to generate a unique Id.
Can you align the descriptions in some way (either one space between param name and description or have all descriptions start at the same column)?

2017-02-14 00:07 UTC, KamilSzostak commented on applicationinsights-js/index.d.ts
> +         * @param id    unique id, this is used by the backend o correlate server requests. Use Util.newId() to generate a unique Id.
Fixed.

2017-02-17 21:02 UTC, zhengbli commented
@DanielRosenwasser @aozgaa pinging

2017-03-01 22:30 UTC, merged