pixijs v4.3 and pixi-spine updates
DefinitelyTyped/DefinitelyTyped pull request #14318
Opened 2017-01-28 17:58 UTC by ivanpopelyshev

Please fill in this template.

- [ x ] Make your PR against the `master` branch.
- [ x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x ] Test the change in your own code. (Compile and run.)
- [ x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ x ] Run `tsc` without errors.
- [ x ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ x ] Delete the package's directory.
- [ x ] Add it to `notNeededPackages.json`.

2017-01-29 23:26 UTC, clark-stevenson commented
👍 Awesome Ivan

2017-01-30 06:08 UTC, DanielRosenwasser requested changes
Can you also add a `tslint.json`?

2017-01-30 06:08 UTC, DanielRosenwasser commented on pixi.js/index.d.ts
> +// Type definitions for Pixi.js 4.3.4
Can you keep this at 4.3? We don't keep anything other than major & minor version numbers.

2017-01-30 09:20 UTC, ivanpopelyshev commented on pixi.js/index.d.ts
> +// Type definitions for Pixi.js 4.3.4
Yeah, no problem. People can use special compatibility plugin that adds new API to older versions of lib, so this definition will work even for any 4.x

2017-01-30 09:21 UTC, ivanpopelyshev commented
@DanielRosenwasser I didn't use tslint yet, and we don't have code conventions for pixi-typescript :(

2017-02-02 08:38 UTC, ivanpopelyshev commented
Thanks to that tslint it'll be merged later.

2017-02-05 02:24 UTC, clark-stevenson commented
@DanielRosenwasser

I can't give you a tslint right now.  There are problems, this is one of them.... but not really because the real problem is.

1. How do I generate d.ts from a JS codebase? I don't mean that in a silly way.  Is there any documentation systems which allow me to describe my intent?
2. I re-write the project in TypeScript and maintain that. 

Until one of those are done, this is, and always will be a hackjob, but it works, and it is either that or `any`.

2017-02-06 23:37 UTC, aozgaa commented
regarding tslint, see this for advice: https://github.com/DefinitelyTyped/DefinitelyTyped#lint

The `../tslint.json` is the tslint file in the root directory of the repo. It contains our default rules.

2017-02-07 08:26 UTC, clark-stevenson commented
I still can't see that `../tslint.json` and if `pixi-typescript` is going to pass linting, then I need the same rules as DT.

2017-02-07 21:40 UTC, aozgaa commented
If you have the repo cloned, and then running
```
npm install tslint typescript -g
tslint -c /path/to/tslint.json /path/to/DT/pixi.js/*.ts
```

should work. Are you running into issues there?

2017-02-07 21:51 UTC, ivanpopelyshev commented
@aozgaa I dont understand what are you doing :)

2017-02-22 11:56 UTC, GeorgeA93 commented
Any chance of an update on the status of this PR?

2017-02-24 09:25 UTC, ivanpopelyshev commented
1. we have to exclude "v3" folder from lint.
2. in index ```2867:26   variable-name   variable name clashes with keyword/type```

2017-02-24 09:31 UTC, clark-stevenson commented
That second one needs `"variable-name": false` as `isMobile.any` is a valid property of the library.

2017-02-24 09:51 UTC, ivanpopelyshev commented
All failed and no log. What's happening ?

2017-02-24 19:36 UTC, ivanpopelyshev commented
@DanielRosenwasser Quick! Merge it while its green!

2017-03-01 09:43 UTC, samalexander commented
@DanielRosenwasser  Please can we get this merged?

2017-03-01 09:53 UTC, ivanpopelyshev commented
/me preparing victory dance

2017-03-01 23:49 UTC, aozgaa commented
Please follow the schema for `tslint.json` files. You don't need any `jsRules` since there are not `*.js` files in the directory. I cloned your repo and this should work:
```
{
    "extends": [
        "../tslint.json"
    ],
    "rules": {
        "forbidden-types": false,
        "no-single-declare-module": false,
        "unified-signatures": false,
        "interface-name": [false],
        "max-line-length": [false]
    }
}
```

2017-03-01 23:52 UTC, aozgaa requested changes
Please follow the schema for `tslint.json` files. You don't need any `jsRules` since there are not `*.js` files in the directory. I cloned your repo and this should work:
```
{
    "extends": [
        "../tslint.json"
    ],
    "rules": {
        "forbidden-types": false,
        "no-single-declare-module": false,
        "unified-signatures": false,
        "interface-name": [false],
        "max-line-length": [false]
    }
}
```

2017-03-02 09:23 UTC, ivanpopelyshev commented
It doesn't work. I see a lot of errors from index and tests.

```
d:\pixi-games\DefinitelyTyped>npm run lint pixi.js

> definitely-typed@0.0.1 lint d:\pixi-games\DefinitelyTyped
> node scripts/lint.js "pixi.js"

node ../node_modules/tslint/lib/tslint-cli --format stylish "**/*.ts"
index.d.ts
1597:9    adjacent-overload-signatures  All 'from' signatures should be adjacent
1083:20   array-type                    Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.
...
```

2017-03-11 01:34 UTC, clark-stevenson commented
Can anyone help get this merged?

I just want to underline the situation in case it got lost.  We can mess around with this PR for another 5-6 weeks, but it don't resolve the underlying issue that this PR is coming from `pixi-typescript` and that no one can use the project because it is has been stuck here for weeks.

As soon as this PR is accepted, I am going to be taking the last few weeks of `pixi-typescript` updates and making a PR with pretty much all of the same problems all over again.  There is zero parity between this PR and that project.

If we can't merge this asap, then DT is not the answer, and I desperately need to know how to give the people who keep asking me a way to acquire the project.  I am quickly losing all hope and interest of maintaining pixi declarations which is tedious by itself, and this 5-6 week PR system blocking anyone from using it is destroying the purpose of even trying. 

Far too much Red Tape.

2017-03-11 01:43 UTC, mhegazy commented
sorry for the delay.

2017-03-11 01:43 UTC, merged

2017-03-11 01:54 UTC, clark-stevenson commented
@mhegazy not at all! Thank you very much for your time!