Update needle definitions to v1.4.3
DefinitelyTyped/DefinitelyTyped pull request #14317
Opened 2017-01-28 15:44 UTC by nikeee

This PR updates the definitions for needle to match the docs/source of v1.4.3. Since this is a new major version, the old definition was moved to the v0 folder.
Docs + Source: https://github.com/tomas/needle
npm package: https://www.npmjs.com/package/needle

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tomas/needle
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-01-30 18:18 UTC, DanielRosenwasser requested changes

2017-01-30 18:18 UTC, DanielRosenwasser commented on needle/index.d.ts
> +            delete(url: string, data: BodyData, options ?: NeedleOptions, callback ?: NeedleCallback): ReadableStream;
can you remove the space between the parameter name and the `?`

2017-01-30 18:19 UTC, DanielRosenwasser commented
@bigsan can you take a quick look/

2017-01-30 19:01 UTC, nikeee commented on needle/index.d.ts
> +            delete(url: string, data: BodyData, options ?: NeedleOptions, callback ?: NeedleCallback): ReadableStream;
Should be fixed in 16e6ab0

2017-02-04 02:42 UTC, bowdenk7 commented
No response from other authors for over 5 days. Merging.

2017-02-04 02:42 UTC, merged