Function 'pick' returns is documented to always return a value.
DefinitelyTyped/DefinitelyTyped pull request #14320
Opened 2017-01-28 19:12 UTC by aredfox

- See issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14319

Function 'pick' returns is documented to always return a value. Before it's return type was :void, I'm sending this proposal as :any would fix this issue.
Reference to dot-object documentation: https://github.com/rhalff/dot-object#pickremove-a-value-using-dot-notation

Please fill in this template.

- [ ] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-01-28 19:16 UTC, aredfox commented
URL to documentation & info: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14319

2017-01-28 19:16 UTC, aredfox commented
cc @rhalff - author of [dot-object](https://github.com/rhalff/dot-object)

2017-01-28 19:19 UTC, aredfox commented on dot-object/index.d.ts
> +        pick(path: string, obj: any, remove?: boolean): any;
- tested this in my production code, and TypeScript was now happy.
- did this according to my experience with using the function and the documentation as described in https://github.com/rhalff/dot-object#pickremove-a-value-using-dot-notation

2017-01-28 19:21 UTC, aredfox commented on dot-object/index.d.ts
> +// Type definitions for Dot-Object v1.4.3
- Bumped the version number, as asked in the checklist/guidelines

2017-01-28 19:43 UTC, rhalff commented on dot-object/index.d.ts
> +        pick(path: string, obj: any, remove?: boolean): any;
The return type is definitely `any`.

2017-01-28 19:53 UTC, aredfox commented on dot-object/index.d.ts
> +        pick(path: string, obj: any, remove?: boolean): any;
thanks for the quick feedback @rhalff

2017-01-29 05:15 UTC, DanielRosenwasser requested changes

2017-01-29 05:15 UTC, DanielRosenwasser commented on dot-object/index.d.ts
> +// Type definitions for Dot-Object v1.4.3
We only use MAJOR.MINOR for version numbers. Can you strip the last portion off?

2017-01-29 08:26 UTC, aredfox commented on dot-object/index.d.ts
> +// Type definitions for Dot-Object v1.4.3
Ok, will make it 1.5 then I guess?

2017-01-29 08:29 UTC, aredfox commented on dot-object/index.d.ts
> +// Type definitions for Dot-Object v1.5
@DanielRosenwasser bumped it now straight to v1.5
thanks

2017-01-29 22:19 UTC, aredfox commented
is there a way I can work around this (in stead of editing the `index.d.ts` file every time I do an `npm i` on any machines where I and my fellow people work on) - until @nkovacic reviewed and/or accepted this?

2017-02-01 02:49 UTC, aredfox commented
A politely ping/bump to @DanielRosenwasser and @nkovacic to futher review/merge the PR when appropriate?

2017-02-01 08:15 UTC, merged

2017-02-01 08:17 UTC, DanielRosenwasser commented
Thanks! Sorry for the delay!

To answer your question: right now you can take the `.d.ts` file and add it to a folder in your project. Then use path mappings (i.e. the `paths` field in your `tsconfig.json`) so that whenever someone imports a path like `"foo"`, it always points to the appropriate `.d.ts` file

There's an extremely technical document about path mappings here: https://github.com/Microsoft/TypeScript/issues/5039

2017-02-02 07:37 UTC, aredfox commented
Thanks @DanielRosenwasser - no prob on the delay, I know we all have a job (or multiple) and this is all voluntary work. Thanks for introducting me to the path mappings as well!