Fix various typings and issues with gsap and greensock
DefinitelyTyped/DefinitelyTyped pull request #14332
Opened 2017-01-30 02:17 UTC by ProbablePrime

I found a number of discrepancies and issues when trying to use the gsap(https://greensock.com/) node module with TypeScript.

- The typings for `gsap` appeared to be incomplete and only supplied `TweenLite`
- There were duplicate typings in `greensock` this is [not an npm module](https://www.npmjs.com/package/greensock) and I therefore consider it to be a completely invalid folder. However its typings were better than `gsap`

To fix this i've merged `gsap` with `greensock` and added comments as appropriate. I then setup gsap to be exported in a similar pattern to [rx](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/rx/index.d.ts)

This should also address: #14193 , #13400, #11265

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://greensock.com/docs/#/HTML5/All
- [ ] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-01-30 02:26 UTC, ProbablePrime commented
Regarding the build failure, any advice on typing these?: https://greensock.com/docs/#/HTML5/All/Power0/

They're aliases for naming reasons.

2017-01-30 06:00 UTC, DanielRosenwasser requested changes

2017-01-30 06:00 UTC, DanielRosenwasser commented on gsap/Ease.d.ts
> +    };
Remove the semicolon to get rid of the build failure

2017-01-30 12:06 UTC, ProbablePrime commented on gsap/Ease.d.ts
> +    };
Good catch thanks!

2017-01-30 18:03 UTC, DanielRosenwasser approved these changes

2017-01-30 18:05 UTC, DanielRosenwasser requested changes

2017-01-30 18:05 UTC, DanielRosenwasser commented on gsap/Animation.d.ts
> +        totalTime(time: number, suppressEvents?: boolean): Animation;
Can you collapse each of these into one overload with optional arguments?

2017-01-30 18:06 UTC, DanielRosenwasser commented
@vilic @codebelt care to look things over?

2017-01-31 00:45 UTC, ProbablePrime commented on gsap/Animation.d.ts
> +        totalTime(time: number, suppressEvents?: boolean): Animation;
@DanielRosenwasser Unless i'm misunderstanding that alters the return type into a manner that i find un-intuitive.
`totalTime(time?: number, suppressEvents?: boolean): Animation | boolean;` 

Just looks confusing. Is this what you meant?

2017-02-04 03:08 UTC, bowdenk7 commented on gsap/Animation.d.ts
> +        totalTime(time: number, suppressEvents?: boolean): Animation;
@DanielRosenwasser ping

2017-03-06 19:07 UTC, minestarks commented on gsap/Animation.d.ts
> +        totalTime(time: number, suppressEvents?: boolean): Animation;
@DanielRosenwasser this looks fine to me as is. Will merge unless you object.

2017-03-09 19:36 UTC, merged