Add generic types for results and collections
DefinitelyTyped/DefinitelyTyped pull request #14340
Opened 2017-01-30 17:19 UTC by rodrigopivi

Now if you declare a variable like:
```js
const ob = DB.objects<IUserContext>("UserContext").sorted("token", true);
```

You can expect that ob's type is the type intersection of `IUserContext & Realm.Object`

2017-01-30 17:58 UTC, DanielRosenwasser submitted a review, later dismissed

2017-01-30 17:58 UTC, DanielRosenwasser commented on realm/index.d.ts
> +        filtered(query: string, ...arg: any[]): Results<T & Object>;
`T & Object` doesn't actually do anything. The apparent type of `T` is `{}` which is effectively the same as `Object` - in short, you get all the same members of `Object` anyway. Furthermore, `number` and `string` are assignable to `Object` and `{}`, so it doesn't do a ton for you.

I think what you really want to do is constrain `T` to be of only an object type, which TypeScript 2.2 will have. [See here](https://github.com/Microsoft/TypeScript/issues/1809)

Until then, I think you'll just have to roll with `T`.

2017-01-30 18:00 UTC, DanielRosenwasser commented on realm/index.d.ts
> +        filtered(query: string, ...arg: any[]): Results<T & Object>;
Ignore the above - I just realized you were referring to `Realm.Object`. Can you please make that explicit?

2017-01-30 18:02 UTC, DanielRosenwasser commented
Can you update the version number at the top of the file? Keep it as the MAJOR.MINOR version (and remove anything else following that)

Can you also add a `tslint.json` file that contains the following line?

```json
{ "extends": "../tslint.json" }
```

@Akim95 can you review this?

2017-01-30 19:12 UTC, rodrigopivi commented on realm/index.d.ts
> +        filtered(query: string, ...arg: any[]): Results<T & Object>;
Thanks for the review. Done, updated to make explicit.

2017-01-30 19:25 UTC, rodrigopivi commented
@DanielRosenwasser Thanks for the review, done.

2017-01-30 20:14 UTC, Akim95 commented on realm/index.d.ts
> +// Type definitions for realm-js 0.14.4
Just change to realm-js 0.14

2017-01-30 20:39 UTC, Akim95 requested changes
Please update version to realm-js 0.14

2017-01-30 20:39 UTC, Akim95 commented on realm/index.d.ts
> +// Type definitions for realm-js 1.0
Please update version to realm-js 0.14

2017-01-30 20:43 UTC, DanielRosenwasser requested changes

2017-01-30 20:43 UTC, DanielRosenwasser commented on realm/index.d.ts
> +        slice(start?: number, end?: number): Array<T>;
The linter is complaining about this being `Array<T>` instead of `T[]`.

2017-01-30 20:43 UTC, DanielRosenwasser commented on realm/index.d.ts
> +        find(callback: (object: any, index?: any, collection?: any) => void, thisArg?: any): (T) | void;
Just `T | null | undefined`

2017-01-30 20:43 UTC, DanielRosenwasser commented on realm/index.d.ts
> +        pop(): (T) | void;
`T | null | undefined`

2017-01-30 20:43 UTC, DanielRosenwasser commented on realm/index.d.ts
> +        shift(): (T) | void;
`T | null | undefined`

2017-01-30 20:45 UTC, Akim95 commented on realm/index.d.ts
> +        slice(start?: number, end?: number): Array<T>;
Could you update to 'T[]' instead. and at line 252.

2017-01-30 20:49 UTC, Akim95 requested changes

2017-01-30 20:49 UTC, Akim95 commented on realm/index.d.ts
> +        slice(start?: number, end?: number): Array<T>;
Could you update to 'T[]'. and at line 252.

2017-01-30 21:42 UTC, rodrigopivi commented
@DanielRosenwasser @Akim95 Thanks for the review, updated.

2017-02-01 14:28 UTC, rodrigopivi commented
hey @DanielRosenwasser @Akim95 sorry to nag, but is there any chance of this PR getting merge soon? please let me know if you need any further change. thanks!

2017-02-01 21:18 UTC, Akim95 commented
Tested and anything works fine for me. You should wait maintainer to merge this PR or otherwise.

2017-02-04 02:44 UTC, merged