allow void return on es6-promise.all
DefinitelyTyped/DefinitelyTyped pull request #14361
Opened 2017-01-31 18:17 UTC by giuseppelt

Allows this scenario:
```javascript
function F() : Promise<void> {
    return Promise.all<void>([p1, p2, p3]);
}
```
actually the return type is void[] or T[] (inferred from p1..n), hence you have to write:
```javascript
function F() : Promise<void> {
    return <Promise<void>>Promise.all([p1, p2, p3]);
}
```

In the definition I used `values: any[]` with any instead of `(any | Thenable<any>)[]` because _any_ swallows - of course - any other type.

2017-01-31 20:58 UTC, DanielRosenwasser requested changes

2017-01-31 20:58 UTC, DanielRosenwasser commented on es6-promise/index.d.ts
> +	function all<T extends void>(values: any[]): Promise<void>;
First off, switch back to spaces.

Second, this doesn't do what you think it does - what you probably mean to do. I think you want is

```ts
function all(values: Thenable<void>[]): Promise<void>;
function all<T>(values: (T | Thenable<T>)[]): Promise<T[]>;
```

Maybe @rbuckton has some feedback here as well.

2017-01-31 23:01 UTC, DanielRosenwasser submitted a review, later dismissed

2017-01-31 23:01 UTC, DanielRosenwasser commented on es6-promise/index.d.ts
> +    function all<T extends void>(values: any[]): Promise<void>;
`T` is never used in the rest of the type, so it's pointless to make this generic.

2017-01-31 23:01 UTC, DanielRosenwasser commented on es6-promise/index.d.ts
> +    function all<T extends Object>(values: (T | Thenable<T>)[]): Promise<T[]>;
`T extends `Object` is a useless constraint because constraints are implicitly `{}` (and `Object` is arguably worse than `{}` anyway).

2017-01-31 23:02 UTC, DanielRosenwasser commented
I would suggest you use the overloads I wrote out earlier.

2017-01-31 23:18 UTC, giuseppelt commented
This patch is quite subtle, you have to consider all cases involved.

Your definition simply covers the basic scenario: all arguments as `Thenable<void>`.

Mine covers void return in all scenarios:
- All void Thenable
- Mixed-type Thenable
- Mixed Not-Thenable and Thenable

All scenarios are valid JS usage and with current typings they can't be written in TS without external assertions.
This patch allows all cases as JS and Promise-semantic permits.

Let consider this all-in example:
```javascript
function F(): Promise<void> {
   return Promise.all([
       thenableNumber() // Thenable<number>
       thenableVoid() //Thenable<void>
       asyncObject() // Thenable<object>
       asyncCachedObject() // object | Thenable<object>
       iDontKnow() //any
   ]);
}
```
Your overload does not catches this.
With mine:
- if you leave the func as is, you get the actual inference `Promise<[T1,...]>`
- if you want `void`, simply use `Promise.all<void>([...])`

To make it, I put the _void_ case with low priority (last declaration) with the constraint `T extends void`, to allow only void type.
In order to keep existing inference in place, I have to exclude the _void_ from the upper declarations, otherwise `Promise.all<T>(values:(T|Thenable<T>)[]): T[]` catches the _void_ and you get `void[]` as return type.
To exclude _void_, the constraint `T extends Object` does the trick.

And you get all cases covered, with the exact same semantic if written in JS.

2017-02-10 00:45 UTC, aozgaa commented
Pinging @rbuckton for a more knowledgeable response.

2017-03-06 20:15 UTC, minestarks commented
@giuseppelt Please provide tests that demonstrate why the change is needed (i.e. a test that would fail today but would be fixed with your change), since as you said the change is quite subtle. Thank you!

2017-03-20 23:26 UTC, paulvanbrenk commented
Going to close this, since there has been no activity for a while and we do need the test cases.

2017-03-20 23:26 UTC, closed without merging