Adding new features for XRM v8.2
DefinitelyTyped/DefinitelyTyped pull request #14460
Opened 2017-02-06 07:25 UTC by clownwilleatme

There is a breaking change with the Control interface which may not be desirable. However, it seems to be required as Microsoft has changed things quite a bit with the latest XRM release (e.g. the introduction of the QuickForm control which does not support many of the methods that most other controls do).

## Adding new features for XRM v8.2
1. **Xrm.Page.ui**
   * Adding quickForms collection
   * Adding Xrm.Page.ui.QuickForm (https://msdn.microsoft.com/en-us/library/mt736908.aspx)
2. **Xrm.Async & XrmPromise**
   * Modifying the Async definitions to allow methods to return specific success or error callback delegates.
   * This is required because of new methods which return promises using callback delegates with different parameters (e.g. Xrm.Utility.openQuickCreate and Xrm.Mobile.offline methods)
3. **Xrm.Utility**
   * Modifying the Xrm.Utility.openQuickCreate method and related asynchronous promise methods (https://msdn.microsoft.com/en-us/library/jj602956.aspx#BKMK_openQuickCreate)
4. **Xrm.Page.data**
   * Adding Xrm.Page.data.save method with saveOptions (https://msdn.microsoft.com/en-us/library/dn481607.aspx#Anchor_2)
5. **Controls**
   * Moved methods from the Control interface into the StandardControl interface. This will be a breaking change, but is req

Please fill in this template.

- [ ] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-02-06 13:25 UTC, daryllabar commented
As much as I applaud @clownwilleatme for the documentation of what change, Github is showing every single line as being changed, and as such I'm not willing to review this change.

2017-02-06 19:39 UTC, aozgaa commented
Perhaps it is a CRLF issue? Please make the diff more readable.

2017-02-06 23:44 UTC, clownwilleatme commented
Sorry, should be fixed now, I should have checking properly first.

2017-02-07 02:07 UTC, daryllabar commented on xrm/index.d.ts
> +        Mobile: {
I'm guessing this should be an interface, not just a field.

2017-02-07 02:08 UTC, clownwilleatme commented on xrm/index.d.ts
> +        Mobile: {
Sure, I'll make that change. Any thoughts on the changes to the Control interface?

2017-02-07 02:10 UTC, daryllabar commented on xrm/index.d.ts
> +        setFormNotification( message: string, level: Page.ui.FormNotificationLevel | string, uniqueId: string ): boolean;
Thinking we should remove the union type string   ERROR, WARNING and INFO are the only options.

2017-02-07 02:14 UTC, daryllabar commented on xrm/index.d.ts
> +            setRequiredLevel( requirementLevel: RequirementLevel | string ): void;
Again, thinking we should remove the string union type.

2017-02-07 02:16 UTC, clownwilleatme commented on xrm/index.d.ts
> +            setRequiredLevel( requirementLevel: RequirementLevel | string ): void;
Agreed, same for `setSubmitMode( submitMode: SubmitMode | string ): void;`

2017-02-07 02:26 UTC, daryllabar requested changes
There are a lot of different changes here...  Submitting smaller pull requests would be helpful for future issues.

Only request I have is for the mobile/offline fields to be defined as an interface so just that section can be mocked, if so desired.

2017-02-07 02:26 UTC, daryllabar commented on xrm/index.d.ts
> +        Mobile: {
This should be an interface, not just a field.

2017-02-07 02:26 UTC, daryllabar commented on xrm/index.d.ts
> +        setFormNotification( message: string, level: Page.ui.FormNotificationLevel | string, uniqueId: string ): boolean;
Thinking we should remove the union type string since ERROR, WARNING and INFO are the only options.

2017-02-07 02:26 UTC, daryllabar commented on xrm/index.d.ts
> +            setRequiredLevel( requirementLevel: RequirementLevel | string ): void;
Again, thinking we should remove the string union type.

2017-02-07 02:26 UTC, daryllabar commented on xrm/index.d.ts
> +            getControlType(): ControlType | string;
Same here.  I know it is a breaking change, but it would be better to force the correct value imho

2017-02-07 02:26 UTC, daryllabar commented on xrm/index.d.ts
> +            offline: {
Interface here to as well

2017-02-07 02:27 UTC, daryllabar commented on xrm/index.d.ts
> +            setRequiredLevel( requirementLevel: RequirementLevel | string ): void;
yep

2017-02-07 02:27 UTC, daryllabar commented on xrm/index.d.ts
> +        Mobile: {
You mean how you've split them into smaller interfaces?

2017-02-07 02:31 UTC, clownwilleatme commented on xrm/index.d.ts
> +            getControlType(): ControlType | string;
This one needs to be a union type because it can return dynamic control names.

2017-02-07 02:33 UTC, daryllabar commented on xrm/index.d.ts
> +            getControlType(): ControlType | string;
Ah yah.

2017-02-07 03:35 UTC, clownwilleatme commented
I have made the changes. However, removing the string union types has caused an error for one of the tests.

`let requirementLevelString = "none";
attribute.setRequiredLevel(requirementLevelString); // This fails
attribute.setRequiredLevel("none"); // This works`

Do you still think removing the string unions is worth it?

2017-02-07 22:14 UTC, clownwilleatme commented
@daryllabar I have made the changes requested, but there's still a question about having string unions for various methods. Having to define strings as consts to pass to methods like setRequiredMode does remove a bit of flexibility, IMO.

2017-02-07 23:54 UTC, daryllabar commented
You're not having to define them as constants, just cast them as that union type or any.  They will only affect someone that is using a variable to pass to the method, which I would guess would only be in a shared function, so it should be a pretty minimal breaking change.

But I'm definitely not going to require it.  If you don't agree with it, don't do it.

2017-02-08 00:00 UTC, clownwilleatme commented
Yeah, you're right - it's a pretty small change and declaring as the union type more or less negates the issue. Are you happy with everything else?

What's the next step for getting this PR approved?

2017-02-08 00:19 UTC, aozgaa commented on xrm/index.d.ts
> +          * @param   {string}                            message     The text of the notification message.
You don't need the types in jsdoc comments if you are declaring them below.

2017-02-08 00:21 UTC, daryllabar commented
Looks good to me.  I Thumbed up the review which I believe means someone will get around to merging the PR eventually.

2017-02-08 00:21 UTC, aozgaa commented on xrm/index.d.ts
> +          *           Only the following attribute types are supported in offline mode: BigInt
Can you start the list on a separate line so it doesn't need to be indented so much?

2017-02-08 00:21 UTC, clownwilleatme commented on xrm/index.d.ts
> +          * @param   {string}                            message     The text of the notification message.
I was just following the existing format that has been used for most of the other methods. Happy to remove them though.

2017-02-08 00:22 UTC, aozgaa commented on xrm/index.d.ts
> +          *           Only the following attribute types are supported in offline mode: BigInt
ditto

2017-02-08 00:25 UTC, aozgaa commented on xrm/index.d.ts
> +          *           Only the following attribute types are supported in offline mode: BigInt
Seeing as this remark is copied so much, I wonder if there might be some way to de-duplicate it.

2017-02-08 00:26 UTC, daryllabar commented on xrm/index.d.ts
> +          *           Only the following attribute types are supported in offline mode: BigInt
I'm not aware of any way to share comments....

2017-02-08 00:27 UTC, aozgaa commented
Can you add a `tslint.json` to make the formatting consistent?

2017-02-08 00:28 UTC, clownwilleatme commented on xrm/index.d.ts
> +          *           Only the following attribute types are supported in offline mode: BigInt
I tried to think of a way to do that but came up blank. Maybe putting them in a few lines instead of one per line will make it a bit easier to read?

2017-02-08 01:31 UTC, clownwilleatme commented
@aozgaa I have added a tslint file with rules that fit the existing formatting. I have updated the various files to correct minor formatting errors.

For the Xrm.Mobile.offline methods with the big lists of supported data types, I have reformatted them so that they take up much less space. Does it look good to you?

2017-02-08 20:59 UTC, aozgaa commented
Can you use a `tslint.json` that follows the general repo rules? ie:
```
{
    "extends": "../tslint.json",
    "rules": {
        // Special rules you *really* need
    }
}
```

2017-02-08 23:44 UTC, aozgaa commented
Actually let's just do it in a separate PR since this looks functionally correct.

2017-02-08 23:44 UTC, merged