[body-parser] update to v1.16
DefinitelyTyped/DefinitelyTyped pull request #14493
Opened 2017-02-07 15:29 UTC by tlaziuk

- [ ] Make your PR against the `master` branch.
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/expressjs/body-parser/tree/1.16.0#body-parser>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-02-09 19:36 UTC, aozgaa commented
Thoughts @santialbo, @vilic, @dreampulse, @tlaziuk ?

2017-02-11 00:05 UTC, tlaziuk commented
@aozgaa @santialbo @vilic @dreampulse
please take a look at the test file, is it a bug?

    body-parser-tests.ts(11,9): error TS2339: Property 'use' does not exist on type 'typeof e'.
    body-parser-tests.ts(12,9): error TS2339: Property 'use' does not exist on type 'typeof e'.
    body-parser-tests.ts(13,9): error TS2339: Property 'use' does not exist on type 'typeof e'.
    body-parser-tests.ts(14,9): error TS2339: Property 'use' does not exist on type 'typeof e'.
    body-parser-tests.ts(14,13): error TS2346: Supplied parameters do not match any signature of call target.
    body-parser-tests.ts(17,9): error TS2339: Property 'all' does not exist on type 'typeof e'.
    body-parser-tests.ts(17,19): error TS7006: Parameter 'req' implicitly has an 'any' type.
    body-parser-tests.ts(17,24): error TS7006: Parameter 'res' implicitly has an 'any' type.
    body-parser-tests.ts(17,29): error TS7006: Parameter 'next' implicitly has an 'any' type.
    body-parser-tests.ts(22,9): error TS2339: Property 'listen' does not exist on type 'typeof e'.

2017-03-06 22:11 UTC, minestarks requested changes

2017-03-06 22:11 UTC, minestarks commented on body-parser/body-parser-tests.ts
> +express.use(raw());
You're initializing the variable ```app``` but not actually using it. ```express``` is the constructor, not the instance, which is why you're getting errors.

2017-03-06 22:11 UTC, minestarks commented
@tlaziuk Please fix the failing tests before I can merge. Thank you.

2017-03-07 07:18 UTC, tlaziuk commented on body-parser/body-parser-tests.ts
> +express.use(raw());
thanks, I didn't notice that before! 👍

2017-03-08 21:27 UTC, minestarks approved these changes

2017-03-08 21:27 UTC, merged

2017-05-24 11:48 UTC, jcristovao commented
Hello,

I'm sorry, but this PR introduced a typo: [reviever](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14493/files#diff-69c3b5d3084ae119dda4ece757760d85R25) instead of [reviver](https://github.com/expressjs/body-parser/blob/master/lib/types/json.js#L57).

@tlaziuk , do you think you can quickly fix this? Thanks