Re-add deleted overloads and fix namespace / extends mess.
DefinitelyTyped/DefinitelyTyped pull request #14509
Opened 2017-02-08 13:21 UTC by NightkingCH

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/16e5b26b3da67b6f1f693af4666db65c10596dbe
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-02-09 09:35 UTC, NightkingCH commented
Don't want to rush, but would be great to get feedback or to see this merged. We face troubles in all our projects and it would be nice to see that fixed. Don't like to cast everything to "any" :/.

2017-02-09 15:00 UTC, alejo90 requested changes
Thanks for your contribution. The `Icon` changes, however, do not reflect the way the library is written. Please remove the extra spaces that were added all over the place in the `{}`.

2017-02-09 15:00 UTC, alejo90 commented on leaflet/index.d.ts
> +        constructor(coords: LatLngTuple | [number, number, number] | LatLngLiteral | { lat: number, lng: number, alt?: number });
Cam you remove all of these extra spaces, please.

2017-02-09 15:00 UTC, alejo90 commented on leaflet/index.d.ts
> +        bindPopup(content: string | HTMLElement | Popup | ((layer: Layer) => Content), options?: PopupOptions): this;
`Content` is an alias for `string | HTMLElement`, the previous definition just requires an extra set of parentheses around the function: `((layer: Layer) => Content) | Content | Popup`

2017-02-09 15:00 UTC, alejo90 commented on leaflet/index.d.ts
> +    export interface IconOptions extends LayerOptions {
Please remove this interface, it's defined just above.

2017-02-09 15:00 UTC, alejo90 commented on leaflet/index.d.ts
> +        static Default: IconDefaultSettings;
Except for the `InternalIcon` class (that is an artifact from when I first wrote the definitions using interfaces), the old way is correct. `Default` is not an instance, but another class and that is the reason way it was defined inside a namespace. You can verify that in the source code and in the documentation. Please revert. You are welcome to remove the `InternalIcon` class, as it is not needed anymore and it doesn't exist anyways.

2017-02-09 15:00 UTC, alejo90 commented on leaflet/leaflet-tests.ts
> +L.Icon.Default.imagePath = "/any/valid/uri/or/path";
From the documentation:

> In order to customize the default icon, just change the properties of L.Icon.Default.prototype.options (which is a set of Icon options).

As I said, `Default` is another class, not an instance.

2017-02-15 15:20 UTC, alejo90 commented
👎 no response from author, so... I'll be submitting a fix for this and other issues this week.

2017-03-07 01:56 UTC, minestarks commented
Looks like this now conflicts with another version of the fix already checked in. I'll close this PR. Please submit a new PR for additional changes. Thank you.

2017-03-07 01:56 UTC, closed without merging