Knex: Add tslint.json and fix issues, Fix dropTableIfExists to be chainable
DefinitelyTyped/DefinitelyTyped pull request #14571
Opened 2017-02-11 22:43 UTC by Nospamas

Please fill in this template.

- [√] Make your PR against the `master` branch.
- [√] Use a meaningful title for the pull request. Include the name of the package modified.
- [√] Test the change in your own code. (Compile and run.)
- [√] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [√] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [√] Run `tsc` without errors.
- [√] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [√] Provide a URL to documentation or source code which provides context for the suggested changes: http://knexjs.org/#Schema-dropTableIfExists
- [√] Increase the version number in the header if appropriate. **Added Version**
- [√] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-02-22 07:16 UTC, tkqubo commented
:+1:

2017-02-22 07:16 UTC, tkqubo commented
As commented in the code, later `on` could be extracted in some way :-)

2017-03-08 04:59 UTC, minestarks requested changes

2017-03-08 04:59 UTC, minestarks commented on knex/index.d.ts
> +        // no way to specifiy this siganiture in the current typescript version
What do you mean by this comment?

2017-03-08 05:06 UTC, Nospamas commented on knex/index.d.ts
> +        // no way to specifiy this siganiture in the current typescript version
the comment is a note above:

// (...callbacks: Function[], wrap?: boolean): QueryInterface;

Which allows the specification of an arbitrary number of callbacks followed by an optional parameter to wrap them. Both spread operator arguments and optional arguments must be specified last, which as far as I know is not possible with typescript.

Docs for this function http://knexjs.org/#Builder-union

2017-03-08 09:43 UTC, minestarks requested changes

2017-03-08 09:43 UTC, minestarks commented on knex/index.d.ts
> +        // no way to specifiy this siganiture in the current typescript version
Got it, thanks. Could you fix the typos in the comment and clarify that it refers to the  line below?

2017-03-08 09:43 UTC, minestarks commented on knex/index.d.ts
>      transaction: <R>(transactionScope: ((trx: Knex.Transaction) => void)) => Promise<any>;
This isn't your change, but it caught my attention -- this ```<R>``` is unnecessary and can be removed.

2017-03-08 21:32 UTC, Nospamas commented on knex/index.d.ts
> +        // no way to specifiy this siganiture in the current typescript version
Sure thing!

2017-03-08 21:53 UTC, Nospamas commented
Clarified comment (if the wording was questionable to you it will be to others) and removed the unnecessary generic type.

2017-03-08 21:56 UTC, minestarks approved these changes

2017-03-08 21:57 UTC, minestarks commented
@Nospamas thank you! Looks like you got some linter errors in tests. Once those are clean I'll merge.

2017-03-09 05:04 UTC, Nospamas commented
Lint of tests updated. Looks like the default lint task doesn't hit non d.ts files when this repo was forked :)

2017-03-11 00:34 UTC, mhegazy commented
looks like this needs a rebase from master.

2017-03-16 03:55 UTC, Nospamas commented
I'm not hugely familiar with the rebase process and the history combined with the merge on the branch seems to be making it tough.

Any advice on this? Am I better off just re-making the repo given the age of this issue and when I originally forked it?

2017-03-20 23:45 UTC, paulvanbrenk commented
I agree remaking the fix on a clean copy seems to right way forward here.

2017-03-20 23:45 UTC, closed without merging