The modularized typings definitions for iscroll package
DefinitelyTyped/DefinitelyTyped pull request #14591
Opened 2017-02-13 09:02 UTC by acrazing

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <http://iscrolljs.com/>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-02-13 13:40 UTC, acrazing commented
The travis-ci error is generated by `types-publisher`, I created a PR to fix it: <https://github.com/Microsoft/types-publisher/pull/296>

2017-02-13 15:33 UTC, andy-ms commented
Why did you delete `v4`?

2017-02-14 03:00 UTC, acrazing commented
@andy-ms 

If user need to use `v4`, just use `yarn add "@types/iscroll@4.2.29"` to invoke it. This version does not support `v4` because there is no document.

The old version use global export, it's useless. <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14591/files#diff-20f2a108c9f72059c3f607f091a732d1L35>

And too much code error, for example: <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14591/files#diff-20f2a108c9f72059c3f607f091a732d1L38>

So I removed it.

2017-03-06 23:23 UTC, minestarks commented
@acrazing Are the tests supposed to be fixed? Could you re-run the checks before I can merge? Thanks.

2017-03-09 20:35 UTC, minestarks requested changes

2017-03-09 20:35 UTC, minestarks commented on iscroll/tslint.json
> +    "interface-name": false
Why was it necessary to disable this rule?

2017-03-09 20:35 UTC, minestarks commented on iscroll/tsconfig.json
> +    "strictNullChecks": false,
Please turn ```strictNullChecks``` on

2017-03-09 20:35 UTC, minestarks commented on iscroll/v4/index.d.ts
> -// Type definitions for iScroll 4.2
It's valid to leave v4 in. This way it can receive bugfixes. Consider un-deleting please.

2017-03-10 02:34 UTC, closed without merging