[lodash] Add uniqWith to array wrappers interfaces
DefinitelyTyped/DefinitelyTyped pull request #14642
Opened 2017-02-15 12:35 UTC by ivanvoznyakovsky

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://lodash.com/docs/4.17.4#uniqWith

2017-02-15 13:55 UTC, zuzusik commented on lodash/lodash-tests.ts
> +        result = _('abc').chain().uniqWith<string[]>(comparator);
I believe tests shouldn't enforce typings (< type > enforces typing, not specifies it, look [at this example ](http://www.typescriptlang.org/play/#src=type%20TMyType%20%3D%20%7B%20b%3A%20string%20%7D%3B%0Afunction%20test(t%3A%20TMyType)%20%7B%20%7D%3B%0Aconst%20a%20%3D%20(%3CTMyType%3E%20%7B%7D)%3B%0Aconst%20b%20%3D%20%7B%7D%0Atest(a)%3B%0Atest(b)%3B%0A))

2017-03-07 01:53 UTC, minestarks commented on lodash/lodash-tests.ts
> +        result = _('abc').chain().uniqWith<string[]>(comparator);
I believe you're referring to type assertions, but these are [type arguments](https://www.typescriptlang.org/docs/handbook/generics.html).

2017-03-07 01:54 UTC, minestarks commented
@ivanvoznyakovsky Could you please fix the failing test before I can merge? Thank you.

2017-03-07 06:16 UTC, zuzusik commented on lodash/lodash-tests.ts
> +        result = _('abc').chain().uniqWith<string[]>(comparator);
This is type arguments but we enforce it. 

Ideally TS bases on Typings should be able to understand true that the result of `_(<string>).chain().uniqWith(comparator)` is `_.LoDashImplicitArrayWrapper<string[]>` 

Is TS typings system capable of handling such cases? If it is then probably it is required to improve typings of `chain` or `_`.

2017-03-07 10:33 UTC, ivanvoznyakovsky commented
@minestarks not sure I see how my changes are failing tests.

> Error in lodash.meanby
Must specify "lib", usually to `"lib": ["es6"]` or `"lib": ["es6", "dom"]`.

2017-03-07 10:42 UTC, zuzusik commented
Maybe you just need to rebase over the latest master?

On 7 Mar 2017 12:33, "Ivan Voznyakovsky" <notifications@github.com> wrote:

> @minestarks <https://github.com/minestarks> not sure I see how my changes
> are failing tests.
>
> Error in lodash.meanby
> Must specify "lib", usually to "lib": ["es6"] or "lib": ["es6", "dom"].
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14642#issuecomment-284683780>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AECXeGneWXj1Ch3JeVrJkXsuzK1KN3Jtks5rjTJwgaJpZM4MBqap>
> .
>

2017-03-07 11:49 UTC, ivanvoznyakovsky commented
yeah. that could be the reason. but after rebase it's still the same error.

2017-03-07 23:37 UTC, minestarks requested changes

2017-03-20 23:58 UTC, paulvanbrenk commented
Closing this, please re-open when you've resolved the open issues.

2017-03-20 23:58 UTC, closed without merging