lodash - change weakmap declaration to work with TS 2.2
DefinitelyTyped/DefinitelyTyped pull request #14662
Opened 2017-02-16 01:01 UTC by budiadiono

In TS 2.2 WeakMap interface for ES6 has been changed from WeakMap<K, V> to WeakMap<K extends object, V>. This changes makes @types/lodash not working with new ES6 introduced in TS2.2.

To keep the backward compatibility with ES5, I think it is safe to rename the WeakMap declaration.

I know TS 2.2 is still in RC version now, but many people using it, including me :). So if you think this is too early and also bad idea then feel free to close this PR without merging it.

If this get merged then it's should close #14324.

This pull request is clean version of pull request #14502

2017-02-16 03:25 UTC, TonyPythoneer commented
I appreciate your idea but it's too early. It's because TypeScript hasn't released stable 2.2 version yet.
I hope this proposal can be an issue and make up a TODO list. It doesn't make you work in vain.

2017-02-22 18:50 UTC, corbinu commented
Can this be merged now that 2.2 is stable?

2017-02-22 20:47 UTC, Dirrk commented
Builds breaking waiting for this change

2017-02-22 22:11 UTC, chrootsu commented
:+1:

2017-02-23 05:15 UTC, sshquack commented
Just to echo what others have already mentioned here, this problem is causing issues with the TypeScript 2.2 release

https://github.com/Microsoft/TypeScript/issues/14256

2017-02-23 18:29 UTC, mhegazy requested changes

2017-02-23 18:29 UTC, mhegazy commented on lodash/index.d.ts
> +        isWeakMap<K, V>(value?: any): value is WeakMapLike<K, V>;
this change disables the guard.  `WeakMapLike` does not even have the declarations of `WeakMap`, so it is not usable.

I would say just remove `WeakMap` declaration altogether, and make this function return boolean.

2017-02-24 03:58 UTC, JProgrammer commented on lodash/index.d.ts
> +        isWeakMap<K, V>(value?: any): value is WeakMapLike<K, V>;
@mhegazy would #14787 be a better solution?

2017-02-24 05:09 UTC, mhegazy commented on lodash/index.d.ts
> +        isWeakMap<K, V>(value?: any): value is WeakMapLike<K, V>;
I do not think so. this change seems good to me, but we just need to remove the weakMap reference altogether.

2017-02-24 08:51 UTC, budiadiono commented on lodash/index.d.ts
> +        isWeakMap<K, V>(value?: any): value is WeakMapLike<K, V>;
@mhegazy thanks for the review. I'll update it now.

2017-02-24 18:21 UTC, andy-ms commented
A better fix would be to have `isWeakMap(value?: any): value is WeakMap<any, any>;`.
(It doesn't make sense to have type parameters because generics are erased, and `isWeakMap<{ x: number }, boolean>(foo)` would still return `true` even if `foo` is a `WeakMap<{ y: string }, Date>`.)

Then the test must be changed to use e.g. `WeakMap<{ x: number }, number>` because of the type constraint on WeakMaps.

2017-02-24 22:35 UTC, mhegazy commented
> A better fix would be to have isWeakMap(value: any): value is WeakMap<any, any>;.

@andy-ms, the issue is not the user-defined type guard, the issue is the declaration of `WeakMap`. `WeakMap` is not defined in `lib.d.ts` (only `lib.es2015.collections.d.ts` or one of its dependents); so lodash had a forward declaration of it. TS 2.2 changed the declaration to include `T extends object` on the key, now lodash needs to do the same, but `object` is a TS 2.2 feature.  so you see it is a catch-22.

Ultimiatlly https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14787 is the correct fix, but this unblocks ppl at the moment.

2017-02-24 22:35 UTC, mhegazy approved these changes

2017-02-24 22:35 UTC, merged