Extend Leaflet Util namespace
DefinitelyTyped/DefinitelyTyped pull request #14722
Opened 2017-02-19 19:08 UTC by DenisCarriere

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

http://leafletjs.com/reference-1.0.3.html#util
https://github.com/Leaflet/Leaflet/blob/master/src/core/Util.js

2017-02-20 15:22 UTC, alejo90 requested changes
Thanks, @DenisCarriere. There are a couple improvements we can make.

2017-02-20 15:22 UTC, alejo90 commented on leaflet/index.d.ts
> +        export function falseFn(): () => void;
According to the docs, this returns a function that always returns `false`, so the signature for the return type can be `() => boolean` or maybe even `() => false`

2017-02-20 15:22 UTC, alejo90 commented on leaflet/index.d.ts
> +        export function cancelAnimFrame(id: number): undefined;
The return type can be `void`

2017-02-20 15:22 UTC, alejo90 commented on leaflet/index.d.ts
> +        export function extend(dest: {}, src?: {}): {};
I suggest changing `{}` to `any` since `{}` is pretty unusual in the definitions I've looked at so far.

2017-02-20 15:25 UTC, alejo90 commented on leaflet/index.d.ts
> +    }
The `lastId` property is missing.

2017-02-20 18:40 UTC, DenisCarriere commented
@alejo90 Thanks for the feedback! I'll make those changes

2017-02-20 18:42 UTC, DenisCarriere commented on leaflet/index.d.ts
> +        export function extend(dest: {}, src?: {}): {};
I used `{}` based on the Typescript linter.

```
1539:45  forbidden-types  Avoid using the Object type. Did you mean `any` or `{}`?
```
However I do agree it looks kinda weird :) I'll use `any` instead

2017-02-20 18:53 UTC, DenisCarriere commented on leaflet/index.d.ts
> +    }
Doesn't look like `lastId` is exported or modified when using `stamp`.

https://github.com/Leaflet/Leaflet/blob/master/src/core/Util.js#L48-L57

Going to include it and make a PR to leaflet to export that variable

2017-02-20 18:57 UTC, DenisCarriere commented on leaflet/index.d.ts
> +    }
https://github.com/Leaflet/Leaflet/pull/5349

2017-02-21 00:19 UTC, alejo90 commented
👍

2017-02-22 19:16 UTC, DenisCarriere commented
Looks like this could be merged, author gave a :+1: and all the suggestions have been reviewed and fixed.

CC: @zhengbli

2017-02-22 20:03 UTC, zhengbli commented
👍 Thanks @DenisCarriere !

2017-02-22 20:03 UTC, merged