[node-forge] Added pkcs12 typings
DefinitelyTyped/DefinitelyTyped pull request #14730
Opened 2017-02-20 09:06 UTC by flynetworks

Please fill in this template.

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [ ] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/digitalbazaar/forge#pkcs12
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-02-20 20:20 UTC, westy92 requested changes

2017-02-20 20:20 UTC, westy92 commented on node-forge/index.d.ts
> +        function pkcs12FromAsn1(obj:any, strictOrPassword: boolean|string, password?: string) : Pkcs12Pfx;
`strictOrPassword` should be an optional parameter

2017-02-20 20:20 UTC, westy92 commented on node-forge/index.d.ts
> +        function pkcs12FromAsn1(obj:any, strictOrPassword: boolean|string, password?: string) : Pkcs12Pfx;
It might be best to use function overloading here instead of providing the single function to handle multiple situations.

2017-02-21 07:42 UTC, flynetworks commented on node-forge/index.d.ts
> +        function pkcs12FromAsn1(obj:any, strictOrPassword: boolean|string, password?: string) : Pkcs12Pfx;
Yes definitely right. Sorry this solution i hadn't in mind :(

2017-02-22 04:17 UTC, westy92 approved these changes

2017-02-22 04:17 UTC, westy92 commented
Looks good, thanks!

2017-02-22 08:55 UTC, flynetworks commented
You're welcome :-) Thanks a lot for the fast merge.

2017-03-03 09:01 UTC, flynetworks commented
Can you please merge this pull request?

2017-03-06 09:45 UTC, closed without merging