Updated Openfin typings to v17
DefinitelyTyped/DefinitelyTyped pull request #14749
Opened 2017-02-20 23:16 UTC by chrisbarker

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.openfin.co/versions/?product=Runtime%20Versions&version=6.49.17.14
- [x] Increase the version number in the header if appropriate.

2017-03-08 22:55 UTC, minestarks requested changes

2017-03-08 22:55 UTC, minestarks commented on openfin/index.d.ts
> +		 * Retrieves an array of wrapped fin.desktop.Windows for each of the application�s child windows.
Could you change these to regular apostrophes or just revert the line please?

A few more occurrences below

2017-03-09 01:31 UTC, minestarks approved these changes

2017-03-09 01:32 UTC, minestarks commented
Now I see somehow there are merge conflicts... once you resolve them I can merge. Thank you.

2017-03-21 23:21 UTC, paulvanbrenk commented
Thanks for the contribution. Manually merging this in.

2017-03-21 23:21 UTC, closed without merging

2017-06-05 16:48 UTC, joneit commented
@chrisbarker FYI we are currently in the process of preparing an update.
Feel free to reach out. I am at: jonathan@openfin.co