Added new typings for rvo2 package on npm
DefinitelyTyped/DefinitelyTyped pull request #14772
Opened 2017-02-22 14:24 UTC by erikvullings

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.

2017-03-08 04:52 UTC, minestarks requested changes

2017-03-08 04:52 UTC, minestarks commented on rvo2/tsconfig.json
> +        "baseUrl": "../",
New typings should have ```strictNullChecks``` enabled.

2017-03-11 19:17 UTC, merged

2017-03-11 19:17 UTC, mhegazy commented
feel free to send a new PR to update the strictNullChecks

2017-03-11 19:18 UTC, mhegazy commented
@erikvullings just curious, you seem to be the author of the original package, why not [host the .d.ts file in your package directly](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html)?