jquery.fancytree: fixes for Fancytree, FancytreeNode, FancytreeOptions
DefinitelyTyped/DefinitelyTyped pull request #14781
Opened 2017-02-22 16:29 UTC by evil-shrike

* Fancytree: added fields widget, $container, focusNode, options; fixed activateKey method signature
* FancytreeNode: added fields span, tr; fixed data field type
* FancytreeOptions: fixed toggleEffect field type

2017-03-08 23:45 UTC, minestarks requested changes

2017-03-08 23:45 UTC, minestarks commented on jquery.fancytree/index.d.ts
> +        widget: any; //JQueryUI.Widget;
Why not add the ```JQueryUI.Widget``` type?

2017-03-08 23:45 UTC, minestarks commented on jquery.fancytree/index.d.ts
> +        data: any;
Why is ```any``` necessary here? Could you add some usage examples in the test file to demonstrate?

2017-03-08 23:45 UTC, minestarks commented on jquery.fancytree/index.d.ts
> +        widget: any; //JQueryUI.Widget;
Could you add the actual ```JQueryUI.Widget``` type?

2017-03-09 08:42 UTC, evil-shrike commented on jquery.fancytree/index.d.ts
> +        widget: any; //JQueryUI.Widget;
JQueryUI.Widget is implemented in such a way that some fields like `element` and methods like `destroy` are not accessible.

2017-03-09 08:50 UTC, evil-shrike commented on jquery.fancytree/index.d.ts
> +        data: any;
It's better to ask "why Object is necessary here" :). Actually `data` is anything associated with a node. 
So if I put some object into it in one place:
```
tree.rootNode.data = { model: someDomainObject }
```
then I'd expect it available in another:
```
let model = tree.rootNode.data.model;
```
but it won't compile:
TS2339: Property 'model' does not exist on type 'Object'.

2017-03-10 23:46 UTC, merged