Docs and some missing functions for chai.assert
DefinitelyTyped/DefinitelyTyped pull request #14883
Opened 2017-02-26 21:22 UTC by JoshuaKGoldberg

Bumped Chai version to 3.5.0.

2017-02-26 21:27 UTC, JoshuaKGoldberg commented
It doesn't pass Travis CI because of TypeScript 2.1 - specific features... but I did as the DT README.md [suggests](https://github.com/DefinitelyTyped/DefinitelyTyped/#i-want-to-use-features-from-typescript-21) and added the 2.1 comment. This is confusing.

2017-03-10 05:47 UTC, mhegazy commented
Chai has multiple dependencies; by pumping it to TS 2.1, you need to update them as well.

2017-03-10 07:29 UTC, JoshuaKGoldberg commented
@mhegazy is this requirement documented anywhere?

2017-03-14 19:44 UTC, JoshuaKGoldberg commented
After a second glance, I don't follow. Why does Chai having a dependency on something necessitate it being bumped to 2.1? 

On the flip side, does bumping Chai to 2.1 mean anything that depends on it should also be bumped to 2.1? That would make more sense, but probably be a huge change. If this is the case, it might make sense to file an issue to generate a tool that auto-bumps everything depending on a 2.1-requiring typing?

2017-03-21 00:34 UTC, paulvanbrenk commented
It's the 2nd case.. once you bump Chai, everything that depends on it needs to be bumped (and potentially fixed) as well... please file a bug so we can get some traction on making that process easier.

2017-04-03 22:51 UTC, JoshuaKGoldberg commented
Alternative proposal: I can remove the TS 2.1-specific features. The only blocker was a string literal type. Could you please re-open the PR @paulvanbrenk? I don't think I have permissions to.

2017-04-05 20:48 UTC, paulvanbrenk commented
@JoshuaKGoldberg  done

2017-04-06 02:11 UTC, JoshuaKGoldberg commented
Thanks!

Re-pinging authors (@jedmao @.Bartvds @AGBrown @olivr70 @mwistrand). Could you review this PR?
👍 or 👎?

2017-04-06 02:51 UTC, jednano requested changes
It's looking pretty good. Just a couple minor comments.

2017-04-06 02:51 UTC, jedmao commented on types/chai/index.d.ts
> +        use(fn: (chai: (any), utils: any) => void): ChaiStatic;
Are these parentheses adding any value?

2017-04-06 02:51 UTC, jedmao commented on types/chai/index.d.ts
> +    export type Operator = string; // "==" | "===" | ">" | ">=" | "<" | "<=" | "!=" | "!==";
I think you can use the actual values here:
```ts
export type Operator = '==' | '===' | '>' | '>=' | '<' | '<=' | '!=' | '!==';
```

2017-04-06 02:51 UTC, jedmao commented on types/chai/index.d.ts
> +}
nope

2017-04-06 02:51 UTC, jedmao commented on types/chai/index.d.ts
> +}
nope

2017-04-06 15:38 UTC, JoshuaKGoldberg commented on types/chai/index.d.ts
> +        use(fn: (chai: (any), utils: any) => void): ChaiStatic;
I honestly have no idea where they came from. Will remove...

2017-04-06 15:38 UTC, JoshuaKGoldberg commented on types/chai/index.d.ts
> +    export type Operator = string; // "==" | "===" | ">" | ">=" | "<" | "<=" | "!=" | "!==";
Can't 😦 see above conversation. This and the `keyof` types are blocked on updating libraries that depend on chai to also require TS 2.1. I'll do that in a subsequent PR.

2017-04-06 15:40 UTC, JoshuaKGoldberg commented on types/chai/index.d.ts
> +}
Will fix!

2017-04-06 18:07 UTC, jednano approved these changes

2017-04-10 21:11 UTC, merged

2017-04-11 15:59 UTC, Agamnentzar commented on types/chai/index.d.ts
> +        deepPropertyNotVal<T, V>(object: T, property: string, value: T, message?: string): void;
shouldn't this be `value: V` ?

2017-04-11 17:34 UTC, JoshuaKGoldberg commented on types/chai/index.d.ts
> +        deepPropertyNotVal<T, V>(object: T, property: string, value: T, message?: string): void;
Oh good catch, thank you! Will file a followup PR.