Update Faker Definitions to V4.1.0
DefinitelyTyped/DefinitelyTyped pull request #15073
Opened 2017-03-08 19:25 UTC by bensw

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
~~Run `npm run lint package-name` if a `tslint.json` is present.~~ N/A

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Faker 4.1.0](https://github.com/Marak/faker.js/releases/tag/v4.1.0)
- [x] Increase the version number in the header if appropriate.
~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.~~ N/A

2017-03-08 21:44 UTC, minestarks requested changes

2017-03-08 21:44 UTC, minestarks commented on faker/v3/tsconfig.json
> +        "strictNullChecks": false,
```strictNullChecks``` should be on

2017-03-08 21:51 UTC, bensw commented on faker/v3/tsconfig.json
> +        "strictNullChecks": false,
This was copied from the current version. Should I also change it for the base directory?

2017-03-08 23:00 UTC, minestarks commented on faker/v3/tsconfig.json
> +        "strictNullChecks": false,
Oh I missed that. Yes please!

2017-03-08 23:00 UTC, minestarks approved these changes

2017-03-09 00:22 UTC, bensw commented
@minestarks What next steps need to be taken on this review? Is there any action on my end?

2017-03-09 00:24 UTC, minestarks commented
No action on your part. I'll give the authors @basp @Kuniwak some time to review, or merge if no comments. Thanks.

2017-03-14 02:48 UTC, merged

2017-03-14 02:48 UTC, yuit commented
@bensw  thanks for the PR!