Add new plaid-link package
DefinitelyTyped/DefinitelyTyped pull request #15135
Opened 2017-03-12 19:20 UTC by pbernasconi

This PR adds definition for [Plaid Link](https://plaid.com/docs/quickstart), as `plaid-link`, a frontend drop-in module for interacting with the [Plaid API](https://plaid.com). It will often be consumed by Angular/Ionic/any frontend project written in Typescript.

More detailed parameter/docs reference can be found at: https://plaid.com/docs/api

- [X] Make your PR against the `master` branch.
- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `tsc` without errors.
- [X] Run `npm run lint package-name` if a `tslint.json` is present.

2017-03-12 20:05 UTC, mhegazy requested changes

2017-03-12 20:05 UTC, mhegazy commented on plaid-link/tsconfig.json
> +        "strictNullChecks": false,
new packages should have `strictNullchecks` `true`.

2017-03-12 20:05 UTC, mhegazy commented on plaid-link/index.d.ts
> +// Type definitions for Plaid Link
no version?

2017-03-12 20:05 UTC, mhegazy commented on plaid-link/index.d.ts
> +// Type definitions for Plaid Link
Is this package available on npm? if so what is the package name?

2017-03-22 23:01 UTC, paulvanbrenk commented
Closing this PR, as it's gotten pretty stale. Please ping us to re-open if you made the requested changes, or start a new PR.

2017-03-22 23:01 UTC, closed without merging