Ensure the HelloSign object can be imported
DefinitelyTyped/DefinitelyTyped pull request #15134
Opened 2017-03-12 17:56 UTC by Flavien

In the current form, the ``hellosign-embedded`` library could not be imported. The type declaration expects a global variable, but [the library](https://github.com/HelloFax/hellosign-embedded/blob/master/src/embedded.js) does not define any.

2017-03-12 18:19 UTC, xt0rted commented
👍

If you load this via `https://s3.amazonaws.com/cdn.hellosign.com/public/js/hellosign-embedded.LATEST.js` then there is a global `HelloSign` object. This is how I'm referencing the library.

The change looks good to me though since you can load this from npm which is the same as what's in their repo.

2017-03-13 17:16 UTC, mhegazy requested changes

2017-03-13 17:16 UTC, mhegazy commented on hellosign-embedded/index.d.ts
> +export = HelloSign;
please add to your change `export as namespace HelloSign` this will grantee that it is available both as a module and a global variable.

2017-03-14 10:59 UTC, Flavien commented on hellosign-embedded/index.d.ts
> +export = HelloSign;
If I try to do that, I get a TypeScript error: "Global module exports may only appear in module files."

2017-03-14 11:24 UTC, Flavien commented on hellosign-embedded/index.d.ts
> +export = HelloSign;
Ok I used ``export declare module HelloSign`` for the export and it works.

2017-03-14 11:27 UTC, Flavien commented on hellosign-embedded/index.d.ts
> +export = HelloSign;
But it looks like if I do that, it's not available as a global variable.

2017-03-22 22:59 UTC, merged