google-protobuf - added built-in proto classes
DefinitelyTyped/DefinitelyTyped pull request #15152
Opened 2017-03-13 16:33 UTC by MarcusLongmuir

This PR adds the classes that are part of the `google-protobuf` library (e.g. `google-protobuf/google/protobuf/any_pb`) that are required by message generated by `protoc`.

These classes were generated by a `protoc` TypeScript plugin that I am working on, with a few of the classes being extended as per the `protoc` JS generator (`any` and `struct` have additional functions). 

I have checked that they match the JS classes.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: None. This is typing more of the library.
- [x] Increase the version number in the header if appropriate. - not appropriate
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

2017-03-13 17:03 UTC, mhegazy requested changes

2017-03-13 17:03 UTC, mhegazy commented on google-protobuf/google-protobuf-tests.ts
> +import "google/protobuf/compiler/plugin_pb";
this does not seem like the module name the file below defines, the file defines `"google-protobuf/google/protobuf/compiler/plugin_pb"`, is that the intention?

2017-03-13 20:56 UTC, MarcusLongmuir commented
@mhegazy: How should I structure these additional classes? They're used like this in generated code:
```ts
import * as google_protobuf_timestamp_pb from "google-protobuf/google/protobuf/timestamp_pb";
```

The (current) error on the build is:
```
Error: Directory /home/travis/build/DefinitelyTyped/DefinitelyTyped/google-protobuf/google/protobuf has unused file any_pb.d.ts
```

`any_pb` is used in the test file, but that doesn't seem to solve it. Is the unused file check only checking for usage within the same directory?

2017-03-15 10:27 UTC, MarcusLongmuir commented
@minestarks: You looked at the previous `google-protobuf` PRs. Do you have an opinion on how this should be done?

2017-03-21 11:58 UTC, MarcusLongmuir commented
@mhegazy: Tests are fixed now 👍

2017-03-22 13:19 UTC, closed without merging