react-intl: Add properties used in tests.
DefinitelyTyped/DefinitelyTyped pull request #15310
Opened 2017-03-22 17:48 UTC by tamlyn

### Context
`react-intl` provides a higher order component which wraps a React component and provides some extra props to it. It also [exposes the original component](https://github.com/yahoo/react-intl/blob/master/src/inject.js) as `WrappedComponent` and this is [useful for testing](https://github.com/yahoo/react-intl/wiki/Testing-with-React-Intl#relativedate-advanced-uses-injectintl).

In order to get the data necessary to pass to such a component, the `IntlProvider` component exposes a [`getChildContext()` method](https://github.com/yahoo/react-intl/blob/master/src/components/provider.js#L147).

### Questions
- Is there a way to say that the type of `WrappedComponent` is the same as that of the `component` parameter, but still assert that this is a react component with the given props? The solution presented here works but feels inelegant.

2017-03-22 17:57 UTC, gyzerok requested changes
Thanks a lot for the PR! This is an amazing addition!

2017-03-22 17:57 UTC, gyzerok commented on react-intl/index.d.ts
> +            intl: any;
What type it should be here? Should it be `InjectedIntl` here? Can you please add it?

2017-03-23 10:30 UTC, tamlyn commented on react-intl/index.d.ts
> +            intl: any;
It includes `InjectedIntl` with [a load of other stuff](https://github.com/yahoo/react-intl/blob/master/src/components/provider.js#L147). It looks something like this:
```
{ 
      locale: 'en',
      formats: {},
      messages: {},
      defaultLocale: 'en',
      defaultFormats: {},
      formatDate: [Function: bound formatDate],
      formatTime: [Function: bound formatTime],
      formatRelative: [Function: bound formatRelative],
      formatNumber: [Function: bound formatNumber],
      formatPlural: [Function: bound formatPlural],
      formatMessage: [Function: bound formatMessage],
      formatHTMLMessage: [Function: bound formatHTMLMessage],
      formatters:
       { getDateTimeFormat: [Function],
         getNumberFormat: [Function],
         getMessageFormat: [Function],
         getRelativeFormat: [Function],
         getPluralFormat: [Function] },
      now: [Function: now] 
}
```

Given it's likely to be used in a test context, I felt it was acceptable to put an `any` in

2017-03-23 12:12 UTC, gyzerok commented on react-intl/index.d.ts
> +            intl: any;
Well, in this case you can just write it like

```ts
const props = { locale: 'en', messages: localizations.en };
const intlProvider = new ReactIntl.IntlProvider(props, {});

return (intlProvider as any).getChildContext().intl;
```

so types additions make no sense.

I would put here at least `InjectedIntl` for now and when [this](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15137) PR will land there will be all other properties within `InjectedIntl` type as well.

2017-03-23 12:13 UTC, gyzerok requested changes
Need to add changes discussed within comments

2017-03-23 14:11 UTC, tamlyn commented
Oh nice! Yeah that works. Updated.

2017-03-23 14:14 UTC, gyzerok requested changes

2017-03-23 14:14 UTC, gyzerok commented on react-intl/index.d.ts
> +        getChildContext(): InjectedIntlProps;
I guess it should be `InjectedIntl` not `InjectedIntlProps`. Am I right?

2017-03-23 14:16 UTC, tamlyn commented on react-intl/index.d.ts
> +        getChildContext(): InjectedIntlProps;
Can either be `{intl: InjectedIntl}` or `InjectedIntlProps`. If you look at the code, it returns an object with a single `intl` key.

2017-03-23 14:17 UTC, gyzerok commented on react-intl/index.d.ts
> +        getChildContext(): InjectedIntlProps;
Oh, not, you are correct, now its type for the whole context, not just `intl` part of it.

However I am thinking if it is safe to do it like this. Still `InjectedIntlProps` is separate thing and the fact that it seems to work here for now might be just a coincidence. So I suggest to do it like:

```ts
getChildContext() {
  return { intl: InjectedIntl };
}
```

2017-03-23 14:56 UTC, tamlyn commented on react-intl/index.d.ts
> +        getChildContext(): InjectedIntlProps;
Makes sense. Updated.

2017-03-23 15:06 UTC, gyzerok approved these changes
LGTM :+1:

2017-03-23 15:07 UTC, gyzerok commented
@paulvanbrenk can you, please, merge it?

2017-03-23 20:41 UTC, merged