New types for node-jose
DefinitelyTyped/DefinitelyTyped pull request #15350
Opened 2017-03-24 03:18 UTC by Drynwynn

Please fill in this template.

- [x] Make your PR against the `master` branch.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `tsc` without errors.
- [x] Run `npm run lint package-name` if a `tslint.json` is present.

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `npm run new-package package-name`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-03-24 15:17 UTC, ghost reviewed
Needs a `tslint.json` containing `{ "extends": "../tslint.json" }`

2017-03-24 15:17 UTC, andy-ms commented on node-jose/index.d.ts
> +     * @param {string} alg The algorithm to use
Don't need type declarations in jsdoc, that's what TypeScript is for!

2017-03-24 15:17 UTC, andy-ms commented on node-jose/index.d.ts
> +     * @property {boolean|string} zip Determines the compression algorithm to
Move documentation to the properties theirselves, i.e.:
```ts
/** Describe zip */
zip?: boolean | string;
```

2017-03-24 15:17 UTC, andy-ms commented on node-jose/index.d.ts
> +         * @readonly
TypeScript provides a `readonly` modifier so you don't need jsdoc for this.

2017-03-24 16:56 UTC, sandersn requested changes

2017-03-24 16:56 UTC, sandersn commented on node-jose/index.d.ts
> +         * @readonly
Also the type should be `"DEF" | ""`, which is more specific than just `string`.

2017-03-24 16:56 UTC, sandersn commented on node-jose/index.d.ts
> +     * @property {boolean|string} zip Determines the compression algorithm to
The `string`s for this type should be broken into their allowed values, eg `zip: boolean | "DEF" | ""`.

2017-03-24 16:56 UTC, sandersn commented on node-jose/index.d.ts
> +     *           (default is **`"A128CBC-HS256"`**).
it's not clear whether `contentAlg` is open-ended, but even if it is `contentAlg: "A128CBC-HS256" | string` is better documentation than just string, even though they are technically equivalent.

2017-03-24 16:56 UTC, sandersn commented on node-jose/index.d.ts
> +    const MODE_DECRYPT: string;
these should probably be `const MODE_DECRYPT: "MODE_DECRYPT";` and then have a union type tying them together for later use: `type Mode = MODE_DECRYPT | MODE_ENCRYPT | ...`

2017-03-24 16:56 UTC, sandersn commented on node-jose/index.d.ts
> +        get: (name: string, isPrivate?: boolean) => any;
from the jsdoc, I think the second parameter should be `isPrivate = false`

2017-03-24 17:20 UTC, andy-ms commented on node-jose/index.d.ts
> +        get: (name: string, isPrivate?: boolean) => any;
You can't have an initializer in a declaration file.

2017-03-24 22:14 UTC, andy-ms commented
We've recently updated the repository structure.
All packages are now in a `types` subdirectory.
Please rebase this pull request onto the latest `master` branch.

2017-04-10 21:33 UTC, RyanCavanaugh commented
@sandersn can you update your review status please?

2017-04-10 21:42 UTC, merged

2017-04-10 21:43 UTC, sandersn commented
My comments aren't addressed, but it would be better to merge at this point so at least the definitions are available.

2017-04-12 23:14 UTC, blakeembrey commented
This PR wasn't fixed up according to @andy-ms' comments, so you have one random definition in the root of the project now (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/node-jose).

2017-04-12 23:42 UTC, Drynwynn commented
Sorry for the delay all.

I'll review the comments (thanks for the feedback) and fix up the structure in another PR to fix what was added in this one.

2019-01-10 18:06 UTC, sandersn commented
@sahlouls It was removed because the types needed more work: See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15953