Add instanceId property for correct server rendering
DefinitelyTyped/DefinitelyTyped pull request #15612
Opened 2017-04-04 08:13 UTC by Dwlad90

custom instance for server rendering

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "../tslint.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-04-12 20:00 UTC, devrelm requested changes

2017-04-12 20:00 UTC, devrelm commented on types/react-select/index.d.ts
> +         instanceId?: string;
1. Can you provide a link to documentation (or a line of code) which proves that this exists and where it's set on the object?
2. You put the comment below the item, so now `isLoading` and `instanceId` have their comments swapped.
3. It looks like the indentation is off -- you have one extra space before `instanceId`.

2017-04-12 20:08 UTC, devrelm commented
👎

2017-05-01 22:13 UTC, mhegazy commented
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-05-01 22:13 UTC, closed without merging