add measure function into ui manager
DefinitelyTyped/DefinitelyTyped pull request #15673
Opened 2017-04-05 18:16 UTC by evollu

it is not documented but by looking at the source code of NativeMethodsMixin you can tell these function are available
https://github.com/facebook/react-native/blob/master/Libraries/Renderer/src/renderers/native/NativeMethodsMixin.js#L72

2017-04-05 18:57 UTC, alloy requested changes
While I agree these functions exist, I wonder why you’d want to expose them over the methods on the components that _are_ publicly exposed and which are already included in these types?

In any case, the lint error is legit and needs fixing as well as my one review comment.

2017-04-05 18:57 UTC, alloy commented on types/react-native/index.d.ts
> +        onFail: () => void /* currently unused */
These callbacks are in [the wrong order](https://github.com/facebook/react-native/blob/269458c613b658a0a3e8e7e86f8394278d5b9e23/Libraries/Renderer/src/renderers/native/NativeMethodsMixin.js#L117-L118).

2017-04-05 20:28 UTC, evollu commented
I tried NativeMethodsMixin but seems like `react-native` no long exports that module.
@alloy can you verify.
I'm tried 0.42 and 0.43

2017-04-06 20:48 UTC, alloy commented
Hmm, in retrospect I didn’t pay attention to the filename, it’s clearly a mixin and those aren’t supported on ES6 classes, so adding these is probably a good idea anyways :+1:

2017-04-06 20:48 UTC, alloy approved these changes

2017-04-06 20:48 UTC, merged