fix(commader): issue with namespace not found
DefinitelyTyped/DefinitelyTyped pull request #16060
Opened 2017-04-22 11:43 UTC by alan-agius4

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

2017-04-22 11:45 UTC, alan-agius4 commented
👍

2017-04-29 07:41 UTC, alan-agius4 commented
Can we have this merged please?

2017-05-04 19:10 UTC, mhegazy requested changes

2017-05-04 19:10 UTC, mhegazy commented on types/commander/index.d.ts
> +    interface Option {
this does not look right. `Option` seems to be a class, and not an object that is callable with `new`:

```sh
> var commander = require("commander");
undefined
> commander.Option
[Function: Option]
> new commander.Option("--f");
Option {
  flags: '--f',
  required: 0,
  optional: 0,
  bool: true,
  long: '--f',
  description: '' }
> new (new commander.Option("--f"))("--f");
TypeError: (intermediate value) is not a constructor
    at repl:1:1
    at realRunInThisContextScript (vm.js:22:35)
    at sigintHandlersWrap (vm.js:98:12)
    at ContextifyScript.Script.runInThisContext (vm.js:24:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:544:10)
    at emitOne (events.js:101:20)
    at REPLServer.emit (events.js:188:7)
```

2017-05-05 06:01 UTC, alan-agius4 commented on types/commander/index.d.ts
> +    interface Option {
How are you suggesting to change it? If I can it to a class. I'll get
```
[ts] Duplicate identifier "commander"
```

And if I do the class outside the `namespace`,  and export as

```
declare const commander: commander.StaticCommander & Option;
```

I can still do 

```
new(new program.Option("--f"))("--f")
```

2017-05-05 22:29 UTC, mhegazy commented on types/commander/index.d.ts
> +        Command: new (name?: string) => Command;
`Command: typeof Command`

2017-05-05 22:30 UTC, mhegazy commented on types/commander/index.d.ts
> +        Option: new (flags: string, description?: string) => Option;
`Option: typeof Option`

2017-05-06 04:07 UTC, alan-agius4 commented on types/commander/index.d.ts
> +        Option: new (flags: string, description?: string) => Option;
thank you for the review @mhegazy, updated as suggested

2017-05-09 18:40 UTC, alan-agius4 commented
Any update please :)


On Sat, 06 May 2017 at 00:30, Mohamed Hegazy <notifications@github.com>
wrote:

> *@mhegazy* commented on this pull request.
> ------------------------------
>
> In types/commander/index.d.ts
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16060#discussion_r115098721>
> :
>
> >           */
> -        outputHelp(cb?: () => void): void;
> +        Option: new (flags: string, description?: string) => Option;
>
> Option: typeof Option
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16060#pullrequestreview-36621830>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQv-WiLQykX2CJ15v3xkt2y2mnACSDzNks5r26MQgaJpZM4NFD3Q>
> .
>

2017-05-13 08:40 UTC, alan-agius4 commented
@mhegazy any update please?

2017-05-28 20:07 UTC, alan-agius4 commented
@mhegazy can we have this merged pls?

2017-06-01 14:07 UTC, merged

2017-06-01 14:50 UTC, sanex3339 commented
it's happening!