improving request-promise-native: expanding defs and linting
DefinitelyTyped/DefinitelyTyped pull request #16103
Opened 2017-04-24 17:17 UTC by jcgillespie

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
[request-promise defs](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/request-promise/index.d.ts)
[request-promise docs](https://github.com/request/request-promise)
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

2017-04-24 17:42 UTC, gustavohenke requested changes

2017-04-24 17:42 UTC, gustavohenke commented on types/request-promise-native/index.d.ts
> +            catch(type: errors.TransformErrorConstructor, onrejected?: (reason: errors.TransformError) => void): Promise<any>;
These should definitely be dropped, as `request-promise-native` uses native promises - and these don't have error type selection, like Bluebird promises do (used by `request-promise` itself).

2017-04-24 17:46 UTC, jcgillespie commented on types/request-promise-native/index.d.ts
> +            catch(type: errors.TransformErrorConstructor, onrejected?: (reason: errors.TransformError) => void): Promise<any>;
Will do. Thanks!

2017-04-24 17:56 UTC, jcgillespie commented on types/request-promise-native/index.d.ts
> +            catch(type: errors.TransformErrorConstructor, onrejected?: (reason: errors.TransformError) => void): Promise<any>;
@gustavohenke that update is committed/built now.
Thanks again!

2017-04-25 15:56 UTC, jcgillespie commented
@gustavohenke thoughts on the latest?

2017-04-27 00:00 UTC, gustavohenke requested changes
I'm quite out of the TypeScript world lately, so I may be lacking to see any further changes than linting fixes, after you removed the error type selection.
Is that correct?

If that's the case, just a tip: in my own projects I prefer to rebase the branch and remove the isolated commits instead of adding more commits to undo stuff

2017-04-27 00:00 UTC, gustavohenke commented on types/request-promise-native/index.d.ts
> +// Type definitions for request-promise-native 1.1
There is no v1.1 of `request-promise-native`: https://github.com/request/request-promise-native/releases

2017-04-27 00:00 UTC, gustavohenke commented on types/request-promise-native/index.d.ts
> +declare module 'request-promise-native/errors' {
Unused module

2017-04-27 00:00 UTC, gustavohenke commented on types/request-promise-native/request-promise-native-tests.ts
> +import * as errors from 'request-promise-native/errors';
Unused import

2017-04-27 13:12 UTC, jcgillespie commented on types/request-promise-native/index.d.ts
> +// Type definitions for request-promise-native 1.1
Correct. The version is for the types, not the library. The linter disallows the "v" prefix and the "patch" number. Didn't think that going "back" to a `1.0` was the right direction, so I went to `1.1

2017-04-27 13:15 UTC, jcgillespie commented on types/request-promise-native/index.d.ts
> +declare module 'request-promise-native/errors' {
Matched the `request-promise` type definitions.

2017-04-27 13:15 UTC, jcgillespie commented on types/request-promise-native/request-promise-native-tests.ts
> +import * as errors from 'request-promise-native/errors';
Matched the `request-promise` type definitions.

2017-04-27 13:15 UTC, jcgillespie commented
@gustavohenke The impetus for the PR was adding the `/errors` module, which did not exist in the native type definitions, but does exist in both [request-promise types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/354cec620daccfa0ad167ba046651fb5fef69e8a/types/request-promise/index.d.ts) and in the underlying [promise-core library](https://github.com/request/promise-core/blob/master/lib/errors.js)

Everything else was driven by one of two things.
1. The linter corrections
2. matching the `request-promise` type definitions.

I didn't anticipate making additional changes, but in walking through the contribution checklist I realized the definitions didn't adhere to the current guidelines. I can abandon this PR and re-open one that is rebased if you prefer.

2017-04-29 01:09 UTC, jcgillespie commented
I'll drop this one and resubmit just the piece I need.

2017-04-29 01:09 UTC, closed without merging

2017-04-29 12:57 UTC, gustavohenke commented
@jcgillespie sorry for taking this long to answer you 🙈 
I just reviewed your other PR #16216.

2017-04-29 14:10 UTC, jcgillespie commented
No worries. I broke the lint changes out into another set of commits that I'll submit separately.