Use correct response typings in request-promise-native
DefinitelyTyped/DefinitelyTyped pull request #16114
Opened 2017-04-25 01:09 UTC by obto

Use `request.RequestResponse` instead of `any`

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/request/request

2017-04-25 02:16 UTC, gustavohenke requested changes

2017-04-25 02:16 UTC, gustavohenke commented on types/request-promise-native/index.d.ts
> +        then<TResult>(onfulfilled?: (value: request.RequestResponse) => TResult | PromiseLike<TResult>, onrejected?: (reason: any) => void): Promise<TResult>;
This isn' true. See [`request-promise`](https://www.npmjs.com/package/request-promise) examples; the default is to return the response body, but you could also be returning the full response object.

2017-04-25 02:36 UTC, obto commented
Ah, good point. How about exporting an alias of `request.RequestResponse` so users can type the response more easily. Something like:

`export type FullResponse = request.RequestResponse;`

2017-04-27 00:12 UTC, gustavohenke approved these changes
LGTM.

But a minor note: in my own branches, I prefer to skip the unused commits, rather than adding extra commits to undo stuff, in case I change my mind.

So in your case I would drop the first commit and add another one adding the alias (keeps the history tidy).

2017-04-27 17:43 UTC, merged