popper.js: update type definitions to 1.8.5
DefinitelyTyped/DefinitelyTyped pull request #16159
Opened 2017-04-27 00:43 UTC by joscha

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/FezVrasta/popper.js/issues/62, https://github.com/FezVrasta/popper.js/commit/2c20861ea17a7090937654852439e178bc16f14e, https://github.com/FezVrasta/popper.js/issues/239
- [x] Increase the version number in the header if appropriate.

cc @FezVrasta @mattrcarter

2017-04-27 09:32 UTC, FezVrasta commented on types/popper.js/index.d.ts
> +      'function'?: Function,
Note that this is deprecated, now it's just `fn`. The old one is still supported tho

2017-04-27 11:00 UTC, joscha commented on types/popper.js/index.d.ts
> +      'function'?: Function,
thanks! Added in 7091e94e7a99e2c10d6c6a1376302c130a70e6fb.

2017-04-27 17:32 UTC, rhysd requested changes

2017-04-27 17:32 UTC, rhysd commented on types/popper.js/index.d.ts
> +// Copyright 2017 Canva Inc. All Rights Reserved.
I think copyright notice should be added after other headers because some bots look `Type definitions for ...` header.

2017-04-27 17:32 UTC, rhysd commented on types/popper.js/index.d.ts
> +// Copyright 2017 Canva Inc. All Rights Reserved.
This copyright notice should be removed because all files are served with license at `DefinitelyTyped/LICENSE`.

2017-04-27 22:23 UTC, joscha commented on types/popper.js/index.d.ts
> +// Copyright 2017 Canva Inc. All Rights Reserved.
ah, an accident - automatically inserted by the editor, will remove!

2017-04-27 22:23 UTC, joscha commented on types/popper.js/index.d.ts
> +// Copyright 2017 Canva Inc. All Rights Reserved.
removed in 49b2040

2017-04-27 23:44 UTC, rhysd approved these changes

2017-04-27 23:45 UTC, rhysd commented on types/popper.js/index.d.ts
> +// Copyright 2017 Canva Inc. All Rights Reserved.
Thanks!

2017-04-28 04:01 UTC, joscha commented
Thanks @rhysd! Do you know what the process is after this to get this merged? I can't tick the checkbox in the bot comment if that's what triggers it?

2017-04-28 06:27 UTC, rhysd commented
The checkbox is checked by committer. So you and I can't do anything. Let's wait for committer visiting this PR.

2017-04-28 17:45 UTC, merged