react-color: Extended definitions for common/{Saturation,Hue} components
DefinitelyTyped/DefinitelyTyped pull request #16168
Opened 2017-04-27 12:06 UTC by vitaliel

If you do not specify hsl/hsv for saturation/hue, it fails with error
like below on rendering:

TypeError: Cannot read property 'h' of undefined
  at Saturation.render (node_modules/react-color/lib/components/common/Saturation.js:89:48)
  at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (node_modules/react/lib/ReactCompositeComponent.js:808:34)

I also added definitions for react-color/lib/helpers/color module

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/casesandberg/react-color/blob/master/src/helpers/color.js
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

2017-04-27 13:56 UTC, LKay commented
@vitaliel I checked the source code and aparently props are required but not correctly doccumented, so I'm good with it. However I'm not sure about definitions for helper which seem to be used only internally and looks like a private API and that's why thery are not even mentioned in the official docs. It might not be a best idea to use them directly. Do you have and solid use case for that?

2017-04-27 13:56 UTC, LKay requested changes

2017-04-27 13:56 UTC, LKay commented on types/react-color/tsconfig.json
> +        "lib/helpers/color.d.ts",
Not sure about this one. check my comment below.

2017-04-28 09:42 UTC, vitaliel commented
Hello @LKay 

Thank you for your feedback.

The interesting issue here is that we need at Mixbook.com only a small part of that great library(react-color), common/{Hue,Saturation} and lib/helpers/color.js to manipulate these two components, in other words we only need the peak of iceberg ;-).

Do you think from your experience it will be better just to copy the needed files, instead of attaching the "iceberg" to our html editor product(hm, ... let me call it ship)?

2017-04-29 09:55 UTC, LKay commented
I'd rather not include definitions for private API which is not mentioned in the docs at all. This might change or be removed in the future without notice. Some better if you remove that part from you PR.

In your case I'd use the definitions provided from DT (after your changes get merged) and just create additional definitions with you helpers definitions inside your project. Then if you set up `paths` in your `tsconfig.json` correctly both should be resolvable by the compiler and you part would just extend the base definitions.

2017-05-16 23:11 UTC, aozgaa commented
Agreed with @LKay. Do not include internal API's. Concretely, remove `lib/helpers/color.d.ts`.

2017-06-01 14:19 UTC, andy-ms commented on types/react-color/lib/helpers/color.d.ts
> +declare module "react-color/lib/helpers/color" {
You shouldn't need a `declare module` here. You're already in the file `react-color/lib/helpers/color.d.ts`, so the contents of that file *are* the declaration of the module.

2017-06-01 14:20 UTC, andy-ms commented on types/react-color/lib/helpers/color.d.ts
> +declare module "react-color/lib/helpers/color" {
Or, just remove this file like @LKay said.

2017-06-05 23:45 UTC, mhegazy commented
Thanks for your contribution. This PR can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-06-05 23:45 UTC, closed without merging