Add koa-helmet type definitions
DefinitelyTyped/DefinitelyTyped pull request #16180
Opened 2017-04-27 18:11 UTC by nsimmons

Adds type definitions for https://github.com/venables/koa-helmet, which is a Koa wrapper around https://github.com/helmetjs/helmet

**Note: `hidePoweredBy` is excluded because Koa does not add `X-Powered-By` header like Express does.**

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-04-27 18:30 UTC, nsimmons commented on types/koa-helmet/index.d.ts
> +export type KoaHelmetContentSecurityPolicyDirectiveFunction = (ctx: Context) => string;
This type is why i had to pull all the rest of HelmetCsp related stuff. Needed to convert function from Express to Koa handler.

2017-05-01 21:01 UTC, mhegazy requested changes

2017-05-01 21:01 UTC, mhegazy commented on types/koa-helmet/index.d.ts
> +export default koaHelmet;
use `export = koaHelmet` instead. See  https://github.com/DefinitelyTyped/DefinitelyTyped#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default

2017-05-02 13:08 UTC, nsimmons commented on types/koa-helmet/index.d.ts
> +export default koaHelmet;
done

2017-05-03 19:11 UTC, merged