Remove path-to-regexp and add koa-route definitions
DefinitelyTyped/DefinitelyTyped pull request #16220
Opened 2017-04-29 13:52 UTC by migstopheles

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If removing a declaration:
- [x] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

2017-05-01 19:34 UTC, mhegazy requested changes

2017-05-01 19:34 UTC, mhegazy commented on types/koa-route/index.d.ts
> +declare const routes: KoaRoutes;
insread of:
```ts
interface KoaRoutes { ... }
declare const routes: KoaRoutes;
export = routes;
```

```ts
 export var all: CreateRouteMethod;
 export var acl: RouteMethod;
 export var bind: RouteMethod;
 export var checkout: RouteMethod;
 export var connect: RouteMethod;
 export var copy: RouteMethod;
 export var delete: RouteMethod;
 export var del: RouteMethod;
 export var get: RouteMethod;
 export var head: RouteMethod;
 export var link: RouteMethod;
 export var lock: RouteMethod;
 export var msearch: RouteMethod;
 export var merge: RouteMethod;
 export var mkactivity: RouteMethod;
 export var mkcalendar: RouteMethod;
 export var mkcol: RouteMethod;
 export var move: RouteMethod;
 export var notify: RouteMethod;
 export var options: RouteMethod;
 export var patch: RouteMethod;
 export var post: RouteMethod;
 export var propfind: RouteMethod;
 export var proppatch: RouteMethod;
 export var purge: RouteMethod;
 export var put: RouteMethod;
 export var rebind: RouteMethod;
 export var report: RouteMethod;
 export var search: RouteMethod;
 export var subscribe: RouteMethod;
 export var trace: RouteMethod;
 export var unbind: RouteMethod;
 export var unlink: RouteMethod;
 export var unlock: RouteMethod;
 export var unsubscribe: RouteMethod;
```

2017-05-01 19:57 UTC, andy-ms commented on notNeededPackages.json
> +            "asOfVersion": "1.7.0"
Prefer `^1.7.0`.

2017-05-03 20:27 UTC, migstopheles commented on types/koa-route/index.d.ts
> +declare const routes: KoaRoutes;
@mhegazy the reason for using the interface is that I get errors on the `delete` keyword due to strict mode. Figured it was better to keep strict mode and export in a different way, but I'm happy to make this change if you disagree, thanks

2017-05-03 20:30 UTC, andy-ms commented on notNeededPackages.json
> +            "asOfVersion": "^1.7.0"
This should be an exact version `1.7.0`. It's not a dependency.

2017-05-03 20:30 UTC, andy-ms commented on types/koa-route/package.json
> +        "path-to-regexp": "1.7.0"
*This* should be `^1.7.0`.

2017-05-03 20:41 UTC, migstopheles commented on types/koa-route/package.json
> +        "path-to-regexp": "1.7.0"
💡 that makes much more sense. Updated, let me know if I should clean up the commit history for the branch.

2017-05-03 20:45 UTC, andy-ms commented on types/koa-route/package.json
> +        "path-to-regexp": "1.7.0"
No need, we squash the commit history anyway.

2017-05-03 21:11 UTC, merged