Adding type definition leaflet-areaselect plugin
DefinitelyTyped/DefinitelyTyped pull request #16225
Opened 2017-04-29 20:29 UTC by awallat

Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ x] The package does not provide its own types, and you can not add them.
- [ x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ x] Increase the version number in the header if appropriate.
- [ x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-05-01 20:11 UTC, mhegazy requested changes

2017-05-01 20:11 UTC, mhegazy commented on types/leaflet-areaselect/index.d.ts
> +declare global {
use `export as namespace` instead:

```ts
declare namespace L {
    function areaSelect(box: AreaSelectOptions): AreaSelect;

    interface AreaSelectOptions {
      width?: number;
      height?: number;
      keepAspectRatio?: boolean;
    }

    interface Dimension {
      width: number;
      height: number;
    }

    interface AreaSelect {
      addTo(map: Map): Map;
      getBounds(): LatLngBounds;
      remove(): void;
      setDimensions(dim: Dimension): void;
    }
  }
}

export as namespace L;
export = L;
```

2017-05-01 21:27 UTC, awallat commented on types/leaflet-areaselect/index.d.ts
> +declare global {
Ok, thanks for pointing that out!
I added your change request.

2017-05-01 21:31 UTC, mhegazy requested changes

2017-05-01 21:31 UTC, mhegazy commented on types/leaflet-areaselect/index.d.ts
> +declare global {
you do not need `declare global { ` line now.

2017-05-04 21:06 UTC, awallat commented on types/leaflet-areaselect/index.d.ts
> +declare global {
I removed the global declaration, but also removed those export statements since all the other leaflet-plugins are declared similar.
Is it ok? ;)

2017-05-04 23:15 UTC, merged