Update util.inspect in Node.js contract to match docs
DefinitelyTyped/DefinitelyTyped pull request #16234
Opened 2017-04-30 20:40 UTC by JustinBeckwith

Two things here:
1. [util.inspect](https://nodejs.org/dist/latest-v6.x/docs/api/util.html#util_util_inspect_object_options) As of Node.js v6 and beyond has additional properties in the options that were missing
2. I could not find a doc that suggested the method of passing flags in a particular order outside of the opts object was supported, so I deleted that from the contract.  It's possible it works, but it is not documented in the official Node.js docs. If @mylesborins could verify here, that would be nice :) 

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v6.x/docs/api/util.html#util_util_inspect_object_options

2017-05-01 20:43 UTC, mhegazy commented
looks like both work

```sh
C:\Users\mhegazy>node
> const util = require("util");
undefined

> util.inspect(util, false, 2, /*color*/false)
'{ format: [Function],\n  deprecate: [Function],\n  debuglog: [Function],\n  inspect: \n   { [Function: inspect]\n     colors: \n      { bold: [Object],\n        italic: [Object],\n        underline: [Object],\n        inverse: [Object],\n        white: [Object],\n        grey: [Object],\n        black: [Object],\n        blue: [Object],\n        cyan: [Object],\n        green: [Object],\n        magenta: [Object],\n        red: [Object],\n        yellow: [Object] },\n     styles: \n      { special: \'cyan\',\n        number: \'yellow\',\n        boolean: \'yellow\',\n        undefined: \'grey\',\n        null: \'bold\',\n        string: \'green\',\n        symbol: \'green\',\n        date: \'magenta\',\n        regexp: \'red\' },\n     custom: Symbol(util.inspect.custom) },\n  isArray: [Function: isArray],\n  isBoolean: [Function: isBoolean],\n  isNull: [Function: isNull],\n  isNullOrUndefined: [Function: isNullOrUndefined],\n  isNumber: [Function: isNumber],\n  isString: [Function: isString],\n  isSymbol: [Function: isSymbol],\n  isUndefined: [Function: isUndefined],\n  isRegExp: [Function: isRegExp],\n  isObject: [Function: isObject],\n  isDate: [Function: isDate],\n  isError: [Function: isError],\n  isFunction: [Function: isFunction],\n  isPrimitive: [Function: isPrimitive],\n  isBuffer: [Function: isBuffer],\n  log: [Function],\n  inherits: [Function],\n  _extend: [Function],\n  print: [Function: deprecated],\n  puts: [Function: deprecated],\n  debug: [Function: deprecated],\n  error: [Function: deprecated],\n  _errnoException: [Function],\n  _exceptionWithHostPort: [Function] }'

> util.inspect(util, false, 2, /*color*/true)
'{ format: \u001b[36m[Function]\u001b[39m,\n  deprecate: \u001b[36m[Function]\u001b[39m,\n  debuglog: \u001b[36m[Function]\u001b[39m,\n  inspect: \n   { [Function: inspect]\n     colors: \n      { bold: \u001b[36m[Object]\u001b[39m,\n        italic: \u001b[36m[Object]\u001b[39m,\n        underline: \u001b[36m[Object]\u001b[39m,\n        inverse: \u001b[36m[Object]\u001b[39m,\n        white: \u001b[36m[Object]\u001b[39m,\n        grey: \u001b[36m[Object]\u001b[39m,\n        black: \u001b[36m[Object]\u001b[39m,\n        blue: \u001b[36m[Object]\u001b[39m,\n        cyan: \u001b[36m[Object]\u001b[39m,\n        green: \u001b[36m[Object]\u001b[39m,\n        magenta: \u001b[36m[Object]\u001b[39m,\n        red: \u001b[36m[Object]\u001b[39m,\n        yellow: \u001b[36m[Object]\u001b[39m },\n     styles: \n      { special: \u001b[32m\'cyan\'\u001b[39m,\n        number: \u001b[32m\'yellow\'\u001b[39m,\n        boolean: \u001b[32m\'yellow\'\u001b[39m,\n        undefined: \u001b[32m\'grey\'\u001b[39m,\n        null: \u001b[32m\'bold\'\u001b[39m,\n        string: \u001b[32m\'green\'\u001b[39m,\n        symbol: \u001b[32m\'green\'\u001b[39m,\n        date: \u001b[32m\'magenta\'\u001b[39m,\n        regexp: \u001b[32m\'red\'\u001b[39m },\n     custom: \u001b[32mSymbol(util.inspect.custom)\u001b[39m },\n  isArray: \u001b[36m[Function: isArray]\u001b[39m,\n  isBoolean: \u001b[36m[Function: isBoolean]\u001b[39m,\n  isNull: \u001b[36m[Function: isNull]\u001b[39m,\n  isNullOrUndefined: \u001b[36m[Function: isNullOrUndefined]\u001b[39m,\n  isNumber: \u001b[36m[Function: isNumber]\u001b[39m,\n  isString: \u001b[36m[Function: isString]\u001b[39m,\n  isSymbol: \u001b[36m[Function: isSymbol]\u001b[39m,\n  isUndefined: \u001b[36m[Function: isUndefined]\u001b[39m,\n  isRegExp: \u001b[36m[Function: isRegExp]\u001b[39m,\n  isObject: \u001b[36m[Function: isObject]\u001b[39m,\n  isDate: \u001b[36m[Function: isDate]\u001b[39m,\n  isError: \u001b[36m[Function: isError]\u001b[39m,\n  isFunction: \u001b[36m[Function: isFunction]\u001b[39m,\n  isPrimitive: \u001b[36m[Function: isPrimitive]\u001b[39m,\n  isBuffer: \u001b[36m[Function: isBuffer]\u001b[39m,\n  log: \u001b[36m[Function]\u001b[39m,\n  inherits: \u001b[36m[Function]\u001b[39m,\n  _extend: \u001b[36m[Function]\u001b[39m,\n  print: \u001b[36m[Function: deprecated]\u001b[39m,\n  puts: \u001b[36m[Function: deprecated]\u001b[39m,\n  debug: \u001b[36m[Function: deprecated]\u001b[39m,\n  error: \u001b[36m[Function: deprecated]\u001b[39m,\n  _errnoException: \u001b[36m[Function]\u001b[39m,\n  _exceptionWithHostPort: \u001b[36m[Function]\u001b[39m }'

> util.inspect(util, {colors: false } )
'{ format: [Function],\n  deprecate: [Function],\n  debuglog: [Function],\n  inspect: \n   { [Function: inspect]\n     colors: \n      { bold: [Object],\n        italic: [Object],\n        underline: [Object],\n        inverse: [Object],\n        white: [Object],\n        grey: [Object],\n        black: [Object],\n        blue: [Object],\n        cyan: [Object],\n        green: [Object],\n        magenta: [Object],\n        red: [Object],\n        yellow: [Object] },\n     styles: \n      { special: \'cyan\',\n        number: \'yellow\',\n        boolean: \'yellow\',\n        undefined: \'grey\',\n        null: \'bold\',\n        string: \'green\',\n        symbol: \'green\',\n        date: \'magenta\',\n        regexp: \'red\' },\n     custom: Symbol(util.inspect.custom) },\n  isArray: [Function: isArray],\n  isBoolean: [Function: isBoolean],\n  isNull: [Function: isNull],\n  isNullOrUndefined: [Function: isNullOrUndefined],\n  isNumber: [Function: isNumber],\n  isString: [Function: isString],\n  isSymbol: [Function: isSymbol],\n  isUndefined: [Function: isUndefined],\n  isRegExp: [Function: isRegExp],\n  isObject: [Function: isObject],\n  isDate: [Function: isDate],\n  isError: [Function: isError],\n  isFunction: [Function: isFunction],\n  isPrimitive: [Function: isPrimitive],\n  isBuffer: [Function: isBuffer],\n  log: [Function],\n  inherits: [Function],\n  _extend: [Function],\n  print: [Function: deprecated],\n  puts: [Function: deprecated],\n  debug: [Function: deprecated],\n  error: [Function: deprecated],\n  _errnoException: [Function],\n  _exceptionWithHostPort: [Function] }'

> util.inspect(util, {colors: true } )
'{ format: \u001b[36m[Function]\u001b[39m,\n  deprecate: \u001b[36m[Function]\u001b[39m,\n  debuglog: \u001b[36m[Function]\u001b[39m,\n  inspect: \n   { [Function: inspect]\n     colors: \n      { bold: \u001b[36m[Object]\u001b[39m,\n        italic: \u001b[36m[Object]\u001b[39m,\n        underline: \u001b[36m[Object]\u001b[39m,\n        inverse: \u001b[36m[Object]\u001b[39m,\n        white: \u001b[36m[Object]\u001b[39m,\n        grey: \u001b[36m[Object]\u001b[39m,\n        black: \u001b[36m[Object]\u001b[39m,\n        blue: \u001b[36m[Object]\u001b[39m,\n        cyan: \u001b[36m[Object]\u001b[39m,\n        green: \u001b[36m[Object]\u001b[39m,\n        magenta: \u001b[36m[Object]\u001b[39m,\n        red: \u001b[36m[Object]\u001b[39m,\n        yellow: \u001b[36m[Object]\u001b[39m },\n     styles: \n      { special: \u001b[32m\'cyan\'\u001b[39m,\n        number: \u001b[32m\'yellow\'\u001b[39m,\n        boolean: \u001b[32m\'yellow\'\u001b[39m,\n        undefined: \u001b[32m\'grey\'\u001b[39m,\n        null: \u001b[32m\'bold\'\u001b[39m,\n        string: \u001b[32m\'green\'\u001b[39m,\n        symbol: \u001b[32m\'green\'\u001b[39m,\n        date: \u001b[32m\'magenta\'\u001b[39m,\n        regexp: \u001b[32m\'red\'\u001b[39m },\n     custom: \u001b[32mSymbol(util.inspect.custom)\u001b[39m },\n  isArray: \u001b[36m[Function: isArray]\u001b[39m,\n  isBoolean: \u001b[36m[Function: isBoolean]\u001b[39m,\n  isNull: \u001b[36m[Function: isNull]\u001b[39m,\n  isNullOrUndefined: \u001b[36m[Function: isNullOrUndefined]\u001b[39m,\n  isNumber: \u001b[36m[Function: isNumber]\u001b[39m,\n  isString: \u001b[36m[Function: isString]\u001b[39m,\n  isSymbol: \u001b[36m[Function: isSymbol]\u001b[39m,\n  isUndefined: \u001b[36m[Function: isUndefined]\u001b[39m,\n  isRegExp: \u001b[36m[Function: isRegExp]\u001b[39m,\n  isObject: \u001b[36m[Function: isObject]\u001b[39m,\n  isDate: \u001b[36 [...]

2017-05-01 20:44 UTC, mhegazy requested changes
I would keep both APIs

2017-06-01 14:48 UTC, andy-ms commented
See above - please add the old overload back.

2017-06-06 16:43 UTC, yuit commented
Thanks for your contribution. This PR has unaddress comment and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-06-06 16:43 UTC, closed without merging