Change "object" to "Object" in index.d.ts
DefinitelyTyped/DefinitelyTyped pull request #16271
Opened 2017-05-02 14:28 UTC by jbeard4

"object" is now a keyword in Typescript. In Typescript 2.1, this throws an error "Cannot find name 'object'." This change resolves the error.

Please fill in this template.

- [ y ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ y ] Test the change in your own code. (Compile and run.)
- [ y ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ y ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ y ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ y ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Microsoft/TypeScript/issues/14647
- [ n ] Increase the version number in the header if appropriate.
- [ n ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dslint/dt.json" }`.

2017-05-02 15:42 UTC, andy-ms commented
We should probably stop trying to duplicate `lib.es6.d.ts` typings in this package, so you can just use the typings from whatever TypeScript version you have. CC @rbuckton

2017-05-03 17:53 UTC, mhegazy requested changes
This is not the correct change. this will break TS 2.2 users.

2017-05-03 17:54 UTC, mhegazy commented
I wounder if we just should deprecate this package all together.

2017-06-01 18:22 UTC, rbuckton commented
Once we get Microsoft/TypeScript#15780 merged, we can look into [andy's comment](#issuecomment-298674041). I recommend that we don't take this change.

2017-06-01 18:22 UTC, closed without merging

2017-06-01 18:25 UTC, rbuckton commented
@jbeard4 If you still require TypeScript 2.1 support you can use `npm install @types/es6-shim@ts2.1 --save-exact` to install (and lock in) the version of es6-shim prior to the introduction of `object`.