emit ...param:any[]
DefinitelyTyped/DefinitelyTyped pull request #16270
Opened 2017-05-02 14:26 UTC by liudongpu

2017-05-02 14:32 UTC, alloy requested changes
Thanks! Change looks good to me 👍 Just need to fix the linter failure.

2017-05-02 14:32 UTC, alloy commented on types/react-native/index.d.ts
> +    emit(eventType: string,...param:any[]): void
Fix the linter failure like so: `emit(eventType: string, ...param: any[]): void`

2017-05-03 17:52 UTC, mhegazy commented
@liudongpu can you please address the CI test failures

2017-05-08 08:45 UTC, gyzerok commented on types/react-native/index.d.ts
> +    emit(eventType: string,...param:any[]): void
And should maybe variable name be `params`?

2017-05-08 09:21 UTC, alloy commented on types/react-native/index.d.ts
> +    emit(eventType: string,...param:any[]): void
Good point

2017-06-01 14:55 UTC, merged