[reactstrap] Row props extends react.HTMLProps and add noGutters property
DefinitelyTyped/DefinitelyTyped pull request #16286
Opened 2017-05-03 09:08 UTC by pollen8

Currently
```<Row noGutters>```
gives a property does not exist typescript error.
This MR should resolve that.

2017-05-03 18:36 UTC, mhegazy commented
@alihammad and @mfal can you please review this change?

2017-05-08 19:19 UTC, mfal requested changes

2017-05-08 19:19 UTC, mfal commented on types/reactstrap/lib/Row.d.ts
> +interface Props extends React.HTMLProps<any> {
I would say the right interface to extends is `React.HTMLAttributes<HTMLDivElement>`.

2017-05-08 19:19 UTC, mfal commented on types/reactstrap/lib/Row.d.ts
> +interface Props extends React.HTMLProps<any> {
BTW: This is sadly not consistent throughout the whole defs and should be fixed for all components anyhow. @pollen8 I would appreciate your contribution! ;-)

2017-05-30 22:31 UTC, mfal requested changes
Please update your PR

2017-05-30 22:31 UTC, mfal commented on types/reactstrap/lib/Row.d.ts
> +interface Props extends React.HTMLProps<any> {
Hey @pollen8!

If you could specify the typed interface to `React.HTMLProps<HTMLDivElement>` we should merge your PR!

2017-06-06 17:41 UTC, yuit commented
Thanks for your contribution. This PR has unaddress comment and cannot be merged in at the time being. For housekeeping purposes we are closing stale PRs. I have opened another PR that is the same as this one + address PR feedback

2017-06-06 17:41 UTC, closed without merging