add jpush-react-native
DefinitelyTyped/DefinitelyTyped pull request #16387
Opened 2017-05-08 16:58 UTC by huhuanming

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-05-10 03:51 UTC, huhuanming commented
@mhegazy  
it's pass all test.
Could you help me merge it?

2017-05-11 09:01 UTC, huhuanming commented
A massive PR backlog need to do.
@mhegazy 
can I join in and help it?

2017-05-12 17:42 UTC, huhuanming commented
@sandersn
sorry....

2017-05-14 09:14 UTC, huhuanming commented
@DanielRosenwasser  😳 Could you help me merge it?

2017-05-14 17:44 UTC, DanielRosenwasser requested changes
Other than my comment this looks good and accurate. Let me know when you send out the changes and I can merge it in.

2017-05-14 17:44 UTC, DanielRosenwasser commented on types/jpush-react-native/index.d.ts
> +    static setAlias(alias: string, successCallback: (resultCode: number[]) => void, failedCallback: () => void): void;
From the source, it looks like `successCallback` never gets called with parameters.

2017-05-14 17:44 UTC, DanielRosenwasser commented on types/jpush-react-native/index.d.ts
> +    static setAlias(alias: string, successCallback: (resultCode: number[]) => void, failedCallback: () => void): void;
What about `setAliasAndTags`?

2017-05-14 17:45 UTC, DanielRosenwasser requested changes

2017-05-14 17:45 UTC, DanielRosenwasser commented on types/jpush-react-native/index.d.ts
> +    static setTags(tags: string[], successCallback: (resultCode: number[]) => void, failedCallback: () => void): void;
From the source, it looks like `successCallback` never gets called with parameters.

2017-05-15 00:59 UTC, huhuanming commented
Thank you for Reviewing

I fixed `successCallback` and  added `setAliasAndTags` .

2017-05-15 15:46 UTC, huhuanming commented
@DanielRosenwasser 
😳 Can we go on?

2017-05-15 22:17 UTC, merged