Added optional index argument to FlatList renderItem prop
DefinitelyTyped/DefinitelyTyped pull request #16634
Opened 2017-05-19 10:56 UTC by sverrejoh

The index argument is missing from the definition:

https://facebook.github.io/react-native/docs/flatlist.html#renderitem

2017-05-19 12:35 UTC, alloy requested changes

2017-05-19 12:35 UTC, alloy commented on types/react-native/index.d.ts
> +    renderItem: (info: ItemT, index: number) => React.ReactElement<any> | null
This actually seems wrong altogether, there should be 1 parameter, which is `info`, which is an object that holds `item` and `index`, just like is done in the [`SectionListData` interface](https://github.com/sverrejoh/DefinitelyTyped/blob/f0231257f101cec786c450811ec8b5cf90b6e3f4/types/react-native/index.d.ts#L3578).

Having said that, both [`FlatList`](https://facebook.github.io/react-native/docs/flatlist.html#renderitem) and [`SectionList`](https://facebook.github.io/react-native/docs/sectionlist.html) wrap [`VirtualizedList`](https://facebook.github.io/react-native/docs/virtualizedlist.html), which is the one that _actually_ has these shared props, so I think it’s best if you could add an interface for `VirtualizedList` and extend both `SectionList` and `FlatList` from it.

2017-05-19 16:54 UTC, huhuanming commented on types/react-native/index.d.ts
> +    renderItem: (info: ItemT, index: number) => React.ReactElement<any> | null
I think so and will add `VirtualizedList ` in recent days.

2017-05-20 13:16 UTC, sverrejoh commented on types/react-native/index.d.ts
> +    renderItem: (info: ItemT, index: number) => React.ReactElement<any> | null
Right, I see I see. I was a little trigger happy there. Thanks for the feedback!

2017-05-20 13:16 UTC, closed without merging

2017-08-04 01:19 UTC, zachkirsch commented on types/react-native/index.d.ts
> +    renderItem: (info: ItemT, index: number) => React.ReactElement<any> | null
@huhuanming any update on adding `VirtualizedList`?

2017-08-04 01:28 UTC, huhuanming commented on types/react-native/index.d.ts
> +    renderItem: (info: ItemT, index: number) => React.ReactElement<any> | null
will be updated lately, I get sick now... 😳