Add resolves to Jest Matchers interface
DefinitelyTyped/DefinitelyTyped pull request #16645
Opened 2017-05-19 18:47 UTC by garbles

`.resolves` was added in Jest 20. https://facebook.github.io/jest/docs/en/expect.html#resolves

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-05-23 17:44 UTC, mdebruijne commented
Please note that resolves and rejects is not of type Matchers, because the matchers in interface Matchers have return type void, but the matchers after resolves and rejects should have return type Promise.

2017-05-23 19:03 UTC, garbles commented
@mdebruijne Thank you! Please see the new commit.

Also worth noting that this also fixes another issue which I've noted in the description:

`- Also fixed return types for the `toHaveBeenCalledX` matchers as they return `undefined` and not a boolean.`

2017-05-23 19:51 UTC, mdebruijne commented
@garbles awesome, thanks!

2017-05-25 16:48 UTC, Apidcloud commented
May I ask if this is the reason `expect.resolves` isn't working on typescript yet?

I'm still new to typescript, so I'm trying to get my head around typings.

2017-05-25 16:57 UTC, garbles commented
@Apidcloud this is the reason 😃

2017-05-25 16:59 UTC, Apidcloud commented
Thank you, @garbles ! Will this be available on @types/node and/or @types/jest when merged?

2017-05-25 17:00 UTC, garbles commented
@Apidcloud no idea when it will be merged. my first PR to DefinitelyTyped

2017-05-28 10:04 UTC, Fahrradflucht commented
@garbles since this is a jest v20 feature the jest version header should probably be incremented to the jest version you tested this against...

2017-05-29 22:06 UTC, artemyarulin commented
Didn't find this PR at first and created this issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/16803. Actually the one which is missing from this PR is `New expect.hasAssertions() function similar to expect.assertions().`

Probably I can save a few seconds of your time - you can copy it from here and put it under `interface Expect`:
```
/** Verifies that at least one assertion is called during a test. This is often useful when testing asynchronous code, in order to make sure that assertions in a callback actually got called. */
hasAssertions(): void;
```

2017-05-29 23:18 UTC, garbles commented
Done and done. Thanks @Fahrradflucht, @artemyarulin

2017-05-31 15:02 UTC, clebert commented
The following methods are currently not formatted correctly:

Previous:

```js
toHaveBeenCalled(): boolean;
toHaveBeenCalledTimes(expected: number): boolean;
toHaveBeenCalledWith(...params: any[]): boolean;
toHaveBeenLastCalledWith(...params: any[]): boolean;
```

Current:

```js
toHaveBeenCalled(): R;
toHaveBeenCalledTimes(expected: number): R;
toHaveBeenCalledWith(...params: any[]): R;
toHaveBeenLastCalledWith(...params: any[]): R;
```

I would suggest the following typing:

```
interface Matchers<R=void, S=boolean> {
  resolves: Matchers<Promise<R>, Promise<S>>;

  // ...

  toBe(expected: any): R;

  // ...

  toHaveBeenCalled(): S;

  // ...
}
```

2017-05-31 16:28 UTC, garbles commented
@clebert `expect(fn).toHaveBeenCalled()` returns `void`. The follow spec passes.

```js
test('', () => {
  const a = jest.fn();
  a();
  const result = expect(a).toHaveBeenCalled();
  expect(result).toEqual(undefined);
});
```

2017-05-31 16:32 UTC, clebert commented
@garbles Okay, then probably the previous typing is wrong.

2017-05-31 16:33 UTC, garbles commented
@clebert yea I think so! 😄

2017-06-01 17:26 UTC, mhegazy commented on types/jest/index.d.ts
> +    interface Matchers<R> {
why is this generic? i only see one use of it, and it takes `void`.
can you share references to the docs that clarify this change?

2017-06-01 17:26 UTC, mhegazy requested changes
why has `Matchers` become generic?

2017-06-02 00:03 UTC, garbles commented on types/jest/index.d.ts
> +    interface Matchers<R> {
`resolves` and `rejects` return `Matchers<Promise<void>>`. How should I make this change without introducing parameters?

2017-06-05 22:34 UTC, garbles commented
@mhegazy Have you had a chance to review my comment?

> resolves and rejects return Matchers<Promise<void>> while not returns Matchers<void>. How should I make this change without introducing parameters?

2017-06-12 04:13 UTC, dandv commented
Can this please be sorted out? I wanted to add [`stringContaining`](http://facebook.github.io/jest/docs/en/expect.html#expectstringcontainingstring) but this PR changes the return type for matchers and I'm not sure what I should use.

2017-06-15 07:30 UTC, DanielRosenwasser commented on types/jest/index.d.ts
> +    interface Matchers<R> {
Ping @mhegazy - this seems pretty strange behavior but it doesn't seem unreasonable. are you okay to pull this in?

2017-06-15 22:57 UTC, merged