Updated YouTube to include 'playsinline' parameter
DefinitelyTyped/DefinitelyTyped pull request #16670
Opened 2017-05-22 13:31 UTC by eliotfallon213

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/youtube/player_parameters#playsinline
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-05-23 19:05 UTC, DanielRosenwasser commented on types/youtube/index.d.ts
> +		playsinline?: number;
Sorry to be pedantic, but could you change this to `0 | 1`?

2017-05-30 13:27 UTC, eliotfallon213 commented
@DazWilkin @ianobermiller @JoshuaKGoldberg Just need to bump this as I could really do with this feature getting in as soon as I can.

2017-05-30 14:54 UTC, JoshuaKGoldberg approved these changes

2017-05-30 14:54 UTC, JoshuaKGoldberg commented
:+1:

2017-05-31 23:24 UTC, DanielRosenwasser requested changes

2017-05-31 23:24 UTC, DanielRosenwasser commented on types/youtube/index.d.ts
> +		playsinline?: PlaysInline;
There really shouldn't be of the const enum type because this means that a user cannot just pass `0` or `1` like in plain JS code.

2017-05-31 23:25 UTC, DanielRosenwasser commented on types/youtube/index.d.ts
> +		playsinline?: PlaysInline;
To follow up, you can leave the const enum as a declaration, but it shouldn't be used here for the type of `playsinline`.

2017-06-01 09:59 UTC, eliotfallon213 commented on types/youtube/index.d.ts
> +		playsinline?: PlaysInline;
@DanielRosenwasser But this is the convention already present in this file. It's the exact same as used for Loop, ShowInfo, ModestBranding, etc.

2017-06-01 18:52 UTC, JoshuaKGoldberg commented on types/youtube/index.d.ts
> +		playsinline?: PlaysInline;
If the convention in the file is wrong, can you fix it? It should be fairly straightforward.

2017-06-02 11:44 UTC, eliotfallon213 commented on types/youtube/index.d.ts
> +		playsinline?: PlaysInline;
@JoshuaKGoldberg @DanielRosenwasser I'm happy to change it if you guys think the convention is wrong? I've just followed what was there. What I'd put forward originally didn't restrict the value to 1 or a 0.

2017-06-02 16:46 UTC, mhegazy commented on types/youtube/index.d.ts
> +		playsinline?: PlaysInline;
@DanielRosenwasser can you explain what you mean, numbers are assignable to enums any ways.

2017-06-06 22:44 UTC, DanielRosenwasser approved these changes

2017-06-06 22:44 UTC, DanielRosenwasser commented on types/youtube/index.d.ts
> +		playsinline?: PlaysInline;
D'oh, you're right, sorry about that :/

2017-06-06 22:44 UTC, merged

2017-06-07 16:07 UTC, yuukive commented
Great fix!
Will it be also available via @types soon?