[koa-generic-session] Types for koa.Context
DefinitelyTyped/DefinitelyTyped pull request #16671
Opened 2017-05-22 14:31 UTC by Ragg-

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
  - But got below errors
    ```
    ./DefinitelyTyped/types/koa-generic-session/index.d.ts
    ERROR: 58:30  expect  TypeScript compile error: Cannot find name 'Generator'.

    ./DefinitelyTyped/types/koa-generic-session/koa-generic-session-tests.ts
    ERROR: 43:21  expect  TypeScript compile error: Property 'key' does not exist on type 'Session'.
    ````

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/koajs/generic-session#example
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-05-23 13:05 UTC, nsimmons requested changes

2017-05-23 13:05 UTC, nsimmons commented on types/koa-generic-session/index.d.ts
> +        regenerateSession(): Generator;
Where is `Generator` defined? It either needs to be defined here or imported from somewhere.

2017-05-23 13:05 UTC, nsimmons commented on types/koa-generic-session/koa-generic-session-tests.ts
> +    context.session.key = 'value';
You can't access the session keys like this when you define it with `[key: string]: any;`. 

`context.session['key'] = 'value';` should work.

2017-05-24 01:10 UTC, Ragg- commented on types/koa-generic-session/index.d.ts
> +        regenerateSession(): Generator;
`Generator` defined in `lib.es6.ts` from TypeScript starndard library.
This type definition already setting up to import `es6`  lib, but got error 🤔 https://github.com/Ragg-/DefinitelyTyped/blob/8117819ce704fe73c3ac9f0db5cb9dfbf2b70f01/types/koa-generic-session/tsconfig.json#L5

2017-05-24 13:05 UTC, nsimmons commented on types/koa-generic-session/index.d.ts
> +        regenerateSession(): Generator;
Oh I see.... hmm not sure what's wrong.

2017-06-01 14:38 UTC, Ragg- commented on types/koa-generic-session/index.d.ts
> +        regenerateSession(): Generator;
`Generator` is defined since TypeScript 2.3, but linter is using < 2.3.

2017-06-02 14:28 UTC, andy-ms commented
Thanks! Issue was Microsoft/dtslint#43

2017-06-02 14:28 UTC, merged