update packageName:rangy definitions
DefinitelyTyped/DefinitelyTyped pull request #16686
Opened 2017-05-23 06:35 UTC by ashubham

Update type definitions for the Rangy Module.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/timdown/rangy/wiki/Text-Range-Module
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-05-23 06:36 UTC, ashubham commented
@MidnightDesign

2017-05-23 06:58 UTC, MidnightDesign commented
Tests are missing.

2017-05-23 08:30 UTC, ashubham commented
@MidnightDesign I cannot see any tests defined for any package types. Am I missing something ? Did you mean the travis build ? That should be passing now.

2017-05-23 09:53 UTC, MidnightDesign requested changes

2017-05-23 09:53 UTC, MidnightDesign commented on types/rangy/index.d.ts
> +    saveCharacterRanges(containerNode:Node): Object;
Please keep the style consistent. (Space before `Object`)

2017-05-23 09:53 UTC, MidnightDesign commented on types/rangy/index.d.ts
> +declare module 'rangy' {
This is not tested, is it?

2017-05-23 09:53 UTC, MidnightDesign commented on types/rangy/index.d.ts
> +    getRangeAt(idx:number):RangyRange;
This function has no test.

2017-05-23 10:01 UTC, ashubham commented on types/rangy/index.d.ts
> +declare module 'rangy' {
@MidnightDesign Do you have any ideas of how this could be tested ?

2017-05-23 10:05 UTC, ashubham commented on types/rangy/index.d.ts
> +    getRangeAt(idx:number):RangyRange;
Done

2017-05-23 10:05 UTC, ashubham commented on types/rangy/index.d.ts
> +    saveCharacterRanges(containerNode:Node): Object;
Done

2017-05-23 10:42 UTC, MidnightDesign commented on types/rangy/index.d.ts
> +declare module 'rangy' {
I don't know either. Nevermind.

2017-05-23 10:42 UTC, MidnightDesign commented
LGTM. Thanks for the contribution!

2017-05-23 10:46 UTC, MidnightDesign approved these changes

2017-05-23 22:35 UTC, ashubham commented
@DanielRosenwasser Please merge whenever you get a chance.

2017-05-30 18:42 UTC, merged

2017-05-30 18:42 UTC, DanielRosenwasser commented
Sorry about that! Thanks for the PR.