Superagent: Added support for multiple timeouts
DefinitelyTyped/DefinitelyTyped pull request #16757
Opened 2017-05-26 20:07 UTC by ricardo-mello

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://visionmedia.github.io/superagent/#timeouts>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Closes #16756

2017-06-01 05:38 UTC, mhegazy requested changes

2017-06-01 05:38 UTC, mhegazy commented on types/superagent/index.d.ts
> +      timeout(ms: number | Object | { response: number, read: number, deadline: number }): this;
Did you mean 'object'?

2017-06-01 05:50 UTC, ricardo-mello commented
@mhegazy I copied the `Object` param from superagent signature, but it's really not necessary. Updated the branch.

2017-06-01 05:53 UTC, ricardo-mello commented on types/superagent/index.d.ts
> +      timeout(ms: number | Object | { response: number, read: number, deadline: number }): this;
@mhegazy I copied the Object param from superagent signature, but it's really not necessary. Updated the branch.

2017-06-02 10:26 UTC, mxl commented
@ricardo-mello superagent v2.x [does not have](https://github.com/visionmedia/superagent/blob/v2.3.0/lib/request-base.js#L55) these options in `req.timeout()` method. I'm preparing PR with superagent v3 definitions and suggest to rebase your changes on master after merging that PR.

2017-06-02 20:07 UTC, mxl commented
@ricardo-mello @mhegazy Please look at #16920

2017-06-08 02:36 UTC, ricardo-mello commented
@mxl you're right. I forgot to change the version, but if you're working on all the features of the new version, this PR is unnecessary.

2017-06-13 18:47 UTC, closed without merging