Added noble callback function signatures
DefinitelyTyped/DefinitelyTyped pull request #16898
Opened 2017-06-01 17:27 UTC by LukeL99

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
Start Scanning
https://github.com/sandeepmistry/noble#start-scanning
Stop Scanning
https://github.com/sandeepmistry/noble/blob/master/lib/noble.js#L129
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-06-01 17:33 UTC, mhegazy requested changes

2017-06-01 17:33 UTC, mhegazy commented on types/noble/index.d.ts
> +export declare function startScanning(callback: Function): void;
do not use `Function` use `(....): void`

2017-06-01 17:33 UTC, mhegazy commented on types/noble/index.d.ts
> +export declare function stopScanning(callback: Function): void;
combine with previous signature, 
```ts
export declare function stopScanning(callback?: Function)
```

2017-06-01 17:58 UTC, LukeL99 commented on types/noble/index.d.ts
> +export declare function startScanning(callback: Function): void;
Not exactly sure what you mean here. Would this be better?

`export declare function startScanning(callback?: (error?: Error) => void): void;`

2017-06-01 17:58 UTC, LukeL99 commented on types/noble/index.d.ts
> +export declare function stopScanning(callback: Function): void;
:+1: I thought I read that was a bad practice in the FAQ, but I realized that was only for getters/setters.

2017-06-04 17:52 UTC, swook commented
Hello @LukeL99  please merge with branch master again to have this PR ready for merging.

2017-06-12 15:01 UTC, merged

2017-06-12 19:41 UTC, LukeL99 commented
Sorry @swook & @yuit , was traveling. Thanks for merging!

:+1: