Add definitions for superagent 3.5
DefinitelyTyped/DefinitelyTyped pull request #16920
Opened 2017-06-02 20:06 UTC by mxl

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - `request.on('progress', ...)` - [superagent/progress-tracking](https://github.com/visionmedia/superagent/blob/master/docs/index.md#progress-tracking)
  - attaching blobs - `lib/client.js` [uses](https://github.com/visionmedia/superagent/blob/v3.5.1/lib/client.js#L580) `FormData.append()` method which `value` parameter [has](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.es6.d.ts#L9912) `string | Blob` type

- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-06-05 04:22 UTC, aleung commented
@mxl Could you show me a reference about the usage of `TypeScript Version:` in header? I can't find it in http://definitelytyped.org/guides/contributing.html

2017-06-05 05:02 UTC, mhegazy requested changes

2017-06-05 05:02 UTC, mhegazy commented on types/superagent-no-cache/index.d.ts
> +export default plugin;
Export= instead.

2017-06-05 05:02 UTC, mhegazy commented on types/superagent-no-cache/index.d.ts
> +export default plugin;
See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default

2017-06-05 08:06 UTC, mxl commented
@aleung promisify-superagent definitions uses superagent definitions which need TypeScript 2.2.

2017-06-05 23:34 UTC, mhegazy commented on types/superagent-prefix/index.d.ts
> +export default function(prefix: string): request.Plugin;
here as well. should be `export =`

2017-06-05 23:43 UTC, mxl commented on types/superagent-prefix/index.d.ts
> +export default function(prefix: string): request.Plugin;
@mhegazy I tried but build fails https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/239514755 with
> Module '"/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/superagent-prefix/index"' resolves to a non-module entity and cannot be imported using this construct.

It seems that it doesn't work with functions - https://github.com/Microsoft/TypeScript/issues/5073. Any thoughts?

2017-06-06 00:01 UTC, andy-ms commented on types/superagent-prefix/index.d.ts
> +export default function(prefix: string): request.Plugin;
An `export =` should be matched by an `import =`, as in `import plugin = require('superagent-no-cache');`.
You could also add an `export namespace plugin {}` to make the `import *` work...

2017-06-06 05:53 UTC, aleung commented
@mxl I searched a bit. The `TypeScript Version` header is used by [types-publisher](https://github.com/Microsoft/types-publisher). Though there is no clear document on this header, I believe it describes what typescript version feature is in used in current typing file.

If `superagent` definition needs typescript 2.2, it should already have define `TyepScript Version` in its header.

2017-06-06 09:00 UTC, mxl commented
@aleung Yes, it defines `TypeScript Version: 2.2` in its header. But because promisify-superagent uses superagent, it's also should define `TypeScript Version: 2.2` in its header. Otherwise as I understand when promisify-superagent definitions are tested TypeScript version 2.0 (https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-21-or-above) will be loaded and it will fail on importing superagent because its definitions have newer syntax.

2017-06-06 13:35 UTC, andy-ms commented
CC package authors @varju @NicoZelaya

2017-06-06 15:40 UTC, aleung commented
I am OK with the change on `types/promisify-supertest/index.d.ts`.
👍

2017-06-13 19:21 UTC, mxl commented
@varju @NicoZelaya Could you review?

2017-06-13 19:22 UTC, ricardo-mello commented
Closes #16756

2017-06-13 19:24 UTC, varju commented
I haven't been active in this community for years.  Is there a way to unsubscribe permanently from this repo?

2017-06-13 19:26 UTC, mxl commented
@varju Should I remove you from these definitions authors?

2017-06-13 19:26 UTC, varju commented
Yes.  If that's an option, that would be awesome, thank you.

2017-06-15 14:47 UTC, merged