[Mongodb] MongoClient.connection() options v2.2.
DefinitelyTyped/DefinitelyTyped pull request #16932
Opened 2017-06-02 23:56 UTC by hinell

## Changes 
- Upd :chart_with_upwards_trend: ``MongoClientOptions`` interface for ``... .connect(..., options)`` method from [v2.1.][v21] to [v2.2.][v22].
- - Removes duplicate props
- - Removes [obsolete][uridecodeobsolete] ``uri_decode_auth`` property
- - New tests for ``MongoClient.connect(..., options)``
- - Features more docs
Summary, these interfaces were revised: 
```

[v21]: http://mongodb.github.io/node-mongodb-native/2.1/api/MongoClient.html#connect
[v22]: http://mongodb.github.io/node-mongodb-native/2.2/api/MongoClient.html#connect
[uridecodeobsolete]: https://github.com/mongodb/node-mongodb-native/blob/33238a28bcfffbd08a2f52418ce96aab7a28f0fe/HISTORY.md#2225-2017-03-17
<details>
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.
</details>

2017-06-03 00:21 UTC, andy-ms commented on types/mongodb/index.d.ts
> +// TypeScript Version: 2.3'
Extra `'` on the end

2017-06-03 00:34 UTC, hinell commented on types/mongodb/index.d.ts
> +// TypeScript Version: 2.3'
:expressionless: Ahhh.. such a small feature and already ruines all travis checking.

2017-06-04 10:32 UTC, CaselIT commented on types/mongodb/index.d.ts
>  export interface DbCreateOptions {
Since only the formatting has changed I would keep the original one to keep a cleaner history

2017-06-04 10:32 UTC, CaselIT commented on types/mongodb/index.d.ts
>  export interface SocketOptions {
Same here

2017-06-04 10:32 UTC, CaselIT commented on types/mongodb/index.d.ts
>  export interface ServerOptions {
This one is not correct as per documentation

2017-06-04 10:32 UTC, CaselIT commented on types/mongodb/index.d.ts
>  export interface MongosOptions {
This is also not correct, see the documentation

2017-06-04 10:37 UTC, CaselIT commented
@hinell I've left a review.

As a side note: I'm not a fan of your formatting style but I guess it's ok on the new contributions you provide since I don't think DT enforce a particular style. I just don't think it's a good idea to reformat the existing code since it unnecessarily changed their history

2017-06-04 12:19 UTC, hinell commented on types/mongodb/index.d.ts
>  export interface DbCreateOptions {
Are you meaning the <space> between ``//`` and ``http`` when talking about formatting?

2017-06-04 12:25 UTC, hinell commented on types/mongodb/index.d.ts
>  export interface ServerOptions {
What exactly?

2017-06-04 12:34 UTC, hinell commented on types/mongodb/index.d.ts
>  export interface DbCreateOptions {
I have indented comments cause they are quite unreadable when stacked one their respective code.

2017-06-04 12:37 UTC, CaselIT commented on types/mongodb/index.d.ts
>  export interface DbCreateOptions {
I meant the spacing between the property name and the type and the type and the `;`

2017-06-04 12:39 UTC, CaselIT commented on types/mongodb/index.d.ts
>  export interface ServerOptions {
`ServerOptions` only 3 property instead of the 16 in the documentation

2017-06-04 13:01 UTC, hinell commented
>I'm not a fan of your formatting style

These style changes doesn't introduce any reading difficulties and doesn't reduce docs quality at all.
and could be easily brought back. 

>since it unnecessarily changed their history

Well purity of the DT history is not subject of matter seriously.

2017-06-04 13:03 UTC, CaselIT commented
@hinell that was just my personal opinion.

2017-06-04 13:13 UTC, hinell commented on types/mongodb/index.d.ts
>  export interface ServerOptions {
These are already fixed in the next commit that will be sent soon. There is an error in the MongosOptions, SocketOptions and ReplSetOptions as well.

2017-06-04 13:17 UTC, hinell commented on types/mongodb/index.d.ts
>  export interface DbCreateOptions {
Do you think these spacing between ``prop`` and ``?:`` and ``type`` and ``// comment`` lowering quality of the code? 😶

2017-06-04 13:19 UTC, hinell commented
@CaselIT Ah, It's fine. 😄

2017-06-04 21:12 UTC, mhegazy commented
@CaselIT mind taking one more look.

2017-06-05 08:02 UTC, CaselIT requested changes

2017-06-05 08:02 UTC, CaselIT commented on types/mongodb/index.d.ts
> +export interface SocketOptions extends SSLOptions, HighAvailabilityOptions{
`SocketOption` should not extend `SSLOptions`, `HighAvailabilityOptions` (at least according to the documentation here http://mongodb.github.io/node-mongodb-native/2.2/api/Server.html)

2017-06-05 08:02 UTC, CaselIT commented on types/mongodb/index.d.ts
> +export interface ServerOptions extends SSLOptions, HighAvailabilityOptions{
I'm not sure if the `ha?: boolean;` from `HighAvailabilityOptions` is present in the `ServerOptions`

2017-06-05 08:02 UTC, CaselIT commented on types/mongodb/index.d.ts
>  export interface ReplSetOptions {
I think `ReplSetOptions` should extend `SSLOptions` and `HighAvailabilityOptions`

2017-06-05 09:29 UTC, hinell commented on types/mongodb/index.d.ts
> +export interface ServerOptions extends SSLOptions, HighAvailabilityOptions{
I've discovered that options from``HighAvailabilityOptions`` interface are legal for all three classes (i.e. [Server][s], [Mongos][m] and [Replset][r]) but a few actually used inside the source code.

[s]: ../../../mongodb/node-mongodb-native/blob/2.2/lib/server.js#L47
[m]: ../../../mongodb/node-mongodb-native/blob/2.2/lib/mongos.js#L50
[r]: ../../../mongodb/node-mongodb-native/blob/2.2/lib/replset.js#L43

2017-06-05 09:31 UTC, CaselIT commented on types/mongodb/index.d.ts
> +export interface ServerOptions extends SSLOptions, HighAvailabilityOptions{
yes, I thought the same. It's ok for me to leave it

2017-06-05 10:19 UTC, CaselIT commented
Looks good now 👍

2017-06-05 10:55 UTC, hinell commented
@CaselIT Don't forget to approve your review in top-right corner of the page . :blush:

2017-06-05 11:14 UTC, CaselIT approved these changes

2017-06-05 11:14 UTC, CaselIT commented
@hinell sorry, I'm not very familiar with the github review procedure. It should be approved now

2017-06-05 11:16 UTC, hinell commented
@CaselIT Thanks! 👍

2017-06-05 13:31 UTC, merged