[nouislider]: Fix TSC error. Fix Callback signature (unencodedValues)
DefinitelyTyped/DefinitelyTyped pull request #17129
Opened 2017-06-12 15:52 UTC by christophercr

Fix TSC error: "global module exports may only appear at top level" (remove wrong duplicate namespace export).

Fix Callback interface: unencodedValues is an array of values instead of single value.

2017-06-15 07:21 UTC, DanielRosenwasser commented
I don't understand - you're still going to get an error when using this as a global, so now nobody can use this module as a UMD global.

2017-06-16 10:59 UTC, christophercr commented
Oh yeah, right, I overlooked that, I'll fix it to make it global but without having the TSC error...

2017-06-16 11:13 UTC, christophercr commented
I've converted it to module global, so you can use it as a global (also UMD):

`import * as noUiSlider from "nouislider";
import noUiSlider = require("nouislider");`

2017-06-17 00:32 UTC, minestarks commented
What TSC error are you trying to fix? Can you provide an example or a test? The imports work just as fine before and after your change, while using it as a global is now broken.

2017-06-19 09:22 UTC, christophercr commented
Well, I solved a TSC error: "global module exports may only appear at top level" caused by the "export as namespace nouislider" line. I use typescript 2.3.x.

And thanks to comment from @DanielRosenwasser I made it a global module (you got an error when you tried it as global dependency, so before they were in fact a module dependency).

2017-06-26 17:30 UTC, paulvanbrenk commented
@DanielRosenwasser, @bleuarg, or @Lagaffe does this look correct.

2017-07-12 21:08 UTC, RyanCavanaugh commented
This isn't a correct fix. You need to **not** undo the UMD declaration (`export as namespace ...`).

2017-07-12 22:17 UTC, RyanCavanaugh requested changes

2017-07-12 22:17 UTC, RyanCavanaugh commented on types/nouislider/index.d.ts
> -export as namespace noUiSlider;
Don't remove this line

2017-07-13 12:34 UTC, christophercr commented on types/nouislider/index.d.ts
> -export as namespace noUiSlider;
You're right. I've added back the UMD declaration.

I also took the chance to add a missing option and use literal types where necessary ;)

2017-07-13 17:18 UTC, merged

2017-07-14 13:50 UTC, teppeis commented
@RyanCavanaugh When this PR was merged, the CI job was failed and all packages updated after this merge are not published to npm.

- https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/253300526
- https://www.npmjs.com/package/@types/nouislider
- https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master?after=c113d3ad62a3d4535b7493fccfc3c020c8d79487+69

2017-07-15 02:39 UTC, teppeis commented
published