Update to the swagger-parser module
DefinitelyTyped/DefinitelyTyped pull request #17156
Opened 2017-06-13 15:34 UTC by EricHenry

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-06-15 21:12 UTC, Tobias4872 commented
Hi Henry,

looks good to me. Much more complete now. On a side note, I have no clue how you derived the option structure. Tried to trace this down in "json-schema-ref-parser/lib/options", but did not get a handle. You obviously did, so good work.

Tobias.

2017-06-15 23:51 UTC, minestarks commented
@EricHenry please fix the failing tests before we can merge, thank you!

2017-06-16 11:37 UTC, EricHenry commented
@Tobias4872 the source code isn't the greatest at defining what the option structure looks like, but the docs make up for that! [check it out here](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/options.md)

@minestarks will do!

2017-06-16 18:02 UTC, minestarks requested changes

2017-06-16 18:02 UTC, minestarks commented on types/swagger-parser/index.d.ts
> +export function parse(api: string | any, options?: Options): Promise<any>;
```string | any``` is rather misleading, as it's the same exact type as ```any``` so it doesn't provide any stronger type checking.

Furthermore the docs state this should be a [SwaggerObject](https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/swagger-parser.md#parseapi-options-callback) 

How about defining a ```Swagger``` interface and having the argument be ```string | Swagger``` ? 

If you'd rather not do that, then I'd say convert all the ```string | any```s to ```any```s.

2017-06-19 17:23 UTC, EricHenry commented on types/swagger-parser/index.d.ts
> +export function parse(api: string | any, options?: Options): Promise<any>;
I think this is a good idea. There is an [official swagger schema](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/swagger-schema-official) type defined in the DefinitelyTyped project. Is there a supported way to reference that type, inside of this project definition?

2017-06-19 19:40 UTC, minestarks commented on types/swagger-parser/index.d.ts
> +export function parse(api: string | any, options?: Options): Promise<any>;
Yes, you can do:
```ts
import { Spec } from "swagger-schema-official";
```
See https://github.com/DefinitelyTyped/DefinitelyTyped#im-writing-a-definition-that-depends-on-another-definition-should-i-use-reference-types--or-an-import

2017-06-19 19:45 UTC, minestarks approved these changes

2017-06-19 19:47 UTC, minestarks commented on types/swagger-parser/index.d.ts
> +import { Spec as Swagger } from '../swagger-schema-official';
You'll want to change this to ```'swagger-schema-official'``` (non-relative)

2017-06-19 21:31 UTC, merged

2017-06-19 21:31 UTC, sandersn commented on types/swagger-parser/index.d.ts
> +import { Spec as Swagger } from '../swagger-schema-official';
I went ahead and did this.

2017-06-19 21:49 UTC, EricHenry commented on types/swagger-parser/index.d.ts
> +import { Spec as Swagger } from '../swagger-schema-official';
@sandersn thanks! glad I could contribute. Thanks for the guidance and helpful feedback! @minestarks