ramda: Add R.pathSatisfies
DefinitelyTyped/DefinitelyTyped pull request #17158
Opened 2017-06-13 16:36 UTC by afharo

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: http://ramdajs.com/docs/#pathSatisfies
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-06-16 00:10 UTC, minestarks requested changes

2017-06-16 00:10 UTC, minestarks commented on types/ramda/index.d.ts
> +    type ListIterator<T, TResult> = (value: T, index: number, list: T[]) => TResult;
This type isn't used anywhere.

2017-06-16 00:10 UTC, minestarks commented on types/ramda/index.d.ts
> +    type ObjectIterator<T, TResult> = (element: T, key: string, obj: Dictionary<T>) => Dictionary<TResult>;
Same here, it's not used anywhere

2017-06-16 00:10 UTC, minestarks commented on types/ramda/index.d.ts
> +    }
Fix weird newline please

2017-06-16 08:48 UTC, afharo commented on types/ramda/index.d.ts
> +    type ListIterator<T, TResult> = (value: T, index: number, list: T[]) => TResult;
You are right! Removed!

2017-06-16 08:48 UTC, afharo commented on types/ramda/index.d.ts
> +    type ObjectIterator<T, TResult> = (element: T, key: string, obj: Dictionary<T>) => Dictionary<TResult>;
You are right! Removed!

2017-06-16 08:48 UTC, afharo commented on types/ramda/index.d.ts
> +    }
Fixed

2017-06-16 08:52 UTC, afharo commented
@minestarks Fixed your comments (thank you, btw). Can you have a second look?

2017-06-16 17:37 UTC, minestarks approved these changes

2017-06-16 17:37 UTC, merged

2017-06-19 17:00 UTC, afharo commented
Can these changes be npm published?
It looks like there was an `npm publish` just after the merge, but if I update my package, my changes are still missing :(

2017-06-19 19:36 UTC, minestarks commented
@afharo I see them now.

2017-06-20 12:19 UTC, afharo commented
@minestarks yeah! now working! thank you!