fix(cordova-plugin-inappbrowser): add missing entry of InAppBrowser to Cordova interface
DefinitelyTyped/DefinitelyTyped pull request #17192
Opened 2017-06-14 18:27 UTC by timbru31

This PR adds the missing interface entry of `InAppBrowser` to `Cordova` in order to fix `Property 'InAppBrowser' does not exist on type 'Cordova'.`
Besides that it enables linting of the types and fixes the reported errors.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/apache/cordova-plugin-inappbrowser#cordovainappbrowseropen
- [x] There is an open issue on StackOverflow for the missing entry: https://stackoverflow.com/q/42095516/1902598
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-06-14 21:45 UTC, timbru31 commented
Does anyone know what's wrong with @dt-bot?
Nevertheless, I'm manually pinging the people involved with prior versions: @matrosov-nikita, @yuit, @billti

2017-06-16 23:55 UTC, minestarks requested changes

2017-06-16 23:55 UTC, minestarks commented on types/cordova-plugin-inappbrowser/index.d.ts
> +    open(url: string, target?: target | string, options?: string, replace?: boolean): InAppBrowser;
```target | string``` is the same type as ```string``` . If you don't care for the overloads I suggest removing ```target``` altogether.

2017-06-19 07:55 UTC, timbru31 commented on types/cordova-plugin-inappbrowser/index.d.ts
> +    open(url: string, target?: target | string, options?: string, replace?: boolean): InAppBrowser;
done

2017-06-19 21:52 UTC, merged