Added missing jwt-decode@1 types. Added generic for jwt-docode.
DefinitelyTyped/DefinitelyTyped pull request #17258
Opened 2017-06-16 19:34 UTC by GiedriusGrabauskas

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17049
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-06-16 22:33 UTC, madsmadsen approved these changes

2017-06-17 01:20 UTC, minestarks requested changes

2017-06-17 01:20 UTC, minestarks commented on types/jwt-decode/jwt-decode-tests.ts
> +import * as jwtDecode from "jwt-decode";
The old import statement was correct as ```jwt-decode``` isn't an ES6 module ([explanation](https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this))
```ts 
import jwtDecode = require('jwt-decode')
```

2017-06-17 06:54 UTC, GiedriusGrabauskas commented on types/jwt-decode/jwt-decode-tests.ts
> +import * as jwtDecode from "jwt-decode";
It's the same. Read the section "I'm Sad About This; Rules are Dumb." about "hack" in your explanation.

2017-06-17 13:38 UTC, DovydasNavickas approved these changes

2017-06-17 13:38 UTC, DovydasNavickas commented on types/jwt-decode/jwt-decode-tests.ts
> +import * as jwtDecode from "jwt-decode";
I think @GiedriusGrabauskas is right. The imports are the same.

2017-06-19 18:09 UTC, GiedriusGrabauskas commented
@minestarks ?

2017-06-20 16:33 UTC, merged