[paho-mqtt] Added type definitions and test for paho-mqtt
DefinitelyTyped/DefinitelyTyped pull request #17310
Opened 2017-06-20 05:18 UTC by amikhalev

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

Closes #8010

2017-06-20 21:56 UTC, sandersn requested changes
Please remove the import from the tests.

2017-06-20 21:56 UTC, sandersn commented on types/paho-mqtt/paho-mqtt-tests.ts
> +import "paho-mqtt";
The library adds to the global namespace, so the import is not needed.

2017-06-21 03:24 UTC, amikhalev commented
@sandersn done!

2017-06-21 03:49 UTC, sandersn approved these changes

2017-06-21 03:49 UTC, merged