Update accounting.formatMoney definition to allow string input
DefinitelyTyped/DefinitelyTyped pull request #17331
Opened 2017-06-20 18:01 UTC by chrisleck

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/openexchangerates/accounting.js/blob/master/accounting.js#L287
- [X] Increase the version number in the header if appropriate.

2017-06-20 21:59 UTC, chrisleck commented
@gerich-home, please take a look.

2017-06-21 08:30 UTC, gerich-home requested changes

2017-06-21 08:30 UTC, gerich-home commented on types/accounting/accounting-tests.ts
> +accounting.formatMoney('$4394958309392.9401'); // $4,394,958,309,392.94
Could you please show me such example in their documentation/code?
I was not able to find an example in their documentation: http://openexchangerates.github.io/accounting.js/

2017-06-21 08:30 UTC, gerich-home commented on types/accounting/index.d.ts
>  // Project: http://josscrowcroft.github.io/accounting.js/
The site is dead now, probably we also need to update the link to the http://openexchangerates.github.io/accounting.js/

2017-06-22 00:36 UTC, chrisleck commented on types/accounting/accounting-tests.ts
> +accounting.formatMoney('$4394958309392.9401'); // $4,394,958,309,392.94
If you follow the link I give above, you see the string parsing code under `formatMoney` via `unformat`.  We use this successfully in our (private) codebase.

2017-06-22 00:37 UTC, chrisleck commented on types/accounting/index.d.ts
>  // Project: http://josscrowcroft.github.io/accounting.js/
Updated.

2017-06-22 00:38 UTC, chrisleck commented
@gerich-home please take another look.

2017-06-22 09:21 UTC, gerich-home approved these changes
Looks good to me

2017-06-22 19:18 UTC, chrisleck commented
Thanks!  Not sure how to actually get this committed now :)

2017-06-22 23:10 UTC, merged