add definition for bootstrap-tagsinput
DefinitelyTyped/DefinitelyTyped pull request #17425
Opened 2017-06-23 11:45 UTC by abedi-ir

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-06-23 16:25 UTC, sandersn requested changes
Fails to compile; see Travis logs for details.

2017-06-23 16:25 UTC, sandersn commented on types/bootstrap-tagsinput/index.d.ts
> +declare module "bootstrap-tagsinput" {}
why is this needed?

2017-06-23 16:25 UTC, sandersn commented on types/bootstrap-tagsinput/index.d.ts
> +interface JQuery {
JQuery has two type parameters according to the compile error in the travis logs.

2017-06-28 12:31 UTC, abedi-ir commented on types/bootstrap-tagsinput/index.d.ts
> +interface JQuery {
Hi @sandersn 
I tries every way for this error and I have no idea what I should do to resolve this error?
I also looked at the other jquery plugins in this repository and they just use `JQuery` interface.
Can help me?

2017-06-29 20:29 UTC, paulvanbrenk commented
Closing as this seems abandoned.

2017-06-29 20:29 UTC, closed without merging