Leaflet: restructured into UMD with satellite modules as augmentations
DefinitelyTyped/DefinitelyTyped pull request #17468
Opened 2017-06-25 15:24 UTC by aluanhaddad

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

I'm not 100% sure if this is the correct way to model the dependencies between Leaflet and the many surrounding packages that enrich it. 
There are a number of issues with how Leaflet is currently represented.
It is an ambient external module.
It depends on a global but that is not necessary
In the process of trying to change these, it soon became clear that adjusting ~11 other packages would be necessary.

I am curious to see the feedback on this PR, especially as there are many longstanding libraries, like jQuery, that still have not migrated to the UMD declaration format, it will be interesting to see if this is deemed practical.

I am also keen to learn if there is a better approach to take here.

Thanks!

2017-06-25 17:19 UTC, DenisCarriere commented on types/leaflet.gridlayer.googlemutant/index.d.ts
> +import L = require('leaflet');
I don't think this should be using `require`.

**Should be**

```javascript
import * as L from 'leaflet'
```

2017-06-25 17:21 UTC, DenisCarriere requested changes

2017-06-25 17:21 UTC, DenisCarriere commented on types/leaflet.locatecontrol/index.d.ts
> -declare namespace L {
This breaks the tests, the Type definition should be defined in the `namespace L`.

![image](https://user-images.githubusercontent.com/550895/27518230-165abd36-59a9-11e7-85fd-699b912a36e2.png)

2017-06-25 17:21 UTC, DenisCarriere commented
Big no 👎, this PR won't pass any tests soon.

2017-06-26 22:39 UTC, paulvanbrenk commented
I would break this into smaller PRs or at least commits and start with changes to the main leaflet package to get that updated.

That way it's easier to review, and help you get to a good end result. As is this PR is very intimidating.

2017-06-27 21:06 UTC, paulvanbrenk commented
Going to close this PR @DenisCarriere

2017-06-27 21:06 UTC, closed without merging