jquery: Add null as a possible return value on val()
DefinitelyTyped/DefinitelyTyped pull request #17481
Opened 2017-06-26 05:23 UTC by Kovensky

Handles a corner case when a multiple-option select has no options selected.

```ts
$(`<select multiple>
  <option>A</option>
  <option>B</option>
</select>`).val() === null
```

The `| undefined` case would already require a truth check in any case, though.

2017-06-26 08:13 UTC, johnnyreilly commented
Failing test - could you take a look please?

2017-06-26 10:45 UTC, leonard-thieu approved these changes

2017-06-26 11:35 UTC, leonard-thieu requested changes
Actually, returning `null` seems to be a pre-3.0 behavior (https://jquery.com/upgrade-guide/3.0/#breaking-change-select-multiple-with-nothing-selected-returns-an-empty-array).

You get an empty array back with no options selected (https://fiddle.jshell.net/4mcLwvvh/).

2017-06-26 11:36 UTC, merged

2017-06-26 23:54 UTC, Kovensky commented
@leonard-thieu oh, I see; I tried it out on a page with live jquery but forgot to check the jquery version :facepalm:

By the way, how do you get .val() to return a number? It seems to be a string even for numeric inputs like `input[type=range]`

2017-06-27 00:14 UTC, leonard-thieu commented
That's a good question. I did some investigating and found out you get a numeric return on... `li` elements 😆 (and `meter` and `progress`).
https://fiddle.jshell.net/leonard_thieu/6u6s2f1c/

https://github.com/jquery/jquery/blob/56136897f241db22560b58c3518578ca1453d5c7/src/attributes/val.js#L15-L15
Looks like jQuery just returns the `value` property from an element if there's no `valHook` defined. I think `valHooks` allows you to return arbitrary values so `val()` might need to be changed to `any`.

2017-06-27 06:02 UTC, johnnyreilly commented
Remember, when writing type definitions we're seeking to codify the official API; in this case: http://api.jquery.com/val/

There may be times when jquery isn't actually honouring it's official API and that's probably a bug in jquery. We don't want to amend our API to cater for bugs which aren't intended behaviour and will hopefully be resolved in time.

It can also be true that the API can be wrong - in that case we want to get that fixed as well. (They accept PRs - I have done this myself :smile: )

2017-06-27 11:59 UTC, leonard-thieu commented
In my experience with jQuery's API, API members tend to fall into one of three categories:
- **Public**
  - Documented and supported
- **Pseudo-internal**
  - Mentioned in documentation
  - Effectively public because enough consumers depend on it
  - jQuery publicly deprecates it
- **Internal**
  - _Never_ mentioned in documentation

When I was writing the v3 typedefs, I included public and pseudo-internal APIs but not fully internal ones.

`valHooks` falls into the pseudo-internal category.

2017-06-27 12:26 UTC, johnnyreilly commented
Probably pseudo-internal shouldn't be included but I'd be interested to hear more on what:

> Effectively public because enough consumers depend on it

Means. Do you have some examples of how consumers depend upon it? Either way, it likely wouldn't be useful for `val` to become `any` instead of the official API return types of "String or Number or Array"

2017-06-27 12:46 UTC, leonard-thieu commented
That doesn't apply specifically to `val()`'s case but `$.easing` has been partially [deprecated](https://jquery.com/upgrade-guide/3.0/#deprecated-additional-easing-function-parameters) because it [gets used a lot](https://github.com/jquery/api.jquery.com/issues/912) despite it being apparently internal (`$.easing` is never mentioned in documentation).

`valHooks` hits the first point. It gets mentioned explicitly: http://api.jquery.com/val/#entry-longdesc.
```javascript
$.valHooks.textarea = {
  get: function( elem ) {
    return elem.value.replace( /\r?\n/g, "\r\n" );
  }
};
```

Ideally, we'd be able to get the return values from functions added to `valHooks` and include them as return values on `val()` but I don't think that's possible.