[react-native] Support arrays in view style props. Fixes #17308
DefinitelyTyped/DefinitelyTyped pull request #17622
Opened 2017-06-29 16:14 UTC by newyankeecodeshop

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/style.html
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Note that the array uses `| undefined` because React will ignore undefined values in the array. This is also indicated by the flow type RN uses for stylesheet props:
https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheetTypes.js

2017-06-29 17:27 UTC, iRoachie commented
This is already possible. What's the reason for this PR?

Example below shows no errors
```jsx
<View style={[styles.item, { backgroundColor: props.color }]}>
```

2017-06-29 17:41 UTC, huhuanming commented
`Array<StyleProps>` and` StyleProps[]`, which is better one?
TSLint rules recommend using `StyleProps[]`.

2017-06-29 18:08 UTC, newyankeecodeshop commented
@iRoachie What version of TypeScript are you using? When I upgraded a project to 2.4.1, I started getting these errors.

2017-06-29 18:12 UTC, newyankeecodeshop commented
I used `Array<>` because I thought it would look better than `(ViewStyle | undefined)[]`.

2017-06-29 18:17 UTC, iRoachie commented
@newyankeecodeshop Ahh 2.4 just got released yesterday, and the typings currently if you check at the top are for Typescript 2.3. So haven't tested as yet. Will upgrade mine now and see

2017-06-29 20:09 UTC, iRoachie commented
@newyankeecodeshop @huhuanming Confirming that they are broken in TypeScript 2.4

2017-06-29 20:16 UTC, iRoachie requested changes
Change all the Array<> to the Type[]. What's the purpose for the undefined?

2017-06-29 20:16 UTC, iRoachie commented on types/react-native/index.d.ts
> +    style?: TextStyle | Array<TextStyle | undefined>
Can just use `TextStyle | TextStyle[]`

2017-06-29 20:42 UTC, iRoachie commented
All the style props are broken, may want to make a generic to handle all of them. 
`type StyleProp<T> = T | T[];`

2017-06-29 20:47 UTC, alloy commented
Could you add some test coverage as well?

2017-06-29 20:49 UTC, iRoachie commented
@alloy Do you have anyway we could do this? Setting the TS version to 2.4 doesn't work for dslint. #17626

2017-06-29 20:52 UTC, alloy commented
Yeah, my bad, I didn’t mean for it to fail CI, so no need to check that version change in, but make sure it’s a test that would fail locally when using TS 2.4.

2017-06-29 21:00 UTC, newyankeecodeshop commented on types/react-native/index.d.ts
> +    style?: TextStyle | Array<TextStyle | undefined>
The flow type supports undefined values in the array, and that would work better for optionals where a given prop might be `ViewStyle?`. If you want to put that in an array, the array would need to support undefined values, right?

2017-06-29 21:03 UTC, iRoachie commented on types/react-native/index.d.ts
> +    style?: TextStyle | Array<TextStyle | undefined>
Can you give an example where undefined would appear in that array?

2017-06-29 21:05 UTC, newyankeecodeshop commented on types/react-native/index.d.ts
> +    style?: TextStyle | Array<TextStyle | undefined>
An example of why the array needs to support undefined values:
```
interface MyComponentProps {
   extraStyle?: ViewStyle
}

function MyComponent(props: MyComponentProps) {
  const styles = [props.style, props.extraStyle];
  // styles is of type "(ViewStyle | undefined)[]"
  return <View style={styles} />;
}
```

2017-06-29 21:09 UTC, newyankeecodeshop commented
Does anyone know why this hasn't caused a problem before? It seems like passing an array for `style` should not have worked, since arrays don't implement the `ViewStyle` interface.

2017-06-30 05:08 UTC, petejkim commented on types/react-native/index.d.ts
> +    style?: TextStyle | Array<TextStyle | undefined>
:+1:

2017-06-30 05:10 UTC, huhuanming commented
In TS 2.4
`<View style={[styles.first, styles.second] as ViewStyle}>`
Or just need a better way.

2017-06-30 05:19 UTC, iRoachie approved these changes

2017-06-30 21:55 UTC, petejkim commented
Are we merging this?

2017-06-30 21:57 UTC, merged

2017-06-30 21:57 UTC, alloy commented
@iRoachie @huhuanming in the future send me a ping when you’ve approved a PR, otherwise I may miss it.

2017-07-01 03:04 UTC, huhuanming commented
fine 👍

2017-07-01 05:28 UTC, pocesar commented
missing TextStyle as well

2017-07-12 16:49 UTC, dannycochran commented
Would be good to get this landed -- Visual Studio Code now auto-updates with TypeScript 2.4.1, so the warnings are hard to opt out of at this point.

2017-07-12 16:51 UTC, iRoachie commented
@dannycochran This is already live

2017-07-12 17:11 UTC, dannycochran commented
Ah I see -- I think the usage of "ViewStyleProp" is still not everywhere it could be.

Do you know if there's any open PR for giving this treatment to TextStyle, as well? Otherwise I can open one.

2017-07-12 17:12 UTC, iRoachie commented
@dannycochran It's there for TextStyle as well.

2017-07-12 18:57 UTC, newyankeecodeshop commented
@dannycochran Yes, TextProperties has been updated, but it's possible some custom components aren't extending it or re-defined `style`. What component is broken for you?

2017-07-12 19:32 UTC, dannycochran commented
@iRoachie thanks, missed it as I was searching for "TextStyleProp" but I see it's just inlined into TextInput and Text. I created a PR that abstracts the typing and uses it in a few other places.

I was using three components where the ViewStyleProp wasn't in effect (ActivityIndicator, ScrollView, KeyboardAvoidingView), but there were several others.

Just submitted a PR:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17990

2018-07-26 07:41 UTC, hpmax00 commented
Is the PR merged?
I use 2.9.2, and have the save issue
<img width="841" alt="image" src="https://user-images.githubusercontent.com/40781942/43248294-fdce54c0-90e9-11e8-8ea5-968303906756.png">
and ScrollableTabView type of @types/react-native-scrollable-tab-view
<img width="521" alt="image" src="https://user-images.githubusercontent.com/40781942/43248337-1ffce8e0-90ea-11e8-8aa9-f43d673c09e3.png">