knockout.validation: Change indexer to KnockoutValidationRuleBase.
DefinitelyTyped/DefinitelyTyped pull request #17683
Opened 2017-07-01 21:25 UTC by MindGirl

To allow the addition of asynchronous validation rules, the type is changed from KnockoutValidationRuleDefinition to KnockoutValidationRuleBase. 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Knockout-Contrib/Knockout-Validation/wiki/Async-Rules

2017-07-05 23:47 UTC, rbuckton requested changes

2017-07-05 23:47 UTC, rbuckton commented on types/knockout.validation/index.d.ts
> +    [ruleName: string]: KnockoutValidationRuleBase;
`KnockoutValidationRuleBase` seems too loose. Perhaps `KnockoutValidationRuleDefinition | KnockoutValidationAsyncRuleDefinition`?

2017-07-07 09:00 UTC, MindGirl commented on types/knockout.validation/index.d.ts
> +    [ruleName: string]: KnockoutValidationRuleBase;
You are right, thats better... will do.

2017-07-11 12:21 UTC, MindGirl commented
I have addressed the feedback in the latest commit. Is there anything else I have to do?

2017-07-13 11:59 UTC, MindGirl commented
@rbuckton I have addressed your feedback. Any other changes needed?

2017-07-14 04:37 UTC, merged