Update Jest definitions with more inline documentation
DefinitelyTyped/DefinitelyTyped pull request #17714
Opened 2017-07-03 16:44 UTC by orta

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://facebook.github.io/jest/docs/en/mock-function-api.html#mockfnmockclear
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

No major changes, I did add `mockRestore` though - http://facebook.github.io/jest/docs/en/mock-function-api.html#mockfnmockrestore

2017-07-03 19:45 UTC, orta commented
This is green now 👍

2017-07-03 20:08 UTC, jwbay requested changes

2017-07-03 20:08 UTC, jwbay commented on types/jest/index.d.ts
> +         * @param {fn?} ProvidesCallback The function which provides the scope to work in
ProvidesCallback is a little out of place here. Should this be `@param {Function} fn`?

2017-07-03 20:08 UTC, jwbay commented on types/jest/index.d.ts
> +         * @param {Function} fn The initola implmentation
typo, initial?

2017-07-03 20:46 UTC, rbuckton requested changes

2017-07-03 20:46 UTC, rbuckton commented on types/jest/index.d.ts
> +         * @param {string} name The name of your scope
JSDoc types like `{string}` aren't necessary in a TypeScript declaration file.

2017-07-03 20:46 UTC, rbuckton commented on types/jest/index.d.ts
> +         * @param {fn?} ProvidesCallback The function which provides the scope to work in
Or just `@param fn` as the JSDoc type is not necessary.

2017-07-03 20:46 UTC, rbuckton commented on types/jest/index.d.ts
> +         * @param {Function} fn The initola implmentation
Also, as above the `{Function}` annotation is not very useful here.

2017-07-03 20:46 UTC, rbuckton commented on types/jest/index.d.ts
> +         * @returns {Mock<T>} The same Jest mock
These JSDoc types are not necessary in a .d.ts file.

2017-07-03 20:46 UTC, rbuckton commented on types/jest/index.d.ts
> +         * @returns {Mock<T>} The same Jest mock
JSDoc type `{Mock<T>}` not necessary in a .d.ts file.

2017-07-06 09:51 UTC, vkrol commented
I think that we need to get rid of this deprecation warning too https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L37
Also we need to fix the description of the resetAllMocks method https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L40

2017-07-10 22:34 UTC, jwbay commented on types/jest/index.d.ts
> +         * @deprecated Use ` jest.fn(() => value` instead.
I was able to get some clarification (via https://github.com/facebook/jest/pull/3993 being merged) that this is not actually deprecated. The documentation for `mockReturnValueOnce` is updated as well. https://github.com/facebook/jest/blob/master/docs/en/MockFunctionAPI.md#mockfnmockreturnvaluevalue

2017-07-14 21:17 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@orta Please address comments from the code reviewers.
<!--footer bot @ 7/14/2017, 2:17:06 PM footerend-->

2017-07-15 00:10 UTC, orta commented
Oops, yeah, I missed all these - sorry! I think it's better that #18034 gets merged, I'll re-create this later

2017-07-15 00:10 UTC, closed without merging