[react-native] Correct signatures for FlatList components
DefinitelyTyped/DefinitelyTyped pull request #17712
Opened 2017-07-03 15:57 UTC by iRoachie

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://facebook.github.io/react-native/docs/flatlist.html#listemptycomponent>>

Adds correct signature for ListEmptyComponent, ListFooterComponent, ListHeaderComponent on the FlatList component.

2017-07-03 21:35 UTC, rbuckton requested changes

2017-07-03 21:35 UTC, rbuckton commented on types/react-native/index.d.ts
> +    ListFooterComponent?: React.ComponentClass<any> | React.ReactElement<any> | null
According to the documentation:
> Can be a React Component Class, a render function, or a rendered element.

It looks like adding `React.ReactElement<any>` to the union is correct, but removing the `(() => React.ReactElement<any>)` from the union may be incorrect.

2017-07-03 21:35 UTC, rbuckton commented on types/react-native/index.d.ts
> +    ListEmptyComponent?: React.ComponentClass<any> | React.ReactElement<any> | null
According to the documentation:
> Can be a React Component Class, a render function, or a rendered element.

Should this also include a "render function" in the union?

2017-07-03 21:35 UTC, rbuckton commented on types/react-native/index.d.ts
> +    ListHeaderComponent?: React.ComponentClass<any> | React.ReactElement<any> | null
As above, per the documentation:
> Can be a React Component Class, a render function, or a rendered element.

Shouldn't the "render function" remain in the union?

2017-07-04 01:03 UTC, iRoachie commented on types/react-native/index.d.ts
> +    ListHeaderComponent?: React.ComponentClass<any> | React.ReactElement<any> | null
@rbuckton However that might be in the documentation. The actual flow typings do not carry a render function. https://github.com/facebook/react-native/blob/master/Libraries/Lists/FlatList.js#L80

2017-07-04 02:20 UTC, huhuanming commented on types/react-native/index.d.ts
> +    ListEmptyComponent?: React.ComponentClass<any> | React.ReactElement<any> | null
```
  /**
   * Rendered when the list is empty. Can be a React Component Class, a render function, or
   * a rendered element.
   */
  ListEmptyComponent?: ?(ReactClass<any> | React.Element<any>),
```

but no `render function` in the source

2017-07-04 02:22 UTC, huhuanming requested changes
Add Source

2017-07-04 02:22 UTC, huhuanming commented on types/react-native/index.d.ts
> +    ListFooterComponent?: React.ComponentClass<any> | React.ReactElement<any> | null
```
 /**
   * Rendered at the bottom of all the items. Can be a React Component Class, a render function, or
   * a rendered element.
   */
  ListFooterComponent?: ?(ReactClass<any> | React.Element<any>),
```

2017-07-04 02:22 UTC, huhuanming commented on types/react-native/index.d.ts
> +    ListFooterComponent?: React.ComponentClass<any> | React.ReactElement<any> | null
the document is not correctly.

2017-07-04 02:24 UTC, iRoachie commented
Source code here https://github.com/facebook/react-native/blob/master/Libraries/Lists/FlatList.js#L80

2017-07-04 06:48 UTC, alloy commented on types/react-native/index.d.ts
> +    ListHeaderComponent?: React.ComponentClass<any> | React.ReactElement<any> | null
Seeing as the implementation tries to use the component like so `<ListEmptyComponent />`, it seems like you should be able to pass in a stateless function component and the flow types are not correct.

2017-07-04 07:00 UTC, huhuanming commented on types/react-native/index.d.ts
> +    ListHeaderComponent?: React.ComponentClass<any> | React.ReactElement<any> | null
😄 This is true source.

2017-07-04 19:31 UTC, iRoachie commented
@alloy @huhuanming What are we agreeing on? Adding function to the union?

2017-07-04 21:31 UTC, alloy commented
@iRoachie Yeah, but be sure to verify the other props are used the same way, I only checked `ListEmptyComponent`.

2017-07-05 04:02 UTC, iRoachie commented
Just did some tests and the component renders both using `<Compontent />` and `() => <Component />`

2017-07-05 04:06 UTC, iRoachie commented
@alloy Changes made

2017-07-05 06:52 UTC, merged

2017-07-05 06:52 UTC, rbuckton commented
Thanks for the contribution!

2017-07-05 10:18 UTC, alloy commented
Ace 👍