react-dropzone: Use namespace for importing
DefinitelyTyped/DefinitelyTyped pull request #17718
Opened 2017-07-03 20:06 UTC by mllrjb

Fixes `error TS2497: Module '"react-dropzone"' resolves to a non-module entity and cannot be imported using this construct.` when using:

```
import * as Dropzone from 'react-dropzone';
```

2017-07-03 21:01 UTC, rbuckton commented
@mllrjb, ES6-style imports using `import * as X from ...` are supposed to allocate a special namespace object for the named exports of the module. The reason you see the error is that the class `Dropzone` *is* the module instance. This kind of export can only really be imported as a value using the `import X = require(...)` syntax that we support for AMD/CommonJS modules.

2017-07-03 21:04 UTC, rbuckton requested changes

2017-07-03 21:04 UTC, rbuckton commented on types/react-dropzone/react-dropzone-tests.tsx
> +import * as Dropzone from 'react-dropzone';
While the changes to _index.d.ts_ are ok, I would caution you against using the ES6-style `import * as X from ...` syntax, as it is not designed to work with `export =` in this fashion.

2017-07-03 21:07 UTC, mllrjb commented
@rbuckton, `import X = require(...)` isn't compatible with all module types (e.g. `es2015`), however, it continues to work fine (for `commonjs` modules with my changes.

2017-07-03 21:07 UTC, mllrjb commented on types/react-dropzone/react-dropzone-tests.tsx
> +import * as Dropzone from 'react-dropzone';
Should I extend the test to cover `import * as` as well as `require` import?

2017-07-03 21:08 UTC, benbayard commented
This should be imported using the new require syntax. While the sourcecode using `export default`, the outputted module used a Node-style import and instead should be imported with the require syntax.

2017-07-03 21:21 UTC, rbuckton commented
@benbayard, the import/export mismatch is an issue we're trying to get a better idea on how to resolve. Despite the fact the source is written as `export default Dropzone`, the output actually uses `module.exports = exports["default"]`. As far as TypeScript is concerned, this is equivalent to `export = Dropzone`. 

We don't currently do anything to "fix" the import in the same way that Babel does. If there was one-to-one parity between the source for react-dropzone and the declaration file, then the import statement actually would have been `import Dropzone from "react-dropzone"` not `import * as Dropzone from "react-dropzone"`. Unfortunately, the transformation that Babel applies here does not allow for that parity.

CC: @DanielRosenwasser

2017-07-03 21:25 UTC, benbayard commented
@rbuckton absolutely understood. I see this often with react components, actually. The two most common are `let Component: ClassicComponent` and improper exports for the `distributed` code. Certainly not a problem with `@types` or `typescript`, but perhaps something worth an audit?

2017-07-03 23:07 UTC, rbuckton commented
I would like to follow up with @DanielRosenwasser about this one. I will hopefully have an answer in the next few days.

2017-07-14 21:17 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@mllrjb Please address the merge conflict.
<!--footer bot @ 7/14/2017, 2:17:04 PM footerend-->

2017-07-16 22:14 UTC, closed without merging