[node] Fix `https?` classes
DefinitelyTyped/DefinitelyTyped pull request #17720
Opened 2017-07-03 21:10 UTC by blakeembrey

Changes the `http` interfaces to correctly be classes. Some of it is directly copied from @types.

I was hoping to be able to copy more across, especially from a few of the modules I typed from scratch in https://github.com/types/env-node (`fs`, `path`, `tls`, `crypto`, `child_process` etc), but things have diverged too much for me to take the time to verify the conflicts. One day I might get to them. The initial work took me around 12 hours in @types, so copying it across for someone else might be a bit quicker in the future (plus there's the specific commits you can grab, e.g. https://github.com/types/env-node/commit/f3dc5120a3fa4bc65263a61d097903de3f451ac8).

2017-07-03 21:11 UTC, blakeembrey commented
Note: This did delete the deprecated and non-existing stuff in the `http` definition.

2017-07-04 08:08 UTC, Flarna requested changes

2017-07-04 08:08 UTC, Flarna commented on types/node/index.d.ts
> +    export function request(options: string | RequestOptions, callback?: (res: http.IncomingMessage) => void): http.ClientRequest;
Variant to use URL as option got lost.

2017-07-04 08:08 UTC, Flarna commented on types/node/index.d.ts
>          connections: number;
I think `connections` can be removed here has it should be visible from `net.Server`

2017-07-04 08:08 UTC, Flarna commented
Nice work! Seems some dependent packages use the deprecated types you removed but it should be simple to adapt them.

2017-07-04 15:13 UTC, blakeembrey commented on types/node/index.d.ts
> +        ca?: string | Buffer | string[] | Buffer[];
That is what it says, see what you just commented on 👍

2017-07-04 15:13 UTC, blakeembrey commented
Thanks for the review @Flarna. I'll try to come back to these, but it'll take some time.

2017-07-04 15:17 UTC, blakeembrey commented on types/node/index.d.ts
> +    export interface OutgoingHeaders {
Consistency, but I can change it back since there's no semver in DT.

2017-07-04 15:19 UTC, blakeembrey commented on types/node/index.d.ts
> +    export class OutgoingMessage extends stream.Writable {
Technically it inherits from stream internally but all the types match up with a writable stream.

![image](https://user-images.githubusercontent.com/1088987/27835822-a66b177e-60aa-11e7-8a89-0163f1f8455c.png)

2017-07-04 15:20 UTC, blakeembrey commented on types/node/index.d.ts
> +    }
They should be correctly typed in `stream`.

2017-07-04 15:21 UTC, blakeembrey commented on types/node/index.d.ts
> +        assignSocket(socket: stream.Writable): void;
Fair enough. Most of this is documented from my internal experience with the node types. I can add docblocks with `@internal` if that's the right way.

2017-07-04 15:22 UTC, blakeembrey commented on types/node/index.d.ts
> +    export function request(options: string | RequestOptions, callback?: (res: IncomingMessage) => void): ClientRequest;
Because it's wrong? It just happens that `URL` is assignable to `RequestOptions`, so this still works fine.

2017-07-04 15:23 UTC, blakeembrey commented on types/node/index.d.ts
> +    export function request(options: string | RequestOptions, callback?: (res: IncomingMessage) => void): ClientRequest;
We can make sure there's a test case for this, but adding `URL` should be redundant (if the typings are correct).

2017-07-04 15:23 UTC, blakeembrey commented on types/node/index.d.ts
>          connections: number;
True. It's really only here because of the docblock, but I can move that to `net`.

2017-07-04 16:12 UTC, Flarna commented on types/node/index.d.ts
> +    export function request(options: string | RequestOptions, callback?: (res: IncomingMessage) => void): ClientRequest;
Currently it's redundant as it is enough that at least one property from `URL` matches `RequestOptions`. But `URL` would be also allowed if there would be no match as this is a separate path in code. Was added somewhere in NodeJS 7.x

2017-07-04 16:13 UTC, Flarna commented on types/node/index.d.ts
> +        ca?: string | Buffer | string[] | Buffer[];
`ca` matches but `cert` does not. Seems I was interrupted too often during my review...

2017-07-04 16:15 UTC, Flarna commented on types/node/index.d.ts
> +        assignSocket(socket: stream.Writable): void;
If there is a real use case for calling it it's fine, if no one should call them I would not add them here. But this is just my opinion so feel free to keep them.

2017-07-04 16:17 UTC, Flarna commented on types/node/index.d.ts
> +    }
Streams have additionally support for object mode which allows any object. HTTP allows only `string' and `Buffer` (and maybe `Uint8Array`).

2017-07-04 16:19 UTC, Flarna commented on types/node/index.d.ts
> +    export interface OutgoingHeaders {
personally I don't care that much as I would get hit just at one or two places. but others may see more impact.

2017-07-04 17:42 UTC, blakeembrey commented on types/node/index.d.ts
> +        ca?: string | Buffer | string[] | Buffer[];
I see. Good catch!

2017-07-12 19:31 UTC, closed without merging

2017-07-12 20:02 UTC, Flarna commented
Our new best friends the bots...
I will keep in mind that I should look into types during future PRs.

2017-07-13 09:32 UTC, leizongmin commented
nice work!