Add mutateIn and lookupIn to Couchbase Bucket definition.
DefinitelyTyped/DefinitelyTyped pull request #17768
Opened 2017-07-05 15:17 UTC by JesseObrien

I'm adding these to at _least_ make them available to be used by typescript. There's more work to be done to add the proper return types including a [LookUpInBuilder](https://github.com/couchbase/couchnode/blob/4e61a6390275a8aa1ff94cc05bdfed9a50af6b6d/lib/bucket.js#L2695) and [MutateInBuilder](https://github.com/couchbase/couchnode/blob/4e61a6390275a8aa1ff94cc05bdfed9a50af6b6d/lib/bucket.js#L2825) but I don't have time to put these into play right now. I'll consider adding those later.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/couchbase/couchnode/blob/4e61a6390275a8aa1ff94cc05bdfed9a50af6b6d/lib/bucket.js#L2789
https://github.com/couchbase/couchnode/blob/4e61a6390275a8aa1ff94cc05bdfed9a50af6b6d/lib/bucket.js#L3046
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-07-07 07:56 UTC, rbuckton requested changes
The build failed due to an npm issue. After restarting the build there are errors that must be corrected.

2017-07-07 07:56 UTC, rbuckton commented on types/couchbase/index.d.ts
> +    mutateIn(key: string, options?: object): any;
Use of the `object` keyword requires you to add a `// TypeScript Version: 2.3` comment at the top of the file, per [the readme](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-use-features-from-typescript-21-or-above)

2017-07-14 21:17 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@JesseObrien Please fix the failures indicated in the Travis CI log.
<!--footer bot @ 7/14/2017, 2:17:04 PM footerend-->

2017-08-08 21:38 UTC, mhegazy commented
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-08-08 21:38 UTC, closed without merging