Updates type definitions for Dropzone 5.0.0
DefinitelyTyped/DefinitelyTyped pull request #17806
Opened 2017-07-06 16:40 UTC by tedbcsgpro

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<http://www.dropzonejs.com/#news>>
- [x] Increase the version number in the header if appropriate.

@nvivo @a904guy

Rationale for updates:
* Dropzone.js 5.0.0 recently released
* Added strongly typed support for new client-side image resizing functionality in 5.0.0
* Prior type definition did not expose some methods our team finds useful

2017-07-06 18:01 UTC, benbayard commented on types/dropzone/dropzone-tests.ts
> +
two new lines?

2017-07-06 18:01 UTC, benbayard commented on types/dropzone/index.d.ts
> +      	resizeHeight?: number;
indentation differences

2017-07-06 18:02 UTC, benbayard commented on types/dropzone/index.d.ts
> +	createThumbnailFromUrl(file:Dropzone.DropzoneFile, width?: number, height?: number, resizeMethod?:string, fixOrientation?: boolean, callback?:(...args:any[]) => void, crossOrigin?:string):any;
space after colon

2017-07-06 18:02 UTC, benbayard commented on types/dropzone/index.d.ts
> +	getActiveFiles(): Dropzone.DropzoneFile[]
semicolon

2017-07-06 18:03 UTC, benbayard commented on types/dropzone/dropzone-tests.ts
> +    resizeHeight: 1024,
indentation differences

2017-07-06 18:35 UTC, tedbcsgpro commented
@benbayard Updated per your comments.

2017-07-07 23:06 UTC, rbuckton requested changes
As this is a major version update for the package, please follow the guidelines in the readme regarding maintaining historical versions: https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version

2017-07-08 00:12 UTC, tedbcsgpro commented
@rbuckton done

2017-07-08 03:59 UTC, rbuckton approved these changes

2017-07-08 03:59 UTC, merged

2017-07-08 03:59 UTC, rbuckton commented
Thanks for the contribution!