[jquery] fn property should be not readonly
DefinitelyTyped/DefinitelyTyped pull request #17837
Opened 2017-07-07 10:45 UTC by stonio

Modifying jQuery property `$.fn` is required to create a jQuery plugin.

So me should remove `readonly` keyword from its TypeScript definition.

Reference: https://learn.jquery.com/plugins/basic-plugin-creation/#basic-plugin-authoring

2017-07-07 12:27 UTC, DickvdBrink commented
I don't think `readonly` does what you think it does. `readonly` means that you can't overwrite/assign `fn`, you can however modify the content of `fn`.
For jQuery you modify `fn` by assigning new functions to it which is still possible so I don't think this is the right change.

Small example below
```
class test {
    static readonly fn: any;
}

test.fn = {};// error because fn is readonly
test.fn.test = {};// allowed
```

2017-07-07 13:34 UTC, stonio commented
You're right The `readonly` keyword is not the culprit. However the basic plugin definition raises error:
> Property 'greenify' does not exist on type 'JQuery<HTMLElement>'.

What do you suggest?
```js
// From https://learn.jquery.com/plugins/basic-plugin-creation/#basic-plugin-authoring

$.fn.greenify = function () {
    this.css( "color", "green" );
};
 
$( "a" ).greenify(); // Makes all the links green.
```

2017-07-07 13:43 UTC, leonard-thieu commented
You just need to declare a new property on `JQuery`.

See https://github.com/DefinitelyTyped/DefinitelyTyped/blob/66fe42e92c92fdbd254204987b99e45feadf9862/types/jquery/README.md#authoring-type-definitions-for-jquery-plugins for details.

2017-07-07 14:12 UTC, stonio commented
Can we add the plugin "greenify" in example-tests to check implementation?

2017-07-07 14:22 UTC, leonard-thieu commented
That sounds reasonable. Did you want to handle that?

If you do, I'd suggest creating a new test file (probably `learn-tests.ts`) to put it in. I didn't make it explicit in the README but `example-tests.ts` scraped the code from https://github.com/jquery/api.jquery.com. It'd be nice to leave open the possibility of regenerating the tests without having to worry too much about manual entries.

2017-07-07 16:27 UTC, leonard-thieu requested changes
You need to add `test/learn-tests.ts` to `tsconfig.json`.

2017-07-07 16:27 UTC, leonard-thieu commented on types/jquery/index.d.ts
> +    fn: JQuery<TElement>;
Don't forget to undo this.

2017-07-08 18:02 UTC, leonard-thieu commented on types/jquery/test/learn-tests.ts
> +const jQuery = jQueryFactory(window, true);
I would just drop the import and just use the `jQuery` global.

2017-07-10 10:15 UTC, stonio commented
@leonard-thieu thanks for your tips

2017-07-10 11:02 UTC, leonard-thieu approved these changes

2017-07-10 20:36 UTC, merged