node: Added overloads of ChildProcess#send() method
DefinitelyTyped/DefinitelyTyped pull request #17860
Opened 2017-07-08 10:36 UTC by achugaev93

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://nodejs.org/api/child_process.html#child_process_child_send_message_sendhandle_options_callback>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-07-08 13:34 UTC, Flarna requested changes
Please add some tests to cover all usecases allowed.

2017-07-08 13:34 UTC, Flarna commented on types/node/index.d.ts
> +        send(message: any): boolean;
I think this one is not needed as the next one with optional callback should cover the `send(message)` and `send(message, cb)` use cases.

2017-07-08 13:34 UTC, Flarna commented on types/node/index.d.ts
> +        send(message: any, sendHandle?: net.Socket | net.Server, options?: MessageOptions): boolean;
I think this one is not needed as the next one with optional callback after options covers the `send(message, sendHandle, options)` and `send(message, sendHandle, options, cb)` use cases.
But I think the use case `send(message, sendHandle, cb)` is not yet covered.

2017-07-08 16:58 UTC, achugaev93 commented
@Flarna I have updated signatures. You're right, missed case with 3 arguments. I looked at tests file, but i don't understand, how to write own. I familiar with Jest/Jasmine, but it seems there are another engine/approach.

2017-07-09 09:24 UTC, Flarna commented
Tests are quite simple - it's just validated that `node-tests.ts` contains valid typescript.
There is already a section `namespace child_process_tests` which contains some use of child process, just add a few lines using the API you added/improved.

2017-07-11 23:24 UTC, achugaev93 commented
Changes in this PR - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/17959

2017-07-12 17:22 UTC, RyanCavanaugh commented
Closing per comments in #17959

2017-07-12 17:22 UTC, closed without merging