Typings for google-images
DefinitelyTyped/DefinitelyTyped pull request #17861
Opened 2017-07-08 11:05 UTC by dolanmiu

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

This is the package:
https://www.npmjs.com/package/google-images

I have used information from the official Google CSE documentation:
https://developers.google.com/custom-search/json-api/v1/reference/cse/list

2017-07-11 13:37 UTC, dolanmiu commented
Can someone merge this?

2017-07-13 21:17 UTC, RyanCavanaugh requested changes

2017-07-13 21:17 UTC, RyanCavanaugh commented on types/google-images/index.d.ts
> +export as namespace GoogleImages;
This isn't a UMD module, so this line shouldn't be here.

2017-07-13 22:53 UTC, dolanmiu commented
Done

2017-07-13 23:31 UTC, merged