added json-rpc-ws type definition
DefinitelyTyped/DefinitelyTyped pull request #17881
Opened 2017-07-09 11:21 UTC by npenin

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-07-14 18:08 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@npenin Please fix the failures indicated in the Travis CI log.
<!--footer bot @ 7/14/2017, 11:08:06 AM footerend-->

2017-07-17 17:28 UTC, ghost requested changes
Needs a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-07-17 17:28 UTC, andy-ms commented on types/json-rpc-ws/tsconfig.json
> +{
Base this on the one in `abs/tsconfig.json`.

2017-07-17 17:28 UTC, andy-ms commented on types/json-rpc-ws/index.d.ts
> +     * @public
Don't include redundant JSDoc annotations -- accessibility and types are handled by TypeScript.
In this particular case I would say all of the docs are redundant.

2017-07-17 17:28 UTC, andy-ms commented on types/json-rpc-ws/index.d.ts
> +    // connections: { [id: string]: TConnection };
Need a decision on whether this should be included or not -- don't leave it commented.

2017-07-19 13:54 UTC, andy-ms commented on types/json-rpc-ws/index.d.ts
> +export type handler<TConnection extends Connection, ParamType, ParamCallbackType> = (this: TConnection, params: ParamType, reply: replyCallback<ParamCallbackType>) => void;
Prefer an upper-case type name.

2017-07-19 13:54 UTC, andy-ms commented on types/json-rpc-ws/index.d.ts
> +    // connections: { [id: string]: TConnection };
Bump -- if this isn't needed, delete it.

2017-07-19 13:54 UTC, andy-ms commented on types/json-rpc-ws/json-rpc-ws-tests.ts
> +let server = JsonRpcWs.createServer();
This could use an example of providing a generic type argument to `createServer` -- when is that useful?

2017-07-19 13:54 UTC, andy-ms commented on types/json-rpc-ws/json-rpc-ws-tests.ts
> +server.expose('mirror', function mirror(params, reply)
If it's not important for this function to be named, use an arrow function.

2017-07-20 04:48 UTC, npenin commented on types/json-rpc-ws/json-rpc-ws-tests.ts
> +server.expose('mirror', function mirror(params, reply)
this code is part of the official documentation of the package, I just wanted to have it as close as possible to the official documentation. Should I remove the name anyway ?

2017-07-20 13:44 UTC, andy-ms commented on types/json-rpc-ws/json-rpc-ws-tests.ts
> +server.expose('mirror', function mirror(params, reply)
No, it's fine.

2017-07-23 07:05 UTC, npenin commented
@andy-ms There is a check I would not like to fix as it is a false positive ; based on tslint: `'this' implicitly has type 'any' because it does not have a type annotation`). However, my handler definition is providing the `this` type, and itstherefore typed. Would you please accept this deviation ?

2017-07-24 14:26 UTC, andy-ms commented
That looks like a bug in TypeScript 2.0; you could add `TypeScript Version: 2.1` to the end of the header (line 5) to fix it.

2017-07-26 14:06 UTC, andy-ms commented
Thanks!

2017-07-26 14:06 UTC, merged