[@types/eonasdan-bootstrap-datetimepicker] Allow call methods
DefinitelyTyped/DefinitelyTyped pull request #17906
Opened 2017-07-10 11:40 UTC by JoniJnm

Allow call datetimepicker methods like show, destroy, etc.

- https://github.com/Eonasdan/bootstrap-datetimepicker/blob/master/src/js/bootstrap-datetimepicker.js#L2413
- http://eonasdan.github.io/bootstrap-datetimepicker/Functions/

2017-07-11 06:09 UTC, ToastHawaii commented
@JoniJnm If you want. You can explizit specify the methods eg like this

/** description */
datetimepicker("destroy"): any;

/** description */
datetimepicker("hide"): JQuery;

2017-07-11 11:01 UTC, JoniJnm commented
There are a lot of functions :(

2017-07-17 17:43 UTC, andy-ms commented on types/eonasdan-bootstrap-datetimepicker/index.d.ts
> +        datetimepicker(methodName: string, ...args: any[]): JQuery | any;
`JQuery | any` is just `any`.

2017-07-17 17:44 UTC, ghost reviewed
Does this take the name of a method in `Datetimepicker` and its arguments? If we had something like Microsoft/TypeScript#5453 we might have a way of representing that, until then, `any[]` may be the best we can do without copying all those definitions over.

2017-07-17 21:26 UTC, weswigham requested changes
Just these overloads should be fine, since most people care more about chaining than anything else (and these are the only methods that chain).

2017-07-17 21:26 UTC, weswigham commented on types/eonasdan-bootstrap-datetimepicker/index.d.ts
> +        datetimepicker(methodName: string, ...args: any[]): JQuery | any;
Add
```ts
datetimepicker(methodName: "destroy"): JQuery;
datetimepicker(methodName: "hide"): JQuery;
datetimepicker(methodName: "show"): JQuery;
datetimepicker(methodName: "toggle"): JQuery;
```
Above this, then this line is fine - this should let chaining work with type inference, but still allow calling arbitrary methods.

2017-08-08 21:43 UTC, mhegazy commented
Thanks for your contribution. This PR has unaddressed reviewer comments and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-08-08 21:43 UTC, closed without merging