Add types for css-modules
DefinitelyTyped/DefinitelyTyped pull request #17963
Opened 2017-07-12 05:29 UTC by NeekSandhu

Enables users to `import styles from '../main.css'` in your TypeScript files.

From there on, assuming user is using `webpack` with `css-loader`, they can also do `styles.toString()` or `classNames(styles.productLabel...` without any squiggly lines.

Also works beautifully with intellisense (both of ops have `string` as return type)

https://github.com/css-modules/css-modules

2017-07-13 08:32 UTC, Kovensky commented
This might work better as an additional file in the `webpack-env` definitions.

(incidentally they do not correspond to a real package either; there _is_ a real `webpack-env` package but it has no definitions)

2017-07-13 16:14 UTC, NeekSandhu commented
@use-strict your thoughts on having this inside `webpack-env`?

2017-07-13 21:25 UTC, use-strict commented
@NeekSandhu  I don't have a strong opinion here, but, I'd advise against it. `webpack-env` is strictly about Webpack API available by default in every module. Since there are so many combinations of loaders and webpack plugins, I'd keep definitions separate, instead of adding them all into the `webpack-env` umbrella. Maybe go for something like `webpack-env-css-loader` instead?

Naming might not be the best, but it had to be different from `webpack` which is the node API to build bundles programatically. I don't remember there being a `webpack-env` npm package at the time, but I see now this lead to some confusion. Guess it's probably too late to change it now.

2017-07-14 18:08 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@NeekSandhu Please fix the failures indicated in the Travis CI log.
<!--footer bot @ 7/14/2017, 11:08:02 AM footerend-->

2017-07-14 18:23 UTC, NeekSandhu commented
@RyanCavanaugh The log isn't very verbose, also it fails somewhere that I have no control over. Any help in locating the culprit would be appreciated.

2017-07-14 20:35 UTC, RyanCavanaugh commented
@NeekSandhu 
```
Started at Wed, 12 Jul 2017 05:30:22 GMT
Found 3251 typings folders in /home/travis/build/DefinitelyTyped/DefinitelyTyped/types
Error: At 1:1 : Expected '// Type definitions for '
    at Object.parseHeaderOrFail (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/node_modules/definitelytyped-header-parser/index.js:49:15)
    at /home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/lib/definition-parser.ts:91:3
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/lib/definition-parser.js:4:58)
    at <anonymous>
```

You're missing the header. Look at any other index.d.ts file in this repo

2017-07-15 02:19 UTC, NeekSandhu commented
@RyanCavanaugh Thanks for the help, everything green now.

2017-07-17 17:52 UTC, andy-ms commented
Need a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-07-17 21:41 UTC, weswigham requested changes
As @andy-ms said, please add a tslint.json containing `{ "extends": "dtslint/dt.json" }` (and if need be, fix any lint errors which CI reveals).

2017-07-18 06:07 UTC, merged