add support for React stateless functional components: react-navigation
DefinitelyTyped/DefinitelyTyped pull request #17987
Opened 2017-07-12 17:08 UTC by andrewlinfoot

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L279>
- [x] Increase the version number in the header if appropriate.

2017-07-13 08:26 UTC, Kovensky commented on types/react-navigation/index.d.ts
> +export type NavigationScreenSFC<T, Options> = React.SFC<T> & {
This probably needs to be added to the `NavigationComponent` union

2017-07-17 21:30 UTC, weswigham requested changes

2017-07-17 21:30 UTC, weswigham commented on types/react-navigation/index.d.ts
> +export type NavigationScreenSFC<T, Options> = React.SFC<T> & {
@andrewlinfoot If you could address @Kovensky's comment, that'd be great.

2017-08-08 21:44 UTC, mhegazy commented
Thanks for your contribution. This PR has unaddressed reviewer comments and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-08-08 21:44 UTC, closed without merging