[integer] Add type declaration file
DefinitelyTyped/DefinitelyTyped pull request #18001
Opened 2017-07-12 23:49 UTC by Morfent

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-07-13 00:41 UTC, Morfent commented
@JoshuaWise, could you take a quick look at this in case I missed anything?

2017-07-13 14:56 UTC, JoshuaWise requested changes

2017-07-13 14:56 UTC, JoshuaWise commented on types/integer/index.d.ts
> +	function fromNumber(val: number, defaultVal?: IntClass): IntClass;
`defaultVal?` here can be a `number` or `IntClass`.

2017-07-13 14:56 UTC, JoshuaWise commented on types/integer/index.d.ts
> +	function fromString(val: string, radix?: number): IntClass;
There's an optional third argument (to specify a default value) which can either be a `string` or `IntClass`

2017-07-13 14:56 UTC, JoshuaWise commented on types/integer/index.d.ts
> +		greaterThanOrEquals(val: IntLike): boolean;
This is missing `isGreaterThan()` and `isGreaterThanOrEqualTo()`

2017-07-13 14:56 UTC, JoshuaWise commented on types/integer/index.d.ts
> +		lessThanOrEquals(val: IntLike): boolean;
This is missing `isLessThan()` and `isLessThanOrEqualTo()`

2017-07-13 17:46 UTC, Morfent commented
Made the changes you brought up. Thanks for catching them before they caused any problems

2017-07-14 05:52 UTC, RyanCavanaugh requested changes

2017-07-14 05:52 UTC, RyanCavanaugh commented on types/integer/index.d.ts
> +export as namespace Integer;
This is not a UMD module, so there shouldn't be a UMD module declaration.

2017-07-14 06:32 UTC, Morfent commented on types/integer/index.d.ts
> +export as namespace Integer;
Would `export default` be more appropriate?

2017-07-14 06:35 UTC, RyanCavanaugh commented on types/integer/index.d.ts
> +export as namespace Integer;
No.
```
C:\Throwaway>node
> require('integer').default
undefined
>
```
You can just remove line 111.

2017-07-14 07:03 UTC, Morfent commented on types/integer/index.d.ts
> +export as namespace Integer;
...checking the documentation again, you're right

2017-07-14 07:03 UTC, Morfent commented
Removed line 11

2017-07-14 15:33 UTC, JoshuaWise approved these changes

2017-07-14 18:07 UTC, RyanCavanaugh commented
<!--header {"slug":"reviewPing-c312a14e6aed7a8616ad4ed600ac681c"} headerend-->
@RyanCavanaugh - Thanks for your review of this PR! Can you please look at the new code and update your review status if appropriate?
<!--footer bot @ 7/14/2017, 11:07:58 AM footerend-->

2017-07-14 18:10 UTC, merged