Updated react-maskedinput for 4.0.0
DefinitelyTyped/DefinitelyTyped pull request #18058
Opened 2017-07-14 10:47 UTC by Lavoaster

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/insin/react-maskedinput/commit/09472b84e83fe7f0d2ea693125731a306a7b3177
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

3.3.4 => 4.0.0 changes it so that it does have a default export, other than that there were no breaking changes to anything else.

2017-07-14 13:35 UTC, Lavoaster commented
This module has two differing exports based on what is being loaded. This PR resolves an issue loading it with the new `es` module it has, but conflicts with the `lib` module. You can read more about the issue in insin/react-maskedinput#104.

I'm not sure what to do about this PR, is this something I should / could resolve here? Or would it be better to wait for the package maintainer to make a decision on if exports should be standard or not?

2017-07-14 15:32 UTC, LKay requested changes

2017-07-14 15:32 UTC, LKay commented on types/react-maskedinput/index.d.ts
> +interface ReactMaskedInputCharsFormatters {
Don't rename interfaces when you only changed the way they are exported. This will break people's code.

2017-07-14 15:32 UTC, LKay commented on types/react-maskedinput/index.d.ts
> +declare const ReactMaskedInput: React.ClassicComponentClass<ReactMaskedInputProps>;
You can just do:
```typescript
declare class MaskedInput extends React.Component<MaskedInputProps> {}
export default MaskedInput;
```

2017-07-14 16:13 UTC, Lavoaster commented on types/react-maskedinput/index.d.ts
> +interface ReactMaskedInputCharsFormatters {
I assumed this would be fine with the potential breaking change introduced in 4.0.0. Will revert though.

2017-07-14 16:26 UTC, Lavoaster commented
@LKay I've made the changes you've request.

Do you have any thoughts on my previous comment?

2017-07-14 16:53 UTC, LKay commented
I think you misunderstood me. It's ok to remove namespace. Since the export in not in cjs style you can export all the types and interfaces directly. You should avoid using `export as namespace ...`. Just add `export` before interfacesAfter you remove namespace.

2017-07-14 18:07 UTC, RyanCavanaugh commented
<!--header {"slug":"reviewPing-11eaf7280f3ab057b144014b660a02e2"} headerend-->
@LKay - Thanks for your review of this PR! Can you please look at the new code and update your review status if appropriate?
<!--footer bot @ 7/14/2017, 11:07:51 AM footerend-->

2017-07-14 20:25 UTC, Lavoaster commented
@LKay Oh! I get it now. Sorry, about that.

Just FYI, the package exports both CJS and ES modules, but they don't interop with this definition.

2017-07-15 03:10 UTC, LKay commented
Now it's LGTM and ready to merge.

2017-07-15 03:11 UTC, LKay approved these changes

2017-07-17 18:24 UTC, merged