[react-codemirror] Add types for the change object
DefinitelyTyped/DefinitelyTyped pull request #18145
Opened 2017-07-17 18:19 UTC by rudi-c

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://codemirror.net/doc/manual.html
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-07-20 21:15 UTC, velveret requested changes

2017-07-20 21:15 UTC, velveret commented on types/react-codemirror/index.d.ts
> +// Type definitions for React Codemirror v0.2.7
there is no v0.2.7.

2017-07-20 21:15 UTC, velveret commented on types/react-codemirror/index.d.ts
> +    interface Pos {
`Pos` and `Change` should be the `CodeMirror` types, not added here.

2017-07-23 20:59 UTC, rudi-c commented
True, true, newbie mistakes! Thanks for the suggestions @velveret, please take a look?

2017-07-25 19:44 UTC, velveret requested changes

2017-07-25 19:44 UTC, velveret commented on types/react-codemirror/index.d.ts
>  // Type definitions for React Codemirror v0.2.6
your type change isn't in 0.2.6, it's in 1.0.0. 1.0.0 introduces other changes as well - you should update the typings to match all of 1.0.0's changes if you're going to bump the version.
See https://github.com/JedWatson/react-codemirror/blob/master/HISTORY.md#v100--2017-05-14

2017-07-30 18:49 UTC, rudi-c commented
@velveret That's a good idea, done.

2017-08-05 05:53 UTC, velveret commented on types/react-codemirror/index.d.ts
> +        path?: string;
There's a preserveScrollPosition prop as well

2017-08-05 05:53 UTC, velveret commented on types/react-codemirror/index.d.ts
> +        codeMirrorInstance?: CodeMirror.Editor;
this has been changed to a function type - see https://github.com/JedWatson/react-codemirror/pull/54

2017-08-05 05:53 UTC, velveret commented on types/react-codemirror/index.d.ts
> +        onCursorActivity?: (cm: CodeMirror.Editor) => any;
prefer `codemirror` over `cm` to match react-codemirror docs and be more descriptive

2017-08-05 05:53 UTC, velveret commented on types/react-codemirror/index.d.ts
> +        autoSave?: boolean;
this prop is listed in the docs but isn't actually in the library - see https://github.com/JedWatson/react-codemirror/pull/22#issuecomment-320414389. I'm fine with leaving this in for now to match the react-codemirror docs and so we don't have to update again once it's restored.

2017-08-06 19:39 UTC, rudi-c commented
@velveret I've made the changes, but I have no idea how to refer to a type that's the default export of a module that's also a merge function-interface type. I just put a function signature that works, but can we merge it like this? Investigating this further would be beyond my needs or interest.

2017-08-07 00:20 UTC, velveret approved these changes
Thanks for making all the changes for 1.0.

2017-08-07 00:20 UTC, velveret commented on types/react-codemirror/react-codemirror-tests.tsx
>                          codeMirrorInstance={codeMirrorInstance}
you can remove the `codeMirrorInstance` variable and put `CodeMirror` here

2017-08-08 20:45 UTC, merged