https://github.com/crocodilejs/node-email-templates/blob/master/examples/handlebars_i18n/index.js
DefinitelyTyped/DefinitelyTyped pull request #18166
Opened 2017-07-18 07:45 UTC by janwo

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-07-18 07:47 UTC, janwo commented
Retry, see comments of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18166m

2017-07-18 10:06 UTC, cyrilschumacher approved these changes

2017-07-19 16:51 UTC, RyanCavanaugh commented
Welcome back Travis!

2017-07-20 08:53 UTC, janwo commented
@RyanCavanaugh Done! 👍

2017-07-20 10:02 UTC, cyrilschumacher approved these changes

2017-07-20 14:26 UTC, gurisko requested changes

2017-07-20 14:26 UTC, gurisko commented on types/email-templates/index.d.ts
> +        render(locals: EmailTemplateCallback|Object): Promise<EmailTemplateResults>;
This doesn't return a promise if `EmailTemplateCallback` is passed.

2017-07-20 14:26 UTC, gurisko commented on types/email-templates/index.d.ts
> +        render(locals: EmailTemplateCallback|Object, locale: string): Promise<EmailTemplateResults>;
`EmailTemplateCallback` shouldn't be here.

2017-07-20 14:26 UTC, gurisko commented on types/email-templates/index.d.ts
> +        render(locals: EmailTemplateCallback|Object, callback: EmailTemplateCallback): void;
This accepts two callback functions.

2017-07-20 14:27 UTC, gurisko commented
These changes do not comply with the latest release 2.6.0. Please have a look at #18254

2017-07-22 15:21 UTC, closed without merging