[react-navigation] Adds createNavigator, createNavigationContainer
DefinitelyTyped/DefinitelyTyped pull request #18217
Opened 2017-07-19 14:06 UTC by iRoachie

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Adds createNavigator, createNavigationContainer. Url and reference in definitions

2017-07-24 03:05 UTC, iRoachie commented
@huhuanming Can you check this for me>?

2017-07-24 03:11 UTC, huhuanming commented
😄
sure... 
let me check that.

2017-07-24 06:21 UTC, huhuanming requested changes

2017-07-24 06:21 UTC, huhuanming commented on types/react-navigation/index.d.ts
> +  navigatorConfig?: any,
is the `navigatorConfig` type `StackNavigatorConfig`?

2017-07-24 11:06 UTC, iRoachie commented on types/react-navigation/index.d.ts
> +  navigatorConfig?: any,
Not sure actually. The flow typings have ‘any’ there as well.

2017-07-24 12:00 UTC, iRoachie commented on types/react-navigation/index.d.ts
> +  navigatorConfig?: any,
Nah its doesn't have to be, it could be Tab, Drawer, Stack. The flow types changed recently.

2017-07-24 12:07 UTC, iRoachie commented on types/react-navigation/index.d.ts
> +  navigatorConfig?: any,
I'm not sure actually. The flow types changed since I made the PR so I have to update this.

2017-08-14 18:21 UTC, mhegazy commented
@iRoachie are you sill interested in pursuing this PR? if so can we resolve the comment above?

2017-08-14 18:48 UTC, iRoachie commented
@mhegazy Updated

2017-08-14 19:10 UTC, merged