[ora] introduce typings for v1
DefinitelyTyped/DefinitelyTyped pull request #18233
Opened 2017-07-19 22:35 UTC by BendingBender

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sindresorhus/ora
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-07-19 22:41 UTC, BendingBender commented
_types/ora/index.d.ts_

to authors (@screendriver). Could you review this PR?
:+1: or :-1:?

2017-07-20 05:10 UTC, screendriver requested changes
Please fix [indentation](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes) (4 spaces)

2017-07-20 07:45 UTC, BendingBender commented
@screendriver Do you mind if I change the URL to your profile in the header to you github profile so that dt-bot can find and notify you automatically the next time?

2017-07-21 14:16 UTC, screendriver commented on types/ora/index.d.ts
> +  'dots'
2 spaces

2017-07-21 14:17 UTC, screendriver commented
> [@screendriver](https://github.com/screendriver) Do you mind if I change the URL to your profile in the header to you github profile so that dt-bot can find and notify you automatically the next time?

Of course, thank you ;-) I thought I can add any URL but it seems that it must be my [profile URL](https://github.com/screendriver) here at GitHub.

There are still 2 spaces at `type SpinnerName`. The rest of the changes looks good to me 👍

2017-07-21 17:02 UTC, merged