Add Rangy Class Applier module to Rangy
DefinitelyTyped/DefinitelyTyped pull request #18259
Opened 2017-07-20 16:51 UTC by MaximeKjaer

This PR introduces type definitions for the [Rangy Class Applier module](https://github.com/timdown/rangy/wiki/Class-Applier-Module) which is a part of [Rangy](https://github.com/timdown/rangy).

This module is a global plugin, since it adds a method to the global `RangyStatic` object `rangy`, and adds its own `ClassApplier` type to the global scope. As such I've tried to follow the [global plugin template](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/global-plugin-d-ts.html) and to add annotations for the dependence on the [global `rangy-core` library](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#dependencies-on-global-libraries). But this is my first contribution to DefinitelyTyped, so please tell me if that isn't the way to go.

***

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/timdown/rangy/wiki/Class-Applier-Module
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-07-20 17:24 UTC, MaximeKjaer commented
@MidnightDesign @ashubham

2017-07-21 06:49 UTC, MidnightDesign requested changes

2017-07-21 06:49 UTC, MidnightDesign commented on types/rangy/rangy-classapplier.d.ts
> +    createClassApplier(theClass: string, options?: RangyClassApplierOptions, tagNames?: Array<string> | string): RangyClassApplier;
Why not `string[]`?

2017-07-21 06:49 UTC, MidnightDesign commented on types/rangy/rangy-classapplier.d.ts
> +    elementAttributes?: {[attribute: string]: any};
`any`? Can't this be more restrictive?

2017-07-21 06:49 UTC, MidnightDesign commented on types/rangy/rangy-classapplier.d.ts
> +interface RangyClassApplier extends RangyClassApplierOptions {
What's up with all this returned anys? What gets returned there?

2017-07-21 10:24 UTC, MaximeKjaer reviewed
Added @MidnightDesign's suggestions

2017-07-21 11:38 UTC, MidnightDesign commented on types/rangy/rangy-classapplier.d.ts
> +interface RangyClassApplier extends RangyClassApplierOptions {
The return type of `getNativeTextRange()` seems to be [well defined](https://github.com/timdown/rangy/wiki/Rangy-Selection#getnativetextrange) for example.

2017-07-21 11:40 UTC, MidnightDesign approved these changes

2017-07-21 11:40 UTC, MidnightDesign commented
LGTM. Thank you!

2017-07-21 15:35 UTC, MaximeKjaer commented on types/rangy/rangy-classapplier.d.ts
> +interface RangyClassApplier extends RangyClassApplierOptions {
Yeah that should be tightened up a bit. But `getNativeTextRange` isn't part of the Class Applier module, so I'll leave that for a separate PR.

My intention here was to do a first PR of a manageable size to get a feel for the whole process of submitting to DefinitelyTyped, and to do a bigger PR solving all the issues with Rangy after that (there are some other modules that would need to be typed, and some methods like `rangy.init()` are still undefined here). I'm happy to take care of them, just in the next PR 😊

2017-07-21 17:03 UTC, merged