Improved type definitions for Recharts
DefinitelyTyped/DefinitelyTyped pull request #18256
Opened 2017-07-20 14:26 UTC by mthmulders

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: Correct import style shown [here](http://recharts.org/#/en-US/guide/getting-started)
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-07-20 15:04 UTC, rapmue commented
I think @dt-bot has missed my PR to your branch @mthmulders . Do we have to do something about this?

2017-07-20 17:02 UTC, weswigham requested changes

2017-07-20 17:02 UTC, weswigham commented on types/recharts/tslint.json
> +		"no-single-declare-module": false,
Remove this rule ignore.

2017-07-20 17:02 UTC, weswigham commented on types/recharts/tslint.json
> +		"strict-export-declare-modifiers": false
And this one.

2017-07-20 17:02 UTC, weswigham commented on types/recharts/index.d.ts
> +declare module 'recharts' {
Then just remove this module wrapper from the file. Nothing else should need to be changed.

2017-07-20 17:23 UTC, mthmulders commented on types/recharts/index.d.ts
> +declare module 'recharts' {
@rapmue I'm not completely sure about this one. What's your thought?

2017-07-20 17:23 UTC, mthmulders commented
@rapmue I think that @dt-bot only monitors PR's to this repo, not to mine. That's why I merged your PR into my repo, so that now we can merge my repo into this one. I think all of your changes are in this PR, but correct me if I'm wrong.

2017-07-20 19:11 UTC, mthmulders commented
@weswigham, as you can see I can remove the two lines from tslint.json, but it breaks the Travis build. To use Recharts correctly, the [docs](http://recharts.org/#/en-US/guide/getting-started) say you should import its types using `import { LineChart, Line } from 'recharts'`. How to get that working using the default tslint settings?

2017-07-20 19:17 UTC, weswigham commented
@mthmulders just remove the `declare module 'recharts'` and accompanying curly braces wrapping all your declarations. The file itself acts as your module declaration.

2017-07-20 19:44 UTC, mthmulders commented
@weswigham Thanks for the hint, that seems to fix it. Need to export the interface props as well, although that is not strictly required for Recharts but otherwise tslint will say
> Prefer to explicitly write 'export' for an external module export.

2017-07-20 19:50 UTC, mthmulders commented on types/recharts/index.d.ts
> +declare module 'recharts' {
Nevermind, got it sorted already.

2017-07-20 20:10 UTC, weswigham commented
Great, these look excellent now

2017-07-20 20:10 UTC, merged

2017-07-21 11:43 UTC, mthmulders commented
Thanks for the help, @weswigham!