[angular-ui-router-uib-modal] remove typings provided by package directly
DefinitelyTyped/DefinitelyTyped pull request #18333
Opened 2017-07-23 16:20 UTC by BendingBender

One of the packages to remove from the list in #13364

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

2017-07-23 16:30 UTC, BendingBender commented
@nonplus: I am removing the typings for `angular-ui-router-uib-modal` from DefinitelyTyped because they are now available in the project repo (https://github.com/nonplus/angular-ui-router-uib-modal). Could you please give your ack?

2017-07-23 16:31 UTC, BendingBender commented
@weswigham any idea on how to fix the build breakage?

2017-08-05 00:11 UTC, sheetalkamat commented
@BendingBender Can you please fix the merge conflict. Thanks

2017-08-08 20:54 UTC, amcasey commented
@nonplus, do you have any concerns about this change?

2017-08-14 19:13 UTC, mhegazy requested changes

2017-08-14 19:13 UTC, mhegazy commented on notNeededPackages.json
> +            "asOfVersion": "0.11.0"
i think this should be `angular-ui-router-uib-modal@0.0.11` instead.

2017-08-14 19:34 UTC, BendingBender commented on notNeededPackages.json
> +            "asOfVersion": "0.11.0"
no idea how this happened, this was generated by dts-gen

2017-08-14 20:52 UTC, merged