Add declarations for "plotly.js/lib/core"
DefinitelyTyped/DefinitelyTyped pull request #18392
Opened 2017-07-26 01:29 UTC by gnestor

This resolves an issue with plotly.js + typescript + webpack: https://github.com/jupyterlab/jupyter-renderers/issues/10

2017-07-26 15:51 UTC, gnestor commented
@frederikaalund The issue is that when using plotly.js with webpack, the default export causes a runtime error (see https://github.com/jupyterlab/jupyter-renderers/issues/10#issue-245487543 for details). Importing `plotly.js/lib/core` resolves this issue, but the type declarations provided by `@types/plotly.js` don't provide declarations for the `plotly.js/lib/core` module (even though that module is identical to the default module). 

My solution: Add a type declaration at "plotly.js/lib/core" and simply export everything from the default export. Is there a better way to do this?

2017-07-26 19:12 UTC, blink1073 commented
This looks good to me.  @gnestor, the renderer works with this change locally to `node_modules`.

2017-07-27 22:58 UTC, gnestor commented
@typescript-bot Fixed!

2017-07-31 18:48 UTC, gnestor commented
@RyanCavanaugh This is ready to be reviewed

2017-07-31 22:38 UTC, sheetalkamat commented on types/plotly.js/tsconfig.json
> +        "lib/core.d.ts",
Please do not copy paste the file to create duplicate typings. 

You would want to follow something like what d3 typings do.
Please take a look at: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3/index.d.ts and the corresponding sub typings you can get eg. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-array/index.d.ts

This is what you need to do here as well.

2017-07-31 22:38 UTC, sheetalkamat requested changes
This isnt the right change, please take a look at the comment for more details

2017-08-01 15:29 UTC, gnestor commented on types/plotly.js/tsconfig.json
> +        "lib/core.d.ts",
Hi @sheetalkamat, thanks for taking a look! If you look at `lib/core.d.ts`, it is simply doing an `export * from 'plotly.js';`. The copied-and-pasted code is the test, which can be removed. The goal with this PR is to allow users to import from `plotly.js/lib/core` in addition to plain old `plotly.js` while still importing type declarations.

2017-08-01 17:28 UTC, sheetalkamat approved these changes

2017-08-01 17:29 UTC, sheetalkamat approved these changes

2017-08-01 17:29 UTC, merged

2017-08-01 17:32 UTC, gnestor commented
Thanks @sheetalkamat!