@types/gm Add GetterOptions for working with streams and identify operations
DefinitelyTyped/DefinitelyTyped pull request #18447
Opened 2017-07-27 17:07 UTC by maartenvanvliet

First commit on DefinitelyTyped so I hope I've done things correctly.

Added GetterOptions interface because identify operations need to buffer readStream in memory if you need to write()/stream() afterwards and the current definitions did not cover that.
See: https://github.com/aheckmann/gm/blob/c6a6c5a/README.md#streams

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
  - I see some linting errors, fixed a couple but still some remain.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - Documentation: https://github.com/aheckmann/gm/blob/c6a6c5a/README.md#streams
  - Source: https://github.com/aheckmann/gm/blob/c6a6c5a/lib/getters.js#L39
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-07-27 17:52 UTC, andy-ms commented
@maartenvanvliet There are some remaining lint errors.

2017-07-27 18:07 UTC, maartenvanvliet commented
@andy-ms I know, they were there before. Most are overloaded functions that should be using union types instead. There are now close to 2000 lint errors and I don't have the time to fix it tonight.

2017-07-27 18:21 UTC, maartenvanvliet commented
@andy-ms Fixed it, but disabled the "unified-signatures" exception rule. Too many linting errors for now.

2017-07-29 17:33 UTC, joelspadin requested changes

2017-07-29 17:33 UTC, ChaosinaCan commented on types/gm/index.d.ts
>          geometry(width: number, height?: number, option?: string): State;
Should the type of option be a ResizeOption?

2017-07-29 18:03 UTC, maartenvanvliet commented on types/gm/index.d.ts
>          geometry(width: number, height?: number, option?: string): State;
Yes, good call

2017-07-29 18:05 UTC, ChaosinaCan commented
👍

2017-07-31 20:55 UTC, merged