[three] Update to THREE.js r86 (0.86.0)
DefinitelyTyped/DefinitelyTyped pull request #18481
Opened 2017-07-28 21:54 UTC by vcasagrande

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://threejs.org/docs/ https://github.com/mrdoob/three.js/tree/r86
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

#13418

2017-08-02 23:06 UTC, sheetalkamat requested changes

2017-08-02 23:06 UTC, sheetalkamat commented on types/three/three-core.d.ts
> +        parameters: TextGeometryParameters;
I see the paraemters of type { text: string; parameters: TextGeometryParameters } https://github.com/mrdoob/three.js/blob/ff2ce5657cf1e2567c7d240ff881b2564d133570/src/geometries/TextGeometry.js#L32

2017-08-02 23:06 UTC, sheetalkamat commented on types/three/three-core.d.ts
> +    parameters: TextGeometryParameters
Dont see this.parameters assignment here? https://github.com/mrdoob/three.js/blob/ff2ce5657cf1e2567c7d240ff881b2564d133570/src/geometries/TextGeometry.js#L46

2017-08-02 23:06 UTC, sheetalkamat commented on types/three/three-core.d.ts
> +    constructor(radius: number, radials: number, circles: number, divisions: number, color1: number, color2: number);
Arent all these parameters optional? https://github.com/mrdoob/three.js/blob/dcfa48a23524c4ecd5637cd9060ccc1413d2b429/src/helpers/PolarGridHelper.js#L16

2017-08-03 02:36 UTC, efokschaner commented on types/three/three-core.d.ts
> +    constructor(color?: number|string, intensity?: number, width?: number, height?: number);
looks like color can also be a `THREE.Color`,
It ends up here:
https://github.com/mrdoob/three.js/blob/74d0bdc64271f3e7f1b23c331a733433b1ea9915/src/math/Color.js#L37

2017-08-03 03:38 UTC, efokschaner commented on types/three/three-core.d.ts
> +export class MeshToonMaterial extends MeshPhongMaterial {
There's also a `type` property that is undocumented but seems to be intentionally part of its public interface, see:
https://github.com/mrdoob/three.js/blob/e220a4baac6b415124cbfbf370f3c7aa44fbb13e/src/materials/MeshToonMaterial.js#L17

and for motivation:

https://threejs.org/docs/index.html#api/materials/Material

2017-08-03 03:48 UTC, efokschaner commented on types/three/three-core.d.ts
> +    UVGenerator?: any;
It needs to match this: https://github.com/mrdoob/three.js/blob/61520f0d8a935f599e658119d7020e0525e17f35/src/geometries/ExtrudeGeometry.js#L756

2017-08-03 03:51 UTC, efokschaner commented on types/three/three-core.d.ts
> +    addShapeList(shapes: Shape[], options?: ExtrudeGeometryParameters): void;
agreed, don't think it should be deleted, and in fact you should extract its interface and share it with the `UVGenerator?: any` above.

2017-08-14 19:14 UTC, mhegazy commented
Thanks for your contribution. This PR has unaddressed review commments and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2017-08-14 19:14 UTC, closed without merging