[react-redux] Add connectAdvanced from v5
DefinitelyTyped/DefinitelyTyped pull request #18488
Opened 2017-07-29 07:15 UTC by kenzierocks

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/reactjs/react-redux/blob/master/docs/api.md#user-content-connectAdvanced
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This PR adds the `connectAdvanced` function from `react-redux` v5. I didn't add any other functions, but I can if completeness is desired. I did add a `tslint.json`, but I got the following error running the linter:

```
[REDACTED]/DefinitelyTyped/node_modules/dtslint/bin/rules/definitelytyped-header-parser.js:83
        const [, version, a, b, c, v, nameReverse] = match;
              ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> ([REDACTED]/DefinitelyTyped/node_modules/dtslint/bin/index.js:15:41)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

2017-08-01 20:08 UTC, thasner requested changes
build is failing

2017-08-01 20:29 UTC, kenzierocks commented on types/react-redux/tslint.json
> +{ "extends": "dtslint/dt.json" }
Initially yes, as suggested in the PR template, but I think I'll remove it due to the high amount of failures.

2017-08-01 20:30 UTC, kenzierocks commented on types/react-redux/index.d.ts
> +interface AdvancedComponentDecorator<TOwnProps, TProps> {
Ok, can do

2017-08-01 20:34 UTC, kenzierocks commented on types/react-redux/index.d.ts
> +export interface ConnectOptions {
Ok, done.

2017-08-08 18:23 UTC, thasner commented
👍

2017-08-08 19:20 UTC, merged