Add node-geocoded definition.
DefinitelyTyped/DefinitelyTyped pull request #18503
Opened 2017-07-30 08:09 UTC by rosek86

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-08-01 18:31 UTC, sheetalkamat requested changes

2017-08-01 18:31 UTC, sheetalkamat commented on types/node-geocoder/index.d.ts
> +        'agol' | 'tomtom' | 'nominatimmapquest' |
Shouldnt this also have mapzen:  https://github.com/nchaulet/node-geocoder/blob/master/lib/geocoderfactory.js#L84

2017-08-14 19:15 UTC, mhegazy commented
@rosek86 are you still interested in pursuing this PR? if so can you address the review comments.

2017-08-20 09:06 UTC, rosek86 commented
Hello,

Mapzen is not listed in the documentation so I assume that it isn't fully supported.
https://github.com/nchaulet/node-geocoder#geocoder-provider

2017-08-30 18:20 UTC, merged