[react-redux] Update types for react-redux to support prop omission
DefinitelyTyped/DefinitelyTyped pull request #18510
Opened 2017-07-30 15:34 UTC by clayne11

The types were failing to remove props they injected from requirements
for the parents rendering them. By using Omit we can omit props that are
injected from the connect component so that we don't get errors during
parent rendering.

All of this is done through type inference so that end users don't have
to be aware that this is happening.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-08-01 19:40 UTC, thasner commented
@clayne11 can you provide an example of the problem this change is intended to solve?

2017-08-01 22:50 UTC, clayne11 commented
I added one test in the PR but I can add more examples.

If you look at the test I added:

```javascript

namespace RemoveInjectedAndPassOnRest {
    interface TProps {
        showGlobalSpinner: boolean;
        foo: string;
    }
    class SpinnerClass extends React.Component<TProps & DispatchProp<any>, {}> {
        render() {
            return (<div />);
        }
    }

    export const Spinner = connect((state: any) => {
        return { showGlobalSpinner: true };
    })(SpinnerClass);

    <Spinner foo='bar' />
}
```

In the render test I added the prop `<Spinner foo='bar' />`. My test would fail without the `foo='bar'` since it passes through the `foo: string` prop requirement but filters out the `showGlobalSpinner` prop which is injected by the `connect` HOC. With the previous current implementation, the test would pass withough adding `foo='bar'` even though the prop requiremen ts aren't being met for the wrapped component.

If you need further clarification let me know.

2017-08-08 16:15 UTC, thasner reviewed
thanks for the explanation

2017-08-08 16:15 UTC, thasner commented on types/react-redux/index.d.ts
> +export type DefaultingInferableComponentEnhancer<TInjectedProps> =
is this used anywhere?

2017-08-08 16:15 UTC, thasner commented on types/react-redux/index.d.ts
> +): InferableComponentEnhancerWithProps<TStateProps & DispatchProp<any>, TOwnProps>;
why are `DispatchProp<any>` added when `mapDispatchToProps` is undefined?

2017-08-08 18:21 UTC, clayne11 commented on types/react-redux/index.d.ts
> +export type DefaultingInferableComponentEnhancer<TInjectedProps> =
Nope good catch - I accidentally brought that over from other types I was working on. I'll remove it.

2017-08-08 18:22 UTC, clayne11 commented on types/react-redux/index.d.ts
> +): InferableComponentEnhancerWithProps<TStateProps & DispatchProp<any>, TOwnProps>;
That's how `react-redux` works:

> If you do not supply your own mapDispatchToProps function or object full of action creators, the default mapDispatchToProps implementation just injects dispatch into your component’s props.

https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

2017-08-08 18:27 UTC, thasner approved these changes
👍

2017-08-08 18:27 UTC, thasner commented on types/react-redux/index.d.ts
> +): InferableComponentEnhancerWithProps<TStateProps & DispatchProp<any>, TOwnProps>;
👍

2017-08-08 18:27 UTC, thasner requested changes
errr, waiting to remove the unused interface

2017-08-08 18:41 UTC, thasner approved these changes
👍

2017-08-08 20:48 UTC, amcasey commented
@clayne11 Do you want to try to resolve the merge conflicts?

2017-08-08 20:53 UTC, clayne11 commented
That merge is a bit broken - I'm going to rebase.

2017-08-08 20:59 UTC, clayne11 commented
Alright, it should be good to go now.

2017-08-08 21:19 UTC, thasner approved these changes

2017-08-09 17:33 UTC, amcasey commented on types/react-redux/index.d.ts
> +type Diff<T extends string, U extends string> = ({ [P in T]: P } & { [P in U]: never } & { [x: string]: never })[T];
These types seem rather complicated.  Would it make sense to add some sample uses to the test case below?

2017-08-09 18:36 UTC, clayne11 commented on types/react-redux/index.d.ts
> +type Diff<T extends string, U extends string> = ({ [P in T]: P } & { [P in U]: never } & { [x: string]: never })[T];
I'm not opposed to doing that. It's definitely not trivial.

2017-08-11 17:10 UTC, mhegazy commented
@clayne11 can you please resolve merge conflicts.

2017-08-14 19:09 UTC, merged

2017-08-14 20:43 UTC, coreh commented
🎉  This is a significant improvement for the usability of the library.

One suggestion: Can we make the `dispatch` field optional in `DispatchProp`?

```
export interface DispatchProp<S> {
    dispatch?: Dispatch<S>;
}
```

That way I don't need to add a prop compatible with `dispatch: Dispatch<S>` to all my controlled components that don't specify mapDispatchToProps, (Sometimes there's really nothing to dispatch) but I can add it to the ones where I want to dispatch and it will be type checked.

2017-08-14 20:47 UTC, clayne11 commented
That makes sense to me. If you open a PR for that I'll approve it.

2017-10-07 09:16 UTC, 19majkel94 commented
@clayne11 
Looks like your types doesn't work with optional props, like the one with 3rd party HOC, e.g. redux-form:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19989