add iso-3166-2 typings
DefinitelyTyped/DefinitelyTyped pull request #18525
Opened 2017-07-31 17:18 UTC by Sicilica

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-08-01 00:12 UTC, sheetalkamat requested changes

2017-08-01 00:12 UTC, sheetalkamat commented on types/iso-3166-2/index.d.ts
> +
May be you want to write this as below for it to be more readable
```TypeScript
export interface SubDivisionInfoPartial {
    type: string;
    name: string;
}

export interface SubDivisionInfoFull extends SubDivisionInfoPartial {
    countryName: string;
    countryCode: string;
    code: string;
    regionCode: string;
}

export interface SubDivisions {
    [subdivisionCode: string]: SubDivisionInfoPartial | SubDivisionInfoFull;
}


export interface CountryInfoPartial {
    name: string;
    sub: SubDivisions,
}

export interface CountryInfoFull extends CountryInfoPartial {
    code: string;
}

export interface CountryData {
    [countryCode: string]: CountryInfoPartial | CountryInfoFull;
}

export type InfoOrEmptyRecord<T> = T | {};

export function subdivision(code: string): InfoOrEmptyRecord<SubDivisionInfoFull>;
export function subdivision(countryCode: string, subdivisionCodeOrName: string): InfoOrEmptyRecord<SubDivisionInfoFull>;

export function country(countryCodeOrName: string): InfoOrEmptyRecord<CountryInfoFull>;

export const data: CountryData;

```

2017-08-01 00:12 UTC, sheetalkamat commented on types/iso-3166-2/index.d.ts
> +export function country(countryName: string): CountryInfo|{};
write the single definition as country(countryCodeOrName: string): CountryInfo

2017-08-02 16:05 UTC, Sicilica commented
Made most of the requested changes, in particular getting rid of the need for the tslint rule override.

Readability should be fairly well improved, but since the interfaces in this file will be exported to the calling context, I kept the namespaced interfaces (eg, SubdivisionInfo.Full and Subdivision.Partial instead of SubdivisionInfoFull and SubdivisionPartial).

Keeping the namespaces allows users of this file to simply use "SubdivisionInfo" without necessarily needing to know about the details of why there are two types internally.

2017-08-02 18:02 UTC, sheetalkamat approved these changes

2017-08-02 18:02 UTC, merged