[is-url-superb]: Add initial type definition
DefinitelyTyped/DefinitelyTyped pull request #18531
Opened 2017-08-01 01:32 UTC by kryops

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-08-01 18:10 UTC, sheetalkamat requested changes

2017-08-01 18:10 UTC, sheetalkamat commented on types/is-url-superb/index.d.ts
> +declare namespace isUrl {}
You dont need the namespace isUrl here.

2017-08-02 00:25 UTC, kryops commented on types/is-url-superb/index.d.ts
> +declare namespace isUrl {}
This is https://github.com/Microsoft/TypeScript/issues/5073 all over again.
Has there a good solution been found yet?
* `import isUrl = require('is-url-superb');` does not work with `"module": "ES2015"`
* `import isUrl from 'is-url-superb'` + `"allowSyntheticDefaultExports": true` works with webpack/babel, but breaks CommonJS (e.g. for testing)
* `import isUrl = require('is-url-superb');` with `"module": "esnext"` does not error, but does not seem to emit anything

2017-08-02 18:21 UTC, sheetalkamat approved these changes

2017-08-02 18:21 UTC, merged