Improve react-transition-group import
DefinitelyTyped/DefinitelyTyped pull request #18550
Opened 2017-08-01 22:33 UTC by tkrotoff

Allow to write:
```TypeScript
import { CSSTransition, Transition, TransitionGroup } from "react-transition-group";
```
instead of:
```TypeScript
import CSSTransition from "react-transition-group/CSSTransition";
import Transition from "react-transition-group/Transition";
import TransitionGroup from "react-transition-group/TransitionGroup";
```
(which is still possible)

2017-08-02 03:04 UTC, LKay requested changes
It's second exactly the same PR. Current export is correct. File index.js exports common js module and and type definition is correct. This should also be imported as cjs.

Disapproving this.

2017-08-02 07:58 UTC, tkrotoff commented
> It's second exactly the same PR.

I don't understand your sentence.

> File index.js exports common js module

True, you are refering to https://github.com/reactjs/react-transition-group/blob/v2.2.0/src/index.js#L6:
```JavaScript
module.exports = {
  Transition,
  TransitionGroup,
  CSSTransition,
};
```

Like 99% of npm packages, they use `module.exports` and you can still use ES6 syntax with them thanks to TypeScript. That's the whole point of TypeScript and Babel: use ES6 syntax today.

Try it by yourself, use `import { ... } from 'react-transition-group'` in your code and you will see that it runs exactly the same (beside the TypeScript error with current definition - hence this PR).

For the little story, react-transition-group authors don't advertise this use of `import` for [optimisation reasons](https://github.com/reactjs/react-transition-group/pull/40#issuecomment-319516752).

2017-08-02 08:39 UTC, Kovensky commented
It "works" by historical accident. This import you write that "works" will _not_ work on real module implementations.

https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#461-default-imports

2017-08-02 10:20 UTC, LKay commented
@tkrotoff Your PR is the same as #18403 and why it shouldn't be merged is explained in other's PR comments.

2017-08-02 20:10 UTC, sheetalkamat commented
Closing the pull request as per author's comment.

2017-08-02 20:10 UTC, closed without merging

2017-08-03 17:33 UTC, tkrotoff commented
@sheetalkamat @LKay @Kovensky 
The main author of react-transition-group officially support `import { Transition } from 'react-transition-group'` syntax. You can see the discussion here: https://github.com/reactjs/react-transition-group/issues/142#issuecomment-320033131

So this should be merged.

Your concerns about `"works" by historical accident` is not DefinitelyTyped concern but react-transition-group authors's since this syntax is officially supported.

2017-08-04 05:34 UTC, LKay commented
@tkrotoff You're talking about supporting it by the `react-transition-group` but not taking into consideration how Typescript resolves such modules. These are two different things. The fact is exports is cjs and current definitions reflect that.

2017-08-04 16:23 UTC, tkrotoff commented
> The fact is exports is cjs

Do you mean that if instead of:
```JavaScript
module.exports = {
  Transition,
  TransitionGroup,
  CSSTransition
};
```

[`index.js`](https://github.com/reactjs/react-transition-group/blob/v2.2.0/src/index.js#L6) contains:
```JavaScript
export {
  Transition,
  TransitionGroup,
  CSSTransition
};
```

It would be OK? (knowing of course that the code uses Babel)

2017-08-04 17:39 UTC, taion commented
@LKay 

This is a misunderstanding on your part. It is intended that

```js
import { CSSTransition, Transition, TransitionGroup } from "react-transition-group";
```

works.

Of course, it only works with the current transpiled code because of Babel quirks, but for the time being that's the best that's available, given the lack of actual existing ES module implementations.

When the time does come, the expectation here would be to perhaps add a proper ES module build. In the meantime, it's really the same as for React, where in standard cases, both:

```js
import React from 'react'; // And then use React.Component.
import React, { Component } from 'react'; // And then use Component.
```

are valid.

For TypeScript purposes, of course, whatever semantics are relevant will be appropriate, but it is in fact the case that those exports should be consumable via `import`.

2017-08-04 17:51 UTC, jquense commented
Yeah as one of the authors of the library 

`import { CSSTransition, Transition, TransitionGroup } from "react-transition-group";`

should absolutely be supported, the only reason there is a `module.exports` in src code is so the compiled code provides a better api for commonJS users. As for ppl saying this is a quirk, sure, thats sort of silly, ALL consumed code at this point is _actually_ A common js module, there isn't much value in being pedantic about it until the compiled, consumed code is really es modules.

2017-08-05 02:19 UTC, LKay commented
I created new PR to reflect transpiled code here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18622 

Note that imports of `Transition` uses ES6 default import, yet others use cjs imports. That's because how Babel compiles the source files. Check out the tests for example.

2017-08-18 14:44 UTC, tkrotoff commented
@LKay @Kovensky to sum-up:
- `import { ... } from 'react-transition-group'` works today
- react-transition-group author explained that it _should absolutely be supported_

Can we be pragmatic? If it hypothetically breaks in the future we can fix it: 
it's not set in stone.

2017-08-18 18:03 UTC, LKay commented
As soon as transpiled files will contain ES6 exports and not cjs exports I'll be first to change that. Unfortunately right now modules are exported as cjs and definitions are written as such, so the correct way of importing cjs module
in Typescript is to use cjs syntax `import X = require(...)`. It has been explained that node and to resolve modules differently and I pointed that out in the original library repo. The result was to create https://github.com/reactjs/react-transition-group/issues/147 in the original project.