Types for gulp-mustache
DefinitelyTyped/DefinitelyTyped pull request #18607
Opened 2017-08-03 13:00 UTC by CAD97

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-08-03 13:03 UTC, CAD97 commented
Fixed the test file which had a wrong name.

2017-08-03 16:56 UTC, sheetalkamat commented
@CAD97 The failure is in the tests file:

> 874Error: 'gulp-mustache/gulp-mustache-tests.ts' unnecessarily references 'node', which is already referenced in the type definition.
> 
> 875    at Object.<anonymous> (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/src/lib/module-info.ts:380:11)
> 
> 876    at Generator.next (<anonymous>)
> 
> 877    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/lib/module-info.js:4:58)
> 
> 878    at <anonymous>
>

2017-08-03 20:42 UTC, CAD97 commented
I can `squash` if desired. Fix was just removing extraneous `/// <reference types="node" />`.

2017-08-03 21:00 UTC, sheetalkamat requested changes

2017-08-03 21:00 UTC, sheetalkamat commented on types/gulp-mustache/index.d.ts
> +    interface Partials {
Might want to rename this as Hash instead? and write View as:
```TypeScript
type View = Hash | string | undefined;
```

2017-08-03 21:01 UTC, sheetalkamat commented
@CAD97 Please do not squash the changes. We will do that while merging.

2017-08-03 21:44 UTC, CAD97 commented on types/gulp-mustache/index.d.ts
> +    interface Partials {
👍

2017-08-04 22:55 UTC, sheetalkamat approved these changes

2017-08-04 22:55 UTC, merged