[semver] upgrade to 5.4, correct typings, add strict null checks
DefinitelyTyped/DefinitelyTyped pull request #18680
Opened 2017-08-07 00:25 UTC by BendingBender

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/npm/node-semver/blob/master/semver.js; https://github.com/npm/node-semver
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-08-07 00:27 UTC, BendingBender commented
@Bartvds: Could you review this PR?

2017-08-17 20:03 UTC, DanielRosenwasser requested changes

2017-08-17 20:03 UTC, DanielRosenwasser commented on types/semver/index.d.ts
> +export function inc(v: string | SemVer, release: ReleaseType, loose?: boolean, identifier?: string): string | null;
I don't know if this is correct. See https://github.com/npm/node-semver/blob/ec6f97ad9bb4e8ffe9100c2f331f4e0015a24212/semver.js#L476-L478

2017-08-17 20:48 UTC, BendingBender commented on types/semver/index.d.ts
> +export function inc(v: string | SemVer, release: ReleaseType, loose?: boolean, identifier?: string): string | null;
It's not documented but this is how it's implemented.

2017-08-17 20:49 UTC, BendingBender commented on types/semver/index.d.ts
> +export function inc(v: string | SemVer, release: ReleaseType, loose?: boolean, identifier?: string): string | null;
Sorry, you're absolutely right. Will fix it.

2017-08-17 20:53 UTC, BendingBender commented on types/semver/index.d.ts
> +export function inc(v: string | SemVer, release: ReleaseType, loose?: boolean, identifier?: string): string | null;
OK, looked it up, my typings seem to be correct, you were looking at the wrong `inc()`. This is the corresponding one: https://github.com/npm/node-semver/blob/ec6f97ad9bb4e8ffe9100c2f331f4e0015a24212/semver.js#L485-L496

2017-08-18 22:28 UTC, DanielRosenwasser commented on types/semver/index.d.ts
> +export function inc(v: string | SemVer, release: ReleaseType, loose?: boolean, identifier?: string): string | null;
Sorry about that; could you resolve the merge conflicts? That way I can pull this in.

2017-08-21 09:07 UTC, BendingBender commented on types/semver/index.d.ts
> +export function inc(v: string | SemVer, release: ReleaseType, loose?: boolean, identifier?: string): string | null;
Done. It would be really helpful if you could merge this one in before you merge any other pull requests regarding `semver`.

2017-08-22 04:17 UTC, DanielRosenwasser approved these changes

2017-08-22 04:17 UTC, merged