Add echart method and `graphic` declaration.
DefinitelyTyped/DefinitelyTyped pull request #18685
Opened 2017-08-07 08:13 UTC by AntiMoron

0. Add declaration of graphic.
1. Add method ```convertFromPixel```

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
    - https://ecomfe.github.io/echarts-doc/public/en/api.html#echartsInstance.convertFromPixel
    - https://ecomfe.github.io/echarts-doc/public/en/api.html#echarts.graphic

Tested and used in my production code.

2017-08-07 08:18 UTC, AntiMoron commented
:+1

2017-08-07 08:19 UTC, AntiMoron commented
👍

2017-08-08 19:16 UTC, mhegazy requested changes
Also please add tests.

2017-08-08 19:16 UTC, mhegazy commented on types/echarts/index.d.ts
> +    const graphic: any;
```ts
const graphic: {
    clipPointsByRect (points: number[][], rect: Rectangle) : number[][];
    clipRectByRect (targetRect: Rectangle, rect: Rectangle) : Rectangle;
}
```

2017-08-10 03:26 UTC, AntiMoron commented on types/echarts/index.d.ts
> +    const graphic: any;
👍 

FWIW, `LinearGradient` isn't included in the document but used in the official [demo](http://echarts.baidu.com/demo.html#bar-gradient).

```
import * as EChart from 'echarts';

new (<any>EChart.graphic).LinearGradient
```

2017-08-10 03:30 UTC, AntiMoron commented on types/echarts/index.d.ts
> +    const graphic: any;
type ```Rectangle``` needs to be added then...

2017-08-10 03:59 UTC, AntiMoron commented on types/echarts/index.d.ts
> +    const graphic: any;
Modified.

2017-08-14 02:55 UTC, AntiMoron commented
@mhegazy Please review the code and decide whether it can merge now.

2017-08-14 11:34 UTC, AM-young-fun reviewed
Add typed object & apis.

2017-08-14 20:55 UTC, merged