[superagent] Added error response type
DefinitelyTyped/DefinitelyTyped pull request #18775
Opened 2017-08-09 06:49 UTC by SamuelMarks

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: See [`Response.prototype.toError`](https://github.com/visionmedia/superagent/blob/822fe7c16ec46c054f31480558ac10d9fef0673f/lib/node/response.js#L88)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-08-09 08:35 UTC, mxl requested changes

2017-08-09 08:35 UTC, mxl commented on types/superagent/index.d.ts
> +    interface ErrorResponse extends Error {
I think `ResponseError` is better name .

2017-08-10 01:35 UTC, SamuelMarks commented on types/superagent/index.d.ts
> +    interface ErrorResponse extends Error {
Sure thing, changed it: https://github.com/SamuelMarks/DefinitelyTyped/commit/0fe027fe89391de491d7002adda078439d7a2956 on my [superagent-patch-error](https://github.com/SamuelMarks/DefinitelyTyped/tree/superagent-patch-error) branch.

(not sure why it didn't get appended to this PR?)

2017-08-10 08:12 UTC, paplorinc commented
I'm on a vacation, will review later, if it's still open.

2017-08-10 08:17 UTC, mxl approved these changes

2017-08-10 23:36 UTC, merged