[ramda] Updated definitions for better type inference + narrower types
DefinitelyTyped/DefinitelyTyped pull request #18873
Opened 2017-08-11 14:42 UTC by kujon

Hello,

this PR improves the type inference situation and narrows certain definitions for improved type safety:
1) `countBy` now has got a specific return type and ensures that the passed function is compatible with elements in the array.
2) `keys` return type is narrowed down to the actual keys of the object.
3) `sortBy` ensures that the passed function is compatible with elements in the array.
4) `toPairs` automatically infers the return type from the type of the object.
5) `values` automatically infers the return type from the type of the object.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://ramdajs.com/docs/#countBy, http://ramdajs.com/docs/#keys, http://ramdajs.com/docs/#sortBy, http://ramdajs.com/docs/#toPairs, http://ramdajs.com/docs/#values
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-08-16 20:40 UTC, DanielRosenwasser requested changes

2017-08-16 20:40 UTC, DanielRosenwasser commented on types/ramda/index.d.ts
> +        keys<T>(x: T): Array<keyof T>;
This is technically not correct since types are open-ended; the known set of properties on an object may be a subset of those that exist at runtime.

2017-08-16 23:27 UTC, LiamGoodacre commented on types/ramda/index.d.ts
> +        keys<T>(x: T): Array<keyof T>;
Quick demonstration: [playground link](http://www.typescriptlang.org/play/index.html#src=type%20M%20=%20{%20x:%20number,%20y:%20string,%20z:%20boolean%20}%0D%0Atype%20N%20=%20{%20x:%20number,%20y:%20string%20}%0D%0A%0D%0A//%20note%20that%20`M%20<:%20N`,%20therefore:%0D%0Aconst%20m:%20M%20=%20{%20x:%2042,%20y:%20"hi",%20z:%20true%20}%0D%0Aconst%20n:%20N%20=%20m%0D%0A%0D%0Aconst%20keys%20=%20<T>(t:%20T):%20Array<keyof%20T>%20=>%20Object.keys(t)%20as%20any%0D%0A%0D%0Aconst%20km%20=%20keys(m)%20//%20computes:%20`km:%20Array<'x'%20|%20'y'%20|%20'z'>`%0D%0Aconst%20kn%20=%20keys(n)%20//%20computes:%20`kn:%20Array<'x'%20|%20'y'>`%0D%0A%0D%0A//%20the%20keys%20are%20actually%20the%20same%0D%0Adocument.write(JSON.stringify({%0D%0A%20%20%20%20km,%0D%0A%20%20%20%20kn%20//%20i.e:%20`kn`%20contains%20`'z'`%0D%0A}))%0D%0A)

```typescript
type M = { x: number, y: string, z: boolean }
type N = { x: number, y: string }

// note that `M <: N`, therefore:
const m: M = { x: 42, y: "hi", z: true }
const n: N = m

const keys = <T>(t: T): Array<keyof T> => Object.keys(t) as any

const km = keys(m) // computes: `km: Array<'x' | 'y' | 'z'>`
const kn = keys(n) // computes: `kn: Array<'x' | 'y'>`

// the keys are actually the same
document.write(JSON.stringify({
    km,
    kn // i.e: `kn` contains `'z'`
}))
```

2017-08-17 12:29 UTC, kujon commented on types/ramda/index.d.ts
> +        keys<T>(x: T): Array<keyof T>;
Am I correct in thinking that the same would apply to `values` and `toPairs`?

2017-08-17 16:59 UTC, DanielRosenwasser commented on types/ramda/index.d.ts
> +        keys<T>(x: T): Array<keyof T>;
@kujon yup, same with those functions. You run the risk of an unhandled type.

2017-08-29 00:43 UTC, minestarks commented
@kujon please address the comments. If no activity I'll close this out in a few days. Thanks!

2017-09-06 13:23 UTC, kujon commented
I've reverted the changes to `keys`, `values` and `toPairs` as I don't see how they can be improved given the CR comments.

2017-09-07 04:53 UTC, DanielRosenwasser approved these changes

2017-09-07 12:48 UTC, kujon commented
Does anyone have an idea of why the TSLint started failing suddenly?

2017-09-07 17:06 UTC, merged