react-native Dimensions: Added addEventListener/removeEventListener
DefinitelyTyped/DefinitelyTyped pull request #18885
Opened 2017-08-11 20:34 UTC by adrianhall

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X\] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/dimensions.html
- [X] Increase the version number in the header if appropriate.

2017-08-11 22:04 UTC, iRoachie requested changes

2017-08-11 22:04 UTC, iRoachie commented on types/react-native/index.d.ts
> +// Type definitions for react-native 0.48
Remove this. 0.48 ins't out as yet.

2017-08-11 22:04 UTC, iRoachie commented on types/react-native/index.d.ts
> +//		   Adrian Hall <https://github.com/adrianhall>
Adding your name here means that you become a maintainer and all issues and pull requests will be sent to your email as well. Just making sure you know what this means.

2017-08-12 00:08 UTC, adrianhall commented on types/react-native/index.d.ts
> +// Type definitions for react-native 0.48
Will do

2017-08-12 00:09 UTC, adrianhall commented on types/react-native/index.d.ts
> +//		   Adrian Hall <https://github.com/adrianhall>
Did not realize that - should probably back that out here.  Next commit will have the right thing here.

2017-08-12 01:45 UTC, iRoachie commented
👍🏽

2017-08-14 10:29 UTC, merged