UglifyJS IE8 flag
DefinitelyTyped/DefinitelyTyped pull request #18905
Opened 2017-08-13 12:42 UTC by jameswilddev

Added the IE8 flag as documented in https://github.com/mishoo/UglifyJS2#minify-options.

This type definition might need some review; the mangling/compression objects don't have strict interfaces defined, and by mistyping a property I was able to get an output other than MinifyOutput from the minify function.

Otherwise very good though, thanks!

2017-08-13 18:04 UTC, tkrotoff commented
The definition is for UglifyJS **2**. The link you gave is for UglifyJS **3**.
Here the documentation for version 2: https://github.com/mishoo/UglifyJS2/tree/v2.x and there is no ie8 flag.

What should be done here is move version 2 to a directory named v2 and implement a new definition for v3.

2017-08-13 18:07 UTC, jameswilddev commented
Aha, well spotted!

2017-08-17 05:21 UTC, DanielRosenwasser commented
So should I close this out?

2017-08-17 06:02 UTC, tkrotoff commented
@DanielRosenwasser Yes

2017-08-18 13:37 UTC, tkrotoff requested changes
Avoid typescript-bot to merge this PR, see above comment

2017-08-18 22:22 UTC, closed without merging