[react-native] Added missing type cases for ItemSeparatorComponent on FlatList
DefinitelyTyped/DefinitelyTyped pull request #18924
Opened 2017-08-13 22:57 UTC by mcousillas6

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X ] Provide a URL to documentation or source code which provides context for the suggested changes: <https://facebook.github.io/react-native/docs/flatlist.html#itemseparatorcomponent>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Fixes #18823

2017-08-13 22:59 UTC, iRoachie approved these changes

2017-08-14 10:23 UTC, alloy requested changes

2017-08-14 10:23 UTC, alloy commented on types/react-native/index.d.ts
> +    ItemSeparatorComponent?: React.ComponentClass<any> | React.ReactElement<any> | (() => React.ReactElement<any>) | null
I’m confused, [we determined](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18823#issuecomment-321985718) that this was supposed to be just: `React.ComponentClass<any> | null`, right?

Afaik it should definitely _not_ have `React.ReactElement<any>`.

2017-08-14 11:33 UTC, mcousillas6 commented on types/react-native/index.d.ts
> +    ItemSeparatorComponent?: React.ComponentClass<any> | React.ReactElement<any> | (() => React.ReactElement<any>) | null
Oh, I understood that the idea was to keep the React.ComponentClass and then the other two for `ReactElement`, sorry about that misunderstanding.

From what I've tested while getting the PR ready, `React.ComponentClass` does not work for  `React.StatelesComponents`, `ItemSeparatorComponent?: React.ComponentClass<any> | null` was the one that the spec had before I opened the issue. 

I'm not entirely sure about the `ReactElement<any>` if that should not be permitted then the solution that works is `ItemSeparatorComponent?: React.ComponentClass<any> | React.StatelessComponent<any> | null`

Again, sorry about that misunderstanding.

2017-08-14 16:37 UTC, alloy commented on types/react-native/index.d.ts
> +    ItemSeparatorComponent?: React.ComponentClass<any> | React.ReactElement<any> | (() => React.ReactElement<any>) | null
Oops, re-reading my last comment on the issue it seems like I suggested the wrong typing and here again, my bad. I meant `React.ComponentType<any> | null`.

`ReactElement` is afaik the output of a `React.ComponentClass` or `React.StatelessComponent`, which is not what the React Native source expects (it does `<ItemSeparatorComponent … />`)

2017-08-15 12:01 UTC, mcousillas6 commented on types/react-native/index.d.ts
> +    ItemSeparatorComponent?: React.ComponentClass<any> | React.ReactElement<any> | (() => React.ReactElement<any>) | null
`React.ComponentType<any> | null` Worked perfectly 👌 .

2017-08-15 12:02 UTC, mcousillas6 commented
@alloy Updated the typing to use `React.ComponentType`, worked like a charm.

2017-08-15 16:24 UTC, alloy commented
Ace, thanks for bearing with me and your contribution 👏👏👏

2017-08-15 16:25 UTC, merged