Openstack wrapper
DefinitelyTyped/DefinitelyTyped pull request #18927
Opened 2017-08-14 03:59 UTC by sanjaymadane

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-08-14 17:05 UTC, mhegazy submitted a review, later dismissed

2017-08-14 17:05 UTC, mhegazy commented on types/openstack-wrapper/index.d.ts
> +declare module "openstack-wrapper" {
do not wrap in a module declaration, i.e. `declare module "openstack-wrapper" { ...`. instead, export declarations directelly:

```ts
 export interface RequestOption {
...
```

2017-08-14 17:05 UTC, mhegazy commented on types/openstack-wrapper/index.d.ts
> +export default "openstack-wrapper"
is the default export of this module a string?

2017-08-15 04:20 UTC, sanjaymadane reviewed
Hi, @mhegazy - as per your review comments. updated code and committed.

2017-08-15 18:24 UTC, DanielRosenwasser commented
Can you add a `tslint.json` as requested by the checklist? See https://github.com/DefinitelyTyped/DefinitelyTyped/tree/d542dc45448a3759649e27d6579dd5af33928131#lint for more details.

Note that the `Function` type is not allowed by the current lint rules. If you could provide a more accurate function type, or use `(...args: any[]) => any` instead, that would be better. If not, you can disable that lint rule.

2017-08-15 18:24 UTC, DanielRosenwasser requested changes
Can you add a `tslint.json` as requested by the checklist? See https://github.com/DefinitelyTyped/DefinitelyTyped/tree/d542dc45448a3759649e27d6579dd5af33928131#lint for more details.

Note that the `Function` type is not allowed by the current lint rules. If you could provide a more accurate function type, or use `(...args: any[]) => any` instead, that would be better. If not, you can disable that lint rule.

2017-08-16 17:00 UTC, mhegazy commented on types/openstack-wrapper/tsconfig.json
> +        "strictNullChecks": false,
can you also make this `true` please.

2017-08-17 05:14 UTC, DanielRosenwasser approved these changes

2017-08-17 05:15 UTC, merged