[knockout] added missing API for ko.selectExtensions.writeValue()
DefinitelyTyped/DefinitelyTyped pull request #19037
Opened 2017-08-16 17:12 UTC by BenjaminEckardt

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/knockout/knockout/blob/master/src/binding/selectExtensions.js#L23
- [x] Increase the version number in the header if appropriate.

2017-08-17 20:56 UTC, Igorbek requested changes

2017-08-17 20:56 UTC, Igorbek commented on types/knockout/index.d.ts
> +        writeValue(element: HTMLElement, value: any,  allowUnset: boolean): void;
- I think it should be optional, to not introduce breaking change; according to code it doesn't rely on any particular value to be certainly there
- please fix double space

2017-08-18 01:10 UTC, BenjaminEckardt commented
@Igorbek: i have applied your requests changes.

2017-08-18 21:40 UTC, Igorbek approved these changes

2017-08-18 21:40 UTC, merged