[es6-promisify] Add typings
DefinitelyTyped/DefinitelyTyped pull request #19048
Opened 2017-08-16 23:41 UTC by harryshipton

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-08-16 23:43 UTC, harryshipton commented
These were the best typings that I could make at the current time.

Should Microsoft/TypeScript#1360 be resolved, then the typings could be improved as per the comment that I've added.

2017-08-17 17:12 UTC, DanielRosenwasser requested changes

2017-08-17 17:12 UTC, DanielRosenwasser commented on types/es6-promisify/index.d.ts
> +interface Settings {
Could you wrap this in an `es6_promisify` namespace so that users can access the `Settings` type?

2017-08-17 18:10 UTC, harryshipton commented
Before merging, I'll be updating the tests to reflect the exported Settings object, including type testing it.

2017-08-18 22:25 UTC, merged