[dompurify] enhance typings
DefinitelyTyped/DefinitelyTyped pull request #19077
Opened 2017-08-17 16:49 UTC by falsandtru

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: no document, see sources https://github.com/cure53/DOMPurify/blob/master/src/purify.js

2017-08-17 20:08 UTC, DanielRosenwasser requested changes

2017-08-17 20:08 UTC, DanielRosenwasser commented on types/dompurify/index.d.ts
> +declare var DOMPurify: DOMPurify;
I think this should be changed to be something like

```ts
declare var DOMPurify: IDOMPurify;
export = DOMPurify;
export as namespace DOMPurify;
```

2017-08-17 20:54 UTC, falsandtru commented on types/dompurify/index.d.ts
> +declare var DOMPurify: DOMPurify;
adopted.

2017-08-18 10:30 UTC, falsandtru commented on types/dompurify/index.d.ts
> +    | null;
Seems like TS cannot use nullable union types. Is this a spec?

2017-08-18 21:22 UTC, DanielRosenwasser commented on types/dompurify/index.d.ts
> +    | null;
What exactly do you mean by "nullable union types"?

2017-08-18 21:30 UTC, falsandtru commented on types/dompurify/index.d.ts
> +    | null;
I want to get `DOMPurifyHookEvent: DOMPurifySanitizeElementHookEvent | DOMPurifySanitizeAttributeHookEvent | null` but `null` is removed by compiler. So I actually got `DOMPurifyHookEvent: DOMPurifySanitizeElementHookEvent | DOMPurifySanitizeAttributeHookEvent`. This type doesn't have `null`. How can I add to this type possibility to be `null`?

2017-08-18 22:03 UTC, DanielRosenwasser commented on types/dompurify/index.d.ts
> +    | null;
I'm not sure; under `strictNullChecks` this should just work. Can you send a repro to the TS issue tracker?

2017-08-18 22:26 UTC, falsandtru commented on types/dompurify/index.d.ts
> +    | null;
I checked that type again then it works fine. Something was wrong. Now there is no problem. Please merge.

2017-08-18 22:32 UTC, merged