Nightmare: Add typeInterval constructor option and screenshot overload for clipping path
DefinitelyTyped/DefinitelyTyped pull request #19109
Opened 2017-08-17 22:48 UTC by delesseps

* screenshot over load - https://github.com/segmentio/nightmare#screenshotpath-clip
* typeInterval - https://github.com/segmentio/nightmare#typeinterval-default-100ms

2017-08-18 21:52 UTC, DanielRosenwasser requested changes

2017-08-18 21:52 UTC, DanielRosenwasser commented on types/nightmare/index.d.ts
> +    screenshot(path: string, clip: Object): Nightmare;
Could you add an explicit type for the shape of `clip`? Either a declared one, or a type literal like `{ x: number, y: ... }`

Also, [according to the source](https://github.com/segmentio/nightmare/blob/a835558067c0dd72b5b10c14613d9071aef39d13/lib/actions.js#L586-L602), it looks like the appropriate overloads here would be

```ts
screenshot(path: string, done?: (err: any) => void): Nightmare;
screenshot(clip: { x: number, y: number, width: number, height: number }, done?: (err: any) => void): Nightmare;
screenshot(path: string, clip?: { x: number, y: number, width: number, height: number }, done: (err: any) => void): Nightmare;
```

2017-08-22 23:43 UTC, delesseps reviewed
Have adjusted as per feedback.  Thanks @DanielRosenwasser

2017-08-22 23:43 UTC, delesseps commented on types/nightmare/index.d.ts
> +    screenshot(path: string, clip: Object): Nightmare;
Thanks @DanielRosenwasser for the feedback.  I have adjusted and added overloads to handle the buffer being returned too.

2017-08-30 01:50 UTC, delesseps commented
Hi @DanielRosenwasser is there anything that needs to be done to get this merged?

2017-09-06 23:27 UTC, merged