Fix a problem when implement the `_handleFile`
DefinitelyTyped/DefinitelyTyped pull request #19112
Opened 2017-08-18 06:16 UTC by HyunSeob

When implementing the `StorageEngine`, I did have to implement `_handleFile` & `_removeFile`.
But it had a problem. When I call the `callback` function, I have to specify all fields of the `Express.Multer.File` interface. Actually, it's not required.

So, I add a new interface which named `FileInfo`. It's similar to `Express.Multer.File`, but all fields are optional.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-08-18 12:11 UTC, mxl requested changes

2017-08-18 12:11 UTC, mxl commented on types/multer/index.d.ts
> +        _handleFile(req: express.Request, file: Express.Multer.File, callback: (error?: any, info?: FileInfo) => void): void;
It's better to use `Partial<Express.Multer.File>` here. See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html.
For this you have to append `// TypeScript Version: 2.1` line to header.

2017-08-21 02:51 UTC, HyunSeob commented
@mxl 
Thank you for review. I just changed the code as you reviewed. Check it out!

2017-08-21 18:08 UTC, mxl approved these changes

2017-08-22 17:51 UTC, merged