react-redux: fix dispatchToProps being passed as object
DefinitelyTyped/DefinitelyTyped pull request #19143
Opened 2017-08-19 00:18 UTC by coreh

This PR fixes the resulting wrapped component type returned by the `connect()` HOC when the given `dispatchToProps` argument is an object. (Fixes issue #18955)

Previously we were using `MapDispatchToPropsObject` but that doesn't work with `Omit<T, K>`, so dispatch props were being preserved on the resulting object. I've replaced that with `TDispatchProps` instead.

I've added test code by @horiuchi, adapted from:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18955

Everything _seems_ to be working fine after this change, but I'm unsure if there might be any unintended consequences of this change.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18955
- [x] Increase the version number in the header if appropriate. **N/A**
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. **N/A**

2017-08-19 17:38 UTC, clayne11 requested changes
Looks like `MapDispatchToPropsObject` isn't being used anymore. Remove that and it looks good to me.

2017-08-20 14:19 UTC, horiuchi commented
@coreh Thank you for your PR about my issue! 👍

2017-08-21 11:50 UTC, coreh commented
@clayne11 `MapDispatchToPropsObject` is already removed

2017-08-21 14:50 UTC, clayne11 commented
Whoops - not sure how I missed that. All good then.

2017-08-21 14:51 UTC, clayne11 approved these changes

2017-08-22 17:52 UTC, merged