New definition for animejs
DefinitelyTyped/DefinitelyTyped pull request #19222
Opened 2017-08-21 21:40 UTC by A-Babin

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-08-21 21:48 UTC, andy-ms commented on types/animejs/tsconfig.json
> +{
Base this on `abs/tsconfig.json`. Just change "files".

2017-08-21 22:11 UTC, andy-ms commented on types/animejs/index.d.ts
> +	const enum EasingsEnum {
String enums are a ts2.4 feature, so you'll need to add a `// TypeScript Version: 2.4` comment on line 5 (just under the header).

2017-08-21 22:32 UTC, mhegazy requested changes

2017-08-21 22:32 UTC, mhegazy commented on types/animejs/index.d.ts
> +	const enum EasingsEnum {
do not use string enums in declaration files. they will break under `--isolatedModule`.

2017-08-21 22:53 UTC, mhegazy approved these changes

2017-08-22 17:56 UTC, merged

2017-08-22 18:05 UTC, A-Babin commented
Great! Thanks @andy-ms and @mhegazy for the assistance.