Add types for istanbuljs libraries
DefinitelyTyped/DefinitelyTyped pull request #19438
Opened 2017-08-29 19:24 UTC by jason0x43

This PR includes typings for the libraries in the [istanbuljs monorepo](https://github.com/istanbuljs/istanbuljs/tree/master/packages):

* istanbul-lib-coverage
* istanbul-lib-hook
* istanbul-lib-instrument
* istanbul-lib-report
* istanbul-lib-source-maps
* istanbul-reports

This PR includes typings for all the libraries mentioned above because their inter-dependence was going to make individual PRs a pain.

This is related to https://github.com/theintern/intern/issues/765

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-08-29 23:43 UTC, minestarks requested changes
LGTM except for the `strictNullChecks` nitpick

2017-08-29 23:43 UTC, minestarks commented on types/istanbul-reports/tsconfig.json
> +        "strictNullChecks": false,
Please, `"strictNullChecks": true` for all new packages

2017-08-29 23:43 UTC, minestarks commented on types/istanbul-lib-source-maps/tsconfig.json
> +        "strictNullChecks": false,
`"strictNullChecks": true`

2017-08-29 23:43 UTC, minestarks commented on types/istanbul-lib-report/tsconfig.json
> +        "strictNullChecks": false,
`"strictNullChecks": true`

2017-08-29 23:43 UTC, minestarks commented on types/istanbul-lib-instrument/tsconfig.json
> +        "strictNullChecks": false,
`"strictNullChecks": true`

2017-08-29 23:43 UTC, minestarks commented on types/istanbul-lib-hook/tsconfig.json
> +        "strictNullChecks": false,
`"strictNullChecks": true`

2017-08-29 23:43 UTC, minestarks commented on types/istanbul-lib-coverage/tsconfig.json
> +        "strictNullChecks": false,
`"strictNullChecks": true`

2017-08-30 00:45 UTC, minestarks approved these changes

2017-08-30 00:46 UTC, merged

2017-08-31 12:49 UTC, jason0x43 commented
@RyanCavanaugh, @andy-ms -- just pinging you because it's been a couple days since this was merged but it hasn't shown up yet in the npm repo.

2017-08-31 15:27 UTC, andy-ms commented
@jason0x43 Thanks, fixed.