fix net.createConnection() and Socket#connect() signatures.
DefinitelyTyped/DefinitelyTyped pull request #19456
Opened 2017-08-30 13:47 UTC by rogierschouten

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://nodejs.org/api/net.html#net_net_createconnection
https://nodejs.org/api/net.html#net_new_net_socket_options
https://nodejs.org/api/net.html#net_socket_connect_options_connectlistener
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-08-30 14:33 UTC, rogierschouten commented
I don't understand the failing tests - these don't seem to be caused by my commit?

2017-09-04 19:25 UTC, Flarna requested changes

2017-09-04 19:25 UTC, Flarna commented on types/node/index.d.ts
> +        path?: string;
According to doc the path is required for IPC connections. If I understood the code correct the presence of path property is used to decide if TCP or IPC should be used.

2017-09-04 19:25 UTC, Flarna commented on types/node/index.d.ts
> +        lookup?: Function;
Would be nice of the lookup property could be typed more concrete. I think it should be of same type as `dns.lookup()`, the variant using `LookupOneOptions`.

2017-09-04 19:25 UTC, Flarna commented on types/node/index.d.ts
> +    export interface NetConnectOpts extends TcpSocketConnectOpts, IpcSocketConnectOpts, SocketConstructorOpts {
This will no longer work once property `path` in `IpcSocketConnectOpts` is mandatory.

2017-09-04 19:25 UTC, Flarna commented on types/node/index.d.ts
> +        connect(options: SocketConnectOpts, connectionListener?: Function): void;
Actually `Socket.conncet()` returns `this` not `void`.

2017-09-05 08:30 UTC, rogierschouten commented
@Flarna thank you for your input, I've fixed all your comments. 

I suspect that the failing travis build is not due to my changes. I tried updating my master branch to the DT master branch and even then the tests fail. So the DT master branch doesn't seem to be stable at the moment.

2017-09-05 09:18 UTC, Flarna approved these changes

2017-09-05 09:18 UTC, Flarna commented
Thanks!
I think also that the fails are not related to your changes.

2017-10-16 15:26 UTC, merged