feat: upgrade Kendo UI definitions to 2017.3.913
DefinitelyTyped/DefinitelyTyped pull request #19739
Opened 2017-09-14 05:41 UTC by hadjieva

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-09-19 23:30 UTC, uniqueiniquity commented
Since you are updating to a new major version, please follow the guidelines at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#i-want-to-update-a-package-to-a-new-major-version

Also, please add tests to reflect your changes.

2017-09-20 06:57 UTC, Stamo-Gochev commented
@uniqueiniquity Is it OK for the folder name to contain dots, e.g. `v2017.3.913` or is it preferable to look like `v20173913`?

2017-09-20 16:07 UTC, uniqueiniquity commented
@Stamo-Gochev the dots should be fine.

2017-09-20 16:08 UTC, uniqueiniquity requested changes

2017-09-20 16:08 UTC, uniqueiniquity commented on types/kendo-ui/index.d.ts
> +        size?: number|Function;
On this and other uses of the type `Function`, please consider using a more specific type as discussed here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes

2017-09-21 12:46 UTC, Stamo-Gochev commented
@uniqueiniquity Can you shed some light why the changes result in the [error](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/278145143#L878):
```
Error: Directory /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/kendo-ui/v2017.3.913 has unused file index.d.ts
```
It looks correct according to the example: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/history/v2

As for the case with `Function` - our TS definitions are dependent on our docs:
http://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.template

Currently there is no information about the return type of the function:
```
columns.template String | Function
```
which prevents us from upgrading to the required format right now, but we have ideas for improving the TS definitions process as soon as we can.

2017-09-22 01:29 UTC, uniqueiniquity commented
@andy-ms Do you know why this error might be happening?

2017-09-22 14:00 UTC, andy-ms commented
We only support major versions that are natural numbers, just like NPM does.
In this case it doesn't seem that this is actually a major version change -- 2017.2.621 to 2017.3.913 . So it shouldn't be necessary to create a new directory.

2017-09-22 17:07 UTC, uniqueiniquity commented
Thanks, @andy-ms. My mistake, I apologize for the confusion.

2017-09-25 06:23 UTC, Stamo-Gochev commented
@uniqueiniquity @andy-ms Thanks for the clarifications. The TS definitions are now updated.

2017-09-25 15:37 UTC, uniqueiniquity approved these changes

2017-09-25 15:37 UTC, merged