[noble] add missing noble.removeEventListener() interface and noble.state variable
DefinitelyTyped/DefinitelyTyped pull request #19757
Opened 2017-09-14 18:27 UTC by keton

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
Example usage of [removeEventListener](https://github.com/sandeepmistry/noble-device/blob/5d69e81a8cb4f28e114f6f5b3c708f88d2d8a0c6/lib/util.js#L65) which was missing from .d.ts
likewise for [noble.state variable](https://github.com/sandeepmistry/noble-device/blob/5d69e81a8cb4f28e114f6f5b3c708f88d2d8a0c6/lib/util.js#L55)

2017-09-19 21:25 UTC, uniqueiniquity requested changes

2017-09-19 21:25 UTC, uniqueiniquity commented on types/noble/index.d.ts
> +export declare function removeListener(event: string, listener: Function): events.EventEmitter;
More general overload should come last, as described at http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html.

2017-09-19 21:25 UTC, uniqueiniquity commented on types/noble/index.d.ts
> +export declare function removeListener(event: string, listener: Function): events.EventEmitter;
Also, consider not using the type Function as described at 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes.

2017-09-21 09:17 UTC, keton commented
@uniqueiniquity I've moved general definitions to the bottom. 

As for using Function typed callbacks it's used all over existing EventEmitter definitions for this package. Most notably there's [on()](https://github.com/keton/DefinitelyTyped/blob/a218de290fdc242796bf6c03ae7bf7f189792e73/types/noble/index.d.ts#L25) for which I'm simply adding corresponding removeListener. 

I'm not sure but I think that some libraries are using noble's eventEmitter instances for their own events and that might be a reason why `on(event: string, listener: Function)` declarations were added.

2017-09-21 22:43 UTC, uniqueiniquity approved these changes

2017-09-21 22:43 UTC, merged