Bug fixes in EventHandlet<Event> of Field for onBlur and onChange
DefinitelyTyped/DefinitelyTyped pull request #19777
Opened 2017-09-15 08:43 UTC by rezanouri87

Bug fixes in EventHandlet<Event> of Field for onBlur and onChange events. Based on the redux-form's documentation, the signature of event handler for onBlur and onChange must be:

onBlur : (event, newValue, previousValue) => void [optional]
onChange : (event, newValue, previousValue) => void [optional]

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://redux-form.com/7.0.4/docs/api/field.md/#-code-onblur-event-newvalue-previousvalue-gt-void-code-optional->>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-09-15 09:03 UTC, rezanouri87 commented
Hey @carsonf, @aikoven, @LKay, @bancek, @alsiola .

I am not familiar with dt-bot that's why I mentioned you guys. Sorry for that!

Could you please review this PR?

Thanks

2017-09-21 23:16 UTC, uniqueiniquity commented
You would know better than me, but it seems that the type for onDragStart no longer matches the API documentation that you cited?

2017-10-02 22:00 UTC, RyanCavanaugh requested changes

2017-10-02 22:00 UTC, RyanCavanaugh commented on types/redux-form/redux-form-tests.tsx
> +    input.onDragStart({} as React.DragEvent<HTMLDivElement>, "newValue", "previousValue");
This code is wrong. You should be changing the declared types of these properties instead of changing the definition of `EventHandler`

2017-10-02 22:12 UTC, alsiola commented
Agree with @RyanCavanaugh - changing the type of `EventHandler` is not correct - the relevant part of the docs for `EventHandler` and `EventOrValueHandler` is further down the page you linked (https://redux-form.com/7.0.4/docs/api/field.md/#props).

2017-10-31 22:26 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@rezanouri87 Please address the merge conflict.
<!--footer bot @ 2017-10-31 15:26:18 footerend-->

2017-12-12 00:20 UTC, minestarks commented
I'm closing this PR since it has feedback that hasn't been addressed in over two months. Please open a new PR if you would still like to get this in. Thank you!

2017-12-12 00:20 UTC, closed without merging