Add body_hash option to @types/request
DefinitelyTyped/DefinitelyTyped pull request #19963
Opened 2017-09-22 16:37 UTC by osdavison

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/request/request#oauth-signing>>
(Go to the last sub-section)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

@soywiz @bonnici @Bartvds @joeskeen @ccurrens @lookfirst
The request library supports generating an oauth body hash for you if you use the body_hash option. I've simply added it to the model.

2017-09-23 00:51 UTC, lookfirst commented
I hate to be pedantic, but it seems you used tabs and the convention is spaces. I love tabs myself, but we should follow the existing conventions, no?

2017-09-23 00:53 UTC, lookfirst commented
Also, no test?

2017-09-25 20:56 UTC, joeskeen requested changes

2017-09-25 20:56 UTC, joeskeen commented on types/request/index.d.ts
> +        body_hash?: boolean | string;
This looks good, but please add a test.

2017-10-16 16:14 UTC, andy-ms commented
Looks like #20182 made it in first, which does the same thing.

2017-10-16 16:14 UTC, closed without merging