Cookie interface don't inherit from RawResult
DefinitelyTyped/DefinitelyTyped pull request #19961
Opened 2017-09-22 15:15 UTC by robertorobles

Cookie interface don't inherit from RawResult, only the Cookie responses.
http://webdriver.io/api/cookie/setCookie.html
https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriver/BrowserCookie.cpp#L23

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: Cookie interface don't inherit from RawResult, only the Cookie responses.
http://webdriver.io/api/cookie/setCookie.html
https://github.com/SeleniumHQ/selenium/blob/master/cpp/iedriver/BrowserCookie.cpp#L23
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-09-22 15:19 UTC, timbru31 commented
Ping @christian-bromann, can you assist?

2017-09-22 19:04 UTC, robertorobles commented
blank line removed

2017-09-25 09:41 UTC, timbru31 requested changes

2017-09-25 09:41 UTC, timbru31 commented on types/webdriverio/index.d.ts
> +        getCookie(): Client<Cookie & RawResult<string>[]> & Cookie[] & RawResult<string>[];
Travis complains about `ERROR: 772:38   array-type  Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead.`. This applies to multiple lines. Can you please fix these issues?

2017-09-25 09:44 UTC, robertorobles commented
I've created a new pull request

2017-09-25 09:44 UTC, closed without merging

2017-09-25 09:55 UTC, timbru31 commented
You could have squashed, rebased and force-pushed your current PR, too - but no problem :)
Crossref to #19998

2017-09-25 15:02 UTC, robertorobles commented
Thank you for your advice.
For the next time I'll do it as you say :)