Type definition for Lazar Laszlo's jsqrcode lib
DefinitelyTyped/DefinitelyTyped pull request #20051
Opened 2017-09-26 19:45 UTC by lordazzi

Type definition for Lazar Laszlo's jsqrcode lib.
This package was never on DefinitelyTyped.
Lazlo's is a javascript lib to read qrcode, it isn't an npm package and you can get his lib here: https://github.com/LazarSoft/jsqrcode

Thank you

2017-09-26 19:53 UTC, lordazzi commented
I haven't created a test file for the definitions.
The travis is falling because there are no test file.
I belive that the correct name for the lib would be https://www.npmjs.com/package/@types/jsqrcode, according to the other libraries.

2017-09-26 19:59 UTC, mhegazy requested changes
Please follow the template in https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

2017-09-26 19:59 UTC, mhegazy commented on types/jsqrcode/LICENSE
> +    MIT License
please do not include a separate licence files. all definition packages under DT are distributed under https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE

2017-09-26 19:59 UTC, mhegazy commented on types/jsqrcode/README.md
> +# Installation
do not add a README either.

2017-09-26 19:59 UTC, mhegazy commented on types/jsqrcode/package.json
> +{
do not add a package.json.

2017-09-26 19:59 UTC, mhegazy commented on types/jsqrcode/index.d.ts
> +// Type definitions for Lazar Laszlo's jsqrcode
add a tslint.json, this should flag errors in your header.

2017-09-26 23:20 UTC, mhegazy commented on types/jsqrcode/tsconfig.json
> +        "strictNullChecks": false,
this should be true as well for new declarations.

2017-09-26 23:23 UTC, lordazzi commented
I have fixed it all

2017-09-26 23:42 UTC, merged

2017-09-26 23:42 UTC, mhegazy commented
thanks and welcome to @types :)

2017-09-27 00:21 UTC, lordazzi commented
Thanks!