connect-pg-simple: add types
DefinitelyTyped/DefinitelyTyped pull request #20109
Opened 2017-09-28 14:34 UTC by pasieronen

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-09-29 02:07 UTC, plantain-00 requested changes
There are 2 missing methods, can you add them?https://github.com/voxpelli/node-connect-pg-simple#useful-methods

2017-09-29 02:07 UTC, plantain-00 commented on types/connect-pg-simple/index.d.ts
> +      new (options: PGStoreOptions): Store;
`options` should be optional. https://github.com/voxpelli/node-connect-pg-simple/blob/master/index.js#L15

2017-09-29 02:07 UTC, plantain-00 commented on types/connect-pg-simple/index.d.ts
> +// TypeScript Version: 2.4
This can be Typescript 2.5 here.

2017-09-29 06:59 UTC, pasieronen commented
@plantain-00, thanks for the review! And good catch about options being optional. 

I also added the close/pruneSessions methods. This was a bit trickier than I thought (I had to change the interface to a class), but at least the tests seem to be happy.

2017-09-29 08:38 UTC, plantain-00 approved these changes

2017-10-02 18:06 UTC, RyanCavanaugh requested changes

2017-10-02 18:06 UTC, RyanCavanaugh commented on types/connect-pg-simple/connect-pg-simple-tests.ts
> +import * as connectPgSimple from "connect-pg-simple";
Classes and functions cannot be imported using `import * as` syntax. Please fix either the test or the definition file to use a correct import form.

See also https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this

2017-10-03 07:27 UTC, pasieronen commented
@RyanCavanaugh, thanks for your review! I've now fixed the tests to use the `import connectPgSimple = require("connect-pg-simple")` form.

2017-10-03 18:04 UTC, merged