[react-table]Add react-table
DefinitelyTyped/DefinitelyTyped pull request #20122
Opened 2017-09-29 00:21 UTC by royxue

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-09-29 01:12 UTC, plantain-00 approved these changes

2017-09-29 01:12 UTC, plantain-00 commented on types/react-table/index.d.ts
> +// Project: https://github.com/react-tools/react-table#readme
`#readme` can be removed here

2017-10-02 19:45 UTC, RyanCavanaugh requested changes

2017-10-02 19:45 UTC, RyanCavanaugh commented on types/react-table/index.d.ts
> +        footerClassName: '';
This implies `''` is the *only* legal string value!

2017-10-02 19:45 UTC, RyanCavanaugh commented on types/react-table/index.d.ts
> +        headerClassName: '';
Same here - all uses of `''` as a type need to be changed

2017-10-02 20:03 UTC, royxue commented
@RyanCavanaugh 
Thanks for your comments, resolved

2017-10-02 21:48 UTC, merged