Bluebird: improve typings for `Promise.coroutine`
DefinitelyTyped/DefinitelyTyped pull request #20148
Opened 2017-09-30 01:52 UTC by Retsam

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:  http://bluebirdjs.com/docs/api/promise.coroutine.html
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---

I've improved the typings for `Promise.coroutine`: added support for the options argument, and added explicit arguments, as the arguments passed to the returned coroutine should match the arguments defined by the generator function.

---

A perhaps controversial change is that I added a type parameter for the return type of the generator function, despite that the type parameter doesn't show up as part of the parameters, but this is due to a limitation with generators that I was unable to find a workaround for.  

Once Typescript#2938 is merged, and Generators can be typed as `Generator<TYield, TReturn, TNext>`, the signature for `Promise.coroutine` would be: (omitting the options param for clarity)

```
coroutine<T>(generatorFunction: () => Generator<any, T, any>): () => Bluebird<T>;
```

So, long-term, I think it makes sense for <T> to be a type param, and, short-term, I think it's cleaner as a type param than a type assertion.  (`coroutine<string>(/* */)` vs. `coroutine(/* */) as () => Promise<string>`), but I can remove that type param, if it's preferred.  

--- 

I back-ported my changes to v2, but did not backport them to v1.  The options param didn't exist in v1, and I could get the Iterator stuff working correctly, as v1 couldn't be used with `lib: [ "es6" ]`, as written.

2017-09-30 02:21 UTC, Retsam commented
I had backported these changes to v2, but setting `lib: [ "es6" ]` caused test failures, specifically with Typescript@2.0, and I haven't been able to figure out why.  It's causing, for example:

```
fooArrProm = Promise.all(fooThenArrThen);
fooArrProm = Promise.all(fooArrProm); //Error on this line, Type 'Promise<{}[]>' is not assignable to type 'Promise<Foo[]>'.
fooArrProm = Promise.all(fooThenArr);
fooArrProm = Promise.all(fooArr);
```

If anyone has any idea what the cause of that, and how to fix it, I'd be much obliged.  Oddly, the code seems nearly identical in the v3 version, but I'm not seeing the issue there.

2017-09-30 09:12 UTC, lhecker requested changes
Otherwise I really do like this PR. It might add quite a lot verbosity to the code using these typings, but an improved type safety is always a good thing in my eyes.

2017-09-30 09:12 UTC, lhecker commented on types/bluebird/bluebird-tests.ts
> + //TODO enable generator
I personally forgot what was meant with `enable generator`, so IMO you can remove that comment since you rewrote the generator test anyways.

2017-09-30 09:12 UTC, lhecker commented on types/bluebird/index.d.ts
> +  // TODO: improve this to infer the return type of the generator, I believe this is blocked by https://github.com/Microsoft/TypeScript/issues/2983
Please state _why_ it's blocked by https://github.com/Microsoft/TypeScript/issues/2983.

Something like

```
// TODO: After https://github.com/Microsoft/TypeScript/issues/2983 is fixed, we can use
// the return type propagation of generators to automatically infer the return type T.
```

ought to be enough.

2017-09-30 09:18 UTC, lhecker commented
@Retsam I sadly can't right away see a reason for your issues with v2 either. But IMO we don't need to think about it that much anyways, because the amount of `bluebird@2` users should be considerably small, compared to `bluebird@3`.

2017-10-01 18:48 UTC, Retsam commented
@lhecker Thanks for the review; I think I've hit all the points of feedback.

2017-10-02 17:31 UTC, merged