[sequelize] Allow partial TAttribute updates.
DefinitelyTyped/DefinitelyTyped pull request #20168
Opened 2017-09-30 19:37 UTC by soncodi

Allows updating models via their `Model`'s static methods using partial keys ([see docs](http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-update) for intended behavior). This enables the use of `--strictNullChecks` without having to define all attributes as optional:

#### before
```ts
interface UserAttrs {
  id?:    number;
  name?:  string;
  email?: string;
}
```

#### after
```ts
interface UserAttrs {
  id:    number;
  name:  string;
  email: string;
}
```

```ts
// ...
await User.update({
  name: 'Bob'
}, {
  where: { id: 1 }
});
```

---

 - [x]  Use a meaningful title for the pull request. Include the name of the package modified.
 - [x]  Test the change in your own code. (Compile and run.)
 - [x]  Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
 - [x]  Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
 - [x]  Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
 - [x]  Provide a URL to documentation or source code which provides context for the suggested changes: <http://docs.sequelizejs.com/class/lib/model.js~Model.html#static-method-update>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-10-01 00:16 UTC, oktapodia requested changes
Can you add some tests please?

2017-10-01 00:17 UTC, oktapodia commented
👎 Can you add some tests please?

2017-10-01 09:29 UTC, drinchev commented
This is not so easy. You will also have to modify everywhere `TAttributes` is used. 

Also I'm really not sure of the benefit, since we still can't map which keys are `required` on the database level.

2017-10-01 16:02 UTC, soncodi commented
With this model definition file:

```ts
interface UserAttrs {
  id:    number;
  email: string;
  bday:  Date|null;
  role:  'admin'|'user';
}

export interface User extends Instance<UserAttrs>, UserAttrs {}

export interface UserModel extends Model<User, UserAttrs> {}

export default function(sequelize: Sequelize, dataTypes: DataTypes) {
  return sequelize.define<User, UserAttrs>('User', {
    id: { type: dataTypes.INTEGER, primaryKey: true, autoIncrement: true },
    email: dataTypes.STRING(100),
    bday: { type: dataTypes.DATE, allowNull: true, defaultValue: null },
    role: { type: dataTypes.ENUM, values: ['admin', 'user'], defaultValue: 'user' }
  });
}
```

Using the model class (vs. the instance), typing with `--strictNullChecks` then permits:

```ts
// user is of type User|null
const user = await UserModel.findById(1);

// create fields optional with Partial<TAttributes>, receives model defaults
// newUser is of type User
const newUser = await UserModel.create({
  email: 'user@example.com',
  role: 'user'
});

// update fields optional with Partial<TAttributes>
await UserModel.update({
  bday: null 
}, {
  where: {
    id: newUser.id
  }
});
```

Can you elaborate on why `Partial<TAttributes>` would be needed everywhere?

2017-10-31 22:26 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@soncodi Please address comments from the code reviewers.
<!--footer bot @ 2017-10-31 15:26:10 footerend-->

2017-11-07 01:58 UTC, soncodi commented
Please close this issue; I am no longer using this library.

2017-11-07 01:58 UTC, closed without merging