@types/jest: added setTimeout method
DefinitelyTyped/DefinitelyTyped pull request #20610
Opened 2017-10-16 13:43 UTC by totano

Please fill in this template.

- [X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [X ] Test the change in your own code. (Compile and run.)
- [ X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: http://facebook.github.io/jest/docs/en/jest-object.html#jestsettimeouttimeout

2017-10-16 13:53 UTC, ikatyang commented on types/jest/index.d.ts
> +    function setTimeout(timeout: number): typeof jest
Can you add a test for it? e.g. `jest.setTimeout(1000);`.

And you have to fix the linter error.

2017-10-16 15:04 UTC, wsmd requested changes
Nice work. One suggestion about indentation. I'm gonna have to ask other reviewers if they have any objections to renaming the index file.

2017-10-16 15:04 UTC, wsmd commented on types/jest/index.ts
> +    function setTimeout(timeout: number): typeof jest;
The documentation comment got indented by one extra space in your last commit. Do you mind fixing that? 😄

2017-10-16 15:12 UTC, wsmd commented
I see that the tests are failing:

```
Found 3830 typings folders in /home/travis/build/DefinitelyTyped/DefinitelyTyped/types
{ Error: ENOENT: no such file or directory, open '/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/jest/index.d.ts'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/travis/build/DefinitelyTyped/DefinitelyTyped/types/jest/index.d.ts' }
npm ERR! Test failed.  See above for more details.
```

2017-10-16 15:23 UTC, wsmd requested changes
> Can you add a test for it? e.g. jest.setTimeout(1000);

Could I ask you to add a test? Making sure we don't miss that.

2017-10-16 15:32 UTC, wsmd requested changes

2017-10-16 15:32 UTC, wsmd commented on types/jest/index.d.ts
> +      */
@totano I meant to ask you to push the indentation one space back to keep it consistent with the rest of the file

```diff
      * for the specified module.
      */
     function setMock<T>(moduleName: string, moduleExports: T): typeof jest;
-    /**
-     * Creates a mock function similar to jest.fn but also tracks calls to object[methodName]
-     */
+    ←/**
+     ←* Set the default timeout interval for tests and before/after hooks in milliseconds.
+     ←* Note: The default timeout interval is 5 seconds if this method is not called.
+     ←*/
+    function setTimeout(timeout: number): typeof jest;
+    ←/**
+     ←* Creates a mock function similar to jest.fn but also tracks calls to object[methodName]
+     ←*/
     function spyOn<T extends {}, M extends keyof T>(object: T, method: M): SpyInstance<T[M]>;
     /**
      * Indicates that the module system should never return a mocked version of
```

2017-10-16 17:36 UTC, totano commented
indentation fixed. tomorrow i will add a test

2017-10-17 15:01 UTC, wsmd requested changes

2017-10-17 15:01 UTC, wsmd commented on types/jest/jest-tests.ts
> +                expect(true).toBeTruthy();
Thanks for adding the test. Can we change the indentation to 4 spaces in this block for consistency?

2017-10-17 17:03 UTC, wsmd approved these changes
Great work!

2017-10-17 17:13 UTC, merged