Tcp ping
DefinitelyTyped/DefinitelyTyped pull request #20681
Opened 2017-10-18 14:20 UTC by stegano

Please fill in this template.

- [v] Use a meaningful title for the pull request. Include the name of the package modified.
- [v] Test the change in your own code. (Compile and run.)
- [v] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [v] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [v] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [v] The package does not provide its own types, and you can not add them.
- [v] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [v] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [v] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, and `strictNullChecks` set to `true`.

2017-10-22 01:25 UTC, stegano commented
How do I select a checklist of comments from dt-bot?

2017-10-23 05:55 UTC, plantain-00 requested changes

2017-10-23 05:55 UTC, plantain-00 commented on types/tcp-ping/index.d.ts
> +                  }
The type of `results` is array, `time` and `error` can be `undefined`
https://github.com/apaszke/tcp-ping/blob/master/ping.js#L65
https://github.com/apaszke/tcp-ping/blob/master/ping.js#L71

2017-10-23 05:55 UTC, plantain-00 commented on types/tcp-ping/index.d.ts
> +// Project: https://github.com/wesolyromek/tcp-ping/issues
It should be the project url, rather than the issue url.

2017-10-23 05:55 UTC, plantain-00 commented on types/tcp-ping/index.d.ts
> +                   }
Same here, you can define an interface to reuse them like:
```js
interface Result = { address: string; ... }
export function ping(options: Option, callback: (error: Error, result: Result) => void): void;
export function probe(address: string, port: number, callback: (error: Error, result: Result) => void): void;
```

2017-10-23 05:57 UTC, plantain-00 commented
Don't worry about the checklist of comments from dt-bot, it is expected to be selected by owners or maintainers, or not expected to be selected.

2017-10-24 12:17 UTC, stegano commented
@plantain-00 Thanks for letting me know. :)

2017-10-24 14:06 UTC, plantain-00 commented on types/tcp-ping/index.d.ts
> +    results: {
The type of `results` is array

2017-10-25 00:28 UTC, stegano commented on types/tcp-ping/index.d.ts
> +    results: {
Thank you! :)

2017-10-25 00:59 UTC, plantain-00 approved these changes

2017-10-25 18:11 UTC, merged