Bitcoinjs
DefinitelyTyped/DefinitelyTyped pull request #21018
Opened 2017-10-26 00:14 UTC by dlebrecht

builder addOutput now takes Buffer | string
nullData.output.encode Buffer
fixing bugs according to @bobrosoft

2017-10-26 08:27 UTC, bobrosoft approved these changes
Looks correct.

2017-10-26 09:53 UTC, dlebrecht commented
@bobrosoft it takes usually around a week for the changes to show up in npm repository

if u want them now, point npm to my github branch

2017-10-26 10:03 UTC, bobrosoft commented
@dlebrecht thanks, np. I used `as any` in code for now to overcome that, will replace later as changes show.

2017-10-28 18:16 UTC, DanielRosenwasser requested changes

2017-10-28 18:16 UTC, DanielRosenwasser commented on types/bitcoinjs-lib/index.d.ts
> +    inputs: Array<{ pubKeys: Buffer[],
Can you extract the element type into its own type?

2017-10-30 17:04 UTC, DanielRosenwasser approved these changes

2017-11-02 17:29 UTC, RyanCavanaugh commented
<!--header {"slug":"merge"} headerend-->
Approved by third party. PR appears ready to merge pending review by a maintainer.
<!--footer bot @ 2017-11-2 10:29:30 footerend-->

2017-11-04 08:36 UTC, merged