Add missing options to selectize config
DefinitelyTyped/DefinitelyTyped pull request #21109
Opened 2017-10-30 09:33 UTC by topaxi

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/selectize/selectize.js/blob/master/docs/usage.md
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-11-04 10:27 UTC, RyanCavanaugh commented
<!--header {"slug":"merge"} headerend-->
This PR has been open and unchanged 5 days without signoff or complaint. This will be merged by a maintainer soon if there are no objections.
<!--footer bot @ 2017-11-4 03:27:37 footerend-->

2017-11-07 19:09 UTC, DanielRosenwasser requested changes

2017-11-07 19:09 UTC, DanielRosenwasser commented on types/selectize/index.d.ts
> +        searchField?: string | string[];
Shouldn't this just be `string[]`?

2017-11-07 20:46 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@topaxi Please address comments from the code reviewers.
<!--footer bot @ 2017-11-7 12:46:32 footerend-->

2017-11-08 06:16 UTC, topaxi commented
Search field can be a single string according to
https://github.com/brianreavis/sifter.js/blob/master/lib/sifter.js#L314

Can update the PR to reflect the official selectize documentation.

2017-11-09 20:08 UTC, DanielRosenwasser approved these changes

2017-11-09 20:08 UTC, DanielRosenwasser commented
Sorry for the delay, thanks for your patience!

2017-11-09 20:08 UTC, merged