React-Native: Add typings for ARTStatic Group
DefinitelyTyped/DefinitelyTyped pull request #21180
Opened 2017-11-01 17:59 UTC by nikolasleblanc

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://medium.com/the-react-native-log/animated-charts-in-react-native-using-d3-and-art-21cd9ccf6c58>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-11-02 01:05 UTC, iRoachie commented
Can you provide a link to the rn source?

2017-11-02 02:27 UTC, timwangdev commented on types/react-native/index.d.ts
> +//                 Nikolas LeBlanc <https://github.com/nikolasleblanc>
Just wanting to make sure that you understand that by adding this line means you’ll be signing up as a maintainer and will get notifications for all issues/PRs.

2017-11-02 02:29 UTC, timwangdev requested changes
Please address @iRoachie 's comment.

2017-11-02 03:42 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@nikolasleblanc Please address comments from the code reviewers.
<!--footer bot @ 2017-11-1 20:42:57 footerend-->

2017-12-07 16:34 UTC, alloy commented
Bump.

2017-12-21 11:10 UTC, alloy commented
@nikolasleblanc I’m going to close this PR for now. Please do re-open when/if you fix these merge conflicts.

2017-12-21 11:10 UTC, closed without merging