Jest matchers can accept many arguments
DefinitelyTyped/DefinitelyTyped pull request #21327
Opened 2017-11-07 22:56 UTC by JamieMason

This PR removes the restriction on the number of arguments Jest's custom matchers can accept, which does not exist in Jest itself.

Jest allows you to define the following custom matcher for example which accepts 2 arguments:

```js
expect.extend({
  toBeWithinRange(received, floor, ceiling) {
    // implementation...
  }
});
```

The Jest typings currently state that a Jest matcher can only accept one argument.

A URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/jest/docs/en/expect.html#expectextendmatchers.

Thanks.

2017-11-09 19:46 UTC, wsmd commented
Hi @JamieMason, great catch! Thanks for a quick fix. I'm happy to approve this PR, but do you mind adding this use case to [`jest-tests.ts`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/jest-tests.ts#L253-L278)?

2017-11-09 20:24 UTC, wsmd requested changes
Test needed

2017-11-09 20:37 UTC, JamieMason commented
will do! Thanks

2017-11-09 20:45 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@JamieMason Please address comments from the code reviewers.
<!--footer bot @ 2017-11-9 12:45:28 footerend-->

2017-11-09 22:30 UTC, JamieMason commented
Hi all, I have updated this PR to include a new test case. Please let me know if there is anything more I can do, thanks a lot.

2017-11-09 23:25 UTC, RyanCavanaugh commented
<!--header {"slug":"reviewPing-8797439a73b6b412db4bcd015f6aa81d"} headerend-->
@wsmd - Thanks for your review of this PR! Can you please look at the new code and update your review status if appropriate?
<!--footer bot @ 2017-11-9 15:25:06 footerend-->

2017-11-10 15:52 UTC, wsmd approved these changes
Looks good! - Thanks for the fix 👍

2017-11-10 16:56 UTC, RyanCavanaugh commented
<!--header {"slug":"merge"} headerend-->
Approved by a listed owner. PR ready to merge pending express review by a maintainer.
<!--footer bot @ 2017-11-10 08:56:21 footerend-->

2017-11-10 22:58 UTC, merged