Update index.d.ts
DefinitelyTyped/DefinitelyTyped pull request #21397
Opened 2017-11-10 07:37 UTC by k8w

SetOption value should be any (maybe boolean, number ...)

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-11-10 14:57 UTC, micksatana requested changes
Seem correct.

Should update project url as well? It changed to https://github.com/showdownjs/showdown

2017-11-10 16:56 UTC, RyanCavanaugh commented
<!--header {"slug":"complaint"} headerend-->
@k8w Please address comments from the code reviewers.
<!--footer bot @ 2017-11-10 08:56:18 footerend-->

2017-11-13 03:54 UTC, tan9 commented on types/showdown/index.d.ts
>           * @param string
Please update the jsdoc according to your change.

2017-11-13 04:01 UTC, k8w commented
@tan9 done

2017-11-13 17:28 UTC, merged