[@types/epilogue] Create type definition for Epilogue
DefinitelyTyped/DefinitelyTyped pull request #21614
Opened 2017-11-18 15:29 UTC by micksatana

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2017-11-21 05:31 UTC, plantain-00 requested changes

2017-11-21 05:31 UTC, plantain-00 commented on types/epilogue/index.d.ts
> +export function resource(options: ResourceOptions): Resource;
The `options` seems to be optional.
https://github.com/dchester/epilogue/blob/master/lib/index.js#L14
https://github.com/dchester/epilogue/blob/master/lib/index.js#L40

2017-11-21 06:38 UTC, plantain-00 approved these changes

2017-11-21 06:38 UTC, micksatana commented
Thanks @plantain-00 

Updated.

2017-11-21 20:30 UTC, uniqueiniquity commented on types/epilogue/index.d.ts
> +export function initialize(options?: InitializeOptions): undefined;
Should the return type here be `void`?

2017-11-22 03:07 UTC, micksatana commented on types/epilogue/index.d.ts
> +export function initialize(options?: InitializeOptions): undefined;
Thanks @uniqueiniquity 

Done.

2017-11-22 16:50 UTC, merged