@types/Chrome - chrome.system.display updates
DefinitelyTyped/DefinitelyTyped pull request #21669
Opened 2017-11-21 10:09 UTC by niikoo

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.chrome.com/apps/system_display
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-11-27 13:12 UTC, niikoo commented
All build failures fixed

2017-12-12 15:43 UTC, niikoo commented
Can someone please review this? Thanks!

2017-12-13 08:21 UTC, couven92 commented
changes for `types/chrome/index.d.ts` look good :+1:

2017-12-13 18:05 UTC, minestarks requested changes

2017-12-14 09:16 UTC, niikoo commented on .gitignore
> +types/chrome/doc-generator/
It's reverted now

2017-12-14 09:16 UTC, niikoo commented on types/chrome/chrome-app.d.ts
> +/// <reference path="./index.d.ts"/>
Done

2017-12-14 09:17 UTC, niikoo commented
All requested changes fixed

2017-12-14 16:37 UTC, minestarks approved these changes

2017-12-14 16:37 UTC, merged