add element.destroy to stripe-v3
DefinitelyTyped/DefinitelyTyped pull request #21736
Opened 2017-11-25 12:19 UTC by benstevens48

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Reference](https://stripe.com/docs/stripe-js/reference#other-methods)

This is my first pull request, so sorry if  I've done something wrong.

2017-11-28 21:30 UTC, amritk requested changes

2017-11-28 21:30 UTC, amritk commented on types/stripe-v3/index.d.ts
> +            destroy(): void;
@benstevens48 looks good, but could you add a test?

2017-12-01 19:40 UTC, benstevens48 commented
Ok, I added a test although I wasn't 100% sure about how the tests worked. As I understand they are just type-checked and not actually run. Also I wasn't quite sure why there were tests for stripe-v2 inside stripe-v3.

2017-12-01 19:48 UTC, amritk commented
@benstevens48 the rests are run. Honestly I can't remember now, but here is the pull request where the versions were split https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16539. Maybe they can be removed.

2017-12-01 19:49 UTC, amritk approved these changes

2017-12-01 19:49 UTC, amritk commented
:+1:

2017-12-01 20:05 UTC, benstevens48 commented
Thanks. According to the DefinitelyTyped docs, the code in the tests is not actually run, only type-checked - [https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package](https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package). I hope this is the case else the `card.destroy()` I added to the test is called too early.

There are a few more updates I'd like to add if I have time (relating to 3D secure payment) but I'll open another pull request for that (if I have time).

2017-12-01 21:56 UTC, amritk commented
Maybe that is the case then

2017-12-02 01:37 UTC, armanio123 commented
Test are not run only type-checked as @benstevens48 correctly mentioned.

2017-12-02 01:37 UTC, merged