[d3-geo] Remove crs from Extended GeoJSON feature
DefinitelyTyped/DefinitelyTyped pull request #21801
Opened 2017-11-28 11:33 UTC by atd-schubert

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://tools.ietf.org/html/rfc7946#section-4
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

---

According to the [RFC section 4](https://tools.ietf.org/html/rfc7946#section-4) of the GeoJSON specification @JeffJacobson apply the changes to the GeoJSON type definition in PR #21590.

In #21794 the change of removing the `CoordinateReferenceSystem` interface was mentioned as a fault, but it is not. In addition I can not find [any hint](https://github.com/d3/d3-geo/search?utf8=%E2%9C%93&q=crs&type=) that `d3-geo` implements a `crs` property on its own. As result I removed the `crs` property in `d3-geo` to have no conflicts anymore.

---

Closes #21794

2017-11-28 15:05 UTC, gustavderdrache approved these changes

2017-11-28 16:28 UTC, tomwanzek commented
We can make the change, as proposed, I am not sure, if it will break anyone who actually used the `crs` property for some use case.

@Ledragon Thoughts?

We should prioritize this PR, as it currently breaks install due to the TS compile error arising from the missing `GeoJSON.CoordinateReferenceSystem`.

Worst case, we could replace the imported interface with our own, if we needed to sustain some kind of backward compatibility.

2017-11-28 16:38 UTC, j4ys0n commented
@atd-schubert can you merge this in please?

2017-11-28 16:39 UTC, tomwanzek commented
@andy-ms Can we have this merge expedited? **d3-geo** installs are broken since the merge of `geojson` in #21590.

I'm not sure, why the Travis CI on PR #21590 did not fail and get us alerted the change impact?

2017-11-28 17:31 UTC, tomwanzek commented
DO NOT MERGE!!! 

On further thought, do not merge this PR. I am pushing a new PR that pins `geojson` to version `1.0.6`. So we can complete the change impact discussion of removing `crs`. There is too much noise to determine, whose builds are broken only because of the compile time error of the missing interface, or because, they actually relied on `crs`, even if it  is not standard RFC at this point.

2017-11-28 17:32 UTC, tomwanzek requested changes
See my last comment. We will take the conservative route and first pin to the old `geojson` version, before we pull out `crs` after further discussion.

2017-11-28 17:54 UTC, tomwanzek commented
I have created PR #21808 to pin the dependency to `geojson` version `1.0.6` as an interim patch.

2017-11-28 19:31 UTC, tomwanzek commented
@atd-schubert  Please close this PR to avoid confusion going forward.

We have just **released an interim patch** for the **d3-geo** TS definitions (version 1.9.4). Until completion of an impact assessment and resulting re-factoring of **d3-geo**, the patch replaced the dependency  on `CoordinateReferenceSystem` with a literal. I.e., _for now_, it  retains the `crs` optional property of the `ExtendedGeometryCollection<GeometryType extends GeoGeometryObjects>` interface as a conservative strategy.

I am reviewing whether we should start a new issue to consider the change impacts and refactoring, or re-purpose one  of the already open ones.

2017-11-28 22:18 UTC, closed without merging

2017-11-29 08:31 UTC, atd-schubert commented
@tomwanzek I closed this merge request, but I still think that this is a correct solution. I could not find any hint that `d3-geo` account the `crs` property. It is probably just an implementation of the GeoJSON standard. The specification drops the `crs` property, so there is no reason to introduce a `crs` on our own for `d3-geo`.

Anyway, please add me to further discussions...