[WIP][materialize-css] New types for 1.0
DefinitelyTyped/DefinitelyTyped pull request #21839
Opened 2017-11-29 17:43 UTC by huww98

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://next.materializecss.com

2017-11-29 17:47 UTC, huww98 commented
There are so many changes so that I decided to build to from scratch. In this case, am I supposed to keep the original v0 contributors' names in the new v1 file?

2017-12-01 14:28 UTC, scote requested changes

2017-12-01 16:45 UTC, huww98 commented on types/materialize-css/index.d.ts
> +// Type definitions for materialize-css 1.0
The dtslint will report error if I write `1.0.0`

````
dt-header  Error parsing header. Expected: foo MAJOR.MINOR (patch version not allowed). See: https://github.com/Microsoft/dtslint/blob/master/docs/dt-header.md
````

2017-12-01 17:14 UTC, scote approved these changes

2017-12-01 19:38 UTC, merged