Changes Jest type to use array rather than Set.
DefinitelyTyped/DefinitelyTyped pull request #22025
Opened 2017-12-07 04:49 UTC by technion

Set may be technically stricter but as per #19662, there have been a number of associated problems with this.

Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: See #19662
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-12-11 21:06 UTC, wsmd commented
@technion many of jest internals/packages expect `onRunComplete` to be passed a `Set`.

**notify_reporter**
- https://github.com/facebook/jest/blob/master/packages/jest-cli/src/reporters/notify_reporter.js#L36

**coverage_reporter**
- https://github.com/facebook/jest/blob/master/packages/jest-cli/src/reporters/coverage_reporter.js#L80
- https://github.com/facebook/jest/blob/master/packages/jest-cli/src/reporters/__tests__/coverage_reporter.test.js#L131

**summary_reporter**
- https://github.com/facebook/jest/blob/master/packages/jest-cli/src/reporters/summary_reporter.js#L80

I'm not quite sure why the typing should be changed to an array.

2017-12-11 23:46 UTC, technion commented
@wsmd See the discussion on #19662. Several people are struggling to get this to build.

2017-12-12 07:26 UTC, ikatyang requested changes
It'd be better to replace it with something like `SetLike<T>` or add a global fake `Set<T>` type, e.g. `interface Set<T> {}`.

2017-12-12 20:34 UTC, technion commented
Surely a fake Set would end up clashing with something.

I'm not sure what SetLike would look like if not just an array.

2017-12-12 20:35 UTC, wsmd commented
Is using a union of an array and set a good idea?

2017-12-14 08:15 UTC, ikatyang commented
Based on [Declaration Merging](http://www.typescriptlang.org/docs/handbook/declaration-merging.html), a fake `Set<T>` should be fine:

```ts
interface Set<T> {}
```

People who want to use `Set` needs to set `lib: ["es6"]` to get the entire `Set` typing, and the others won't get `error TS2304: Cannot find name 'Set'`.

2017-12-14 10:52 UTC, technion commented
I've amended the patch to use the fake Set as described. Unfortunately whilst it ran fine in my app and test suite, well you can see Travis doesn't like it. I'll look into what I can do with this.

2017-12-14 11:22 UTC, ikatyang commented on types/jest/index.d.ts
> +    interface Set<T> {} // To allow non-ES6 users the Set below
`// tslint:disable-line:no-empty-interface` 

or 

`// tslint:disable-next-line:no-empty-interface`

2017-12-14 21:11 UTC, technion commented
Thanks. I hadn't done that as the README suggested the linting style was more set in stone.

Done now.

2017-12-14 23:55 UTC, ikatyang approved these changes

2017-12-19 19:23 UTC, merged