Update index.d.ts for Kendo-UI GridColumn definition
DefinitelyTyped/DefinitelyTyped pull request #22100
Opened 2017-12-11 17:04 UTC by clabough

Since the command property of a GridColumn can be an array of strings, for example:

{ command: ["edit", "destroy"], title: "&nbsp;", width: "250px" }

The current definition is

command?: GridColumnCommandItem[];

but it should be

command?: (string|GridColumnCommandItem)[];

Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://docs.telerik.com/kendo-ui/api/javascript/ui/grid#configuration-columns.command>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2017-12-11 22:07 UTC, minestarks commented on types/kendo-ui/index.d.ts
> +        command?: (string|GridColumnCommandItem)[];
Are you sure you don't want `string[] | GridColumnCommandItem[]` here? Can the array be a mixture of `string`s and `GridColumnCommandItem`s?

2017-12-14 18:12 UTC, minestarks requested changes

2017-12-14 18:12 UTC, minestarks commented on types/kendo-ui/index.d.ts
> +        command?: string|(string|GridColumnCommandItem)[];
Could you please add a test case, showing intended usage, that would fail without your changes? This will help me understand your intention.

2017-12-15 05:46 UTC, clabough commented
Two of the three examples on the documentation page I listed above would fail.
e.g. `{ command: ["edit", "destroy"], title: " ", width: "250px" }`

 or this example that works during my testing 
`{ command: [{
         name: "details",
         click: function(e) {
            // command button click handler
         }
        }, "destroy"], title: " ", width: "250px" }`

2018-01-03 19:22 UTC, merged