Fix setState to work in callback form and to allow partial intellisense
DefinitelyTyped/DefinitelyTyped pull request #22127
Opened 2017-12-12 15:26 UTC by ericanderson

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

See: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/18365#issuecomment-351013257

2017-12-12 18:46 UTC, vsiao requested changes
Mind adding some `// $ExpectError` tests for this? Looks good otherwise.

2017-12-13 20:45 UTC, ericanderson commented
@vsiao GTG

2017-12-13 22:58 UTC, vsiao approved these changes
Thanks for the thorough suite of tests!

2017-12-13 22:58 UTC, vsiao commented on types/react/test/tsx.tsx
> +class Comp extends React.Component<{}, { foo: boolean, bar: boolean }> {
Maybe could name this component `SetStateTest`? :)

2017-12-13 23:15 UTC, merged

2017-12-13 23:16 UTC, johnnyreilly commented
Thanks!