add typings for screeps
DefinitelyTyped/DefinitelyTyped pull request #22154
Opened 2017-12-13 11:26 UTC by Arcath

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
  `screeps` on NPM is a place holder package for all the `screeps-*` packages. We are the community team that have created typings for the game not the package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

See this PR https://github.com/screepers/typed-screeps/pull/24 for our work building this.

Will replace our `typed-screeps` package that is currently used by players for typings.

@apemanzilla
@resir014

2017-12-13 18:34 UTC, minestarks commented
Sorry, I don't really understand the naming here. I'm not familiar with the game. So this is not for the npm package `screeps`? Which library are they for, and how is that library distributed?

2017-12-13 18:34 UTC, minestarks requested changes

2017-12-13 18:34 UTC, minestarks commented on types/screeps/tslint.json
> +	"rules": {
Please don't turn any linter rules off on new typings.

2017-12-13 19:09 UTC, Arcath commented
@minestarks The game runs players code in a vm, these are the typings for the API provided in the game.

The screeps package on npm is the game server for running your own private servers. There would be no scenario where you would require the screeps package.

The in game typescript community are on board with `@types/screeps` being typings for the players.

The Screepers/Typescript team will look into meeting the default linter rules. We, for example, need to supply empty interfaces that players can override them later.

2017-12-14 20:38 UTC, minestarks approved these changes

2017-12-14 20:38 UTC, merged