Updated ReadMe FAQ
DefinitelyTyped/DefinitelyTyped pull request #22197
Opened 2017-12-14 21:11 UTC by CaselIT

PR to add to the FAQ section of the ReadMe a new answer regarding the creation of empty namespace to allow ES6 import of non module objects

Previously discussed in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22052

@minestarks @andy-ms

2017-12-14 21:21 UTC, andy-ms commented
@DanielRosenwasser and @weswigham were working on something to allow people to import those types of modules with default imports. Presumably we'll start *really* discouraging `namespace thisModule {}` then. :+1: for now though.

2017-12-19 23:05 UTC, DanielRosenwasser requested changes

2017-12-19 23:05 UTC, DanielRosenwasser commented on README.md
> +This error can be suppressed by aliasing the exported function in the `.d.ts` with an empty namespace with the same name, but this practice is discuraged. This is a commonly cited [Stack Overflow ans
One sentence per line, "discuraged" -> "discouraged"

2017-12-19 23:05 UTC, DanielRosenwasser commented on README.md
> +This error can be suppressed by aliasing the exported function in the `.d.ts` with an empty namespace with the same name, but this practice is discuraged. This is a commonly cited [Stack Overflow ans
Replace

"by aliasing the exported function in the `.d.ts` with an empty namespace"

with

"by merging the function declaration with an empty namespace of the same name"

2017-12-19 23:05 UTC, DanielRosenwasser commented on README.md
> +This error can be suppressed by aliasing the exported function in the `.d.ts` with an empty namespace with the same name, but this practice is discuraged. This is a commonly cited [Stack Overflow ans
Add something like

```markdown
It is more appropriate to import the module using the `import foo = require("foo");` syntax, or to use a default import like `import foo from "foo";` if using the `--allowSyntheticDefaultImports` flag if your module runtime supports an interop scheme for non-ECMAScript modules as such.
```

2017-12-20 08:38 UTC, CaselIT commented
Thanks @DanielRosenwasser for the review!

2017-12-27 20:49 UTC, merged