[lodash] genericize isEqual
DefinitelyTyped/DefinitelyTyped pull request #22443
Opened 2017-12-21 21:39 UTC by jeffkenney

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ReactiveX/rxjs/blob/5.5.5/src/operator/distinctUntilChanged.ts#L6
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

More context: When chaining observable sequences and using `_.isEqual` as an argument to `distinctUntilChanged`, the type `any` is inferred instead of the correct type of the Observable that was used as an input to `distinctUntilChanged`:

```typescript
// https://github.com/ReactiveX/rxjs/blob/5.5.5/src/operator/distinctUntilChanged.ts#L6
export function distinctUntilChanged<T>(this: Observable<T>, compare?: (x: T, y: T) => boolean): Observable<T>;
```
Example:

```typescript
import { isEqual } from 'lodash';

Observable.of(1).distinctUntilChanged(isEqual).subscribe((value) => {
  // the inferred type of `value` is `any` due to `isEqual` arguments being typed as `any`, so no compilation errors
  value.foo();
});
```

This PR genericizes the inputs to isEqual, allowing types to be inferred from calls to `isEqual`.

2017-12-21 21:44 UTC, miller-time commented on types/lodash/index.d.ts
> +        isEqual<T2>(
why `T2` when there's only one type parameter (instead of `T1`)?

2017-12-30 12:13 UTC, thorn0 commented
That's not how `isEqualWith` works. Please see the [docs](https://lodash.com/docs/4.17.4#isEqualWith). `customizer` is used recursively to do a deep comparison, so it's called not only for `value` and `other`. So `IsEqualCustomizer` should stay non-generic.

As for your example with `isEqual`, it's an interesting issue, which needs an additional investigation, because at first glance it seems pointless to add generics to a signature that uses each of them only once. Have there been precedents like this (probably in other packages)? What TS version do you use? Compiler settings?

2018-01-02 23:57 UTC, thorn0 requested changes
This can't be merged as it is. See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22443#issuecomment-354543078

2018-01-23 19:28 UTC, andy-ms commented
Closing since it's been a while with no update. If you still want to do something like this please make a new pull request.

2018-01-23 19:28 UTC, closed without merging

2018-01-23 19:29 UTC, andy-ms commented on types/lodash/index.d.ts
> +        isEqual<T1, T2>(
This change doesn't really make sense. If this function accepts a `T1` and a `T2` for arbitrary values of `T1` and `T2`, that's the same as saying it accepts `any`.