angular: Update angular.module to accept an Injectable as the configFn
DefinitelyTyped/DefinitelyTyped pull request #22450
Opened 2017-12-21 22:25 UTC by theRobinator

This is undocumented behavior in Angular, but works because this argument is passed to `$injector.invoke`. `Injectable<Function>` is a union with `Function`, so this change is backwards-compatible.

See https://github.com/angular/angular.js/blob/49aba51e6bfd3f6d59c0f28628cc983d84438cfa/src/loader.js lines 81, 370, and 111 for how this function is used in `angular.module`.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate. **Is this appropriate?**
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. **No substantial changes**

2017-12-28 22:37 UTC, paulvanbrenk requested changes
I'm not a fan of adding undocumented features in a definition file.

@diegovilar @thorn0 @calebstdenis @leonard-thieu thoughts?

2017-12-29 01:12 UTC, leonard-thieu commented
Actually, this looks like [it is documented](https://docs.angularjs.org/api/ng/function/angular.module#angular.module-arguments).

> Optional configuration function for the module. Same as [Module#config(](https://docs.angularjs.org/api/ng/type/angular.Module#config)).

2017-12-29 01:15 UTC, leonard-thieu approved these changes

2017-12-29 08:33 UTC, thorn0 approved these changes

2017-12-29 08:35 UTC, thorn0 commented
It's not undocumented. Such functions are by default considered injectable in AngularJS.

2017-12-29 20:16 UTC, paulvanbrenk commented
Thanks for the feedback.

2017-12-29 20:16 UTC, merged