Update index.d.ts
DefinitelyTyped/DefinitelyTyped pull request #22511
Opened 2017-12-26 15:03 UTC by bobby77

Changed error in "transform" and "inverseTransform" return type: Point instead of Matrix (L307)
Changed error in clone parameters : object instead of boolean (L1358-1360)

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2017-12-26 15:05 UTC, bobby77 commented
Link to documentation on changes made: 
http://paperjs.org/reference/matrix/#transform-point
http://paperjs.org/reference/matrix/#inversetransform-point
http://paperjs.org/reference/item/#clone

2018-01-02 20:39 UTC, mhegazy requested changes

2018-01-02 20:39 UTC, mhegazy commented on types/paper/index.d.ts
> +         * @param options [optional] - object with 2 parameters
seems like you have a comment specifying the shape of the object here, `{ insert?: boolean, deep?: boolean }` so why not use it?

2018-01-08 23:09 UTC, clark-stevenson commented
@bobby77 

Sorry I was away for the last couple of weeks.  What you done looks good, but I agree with mhegazy. 

Can you make a slight alteration so that: 

`clone(options?: any): Item;` becomes `clone(options?: { insert?: boolean, deep?: boolean }): Item;`

Since the parameters are known, this beats `any`

2018-01-24 18:37 UTC, andy-ms commented
Merged with @mhegazy's suggestion.

2018-01-24 18:37 UTC, merged