Add is-negated-glob
DefinitelyTyped/DefinitelyTyped pull request #22573
Opened 2017-12-29 22:32 UTC by ajafff

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2017-12-30 12:02 UTC, plantain-00 requested changes

2017-12-30 12:02 UTC, plantain-00 commented on types/is-negated-glob/is-negated-glob-tests.ts
> +import * as isNegatedGlob from 'is-negated-glob';
Since `isNegatedGlob` is function, it should be `import isNegatedGlob = require(...)` here

2017-12-30 13:04 UTC, plantain-00 approved these changes

2018-01-02 17:19 UTC, RyanCavanaugh commented
@ajafff looks like Travis isn't running on this PR for some reason. Can you follow these steps (courtesy the Travis support team) and see if that fixes it? Thanks!

> This is an unfortunate side effect of our abuse detection which sometimes produces false positives. In this case, the users who opened those pull requests don’t have accounts on Travis CI and this situation has led to abuse before (mostly through automated accounts). Could you ask the people who opened those PRs to visit travis-ci.org, click “Sign up”, and consent to connecting their GitHub accounts to Travis CI?

Previously happened at #19871

2018-01-04 11:48 UTC, ajafff commented
There it is: green CI

2018-01-04 17:24 UTC, merged