[reactstrap] Don't declare "popper.js" module, prevent TypeScript conflict error
DefinitelyTyped/DefinitelyTyped pull request #22680
Opened 2018-01-04 21:19 UTC by KurtPreston

I recently submitted pull request #22512, which was merged.  However, upon updating my definitions, I realized that if a user has the `popper.js` node module installed, Typescript complains about conflicting type definitions.

This pull request removes the line re-declaring the popper.js module, and uses `import`s instead of `reference`s, keeping the definition internal.

I have copied this folder into my project's `node_modules/types/reactstrap` path, and it seems to work.  Please let me know if there is a better way to test it.

Also, apologies for pushing out an errant definition.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: **n/a — no external API changes, but rather fixing conflicting definition error**
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-01-04 21:38 UTC, mhegazy commented on types/reactstrap/lib/Popper.d.ts
> +export default Popper;
add `export as namespace Popper;` to make sure the module is still accessible as a global (which seems to be the case from the examples in https://github.com/FezVrasta/popper.js/).

2018-01-04 21:40 UTC, mhegazy requested changes
Please add `export as namespace Popper`.

2018-01-05 19:21 UTC, KurtPreston commented
@mhegazy Updated.

2018-01-05 19:25 UTC, merged

2018-01-05 19:59 UTC, KurtPreston commented
@mhegazy Thanks!