speakeasy: Update definition for missing functions
DefinitelyTyped/DefinitelyTyped pull request #22717
Opened 2018-01-06 13:07 UTC by xeoneux

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/speakeasyjs/speakeasy/issues/90
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-01-07 08:18 UTC, mhegazy requested changes

2018-01-07 08:18 UTC, mhegazy commented on types/speakeasy/index.d.ts
> +declare module "speakeasy" {
Do not use `declare module "speakeasy"` instead use `export as namespace speakeasy`

2018-01-08 09:47 UTC, xeoneux commented
@mhegazy how do I handle a function that is also an object with method?

```
function totp(options: TotpOptions): string;
function totp.verify(options: TotpVerifyOptions): boolean;
function totp.verifyDelta(options: TotpVerifyOptions): boolean;
```

2018-01-08 10:02 UTC, xeoneux commented
@mhegazy solved! 😄

2018-01-09 01:11 UTC, mrOlorin approved these changes

2018-01-09 19:33 UTC, RyanCavanaugh requested changes

2018-01-09 19:33 UTC, RyanCavanaugh commented on types/speakeasy/index.d.ts
> +export as namespace speakeasy;
This isn't a UMD module, so there shouldn't be a UMD module declaration here

2018-01-10 07:24 UTC, xeoneux commented
@RyanCavanaugh fixed! 😸

2018-01-10 18:14 UTC, merged