Require entire express namespace
DefinitelyTyped/DefinitelyTyped pull request #22711
Opened 2018-01-06 00:31 UTC by Echron

Express is required at line 66 and 93

2018-01-08 23:24 UTC, RyanCavanaugh requested changes

2018-01-08 23:24 UTC, RyanCavanaugh commented on types/oauth2-server/index.d.ts
> +import * as Express from "express";
This should be
```
import Express = require('express');
```

2018-01-08 23:37 UTC, vangorra commented
:+1:

2018-01-24 19:37 UTC, andy-ms commented
I've done something like this at #22711.
This pull request is trying to merge into the wrong branch, so I'll make the change there.

2018-01-24 19:37 UTC, closed without merging