[react-bootstrap] Added Panel typings for Version 0.32.0
DefinitelyTyped/DefinitelyTyped pull request #22776
Opened 2018-01-09 12:16 UTC by Ritorna

Provided Panel typings for react Bootstrap Version 0.32.0. 
While still being backward compatible with the additional string type on the collapsiable Property for the Panel.
As defined in the updated specification of: 
[https://react-bootstrap.github.io/components/panel/](https://react-bootstrap.github.io/components/panel/)

Needs some more rework, since not all types are provided within this PR. 
Provided typings for the use case for [https://react-bootstrap.github.io/components/panel/#panels-collapsible](Collapsible Panels)

- [x] Test the change in your own code. (Compile and run.)
- [x] The package does not provide its own types, and you can not add them.

2018-01-10 19:23 UTC, Batbold-Gansukh commented
@Ritorna 
Since you implemented `Panel` typings, would you mind to implement new `Pagination` typings?

2018-01-10 19:25 UTC, bat-bold requested changes
Please provide a test for Panel typings and it would be nice if you provide new Pagination typings.

2018-01-10 20:23 UTC, Ritorna commented
@Batbold-Gansukh i'll try to also add the Pager and Pagination typings. Meanwhile i updated the Panel typings which should now provide the full typings as in React Bootstraps documentation.
I'll give my best on the Tests, yet a little help would be appreciated.

2018-01-11 00:18 UTC, Batbold-Gansukh commented
I ended up creating new pull request. It contains `Pagination` and `Panel` typings.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22823

2018-01-11 06:24 UTC, closed without merging