[merkle] Add merkle module types
DefinitelyTyped/DefinitelyTyped pull request #22780
Opened 2018-01-09 15:12 UTC by kerol2r20

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-01-10 06:00 UTC, kerol2r20 commented
Excuse me, how add add dependencies on @types?
This package depend on @types/node.

2018-01-14 00:08 UTC, plantain-00 requested changes

2018-01-14 00:08 UTC, plantain-00 commented on types/merkle/README.md
> +# Installation
The file will be generated automatically when published to npm, so you don't need to add this file as source code.

2018-01-14 00:08 UTC, plantain-00 commented on types/merkle/tsconfig.json
> +        "strictNullChecks": false,
For new packages, `strictNullChecks` should be enabled.

2018-01-14 00:08 UTC, plantain-00 commented on types/merkle/tslint.json
> +    "rules": {
For new packages, this file should only `"extends": "dtslint/dt.json"`

2018-01-14 07:15 UTC, plantain-00 approved these changes

2018-01-17 19:22 UTC, merged