snapsvg: Added missing parameter format
DefinitelyTyped/DefinitelyTyped pull request #22879
Opened 2018-01-13 14:13 UTC by grypho

Paper.path also accepts an array of commands instead of a path string. 

Example: 
paper.path([
            ["M", 5, 10],
            ["l", 15,  2],
            ["h", 30],
            ["Z"]
]);

Please fill in this template.

- [X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [X ] Test the change in your own code. (Compile and run.)
- [X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ C] Provide a URL to documentation or source code which provides context for the suggested changes: 
See code of proto.path (~line 5009 of snap.svg.js) where (if an object or array was provided a special handling of the given parameter "d" is done. This dives into the function Snap.parsePathString (roughly line 1819 in actual node version (0.5.0)) where a stringified path definition is converted to an array of arrays. If an array of arrays is given, this step is skipped and the next function is called with a cloned version.

- [Already there ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-01-15 17:08 UTC, kant2002 requested changes

2018-01-15 17:08 UTC, kant2002 commented on types/snapsvg/index.d.ts
> +        path(pathSpec:(string | number)[][]):Snap.Element;
I think that should be rewritten as 
```
path(pathSpec?: string | (string | number)[][]):Snap.Element; 
```
That way would be no need to have two signatures

2018-01-15 17:10 UTC, kant2002 commented on types/snapsvg/index.d.ts
> +        path(pathSpec:(string | number)[][]):Snap.Element;
Also would be good if you drop piece of code in the issue description in the tests file, so compilation will check you example when new submissions would be added

2018-01-24 19:46 UTC, andy-ms commented
Merged with @kant2002 's suggestions.

2018-01-24 19:46 UTC, merged