enzyme: Improve signature of ShallowWrapper.filter and ReactWrapper.filter to
DefinitelyTyped/DefinitelyTyped pull request #22975
Opened 2018-01-16 20:43 UTC by UselessPickles

return appropriate specific types when the apram is a ComponentClass or
StatelessComponent.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: (shouldn't be necessary because it's very simple)
- [ ] Increase the version number in the header if appropriate. (there's no clarification of when it is "appropriate"; should I do this?)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. (I'm guessing that my changes are not "substantial")

2018-01-17 16:49 UTC, UselessPickles commented
Looks like the travis-ci build was cancelled. How can it be re-run?

2018-01-18 23:43 UTC, jwbay requested changes
Changes look good! Could you add tests please? Just need some lines leveraging the new signatures in enzyme-tests.tsx.

2018-01-19 00:05 UTC, UselessPickles commented
The current structure of the unit test code doesn't allow for quickly adding such a unit test. The wrapper on which `filter()` is being called is already exactly the same type of wrapper that `filter()` is expected to return, so the most obvious quick change to the unit test would have also passed before making my changes. The same problem exists for all other methods with similar signatures (find, etc), which also don't have unit tests for this situation.

I'll take a look again tonight at enhancing the unit test code to have additional component types involved so that it can be properly unit tested. I may as well add the same unit tests to other similar methods while I'm in there.

2018-01-19 01:52 UTC, UselessPickles commented
Unit tests have been improved to test find/filter/parents/children/etc in ways where a wrapper with different props than the original root wrapper is expected as a result.

Also improved the `props()` unit tests similarly.

I also noticed that `filter()` was not properly overloaded to return different types for a string param vs a props object param. I fixed this as well.

2018-01-19 02:50 UTC, jwbay approved these changes

2018-01-19 18:15 UTC, merged