Improved definitions of Video.js 6+ for to implement custom Techs
DefinitelyTyped/DefinitelyTyped pull request #22991
Opened 2018-01-17 10:37 UTC by cipacda

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-01-25 18:26 UTC, ghost requested changes
The file currently uses tabs, please stick to that.

2018-01-25 18:26 UTC, andy-ms commented on types/video.js/index.d.ts
> +    new(options: any, ready: () => void);
Did you mean `class Component` and `constructor(...)`? This declares an interface for objects `x` s.t. you can call `new x(...)` and also `x.dispose()` etc.

2018-01-25 18:26 UTC, andy-ms commented on types/video.js/index.d.ts
> +	type TechType = Tech;
This shouldn't be necessary, just use `Tech`

2018-01-25 18:26 UTC, andy-ms commented on types/video.js/tsconfig.json
> +        "noImplicitAny": false,
Please keep this `true`

2018-04-09 20:04 UTC, mhegazy commented
Thanks for your contribution. This PR has unaddressed comments and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2018-04-09 20:04 UTC, closed without merging