Updated sinon-chrome to v2.2.4
DefinitelyTyped/DefinitelyTyped pull request #23043
Opened 2018-01-19 06:10 UTC by crimx

Added `dispatch` to events. [Reference](https://github.com/acvetkov/sinon-chrome/blob/84b5743d4e828132382f155491d9c2babc67e99e/src/events/index.js#L20-L22).

Added `flush` to stubs. [Reference](https://github.com/acvetkov/sinon-chrome/blob/c6f73be55da567716e16f85c9d232276d7cc9b3b/src/api/stub.js#L45-L48).

Changed the following spies to stubs since only event listeners are spies. [Reference](https://github.com/acvetkov/sinon-chrome/blob/84b5743d4e828132382f155491d9c2babc67e99e/src/api/events.js#L57-L60)

```
chrome.alarms.clear
chrome.alarms.clearAll
chrome.alarms.create
chrome.alarms.get
chrome.alarms.getAll
crhome.runtime.getURL
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes.
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-01-20 12:47 UTC, pimterry approved these changes

2018-01-23 18:47 UTC, ghost requested changes

2018-01-23 18:47 UTC, andy-ms commented on types/sinon-chrome/index.d.ts
> +  flush(): void;
Rest of the file uses 4 space indents

2018-01-23 18:49 UTC, andy-ms commented on types/sinon-chrome/index.d.ts
> +  flush(): void;
I'll just fix these when merging

2018-01-23 18:49 UTC, merged