Loopback: add typing to Role.registerResolver function
DefinitelyTyped/DefinitelyTyped pull request #23074
Opened 2018-01-20 10:38 UTC by hiddestokvis

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Find an example usage of registerResolver here](https://loopback.io/doc/en/lb3/Defining-and-using-roles.html) [API docs here](http://apidocs.loopback.io/loopback/#role-registerresolver)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-01-20 18:37 UTC, enko commented
@hiddestokvis please also add the promise based resolver:

```typescript
static registerResolver(role: string, resolver: (role: string, ctx: Context) => Promise<boolean>): void;
```

2018-01-20 18:39 UTC, enko requested changes

2018-01-20 18:39 UTC, enko commented on types/loopback/index.d.ts
> +            static registerResolver(role: string, resolver: (role: string, ctx: Context, callback?: (err: Error, resolved: boolean) => void) => void): void;
Please add promised based resolver.

2018-01-20 19:41 UTC, kattsushi approved these changes
LGTM

2018-01-22 10:48 UTC, hiddestokvis commented
@enko good catch, I made the changes

2018-01-22 14:42 UTC, Sequoia commented
@ryancavanaugh is it possible for me to be removed from the loopback typings? I no longer work on that project. Thank you!

2018-01-25 17:11 UTC, andy-ms commented
@Sequoia Create a pull request removing yourself from the header.

2018-01-25 17:11 UTC, merged