Add types for hbs npm package
DefinitelyTyped/DefinitelyTyped pull request #23091
Opened 2018-01-21 13:59 UTC by DavidM77

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [X] The package does not provide its own types, and you can not add them.
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

Notes: Function type is used, but this is inline with the existing Handlebars and Express types.  Since hbs is an integration between Handlebars and Express I feel this is justified.

2018-01-22 12:45 UTC, plantain-00 requested changes

2018-01-22 20:33 UTC, DavidM77 commented
The test contains the following idiomatic express:
app.engine('html', require('hbs').__express);

If I use the suggested tslint.json, the tests fail with the following:
ERROR: 6:20  no-var-requires  require statement not part of an import statement

I not sure how to resolve this issue without adding to tslint.json.

2018-01-23 00:01 UTC, plantain-00 commented
You can add `// tslint:disable-next-line no-var-requires` above the line of code

2018-01-23 00:34 UTC, plantain-00 approved these changes

2018-01-23 18:29 UTC, andy-ms commented on types/hbs/hbs-tests.ts
> +app.engine('html', require('hbs').__express);
Actually, this lint rule is important -- `require()` is a function returning `any`. Please use an `import hbs = require("hbs")` instead.

2018-01-23 18:29 UTC, ghost requested changes
See comment

2018-01-24 00:19 UTC, merged