Fix trial_end type to allow special value 'now'
DefinitelyTyped/DefinitelyTyped pull request #23149
Opened 2018-01-23 23:59 UTC by acoll

https://stripe.com/docs/api/node

The api allows the special value of 'now' to be passed for trial_end.

2018-01-24 09:29 UTC, CodeAnimal commented
Looks good to me, although [L1333](https://github.com/acoll/DefinitelyTyped/blob/459189c25ab2da839da5158532bbea2d42ef90df/types/stripe/index.d.ts#L1333) is redundant as it isn't a valid [creation option](https://stripe.com/docs/api/node#create_customer) for a customer any more. 👍 

I'll update the customer creation options at some point though, so for now this looks good.

2018-01-24 09:30 UTC, CodeAnimal approved these changes

2018-01-24 09:30 UTC, CodeAnimal requested changes
Actually, can we change the `string` type to `"now"` so it explicitly only allows that word, not just any string.

2018-01-24 09:31 UTC, CodeAnimal commented
And can you then add some tests too, please.

2018-01-24 17:33 UTC, LinusU commented on types/stripe/index.d.ts
> +            trial_end?: number | string;
As noted, please change this to `number | "now";` 👍

2018-01-25 11:58 UTC, LinusU approved these changes
Perfect 👍

2018-01-25 11:58 UTC, CodeAnimal approved these changes
Good work 👍

2018-01-25 16:24 UTC, merged