Type definitions for catalog (2.x)
DefinitelyTyped/DefinitelyTyped pull request #23276
Opened 2018-01-30 05:25 UTC by wereHamster

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

dts-gen was a really bad starting point. Instead, it's based on a type definition file we've used internally for a while.

2018-01-30 12:26 UTC, plantain-00 requested changes

2018-01-30 12:26 UTC, plantain-00 commented on types/catalog/catalog-tests.ts
> +import { render } from "catalog";
I think some test should be added in this file, you may refer to: https://docs.catalog.style/configuration

2018-01-31 04:52 UTC, plantain-00 approved these changes

2018-01-31 09:33 UTC, wereHamster commented
@plantain-00 what are the next steps to get this PR merged?

2018-01-31 10:26 UTC, plantain-00 commented
Others will merge this, I just do code review

2018-01-31 20:19 UTC, sheetalkamat requested changes
Please update the tslint file

2018-01-31 20:19 UTC, sheetalkamat commented on types/catalog/tslint.json
> +	"rules": {
Please remove the rules from this tslint. You should just be extending dtslint/dt.json

2018-02-01 17:05 UTC, sheetalkamat approved these changes

2018-02-01 17:05 UTC, merged