[qrcode]improve types of qrcode@1.2.0
DefinitelyTyped/DefinitelyTyped pull request #23289
Opened 2018-01-30 15:14 UTC by ArtworkAD

Add toDataURL with promise as response

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/soldair/node-qrcode#es6es7>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-01-30 19:58 UTC, sheetalkamat requested changes
Please address feedback

2018-01-30 19:58 UTC, sheetalkamat commented on types/qrcode/index.d.ts
> +export function toDataURL(text: string | QRCodeSegment[]): Promise<any>;
Dont you need similar methods for ```toCanvas```

2018-01-30 19:58 UTC, sheetalkamat commented on types/qrcode/index.d.ts
> +/**
You would want the signature of toDataUrl that returns promise before the existing signature since the new one takes fewer parameters

2018-01-31 10:53 UTC, ArtworkAD commented
@sheetalkamat changes applied :)

2018-01-31 20:24 UTC, sheetalkamat approved these changes

2018-01-31 20:25 UTC, merged