[@types/expo] Improve Facebook's Response type definition
DefinitelyTyped/DefinitelyTyped pull request #23343
Opened 2018-02-01 14:10 UTC by sergioalvz

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.expo.io/versions/latest/sdk/facebook.html#returns
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

***

Hi there,

with the previous definition for the type `Response` it was required to do some type casting in order to access the `token` property (since union only allows to access common members). This change, otherwise, respects the response definition from Expo but does not force the user to check the response type in order to access its members.

The compiler was raising an error when working with the following code:

```typescript
const { token } = await Facebook.logInWithReadPermissionsAsync(appId, {
    behavior: 'system',
    permissions,
});
```

Let me know if there is something more I can do! :)

2018-02-01 14:56 UTC, KonstantinKai requested changes
@sergioalvz, thank you for your PR. Can you write the test to cover this case, please?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/expo/expo-tests.tsx#L169

2018-02-02 08:18 UTC, sergioalvz commented
@KonstantinKai just did it :)

2018-02-02 09:08 UTC, KonstantinKai approved these changes
@sergioalvz 10x. Approved 👍

2018-02-02 21:58 UTC, merged

2018-02-05 12:24 UTC, sergioalvz commented
Hey folks @RyanCavanaugh @andy-ms, sorry to bother you, but according to the FAQ I should ping you if the merge does not roll out a new package version on NPM in more than 24 hours. Could you please take a look? This was merged 3 days ago, but the npm package was not published yet: https://www.npmjs.com/package/@types/expo

Thanks!