[UIKit] updated `upload` definition due to UIKit api changes
DefinitelyTyped/DefinitelyTyped pull request #23439
Opened 2018-02-05 21:26 UTC by romko391

@andy-ms please review the change.
UIKit has now only `UIKit.upload()` method for file upload.
Therefore old ones are removed in the [latest version](https://getuikit.com/docs/upload).

2018-02-14 12:12 UTC, giovannicandido commented
We need to provide a major version change for this definition (3.x).
I don't find info on how to do that.

2018-02-14 12:28 UTC, giovannicandido requested changes
Looks like there is no way to keep 2.x and 3.x branches and incrementally update the definition.
We going to need update the version to 3 and review all definitions, that is a lot of work.

Any thoughts?

2018-02-14 15:59 UTC, andy-ms commented
@giovannicandido It is possible to create a `v2` directory to stoll the older types -- though this should only be done if you plan to continue making v2 updates even after v3 is published.

2018-02-19 16:27 UTC, giovannicandido commented
@andy-ms Thanks. 2.x is going to be freeze I think.
Going to check that this week.

2018-04-09 20:06 UTC, mhegazy commented
Thanks for your contribution. This PR has unaddressed comments and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2018-04-09 20:06 UTC, closed without merging