update type of bold property
DefinitelyTyped/DefinitelyTyped pull request #23452
Opened 2018-02-06 09:21 UTC by gowthamrodda

fix for the issue
node_modules/@types/colors/index.d.ts(118,5): error TS2717: Subsequent property declarations must have the same type.  Property 'bold' must be of type '() => string', but here has type 'string'.

2018-02-06 12:08 UTC, staeke requested changes
The properties under the String type are marked as properties returning String objects, not functions. I think you’re confusing extensions of String with the safe import which indeed exposes chainable Color objects. And Color is invokable with a String return type. Maybe it just works and you’ve mixed them. Maybe the safe part needs improvement. Haven’t checked. But as of now this PR seems erroneous

2018-02-13 00:20 UTC, DABH commented
I believe this is related to https://github.com/Marak/colors.js/issues/168 -- problem is bold is now a String prototype method.  There is likely a better solution than what's proposed here, though need to think for a bit of a proper workaround... (`string | () => string`? lol)

2018-02-22 05:17 UTC, DABH commented
I suggested a possible workaround in ^^that issue (168) -- give it a try if you can, if it works then we can use that as the fix...

2018-04-09 20:07 UTC, mhegazy commented
Thanks for your contribution. This PR has merge conflicts and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2018-04-09 20:07 UTC, closed without merging