fix for knockout mapping bug reported in #23015
DefinitelyTyped/DefinitelyTyped pull request #23478
Opened 2018-02-07 10:37 UTC by ffMathy

fix for knockout mapping bug reported in #23015

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-02-15 22:21 UTC, DanielRosenwasser commented
Can you add a test with an `// $ExpectError` or `// $ExpectType` as explained [here](https://github.com/Microsoft/dtslint/tree/1b1a11168619108dd8fff7453c3df28201282338#write-tests)?

2018-02-15 22:22 UTC, DanielRosenwasser requested changes
Can you add a test with an `// $ExpectError` or `// $ExpectType` as explained [here](https://github.com/Microsoft/dtslint/tree/1b1a11168619108dd8fff7453c3df28201282338#write-tests)?

2018-02-26 11:03 UTC, ffMathy commented
I added a test.

2018-02-26 22:18 UTC, DanielRosenwasser approved these changes

2018-02-28 23:05 UTC, merged

2018-03-03 14:30 UTC, Sebazzz commented on types/knockout/index.d.ts
> +    isObservable<T>(instance: KnockoutObservable<T>): instance is KnockoutObservable<T>;
Input of type T is still valid for this function.

2018-03-03 14:30 UTC, Sebazzz commented on types/knockout/index.d.ts
> +    isWriteableObservable<T>(instance: KnockoutObservable<T>): instance is KnockoutObservable<T>;
Input of type T is still valid for this function.

2018-03-03 14:31 UTC, Sebazzz commented on types/knockout/index.d.ts
> +    isObservable<T>(instance: KnockoutObservable<T>): instance is KnockoutObservable<T>;
You might want to consider adding:

     isObservable<T>(instance: KnockoutObservable<T>): false;

Or changing it to:

     isObservable<T>(instance: KnockoutObservable<T> | T): instance is KnockoutObservable<T>;