[bytes] Upgrade to 3.0.0
DefinitelyTyped/DefinitelyTyped pull request #23516
Opened 2018-02-08 18:52 UTC by believer

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [https://github.com/visionmedia/bytes.js](https://github.com/visionmedia/bytes.js)
- [X] Increase the version number in the header if appropriate.

2018-02-13 19:55 UTC, DanielRosenwasser requested changes

2018-02-14 03:58 UTC, believer commented
@DanielRosenwasser I've removed the tslint rules and fixed all issues that surfaced when linting without them commented out!

2018-03-01 20:43 UTC, DanielRosenwasser approved these changes

2018-03-01 20:44 UTC, DanielRosenwasser commented
Sorry for the delay, I didn't catch the notifications here. Thank you!

2018-03-01 20:44 UTC, merged