[filesize] Update to 3.6.0
DefinitelyTyped/DefinitelyTyped pull request #23561
Opened 2018-02-11 12:07 UTC by renchap

Updating to the latest version.
Options have been updated according to the README documentation, added the `partial` function, updated tests with the latest examples from the README.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/avoidwork/filesize.js/blob/master/README.md
- [x] Increase the version number in the header if appropriate.

2018-02-16 22:29 UTC, DanielRosenwasser requested changes

2018-02-16 22:29 UTC, DanielRosenwasser commented on types/filesize/index.d.ts
> +// Type definitions for filesize 3.6.0
Looks like our lint rules are disabled for this package. Can you enable the lints in our `tslint.json` and fix up the version string to only be a `MAJOR.MINOR` version (e.g. `4.7`), as opposed to including the patch or containing a leading `v` (e.g. `v1.2.3`).

2018-02-16 22:30 UTC, DanielRosenwasser commented on types/filesize/index.d.ts
> +        * Decimal separator character, default is .
Probably want to put this in backticks or quotemarks

2018-02-17 15:29 UTC, renchap commented
Thanks for the review @DanielRosenwasser 
I do not know why but a lot of TSLint rules were ignored in `tslint.json`. Now it only extends `dtslint/dt.json` and I fixed all the linting errors.

2018-02-19 06:23 UTC, DanielRosenwasser approved these changes

2018-02-19 06:23 UTC, merged

2018-02-19 06:23 UTC, DanielRosenwasser commented
Thank you very much!