Add null type to Value union type
DefinitelyTyped/DefinitelyTyped pull request #23627
Opened 2018-02-13 22:57 UTC by richbai90

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/tgriesser/knex/blob/ca702cf4d15a48b246b130738b9f0948026086c1/src/query/builder.js#L253

- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-02-14 00:29 UTC, mastermatt requested changes
The `Value` type is used heavily throughout the file, yet the example provided is a discrete case for the third arg in a three arg `where` call. Perhaps it would be more appropirate to just add `| null` to the `value` of https://github.com/richbai90/DefinitelyTyped/blob/272910b18c40ef5a6526f9983ab7adc94836747e/types/knex/index.d.ts#L266.

Also, if you could add a test or two showing the usage and add `Knex` to the PR title.

2018-02-14 16:33 UTC, richbai90 commented
The requested changes have been made in the latest commits

2018-02-14 21:44 UTC, mastermatt approved these changes

2018-02-15 19:14 UTC, merged

2018-02-15 19:14 UTC, DanielRosenwasser commented
Thanks!