Master
DefinitelyTyped/DefinitelyTyped pull request #23669
Opened 2018-02-15 16:19 UTC by flavionegrao

Added beforeFind readPreferences options

2018-02-16 07:41 UTC, DanielRosenwasser requested changes

2018-02-16 07:41 UTC, DanielRosenwasser commented on types/parse/index.d.ts
> +            Primary = 'PRIMARY',
Does this enum actually exist at runtime? Can you provide documentation for the change?

2018-02-16 11:18 UTC, flavionegrao commented
Apart from being a awesome feature Parse docs are not updated with this at the moment.
But it is implemented since 2.5.0, you can see them implemented reading the unit tests.
https://github.com/parse-community/parse-server/pull/3865/commits <https://github.com/parse-community/parse-server/pull/3865/commits>
https://github.com/parse-community/parse-server/issues/3960 <https://github.com/parse-community/parse-server/issues/3960>
https://github.com/parse-community/parse-server/pull/3865/files#diff-69d2e3afe48f905f42e4bd18eb855beb <https://github.com/parse-community/parse-server/pull/3865/files#diff-69d2e3afe48f905f42e4bd18eb855beb>


Cheers, Flavio



> Em 16 de fev de 2018, à(s) 05:41, Daniel Rosenwasser <notifications@github.com> escreveu:
> 
> @DanielRosenwasser requested changes on this pull request.
> 
> In types/parse/index.d.ts <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23669#discussion_r168690174>:
> 
> >          interface BeforeSaveResponse extends FunctionResponse {
>              success: () => void;
>          }
> +
> +        // Read preference describes how MongoDB driver route read operations to the members of a replica set.
> +        enum ReadPreferenceOption {
> +            Primary = 'PRIMARY',
> Does this enum actually exist at runtime? Can you provide documentation for the change?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23669#pullrequestreview-97099199>, or mute the thread <https://github.com/notifications/unsubscribe-auth/ABhfNB5TqmIS3f8vKgNY7H4fPCuvOBOFks5tVTEegaJpZM4SHG0L>.
>

2018-02-20 00:29 UTC, flavionegrao commented
Daniel?

2018-02-20 20:15 UTC, DanielRosenwasser approved these changes

2018-02-20 20:15 UTC, merged

2018-02-20 20:15 UTC, DanielRosenwasser commented
Thanks for the patience!