Add DayPickerSingleDateController support
DefinitelyTyped/DefinitelyTyped pull request #23660
Opened 2018-02-15 05:43 UTC by NathanNZ

Add the typing for DayPickerSingleDateControllerShape. This isn't documented too well on the react-dates page, but works similar to the SingleDayPicker. 

I'm relatively new to typescript so any suggestions are more than welcome!

___

- [:thumbsup: ] Use a meaningful title for the pull request. Include the name of the package modified.
- [:thumbsup: ] Test the change in your own code. (Compile and run.)
- [:thumbsup:] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [:thumbsup:] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [:thumbsup: ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [:thumbsup: ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/airbnb/react-dates
- [:thumbsup: ] Increase the version number in the header if appropriate. **(tested on v16)**
- [:thumbsup: ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. **(no substantial changes)**

2018-03-02 17:26 UTC, uniqueiniquity requested changes
Code looks good! Please test your changes in react-dates-tests.tsx.

2018-03-20 16:32 UTC, uniqueiniquity commented
Please ensure your new test passes by adding `DayPickerSingleDateController` to the set of members you are importing from `react-dates`.

2018-03-20 16:33 UTC, uniqueiniquity requested changes

2018-03-20 16:33 UTC, uniqueiniquity commented on types/react-dates/react-dates-tests.tsx
> +         return <DayPickerSingleDateController
Please ensure your new test passes by adding `DayPickerSingleDateController` to the set of members you are importing from `react-dates`.

2018-04-09 17:58 UTC, mhegazy commented
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2018-04-09 17:58 UTC, closed without merging