Added typings for jquery-treegrid
DefinitelyTyped/DefinitelyTyped pull request #23702
Opened 2018-02-16 14:19 UTC by pmorelli92

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.

2018-02-16 18:20 UTC, DanielRosenwasser requested changes
Thanks! Please remove the global `treegrid` unless I've missed something.

2018-02-16 18:20 UTC, DanielRosenwasser commented on types/jquery-treegrid/index.d.ts
> +declare var treegrid: JQueryStatic;
I'm not seeing this global variable when I try using the library.

2018-02-19 15:20 UTC, pmorelli92 commented
@DanielRosenwasser done!

2018-02-19 18:54 UTC, DanielRosenwasser approved these changes

2018-02-19 18:54 UTC, DanielRosenwasser commented
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.

If you don't care about any of this stuff, I can always just pull in the changes.

2018-02-20 20:01 UTC, DanielRosenwasser commented
Uh oh - your rebase brought a bunch of merge commits. Try creating a new branch based off of DefinitelyTyped's `master`:

```
git branch add upstream https://github.com/DefinitelyTyped/DefinitelyTyped
git checkout upstream/master
git checkout -b jqueryTreegrid
```

and cherry-pick the following:

1. 500c02f
2. 6245eac

push the branch to your remote

```sh
git push origin jqueryTreegrid
```

then switch this PR's active branch to your `jqueryTreegrid` branch or open up a new PR.

2018-02-26 22:17 UTC, DanielRosenwasser requested changes
Problems with merge commit history.

2018-04-09 19:13 UTC, mhegazy commented
Thanks for your contribution. This PR has failing CI tests and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2018-04-09 19:13 UTC, closed without merging