D3 geo strict null check
DefinitelyTyped/DefinitelyTyped pull request #23794
Opened 2018-02-20 18:17 UTC by Ledragon

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: [23611](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23611)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-02-20 18:31 UTC, tomwanzek commented on types/d3-geo/index.d.ts
> +// TypeScript Version: 2.4
Can you already set this back to 2.3 (we should not need a TS 2.4 minimum constraint at this point, unless you were thinking of using something like `string enums`)

Setting the constraint back to TS 2.3 will remove the Travis/Test conflicts with `d3`.

2018-02-20 18:33 UTC, tomwanzek commented
Thanks for opening it! I'll look at it in more detail tonight, hopefully.

2018-02-20 19:58 UTC, Ledragon commented
Ha! Nailed it! Let me know if the changes suit you

2018-02-20 20:07 UTC, tomwanzek commented
Thanks, will take a look tonight.

2018-02-26 19:57 UTC, tomwanzek commented
@typescript-bot Do not merge this PR. My started review will need to be completed. The review will request changes.

cc @Ledragon Got sidetracked on something else and will follow-up shortly.

2018-02-26 20:06 UTC, tomwanzek requested changes
We will need to move the addition of `null` to the intersection somewhere else. 

```ts
export type GeoGeometryObjects = GeoJSON.GeometryObject | GeoSphere;
```
Is too broad, It might be that we need to do either

Option 1)
```ts
export interface ExtendedFeature<GeometryType extends GeoGeometryObjects | null, Properties extends GeoJSON.GeoJsonProperties> extends GeoJSON.GeoJsonObject {
    geometry: GeometryType;
    properties: Properties;
    id?: string | number;
}
```

or 

Option 2)
```ts
export interface ExtendedFeature<GeometryType extends GeoGeometryObjects, Properties extends GeoJSON.GeoJsonProperties> extends GeoJSON.GeoJsonObject {
    geometry: GeometryType | null;
    properties: Properties;
    id?: string | number;
}
```

I would prefer option 1), because it allows to narrow a specific `ExtendedFeature<G, P>` down where it is known that `G` will never be null. But by implication, we may have to adjust some of the method signatures to infer types differently. Option 2) would be the smallest common denominator, but it is also very conservative.

I am still investigating (need to look at the interaction with the GeoJSON definitions, which in essence take Option 2) for Feature)

2018-02-27 18:03 UTC, Ledragon commented
@tomwanzek thanks for the feedback. Do you think we should try and handle your proposed change to `GeoJSON` together with the changes suggested in your Option 1?

Anyhow, as you still seem to be fiddling with it, I suggest not to make any change as of now, and will follow the path indicated by your infinite wisdom and knowledge :p

2018-02-27 19:54 UTC, tomwanzek commented
Very finite 🤣 . Agreed to hold off on changes until I have figured out the little snag I ran into with `ExtendedFeatureCollection`. Did not get to play with it to finalization yesterday, hopefully by tomorrow I have a more complete picture.

2018-02-27 20:12 UTC, denisname commented
Hi,
While finishing writing types for `topojson`, I got the same problems as you in definition of `Feature` in GeoJSON. I just wrote a fix and tests. I was going to do the push request but now I see your discussion...

2018-02-28 04:28 UTC, tomwanzek commented
@denisname As far as GeoJSON goes, your proposed definition changes are exactly in line with my thinking. So I would second the PR you drafted to them.

Unfortunately, with respect to what we called `ExtendedFeatureCollection` in `d3-geo` we are in a little bind. Oh, path-dependency 😭  😉 

Not having done the `strictNullChecks` right away, we used only one generic parameter to represent the permissible features for the collection. Ideally, we should have split out the `geometry` and `properties` as we did with `ExtendedFeature`.

That's what is creating  the extra little wrinkle with type inference on functions like `geoArea(...)`, if we add generics with defaults to them.

As far as I have tested it out, we may have to end up breaking users _either_:
(A) by rewriting the `ExtendedFeatureCollection<G, P>` interface with two parameters (geometry, properties) rather than feature, _or_
(B) by simply adding a `null` union to 
```ts
export interface ExtendedFeatureCollection<FeatureType extends ExtendedFeature<GeoGeometryObjects | null, any>> extends GeoJSON.GeoJsonObject {
    features: FeatureType[];
}
```
which will mean they may have to explicitly cast the generics in updated function signatures like `geoArea<...>(...)`.

Conceptually (A) is clearly preferable, as it fixes a, in hindsight, slightly misguided design. I will give it one more try to see if there is a way to not break anyone. However, if we _at least_ face the breaking impact of (B), then we might as well bite the bullet and clean up properly using (A).

Short-term pain, long-term gain. Too bad we have no public changelog for the definitions to explain the change, even if we cannot use semantic versioning...

2018-03-06 18:10 UTC, Ledragon commented
Not sure I am following all the details of the conversation, but I am still alive at least :p

2018-03-06 19:10 UTC, tomwanzek commented
I have not seen a response to GeoJSON PR #23978 yet. Let's give that a couple of more days, to see, if the definition owners are going along with the proposal.

Then we can decide on how we proceed here.

2018-03-09 17:42 UTC, tomwanzek commented
@Ledragon: Now that the geoJSON definitions have been updated to have the more permissive `Feature<...>` and `FeatureCollection<...>` definitions, could you re-base this PR so we can utilize them?

Then we can tackle the next steps on their `Extended...` counterparts  and the method signatures.

2018-03-10 09:46 UTC, Ledragon commented
@tomwanzek Merged master in the branch

2018-03-13 16:57 UTC, tomwanzek commented
Thanks, I will get back to it later, probably tonight, and provide a proposal to address the necessary changes by means of an example, say for `geoArea()` to  use generics.

2018-03-13 17:32 UTC, Ledragon commented
Great, sounds good to me (especially cause you're taking the job on :-) )

2018-03-13 17:36 UTC, tomwanzek commented
Not too fast :smile: I will just provide a proposed example solution with possibly an impact assessment that identifies a breaking change. The heavy lifting of updating the PR for review is all yours 😜 Oh, and I am pushing a small mini PR to wrap up one final improvement to **d3-contour**

2018-03-13 17:36 UTC, tomwanzek commented
"small mini", now that was redundant!

2018-03-13 17:52 UTC, Ledragon commented
Okay, s(hoot)ure :-)

2018-03-13 17:57 UTC, tomwanzek commented
> s(hoot)ure

Had not seen that one before... 🤣

2018-03-13 18:01 UTC, Ledragon commented
It felt right ^^

2018-03-13 21:02 UTC, tomwanzek commented
Let's meet mid ground, shall we? :smile:

Here is the proposed `index.ts` file in its entirety for copy/pasting. Since this PR is already half-way there...
The only **"breaking change"** will be that we actually start using TS 2.3 features, namely the generic parameter defaults.

Once you have it in you change tracking you will see the detailed changes easier. Essentially, it:
* adds nullability to `ExtendedFeature` and `ExtendedFeatureCollection` "geometries" and "properties" generics
* sets defaults on various interfaces for short-hand use
* cleans up the argument types in signatures to use the shorthand interfaces (with implied default generic types)
* cleans up intersection types to use the shorthand interfaces (with implied default generic types)
* cleans up method/function generics where possible. Note that in the case of `geoCircle<...>()` and `geoPath<...>()` we cannot simplify the overloads further without possibly breaking the consumer, as the meaning of the second overload would change from setting the "Datum" to setting the `this` context. (single template parameter for second  generic in return-type interface)

In the next comment, I will post a pre-view of the proposed changes to the "test" file, beyond, what you have already done.

```ts
// Type definitions for D3JS d3-geo module 1.9
// Project: https://github.com/d3/d3-geo/
// Definitions by: Hugues Stefanski <https://github.com/Ledragon>, Tom Wanzek <https://github.com/tomwanzek>, Alex Ford <https://github.com/gustavderdrache>, Boris Yankov <https://github.com/borisyankov>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped
// TypeScript Version: 2.3

// Last module patch version validated against: 1.9.0

import * as GeoJSON from 'geojson';

// ----------------------------------------------------------------------
// Shared Interfaces and Types
// ----------------------------------------------------------------------

/**
 * A basic geometry for a sphere, which is supported by d3-geo
 * beyond the GeoJSON geometries.
 */
export interface GeoSphere {
    /**
     * Sphere geometry type
     */
    type: 'Sphere';
}

/**
 * Type Alias for GeoJSON Geometry Object and GeoSphere additional
 * geometry supported by d3-geo
 */
export type GeoGeometryObjects = GeoJSON.GeometryObject | GeoSphere;

/**
 * A GeoJSON-style GeometryCollection which supports GeoJSON geometry objects
 * and additionally GeoSphere.
 *
 * The generic refers to the type(s) of d3-geo geometry objects contained in the collection.
 */
export interface ExtendedGeometryCollection<GeometryType extends GeoGeometryObjects = GeoGeometryObjects> {
    type: string;
    bbox?: number[];
    crs?: {
        type: string;
        properties: any;
    };
    geometries: GeometryType[];
}

/**
 * A GeoJSON-style Feature which support features built on GeoJSON GeometryObjects
 * or GeoSphere.
 *
 * The first generic refers to the type(s) of d3-geo geometry objects underlying the ExtendedFeature.
 * Unless explicitly ruled out, the geometry value is nullable.
 *
 * The second generic refers to the data type of the properties of the ExtendedFeature. Unless explicitly ruled out,
 * the properties value is nullable.
 */
export interface ExtendedFeature<
    GeometryType extends GeoGeometryObjects | null = GeoGeometryObjects | null,
    Properties extends GeoJSON.GeoJsonProperties = GeoJSON.GeoJsonProperties
    > extends GeoJSON.GeoJsonObject {
    geometry: GeometryType;
    properties: Properties;
    id?: string | number;
}

/**
 * A GeoJSON-style FeatureCollection which supports GeoJSON features
 * and features built on GeoSphere
 *
 * The generic refers to the type of ExtendedFeature contained in the ExtendedFeatureCollection.
 */
export interface ExtendedFeatureCollection<FeatureType extends ExtendedFeature = ExtendedFeature> extends GeoJSON.GeoJsonObject {
    features: FeatureType[];
}

/**
 * Type Alias for permissible objects which can be used with d3-geo
 * methods
 */
export type GeoPermissibleObjects = GeoGeometryObjects | ExtendedGeometryCollection | ExtendedFeature | ExtendedFeatureCollection;

// ----------------------------------------------------------------------
// Spherical Math
// ----------------------------------------------------------------------

/**
 * Returns the spherical area of the specified feature in steradians.
 * This is the spherical equivalent of path.area.
 *
 * @param object A geographic feature supported by d3-geo (An extension of GeoJSON feature).
 */
export function geoArea(object: ExtendedFeature): number;
/**
 * Returns the spherical area of the specified feature collection in steradians.
 * This is the spherical equivalent of path.area.
 *
 * @param object A geographic feature collection supported by d3-geo (An extension of GeoJSON feature).
 */
export function geoArea(object: ExtendedFeatureCollection): number;
/**
 * Returns the spherical area of the specified GeoJson Geometry Object or GeoSphere object in steradians.
 * This is the spherical equivalent of path.area.
 *
 * @param object A GeoJson Geometry Object or GeoSphere object supported by d3-geo (An extension of GeoJSON).
 */
export function geoArea(object: GeoGeometryObjects): number;
/**
 * Returns the spherical area of the specified geographic geometry collection in steradians.
 * This is the spherical equivalent of path.area.
 *
 * @param object A geographic geometry collection supported by d3-geo (An extension of GeoJSON geometry collection).
 */
export function geoArea(object: ExtendedGeometryCollection): number;

/**
 * Returns the spherical bounding box for the specified feature. The bounding box is represented by a two-dimensional array: [[left, bottom], [right, top]],
 * where left is the minimum longitude, bottom is the minimum latitude, right is maximum longitude, and top is the maximum latitude. All coordinates are given in degrees.
 * (Note that in projected planar coordinates, the minimum latitude is typically the maximum y-value, and the maximum latitude is typically the minimum y-value.)
 * This is the spherical equivalent of path.bounds.
 *
 * @param object A geographic feature supported by d3-geo (An extension of GeoJSON feature).
 */
export function geoBounds(object: ExtendedFeature): [[number, number], [number, number]];
/**
 * Returns the spherical bounding box for the specified feature collection. The bounding box is represented by a two-dimensional array: [[left, bottom], [right, top]],
 * where left is the minimum longitude, bottom is the minimum latitude, right is maximum longitude, and top is the maximum latitude. All coordinates are given in degrees.
 * (Note that in projected planar coordinates, the minimum latitude is typically the maximum y-value, and the maximum latitude is typically the minimum y-value.)
 * This is the spherical equivalent of path.bounds.
 *
 * @param object A geographic feature collection supported by d3-geo (An extension of GeoJSON feature).
 */
export function geoBounds(object: ExtendedFeatureCollection): [[number, number], [number, number]];
/**
 * Returns the spherical bounding box for the specified GeoJson Geometry Object or GeoSphere object. The bounding box is represented by a two-dimensional array: [[left, bottom], [right, top]],
 * where left is the minimum longitude, bottom is the minimum latitude, right is maximum longitude, and top is the maximum latitude. All coordinates are given in degrees.
 * (Note that in projected planar coordinates, the minimum latitude is typically the maximum y-value, and the maximum latitude is typically the minimum y-value.)
 * This is the spherical equivalent of path.bounds.
 *
 * @param object A GeoJson Geometry Object or GeoSphere object supported by d3-geo (An extension of GeoJSON).
 */
export function geoBounds(object: GeoGeometryObjects): [[number, number], [number, number]];
/**
 * Returns the spherical bounding box for the specified geometry collection. The bounding box is represented by a two-dimensional array: [[left,  [...]

2018-03-13 21:13 UTC, tomwanzek requested changes
Suggestion:
* use comment `index.ts
* see my comment about updates to `d3-geo-tests.ts`, as I cannot comment on the affected lines directly in this review.

2018-03-13 21:13 UTC, tomwanzek commented on types/d3-geo/d3-geo-tests.ts
> +let canvasContext: CanvasRenderingContext2D = {} as any;
You can alternatively do this for definition testing purposes
```ts
// HACK: declare to not have to initialize
declare let canvasContext: CanvasRenderingContext2D;
```

2018-03-13 21:13 UTC, tomwanzek commented on types/d3-geo/index.d.ts
> +export type GeoGeometryObjects = GeoJSON.GeometryObject | GeoSphere | null;
As per my main thread comment, you can do a wholesale replacement of the pasted `index.ts` which will remove the need for this line change.

2018-03-13 21:25 UTC, Ledragon commented
I'll try to review this in the upcoming days, unsure at to when exactly...

2018-03-13 21:28 UTC, tomwanzek commented
As for the `d3-geo-tests.ts` file:

Keep your current changes and:

(1) Use the following to remove the tslint comment for the `circleGeneratorSimple` initialization (uses defaults)
```ts
let circleGeneratorSimple: d3Geo.GeoCircleGenerator = d3Geo.geoCircle();
```
(2) The declaration of geoPathCanvas can be shortened  to (uses defaults)
```ts
let geoPathCanvas: d3Geo.GeoPath;
```

(3) Add the following nullable features/collections to the beginning of the file, where we keep all the sample data:
```ts
const sampleNullableFeature: GeoJSON.Feature<null> = {
    type: 'Feature',
    geometry: null,
    properties: null
};

const sampleExtendedNullableFeature: d3Geo.ExtendedFeature = {
    type: 'Feature',
    geometry: null,
    properties: null
};

const sampleNullableFeatureCollection: GeoJSON.FeatureCollection<null> = {
    type: 'FeatureCollection',
    features: [
        sampleNullableFeature,
        sampleNullableFeature
    ]
};

const sampleExtendedNullableFeatureCollection: d3Geo.ExtendedFeatureCollection = {
    type: 'FeatureCollection',
    features: [
        sampleExtendedNullableFeature,
        sampleExtendedNullableFeature
    ]
};
```
(4) This is where the chore part comes in 🤢 , wherever function/methods allow `Feature`, `FeatureCollection`, `ExtendedFeature` and `ExtendedFeatureCollection` add in test lines for their "nullable" sample data equivalents. E.g. in the case of `geoArea(...)`, this would end up adding to the existing tests:
```ts
area = d3Geo.geoArea(sampleNullableFeature);
area = d3Geo.geoArea(sampleExtendedNullableFeature);
area = d3Geo.geoArea(sampleNullableFeatureCollection);
area = d3Geo.geoArea(sampleExtendedNullableFeatureCollection);
```

2018-03-13 21:33 UTC, tomwanzek commented
@LeDragon No worries, it's not a rush but at least we're getting to closure without breaking changes to `ExtendedFeatureCollection<....>`
FYI, I will submit another PR to GeoJson to also set a default for the geometries in `Feature` and `FeatureCollection`, this way the can be used with the same shorthand as `ExtendedFeature` and `ExtendedFeatureCollection`, without any template parameters. Overlooked the simplicity the first time around.

2018-03-21 23:54 UTC, tomwanzek commented
@Ledragon Do you want to leave this PR limited to its initial focus or add in the additional minor-release feature in [d3-geo 1.10](https://github.com/d3/d3-geo/releases/tag/v1.10.0)?

2018-03-22 20:04 UTC, Ledragon commented
I think a separate PR can be submitted fro v1.10, as I still have to grasp what you suggested above (I keep it in mind, but my time devote to this is not as extended as I would like)

2018-03-22 21:16 UTC, tomwanzek commented
Understandable. I can just review the other PR before the week is up and approve it in the meantime. If it gets merged earlier, you'll just have to rebase/merge the new feature into this PR.

2018-04-07 08:59 UTC, Ledragon commented
Ok, so I started resynchronizing the code you posted with the state of my branch. The task is less simple than expected, as the version 10 methods were added, preventing a simple copy/paste (this will teach me not to wait so long before getting to the task). I am putting this on the top of my task list as of now, I hope to be done in the upcoming days.

2018-04-08 08:10 UTC, Ledragon commented
Unless I am mistaken, that should be it :-)

2018-04-09 19:57 UTC, mhegazy commented
@tomwanzek can i get a final 👍 for this PR?

2018-04-14 18:39 UTC, tomwanzek commented
@Ledragon and @mhegazy apologies for the slight delay. Will review now.

2018-04-14 19:25 UTC, tomwanzek approved these changes
LGTM

2018-04-14 19:35 UTC, tomwanzek commented
@Ledragon Thanks for all the tedious work on this one!!! I would say: LGTM.

The only, two follow-up items are as follows:
(1) I am  wondering, whether we should introduce two new interfaces `GeoInvertibleRawProjection` and `GeoInvertibleProjection`. To avoid the need for either testing `invert()` existence or asserting it `invert!()` in cases where it is know to be supported. May require adding some generics to some functions/methods (with defaults, so it's non-breaking), but allows narrowing in known circumstances. Then we would declare invertible (raw) projection right away with the invertible type.

(2) Chore PR to change from commenting out expectedly failing tests, to using: `// $ExpectError` in the prior line (It's something @denisname pointed out. We have never revisited our practice since the early days of DT in this regard. I will take that one one)

2018-04-14 19:37 UTC, merged

2018-04-14 20:47 UTC, tomwanzek commented
@mhegazy Thanks, you just made my day, 'cause outside is a it's raining ice pellets and sluch and I'll take anything to cheer up the spring mood right now 😄 🌞

2018-04-17 19:56 UTC, Ledragon commented
Weeeeeeee 🎉 
Not so tedious in the end, :VS: code made it not too hard

Let's maybe open a new issue with the chore points, so that we can let this thread die in peace