adding the exact property to IndexRoute definition
DefinitelyTyped/DefinitelyTyped pull request #23975
Opened 2018-02-28 10:25 UTC by Hrafnkellos

I'm getting an error in my project because the exact property isn't defined,
so here we can add it.

Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-02-28 11:28 UTC, egorshulga commented
@Hrafnkellos, could you provide link to the API documentation where this feature is described?

2018-02-28 15:11 UTC, Hrafnkellos commented
The documentation of react router where this property is used?

Documentation Page:
https://reacttraining.com/react-router/web/api/Route/exact-bool
https://reacttraining.com/react-router/web/api/Redirect/exact-bool
https://reacttraining.com/react-router/web/api/NavLink/exact-bool

Github Code for Route in React Router:
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js
Line 16

2018-03-01 06:17 UTC, egorshulga commented
@Hrafnkellos, actually, these docs are for react-router v4, but you PR brings changes to type definitions for v3. Its docs are [here](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md).
[Docs for IndexRoute](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#indexroute-1) state that it has `All the same props as Route except for path.` And Route doesn't have `exact` as a prop.

2018-03-01 06:19 UTC, egorshulga requested changes
IndexRoute doesn't have exact as a prop in react-router v3.

2018-03-04 01:22 UTC, closed without merging