README.es.md
DefinitelyTyped/DefinitelyTyped pull request #23993
Opened 2018-03-01 05:14 UTC by LuigiBaute

the second part which would be the whole README file. if you got any suggestions let me know! I'll gladly make as many commits as necessary :+1:  @DanielRosenwasser

2018-03-01 23:47 UTC, armanio123 requested changes
Let me know if you need translation on any of the comments.
Avisame si necesitas que traduzca cualquier comentario

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +#### Debería añadir un espacio de nombres vacío que no exporte un módulo que utilice ES6 style imports?
Change "espacio de nombres vacio" for "namespace"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +#### Debería añadir un espacio de nombres vacío que no exporte un módulo que utilice ES6 style imports?
...que utilice imports estilo ES6?

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +importar este módulo con un ES6 style import de forma `import * como foo de "foo";` conduce al error:
Fix the code: `import * as foo from "foo"`

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +> error TS2497: El módulo 'foo' resuelve a una entidad non-module y no puede ser importado utilizando esta construcción
Use the right translated message:

error ts2497: El módulo 'foo' se resuelve en una entidad que no es un módulo y no se puede importar mediante esta construcción

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Este error puede ser suprimido merging la declaración de función con un espacios de nombres vacíos de el mismo nombre, pero esta práctica no es recomendable.
...puede ser suprimido al unir la declaración de una función con un namespace vacío del mismo nombre,...

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Es más apropiado importar este módulo utilizando la sintaxis `import foo = require("foo");`, o utilizando una importación predeterminada como `import foo from "foo";` if using the `--allowSyntheticDe
Missing translation:

si usas la bandera `--allowSyntheticDefaultImports` si la ejecución de tu módulo soporta un esquema de interoperación para módulos no ECMAScript como tal.

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Los derechos de autor definidos en los archivos son respectivos de cada contribuidor enumerado al comienzo de cada archivo de definición.
Change to:
Los derechos de autor de cada archivo de definición son respectivos de cada contribuidor listado al comienzo de cada archivo de definición.

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +La `master` branch es automáticamentes publicada en el alcande de los  `@types` en NPM gracias a los [types-publisher](https://github.com/Microsoft/types-publisher).
Fix extra "s" on "automáticamentes". Also remove accent.

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Esto depende, pero la mayoría de los pull requests serán merged en alrededor de una semana. PRs que hayan sido autor aproved enumerado en el encabezado de las definiciones usualmente son merged más r
Missing accent "rápidamente"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Esto depende, pero la mayoría de los pull requests serán merged en alrededor de una semana. PRs que hayan sido autor aproved enumerado en el encabezado de las definiciones usualmente son merged más r
Fix typo: "revisones"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +#### Mi PR ha sido merged; ¿cuándo sera actualizado el paquete de `@types` NPM?
Missing accent: "será"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Un `package.json` puede ser incluido por el bien de especificar dependencias Aqui tienen un [ejemplo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pikaday/package.json).
Missing accent: "Aquí"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Ademas, `/// <reference types=".." />` no trabajara con path mapping, así que las dependencias deberán utilizar `import`.
Missing accent: "Además"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Porfavor tenga en cuenta que no es necesario para ejercer plenamente la definición en cada archivo de prueba - Es suficiente con probar solo los elementos globalmente accesibles en la prueba de archi
Typo "Porfavor"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Types para un paquete scoped `@foo/bar` deberán ir en `types/foo__bar`. tenga en cuenta el doble guión bajo.
Remove accent on "guión"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Cuando `dts-gen` es utilizado como scaffold en un paquete scoped, las propiedades `paths` deberan ser adaptadas manualmente en el paquete generado
Missing accent: "deberán"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Esto depende, pero la mayoría de los pull requests serán merged en alrededor de una semana. PRs que hayan sido autor aproved enumerado en el encabezado de las definiciones usualmente son merged más r
Missing accent: "más"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Los paquetes NPM deberán ser actualizados en unas cuantas horas. si ha pasado mas de 24 horas, menciona a @RyanCavanaugh y/o a @andy-ms en el PR para investigar.
Missing accent: "más"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Si el modulo al cual te estás refiriendo es un modulo externo (utilice `export`), utilice una import.
Missing accent: "módulo"

2018-03-01 23:47 UTC, armanio123 commented on README.es.md
> +Para probar como puede ser usada tu definición cuando se refieren globalmente o como un módulo importado, crea una carpeta `test`, y coloca dos archivos de prueba en el.  Name one `YourLibraryName-gl
Missing accent: "...archivos de  prueba en él..."

2018-03-02 02:46 UTC, LuigiBaute commented
Hey @armanio123 this one is fixed aswell! :+1:  thank you for your time and your corrections!

2018-03-02 03:27 UTC, LuigiBaute commented
Hi @armanio123 let me know if there is anything else to change :+1:

2018-03-02 03:43 UTC, closed without merging