Added types for wordpos 1.1
DefinitelyTyped/DefinitelyTyped pull request #24007
Opened 2018-03-01 18:24 UTC by guidojo

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-03-02 07:24 UTC, plantain-00 requested changes
A test file is required

2018-03-02 16:00 UTC, guidojo commented
@plantain-00 added tests, thought they weren't required in that manner. Had to rebase as well because author was incorrect

2018-03-02 23:41 UTC, plantain-00 approved these changes

2018-03-07 02:07 UTC, armanio123 requested changes

2018-03-07 02:07 UTC, armanio123 commented on types/wordpos/index.d.ts
> +export default WordPOS;
The library doesn't have a default export. Please change to use "export ="

2018-03-07 02:07 UTC, armanio123 commented on types/wordpos/wordpos-tests.ts
> +import WordPOS from 'wordpos';
Use import x = require("module") instead, as it doesn't define a default.

2018-04-09 19:09 UTC, mhegazy commented
Thanks for your contribution. This PR has unaddressed comments and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2018-04-09 19:09 UTC, closed without merging