[react-navigation]: added types in navigate params
DefinitelyTyped/DefinitelyTyped pull request #24051
Opened 2018-03-03 02:22 UTC by ArmandoAssuncao

Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-03-03 23:39 UTC, timwangdev commented
Flow type for `NavigationScreenProp` in official project does not include params generic, which is the most of this definition referenced.

https://github.com/react-navigation/react-navigation/blob/master/flow/react-navigation.js#L473-L499

What's the opinions of other maintainers? Should we keep sync with the flow type?

2018-03-10 13:20 UTC, iRoachie commented on types/react-navigation/index.d.ts
> +//                 Armando Assuncao <https://github.com/ArmandoAssuncao>
Adding your name here means you'll be one of the maintainers for these typings, and you'll get notifications for issues and PRs to this definition. Just checking if you understand what it means

2018-03-10 13:21 UTC, iRoachie requested changes
Confirm becoming a maintainer

2018-03-10 13:59 UTC, ArmandoAssuncao commented
@iRoachie yep, i understood about becoming maintainer.

2018-03-10 15:54 UTC, iRoachie approved these changes

2018-03-16 20:27 UTC, merged