[react-stripe-elements] - Allow id prop in ElementProps
DefinitelyTyped/DefinitelyTyped pull request #24054
Opened 2018-03-03 09:21 UTC by thchia

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/stripe/react-stripe-elements/pull/178 (I made the changes in the original repo too).
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-03-03 14:41 UTC, thchia commented
@santiagodoldan not sure who is the best person to @ here but you seem pretty active.

2018-03-03 16:26 UTC, santiagodoldan requested changes

2018-03-03 16:26 UTC, santiagodoldan commented on types/react-stripe-elements/index.d.ts
> +// 								 Thomas Chia <https://github.com/thchia>
Tabulate this correctly

2018-03-03 16:27 UTC, santiagodoldan commented
I'd merge both commits and add a better message, maybe mentioning the library you are modifying.

2018-03-04 03:04 UTC, thchia commented
@santiagodoldan Thanks, have addressed the issues.

2018-03-05 10:55 UTC, santiagodoldan approved these changes

2018-03-05 23:01 UTC, merged