Atom: Add id to MarkerLayer
DefinitelyTyped/DefinitelyTyped pull request #24075
Opened 2018-03-05 02:26 UTC by Hirse

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://atom.io/docs/api/v1.24.0/TextEditor#instance-getMarkerLayer

`MarkerLayer`s can be addressed by `id` but the typings do not currently include this id.

2018-03-05 17:35 UTC, lierdakil commented
Thanks. Bot seems to be broken, so /cc @smhxx, @GlenCFL.

For additional context:

`DisplayMarkerLayer`:
https://github.com/atom/text-buffer/blob/f85b6763bc39c2dd6739a9b2072ae06fc19e4c12/src/display-marker-layer.coffee#L13

`MarkerLayer`:
https://github.com/atom/text-buffer/blob/f85b6763bc39c2dd6739a9b2072ae06fc19e4c12/src/marker-layer.coffee#L34

2018-03-05 17:43 UTC, lierdakil requested changes
Since `TextEditor::getMarkerLayer(id)` at least claims to return `DisplayMarkerLayer`, I would argue by the same reasoning `id` should be added to the `DisplayMarkerLayer` interface as well (there it's the id of an underlying `MarkerLayer`)

Also, a good idea to add a couple simple tests to `types/atom/atom-tests.ts` while at it.

2018-03-05 22:18 UTC, Hirse commented
@lierdakil Done. Thanks for your suggestions.

2018-03-05 22:22 UTC, GlenCFL approved these changes
Thanks for the contribution.

2018-03-05 23:16 UTC, smhxx approved these changes
LGTM. Thanks for contributing!

2018-03-06 11:40 UTC, lierdakil approved these changes
Thanks

2018-03-06 20:29 UTC, merged