First attempt to implement a definition to yahoo/dnscache
DefinitelyTyped/DefinitelyTyped pull request #24102
Opened 2018-03-06 11:08 UTC by Nagato-Yuki

Please fill in this template.

- [/] Use a meaningful title for the pull request. Include the name of the package modified.
- [/] Test the change in your own code. (Compile and run.)
- [/] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [/] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [/] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [/] The package does not provide its own types, and you can not add them.
- [/] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [/] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [/] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

First attempt to implement a definition to `yahoo/dnscache`, mostly copied from `@types/node`'s `dns` because `dnscache` itself is wrapped around `dns`

2018-03-06 22:56 UTC, armanio123 requested changes

2018-03-06 22:56 UTC, armanio123 commented on types/dnscache/index.d.ts
> +declare var dnscache: DnsCache;
Use const instead of var.

2018-03-06 22:56 UTC, armanio123 commented on types/dnscache/dnscache-tests.ts
> +import * as dnscache from "dnscache";
Use require("module") as the d.ts is using commonjs modules.

2018-03-06 22:56 UTC, armanio123 commented on types/dnscache/tslint.json
> +        "unified-signatures": false,
Don't disable lint rules.

2018-03-06 22:56 UTC, armanio123 commented on types/dnscache/index.d.ts
> +declare module "dnscache" {
No need to declare module just use the "export =" instead.

2018-03-13 20:50 UTC, armanio123 commented
The latest commit doesn't address the import x = require("module") syntax. Please fix that before approving the PR.

2018-03-23 22:51 UTC, minestarks commented
@Nagato-Yuki please address the review comments to avoid the PR being closed due to inactivity. Thanks!

2018-04-03 20:52 UTC, paulvanbrenk commented
And closing due to inactivity

2018-04-03 20:52 UTC, closed without merging