Partial Translation of README.md to Filipino
DefinitelyTyped/DefinitelyTyped pull request #24111
Opened 2018-03-06 14:46 UTC by caratzky

Good day, @DanielRosenwasser !

This file is composed of about 2600 translatable words, so I decided to split them into two. I'll be submitting another pull request updating this file, this time the whole file being completely translated. I hope you merge this one as soon as possible so I can edit it in my next pull request. 

I'm also doing this because in the rewarding rules of Utopian, only a minimum of 1000 words is needed. So I'm planning to split these into two to receive two separate rewards. For this commit, I've translated about 1400 words. Hope you get my point. Thank you. 

Best Regards,
@caratzky

2018-03-15 05:21 UTC, DanielRosenwasser requested changes
Hey @caratzky, thanks so much for the PR! I was unable to find reviewers, however, I ran this through a translator and this looks pretty darn accurate!

If you wouldn't mind making updates based on my feedback and pinging me, I can then pull this in. Thanks!!

2018-03-15 05:21 UTC, DanielRosenwasser commented on README.fil.md
> +* [Mga Pagta-tyoe](https://github.com/typings/typings)
This should be left as `typings`

2018-03-15 05:21 UTC, DanielRosenwasser commented on README.fil.md
> +  // Mga Paglalarawan ni: Alice <https://github.com/alice>
This needs to be left with the old text for contributors

2018-04-14 19:31 UTC, mhegazy commented
Thanks for your contribution. This PR has unaddressed comments and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2018-04-14 19:31 UTC, closed without merging