make graphql typing for getDescription conform with graphql-js
DefinitelyTyped/DefinitelyTyped pull request #24169
Opened 2018-03-09 08:19 UTC by divyenduz

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/graphql/graphql-js/blob/master/src/utilities/buildASTSchema.js#L465, https://github.com/graphql/graphql-js/pull/1165
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-03-09 21:03 UTC, alessiodionisi requested changes
My advice is to preserve the original structure so it would be useful to create and export type `GraphQLSchemaValidationOptions` in `../type/schema.d.ts` (like https://github.com/graphql/graphql-js/blob/master/src/type/schema.js#L233) and extend in `BuildSchemaOptions` (like https://github.com/graphql/graphql-js/blob/master/src/utilities/buildASTSchema.js#L76).

2018-03-09 21:16 UTC, IvanGoncharov commented on types/graphql/utilities/buildASTSchema.d.ts
> +  ): string;
Please use two spaces as indentation to be consistent with `graphql-js`.

2018-03-09 21:16 UTC, IvanGoncharov commented on types/graphql/utilities/buildASTSchema.d.ts
>   */
Also updated comment to keep it in sync with graphql-js:
https://github.com/graphql/graphql-js/blob/master/src/utilities/buildASTSchema.js#L456-L464

2018-03-10 09:05 UTC, divyenduz commented
Thanks for the feedback @adnsio, @IvanGoncharov! 

I have made the requested changes. Please let me know if any further changes are needed.

2018-03-10 09:11 UTC, IvanGoncharov approved these changes

2018-03-10 16:03 UTC, alessiodionisi approved these changes

2018-03-15 19:36 UTC, merged