Added tlds types
DefinitelyTyped/DefinitelyTyped pull request #24262
Opened 2018-03-13 15:06 UTC by ajshres

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-03-21 09:27 UTC, plantain-00 requested changes

2018-03-21 09:27 UTC, plantain-00 commented on types/tlds/tsconfig.json
> +        "strictNullChecks": false,
For new packages, it should be enabled

2018-03-21 09:27 UTC, plantain-00 commented on types/tlds/tslint.json
> +        "no-empty-interface": false,
For new packages, this file should only `"extends": "dtslint/dt.json"`, you can disable some rules in source code like `// tslint:disable-next-line no-empty-interface`

2018-04-09 19:04 UTC, mhegazy commented
Thanks for your contribution. This PR has unaddressed comments and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2018-04-09 19:04 UTC, closed without merging