Added type definitions for Naver maps
DefinitelyTyped/DefinitelyTyped pull request #24303
Opened 2018-03-15 06:35 UTC by ckboyjiy

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-03-15 13:09 UTC, plantain-00 requested changes

2018-03-15 13:09 UTC, plantain-00 commented on navermaps/tslint.json
> +    "rules": {
For new packages, this file should only `"extends": "dtslint/dt.json"`

2018-03-15 13:09 UTC, plantain-00 commented on navermaps/index.d.ts
> +// Project: https://navermaps.github.io
The link seems broken

2018-03-23 22:37 UTC, minestarks requested changes
All typings need to go under the `/types` path. Please don't add files to the root.  Please see [README](https://github.com/DefinitelyTyped/DefinitelyTyped#readme)

2018-03-24 22:39 UTC, plantain-00 approved these changes

2018-03-26 19:25 UTC, merged