[is-empty] add types
DefinitelyTyped/DefinitelyTyped pull request #24364
Opened 2018-03-18 16:31 UTC by termosa

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-03-19 05:43 UTC, plantain-00 approved these changes

2018-03-21 07:21 UTC, termosa commented
The author of the library rejected to merge types into the repository, so DefinitelyTyped is the only option: https://github.com/ianstormtaylor/is-empty/pull/15#issuecomment-374791141

2018-03-23 21:28 UTC, minestarks requested changes

2018-03-23 21:28 UTC, minestarks commented on types/is-empty/index.d.ts
> +export default isEmpty;
`export = isEmpty` is more accurate based on the implementation at https://github.com/ianstormtaylor/is-empty/blob/master/lib/index.js

Corresponding import statement would be `import isEmpty = require('is-empty')`

2018-03-26 18:24 UTC, merged