Created Glue project
DefinitelyTyped/DefinitelyTyped pull request #24411
Opened 2018-03-20 17:05 UTC by garfty

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not provide its own types, and you can not add them.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-03-21 09:25 UTC, plantain-00 requested changes

2018-03-21 09:25 UTC, plantain-00 commented on glue/tsconfig.json
> +    "strictFunctionTypes": false,
For new packages, this should be enabled

2018-03-21 09:25 UTC, plantain-00 commented on glue/tslint.json
> +      "ban-types": false
for new packages, this file should only `"extends": "dtslint/dt.json"`, you can disable some rules in source code like `// tslint:disable-next-line ban-types`

2018-03-21 10:29 UTC, plantain-00 approved these changes

2018-03-22 20:26 UTC, garfty commented
Hi @minestarks my account is connected, not sure what happened but anything I can do to help I will 👍

2018-03-22 21:01 UTC, minestarks commented
Oh hey, Travis is back! 

@garfty thanks, I'll merge once the tests pass.

2018-03-22 21:17 UTC, merged

2018-03-23 22:50 UTC, minestarks commented
@garfty  uh oh, I missed this: All typings need to go under the `/types` path. Please don't add files to the root.  

I merged this already but would you mind opening a new PR moving these to the `types` subdirectory? They won't be published to `@types` as long as they're in here.

2018-03-24 06:19 UTC, garfty commented
Hi @minestarks Apologies for this, I was wondering about it. I've now done this and a new PR is open [https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24500](here).