Integer for tabIndex produces type error for react types.
DefinitelyTyped/DefinitelyTyped pull request #24616
Opened 2018-03-29 18:11 UTC by smithywick

When using tabIndex="0" I'm getting a type error for a string. When using tabIndex=0 I'm getting a type error for a boolean.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not provide its own types, and you can not add them.
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v15/index.d.ts#L2415
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-03-31 21:31 UTC, AviVahl commented
Why not use `tabIndex={0}`?

2018-04-03 19:58 UTC, paulvanbrenk requested changes
Please add a test to ensure this doesn't get reverted.

2018-04-04 17:35 UTC, AviVahl commented
But shouldn't this always be a number? He just used invalid JSX syntax and got an error. I don't see this as valid reasoning to convert this to string, do you?

2018-04-04 17:41 UTC, paulvanbrenk commented
@AviVahl I wasn't sure what he meant, I hoped a sample/test case would clarify.

2018-04-14 19:36 UTC, mhegazy commented
Thanks for your contribution. This PR has unaddressed comments and can not be merged in at the time being. For housekeeping purposes we are closing stale PRs. If you'd still like to merge this code in, please open a new PR that has been merged and rebased with the `master` branch.

2018-04-14 19:36 UTC, closed without merging