[hapi] Fix: Make  ServerInjectOptions.app optional
DefinitelyTyped/DefinitelyTyped pull request #24628
Opened 2018-03-30 06:48 UTC by dcharbonnier

Revert a change made on : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/24341
This change had noting to do with the PR and does not align to the documentation few lines above.

2018-03-30 06:59 UTC, ozum requested changes
Providing options.app is optional, but if you do not provide any value to options.app, it has a default value of `{}`. As a result it is always defined.

If that's not the case, could you please elaborate.

2018-03-30 07:14 UTC, dcharbonnier commented
In this case, open a PR on the hapi repository to correct the documentation, when the PR on hapi is accepted and merged back to the type repository, correct the type and the documentation.
Right now we have an inconsistency between the documentation and the type definition and I don't think the documentation is the problem.
Example : `server.inject( {  url:"http://example.com});` is supposed to be correct and it's not anymore.
https://github.com/dcharbonnier/DefinitelyTyped/blob/204e0d396a0bb36c0f1b4b34ad0c939f94bbc273/types/hapi/index.d.ts#L3616

This type is only used as a function parameter so I don't see your point, maybe if it was accessible somewhere else it could be split in 2 different interfaces but it's not the case for **ServerInjectOptions**, I'm not speaking about your PR that's an other topic

2018-03-30 07:26 UTC, ozum commented
I examined docs and code again. Hapi Doc is correct and you are right, I confused your comment with
* [line 3260](https://github.com/dcharbonnier/DefinitelyTyped/blob/204e0d396a0bb36c0f1b4b34ad0c939f94bbc273/types/hapi/index.d.ts#L3260)

My PR was fixing a bug, but added a new one, and this PR will fixed that one.

2018-03-30 07:27 UTC, ozum approved these changes

2018-03-30 07:27 UTC, dcharbonnier commented
thx @ozum

2018-03-30 07:54 UTC, dcharbonnier commented
@ozum there is still the "Revision needed" label, maybe you need to cancel your request for change.

2018-03-31 17:46 UTC, jhsimms approved these changes

2018-04-03 18:11 UTC, merged