Replace express req.params 'any' type with index types (Revive #17610)
DefinitelyTyped/DefinitelyTyped pull request #24648
Opened 2018-03-31 00:19 UTC by felipeochoa

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: #17610
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-03-31 00:24 UTC, cyrilschumacher approved these changes

2018-03-31 00:25 UTC, dolanmiu approved these changes

2018-03-31 00:25 UTC, dolanmiu commented
Good work

2018-03-31 04:11 UTC, erikmav approved these changes
One small formatting issue otherwise LGTM

2018-03-31 04:11 UTC, erikma commented on types/express/express-tests.ts
> +}
Unneeded unindent in this block

2018-03-31 07:52 UTC, MichalLytek requested changes
I'm afraid we will se this again:
> This is breaking my app's build, which uses Typescript 2.2.2

@mhegazy can we safely bump all deps to TS 2.3?

2018-03-31 10:05 UTC, 0x6368656174 approved these changes

2018-04-02 08:36 UTC, kvcpr approved these changes

2018-04-02 14:35 UTC, pinguet62 approved these changes

2018-04-18 00:57 UTC, closed without merging