winston: add 'all', 'level' and	'message' as valid colorize values.
DefinitelyTyped/DefinitelyTyped pull request #24663
Opened 2018-04-01 02:25 UTC by blair

Supports https://github.com/winstonjs/winston/commit/72273b1 .

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/winstonjs/winston/commit/72273b1
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-04-01 05:35 UTC, DABH approved these changes
Fair enough, I do see this in https://github.com/winstonjs/winston/blob/2.x/lib/winston/common.js !  Thank you for your contribution!  Approved.

2018-04-03 18:21 UTC, paulvanbrenk requested changes

2018-04-03 18:30 UTC, blair commented on types/winston/index.d.ts
> +        colorize: boolean | 'all' | 'level' | 'message';
I looked at doing that, however, the style in the file is to duplicate the union types everywhere. Can you let me know if you still want this change or will submit as is?

2018-04-03 18:32 UTC, paulvanbrenk commented on types/winston/index.d.ts
> +        colorize: boolean | 'all' | 'level' | 'message';
In that case it's _ok_, in a perfect world someone would fix them all.... but I'll merge this PR.

2018-04-03 18:32 UTC, paulvanbrenk approved these changes

2018-04-03 18:32 UTC, merged