(react-native) Added listKey prop to VirtualizedListProperties
DefinitelyTyped/DefinitelyTyped pull request #24954
Opened 2018-04-12 15:38 UTC by nicomontanari98

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

2018-04-12 16:17 UTC, alloy requested changes
Can you please provide a link to the documentation/flow type? And the CI is red due to whitespace https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/365675073#L3246

2018-04-13 09:13 UTC, nicomontanari98 commented
@alloy You can find listKey here [VirtualizedList.js](https://github.com/facebook/react-native/blob/master/Libraries/Lists/VirtualizedList.js) line 138

2018-04-13 10:58 UTC, iRoachie approved these changes

2018-04-13 14:54 UTC, alloy approved these changes

2018-04-13 14:54 UTC, merged