firefox-webext-browser: remove bookmark.import/export
DefinitelyTyped/DefinitelyTyped pull request #25044
Opened 2018-04-16 20:48 UTC by Alexendoo

They aren't used by any browser and break the bookmarks namespace (no other properties are accessible on completion)

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/bookmarks
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-04-24 23:54 UTC, weswigham commented
> They ... break the bookmarks namespace (no other properties are accessible on completion)

That's because the other namespace members need `export` modifiers once there's an `export` declaration in-scope. It's a quirk of declaration file scoping - `export` gets implicitly applied to everything in a declared namespace unless there's an `export` declaration present, as which point only explicitly `export`ed things are `export`ed.

Do you want to keep them around and just fix the namespace? Or is the lack of them being in browsers the main driver?

2018-04-24 23:54 UTC, weswigham requested changes
> They ... break the bookmarks namespace (no other properties are accessible on completion)

That's because the other namespace members need `export` modifiers once there's an `export` declaration in-scope. It's a quirk of declaration file scoping - `export` gets implicitly applied to everything in a declared namespace unless there's an `export` declaration present, as which point only explicitly `export`ed things are `export`ed.

Do you want to keep them around and just fix the namespace? Or is the lack of them being in browsers the main driver?

2018-05-01 11:05 UTC, Alexendoo commented
@weswigham I would still remove them personally. I think it would be confusing for people to come across since they aren't documented anywhere

2018-05-02 01:29 UTC, weswigham commented
Bot pls.

2018-05-02 01:29 UTC, weswigham approved these changes

2018-05-07 18:38 UTC, merged