Add INgModelController to IDirectiveLinkFn Controller (#19933)
DefinitelyTyped/DefinitelyTyped pull request #25070
Opened 2018-04-17 18:36 UTC by drawyan

Allow `IDirectiveLinkFn` controller type to be `INgModelController`.

Fixes: Issue #19933

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/19933

2018-04-17 21:03 UTC, thorn0 requested changes
Sorry, this change cannot be accepted.

This argument can be a controller of any type, which depends on the `require` [property of the directive definition object](https://docs.angularjs.org/api/ng/service/$compile#-require-). Even if this change happened, a type assertion still would be needed. So what is the point?

2018-04-17 21:12 UTC, thorn0 commented
Now we have to write code like this:
```ts
module.directive('foo', () => {
    return {
        require: 'ngModel',
        link($scope, $element, $attrs, ctrl) {
            const ngModel = ctrl as ng.INgModelController;
            // ...
        }
    };
};
```
With the proposed change, this code would look absolutely the same. It cannot be improved this way.

2018-04-17 21:16 UTC, drawyan commented
@th0br0 The current `ng.IDirective` cannot be applied to the return type of the function that returns the definition of an angular directive. For example:
```
export default function someDirective($filter): ng.IDirective {
  return {
    require: 'ngModel',
    restrict: 'A',
    link(scope, element, attrs, ngModelController) {
      ngModelController.$formatters.unshift(() => $filter('number')(ngModelController.$modelValue));
    },
  };
}
```
This will have a type error because `ngModelController` isn't of type `IController`, it is instead `INgModelController`.

And with this change, it should eliminate the cast I believe.
`const ngModel = ctrl as ng.INgModelController;`

2018-04-17 21:18 UTC, drawyan commented
Or `INgModelController ` should implement `IController`, if this is a better solution.

2018-04-17 22:02 UTC, drawyan commented
Never mind, @thorn0 you are correct, we'll still have to do the casting. And forcing `INgModelController` to extend `IController` also requires a down casting for the type.

Thanks for the explanation, I'll abandon this PR

2018-04-17 22:02 UTC, closed without merging

2020-05-29 13:27 UTC, tommck commented
@thorn0 - it is not structurally the same though