Update `klaw-sync` module interface from v1.0 to v2.0.0 +
DefinitelyTyped/DefinitelyTyped pull request #25134
Opened 2018-04-19 18:05 UTC by luozhihua

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/manidlou/node-klaw-sync/blob/v2.0.0/CHANGELOG.md>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-04-19 20:04 UTC, shiftkey requested changes

2018-04-19 20:04 UTC, shiftkey commented on types/klaw-sync/index.d.ts
> +// Type definitions for klaw-sync 3.0
Does this need to go up to `3.0`? Can it stay on `2.0` to be in sync with the version of the dependency project?

2018-04-19 20:04 UTC, shiftkey commented on types/klaw-sync/index.d.ts
> +        ignore?: string | string[]
If this has been deprecated in `2.0` then I'd just remove the parameter so that it's clear what's currently supported.

2018-04-19 20:05 UTC, shiftkey commented on types/klaw-sync/klaw-sync-tests.ts
> +const optionsV2 = {
I'd just refresh the old `options` hash above to reflect what's currently supported.

2018-04-20 17:13 UTC, shiftkey commented on types/klaw-sync/index.d.ts
> +        ignore?: string | string[]
Let's focus on the v2 changes here, it seems like v3 is a smoother upgrade that we can follow up with later.

2018-04-20 17:51 UTC, shiftkey requested changes
One more bit of tidy up!

2018-04-20 17:51 UTC, shiftkey commented on types/klaw-sync/klaw-sync-tests.ts
> +    filter(item: any) {
You can specify `item: klawSync.item` here instead of `item: any`

2018-04-21 08:05 UTC, luozhihua commented
@shiftkey Thanks for help me, this is my first PR of DefinitelyTyped, your reviews is so helped.

2018-04-21 22:55 UTC, shiftkey commented
@luozhihua you're welcome!

> this is my first PR of DefinitelyTyped, your reviews is so helped.

If you'd like to help with future reviews, add your name and GitHub alias below mine, like this:

```tsx
// Definitions by: Brendan Forster <https://github.com/shiftkey>
// Definitions by: Colin Luo <https://github.com/luozhihua>
```

I'm no longer reliant on `klawSync`, and it seems like you're more across the details than myself!

2018-04-22 16:04 UTC, shiftkey approved these changes

2018-04-22 16:05 UTC, shiftkey commented on types/klaw-sync/index.d.ts
> -// Definitions by: Colin Luo <https://github.com/luozhihua>
😢

2018-04-24 23:05 UTC, merged