Add namespace to highcharts/highcharts-more.d.ts
DefinitelyTyped/DefinitelyTyped pull request #25132
Opened 2018-04-19 15:39 UTC by DaemonExMachina

This file was making it impossible to import from the actual
highcharts-more file. As it's not an ES6 native module, we have to
import it with:

    import * as HighchartsMore from 'highcharts/highcharts-more';

This is the same as the Highcharts object itself. However, because the
highcharts-more.d.ts file does not include a namespace declaration
(instead declaring a function and exporting it `as namespace
HighchartsMore`), this import syntax causes a tsc error:

> Error:(4, 45) TS2497: Module '.../highcharts-more' resolves to a
non-module entity and cannot be imported using this construct.

I have updated the file to properly declare and export a namespace in
the same way as other such files.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-04-19 17:15 UTC, hanssens approved these changes

2018-04-19 18:03 UTC, RyanCavanaugh requested changes
This PR is incorrect. **You cannot import a function into an ES6 module using `import *`**; we do not accept new PRs to add a workaround to enable broken behavior.

2018-04-19 18:03 UTC, RyanCavanaugh commented
Classes and functions cannot be imported using `import * as` syntax. Please fix either the test or the definition file to use a correct import form.

See also https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this

2018-04-20 08:05 UTC, DaemonExMachina commented
Hi Ryan. Thanks for the link, and for (presumably quite deliberately) creating that question-and-answer combo in the first place. Just goes to show, even when you think you know what you're talking about, there's always something new to learn. That syntax is definitely peculiar-looking, but it's good to know it exists.

So I guess I should just completely close this PR. Reverting my change in my local environment and using the `import = require` syntax does indeed work for me, making this change completely pointless!

2018-04-20 08:05 UTC, closed without merging