moment-timezone: Fix type: .tz() can also return undefined as per the docs
DefinitelyTyped/DefinitelyTyped pull request #25288
Opened 2018-04-25 09:43 UTC by woutervh-

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://momentjs.com/timezone/docs/#/using-timezones/converting-to-zone/
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-04-26 20:36 UTC, alanblins reviewed
I agree. It is according to docs. I would suggest add some changes in moment-timezone-tests.ts as well.

2018-04-26 20:48 UTC, alanblins requested changes
It would be better to add this change in moment-timezone-tests.ts as well in order to test.

2018-04-27 18:30 UTC, woutervh- commented
Hi  @alanblins. I wasn't sure how to add tests for type module, but I've added a test that I think should do it.

2018-05-21 00:13 UTC, alanblins approved these changes

2018-05-23 15:49 UTC, merged