[ember-data] - improve relationship options
DefinitelyTyped/DefinitelyTyped pull request #25282
Opened 2018-04-25 07:26 UTC by jamescdavis

* `allowNull` is needed for the [BooleanTransform](https://emberjs.com/api/ember-data/3.0/classes/DS.BooleanTransform) (could be restricted once we can use TS 2.8)
* moving the relationship options to an interface DRYs up the code and makes them accessible externally on the DS namespace

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://emberjs.com/api/ember-data/3.0/classes/DS.BooleanTransform
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-04-25 14:36 UTC, mike-north requested changes
I'd like to use this in an app before approving for merge. Please give me 48h to test it out.

I'm only marking as "request changes" so the bot won't automatically merge (yet).

2018-04-26 12:54 UTC, jamescdavis commented
@mike-north of course! Appreciate the thorough testing!

2018-04-30 12:28 UTC, mike-north approved these changes

2018-04-30 12:29 UTC, mike-north commented
This appears to work nicely with a non-trivial TS/Ember app. Thanks for the good work @jamescdavis

2018-05-07 17:45 UTC, merged