fix(unzipper): update promise and buffer to be functions, not properties
DefinitelyTyped/DefinitelyTyped pull request #25685
Opened 2018-05-10 19:38 UTC by natemara

Entry.buffer and Parse.promise were incorrectly labeled as properties, but they are functions. This can be verified by looking at the source code that I have linked below.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
    - https://github.com/ZJONSSON/node-unzipper/blob/master/lib/parse.js#L240
    - https://github.com/ZJONSSON/node-unzipper/blob/master/lib/parse.js#L89

2018-05-10 19:41 UTC, natemara commented
@s73obrien, does this look good to you?

2018-05-11 00:51 UTC, s73obrien requested changes
Great catch!

Can I get you to lint and re-commit?

Thank You!

2018-05-11 13:08 UTC, natemara commented
@s73obrien I did run `npm run lint unzipper`, and it passes without problem except in TS 2.1, which is why I added the Typescript Version 2.2 line. Is there something else that I need to do?

2018-05-11 21:17 UTC, s73obrien approved these changes
No no, it's all good.  Sorry for the hold-up.  Thanks again!

2018-05-11 22:01 UTC, merged