[Plotly.js] Added missing hoverinfo type permutations for
DefinitelyTyped/DefinitelyTyped pull request #25877
Opened 2018-05-18 18:38 UTC by MercifulCode

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://plot.ly/javascript/reference/#scattergl-hoverinfo>>
- [x] Increase the version number in the header if appropriate.

2018-05-19 11:01 UTC, martinduparc approved these changes

2018-05-19 20:53 UTC, kvcpr approved these changes

2018-05-21 03:47 UTC, taoqf requested changes

2018-05-21 03:47 UTC, taoqf commented on types/plotly.js/index.d.ts
> +    hoverinfo: 'all' | 'none' | 'skip' |
Missing `text`, `name`,`all`, `none`

2018-05-22 03:47 UTC, taoqf approved these changes

2018-05-24 05:54 UTC, merged