Add typings for just-extend.
DefinitelyTyped/DefinitelyTyped pull request #25894
Opened 2018-05-20 08:32 UTC by pe8ter

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-05-20 17:07 UTC, pe8ter commented
I re-read the source code for this library and discovered that my typings weren't quite correct. I squashed history and force pushed.

2018-05-22 04:43 UTC, DanielRosenwasser requested changes

2018-05-22 04:43 UTC, DanielRosenwasser commented on types/just-extend/index.d.ts
> +declare namespace extend {}
This is an inappropriate hack. [Please read more here from the DefinitelyTyped REAMDE](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/fbba9f55beab742b9d1c0fa9ef714e0771ad9d05#should-i-add-an-empty-namespace-to-a-package-that-doesnt-export-a-module-to-use-es6-style-imports)

Additionally, test files should ideally use the `import Foo = require("foo")` style syntax.

2018-05-24 05:45 UTC, DanielRosenwasser commented on types/just-extend/index.d.ts
> +declare namespace extend {}
CC @RyanCavanaugh

2018-05-24 05:45 UTC, DanielRosenwasser approved these changes

2018-05-24 05:45 UTC, merged