kendo-ui: CalendarOptions.footer should allow boolean as well
DefinitelyTyped/DefinitelyTyped pull request #25996
Opened 2018-05-24 09:06 UTC by msmolka

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.

kendo-ui CalendarOptions.footer should allow boolean as well.
Based on docs: 

> The template which renders the footer. If false, the footer will not be rendered.
https://docs.telerik.com/kendo-ui/api/javascript/ui/calendar/configuration/footer

- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://docs.telerik.com/kendo-ui/api/javascript/ui/calendar/configuration/footer>>

2018-06-01 03:51 UTC, uniqueiniquity requested changes

2018-06-01 03:51 UTC, uniqueiniquity commented on types/kendo-ui/index.d.ts
> +        footer?: boolean|string|Function;
Might as well make the type `false | string | Function` so that `true` isn't allowed accidentally.

2018-06-04 07:45 UTC, msmolka commented
@uniqueiniquity : done

2018-06-04 15:33 UTC, uniqueiniquity approved these changes

2018-06-04 15:34 UTC, merged