[node] Update net.Server ListenOptions
DefinitelyTyped/DefinitelyTyped pull request #26115
Opened 2018-05-29 19:09 UTC by mantyz

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://nodejs.org/dist/latest-v10.x/docs/api/net.html#net_server_listen_options_callback>>

2018-05-29 19:42 UTC, Flarna requested changes
Please update the version (first line in file) to 10.3.x as these properties have been added in 10.3.0.

2018-05-29 19:59 UTC, mantyz commented
Version updated.

2018-05-29 20:48 UTC, Flarna approved these changes

2018-05-30 06:28 UTC, BrunoScheufler approved these changes
Great work, LGTM 👍

2018-05-31 17:18 UTC, merged