JSforce: Add proper types for describe calls
DefinitelyTyped/DefinitelyTyped pull request #26153
Opened 2018-05-30 19:32 UTC by WhiteAbeLincoln

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://jsforce.github.io/document/#describe>><<https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_describeglobal_describeglobalresult.htm#!>> <<https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_describesobjects_describesobjectresult.htm#!>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Adds types for the caching versions of Connection.describe, Connection.describeGlobal, SObject.describe, SObject.layouts, SObject.compactLayouts, and SObject.approvalLayouts.

Documentation for these caching versions can be found at [jsforce](https://jsforce.github.io/document/#describe) under 'Cached Call'. The jsdoc doesn't list these calls, but they can be found [in source](http://jsforce.github.io/jsforce/doc/connection.js.html#line150)

Also removes a describeGlobal method definition from the SObject class that doesn't exist in the jsforce code or documentation.

Adds types for the result of Connection.describe() and Connection.describeGlobal(). 

The types were pulled from the official salesforce documentation for the describe() and describeGlobal() soap api calls (see [DescribeGlobalResult](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_describeglobal_describeglobalresult.htm#!) and [DescribeSObjectResult](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_describesobjects_describesobjectresult.htm#!) ) as well as real-world types constructed by looking at the result calling of describeGlobal() and describe() for about 486 salesforce objects.

This was done by running [quicktype](https://quicktype.io/) and [maketypes](http://jvilk.com/MakeTypes/) on the JSON result of describeGlobal() and SObject.describe() for every object in a salesforce sandbox instance.

2018-06-01 17:20 UTC, dolanmiu approved these changes

2018-06-01 22:11 UTC, uniqueiniquity requested changes

2018-06-01 22:11 UTC, uniqueiniquity commented on types/jsforce/connection.d.ts
> +        <T>(callback?: (err: Error, result: DescribeGlobalResult) => void): DescribeGlobalResult;
Please remove the type parameter `<T>` here and on line 117 if it is unused.

2018-06-05 16:22 UTC, WhiteAbeLincoln commented
I've removed the unused type parameters. Thanks!

2018-06-05 17:04 UTC, uniqueiniquity approved these changes

2018-06-05 17:04 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2018-06-05 17:05 UTC, merged