#26284 [Expo] Add v 27.0.0 docs
DefinitelyTyped/DefinitelyTyped pull request #26324
Opened 2018-06-06 12:35 UTC by moshfeu

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://docs.expo.io/versions/v27.0.0/>>
- [ ] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-06-06 20:32 UTC, armanio123 commented
Seems like the typescript-bot got confused and didn't mentioned the type owners for review. @KonstantinKai @martynaskadisa @janaagaard75 @ssanchezmarc @fhelwanger @umidbekkarimov Could any of you please do a review and let me know if it's good for merge?

2018-06-07 07:54 UTC, KonstantinKai requested changes
@moshfeu, thanks a lot for contribution. But, I found a few inconsistencies with the original source.
https://github.com/expo/expo-sdk/blob/191eeffb934c84ffb7e05dd1c5616282dccaff23/src/MediaLibrary.js
https://github.com/expo/expo-sdk/blob/191eeffb934c84ffb7e05dd1c5616282dccaff23/src/Haptic.js

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +  function notification(type: NotificationFeedbackType): void;
`type` argument is optional -> https://github.com/expo/expo-sdk/blob/191eeffb934c84ffb7e05dd1c5616282dccaff23/src/Haptic.js#L68

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +  function impact(style: ImpactFeedbackStyle): void;
`style` argument is also optional -> https://github.com/expo/expo-sdk/blob/191eeffb934c84ffb7e05dd1c5616282dccaff23/src/Haptic.js#L80

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +  enum ImpactFeedbackStyle {
https://github.com/expo/expo-sdk/blob/191eeffb934c84ffb7e05dd1c5616282dccaff23/src/Haptic.js#L40
I think, preferably, need to export enum with `ImpactStyles` name, instead `ImpactFeedbackStyle`. And use this enum like arg type in the method above.

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +  enum NotificationFeedbackType {
https://github.com/expo/expo-sdk/blob/191eeffb934c84ffb7e05dd1c5616282dccaff23/src/Haptic.js#L29
Similar to the previous comment.

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +    mediaSubtypes: MediaType[];
Optional prop.

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +    albumId: string;
Optional prop

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +    localUri: string;
Optional prop

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +    location: object;
Optional prop with type Location.LocationProps

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +    exif: object;
Optional prop

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +    type: string;
Optional prop

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +    locationNames: string[];
Optional prop

2018-06-07 07:54 UTC, KonstantinKai commented on types/expo/index.d.ts
> +    approximateLocation: Location.LocationProps;
Optional prop

2018-06-07 08:53 UTC, KonstantinKai requested changes
@moshfeu, please make changes according to the source.

2018-06-07 08:59 UTC, moshfeu commented
@KonstantinKai I pushed a fix commit for all of your good comments. Can you take a look? 
Thanks!

2018-06-07 09:03 UTC, KonstantinKai approved these changes
@moshfeu looks good. Approved. 👍

2018-06-07 09:05 UTC, moshfeu commented
@KonstantinKai Thanks!

2018-06-07 19:46 UTC, merged