Updated tsjson as per last comment.
DefinitelyTyped/DefinitelyTyped pull request #26367
Opened 2018-06-08 04:36 UTC by ajshres

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-06-10 23:27 UTC, plantain-00 approved these changes

2018-06-19 22:50 UTC, sandersn requested changes

2018-06-19 22:50 UTC, sandersn commented on types/tlds/index.d.ts
> +export const tlds: string[];
Looking at the source of node-tlds, it's a commonjs export, which means it needs to be exported with `export =` like so

```ts
declare const tlds: string[];
export = tlds
```

and imported with `import tlds = require('tlds')`

2018-06-20 08:34 UTC, ajshres commented
@sandersn : I have done the changes as per requested. Could you send me some reference so I could be sure what might be a good definition syntax for similar situations?

2018-06-20 15:07 UTC, sandersn approved these changes

2018-06-20 15:09 UTC, sandersn commented
These two links are relevant, I think. The first is just a summary but the second has lots of detail. 
* https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default
* http://www.typescriptlang.org/docs/handbook/modules.html

2018-06-20 15:09 UTC, merged