[react-native] Add viewabilityConfigCallbackPairs property to scrollView
DefinitelyTyped/DefinitelyTyped pull request #26441
Opened 2018-06-11 13:24 UTC by reddor

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://facebook.github.io/react-native/docs/next/virtualizedlist.html#viewabilityconfigcallbackpairs>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Some more context:
The added property has been part of VirtualizedList/FlatList since 0.5 and is basically an extension to the viewabilityConfig propery which is already part of the typed declarations.

2018-06-11 17:14 UTC, iRoachie commented on types/react-native/index.d.ts
> +    viewabilityConfigCallbackPairs?: ViewabilityConfigCallbackPairs;
Any reason you just didn't use `ViewabilityConfigCallbackPairs[]`, instead of making a ViewabilityConfigCallbackPairs type?

2018-06-18 09:42 UTC, alloy requested changes
@reddor Please see @iRoachie’s question.

(Marking this as a request for changes, because the bot seems to think that no review has been done.)

2018-06-24 12:48 UTC, alloy commented
@iRoachie What do you wanna do here?

2018-06-24 13:32 UTC, iRoachie commented
It's trivial I guess, merge

2018-06-24 13:51 UTC, alloy commented
Okeydokey 👍

2018-06-24 13:51 UTC, alloy approved these changes

2018-06-24 13:51 UTC, merged