Added type definitions for emoji-regex
DefinitelyTyped/DefinitelyTyped pull request #26475
Opened 2018-06-12 08:44 UTC by iKBAHT

Added type definitions for [emoji-regex](https://github.com/mathiasbynens/emoji-regex).

2018-06-13 00:10 UTC, plantain-00 requested changes

2018-06-13 00:10 UTC, plantain-00 commented on types/emoji-regex/index.d.ts
> +// Project: https://mths.be/emoji-regex
Use its github url is better: https://github.com/mathiasbynens/emoji-regex

2018-06-13 00:10 UTC, plantain-00 commented on types/emoji-regex/index.d.ts
> +export default createRegExp;
It should be `export = createRegExp ` https://github.com/mathiasbynens/emoji-regex/blob/master/src/index.js#L1

2018-06-18 23:26 UTC, plantain-00 approved these changes

2018-06-20 19:49 UTC, merged

2018-06-20 19:49 UTC, sandersn commented
Thanks for your contribution @iKBAHT!