mongodb Update generic type of Cursor.map
DefinitelyTyped/DefinitelyTyped pull request #26505
Opened 2018-06-13 00:25 UTC by dobesv

The output type of the contents of the Cursor should match the return type of the mapping function.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15991

2018-06-13 19:38 UTC, julien-c approved these changes

2018-06-13 19:39 UTC, julien-c requested changes

2018-06-13 19:39 UTC, julien-c commented on types/mongodb/index.d.ts
> +    map<U>(transform: (T) => U ): Cursor<U>;
please remove the extra space after `U`

2018-06-13 19:54 UTC, CaselIT approved these changes

2018-06-13 19:55 UTC, CaselIT commented
The original issue referenced version 2. This will only change the types for version 3.
Maybe it can also be backported?

2018-06-13 23:10 UTC, dobesv commented on types/mongodb/index.d.ts
> +    map<U>(transform: (T) => U ): Cursor<U>;
Good catch!  I removed it.

2018-06-13 23:39 UTC, julien-c approved these changes

2018-06-14 08:50 UTC, CaselIT approved these changes

2018-06-15 18:15 UTC, merged