[signature_pad] Make @types/signature_pad compatible with Typescript 2.8
DefinitelyTyped/DefinitelyTyped pull request #26573
Opened 2018-06-15 03:42 UTC by leejaedus

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-06-18 13:02 UTC, jrmihalick approved these changes

2018-06-18 18:03 UTC, sandersn requested changes

2018-06-18 18:03 UTC, sandersn commented on types/signature_pad/index.d.ts
> +declare module 'signature_pad' {
This is not the 2.x way of making a UMD module. The easiest way is actually to keep the old structure with `declare namespace SignaturePad` and then at the end add:

```ts
declare namespace SignaturePad {
  // ... original structure ...
}
export default SignaturePad
export as namespace SignaturePad
```

The new `export as namespace` syntax implements UMD by creating a global namespace named SignaturePad, but only in non-module-using programs.

2018-06-24 03:40 UTC, leejaedus commented
Thanks for the review! @sandersn

I fixed that points. and I re-add some type defs

2018-06-25 15:22 UTC, sandersn approved these changes

2018-06-25 15:23 UTC, merged