new-relic-browser: Export api and fix doc
DefinitelyTyped/DefinitelyTyped pull request #26590
Opened 2018-06-15 19:17 UTC by cscleison

api was not exporting anything. changed to be consistent with newrelic types

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2039466749e8dc995251df2624cfa4a38f6c0168/types/newrelic/index.d.ts#L350

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

2018-06-16 11:02 UTC, piotrkubisa approved these changes
LGTM

2018-06-18 20:15 UTC, sandersn commented on types/new-relic-browser/new-relic-browser-tests.ts
> +import * as newrelic from "new-relic-browser";
Since this now uses a commonjs-style `export =`, the import should match: `import newrelic = require("new-relic-browser")`

2018-06-18 20:16 UTC, sandersn requested changes
Please use `import newrelic = require("new-relic-browser")`

2018-06-19 11:53 UTC, cscleison commented
done

2018-06-19 13:53 UTC, merged

2019-02-25 17:14 UTC, vmasek commented
Is there any way to import this via the ES6 style imports?

I'm trying to get this typedef into the Angular project and I'm struggling a bit.

What I'm trying to achieve is:
```
import NewRelic = require('new-relic-browser');

declare global {
  interface Window {
    NREUM: NewRelic.Browser;
  }
}
```
But neighter of the imports (es6 or require) work for me.