Missing definition for `dns.resolveAny` and `dns.resolve(domain, 'ANY')` in `@types/node`
DefinitelyTyped/DefinitelyTyped pull request #26613
Opened 2018-06-17 11:17 UTC by ZaneHannanAU

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <https://nodejs.org/docs/latest/api/dns.html#dns_dns_resolveany_hostname_callback> <https://nodejs.org/docs/latest/api/dns.html#dns_dns_resolve_hostname_rrtype_callback>

done late in the evening only trying to follow the style around the definitions.

Should probably be sorted at least.

2018-06-17 11:24 UTC, BrunoScheufler approved these changes

2018-06-17 11:56 UTC, BrunoScheufler approved these changes
LGTM 🎉

2018-06-17 12:06 UTC, ZaneHannanAU commented
Cool.

2018-06-17 12:26 UTC, islishude requested changes
Please add tests for new adding.

2018-06-17 13:20 UTC, ZaneHannanAU commented
On mobile ATM; I'll do what I can

```typescript
 dns.resolve("nodejs.org", "ANY", (err, addresses) => {
    const _addresses: ReadonlyArray<...Any*Record> = addresses;
});
dns.resolveAny("nodejs.org", (err, addresses) => {
    const _addresses: ReadonlyArray<...Any*Record> = addresses;
});
```
though the full record stack is giant.

Do you have a good way of saying one value is one of many types like the binary or in ts? The one that lets you `Array | Set` and so on?

Thank you.

2018-06-18 01:49 UTC, ZaneHannanAU commented
I actually made a spelling mistake...

2018-06-18 02:52 UTC, islishude approved these changes

2018-06-18 02:57 UTC, ZaneHannanAU commented
Thank you.

2018-06-18 22:13 UTC, sandersn approved these changes

2018-06-18 22:13 UTC, sandersn commented on types/node/index.d.ts
>          export function __promisify__(hostname: string, rrtype?: "A" | "AAAA" | "CNAME" | "NS" | "PTR"): Promise<string[]>;
This is not for this PR, but I noticed that `__promisify__(hostname: string, rrtype?: "A" | ...)` prevents `__promisify__(hostname: string, rrtype?: string)` from ever matching a call like `__promisify__("host")`. I'm pretty sure that `rrtype` should not be optional in the first overload.

2018-06-18 22:14 UTC, merged