Extending intercom types and fixing response type
DefinitelyTyped/DefinitelyTyped pull request #26657
Opened 2018-06-19 09:40 UTC by saulogt

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-06-19 09:46 UTC, saulogt commented
Thanks for stating this types.
I added:
1. Callback format interfaces 
2. Companies operations
3. IntercomError definition

I fixed:
1. The response type for all functions. The return content is an http.IncomingMessage with the `body` being the actual expected object(s)

2018-06-19 09:50 UTC, saulogt commented
@jineshshah36 
@Peping

2018-06-19 14:44 UTC, jineshshah36 requested changes
```
export type CompanyIdentifier = {company_id: string }
```

should be an interface to make it easier to extend or use

Also, you are using a tuple to represent errors in IntercomError. That should probably be an array type not a tuple type.

```
export type ApiResponse<T> = IncomingMessage & {
  body: T
}
```

should probably be an interface that extends IncomingMessage to make it easier to extend or use

2018-06-21 14:21 UTC, jineshshah36 approved these changes

2018-06-21 16:47 UTC, merged