[@types/webpack] Add devserver options
DefinitelyTyped/DefinitelyTyped pull request #26751
Opened 2018-06-22 15:39 UTC by arturovt

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-06-22 16:57 UTC, alan-agius4 requested changes

2018-06-22 16:57 UTC, alan-agius4 commented on types/webpack/index.d.ts
> +            after?: () => void;
This doesn’t look right. Based on the docs the function has a parameter.

https://webpack.js.org/configuration/dev-server/#devserver-after

2018-06-22 16:57 UTC, alan-agius4 commented on types/webpack/index.d.ts
> +            before?: () => void;
Same thing as the ‘after’

2018-06-22 16:57 UTC, alan-agius4 commented on types/webpack/index.d.ts
> +            headers?: object;
This should be a dictionary. 

‘{[key: string]: string}’

2018-06-22 16:57 UTC, alan-agius4 commented on types/webpack/index.d.ts
> +            https?: boolean | object;
Maybe instead of object create an interface?

https://webpack.js.org/configuration/dev-server/#devserver-https

2018-06-22 16:57 UTC, alan-agius4 commented on types/webpack/index.d.ts
> +            overlay?: boolean | object;
There than object create an interface with the valid options 

https://webpack.js.org/configuration/dev-server/#devserver-overlay

2018-06-22 16:57 UTC, alan-agius4 commented on types/webpack/index.d.ts
> +            stats?: string | object;
Instead of object use the Stats interface, which is already created. 

Options.Stats

2018-06-22 16:57 UTC, alan-agius4 commented on types/webpack/index.d.ts
> +            watchOptions?: object;
Use the already created WatchOptions

2018-06-22 16:58 UTC, alan-agius4 requested changes
Left some comment with feedback.

Nice addition!

2018-06-22 18:02 UTC, Hotell commented
IMHO webpack-dev-server has nothing to do with webpack config ( meaning if I install webpack+webpack-cli ) there is no devServer. We should adhere to implementation packages so what I suggest:

- updating type defs for [dev-server ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack-dev-server/index.d.ts)
- leveraging declaration merging - extending 
```tsx
declare namespace webpack {
     interface Configuration { ... } 
}
```
 from webpack-dev-server definitions

- setting devServer type within webpack ambient types to `devServer?: {}`

2018-06-23 08:46 UTC, alan-agius4 commented
it makes a lot of sense what you propose @Hotell

2018-06-27 21:10 UTC, arturovt commented
@alan-agius4,
what about if we
1. close this PR
2. i will make another PR with making module augmentation and updating defs for `@types/webpack-dev-server`, like:
```
// @types/webpack-dev-server/index.d.ts
import * as webpack from 'webpack';

declare module 'webpack' {
    interface Configuration {
        // some description
        devServer?: {
            // some description
            port?: number;
        }
    }
}
```

2018-06-27 21:13 UTC, Hotell commented
@arturovt go for it! but close this once the new PR is created so we have some history/reference.
cheers  ✌👌👍

2018-06-27 21:15 UTC, arturovt commented
@Hotell, :thumbsup:

2018-07-03 16:41 UTC, mhegazy commented
Closing since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26895 went in.

2018-07-03 16:41 UTC, closed without merging

2018-07-03 17:15 UTC, alan-agius4 commented
Go for it!

On Tue, 03 Jul 2018 at 18:42, Mohamed Hegazy <notifications@github.com>
wrote:

> Closing since #26895
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26895> went in.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26751#issuecomment-402220296>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AQv-WnaGaUNaW5XSJmIJbbWaUN3Dl8Z1ks5uC57bgaJpZM4U0A-6>
> .
>