[@types/passport]: Add callbackURL to the list of options
DefinitelyTyped/DefinitelyTyped pull request #26781
Opened 2018-06-23 23:30 UTC by autaut03

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L135

Method `.authenticate` is the method that custom passport strategies implement theirselves. `options` object is being passed to them as a second argument. Since we don't know which of the `.authenticate` methods will get called at type-checking stage and it's `options` object's properties can vary between implementations, `[key: any]: any` should probably be added to it. However I'm not sure if this is a correct way to do it, so at least I added a `callbackURL` option from oauth2 package. It already has got options that are from external strategies such as `passReqToCallback` (from oauth2 too), so I think it's fine to add another one.

2018-06-24 01:34 UTC, danielpa9708 commented on types/passport/index.d.ts
> +		callbackURL?: string;
not aligned to other props

2018-06-28 22:03 UTC, tlaziuk requested changes
could you please provide some tests for that change?

also I believe if this is a change which refers to the OAuth plugin (and other similar packages) then maybe this change should be provided by a respective package?

2018-06-28 22:42 UTC, autaut03 commented
@tlaziuk Hey. As I'm new to TS, I'm not sure if you can modify TS defined types from another typings package.

If it's still ok to add the option into @types/passport and not to something else, then yes, I can write the tests. However as the change is only related to passport-oauth plugin, again I'm in doubt if it's good to require direct implementations packages just to write some tests :/

2018-06-29 07:32 UTC, tlaziuk commented
@autaut03 yes you can redefine types of another package, a good example of how to do that is `rxjs@^5.0.0` eg. https://github.com/ReactiveX/rxjs/blob/5.5.11/src/add/operator/do.ts

there are some definitions here which are using such practice (eg. `@types/node`), it's called ambient modules - https://www.typescriptlang.org/docs/handbook/modules.html#ambient-modules

you are right about implementing a new package just to write tests, but if changes are related only to `passport-oauth` then you should create type definitions for that package and write tests there - I believe that's how it works here :)

2018-07-05 22:24 UTC, closed without merging