New type definitions for obj-file-parser package
DefinitelyTyped/DefinitelyTyped pull request #26790
Opened 2018-06-24 17:40 UTC by benc-uk

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-06-24 23:21 UTC, plantain-00 requested changes

2018-06-25 07:49 UTC, plantain-00 commented on types/obj-file-parser/index.d.ts
> +export default class Parser {
You can try to check this example: https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-class-d-ts.html

2018-06-25 08:14 UTC, benc-uk commented on types/obj-file-parser/index.d.ts
> +export default class Parser {
Ok, thanks! I think that has got it working, new commit: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26790/commits/d1e2fcdf69db6987b9d558f134b51c05cbbf51d8

2018-06-25 12:44 UTC, plantain-00 approved these changes

2018-06-25 21:30 UTC, merged