Add typings for vexdb
DefinitelyTyped/DefinitelyTyped pull request #26942
Opened 2018-06-29 08:29 UTC by MayorMonty

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-06-29 12:43 UTC, plantain-00 requested changes

2018-06-29 12:43 UTC, plantain-00 commented on .editorconfig
> -root = true
I think this file shouldn't be removed

2018-06-29 12:43 UTC, plantain-00 commented on types/vexdb/README.md
> +# Installation
I think the `README.md` is not required here, there will be one generated when published to npm

2018-06-29 22:17 UTC, plantain-00 commented on .editorconfig
> +indent_style = space
Still, this file is not expected to be changed here

2018-06-29 22:17 UTC, plantain-00 commented on types/vexdb/.editorconfig
> +indent_style = space
This file is not required here

2018-07-02 08:35 UTC, MayorMonty commented
@plantain-00 I think was able to fix the automatic file generation of my editor, could this be approved?

2018-07-02 08:49 UTC, plantain-00 commented
The `.editorconfig` is still changed in this PR, I suggest not to.

2018-07-03 16:53 UTC, merged