Add missing stripe.iinvoice fields
DefinitelyTyped/DefinitelyTyped pull request #27030
Opened 2018-07-03 20:29 UTC by dozoisch

- Added: amount_paid, amount_remaining, billing, billing_reason, due_date, hosted_invoice_url, invoice_pdf, number

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://stripe.com/docs/api#invoice_object
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-07-04 09:34 UTC, LinusU commented on types/stripe/index.d.ts
> +            due_date: number;
`number | null`?

> This value will be null for invoices where billing=charge_automatically.

2018-07-04 09:34 UTC, LinusU commented
Just one small nit

2018-07-04 09:35 UTC, LinusU requested changes
Just one small thing...

2018-07-04 09:35 UTC, LinusU commented on types/stripe/index.d.ts
> +            due_date: number;
`number | null`?

> This value will be null for invoices where billing=charge_automatically.

2018-07-04 18:08 UTC, dozoisch commented on types/stripe/index.d.ts
> +            due_date: number;
Oh good catch!

2018-07-04 18:16 UTC, dozoisch commented
@LinusU alright corrected it! and added descriptions that were missing on some field.

Also `ending_balance` was missing an `| null`

2018-07-05 11:25 UTC, LinusU approved these changes
Nice 👍

2018-07-05 17:00 UTC, merged