feat(fs-extra): replace fs.symlink.Type with local copy FsSymlinkType
DefinitelyTyped/DefinitelyTyped pull request #27072
Opened 2018-07-05 12:38 UTC by DomiR

**The gist of it**: using fs.symlink.Type from new node definitions is a breaking change.
As long fs-extra supports node versions below 8.9 we cannot just require to have newest node definitions installed [see here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25975#issuecomment-395774578).

This issue is causing some trouble: 
- https://github.com/byCedric/semantic-release-expo/pull/10
- #26460
- https://github.com/Matticusau/sqlops-mssql-db-insights/issues/19
- #26381
- #26730

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-07-05 17:44 UTC, shiftkey approved these changes

2018-07-05 17:48 UTC, alan-agius4 requested changes
the issue is the consumer are pinning node typings. For me the should pin this library too.

2018-07-05 17:54 UTC, alan-agius4 approved these changes

2018-07-05 18:00 UTC, alan-agius4 requested changes
Consumers which are pinning down @types/node need to pin down @types/fs-extra.

Duplicating typings because consumers are pinning down one of the dependencies is not ideally IMHO, as this add an addition layer of maintaince,  if this model is changed in a next version of node.

//cc @mhegazy maybe he shares a different opinion. And I don’t want to stall this PR, if it’s acceptable by the members of DT.

2018-07-06 05:38 UTC, alan-agius4 approved these changes

2018-07-06 16:40 UTC, merged