Update next definitions for 6.1.1 - router events API
DefinitelyTyped/DefinitelyTyped pull request #27143
Opened 2018-07-09 02:49 UTC by jakemmarsh

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/zeit/next.js/pull/4726
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-07-14 06:23 UTC, jthegedus approved these changes

2018-07-14 06:30 UTC, resir014 requested changes

2018-07-16 02:52 UTC, jakemmarsh commented on types/next/router.d.ts
> +        on: (eventName: EventName, handler: (url: string) => any) => void;
Thanks, updated. Not sure if the way I've handled it is ideal so I'm open to feedback.

2018-07-23 17:10 UTC, merged

2018-07-30 10:16 UTC, kachkaev commented
`Router.onRouteChangeStart` still works in `next@6.1`, but is removed here. This is a breaking change, which can cause false-positive TypeErrors. Some context: https://github.com/zeit/next.js/issues/4863

Could `onRouteChangeXXX` be brought back?

2018-07-30 15:41 UTC, andy-ms commented
@kachkaev PRs accepted.

2018-07-30 16:12 UTC, resir014 commented
@kachkaev @andy-ms Yeah, apologies guys. I'm working on a PR to get it back as we speak.