react-native - Added nativeConfig to WebViewProps
DefinitelyTyped/DefinitelyTyped pull request #27211
Opened 2018-07-12 05:51 UTC by TheAlmightyBob

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://facebook.github.io/react-native/docs/webview#nativeconfig
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-07-12 06:34 UTC, iRoachie requested changes

2018-07-12 06:34 UTC, iRoachie commented on types/react-native/test/index.tsx
> +                nativeConfig={{ component: 'test' }}
Could you add the other props here?

2018-07-12 22:34 UTC, alloy commented
It’s been red since https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/403199671 /cc @RyanCavanaugh

2018-07-13 20:40 UTC, iRoachie approved these changes

2018-07-14 06:26 UTC, a-tarasyuk approved these changes
LGTM

2018-07-15 19:19 UTC, RyanCavanaugh commented
🌟 🎈 🎉 🏆 🎂 ✨ ⭐️ 

Congratulations on your first DefinitelyTyped contribution!

🌟 🎈 🎉 🏆 🎂 ✨ ⭐️

2018-07-15 19:19 UTC, merged