Adds jira-client
DefinitelyTyped/DefinitelyTyped pull request #27349
Opened 2018-07-16 23:17 UTC by orta

Adds [jira-client](https://github.com/jira-node/node-jira-client) which has had an idle PR for a long time, by @KOPTE3 - https://github.com/jira-node/node-jira-client/pull/194

It's time to move the type definitions to DT.

> QA

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

> If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-07-16 23:44 UTC, plantain-00 requested changes

2018-07-16 23:44 UTC, plantain-00 commented on types/jira-client/index.d.ts
> +export = JiraApi;
It's `export default` rather than `export =`: https://github.com/jira-node/node-jira-client/blob/master/src/jira.js#L10

2018-07-17 11:57 UTC, orta commented
Thanks @plantain-00  - I've fixed that 👍

2018-07-17 12:52 UTC, plantain-00 approved these changes

2018-07-23 18:03 UTC, merged