fix: let jQuery's insertAfter / insertBefore accept JQuery<HTMLElement> as well as HTMLElement
DefinitelyTyped/DefinitelyTyped pull request #27404
Opened 2018-07-19 02:45 UTC by gfx

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- <del>[ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>></del>
- <del>[ ] Increase the version number in the header if appropriate.</del>
-<del> [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.</del>

---

As `insertBefore(x as JQuery<Element>)` is valid , `insertBefore(x as JQuery<HTMLElement>)` but it doesn't compile. The signature should be ones in this pull-request, as the test code suggests.

2018-07-19 03:36 UTC, gfx commented
Unfortunately, lots of dtses that depend on jquery requires TypeScript 2.3, but this PR requires TypeScript 2.4.

Is it okay to upgrade these TypeScript versions?

2018-07-19 11:35 UTC, leonard-thieu requested changes
I had to verify that you can target DOM nodes with `insertAfter`/`insertBefore`. Looks like that is indeed the case.

https://jsfiddle.net/leonard_thieu/xpvt214o/446079/

And it does seem to be the case that `insertAfter`/`insertBefore` does not include the target elements in the return jQuery object.

https://jsfiddle.net/leonard_thieu/xpvt214o/446101/

2018-07-19 11:45 UTC, leonard-thieu commented on types/jquery/index.d.ts
> +    insertAfter<E extends Node>(target: JQuery.Selector | JQuery.htmlString | JQuery.TypeOrArray<E> | JQuery<E>): this;
The type parameter is not necessary. You're effectively using it only once. This should be

```typescript
insertAfter(target: JQuery.Selector | JQuery.htmlString | JQuery.TypeOrArray<Node> | JQuery<Node>): this;
```

2018-07-19 11:45 UTC, leonard-thieu commented on types/jquery/index.d.ts
> +    insertBefore<E extends Node>(target: JQuery.Selector | JQuery.htmlString | JQuery.TypeOrArray<E> | JQuery<E>): this;
Same as with `insertAfter`.

2018-07-19 11:46 UTC, leonard-thieu requested changes
<!---->

2018-07-20 02:09 UTC, gfx commented
@leonard-thieu Thanks, I did misunderstand what is the problem. Now I've fied everything you reviewed!

2018-07-20 10:01 UTC, leonard-thieu approved these changes

2018-07-21 00:56 UTC, merged

2018-07-23 03:17 UTC, gfx commented
Thanks!