Update types of uri-templates to be up to date to new version.
DefinitelyTyped/DefinitelyTyped pull request #27559
Opened 2018-07-25 07:35 UTC by barnski

Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/geraintluff/uri-templates/compare/v0.1.2...v0.1.9 (new features came and original typing was incomplete.)
- [ x] Increase the version number in the header if appropriate.

2018-07-30 18:53 UTC, sheetalkamat commented on types/uri-templates/uri-templates-tests.ts
> +const obj: { [key: string]: string } = { test: 'test1' };
You dont need to type obj here. just set obj = { test: 'test1' }

2018-07-30 18:53 UTC, sheetalkamat requested changes
Nit in test

2018-07-31 10:00 UTC, barnski commented
Ok, changed. Should I click something here to sign it as "ready for review" or you just take it up? @sheetalkamat

2018-07-31 18:45 UTC, sheetalkamat approved these changes

2018-07-31 18:45 UTC, merged