Add `currentRouteName` to Ember RouterService
DefinitelyTyped/DefinitelyTyped pull request #27590
Opened 2018-07-26 02:09 UTC by lsg-braymon

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.emberjs.com/api/ember/3.3/classes/RouterService/properties/currentRouteName?anchor=currentRouteName
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-07-26 05:45 UTC, mike-north requested changes
Thanks for your contribution to Ember's type definitions!

In addition to the `readonly` thing, please also ensure this has test coverage. in the ./tests folder, find a reasonable place to add positive test case (i.e., 

```ts
const x: string = routerService.currentRouteName;
```

2018-07-26 05:45 UTC, mike-north commented on types/ember/index.d.ts
> +            currentRouteName: string;
Can we have this as a readonly property, in alignment with the implementation

https://github.com/emberjs/ember.js/blob/b08b93c925bbc7fd4c39ad94cc8280abc56946e0/packages/ember-routing/lib/services/router.js#L41

2018-07-29 23:20 UTC, lsg-braymon commented
@mike-north Thanks for the feedback.
Apologies for my original changes wherein I placed the `currentRouteName` in the Router class instead of the RouterService. I also added `currentURL` in the updated version.

2018-07-29 23:44 UTC, mike-north approved these changes
LGTM. :shipit:

2018-07-30 18:05 UTC, merged