React-select : option multi renamed to isMulti
DefinitelyTyped/DefinitelyTyped pull request #27611
Opened 2018-07-26 14:40 UTC by gsalaun1

In react-select, the option for multi selection is named isMulti, not multi as it was in the file before my merge request.

2018-07-26 17:12 UTC, burtek commented
@gsalaun1 TBH, those typings are for `react-select@1.3`, not `2.0` which you;re probably trying to use. There are many changes that should be taken into consideration and published together as for version `2.0`

2018-07-31 15:42 UTC, burtek commented
Voting against this change, as it's not compatible with v1.3.

Development for v2.0 typings is taking place in [Jtango18/updated-react-select-ts-defs](https://github.com/Jtango18/updated-react-select-ts-defs) (see https://github.com/JedWatson/react-select/issues/2860)

2018-07-31 15:42 UTC, burtek reviewed
Voting against this change, as it's not compatible with v1.3.

Development for v2.0 typings is taking place in [Jtango18/updated-react-select-ts-defs](https://github.com/Jtango18/updated-react-select-ts-defs) (see JedWatson/react-select#2860)

2018-09-02 08:32 UTC, claasahl requested changes
As per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27611#issuecomment-408168432

Typings for react-select V2 have been released since this PR was last edited/commented.

2018-09-09 09:26 UTC, closed without merging