[node]: Update assert.fail parameters
DefinitelyTyped/DefinitelyTyped pull request #27622
Opened 2018-07-26 21:48 UTC by eyqs

[assert.fail](https://nodejs.org/api/assert.html#assert_assert_fail_message) has an optional `message` parameter that can be either a `string` or `Error`.

2018-07-29 20:55 UTC, Flarna requested changes
Could you please update also latest NodeJs (file types/node/index.d.ts).

Docs tell that `string | Error` is applicable to other assert apis also. Would be nice to update them also if you like.

2018-08-01 22:28 UTC, eyqs commented
OK, I'm working on it.

2018-08-02 22:13 UTC, Flarna commented
Changes in nodejs 10 look good.

For version 9.x I would recommend also `string | Error` (even docs say `any`) as implementation change to support `Error` in in since 9.0.0 (see https://github.com/nodejs/node/commit/e13d1df89bbaf26601b6c1c8406113b80bb6a95c).

I don't think the change from `string` to `any` for nodejs < 10.x should be done. I know the docs tell `any` but actually the source just passes the content of `message` to the `Error` constructor (except if it is `undefined`) which expects a `string`.

Type specification in nodejs docs is getting better and better but for old nodejs versions it's often to unspecific/sloppy for direct reuse here therefore I tend to take a look into the source code also.

2018-08-02 22:42 UTC, Flarna commented on types/node/v0/index.d.ts
> +        export function fail(actual: any, expected: any, message: any, operator: string): never;
I think this change is not needed or an overload `fail(message?: string)` should be added.

2018-08-02 22:43 UTC, Flarna commented on types/node/v4/index.d.ts
> +            code: 'ERR_ASSERTION';
I think this field is not yet present in node 4

2018-08-02 22:43 UTC, Flarna commented on types/node/v4/index.d.ts
> +        export function fail(actual: any, expected: any, message: any, operator: string): never;
I think this change is not needed or an overload fail(message?: string) should be added.

2018-08-02 22:44 UTC, Flarna commented on types/node/v6/index.d.ts
> +            code: 'ERR_ASSERTION';
this field is not yet present in node v6

2018-08-02 22:45 UTC, Flarna commented on types/node/v6/index.d.ts
> +        export function fail(message: string): never;
message is optional

2018-08-02 22:46 UTC, Flarna commented on types/node/v7/index.d.ts
> +        export function fail(actual: any, expected: any, message: any, operator: string): never;
fail without arguments is missing here, message should be an optional string

2018-08-02 22:46 UTC, Flarna commented on types/node/v8/index.d.ts
>          export function fail(message: string): never;
message is optional

2018-08-02 22:47 UTC, Flarna commented on types/node/v9/index.d.ts
> +        export function fail(actual: any, expected: any, message?: string | Error): never;
Please add parameter `stackStartFn?: Function`.

2018-08-02 22:49 UTC, eyqs commented
Sorry about all that, I was still basing it on the documentation. I'll revert the entire commit except the AssertionError part.

2018-08-02 23:15 UTC, Flarna commented on types/node/v9/index.d.ts
> +        export function fail(actual: any, expected: any, message?: string, operator?: string, stackStartFn?: Function): never;
`| Error` got lost here

2018-08-02 23:16 UTC, Flarna commented on types/node/v0/index.d.ts
> +        export function fail(actual?: any, expected?: any, message?: any, operator?: string): never;
`any`=> `string` for message

2018-08-02 23:16 UTC, Flarna commented on types/node/v4/index.d.ts
> +        export function fail(actual: any, expected: any, message?: any, operator?: string): never;
`any`=> `string` for message

2018-08-02 23:17 UTC, Flarna commented on types/node/v9/index.d.ts
> +        export function fail(actual: any, expected: any, message?: string, operator?: string, stackStartFn?: Function): never;
`| Error` got lost here

2018-08-02 23:31 UTC, eyqs commented
Thank you for looking over the PR so thoroughly!

2018-08-03 06:17 UTC, eyqs commented
I squashed the commits into one.

2018-08-03 07:43 UTC, Flarna approved these changes

2018-08-06 16:28 UTC, merged

2018-08-06 17:09 UTC, eyqs commented
CI is still failing, was it OK to merge?

2018-08-06 17:09 UTC, andy-ms commented
Yes, we're fixing the CI separately. It's not because of this change.