@types/graphql: Make GraphQLNonNull and GraphQLList structurally different
DefinitelyTyped/DefinitelyTyped pull request #27641
Opened 2018-07-27 17:04 UTC by benwaffle

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://stackoverflow.com/questions/51547169/structural-typing-and-user-defined-type-guards
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-07-31 07:47 UTC, bradzacher commented
I understand your intention though I don't agree with this living in typings.
This will make the typings differ from the underlying implementation.

2018-07-31 12:04 UTC, IvanGoncharov requested changes
I argee with @bradzacher we should try to keep types consistent with `graphql-js`.
Moreover `__kind` doesn't exist in runtime so you can't do `type.__kind` so it also differs from actual class content.

2018-07-31 14:56 UTC, benwaffle commented
So what should I be doing to make the test compile? I've tried adding the `__kind` in my own code through module augmentation but that didn't seem to work

2018-07-31 15:00 UTC, benwaffle commented
is the solution just a cast?

2018-07-31 20:00 UTC, IvanGoncharov commented
@benwaffle I don't know what would be a good solution but we shouldn't add fake fields just to make TS happy.

As a workaround, you can do `type instaceof GraphQLList` and `type instanceof GraphQLNonNull`.

2018-07-31 20:52 UTC, closed without merging

2018-08-03 12:48 UTC, TonyPythoneer commented
This question should ask GraphQL team, not here. We are just according to the source code to provide the
definition.