Added declaration of chrisjpatty/react-dragtastic
DefinitelyTyped/DefinitelyTyped pull request #27669
Opened 2018-07-30 04:14 UTC by nscarcella

* Added declaration of chrisjpatty/react-dragtastic

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-07-30 19:33 UTC, sheetalkamat requested changes

2018-07-30 19:33 UTC, sheetalkamat commented on types/react-dragtastic/tsconfig.json
> +        "strictNullChecks": false,
Since this is new definition please change this property to true and fix any errors

2018-07-30 19:33 UTC, sheetalkamat commented on types/react-dragtastic/tslint.json
> +  "rules": {
No. This is new definition, so should just extends dtslint/dt.json

2018-07-30 20:06 UTC, nscarcella commented
Added the changes @sheetalkamat. Sorry about the strict null issue, I was sure I left the original values as they where. About the semicolon, you can't blame me for trying :P

2018-08-03 22:35 UTC, sheetalkamat approved these changes

2018-08-03 22:35 UTC, merged