[@types/aws-lambda]: Add extractedFields optional field
DefinitelyTyped/DefinitelyTyped pull request #27670
Opened 2018-07-30 05:31 UTC by DavidJFelix

Added an undocumented optional field to a datatype which is sent zipped and base64 encoded. This field is only available if users select certain options when creating a subscription filter.

You can see the field used if you create a subscription filter to elasticsearch and look at the source for the builtin lambda. I couldn't find any documentation for this field except in the terms "fields extracted" [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/FilterAndPatternSyntax.html) and found some amazon code referencing it [here](https://github.com/amazon-archives/cloudwatch-logs-subscription-consumer/blob/master/src/test/resources/aws-lambda-log-example.json#L14).

I nearly went insane tracking this down.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-07-30 09:24 UTC, simonbuchan requested changes
Also should have a type test, a line reading a value out of this.

2018-07-30 12:55 UTC, DavidJFelix commented on types/aws-lambda/index.d.ts
> +    extractedFields?: object;
I think you're right that it is `{string: string}`. It is only sometimes present. It is present if they set filter parameters with names on the filter subscription used to request events be sent.

Suppose you set up a filter like:

```
    qraphqlLogSubscription:
      Type: AWS::Logs::SubscriptionFilter
      DependsOn:
        - GraphqlLogGroup
      Properties:
        DestinationArn: {Fn::ImportValue: SendLogLambdaFunctionArn}
        FilterPattern: '[timestamp=*Z, request_id="*-*", message]'
        LogGroupName: {Ref: GraphqlLogGroup}
```

Note the filter pattern variable. This is assigning keys to the `extractedValues` dictionary by matching values in the log line. The line above is verbatim what is suggested for lambda logging.

So `message` might be something like: `2018-07-26T15:55:20.941Z 4c18df59-90ec-11e8-a4c6-359cf8abd509 {"my": "message"}`. For this, you'll get:

```
{
  "awslogs": {
    "data": {
      "id": "someid",
      "timestamp":  1234,
      "message": "2018-07-26T15:55:20.941Z 4c18df59-90ec-11e8-a4c6-359cf8abd509 {\"my\": \"message\"}",
      "extractedFields: {
        "timestamp": "2018-07-26T15:55:20.941Z",
        "request_id": "4c18df59-90ec-11e8-a4c6-359cf8abd509",
        "message": "{\"my\": \"message\"}"
      }
    }
  }
}
```

It's important to note that the key names are entirely defined by the filter pattern. If no keys are extracted, I believe this dictionary is not present.

2018-08-05 21:56 UTC, simonbuchan approved these changes
Looks good, thanks for your time!

2018-08-05 21:59 UTC, simonbuchan commented
Note that `object` is actually a narrower type than `{ [string]: string }`, as it doesn't actually let you access any properties - all you know is that `typeof` will return `"object"` (it's similar to `{}`, while not allowing primitive types)

2018-08-06 18:34 UTC, merged