Strophe for ts >= 2.1
DefinitelyTyped/DefinitelyTyped pull request #27682
Opened 2018-07-30 11:35 UTC by tijszwinkels

importing the Strophe types on a contemporary typescript-version, would give the following error:

```
    ERROR in [at-loader] ./node_modules/@types/strophe/index.d.ts:1111:3
        TS2666: Exports and export assignments are not permitted in module augmentations.
```

This is fixed in this PR.

For the reviewer: I added a // TypeScript Version: 2.1 header, to make sure that the tests fail without this change. Let me know if this has undesirable side-effects. 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Reason explained in commit and PR.
- [x] Increase the version number in the header if appropriate. -> No version number in header.

2018-08-06 22:47 UTC, rbuckton commented
From what I can tell, "strophe" isn't even a module, though its replacement "strophe.js" is. Upon review, it seems like the package definition also incorrectly declares modules for `"$build"`, `"$msg"`, `"$iq"`, and `"$pres"` that aren't actually modules. Should these also be removed?

2018-08-08 12:07 UTC, tijszwinkels commented
You're right; The name of the npm module is currently "strophe.js". The "strophe" module has been deprecated. Not entirely sure what the right approach is here, because we'll probably break things for existing users if we rename the strophe typescript definitions. Perhaps copy the definitions to "strophe.js" as well?

I'm pretty new to typescript, but why would you say that "$build", "$msg", "$iq", and "$pres" are incorrect? We use these in our software, like so:

```
import { Strophe as Strophe, $iq, $pres} from "strophe.js"

const iq = $iq({
            to : 'endpoint.' + this._server,
            type : 'get'
        }) // etc.

```

2018-08-16 15:10 UTC, tijszwinkels commented
@rbuckton Do you want me to duplicate the 'strophe' folder into the 'strophe.js' folder in this MR?

2018-08-17 00:12 UTC, uniqueiniquity requested changes
@tijszwinkels if `strophe` has been deprecated in favor of `strophe.js`, it probably makes the most sense to forgo fixing up this .d.ts and create a new definition for strophe.js. You can copy what's here to a fresh PR if that's what's best for the new package.

2018-08-21 07:19 UTC, closed without merging