[@types/webvr-api] Make webvr-api work with Typescript 3
DefinitelyTyped/DefinitelyTyped pull request #27735
Opened 2018-07-31 19:33 UTC by arilotter

Allow a Float32Array as leftBounds and rightBounds. This lets webvr-api work with typescript 3.0.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (No changes)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.mozilla.org/en-US/docs/Web/API/VRLayerInit/leftBounds
^ This url suggests that it can take an "array of four floats", of which a `Float32Array` is a valid type.
- [x] Increase the version number in the header if appropriate. (didn't increment version number, since it's for the same three.js version)

2018-08-06 22:12 UTC, rbuckton commented
@arilotter have you tested that this works? According to [the spec](https://immersive-web.github.io/webvr/spec/1.1/#interface-vrlayerinit), `leftBounds` expects a WebIDL `sequence<float>`, so its not clear whether the spec would accept a `Float32Array` here, or just an `Array`. It's unclear from Mozilla's documentation whether a `Float32Array` would be expected to work here, and other browser implementations might not support it.

2018-08-17 00:08 UTC, uniqueiniquity requested changes
Marking as changes requested until @rbuckton's comment is addressed.

2018-08-20 06:03 UTC, efokschaner commented
Just want to add that (assuming these definitions matched the ones in ts 2.x) this would also break compatibility with those TS versions. If these definitions were not already in ts pre-3.0 this can be ignored. Otherwise perhaps a major version bump of these definitions is warranted, to fix TS 3.0 compatible while preserving it for those that have installed these pre 3.0.

2018-08-20 06:05 UTC, efokschaner commented
I'll also add that I'm in favour of these matching TS's built-in definitions over the spec, unless TS itself would mind placing the spec over the implementations.

2018-08-24 00:34 UTC, closed without merging