Add new (partial) typings for npm 'di' github 'node-di'
DefinitelyTyped/DefinitelyTyped pull request #27741
Opened 2018-08-01 01:11 UTC by johnjbarton

These typings are adequate for the primary user of di, karma-runner.
The underlying project is deprecated and we will move to a new di system,
but these typings help document where we are today.

Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [ x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-08-01 19:00 UTC, sheetalkamat requested changes

2018-08-01 19:00 UTC, sheetalkamat commented on package.json
>      }
Please remove the change to this file  as its not needed.

2018-08-03 16:13 UTC, johnjbarton commented
Done, thanks.

2018-08-03 17:44 UTC, sheetalkamat approved these changes

2018-08-03 17:45 UTC, merged