Make typings compatible with ES6 promises
DefinitelyTyped/DefinitelyTyped pull request #27779
Opened 2018-08-01 19:33 UTC by gscshoyru

Since ES6 promises don't implement finally, trying to $q.when a third
party promises fails typings. This introduces a new type that is
compatible with this, to allow for typings to work when
taking an ES6 promise.

Totally willing to change the name to something more sensible here

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.angularjs.org/api/ng/service/$q#when
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-08-01 21:38 UTC, gscshoyru commented
Tests are failing, I'm guessing that's because of #27778 -- will rebase when that merges.

2018-08-03 23:15 UTC, thorn0 requested changes
`resolve`/`when` doesn't expect an "ES6 promise", it [expects "a (3rd party) then-able promise"](https://docs.angularjs.org/api/ng/service/$q#when), i.e. an object with the `then` method. TypeScript already has a definition for this type in its library (`lib.d.ts`): it's called `PromiseLike`. Please use it.

2018-08-03 23:35 UTC, gscshoyru commented
Yeah I knew I needed some global base class but for some reason thought I should make it myself. Should have looked into the typings in a little more detail. This is _way_ better thanks for the tip.

2018-08-04 10:14 UTC, thorn0 requested changes
Great. Please add tests with native promises to demonstrate that it works.

2018-08-11 10:25 UTC, closed without merging