Parse git config
DefinitelyTyped/DefinitelyTyped pull request #27886
Opened 2018-08-05 13:44 UTC by LexSwed

Change types to have latest api in https://github.com/jonschlinkert/parse-git-config

P.S: current README wasn't updated after ```keys()``` method removal, PR already exist to fix that:
https://github.com/jonschlinkert/parse-git-config/pull/11
and there is only ```expandKeys()``` method left:
https://github.com/jonschlinkert/parse-git-config/blob/master/index.js#L149

2018-08-06 19:49 UTC, deltaidea commented
Thanks for updating the types!
It looks like `_Options` interface can also include `expandKeys: boolean`. Do you think it's a good idea to update that as well while we're at it?

Take a look at [`index.js`](https://github.com/jonschlinkert/parse-git-config/blob/2.0.2/index.js):
- `parse` uses `parse.promise` at line 45
- `parse.promise` uses `parseIni` at line 80
- `parseIni` checks `opts.expandKeys === true` and calls `parse.expandKeys` at line 170

2018-08-06 19:52 UTC, deltaidea requested changes
See comment above. Thank you for helping! I'll click approve ASAP, just wanted to discuss before merging.

2018-08-07 11:28 UTC, LexSwed commented
Hey, good notice. I am not sure that it was a good idea, but I also added ```include``` from what I've seen here: https://github.com/jonschlinkert/parse-git-config/blob/2.0.2/index.js#L77 to ```Options```

2018-08-07 11:29 UTC, deltaidea commented
What does `include` option do? Never seen it.

2018-08-07 11:32 UTC, LexSwed commented
Same, didn't try it :D
it's undocumented, but it's there.

2018-08-07 11:38 UTC, deltaidea approved these changes

2018-08-07 11:39 UTC, deltaidea commented
Good enough for me! <3

2018-08-08 20:33 UTC, merged