Add typings file for dialogflow
DefinitelyTyped/DefinitelyTyped pull request #27899
Opened 2018-08-06 12:56 UTC by dyladan

This PR offers mostly complete coverage of the `dialogflow` NPM package. As far as I know the only missing things are:

- typings for batch transactions
- callback style overloads (currently the Promise style is supported)
- some newer functionality only available via the `v2beta1` namespace (these are not yet stable and change very quickly)
- tests

We have used this typings file extensively within our code and it has worked very well for us, and I plan to continue to work on this until the above things are done, but many other people have asked for this functionality (dialogflow/dialogflow-nodejs-client-v2#10) so I am making this available for those users in hopes that it will be valuable.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
n/a

If removing a declaration:
n/a

2018-08-16 08:17 UTC, qws777 approved these changes

2018-08-17 03:32 UTC, uniqueiniquity requested changes
Looks good for the most part. I couldn't leave a comment on the line because the diff was too big, but there's several places where you have optional parameters for a callback. As discussed [here](http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html), this isn't really good practice.

2018-08-17 12:46 UTC, dyladan commented
@uniqueiniquity pushed the requested changes

2018-08-17 15:56 UTC, uniqueiniquity approved these changes

2018-08-17 15:56 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2018-08-17 15:56 UTC, merged