rethinkdb: add merge & coerceTo, improve getAll signature with overloads
DefinitelyTyped/DefinitelyTyped pull request #27948
Opened 2018-08-07 17:37 UTC by gristow

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://www.rethinkdb.com/api/javascript/coerce_to/>><<https://www.rethinkdb.com/api/javascript/merge/>>
- [x] Increase the version number in the header if appropriate. (Not appropriate -- did not increase)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-08-08 01:30 UTC, Hoishin requested changes

2018-08-08 01:30 UTC, Hoishin commented on types/rethinkdb/index.d.ts
> +        getAll(...keys: string[]): Sequence;
Duplicate lines.
Also I think each overload needs `index`.

2018-08-08 01:37 UTC, Hoishin commented on types/rethinkdb/index.d.ts
> +        getAll(...keys: string[]): Sequence;
nvm about `index`. TypeScript doesn't support additional parameters after rest parameters...

2018-08-09 19:42 UTC, gristow commented
`.getAll` is just massively overloaded as a function, so to catch all of it takes a lot. I've done my best.

Sorry about the duplicate lines in the prior commit -- I got rid of those.

I also added support for compound indexes which hadn't been there before.

To deal with the impossible `getall(...keys: string[], index?: index` signature, I added overloads for up to five key properties (both for simple & compound indexes).

Let me know if you see any other errors!

2018-08-10 09:43 UTC, Hoishin requested changes

2018-08-10 09:43 UTC, Hoishin commented on types/rethinkdb/index.d.ts
> +        getAll(compoundKey: string[], index: Index): Sequence; // without index defaults to primary key
One of overloads with `compoundKey` have `index` optional. Did you mean to have the one required or have all the overloads optional?

2018-08-10 12:42 UTC, gristow commented
Thanks for catching -- none optional for compound indexes. Fixed.

2018-08-11 07:36 UTC, Hoishin approved these changes

2018-08-11 07:36 UTC, Hoishin commented
Thank you!

2018-08-13 16:14 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2018-08-13 16:14 UTC, merged