@types/react-select Fix: MouseEventHandler is marked as a Generic type
DefinitelyTyped/DefinitelyTyped pull request #27980
Opened 2018-08-09 04:37 UTC by dropbeardan

Env:
```
{
  "react": "16.2.0",
}
```

Error(s) Encountered:
- .../Option.d.ts(17,12): error TS2314: Generic type 'MouseEventHandler' requires 1 type argument(s).

Fix:
- Treat MouseEventHandler as a generic.

2018-08-11 09:51 UTC, claasahl commented
Hi @dropbeardan 

Sorry for the delayed feedback. The @typescript-bot (@RyanCavanaugh) did not @-mention @jonfreedman or me.

Do you have a sample that can be added to the test cases? Perhaps, this [test](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-select/test/examples/CustomOption.tsx) can be improved.

2018-08-12 08:37 UTC, claasahl commented
This commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6ddc57f14d431f54aa17a5c92427c62b08cb3fe6 already added a default type to various event handlers (incl. `MouseEventHandler`).

2018-08-12 09:32 UTC, claasahl requested changes
As per previous comments, there should be no more need for adding `<any>` (see https://github.com/DefinitelyTyped/DefinitelyTyped/commit/6ddc57f14d431f54aa17a5c92427c62b08cb3fe6). Updating to the latest react definitions should do the trick. If updating is not an option, I suggest to use the type `Element` (as in the referenced commit).

2018-08-15 14:03 UTC, dropbeardan commented
Many thanks @claasahl , upon review we did not implement @types/react as per the commit. I think the commit should be satisfactory for the purpose and we will work towards implementing @types/react to synergise the typings.

2018-08-15 14:03 UTC, closed without merging