Add types for @mysql/xdevapi
DefinitelyTyped/DefinitelyTyped pull request #28062
Opened 2018-08-12 17:37 UTC by r-a303931

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-08-12 23:45 UTC, plantain-00 requested changes

2018-08-12 23:45 UTC, plantain-00 commented on types/mysql__xdevapi/index.d.ts
> +// Project: https://github.com/mysql/mysql-connector-nodejs (Does not have to be to GitHub, but prefer linking to a source code repository rather than to a project website.)
It should be just `// Project: https://github.com/mysql/mysql-connector-nodejs` here

2018-08-13 09:12 UTC, plantain-00 approved these changes

2018-08-14 20:58 UTC, uniqueiniquity requested changes

2018-08-14 20:58 UTC, uniqueiniquity commented on types/mysql__xdevapi/index.d.ts
> +	createSocket: Function;
As discussed [here](https://github.com/DefinitelyTyped/DefinitelyTyped#common-mistakes), it's not good practice to use `Function`.

2018-08-14 20:58 UTC, uniqueiniquity commented on types/mysql__xdevapi/index.d.ts
> +	// tslint:disable-next-line
What TSLint rule are you disabling here and why?

2018-08-14 20:58 UTC, uniqueiniquity commented on types/mysql__xdevapi/index.d.ts
> +	// tslint:disable-next-line
Same here

2018-08-14 20:58 UTC, uniqueiniquity commented on types/mysql__xdevapi/index.d.ts
> +		J extends keyof T[K] = keyof T[K]
I don't think you need these defaults here (e.g. `= keyof T`).
In fact, you don't even need `J`; you can just index with `keyof T[K]`.

2018-08-14 20:58 UTC, uniqueiniquity commented on types/mysql__xdevapi/index.d.ts
> +	getCollection<T>(name: string): Collection<T>;
As discussed [here](https://github.com/Microsoft/dtslint/blob/master/docs/no-unnecessary-generics.md), it's cleaner if this is just `getCollection(name: string): Collection<any>`.

2018-08-14 20:58 UTC, uniqueiniquity commented on types/mysql__xdevapi/index.d.ts
> +	getTable<T = {}>(name: string): Table<T>;
Same here, except `Table<{}>`.

2018-08-21 23:27 UTC, closed without merging