Adding Writeable and Readable vs WriteStream and ReadStream
DefinitelyTyped/DefinitelyTyped pull request #28117
Opened 2018-08-14 16:30 UTC by micahriggan

On @types/node WriteStream and ReadStream are now WritableStream and ReadableStream.

I imagine this will break older versions of the node typings where WriteStream and ReadStream are still a thing. Let me know if I need to do something to make this safer for older versions.

2018-08-15 01:32 UTC, BANG88 approved these changes

2018-08-16 20:15 UTC, uniqueiniquity commented
Seems to me that [`WriteStream`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7ee3f0b455d69da5ee8e367569e91997877e3db3/types/node/index.d.ts#L696) is still a thing and is different from [`WritableStream`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/7ee3f0b455d69da5ee8e367569e91997877e3db3/types/node/index.d.ts#L609). Is the current type incorrect? Please let me know if I'm misunderstanding something.

2018-08-17 13:08 UTC, micahriggan commented
Maybe I'm confused, but when I upgraded ionic to version 4, it installs this typings, which throws a compile error  "NodeJS  has no exported member WiteStream"

Perhaps I have the wrong version of the node typings, I'm on version 7 where this is breaking, changing it to this is what fixed the compile issues for me, but it could be the wrong type.

2018-08-17 22:59 UTC, uniqueiniquity commented
I just created a new project using ionic 4 and the following compiled fine:
```
import inquirer from "inquirer";
inquirer.createPromptModule({ output: {} as NodeJS.WriteStream });
```
This is with @types/inquirer version 0.0.42, ionic version 4.1.0, and @types/node version 7.0.69.

2018-08-17 23:54 UTC, uniqueiniquity requested changes
Marking as changes requested until justification given for the change.

2018-08-22 19:28 UTC, closed without merging