[joi]  Added missing attributes in UriOptions
DefinitelyTyped/DefinitelyTyped pull request #28175
Opened 2018-08-16 14:44 UTC by k7sleeper

Add missing optional attributes `allowRelative` and `relativeOnly ` to `UriOptions` as stated in [api doc](https://github.com/hapijs/joi/blob/v13.4.0/API.md#stringurioptions).

2018-08-17 02:06 UTC, rokoroku reviewed
I think you'd better match indent :)

2018-08-19 11:48 UTC, SimonSchick requested changes
The changes look good but please fix indenting.

2018-08-22 09:07 UTC, SimonSchick approved these changes

2018-08-22 09:08 UTC, rokoroku approved these changes

2018-08-24 22:00 UTC, merged