add Parse.Query.and
DefinitelyTyped/DefinitelyTyped pull request #28182
Opened 2018-08-16 19:10 UTC by kyawswarthwin

Please fill in this template.

- [ add Parse.Query.and in @types/parse] Use a meaningful title for the pull request. Include the name of the package modified.
- [yes already test it ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: http://parseplatform.org/Parse-SDK-JS/api/v2.0.1/Parse.Query.html#.and
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-08-16 19:12 UTC, kyawswarthwin commented
add Parse.Query.and in @types/parse

2018-08-17 15:13 UTC, jaeggerr commented
Looking at the documentation, the method accepts a variable number of arguments. Your definition only accepts two.

You should do something similar to Query.or.

```typescript
static and<U extends Object>(...var_args: Query<U>[]): Query<U>;
```

2018-08-21 20:18 UTC, jaeggerr requested changes

2018-08-21 20:18 UTC, jaeggerr commented on types/parse/index.d.ts
> +        static and<U extends Object>(arg0: Query<U>, arg1: Query<U>): Query<U>;
Should accept a variable number of arguments
static and<U extends Object>(...var_args: Query<U>[]): Query<U>;

2018-08-28 20:33 UTC, closed without merging