add express-wechat-access types
DefinitelyTyped/DefinitelyTyped pull request #28232
Opened 2018-08-20 10:12 UTC by simmons8616

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-08-22 08:11 UTC, plantain-00 requested changes
The package is written by typescript, it contains types: https://github.com/simmons8616/express-wechat-access/blob/master/package.json#L5

2018-08-22 08:52 UTC, simmons8616 commented
@plantain-00 
I have deleted the types in package.json. （https://github.com/simmons8616/express-wechat-access/blob/master/package.json#L5）

2018-08-22 12:40 UTC, plantain-00 requested changes

2018-08-22 12:40 UTC, plantain-00 commented on types/express-wechat-access/tsconfig.json
> +        "strictNullChecks": false,
For new packages, it should enabled by default

2018-08-22 12:40 UTC, plantain-00 commented on types/express-wechat-access/tslint.json
> +    "extends": "dtslint/dt.json",
For new packages, this file should only `"extends": "dtslint/dt.json"`

2018-08-23 10:04 UTC, simmons8616 commented
@plantain-00 
Thank you for your suggestion, I have corrected all of them according to your suggestions.

2018-08-23 10:46 UTC, plantain-00 approved these changes

2018-08-24 23:03 UTC, merged

2018-08-24 23:03 UTC, DanielRosenwasser commented
Thanks all!