[koa-passport] Update authenticate to support object for options
DefinitelyTyped/DefinitelyTyped pull request #28255
Opened 2018-08-21 04:14 UTC by kevinschoonover

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: **Different strategies require more complex AuthenticationOptions and extending from passport.AuthenticationOptions makes options such as `hd` in** [passport-google-oauth2](https://github.com/jaredhanson/passport-google-oauth2/blob/master/lib/strategy.js#L159) **break**. **Moreover, `hd` is not generic enough to be added to the parent `AuthenticationOptions`. I believe this breaks more cases, `hd` is just a specific attribute I am using in my application.** 
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

I apologize if this pull request seems naive, I just do not know another solution for extending the AuthenticationOptions within different strategies as it currently prevents usage of `hd` and `hostedDomain`. These two options work when `koa-passport` is not installed. See the package [here](https://github.com/jaredhanson/passport-google-oauth2).

2018-08-27 10:25 UTC, brendtumi reviewed
I believe this type of change on AuthenticateOptions should made in passport not in koa-passport.

2018-08-27 10:27 UTC, brendtumi requested changes
I believe this type of change on `AuthenticateOptions` should made in [passport](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/passport) not in koa-passport.

2018-08-27 19:39 UTC, kevinschoonover commented
The change is not geared towards `AuthenticateOptions` per say. From my understanding, the `AuthenticateOptions` in [passport](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/passport) focuses on options that are generic to any strategy. See [this pr](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27337) for context to that. However, I was not able to replicate the overwrite/extending strategies mentioned in that PR with how koa-passport imports `passport.AuthenticateOptions`.

If I remove `@types/koa-passport` both [passport-google-oauth](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-google-oauth/index.d.ts) and [passport-facebook](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/passport-facebook/index.d.ts) work as expected.

A code example:
```

2018-09-02 14:11 UTC, brendtumi approved these changes

2018-09-05 15:45 UTC, merged