pouchdb-upsert: fixes to the UpsertDiffCallback type
DefinitelyTyped/DefinitelyTyped pull request #28258
Opened 2018-08-21 07:39 UTC by zamb3zi

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pouchdb/upsert#example-3
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-08-21 07:39 UTC, zamb3zi commented
• true is not a valid return value since only falsey values or documents are allowed. Returning true results in a runtime error (Cannot create property '_id' on boolean 'true').
• Other falsey values (such as '', null, 0 and undefined) may be returned and cause the upsert to be cancelled.
• As per the documentation, "You can also return a new object. The _id and _rev are added automatically", so the document return type must be Content & Partial<Core.IdMeta> as compared to Core.Document<Content> which is equal to Content & IdMeta.
• The _id property is removed from the test case UpsertDocModel Content type because this is added by Core.Document.

2018-08-21 23:06 UTC, keithdmoore approved these changes

2018-08-23 16:56 UTC, DanielRosenwasser requested changes

2018-08-23 16:56 UTC, DanielRosenwasser commented on types/pouchdb-upsert/index.d.ts
> +// Type definitions for pouchdb-upsert 2.3
Can you roll back the version? We try to correspond to MAJOR.MINOR on definitelytyped

2018-08-24 05:50 UTC, merged

2018-08-24 05:50 UTC, DanielRosenwasser commented
Thanks!