Adding types for `expired-storage` npm package
DefinitelyTyped/DefinitelyTyped pull request #28283
Opened 2018-08-21 22:33 UTC by intolerance

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-08-22 08:21 UTC, plantain-00 requested changes

2018-08-22 13:40 UTC, intolerance commented on types/expired-storage/tsconfig.json
> +        "strictNullChecks": false,
Thanks for your review. I've set `strictNullChecks` to `true`.

2018-08-22 13:42 UTC, intolerance commented on types/expired-storage/tslint.json
> +    "extends": "dtslint/dt.json",
tslint now purely uses `dt.json` with no exceptions.

2018-08-22 21:56 UTC, plantain-00 approved these changes

2018-08-24 20:58 UTC, DanielRosenwasser commented on types/expired-storage/expired-storage-tests.ts
> +  familyName: 'Keenan',
Nice.

2018-08-24 21:01 UTC, DanielRosenwasser requested changes

2018-08-24 21:01 UTC, DanielRosenwasser commented on types/expired-storage/expired-storage-tests.ts
> +// const expiredStorage = new ExpiredStorage(localStorage); // ExpiredStorage requires a LocalStorage provider
Can you just remove the comments?

2018-08-28 00:46 UTC, merged

2018-08-28 00:46 UTC, DanielRosenwasser commented
Thanks!