add createIntersectionObserver for weixin-app
DefinitelyTyped/DefinitelyTyped pull request #28316
Opened 2018-08-23 07:23 UTC by deepcoldy

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://developers.weixin.qq.com/miniprogram/dev/api/intersection-observer.html#wxcreateintersectionobserverthisoptions>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-08-23 09:34 UTC, AlexStacker approved these changes

2018-08-23 09:47 UTC, taoqf requested changes

2018-08-23 09:47 UTC, taoqf commented on types/weixin-app/index.d.ts
> +        relativeTo: (selector?: string, margins?: margins) => createIntersectionObserverCallBack;
try this:
```ts
relativeTo(selector?: string, margins?: margins): createIntersectionObserverCallBack;
```

2018-08-24 02:54 UTC, taoqf approved these changes

2018-08-24 21:49 UTC, DanielRosenwasser commented
Can you resolve the merge conflicts? Sorry!

2018-08-25 06:25 UTC, Jimexist commented on types/weixin-app/index.d.ts
> +    interface createIntersectionObserverOption {
upper camel case?

2018-08-25 06:25 UTC, Jimexist commented on types/weixin-app/index.d.ts
> +    interface margins {
upper camel case?

2018-08-25 06:25 UTC, Jimexist commented on types/weixin-app/index.d.ts
> +    interface observeResponse {
upper camel case?

2018-08-25 06:25 UTC, Jimexist commented on types/weixin-app/index.d.ts
> +    interface createIntersectionObserverCallBack {
upper camel case?

2018-08-25 06:26 UTC, Jimexist commented on types/weixin-app/index.d.ts
> +        boundingClientRect: {
upper camel case?

2018-09-01 14:21 UTC, jimexist approved these changes

2018-09-05 15:50 UTC, minestarks commented
@deepcoldy if you could resolve the conflicts I'll merge. Thanks!

2018-09-05 16:06 UTC, deepcoldy commented
@minestarks Done. Thanks.

2018-09-07 22:04 UTC, merged