lodash modularized: allow for import syntax without require()
DefinitelyTyped/DefinitelyTyped pull request #28329
Opened 2018-08-23 16:07 UTC by gdelmas

The proposed changes would allow for importing modularized lodash functions like this:

    import * as flowRight from 'lodash.flowright';

currently only the following syntax is supported (which after the change still will work)

    import flowRight = require('lodash.flowright'); and 

_If you all agree with the change, before merging the type definitions will have to be re-generated with `generate-modules.ts`_

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/21085#issuecomment-362910453
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-08-23 16:26 UTC, gdelmas commented
cc: @aj-r

2018-08-23 16:57 UTC, aj-r requested changes
You also need to run the script before committing, otherwise it will have no effect :)

2018-08-23 23:32 UTC, aj-r commented
After thinking about this more, I'm not sure if we should do this. The namespace trick is actually a hack, and the fact that it makes `import *` work is apparently a bug (https://github.com/Microsoft/TypeScript-Handbook/issues/350). TypeScript 2.7 added the `esModuleInterop` compiler option to address this. Anyone using TS 2.7 or later should use `esModuleInterop` and import like this:

```ts
import flowRight from "lodash.flowright";
```

This method works even without the namespace hack.

The only issue is that lodash still supports TS 2.6, and you can't use the above method in TS 2.6. But maybe it's best for those people to continue using the require method:

```ts
import flowRight = require("lodash.flowright");
```

Does `require()` cause problems for anyone? Of not, I would prefer to update the readme to show both the `esModuleInterop` method and the `require()` method, and get rid of the `import *`  method.

2018-08-24 06:29 UTC, gdelmas commented
i could not get the esModuleInterop method to work in TypeScript 3.0.

2018-08-24 12:06 UTC, aj-r commented
It worked for me in TS 2.8. I will try again with 3.0.

On Fri, Aug 24, 2018, 2:29 AM Gerard Delmàs, <notifications@github.com>
wrote:

> i could not get the esModuleInterop method to work in TypeScript 3.0.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/28329#issuecomment-415664582>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AGpes-VMxu-CRY1aa-psvyn9MnVswC-bks5uT51ZgaJpZM4WJ1iz>
> .
>

2018-09-27 10:07 UTC, dljcollette commented
> It worked for me in TS 2.8. I will try again with 3.0.
> […](#)
> On Fri, Aug 24, 2018, 2:29 AM Gerard Delmàs, ***@***.***> wrote: i could not get the esModuleInterop method to work in TypeScript 3.0.

@aj-r Did it work for you in 3.0?

2018-10-10 20:06 UTC, andy-ms commented
It looks like the type definitions are already correct and `--esModuleInterop` is working fine for me with `import add from "lodash.add";` with `@types/lodash.add` installed. We're not adding new `namespace {}` hacks.

2018-10-10 20:06 UTC, closed without merging

2018-10-23 12:34 UTC, gdelmas commented
hi @andy-ms,

i'm all for not having the namespace hack. yet i can not reproduce the `import get from "lodash.get";` working with `"esModuleInterop": true` in `tsconfig.json`.

i'm getting: `TS1192: ... 'node_modules/@types/lodash.get/index"' has no default export.`