Dialogflow: Added sentiment analysis to query result payload
DefinitelyTyped/DefinitelyTyped pull request #28430
Opened 2018-08-27 15:36 UTC by beeme1mr

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://dialogflow.com/docs/reference/api-v2/rpc/google.cloud.dialogflow.v2beta1#queryresult
- [X] Increase the version number in the header if appropriate.

2018-08-27 17:29 UTC, dyladan approved these changes
This looks good to me and I can confirm the payload and documentation both match this type. I'm the original contributor of these types :)

edit: see later review

2018-08-27 17:30 UTC, dyladan commented
This has the unowned tag, but I originally contributed these types. Is there a way I can take ownership of this? Or does "owner" refer to the owner of the package being referenced by the types?

2018-08-27 19:00 UTC, dyladan requested changes

2018-08-27 19:00 UTC, dyladan commented on types/dialogflow/index.d.ts
> +// Type definitions for dialogflow 0.7
This is the version of the package being typed. Still at 0.6

2018-08-27 19:09 UTC, dyladan approved these changes
Better thanks

2018-08-27 19:47 UTC, dyladan commented
@RyanCavanaugh Any idea why @typescript-bot doesn't recognize me as the author?

2018-08-27 20:56 UTC, RyanCavanaugh commented
@dyladan looks like the CODEOWNERS file is out of date. I'll have someone update it

2018-08-28 17:26 UTC, dyladan approved these changes
Trying to add another review after CODEOWNERS file change

2018-08-31 23:04 UTC, merged