Patch 5
DefinitelyTyped/DefinitelyTyped pull request #28471
Opened 2018-08-29 00:59 UTC by rycornell

See docs here https://github.com/libxmljs/libxmljs/wiki/Namespaces

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/libxmljs/libxmljs/wiki/Namespaces>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-08-29 06:45 UTC, ComFreek requested changes
Thanks for the PR! I'll approve it as soon as you switch the double quotes to the single quotes 👍

2018-08-29 06:45 UTC, ComFreek commented on types/libxmljs/libxmljs-tests.ts
> +const gchildWithNs = xmlDocWithNs.get('//a:grandchild', {a: "http://test.com/test"})!;
Really minor comment: It would be nice to stay consistent with single quotes.

2018-08-29 06:45 UTC, ComFreek commented on types/libxmljs/index.d.ts
> +    get(xpath: string, namespaces?: { [key: string]: string; }): Element|null;
I see the type `{ [key: string]: string; }` in multiple places in this file. Is is possible to outsource it, e.g. define `NamespaceLiteral` (or any other name) once and then only use that name everywhere? Namely, without exposing `NamespaceLiteral` to consumers of this typing package.

I think I tried this once months ago and could not find a way to do it.

2018-08-29 06:47 UTC, ComFreek commented
Also, maybe it would be nice to mention this function overload in the official libxmljs documentation under `Document` as well: https://github.com/libxmljs/libxmljs/wiki/Document/_edit.

2018-08-29 23:14 UTC, rycornell commented
Thanks @ComFreek, I've updated the wiki https://github.com/libxmljs/libxmljs/wiki/Document/

2018-08-30 07:37 UTC, ComFreek approved these changes

2018-08-30 17:48 UTC, merged