web3 type definition: fix typo: ssh to shh
DefinitelyTyped/DefinitelyTyped pull request #28606
Opened 2018-09-03 14:46 UTC by clchiang

According to the web3 documentation,  (https://web3js.readthedocs.io/en/1.0/web3-shh.html), the module inside the web3 object is named `shh` instead of `ssh`.

2018-09-03 17:51 UTC, zlumer approved these changes
Good catch!

2018-09-03 23:24 UTC, yxliang01 approved these changes
LGTM

2018-09-04 04:23 UTC, levino requested changes
Please add a regression test.

2018-09-05 17:44 UTC, phra approved these changes

2018-09-06 06:08 UTC, Levino commented
#28645 is now a better suggestion than this. Please close this PR @ilovecodingxyz . Thank you for your contribution. If you have futher additions to this PR please create a PR to the branch of #28645 .

2018-09-07 22:30 UTC, sana-ajani commented
Merged PR #28645 and closing this one.

2018-09-07 22:30 UTC, closed without merging

2018-09-08 09:08 UTC, Levino commented
@sana-ajani the other PR has not been merged