[@types/validator] Add no_symbols as option
DefinitelyTyped/DefinitelyTyped pull request #28600
Opened 2018-09-03 12:46 UTC by henrikra

Types for `validator` was missing options for function `isNumeric`

Here is picture of documentation for `isNumeric`
![image](https://user-images.githubusercontent.com/12229968/44987597-6b96da80-af90-11e8-8855-3f0de445cd47.png)

Here is also implementation for that function: https://github.com/chriso/validator.js/blob/c192d7c442193d790f5497d92267931d48b2dbc8/src/lib/isNumeric.js

2018-09-03 13:11 UTC, henrikra commented
The CI is failing but it is not this library it is `sequelize`
![image](https://user-images.githubusercontent.com/12229968/44988635-0fce5080-af94-11e8-8337-0d7adea8f322.png)

2018-09-03 13:13 UTC, henrikra commented
@qqilihq @builtinnya Can you guys check this out?

2018-09-03 16:43 UTC, qqilihq requested changes

2018-09-03 16:43 UTC, qqilihq commented on types/validator/index.d.ts
> +    isNumeric(str: string, options?: { no_symbols?: boolean }): boolean;
I would suggest introducing an interface `IsNumericOptions` in order to adhere to the current structure.

2018-09-03 16:43 UTC, qqilihq commented on types/validator/validator-tests.ts
> +  result = validator.isNumeric('+358', { no_symbols: true })
Add trailing `;`

2018-09-03 18:40 UTC, henrikra commented
What about now @qqilihq ?

Btw one thing that which came to my mind is that should we also export interfaces of different options? Because for example library called `class-validator` is using `validator` library as dependency and they are *redefining* types in this package. For example `IsCurrencyOptions` on this package: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/validator/index.d.ts#L280 and on `class-validator` are exactly the same. I think this isn't that great. I think the solution would be to export interface from this package so other packages could use them :). What do you think?

2018-09-03 19:33 UTC, qqilihq commented
@henrikra Looks good to me 👍 

About the failing build: Not sure what's going on here. I'm just a contributor to this specific package, so I've no clue, why the CI is failing. But it's obviously not caused by your changes, so I'd suggest getting in touch with one of the Definitely Typed admins/maintainers, and/or opening a separate issue about it.

2018-09-03 19:38 UTC, henrikra commented
Good to hear. Did you get what I was trying to say with exporting options interfaces?

2018-09-04 10:53 UTC, qqilihq commented
> Did you get what I was trying to say with exporting options interfaces?
Sorry, just had time to have a close look/thought. I'd agree with you that exporting would make sense. But I'm not a TS/DT expert, so I'd suggest waiting for further opinions!

2018-09-06 12:07 UTC, henrikra commented
@builtinnya Can you check this out?

2018-09-07 04:07 UTC, builtinnya commented
@henrikra 
LGTM :+1: 
The same error as CI can be reproduced on current master (2ae8bc7a1c05064713371851d1a7ce26f02f8841) by running `npm run lint  sequelize`.
It should have nothing to do with your change.
I agee to exporting options interfaces.

2018-09-07 05:04 UTC, henrikra commented
@builtinnya I can add those exports to this PR too if it is ok?

2018-09-07 06:04 UTC, builtinnya commented
@henrikra 
I'd recommend that you add those exports in a separated PR for clarity.
I will review your PR then.

2018-09-07 06:42 UTC, henrikra commented
Ok I can do that :) Can we merge this?

2018-09-07 07:13 UTC, builtinnya commented
As @qqilihq suggested, we need to get in touch with one of maintainers OR resolve the build error.
Some pull requests based on 2ae8bc7a1c05064713371851d1a7ce26f02f8841  this have passed CI, so this PR will also pass if you re-run the tests.
Can you rebase your commits or something like that to trigger the CI again?

2018-09-07 08:16 UTC, henrikra commented
@builtinnya I did rebase new master to my PR but still it has the same error. 

@IOAyman @uniqueiniquity Can check this out so this can be merged?

2018-09-07 09:32 UTC, bhanuy commented
tested and works for me..

2018-09-13 09:38 UTC, henrikra commented
@IOAyman @mhegazy @minestarks Can you guys check this and merge? The issue with CI is not made by this PR!

2018-09-13 15:37 UTC, uniqueiniquity commented
@henrikra I'm rerunning the build, let's see if that fixes anything.

2018-09-13 18:50 UTC, henrikra commented
@uniqueiniquity As you can see this has something to do with `sequelize` and my code cannot change that 
![image](https://user-images.githubusercontent.com/12229968/45509025-0f596500-b79f-11e8-955c-b53da45f8beb.png)

2018-09-13 23:51 UTC, merged