Added types for urlencode
DefinitelyTyped/DefinitelyTyped pull request #28633
Opened 2018-09-04 21:10 UTC by htunnicliff

## urlencode

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-09-05 19:33 UTC, tup1tsa commented
It should be possible to use this module by calling it directly
`import urlencode = require('urlencode')`
[https://github.com/node-modules/urlencode/blob/feb6a0897490e7d12a248a10da8ae8e2744d1e88/lib/urlencode.js#L223](url)

2018-09-07 23:50 UTC, minestarks requested changes

2018-09-07 23:50 UTC, minestarks commented on types/urlencode/tslint.json
> +    "semicolon": false
Please don't turn off linter rules, it makes typings much easier to read if they're uniform across the project.

2018-09-14 01:57 UTC, htunnicliff commented
@typescript-bot I’ll make the changes shortly.

2018-09-15 00:25 UTC, closed without merging