koa-router: Router verb handlers support array of paths
DefinitelyTyped/DefinitelyTyped pull request #28949
Opened 2018-09-17 16:27 UTC by andywer

See <https://github.com/alexmingoia/koa-router/blob/590df78ef38a557e9ce86a14bd9bfe567c5701a1/lib/router.js#L543-L550>.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/alexmingoia/koa-router/blob/590df78ef38a557e9ce86a14bd9bfe567c5701a1/lib/router.js#L543-L550>
- [ ] ~~~Increase the version number in the header if appropriate.~~~
- [ ] ~~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~~

2018-09-18 07:16 UTC, romain-faust requested changes
Correct me if I'm wrong but I think that it should be:
```typescript
path: string | RegExp | (string | RegExp)[]
```

2018-09-18 12:02 UTC, JounQin requested changes
https://github.com/alexmingoia/koa-router/blob/590df78ef38a557e9ce86a14bd9bfe567c5701a1/lib/router.js#L194-L200

When `path` is not `string` neither `RegExp` (Array here), it will be considered as `middleware`, so your changed lines are incorrect, they should be the next lines which do not contains parameter `name`.

2018-09-19 08:06 UTC, romain-faust approved these changes

2018-09-19 08:27 UTC, JounQin approved these changes

2018-09-19 21:01 UTC, merged