styled-components fix: Define StyleSheet and change Node to React.ReactNode
DefinitelyTyped/DefinitelyTyped pull request #29022
Opened 2018-09-19 15:56 UTC by nicogreenarry

As referenced [here](https://github.com/styled-components/styled-components/issues/1952), the `StyleSheet` and `Node` types were undefined. This PR defines `StyleSheet`, and replaces `Node` with `React.ReactNode`, following the example found [here](https://github.com/styled-components/styled-components/pull/1954).

Request for community help: I intend to use these changes in my project to try to catch any errors they cause, but I won't be able to do that for a few weeks. If anyone else has a chance to test these changes in the meantime, I'd appreciate you leaving some comments on this PR. Also, first-time DefinitelyTyped contributor here, so let me know if there are things I should be doing differently in this PR 😀 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
  - TODO. I won't have time to test this for a few weeks, but I wanted to get this PR up so others could see and comment on it in the meantime.
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
  - No tests added/changed; tests passed
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint styled-components` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-09-19 17:41 UTC, Igorbek requested changes
I was not sure how this `target` prop was used and looked the code:

https://github.com/styled-components/styled-components/blob/cb7d90c3a138df0a5defc561574e9cb2e1f2bd81/src/models/StyleSheetManager.js#L27-L29

and

https://github.com/styled-components/styled-components/blob/cb7d90c3a138df0a5defc561574e9cb2e1f2bd81/src/models/StyleSheet.js#L49

it seems it is used as a DOM Node, not a React Node.
So the type was correct. Let me see what the issue was in the first place...

2018-09-20 15:48 UTC, nicogreenarry commented
@Igorbek thanks for looking. `Node` isn't defined, though it's possible I have an incorrect typescript setup. I tried including "DOM" in the typescript `lib` config array, but `Node` was still undefined. Maybe it should be `HTMLElement`, or perhaps `HTMLElement | null`? I'm going to push that change, since `ReactNode` is definitely wrong.

2018-09-20 16:12 UTC, nicogreenarry commented
Ah. I think what we actually want is to add this to the top of the file:
`/// <reference lib="dom" />`

2018-09-21 15:00 UTC, nicogreenarry commented
Sigh. Maybe I'm seeing ghosts. The entire premise for this fix was that the `.d.ts` file failed to properly define/reference the DOM library. I've tried various fixes in this repo, and have run into various test failures. I tried fixing the issue again locally, on the premise that maybe these types are just fine as they are, and it's my own local typescript config that has problems. And, after upgrading to `styled-components@beta`, and ensuring that "dom" is listed as one of my lib's in my `tsconfig.json`, the compilation errors went away. So there's nothing to see here, folks, nothing at all!

2018-09-21 15:00 UTC, closed without merging

2018-09-21 17:26 UTC, Igorbek commented on types/styled-components/index.d.ts
> +// TypeScript Version: 3.0
oops, didn't see you closed this.