node: Export Http2ServerRequest and Http2ServerResponse as class
DefinitelyTyped/DefinitelyTyped pull request #29173
Opened 2018-09-25 07:37 UTC by ofavre

I'm basically refiling #26048 now that #26063 is merged.

----

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

> Sorry but `npm run lint package-name` gives me:
> 
> ```
> > definitely-typed@0.0.3 lint /data/notiflex/gits/DefinitelyTyped-wonderpush
> > dtslint types "node"
> 
> Error: Since this type definition includes a header (a comment starting with `// Type definitions for`), assumed this was a DefinitelyTyped package.
> But it is not in a `DefinitelyTyped/types/xxx` directory.
>     at assertPathIsInDefinitelyTyped (/data/notiflex/gits/DefinitelyTyped-wonderpush/node_modules/dtslint/bin/index.js:112:15)
>     at /data/notiflex/gits/DefinitelyTyped-wonderpush/node_modules/dtslint/bin/index.js:93:13
>     at Generator.next (<anonymous>)
>     at fulfilled (/data/notiflex/gits/DefinitelyTyped-wonderpush/node_modules/dtslint/bin/index.js:5:58)
>     at <anonymous>
> ```
> 
> And greping for `Type definitions for` only gives results under `node_modules/`.

> And `npm test` seems to fail for this reason.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_class_http2_http2serverrequest and https://nodejs.org/dist/latest-v8.x/docs/api/http2.html#http2_class_http2_http2serverresponse
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-09-25 09:08 UTC, ThomasdenH approved these changes

2018-09-25 09:48 UTC, islishude approved these changes

2018-09-25 11:36 UTC, danielrentz commented
> > Sorry but `npm run lint package-name` gives me:
> > ```
> > > definitely-typed@0.0.3 lint /data/notiflex/gits/DefinitelyTyped-wonderpush
> > > dtslint types "node"
> > 
> > Error: Since this type definition includes a header (a comment starting with `// Type definitions for`), assumed this was a DefinitelyTyped package.
> > But it is not in a `DefinitelyTyped/types/xxx` directory.

The code must be located in a directory named "DefinitelyTyped" (e.g. /data/notiflex/gits/DefinitelyTyped) to get rid of this error.

2018-09-25 11:39 UTC, ZaneHannanAU approved these changes

2018-09-25 14:57 UTC, mohsen1 commented
Do constructors get any arguments?

2018-09-26 08:11 UTC, ofavre commented
> Do constructors get any arguments?

This is not documented, but `http2.Http2ServerRequest.length` is 4 and it fails to construct if given no arguments.
Looking at NodeJS [source](https://github.com/nodejs/node/blob/v8.12.0/lib/internal/http2/compat.js#L213) [code](https://github.com/nodejs/node/blob/v8.12.0/lib/internal/http2/compat.js#L348) I can try to infer their type.
Shall I add them?

I also noticed that `Http2ServerRequest` exposes `httpVersionMajor` and `httpVersionMinor` which are not present in the official documentation.
Shall I add these too?

2018-09-26 09:01 UTC, ThomasdenH commented
Yes, it might be better to leave it an interface. An improvement would be to make the members `readonly`.

2018-09-26 15:04 UTC, ThomasdenH commented
I guess it makes sense to follow the source code as closely as possible. Can a private constructor be added to prevent instantiation?

2018-09-26 17:09 UTC, Flarna commented
I think use of `instanceof` is a valid use case.

Declaration files created by Typescript compiler include private fields.
```
export class Foo {
	private constructor(private i: number) {}
	get_i(): number { return this.i; }
}
```
results in
```
export declare class Foo {
    private i;
    private constructor();
    get_i(): number;
}
```
==> type annotations are  removed in declaration files
Adding private members in classes have the additional advantage that derived classes can't add public members with same name.

@ofavre Do you have a specific use case why you change interface to class here?

2018-09-27 17:58 UTC, amcasey commented
@ofavre it looks like @Flarna still has an outstanding question.

2018-10-02 04:18 UTC, weswigham requested changes
Marking as having an unresolved comment until @Flarna 's comments are responded to.

2018-10-02 15:54 UTC, ofavre commented
> I think use of `instanceof` is a valid use case.
> @ofavre Do you have a specific use case why you change interface to class here?

I was precisely trying to use `instanceof`. :slightly_smiling_face:

2018-10-02 15:57 UTC, ofavre commented
I'm OK with adding a private constructor.
What private fields are we talking about?
I'll edit my PR to add a private constructor with no parameters, and no private fields.

I'll do a separate PR afterwards for adding `httpVersionMajor` and `httpVersionMinor`, that I didn't see in the bottom of the documentation of `httpVersion`.

2018-10-02 16:16 UTC, ofavre commented
`npm run lint node` runs fine now that I've rename my repo folder.
The types compile fine in my code.

2018-10-02 17:09 UTC, Flarna approved these changes

2018-10-02 17:13 UTC, weswigham approved these changes

2018-10-02 17:13 UTC, merged

2018-10-03 07:04 UTC, ThomasdenH commented
Great.