[@google-cloud/datastore] Fix ES6/ES2015 import syntax
DefinitelyTyped/DefinitelyTyped pull request #29224
Opened 2018-09-27 12:51 UTC by arjenvanderende

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This PR reintroduces the namespace that was removed in #27900. The removal broken ES6-style import for this package:

```javascript
import * as Datastore from "@google-cloud/datastore";
```

When the package is imported in this way, this results in the following compile error:

```
Module ''@google-cloud/datastore'' resolves to a non-module entity and cannot be imported using this construct.
```

This import style used to work with older versions of the type definitions for this package.
I've updated the import in the tests as well to cover this behaviour.

2018-09-27 14:04 UTC, beaulac approved these changes
Hopefully everyone is running with `allowSyntheticDefaultImports: true` :)

2018-09-27 18:30 UTC, amcasey requested changes
This anti-pattern is discouraged: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#should-i-add-an-empty-namespace-to-a-package-that-doesnt-export-a-module-to-use-es6-style-imports

2018-10-03 14:43 UTC, arjenvanderende commented
So `import Datastore = require("@google-cloud/datastore");` is the preferred way to fix issue?
I guess there's nothing to fix here then...

2018-10-03 14:43 UTC, closed without merging

2018-10-03 17:17 UTC, amcasey commented
@arjenvanderende, yes, if you'd like `DataStore` to be callable/newable, that form is preferable to an ES6 import.