[jquery] Change all `HTMLElement` to be `Element`
DefinitelyTyped/DefinitelyTyped pull request #29282
Opened 2018-09-29 03:31 UTC by boriskor

This PR fixes the inconsistencies introduced by #29212 by changing **all** `HTMLElement` usages to `Element` to reflect the fact that jQuery can operate elements other than HTML (e.g. SVG).
Example of broken code after the change introduced in #29212:
```typescript
const itemEl = $('#item')[0];
$('li').toArray().indexOf(itemEl); // error TS2345: Argument of type 'Element' is not assignable to parameter of type 'HTMLElement'.
```

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://api.jquery.com/jQuery.parseHTML/>
<https://api.jquery.com/toArray/>
<https://api.jquery.com/get/#get-index>
<https://api.jquery.com/get/#get>
- [ ] Increase the version number in the header if appropriate. **Should be non-breaking**
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-09-29 11:01 UTC, boriskor commented
While we're at it, shouldn't we consider changing [jqLite] (/DefinitelyTyped/DefinitelyTyped/blob/master/types/angular/jqlite.d.ts#L29) and [jQuery v3](/DefinitelyTyped/DefinitelyTyped/blob/master/types/jquery/index.d.ts#L145) types? WDYT?

2018-10-01 09:27 UTC, boriskor commented
> This is actually a breaking change.

Of course, you're right, it's a breaking change, got confused by the  #29212 which was marked as a non-breaking change.

> jqLite should at least be tested to ensure that it merges correctly with v2 declarations. It's not currently possible to test multiple jQuery versions automatically under the current infrastructure

Indeed, I've tried to setup it locally and couldn't make it work.

Anyway, it seems that jqLite can't support both v2 & v3 properly in it's current form. If I change 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/118bdba29e0a94778a7e46cb6e33dd26f9ee484c/types/angular/jqlite.d.ts#L29
to `Element` instead of `HTMLElement`, it starts clashing with v3 (`Interface 'JQLite' incorrectly extends interface 'JQuery<HTMLElement>'`)

With all that being said, is anything missing from this PR to be merged? 🙂

2018-10-02 21:24 UTC, leonard-thieu requested changes

2018-10-02 23:07 UTC, leonard-thieu commented on types/jquery/v2/index.d.ts
> +    parseHTML(data: string, context?: Element, keepScripts?: boolean): any[];
Just realized the `Document` overload is already there. In that case, this overload should be removed.

2018-10-03 09:08 UTC, boriskor commented on types/jquery/v2/index.d.ts
> +    parseHTML(data: string, context?: Element, keepScripts?: boolean): any[];
Done!

2018-10-03 14:01 UTC, leonard-thieu approved these changes

2018-10-03 18:53 UTC, merged

2018-10-19 15:37 UTC, michaelaird commented
These are acknowledged as breaking changes. Why was this released as patch version?

2018-10-19 15:50 UTC, leonard-thieu commented
`@types` packages do _not_ use semver. Packages are locked to the MAJOR.MINOR version of the library they represent. I recommend locking the versions of your `@types` packages to avoid unexpected breaking changes.