Adding next-redux-saga types
DefinitelyTyped/DefinitelyTyped pull request #29383
Opened 2018-10-02 19:07 UTC by leocavalcante

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

Closes https://github.com/bmealhouse/next-redux-saga/issues/5

2018-10-06 23:31 UTC, plantain-00 requested changes

2018-10-06 23:31 UTC, plantain-00 commented on types/next-redux-saga/tslint.json
> +    "extends": "dtslint/dt.json",
For new packages, this file should only `"extends": "dtslint/dt.json"`

2018-10-07 02:58 UTC, plantain-00 approved these changes

2018-10-08 17:19 UTC, ghost requested changes

2018-10-08 17:19 UTC, andy-ms commented on types/next-redux-saga/index.d.ts
> +export default nextReduxSaga;
`require("next-redux-saga")` is itself a function, not an object with a `default` property. So this should be `export = nextReduxSaga;`.

2018-10-08 17:44 UTC, andy-ms commented on types/next-redux-saga/next-redux-saga-tests.tsx
> +import withReduxSaga from 'next-redux-saga';
This should be `import withReduxSaga = require('next-redux-saga')`, or you could add `"esModuleInterop": true` to `tsconfig.json` compiler options.

2018-10-08 18:39 UTC, merged

2018-10-08 18:43 UTC, leocavalcante commented
Awesome! cc @bmealhouse

2018-10-09 02:46 UTC, bmealhouse commented
Thanks @leocavalcante!