react-image-crop update types
DefinitelyTyped/DefinitelyTyped pull request #29494
Opened 2018-10-06 02:46 UTC by skvale

* Add className prop
* Add onImageError prop
* Update onImageLoaded prop to take pixelCrop as a second argument

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DominicTobias/react-image-crop/blob/master/lib/ReactCrop.js
- [x] Increase the version number in the header if appropriate.

2018-10-07 16:04 UTC, danielasy requested changes
Hi @skvale! I looked at `react-image-crop` [releases](https://github.com/DominicTobias/react-image-crop/releases) and it seems some of the types you updated were changed in v4, so we should bump this to a major version before applying these updates. DefinitelyTyped has instructions on how to upgrade to a major version on their [FAQ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md). What do you think? Would you like to work on it?

2018-10-07 16:49 UTC, skvale commented on types/react-image-crop/index.d.ts
> +    function containCrop(previousCrop: Crop, crop: Crop, imageAspect: number): Crop;
This change was from v5.0.0

2018-10-07 16:52 UTC, skvale commented
@danielasy Looks like all that needs to be done is bump the version to 5.0?
> If you intend to continue updating the older version of the package, you may create a new subfolder with the current version e.g. v2, and copy existing files to it.

Doesn't seem to apply.

2018-11-01 23:47 UTC, DanielRosenwasser commented
@danielasy thoughts on whether I can pull this in?

2018-12-15 13:14 UTC, closed without merging