added typings for the panel plugin.
DefinitelyTyped/DefinitelyTyped pull request #29660
Opened 2018-10-11 18:36 UTC by nkappler

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

~If adding a new definition:~

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://codemirror.net/doc/manual.html#addon_panel
- [ ] ~Increase the version number in the header if appropriate.~
- [ ] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

~If removing a declaration:~

2018-10-11 18:47 UTC, nkappler commented
@mihailik @Pr1st0n

2018-10-15 12:09 UTC, mihailik requested changes
Thanks, great work closing the gap between official docs and typings!

It would be great to tweak it just tiny bit, for smoother neater readability, if thats OK.

Many thanks!

2018-10-15 12:09 UTC, mihailik commented on types/codemirror/codemirror-panel.d.ts
> +        changed: (height?: number) => void;
It's easier to read with method-like notation, no? Can we lose those extra arrow characters please?

```typescript
interface Panel {
  clear(): void;
  changed(height?: number): void;
}

2018-10-15 12:09 UTC, mihailik commented on types/codemirror/codemirror-panel.d.ts
> +        addPanel: (node: HTMLElement, options?: ShowPanelOptions) => Panel;
Here as well, please.

```typescript
addPanel(node: HTMLElement, options?: ShowPanelOptions): Panel;
```

2018-10-15 21:45 UTC, mihailik approved these changes
Awesome, thanks a lot @nkappler, appreciate extra effort there!

2018-10-15 22:19 UTC, merged