ElasticSearch - add "slices" option to UpdateDocumentByQueryParams and update Response too
DefinitelyTyped/DefinitelyTyped pull request #29717
Opened 2018-10-14 20:50 UTC by LakMoore

…for elasticsearch update_by_query
documentation: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/api-reference.html#api-updatebyquery

'slices' was missing and speeds up execution of update_by_query.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-10-15 00:26 UTC, pushplay requested changes
We should support slices in `deletebyquery` and `reindex` while we're at it.

In the [documentation ](https://www.elastic.co/guide/en/elasticsearch/reference/6.3/docs-update-by-query.html):

> Setting slices to auto will let Elasticsearch choose the number of slices to use.

Does that mean https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1f3d115a45ff927ff356c05103cba016b298670e/types/elasticsearch/index.d.ts#L787 should be `number | "auto"`?  

I also think the new interfaces could do with better naming.  `GenericUpdateResponse` is misleading because it's unrelated the response to `update()`.  `SliceUpdateResponse` feels incomplete and I'd prefer something like `UpdateDocumentByQueryResponseSlice`.

2018-10-15 07:59 UTC, LakMoore commented
Thanks for taking a look at this.

I tried ?slices=auto in Kibana and it gives the following error, but I haven't tried it using the JS Client.  Although the docs call for a number only!
```
"type": "illegal_argument_exception",
"reason":` "Failed to parse int parameter [slices] with value [auto]"
```

Agreed on the other two use cases for slices, but my API doesn't need those ;-) 
I'll take a look at coding a test case.

2018-10-16 12:13 UTC, LakMoore commented
These changes have not been tested.  Have put them here to see if you, @pushplay , agree with naming and arrangement, in principal.

Also, can I re-write the tests to actually do some work against a real es server, or is that a bad idea?

2018-10-16 15:53 UTC, pushplay commented
I like the `ResponseBase` naming.  `OrByQuery` still feels slightly janky to me.  What if `ReIndexOrByQueryResponseBase` was just `ReIndexResponseBase`?

Good call catching that some of those responses are identical.  I like how you preserved the interfaces.

Thanks for looking into that slice=auto thing.  The docs seem to indicate that should work but I'm happy to go with real experience.

> can I re-write the tests to actually do some work against a real es server, or is that a bad idea?

Most of our existing tests are based on documentation which I think is usually preferable because they can test a certain feature with reduced noise.  The test coverage in this file is pretty poor though.  I wouldn't replace anything existing but more tests are certainly welcome.

2018-10-16 19:05 UTC, LakMoore commented
Agreed, with thanks.
Have made the recommended changes and added a simple test for client.reindex()
Ready to merge?? :-)

2018-10-16 20:39 UTC, pushplay approved these changes
Looks good.  Thanks.

2018-10-16 21:41 UTC, merged