add types for storage-helper
DefinitelyTyped/DefinitelyTyped pull request #29806
Opened 2018-10-17 08:56 UTC by ajafff

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-10-17 18:21 UTC, sheetalkamat requested changes

2018-10-17 19:07 UTC, ajafff commented on types/storage-helper/index.d.ts
> +export function getItem(key: string): string | null;
done, although it's a bit messy. Note that I can't use `unknown` as return type for parsed items because TypeScript@3.0 is still not supported

2018-10-17 19:09 UTC, ajafff commented on types/storage-helper/index.d.ts
> +export as namespace StorageHelper;
Looks like it's an implementation detail. I looked it up in the published code: https://unpkg.com/storage-helper@1.4.1/dist/storage-helper.js

That's actually the only way to use this library in global scripts.

I can remove it if you want me to.

2018-10-17 20:10 UTC, sheetalkamat requested changes

2018-10-17 20:10 UTC, sheetalkamat commented on types/storage-helper/tslint.json
> +    "rules": {
We do not want any rules in the tslint for new definitions.

2018-10-18 15:39 UTC, sheetalkamat approved these changes

2018-10-18 15:39 UTC, merged