[doubleclick-gpt] Apply standard lint rules
DefinitelyTyped/DefinitelyTyped pull request #29982
Opened 2018-10-23 20:15 UTC by djcsdy

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [ ] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-10-24 08:27 UTC, johngeorgewright requested changes

2018-10-24 23:02 UTC, djcsdy commented on types/doubleclick-gpt/index.d.ts
> +// Type definitions for Google Publisher Tag 238.0
The standard linting rules do require this, yes.

```text
ERROR: 1:25  dt-header  Error parsing header. Expected: foo MAJOR.MINOR (Needs MAJOR.MINOR). See: https://github.com/Microsoft/dtslint/blob/master/docs/dt-header.md
```

2018-10-24 23:03 UTC, djcsdy commented on types/doubleclick-gpt/index.d.ts
> +        fetchMarginPercent?: number;
Every other interface already uses semicolons. This was the only exception.

2018-10-25 08:54 UTC, johngeorgewright approved these changes

2018-10-25 21:22 UTC, merged