[mongodb] Added arrayFilters to update operations
DefinitelyTyped/DefinitelyTyped pull request #29986
Opened 2018-10-24 00:11 UTC by wyattjoh

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#updateOne
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-10-24 00:13 UTC, wyattjoh commented
This fixes #26082

2018-10-25 12:55 UTC, CaselIT requested changes

2018-10-25 12:55 UTC, CaselIT commented on types/mongodb/index.d.ts
> +export interface FindOneAndUpdateOption {
You can extend `FindOneAndReplaceOption` adding only `arrayFilters`, to avoid the duplication

2018-10-25 12:55 UTC, CaselIT commented on types/mongodb/index.d.ts
> +    j?: boolean;
`w`, `j`, `wtimeout` are already in CommonOption

2018-10-25 12:55 UTC, CaselIT commented on types/mongodb/index.d.ts
> +export interface UpdateOneOptions extends CommonOptions {
You can extend `ReplaceOneOptions` adding only `arrayFilters`, to avoid the duplication

2018-10-26 05:32 UTC, CaselIT approved these changes

2018-10-27 01:37 UTC, merged

2018-10-28 19:59 UTC, errorx666 commented
It appears you made `arrayFilters` mandatory on `UpdateManyOptions`, but it should be optional.

2018-10-28 23:32 UTC, rbuckton commented
@errorx666: #30098 has been merged so this should no longer be an issue.