[jspdf] Add get methods for pageSize
DefinitelyTyped/DefinitelyTyped pull request #30060
Opened 2018-10-26 12:38 UTC by Lleios

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/MrRio/jsPDF/issues/1888
- [x] Increase the version number in the header if appropriate.

2018-10-31 16:51 UTC, ambervdberg approved these changes

2018-11-01 17:59 UTC, DanielRosenwasser requested changes

2018-11-01 17:59 UTC, DanielRosenwasser commented on types/jspdf/index.d.ts
> +// Definitions by:  Amber Schühmacher <https://github.com/amberjs>
Avoid the extra space

2018-11-01 17:59 UTC, DanielRosenwasser commented on types/jspdf/index.d.ts
> +// Type definitions for jsPDF v1.1.136
Looks like our lint rules are disabled for this package. Can you enable the lints in our `tslint.json` and fix up the version string to only be a `MAJOR.MINOR` version (e.g. `4.7`), as opposed to including the patch or containing a leading `v` (e.g. `v1.2.3`).

2018-11-05 21:57 UTC, merged