dd-trace: Fix incorrect typings for TracerOptions interface
DefinitelyTyped/DefinitelyTyped pull request #30223
Opened 2018-11-02 02:30 UTC by dominikeinkemmer

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
This property exists in the javascript package but is missing in the typings see [here](https://github.com/DataDog/dd-trace-js/blob/v0.6.1/src/config.js#L25)

2018-11-02 11:22 UTC, alloy requested changes

2018-11-04 05:44 UTC, dominikeinkemmer commented on types/dd-trace/index.d.ts
> +    tags?: { [key: string]: any } | string;
ah sorry that's true, I'll update the PR 🙇

2018-11-04 07:00 UTC, dominikeinkemmer commented
@alloy I updated, can you check again please? :)

2018-11-04 07:32 UTC, alloy approved these changes
Thanks!

2018-11-04 07:32 UTC, merged