Typings for expo-localization
DefinitelyTyped/DefinitelyTyped pull request #30308
Opened 2018-11-06 11:36 UTC by burtek

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-11-06 23:36 UTC, armanio123 requested changes

2018-11-06 23:36 UTC, armanio123 commented on types/expo-localization/index.d.ts
> +    country: string | undefined;
Based on the documentation this property is a Flow `maybe` type. Meaning it's `string | undefined | null`

2018-11-06 23:36 UTC, armanio123 commented on types/expo-localization/index.d.ts
> +    isoCurrencyCodes: string[] | undefined;
Based on the documentation this property is a Flow `maybe` type. Meaning it's `string | undefined | null`

2018-11-06 23:36 UTC, armanio123 commented on types/expo-localization/index.d.ts
> +    const country: string | undefined;
Based on the documentation this property is a Flow maybe type. Meaning it's string | undefined | null

2018-11-06 23:36 UTC, armanio123 commented on types/expo-localization/index.d.ts
> +    const isoCurrencyCodes: string[] | undefined;
Based on the documentation this property is a Flow maybe type. Meaning it's string | undefined | null

2018-11-07 00:52 UTC, burtek commented
@armanio123 true, missed that one.

2018-11-07 00:53 UTC, armanio123 approved these changes

2018-11-07 00:53 UTC, merged