Ramda: assoc overloads order
DefinitelyTyped/DefinitelyTyped pull request #30341
Opened 2018-11-07 10:06 UTC by infctr

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://ramdajs.com/docs/#assoc
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Fix `assoc` overloads order. Somehow got a ts error with `R.compose(R.assoc, R.toString)`

<img width="682" alt="screenshot 2018-11-07 13 02 12" src="https://user-images.githubusercontent.com/15550153/48124603-c816be80-e28d-11e8-9e15-c8ae7814d492.png">

2018-11-12 11:53 UTC, googol requested changes
Please see my previous comment https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30341#issuecomment-436696513, that should have been a review comment

2018-11-14 14:12 UTC, infctr commented
Apologies I couldn't address the requested changes earlier.

For test I had to use  `Record<string, string>` because with `compose` it produces a signature of type `Record<string, string> & { 1: string; 2: string; }`

2018-11-14 14:38 UTC, googol approved these changes

2018-11-14 14:39 UTC, googol commented
That's ok, thanks for the pr!

2018-11-18 17:27 UTC, merged