Added type definitions for kerberos npm package
DefinitelyTyped/DefinitelyTyped pull request #30379
Opened 2018-11-08 15:26 UTC by shervinmathieu

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

Definition file for kerberos package (https://github.com/mongodb-js/kerberos).

All annotations are pulled from the original source code (https://github.com/mongodb-js/kerberos/blob/master/lib/kerberos.js) with slight changes to conform to DT linting rules.

All functions in Kerberos package either accept a callback function as a parameter or return a Promise if no callback is provided, all functions are declared twice because of this.
Due to Kerberos's implementation, it is possible to call functions with an optional parameter before a required parameter. These functions are declared once more with a different signature to accommodate for this.

2018-11-08 19:18 UTC, armanio123 requested changes

2018-11-08 19:18 UTC, armanio123 commented on types/kerberos/index.d.ts
> +export function checkPassword(name: string, password: string, service: string, defaultRealm: string): Promise<void>;
Based on the documentation `defaultRealm` is optional.

2018-11-08 19:18 UTC, armanio123 commented on types/kerberos/index.d.ts
> +export function checkPassword(name: string, password: string, service: string, defaultRealm: string, callback: (err: string) => any): void;
`defaultRealm` is optional.

2018-11-09 07:15 UTC, velezsarain commented
Hi Armando,
The documentation is wrong. DefaultRealm isn't optional, and passing the wrong argument count or a different argument type than a string will make the function call to be rejected by the built in type checker. Also, the C code bindings that the kerberos package contains expect this value to be a char array, and will error if the value is null (this should never happen because of the type checker).

I don't believe that type definitions should mislead users into using functions with the wrong arguments.

I'm going to fill an issue in the kerberos repository to check if this was intentional or is an oversight.

2018-11-09 08:35 UTC, velezsarain commented
I've filled an issue in the kerberos package (https://github.com/mongodb-js/kerberos/issues/91)

I will wait for the package maintainer to respond to check if the type definition should be changed or not.

2018-11-15 19:27 UTC, closed without merging