add setReproStepsMode declare
DefinitelyTyped/DefinitelyTyped pull request #30397
Opened 2018-11-09 01:55 UTC by pengcao1

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-11-12 02:44 UTC, pengcao1 commented
anybody can review this?

2018-11-13 01:32 UTC, pengcao1 commented
@rbuckton  could you help me to review and merge this commit?

2018-11-13 07:05 UTC, pengcao1 commented
@PranavSenthilnathan 
could you help me to review and merge this commit?

2018-11-19 01:11 UTC, PranavSenthilnathan requested changes

2018-11-19 01:11 UTC, PranavSenthilnathan commented on types/instabug-reactnative/index.d.ts
> +  ollectingDataText: string;
Is this a typo?

2018-11-26 01:28 UTC, closed without merging