Improves react-navigation typings
DefinitelyTyped/DefinitelyTyped pull request #30415
Opened 2018-11-09 18:03 UTC by chagasaway

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

2018-11-17 14:44 UTC, lijunle commented
@chagasaway I checked that react-navigation@3 has been [released](https://reactnavigation.org/blog/2018/11/17/react-navigation-3.0.html) today. Is the change still compatible with the new version?

2018-11-17 17:58 UTC, chagasaway commented
@lijunle those changes are compatible with the 2.x version which is the currently supported here. I can help with the typings for the new version later but those changes from this PR aims only to improve the 2.x version instead of making it compatible with the 3.x

2018-11-20 06:40 UTC, lijunle approved these changes

2018-11-20 06:40 UTC, lijunle commented on types/react-navigation/index.d.ts
> +  routes: NavigationRoute[];
Add JSDoc for these fields?

2018-11-21 17:36 UTC, uniqueiniquity requested changes

2018-11-21 17:36 UTC, uniqueiniquity commented on types/react-navigation/index.d.ts
> +  routes: NavigationRoute[];
Waiting to merge until requested JSDoc is added.

2018-11-22 20:42 UTC, chagasaway commented
@lijunle @uniqueiniquity just added the docs for the new fields, and sorry for the delay

2018-11-26 14:34 UTC, uniqueiniquity approved these changes

2018-11-26 14:34 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2018-11-26 14:34 UTC, merged