[ember] Polyfill: allow assign to take in more than 4 args
DefinitelyTyped/DefinitelyTyped pull request #30424
Opened 2018-11-09 22:30 UTC by dorilla

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/emberjs/ember.js/blob/v3.5.1/packages/%40ember/polyfills/lib/assign.ts#L8
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

This PR allows the ember polyfill for object assign to take in more than 4 objects, which more closely aligns with the ember source code's definition: https://github.com/emberjs/ember.js/blob/v3.5.1/packages/%40ember/polyfills/lib/assign.ts#L8

2018-11-10 04:54 UTC, mike-north requested changes

2018-11-10 04:54 UTC, mike-north commented on types/ember__polyfills/index.d.ts
> +export function assign(target: object, ...sources: object[]): any;
`any` includes the ability for the return to be undefined, null, boolean, etc... You should probably return `object` here.

2018-11-11 00:47 UTC, mike-north commented on types/ember__polyfills/ember__polyfills-tests.ts
> +    assign({}, { a: 0 }, { b: 1 }, { c: 2 }, { d: 3 }).a; // $ExpectType any
```suggestion
    assign({}, { a: 0 }, { b: 1 }, { c: 2 }, { d: 3 }).a; // $ExpectType object
```

2018-11-11 00:54 UTC, mike-north approved these changes
LGTM! thanks for the fix

2018-11-11 00:57 UTC, mike-north commented
@dorilla sorry for the flip-flop -- looks like you'll have to go back to the `any` return type in order to facilitate direct property access like `.a`

2018-11-15 01:46 UTC, merged

2018-11-15 01:46 UTC, PranavSenthilnathan commented
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!