GmailApp getAttachments()
DefinitelyTyped/DefinitelyTyped pull request #30444
Opened 2018-11-11 08:52 UTC by labnol

Advanced parameters to get all the attachments for any Gmail message.

2018-11-11 15:39 UTC, grant approved these changes

2018-11-14 00:56 UTC, PranavSenthilnathan requested changes
Please consider making `options` an optional parameter to `getAttachments()`. Take a look at [this section in the handbook](http://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#use-optional-parameters) for more details.

2018-11-14 13:40 UTC, grant commented
@PranavSenthilnathan True, but almost all methods in this tsd could be improved with things like optional types. We should add optionals all at once by updating the type generator. Having consistent type styles should be okay.

What to do think?

2018-11-14 22:41 UTC, PranavSenthilnathan commented
I agree with your consistency reasoning, so I'll go ahead and merge it. It would be great to eventually fix up all the overloads with optionals because there are a few bugs that this could catch!

2018-11-14 22:41 UTC, PranavSenthilnathan approved these changes

2018-11-14 22:41 UTC, merged