Add timsort
DefinitelyTyped/DefinitelyTyped pull request #30493
Opened 2018-11-13 15:41 UTC by Vunovati

Please fill in this template.

- [*] Use a meaningful title for the pull request. Include the name of the package modified.
- [*] Test the change in your own code. (Compile and run.)
- [*] Add or edit tests to reflect the change. (Run with `npm test`.)
- [*] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [*] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [*] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [*] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [*] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [*] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [*] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-11-14 23:20 UTC, plantain-00 approved these changes

2018-11-18 23:15 UTC, PranavSenthilnathan requested changes

2018-11-18 23:15 UTC, PranavSenthilnathan commented on types/timsort/index.d.ts
> +export function sort(array: any[], lo?: number, hi?: number): void;
Is it possible to have just 2 overloads (in this order):
export function sort(array: any[], lo: number, hi?: number): void; // If 2nd arg is number then we know no comparer was passed in
export function sort<T>(array: T[], compare?: (a: T, b: T) => number, lo?: number, hi?: number): void;

2018-11-19 16:32 UTC, merged

2018-11-19 16:32 UTC, PranavSenthilnathan commented
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!