[WebAssembly] Align bufferSource value type to WebAssembly JS API Specification
DefinitelyTyped/DefinitelyTyped pull request #30644
Opened 2018-11-19 02:51 UTC by chicoxyzzy

According to [WebAssembly JS API specification](https://webassembly.github.io/spec/js-api/#webassembly-namespace) `bufferSource` is of type `BufferSources` which is union of [these types](https://heycam.github.io/webidl/#BufferSource)

2018-11-19 03:18 UTC, chicoxyzzy commented
oops I accidentally deleted issue template to ping @dt-bot :(

2018-11-19 03:20 UTC, chicoxyzzy commented
@PranavSenthilnathan sorry for that. How can I fix that?

2018-11-20 21:27 UTC, jhenninger requested changes

2018-11-21 12:49 UTC, chicoxyzzy commented on types/webassembly-js-api/index.d.ts
> +
good catch! thank you!

2018-11-21 15:06 UTC, jhenninger approved these changes

2018-11-21 16:42 UTC, merged