Add type definitions for netlify-widget-tests
DefinitelyTyped/DefinitelyTyped pull request #30689
Opened 2018-11-20 11:53 UTC by nkprince007

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-11-20 12:00 UTC, nkprince007 commented
As suggested by the package maintainer (@sw-yx) of netlify-identity-widget, the type definitions are expected to be maintained here.

2018-11-20 21:00 UTC, uniqueiniquity requested changes

2018-11-20 21:00 UTC, uniqueiniquity commented on types/netlify-identity-widget/index.d.ts
> +export { };
This line is unnecessary.
In order to have an ES6 style, callable import statement when consuming these type definitions, the consumer must enable `--esModuleInterop` (or more specifically, `--allowSyntheticDefaultImports`), thereby allowing them to use `import NetlifyIdentityWidget from "netlify-identity-widget";` in the same way that one would use `import NetlifyIdentityWidget = require("netlify-identity-widget");`

2018-11-21 00:01 UTC, nkprince007 commented
Thanks for the early review @uniqueiniquity. The response has been extremely timely. 👍

2018-11-21 15:51 UTC, uniqueiniquity approved these changes

2018-11-21 15:51 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2018-11-21 15:51 UTC, merged