Add react-native-onesignal
DefinitelyTyped/DefinitelyTyped pull request #30858
Opened 2018-11-27 12:55 UTC by FabianMeul

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-11-27 12:55 UTC, FabianMeul commented
Big thanks to @krystofcelba for providing the initial types in https://github.com/geektimecoil/react-native-onesignal/pull/395

2018-12-14 12:04 UTC, slorber requested changes
These types seem to work great for me except few details

Note there is a method `syncHashedEmails` that is missing

2018-12-14 12:04 UTC, slorber commented on types/react-native-onesignal/index.d.ts
> +    Configure(undocumentedParam1?: any, undocumentedParam2?: any): void;
this is normally lowercase no?

2018-12-14 12:04 UTC, slorber commented on types/react-native-onesignal/index.d.ts
> +    kOSSettingsKeyAutoPrompt: boolean;
make all attributes optional with ? please

2018-12-14 12:13 UTC, slorber commented on types/react-native-onesignal/index.d.ts
> +    setEmail(email: string, callback: (error?: any) => {}): void;
I think the callback should be optional

2018-12-14 12:13 UTC, slorber commented on types/react-native-onesignal/index.d.ts
> +    setEmail(email: string, emailAuthCode: string, callback: (error?: any) => {}): void;
optional callback?

2018-12-21 12:30 UTC, closed without merging