Remove const enum
DefinitelyTyped/DefinitelyTyped pull request #30939
Opened 2018-11-30 03:47 UTC by wyqydsyq

Was throwing error:
```
Type error: Ambient const enums are not allowed when the '--isolatedModules' flag is provided.  TS1209
```

RE: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28744#issue-358403102

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-12-03 23:53 UTC, amcasey commented on types/range-parser/index.d.ts
>          invaild = -2,
Unrelated, but this typo will probably cause problems.

2018-12-03 23:54 UTC, amcasey approved these changes

2018-12-05 02:46 UTC, amcasey commented
Re-opening to trigger Travis.

2018-12-06 09:43 UTC, tlaziuk requested changes
enums should not be used, please change to literal types as the `Restult` structure doesn't exists in the source code,

look at this PR for reference: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29783 https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30680

actually this is the 3rd one which tries to solve the issue

2018-12-07 04:05 UTC, wyqydsyq commented
In that case it looks like https://github.com/DefinitelyTyped/DefinitelyTyped/pull/29783 should be re-opened, it looks to be the correct change and appears to have only been closed due to a naughty bot

2018-12-07 04:05 UTC, closed without merging