Add missing types for imap-simple 4.2
DefinitelyTyped/DefinitelyTyped pull request #30993
Opened 2018-12-02 21:00 UTC by iaarnio

Add type definitions for functions:
- addBox
- delBox
- getBoxes
- append

Fix parameter name for delFlags.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-12-02 21:13 UTC, iaarnio commented
Type definitions for https://github.com/chadxz/imap-simple

2018-12-02 23:16 UTC, pushplay requested changes
Thanks for updating this.  There are a couple opportunities to improve it further and it's good to go.

2018-12-02 23:16 UTC, pushplay commented on types/imap-simple/index.d.ts
> +    getBoxes(): Promise<any>;
Reading the docs it looks like the returned object can be typed `Imap.MailBoxes`.

2018-12-02 23:16 UTC, pushplay commented on types/imap-simple/index.d.ts
> +    append(message: any, options: any): Promise<void>;
Looks like `options` is type `Imap.AppendOptions`.

2018-12-03 17:50 UTC, iaarnio commented
Good observations! I added those more detailed type definitions.

2018-12-03 17:52 UTC, pushplay approved these changes
Cheers.

2018-12-03 20:46 UTC, merged