iframe-resizer: make iframeResizer default export
DefinitelyTyped/DefinitelyTyped pull request #31020
Opened 2018-12-03 14:39 UTC by polar-lukas

"iframeResizer" is the default export of the typed library. Hence it should also be declared such.

If you try to require iframeResizer as AMD module, the function "iframeResizer" is not provided within an object but as function. Using the provided types results in an undefined propery "iframeResizer" on the "define"d object.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/davidjbradshaw/iframe-resizer/blob/d0e8addce5ff9c657292c5732cceb6cfe90b23ae/src/iframeResizer.js#L1296
https://github.com/davidjbradshaw/iframe-resizer/blob/d0e8addce5ff9c657292c5732cceb6cfe90b23ae/src/iframeResizer.js#L1251
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-12-04 14:58 UTC, arminbaljic approved these changes

2018-12-04 23:41 UTC, sandersn requested changes

2018-12-04 23:41 UTC, sandersn commented on types/iframe-resizer/index.d.ts
> +export default function iframeResizer(options: IFrameOptions, target: string | HTMLElement): IFrameComponent[];
`export default` is almost right here, but not quite. It should be `export = iframeResizer`, followed by `export as namespace iframeResize`. That's based on the source code's commonjs `module.exports = factory()` and global `window.iFrameResize = window.iFrameResize || factory()`. Once you have the commonjs syntax correct, Typescript will emit the correct AMD import code when you import it with `import iframeResizer = require('iframe-resizer')`.

2018-12-04 23:41 UTC, sandersn commented on types/iframe-resizer/iframe-resizer-tests.ts
> +import iframeResizer, { IFrameComponent, IFrameOptions } from "iframe-resizer";
together with my other comment, `iframeResizer` should be imported as `import iframeResizer = require('iframe-resizer')`. That in turn means that IFrameComponent and the rest will need to be nested inside a namespace like so:

```ts
export namespace iframeResizer {
  interface IFrameObject { ...
```

and namespaced in the tests as `iframeResizer.IFrameComponent`.

2018-12-05 13:04 UTC, polar-lukas commented
The change is no longer backwards compatible. Maybe we now need a new type version.

2018-12-05 16:31 UTC, sandersn commented
@polar-lukas I think it is fine for the change to break current users:

1. Nobody will get the new types until they `npm install @types/iframe-resizer`.
2. The old types are useless anyway, since iframeResizer is incorrect. Nobody installs the types just to use IFrameComponent.
3. You can still access the types unqualified by adding another line underneath the import: `import IFrameComponent = iframeResizer.IFrameComponent`

2018-12-05 16:31 UTC, sandersn approved these changes

2018-12-05 16:32 UTC, merged

2018-12-12 16:08 UTC, polar-lukas commented
@sandersn Do you see any problems on changing line 315 like @skasgarv suggested above?

2018-12-18 10:53 UTC, clark-stevenson commented
Hey guys, 

I have to use the global version of this library but I am not sure how much that matters.  

If you head over to here `http://davidjbradshaw.com/iframe-resizer/example/` and in the console, the only function is `iFrameResize()`.  

I can't for the life of me understand the line `declare function iframeResizer(options: iframeResizer.IFrameOptions, target: string | HTMLElement): iframeResizer.IFrameComponent[];`  

In my Angular project, I ended up adding a global augmentation to my `typings.d.ts` file which worked as a quick hack. 

```
/* Repairs incorrect @types/iframe-resizer */
interface Window {
  iFrameResize(options: iframeResizer.IFrameOptions, target: string | HTMLElement): iframeResizer.IFrameComponent[];
}
```

I am clueless on the usage of UMD modules or how to declare them correctly, it seems that the rest of the typings are fine though.

2019-07-07 16:48 UTC, hvedemelsbof commented
I had the same problem as @skasgarv .

2019-07-07 16:54 UTC, hvedemelsbof commented
I had the same problem as @skasgarv in angular 8.0.1 // typescript 3.4.5
Fixed be altering last three lines of type declarations to:
`export declare function iframeResizer(options: iframeResizer.IFrameOptions, target: string | HTMLElement): iframeResizer.IFrameComponent[];
// export = iframeResizer;
export as namespace iframeResizer;`
(as @skasgarv already pointed out)
Imported in directive with:
`import { iframeResizer } from 'iframe-resizer';`
and defining iframe component:
`component: iframeResizer.IFrameComponent;`