[@types/three] Adding MapControls from THREE r94
DefinitelyTyped/DefinitelyTyped pull request #31113
Opened 2018-12-06 06:17 UTC by danyim

This is a re-submission of #30104

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mrdoob/three.js/blob/dev/examples/js/controls/MapControls.js
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-12-06 10:13 UTC, JuStTheDev requested changes
See line-comments

2018-12-06 10:13 UTC, JulianSSS commented on types/three/three-mapcontrols.d.ts
> +    update(): false;
```suggestion
    update(): boolean;
```
MapControls.js returns true in line 216

2018-12-09 21:34 UTC, danyim commented on types/three/three-mapcontrols.d.ts
> +    update(): false;
Got it!

2018-12-09 21:34 UTC, danyim commented
@JulianSSS Done!

2018-12-09 21:40 UTC, JuStTheDev approved these changes

2018-12-13 19:03 UTC, merged

2019-01-17 00:14 UTC, bhouston commented
BTW we are trying to get *.d.ts files into Three.JS proper based on automated processing of the typings in types/three.  It would be good to have ownership of the *.d.ts files in Three.JS proper.  See here for more details: https://github.com/mrdoob/three.js/pull/15597