types/react-map-gl: Change onViewStateChange to an optional property
DefinitelyTyped/DefinitelyTyped pull request #31120
Opened 2018-12-06 11:28 UTC by daraclare

Package: types/react-map-gl
Description: The `onViewStateChange` is an optional property, please see [react-map-gl's what's new doc](https://github.com/uber/react-map-gl/blob/fe1aa482a6fffe52125ad70d1bbecb223ae9bed6/docs/whats-new.md)
This PR just adds a question mark to change it to an optional property and prevent TS errors when it is omitted.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.) ***RETURNS AN ERROR***
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present). ***RETURNS AN ERROR***

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate. WHRE IS THIS? SHOULD I CHANGE IT?
- [ ] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~~

2018-12-06 11:31 UTC, daraclare commented
@fnberta I've created this PR, but if I can edit it in any way to make it better let me know! Thanks!

2018-12-06 20:55 UTC, fnberta requested changes
Thanks you for this PR, this prop should in fact be optional! Checking the react-map-gl docs and code, the older `onViewportChange` prop should also be optional. Could you add that as well? Thank you!

2018-12-13 09:22 UTC, daraclare commented
@fnberta apologies, I missed your comment, `onViewportChange` is now optional as well.

2018-12-17 13:06 UTC, fnberta approved these changes

2018-12-18 21:42 UTC, merged