js-yaml: fix types of LoadOptions and DumpOptions
DefinitelyTyped/DefinitelyTyped pull request #31450
Opened 2018-12-16 18:40 UTC by ajafff

There's no `strict` property on `LoadOptions` according to the docs.
Added `onWarning` to `LoadOptions`.
`schema` in `LoadOptions` and `DumpOptions` is now typed as `SchemaDefinition` instead of `any`.
Converted single line comments to JSDoc.

2018-12-16 21:15 UTC, sclausen requested changes
Please remove all unnecessary reformatting.

2018-12-17 06:46 UTC, sclausen requested changes
Please make either a PR for change the comment style if you dislike it (I'm really neutral regarding this topic), or make a PR for adding features. Don't mix adding features with reformatting everything else!

2018-12-17 07:45 UTC, ajafff commented
as you wish

> PR for change the comment style if you dislike it

this is not my personal preference. it's about showing those comments as documentation in the editor (e.g. on hover)

2018-12-18 21:17 UTC, ajafff commented
@sclausen would you mind giving this another review?

2018-12-19 06:41 UTC, sclausen approved these changes

2018-12-19 18:17 UTC, merged