Add types for distributions
DefinitelyTyped/DefinitelyTyped pull request #31472
Opened 2018-12-17 11:15 UTC by marcolanaro

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-12-18 19:06 UTC, sandersn requested changes

2018-12-18 19:06 UTC, sandersn commented on types/distributions/distributions-tests.ts
> +import distributions from 'distributions';
there's no default export so you need to use `import * as distributions from 'distributions'`

Looks like a bug in the linter skipped the error that should have arisen from this.

2018-12-19 21:16 UTC, sandersn commented on types/distributions/index.d.ts
> +export default distributions;
distributions doesn't have a default export -- it's a commonjs export. I think you should just export Normal, Studentt, etc individually:

```ts
export function Normal(mean?: number, sd?: number): Distribution;
// etc
```

And then you can go back to `import * as distributions from 'distributions';`

2018-12-19 21:16 UTC, sandersn requested changes
Need to match exports from distributions source.

2018-12-31 18:29 UTC, sheetalkamat approved these changes

2018-12-31 18:29 UTC, merged