react-json-tree: Adjusted the definition of the valueRenderer method.
DefinitelyTyped/DefinitelyTyped pull request #31508
Opened 2018-12-18 11:58 UTC by devjedi

The valueRenderer is actually invoked with more attributes then just a raw value. Also the first attribute is not the rawValue but the already pre-parsed displayValue (e.g. with quotes around a string).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/alexkuz/react-json-tree/blob/master/src/JSONValueNode.js#L22
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2018-12-18 17:05 UTC, gnestor commented
@devjedi It looks `valueRenderer` [is called with this call signature](https://sourcegraph.com/github.com/alexkuz/react-json-tree/-/blob/src/JSONValueNode.js#L22:8) 

```js
valueRenderer(valueGetter(value), value, ...keyPath)
```

But the [docs](https://sourcegraph.com/github.com/alexkuz/react-json-tree/-/blob/README.md#L124:5) and [example](https://sourcegraph.com/github.com/alexkuz/react-json-tree/-/blob/examples/src/App.js#L158:9) define it as follows:

```js
valueRenderer={raw => <em>{raw}</em>}
```

Have you filed an issue on react-json-tree regarding this discrepancy? 

As for this PR, I think that all but the first argument should be optional so that the types are still compatible with the usage examples.

2018-12-18 17:05 UTC, gnestor requested changes
I think that all but the first argument should be optional so that the types are still compatible with the usage examples

2018-12-25 11:16 UTC, devjedi commented
Agreed @gnestor . 
I improved the signature of the valueRenderer method and declared all the arguments but the first optional.

2018-12-26 05:57 UTC, gnestor approved these changes

2018-12-26 06:37 UTC, merged