Update typings for lru-cache v5.1
DefinitelyTyped/DefinitelyTyped pull request #31577
Opened 2018-12-21 00:47 UTC by forivall

BREAKING CHANGE: major version bump for lru-cache, which uses native js
class type, and so the typings use a class as well

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - [uses `class`](https://github.com/isaacs/node-lru-cache/commit/9ce69193c4cefbeee27e759b1cf94e02a3eadf8b)
  - [ageOnGet Option](https://github.com/isaacs/node-lru-cache/commit/fc66d5af76cf9b3b77da87a2448612b18f13482b)
- [x] Increase the version number in the header if appropriate.

2018-12-22 19:26 UTC, BendingBender requested changes

2018-12-22 19:30 UTC, BendingBender requested changes

2018-12-22 19:30 UTC, BendingBender commented on types/lru-cache/index.d.ts
> +// Type definitions for lru-cache 5.1
Please follow instructions [here](https://github.com/DefinitelyTyped/DefinitelyTyped#i-want-to-update-a-package-to-a-new-major-version) for major version updates.

2018-12-27 07:45 UTC, forivall commented
It's Christmas you dang typescript bot. I'll get to it

2018-12-27 07:48 UTC, forivall commented on types/lru-cache/index.d.ts
> +declare class LRU<K = any, V = any> {
The original LRU.Cache interface defaulted to any. I can remove in the LRU class type.

2018-12-28 01:25 UTC, closed without merging