Update react-webcam
DefinitelyTyped/DefinitelyTyped pull request #31617
Opened 2018-12-23 14:54 UTC by skubarenko

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
       - [React Webcam Props](https://github.com/mozmorris/react-webcam/blob/a354b668e4719533a491fde7fe6b907b56dcb956/src/react-webcam.js#L85-L102);
       - [React Webcam defaultProps](https://github.com/mozmorris/react-webcam/blob/a354b668e4719533a491fde7fe6b907b56dcb956/src/react-webcam.js#L74-L83);
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2018-12-28 16:27 UTC, squat reviewed
Sorry for the delay, I am traveling at the moment. This looks overall like an improvement, but I am little confused by the new `defaulProps` field.

2018-12-28 16:29 UTC, squat requested changes
Sorry for the delay, I am traveling at the moment. This looks overall like an improvement, but I am little confused by the new `defaulProps` field.

2018-12-28 17:04 UTC, skubarenko commented on types/react-webcam/index.d.ts
> +    static defaultProps: Webcam.WebCamDefaultProps;
These properties are defined in [here](https://github.com/mozmorris/react-webcam/blob/a354b668e4719533a491fde7fe6b907b56dcb956/src/react-webcam.js#L74-L83)
TypeScript 3.0 has added support for `defaultProps`, so I decided to add these types to the `d.ts`. Maybe in the future, IDEs will show these `defaultProps` in intellisense, but for now, you can navigate to type definitions and find the default values for component properties

2018-12-29 03:44 UTC, squat commented on types/react-webcam/index.d.ts
> +    static defaultProps: Webcam.WebCamDefaultProps;
Ah awesome. I had not realized this had been added.

2019-01-04 16:41 UTC, closed without merging