[strange] add types
DefinitelyTyped/DefinitelyTyped pull request #31757
Opened 2018-12-29 06:59 UTC by wanganjun

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2018-12-31 16:29 UTC, weswigham requested changes

2019-01-01 11:49 UTC, wanganjun commented on types/strange/tslint.json
> +        "new-parens": false
Because `new Range` is documented
https://github.com/moll/js-strange/blob/master/doc/API.md#rangebegin-end-bounds-

2019-01-01 18:42 UTC, weswigham commented on types/strange/tslint.json
> +        "new-parens": false
Sure it is, but it's not like it's used in the test file (or any different than `new Range()`).

2019-01-02 01:39 UTC, wanganjun commented on types/strange/tslint.json
> +        "new-parens": false
Ok, I will remove that lint rule

2019-01-02 03:45 UTC, weswigham approved these changes

2019-01-02 03:46 UTC, merged