[react-redux] Improve Selector type to handle function with no OwnProps
DefinitelyTyped/DefinitelyTyped pull request #31799
Opened 2018-12-31 14:13 UTC by VincentLanglet

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Cf issue : https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25804

2018-12-31 14:18 UTC, VincentLanglet commented
I'm not sure it's the best way to do it.

The goal is to have a bivalent type : 
```
const foo: Selector<State, string> = (state: State) => ...
const bar: Selector<State, string, OwnProps> = (state: State, ownProps: OwnProps) => ...
```
With the errors : 
```
foo(state) // ok
foo(state, ownProps) // error expected 1 argument
bar(state) // error expected 2 argument
bar(state, ownProps) // ok
```

`(state: State, ownProps?: OwnProps)` is not doing the job

2019-01-06 02:33 UTC, mDibyo requested changes
@VincentLanglet I don't think this work as expected. For instance, the following does not raise any errors with either the existing definition or the new definition you added:
```ts
const f: Selector<State, Props, OwnProps> = (state: State) => {
    ...
}
```
It looks like Typescript thinks `(state: State): TProps` satisfies `(state: State, ownProps: TOwnProps) => TProps`, so seems impossible to enforce the bivalent type as you wanted to.

2019-01-12 12:37 UTC, VincentLanglet commented
@alloy Why should I do new commit if I don't want to see this PR closed ? The only reviewer post a comment and I don't have answer from him. I think sometimes is wrong or not clear with this bot behaviour.

2019-01-21 17:11 UTC, VincentLanglet commented
@DanielRosenwasser @rbuckton I have no news from @mDibyo 
I have tested this change in my project, and it's working well. And I have written tests.
What can I do more ?
Thanks

2019-01-24 17:34 UTC, uniqueiniquity requested changes

2019-01-24 17:34 UTC, uniqueiniquity commented on types/react-redux/index.d.ts
> +export type Selector<S, TProps, TOwnProps = null> = TOwnProps extends null
You'll actually want `extends null | undefined` to totally match your example.

2019-01-24 17:34 UTC, uniqueiniquity commented on types/react-redux/react-redux-tests.tsx
> +    simpleSelect(state);
You can also add the following to test:
```ts
simpleSelect(state, ownProps); // $ExpectError
notSimpleSelect(state); // $ExpectError
```

2019-01-24 21:22 UTC, VincentLanglet commented
@uniqueiniquity Thanks for your review. I made the changes.

2019-01-24 22:33 UTC, uniqueiniquity approved these changes

2019-01-24 22:33 UTC, merged

2019-01-25 07:51 UTC, mDibyo commented
@VincentLanglet I am sorry for not getting back to you on this PR. :( I wanted to play with the example you posted, but forgot about it.

2019-01-25 08:43 UTC, VincentLanglet commented
@mDibyo No problem !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>