[expo] Add types for SecureStore keychain item accessibility constants
DefinitelyTyped/DefinitelyTyped pull request #31840
Opened 2019-01-02 16:31 UTC by JKillian

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.expo.io/versions/latest/sdk/securestore#exposecurestoresetitemasynckey-value-options
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-01-03 06:08 UTC, moshfeu requested changes

2019-01-03 06:08 UTC, moshfeu commented on types/expo/expo-tests.tsx
> +        keychainAccessible: SecureStore.WHEN_PASSCODE_SET_THIS_DEVICE_ONLY,
Maybe you can test the `keychainService` option too.

2019-01-03 06:08 UTC, moshfeu commented on types/expo/expo-tests.tsx
> +};
Other `keychainAccessible` options can be tested here. Something like this:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/expo/expo-tests.tsx#L160

2019-01-03 06:08 UTC, moshfeu commented on types/expo/index.d.ts
> +//                 Jason Killian <https://github.com/jkillian>
👍

2019-01-06 09:17 UTC, moshfeu approved these changes
Thanks!

2019-01-06 19:07 UTC, merged

2019-01-07 00:57 UTC, JKillian commented
Glad to get this merged, thanks for the reviews @moshfeu!