[reactstrap] Update type of CustomInput label prop
DefinitelyTyped/DefinitelyTyped pull request #31875
Opened 2019-01-04 01:39 UTC by bettyyin

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/reactstrap/reactstrap/blob/317e8014e30e2084ad02424f69d6f840730b452a/src/CustomInput.js#L10

~- [ ] Increase the version number in the header if appropriate.~
~- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.~

2019-01-11 01:31 UTC, changLiuUNSW commented on types/reactstrap/lib/CustomInput.d.ts
> +  label?: React.ReactChild;
The type is wrong. It should be ```React.ReactNode```

2019-01-11 01:33 UTC, changLiuUNSW commented on types/reactstrap/lib/CustomInput.d.ts
> +  label?: React.ReactChild;
test

2019-01-11 01:34 UTC, changLiuUNSW requested changes

2019-01-11 01:34 UTC, changLiuUNSW commented on types/reactstrap/lib/CustomInput.d.ts
> +  label?: React.ReactChild;
The type is wrong. It should be ```React.ReactNode```

2019-01-14 01:46 UTC, changLiuUNSW approved these changes

2019-01-25 00:50 UTC, uniqueiniquity requested changes
Please add a test to validate your change.

2019-01-31 03:57 UTC, changLiuUNSW commented
@bettyyin  Can you grand me the access for your repo and I can fix the issue for you if you do not have time

2019-01-31 03:58 UTC, changLiuUNSW commented
@uniqueiniquity  I will create a new PR if @bettyyin did not have time to fix the issue

2019-02-01 01:32 UTC, closed without merging