Add typings for BdApi (BetterDiscordApi)
DefinitelyTyped/DefinitelyTyped pull request #31895
Opened 2019-01-04 17:44 UTC by Acidic9

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

#### Adding a new package
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-01-04 18:24 UTC, sheetalkamat requested changes

2019-01-05 04:47 UTC, Acidic9 commented on types/bdapi/index.d.ts
> +// Project: https://betterdiscord.net (Does not have to be to GitHub, but prefer linking to a source code repository rather than to a project website.)
I fixed the project link as well as added a comment to the api documentation

2019-01-05 05:03 UTC, Acidic9 commented
I don't understand why my test is failing because `Expected file 'bdapi-tests.ts' to be named bandagedbd__bdapi-tests.ts` even though I did that in commit Acidic9/DefinitelyTyped@5f6045d.

2019-01-05 05:14 UTC, Acidic9 commented
@sheetalkamat It should be all good now. I've added the correct links in index.d.ts

2019-01-07 16:30 UTC, merged