add typings for @google-cloud/tasks
DefinitelyTyped/DefinitelyTyped pull request #32051
Opened 2019-01-11 01:13 UTC by ifiokjr

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

2019-01-23 05:33 UTC, ifiokjr commented
![Help... somebody... anybody 😢 - with Simba (lion king) crying over his lost father](https://media.giphy.com/media/cz314BBYiCkiA/giphy.gif "Help... somebody... anybody 😢 - with Simba from the Lion King crying over his lost father. So sad...")

2019-01-24 13:16 UTC, ifiokjr commented
@uniqueiniquity anything I can do to get this merged?

2019-01-24 21:42 UTC, uniqueiniquity commented
@ifiokjr I'm here! I'll get to this as soon as I can.

2019-01-24 21:53 UTC, uniqueiniquity requested changes

2019-01-24 21:53 UTC, uniqueiniquity commented on types/google-cloud__tasks/index.d.ts
> +// Project: https://github.com/googleapis/nodejs-tasks (Does not have to be to GitHub, but prefer linking to a source code repository rather than to a project website.)
Please remove the parenthesized clause.

2019-01-24 21:53 UTC, uniqueiniquity commented on types/google-cloud__tasks/index.d.ts
> +// import * as gax from "google-gax";
What are these two commented-out lines for?

2019-01-24 21:53 UTC, uniqueiniquity commented on types/google-cloud__tasks/index.d.ts
> +    [key: string]: any;
Prefer `object` over `{ [key: string]: any; }`.

2019-01-24 21:53 UTC, uniqueiniquity commented on types/google-cloud__tasks/ts3.1/index.d.ts
> +    [key: string]: any;
Prefer `object` over `{ [key: string]: any; }`

2019-01-26 06:43 UTC, ifiokjr commented
Thanks, @uniqueiniquity. I've made the suggested changes.

2019-01-28 16:40 UTC, uniqueiniquity approved these changes

2019-01-28 16:40 UTC, merged

2019-01-28 19:46 UTC, Flarna commented
Seems this PR causes a fail in node tests, see [CI](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/485494766?utm_source=github_status&utm_medium=notification) run of #32552

```
Error in google-cloud__tasks
Error: Expected compilerOptions["baseUrl"] === "../"
    at Object.<anonymous> (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/checks.js:72:27)
    at Generator.next (<anonymous>)
    at fulfilled (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/dtslint/bin/checks.js:4:58)
    at <anonymous>
```

Most likely the same issue as with jsdom.