change bn.js to use default export to fix declaration gen
DefinitelyTyped/DefinitelyTyped pull request #32178
Opened 2019-01-15 20:24 UTC by danwbyrne

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<See below>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

I firmly believe `bn.js` should be using `export default`. I have setup a minimal repo that illustrates the issue here: https://github.com/danwbyrne/bn-repo; In short, setting `declaration: true` in compilerOptions causes cascading errors of the form:

```
Exported variable 'X' has or is using name 'BN' from external module "path/to/node_modules/@types/bn.js/index" but cannot be named.
```

 that can only be resolved by:

1. importing `bn.js` to any issue that has the issue and ignore the useless import.
2. changing `bn.js` to use `export default`.

for precedence on this issue (and how I discovered the solution) we can look at the `BigNumber` library: ([.d.ts](https://github.com/MikeMcl/bignumber.js/blob/bde4ac1f6380eae9ba54e5015cdf02f866cd5be4/bignumber.d.ts#L35))([index](https://github.com/MikeMcl/bignumber.js/blob/bde4ac1f6380eae9ba54e5015cdf02f866cd5be4/bignumber.js#L1))

it *does not* use `default` exports in its index, however it still uses `default` in its `.d.ts`. Whether this is because of the `(function (...args) {...` setup of the index file, *OR* if it was to solve issues like what I've laid out above.

`bn.js` uses an almost identical index file layout with no `default` exports, but it does have the `(function (...args) {...` layout like `BigNumber` does [here](https://github.com/indutny/bn.js/blob/24cc2dd51b58694088a637a314689f61c9ba65a4/lib/bn.js#L1).

2019-01-17 19:21 UTC, LogvinovLeon approved these changes

2019-01-18 07:30 UTC, levino requested changes
I think this is a mistake. I will investigate and review and then remove my veto if possible.

2019-01-18 07:32 UTC, Levino commented
@LogvinovLeon May I ask in which regard you verified the correctness of this code and the nature of actual issue behind the changes? There is not even a test.

2019-01-18 07:45 UTC, Levino commented
I think this is rather a [TypeScript issue](https://github.com/Microsoft/TypeScript/issues/5711)

2019-01-18 08:01 UTC, Levino commented
As expected your change would break this package for all users who do not use `esModuleInterop`. This is an absolute no go for me and I have to reject these changes. Maybe I am overlooking something then please explain further why this is not a problem. I opened a [PR](https://github.com/Levino/bn-repo/pull/1) to discuss things further.

2019-01-18 08:04 UTC, Levino commented
Also I am pretty sure @danwbyrne did not [test](https://github.com/DefinitelyTyped/DefinitelyTyped#test) these code changes at all which is very annoying.

2019-01-18 10:19 UTC, LogvinovLeon commented
@Levino To be completely honest - I just quickly skimmed through that PR and read the description. Seemed reasonable. I didn't test it. Thank you for pointing it out.

2019-01-18 10:43 UTC, Levino commented
Just a remark: This PR changes the code for multiple packages. Should be double checked at least.

2019-01-18 19:58 UTC, danwbyrne commented
@Levino thanks for taking the time to review and create examples in the repo. All of the actual compilation testing I did was locally in our [library](https://github.com/neo-one-suite/neo-one), I wasn't aware removing `esModuleInterop` would have this effect.

I agree this is a typescript issue, we have looked into the issue numerous times before and I only stumbled on this `fix` recently. If you can think of another solution I am willing to put in some time here, but otherwise I'll just continue using the modified definition in our repo only.

2019-01-19 14:55 UTC, Gilthoniel commented
@danwbyrne 

https://github.com/danwbyrne/bn-repo/pull/2

I made a PR on your example repo with a way to go around this Typescript issue (more than a dev mistake..).

2019-01-21 18:15 UTC, closed without merging