react-bootstrap: add missing bsClass, bsSize declarations
DefinitelyTyped/DefinitelyTyped pull request #32199
Opened 2019-01-16 08:31 UTC by bes

I tried to find as many as possible of the declarations of bsClass, and bsSize
that were missing.

I used the following sources:
* The documentation for pre-v1.0.0 react-bootstrap at https://react-bootstrap.github.io
* Double checked using the source code for pre-v1.0.0 at https://github.com/react-bootstrap/react-bootstrap

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

f changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://react-bootstrap.github.io
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-01-25 17:24 UTC, uniqueiniquity requested changes
Marking as changes requested until @sandersn's comment is addressed.

2019-01-29 10:31 UTC, bes commented on types/react-bootstrap/README.md
> +It does not make sense for everyone to upgrade to Bootstrap v3, therefore these typings
Thanks! Done!

2019-01-29 12:28 UTC, r3nya approved these changes

2019-01-29 17:36 UTC, uniqueiniquity approved these changes

2019-01-29 17:36 UTC, merged