[leaflet-providers] Fix previous breaking change and update tests to catch the mistake in future. Also change indentation to match style-guide.
DefinitelyTyped/DefinitelyTyped pull request #32240
Opened 2019-01-17 09:33 UTC by Shne

…at it allows types fulfilling either TileLayerOptions or {[name: string]: string}, instead of both. Requiring both forced every option to be a string, even those declared as numbers in TileLayerOptions.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/20b366a5758aa03da779e1ef1cff85857c7675ca#commitcomment-31957005
- [ ] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-01-17 09:39 UTC, Shne commented
With the new test cases I added, linting and compilation fails when using the previous type definitions, just like my own code did. It works with the new type definitions.

2019-01-23 03:20 UTC, uniqueiniquity requested changes
A couple things:

- The patch version of the package will automatically be updated, so don't worry about that.
- I agree that the previous change was incorrect. However, I'm worried about your change as well. With your change, you can provide `TileLayerOptions` as usual, but as soon as you provide any option outside of that set, then _all_ properties provided must be strings. This will likely conflict with existing properties in `TileLayerOptions` that have to be `number`s. Instead, you should just change the original location within `TileLayerOptions` to be `[name: string]: string`.

Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.
If you don't care about any of this stuff, I can always just pull in the changes.

2019-01-23 07:50 UTC, BendingBender commented
I think that an appropriate fix would look something like this (I didn't test it):

```typescript
interface ProviderOptions extends TileLayerOptions {
    [key: string]: string;
}
```

And then replacing all usages of `TileLayerOptions`.

2019-01-23 07:57 UTC, Shne commented
I'm on vacation this week. Next week I'll try the suggested changes and
include some tests with extra fields not in TileLayerOptions.
I'll also fix the email on the commits.


On Wed, Jan 23, 2019, 08:50 Dimitri Benin <notifications@github.com> wrote:

> I think that an appropriate fix would look something like this (I didn't
> test it):
>
> interface ProviderOptions extends TileLayerOptions {
>     [key: string]: string;
> }
>
> And then replacing all usages of TileLayerOptions.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32240#issuecomment-456703177>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABLGvk0ennPFvYLxrQ79SiZFh3WbvAsiks5vGBRCgaJpZM4aEynZ>
> .
>

2019-01-30 03:26 UTC, closed without merging