Update replace() definition from @types/node-emoji
DefinitelyTyped/DefinitelyTyped pull request #32286
Opened 2019-01-18 11:22 UTC by rimiti

Hello,

This pull request fix the `replace` function definition.

Concerned line of the official repository: 
https://github.com/omnidan/node-emoji/blob/5975ad506a97465d4050f8895a02b79cccea8373/lib/emoji.js#L272

It works fine. 🚀

2019-01-18 14:49 UTC, styu approved these changes

2019-01-18 21:30 UTC, DanielRosenwasser requested changes

2019-01-18 21:30 UTC, DanielRosenwasser commented
> If you are seeking a new maintainer, I'm in! rocket

It can be a burden as a heads up, but if you're interested, feel free to add yourself to the header comment at the top!

2019-01-19 13:41 UTC, rimiti commented on types/node-emoji/index.d.ts
> +export function replace(str: string, replacement: (emoji: Emoji) => string | string, cleanSpaces?: boolean): string;
Oh! Your right, I was distracted.
It's fixed.

2019-01-19 13:49 UTC, rimiti commented
It can be merged.

2019-01-22 23:57 UTC, merged

2019-01-22 23:57 UTC, DanielRosenwasser commented
Thank you!