[@types/ts-nameof] Add package
DefinitelyTyped/DefinitelyTyped pull request #32311
Opened 2019-01-19 18:11 UTC by dsherret

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes). -- Need to use the unnecessary generics because it's a compile time transformation
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration` -- It does have its own package, but it would be better if it were a types package so the global functions can be more easily resolved. Maybe there's a better way, but I'm not so sure.
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`. -- Note: dts-gen did not add `strictFunctionTypes`

2019-01-19 18:13 UTC, dsherret commented on types/ts-nameof/index.d.ts
> +// tslint:disable-next-line no-unnecessary-generics
This generic type is necessary because it's a compile time transformation. Ex. `nameof<MyInterface>()` -> `"MyInterface"`.

2019-01-19 18:20 UTC, BendingBender commented
The package for the types you've provided already has type definitions. You shoudn't add typedefs here if the package already has types.

2019-01-19 18:23 UTC, BendingBender requested changes
The package for the types you've provided already has type definitions. You shoudn't add typedefs here if the package already has types. See: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#create-a-new-package

2019-01-19 19:26 UTC, BendingBender approved these changes

2019-01-24 03:16 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2019-01-24 03:16 UTC, merged