[massive] Allow named parameters to be passed to Database.query
DefinitelyTyped/DefinitelyTyped pull request #32314
Opened 2019-01-19 20:51 UTC by pbgodwin

When using the latest definitions for massive, using the following sample from the massive docs:

```js
db.query(
  'select * from tests where id > ${something}',
  {something: 1}
).then(tests => {
  // all tests matching the criteria
});
```
Produces the following error:

```
Argument of type '{ something: string; }' is not assignable to parameter of type 'string[]'.
  Object literal may only specify known properties, and 'something' does not exist in type 'string[]'.
```

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://dmfay.github.io/massive-js/queries.html#raw-sql
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-01-19 23:32 UTC, AmazingTurtle requested changes
MassiveJS uses QueryStream from [pg-query-stream](https://github.com/brianc/node-pg-query-stream#use). That's using `pg-cursor` which is using `pg`. According to pg sources, here's the method for processing params:

https://github.com/brianc/node-postgres/blob/master/lib/utils.js#L49

Seems that it is also taking a Buffer, ArrayBuffer, Date, Arrays and objects (for which this PR was initially designed for).
I suggest taking a quick dive into the pg source to find out an adequate type for typings.

2019-01-20 00:10 UTC, pbgodwin commented
Thanks for the context & source pointers, it's super helpful. Would you expect a type that satisfies this function to look something like:

```ts
type QueryParameters = Array<any> | Buffer | ArrayBuffer | object | null | undefined;
```

I could also see wanting to restrict the types in the Array portion of the definition further.

2019-01-20 01:03 UTC, AmazingTurtle commented
I‘m unsure about what would be a good typing here. For example, in case of using a buffer, we should try to investigate what kind of data those represent. Maybe that‘s too much at all. Maybe we just leave it to something like

type QueryParams = Array<QueryParams> | string | number | object;

And then use the nullable parameter (`params?: QueryParams`) in typings.

I‘ll leave it to you

2019-01-20 20:10 UTC, AmazingTurtle approved these changes
Looks good to me

2019-01-22 17:49 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2019-01-22 17:49 UTC, merged