[openapi-factory ]Add HttpRequest type
DefinitelyTyped/DefinitelyTyped pull request #32342
Opened 2019-01-21 14:44 UTC by dhermyt

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/wparad/openapi-factory.js
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-01-21 15:04 UTC, runebaas commented on types/openapi-factory/index.d.ts
>      head(route: string, options: OpenApi.HttpMethodOptions, handler: (req?: any) => any): void;
You forgot this line

2019-01-21 15:04 UTC, runebaas commented on types/openapi-factory/index.d.ts
> +        headers?: {[key: string]: any},
this `{[key: string]: any}` should be `{[key: string]: string}`

2019-01-21 15:04 UTC, runebaas commented on types/openapi-factory/index.d.ts
> +        queryStringParameters?: {[key: string]: any},
this `{[key: string]: any}` should be `{[key: string]: string}`

2019-01-21 15:04 UTC, runebaas commented on types/openapi-factory/index.d.ts
> +        body?: (object | string);
Should be `body?: ({} | string)` or preferably `body?: any` because it can be anything

2019-01-21 18:01 UTC, runebaas approved these changes

2019-01-25 01:10 UTC, uniqueiniquity requested changes

2019-01-25 01:10 UTC, uniqueiniquity commented on types/openapi-factory/index.d.ts
> +    get<RequestBodyType = void, ResponseBodyType = void>(route: string, handler: (req: OpenApi.HttpRequest<RequestBodyType>) => (OpenApi.HttpResponse<ResponseBodyType | null> | Promise<OpenApi.HttpRe
`void` is definitely not what you want here; that should only be the type of functions that don't return anything. Did you mean `object` or `{}`?

2019-01-25 01:10 UTC, uniqueiniquity commented on types/openapi-factory/index.d.ts
> +    get<RequestBodyType = void, ResponseBodyType = void>(route: string, handler: (req: OpenApi.HttpRequest<RequestBodyType>) => (OpenApi.HttpResponse<ResponseBodyType | null> | Promise<OpenApi.HttpRe
In fact, I'm not even sure your usage of `RequestBodyType` here is helping you at all. What are you trying to do with it? See my comment in the test file.

2019-01-25 01:10 UTC, uniqueiniquity commented on types/openapi-factory/openapi-factory-tests.ts
> +function getResponse<T>(request: OpenApiFactory.HttpRequest<T>) {
Here, your generic `T` isn't helping you at all, since you can't depend on anything being true about it in the body of the function.

2019-02-01 01:30 UTC, closed without merging