Added typings for react-native-material-dropdown
DefinitelyTyped/DefinitelyTyped pull request #32373
Opened 2019-01-22 06:19 UTC by jaydeep987

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-01-22 19:21 UTC, uniqueiniquity requested changes

2019-01-22 19:21 UTC, uniqueiniquity commented on types/react-native-material-dropdown/index.d.ts
> +// TypeScript Version: 3.0
Is there a particular reason you need a minimum version of 3.0? It seems like you'd be fine with 2.8.

2019-01-23 03:09 UTC, uniqueiniquity approved these changes

2019-01-23 03:09 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2019-01-23 03:09 UTC, merged

2019-01-23 08:00 UTC, jaydeep987 commented
Thanks a lot!