[@types/express] adds overload for app.use mounting sub-app
DefinitelyTyped/DefinitelyTyped pull request #32385
Opened 2019-01-22 14:33 UTC by mako-taco

An overload of `app.use`, see docs for `app.mountpath` here (sub-app): https://expressjs.com/en/api.html#app.mountpath

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://expressjs.com/en/api.html#app.mountpath](https://expressjs.com/en/api.html#app.mountpath)
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-01-22 15:35 UTC, MichalLytek approved these changes

2019-01-22 15:35 UTC, kvcpr requested changes

2019-01-22 15:35 UTC, kacepe commented on types/express-serve-static-core/index.d.ts
> +    (path: PathParams, Application): T;
Missing parameter name

2019-01-22 19:45 UTC, MichalLytek approved these changes

2019-01-22 21:33 UTC, kvcpr approved these changes
LGTM

2019-01-23 00:12 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2019-01-23 00:13 UTC, merged

2019-01-31 23:11 UTC, cookrn commented
@mako-taco question for you. Not sure if my problem is with typescript, sinon types, or the additional signature added in this PR for express, but I'm unable to test spying on the binding of a `RequestHandler` to a path/method now. Previously, I had something like:

```typescript
const router = express.Router();
const method = "post";
const spy = sinon.spy(router, method);
const handler = (_: any, res: any) -> res.json({}) as express.RequestHandler;
functionThatBindsRoute(router, method, handler);
assert(spy.calledOnceWithExactly(method, handler));
```

The error I get now is: `Argument of type '(_: any, res: any) => RequestHandler' is not assignable to parameter of type 'Application | SinonMatcher'.`

I can get it to work though if I say `assert(spy.calledOnceWithExactly(method, handler as express.Application));` but that's not optimal because it's a lie 😉 

Any thoughts/ideas? Doesn't it seem like the other two possible signatures for `IRouteHandler<T>` aren't being respected?

2019-02-05 17:12 UTC, mako-taco commented
@cookrn I'm sorry, I'm not really familiar with sinon. With my change, all implementors of `use` would need to be able to handle the new signature.

2019-02-11 21:33 UTC, cookrn commented
@mako-taco no problem! Thanks for thinking it through.

The only thing I could think of is that since the order of function type declarations is important [[1](https://basarat.gitbooks.io/typescript/content/docs/types/functions.html#overloading)] [[2](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#function-overloads)], maybe it needed a tweak? When I have a chance, I'll play with it and see if that is able to fix.