Mithril - Additional signature for m.route.link
DefinitelyTyped/DefinitelyTyped pull request #32504
Opened 2019-01-26 01:52 UTC by spacejack

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://github.com/MithrilJS/mithril.js/blob/next/api/router.js#L66
This function has an additional signature that was missed in the type defs previously.
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-01-26 15:43 UTC, dead-claudia requested changes
Just a couple nits.

2019-01-26 15:43 UTC, isiahmeadows commented on types/mithril/index.d.ts
> +        link(options: {replace: boolean}): (vnode: Vnode<any, any>) => (e?: Event) => any;
Almost.

```suggestion
        link(options: RouteOptions): (vnode: Vnode<any, any>) => (e?: Event) => any;
```

2019-01-26 15:43 UTC, isiahmeadows commented on types/mithril/test/test-route.ts
> +const ex2 = h('a', {href: '/url', oncreate: route.link({replace: true})});
Also, it'd be worth adding tests for all the other route options, similar to `m.route.set`.

2019-02-02 00:35 UTC, dead-claudia approved these changes

2019-02-04 21:32 UTC, merged