[Bull] Add missing getJobCountByTypes definition
DefinitelyTyped/DefinitelyTyped pull request #32514
Opened 2019-01-26 16:16 UTC by letoche

ReturnsAdd missing getJobCountByTypes definition
Queue.getJobCountByTypes return a promise that resolves with the job counts for the given queue of the given types.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/OptimalBits/bull/blob/develop/lib/getters.js
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-01-26 17:42 UTC, pc-jedi requested changes

2019-01-26 17:42 UTC, pc-jedi commented on types/bull/index.d.ts
> +    getJobCountByTypes(types: string[]): Promise<JobCounts>;
`types` can also be just `string`.

2019-01-27 15:41 UTC, letoche commented on types/bull/index.d.ts
> +    getJobCountByTypes(types: string[]): Promise<JobCounts>;
added

2019-01-27 19:13 UTC, pc-jedi approved these changes
LGTM :+1: 

Thanks for the PR!

2019-01-29 00:16 UTC, PranavSenthilnathan commented
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

2019-01-29 00:16 UTC, merged