[d3-array] Update to 2.0 - add quickselect, group, and rollup
DefinitelyTyped/DefinitelyTyped pull request #32528
Opened 2019-01-27 12:01 UTC by Ledragon

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [2.0.0](https://github.com/d3/d3-array/releases/tag/v2.0.0)
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Should resolve issue #32162

2019-01-27 17:27 UTC, gustavderdrache requested changes
I'm not convinced the types of `group` and `rollup` are correct.

2019-01-31 15:30 UTC, denisname requested changes

2019-01-31 15:33 UTC, denisname commented
d3-array 2.0 "accept iterables (not just arrays) where relevant". You have not done that part. This v2 is a big update...

2019-02-03 07:53 UTC, Ledragon commented on types/d3-array/index.d.ts
> +export function group<TObject, TKey>(a: ArrayLike<TObject>, key: (value: TObject) => TKey): Map<TKey, TObject>;
Not to me: done

2019-02-03 07:53 UTC, Ledragon commented on types/d3-array/index.d.ts
> +export function rollup<TObject, TKey>(a: ArrayLike<TObject>, reduce: (value: ArrayLike<TObject>) => number, key: (value: TObject) => TKey): Map<TKey, TObject>;
Not to me: done

2019-02-03 08:08 UTC, Ledragon commented
Temporary update to see how it goes through CI, for sure not complete, the whole `iterable` stuff is not complete

2019-02-03 09:15 UTC, Ledragon commented
Can't dedicate any more time to this ATM, I keep going on this afternoon

2019-02-03 15:06 UTC, Ledragon commented
To sum up what has been going on:
* I created the v1 sub folder for d3-array
* I referenced it where relevent
* I had to update a generic return type to get the tests to pass. I don't know why it broke, but it seems to be due to TS 3.3. I opened a review
* I have a branch where all `ArrayLike` have been converted to `Iterable`. I however have a doubt about a couple of methods, whether they have to be changed or not. I opened [an issue](https://github.com/d3/d3-array/issues/91) on d3-array to ask about these

2019-02-05 09:38 UTC, denisname requested changes

2019-02-05 09:38 UTC, denisname commented on types/d3-array/d3-array-tests.ts
> +const p2: Array<number | string | Date | number[]> = d3Array.permute(testObject, ['when', 'more']);
Why you changed this?

2019-02-05 09:43 UTC, denisname commented on types/d3-array/d3-array-tests.ts
> +const p2: Array<number | string | Date | number[]> = d3Array.permute(testObject, ['when', 'more']);
Also remove all `@deprecated` in v2.

2019-02-12 10:32 UTC, closed without merging

2019-02-12 19:14 UTC, Ledragon commented
@denisname I'm not forgetting about this, I hope I get more time to finish it properly soon. 

As for your question, I changed the return type of the test because it fails with Tyepscript 3.3, and I have no clue why