Updated zadd overloading to handle score as number
DefinitelyTyped/DefinitelyTyped pull request #32582
Opened 2019-01-29 05:41 UTC by reichjustin

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:  https://redis.io/commands/zadd
- [X] Increase the version number in the header if appropriate.

2019-01-29 06:57 UTC, plantain-00 approved these changes

2019-01-29 19:28 UTC, PranavSenthilnathan requested changes

2019-01-30 23:31 UTC, reichjustin commented on types/ioredis/index.d.ts
> +        zadd(key: KeyType, ...args: Array<[ number, string ]>): Promise<number | string>;
Sounds good! Updated to:

`zadd(key: KeyType, ...args: Array<[ number, string ] | string>): Promise<number | string>`

2019-03-18 21:00 UTC, sheetalkamat requested changes

2019-03-18 21:00 UTC, sheetalkamat commented on types/ioredis/index.d.ts
> +        zadd(key: KeyType, ...args: Array<[ number, string ] | string>): Pipeline;
this signature is not combined, please combine this signature with first overload.

2019-03-25 21:33 UTC, closed without merging