[@types/react-highlight-words] Upgrading  typings to version 0.16.0
DefinitelyTyped/DefinitelyTyped pull request #32580
Opened 2019-01-29 02:33 UTC by salguerooo

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/bvaughn/react-highlight-words/blob/master/src/Highlighter.js
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-02-02 19:26 UTC, kelly-tock requested changes

2019-02-02 20:45 UTC, salguerooo commented on types/react-highlight-words/index.d.ts
> +    activeIndex?: number;
Thanks for the taking the time to review @kelly-tock!
I think the docs there need to be updated to reflect the actual implementation, which is this:
```
activeIndex: PropTypes.number,
```
(https://github.com/bvaughn/react-highlight-words/blob/master/src/Highlighter.js#L9)

I'll open a PR on the repo there to change the docs!

2019-02-02 20:50 UTC, salguerooo commented on types/react-highlight-words/index.d.ts
> +    highlightTag?: string | React.ComponentType<any>;
By looking at the implementation, it expects a component type (either a class or function), while ReactNode represents a rendered react element.

The place where it's used in the source code: https://github.com/bvaughn/react-highlight-words/blob/master/src/Highlighter.js#L121

2019-02-02 21:33 UTC, kelly-tock commented on types/react-highlight-words/index.d.ts
> +    activeIndex?: number;
cool with me

2019-02-02 21:34 UTC, kelly-tock commented on types/react-highlight-words/index.d.ts
> +    highlightTag?: string | React.ComponentType<any>;
yep, you're right.

2019-02-02 21:36 UTC, kelly-tock approved these changes

2019-02-03 05:54 UTC, salguerooo commented on types/react-highlight-words/index.d.ts
> +    activeIndex?: number;
I made the PR and it got merged btw! No more confusion moving forward.

2019-02-08 01:59 UTC, merged