[node] Add KeyObject support (added in node 11.6.0)
DefinitelyTyped/DefinitelyTyped pull request #32597
Opened 2019-01-29 18:49 UTC by btoueg

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/docs/latest-v11.x/api/crypto.html#crypto_class_keyobject
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-01-29 19:28 UTC, SimonSchick requested changes
The features you added were specifically added in node v11, you'll have to create a new definitions folder, HOWEVER there is currently some large scale refactoring going on so I would ask to coordinate with @rbuckton here.

2019-01-29 22:22 UTC, btoueg commented
Hi @rbuckton 👋 What's that refactoring mentioned by @SimonSchick ?

The change in TS definition in this PR is backward compatible with node 10, even though to add definitions that are not present in node 10...

What should be done here?

2019-02-05 00:09 UTC, btoueg commented on types/node/index.d.ts
> +        verify(object: Object | string | Buffer | KeyObject, signature: Buffer | NodeJS.TypedArray | DataView): boolean;
There is room for improvement, but let's agree that it's better typed than before, and also it's ordered according to the doc

2019-02-05 00:11 UTC, btoueg commented
👋 @SimonSchick 
I've updated the PR to match the refacto, and included most of your feedback
Let's consider merging this PR as it's definitely an improvement even if it's a small incremental change

2019-02-05 03:20 UTC, SimonSchick commented
You'll still have to move all current typings into a `v10` folder and tag these typings for node v11 in the `index.d.ts`

2019-02-05 13:44 UTC, Flarna commented
> Even if they are backward compatible? ok

It's not only about backward compatibility. If this is added users of NodeJs 10 - which are a lot as this is the current LTS version - could call an API which doesn't exist.
By adding a dedicated v10/v11 version users can choose the matching version.

2019-02-06 21:36 UTC, btoueg commented
I've bumped the version in the header, not sure if I should have started from 11.0 or be aligned with the current version of nodejs
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32597/files#diff-7d84e08967cded0b99ed4328aab0a1a8R1

2019-02-06 21:44 UTC, SimonSchick commented
You should only bump it up to the version your changes actually support.

2019-02-06 22:48 UTC, rbuckton commented
If @btoueg's changes go in before #32691, that's fine. I can update my PR and add a "typesVersions" entry for v10 as well.

2019-02-06 23:05 UTC, Flarna commented on types/node/crypto.d.ts
> +            passphrase?: string
I think passphrase can be `string | Buffer` (see https://nodejs.org/docs/latest-v11.x/api/crypto.html#crypto_keyobject_export_options)

2019-02-06 23:11 UTC, Flarna commented on types/node/crypto.d.ts
> +        symmetricSize: number;
```suggestion
        symmetricSize?: number;
```
see https://nodejs.org/docs/latest-v11.x/api/crypto.html#crypto_keyobject_symmetrickeysize

2019-02-06 23:15 UTC, Flarna commented on types/node/crypto.d.ts
> +        type?: 'pkcs1' | 'spki';
```suggestion
        type?: 'pkcs1' | 'pkcs8' | 'sec1';
```
see https://nodejs.org/docs/latest-v11.x/api/crypto.html#crypto_crypto_createprivatekey_key

2019-02-06 23:18 UTC, Flarna commented on types/node/crypto.d.ts
> +        saltLength?: number;
I think `padding?: number` is missing here.

2019-02-07 10:16 UTC, btoueg commented
Thanks for the feedback @Flarna

2019-02-09 18:11 UTC, Flarna commented
Seems there are two PRs now to create a v10 folder and add v11 changes (#32878).
@SimonSchick and @btoueg I think you should agree on who waits or you combine the changes into one PR.

2019-02-09 19:01 UTC, SimonSchick commented
If @btoueg is ok with that I will add their changes to my PR.

2019-02-11 08:47 UTC, btoueg commented
Go ahead

2019-02-13 13:52 UTC, closed without merging