Change SinonStub.resolves() to allow a partial of the type being resolved
DefinitelyTyped/DefinitelyTyped pull request #32683
Opened 2019-01-31 21:25 UTC by gjednaszewski

In https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31401, a change was made to correctly type the return value of the function being mocked.  This is pretty nice, generally, but a bit too restrictive.  Sometimes you need to mock functions that return a complicated data structure, which makes writing unit tests really cumbersome. 

 I made the change to require a partial type instead of the full type.  That way, when writing unit tests, you can have the stub resolve only the parts of the return value that the test needs, while providing type checking for the parts that are included.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/31401
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-01-31 22:32 UTC, 43081j commented
I'm not sure I agree with this.

The resolution type can be anything, even a primitive. It doesn't make sense to have a `Partial` of that (which introduces an index type). This would modify the type incorrectly.

It honestly sounds to me like you're trying to shortcut around writing the correct objects in tests by altering the types. You should really just write the full, correct objects that match your interfaces.

If you want a `Partial`, don't force that on to everyone else's types, just change your own types (so your promise resolves to a partial).

2019-01-31 22:43 UTC, 43081j requested changes
This will add an index type to all types, primitives included, see my main comment.

2019-01-31 23:11 UTC, SimonSchick commented
Also disagree, you can always use type assertions on your site.

2019-02-01 14:23 UTC, gjednaszewski commented
> The resolution type can be anything, even a primitive. It doesn't make sense to have a Partial of that (which introduces an index type). This would modify the type incorrectly.

OK, I understand the implications of the change so I'll withdraw the PR.

> It honestly sounds to me like you're trying to shortcut around writing the correct objects in tests by altering the types. You should really just write the full, correct objects that match your interfaces.

Yeah, I'm absolutely doing that, but not with my own interfaces.  Rather, third-party libraries where I don't have control over the types.  For instance a web request or DB query where I'm only interested in mocking the results, not all the other stuff that comes back with such a call - neither my code nor my tests care about any of that.  But in those cases, it looks like I can do this:

```
sandbox.stub(module, "method").resolves({stuffICareAbout: {...}} as ComplicatedType)
```

However, I'm still having trouble with certain cases (which my PR didn't actually address) where the type I want isn't properly being inferred.  Maybe you can help me figure out the correct way to handle this.  A good example is the `got` library.  

The types are set up with multiple overloads that change the return type depending on the options passed to the call:
```
    interface GotFn {
        (url: GotUrl): GotPromise<string>;
        (url: GotUrl, options: GotJSONOptions): GotPromise<any>;
        (url: GotUrl, options: GotFormOptions<string>): GotPromise<string>;
        (url: GotUrl, options: GotFormOptions<null>): GotPromise<Buffer>;
        (url: GotUrl, options: GotBodyOptions<string>): GotPromise<string>;
        (url: GotUrl, options: GotBodyOptions<null>): GotPromise<Buffer>;
    }
```
 
If you pass `json: true` in the request options, the type you get back is `any`.  This is what my code does and what I want to mock.  The problem is that the type inference picks the last overload where the return type is `Buffer`, which is wrong for my case.  I suppose I could wrap the call with my own function that always returns `any`, but I don't really want to do that just to make the tests work if I don't have to.  Is there a way to set up the stub so that `.resolves` can figure out which version I want? 

Thanks.

2019-02-04 15:04 UTC, closed without merging

2019-02-05 07:01 UTC, nicojs commented
@gjednaszewski In general, the best practice is to order your method overloads with the most generic one at the bottom: https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/declaration%20files/Do's%20and%20Don'ts.md#ordering

I've also asked a question on the TypeScript gitter to see if you could utilize the way the typing for `util.promisify` works for your benefit.

Hope that helps.