Add missing children prop in exotic component
DefinitelyTyped/DefinitelyTyped pull request #32785
Opened 2019-02-05 12:46 UTC by pkeuter

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

This change is needed when using for example: 

```
 private WrappedPlayer = React.forwardRef<HTMLAudioElement>((props, ref) => (
    <Player autoPlay ref={ref} {...props} />
  ));
```

This changes makes it possible to pass children, because now it throws an error because the created forwardref component doesn't accept the children prop.

```
<this.WrappedPlayer ref={this.player}>
          <source src={this.props.url} type="audio/mpeg" />
</this.WrappedPlayer>
```

![image](https://user-images.githubusercontent.com/433441/52274201-3a11a900-294c-11e9-8c25-7eb11dd85de4.png)

By adding `{ children?: ReactNode }`, this problem is mitigated.

2019-02-05 14:31 UTC, ferdaber commented
The wrapped component itself might not accept children though, in which case the exotic component has unsoundly added an extra available attribute. The actual fix in the example code would be to properly type `props` in the argument to `forwardRef`, or use the second generic type parameter to properly type the props:
```tsx
private WrappedPlayer = React.forwardRef<HTMLAudioElement, JSX.IntrinsicElements['audio']>((props, ref) => ( <audio autoPlay ref={ref} {...props} /> ));
```

2019-02-05 15:03 UTC, pkeuter commented
@ferdaber https://github.com/DefinitelyTyped/DefinitelyTyped/blob/23f5364ef4088e0b8d47381eb59042d77ae7a30b/types/react/index.d.ts#L472 also does this. These might also be used in components that might not accept children. Also, the `props` argument already provides 'children' as a prop, so that would be contrasting behaviour.

2019-02-05 15:08 UTC, ferdaber commented
Yeah it was a change I never really agreed with... but I can understand why it would be convenient. 

It makes it difficult to narrow the type of children if your component only accepts render functions, for example, and this predated render functions being super popular; but in the spirit of consistency I suppose it makes sense.

I'm going to abstain from reviewing so another maintainer can take a look so you can get their thoughts on it too.

2019-02-07 08:54 UTC, Jessidhia requested changes
Don't; this is broken _because_ of the "magic `children`" system and adding yet another place where magic children shows up just makes the problem worse while burying it under another layer.

You never said you accept any props in your component so it is **correctly** expecting `{}` as props. If you want to forward the props to `<audio/>` then you need to type your argument, and the correct type is not `{ children?: React.ReactNode }` but `props: React.ComponentPropsWithoutRef<'audio'>`.

2019-02-07 09:34 UTC, Jessidhia commented
This problem does give me an idea for a convenience overload for `forwardRef` itself:


This does give me an idea for a convenience overload for `forwardRef` itself.

```ts
type RefTypeOfComponent<T extends ReactType> = T extends any
    ? Required<ComponentPropsWithRef<T>> extends { ref: Ref<infer R> }
        ? R
        : never
    : never;

function forwardRef<T extends ReactType>(
    Component: RefForwardingComponent<RefTypeOfComponent<T>, ComponentPropsWithoutRef<T>>
): ForwardRefExoticComponent<ComponentPropsWithRef<T>>;
```

2019-02-07 21:19 UTC, pkeuter commented
@Jessidhia, @ferdaber, thanks for both of your comments. I can agree with the fact that adding `{ children?: React.ReactNode }` might not be the best way to go here. 

I don't really understand though, that if "magic children" are an issue, that the behaviour is so different between types. Shouldn't this be more coherent?

The method you're proposing seems nice! Are you going to add it? It doesn't really solve the other issue though. Is that already being addressed?

2019-02-07 21:26 UTC, ferdaber commented
If we were able to rewrite React types, `children` would not be built-in to the `SFC` type and the `React.Component` base `props` class property, because it leads to the unsoundness that @Jessidhia mentioned.

With the popularity of class based components it became an expectation; but actually un-annotated function components would not by default be allowed to accept children. Maybe we can move away from this convenience and have users actually strongly type children if their components accept them, by not adding to the cruft to exotic component types.

2019-02-07 21:35 UTC, pkeuter commented
That would IMHO at least be consistent and less confusing than it is now. But it would also mean that users would have to change their existing convenient methods (or just not upgrade).

2019-02-07 21:41 UTC, ferdaber commented
Yeah, I'm thinking that when we get better JSX facilities from the TS team, and when React 17 comes out, we can do a much bigger breaking change for all this stuff. I agree though that at this point it's not clear when `children` as a prop is auto added.

I think right now the most consistent convention is to *never* expect `children` to be auto added, and to explicitly add it to your props interface when you expect them. They will always work with the auto added children anyways.

2019-02-14 09:26 UTC, closed without merging