Fix spelling errors.
DefinitelyTyped/DefinitelyTyped pull request #32828
Opened 2019-02-06 12:58 UTC by Losses

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-02-06 13:52 UTC, claasahl requested changes
Hi @Losses 
Thanks for catching this.

I think the correct spelling is "Whether".

2019-02-06 13:52 UTC, claasahl commented on types/react-select/lib/components/Option.d.ts
>    /** Wether the option is focused. */
```suggestion
  /** Whether the option is focused. */
```

2019-02-06 13:54 UTC, Losses commented
@claasahl oops :P

2019-02-13 00:53 UTC, Losses commented
@typescript-bot All request has been resolved :P

2019-02-13 16:35 UTC, closed without merging

2019-02-14 07:03 UTC, claasahl commented
> 
> 
> @typescript-bot All request has been resolved :P

Hi @Losses 

I believe that you would have had to accept my suggested changes, otherwise @typescript-bot won't realize that progress had been made.
Would you like to create a new PR this?

2019-02-14 07:14 UTC, Losses commented
@claasahl Okay, I will create one later :D

2019-02-22 22:29 UTC, amcasey commented
I think the bot was waiting for an official sign-off or a LGTM comment.  I can re-open and merge if this is ready to go.

2019-02-23 09:20 UTC, claasahl commented
Hi @amcasey 

This fix was addressed as part of PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33085

2019-02-25 18:24 UTC, amcasey commented
@claasahl Thanks!