@types/mongoose findOneAndUpdate with option { rawResult: true }
DefinitelyTyped/DefinitelyTyped pull request #32874
Opened 2019-02-07 20:42 UTC by JulioJu

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e8b63b0bdafe5b3f86c1f2eb062e77aef9fe99c6/types/mongodb/index.d.ts#L708,L711
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

<hr />

Actually, definitions doesn't include `{ rawResult: true }` options. 

For instance https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cd60bb4798fc9feb18dfc2e6b378088bd0f87a4e/types/mongoose/index.d.ts#L3087,L3095 doesn't integrate `FindAndModifyWriteOpResultObject<T | null> | FindAndModifyWriteOpResultObject<T>`. 

See also definition in MongoDB : https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e8b63b0bdafe5b3f86c1f2eb062e77aef9fe99c6/types/mongodb/index.d.ts#L708,L711

Therefore I make the current pull request. 

Other functions with { rawResult: true } should also be changed. I wait to know if you validate changes for `findOneAndUpdate` before make a new PR for others definitions.

2019-02-09 14:55 UTC, emmanuelgautier approved these changes

2019-02-10 06:45 UTC, JulioJu commented
Please do not merge !

There are maybe others corrections to do accordingly to this.

2019-02-10 08:41 UTC, JulioJu commented
Maybe wait asnwer for https://github.com/Automattic/mongoose/issues/7506

2019-02-10 09:19 UTC, emmanuelgautier reviewed
waiting answer for [Automattic/mongoose#7506](https://github.com/Automattic/mongoose/issues/7506)

2019-02-10 09:23 UTC, emmanuelgautier requested changes
No changes expected, just prevent branch to be merged before response from mongoose [Automattic/mongoose#7506](https://github.com/Automattic/mongoose/issues/7506)

2019-02-15 18:08 UTC, JulioJu commented
@emmanuelgautier could you review please ?

Note that `Model.Find…And…` return a `Query` ! that's why I've deleted ModelOption interfaces

2019-02-20 09:38 UTC, emmanuelgautier approved these changes
Great Job ! 👍

2019-02-20 14:55 UTC, JulioJu commented
Thanks ;-)

2019-02-22 00:30 UTC, merged