fix issue: serialport: type error for "stopbits" #32692
DefinitelyTyped/DefinitelyTyped pull request #32942
Opened 2019-02-11 02:21 UTC by kidd808

Please fill in this template.

- [ ]  when i use "stopBits" from interface OpenOptions, there's an error occured with output: TypeError: "stopbits" is invalid: undefined. I think the member "stopBits" should be "stopbits".

- [ ] the source code path is types/serialport/index.d.ts.
- [ ] Test the change compile and run in my own code. 
- [ ] npm test passed

2019-02-11 02:42 UTC, apearson commented
@kidd808 Not sure changing stopBits to stopbits is the correct thing to do. 

The following shows it's currently the correct capitalization: 
https://github.com/node-serialport/node-serialport/blob/master/packages/stream/stream.js#L19
https://github.com/node-serialport/node-serialport/blob/master/packages/stream/stream.js#L63

Let me set up a test environment and test this.

2019-02-11 18:16 UTC, apearson commented
No changes are needed.  I tested and the stopBits is the correct capitalization to use. 

@kidd808 I can try to help you with your project. Message me with the email on my profile if you would like.

2019-02-11 18:17 UTC, apearson requested changes
No changes are needed. I tested and "stopBits" is the correct capitalization to use.

2019-02-12 02:04 UTC, kidd808 commented
> No changes are needed. I tested and "stopBits" is the correct capitalization to use.
> 
> @kidd808 I can try to help you with your project. Message me with the email on my profile if you would like.

@apearson, I have confirmed that, it's my fault. i used wrong data type for "stopBits", in my jest test case, which is written by js. But thanks all the same.

2019-02-12 02:04 UTC, closed without merging