Add rewriteUrls to the supported options
DefinitelyTyped/DefinitelyTyped pull request #32991
Opened 2019-02-12 10:50 UTC by ccapndave

Added `rewriteUrls`, which is supported in Less 3+

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/less/less.js/blob/master/lib/less/default-options.js#L41-L45
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-02-12 12:04 UTC, dwaxweiler commented
@ccapndave I think marking this option as optional is better and should fix the tests.

2019-02-12 12:05 UTC, dwaxweiler requested changes
I think marking this option as optional is better and should fix the tests.

2019-02-12 12:43 UTC, ccapndave commented
Cheers!

2019-02-12 14:36 UTC, dwaxweiler commented
@ccapndave You need to make the necessary change yourself. By the way, add your name to the authors in the header. :)

2019-02-19 06:50 UTC, ccapndave commented
Ah, I'm on holiday this week.  Can you leave it open till next week?

2019-02-19 16:23 UTC, ccapndave commented
You have officially passed the Turing test, bot.

2019-02-19 16:46 UTC, chigix commented
Maybe it's just a practice upon Wizard of Oz Method. @ccapndave  😄

2019-02-22 22:37 UTC, closed without merging

2019-02-22 22:54 UTC, amcasey commented
We're having CI problems that are causing significant issues for widely consumed packages (esp Node).  We know how frustrating it is and we're working on a fix, which you can track here: https://github.com/Microsoft/TypeScript/issues/29898.  Sorry!