Create non-secure.d.ts for nanoid
DefinitelyTyped/DefinitelyTyped pull request #33090
Opened 2019-02-15 10:05 UTC by Amorites

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/ai/nanoid/blob/master/non-secure/index.js>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-02-17 20:00 UTC, tautropfli requested changes
I think you forgot to add typings for [`nanoid/non-secure/generate`](https://github.com/ai/nanoid/blob/master/non-secure/generate.js). Could you add those too?

2019-02-18 07:14 UTC, tautropfli approved these changes
LGTM 👍

2019-02-19 23:58 UTC, amcasey requested changes
Minor comments.

2019-02-19 23:58 UTC, amcasey commented on types/nanoid/non-secure/generate.d.ts
> +declare function generate(alphabet: string, size?: number): string;
The underlying library appears to have nice doc comments for these functions.  Consider copying them over so that they appear in IntelliSense.

2019-02-19 23:58 UTC, amcasey commented on types/nanoid/tsconfig.json
> +        "non-secure/index.d.ts",
It would be great to add tests for these new functions/modules.

2019-02-21 02:19 UTC, amcasey approved these changes
Thanks!

2019-02-21 02:19 UTC, merged