ref lib name changed
DefinitelyTyped/DefinitelyTyped pull request #33098
Opened 2019-02-15 14:05 UTC by mehmetgelmedi

Updated ref types
lib.esnext.asynciterable lib name was wrong.
The reason for error is that the I character is not i in all languages.

Example when you use /// <reference lib="esnext.asyncIterable" /> and build your project you will get the following error

node_modules/@types/node/ts3.1/index.d.ts:10:21 - error TS2727: Cannot find lib
definition for 'esnext.asyncıterable'. Did you mean 'esnext.asynciterable'?

2019-02-15 18:00 UTC, Flarna requested changes
Could you please do the same change in file `types/node/v10/ts3.1/index.d.ts`

2019-02-15 19:35 UTC, Flarna approved these changes
Thanks!

2019-02-15 20:20 UTC, r3nya approved these changes

2019-02-15 20:21 UTC, BrunoScheufler approved these changes

2019-02-15 21:06 UTC, SimonSchick approved these changes

2019-02-22 22:11 UTC, amcasey commented
This change looks good.  Overriding CI.

2019-02-22 22:11 UTC, merged