[pg]: Add QueryResult array possibility if query has multiple statements
DefinitelyTyped/DefinitelyTyped pull request #33297
Opened 2019-02-22 03:42 UTC by fluggo

This is sure to be unpopular, because it ruins the library's usability, but multi-statement results were added to pg back in v7.0.0:

https://github.com/brianc/node-postgres/commit/28b330c88ebac2ea3ad565f8f2ce4ebe5c9a5579

This means that any query could possibly return an array of results instead of just one, and there's no way for TypeScript to distinguish the two cases. It's completely dynamic. So the user has to cast to one of the two types.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/brianc/node-postgres/commit/28b330c88ebac2ea3ad565f8f2ce4ebe5c9a5579
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-02-22 06:37 UTC, aleung approved these changes
It's a breaking change. 

Don't know how the version of typing package is generated. Any idea?

2019-02-22 14:22 UTC, fluggo commented
> It's a breaking change.
> 
> Don't know how the version of typing package is generated. Any idea?

It's generated from the first line of the source file. I left that line alone, so this becomes a patch change. I left it alone because _ideally_ that line matches the types to a major/minor version of the library itself.

But you're right, this _is_ a breaking change and I kind of want more comment before it's merged.

*MAINTAINERS*: Please don't merge yet. Let's get more time for comments.

2019-03-04 22:07 UTC, sandersn commented
I am just a DT maintainer, but my opinion is that this break should wait until a major version of pg, and that people who otherwise need it can just cast manually until then. 8 is the next one I guess?

2019-03-20 22:27 UTC, 43081j commented
I was browsing around and saw this.

If you didn't want to diverge versions/introduce a breaking change, you could consider introducing a type parameter which extends the union type and defaults to the non-array.

y'know like `query<T extends (QueryResult|QueryResult[]) = QueryResult>(queryConfig: QueryConfig): Promise<T>;` 🤷‍♂️

2019-04-01 18:52 UTC, uniqueiniquity requested changes
Marking as changes requested until the next major version of `pg` is released, at which time this package can also increase its major version.

2019-04-01 20:18 UTC, fluggo commented
That's fair, I hadn't thought of that, @43081j. I'll find some time to fix up my patch.

2019-04-08 19:32 UTC, closed without merging