nock.back.record returns rawHeaders array
DefinitelyTyped/DefinitelyTyped pull request #33523
Opened 2019-03-01 20:51 UTC by Downchuck

Using nock to record http requests the afterRecord method will have a rawHeaders attribute.

Presently this results in an error:
fetch.spec.ts:32:25 - error TS2551: Property 'rawHeaders' does not exist on type 'NockDefinition'.

rawHeaders is an optional string.

2019-03-02 09:55 UTC, afharo commented
Hey @Downchuck! 
Can you please point at the code where you saw these `rawHeaders` as an array of strings?
I’ve been looking at the nock repo and it looks to me that it has the same type as `reqheaders`. Does it not?

2019-03-02 17:08 UTC, Downchuck commented
https://github.com/nock/nock/blob/89fbcfbe9cfc2a19a6d89ff5d7196c3f30ffeca5/tests/test_replies.js

That shows the string array; the other two header attributes are
preprocessed in some manner into a structure, where raw is just split.


On Sat, Mar 2, 2019, 1:56 AM Alejandro Fernández Haro <
notifications@github.com> wrote:

> Hey @Downchuck <https://github.com/Downchuck>!
> Can you please point at the code where you saw these rawHeaders as an
> array of strings?
> I’ve been looking at the nock repo and it looks to me that it has the same
> type as reqheaders. Does it not?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33523#issuecomment-468905719>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAIomiGhkGtH8WMwupLdXkAqiCqpW4Voks5vSkq6gaJpZM4bZyo2>
> .
>

2019-03-02 21:46 UTC, afharo commented
Those `rawHeaders` from the test files you shared are the ones returned by the HTTP client `got` (https://github.com/sindresorhus/got). I don't think it has anything to do with this.

The `rawHeaders` in the nock scope object are assigned in here: https://github.com/nock/nock/blob/master/lib/recorder.js#L111
```javascript
rawHeaders: res.rawHeaders || res.headers
```

`res.rawHeaders` are indeed `string[]`, but `res.headers` is an object `{[key: string]: string}`.

So I think the type definition should be as follows because there is a chance for it to be an object (at least based on the implementation):
```typescript
rawHeaders?: string[] | { [key: string]: string | RegExp | { (headerValue: string): boolean; }; };
```

2019-03-02 22:20 UTC, mastermatt commented
If we are basing the `NockDefinition` interface on the [`generateRequestAndResponseObject`](https://github.com/nock/nock/blob/253cb65fabeb507b8fe97a18df8903173c299f11/lib/recorder.js#L84-L110) function then it needs further updating. `port`, `headers`, and `options` need to be removed. `rawHeaders` needs to be added with the type def as @afharo noted, and `responseIsBinary?: true` needs to be added also.

The other thing I noticed when poking around the lib is that the arg passed to `afterRecord` are the values pushed to an [array in this chunk of code](https://github.com/nock/nock/blob/master/lib/recorder.js#L271-L303), and [anything can be returned as long as it can be JSON encoded](https://github.com/nock/nock/blob/9b92c0c2e53641f1177d658a6a50fa832cf7c3f0/lib/back.js#L170-L180). Which means the def of `afterRecord` needs to be updated to 
```js
afterRecord?: (defs: string[] | NockDefinition[]) => { [k: string]: any };
```
I would also approve/prefer adding the  `{ [k: string]: any }` to the `NockDefinition` interface itself and leaving the response of `afterRecord` as `NockDefinition[]`, this would make the interface more accurate for `loadDefs` and `define` since `afterRecord` could add any extraneous key/values it wishes.

2019-03-05 04:23 UTC, Downchuck commented
Great investigative work -- I'll give another round at this to incorporate what y'all have found.

2019-03-08 00:29 UTC, sandersn requested changes
Looks like the maintainers requested some additional changes.

2019-03-14 02:15 UTC, Downchuck commented
Fastly fast. I'll take a look. The PR itself improved on current state -
but I totally agree with the reviews that more can be done.

I've been stuck in a multiday limbo of legacy typescript, webpack and bad
karma (lol pun).

On Wed, Mar 13, 2019, 5:29 PM TypeScript Bot <notifications@github.com>
wrote:

> @Downchuck <https://github.com/Downchuck> I haven't seen anything from
> you in a while and this PR currently has problems that prevent it from
> being merged. The PR will be closed tomorrow if there aren't new commits to
> fix the issues.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33523#issuecomment-472657937>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAIomuqNR2AfW7GS3GfjdyrIcWQGPi6Eks5vWZf3gaJpZM4bZyo2>
> .
>

2019-03-15 00:28 UTC, closed without merging