Add types for plurals-cldr
DefinitelyTyped/DefinitelyTyped pull request #33553
Opened 2019-03-03 07:35 UTC by ChaosinaCan

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-03-04 02:42 UTC, plantain-00 requested changes

2019-03-04 02:42 UTC, plantain-00 commented on types/plurals-cldr/index.d.ts
> +export default plural;
It should be `export = `: https://github.com/nodeca/plurals-cldr/blob/master/index.js#L93

2019-03-04 03:11 UTC, ChaosinaCan commented
Fixed.

2019-03-04 06:53 UTC, plantain-00 approved these changes

2019-03-08 00:17 UTC, merged

2019-03-08 01:35 UTC, ChaosinaCan commented
Thanks!