Add type definitions for seen.js (http://seenjs.io)
DefinitelyTyped/DefinitelyTyped pull request #33604
Opened 2019-03-05 06:44 UTC by admvx

General checklist:
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
  Tests pass but only after `safe-buffer` and `normalize-url` (unrelated to this update) are added to `node_modules/types-publisher/dependenciesWhitelist.txt`
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-03-06 15:20 UTC, plantain-00 approved these changes

2019-03-06 15:20 UTC, plantain-00 commented on types/seen/tsconfig.json
> +        "strictNullChecks": false,
It could be better if this enabled

2019-03-08 02:51 UTC, sandersn requested changes
Can you turn on strictNullChecks? What fails with it on?

2019-03-08 03:47 UTC, admvx commented
Thanks for reviewing, @plantain-00 and @sandersn! Sorry about the confusion with strictNullChecks; I hadn't realised I'd left it off. No tests failing with it enabled, but I did have to add a non-null assertion to the test here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/a716830bc976036f403c6a8466e966236c46b54b/types/seen/seen-tests.ts#L53

2019-03-08 18:49 UTC, sandersn approved these changes

2019-03-08 18:49 UTC, merged