[electron-store] augment NodeRequireFunction
DefinitelyTyped/DefinitelyTyped pull request #33608
Opened 2019-03-05 10:27 UTC by romansp

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

Following what 'electron' does in their type declarations over here: https://github.com/electron/electron-typescript-definitions/blob/42064450b8c9f4deae128edaf2d0c7070c483dbe/base/base_footer.ts#L5-L7

This allows to have proper types when doing conditional import like this: 
```
if (isElectronRenderer) {
  const Store = require("electron-store");
  // `Store` is of type `ElectronStore` here
}
```

2019-03-05 16:40 UTC, unindented commented
@romansp can you paste the error you get if you try to do a conditional require with the current version?

Also, can you add something to the test file that covers your addition?

2019-03-05 18:13 UTC, romansp commented
@unindented there is no error actually. What I mean is that inside conditional import `require("electron-store")` return value is of type `any`, but could be of `typeof ElectronStore`. 

This removes required `as typeof ElectronStore` cast or explicit `const Store: ElectronStore` annotation.

Yes, I would like to add test case for this. Wondering how I can test that 🤔.

2019-03-06 10:34 UTC, romansp commented
It doesn't seem to be a way to type-check against usage of `any` type in this case. 

The only thing I found is TSLint ['no-unsafe-any'](https://palantir.github.io/tslint/rules/no-unsafe-any/) rule. It works, and linter reports error when `NodeRequireFunction` augument is missing, but it doesn't look as a good idea at all - no other type definition in DefinitelyTyped uses this rule.

2019-03-18 20:31 UTC, sheetalkamat requested changes
You shouldn't need this change.

2019-03-25 21:31 UTC, closed without merging