[oakdex-pokedex] Added type defs for oakdex-pokedex
DefinitelyTyped/DefinitelyTyped pull request #33657
Opened 2019-03-06 16:27 UTC by jalyna

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-03-06 17:54 UTC, SimonSchick approved these changes
Looks ok overall, some minor style issue.

Also I noticed you initially added the types to your package but then removed them from the published bundle, did you run into any issues we might be able to help with?

2019-03-06 17:54 UTC, SimonSchick commented on types/oakdex-pokedex/index.d.ts
> +    de: string,
Nit: `,` should be `;` in all interfaces.

2019-03-06 17:54 UTC, SimonSchick commented on types/oakdex-pokedex/index.d.ts
> +export {}
NIt: is this needed?

2019-03-07 11:11 UTC, jalyna commented
@SimonSchick Thanks for your feedback, all applied :heart:

2019-03-07 11:26 UTC, SimonSchick approved these changes

2019-03-08 19:30 UTC, sandersn requested changes

2019-03-08 19:30 UTC, sandersn commented on types/oakdex-pokedex/tslint.json
> +    "semicolon": [
Can you please remove these overrides and fix the resulting lint?

2019-03-08 23:20 UTC, sandersn approved these changes

2019-03-08 23:20 UTC, merged