react-window: Get rid of unnecessary any types
DefinitelyTyped/DefinitelyTyped pull request #33651
Opened 2019-03-06 14:58 UTC by swissmanu

* Introduce Generic Type Parameter for itemData
* Change return values of event handlers to void

----

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://react-window.now.sh/#/api/FixedSizeList (and other components)
- [x] Increase the version number in the header if appropriate.

2019-03-06 21:27 UTC, swissmanu commented
will have a look at the failed ci run tomorrow

2019-03-07 06:10 UTC, swissmanu commented
all lights green ✅

2019-03-07 20:27 UTC, heyimalex commented
Shouldn't the generic default be `undefined`?

It'd be cool if we could make this safer. Because `itemData` is optional, technically everything it gets passed to should be optional too. I took a crack at this a while ago, but couldn't figure out a good way to make it work which is why I settled for `any`. It looks like typescript fixed the issue with generic type inference in react components so maybe it's possible now? Looks something like this:

```ts
type OptionalItemData<T> = T extends undefined
  ? { itemData?: undefined }
  : { itemData: T };

type CommonProps<T = undefined> = OptionalItemData<T> & {
  // The rest of the common props
};
```

Anyhow, I think the odds someone passes `itemData: undefined` to a `FixedSizeList<T>` they manually specified the generic type of is probably really low, so I support this.

2019-03-07 21:06 UTC, heyimalex commented
Oh and also there have been changes to the api in 1.6. Check the [changelog](https://github.com/bvaughn/react-window/blob/master/CHANGELOG.md) for details but from [#142](https://github.com/bvaughn/react-window/pull/156) I gather `direction` has basically been renamed to `layout` in lists, and now `direction` is for `"ltr" | "rtl"` rendering.

2019-03-08 05:40 UTC, swissmanu commented
thx for your review. will have another look

2019-03-18 18:57 UTC, heyimalex requested changes
Just to be clear, my only actual issue with this before merge is that I think the generic default should be `T = undefined`. The other suggestions can be done in separate PRs.

2019-03-25 19:44 UTC, jgoz requested changes

2019-03-25 19:44 UTC, jgoz commented on types/react-window/index.d.ts
> +// Type definitions for react-window 1.6
You should merge the latest changes from `master`. This has already been bumped to 1.7.

2019-03-25 21:31 UTC, closed without merging