[styled-system] Update ResponsiveValue to accept generic type variables for breakpoints
DefinitelyTyped/DefinitelyTyped pull request #33803
Opened 2019-03-12 10:08 UTC by ktranada

**Context**:
I am using an object to define my breakpoints.

**Issue**:
As it currently stands, `ResponsiveValue` utilizes an index signature - accepting any/all propertiets.

**Proposal**:
Update `type ResponsiveValue<T>` to take in an additional generic type variable for breakpoints, while also providing a default (string index signature) - which was previously hardcoded. In doing so, type consumers will have the ability to extend and have their breakpoint objects be strongly typed.

--- 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Defining breakpoints as an object and then passing an object to configure responsive styles](https://styled-system.com/responsive-styles#using-objects)
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-03-12 11:26 UTC, alloy commented
LGTM 👍 

Could you add some test coverage that actually uses the alias generic, though? (And I mean _additional_ test coverage, not by changing the existing tests that now exercise the default value of the type parameter.)

2019-03-12 12:24 UTC, alloy requested changes
Hold that thought, @typescript-bot

2019-03-12 14:45 UTC, ktranada commented
@alloy Of course! Will get that in shortly - brain was a lil foggy at 330AM 🤪

2019-03-12 16:45 UTC, ktranada commented
@alloy In writing my tests, I've noticed that while the shape of the Breakpoint Alias is now strongly typed, the values are not.

For example:

```
 interface BreakpointAlias {
     small?: string | number;
     medium?: string | number;
     large?: string | number;
 }

 interface GenericBreakpointBoxProps<T = TLengthStyledSystem, B = BreakpointAlias> extends 
    FlexWrapProps<T, B>,
    FlexDirectionProps<T, B>,
    WidthProps<T, B>
{ }
```

While defining `BreakpointAlias` outside and passing it to the `GenericBreakpointsBoxProps` can reduce keystrokes, every property defined via the alias will now be of the same type. So `flexWrap` will accept any string | number when it should be typed to the `FlexWrapProperty` defined in `csstype`.

Please feel free to correct me, but it feels that in order to support this feature, the consumer will have to manually extend the props with the correct CSS Property.

For example:
```
interface BreakpointAlias<T> {
     small?: T;
     medium?: T;
     large?: T;
 }

interface FlexWrapProps extends 
  styledSystem.FlexWrapProps<string | number, BreakpointAlias<CSS.FlexWrapProperty>> {}

....
```

While this is a tradeoff, I still value the ability to have my aliases strongly typed. What are your thoughts?

2019-03-12 17:12 UTC, ktranada commented
Also, the need to extend Props to handle breakpoint aliases can come by a need-to-have basis. In that the consumer can decide which props will need to handle responsive styles via object.

2019-03-13 09:52 UTC, alloy commented
Ah, I see. In a [media query related library](https://github.com/artsy/react-responsive-media) of our own, we have [a single function](https://github.com/artsy/react-responsive-media/blob/9b546c24b2f9261b4c9874168cb5016ad1325142/src/Media.tsx#L300-L304) that creates the actual API to use, which also allows for making the entire generic API specific to your project’s breakpoints. Obviously this isn’t a change we can make to styled-system or the types, but perhaps what you could do is create a similar function/library that would wrap styled-system to give you a version of the API that has the breakpoint aliases made specific?

I do think that for this types package we should leave the simplest existing default in place and not break any projects, i.e. leave it as-is.

Does that sound good?

2019-03-19 12:25 UTC, closed without merging