knex column builder defaultTo() accepts null
DefinitelyTyped/DefinitelyTyped pull request #33882
Opened 2019-03-14 16:34 UTC by panzi

knex's `ColumnCompiler.defaultTo()` method also accepts `null` values.

2019-03-14 18:19 UTC, mastermatt commented
@panzi can you add and fill out [the template](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/PULL_REQUEST_TEMPLATE.md) for this PR please. It will have you include links to docs and/or code backing up the change.
Also add a call in the test file that takes a `null`.

2019-03-14 18:32 UTC, panzi commented
Sorry, got work stress and then I'll be away for 1.5 weeks. I just noticed this while working and wanted to let you know. Have no time for more. But I can link you to that: https://github.com/tgriesser/knex/blob/11fdc0c90afbcf8011aea5a2493458dfda3052f6/src/schema/columncompiler.js#L150

2019-03-14 19:36 UTC, mastermatt requested changes
I don't think this PR should be merged.
- It seems like `null` may not actually work as a value https://github.com/tgriesser/knex/issues/3092
- As of last Oct, Knex bundles its own types https://github.com/tgriesser/knex/pull/2845

2019-03-16 20:39 UTC, mastermatt commented
I've gone ahead and begun the process of removing `@types/knex`. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33889

2019-03-21 20:30 UTC, closed without merging