[@types/parse] Update with LocalDatastore
DefinitelyTyped/DefinitelyTyped pull request #33981
Opened 2019-03-18 19:30 UTC by dplewis

Updated to reflect changes in Parse 2.2.1.

There is an issue I can't figure out.

`Cannot assign to 'serverURL' because it is a read-only property.`

I don't know why this happens as serverURL isn't readonly in the @type/parse but can be fix with the following workaround.

(Parse as any).serverURL = '';

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/parse-community/Parse-SDK-JS/blob/master/src/Parse.js
- [X] Increase the version number in the header if appropriate.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-03-18 22:46 UTC, agoldis requested changes
Please check out the suggested changes. 
Also, it would be nice to see tests, e.g.:

```typescript
async function test_local_datastore() {
    Parse.enableLocalDatastore();

    if (Parse.isLocalDatastoreEnabled()) {
        for (let key in await Parse.dumpLocalDatastore()) {
        }
    }
}
```

2019-03-18 22:46 UTC, agoldis commented on types/parse/index.d.ts
> +    function isLocalDatastoreEnabled(): any;
```suggestion
    function isLocalDatastoreEnabled(): boolean;
```

2019-03-18 22:46 UTC, agoldis commented on types/parse/index.d.ts
> +    function dumpLocalDatastore(): any;
```suggestion
    function dumpLocalDatastore(): Promise<{ [key: string]: any }>;
```

2019-03-18 22:48 UTC, agoldis commented
> There is an issue I can't figure out.
> `Cannot assign to 'serverURL' because it is a read-only property. `

BTW, @dplewis when do you see the error?

2019-03-19 00:32 UTC, dplewis commented
@agoldis Thanks for the review. I didn't realize how much was missing from here

2019-03-20 06:31 UTC, agoldis requested changes
@dplewis great job adding so many missing definitions! 👏🏻

I am sorry for the amount of comments, but there were quite a lot of changes. 

If you plan to submit more PRs similar to this one I'd suggest:

1. Create a separate commit for changes that just move code around without modification and mention that commit in the PR body. That will make the review easier.

2. Create a scoped by class and smaller PRs - it will increase the chance that the PR will be reviewed and approved quickly.

3. The PR had some obvious type mismatches, I suspect you're using `dts-gen` and that's fine, probably smaller set of changes would allow to validate them manually before submitting the PR for review.

2019-03-20 06:31 UTC, agoldis commented on types/parse/index.d.ts
> +        static fromJSON<U extends Object>(className: any, json: any): Query<U>;
```suggestion
        static fromJSON<U extends Object>(className: string, json: any): Query<U>;
```

2019-03-20 06:31 UTC, agoldis commented on types/parse/index.d.ts
> +        containsAllStartingWith(key: string, values: any[]): Query<T>;
```suggestion
        containsAllStartingWith(key: string, values: string[]): Query<T>;
```

2019-03-20 06:31 UTC, agoldis commented on types/parse/index.d.ts
> +        sortByTextScore(): any;
```suggestion
        sortByTextScore(): this;
```

2019-03-20 06:31 UTC, agoldis commented on types/parse/index.d.ts
> +        withJSON(json: any): any;
```suggestion
        withJSON(json: any): this;
```

2019-03-20 06:31 UTC, agoldis commented on types/parse/index.d.ts
> +        static become(sessionToken: string, options?: SuccessFailureOptions): Promise<User>;
`SuccessFailureOptions` is incorrect here, see the list of accepted options [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/ParseUser.js#L637)

2019-03-20 06:39 UTC, dplewis commented
@agoldis I used dts-gen as a base. I really like how everything is in alphabetical order, makes it easier to find what is missing. If you want I can close this out and follow your suggestions on creating separate PR's go for it.

I be busy this week with releasing new versions of Parse. So If you could take this over that would be great

2019-03-20 21:56 UTC, dplewis commented
@agoldis I made the requested changes and found a few more. How does this look?

2019-03-21 03:17 UTC, agoldis approved these changes
Thanks @dplewis!

2019-03-21 16:57 UTC, merged