Add new ServiceNow London API type definitions
DefinitelyTyped/DefinitelyTyped pull request #34162
Opened 2019-03-24 21:22 UTC by johncaruso

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

2019-03-25 17:16 UTC, sheetalkamat requested changes

2019-03-25 17:16 UTC, sheetalkamat commented on types/servicenow-london/tslint.json
> +    "rules": {
Please remove everything from here except extends clause. New packages cannot have custom tslint rules/options

2019-03-25 22:43 UTC, johncaruso commented on types/servicenow-london/tslint.json
> +    "rules": {
OK. Done.

2019-03-25 23:12 UTC, johncaruso commented
Will the bot update this to get another review?

2019-03-28 09:27 UTC, johncaruso commented
@sheetalkamat I've made changes, all checks have passed. Shouldn't this get tagged with Awaiting reviewer feedback? Just want to make sure you're not waiting on me for something further.

2019-04-08 02:05 UTC, DanielRosenwasser commented
Thanks!

2019-04-08 02:05 UTC, merged