[node-cron] Define timezone as a string literal
DefinitelyTyped/DefinitelyTyped pull request #34179
Opened 2019-03-25 11:38 UTC by RMHonor

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-03-25 12:30 UTC, burtek commented
I'm not sure that relying on another package's data is a good idea here. Wouldn't it be safer to create typings for `tz-offset` and depend on them here? At least when `tz-offset` data changes, one can change it in `@types/tz-offset` and it would be handled here too...

2019-03-25 20:16 UTC, RMHonor commented
Whilst I agree, `tz-offset` is not a package published on NPM. Is it normal to have type libraries published available for libraries which aren't available through standard means?

Happy to make a start on `tz-offset` anyway

2019-03-25 21:28 UTC, burtek commented
> Whilst I agree, `tz-offset` is not a package published on NPM

https://www.npmjs.com/package/tz-offset 🤔

2019-03-25 21:31 UTC, RMHonor commented
Blind as a bat 😆

2019-03-25 21:32 UTC, burtek commented
Happens to me too, np :D

2019-03-26 08:39 UTC, RMHonor commented
#34209 may be of interest to you!

2019-03-26 09:43 UTC, burtek commented
@RMHonor approved that one :)

2019-04-01 11:55 UTC, burtek requested changes
Make it depend on `@types/tz-offset` as per previous discussion

2019-04-07 14:40 UTC, burtek commented
@RMHonor any plans for making this happen? :)

2019-04-08 08:12 UTC, RMHonor commented
PR updated to use `tz-offset`

2019-04-08 21:34 UTC, burtek requested changes
Shouldn't `@types/tz-offset` be added to dependencies in `package.json` now? [It won't be included by default](https://github.com/DefinitelyTyped/DefinitelyTyped#i-notice-some-packages-having-a-packagejson-here).

```json
{
    "private": true,
    "dependencies": {
        "@types/tz-offset": "0.0.0"
    }
}

2019-04-09 08:16 UTC, RMHonor commented
Ah, of course. Pushed a new `package.json`

2019-04-09 08:18 UTC, burtek approved these changes

2019-04-09 08:19 UTC, burtek requested changes

2019-04-09 08:19 UTC, burtek commented on types/node-cron/package.json
> +      "tz-offset": "0.0.0"
`@types/tz-offset`

2019-04-09 08:24 UTC, RMHonor commented on types/node-cron/package.json
> +      "tz-offset": "0.0.0"
Updated

2019-04-09 08:25 UTC, burtek commented
Actually my bad 🤦‍♂️ it must have changed some time ago
![image](https://user-images.githubusercontent.com/2940958/55784847-afffd100-5ab1-11e9-98e7-988740d7301b.png)

2019-04-09 08:31 UTC, RMHonor commented
Ah, that's clever, so DefinitelyTyped is able to look at the required imports in `.d.ts` files and adds them as dependencies?

Updated to remove the `package.json`

2019-04-09 08:32 UTC, burtek commented
> DefinitelyTyped is able to look at the required imports in `.d.ts` files and adds them as dependencies?

looks like this.

2019-04-09 08:32 UTC, burtek approved these changes

2019-04-10 17:29 UTC, merged

2019-04-10 17:36 UTC, burtek commented
@RMHonor it does work ;)
https://www.npmjs.com/package/@types/node-cron?activeTab=dependencies