ramda v0.26 add more strict type checking for propEq function
DefinitelyTyped/DefinitelyTyped pull request #34332
Opened 2019-03-29 18:55 UTC by radziksh

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint ramda`
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://ramdajs.com/docs/#propEq

- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-03-29 19:13 UTC, radziksh commented
@tycho01 @mdekrey @mrdziuban @sbking @afharo @teves-castro @hojberg @samsonkeung @angeloocana @raynerd @googol @moshensky @ethanresnick @CaptJakk @deftomat @deptno @blimusiek @biern @rayhaneh @rgm @drewwyatt @jottenlips @minitesh @Krantisinh @pirix-gh could you please review my pr when you have time?

2019-04-04 20:28 UTC, DanielRosenwasser commented
Ping - this looks good to me, but I wanted to get some feedback from the authors first.

2019-04-05 07:57 UTC, googol requested changes
The `= any` defaults to the type parameters seem like a very bad idea to me, it's going to be very easy to forget defining those type parameters

2019-04-05 15:21 UTC, radziksh commented
@googol @DanielRosenwasser Yes, this is not an ideal solution, but I had to enter `any` in order to maintain backward compatibility and allow programmers to gradually switch to the typed version of this function. Otherwise, almost all users will have problems with the next update.

2019-04-23 13:34 UTC, radziksh commented
@DanielRosenwasser @googol ping

2019-04-23 15:14 UTC, googol commented
What is the problem this solves? I am still worried about those `= any`s in the type parameters.

2019-04-23 16:12 UTC, radziksh commented
> Ping - @googol @DanielRosenwasser Yes, this is not an ideal solution, but I had to enter `any` in order to maintain backward compatibility and allow programmers to gradually switch to the typed version of this function. Otherwise, almost all users will have problems with the next update.

@googol I wanted to draw attention to my comment, because if I remove `= any` then many users who use this function will have errors after the update. Specifically, on my project, this is not a problem, but I do not want to break the projects of other people, as I see that this library is quite popular. If you still think that any is a bad idea, then I am ready to remove it.

2019-04-23 19:39 UTC, googol commented
Right, I understand that. But what is the problem this PR is solving at its core?

2019-05-20 15:47 UTC, radziksh commented
Make the world a better place? :)

2019-07-08 17:44 UTC, Nemo108 commented on types/ramda/index.d.ts
> +        propEq<T = any, K extends keyof T = any>(name: K, value: T[K]): (obj: T) => boolean;
Не, чувак, так не пойдет. Давай либо все перегрузки правь, либо никакие. И без any, желательно

2019-07-17 12:38 UTC, KrzysztofKarol commented
Hi @radziksh, any update on this? It will be very helpfull (type and typo safe)!

2019-12-19 09:32 UTC, orta commented
Hey folks, it's been 6 months-ish - the merge conflict on this is pretty wild, and we've not had one approval from someone who owns the definition. I'm going to preemptively close this PR, which doesn't mean that the code is bad, but that we'd like to try this repo fresh given that it's one of the most popular reps in the world. 

Re-opening with fresh code its totally OK 👍

2019-12-19 09:32 UTC, closed without merging