Update Redirect to use RouteComponentProps
DefinitelyTyped/DefinitelyTyped pull request #34461
Opened 2019-04-04 09:08 UTC by lifeiscontent

Update Redirect to use RouteComponentProps

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-04-04 14:26 UTC, kingdaro commented
[I'm reading through the docs](https://reach.tech/router/api/Redirect), and I don't see where it allows using normal route component props. The only ones I see listed are those that the type definitions currently define. Could you point to where it does? Or was there a non-documented change?

2019-04-04 14:52 UTC, itsMapleLeaf requested changes
[I'm reading through the docs](https://reach.tech/router/api/Redirect), and I don't see where it allows using normal route component props. The only ones I see listed are those that the type definitions currently define. Could you point to where it does? Or was there an undocumented change?

2019-04-05 22:09 UTC, lifeiscontent commented
@kingdaro any child of `Router` is considered a `Route` component, so now that I've type it out, my changes don't make sense. However another question now enters my head, Can children be typed?

2019-04-10 15:45 UTC, itsMapleLeaf approved these changes
Children can't be typed, so this does look like the only real solution to that. I'll approve this

2019-04-10 17:47 UTC, merged

2019-04-10 23:57 UTC, lifeiscontent commented
@kingdaro I don't think this should of been merged, Redirect components aren't always direct children of Router so now this change makes the incorrect assumption that it is the case.

I think although not ideal, it'd be better in user land to create another function like this:

```ts
const RedirectRoute: React.FC<RouteComponentProps & RedirectProps> (props) => <Redirect {...props} />
```