[@types/mongodb] Collection.mapReduce
DefinitelyTyped/DefinitelyTyped pull request #34584
Opened 2019-04-09 13:56 UTC by lenartbezek

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#mapReduce
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

***

Collection reduce function does not necessarily take string as the key argument, but it does take an array of values that should be reduced into a single value.

2019-04-10 08:09 UTC, CaselIT approved these changes

2019-04-10 08:12 UTC, CaselIT commented
Looks good.
Maybe you can also add an optional type `TResult=any` so that the callback can be typed if needed?
Something like
```ts
mapReduce<TKey, TValue, TResult=any>(map: CollectionMapFunction<TSchema> | string, reduce: CollectionReduceFunction<TKey, TValue> | string, callback: MongoCallback<TResult>): void;
```

2019-04-10 17:51 UTC, uniqueiniquity requested changes
Since this is a popular package, could you add a brief test to avoid your change being regressed in the future? Thanks!

2019-04-11 16:30 UTC, uniqueiniquity approved these changes

2019-04-11 16:30 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2019-04-11 16:30 UTC, merged