[@types/auth0-js] add missing error_description field
DefinitelyTyped/DefinitelyTyped pull request #34583
Opened 2019-04-09 13:03 UTC by marknelissen

Auth0-js is not consistent in the use of errorDescription within error objects returned to the callback method, not even within the same method (eg. WebAuth.checkSession). Depending on the error (and thus the place where it is constructed) the description in contained in either errorDescription or error_description.

On top of this, the official documentation snippets make use of error_description. It is unclear which is the "official" one, but technically, both are possible. So the typing should reflect this.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/auth0/auth0.js/blob/master/src/web-auth/index.js>>
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-04-09 13:42 UTC, adrianchia approved these changes

2019-04-10 17:31 UTC, uniqueiniquity requested changes
Since this is a popular package, [perhaps it would be best to create a `v8` directory](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/a26cc7b6f60de02a152168a21a9159a856bf581b#if-a-library-is-updated-to-a-new-major-version-with-breaking-changes-how-should-i-update-its-type-declaration-package).

2019-04-11 22:39 UTC, adrianchia commented
I believe versions before v9 are [deprecated](https://auth0.com/docs/libraries/auth0js/v9/migration-guide#should-i-migrate-to-v9-) now. We could probably verify what is missing.

2019-04-11 23:17 UTC, uniqueiniquity approved these changes

2019-04-11 23:17 UTC, merged

2019-04-12 07:49 UTC, marknelissen commented
This change is also compatible with v8, since the behaviour I described at the start of the pull request is also present in v8 https://github.com/auth0/auth0.js/blob/v8.12.3/src/web-auth/index.js . It is thus not a breaking change.