[office-js-preview] (Outlook) Add masterCategories
DefinitelyTyped/DefinitelyTyped pull request #34644
Opened 2019-04-10 23:11 UTC by ElizabethSamuel-MSFT

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-04-10 23:12 UTC, ElizabethSamuel-MSFT commented
Please do not merge yet as we're await technical review. Thanks.

2019-04-11 17:53 UTC, uniqueiniquity requested changes
Marking as changes requested until technical review is completed.

2019-04-12 23:04 UTC, exextoc approved these changes

2019-04-12 23:04 UTC, exextoc commented on types/office-js-preview/index.d.ts
> +        removeAsync(categories: CategoryDetails[], options?: Office.AsyncContextOptions, callback?: (asyncResult: Office.AsyncResult<void>) => void): void;
This is not a CategoryDetails object array, it should be an array of category strings that correspond to the name of the categories in the master table.

2019-04-15 15:26 UTC, ElizabethSamuel-MSFT commented
We've received technical review. Thanks.

2019-04-15 15:59 UTC, uniqueiniquity approved these changes

2019-04-15 15:59 UTC, merged