[storybook__addon-knobs] Update for v5
DefinitelyTyped/DefinitelyTyped pull request #34691
Opened 2019-04-12 16:05 UTC by azmenak

Updating for changes made in v5

https://github.com/storybooks/storybook/tree/next/addons/knobs

2019-04-13 21:23 UTC, joscha reviewed
I think for v5 there should be types coming with the package, are they not?

2019-04-15 13:33 UTC, azmenak commented
> I think for v5 there should be types coming with the package, are they not?

@joscha I don't think so, using `@storybook/addon-knobs@5.0.8`

I'm seeing this in VSCode

<img width="714" alt="Screen Shot 2019-04-15 at 9 25 52 AM" src="https://user-images.githubusercontent.com/859321/56136755-660b6500-5f61-11e9-947f-959825b4a81f.png">

Also checked the files installed in `node_modules`, no type definitions in there

2019-04-17 23:27 UTC, joscha requested changes
Intent LGTM, I think the values should follow the generic. The defaultValue would be an added bonus but I think it would require changes in storybook itself.

2019-04-17 23:27 UTC, joscha commented on types/storybook__addon-knobs/index.d.ts
> +        [key: string]: any;
```suggestion
        [key: string]: T;
```

2019-04-17 23:27 UTC, joscha commented on types/storybook__addon-knobs/index.d.ts
> +    defaultValue?: T,
any chance for us to make sure `defaultValue` is a value in `values`?

2019-04-18 03:10 UTC, joscha approved these changes

2019-04-18 23:06 UTC, merged