feat: update prettier with standalone files
DefinitelyTyped/DefinitelyTyped pull request #34726
Opened 2019-04-14 12:03 UTC by ifiokjr

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-04-14 13:16 UTC, ikatyang requested changes
Could you add tests to ensure it works?

2019-04-14 13:16 UTC, ikatyang commented on types/prettier/parser-angular.d.ts
> +export as namespace plugin;
It's actually exported as `prettierPlugin[pluginName]`, see https://prettier.io/docs/en/browser.html#global.

2019-04-14 13:16 UTC, ikatyang commented on types/prettier/parser-glimmer.d.ts
> +
We should not add this parser as it's not ready.

2019-04-14 13:16 UTC, ikatyang commented on types/prettier/standalone.d.ts
> +export { Plugin };
Since the `Plugin` type is already available in `index.d.ts`, we shouldn't need to re-export it.

2019-04-14 13:16 UTC, ikatyang commented on types/prettier/standalone.d.ts
> +
The `export as namespace prettier` is missing.

2019-04-14 13:16 UTC, ikatyang commented on types/prettier/standalone.d.ts
> +type MR<GType extends { parser?: any }> = MakeRequired<GType, 'parser'>;
The `parser` option is not required here, it's same as the one used in `index.d.ts`, which defaults to `babylon` (`babel`).

2019-04-15 13:20 UTC, ikatyang approved these changes

2019-04-15 13:28 UTC, ifiokjr commented
@ikatyang Thanks for reviewing so quickly.

2019-04-15 20:05 UTC, merged