Add type definitions for ssh2-sftp-client 2.5
DefinitelyTyped/DefinitelyTyped pull request #34739
Opened 2019-04-15 12:22 UTC by Infantys

2019-04-15 15:13 UTC, ascariandrea approved these changes

2019-04-16 13:38 UTC, viamuli reviewed
Looks pretty good but shouldn't the version bump to 3.x instead of 2.5 since the public API change in `put` (l:27)?

2019-04-16 13:48 UTC, Infantys commented
> Looks pretty good but shouldn't the version bump to 3.x instead of 2.5 since the public API change in `put` (l:27)?

The latest version is ssh2-sftp-client 2.5.0 from Mar 8 2019 (https://github.com/jyu213/ssh2-sftp-client/releases). Changes are made for this version.

2019-04-16 14:49 UTC, viamuli approved these changes

2019-04-16 20:43 UTC, armanio123 requested changes

2019-04-16 20:43 UTC, armanio123 commented on types/ssh2-sftp-client/ssh2-sftp-client-tests.ts
> +import * as Client from "ssh2-sftp-client";
Could you please rollback this line? Namespaces object are not callable. See [this](https://stackoverflow.com/questions/39415661/what-does-resolves-to-a-non-module-entity-and-cannot-be-imported-using-this) post for details.

2019-04-17 19:40 UTC, armanio123 approved these changes

2019-04-17 19:40 UTC, merged