[forge-viewer] Repair definitions in BubbleNode and Viewer3D
DefinitelyTyped/DefinitelyTyped pull request #34813
Opened 2019-04-17 19:58 UTC by ClaysonIO

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

The changes have not been made public via the documentation, but using them against the current iteration of the forge viewer has confirmed that these are accurate.

2019-04-23 21:59 UTC, PranavSenthilnathan requested changes

2019-04-23 21:59 UTC, PranavSenthilnathan commented on types/forge-viewer/index.d.ts
> +          isViewPreset(): boolean;
Is there any documentation for this (the package isn't on npm so I can't check the code). Same with `setView`? I was able to find `traverse` in the online docs.

2019-04-25 15:42 UTC, ClaysonIO commented
I've added links to the updated documentation.

2019-04-26 06:20 UTC, dukedhx commented
Thanks @PranavSenthilnathan for reviewing this and this is Bryan from Autodesk Forge Developer Network and we hereby approve these changes. Please proceed to merge. Thanks!

2019-04-30 22:26 UTC, closed without merging