[secure-password] Add definition
DefinitelyTyped/DefinitelyTyped pull request #34846
Opened 2019-04-19 06:44 UTC by jloveridge

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.

Attempting to run `dtslint secure-password` always resulted in:
`Duplicate identifier 'prototype'.`

I was unable to resolve it so resorted to an older style module definition format that seems to work just fine.

- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-04-19 19:57 UTC, jloveridge commented
The build failure appeared to be due to a timeout issue. Added some comments to the function definitions and pushed up again, this time it passed the build so I don't really think it was anything I could have avoided.

2019-04-20 00:02 UTC, armanio123 requested changes

2019-04-20 00:02 UTC, armanio123 commented on types/secure-password/secure-password-tests.ts
> +import * as SecurePassword from 'secure-password';
namespaces are not callable, instead use: 
```suggestion
import SecurePassword = require('secure-password')
```

2019-04-20 00:02 UTC, armanio123 commented on types/secure-password/tslint.json
> +        "adjacent-overload-signatures": false,
Please don't disable any rules unless there's a specific reason for it.

2019-04-22 20:11 UTC, merged