Add typings for node-insights
DefinitelyTyped/DefinitelyTyped pull request #34844
Opened 2019-04-19 05:18 UTC by wrumsby

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-04-19 16:58 UTC, jloveridge commented
Not sure if this will present a problem to anyone but the `node-insights` module does not actually have an export called `default` as is implied in these types. It, as many other npm modules, simply exports the function directly. How would these typings affect someone regardless of their use of the `esModuleInterop` setting in `tsconfig.json`?

2019-04-19 23:58 UTC, armanio123 requested changes
Check this [documentation](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require) for details about the default export.

2019-04-19 23:58 UTC, armanio123 commented on types/node-insights/index.d.ts
> +export default class Insights {
As @jloveridge has mentioend, the `default` should be removed if there's no default export.

2019-04-19 23:58 UTC, armanio123 commented on types/node-insights/node-insights-tests.ts
> +import Insights from 'node-insights';
Instead use `import x = require('module')` syntax. You can still use this style byt the `--allowSyntheticDefaultImports` or `--esModuleInterop` should be turned on instead.

2019-04-20 22:07 UTC, wrumsby commented
@armanio123 changes made as requested.

2019-04-22 20:07 UTC, armanio123 approved these changes

2019-04-22 20:07 UTC, merged