new package: kind-of
DefinitelyTyped/DefinitelyTyped pull request #34879
Opened 2019-04-20 09:59 UTC by claasahl

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-04-20 16:54 UTC, colbywhite commented
With 31.8M weekly downloads, `kind-of` certainly seems like a popular package. 

I'm curious however if it is relevant in _typescript_ projects. It seems like the package is all about doing type checks, which is what typescript does already. in a typescript project, what's the use case for needing a package like `kind-of`? Not saying this shouldn't be merged, but I'm just curious the use case for it.

2019-04-20 18:58 UTC, claasahl commented
Thanks for your comment, @colbywhite

I agree that `kind-of` is not likely to be useful in TS projects. Even more so, when one starts a TS-project from scratch. However, given the popularity of `kind-of`, it is likely to show up in existing code bases that will hopefully soon be transitioned to TS 😉 

Despite my guess that `kind-of` (incl. these types) is not likely to remain in TS-projects for long, my hope is that there are enough people / projects out there which can benefit from these types.

2019-04-23 01:05 UTC, PranavSenthilnathan requested changes

2019-04-23 18:29 UTC, claasahl commented on types/kind-of/index.d.ts
> +declare function kind_of(thing: any): "object" | string;
Thanks for the pointer, @PranavSenthilnathan 

`"object"` was originally intended as a hint (i.e. this thing that you are testing is _probably_ an "object"). `string` was meant to "catch" those cases where my overloads have diverged from the actual outputs from `kind-of` (e.g. due to incorrect mapping on my behalf or possible updates to the package `kind-of`). To make this intend clearer, I have split this line into two.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e39d217dde6e29507f7ab55710a08b445e68b54d/types/kind-of/index.d.ts#L48-L49

I am aware that it is not recommended to use `Object`. Given that `kind-of` will recognize `Object.prototype` as `"object"`, `Number.prototype` as `"number"`, `String.prototype` as `"string"` (see [RunKit + npm: kind-of](https://runkit.com/embed/8dccvqtplzqg)), how should one resolve this? Should one simply drop references to `Object` and such, even though they actually seem correct? Perhaps, I am not seeing something here.

2019-04-23 18:37 UTC, claasahl commented on types/kind-of/index.d.ts
> +declare function kind_of(thing: any): "object" | string;
... just pushed a work-around.

2019-05-01 22:59 UTC, PranavSenthilnathan approved these changes

2019-05-01 23:00 UTC, merged