Support function component for `forwardRef` in `react`
DefinitelyTyped/DefinitelyTyped pull request #34876
Opened 2019-04-20 05:33 UTC by hyochan

Support function component for `forwardRef`, `forwardRef` currently does not support function component.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-04-20 10:22 UTC, eps1lon requested changes
Could you add a test that failed previously and would be accepted with this change?

2019-04-21 04:12 UTC, hyochan commented
@eps1lon Hi! Thanks for the review. Could you please guide my where the error is occuring in `travis`? I just can't see where the error is.

2019-04-21 05:29 UTC, hyochan commented
@eps1lon What I can see is `The job exceeded the maximum time limit for jobs, and has been terminated.`.

2019-04-21 08:55 UTC, eps1lon commented
Timeout is normal. Could you please address my review?

2019-04-21 10:46 UTC, hyochan commented
@eps1lon Oh. Sorry, I miss understood your request. I thought you were talking about the `ci build`. Also, I just tried myself to generate problem again but I couldn't. I think there was something wrong in my local env. Sorry for that and I will close this for now.

2019-04-21 10:46 UTC, closed without merging