fix(treeify): types
DefinitelyTyped/DefinitelyTyped pull request #34907
Opened 2019-04-22 13:30 UTC by yxliang01

- Fixed previously only `object` can be supplied as argument for printing
- Made `TreeObject` attributes `readonly`
- Fixed `asTree` `hideFunctions` argument that it should be optional

2019-04-22 13:41 UTC, yxliang01 commented
Hmm how do I locate where the error is? The CI logs don't really point that out.

2019-04-23 06:50 UTC, mike-north requested changes
Thanks for your contribution @yxliang!

Could you fill out the pull request template for this change? I need some of that information in order to review.
- Links to where I can find public API documentation to support each substantive change you're proposing (function arg renaming isn't something I'm too worried about)
- Whether or not you've tested this in a real app or not

2019-04-23 06:56 UTC, mike-north commented
> Hmm how do I locate where the error is? The CI logs don't really point that out.

[The error](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/523034980#L471) relates to the DT header parser having trouble with the changes you've made to the header comments at the top, since they [only expect to find a major and minor package version](https://github.com/Microsoft/definitelytyped-header-parser/blob/f5c301b88d72b93eadd0d2a46e52985eac5d94ec/index.ts#L75-L76)

2019-04-23 12:51 UTC, yxliang01 commented
Will modify the issue soon.

2019-04-24 20:49 UTC, mike-north requested changes
Not all review feedback has been acted on yet

2019-04-25 18:47 UTC, yxliang01 commented
@mike-north Modified PR description as per your comment https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34907#pullrequestreview-229373213 .

2019-04-25 19:48 UTC, mike-north commented
> Note: the documentation didn't specify that the hideFunctions argument for method asTree is optional, it is however optional. 

> The documentation doesn't also explicitly state that it supports Array object, it instead just use placeholder obj which can be an Array.

@yxliang01 How do we know whether these things just happen to work for now, or whether they're part of the public API that the maintainers intend to support?

Are there tests that assert these cases work properly now, and will continue to work with future changes?

2019-04-28 21:03 UTC, yxliang01 commented
@mike-north Nope. No test supporting the type changes in this PR. We know it works for now by trying. No way to guarantee it will be working in the future versions as the inability to predict the future nor controlling `treeify`'s future. As suggested above, the documentation didn't mention what the object to be passed to be like, that includes it doesn't mention passing an array is supported. 

Things to note though:
1. In one example provided in documentation, `treeify.asTree` is called without supplying the `hideFunctions` value.
2. The type file header specifies the targeted version. Why do we need to assure about the future versions?

2019-05-01 06:19 UTC, yxliang01 commented
I am currently awaiting for @mike-north 's response.

2019-05-01 21:27 UTC, closed without merging

2019-05-02 16:05 UTC, mike-north commented
> Nope. No test supporting the type changes in this PR. We know it works for now by trying. No way to guarantee it will be working in the future versions as the inability to predict the future nor controlling treeify's future. As suggested above, the documentation didn't mention what the object to be passed to be like, that includes it doesn't mention passing an array is supported.

These are all indications that these changes are not necessarily in alignment with the project's public API

> In one example provided in documentation, treeify.asTree is called without supplying the hideFunctions value.

However, the documentation at the bottom doesn't suggest that `hideFunctions` is optional. We have conflicting signals here and need to straighten that out before we can be confident about the library's public API

> The type file header specifies the targeted version. Why do we need to assure about the future versions?.

Without knowing whether something is part of the public API, we don't know whether breaking/removing it would be accompanied by a [major version bump](https://docs.npmjs.com/about-semantic-versioning)

> What is the difference between an object between an Array? At the end of the day, an Array is an object? In that sense, a parameter of type object should accept any JS value that is not undefined nor null? (correct me if wrong)

I think you're referring to your use of `ReadonlyArray<any>` here?

The goal of these `@types/*` packages is to represent the public API of each library as accurately as possible. This does not mean that we should type according to what _happens to work_, but instead _what the authors/maintainers intend to officially support_. I don't see a readonly `any[]` as being a good representation of the public API of this library, as it allows for consumers to assume things that simply aren't going to happen (i.e., an array of `null`, an array of `true`s, etc...)