Types definitions to simplecrawler module
DefinitelyTyped/DefinitelyTyped pull request #34997
Opened 2019-04-25 18:00 UTC by MutterPedro

- [ X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X ] Test the change in your own code. (Compile and run.)
- [ X ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ X ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [ X ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ X ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ X ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ X ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-04-25 19:11 UTC, MutterPedro commented
I think the error is not on my side... I ran `npm run test` on my local machine, and it works perfectly with node v10.15.3, Travis is using node v8.16.

The error was this:
```

/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/types-publisher/bin/util/util.js:484
                    catch {
                          ^
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at Module.patchedRequire [as require] (/home/travis/build/DefinitelyTyped/DefinitelyTyped/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
    at require (internal/module.js:11:18)
```

It looks like is because of the catch with omitted error ([supported since TypeScript 2.5](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#The_exception_identifier))

2019-04-25 22:37 UTC, PranavSenthilnathan requested changes

2019-04-25 22:37 UTC, PranavSenthilnathan commented on types/simplecrawler/index.d.ts
> +export default Crawler;
It seems like the [underlying library](https://www.npmjs.com/package/simplecrawler#getting-started) is not using `export default`, so this .d.ts file should not either. Instead, you should follow the appropriate template from [the TypeScript handbook](http://www.typescriptlang.org/docs/handbook/declaration-files/templates.html). Note that if you want to use `import name from 'package';` in your consuming code, you can use the `esModuleInterop` compiler setting.

2019-04-30 18:27 UTC, MutterPedro commented
@PranavSenthilnathan could you review the PR again? I already committed some changes. :)

2019-05-02 00:25 UTC, PranavSenthilnathan approved these changes

2019-05-02 00:25 UTC, merged