[@types/got] Support retries of "POST" method
DefinitelyTyped/DefinitelyTyped pull request #35000
Opened 2019-04-25 19:56 UTC by ryanwilsonperkin

The current list of supported methods for RetryOptions omits the "POST" method. I believe this is because the list was taken from https://www.npmjs.com/package/got#retry however this is only the _default_ methods that are supported. [This issue](https://github.com/sindresorhus/got/issues/757) from the `got` GitHub repo indicates that it _is_ possible to specifically state that you would like to retry on POST as well.

I have a use-case where I'd like to automatically retry failed POSTs but can't right now without overriding the typing.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-04-25 21:02 UTC, ikokostya requested changes

2019-04-25 21:25 UTC, ryanwilsonperkin commented on types/got/index.d.ts
> +        methods?: Array<'GET' | 'POST' | 'PUT' | 'POST' | 'HEAD' | 'DELETE' | 'OPTIONS' | 'TRACE'>;
🤦‍♂️ Thanks!
Bad mistake while handling a merge conflict

2019-04-25 21:26 UTC, ryanwilsonperkin commented
@ikokostya fixed the issue you called out, ready for re-review

2019-04-25 23:51 UTC, ikokostya approved these changes

2019-04-26 02:14 UTC, merged

2019-04-26 02:14 UTC, PranavSenthilnathan commented
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!