[google.visualization] Added type support for Controls and Dashboards
DefinitelyTyped/DefinitelyTyped pull request #35109
Opened 2019-04-30 14:04 UTC by grizzlysol

https://developers.google.com/chart/interactive/docs/gallery/controls

Currently @types/google.visualization doesn't support the Controls and Dashboards feature of the google.visualization framework. I have added the class and interface definitions provided by the google documentation (the link provided above).

2019-05-01 17:24 UTC, shrujalshah28 requested changes

2019-05-01 17:24 UTC, shrujalshah28 commented on types/google.visualization/index.d.ts
> +            bind(controls: any, charts: ChartWrapper): google.visualization.Dashboard;
As per the [doc](https://developers.google.com/chart/interactive/docs/gallery/controls#dashboard)

> controls - Either a single one or an array of google.visualization.ControlWrapper instances defining the controls to bind

> charts - Either a single one or an array of google.visualization.ChartWrapper instances defining the charts the that will be driven the by the controls

both controls and charts are either single or array of type google.visualization.ControlWrapper

2019-05-01 17:35 UTC, shrujalshah28 requested changes

2019-05-01 17:35 UTC, shrujalshah28 commented on types/google.visualization/index.d.ts
> +            controlType?: string;
As per [doc](https://developers.google.com/chart/interactive/docs/gallery/controls#controlwrapperobject), this field is required.
```suggestion
            controlType: string;
```

2019-05-01 17:35 UTC, shrujalshah28 commented on types/google.visualization/index.d.ts
> +            containerId?: string;
As per [https://developers.google.com/chart/interactive/docs/gallery/controls#controlwrapperobject](doc), this field is also required.
```suggestion
            containerId: string;
```

2019-05-07 17:00 UTC, grizzlysol commented
@shrujalshah28 Thanks for the help. Been having a hard time juggling this with my work.

2019-05-07 17:52 UTC, shrujalshah28 approved these changes
LGTM

2019-05-07 18:37 UTC, merged