Update index.d.ts
DefinitelyTyped/DefinitelyTyped pull request #35650
Opened 2019-05-22 10:18 UTC by Kamill90

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-05-22 10:47 UTC, vintage requested changes

2019-05-22 10:47 UTC, vintage commented on types/react-native-video/index.d.ts
> +export interface onSeekData {
Should be `OnSeekData`

2019-05-22 10:51 UTC, vintage approved these changes
Thanks, LGTM

2019-05-23 09:26 UTC, PikachuEXE commented
You might want to add link to doc about this update
https://github.com/react-native-community/react-native-video#onseek
Also `target` seems to be from
https://github.com/react-native-community/react-native-video/blob/c36a9cf2efdb920b86ca453e1be89398df3dae16/ios/Video/RCTVideo.m

2019-05-28 19:53 UTC, merged