[stripe-v3] Update Stripe interface for new APIs
DefinitelyTyped/DefinitelyTyped pull request #35807
Opened 2019-05-29 08:54 UTC by vgaudard

* Add methods for new APIs:
    - PaymentMethod
    - Checkout
    - PaymentIntent

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

(changing an existing definition)
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [stripe-js reference](https://stripe.com/docs/stripe-js/reference),
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-05-30 00:28 UTC, arjunkomath commented
👍

2019-05-30 00:55 UTC, znagatomo commented
👍

2019-05-30 07:57 UTC, marlosin requested changes
it'd be great some basic tests :+1:

2019-05-30 07:57 UTC, marlosin commented on types/stripe-v3/index.d.ts
> +        createPaymentMethod(type: 'card' | 'card_present', element: elements.Element, data?: StripePaymentMethod): Promise<StripePaymentMethodResponse>;
you can use the type `paymentMethodType` for `card` parameter

2019-06-03 08:37 UTC, vgaudard commented
Currently, tests in `types/stripe-v3` seem to use stripe-v2 (See [this](https://github.com/vgaudard/DefinitelyTyped/blob/d0d41ad9519a856f5792694eb8fd204f843869fd/types/stripe-v3/stripe-v3-tests.ts#L1)). Is there a reason for that or is that an oversight?

2019-06-04 08:52 UTC, marlosin commented
> Currently, tests in `types/stripe-v3` seem to use stripe-v2 (See [this](https://github.com/vgaudard/DefinitelyTyped/blob/d0d41ad9519a856f5792694eb8fd204f843869fd/types/stripe-v3/stripe-v3-tests.ts#L1)). Is there a reason for that or is that an oversight?

TBH I don't know why it's like that, I'd guess who created v3 copied those tests.

2019-06-04 08:52 UTC, marlosin approved these changes
LGTM

2019-06-04 20:11 UTC, merged