@types/graphql - provide type definitions for mergeAST utility
DefinitelyTyped/DefinitelyTyped pull request #35942
Opened 2019-06-04 05:42 UTC by acao

For a simple new utility we are introducing: https://github.com/graphql/graphql-js/pull/1948

Needed because we are converting GraphiQL to typescript, and moving this utility from GraphiQL to graphql-js.

2019-06-04 11:56 UTC, JCMais approved these changes

2019-06-04 12:04 UTC, langpavel requested changes
Not merged yet and not released. Wait for https://github.com/graphql/graphql-js/pull/1948

2019-06-04 16:13 UTC, acao commented
@langpavel indeed, i mentioned that in the PR description, but I think I'll just close it for now anyways

2019-06-04 16:14 UTC, closed without merging

2019-06-04 21:55 UTC, langpavel commented
Well, @acao, I hope you understand. Unfortunately DefinitelyTyped is managed by bot at some point, so I must reject this PR or suggest changes.
It may be unfortunate especially for small libraries because bot will accept changes if someone approve them, there is only trust.
I must admit that I'm interested in feature — so I looked at; heh :smiley: there are so many variants of this. At least 5 packages have similar utility function, but each behave differently....

2019-06-05 22:19 UTC, acao commented
@langpavel of course, please do what you need. feel free to reject it. 

yeah it's no small effort! this originally began as an effort to move the utility from graphiql to graphql-js, but it turns out theres a lot of thought that would go into it. currently this utility is used in graphiql for a "merge queries" button that we now realize is quite precarious, and could lead to losing significant parts of your query in complex situations. back to the drawing board, I'll need to approach this in a very careful manner when re-opening it so i dont waste your and Ivan's time again, haha