update react-instantsearch-dom & core
DefinitelyTyped/DefinitelyTyped pull request #35940
Opened 2019-06-04 04:22 UTC by foray1010

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

1. `appId` and `appKey` no longer recommended way to init the `InstantSearch` (see https://www.algolia.com/doc/api-reference/widgets/instantsearch/react/), it suggests we use `searchClient` now

2. `InfiniteHits` does not have `refine` but `refineNext` and `refinePrevious` (see https://www.algolia.com/doc/api-reference/widgets/infinite-hits/react/?language=react#full-example)

2019-06-04 17:10 UTC, gburgett commented
Thanks @foray1010 !

Regarding `<InstantSearch />`, is it still possible to use `apiKey` and `appId`?  If so I'd prefer we not remove them from the type definitions.  Better just to add the new parameter.

2019-06-05 02:02 UTC, foray1010 commented
hi @gburgett ! I have read the source code and seems it is no longer possible to use `apiKey` and `appId`
https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/components/InstantSearch.js#L176-L204

2019-06-05 13:26 UTC, gburgett commented
Aha, I figured out the issue!  That component which you've linked is actually not the one exported by `react-instantsearch-dom`.  If you do the following:

```ts
import { InstantSearch } from 'react-instantsearch-dom'
```
then you actually get this object: https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-dom/src/widgets/InstantSearch.js  
which is created by this connector: https://github.com/algolia/react-instantsearch/blob/master/packages/react-instantsearch-core/src/core/createInstantSearch.js  
which wraps that InstantSearch component you have linked above.  The actual prop types therefore ought to be:

```js
static propTypes = {
      algoliaClient: PropTypes.object,
      searchClient: PropTypes.object,
      appId: PropTypes.string,
      apiKey: PropTypes.string,
      children: PropTypes.oneOfType([
        PropTypes.arrayOf(PropTypes.node),
        PropTypes.node,
      ]),
      indexName: PropTypes.string.isRequired,
      createURL: PropTypes.func,
      searchState: PropTypes.object,
      refresh: PropTypes.bool.isRequired,
      onSearchStateChange: PropTypes.func,
      onSearchParameters: PropTypes.func,
      resultsState: PropTypes.oneOfType([PropTypes.object, PropTypes.array]),
      root: PropTypes.shape({
        Root: PropTypes.oneOfType([
          PropTypes.string,
          PropTypes.func,
          PropTypes.object,
        ]).isRequired,
        props: PropTypes.object,
      }),
};
```

2019-06-05 13:26 UTC, gburgett commented
@Haroenv can you confirm?

2019-06-05 13:28 UTC, gburgett requested changes
I have to explicitly leave a comment with "request changes" - please revert your changes to the InstantSearchProps, or improve them according to the propTypes linked above.

2019-06-05 13:38 UTC, samouss requested changes

2019-06-05 13:38 UTC, samouss commented on types/react-instantsearch-dom/index.d.ts
> -  appId: string;
Those values aren't documented anymore but it's still possible to provide them. Note that they will be removed with the next major version of React InstantSearch. Until the release it's probably better to keep them.

2019-06-05 13:38 UTC, samouss commented on types/react-instantsearch-dom/index.d.ts
> -  algoliaClient?: any;
This one can be removed though. The `searchClient` is the prefer alternative.

2019-06-05 14:18 UTC, samouss approved these changes

2019-06-05 14:18 UTC, samouss commented on types/react-instantsearch-dom/react-instantsearch-dom-tests.tsx
> -      apiKey="3d9875e51fbd20c7754e65422f7ce5e1"
We should keep at least one test that use this notation to check that it's actually working.

2019-06-05 14:27 UTC, foray1010 commented
thank you very much @gburgett and @samouss ! I have marked `searchClient`, `apiKey` and `appId` as optional field

2019-06-05 19:42 UTC, gburgett approved these changes

2019-06-05 21:35 UTC, merged