Prevent `@types/node` and `@types/requirejs`-confusion
DefinitelyTyped/DefinitelyTyped pull request #35946
Opened 2019-06-04 12:59 UTC by manuth

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  I created this PR as many people are having trouble with `requirejs` overriding the variable `require`:
    - #31628
    - #15851
    - <https://github.com/rollup/rollup/issues/2142>
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

## About this PR
According to the documentation, `@types/requirejs` can be invoked through `require()` and `requirejs()`.  
As `require()` is declared by `@types/node`, too, which is part of most projects.

For that reason I decided to make `@types/requirejs` exporting `requirejs()` rather than `require()`.

2019-07-01 19:48 UTC, RyanCavanaugh commented
This seems extremely dangerous in terms of breaking existing code and JS users. I would need to see data in terms of what % of extant code uses `require` vs `requirejs` to be OK publishing this.

2019-07-01 20:03 UTC, manuth commented
Oh - I thought this should not damage any code as I increased the major version-number.

2019-07-02 04:47 UTC, manuth commented
@RyanCavanaugh is this a wrong assumption?
Is there anything else I need to do in order to increase the major version-number but changing the file-header of `index.d.ts`?

2019-07-07 23:56 UTC, manuth commented
So I just checked the guide of `DefinitelyTyped` and it says that there is nothing to do but increasing the version-number in the first line of the `index.d.ts`-file:
https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library

I updated the major version which means that no package will be affected.
Is there anything more I have to do?

2019-07-15 07:59 UTC, Eagle94T commented
@RyanCavanaugh what's the status for this PR?
With updating the major version, this shouldn't affect any existing projects.

2019-07-17 05:42 UTC, Eagle94T commented
I'm sorry to ask again, but why is this PR still not merged?
I need this change, since I'm using aurelia-bundler (uses @types/node) and @types/select2 (uses @types/requirejs)

2019-07-17 22:24 UTC, andrewbranch commented
> Oh - I thought this should not damage any code as I increased the major version-number.
>
> ...is this a wrong assumption?

Yes—the version number is supposed to represent the version of the _JavaScript library on npm_. The latest release of RequireJS is 2.3.6. In fact, @sandersn _just_ added a CI rule to prevent type definitions from referencing non-existent versions of their JS counterparts.

Echoing Ryan, I think we would want to see some data here. I think my _hunch_ is that lots of RequireJS users probably use `require()` (and want to keep it that way), in which case this change is probably a non-starter, although well-intentioned. If you can prove me wrong, then we can proceed. 👍

2019-07-17 22:36 UTC, andrewbranch requested changes
It appears that @typescript-bot might have interpreted my trailing “👍” in that last comment as an approval? I’m requesting changes just so it’s clear the status is not mergeable without further research/discussion.

2019-07-18 09:22 UTC, manuth commented
Honestly I don't think "people may want to keep using `require()`" is a pretty bad argument.
By now you cannot write typescript-modules which have both `@types/requirejs` and `@types/node` in their dependency-tree which often might be the case as some types in DefinitelyTyped use either parts of `@types/requirejs` or `@types/node`.

To me its a bad idea to prevent people from writing typescript-code just because  "people want to use `require()`.

2019-07-18 17:30 UTC, sandersn commented
Here's a workaround: provide a node-specific version of the package which basically implements this change, but copy it into a subdirectory named `node`. Then people who have the conflict can add the following path mapping to their tsconfig:

```
        "baseUrl": ".",
        "paths": {
            "requirejs": ["node_modules/@types/requirejs/node/index.d.ts"]
        }
```

It should be possible to share the types between the main file and the node file, so that they only differ in the last few lines -- the main file would have 3 globals and the node file would have a single `export =`.

2019-07-18 18:20 UTC, andrewbranch commented
@sandersn I tried this locally, but `node_modules/@types/requirejs/index.d.ts` (with its ambient declarations) still get pulled into the program. I think you’d have to combine this approach with specifying `typeRoots` or `types` in your tsconfig, which could be pretty frustrating if you have tons of @types packages and you just need to _prevent_ one file in them from being included. (Related: https://github.com/microsoft/TypeScript/issues/18588)

2019-07-24 23:30 UTC, closed without merging

2019-07-25 06:40 UTC, manuth commented
@RyanCavanaugh. @andrewbranch I'd be glad if you guys could discuss this further so I can open a new PR for resolving the `node`/`requirejs`-intersection.

2019-07-25 17:35 UTC, sandersn commented
@andrewbranch I was wrong about my fix, the errors you saw got lost in a bunch of others. I'm out of ideas on this one.

2019-07-25 17:40 UTC, manuth commented
Should I wait for you guys to work out a solution or should I rather open a new PR?

2019-07-25 17:52 UTC, andrewbranch commented
My only idea is to publish a separate package, e.g. @types/requirejs-node.