set-cookie-parser: add CookieMap to type defs
DefinitelyTyped/DefinitelyTyped pull request #36160
Opened 2019-06-13 00:00 UTC by hjr3

Provide a CookieMap type to make the parse result easier to use.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-06-13 00:06 UTC, hjr3 commented
The `set-cookie-parser` type definitions only expose `Cookie[]` as return type for the parser. Here is what currently has to be done to use `set-cookie-parser` with the `{map: true}` option:

```ts
// make my own version
interface CookieMap {
  [s: string]: Cookie;
}

// do some type casting
const cookies = (SetCookieParser(response.header['set-cookie'], {
  decodeValues: true,
  map: true,
}) as unknown) as CookieMap;

// now i can use cookie.foo
```

Instead, I want to upstream `CookieMap` so the code can be simplified to:

```ts
// no custom type needed
// more straight-forward type cast
const cookies = SetCookieParser(response.header['set-cookie'], {
  decodeValues: true,
  map: true,
}) as CookieMap;

// now i can use cookie.foo
```

I did not bother changing the parser return type to `Cookie[] | CookieMap` as that looks to break backwards compatibility with the current type definition.

2019-06-13 00:31 UTC, nickp10 approved these changes

2019-06-13 01:39 UTC, iztsv approved these changes

2019-06-13 01:39 UTC, ilyaztsv commented on types/set-cookie-parser/index.d.ts
> +          [s: string]: Cookie;
probably, using `name` instead of `s` as key name will be better for readability, because in case of `map: true` key is name of a cookie.

2019-06-14 03:04 UTC, iztsv approved these changes
LGTM

2019-06-16 06:21 UTC, rbuckton requested changes
I would suggest the following change:

```ts
function parse(input: string | ReadonlyArray<string> | http.IncomingMessage, 
  options: Options & { map: true }): CookieMap;
function parse(input: string | ReadonlyArray<string> | http.IncomingMessage, 
  options?: Options & { map?: false }): Cookie[];
function parse(input: string | ReadonlyArray<string> | http.IncomingMessage, 
  options?: Options): Cookie[] | CookieMap;
```

This way the correct type will be picked up automatically.

2019-06-16 17:41 UTC, hjr3 commented
> I would suggest the following change:
> 
> ```ts
> function parse(input: string | ReadonlyArray<string> | http.IncomingMessage, 
>   options: Options & { map: true }): CookieMap;
> function parse(input: string | ReadonlyArray<string> | http.IncomingMessage, 
>   options?: Options & { map?: false }): Cookie[];
> function parse(input: string | ReadonlyArray<string> | http.IncomingMessage, 
>   options?: Options): Cookie[] | CookieMap;
> ```
> 
> This way the correct type will be picked up automatically.

Thanks! I was thinking of how to do this and it is obvious in retrospect.

2019-06-17 02:52 UTC, rbuckton approved these changes

2019-06-17 02:52 UTC, merged