add notifyme-template typings
DefinitelyTyped/DefinitelyTyped pull request #36170
Opened 2019-06-13 12:18 UTC by ziv

Please fill in this template.

- [v] Use a meaningful title for the pull request. Include the name of the package modified.
- [v] Test the change in your own code. (Compile and run.)
- [v] Add or edit tests to reflect the change. (Run with `npm test`.)
- [v] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [v] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [v] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [v] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [v] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project. **created from module written in Babel using it's Flow output**
- [v] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-06-17 20:53 UTC, DanielRosenwasser commented
Just as a heads up, your commits don't seem to be associated with your GitHub account. While this isn't technically a problem, you might care if you want more appropriate attribution. You can either make sure your GitHub account is associated with the email address you're using for your commits, or rebase and amend your commits to fix the author name and email.

If you don't care about any of this stuff, I can always just pull in the changes.

2019-06-28 17:51 UTC, uniqueiniquity requested changes

2019-06-28 17:51 UTC, uniqueiniquity commented on types/notifme-template/index.d.ts
> +export default function RenderFactory(renderer: RendererType, folder: string, options?: OptionsType): RendererFunction;
It seems like the [underlying library](https://github.com/notifme/notifme-template/blob/master/index.js) is not using `export default`, so this .d.ts file should not either. Instead, you should follow the appropriate template from [the TypeScript handbook](http://www.typescriptlang.org/docs/handbook/declaration-files/templates.html). Note that if you want to use `import name from 'package';` in your consuming code, you can use the `esModuleInterop` compiler setting.

2019-07-03 08:51 UTC, ziv reviewed
seems right

2019-07-03 16:06 UTC, uniqueiniquity commented on types/notifme-template/index.d.ts
> +export default function RenderFactory(renderer: RendererType, folder: string, options?: OptionsType): RendererFunction;
I'm not sure why you marked this as resolved; is there something I'm missing about why this .d.ts should be using `export default`? Please let me know if there's any part I should explain more.

2019-07-05 18:27 UTC, closed without merging