fixing typing for CurrentRefinementsProvided in react-instantsearch-core
DefinitelyTyped/DefinitelyTyped pull request #36283
Opened 2019-06-19 09:56 UTC by e-krebs

This PR is fixing a small error in **react-instantsearch-core**.

The `CurrentRefinementsProvided` interface has a `refine` function, which argument should be of type `Refinement | Refinement[]` (instead of `RefinementValue | RefinementValue[]`).

If this `refine` function is called with a `RefinementValue[]` it throws an error.
Whereas it works as expected when calling it with a `Refinement[]`.

_relevant part of the doc:_
https://www.algolia.com/doc/api-reference/widgets/current-refinements/react/?language=react#full-example

2019-06-19 18:21 UTC, gburgett commented
Hi @e-krebs ,
The documentation seems to show that the proper thing to do is to pass `refinement.value` to the `refine` function:

![image](https://user-images.githubusercontent.com/430257/59790220-0d27b800-9295-11e9-9f6b-2090dfe72644.png)
https://www.algolia.com/doc/api-reference/widgets/current-refinements/react/?language=javascript#connector-param-provided-refine

Which version of react-instantsearch-core are you using?

2019-06-19 18:23 UTC, gburgett commented
FYI, my team is using v5.2.3 and we pass `item.value` to the `refine` call which works fine.
```tsx
    return <button key={item.label} className="btn btn-secondary" onClick={() => refine(item.value)}>
        {item.label}
        <i className="material-icons">clear</i>
      </button>
```
```
"@types/react-instantsearch-core@*":
  version "5.2.3"
  resolved "https://registry.yarnpkg.com/@types/react-instantsearch-core/-/react-instantsearch-core-5.2.3.tgz#9642d15cae7749bd91a0952e59a25ecd357846c7"
  integrity sha512-ujEGrMCrLuB4MOG8GJ/Gp0TxdJi2YaNiE8UC65+Cae0oGo+4B0sa42SAJnDO4VpRnh84OxfvrsZkgbUH9wXYlg==
  dependencies:
    "@types/react" "*"
```

2019-06-25 19:05 UTC, gburgett requested changes
I suspect this change is incorrect according to the docs and have not heard back from @e-krebs

2019-07-02 19:26 UTC, closed without merging

2019-07-02 19:28 UTC, e-krebs commented
sorry, I was on holidays.
no problem, I'll look into it and open a new PR if necessary