Apply typing based on `aws-lambda` handler type
DefinitelyTyped/DefinitelyTyped pull request #36489
Opened 2019-06-27 12:29 UTC by msuntharesan

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-07-02 16:44 UTC, RyanCavanaugh requested changes

2019-07-02 16:44 UTC, RyanCavanaugh commented on types/lambda-tester/index.d.ts
> +        expectSucceed<S extends HandlerResult<T> = HandlerResult<T>>(verifier: Verifier<S>): Promise<any>;
These should all just be e.g.
```ts
expectSucceed(verifier: Verifier<HandlerResult<T>>): Promise<any>;`
```

2019-07-03 12:55 UTC, msuntharesan commented on types/lambda-tester/index.d.ts
> +        expectSucceed<S extends HandlerResult<T> = HandlerResult<T>>(verifier: Verifier<S>): Promise<any>;
This has been resolved in last commit

2019-07-18 14:36 UTC, msuntharesan commented
Any update on this PR?

2019-07-25 12:28 UTC, msuntharesan commented
Been open for too long. closing this and opening a new one.

2019-07-25 12:28 UTC, closed without merging