[office-js-preview] Updating office-js-preview with beta CDN content
DefinitelyTyped/DefinitelyTyped pull request #36578
Opened 2019-07-01 18:06 UTC by AlexJerabek

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://appsforoffice.microsoft.com/lib/beta/hosted/office.d.ts
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT approved these changes
Approving with the understanding that if you opt to take any of these changes they may need to be pushed upstream.

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * Represents the information about the change detail. This property can be retrieved when the Changed event is triggered on single cell. If the Changed event is triggered on multiple cells,
```suggestion
         * Represents the information about the change detail. This property can be retrieved when the Changed event is triggered on a single cell. If the Changed event is triggered on multiple cells, this property cannot be retrieved.
```

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +     * Provides information about the worksheet format change event.
Seems like this should be something like:
```suggestion
     * Provides information about the worksheet row hidden change event.
```

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * Gets the change type that represents how the Changed event is triggered. See Excel.DataChangeType for details.
Seems like this should be:
```suggestion
         * Gets the change type that represents how the Changed event is triggered. See Excel.RowHiddenChangeType for details.
```

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * Represents the information about the change detail. This property can be retrieved when the Changed event is triggered on single cell. If the Changed event is triggered on multiple cells,
```suggestion
         * Represents the information about the change detail. This property can be retrieved when the Changed event is triggered on a single cell. If the Changed event is triggered on multiple cells, this property cannot be retrieved.
```

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +            Returns null if there are cells both which would be saved as an array formula and would not be
This seems incomplete.

Also, won't this all end up being on one line in the docs?

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * Gets the comment from the specific cell.
To me this should remain "specified"

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * Gets a comment related to its reply ID in the collection.
```suggestion
         * Gets a comment by its reply ID from the collection.
```

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * Unhidden represents the hidden state of row is Unhidden.
```suggestion
         * Unhidden represents the row is not hidden.
```

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * Hidden represents the hidden state of row is hidden.
```suggestion
         * Hidden represents the row is hidden.
```

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * WorksheetRowHiddenChanged represents the type of event registered on worksheet, and occurs when there is a row hidden changed.
```suggestion
         * WorksheetRowHiddenChanged represents the type of event registered on worksheet, and occurs when a row's hidden state is changed.
```

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +            Returns null if there are cells both which would be saved as an array formula and would not be
This seems incomplete.

Also, won't this all end up being on one line in the docs?

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +            Returns null if there are cells both which would be saved as an array formula and would not be
This seems incomplete.

Also, won't this all end up being on one line in the docs?

2019-07-01 20:47 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +            Returns null if there are cells both which would be saved as an array formula and would not be
This seems incomplete.

Also, won't this all end up being on one line in the docs?

2019-07-02 16:19 UTC, RyanCavanaugh commented
@AlexJerabek should I merge this or do you want to address the above comments first?

2019-07-02 16:42 UTC, AlexJerabek commented
@RyanCavanaugh Updated and ready to go. Thanks!

2019-07-02 17:00 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * Represents if ALL the cells would be saved as an array formula
If this all gets wrapped together, then I recommend a period at the end of this sentence.

```suggestion
         * Represents if ALL the cells would be saved as an array formula.
```

2019-07-02 17:00 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * Represents if ALL the cells would be saved as an array formula
ditto for later occurrences.

2019-07-02 17:01 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * Hidden represents the hidden state of row is hidden.
Copy-paste? Seems like this should be:
```suggestion
         * Hidden indicates the row is hidden.
```

2019-07-02 17:02 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +            Returns null if there are cells both which would be saved as an array formula and would not be
Sorry, but this statement is still not making sense to me...

2019-07-02 17:03 UTC, ElizabethSamuel-MSFT requested changes
Just a couple of things to clarify.

2019-07-02 17:03 UTC, AlexJerabek commented
Thanks @ElizabethSamuel-MSFT.  Updated!

2019-07-02 17:19 UTC, ElizabethSamuel-MSFT approved these changes

2019-07-03 15:41 UTC, merged