Add Type Definitions for sumologic
DefinitelyTyped/DefinitelyTyped pull request #36597
Opened 2019-07-02 15:38 UTC by banadiga

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-07-02 16:38 UTC, RyanCavanaugh requested changes

2019-07-02 16:38 UTC, RyanCavanaugh commented on types/sumologic/index.d.ts
> +declare namespace SumoLogger {}
Remove this

2019-07-02 16:38 UTC, RyanCavanaugh commented on types/sumologic/tslint.json
> +        "no-unnecessary-generics": false
This doesn't seem needed?

2019-07-22 20:01 UTC, banadiga commented
Hi @RyanCavanaugh Can you please look at this PR? Thanks!

2019-08-19 20:45 UTC, sheetalkamat requested changes

2019-08-19 20:45 UTC, sheetalkamat commented on types/sumologic/index.d.ts
> +    log(): void;
This seems incorrect definition.. as seems like it accepts string as per https://github.com/helix-collective/node-sumologic#usage

2019-08-26 21:31 UTC, closed without merging