Update types/node/v11
DefinitelyTyped/DefinitelyTyped pull request #36592
Opened 2019-07-02 11:29 UTC by lekoaf

* Fixes documentation for `concat`
* Adds `Buffer | Uint8Array` union to `concat`, `compare`, `equals` and `copy`

Solves #36253.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/buffer.html#buffer_class_method_buffer_concat_list_totallength
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-07-02 12:29 UTC, lekoaf commented
FYI, I couldn't run `npm test` because "logrocket" wasn't in the "whitelist".

2019-07-02 16:26 UTC, SimonSchick requested changes
Please update the node v12 typings as well, please keep in mind that v11 is not LTS and is unsupported at this point.

2019-07-02 16:52 UTC, lekoaf commented
Sure, I’ll take look at that tomorrow.

2019-07-03 19:23 UTC, Flarna commented on types/node/globals.d.ts
> +    equals(otherBuffer: Buffer | Uint8Array): boolean;
`Buffer | Uint8Array` should be not needed as `Buffer extends Uint8Array`.

2019-07-03 19:30 UTC, Flarna commented on types/node/globals.d.ts
> +    concat(list: Buffer[] | Uint8Array[], totalLength?: number): Buffer;
`concat` is a class method and not a instance method therefore its part of the constructor and should be removed here.

2019-07-03 19:35 UTC, Flarna requested changes
see other comments

2019-07-10 20:32 UTC, closed without merging