lodash: Consider rest operator for intersectionBy
DefinitelyTyped/DefinitelyTyped pull request #36610
Opened 2019-07-03 06:47 UTC by mtsmfm

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://codesandbox.io/s/hardcore-rain-mgxew?fontsize=14
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-07-03 13:30 UTC, aj-r requested changes
Looks good, I think the chain types need to be updated too.

2019-07-04 04:19 UTC, mtsmfm commented
@aj-r It seems `chain` already works well 🤔 

![image](https://user-images.githubusercontent.com/1796864/60639605-4566f300-9e5e-11e9-919c-e460b6b9c61a.png)

2019-07-04 17:07 UTC, aj-r commented
Interesting. Maybe this overload was included in chain version but overlooked in the regular version. Although I don't have a computer available right now so I can't verify that.

In that case, add some tests for the chains (or do the tests exist already too?)

2019-07-05 13:55 UTC, aj-r approved these changes

2019-07-08 16:59 UTC, merged