[react-native-sortable-list] added generic support and bump version
DefinitelyTyped/DefinitelyTyped pull request #36672
Opened 2019-07-05 15:09 UTC by renjfk

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/gitim/react-native-sortable-list
- [x] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-07-09 05:54 UTC, sivolobov requested changes
It's too difficult to review changes while you adding new features and fixing code style in one commit. Try to not do that again in next PRs.
Also you didn't change tslint config to meet your changes (there are plenty of rules that are unnecessary now). You should remove all manually set rules.
And if you started to fix code style it would be great to fix all CS issues at one time. I'll note lines that have wrong code style.

2019-07-09 06:04 UTC, sivolobov requested changes
By default all interfaces and types declared in this file will be exported automatically. To avoid it add `export { SortableList, RowProps };` at the end of file and `declare` to class declaration.

2019-07-13 13:47 UTC, renjfk commented
@sivolobov What's this waiting for? Can you please review?

2019-07-17 06:32 UTC, renjfk commented
@andrewbranch Can you please take a look?

2019-07-17 21:24 UTC, andrewbranch requested changes

2019-07-17 21:24 UTC, andrewbranch commented on types/react-native-sortable-list/index.d.ts
> +export { SortableList, RowProps };
This appears to be wrong, according to https://unpkg.com/react-native-sortable-list@0.0.23/index.js. `export default` was correct.

2019-07-17 21:24 UTC, andrewbranch commented on types/react-native-sortable-list/tslint.json
> +        "dt-header": false
If you fix the version number in the comment header to be just `0.0`, you can remove this rule too.

2019-07-17 21:25 UTC, andrewbranch commented on types/react-native-sortable-list/index.d.ts
> +export { SortableList, RowProps };
To @sivolobov’s point earlier, you can keep the `export { RowProps }` to avoid the implicit exports, but `SortableList` should be a default export.

2019-07-22 18:39 UTC, renjfk commented
@andrewbranch Can you please take another look?

2019-07-22 19:45 UTC, andrewbranch approved these changes

2019-08-07 07:49 UTC, renjfk commented
@andrewbranch Is it possible for you to merge these changes?

2019-08-07 15:35 UTC, andrewbranch commented
@renjfk sorry for the delay—I didn’t forget; we have a rotation for DefinitelyTyped and at the time that I approved, it was no longer my week, so I wanted to give the person who was in charge at the time the chance to make the decision. Since they didn’t come around to it, maybe they expected that I _would_ merge it. Likely a slight miscommunication, thanks for the ping!

2019-08-07 15:35 UTC, merged