[@types/node] Add missing parameters for process.emitWarning
DefinitelyTyped/DefinitelyTyped pull request #36844
Opened 2019-07-11 22:56 UTC by murgatroid99

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.) (90% of `process` already isn't tested. I'm not adding those tests just to fix a function signature)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/process.html#process_process_emitwarning_warning_options, https://nodejs.org/api/process.html#process_process_emitwarning_warning_type_code_ctor
- [ ] Increase the version number in the header if appropriate.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-07-11 23:52 UTC, SimonSchick requested changes
Test pls

2019-07-11 23:53 UTC, SimonSchick requested changes

2019-07-11 23:53 UTC, SimonSchick commented on types/node/globals.d.ts
> +        type?: String;
This should be `string` not `String`.

2019-07-12 01:14 UTC, murgatroid99 commented
Type fixed and some tests added

2019-07-12 02:19 UTC, KSXGitHub commented
From the docs:

> If warning is passed as an `Error` object, it will be passed through to the `'warning'` event handler unmodified (and the optional `type`, `code` and `ctor` arguments will be ignored)

I think you should remove `Error` from `string | Error` and add an overload for it:

```typescript
emitWarning(warning: Error): void;
```

2019-07-12 02:57 UTC, SimonSchick approved these changes

2019-07-12 03:46 UTC, murgatroid99 commented
I disagree with separating out the `Error` override like that. It is still valid in either case to pass the extra arguments if the first argument is an `Error`.

2019-07-19 01:28 UTC, closed without merging