Correct DivIconOptions html type union
DefinitelyTyped/DefinitelyTyped pull request #36841
Opened 2019-07-11 19:48 UTC by zmullett

- [ x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x ] Test the change in your own code. (Compile and run.)
- [ x ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://leafletjs.com/reference-1.5.0.html#divicon-html
- [ x ] Increase the version number in the header if appropriate.
- [ x ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-07-11 21:22 UTC, atd-schubert commented
It seems to me, that false is also a valid opinion. https://github.com/Leaflet/Leaflet/blob/master/src/layer/marker/DivIcon.js#L36

2019-07-11 21:24 UTC, atd-schubert requested changes
Add false as type

2019-07-12 17:57 UTC, zmullett commented
> Add false as type

Done!

2019-07-15 07:16 UTC, atd-schubert approved these changes

2019-07-15 17:01 UTC, merged