Update/fix typedefs for listr
DefinitelyTyped/DefinitelyTyped pull request #36924
Opened 2019-07-16 06:27 UTC by jgzuke

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/SamVerschueren/listr
- [x] Increase the version number in the header if appropriate.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-07-16 13:35 UTC, polRk requested changes

2019-07-16 13:35 UTC, polRk commented on types/listr/index.d.ts
> +    type ListrContext = any;
Do not use any

2019-07-16 13:35 UTC, polRk commented on types/listr/index.d.ts
> +    type ListrContext = any;
Maybe generic will be good solution

2019-07-16 13:35 UTC, polRk commented on types/listr/index.d.ts
> +    interface ListrError extends Error {
Add generic

2019-07-16 13:35 UTC, polRk commented on types/listr/index.d.ts
> +    interface ListrTaskObject extends Observable<ListrEvent> {
Add generic, for example:
ListrTaskObject<T = ListrContext > Observable<ListrEvent> {
task: (ctx: T, task: ListrTaskWrapper) => void | ListrTaskResult;

2019-07-16 17:04 UTC, jgzuke commented
@polRk added generic Context type

2019-07-19 07:29 UTC, polRk approved these changes
So well

2019-07-19 17:19 UTC, merged