min-app
DefinitelyTyped/DefinitelyTyped pull request #36998
Opened 2019-07-19 08:47 UTC by chobits4

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-07-19 16:32 UTC, andrewbranch requested changes
Can you explain what this is?

2019-07-20 00:57 UTC, chobits4 commented
> Can you explain what this is?

- it's declaration files for Weapp(weixin) mini program
- So far the best preserved declaration files of typescript for mini program

2019-07-20 01:08 UTC, chobitsX reviewed
@AndrewBranch @typescript-bot 
- it's declaration files for Weapp(weixin) mini program
- So far the best preserved declaration files of typescript for mini program

2019-07-20 01:54 UTC, chobits4 commented on types/min-app/index.d.ts
> +
- it's declaration files for Weapp(weixin) mini program
- So far the best preserved declaration files of typescript for mini program

2019-07-20 01:57 UTC, chobits4 commented
> Can you explain what this is?

2019-07-20 09:17 UTC, closed without merging