[stripe] Add expandable properties to checkout session
DefinitelyTyped/DefinitelyTyped pull request #37005
Opened 2019-07-19 15:12 UTC by harrygr

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Changing a definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://stripe.com/docs/api/checkout/sessions/object
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-07-24 17:23 UTC, vaskevich commented on types/stripe/stripe-tests.ts
> +    session && typeof session.payment_intent !== 'string' && session.payment_intent.id;
These tests are only checked for types, not actually invoked. You'll want to do something like this:

```ts
session.payment_intent; // $ExpectType PaymentIntent | string
```

2019-07-24 20:16 UTC, weswigham requested changes
Please address @vaskevich's comments, thanks

2019-07-25 17:25 UTC, vaskevich approved these changes

2019-07-25 18:34 UTC, weswigham approved these changes

2019-07-25 18:34 UTC, merged