[@types/slate] Update for version 0.47
DefinitelyTyped/DefinitelyTyped pull request #37076
Opened 2019-07-23 12:43 UTC by kaydelaney

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ianstormtaylor/slate/tree/67e397100e2f4cc6bcd4b8f98d7a85dcf30c72fd/packages/slate/src
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Making this as a draft PR since there are a lot of changes and I'd like to get some more opinions before making a proper PR.

2019-07-25 21:30 UTC, benjiro commented
@kaydelaney Thanks, I should have some spare time on the weekend to review it.

Cheers,
Ben

2019-07-26 07:39 UTC, kaydelaney commented
@benjiro  awesome, thanks!

2019-07-30 13:42 UTC, fuafa commented on types/slate/index.d.ts
> +    rules?: Array<({ match: ObjectAndType | ObjectAndType[] } & Rules)>;
Should this go to `SchemaProperties`?

2019-07-30 15:53 UTC, kaydelaney commented on types/slate/index.d.ts
> +    rules?: Array<({ match: ObjectAndType | ObjectAndType[] } & Rules)>;
Yes it should, nice catch, thanks!

2019-07-31 23:39 UTC, benjiro approved these changes
LGTM 
Thanks for all the work @kaydelaney, the changes look good to me.

2019-08-01 00:48 UTC, benjiro commented
Don't merge this yet, please.
@fuafa Once you've finished reviewing and ok with the changes, we will merge this in.

2019-08-01 01:28 UTC, benjiro requested changes
#88 RenderMark has now become  RenderAnnotation & RenderDecoration
https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/Changelog.md

```
The renderMark middleware is no longer used for decorations! Previously renderMark would be used for rendering both types of decorations. Now there are separate renderAnnotation and renderDecoration middleware functions to use instead.
```

2019-08-01 10:37 UTC, kaydelaney commented
> #88 RenderMark has now become RenderAnnotation & RenderDecoration
> https://github.com/ianstormtaylor/slate/blob/master/packages/slate-react/Changelog.md
> 
> ```
> The renderMark middleware is no longer used for decorations! Previously renderMark would be used for rendering both types of decorations. Now there are separate renderAnnotation and renderDecoration middleware functions to use instead.
> ```

@benjiro Just pushed a commit (hopefully) fixing this. Also added utility methods to the Editor class.

2019-08-02 07:36 UTC, benjiro approved these changes
Thanks for that change, looks good now. I'm right for this to be merged

2019-08-02 10:13 UTC, kaydelaney commented
@benjiro awesome!

2019-08-02 17:45 UTC, jessetrinity commented
Before I merge this, do you want to be updating the types version to 0.47 (currently at 0.22) to match the library?

2019-08-02 17:56 UTC, kaydelaney commented
The package `slate` is at version 0.47, but `slate-react` is at 0.22 as far as I know, and the versions in the respective `index.d.ts` files reflect that I think unless I'm missing something?

2019-08-02 17:58 UTC, jessetrinity commented
Nope, I was looking at the title that says @types/slate." The file indeed says slate-react.

2019-08-02 17:59 UTC, merged

2019-11-09 09:22 UTC, DinMon commented
Hey just wanna check the type SlateNode which is derived from Node does not match with function getEventTransfer(event) return type which is an object containting { files, fragment, html, node, rich, text }. Please could you check if the type SlateNode should be the returning data type of getEventTransfer?