Fix SectionList<T> generics (#37077), add new methods
DefinitelyTyped/DefinitelyTyped pull request #37178
Opened 2019-07-27 08:55 UTC by Skn0tt

See <https://github.com/DefinitelyTyped/DefinitelyTyped/issues/37077> for a bug report of this.
For the added instance methods, refer to <https://facebook.github.io/react-native/docs/sectionlist#recordinteraction>.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-07-30 11:44 UTC, alloy requested changes
This looks good, but could you add some test coverage?

2019-07-31 11:54 UTC, Skn0tt commented
Somehow I always forget about tests 😅
Added test coverage in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37178/commits/d65cba32b501329b110a707faf893d8fb49d5196.

2019-07-31 14:49 UTC, alloy approved these changes
Hah, that’s what we have reviews for! 😄 Thanks, this looks good, just [a test failure](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/565937601#L551) that should be easy to fix.

2019-07-31 15:43 UTC, Skn0tt commented
The failure concerns a piece of code that I did not touch in this PR. Is it possible that there was a recent change of the used TSC version?

2019-07-31 16:23 UTC, alloy commented
Could be, yeah, but unbeknownst to me

2019-08-07 12:29 UTC, closed without merging

2019-08-09 23:33 UTC, alloy commented
@Skn0tt Sorry for late follow-up, but while you didn’t trigger the test failure it is one that should be easily fixed. Could you amend and re-open?

2019-08-09 23:53 UTC, Skn0tt commented
Sure, I wanted to re-open this for a while but didn‘t come around to it yet. It‘s on my ToDo-List for the weekend.