[echarts] fix series-bar.itemStyle.color for linear gradient
DefinitelyTyped/DefinitelyTyped pull request #37193
Opened 2019-07-29 08:55 UTC by PlayByMyself

**documents just give a example for series-line,but series-bar works well.**

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://echarts.apache.org/en/option.html#series-line.itemStyle.color>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-07-29 09:39 UTC, bilalucar commented
The url you specify has the color feature of the line chart. The title says bar graph. It is also related to the line graph in the change. Is there a mistake?

2019-07-29 09:53 UTC, PlayByMyself commented
@bilalucar documents just give a example for series-line,but series-bar works well.

2019-07-30 08:35 UTC, Ovilia requested changes

2019-07-30 08:35 UTC, Ovilia commented on types/echarts/options/series/bar.d.ts
> +                };
If the linear gradient is supported, radial should also be supported.

2019-07-31 07:25 UTC, Ovilia approved these changes
Seems great!

2019-07-31 07:27 UTC, Ovilia commented
Although this PR is perfect by itself, gradient color is actually avaialble for all color options. This can serve as an improvement for later PRs.

2019-07-31 08:32 UTC, PlayByMyself commented
@Ovilia In fact, I want to make it looks like this:
`color?: string | zrender.LinearGradient | zrender.RadialGradient;`
but LinearGradient is a constructor,and no RadialGradient in [zrender](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2988e824bc1615621e805ee699b307d1ed76080b/types/zrender/index.d.ts).
what about improve zrender first,and then make it available for all color options?

2019-08-01 08:34 UTC, Ovilia commented
Sure.

2019-08-01 21:55 UTC, merged