[lscache] Update version to v.1.3.0
DefinitelyTyped/DefinitelyTyped pull request #37255
Opened 2019-07-31 01:50 UTC by c-py

Please fill in this template.

- [ X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X] Test the change in your own code. (Compile and run.)
- [ X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pamelafox/lscache/blob/master/lscache.js
- [ X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2019-08-05 18:33 UTC, sandersn requested changes
It looks like the dt-header and npm-naming lint rules are disabled in tslint.json. Since you're changing the header, can you please re-enable at least dt-header? Preferably both unless npm-naming fails -- but it shouldn't, because lscache 1.3.0 is on npm.

2019-08-05 18:33 UTC, sandersn commented on types/lscache/index.d.ts
> +// Type definitions for lscache v1.3.0
Definitely Typed doesn't retain patch versions, so you should just put `1.3` here.

2019-08-05 18:33 UTC, sandersn commented on types/lscache/index.d.ts
> +//               : c-py <https://github.com/c-py>
I don't think this is the accepted format for this field. Check something like react with lots of authors for an example.

2019-08-07 03:45 UTC, c-py commented
Thanks @sandersn ! I have updated the PR with the suggested changes.

2019-08-07 22:00 UTC, sandersn approved these changes

2019-08-07 22:00 UTC, merged