[react-redux] add ConnectedProps type
DefinitelyTyped/DefinitelyTyped pull request #37300
Opened 2019-08-01 18:36 UTC by 1000hz

This PR adds a `ConnectedProps` type to infer the props a connector will inject into your component. This lets you use the following pattern:
```tsx
type Props = {
  ownProp: string;
}

type ReduxProps = ConnectedProps<typeof connector>

const Component: React.FC<Props & ReduxProps> = ({ ownProp, injectedProp, dispatch }) => {
  return <div />
}

const connector = connect((state: any) => ({
  injectedProp: "hello"
}))

export default connect(Component)
```
Big shoutout to @robertcepa for coming up with this pattern at Cloudflare!

---
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-08-06 22:46 UTC, sandersn commented
I'm not comfortable changing such a widely-used package without some other type authors looking at the change. @tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @Kallikrein @val1984 @jrakotoharisoa @apapirovski @surgeboris @soerenbf @MrWolfZ do you mind taking a look? It's an addition so it should be easy to review if you know the existing types already.

2019-08-07 20:29 UTC, sandersn requested changes
Requesting changes so the bot will put it in the correct category.

2019-08-13 20:58 UTC, 1000hz commented
@typescript-bot pls no

@sandersn given no previous contributors have responded to this after a week, what's the next move?

2019-08-13 22:08 UTC, sandersn commented
Ping the authors again or try to contact them on some other medium.

@tkqubo @kenzierocks @clayne11 @tansongyang @NicholasBoll @mDibyo @Kallikrein @val1984 @jrakotoharisoa @apapirovski @surgeboris @soerenbf @MrWolfZ can you take a look at this?

2019-08-13 22:57 UTC, octylFractal approved these changes
This looks fine to me.

2019-08-13 23:23 UTC, sandersn approved these changes

2019-08-15 18:56 UTC, merged

2019-08-15 18:56 UTC, PranavSenthilnathan commented
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!

2019-10-27 23:02 UTC, markerikson commented
Awesome!  We'll have to add this to the actual docs somehow.  #31227 can be closed now.

2019-10-28 06:24 UTC, henrikra commented
What about when you pass `mapDispatchToProps`? Then the component *won't* receive `dispatch` ⚠️ Therefore the `ConnectedProps` won't tell correct types :/

2019-10-28 15:04 UTC, markerikson commented
@henrikra: as far as I know, the whole point of `ConnectedProps<T>` is that it infers _all_ props that `connect` is passing to your own component.  Granted, I haven't experimented with it further, but it definitely comes up with a combination of props from `mapState` and props from `mapDispatch`.

2019-10-28 16:34 UTC, henrikra commented
Yeah that is true 👍 But I am talking about `dispatch` function. Check the documentation of react-redux https://react-redux.js.org/using-react-redux/connect-mapdispatch#more-declarative It clearly says: `if you define your own mapDispatchToProps, the connected component will no longer receive dispatch`.

2019-10-28 16:46 UTC, markerikson commented
Yes, I'm very aware of both the behavior and the documentation, but I don't understand what your question is here.  Can you clarify?

2019-10-28 19:22 UTC, henrikra commented
Does `ConnectedProps` take this behavior into account? So if I pass `mapDispatchToProps` to connect is `ConnectProps` wise enough *not* to include `dispatch` in the props of my component?

2019-10-28 19:39 UTC, markerikson commented
Pretty sure, yes.  Try it out and see what happens :)

2019-10-28 20:54 UTC, 1000hz commented
yup, it does. See https://codesandbox.io/s/elated-dust-evg2d

![image](https://user-images.githubusercontent.com/1395018/67717123-1f300a80-f99b-11e9-9651-feff374c7384.png)

2019-10-29 05:58 UTC, henrikra commented
Thx @1000hz !

2019-11-23 22:45 UTC, markerikson commented
The `ConnectedProps<T>` pattern is now described in the React-Redux docs, and we're officially recommending that people use it:

https://react-redux.js.org/using-react-redux/static-typing#typing-the-connect-higher-order-component