[@types/react-stripe-elements] add TokenType to createToken
DefinitelyTyped/DefinitelyTyped pull request #37322
Opened 2019-08-02 11:25 UTC by mulholio

Solution for https://github.com/DefinitelyTyped/DefinitelyTyped/issues/37321. See this issue for more detailed information.

**TL;DR:** The [`react-stripe-elements` docs](https://github.com/stripe/react-stripe-elements#setting-up-your-payment-form-injectstripe) show that you can add a `type` option to `stripe.createToken`. This PR adds that option.

---

Authors: @sonnysangha @9Y5 @thchia @yhnavein @virzak @remotealex @santiagodoldan

2019-08-07 11:41 UTC, yhnavein reviewed
Can you verify why there are so many whitespace changes?

Have you changed line endings to the Windows one? In this repo Linux one should be used.

2019-08-07 12:14 UTC, yhnavein commented
Ah, I can see. You ran prettify on this file. Please revert that.

2019-08-07 13:41 UTC, mulholio commented
Slightly unsure about why the prettification needs to be reverted. I have cleanly separated this change into a separate commit and this seems to be the project-wide default.

Happy to make a separate PR for prettification if that's the issue

2019-08-07 20:33 UTC, sandersn requested changes

2019-08-07 20:33 UTC, sandersn commented on types/react-stripe-elements/index.d.ts
> +        createToken(options?: TokenOptions & { type?: TokenType }): Promise<PatchedTokenResponse>;
stylistically, I'd prefer to see react-stripe-elements' TokenOptions type change, like so:

```ts
type TokenOptions = stripe.TokenOptions & { type?: TokenType };
```

And then this line wouldn't have to change.

2019-08-07 20:34 UTC, sandersn commented
prettify runs on all changed lines right now. We eventually want all of DT prettified, so let's take the whitespace changes in this PR.

2019-08-14 10:36 UTC, mulholio commented
Remade in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37322

2019-08-14 10:36 UTC, closed without merging