[leaflet-draw] Upgrade leaflet-draw compatibility to latest version
DefinitelyTyped/DefinitelyTyped pull request #37372
Opened 2019-08-05 13:07 UTC by Favna

Changes made:

- Formatted the code with VSCode formatter
- Made some parts easier to read
- Included new properties where necessary
- Included the Localization namespace to cover all the localization
types used by leaflet-draw
- Use actual JSDoc tags to document the code (improving VSCode IntelliSense)
- Wherever the JSDoc would say "see code", they are now replaced
with the actual code that it is defaulted to
- Generally went through leaflet-draw's documentation and fixed what
could be fixed

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://leaflet.github.io/Leaflet.draw/docs/leaflet-draw-latest and https://github.com/Leaflet/Leaflet.draw#customizing-language-and-text-in-leafletdraw. Furthermore the localisation interfaces were (in agreement with the package dev) taken from https://github.com/DenisCarriere/Leaflet.draw.locales
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2019-08-14 00:16 UTC, PranavSenthilnathan requested changes
This file is using both tabs and spaces (the original code has tabs and the new code has spaces). Could you format this (I think VSCode has an command to do this).

2019-08-14 07:10 UTC, Favna commented
@PranavSenthilnathan Which file do you mean exactly? I changed from whatever it was to tabs, spaces, back to tabs and once again to spaces in each file in the leaflet-draw folder and the only file that shows up changed in my Git in tsconfig which is just the addition of a new line at the end of the file.

2019-08-14 07:36 UTC, Favna commented
Changes to spaces in 0ab6a07 @PranavSenthilnathan. VSCode does indeed have a command for that. 

Hopefully the tests pass because when I tried to run them locally it was nagging about some other unrelated to this PR package was not in notNeededPackages.json 😕 (full log of that: https://hasteb.in/enasulor.txt)

2019-08-16 00:17 UTC, PranavSenthilnathan approved these changes

2019-08-16 00:17 UTC, merged