update apple-mapkit-js types to 5.18
DefinitelyTyped/DefinitelyTyped pull request #37415
Opened 2019-08-06 21:13 UTC by chrisdrackett

also add docs/comments

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/wsmd/mapkit-typescript/
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-08-06 21:33 UTC, chrisdrackett commented
mapkit is not on NPM, so I'm not sure how to resolve the CI failure. Looks like CI is picking up a related but also unrelated project on NPM that is not apple's mapkit (only available via a URL)

https://developer.apple.com/documentation/mapkitjs/loading_the_latest_or_a_specific_version_of_mapkit_js

2019-08-06 22:15 UTC, chrisdrackett commented
ok, I was able to fix that issue, but now I'm getting `SyntaxError: Unexpected token } in JSON at position 82` when running the tests and I'm not sure what JSON it is even talking about :\

2019-08-19 20:31 UTC, sheetalkamat requested changes

2019-08-19 20:31 UTC, sheetalkamat commented on types/apple-mapkit-js/index.d.ts
> +// Type definitions for MapKit JS 5.18
change this to `// Type definitions for non-npm package MapKit JS 5.18`

2019-08-19 20:31 UTC, sheetalkamat commented on types/apple-mapkit-js/tslint.json
> +    "rules": {
Please remove the rules from here

2019-08-27 17:31 UTC, closed without merging