Additional types for webpack
DefinitelyTyped/DefinitelyTyped pull request #37434
Opened 2019-08-07 10:47 UTC by fa93hws

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-08-07 10:49 UTC, fa93hws commented
The test fails by itself..

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/10626756/62617250-d006aa80-b954-11e9-9542-7c62b578ab74.png">

2019-08-15 00:34 UTC, PranavSenthilnathan commented
Can one of the owners take a look: @tkqubo @bumbleblym @bcherny @tommytroylin @mohsen1 @jcreamer898 @alan-agius4 @elliottsj @jason0x43 @dennispg @christophehurpeau @ZSkycat @johnnyreilly @rwaskiewicz @kuehlein @grgur @rubenspgcavalcante

2019-08-15 22:44 UTC, PranavSenthilnathan requested changes

2019-08-15 22:44 UTC, PranavSenthilnathan commented on types/webpack/index.d.ts
> +            requireExtensions: Hook<string, Chunk, string>;
Should be a `SyncWaterfallHook`: https://github.com/webpack/webpack/blob/ba20513223607eaccb615c8ffabe824413b1613c/lib/MainTemplate.js#L96

2019-08-15 22:44 UTC, PranavSenthilnathan commented on types/webpack/index.d.ts
> +            jsonpScript?: Hook<string, Chunk, string>;
Should be a SyncWaterfallHook: https://github.com/webpack/webpack/blob/ba20513223607eaccb615c8ffabe824413b1613c/lib/web/JsonpMainTemplatePlugin.js#L39

2019-08-15 22:44 UTC, PranavSenthilnathan commented on types/webpack/index.d.ts
> +            id: string | number;
Argument should be an array of those types.

2019-08-15 22:44 UTC, PranavSenthilnathan commented on types/webpack/index.d.ts
> +            filterFn: (module: Module, num: number) => boolean,
`compilation.Module`? Otherwise it picks up the type from the global namespace (which `node` provides).

2019-08-15 22:44 UTC, PranavSenthilnathan commented on types/webpack/index.d.ts
> +  Hook,
Should be able to remove `Hook` once the other changes are in.

2019-08-18 17:53 UTC, johnnyreilly approved these changes

2019-08-19 17:48 UTC, PranavSenthilnathan approved these changes

2019-08-19 17:48 UTC, merged