mui-datatables v2.7.0: added custom filtertype and searchText
DefinitelyTyped/DefinitelyTyped pull request #37537
Opened 2019-08-11 07:25 UTC by skalma

Added value 'custom' to FilterType and searchText as string to MUIDataTableOptions

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.npmjs.com/package/mui-datatables
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-08-11 12:16 UTC, Favna commented
Please fix the TravisCI build. You need to fix the linting, either run `npm test` or `npm run lint mui-datatables` to view the errors.

2019-08-11 12:16 UTC, favna requested changes
Please fix the TravisCI build. You need to fix the linting, either run npm test or npm run lint mui-datatables to view the errors.

2019-08-11 14:41 UTC, skalma commented
Yes, i know, it is the trailing whitespace error i emailed you about:

Error: /home/travis/build/DefinitelyTyped/DefinitelyTyped/types/mui-datatables/index.d.ts:187:25
334ERROR: 187:25  no-trailing-whitespace  trailing whitespace

However i see no trailing whitespaces on the line i added. No idea how to solve this. Any help would be much appreciated

Kind regards,
Steye Kalma

Verzonden vanuit Mail voor Windows 10

Van: Jeroen Claassens
Verzonden: zondag 11 augustus 2019 14:17
Aan: DefinitelyTyped/DefinitelyTyped
CC: skalma; Mention
Onderwerp: Re: [DefinitelyTyped/DefinitelyTyped] mui-datatables v2.7.0: addedcustom filtertype and searchText (#37537)

@Favna requested changes on this pull request.
Please fix the TravisCI build. You need to fix the linting, either run npm test or npm run lint mui-datatables to view the errors.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-08-11 15:05 UTC, Favna commented
@skalma it's quite clear to me where it is, Line 187 colum 25. I can even see it on GitHub

![image](https://user-images.githubusercontent.com/4019718/62835555-22e4a880-bc5a-11e9-9220-70755f1a8e09.png)

2019-08-11 16:15 UTC, skalma commented
Thanks for your quick reply, however when i open the file in edit mode on github i cannot remove anything at the end of this line. If i press delete with the cursor just behind the semicolon the following line immediately comes to the same line as if there is no space. In fact, all the other lines have similar ‘spaces’ behind them:


I also tried copying the cotents to notepad++ and searching on spaces there: the only thing i can find is the space on the next line. Sorry for this but i really do not understand what is going on here
Verzonden vanuit Mail voor Windows 10

Van: Jeroen Claassens
Verzonden: zondag 11 augustus 2019 17:06
Aan: DefinitelyTyped/DefinitelyTyped
CC: skalma; Mention
Onderwerp: Re: [DefinitelyTyped/DefinitelyTyped] mui-datatables v2.7.0: addedcustom filtertype and searchText (#37537)

@skalma it's quite clear to me where it is, Line 187 colum 25. I can even see it on GitHub

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

2019-08-11 17:30 UTC, favna requested changes
One last change, please uncheck the box from `If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.` in your original post. You didn't increase the version number in the header and the typings do not cover the changes made in v2.4.0 of the lib and higher (at least).

2019-08-11 17:47 UTC, skalma commented
Done. And thx!

2019-08-11 18:08 UTC, favna approved these changes

2019-08-12 19:55 UTC, Favna commented
@PranavSenthilnathan why was this PR closed then reopened? And why is it on Done board when it has yet to be merged and released?

2019-08-12 20:57 UTC, merged

2019-08-12 20:57 UTC, PranavSenthilnathan commented
@Favna I was just trying to get the 'Revision Needed' tag removed by closing/reopening, but ended up doing it manually.

@skalma Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!