styled-system: Add overflowX and overflowY properties
DefinitelyTyped/DefinitelyTyped pull request #37573
Opened 2019-08-13 00:26 UTC by eliseumds

Add "overflowY" and "overflowX" that were introduced with https://github.com/styled-system/styled-system/commit/13d1a2f9f2d1830bfd418bfe1a9ac46d952cfc47
Docs: https://styled-system.com/api#layout

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

2019-08-13 09:54 UTC, peduarte approved these changes

2019-08-13 09:55 UTC, peduarte commented
LGTM 👌

2019-08-13 22:22 UTC, PranavSenthilnathan requested changes

2019-08-13 22:22 UTC, PranavSenthilnathan commented on types/styled-system/index.d.ts
> +//                 Eliseu Monar dos Santos <https://github.com/eliseumds>
Rev up the version to 5.1 at the top of the file.

2019-08-14 00:16 UTC, eliseumds commented
@PranavSenthilnathan done. Tks.

2019-08-15 23:09 UTC, PranavSenthilnathan approved these changes

2019-08-15 23:09 UTC, merged

2019-08-15 23:09 UTC, PranavSenthilnathan commented
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!