Patch 1
DefinitelyTyped/DefinitelyTyped pull request #37590
Opened 2019-08-13 11:45 UTC by id0Sch

add typings for the new native image lazy loading feature
Reference:
	https://www.chromestatus.com/feature/5645767347798016

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.chromestatus.com/feature/5645767347798016
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2019-08-13 13:21 UTC, eps1lon approved these changes

2019-08-13 13:33 UTC, ferdaber requested changes
@eps1lon feel free to re-approve if you disagree but I don't really think this should be merged. The `lazy` attribute isn't standard yet and it's not in the official spec. It's just a Chrome feature right now.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37466#issuecomment-519540060 also.

2019-08-13 13:38 UTC, id0Sch commented
> @eps1lon feel free to re-approve if you disagree but I don't really think this should be merged. The `lazy` attribute isn't standard yet and it's not in the official spec. It's just a Chrome feature right now.
> 
> See [#37466 (comment)](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37466#issuecomment-519540060) also.

oh I'm sorry, I couldn't find that issue before submitting this PR.

The audience for my product is Chrome only so we want to support lazy loading, having TS errors until this is a standard / overriding the default typings seems wrong. WDYT?
Thanks for your time!

2019-08-13 13:59 UTC, ferdaber commented
You can augment the React defs in your own codebase. If you create a `react.d.ts` (just has to end in `.d.ts`, filename can be anything) file where your `tsconfig.json` will pick it up, and add this in, it will augment the current type definitions:
```ts
// react.d.ts
import 'react'

declare module 'react' {
  interface ImgHTMLAttribute<T> extends HTMLAttributes<T> {
    loading?: "lazy" | "eager" | "auto" | "";
  }
}
```

2019-08-13 14:23 UTC, id0Sch commented
> You can augment the React defs in your own codebase. If you create a `react.d.ts` (just has to end in `.d.ts`, filename can be anything) file where your `tsconfig.json` will pick it up, and add this in, it will augment the current type definitions:
> 
> ```ts
> // react.d.ts
> import 'react'
> 
> declare module 'react' {
>   interface ImgHTMLAttribute<T> extends HTMLAttributes<T> {
>     loading?: "lazy" | "eager" | "auto" | "";
>   }
> }
> ```
@ferdaber, sounds like a good solution for now.
Thanks again :)

2019-08-13 17:46 UTC, eps1lon requested changes
@ferdaber You're right module augmentation is the better solution. 

There's probably an argument to be made to allow any excess attributes since react allows the same and the platform is always moving anyway. But I guess this would allow invalid values for existing attributes?

2019-08-14 16:43 UTC, ferdaber commented
Yah if we go with the route of type safety first, it's not a great idea. TS's JSX functionality already allows kebab-case freeform attributes (`data-*` or `aria-*`), so that usually covers the vast majority of other cases.

2019-08-20 14:30 UTC, closed without merging

2019-09-15 18:21 UTC, kachkaev commented
@ferdaber there is a small typo in your [code example](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37590#issuecomment-520846460), which I noticed after copy-pasting:

```diff
-   interface ImgHTMLAttribute<T> extends HTMLAttributes<T> {
+   interface ImgHTMLAttributes<T> extends HTMLAttributes<T> {
```

Thanks for sharing the the tip!

2019-09-15 18:26 UTC, ferdaber commented
Thanks, I fixed it

2020-02-14 21:35 UTC, kachkaev commented
This feature should be hopefully merged in #38390 given a recent attribute acceptance.

2020-02-18 21:18 UTC, kachkaev commented
Starting with `@types/react` 16.9.20, @ferdaber's [workaround](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37590#issuecomment-520846460) is no longer needed 🎉