feat: Add type definitions for npm module `ospec`
DefinitelyTyped/DefinitelyTyped pull request #37645
Opened 2019-08-15 12:10 UTC by maranomynet

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-08-16 07:06 UTC, dead-claudia requested changes
See the inline comments. Also, don't forget to test tests returning promises!

Note to DT maintainers: I'm the current maintainer of this library (it's part of the Mithril ecosystem and is used in core development).

2019-08-16 07:06 UTC, isiahmeadows commented on types/ospec/ospec-tests.ts
> +const exampleTtypeUse2: Definer = () => {}; // NOTE: this only works with  "esModuleInterop": true
```suggestion
const exampleTypeUse2: Definer = () => {}; // NOTE: this only works with  "esModuleInterop": true
```

2019-08-16 07:06 UTC, isiahmeadows commented on types/ospec/ospec-tests.ts
> +        /*
See above - my solution should allow you to uncomment this section.

2019-08-16 08:28 UTC, maranomynet commented on types/ospec/index.d.ts
> +declare namespace Ospec {
OK, I'll change that, but AFAIU this definition file doesn't export any global definitions ... or does it? ...or maybe it should?

(I find TypeScript's documentation quite confusing at times.)

2019-08-16 08:34 UTC, maranomynet commented on types/ospec/index.d.ts
> +    interface Spy<Args extends any[] = any[], Returns = undefined> {
Good suggestion, and brings it closer to @spacejack 's original notation. This was me trying too hard to simplify things, but inappropriately.

2019-08-16 08:45 UTC, maranomynet commented on types/ospec/index.d.ts
> +        notEquals(value: any): AssertionDescriber;
I think users may have valid reasons to test against seemingly obvious un-equalities.
Who are we to judge? :-)

If you feel strongly about this, I'll make this change.

2019-08-16 08:49 UTC, maranomynet commented on types/ospec/index.d.ts
> +    interface BasicAssertions<T = any> {
Interesting approach! I'd never have tought of that.

2019-08-16 09:27 UTC, maranomynet commented on types/ospec/index.d.ts
> +    type Definer = (
Regarding the `{}`: Judging by the ospec source `done` accepts any non-nully, non-Errory value and cast it to string (`String(err)` in [ospec.js#L152](https://github.com/MithrilJS/mithril.js/blob/next/ospec/ospec.js#L152))

Should we not reflect that?
...or at least accept `string` also?

2019-08-16 09:49 UTC, maranomynet commented on types/ospec/index.d.ts
> +        // FIXME: Find a more appropriate type annotation for the `error` parameter
TIL
:-)

2019-08-16 10:16 UTC, maranomynet commented on types/ospec/index.d.ts
> +    type Definer = (
Also, I can't get your suggested signatures to work as intended.

Tsc starts complaining about normal usage like

```js
o('test', () => {});
// Type 'void' is not assignable to type 'PromiseLike<any>'
```

and if I allow the first signature return to `PromiseLike<any> | void` then this error appears:

```js
o('test', (done, timeout) => {});
// Parameter 'done' implicitly has an 'any' type.
// Parameter 'timeout' implicitly has an 'any' type.
```

For now, I'm thinking about going for this less-clever improvement:

```
type Definer = (
    done: (error?: Error | string | null) => void,
    timeout: (delay: number) => void,
) => void | PromiseLike<any>;
```

2019-08-16 10:48 UTC, maranomynet commented
BTW, I don't think the failed Travis build is my fault, and affects most other PRs also.

From the log:
```
Error: In package.json: Dependency @vue/test-utils not in whitelist.
```

2019-08-17 18:41 UTC, isiahmeadows commented on types/ospec/index.d.ts
> +    type Definer = (
Okay, let's just go with the less clever part.

> Regarding the {}: Judging by the ospec source done accepts any non-nully, non-Errory value and cast it to string (String(err) in https://github.com/MithrilJS/mithril.js/blob/next/ospec/ospec.js#L152 )
>
> Should we not reflect that?
> ...or at least accept string also?

It's more idiomatic to require actual errors in TS APIs and declaration files, even if the underlying library supports more generic stuff. It also follows the fact TS won't let you throw anything other than an `Error` instance, despite JS letting you throw just about anything.

2019-08-17 18:42 UTC, isiahmeadows commented on types/ospec/index.d.ts
> +declare namespace Ospec {
It *should*. TS *idiomatically* prefers upper-cased namespaces, but the grammar doesn't *mandate* it.

2019-08-17 18:42 UTC, isiahmeadows commented on types/ospec/index.d.ts
> +        notEquals(value: any): AssertionDescriber;
Go ahead and make the change. Static types exist for a reason! 😉

2019-08-19 23:01 UTC, sheetalkamat requested changes

2019-08-19 23:01 UTC, sheetalkamat commented on types/ospec/tsconfig.json
> +        "esModuleInterop": true
Remove this and fix the test.. This flag is not needed just for writing test

2019-08-20 19:00 UTC, merged