luaparse: add loc & fix comments
DefinitelyTyped/DefinitelyTyped pull request #37665
Opened 2019-08-16 08:27 UTC by zaoqi

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] `tslint.json` should be present, and `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-08-16 13:09 UTC, thomasfn commented on types/luaparse/lib/ast.d.ts
> +    comments: string[] | undefined;
Can this be made into an optional property instead? e.g. `comments?: string[];`

2019-08-16 13:10 UTC, thomasfn commented on types/luaparse/lib/ast.d.ts
> +    } | undefined,
As below, can this be an optional property? `loc?: {...`

2019-08-16 13:18 UTC, thomasfn approved these changes

2019-08-19 21:18 UTC, teoxoy requested changes

2019-08-19 21:18 UTC, Teoxoy commented on types/luaparse/lib/ast.d.ts
> +    },
This property needs to end with a semicolon instead of a comma

2019-08-20 11:44 UTC, teoxoy approved these changes

2019-08-20 18:57 UTC, merged