Update BackstopJS types.
DefinitelyTyped/DefinitelyTyped pull request #37834
Opened 2019-08-22 15:47 UTC by cdeutsch

Add support for `Viewport.label` which is more commonly used than `name`.
Seems to be a free form string, not a limited set of strings:
https://github.com/garris/BackstopJS/blob/aa7de8ee059074f947768cfd04db1776348e1a7a/examples/jsBasedConfig/backstopConfig.js

Looks like they may have switched from `name` to `label` in this commit:
https://github.com/garris/BackstopJS/commit/0535303326e658e69d78f6405aac390b620ff222#diff-9e67e5c53c6a24f5b7f26f857fff03ea

Change `misMatchThreshold` to a number:
https://github.com/garris/BackstopJS/blob/aa7de8ee059074f947768cfd04db1776348e1a7a/examples/jsBasedConfig/backstopConfig.js#L35

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-08-22 16:05 UTC, cdeutsch commented
I don't understand this error message. I didn't change package.json

> Error: In package.json: Dependency vega-typings not in whitelist.

https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/575407434

2019-08-22 16:27 UTC, darioblanco approved these changes

2019-08-22 16:30 UTC, darioblanco commented
It LGTM, just the version change and 🚀

2019-08-22 17:53 UTC, sheetalkamat commented
You should merge master into this as there were some build breaks that have been fixed.

2019-08-22 19:20 UTC, sheetalkamat commented
@darioblanco 	Can you please review the additional changes. Thank you

2019-08-22 19:39 UTC, sheetalkamat requested changes
Waiting on rereview from @darioblanco

2019-08-24 12:36 UTC, darioblanco approved these changes

2019-08-24 12:37 UTC, darioblanco approved these changes

2019-08-24 12:38 UTC, darioblanco commented
Approved!

2019-08-24 14:42 UTC, darioblanco approved these changes

2019-08-24 14:42 UTC, darioblanco approved these changes

2019-08-25 04:50 UTC, merged