[lodash] Add missing multiply import
DefinitelyTyped/DefinitelyTyped pull request #37857
Opened 2019-08-23 07:24 UTC by henrikra

## Background

While importing multiply like this works `import { multiply } from 'lodash';` the import like this doesn't work `import multiply from 'lodash/multiply';`.

Then I just noticed that for some reason file that makes this import correct for typescript was missing so I added it.

Here is also picture from lodash docs that shows you can import specific functions like this:
![image](https://user-images.githubusercontent.com/12229968/63574113-b5a51180-c58f-11e9-9da4-0a2b4359fd7d.png)

What do you guys think? :)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://lodash.com/
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-08-24 01:29 UTC, aj-r requested changes
Great catch! I'm amazed this went unnoticed for so long.

Please do the same thing in the `ts3.1` folder.

2019-08-24 06:56 UTC, henrikra commented
@aj-r Can you be more specific what you mean? This is my first PR to Lodash types :D

2019-08-24 07:46 UTC, henrikra commented
@aj-r I think I got it right. Can you check? :)

2019-08-24 12:37 UTC, aj-r requested changes
Yep, that's exactly what I meant :).
I just remembered that there are actaully 2 versions of this that you can import:

- `import multiply from 'lodash/multiply';` (this is the one you just added)
- `import multiple from 'lodash.multiply';` (this is actually outside of the lodash folder, and is a separate npm package)

We actually have a script that generates both of these: `lodash/scripts/generate-modules.ts`. In theory, all you need to do is modify that script (add `multiply` into `allModuleNames()`) and run it.

To run the script:

1. Open a terminal in `lodash/scripts`.
2. `npm install`
3. `ts-node generate-scripts` (requires `ts-node` to be installed globally - alternatively you can use the local version at `lodash/scripts/node_modules/.bin/ts-node`)

I haven't run this script in a very long time so let me know if you have issues.

2019-08-24 20:38 UTC, henrikra commented
@aj-r I think I got it now. Can you check again? :D

2019-08-26 21:57 UTC, aj-r approved these changes

2019-08-27 18:13 UTC, merged