[testing-library/dom/prettyDOM] Allow missing properties in Options type
DefinitelyTyped/DefinitelyTyped pull request #37864
Opened 2019-08-23 11:03 UTC by jonalvarezz

<img width="1285" alt="Screenshot 2019-08-23 at 12 58 33" src="https://user-images.githubusercontent.com/2167222/63588112-fad43e00-c5a5-11e9-9339-57c1cf1a9de2.png">

Use the `OptionsReceived` type from pretty-format instead of `Options` to stop forcing to complete all the options properties.

This prevents TypeScript linter to ask for missing Options properties when extending prettyDOM

```
prettyDOM(container, undefined, { min: true })
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/facebook/jest/blob/fa8ef2269ceb52ee1bec2e77ba4358dd4ade85b2/packages/pretty-format/src/types.ts#L48> and <https://github.com/facebook/jest/tree/master/packages/pretty-format#usage-with-options>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-08-23 13:13 UTC, eps1lon requested changes
Seems like we have to whitelist `pretty-format` as a dependency and unpublish `@types/pretty-format` since `pretty-format` ships their own typings now.

This is explained in https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

2019-08-29 11:44 UTC, eps1lon commented
This PR requires #37934

2019-08-30 11:33 UTC, closed without merging

2019-09-04 05:43 UTC, eps1lon commented
@jonalvarezz This PR should work now. You can just create a new pull request from the existing branch.

2019-09-04 13:21 UTC, jonalvarezz commented
@eps1lon Thank you on it