Add missing FormState element to redux-form
DefinitelyTyped/DefinitelyTyped pull request #37940
Opened 2019-08-26 21:01 UTC by HendrikRoehm

According to the [example](https://redux-form.com/8.2.2/examples/submitvalidation/) on the redux-form page, it is possible to have a general error field for the whole form. I confirmed this behaviour with redux-form 8.2.6.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://redux-form.com/8.2.2/examples/submitvalidation/
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

I am not sure about this. I searched in the redux-form source code where the error field was added, but could not find it.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-09-02 07:46 UTC, bwlt commented
@HendrikRoehm did you mean [this prop](https://redux-form.com/8.2.2/docs/api/props.md/#-code-error-any-code-)?
according to the documentation it could be `any` value

2019-09-02 13:53 UTC, HendrikRoehm commented
Thanks @bwlt for mentioning the api documentation. The error component of the injected props is set correctly in reduxForm.d.ts line 82. I am dealing with another problem: The error key is missing in the (redux) state. 
The error element is set in [createReducer.js](https://github.com/erikras/redux-form/blob/master/src/createReducer.js) line 585 and 604. This is missing in the types currently. Nevertheless, you are right that the type should be any and not string. I have changed that.

What is not clear to me: The injectedFieldProps uses a variable ErrorType, which defaults to string. Shouldn't this also be used in the redux state definition to be consistent?

2019-09-03 07:53 UTC, bwlt commented
> What is not clear to me: The injectedFieldProps uses a variable ErrorType, which defaults to string. Shouldn't this also be used in the redux state definition to be consistent?

good point! I thought that is could be safe to add, but there are some issues:
Before add it it will be nice to have a check (or add a test) where the type parameter will be added to the `FormState` interface, but this type parameter should be also be present on other types (because you don't use `FormState` directly).
The points where to add the type parameter (and pass it down to `FormState`/`FormStateMap`):
1. [`interface FormStateMap`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/714e727c8fb8a9de041ec4eaea39ba9e5c76293a/types/redux-form/lib/reducer.d.ts#L16)
2. [`interface FormReducer`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/714e727c8fb8a9de041ec4eaea39ba9e5c76293a/types/redux-form/lib/reducer.d.ts#L4)
3. [`function formValueSelector`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/714e727c8fb8a9de041ec4eaea39ba9e5c76293a/types/redux-form/lib/formValueSelector.d.ts#L3)
4. [`type GetFormState`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/714e727c8fb8a9de041ec4eaea39ba9e5c76293a/types/redux-form/lib/reduxForm.d.ts#L23)

In my opinion adding it on `interface FormStateMap` (point 1) is not safe, because the interface have an index signature. This means that you can not describe correctly the ErrorType of each form you have: once you set an ErrorType it must be valid for all the forms.
For this reason I think that is not the best solution

2019-09-25 21:56 UTC, uniqueiniquity requested changes
Marking as changes requested until @bwlt's concern is addressed.

2019-09-30 08:14 UTC, bwlt commented
@uniqueiniquity in my opinion the current changes are ok for now.
The proposal described [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37940#issuecomment-527347552) is not feasible for now

2019-10-01 16:27 UTC, uniqueiniquity approved these changes

2019-10-01 16:27 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2019-10-01 16:27 UTC, merged