[node-polyglot] Add types for new options and static methods from latest release
DefinitelyTyped/DefinitelyTyped pull request #37991
Opened 2019-08-28 20:35 UTC by pmmmwh

# Background

Polyglot.js received a version update a year ago which allowed users to change the interpolation setting ([`v2.3.0](https://github.com/airbnb/polyglot.js/blob/master/CHANGELOG.md#v230-july-2-2018). Upon updating the types, I found that some other methods which have been altered, so I decided to also include them in this PR.

All terminology used in this PR follows the terminology used within the package.

**Question**:
Should I bump the version of the types to `v2.3.1` to better indicate that it is compatible with the latest release? I have never attempted such a big jump in versioning so I think it is worth asking before attempting it.

# PR Info

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - `Polyglot.options.interpolation`: [here](https://github.com/airbnb/polyglot.js/blob/3ca7e08c3771e058155ff9e4c3f289988da1190a/index.js#L213) and [here](https://github.com/airbnb/polyglot.js/blob/3ca7e08c3771e058155ff9e4c3f289988da1190a/index.js#L136)
  - [`new Polyglot().extend`](https://github.com/airbnb/polyglot.js/blob/3ca7e08c3771e058155ff9e4c3f289988da1190a/index.js#L273)
  - [`new Polyglot().unset`](https://github.com/airbnb/polyglot.js/blob/3ca7e08c3771e058155ff9e4c3f289988da1190a/index.js#L295)
  - [`Polyglot.transformPhrase`](https://github.com/airbnb/polyglot.js/blob/3ca7e08c3771e058155ff9e4c3f289988da1190a/index.js#L384)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-08-28 21:55 UTC, liamross requested changes
Looks great, just a few minor changes

2019-08-29 19:45 UTC, pmmmwh commented on types/node-polyglot/index.d.ts
> +    function transformPhrase(phrase: string, options?: number | Polyglot.InterpolationOptions, locale?: string): string;
Afaik the exported version do not take this argument - I suspect it wasn't intentional, but it is how it is right now.

https://github.com/airbnb/polyglot.js/blob/3ca7e08c3771e058155ff9e4c3f289988da1190a/index.js#L384-L386

2019-08-29 22:03 UTC, liamross commented on types/node-polyglot/index.d.ts
> +    function transformPhrase(phrase: string, options?: number | Polyglot.InterpolationOptions, locale?: string): string;
Ah I didn't check the export, good stuff

2019-08-29 22:03 UTC, liamross approved these changes

2019-09-05 18:25 UTC, merged