oracledb - Add missing properties and undefined where neccessary
DefinitelyTyped/DefinitelyTyped pull request #37993
Opened 2019-08-28 21:10 UTC by connorjayfitzgerald

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://oracle.github.io/node-oracledb/doc/api.html>>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-08-28 21:40 UTC, Bigous requested changes
It should be nice of yours to keep the original author and maintainer name in the comments.

2019-08-28 22:39 UTC, Bigous reviewed
@connorjayfitzgerald Thanks for your hard work and nice work on identifying optional items correctly.

2019-08-29 05:57 UTC, connorjayfitzgerald commented on types/oracledb/index.d.ts
> +// Definitions by: Connor Fitzgerald <https://github.com/connorjayfitzgerald>
Sorry about that @Bigous

2019-08-29 06:29 UTC, connorjayfitzgerald commented on types/oracledb/index.d.ts
> +// Definitions by: Connor Fitzgerald <https://github.com/connorjayfitzgerald>
@Bigous Could you please approve the changes to progress this PR? Thanks.

2019-08-30 12:22 UTC, Bigous commented on types/oracledb/index.d.ts
> +// Definitions by: Connor Fitzgerald <https://github.com/connorjayfitzgerald>
I've already sent the approval for the request... now it's the time to the bot of DefinitelyTyped to run and process everything

2019-08-30 12:24 UTC, Bigous reviewed
Everything ok

2019-08-30 16:22 UTC, closed without merging