Add Db#watch definition (mongodb)
DefinitelyTyped/DefinitelyTyped pull request #38021
Opened 2019-08-29 21:58 UTC by dvvc

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: http://mongodb.github.io/node-mongodb-native/3.1/api/Db.html#watch

2019-08-31 04:39 UTC, HosseinAgha commented
Hi @dvvc  
We are currently supporting node driver v3.3. Could you please refer to [v3.3 driver docs](http://mongodb.github.io/node-mongodb-native/3.3/api/Db.html#watch) and check if you need to make any updates?

2019-08-31 10:46 UTC, CaselIT approved these changes

2019-08-31 11:01 UTC, HosseinAgha commented
Hi @CaselIT.  
I forgot to submit my pending reviews 2 days ago. I think the PR does not follow docs (specially `startAfter` option).

2019-08-31 11:04 UTC, CaselIT commented on types/mongodb/index.d.ts
> +    watch(pipeline?: object[], options?: ChangeStreamOptions & { startAtOperationTime?: Timestamp, session?: ClientSession }): ChangeStream;
I missed this. I agree

2019-08-31 11:05 UTC, CaselIT requested changes
see comments of @HosseinAgha

2019-08-31 11:07 UTC, CaselIT commented
There seem to be no way to un-approve a pr.

2019-08-31 15:21 UTC, dvvc commented
Thanks @HosseinAgha and @CaselIT, will review and update the PR

2019-08-31 15:28 UTC, dvvc commented
Regarding the change in parameter types, which would affect Collection#watch and MongoClient#watch, should that be part of this same PR, or should I address that in its own PR?

2019-08-31 15:42 UTC, CaselIT commented
I think this one is fine 👍

2019-08-31 16:28 UTC, CaselIT commented
mmm, I think the bot has mistaken the emoji as approval. please wait before merging I think @dvvc is making some changes

2019-09-06 00:59 UTC, amcasey commented
Adding tag so we don't get confused by the bot's error.

2019-09-24 21:41 UTC, mrcrane requested changes
Marking as changes requested until the comments above are addressed

2019-10-01 22:31 UTC, closed without merging