Reference the toplevel index.d.ts from the extensions.
DefinitelyTyped/DefinitelyTyped pull request #38028
Opened 2019-08-30 11:47 UTC by dirk-olmes

cometd: fix imports of the extensions 

When using an extension in code the old 'import ..' does not work. Other modules explicitly import ../index which is what should be used here, too.

2019-09-05 17:47 UTC, amcasey commented
@dirk-olmes I'm not sure I understand - what was the issue with the old imports?

2019-09-06 05:20 UTC, dirk-olmes commented
> @dirk-olmes I'm not sure I understand - what was the issue with the old imports?

Using the following import `import AckExtension from 'cometd/AckExtension';` I get a tsc compile error `import AckExtension from 'cometd/AckExtension';`.

I looked around how other typedefs handle imports from a subdir to the parent definition and they do it in suggested way.

2019-09-06 05:44 UTC, hagl commented
In our codebase we use exactly the same import without problems.

@dirk-olmes Could this StackOverflow post solve your import issue: https://stackoverflow.com/questions/44028806/should-the-index-ts-be-resolved-by-typescript-as-default-module-file

2019-09-11 13:51 UTC, minestarks requested changes
Agree that this is probably an issue with the end user's configuration rather than an issue with the typings themselves. Marking "request changes" to prevent merging by accident

2019-09-13 07:37 UTC, dirk-olmes commented
> In our codebase we use exactly the same import without problems.
> 
> @dirk-olmes Could this StackOverflow post solve your import issue: https://stackoverflow.com/questions/44028806/should-the-index-ts-be-resolved-by-typescript-as-default-module-file

The main difference between your code base and mine is the module system that's used. The SO article suggests using `commonjs` but my project is set to `es2015`.

I'll try to put together something to dig deeper but that won't happen right now as I am super busy. Stay tuned ...

2019-09-18 14:40 UTC, closed without merging