Add "corestone-core"
DefinitelyTyped/DefinitelyTyped pull request #38070
Opened 2019-09-02 07:33 UTC by iamssen

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
    - I can't pass the `npm test`. Is there a way to test only cornerstone-core?
```
A       types/yarnpkg__lockfile/tslint.json
A       types/yarnpkg__lockfile/yarnpkg__lockfile-tests.ts
D       types/year-days/index.d.ts
D       types/year-days/tsconfig.json
D       types/year-days/year-days-tests.ts
M       types/yeoman-environment/index.d.ts
M       types/yeoman-generator/index.d.ts
M       types/yog-bigpipe/index.d.ts
M       types/youtube/index.d.ts
M       types/yup/index.d.ts
M       types/yup/yup-tests.ts
M       types/z-schema/tsconfig.json
A       types/zchat-browser/index.d.ts
A       types/zchat-browser/tsconfig.json
A       types/zchat-browser/tslint.json
A       types/zchat-browser/zchat-browser-tests.ts
A       types/zdog/index.d.ts
A       types/zdog/tsconfig.json
A       types/zdog/tslint.json
A       types/zdog/zdog-tests.ts
A       types/zenaton/index.d.ts
A       types/zenaton/tsconfig.json
A       types/zenaton/tslint.json
A       types/zenaton/zenaton-tests.tswarning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 2291 and retry the command.
AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: The specified version 5.1.0 of active-win must be newer than the version
it is supposed to replace, 5.1.0 of @types/active-win.
    at checkNotNeededPackage (/Users/ssen/Workspace/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:135:5)
    at getAffectedPackagesFromDiff (/Users/ssen/Workspace/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:89:13)
    at Object.runTests [as default] (/Users/ssen/Workspace/DefinitelyTyped/node_modules/types-publisher/src/tester/test-runner.ts:71:65)
    at main (/Users/ssen/Workspace/DefinitelyTyped/node_modules/types-publisher/src/tester/test.ts:35:5) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
npm ERR! Test failed.  See above for more details.
```
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldnt have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-09-05 22:41 UTC, amcasey requested changes
Providing an incomplete type definition is fine, but I have some questions about the way the incomplete sections were handled.

2019-09-05 22:41 UTC, amcasey commented on types/cornerstone-core/index.d.ts
> +    __foo__: 'bar';
This is being used as a brand?

2019-09-05 22:41 UTC, amcasey commented on types/cornerstone-core/index.d.ts
> +export function getMetaData(type: string, imageId: string): unknown;
To confirm, the expectation is that the result of `getMetaData` is intended to be difficult to consume without an explicit cast?

2019-09-06 00:52 UTC, iamssen commented
@amcasey cornerstone-core was a huge library to work alone. I checked the source code and defined it, but it was difficult to check everything.

I temporarily wrote unknowns that required a lot of time to check the source code and then marked TODO.

I also made some garbage code to avoid dts-lint ... (`__foo__: 'bar'` and `__UnknownFunction__`...)

There was too much work to do, so I tried to upload this unfinished definition, but I think I need to close this Pull Request and do more work.

I'm not sure how to work with such large definitions that are difficult to complete at once. Is there a similar definition for reference?

2019-09-06 01:02 UTC, amcasey commented
@iamssen, I think it's just fine to submit part of a definition - especially for a very large library.  I'd suggest using `any`, rather than `unknown`, if you're leaving loose ends (which, again, is fine) and suppress the lint warning about empty types, rather than giving them dummy members.

I'm not sure what sort of example you're looking for.  If you provide more details, I'll see what I can find.

2019-09-06 01:35 UTC, iamssen commented
@amcasey I was thinking about choosing between "unknown" and "any". Providing these uncertain parts as "unknown" will likely cause users to use them more carefully. Conversely, providing it as "any" may lead users to write wrong code.

Users will write a lot of "Type Guard", but is it better than writing insecure code?

-----

```
interface SomeType {
  __dont_use_this__: 'this is an dummy member for supress lint warning';
  // TODO describe type
}
```

Can I give a dummy member with code like this?

2019-09-06 07:21 UTC, iamssen commented
I supplemented the cornerstone-core definition and found that the API documentation differs from the actual API a lot.

I think I will have to rework almost everything, so I close this PR.

2019-09-06 07:21 UTC, closed without merging

2019-09-06 17:42 UTC, amcasey commented
Thanks, we're looking forward to the new version!