Fix chart.js method signatures
DefinitelyTyped/DefinitelyTyped pull request #38095
Opened 2019-09-03 13:28 UTC by burtek

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.chartjs.org/docs/latest/developers/api.html#destroy and below
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-09-03 16:56 UTC, burtek commented
PR's ready now, not a draft anymore. re-ping @anuti @FabienLavocat @KentarouTakeda @larrybahr @mernen @josefpaij @danmana @guillaume-ro-fr @archy-bold @braincore @frabnt @alexdor @mahnuh @Conrad777 @adripanico @wertzui @lekoaf @ElianCordoba

@RyanCavanaugh btw, shouldn't @typescript-bot be waiting until PR is marked as ready? It mentioned everyone before the draft was marked as ready (I created draft at first).

2019-09-08 17:47 UTC, frabnt commented
@burtek  Did you check if chart.js doc is actually in sync with the source code?

2019-09-08 18:08 UTC, burtek commented
Not really, I've just been irritated with `generateLegend()` and `stop()` typing and corrected two more methods based on docs. I've just checked all four and indeed one of them is not as doc says, so I've corrected that one. All four methods I'm changing here are in-sync with source code at the moment. Did not check anything else, though

2019-09-08 18:20 UTC, nebarf requested changes

2019-09-08 18:20 UTC, frabnt commented on types/chart.js/index.d.ts
> +    resize: () => void;
Why did you ignore the boolean param the function takes as input? https://github.com/chartjs/Chart.js/blob/cbace1cfe2c1b70ac26d1ee798eb5841fcd978c5/src/core/core.controller.js#L264

2019-09-08 18:20 UTC, frabnt commented on types/chart.js/chart.js-tests.ts
> +chartWithScriptedOptions.stop().clear().destroy();
Did you remove the call to `resize()` just because it's not chainable anymore?

2019-09-08 18:20 UTC, frabnt commented on types/chart.js/chart.js-tests.ts
> +const legend: string = chartWithScriptedOptions.generateLegend();
What's the point of storing the result of `generateLegend()` call?

2019-09-08 18:22 UTC, frabnt commented
@burtek Please use meaningful commit messages.

2019-09-08 18:23 UTC, burtek commented
I'll just re-check and re-do everything, it will be easier that way

2019-09-08 18:23 UTC, closed without merging