[react-datepicker@2.9.4] formatWeekday parameter is a string, not a date object
DefinitelyTyped/DefinitelyTyped pull request #38106
Opened 2019-09-03 19:03 UTC by enagy27

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Hacker0x01/react-datepicker/blob/de392f68bb08f63676edbbb0f28f17f0595c44a7/src/date_utils.js#L346
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2019-09-04 11:05 UTC, Ky6uk approved these changes

2019-09-09 13:54 UTC, minestarks requested changes
I'm not seeing how the source link shows this parameter is a string, it still seems like `Date` to me. Any reason why this function is singled out?

2019-09-09 16:37 UTC, enagy27 commented
@minestarks yes, I believe it's a `string`, and in my use of `react-datepicker` it looks like it's been passing me a `string`. The `formatWeekDay` function is the `formatFunc` in the provided snippet and it is supplied the result of `date-fns`'s `format` function (via `formatDate`), which will in turn provide a `string` (https://github.com/date-fns/date-fns/blob/ff7b6e1b15fa19e3b5613b1fb68c93abb7d99a1d/src/format/index.js#L314)

2019-09-09 17:10 UTC, minestarks commented
@enagy27 , I see it now, my bad. Thanks for the additional pointer!

2019-09-09 17:11 UTC, minestarks approved these changes

2019-09-09 17:11 UTC, merged

2019-09-09 17:12 UTC, enagy27 commented
@minestarks absolutely! Thanks for your review! 😄