mongoose - Add AsyncIterator to DocumentQuery
DefinitelyTyped/DefinitelyTyped pull request #38113
Opened 2019-09-04 01:01 UTC by muteshen

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://mongoosejs.com/docs/api.html#query_Query-Symbol.asyncIterator>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-09-04 08:57 UTC, Alorel approved these changes

2019-09-10 03:57 UTC, minestarks requested changes

2019-09-10 03:57 UTC, minestarks commented on types/mongoose/index.d.ts
> +    [Symbol.asyncIterator](): AsyncIterator<DocType>;
Wouldn't this break these types for users targeting downlevel ES versions?

2019-09-17 04:37 UTC, closed without merging

2020-02-17 11:33 UTC, toverux commented
I'd love to see this merged.

Is there no way to support older TypeScript versions while still using AsyncIterator?

Right now I use declaration merging with mongoose in my codebase to have this.