Added types for html-webpack-tags-plugin
DefinitelyTyped/DefinitelyTyped pull request #38131
Opened 2019-09-04 14:53 UTC by maxbogus

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldnt have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-09-06 23:30 UTC, rbuckton requested changes

2019-09-06 23:30 UTC, rbuckton commented on types/html-webpack-tags-plugin/index.d.ts
> +// Definitions by: // Definitions by: 贺师俊 <https://github.com/hax>, Vladimir Grenaderov <https://github.com/VladimirGrenaderov>, Max Boguslavskiy <https://github.com/maxbogus>
You have duplicated the `// Definitions by:` part of the comment. I would also suggest this:

```suggestion
// Definitions by: 贺师俊 <https://github.com/hax>
//                 Vladimir Grenaderov <https://github.com/VladimirGrenaderov>
//                 Max Boguslavskiy <https://github.com/maxbogus>
```

2019-09-06 23:30 UTC, rbuckton commented on types/html-webpack-tags-plugin/index.d.ts
> +export default class HtmlWebpackTagsPlugin extends Plugin {
According to the source, this is exported with `module.exports =` not `exports.default =`, so this import would not work at runtime unless additional compiler options are specified. I would recommend using the `export =` syntax to emulate the actual behavior, and move `Options` into an `HtmlWebpackTagsPlugin` namespace that merges with the class definition:

```ts
class HtmlWebpackTagsPlugin extends Plugin {
  constructor(options: HtmlWebpackTagsPlugin.Options);
}
namespace HtmlWebpackTagsPlugin {
  interface Options { ... }
}
export = HtmlWebpackTagsPlugin;
```

2019-09-23 17:19 UTC, maxbogus commented
@rbuckton , please review my changes.

2019-09-30 13:26 UTC, maxbogus commented
@rbuckton , please review my changes.

2019-10-21 10:19 UTC, closed without merging