[redux-form]: fix type discrepancies
DefinitelyTyped/DefinitelyTyped pull request #38189
Opened 2019-09-06 18:59 UTC by jeppeman

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L290
The type in the link is what is being passed to the callbacks provided in `ConfigProps` (ex. `onChange`), note that this does not contain the injected form props, which are currently in the type definitions for the callbacks (`P & InjectedFormProps`). This issue is addressed by this PR.
https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L1160 <-- This type has also been fixed.

2019-09-26 23:49 UTC, uniqueiniquity commented
@CarsonF @aikoven @LKay @bancek @alsiola @tehbi4 @huwmartin @m-b-davis @ethanresnick @Reggino @maddijoyce @smifun @mshaaban088 @esetnik @bwlt @mrsekut
Could I please get a maintainer review? I don't have enough domain knowledge about this library to approve.

2019-09-26 23:49 UTC, uniqueiniquity commented
@jeppeman Please ping me late next week if no maintainers review this by then.

2019-10-03 21:54 UTC, RyanCavanaugh commented
@jeppeman you OK with this getting merged? This looks fine with me but I don't have the requisite redux knowledge. Bummer none of the other owners showed up.

2019-10-04 05:46 UTC, jeppeman commented
@RyanCavanaugh yeah that's fine, tested it quite a bit after as well. Yup too bad. :/

2019-10-06 16:44 UTC, jeppeman commented
@uniqueiniquity looks like we have no takers.

2019-10-07 18:21 UTC, uniqueiniquity commented
As Ryan said, bummer. :)
Ok, I spent some time looking into your change, and I'm a little confused.
Your claim is that the `PropsWithContext` type you linked, which is getting passed to callbacks like `onChange`, does not include the injected form props, which are currently included but you have removed. However, it looks to me like that `PropsWithContext` type basically contains all of the props from `ConfigProps` (e.g., `onChange`, `onSubmit`, `destroyOnUnmount`), but also the the injected form props that you've removed (e.g., `dirty`, `submitFailed`, `invalid`). It seems like the only reason this change didn't break things is because you added the `{ [key: string]: any }` party to the `DecoratedFormProps` type, which prevented any existing references to injected form props from being marked as errors. What am I missing here?

2019-10-08 13:32 UTC, jeppeman commented
Thanks a lot for taking the time to review this, really appreciate it.
Yes, `PropsWithContext` does share some properties with `InjectedFormProps`, but not all of them, some properties found on `InjectedFormProps` (such as handleSubmit) are not present in `PropsWithContext` and vice versa.
Currently `P & InjectedFormProps` are being passed, this is just flat out wrong, it completely omits `ConfigProps` and as previously mentioned some of the properties defined there do not exist on `PropsWithContext`.
So basically this PR makes it so that no false promises are being made about the type passed to the callbacks. 
We could expose type definitions for https://github.com/erikras/redux-form/blob/master/src/createReduxForm.js#L218 in order to make it more specific I suppose, but that changes the scope of the PR quite a bit. Would you be up for reviewing that perhaps?

2019-10-14 21:30 UTC, andrewbranch requested changes

2019-10-14 21:30 UTC, andrewbranch commented on types/redux-form/lib/reduxForm.d.ts
> +> = P & Partial<ConfigProps<FormData, P, ErrorType>> & { [key: string]: any };
I think we should make whatever other changes are necessary to eliminate this `{ [key: string]: any }`, unless the type truly does have an unknowable string index signature at runtime.

2019-10-14 22:40 UTC, uniqueiniquity commented
@jeppeman Sorry for the delay in responding - I may not be the one who ends up reviewing the change, but i still think you should go ahead and do it as well.

2019-10-15 20:06 UTC, andrewbranch commented
Pinging owners again for review—this seems like a fairly substantial change and it would really be better if someone familiar with the library could review. Thank you! 🙏 

@aikoven @LKay @bancek @alsiola @tehbi4 @huwmartin @m-b-davis @ethanresnick @maddijoyce @smifun @mshaaban088 @esetnik @bwlt @mrsekut

2020-01-11 11:42 UTC, jeppeman commented
Ping :)

2020-05-04 18:05 UTC, weswigham approved these changes
In lieu of any responses from any type maintainers, I'm going to say that enough DT people have laid eyes on this to merge it.

2020-05-04 18:05 UTC, merged