Updated definitions for dinero.js 1.6
DefinitelyTyped/DefinitelyTyped pull request #38198
Opened 2019-09-07 15:06 UTC by juandaco

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldnt have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://sarahdayan.github.io/dinero.js/module-Dinero.html#~convertPrecision> <https://www.iso.org/iso-4217-currency-codes.html>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-09-24 23:38 UTC, uniqueiniquity requested changes

2019-09-24 23:38 UTC, uniqueiniquity commented on types/dinero.js/index.d.ts
> +        allocate(ratios: readonly number[]): Dinero[];
If you use `ReadonlyArray<number>` instead of `readonly number[]`, this will remain compatible with earlier versions of TypeScript.

2019-09-29 23:47 UTC, juandaco commented
@uniqueiniquity Done, sorry it took me so long. I had a couple of busy weeks.

2019-10-01 16:34 UTC, uniqueiniquity requested changes

2019-10-01 16:34 UTC, uniqueiniquity commented on types/dinero.js/index.d.ts
> +// TypeScript Version: 3.4
Please set this to the minimum version of TypeScript that is compatible with these type definitions.
Now that you don't use the `readonly` keyword, this should be much lower than 3.4.

2019-10-07 17:51 UTC, uniqueiniquity approved these changes

2019-10-07 17:51 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2019-10-07 17:51 UTC, merged