Fixes #35572, and the problem that using useRef with ref={} currently yields error
DefinitelyTyped/DefinitelyTyped pull request #38228
Opened 2019-09-09 06:11 UTC by staeke

Fixes #35572, and the problem that using 

```jsx
const a = useRef<HTMLDivElement>(); 
return <div ref={a}/>
```

currently yields error

Please fill in this template.

- [ x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x ] Test the change in your own code. (Compile and run.)
- [ x ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://reactjs.org/docs/hooks-reference.html#useref

2019-09-09 10:55 UTC, eps1lon requested changes
My issue with this change is that the overloaded ref type is only encountered before the ref is initialized. With this change the "type lifecycle" becomes `undefined - HTMLDivElement - null (- HTMLDivElement - null)*`. Since most of the use cases will not special case the very first cycle (`undefined`) I think it's fine to require explicit type annotation (`HTMLDivElement | undefined`) if you're interested in it or require `const divRef = useRef<HTMLDivElement>(null)`. 

As it stands right now this would be a breaking change if previous code strictly compared to `null` (`current === null`) since this would only narrow down to `HTMLDivElement | undefined`.

2019-09-09 16:49 UTC, staeke commented
Thanks for reviewing @eps1lon .

I agree and disagree. Since the change is potentially breaking I agree we should be bumping the major. I don't think status quo is acceptable though. But I do think we can reach a compromise that provides reasonable results for all use cases

##### 1.
First, and to the point with this PR - I don't think it's acceptable to require actual code changes from users (as opposed to typing changes) to accommodate ts issues - I'm thinking about adding a `null` parameter to `useRef`. That goes against the fundamental idea with typescript. Then, to your first suggestion. Writing:

```tsx
const ref = useRef<HTMLDivElement|undefined>()
return <div ref={ref}/>
```

...yields an error, so I don't see how your proposed solution works. Also, I personally think it's dirty to require `|undefined` for such a common use case to be sprinkled everywhere.

But, I'm all fine with changing `RefAttributes` and `ClassAttributes` instead, like below (`undefined` added): 

```ts
interface RefAttributes<T> extends Attributes {
    ref?: Ref<T | undefined>;
}
interface ClassAttributes<T> extends Attributes {
    ref?: LegacyRef<T | undefined>;
}
```

Would you be ok with that?

##### 2.
Secondly, I don't think it's acceptable to see that a textbook example yields a typescript error, and one that is also not correct. I'm thinking about:

```tsx
const ref = useRef()
return <div ref={ref}/>
```

I think this use case is best solved by having useRef default its type parameter to `any`. Which, I argue, is fundamentally what we know here. Not using a type parameter, should result in weaker typing, but not compile failure. But, not addressed in this PR. I could though.

##### 3.
Third, I think the `null` overload of `useRef` returning a non-mutable ref object is an error. It's just as mutable and we should change it. Do you agree?

2019-09-09 17:09 UTC, staeke commented
I have yet another problem with not including `undefined` with `useRef` being used without parameters; it simply doesn't reflect how React works. The output of `useRef` in reality **IS** `undefined` if you don't pass parameters. Hiding this fact is just producing worse typings, and more bugs. I think we have two options, either require `undefined` to be part of the type if no parameters are passed (seems overly unsmart to me). Or, simply, draw the conclusion, that it has to be part of the return type. Take the example:

```ts
const n = useRef<number>()
n.current.toFixed()
```

Currently yields no ts error. Breaks at runtime though

Now that could be fixed by amending `MutableRefObject` like I did, or e.g. change the `useRef` signature. Maybe that's better. How about:

```ts
function useRef<T>(): MutableRefObject<T|undefined>;
```

And, to be clear, and summarize it all, this would my preferred overloads:

```ts
function useRef<T = any>(): MutableRefObject<T|undefined>;
function useRef<T>(initialValue: T|null): MutableRefObject<T;
```

2019-09-10 03:09 UTC, Jessidhia commented
There is a reason why the overloads are like they are.

Maybe I need to write a lot more comments in the `.d.ts` files to elaborate; this is something that comes up time and again, and the problem is always the same.

First, `RefObject`  can **never** hold an `undefined` when you create it with `createRef`. It's initialized with `null`, and you are never supposed to write into it.

As for the overloads, here are the current ones:

```ts
function useRef<T>(initialValue: T): MutableRefObject<T>;
function useRef<T>(initialValue: T|null): RefObject<T>;
function useRef<T = undefined>(): MutableRefObject<T | undefined>;
```

The first overload is what you should hit whenever your initial value is sufficient to infer the generic, or when it is directly compatible with the explicit generic. This is what will happen with, for example, `useRef<0>(0)`, as useless as that is. Or `useRef<number>(0)`, which is the same as what's inferred by `useRef(0)`. This is the common case.

The second overload is **the** convenience overload when you want something be passed as a `ref={}` value. `useRef<RefType>(null)`. It's explicitly _not_ a mutable object because its intended use is to be written to by React. From your point of view, `.current` is a read-only value. If you want to make a mutable version of it, then just specify `| null` on your generic like in `useRef<RefType | null>(null)` to hit the first overload.

The third overload is there when you give no arguments (i.e. the "first argument" is `undefined`), and it's what'd be used by `useRef<Foo>()`. This of course prevents you from giving it as a `ref={}` because React will write `null` into it when the ref-ed component unmounts, but never write `undefined`. You can also just specify `useRef<Foo | null>()` here, which does _exactly_ what you ask for in your comments, but if you pass it to a `ref={}` the `.current` will only ever be `undefined` on the initial render pass; React will set it to `Foo | null` exclusively once it has control over the `ref={}`.

As I said in all cases, unless you want to use **the** `ref={}` convenience overload, then include the `| null` in your generic argument. Because React _wants_ to write `null` into it, not specifying the `null` yourself would make the type incorrect. On the other hand, if you let the code assume a `null` can be written there on all cases, like on this PR, then you create an overly-wide and less safe type when you use it as mutable fiber-local storage and not as a `ref={}` argument, and specify an outright unreachable type when used with `createRef()`.

2019-09-10 03:09 UTC, closed without merging

2019-09-20 16:58 UTC, mikew commented
@Jessidhia So how does one create a ref object, with a generic argument, an initial value of null, and have TS complain when there's improper usage? I'd expect a TS error in this:

```ts
const ref = useRef<string>(null)
console.log(ref.current.toUpperCase())
```

But it happily compiles: https://codesandbox.io/s/sparkling-firefly-e6fjk

2019-09-20 22:37 UTC, staeke commented
@mikew good point. Can you pls add it in the other thread - the open PR at https://github.com/DefinitelyTyped/DefinitelyTyped/issues/38260

2019-09-21 09:41 UTC, eps1lon commented
> @Jessidhia So how does one create a ref object, with a generic argument, an initial value of null, and have TS complain when there's improper usage? I'd expect a TS error in this:
> 
> ```ts
> const ref = useRef<string>(null)
> console.log(ref.current.toUpperCase())
> ```
> 
> But it happily compiles: [codesandbox.io/s/sparkling-firefly-e6fjk](https://codesandbox.io/s/sparkling-firefly-e6fjk)

codesandbox has like `strictNullChecks` disabled. The type checker reports and error with `strictNullChecks: true`: http://www.typescriptlang.org/play/index.html#code/JYWwDg9gTgLgBAbzgVwM4FMBK6BmcC+cOUEIcARFOgIYDGM5A3ALABQbOyAdvcBF3AAq6VDAAUASkRs4KDNhwAeUVGBcA5gD4xXZABs9EgHS1kUKlxhGYEAKpgw6KAGFqGSS1ay0WXMpiqGtrGpuboltZ2Dk6u7hKeMnK+Sipq6nAAPihcACa4aug52tx5OAU5IWYWVjb2ji5u6B6JPgr+gelZJflchcEmVeE1UfWxTfFsLfJ+qRqZcLoG2ouGA2ERtdENcZ7e0ykBafMr-aHVkXUxjc2s+GxAA

2021-08-12 11:59 UTC, karimuddin-tech commented
`React.useRef<any | null>();` this is work for me