Fix type for hls.js audio track
DefinitelyTyped/DefinitelyTyped pull request #38241
Opened 2019-09-09 14:28 UTC by drax98

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/video-dev/hls.js/blob/master/src/types/track.ts

2019-09-10 08:48 UTC, adripanico requested changes
What is the sense of having an interface that is not being used anywhere?

2019-09-10 09:57 UTC, drax98 commented
> What is the sense of having an interface that is not being used anywhere?

Before this change, there was used native AudioTrack interface from HTML media elements, which is not what hls.js returns. Adding new interface fixed this problem. 

When you view the whole file you can see where this interface is used.

2019-09-10 10:06 UTC, adripanico approved these changes

2019-09-11 05:28 UTC, minestarks requested changes

2019-09-11 05:28 UTC, minestarks commented on types/hls.js/index.d.ts
> +//                 Alexey I. Berezin <https://github.com/beraliv>
This line is duplicated.

2019-09-11 14:16 UTC, minestarks approved these changes

2019-09-11 14:16 UTC, merged