Add types npm-registry-fetch, libnpmsearch, and pacote
DefinitelyTyped/DefinitelyTyped pull request #38376
Opened 2019-09-14 05:28 UTC by ChaosinaCan

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-09-14 05:31 UTC, ChaosinaCan commented on types/pacote/index.d.ts
> +    directories: {};
[npm's documentation for this field](https://github.com/npm/registry/blob/master/docs/REGISTRY-API.md#version) literally says "???". 🤷‍♀️

In every request I've tried, it's always shown up as an empty object.

2019-09-24 21:59 UTC, uniqueiniquity requested changes

2019-09-24 21:59 UTC, uniqueiniquity commented on types/pacote/index.d.ts
> +export import extract = require('./extract');
For readability, I'd suggest doing:
```ts
import extract = require('./extract');
import manifest = require('./mainfest');
...

export { extract, manifest, ... };
```

2019-09-24 23:42 UTC, ChaosinaCan commented on types/pacote/index.d.ts
> +export import extract = require('./extract');
Good idea. Updated.

2019-09-25 16:37 UTC, uniqueiniquity approved these changes

2019-09-25 16:37 UTC, merged

2019-09-25 18:58 UTC, ChaosinaCan commented
Thanks!