[react] Add loading = auto / eager / lazy prop to img
DefinitelyTyped/DefinitelyTyped pull request #38390
Opened 2019-09-15 11:00 UTC by kachkaev

This PR tweaks React’s `ImgHTMLAttributes` interface to support the new [loading](https://web.dev/native-lazy-loading) HTML attribute.

My personal motivation for this change is to enable `loading=“lazy”` prop in styled-components. Typings in that library rely on React’s typings.

Example:
```tsx
import styled from "styled-components";
 const MyImg = styled.img`
  background: red;
`;

const jsx = <MyImg src="x" loading="lazy" />;
```

**Before:**
```
Type '{ src: string; loading: string; }' is not assignable to type 'IntrinsicAttributes & Pick<Pick<Pick<DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>, "style" | "title" | "key" | "defaultChecked" | "defaultValue" | ... 257 more ... | "width"> & { ...; }, "style" | ... 262 more ... | "width"> & Partial<...>, "style" | ... 262 more ... | "width"> & { ...; }...'.
  Property 'loading' does not exist on type 'IntrinsicAttributes & Pick<Pick<Pick<DetailedHTMLProps<ImgHTMLAttributes<HTMLImageElement>, HTMLImageElement>, "style" | "title" | "key" | "defaultChecked" | "defaultValue" | ... 257 more ... | "width"> & { ...; }, "style" | ... 262 more ... | "width"> & Partial<...>, "style" | ... 262 more ... | "width"> & { ...; }...'.ts(2322)
```
**After:** no error

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

--- 
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://web.dev/native-lazy-loading
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

---

2019-09-15 12:37 UTC, eps1lon requested changes
We decided to not accept attributes that are not part of the spec. If you want to use non-standard attributes I recommend using module augmentation.

Duplicate of #37590

2019-09-15 18:24 UTC, kachkaev commented
Closing in favour of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37590#issuecomment-520846460. Thanks for your feedback @eps1lon 🙌

2020-02-12 14:05 UTC, dartess commented
@kachkaev @eps1lon 
[Lazyload images](https://github.com/whatwg/html/pull/3752) now merged into `whatwg:master`. Now can this be considered a part of the spec?
If yes, this request looks like the best to reopen (I'm not sure about https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37590)

2020-02-12 14:12 UTC, dartess commented
Hurried a little. It seems that the value `auto` has not been accepted https://html.spec.whatwg.org/multipage/urls-and-fetching.html#lazy-loading-attributes 
@kachkaev

2020-02-12 15:44 UTC, kachkaev commented
@dartess PR reopened and updated, thanks for sharing the link to whatwg!

2020-02-12 18:55 UTC, eps1lon commented
Seems good. Could you rebase to trigger CI?

2020-02-14 23:11 UTC, eps1lon approved these changes

2020-02-18 01:16 UTC, merged