enzyme-react-intl typings
DefinitelyTyped/DefinitelyTyped pull request #38499
Opened 2019-09-20 14:34 UTC by mateusz-meller

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-09-24 00:06 UTC, uniqueiniquity requested changes
I noticed that you've written these type definitions in a way that the linter doesn't agree with, but didn't write any tests demonstrating the usage of the features you're aiming for by disabling the linter.

Please either write tests demonstrating why you believe these extra generics are necessary or write them in such a way that the lint rule doesn't need to be disabled. 

For example, unless you have a particular usage in mind, `shallowWithIntl` should be defined as follows:
`export function shallowWithIntl<P>(node: ReactElement<P>, options?: ShallowRendererProps): ShallowWrapper<P>`.

Thank you!

2019-09-24 07:26 UTC, mateusz-meller commented
I added unit test related to generic typings. Can you explain me why:
![image](https://user-images.githubusercontent.com/50196697/65490347-46cc1880-dead-11e9-89b2-04f7081d98a9.png)
constructed is the worst identifier?

2019-09-24 21:23 UTC, uniqueiniquity commented
I don't really have a good reason for why that's the case. Likely it's because of how the type of `constructed` depends on the type argument you provide when calling `shallowWithIntl`. It's not really a good pattern in TS to encourage type arguments to be provided at a method call - that's why we have the "no-unnecessary-generics" lint rule. I suspect that by doing it in this way, the performance is worse than if you just expected users to cast the result of `state()`.

2019-09-24 21:24 UTC, uniqueiniquity requested changes

2019-09-24 21:24 UTC, uniqueiniquity commented on types/enzyme-react-intl/index.d.ts
> +// tslint:disable-next-line no-unnecessary-generics
This `tslint:disable` is unnecessary.

2019-09-24 21:24 UTC, uniqueiniquity commented on types/enzyme-react-intl/index.d.ts
> +// tslint:disable-next-line no-unnecessary-generics
This tslint:disable is unnecessary.

2019-09-25 16:14 UTC, uniqueiniquity approved these changes

2019-09-25 16:14 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2019-09-25 16:14 UTC, merged