add destroyed flag as of node 8 https://nodejs.org/api/stream.html#stream_writable_destroyed
DefinitelyTyped/DefinitelyTyped pull request #38550
Opened 2019-09-23 20:09 UTC by ed-sparkes

Adding destroyed flag to ReadableStream and WriteableStream as per the node documentation from v8 onwards. 

If changing an existing definition:
- [1 ] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/stream.html#stream_writable_destroyed

2019-09-23 22:42 UTC, SimonSchick commented
Please do not update EOL v7 and v9 typings.

2019-09-29 09:23 UTC, trivikr approved these changes

2019-10-24 00:24 UTC, MichaelDeBoey approved these changes

2020-03-06 02:20 UTC, ExE-Boss requested changes
This needs rebasing.

Also, the main `types⁠/node⁠/base.d.ts` file is now for **Node v13**, so you need to do this for `types⁠/node⁠/v12⁠/base.d.ts` as well.

2020-03-13 01:43 UTC, closed without merging