[@types/redlock] Update definitions for redlock v4.0
DefinitelyTyped/DefinitelyTyped pull request #38705
Opened 2019-09-30 00:18 UTC by douglascayers

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/mike-marcacci/node-redlock/blob/v4.0.0/redlock.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-10-02 20:57 UTC, RyanCavanaugh requested changes

2019-10-02 20:57 UTC, RyanCavanaugh commented on types/redlock/v3/tslint.json
> +		// TODO
Please fix

2019-10-02 20:58 UTC, RyanCavanaugh commented on types/redlock/v3/tslint.json
> +		// TODO
Never mind

2019-10-02 20:58 UTC, RyanCavanaugh approved these changes

2019-10-02 20:58 UTC, merged

2019-10-03 01:15 UTC, douglascayers commented
Thanks, Ryan!