[echarts] update legend.textStyle option
DefinitelyTyped/DefinitelyTyped pull request #38708
Opened 2019-09-30 02:21 UTC by bbbbx

`legend.textStyle` has more properties than `TextStyle`, like `legend.textStyle.rich`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present). My network is so slow, can't clone the repo, I edit on Github.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://echarts.apache.org/en/option.html#legend.textStyle>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-09-30 02:35 UTC, Ovilia approved these changes

2019-09-30 02:36 UTC, Ovilia requested changes
Why changing to `object`?

2019-09-30 02:44 UTC, bbbbx commented
> Why changing to `object`?

`TextStyle` doesn't define `rich` property, for example:

![image](https://user-images.githubusercontent.com/22176164/65846017-eaff0500-e36e-11e9-86ef-eedbd95b87a1.png)

or change to `TextStyle | object` ? I am not famililar with TS

2019-09-30 03:56 UTC, ruixuel commented
The definition of TextStyle with rich attributes already is already defined in the namespace `CartesianAxis`  in index.d.ts. I suggest to move that definition to text-style.d.ts, then legend and axis label can share the same definition of this textStyle. If you are not familiar with typescript, I can add it tomorrow.

2019-09-30 05:49 UTC, bbbbx commented
> The definition of TextStyle with rich attribute is already defined in the namespace `CartesianAxis` in index.d.ts. I suggest to move that definition to text-style.d.ts, then legend and axis label can share the same definition of this textStyle. If you are not familiar with typescript, I can add it tomorrow.

OK, huge thanks

2019-09-30 19:36 UTC, ruixuel commented
I created another pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38733

2019-10-01 14:21 UTC, bbbbx commented
This pull request can be closed

2019-10-01 14:21 UTC, closed without merging