@types/mongodb: upgrade minimum typescript version to 3
DefinitelyTyped/DefinitelyTyped pull request #38789
Opened 2019-10-01 21:21 UTC by HosseinAgha

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X\ Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Take a look at #38687 and #38686

2019-10-01 22:08 UTC, julien-c approved these changes

2019-10-02 06:05 UTC, CaselIT requested changes

2019-10-02 06:05 UTC, CaselIT commented on types/mongodb/index.d.ts
> +type a = WithId<{ _id?: number, shit: string }>;
You left a test type

2019-10-02 06:06 UTC, HosseinAgha commented on types/mongodb/index.d.ts
> +type a = WithId<{ _id?: number, shit: string }>;
Oh, Thanks.

2019-10-02 15:10 UTC, CaselIT approved these changes
looks ok now.

2019-10-03 22:46 UTC, merged