[testing-library__dom] Specify element type
DefinitelyTyped/DefinitelyTyped pull request #38901
Opened 2019-10-05 11:35 UTC by mbelsky

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: [why optional](https://github.com/testing-library/dom-testing-library/blob/bda681c85c6c314bd70ec7566e9d7f56bf82d16e/src/pretty-dom.js#L23-L27) [why HTMLDocument](https://github.com/testing-library/dom-testing-library/blob/bda681c85c6c314bd70ec7566e9d7f56bf82d16e/src/__tests__/pretty-dom.js#L39-L46)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-10-05 13:53 UTC, weyert reviewed
The function in the library itself is:
```
function prettyDOM(
  dom = getDocument().body,
  maxLength = getMaxLength(dom),
  options,
) {
```

Can you rename `element` to `dom`?

2019-10-06 05:46 UTC, mbelsky commented
> Can you rename `element` to `dom`?

@weyert thanks for review. Done

2019-10-06 11:07 UTC, weyert approved these changes

2019-10-06 15:58 UTC, eps1lon requested changes

2019-10-06 15:58 UTC, eps1lon commented on types/testing-library__dom/pretty-dom.d.ts
> +    dom?: HTMLElement | HTMLDocument,
This is too narrow. It excludes svg.

```suggestion
    dom?: Element | HTMLDocument,
```

2019-10-06 16:03 UTC, mbelsky commented on types/testing-library__dom/pretty-dom.d.ts
> +    dom?: HTMLElement | HTMLDocument,
Thanks! Done

2019-10-06 16:07 UTC, eps1lon approved these changes

2019-10-07 23:32 UTC, merged