Fixing unreachable method overloads
DefinitelyTyped/DefinitelyTyped pull request #39000
Opened 2019-10-09 10:22 UTC by erik-krogh

Sometimes developers write method overloads that cannot be used.  
For example:

```TypeScript
class ContentBlock extends Record {
   ...
   getType(): DraftBlockType;
   getType(): string;
}
```

When a client invokes an overloaded method [the first matching overload will always be used](https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#4.15.1), and hence the following program will result in a type-error: 

```TypeScript
var foo: string = new ContentBlock().getType();
```

The second method overload is therefore unreachable, and the overload will cause nothing but confusion for developers writing a client or maintaining the library.

Often the mistake is caused by a simple duplicate method, which makes no difference, but can be confusing.
Other times the pattern is mistakenly used instead of having a union-type as the return. 
And a last reason is more tricky, consider the following: 

```TypeScript
interface ShallowRenderer {
    getRenderOutput<E extends ReactElement>(): E;
    getRenderOutput(): ReactElement;
} 
```

The first overload of the above program will always be used when writing a client using the library. This happens even if no type-parameters are used, as the TypeScript compiler will simply insert a default type parameter. 

This pull request attempts to fix all trivially discoverable instances of this mistake. 

Please fill in this template.

- [x] Use a meaningful title for the pull request. ~~Include the name of the package modified.~~
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

~~If changing an existing definition:~~
- [ ] ~~Provide a URL to documentation or source code which provides context for the suggested changes:~~
- [ ] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~
- [ ] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.~~

2019-10-09 18:58 UTC, aj-r requested changes

2019-10-09 19:21 UTC, SimonSchick approved these changes

2019-10-10 09:07 UTC, MunifTanjim approved these changes
Changes for `@types/draft-js` looks alright! :+1:

2019-10-10 09:22 UTC, erik-krogh commented on types/lodash/common/array.d.ts
> +          ): LoDashImplicitWrapper<Dictionary<T>>;
Yeah, you're right. 
Both possible orderings of the overloads are problematic though.   
Here I've showcased the problem with the old ordering: https://bit.ly/31YyVlD 

But yes. The old approach was likely the best, so I'll go ahead and revert this change.

2019-10-10 15:20 UTC, jgoz approved these changes
`react-test-renderer` 👍

2019-10-10 18:22 UTC, aj-r approved these changes

2019-10-14 20:13 UTC, andrewbranch approved these changes
This is great, thank you for doing this!

2019-10-14 20:14 UTC, merged