feat(@types/emoji-js) create types
DefinitelyTyped/DefinitelyTyped pull request #39026
Opened 2019-10-10 08:44 UTC by jasondibenedetto

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-10-10 20:59 UTC, armanio123 requested changes

2019-10-10 20:59 UTC, armanio123 commented on types/emoji-js/index.d.ts
> +export default class EmojiConvertor {
I don't think the library exports a `default`. Please remove this.

2019-10-10 20:59 UTC, armanio123 commented on types/emoji-js/index.d.ts
> +    constructor();
There's no point on defining an empty constructor. You can remove this line.

2019-10-10 20:59 UTC, armanio123 commented on types/emoji-js/index.d.ts
> +
Library appears to be an UMD module. You also need to define `export as namespace EmojiConvertor;`

2019-10-10 20:59 UTC, armanio123 commented on types/emoji-js/emoji-js-tests.ts
> +import EmojiConvertor from 'emoji-js';
Since there's no `default`, you need to change this import to `import EmojiConvertor = require('emoji-js');`

2019-10-10 21:49 UTC, jasondibenedetto commented
Thanks for the feedback @armanio123. I have amended my commit with your suggestions.

2019-10-14 19:51 UTC, armanio123 approved these changes

2019-10-14 19:51 UTC, merged