types/soundmanager2 - added audioFormats SoundManager Top-Level property
DefinitelyTyped/DefinitelyTyped pull request #39048
Opened 2019-10-11 06:46 UTC by tenerd

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <http://www.schillmania.com/projects/soundmanager2/doc/#soundmanager-audioformats>

2019-10-16 17:39 UTC, andrewbranch requested changes

2019-10-16 17:39 UTC, andrewbranch commented on types/soundmanager2/index.d.ts
> +        required: boolean;
Missing the optional `related` property:

```suggestion
        required: boolean;
        related?: string[];
```

2019-11-28 07:47 UTC, tenerd commented
ping :)

2019-12-02 15:08 UTC, andrewbranch approved these changes

2019-12-02 15:08 UTC, merged