support for auto axes display in char.js. Closes #38972
DefinitelyTyped/DefinitelyTyped pull request #39081
Opened 2019-10-12 14:39 UTC by vidi42

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.chartjs.org/docs/latest/axes/
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-10-17 16:39 UTC, ElianCordoba approved these changes
Besides the small change I mentioned LGTM

2019-10-17 16:39 UTC, ElianCordoba commented on types/chart.js/chart.js-tests.ts
> +import { BorderWidth, Chart, ChartColor, ChartData, ChartOptions, Point } from "chart.js";
Keep the imports with single quotes

2019-11-11 13:13 UTC, danmana requested changes

2019-11-11 13:13 UTC, danmana commented on types/chart.js/chart.js-tests.ts
> +                display: 'auto' as any,
with the new ts definition the cast `as any` should not be needed

```suggestion
                display: 'auto',
```

2019-11-11 13:13 UTC, danmana commented on types/chart.js/chart.js-tests.ts
> +                display: 'auto' as any,
```suggestion
                display: 'auto',
```

2019-11-18 13:28 UTC, closed without merging