[meteor] Typed observe() and observeChanges() to the type of documents observed
DefinitelyTyped/DefinitelyTyped pull request #39125
Opened 2019-10-14 20:06 UTC by alesn

(cherry picked from commit 8bcb41f7379422301e0a43a600195c3d52846b0e)

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://docs.meteor.com/api/collections.html#Mongo-Cursor-observe

2019-10-15 18:37 UTC, andrewbranch approved these changes

2019-10-15 23:56 UTC, andrewbranch commented
I probably jumped the gun on marking this approved. It looks reasonable to me but I do want to give the other owners another day or two to review if they’re interested.

2019-10-17 07:29 UTC, andrei-markeev requested changes

2019-10-17 07:29 UTC, andrei-markeev commented on types/meteor/globals/mongo.d.ts
> +    interface ObserveCallbacks<T> {
I believe this is a breaking change for existing projects. Let's avoid that: please provide a default value for `T` (same also for the second interface below)

2019-10-17 09:29 UTC, andrei-markeev approved these changes

2019-10-17 21:21 UTC, merged