Initial upload of V7.0 of 'agilite' node module @types definition
DefinitelyTyped/DefinitelyTyped pull request #39146
Opened 2019-10-15 15:24 UTC by agilitehub

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-10-16 18:04 UTC, andrewbranch requested changes

2019-10-16 18:04 UTC, andrewbranch commented on types/agilite/index.d.ts
> +export class Agilite {
The JavaScript library is a CommonJS module, but these definitions are for an ES2015 module. `module.exports =` in JavaScript needs to be declared as `export =` in .d.ts files. To export your support types from here, you’ll need to put them in a namespace also named `Agilite`:

```ts
declare class Agilite {
  // ...
}

declare namespace Agilite {
  interface AgiliteConfig {
    // ...
  }
  interface ReqType {
    // ...
  }
  interface Sort {
    // ...
  }
  // ...
}

export = Agilite;
```

2019-10-30 12:54 UTC, ArrieAgilite commented
@andrewbranch - Will you please have a look at the new code and update your review status?

2019-10-31 00:49 UTC, andrewbranch approved these changes

2019-10-31 00:49 UTC, merged