[@types/roslib] Add missing options to main constructor.
DefinitelyTyped/DefinitelyTyped pull request #39228
Opened 2019-10-18 07:21 UTC by VorpalBlade

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: http://robotwebtools.org/jsdoc/roslibjs/current/Ros.html
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-10-18 23:23 UTC, skycoop requested changes
Looks good to me other than a slight mismatch on the possible values for `transportLibrary`

2019-10-18 23:23 UTC, skycoop commented on types/roslib/index.d.ts
> +			transportLibrary?: 'websocket' | 'wokersocket' | 'socket.io' | RTCPeerConnection,
`workersocket` is not listed as an option in the [original docstring](https://github.com/RobotWebTools/roslibjs/blob/1.0.1/src/core/Ros.js#L29)

```suggestion
			transportLibrary?: 'websocket' | 'socket.io' | RTCPeerConnection,
```

2019-10-18 23:23 UTC, skycoop commented on types/roslib/index.d.ts
> +		 *   * transportLibrary (optional) - one of 'websocket', 'workersocket' (default), 'socket.io' or RTCPeerConnection instance controlling how the connection is created in `connect`.
```suggestion
		 *   * transportLibrary (optional) - one of 'websocket' (default), 'socket.io' or RTCPeerConnection instance controlling how the connection is created in `connect`.
```

2019-10-19 13:30 UTC, VorpalBlade commented
> Looks good to me other than a slight mismatch on the possible values for `transportLibrary`

Ah, that might be because I'm using the latest git revision. It has been added since. Given that it will presumably be valid in the next release, should we keep it or remove it?

2019-10-19 14:59 UTC, skycoop commented
My personal inclination is to match the current released version of the package (v1.0.1) since:
- That's what the version comment has listed
- To avoid unnecessary confusion we should probably try to adhere to the currently live [JSDocs](http://robotwebtools.org/jsdoc/roslibjs/current/Ros.html)

2019-10-23 01:54 UTC, skycoop approved these changes
Thanks for making those changes :grin:

2019-10-23 21:53 UTC, merged