feat: Add `function‑bind`
DefinitelyTyped/DefinitelyTyped pull request #39337
Opened 2019-10-22 22:43 UTC by ExE-Boss

I’ve been working on this longer than #38979 and #38947 combined.

The reason this took so long was figuring out a way to do this in a way that’s compatible with `strictBindCallApply`.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

---

review?(@ljharb)

2019-10-22 22:53 UTC, ljharb commented
Seems fine but I'm not a TS expert - this package is basically `typeof Function.prototype.bind`, though.

2019-10-22 22:58 UTC, ExE-Boss commented
> Seems fine but I'm not a TS expert - this package is basically `typeof Function.prototype.bind`, though.

Doing&nbsp;that&nbsp;didn’t quite&nbsp;work&nbsp;correctly with&nbsp;`strictBindCallApply`, though.

2019-10-23 22:10 UTC, weswigham requested changes

2019-10-23 22:10 UTC, weswigham commented on types/function-bind/implementation.d.ts
> +// prettier-ignore
Please don't suppress prettier. I'd like it so that when someone goes back and formats this file, it gets formatted per our formatting rules.

2019-10-24 05:33 UTC, ExE-Boss commented
How do I enable `strictBindCallAplly` for tests running on **TS3.4+**, but disable it for **<TS3.3** without duplicating the `ts3.3` type definitions.

This is because of [type inference improvements for generic functions in **TS3.4**](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#higher-order-type-inference-from-generic-functions).

2019-11-27 00:39 UTC, amcasey commented
@ExE-Boss Unfortunately, this has been open long enough to have fallen out of date.  A new policy has been established that would cause it to break immediately in its current form: https://github.com/microsoft/types-publisher/issues/708

Can you please update it accordingly?

2019-11-27 01:04 UTC, ExE-Boss commented
I&nbsp;somehow completely&nbsp;forgot about&nbsp;that despite&nbsp;approving it&nbsp;in&nbsp;<https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40676>.&nbsp;😄

2019-11-27 01:17 UTC, amcasey commented
@ExE-Boss is this ready to go or are you still fine tuning `strictBindCallApply`?

2019-11-27 02:25 UTC, ExE-Boss commented
I’ve&nbsp;already got&nbsp;`strictBindCallApply`&nbsp;working, the&nbsp;only&nbsp;issue is&nbsp;that to&nbsp; test it&nbsp;in&nbsp;CI, I’d&nbsp;need to&nbsp;duplicate the&nbsp;`ts3.3`&nbsp;directory as&nbsp;`ts3.4`, which&nbsp;would have&nbsp;it&nbsp;enabled, but&nbsp;would&nbsp;otherwise be&nbsp;identical to&nbsp;`ts3.3`.

2019-12-03 18:41 UTC, amcasey commented
@ExE-Boss I don't, personally, know how to solve that problem.  Would you like to merge this as-is and then figure out how to enable stricter checking in a subsequent PR?

2019-12-03 18:54 UTC, ExE-Boss commented
@amcasey
> Would you like to merge this as-is and then figure out how to enable stricter checking in a subsequent PR?

Yes.

2019-12-03 18:59 UTC, merged