[terser-webpack-plugin] update `terser` version to ^4.3.9
DefinitelyTyped/DefinitelyTyped pull request #39907
Opened 2019-10-27 05:47 UTC by xnuk

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/terser/terser/blob/3f3fac3b84d229262557ac80fe02532d9630538e/CHANGELOG.md#v438
  - https://github.com/webpack-contrib/terser-webpack-plugin/blob/1b03b6b84652dd451465ea24e60ad717498fad2f/CHANGELOG.md#220-2019-10-22
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-10-28 08:39 UTC, Danscho commented on types/terser-webpack-plugin/index.d.ts
> +        warningsFilter?: (warning: string, source: string, file: string) => boolean;
According to the documentation the `source` argument can be undefined if sourcemaps are not used. So this should be included in the type definition or 'strictNullChecks' are not able to catch this pitfall.

2019-10-29 08:42 UTC, Danscho requested changes
Please see my comment at index.d.ts

2019-11-03 13:27 UTC, xnuk commented
Sorry for late response.

2019-11-04 08:28 UTC, Danscho approved these changes

2019-11-05 00:31 UTC, merged