Fix typings for tsc esModuleInterop=false
DefinitelyTyped/DefinitelyTyped pull request #40146
Opened 2019-11-05 06:18 UTC by zorji

Fix typings when the compilation options don't have "esModuleInterop" enabled.

The existing typings only works when "esModuleInterop" is enabled in the compilation options. i.e.

```
import promiseRetry from 'promise-retry'
```

However, some repositories don't have "esModuleInterop" enabled for compatibility reasons. i.e.

```
import * as promiseRetry from 'promise-retry'
```

And the error `error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.` is raised on a compilation.

This change fixes the error and makes it also work in the environment doesn't' have "esModuleInterop" enabled.

2019-11-11 23:32 UTC, PranavSenthilnathan commented
I think the current definition is correct and the usage in those libraries may be wrong. Without the esModuleInterop flag they should be doing importing the library like:
```
import promiseRetry = require('promise-retry');

promiseRetry(...)
```

2019-11-11 23:35 UTC, PranavSenthilnathan requested changes
As mentioned in the comment, I think it was fine before. Could you share an example (import as well as use-site) of when this change is needed?

2019-11-12 00:45 UTC, zorji commented
> I think the current definition is correct and the usage in those libraries may be wrong. Without the esModuleInterop flag they should be doing importing the library like:
> 
> ```
> import promiseRetry = require('promise-retry');
> 
> promiseRetry(...)
> ```

@PranavSenthilnathan thanks for reviewing

Here is my usage and I am getting error `error TS2497: This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.`

```
import * as promiseRetry from 'promise-retry'
```

Using `import promiseRetry = require('promise-retry');` doesn't throw the error but using `require` instead of `import` lose all the typing.

Do you mind give it a try?

2019-11-12 00:54 UTC, zorji commented
Here is the minimal step to reproduce the issue

```
mkdir example
cd example
npm init -y
npm i -S typescript promise-retry @types/promise-retry ts-node @types/node
npx tsc --init
echo "import * as promiseRetry from 'promise-retry'" > index.ts
npx tsc index.ts
```

2019-11-15 23:32 UTC, PranavSenthilnathan commented
> Using import promiseRetry = require('promise-retry'); doesn't throw the error but using require instead of import lose all the typing.

Where do you lose the typing? If you have `@types/promise-retry` then this will be well typed.

The library is not using the ES6 style export so the import shouldn't be an ES6 import either (it should be using the `require` statement above).

2019-11-18 06:25 UTC, zorji commented
Hi @PranavSenthilnathan 
I just tested it using `require()` and it works. Sorry I used to thought `import` was the only correct to import modules in TypeScript.

I also found the documentation in case anyone interested: https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

2019-11-18 06:25 UTC, closed without merging