feat(@types/ospec): Relax object-only requirement of the ".deep*" methods
DefinitelyTyped/DefinitelyTyped pull request #40160
Opened 2019-11-05 18:07 UTC by maranomynet

See rationale here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37645/files/99d3472488ef8df7f6cd529a7799f99971f56de8#diff-4a55ff58701161f211e3b6ccfa23aea2R30-R33

IMO we made the mistake of making `o.deepEquals()` and `o.notDeepEquals()` too opinionated about the types it compares.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

2019-11-05 19:05 UTC, dead-claudia requested changes
What rationale? I don't see it in the link.

2019-11-05 19:09 UTC, dead-claudia approved these changes
I'm the one who wrote those types, BTW. I misremembered [it works with everything](https://github.com/MithrilJS/ospec/blob/master/ospec.js#L233), so I'll unblock this. The link is still broken, though.

2019-11-05 22:00 UTC, merged

2019-11-05 23:41 UTC, maranomynet commented
Back at the Computer.
@isiahmeadows Sorry about the broken link. I have no idea what GitHub is doing there, but it works for me when I'm logged in, but hides the comment when I open it in a private browsing window.

...which might explain why you probably didn't see it in the first place.

Here's a screen shot for the record:
<img width="809" alt="image" src="https://user-images.githubusercontent.com/86827/68255651-ba715180-0025-11ea-864c-dc9265459370.png">

2019-11-07 20:10 UTC, isiahmeadows commented
@maranomynet Oh okay, so I missed you pointing out the same screwup I noticed in [this comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40160#pullrequestreview-311973352). 😄🤦‍♀️