[@testing-library/cypress] Add JQuery types from cypress
DefinitelyTyped/DefinitelyTyped pull request #40210
Opened 2019-11-07 09:03 UTC by AlgusDark

This PR fix #40099 by using the types from `cypress/types`,

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2019-11-15 15:59 UTC, wKovacs64 commented
My concern is that the Cypress docs mention using the `types` option to avoid conflicts:

> The `types` will tell the TypeScript compiler to only include type definitions from Cypress. This will address instances where the project also uses `@types/chai` or `@types/jquery`. Since Chai and jQuery are namespaces (globals), incompatible versions will cause the package manager (`yarn` or `npm`) to nest and include multiple definitions and cause conflicts.

I suspect if your project used `@types/jquery` and the version didn't match the jQuery types bundled with Cypress, you'd run into conflicts by importing like that. I think that should be confirmed/denied before merging.

@NicholasBoll or @jennifer-shehane might have a more informed opinion here as they authored the aforementioned docs on using TypeScript with Cypress.

2019-11-18 22:19 UTC, sheetalkamat requested changes
Waiting to hear from the owners of cypress

2019-11-25 00:25 UTC, AlgusDark commented
@sheetalkamat is there any way to keep this PR open until we hear from @NicholasBoll or @jennifer-shehane ?

2019-11-25 22:31 UTC, closed without merging

2019-11-26 07:22 UTC, NicholasBoll commented
I didn't respond in time... I replied to the original issue