[invariant] Assertion functions
DefinitelyTyped/DefinitelyTyped pull request #40218
Opened 2019-11-07 18:51 UTC by josh

Make use of TypeScript 3.7 assertion function feature to implement `invariant`.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-11-07 20:26 UTC, bennett000 commented
Looks good to me.

That said I'm not a reviewer (on the right sidebar) and I cannot seem to approve as @typescript-bot suggests

2019-11-08 04:49 UTC, dtinth requested changes
Thanks for the PR!

I'm excited to use assertion functions in TypeScript as well. However I think we should retain support for `invariant (false)` pattern.

2019-11-08 04:49 UTC, dtinth commented on types/invariant/invariant-tests.ts
> +// $ExpectType void | {}
I believe this should stay as `{}` to facilitate this pattern:

```ts
const thing = getThing() || invariant(false, 'Expected getThing to return something')
```

as well as

```ts
const thing = getThing() ?? invariant(false, 'Expected getThing to return something')
```

2019-11-08 04:49 UTC, dtinth commented on types/invariant/index.d.ts
> -    (testValue:false, format?:string, ...extra:any[]):never;
IMO we should keep this overload to not break existing test (see comment below).

2019-11-08 04:49 UTC, dtinth commented on types/invariant/index.d.ts
> +    (testValue:any, format?:string, ...extra:any[]):asserts testValue;
Would be great if some test can be added for this.

2019-11-09 03:09 UTC, josh commented
> I believe this should stay as `{}` to facilitate this pattern:

Is it possible for an `asserts` function to have a return value?

> However I think we should retain support for `invariant (false)` pattern.

👍 that makes sense.

2019-11-09 07:14 UTC, dtinth reviewed
@josh Thanks! Mind adding a corresponding test for this change? Maybe a test could look like this:

```ts
declare const x: any
invariant(typeof x === 'string')
const s = x
// $ExpectType string
x
```

2019-11-09 21:38 UTC, josh commented
> Mind adding a corresponding test for this change? Maybe a test could look like this:

Tried that, but got:

```
expect  TypeScript@next expected type to be:
  string
got:
  any
```

2019-11-19 21:22 UTC, closed without merging