[storybook__addon-info] Update types to match 5.2
DefinitelyTyped/DefinitelyTyped pull request #40270
Opened 2019-11-09 14:31 UTC by gaetanmaisse

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

--

What I did? 

 - Use types directly from `Storybook` repo as it is now written in TS
 - Update types to match version 5.2 of the addon and of Storybook (as they have to have the same version)

2019-11-09 16:27 UTC, MichaelDeBoey requested changes

2019-11-09 16:27 UTC, MichaelDeBoey commented on types/storybook__addon-info/index.d.ts
> +    propTables?: Array<ComponentType<any>> | false;
Use `unknown` instead? 🤔

```suggestion
    propTables?: Array<ComponentType<unknown>> | false;
```

Or just delete the `any`? 🤔
```suggestion
    propTables?: ComponentType[] | false;
```

2019-11-09 16:27 UTC, MichaelDeBoey commented on types/storybook__addon-info/index.d.ts
> +    propTablesExclude?: Array<ComponentType<any>>;
Use `unknown` instead? 🤔

```suggestion
    propTablesExclude?: Array<ComponentType<unknown>>;
```

Or just delete the `any`? 🤔
```suggestion
    propTablesExclude?: ComponentType[];
```

2019-11-09 16:27 UTC, MichaelDeBoey commented on types/storybook__addon-info/index.d.ts
> +    components?: { [key: string]: ComponentType<any> };
Use `unknown` instead? 🤔

```suggestion
    components?: { [key: string]: ComponentType<unknown> };
```

Or just delete the `any`? 🤔
```suggestion
    components?: { [key: string]: ComponentType };
```

2019-11-09 16:27 UTC, MichaelDeBoey commented on types/storybook__addon-info/index.d.ts
> +            defaultValue: any;
Use `unknown` instead? 🤔

```suggestion
            defaultValue: unknown;
```

2019-11-09 16:27 UTC, MichaelDeBoey commented on types/storybook__addon-info/storybook__addon-info-tests.tsx
> +const TableComponent = ({
Make this a `FunctionComponent` instead

```ts
type Props = ComponentProps<Options['TableComponent']>;
const TableComponent : FunctionComponent<Props> = ({ propDefinitions }) => (
  // ...
);
```

2019-11-09 16:27 UTC, MichaelDeBoey commented on types/storybook__addon-info/storybook__addon-info-tests.tsx
> +import { addDecorator, storiesOf, addParameters } from '@storybook/react';
```suggestion
import { addDecorator, addParameters, Options, storiesOf } from '@storybook/react';
```

2019-11-09 16:27 UTC, MichaelDeBoey commented on types/storybook__addon-info/storybook__addon-info-tests.tsx
>  import * as React from 'react';
```suggestion
import React, { Component, ComponentProps } from 'react';
```

2019-11-09 16:27 UTC, MichaelDeBoey commented on types/storybook__addon-info/storybook__addon-info-tests.tsx
>  const { Component } = React;
```suggestion
```

2019-11-09 16:27 UTC, MichaelDeBoey commented on types/storybook__addon-info/storybook__addon-info-tests.tsx
```suggestion
```

2019-11-09 17:24 UTC, gaetanmaisse commented
Thanks for the review @MichaelDeBoey! I already tried to use `unknown` but it's causing TS issues in "tests" because there are more props in the given component than in `ComponentType<unknown>` 🤷‍♂ I'm just a React newbie and don't know a workaround.

I created an interface for the props of `TableComponent` used in `Options` of this addon and was able to use it directly in tests then 😃

2019-11-09 19:27 UTC, MichaelDeBoey commented
@gaetanmaisse I would just delete the `any` between the `ComponentType` props then, since the `props` type is defaulted to `{}`.

2019-11-10 09:09 UTC, gaetanmaisse commented
@MichaelDeBoey we don't want it to be defaulted to `{}` as given component can have required props. 
I added a 2nd commit with a more realistic use of the addon parameters, in this example `label` is a required prop in both `BaseButton` and `CustomButton` component so I have to keep `ComponentType<any>` in the types to avoid:
```
TS2322: Type 'FunctionComponent<HTMLAttributes<HTMLButtonElement> & { label: string; }>[]' is not assignable to type 'ComponentType<{}>[]'.
  Type 'FunctionComponent<HTMLAttributes<HTMLButtonElement> & { label: string; }>' is not assignable to type 'ComponentType<{}>'.
    Type 'FunctionComponent<HTMLAttributes<HTMLButtonElement> & { label: string; }>' is not assignable to type 'FunctionComponent<{}>'.
      Types of parameters 'props' and 'props' are incompatible.
        Type '{ children?: ReactNode; }' is not assignable to type 'PropsWithChildren<HTMLAttributes<HTMLButtonElement> & { label: string; }>'.
          Property 'label' is missing in type '{ children?: ReactNode; }' but required in type '{ label: string; }'.

```

2019-11-10 12:47 UTC, MichaelDeBoey commented
Now there's no example with `TableComponent` anymore? 🤔

2019-11-10 18:00 UTC, gaetanmaisse commented
`TableComponent` is now only used as it was before (and as it is in addon readme and SB examples) so as 
`TableComponent` property of addon Options:  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/40270/files#diff-507fc2a1a9fafe89f249889154266a38R58 😉

2019-11-10 18:20 UTC, MichaelDeBoey approved these changes

2019-11-15 14:38 UTC, ndelangen approved these changes

2019-11-15 19:07 UTC, MichaelDeBoey approved these changes

2019-11-18 21:36 UTC, merged