Update types for react-beautiful-dnd v12
DefinitelyTyped/DefinitelyTyped pull request #40309
Opened 2019-11-11 18:57 UTC by aruniverse

Please fill in this template.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/atlassian/react-beautiful-dnd/blob/master/src/types.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2019-11-12 23:10 UTC, PranavSenthilnathan commented
Can you please take a look @varHarrie @bradleyayers @paustint @marknelissen @enricoboccadifuoco @lonyele @lukyth @aruniverse

2019-11-16 23:34 UTC, aruniverse commented
@alexreardon maybe you want to review this?

2019-11-19 04:50 UTC, alexreardon commented
I can take a look in the next 24hrs

2019-11-19 05:05 UTC, alexreardon reviewed
Best things to do is check out:

- [12.0 release notes](https://github.com/atlassian/react-beautiful-dnd/releases/tag/v12.0.0)
- [Our manual type file](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/types.md)

2019-11-19 05:05 UTC, alexreardon commented on types/react-beautiful-dnd/index.d.ts
> +export type OnDragStartResponder = (start: DragStart, provided: ResponderProvided) => void;
https://github.com/atlassian/react-beautiful-dnd/releases/tag/v12.1.0

2019-11-19 05:05 UTC, alexreardon commented on types/react-beautiful-dnd/index.d.ts
>      'aria-roledescription': string;
this is now `aria-labelledby`

2019-11-19 05:05 UTC, alexreardon commented on types/react-beautiful-dnd/index.d.ts
>      'data-react-beautiful-dnd-drag-handle': string;
```diff
type DragHandleProps = {|
+  // focus management is now handled without needing these handlers
-  onFocus: () => void,
-  onBlur: () => void,

+  // new sensor api does not require on element event handlers
-  onMouseDown: (event: MouseEvent) => void,
-  onKeyDown: (event: KeyboardEvent) => void,
-  onTouchStart: (event: TouchEvent) => void,

+  // Moving to new data-* format
-  'data-react-beautiful-dnd-drag-handle': string,
+  // what draggable the handle belongs to
+  'data-rbd-drag-handle-draggable-id': DraggableId,
+  // What DragDropContext the drag handle is in
+  'data-rbd-drag-handle-context-id': ContextId,

+  // New way of doing lift announcements
-  'aria-roledescription': string,
+  // id of drag handle aria description for screen readers
+  'aria-labelledby': ElementId,

  tabIndex: number,
  draggable: boolean,
  onDragStart: (event: DragEvent) => void,
|};
```

2019-11-19 05:05 UTC, alexreardon commented on types/react-beautiful-dnd/index.d.ts
>  export interface DragDropContextProps {
```diff
type Props = {|
  ...Responders,
  // We do not technically need any children for this component
  children: Node | null,
  // Read out by screen readers when focusing on a drag handle
+ liftInstruction?: string,
+ // Used for strict content security policies
+ // See our [content security policy guide](/docs/guides/content-security-policy.md)
+ nonce?: string,
+ // See our [sensor api](/docs/sensors/sensor-api.md)
+ sensors?: Sensor[],
+ enableDefaultSensors?: ?boolean,
|};
```

2019-11-19 13:38 UTC, aruniverse commented on types/react-beautiful-dnd/index.d.ts
> +export type OnDragStartResponder = (start: DragStart, provided: ResponderProvided) => void;
Thanks, ill take a look and update accordingly. I made this when v12.0 was out, will need to update to support 12.1

2019-11-19 20:38 UTC, sheetalkamat requested changes
Address feedback from @alexreardon

2019-12-03 02:26 UTC, aruniverse commented on types/react-beautiful-dnd/index.d.ts
> +export type OnDragStartResponder = (start: DragStart, provided: ResponderProvided) => void;
I ended up copying from https://github.com/atlassian/react-beautiful-dnd/blob/master/src/types.js.

2019-12-07 19:53 UTC, aruniverse reviewed
addressed changes from @alexreardon

2019-12-12 16:38 UTC, aruniverse commented
Can someone and review the changes ive made since @alexreardon initially commented?

@varHarrie @bradleyayers @paustint @marknelissen @enricoboccadifuoco @lonyele @lukyth

2019-12-12 22:05 UTC, bradleyayers approved these changes
This looks fairly benign, the old types are moved to v11 so compatibility should be maintained for anyone depending on 11.x, and so even if the new 12.x aren't perfect it should only affect people who explicitly upgrade. lgtm

2019-12-13 01:40 UTC, aruniverse reviewed
thank you @bradleyayers.

can you take a look @sheetalkamat @PranavSenthilnathan ?

2020-01-02 00:55 UTC, aruniverse reviewed
addressed changes and added definitions from rbd v11.0.4

2020-01-05 23:33 UTC, alexreardon commented
Anything holding this one up?

2020-01-06 01:54 UTC, aruniverse commented
We're waiting on @sheetalkamat to review

2020-01-16 00:33 UTC, ArielFrischer commented
+1 @sheetalkamat would really appreciate a review, our team is stuck on old types.

2020-01-18 08:07 UTC, bradleyayers approved these changes

2020-01-31 05:28 UTC, leeyeh commented
While waiting for the review, is there any preview/unstable/fork release available? Normally we can simply `npm install` a git brunch, but I dont know how it works for this monorepo.

2020-01-31 05:42 UTC, aruniverse commented
I think a hack for now is to create a react-beautiful-dnd.d.ts locally in your project, and in it just declare the module which just exports all the v12 types in this pr. 

So:

'''
declare module "react-beautiful-dnd" {

// Just copy everything from the new type defs

}
'''

Tomorrow morning I'll try to create another PR from the same branch and see if we can get that approved instead by the community.

2020-01-31 15:40 UTC, aruniverse commented
Created PR #42010 instead

2020-01-31 15:40 UTC, closed without merging

2020-02-01 04:20 UTC, aruniverse commented
Great news! [@types/react-beautiful-dnd@12.1.0](https://www.npmjs.com/package/@types/react-beautiful-dnd/v/12.1.0) has been published.

2021-08-20 09:51 UTC, silviuaavram commented
I have one question about this line:
```tsx
getContainerForClone?: () => React.ReactElement<HTMLElement>;
```

In https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/guides/reparenting.md#droppable---getcontainerforclone it clearly says that it wants an HTMLElement, and I implemented it successfully by providing something similar to `() => document.getElementById('whatever')`. However, types yell that it wants a React.Element.

What do you think? Should these types get updated to reflect this? Should the Readme in the original library be updated according to these types? And if yes, then what's the workaround suggested instead of `document.getElementById`.

Thanks!