Add types for react-query
DefinitelyTyped/DefinitelyTyped pull request #40312
Opened 2019-11-11 19:56 UTC by lukaszfiszer

This PR includes typings for react-query package (npm: https://www.npmjs.com/package/react-query, github: https://github.com/tannerlinsley/react-query).

The package author does not plan to provide types to do the package - as discussed with https://github.com/tannerlinsley/react-query/issues/23.  

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-11-11 20:07 UTC, tannerlinsley requested changes

2019-11-11 20:07 UTC, tannerlinsley commented on types/react-query/index.d.ts
> +    pagination?: boolean;
This should be paginated

2019-11-11 20:07 UTC, tannerlinsley commented on types/react-query/index.d.ts
> +}
Add clearQueryCache method

2019-11-11 22:38 UTC, lukaszfiszer commented on types/react-query/index.d.ts
> +    pagination?: boolean;
Fixed

2019-11-11 22:38 UTC, lukaszfiszer commented on types/react-query/index.d.ts
> +}
Added

2019-11-11 23:00 UTC, tannerlinsley approved these changes

2019-11-12 23:50 UTC, merged

2019-11-12 23:50 UTC, PranavSenthilnathan commented
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!