feat: [@redux-form] Add includes in array fields.
DefinitelyTyped/DefinitelyTyped pull request #40321
Opened 2019-11-12 09:10 UTC by shenghou

Add includes function in redux-form fields  interface.

2019-11-12 10:00 UTC, bwlt reviewed
I cannot find any reference in the documentation. Can you provide some urls with the description of this field? (or a link to the source code)

2019-11-12 10:31 UTC, shenghou commented
> I cannot find any reference in the documentation. Can you provide some urls with the description of this field? (or a link to the source code)

Oh, Just I want to add this type definition. I found `fields.includes(xxx)` was used in some project, when update to ts, need to use `fields.getAll().includes(xxxx)`, so I want to add this function.

2019-11-12 11:03 UTC, bwlt commented
@shenghou but I cannot find any reference on the [redux-form codebase](https://github.com/redux-form/redux-form/blob/v7.4.2/src/createFieldArrayProps.js).
Are you really sure that you are working on the v7 version?
I've also created a POC but I cannot find it: https://codesandbox.io/s/funny-dijkstra-yuytm?fontsize=14

2019-11-12 11:13 UTC, shenghou commented
@bwlt Thank you for your review, maybe I need to add a PR for redux-form 😄

2019-11-12 11:31 UTC, bwlt commented
you are welcome 😉

2019-11-18 22:10 UTC, sheetalkamat requested changes
From the discussion here its not clear if this change is correct Blocked on signoff from one of the owners

2019-11-19 01:52 UTC, closed without merging