Added typing for string-placeholder
DefinitelyTyped/DefinitelyTyped pull request #40373
Opened 2019-11-14 10:17 UTC by iTsFILIPOficial

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
-  [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-11-14 21:47 UTC, PranavSenthilnathan requested changes

2019-11-14 21:47 UTC, PranavSenthilnathan commented on types/string-placeholder/index.d.ts
> +export as namespace template;
I don't this module exports a global so this line isn't needed.

2019-11-15 16:01 UTC, demensky requested changes

2019-11-15 16:01 UTC, demensky commented on types/string-placeholder/string-placeholder-tests.ts
> +
Please add a case with an object.

```suggestion

template('${foo} test ${bar}', {foo: 'Bob', bar: '65'});

```

2019-11-15 16:21 UTC, iTsFILIPOficial commented on types/string-placeholder/index.d.ts
> +    clean?: boolean | Readonly<[]>;
@demesky https://github.com/crysalead-js/string-placeholder/blob/master/index.js#L25

2019-11-15 16:32 UTC, demensky commented on types/string-placeholder/index.d.ts
> +    clean?: boolean | Readonly<[]>;
@iTsFILIPOficial. I agree with the comments mentioned array. But in the source code, it is used only as a boolean value. I can’t even find a spec where an array is passed to `clean`.

2019-11-15 17:28 UTC, demensky approved these changes

2019-11-16 00:36 UTC, PranavSenthilnathan requested changes

2019-11-16 00:36 UTC, PranavSenthilnathan commented on types/string-placeholder/index.d.ts
> +export default template;
```suggestion
export = template;
```

2019-11-19 23:54 UTC, PranavSenthilnathan approved these changes

2019-11-19 23:54 UTC, merged

2019-11-19 23:54 UTC, PranavSenthilnathan commented
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!