[jws] Allow JOSE headers to be string[], number or undefined
DefinitelyTyped/DefinitelyTyped pull request #40561
Opened 2019-11-21 16:50 UTC by grzegorzjudas

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/brianloveswords/node-jws
- [x] ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~ Fixes existing version types
- [x] ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.~ no substantial changes

2019-11-21 17:26 UTC, JustinBeckwith approved these changes

2019-11-21 17:50 UTC, grzegorzjudas commented
@JustinBeckwith I've specified the header properties in more depth according to that RFC. Was forced to do that when I wanted to use "jwk" property that turned out to be an object (see: [RFC7517 4.1.3](https://tools.ietf.org/html/rfc7515#section-4.1.3) that describes it as having multiple properties itself).

That, plus allowing custom (private) parameters, as [RFC7515 4.3](https://tools.ietf.org/html/rfc7515#section-4.3) describes.

2019-11-22 16:31 UTC, sheetalkamat requested changes

2019-11-22 16:31 UTC, sheetalkamat commented on types/jws/index.d.ts
> +} & CertificateProperties & {
Instead of using intersection type here, i would recommend use `export interface Header extends CertificateProperties` instead

2019-11-22 18:00 UTC, merged