Added jqwidgets TypeScript definitions
DefinitelyTyped/DefinitelyTyped pull request #40765
Opened 2019-12-02 09:21 UTC by DimitarD

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2019-12-10 19:40 UTC, orta commented
Hi, given that this comes form the jqwidgets team is there a reason why the d.ts files are not shipped with the library and then will be accurate to the version on npm?

2019-12-11 06:18 UTC, DimitarD commented
The d.ts file is actually included in our npm package (jqwidgets-scripts). However, we would like for it to be featured here too, this repository being an exhaustive list of TypeScript type definitions.

2019-12-20 07:11 UTC, DanielRosenwasser requested changes

2019-12-20 07:11 UTC, DanielRosenwasser commented on types/jqwidgets/index.d.ts
> +// Type definitions for jqwidgets-scripts
Looks like our lint rules are disabled for this package. Can you enable the lints in our `tslint.json` and fix up the version string to be a `MAJOR.MINOR` version (e.g. `8.3`)?

Also, it looks like this containing folder was incorrectly named. jqwidgets doesn't exist on npm, but jqwidgets-scripts does.

2019-12-20 07:12 UTC, DanielRosenwasser commented
> The d.ts file is actually included in our npm package (jqwidgets-scripts). However, we would like for it to be featured here too, this repository being an exhaustive list of TypeScript type definition

I see; however, that's not the purpose of DefinitelyTyped. DefinitelyTyped exists to fill the gap for packages that don't contain `.d.ts` files. Thanks for taking the time though.

2019-12-20 07:12 UTC, closed without merging