mongoose-paginate-v2: support read opts
DefinitelyTyped/DefinitelyTyped pull request #40763
Opened 2019-12-02 08:56 UTC by ChazEpps

…des from which to read.

Please fill in this template.

- [v] Use a meaningful title for the pull request. Include the name of the package modified.
- [v] Test the change in your own code. (Compile and run.)
- [v] Add or edit tests to reflect the change. (Run with `npm test`.)
- [v] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [v] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [v] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [v] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ChazEpps/mongoose-paginate-v2/commit/9bd165499062be113b2e9359a84e50bb2a7ffba5
- [v] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2019-12-02 10:03 UTC, oktapodia requested changes
Thank you for your PR, looks good but [this](https://github.com/aravindnc/mongoose-paginate-v2/pull/56) needs to be merged first

2019-12-02 10:03 UTC, oktapodia commented
Related to https://github.com/aravindnc/mongoose-paginate-v2/pull/56

2019-12-02 10:09 UTC, ChazEpps commented
@okamiconcept  Thank you for your Review 😄 
Yes, I'm waiting for merge. I'll let you know when the merge is complete.

2019-12-03 15:00 UTC, ChazEpps commented
https://github.com/aravindnc/mongoose-paginate-v2/pull/56

@oktapodia p/r merged!

2019-12-03 15:04 UTC, oktapodia approved these changes

2019-12-03 15:04 UTC, oktapodia commented
Thank you for your PR

2019-12-06 06:32 UTC, ChazEpps commented
@horiuchi Thank you for your review 😸

2019-12-10 20:16 UTC, orta commented
Looks good 👍

2019-12-10 20:16 UTC, merged