[airtable] Update definitions for version 0.8
DefinitelyTyped/DefinitelyTyped pull request #40875
Opened 2019-12-06 15:10 UTC by samtgarson

[airtable] Update definitions for version 0.8

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: [airtable.js](https://github.com/Airtable/airtable.js/tree/master/lib)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. 
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-12-06 15:10 UTC, samtgarson commented
I believe @EvanHahn is the maintainer on this 🙌

2019-12-06 15:28 UTC, EvanHahn requested changes
Rejecting just because I have a couple of questions:

First, this change seems to update nearly every line in the type definitions and the tests, including updates to code style. What's the motivation for such a big change?

Second, could these changes be split up into smaller ones for easier review, clearer history, and less risk?

2019-12-06 15:49 UTC, samtgarson commented
Thanks for the review @EvanHahn, fair comments.

The test formatting change was because some clauses were wrapped in `{}`, which seemed unconventional to me—so it's just a de-indentation, although I admit the Github diff makes this hard to see.

The big-ish changes to the declaration file were also because the format seemed unconventional:
- `declare global` doesn't seem super appropriate here
- `interface` has been used for objects that are actual classes in the real library
- the test imports using `import * as Airtable from 'airtable'`, which doesn't actually work with the real library—the default export of the lib is a function and you can import the other named exports.

Hence I decided to make some changes which aren't that substantial but in a git diff do appear significant (I don't think there's any actual code style changes other than the `{}` in the test, but maybe I let some bias slip in so please let me know if you see something specific)

I have been using these types on a personal project for a while and it's all ok—but I will attempt break this into separate commits to make things a little easier to review.

All this to say—I'm fairly new to Typescript so I may have some core misunderstandings which I'm happy to be corrected on 😅

2019-12-07 15:50 UTC, samtgarson commented
@EvanHahn I've broken this into two commits, and also put the definitions back in their original order which should make it clearer what's actually changed.

2019-12-10 17:34 UTC, EvanHahn requested changes
Didn't do a very thorough review, but left a few comments.

Also, as an aside: will this break anyone who is using the existing types? In other words, will they need to change their type imports? If so, what is DefinitelyTyped's process here?

2019-12-10 17:34 UTC, EvanHahn commented on types/airtable/index.d.ts
> +// Type definitions for airtable 0.8
Should this specify an exact version?

2019-12-10 17:34 UTC, EvanHahn commented on types/airtable/index.d.ts
> +    base(appId: string): baseCreateFunctor;
Should this return a `Base` instead?

2019-12-10 17:34 UTC, EvanHahn commented on types/airtable/index.d.ts
> +export type baseCreateFunctor = (tableName: string) => Table;
Does this type need to be exported?

In general, I think we might be exporting more things than need exporting. What do you think?

2019-12-10 17:34 UTC, EvanHahn commented on types/airtable/index.d.ts
> +export interface AirtableOptions {
1. Does this need to be exported?
1. I believe `apiKey` should be required.
1. The `allowUnauthorizedSsl` option was removed in v0.8.0, so it should be removed here.

2019-12-10 17:34 UTC, EvanHahn commented on types/airtable/index.d.ts
> +export class Base {
Users aren't really meant to instantiate this themselves. Could we remove the export (or maybe mark the constructor as private, if TypeScript allows such a thing)?

The same comment applies to `Table` and `Record`.

2019-12-10 17:34 UTC, EvanHahn commented on types/airtable/index.d.ts
> +export class Error {
Internally, this is a class called `AirtableError`. Why was this renamed to `Error` here?

2019-12-17 18:37 UTC, closed without merging