Avoid error when dynamically generating routes
DefinitelyTyped/DefinitelyTyped pull request #40900
Opened 2019-12-07 22:57 UTC by mcaneris

This is supposed to avoid throwing an error when the routes object is the return value of a function passing additional params, rather than creating it as an object.

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<<https://github.com/Paratron/hookrouter>>

2019-12-10 19:08 UTC, orta commented
This doesn't feel right to me - do you maybe mean `| string` to mean that it could also be a string?

2019-12-20 06:45 UTC, DanielRosenwasser requested changes

2019-12-20 06:45 UTC, DanielRosenwasser commented on types/hookrouter/index.d.ts
> +	interface RouteObject { [key: string]: (params: QueryParams & string) => any; }
This is an impossible type - what does this even mean?

2019-12-20 15:21 UTC, mcaneris commented
This was a patch request that unfortunately I didn't have time to fully review, which is my bad. 

I still don't have the necessary time to delve into this, so I'll hopefully revisit this in the future. Closing for now.

2019-12-20 15:21 UTC, closed without merging