[@types/node] Add close event to FSWatcher
DefinitelyTyped/DefinitelyTyped pull request #40912
Opened 2019-12-09 08:29 UTC by JIACHENG9

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes.

> Event: 'close'#
Added in: v10.0.0
Emitted when the watcher stops watching for changes. The closed fs.FSWatcher object is no longer usable in the event handler.

https://nodejs.org/dist/latest-v13.x/docs/api/fs.html#fs_event_close
https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_event_close
https://nodejs.org/dist/latest-v11.x/docs/api/fs.html#fs_event_close
https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_event_close

2019-12-09 09:33 UTC, SimonSchick approved these changes

2019-12-09 09:43 UTC, galkin requested changes
@JIACHENG9, thank you for your work!
Could you remove changes at Node.js v11. We don't update definitions for EOL versions.

2019-12-09 09:59 UTC, JIACHENG9 commented
> Could you remove changes at Node.js v11.

@galkin, Done

2019-12-09 10:01 UTC, Flarna approved these changes

2019-12-09 10:02 UTC, galkin requested changes
@JIACHENG9, you have removed v10 too, but Node.js v10 will be supported until April 2021. V11 is already EOL. More details here https://github.com/nodejs/Release#end-of-life-releases

Please revert back changes v10

2019-12-09 10:10 UTC, JIACHENG9 commented
https://github.com/nodejs/Release#end-of-life-releases

@galkin, Done

2019-12-09 10:12 UTC, galkin approved these changes

2019-12-09 12:37 UTC, r3nya approved these changes

2019-12-09 12:56 UTC, JIACHENG9 commented
@galkin The problem of ci error seems to have nothing to do with this pr. Could you re-run ci?

2019-12-09 12:57 UTC, galkin commented
@JIACHENG9, i can not, but you can reopen the pull. If problem will be happen again, then we will ask TS core team member to merge with red test or help with fix.

2019-12-10 19:17 UTC, orta commented
Looks like travis was having issues responding back to GitHub. It's green though, which is enough for me.

2019-12-10 19:17 UTC, merged