Node: `UrlObject`: omit `path`
DefinitelyTyped/DefinitelyTyped pull request #40939
Opened 2019-12-10 11:24 UTC by OliverJAsh

Incorrect:

```ts
url.format({ path: '/foo?a=b' })
// => ''
```

Correct:

```ts
url.format({ pathname: '/foo', search: '?a=b' })
// => '/foo?a=b'
```

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://devdocs.io/node/url#url_url_format_urlobject
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2019-12-10 12:26 UTC, islishude requested changes
see https://nodejs.org/dist/latest-v12.x/docs/api/url.html#url_urlobject_path

2019-12-10 12:30 UTC, OliverJAsh commented
@islishude IIUC, `path` exists on the _output_ of `url.parse`, but it is never used as a parameter inside of `url.format`. In that case, `search` and `pathname` must be used instead.

The `UrlObject` type in this project reflects the latter part only, as indicated by the comment immediately above the type.

For that reason I think `path` should be considered an invalid parameter and thus removed from the `UrlObject` type?

If `UrlObject` is used in more places than just the input of `url.format`, then we need a separate type.

2019-12-10 12:41 UTC, islishude commented
url.format accepts [url.URL class](https://nodejs.org/dist/latest-v12.x/docs/api/url.html#url_the_whatwg_url_api) instead of [url. urlObject](https://nodejs.org/dist/latest-v12.x/docs/api/url.html#url_legacy_url_api)

2019-12-10 12:42 UTC, islishude commented
FYI 
https://github.com/nodejs/node/blob/525fd9ca7c6146d15b4f73dcdb3854b9c63e8fbb/lib/url.js#L536

2019-12-10 12:44 UTC, OliverJAsh commented
That's not what it says here: https://devdocs.io/node/url#url_url_format_urlobject

I think you're talking about a different thing under the same name: https://devdocs.io/node/url#url_url_format_url_options

2019-12-10 20:36 UTC, galkin requested changes
Thank you for your pull. According my tests and checking documentation https://nodejs.org/dist/latest-v12.x/docs/api/url.html#url_url_format_urlobject
url.format doesn't work with `path`. `pathname` should be used.

2019-12-10 20:36 UTC, galkin commented on types/node/node-tests.ts
> +        // TODO: why won't this work?
Please remove this comment

2019-12-10 20:36 UTC, galkin commented on types/node/url.d.ts
> -        path?: string | null;
Please add similar change  to node v10

2019-12-11 11:38 UTC, OliverJAsh commented on types/node/test/url.ts
> +import assert = require("assert");
I had to move the tests here to workaround https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40967

2019-12-11 11:38 UTC, OliverJAsh commented on types/node/test/url.ts
> +    url.format({ path: '/foo' });
This is the only new test

2019-12-11 11:47 UTC, OliverJAsh commented
@galkin Done

2019-12-11 11:52 UTC, galkin requested changes

2019-12-11 11:52 UTC, galkin commented on types/node/v11/test/url.ts
> +url.format({ path: '/foo' });
We don't update EOL version. v11 is EOL. Please remove this changes.

2019-12-11 11:52 UTC, galkin commented on types/node/v11/tsconfig.json
> -        "test/zlib.ts"
The same.

2019-12-11 11:52 UTC, galkin commented on types/node/v11/url.d.ts
> -        path?: string;
The same.

2019-12-11 12:37 UTC, galkin approved these changes

2019-12-17 14:43 UTC, islishude approved these changes

2019-12-18 19:36 UTC, trivikr approved these changes

2019-12-20 06:43 UTC, DanielRosenwasser commented
The slowdown is likely a fluke - maybe we should re-run tests. Any easy way to do that @sandersn? Also, would be nice if there didn't need to be a new file to work around that linked issue.

2019-12-20 12:14 UTC, OliverJAsh commented
@DanielRosenwasser Merged master in so that should force the tests to re-run 🤞

2019-12-20 16:28 UTC, r3nya approved these changes

2019-12-23 16:19 UTC, andrewbranch commented
Merge conflicts ☹️

2019-12-26 16:56 UTC, merged