expect-puppeteer: Added "default options" functions
DefinitelyTyped/DefinitelyTyped pull request #40973
Opened 2019-12-11 17:24 UTC by minusfive

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - https://github.com/smooth-code/jest-puppeteer/tree/master/packages/expect-puppeteer#configure-default-options
  - https://github.com/smooth-code/jest-puppeteer/blob/master/packages/expect-puppeteer/src/options.js
  - https://github.com/smooth-code/jest-puppeteer/commits/master/packages/expect-puppeteer/src/options.js

---

This PR adds missing definitions for [`expect-puppeteer`](https://github.com/smooth-code/jest-puppeteer/tree/master/packages/expect-puppeteer#configure-default-options)'s default options configuration functions.

2019-12-11 17:45 UTC, minusfive commented
Ping @gregberge in case you want to review?

2019-12-11 19:45 UTC, tkrotoff requested changes
.

2019-12-11 19:46 UTC, tkrotoff approved these changes
Nice!

2019-12-13 10:45 UTC, orta commented
I'm a little worried about the change for: `export = expectPuppeteer` to `export default expectPuppeteer;` - which will break builds for imports. 

Are you sure that's what you want to do?

2019-12-13 12:53 UTC, minusfive commented
@orta right. I'm used to most projects nowadays automatically handling conversion from CJS to ESM. Since TS only allows 1 "=" export, I'm not clear on how to do it, but will dig into it. Perhaps as keys of the parent interface? Will update PR as soon as I'm back at comp.

2019-12-20 06:26 UTC, DanielRosenwasser requested changes

2019-12-20 06:26 UTC, DanielRosenwasser commented on types/expect-puppeteer/index.d.ts
> +export default expectPuppeteer;
This package was declared using `module.exports = ...` or some variant. It should be declared with an `export = ...` like one of the following:

### Variables

```ts
declare var xyz: SomeType;

export = xyz;
```

### Classes

```ts
class Foo {
  // ...
}

export = Foo
```

### Functions

```ts
function foo(): any;

export = foo;
```

To import the entity using a default import, you will need to enable `esModuleInterop`. Alternatively, you can just import using a more appropriate syntax like

```ts
import foo = require("foo");
```

[See more here in the FAQ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f9f6430117d025aef62ed56128deb65508edc86/README.md#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default).

2019-12-27 06:26 UTC, closed without merging