Lodash: add _.camelCase string array support
DefinitelyTyped/DefinitelyTyped pull request #41002
Opened 2019-12-12 21:29 UTC by mouadennaciri

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://lodash.com/docs/4.17.15#camelCase>

2019-12-12 21:33 UTC, mouadennaciri commented on types/lodash/lodash-tests.ts
> +        _(dictionary).transform(iterator, accumulator); // $ExpectType LoDashImplicitWrapper<Dictionary<AbcObject>>
Fix a strange error when I run `npm run lint lodash`
```
The 'use-default-type-parameter' rule threw an error in '.../DefinitelyTyped/types/lodash/lodash-tests.ts':
TypeError: Cannot read property 'default' of undefined
```

2019-12-13 08:02 UTC, thorn0 commented
As per the docs the parameter is `string`. While it indeed works for `string[]` too because Lodash calls `.toString()` on the argument, generally we don't add undocumented signatures to the type definitions.

2019-12-13 18:44 UTC, thorn0 requested changes
As per the docs the parameter is string. While it indeed works for string[] too because Lodash calls .toString() on the argument, generally we don't add undocumented signatures to the type definitions.

So I don't think this PR can be merged.

2019-12-14 11:51 UTC, mouadennaciri commented
> As per the docs the parameter is string. While it indeed works for string[] too because Lodash calls .toString() on the argument, generally we don't add undocumented signatures to the type definitions.
> 
> So I don't think this PR can be merged.

@thorn0 According to the docs _.camelCase can take a string array.

> Arguments
> [string=''] (string): The string to convert.

[_.parseInt](https://lodash.com/docs/4.17.15#parseInt) is for example a utility which takes only string.

> Arguments
> string (string): The string to convert.

2019-12-14 12:56 UTC, thorn0 commented
It's not a string array, this notation means that it's an optional parameter.

2019-12-14 13:04 UTC, mouadennaciri commented
> It's not a string array, this notation means that it's an optional parameter.

@thorn0 You're right, ok I close the PR.

2019-12-14 13:08 UTC, closed without merging