[types/cesium/index.d.ts] added 'fromCartesian' in Cryptographic types definition
DefinitelyTyped/DefinitelyTyped pull request #41142
Opened 2019-12-19 07:49 UTC by UsamaMehmood

Please fill in this template.

- [Done] Use a meaningful title for the pull request. Include the name of the package modified.
- [Done] Test the change in your own code. (Compile and run.)
- [Done] Add or edit tests to reflect the change. (Run with `npm test`.)
- [Done] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [Done] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [Done] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [True] The package does not already provide its own types, or cannot have its `.d.ts` files generated.

2019-12-19 18:42 UTC, szechyjs requested changes

2019-12-19 18:42 UTC, szechyjs commented on types/cesium/index.d.ts
> +    let BingMapsApi: {defaultKey: string};
these are not type definitions.

2020-01-14 03:16 UTC, Crocsx commented
@UsamaMehmood can you check the merge conflict ?

2020-01-17 08:01 UTC, UsamaMehmood commented
Hi @Crocsx, I have fixed the merge conflict, you can proceed. Thanks.

2020-01-20 01:25 UTC, Crocsx approved these changes

2020-03-02 03:24 UTC, Crocsx commented
@UsamaMehmood I do not have the merge right as it is automated. Some owner merge got executed before your. There are still have conflict to fix.

2020-03-02 03:29 UTC, Crocsx commented
BTW, I just noted that I added this in another PR

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42113/files

so I guess this can be closed

2020-03-02 03:30 UTC, Crocsx requested changes
can be closed https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42113

2020-03-09 02:31 UTC, closed without merging