sinon - defined SinonSpy.wrappedMethod
DefinitelyTyped/DefinitelyTyped pull request #41219
Opened 2019-12-23 19:40 UTC by NoamDev

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.

- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2019-12-23 19:43 UTC, NoamDev commented
Based on sinonjs/sinon#988.
Note that this feature is not yet documented but I made an issue for that here: sinonjs/sinon#2182

2019-12-24 11:28 UTC, 43081j commented on types/sinon/ts3.1/index.d.ts
> +         * Get the original method. Only available if the spy replaced an existing method, but not a property.
are you sure this is true? if you spy on an accessor (i.e a property), the wrapped accessor would have a wrappedMethod wouldn't it?

as in:

```
const spy = sinon.spy(obj, 'prop', ['get']);
spy.get.wrappedMethod;
```

2020-01-03 00:47 UTC, RyanCavanaugh requested changes
If it's not documented in a project with otherwise comprehensive documentation, it's likely not intended to be used. Please reopen when they actually document the method for public use.

2020-01-09 08:09 UTC, NoamDev commented
I'm closing it by myself 'cause  I'm tired from all the notifications.
Anyway. Let's wait to see whther or not sinon will document that feature

2020-01-26 16:40 UTC, mroderick commented
The PR for Sinon has been merged, it is not yet documented on the website (because updates there are tied to releases ... for legacy reasons that I'll be addressing soon), but it is visible in `master`.

Is that enough to unblock the work here?

2020-01-27 13:29 UTC, closed without merging

2020-01-27 16:13 UTC, 43081j commented
bleh

@RyanCavanaugh  mind taking a look? bot will keep closing it i imagine

2020-01-31 18:44 UTC, mroderick commented
That bot is keen! Perhaps I need to install that on a few repositories ...