expect-puppeteer: Adding delay to ExpectTimingActions
DefinitelyTyped/DefinitelyTyped pull request #41355
Opened 2020-01-02 22:08 UTC by jfm710

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. 
(not bringing the whole thing up to date)
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

Docs:
https://github.com/smooth-code/jest-puppeteer/tree/master/packages/expect-puppeteer#toFill

2020-01-08 23:22 UTC, armanio123 requested changes
I noticed a couple of discrepancies between the documentation and the `d.ts`. I'm not very familiar with the library so let me know if they make sense.

2020-01-08 23:22 UTC, armanio123 commented on types/expect-puppeteer/expect-puppeteer-tests.ts
> +    await expect(instance).toMatch("selector", { delay: 100 });
Documentation doesn't show delay as part of the `toMatch` options.

2020-01-08 23:22 UTC, armanio123 commented on types/expect-puppeteer/expect-puppeteer-tests.ts
> +    await expect(instance).toSelect("selector", "valueOrText", { delay: 100 });
`toSelect` doesn't have an options parameter.

2020-01-08 23:22 UTC, armanio123 commented on types/expect-puppeteer/expect-puppeteer-tests.ts
> +    await expect(instance).toUploadFile("selector", "filePath", { delay: 100 });
`toUploadFile` doesn't have an options parameter.

2020-01-15 02:02 UTC, jfm710 commented
Pulled test not in docs and opened another pr for a full 4.4 update
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41604

2020-01-15 19:12 UTC, armanio123 commented
> Pulled test not in docs and opened another pr for a full 4.4 update
> #41604

It's not only the test. What I meant to say, is that `delay` is available as part of those methods but I don't think that's correct. I definition should be fixed to the right signature.

2020-01-16 02:23 UTC, jfm710 commented
Ahh, I didn't want to break anyone using this for 3.3 but add the delay. Probably should just close this one in favor the full 4.4 update

2020-01-21 04:39 UTC, closed without merging