Adds existing npm lib multicodec + tests
DefinitelyTyped/DefinitelyTyped pull request #41404
Opened 2020-01-05 07:22 UTC by carsonfarmer

Signed-off-by: Carson Farmer <carson.farmer@gmail.com>

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2020-01-05 07:23 UTC, carsonfarmer commented on types/multicodec/index.d.ts
> +export * from './constants';
Could this 'feature' be better represented using a namespace?

2020-01-07 01:59 UTC, armanio123 requested changes
I think `multicodec` also provides a global value. See https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#global-libraries for details on how to represent this.

2020-01-07 01:59 UTC, armanio123 commented on types/multicodec/index.d.ts
> +// Project: https://github.com/multiformats/js_multicodec#readme
There's a typo. `js_multicodec` to `js-multicodec`

2020-01-10 05:45 UTC, carsonfarmer commented
Typo fixed, good catch!

> I think `multicodec` also provides a global value. See https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#global-libraries for details on how to represent this.

Maybe I'm missing something, but I don't see any evidence of this? The `aegir build` script produces a webpack umd, but doesn't look like there are any globals available..? Could you point me to where I might find this?

2020-01-10 22:33 UTC, armanio123 commented
> Maybe I'm missing something, but I don't see any evidence of this? The aegir build script produces a webpack umd, but doesn't look like there are any globals available..? Could you point me to where I might find this?

Here's documentation of `multicodec` used on the on the browser: https://multiformats.github.io/js-multicodec/

If you check file https://unpkg.com/multicodec@1.0.0/dist/index.js, line 9:
```
root["Multicodec"] = factory();
```
That's where the global variable is being assigned.

2020-01-11 08:14 UTC, carsonfarmer commented
Ah I see, thanks @armanio123, I didn't read that initial link you posted properly. My apologies, yes you are right, and I think the added `export as namespace Multicodec` should cover it. Though it wasn't clear to me how best to 'test' this?

2020-01-13 21:48 UTC, armanio123 commented
> Though it wasn't clear to me how best to 'test' this?
Since you're declaring a global variable by exporting the namespace, you should be able to access it's properties en methods just by using `Multicodec` on the test file (no import require).

2020-01-13 23:46 UTC, carsonfarmer commented
Cool, so that's great. But is it only available globally in a browser context? If I look at the `"main"` entry in the `package.json` I see `"src/index.js"`, which does not have anything exported globally. Is this still 'ok' from a ambient types perspective? Apologies for my ignorance here, this is apparently the first package that has a global export that I've written types for 😬.

So I guess my final question here is, is it misleading to have globally exported types in say a NodeJS context? I see that if I _do_ include the import, this masks the global value, which makes sense. However, in NodeJS, if I _don't_ import the package, I _won't_ actually have it in my global namespace...

2020-01-14 01:36 UTC, armanio123 commented
>So I guess my final question here is, is it misleading to have globally exported types in say a NodeJS context? I see that if I do include the import, this masks the global value, which makes sense. However, in NodeJS, if I don't import the package, I won't actually have it in my global namespace...

I can see how this is confusing, but that's how umd modules work. It would be up to the developer to understand the library and decide the best implementation. As you correctly stated, in the case of a NodeJs environment, you require specify the import. For the case of the browser you must reference the global library by using a `script` block (I think the author documented this to be on the `dist` folder) and make the global variable available.

Btw for test purposes both scenarios should be ok. You can either decide to import or use the global scope. I'll approve and merge the PR.

2020-01-14 01:37 UTC, armanio123 approved these changes

2020-01-14 01:37 UTC, merged

2020-01-14 05:52 UTC, carsonfarmer commented
Thanks so much for a) explaining this, super helpful, and b) approving and merging! Cheers @armanio123!