Added Plotly.js LayoutAxis property
DefinitelyTyped/DefinitelyTyped pull request #41437
Opened 2020-01-07 08:34 UTC by jacklaurencegaray

Added `autotick` property for `LayoutAxis`.

The existing definition lacks `autotick: boolean` as per the example defined in the [Plotly.js documentation](https://plot.ly/javascript/axes/)

2020-01-07 22:35 UTC, marnett-git requested changes
the tabbing needs to be aligned with the lines above. I think it's a 4-space tab.

2020-01-08 01:31 UTC, jacklaurencegaray commented
> the tabbing needs to be aligned with the lines above. I think it's a 4-space tab.

Done

2020-01-08 02:26 UTC, marnett-git approved these changes
looks good

2020-01-08 02:56 UTC, marnett-git approved these changes

2020-01-08 21:05 UTC, merged