Cavy/add focus types
DefinitelyTyped/DefinitelyTyped pull request #41474
Opened 2020-01-08 21:50 UTC by austinpgraham

Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [ x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pixielabs/cavy/pull/160/files
- [x ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-01-08 21:51 UTC, austinpgraham commented
@AbigailMcP Type definition PR!

2020-01-08 22:30 UTC, peterblazejewicz commented on types/cavy/index.d.ts
> +    focus(identifier: string): Promise<void>;
As this is a new api, can we amend the inline doc, like that one from the upstream change?
```text
Returns a promise, use await when calling this function.
Promise will berejected if the component is not found.
```

2020-01-08 22:32 UTC, peterblazejewicz commented
Note for mantainer, this change is not yet relased, would this require version change?
https://github.com/pixielabs/cavy/pull/160/files

2020-01-09 17:59 UTC, AbigailMcP commented
> Note for mantainer, this change is not yet relased, would this require version change?
> https://github.com/pixielabs/cavy/pull/160/files

This change is now released, and is a new feature i.e. minor bump to v3.2.0.

2020-01-09 18:06 UTC, AbigailMcP requested changes
@austinpgraham as per @peterblazejewicz comment, the Cavy version needs to be changed to cavy 3.2 at the top of `types/cavy/index.d.ts` to match the current release. Thanks!

2020-01-09 20:59 UTC, austinpgraham commented
@peterblazejewicz @AbigailMcP Done!

2020-01-09 21:10 UTC, peterblazejewicz approved these changes
LGTM
It's already released in 3.2:
https://cavy.app/docs/api/helpers#focusidentifier

2020-01-10 09:00 UTC, AbigailMcP approved these changes

2020-01-10 23:51 UTC, merged