[react-redux] useSelector can infer its return type with shallowEqual
DefinitelyTyped/DefinitelyTyped pull request #41540
Opened 2020-01-12 04:05 UTC by kazuma1989

Hi. I have an issue with a combination of `useSelector` and `shallowEqual` (described below). I'd like to fix the issue!

The return type of `useSelector` is perfectly inferred:

```ts
type State = { foo: string; };
const foo = useSelector((state: State) => state.foo);
// foo is string
```

But with `shallowEqual`, the return type is not inferred so it gets to be `any`:

```ts
const foo = useSelector((state: State) => state.foo, shallowEqual);
// foo is any
```

A minimal repro is here: https://github.com/kazuma1989/repro-shallowEqual-missing-types

@dt-bot

---
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/kazuma1989/repro-shallowEqual-missing-types
- [ ] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~
- [ ] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.~~

2020-01-21 17:25 UTC, Lazyuki requested changes

2020-01-21 17:25 UTC, Lazyuki commented on types/react-redux/react-redux-tests.tsx
> +
Can you add another test with a correctly inferred type just to be sure?

2020-01-23 16:46 UTC, Lazyuki approved these changes

2020-01-23 18:01 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2020-01-23 18:01 UTC, merged