Added "react-native" TVEventHandler class definition
DefinitelyTyped/DefinitelyTyped pull request #41709
Opened 2020-01-18 23:14 UTC by reallynotburner

React-Native provides a TVEventHandler class that works on Android and iOS.

Please fill in this template.

- [ X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X ] Test the change in your own code. (Compile and run.)
- [ X ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ X ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ X ] Provide a URL to documentation or source code which provides context for the suggested changes: `https://github.com/facebook/react-native/blob/72890965f34ecf87add998131b2c6a6fe3d54c8b/Libraries/Components/AppleTV/TVEventHandler.js`
- [ - ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ - ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-01-23 08:37 UTC, Naturalclar commented on types/react-native/index.d.ts
> +  enable(context: any, callback: Function): undefined;
is there a specific reason to use `undefined` instead of `void`?
```suggestion
  enable(context: any, callback: Function): void;
```

2020-01-23 08:38 UTC, Naturalclar commented on types/react-native/index.d.ts
> +  disable(): undefined;
```suggestion
  disable(): void;
```

2020-01-23 08:38 UTC, Naturalclar requested changes
@reallynotburner the change LGTM :)
made a few comments.
could you resolve the conflict and see my comments?

2020-01-28 13:22 UTC, alloy requested changes
Agreed with @Naturalclar’s review :+1:

2020-01-30 09:25 UTC, closed without merging