Add preset to State object
DefinitelyTyped/DefinitelyTyped pull request #41725
Opened 2020-01-20 00:39 UTC by nikuda

It's possible to use preset in the Stats objects itself as base to extend/enable other flags on:

https://webpack.js.org/configuration/stats/#statspreset

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-01-20 14:04 UTC, ofhouse requested changes
@nikuda Thanks for your PR!
The change you want to add seems to be a new option in webpack v5 which is **not** available in v4.

See v4 documentation of `Stats` object (no `preset` key is present):
- https://v4.webpack.js.org/configuration/stats/
- https://github.com/webpack/webpack/blob/v4.41.5/declarations/WebpackOptions.d.ts#L1242

vs v5 documentation (where the `preset` key is available):
- https://webpack.js.org/configuration/stats/#statspreset
- https://github.com/webpack/webpack/blob/v5.0.0-beta.12/declarations/WebpackOptions.d.ts#L1607

Since the header of the declaration file [refers to v4](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f0260dd21f463b22a44d8cf2aa47e3460ac6a9c8/types/webpack/index.d.ts#L1) I think it is not a good idea to add it to the v4 branch.
Since v5 is in beta right now I guess it makes sense to start a v5 version of this declaration file?
 
I'll take a look what it takes to create a v5 declaration (We need to make sure that it don' t get simply overridden, because there are many v4 users out there) version file later today, but if you do not want to wait you can also go ahead and modify it by yourself & update the PR.

2020-01-20 17:07 UTC, ofhouse commented
@nikuda I created a PR #41736 which introduces a way to add types for the upcoming v5 release of webpack.
The PR also adds the changes you requested here as an example case so hopefully you are not to worried that I hijacked your PR for this 🤗

2020-01-25 16:33 UTC, ofhouse commented
@nikuda This is now fixed in [`@types/webpack@4.41.3`](https://www.npmjs.com/package/@types/webpack):

```ts
import { Configuration } from 'webpack';
import {} from 'webpack/next';

const config: Configuration = {
  stats: {
    preset: 'none',
  },
};
```

2020-01-27 14:26 UTC, closed without merging

2020-01-28 05:08 UTC, nikuda commented
Sorry for the late reply @ofhouse, thanks for doing that, looks good to me 👍