[humps] Change order of function typing to support spread
DefinitelyTyped/DefinitelyTyped pull request #41750
Opened 2020-01-21 04:22 UTC by zprime0920

Array is regarded as Object,
so type of functions are inferred to function returning Object.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
[AS IS](https://www.typescriptlang.org/play/#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzCgFsQIsAvEAaRAE8AKAZwxgC54B5AIwCtwMAlO259MAKFCRYCFOmx4CxUhWp0mLYb34BtALpDOWzHrFiweZgXgBeRSTKUaDAN4BfAfAD0nw6IxmLDHhgGztlRzU9D29ffiA)
[TO BE](https://www.typescriptlang.org/play/?ssl=5&ssc=38&pln=1&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXzCgFsQIsAvEAaRAE8AKAZwxgC54B5AIwCtwMA2gF0AlO259MwgFChIsBCnTY8BYqQrU6TFuN78xnfZmnSweZgXgBeNSTKUaDAN4BfEfAD0no5IxmLDHhgGzsNR21hD29ffmEgA)

2020-01-21 08:35 UTC, nikeee approved these changes

2020-01-21 08:35 UTC, nikeee commented
Good catch!

2020-01-21 17:54 UTC, uniqueiniquity requested changes
It seems like the recommended lint rules are disabled for this package (see humps/tslint.json).
Please at least re-enable the "dt-header" rule and the "ban-types" rule and fix any errors that may come up.
It would be great to re-enable other rules that have been disabled, but I realize that could be a lot of work.

2020-01-22 18:08 UTC, uniqueiniquity approved these changes

2020-01-22 18:08 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2020-01-22 18:08 UTC, merged