Mongoose: Strongly typed the paths of schema definitions
DefinitelyTyped/DefinitelyTyped pull request #41812
Opened 2020-01-23 14:23 UTC by bytenik

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://mongoosejs.com/docs/guide.html#definition
> Each key in our code blogSchema defines a property in our documents which will be cast to its associated SchemaType. For example, we've defined a property title which will be cast to the String SchemaType and property date which will be cast to a Date SchemaType.

2020-01-28 20:07 UTC, weswigham commented on types/mongoose/index.d.ts
> +  type SchemaDefinition<T> = {
Would you consider making it backwards compatible by adding a default, eg
```suggestion
  type SchemaDefinition<T = {[x: string]: unknown}> = {
```
?

2020-02-10 20:49 UTC, sandersn commented
I don't want to merge a change to such a popular package without some reviewers signing off.

 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @Vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps mind taking a look?

I'm having trouble understanding the change because I don't know how SchemaDefinition is used. And I can't tell if the test changes are the desired outcome of the change, or whether more tests are needed to show it.

2020-02-14 17:41 UTC, sandersn requested changes
requesting changes so the bot understands the PR status

2020-02-14 17:41 UTC, sandersn commented
@horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @Vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps 

can anybody take a look?

2020-02-20 18:43 UTC, bytenik commented
There's no changes requested, and, there's no current problems with this PR...

2020-02-20 19:17 UTC, sandersn commented
@bytenik No contributors have reviewed the change, and I don't want to merge a change to such a popular package without that.

@horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @Vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps mind taking a look?

Earlier, I had trouble understanding the change because I don't know how SchemaDefinition is used. And I can't tell if the test changes are the desired outcome of the change, or whether more tests are needed to show it.

2020-02-21 02:34 UTC, ToucheSir commented
Having dealt with gnarly generic-related issues in the mongoose typings before, I'm loathe to step in and make a definitive approve/reject decision without hearing from other folks on this. That said, it doesn't seem like any issues have been raised, and the fallout from having a stricter `SchemaDefinition` type wouldn't be too serious.

@bytenik could you add a test for `add(SchemaDefinition<T>, string)` as well on the `Animal` schema? I'd be comfortable with approving if that test also passes.

2020-02-21 18:43 UTC, bytenik commented
Abandoned? I was working on this change as requested. If you guys are not interested in contributions to this project, please just indicate that and I can move on.

2020-02-21 20:40 UTC, weswigham commented
Mmm the bot looks at commit time and not comment time, I guess. I can reopen, but you'll need to push a recent commit of some kind (rebase on latest?) to get the bot to stop closing it for a few weeks.

2020-02-22 01:34 UTC, closed without merging