[relay-runtime] update store `lookup` arg
DefinitelyTyped/DefinitelyTyped pull request #41920
Opened 2020-01-28 20:51 UTC by hellatan

allow `selector` arg to be same type returned from `getSelector`

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
Type returned from here:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/relay-runtime/lib/store/RelayModernSelector.d.ts#L49

- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-01-29 14:13 UTC, alloy requested changes
The current state of the types matches upstream. That is, [`getSelector` returns a `ReaderSelector`](https://github.com/facebook/relay/blob/597d2a17aa29d401830407b6814a5f8d148f632d/packages/relay-runtime/store/RelayModernSelector.js#L153), which is [a union of `SingularReaderSelector` and `PluralReaderSelector`](https://github.com/facebook/relay/blob/aa60b530d378910d88ba1a41499e6817ee0b370d/packages/relay-runtime/store/RelayStoreTypes.js#L74). If you think `lookup` should accept either, then please first PR a Flow change upstream so we can stay in sync.

2020-01-29 23:25 UTC, hellatan commented on types/relay-runtime/lib/store/RelayStoreTypes.d.ts
> +    lookup(selector: SingularReaderSelector | ReaderSelector): Snapshot;
@alloy should this really be `lookup(selector: ReaderSelector)` then if that `ReaderSelector` is a union of both `SingularReaderSelector` and `PluralReaderSelector`?

2020-01-30 00:00 UTC, hellatan commented
thanks for the guidance @alloy. Walking through the relay source code (instead of just looking at type def files), gives it a lot more clarity as to what's actually going on under the hood. I'm still a little confused as to how these types work within the relay package itself, but from what I was experiencing, I think I can solve this on my app level instead of needing to update these types defs.

2020-01-30 00:00 UTC, closed without merging

2020-01-30 12:21 UTC, alloy commented
Sounds good–happy to be of assistance 👍