fix(d3-axis): Allow use of scales with toString property
DefinitelyTyped/DefinitelyTyped pull request #41935
Opened 2020-01-29 07:04 UTC by robertmoura

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
---
Changing an existing definition
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/d3/d3-axis#axisTop
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.
---
I've changed the axis domain to allow any scale that has a `toString` domain to create an axis. This helps with previous typings for scales like the [ordinal scale](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-scale/index.d.ts#L1451). For example this was an error: 
```typescript
const bandScale = d3.scaleBand<{ toString(): string }>();

d3.axisLeft(bandScale); // Error here
```

2020-02-04 10:40 UTC, denisname commented
Will review it soon...

2020-02-10 17:56 UTC, denisname commented
The problem with the type `{toString (): string}` is that almost everything is of that type:

```typescript
let x: {toString(): string};

x = {};
x = 2;
x = false;
x = () => null;
x = new Object();
```

So, by expanding the type of `AxisDomain`, you have made it possible to write something like:

```typescript
declare let axis: d3.AxisScale<Function>;
d3.axisLeft(axis); // Should be an error
```

The simplest would be to do:

```typescript
const bandScale = d3.scaleBand()
    .domain(objs.map(_ => _.toString()))
    .range([0, width]);

d3.axisLeft(bandScale);
```

I am not convinced that adding
```typescript
export function scaleBand<Domain extends { toString(): string }>(): ScaleBand<Domain>;
```
in the type definition was a god idea in the first place.

2020-02-10 19:08 UTC, sandersn requested changes
requesting changes so the bot understands the status of the PR

2020-02-10 22:28 UTC, robertmoura commented
Yeah, I see what you mean. It does limit what you can do with the axis but I don't think it's worth the risk of allowing runtime errors.

Thanks @denisname ! I'll close this pull request.

2020-02-10 22:28 UTC, closed without merging