Fix: Animated Components are always any type
DefinitelyTyped/DefinitelyTyped pull request #41939
Opened 2020-01-29 08:49 UTC by zusinShinpei

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.
#40424

2020-01-29 13:54 UTC, alloy requested changes
This looks great, thanks 👌 

It would be great if you could add some test coverage that shows typical usage of these components doesn’t lead to any type errors.

2020-01-29 13:54 UTC, alloy commented on types/react-native/index.d.ts
> +    export function createAnimatedComponent<T extends React.FC | typeof React.Component>(component: T): AnimatedComponent<T>;
I wonder if this works too?

```suggestion
    export function createAnimatedComponent<T extends React.ComponentType>(component: T): AnimatedComponent<T>;
```

2020-01-29 13:54 UTC, alloy commented on types/react-native/index.d.ts
> +    export const SectionList: AnimatedComponent<SectionList>;
Nice 👌

2020-01-29 13:55 UTC, alloy commented
The CI failures look legit too.

2020-01-31 10:30 UTC, zusinShinpei commented
@alloy How can I use Recursive Type in DefinitelyTyped? I just try that but Travis CI needs Minimum TypeScript Version to lower than 3.7.

2020-01-31 14:08 UTC, alloy commented
Hmm, it seems a bit of a stretch to bump the requirement that high. Some googling turned up [this](https://stackoverflow.com/a/47842314), could that help for your case?

2020-01-31 14:16 UTC, zusinShinpei commented
@alloy I resolved that. can you approve this PR?

2020-01-31 16:28 UTC, alloy approved these changes

2020-01-31 16:28 UTC, alloy commented
Aha, great! Thanks 🙏

2020-01-31 16:28 UTC, merged

2020-02-11 15:13 UTC, jenshandersson commented
@zusinShinpei I'm getting this type error when setting `ref`. Am I doing something wrong or are the new types incorrect...?

<img width="715" alt="Screenshot 2020-02-11 at 15 08 37" src="https://user-images.githubusercontent.com/1150467/74249331-e6fdcf00-4ce0-11ea-82f5-be8d8446ab63.png">

2020-02-18 06:51 UTC, zusinShinpei commented
> @zusinShinpei I'm getting this type error when setting `ref`. Am I doing something wrong or are the new types incorrect...?
> 
> <img alt="Screenshot 2020-02-11 at 15 08 37" width="715" src="https://user-images.githubusercontent.com/1150467/74249331-e6fdcf00-4ce0-11ea-82f5-be8d8446ab63.png">

#42446

2020-07-17 13:54 UTC, zanona commented
I'm not sure if this is related but it looks that `Animated.*` props are not inferring the `data,sections` types as opposed to their original counterpart, for example: `FlatList.renderItem` and `Animated.FlatList.renderItem` 

```ts
<Animated.FlatList data={[1,2]} renderItem={a => <Text>{a}</Text>} />
```

    Parameter 'a' implicitly has an 'any' type.

While `a` is inferred from `data` on `FlatList`, as below: 

```ts
<FlatList data={[1,2]} renderItem={a => <Text>{a}</Text>} />
```

The same is happening for `keyExtractor`  and `renderSectionHeader` on `SectionList`

2020-07-20 12:57 UTC, alloy commented
@zanona Would you be able to create a PR with ideally the solution but if too complex otherwise at least the test cases that demonstrate the problem?