[webpack] Add RuntimeValue for DefinePlugin
DefinitelyTyped/DefinitelyTyped pull request #42036
Opened 2020-02-02 03:14 UTC by danielthank

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-02-02 07:24 UTC, johnnyreilly requested changes

2020-02-02 07:24 UTC, johnnyreilly commented on types/webpack/index.d.ts
> +        static runtimeValue(fn: ({ module }: { module: any }) => any, fileDependencies?: any[]): any;
Can we be more specific than `any` here?

2020-02-02 09:14 UTC, danielthank commented
@johnnyreilly I changed the types and tests to be more specific. Please review again!

2020-02-02 13:43 UTC, johnnyreilly requested changes

2020-02-02 13:43 UTC, johnnyreilly commented on types/webpack/index.d.ts
> +            exec(parser: any): CodeValuePrimitive;
Nice work! Can `parser` be absolutely anything?

2020-02-02 17:47 UTC, johnnyreilly approved these changes
Nice!

2020-02-02 19:20 UTC, merged

2020-02-04 07:43 UTC, fregante commented on types/webpack/index.d.ts
> +                fileDependencies?: string[]
This should be

```ts
fileDependencies?: true | string[]
```

https://github.com/webpack/webpack/blob/89c752411e9bd803401acf1b8402559dae4c6eea/lib/DefinePlugin.js#L30

2020-02-04 07:43 UTC, fregante commented on types/webpack/index.d.ts
> +                fn: ({ module }: { module: compilation.Module }) => CodeValuePrimitive,
`module` should have a `resource` property but doesn't:


```
webpack.config.ts:115:48 - error TS2551: Property 'resource' does not exist on type 'Module'. Did you mean '_source'?

115                     return JSON.stringify(path.basename(module.resource, '.tsx'));
                                                                   ~~~~~~~~

  node_modules/@types/webpack/index.d.ts:800:13
    800             _source: any;
                    ~~~~~~~
    '_source' is declared here.
```

This code has been working for a while

2020-02-04 07:44 UTC, fregante commented
Thank you for this PR @johnnyreilly!