sinon: allow specifying stub type parameters
DefinitelyTyped/DefinitelyTyped pull request #42042
Opened 2020-02-02 12:57 UTC by 43081j

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: N/A

---

Fixes #36436 

Its a bit of a pain having to specify `TObj` and `TKey` too but they are dependencies of the other two type params so we don't have much of a choice. Its better than now: not working at all.

So edge cases where the method can't be inferred can at least specify the type manually.

2020-02-02 14:47 UTC, 43081j commented
@DanTup @murkey @arkhamRejek would you mind letting me know your thoughts on this?

its not as ideal as it somehow magically understanding overloads but it at least means in the edge cases affected, you can specify the types to override the inference. 

```ts
// force the stub to have args [number]
sinon.stub<typeof myObject, 'myMethod', [number]>(myObject, 'myMethod');
```

2020-02-05 17:00 UTC, jessetrinity commented
You're listed as owner but I will give others more time to review before looking at this. Thanks!

2020-02-10 17:21 UTC, sandersn commented
@43081j Looks like other knowledgeable people haven't reviewed this. Want me to merge it anyway?

My opinion is that this is a dangerous change for a widely-used utility package. 

1. Adding a lot of conditional types means that performance may slow down unpredictably when used with large union types, like those from React.
2. Since the new usage is for explicit type arguments, that means type parameter inference has already failed. In that case we recommend casts anyway, since explicit type parameters are just a prettier hacky cast.

2020-02-11 10:51 UTC, 43081j commented
@sandersn i wouldn't merge it yet.

you have the same concerns i did. its kinda nice that it works and you can override the inferred types but its still something im not entirely sure about.

it didnt used to infer the types, so by introducing the type inference we broke a lot of builds (quite a while back now). the problem is when someone has overloads, the compiler can't possibly infer the type correctly so it'll pick one of many and often picks the one you didn't want.

for the overload situation, casting doesn't quite work because you can't make a stub in the first place. any idea what we can suggest/do for that?

2020-02-11 16:53 UTC, sandersn commented
The explicit `any` argument forces the compiler to use the first overload, or maybe the second? I think that's a decent solution if it doesn't happen very often. If a failure of inference is common, I'd embrace it and try to make to the explicit cast as simple as possible: probably by removing most of the overloads and type parameters and returning a kind of useless type that is easy to cast. Probably `unknown` or `never` are good candidates.

2020-02-12 09:12 UTC, 43081j commented
overloads on the thing you're stubbing, i meant. here's an example:

```ts
class Foo {
  bar(val: string): void;
  bar(val: number): void;
  bar(val: string|number): void {};
}

const obj = new Foo();
```

If we now do `sinon.stub(obj, 'bar')`, it'll try infer the args and return value. but because there are 3 possibilities, you can't infer the right one 2/3 of the times.

```ts
const stub = sinon.stub(obj, 'bar');
stub.calledWith(5); // it infers that the args to the method were [string] rather than [number]
```

So if we tell people to pass `any` (`sinon.stub<any>(obj, 'bar')`), it just means it will won't be able to infer so the args will also be `any[]`. They can then cast to the right type of stub.

Either works for me, guess its a question of slowness/complexity vs. usability. im not sure myself

2020-02-12 18:11 UTC, sandersn commented
Oh, that makes sense. It doesn't change my advice though. I'd go with instructions to add the cast. Basically, inference from overloads is not very good in the compiler, and the overall user experience will be better if users manually work around it instead of the package having complex code to work around it.

2020-02-14 17:17 UTC, sandersn requested changes
requesting changes so the bot understands the PR state

2020-02-21 17:28 UTC, closed without merging