SuperAgent: add toJSON methods
DefinitelyTyped/DefinitelyTyped pull request #42062
Opened 2020-02-03 11:50 UTC by morigs

Those declarations can be useful for `toJSON` method overriding. For that reason, we should return `object`.

https://github.com/visionmedia/superagent/pull/466
https://github.com/visionmedia/superagent/blob/a913704346d9477001820a063b3546f4de9e37be/lib/node/index.js#L972
https://github.com/visionmedia/superagent/blob/a913704346d9477001820a063b3546f4de9e37be/lib/node/response.js#L213

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/visionmedia/superagent/pull/466
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-02-03 12:31 UTC, beeequeue requested changes
The type should definitely be more specific than `object`. It's very clear what the functions will return in the files you linked.

I don't really get what you mean with functions overriding.

2020-02-04 07:58 UTC, morigs commented
> The type should definitely be more specific than `object`. It's very clear what the functions will return in the files you linked.
> 
> I don't really get what you mean with functions overriding.

@BeeeQueue 

By default, these implementations of `toJSON` methods are very minimalistic. So some people may want to override them to get a more verbose JSON representation of request and response. If we'll use the more specific types, for users it'll be more difficult to override these methods to something else

2020-02-04 16:52 UTC, BeeeQueue commented
I feel like the proper way to handle that would be to have a `formatResponse(res)` function rather than overriding the function. Most users shouldn't "suffer" incomplete typings because of a niche use-case.

If you really want to override the function you can make the override's return type compatible with the normal types, or override the type with a `declare module "superagent"`.

2020-02-06 08:43 UTC, morigs commented
@BeeeQueue I agree with you. But in our case, we have automated tracing which serializes response to JSON. So we cannot see response/request details in tracing. So basically it's better for users to know that there is a custom `toJSON` method

2020-02-06 11:46 UTC, BeeeQueue commented
I still don't see the problem. Since this is an issue for your specific implementation only you should have to override the type for your project to your unorthodox solution.

2020-02-10 13:27 UTC, closed without merging