@types/vast-client: add missing track() method to VASTTracker
DefinitelyTyped/DefinitelyTyped pull request #42083
Opened 2020-02-04 06:14 UTC by yowcow

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-02-04 14:26 UTC, jgainfort commented on types/vast-client/vast-client-tests.ts
> +const invitationButton = document.getElementById('inviationButtonId') as HTMLButtonElement;
little typo

inviation -> invitation

2020-02-04 14:27 UTC, jgainfort commented on types/vast-client/index.d.ts
> +         * Indicate if the event has to be tracked onlye once.
typo

onlye -> only

2020-02-04 14:28 UTC, jgainfort requested changes
Just the two typos, otherwise it looks great. Thank you.

2020-02-06 01:16 UTC, yowcow commented on types/vast-client/vast-client-tests.ts
> +const invitationButton = document.getElementById('inviationButtonId') as HTMLButtonElement;
fixed, thanks!

2020-02-06 01:17 UTC, yowcow commented on types/vast-client/index.d.ts
> +         * Indicate if the event has to be tracked onlye once.
fixed

2020-02-06 16:39 UTC, jgainfort approved these changes

2020-02-06 17:40 UTC, merged