fix(estree): declaration should not be undefined
DefinitelyTyped/DefinitelyTyped pull request #42163
Opened 2020-02-06 15:11 UTC by bodinsamuel

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-02-06 16:22 UTC, Swatinem commented
👍 
But I think to be completely complient, I think every optional prop needs to have an explicit `null` instead of an implicit `undefined` :-(

2020-02-06 21:41 UTC, RReverser commented
ESTree consumers are normally fine with accepting both `null` and `undefined`, and typings are trying to reflect it. When you're building ASTs by hand, you want to be able to skip optional properties rather than having to manually type `null` everywhere, otherwise you're going to have issues with upgrades when node types get extended with new flags.

2020-02-06 21:42 UTC, RReverser requested changes
I'd say that in this case it's rollup that should be fixed to accept optional properties in either form.

2020-02-06 22:14 UTC, Swatinem commented
> I'd say that in this case it's rollup that should be fixed to accept optional properties in either form.

CC @lukastaegert

2020-02-13 22:27 UTC, closed without merging

2020-02-14 16:56 UTC, RReverser commented
> Same thing for that, especially with something as specific as estree I would rather break on upgrade than letting new flags pass through.

I can certainly see how that would be useful on the consumer side, but I'm not sure excluding `undefined` would help here. Even if you exclude it, it still won't help you to catch new flags / properties on nodes. The only way to do that is to manually review node types on definition upgrades.

2020-02-14 18:50 UTC, lukastaegert commented
Just my two cents:
-  ESTree is clearly specified as having `null` for optional properties, and this is also usually observed by dedicated parsers. Forcing consumers to add checks for `undefined` (well, probably type casts, but still) where there will never be an `undefined` sounds useless to me. New properties are somewhat special here but my beef is with having `undefined` for existing properties. Named exports are a good example, this did not change since 2015.
- Having uniform object shapes will also be better optimized by the JS runtime. Allowing optional properties defeats that.