Fix using angular-mocks types with typescript 3.7.5
DefinitelyTyped/DefinitelyTyped pull request #42340
Opened 2020-02-13 12:28 UTC by HerbiePorter

Importing these types into a typescript 3.7.5 project resulted in an exception from the typescript compiler.

```
.../node_modules/typescript/lib/tsc.js:78602
                throw e;
                ^

TypeError: Cannot read property 'get' of undefined
```

My hunch is that it was due to a clash between the `mock` namespace and the `mock` property on the IAngularStatic interface.  The IAngularStatic interface is exported from the angular types module as angular so you end up with a clash between `angular.mock` referring to the namespace in the angular-mocks index.d.ts and also referring to the IMockStatic interface. Splitting the angular-mocks `mock` namespace to `http` and `browser` for their respective interfaces fixes the problem for us.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-02-13 21:37 UTC, thorn0 commented
If this is a bug in TS, which it apparently is, it should be reported. Did you try to isolate the issue to create a minimal reproduce case?

2020-02-14 09:21 UTC, HerbiePorter commented
That's a good point, thanks @thorn0.  I'm relatively new to typescript, I had assumed that the angular-mocks type module was doing something wrong (clashing a namespace with a static property) but the error is being thrown from the typescript compiler.  I'll try and isolate it this weekend in a test case, raise a bug with typescript and link it to this PR so we can track them both.

2020-02-14 09:35 UTC, thorn0 commented
> was doing something wrong (clashing a namespace with a static property

Nothing wrong with this. TS supports [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).

2020-02-18 13:28 UTC, thorn0 requested changes
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42340#issuecomment-585983834

2020-02-18 13:37 UTC, HerbiePorter commented
@thorn0 I've tried to reproduce the exception in a standalone project but I couldn't get it to work.  I'm happy to close this PR as it sounds like it might be something related to our project setup rather than the angular-mocks types or typescript compiler.

2020-02-18 13:37 UTC, closed without merging

2020-02-18 13:45 UTC, thorn0 commented
Most probably it's something in your project setup that revealed a bug in the compiler.

When trying to reproduce, did you start from scratch or were you removing / simplifying parts of your project to understand at what point this error stops happening?

2020-02-18 14:12 UTC, HerbiePorter commented
Our project is relatively large and complex (due to a migration from angular to react) so it would be difficult to work backwards from there.  Instead, I tried to start from scratch with a simple hello-world angular webpack project with typescript 3.7.5.  With that simple setup, the compiler didn't throw any warnings.

2020-02-18 14:22 UTC, thorn0 commented
Yeah, I tried that too.