[Node fetch] Allow body to accept FormData
DefinitelyTyped/DefinitelyTyped pull request #42364
Opened 2020-02-14 05:07 UTC by OmgImAlexis

https://www.npmjs.com/package/node-fetch#post-with-form-data-detect-multipart

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-02-14 12:32 UTC, nikcorg commented
Hi @OmgImAlexis,

While it looks like the [form-data](https://www.npmjs.com/package/form-data) package does provide type definitions, you will need to explicitly import the type from that package, which does mean you'll need to add it as a dependency to this project. 

In good news, it's already listed in the [dependencies whitelist](https://github.com/Microsoft/types-publisher/blob/master/dependenciesWhitelist.txt#L96) for DefinitelyTyped, so it _should_ be sufficient to just include it in a [`package.json`](https://github.com/DefinitelyTyped/DefinitelyTyped#i-notice-some-packages-having-a-packagejson-here), which this project doesn't yet have, like this:

```
{
    "private": true,
    "dependencies": {
        "form-data": "^3.0.0"
    }
}
```

Because `form-data` uses [default export](https://github.com/form-data/form-data/blob/master/index.d.ts#L10), you'll need to use an [`import = require`](https://github.com/Microsoft/dtslint/blob/master/docs/no-import-default-of-export-equals.md) instead of `import from` to keep the linter happy and not break older TS versions.

I hope that will fix the build, after which we can merge your PR :-)

PS. Also don't forget to add yourself to the [list of contributors](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42364/files#diff-16dd1699972b26236bcd5bc367af23fbL3-L12)

2020-02-14 12:37 UTC, nikcorg requested changes
Some additional work is required to make the build pass.

2020-02-14 12:37 UTC, nikcorg commented on types/node-fetch/index.d.ts
> +    | FormData;
You'll need to import the `FormData` explicitly. See my [earlier comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42364#issuecomment-586269082) for further details.

2020-02-20 06:13 UTC, OmgImAlexis commented
Sorry I haven’t had a chance to get to this. I’ll fix up the issues tomorrow.

2020-02-21 05:26 UTC, closed without merging

2020-02-21 08:15 UTC, OmgImAlexis commented
Wtf? Your bot needs some work.

2020-02-23 04:35 UTC, OmgImAlexis commented
Can this please be reopened?

2020-02-24 17:49 UTC, nikcorg commented
@OmgImAlexis I'm all for reopening the PR but I don't have the power and I don't know who to ping about it. It might be quicker and easier to reopen a new PR.

2020-02-25 03:28 UTC, OmgImAlexis commented
It’s fine my other PR was merged. Just seems odd not to add more time when someone comments back.

2020-02-25 16:09 UTC, ExE-Boss commented
I’ve found that the easiest workaround in that situation is to create a merge commit:

```sh
git fetch upstream
git branch -f master upstream/master --no-track
git merge master
git push origin HEAD master
```

2020-02-25 20:25 UTC, OmgImAlexis commented
Shouldn’t require a commit to keep the bot happy. No other stale bots work like that. This is counter productive and puts all the responsibility on the OP. Yet reviewers can take multiple days before they appear.

Just seems stacked against people trying to fix things.