[@types/react-big-calendar] update types to v0.24.0
DefinitelyTyped/DefinitelyTyped pull request #42388
Opened 2020-02-15 15:53 UTC by fhessenberger

Add missing property `dayLayoutAlgorithm` introduced in v0.23.0 to `Calendar`.
Add missing property `slotGroupPropGetter`  introduced in v0.24.0 to `Calendar`.
Constrain `Culture` type to `string` instead of `string | string[]` as per original package prop types.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/react-big-calendar/pull/1473 https://github.com/jquense/react-big-calendar/pull/1510
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
~- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.~

2020-02-16 08:15 UTC, eps1lon requested changes
Looks good. Just a minor nit.

2020-02-16 08:15 UTC, eps1lon commented on types/react-big-calendar/index.d.ts
>  // Type definitions for react-big-calendar 0.22
This needs an update as well.

2020-02-16 08:23 UTC, fhessenberger commented on types/react-big-calendar/index.d.ts
>  // Type definitions for react-big-calendar 0.22
Sure, I changed it!

2020-02-16 08:49 UTC, eps1lon approved these changes
Nice, thanks.

2020-02-20 18:30 UTC, merged

2020-02-20 18:30 UTC, PranavSenthilnathan commented
Congratulations on your first DefinitelyTyped contribution! Thank you for being a part of the community!