[aws-lambda] Narrow AuthResponseContext type
DefinitelyTyped/DefinitelyTyped pull request #42421
Opened 2020-02-17 09:44 UTC by c-bandy

Fixes #42418

> You can access the stringKey, numberKey, or booleanKey value (for example, "value", "1", or "true") of the context map in a mapping template by calling $context.authorizer.stringKey, $context.authorizer.numberKey, or $context.authorizer.booleanKey, respectively. The returned values are all stringified. Notice that you cannot set a JSON object or array as a valid value of any key in the context map.

From https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-lambda-authorizer-output.html

2020-02-17 12:04 UTC, simonbuchan commented
Docs are a bit dumb here, there's been an attempt to narrow before is #33437 that was reverted since the cognito authorizer will give you an object in `event.authorizer.claims`. This can be fixed by splitting the authorizer (output) and proxy handler (input) types, but that's a bigger breaking change.

I've put some thoughts about where I think this should go in the related issue #34059, any feedback?

2020-02-17 12:40 UTC, c-bandy commented
Ah! Shame it isn't as straight-forward as documented.

What do you think about using a union type to represent a generic `context`? This could cover the custom authorizer context and the cognito context property.

2020-02-17 13:03 UTC, c-bandy commented
On #34059, I basically agree. I think your last solution is as elegant as it gets. 

If not for that, at the very least we should differentiate the `APIGatewayProxyEvent.requestContext`, `CustomAuthorizerResult.context` and `CustomAuthorizerEvent.requestContext` types.

2020-02-17 21:50 UTC, simonbuchan commented
Yeah, I'm happy narrowing the authorizer result context, it should only catch actual errors (unless someone's playing tricks with `toString()` / `toJSON()`? They knew what they were getting into.)

I also have #42420 open now which will conflict with this if it goes in. If I'm bringing in a new type anyway I can make these changes at the same time?

2020-02-18 18:14 UTC, c-bandy commented
I'll wait for your PR to be merged until I make any changes here

2020-02-19 17:03 UTC, c-bandy commented
@simonbuchan sorry, looks like i completely parsed your question wrong. feel free to do so!

2020-02-22 09:47 UTC, StefH approved these changes

2020-02-22 09:55 UTC, darbio commented
Isn't this going to be addressed by @simonbuchan in #42420? If so this PR should **not** be merged.

2020-02-22 10:35 UTC, simonbuchan requested changes
More relevantly, a very similar PR #33437 has previously had to have been rolled back, so whether this gets added to my PR or not (I was just commenting that it would conflict) this shouldn't be merged.
I'm going to mark this request changes so it doesn't slip through.

2020-02-22 10:36 UTC, simonbuchan commented
... @c-bandy you thumbed that up so fast it was there before the page loaded after my post 😲

2020-02-22 10:37 UTC, c-bandy commented
@simonbuchan I was already here writing essentially the same message you were, but you were faster than me :P

2020-02-22 10:46 UTC, simonbuchan commented
Since it's been open for a week and at least nobody seems to be complaining about it, I'll throw the changes in.

2020-02-25 11:58 UTC, simonbuchan commented
Let me know if the latest changes in #42420 look like they fix this for you.

2020-02-28 11:27 UTC, c-bandy commented
I havent had time to test your changes but the source code looks good to me

2020-02-28 12:58 UTC, c-bandy commented
Hey @simonbuchan, I tried testing this in one of our repos, it looks like the issue raised here is not solved by your work so far, I can still put `any` inside the context for a custom authorizer. Am I expected to use a different type here?

![image](https://user-images.githubusercontent.com/31383109/75550447-3a3a8600-5a32-11ea-9d31-320179b586a3.png)

2020-02-28 16:17 UTC, simonbuchan commented
Ah, yes, by default my PR doesn't narrow the response context type, it probably should. You can instead declare a type that describes the context exactly, then use that with `APIGatewayAuthorizerWithContextResult<MyContext>`, and matching `APIGatewayProxyWithContextEvent<MyContext>`.

I can quickly add narrowing the response type in my PR on my Monday, which should be before a maintainer merges it, since I'm UTC+12, but I might forget. Won't be a huge problem to PR just that though.

2020-02-29 11:25 UTC, closed without merging