Update `webpack-dev-middleware` to 3.7
DefinitelyTyped/DefinitelyTyped pull request #42573
Opened 2020-02-23 19:36 UTC by peterblazejewicz

- v2 created
- update configuration options to v3.7

https://github.com/webpack/webpack-dev-middleware/tree/v3.7.2#options

Note that PR contains change for `webpack-serve` v1 tests, otherwise it wont' pass the CI tests (npm test). The change is technical one, without modyfing the `webpack-serve` definition files.

Thanks!

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webpack/webpack-dev-middleware/tree/v3.7.2#options
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`.

2020-02-23 20:27 UTC, peterblazejewicz commented
as the bot missed opportunity again,
/cc @bumbleblym @reduckted @chrisabrams

2020-02-24 04:44 UTC, chrisabrams requested changes
Overall thanks for getting this up to 3.x. There does seem to be inconsistencies between files on whether they are 2/4 spaces :| If you can fix that happy to approve!

2020-02-24 04:44 UTC, chrisabrams commented on types/webpack-serve/v1/webpack-serve-tests.ts
> +const serveConfig: serve.Options = {
Good catch.

2020-02-24 06:45 UTC, peterblazejewicz commented
@chrisabrams 
I've used the project prettier settings to change the formatting on the current definitions (not v1/v2):
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.prettierrc.json
Should I revert that changes?

2020-02-26 00:38 UTC, merged