[react] Mirror React Hooks Flow and exhaustive deps behaviour
DefinitelyTyped/DefinitelyTyped pull request #42611
Opened 2020-02-25 12:04 UTC by jannes-io

react-hooks/exhaustive-deps is set up to correctly follow React's Flow definition of useCallback and useMemo. However the suggested solutions do not work in TypeScript since @types/react "interpreted" the definitions of Facebook.

When not passing any deps:
```
Failed to compile.
Expected 2 arguments, but got 1.  TS2554
```
When passing undefined as deps:
```
React Hook useMemo was passed a dependency list that is not an array literal. This means we can't statically verify whether you've passed the correct dependencies react-hooks/exhaustive-deps
React Hook useMemo has a missing dependency: 'someDep'. Either include it or remove the dependency array react-hooks/exhaustive-deps
```
As you can tell, this behavior is very confusing so I propose we simply mirror react and let react-hooks/exhaustive-deps do the dependency checking as it also does for useEffect.

This PR aims to mirror the React Flow definitions and have the dep arrays as optional parameters. It should be 100% backwards compatible since the constraints have been loosened.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react/blob/master/packages/react/src/ReactHooks.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-02-25 13:59 UTC, eps1lon requested changes
If it already adds a warning we should prevent this at the type level. There is no use case for 0 dependency useMemo.

React handles a bunch of missing/wrong arguments at runtime as well. Just because they do that doesn't mean the types shouldn't reflect it.

2020-02-25 14:39 UTC, ferdaber commented
Agreed, the types doesn't care whether or not you use React's own ESLint rules also, they're separate concerns.

2020-02-25 14:42 UTC, jannes-io commented
@eps1lon 
Exhaustive-deps will throw if you pass `undefined` as dependency array. So why do we allow that on type level but not leaving the param out?

It is currently just very unclear to understand what one is supposed to do when presented with this error.
Currently these types allow undefined, but not leaving the paramater out.
Exhaustive-deps throws when it's undefined but not when the parameter is left out.

In my opinion we should create declarations as closely to the source as possible since the source expects it to be used that way, definitely since React already uses Flow to do type-checking so we should follow Facebook's Flow definitions.

2020-02-25 14:53 UTC, eps1lon commented
> Exhaustive-deps will throw if you pass undefined as dependency array. So why do we allow that on type level but not leaving the param out?

Now I understand. It was added in #33220 but I do not understand why you'd want conditional memoization. Would be nice to open an issue regarding `exhaustive-deps` as well to see what the core team thinks about it.

But even if I don't understand #33220 it was made pretty clear that passing `undefined` is only allowed if you know what you're doing. `deps?` was not allowed to enforce arity following https://github.com/facebook/react/pull/14894#issuecomment-465433212.

2020-02-25 14:59 UTC, ferdaber commented
But this isn't a runtime error either, it's just an ESLint rule violation, so I'm ambivalent towards this— I guess the workaround for those who *absolutely* need to use undefined can just do: `useMemo(x, undefined!)`

2020-02-25 18:40 UTC, DovydasNavickas commented
I agree with @ferdaber. @types packages are about adding types for the library's JS code, not mitigating ESLint rules. I understand that `react-hooks/exhaustive-deps` rule is provided by Facebook themselves and I use those rules myself. But the change that is proposed here is not mitigating how library works, it's runtime error or anything like that.

Additionally, omitting the deps seems to be an advanced usage, thus, an explicit way of giving `undefined` as `deps` parameter that @ferdaber showed is more appropriate:

```ts
useMemo(x, undefined!)
```

If we started solving our ESlint errors by updating types, we'd have quite a few PRs every day, because we wouldn't find one setup that everyone uses 😄

2020-02-26 13:53 UTC, jannes-io commented
Thank you all for the feedback! Seems like this is something we have to take up with exhaustive-deps.

2020-02-26 13:53 UTC, closed without merging