Fix types for @tryghost/content-api to match library
DefinitelyTyped/DefinitelyTyped pull request #42750
Opened 2020-03-01 00:56 UTC by thrymgjol

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [latest](https://github.com/TryGhost/Ghost-SDK/blob/5bfffd3d7d67d1fe908323a88a1ce1bf9788e8c3/packages/content-api/lib/index.js#L91), [version 3](https://github.com/TryGhost/Ghost-SDK/blob/30b6e6e3a11f62526d65ec0e279f9cb4f2a6af64/packages/content-api/lib/index.js#L91), and [version 2](https://github.com/TryGhost/Ghost-SDK/blob/3c167e5917e7a49a0a5fa213a2edd86e084a81a3/packages/content-api/lib/index.js#L91).
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

I tried all 3 preceding versions of these type definitions with every version of `@tryghost/content-api` since the definitions were released. Every combination failed with the same errors when I tried to run [the sample code from the Ghost docs](https://ghost.org/docs/api/v2/javascript/content/). I'm a little puzzled because there have been several updates to the type definitions and no one has brought this up. I [put together a quick demo](https://github.com/thrymgjol/ghost-content-api-types-demo/tree/master) just in case there's something I'm completely missing.

The lines I linked to above have remained the same for every version of `@tryghost/content-api` since these type definitions were released:
```js
if (!Array.isArray(res.data[resourceType])) {
    return res.data[resourceType];
}
if (res.data[resourceType].length === 1 && !res.data.meta) {
    return res.data[resourceType][0];
}
return Object.assign(res.data[resourceType], {meta: res.data.meta});
```
In the last statement, the array object is assigned the `meta` property (`SomeObject[] & { meta: { ... } }`), whereas the type definitions give the object the form
```ts
interface PostObject {
    posts: PostOrPage[];
    meta: { pagination: Pagination };
}
```
I received this error no matter which version I tried:
```
error TS2350: Only a void function can be called with the 'new' keyword.
```
or this if I removed `new` ([from the sample code](https://ghost.org/docs/api/v2/javascript/content/))
```
error TS2339: Property 'forEach' does not exist on type 'PostObject'.
```

I resolved both of those errors in these type definitions.

2020-03-06 00:07 UTC, amcasey reviewed
Thanks for the detailed explanation!  May I suggest that you turn some of your thorough validation work into official tests for this package?

2020-03-06 05:32 UTC, antonve commented
I ran into the same issue when I used the type definitions earlier, but unfortunately haven't had the time to really dig into it.

I'd like to take a closer look at this PR later. As amcasey said, I'd like to see some tests to validate if these changes actually solve the problem. I'll try and run this branch with a different codebase to see if this fixes the issue over the weekend.

2020-03-15 13:48 UTC, thrymgjol commented
> I'd like to take a closer look at this PR later. As amcasey said, I'd like to see some tests to validate if these changes actually solve the problem. I'll try and run this branch with a different codebase to see if this fixes the issue over the weekend.

I'm not entirely sure how to write tests that validate the types. If I understand correctly, tests written for DefinitelyTyped don't actually have any interaction with the actual package.

2020-03-15 17:27 UTC, levibostian commented
@thrymgjol - I could be wrong, but you are correct in that tests don't run the code in the package but they are tests that execute the compiler to assert that the typings are correct. 

If you look at many of the other modules in this repo as examples, you will see how they run tests. It's more about writing some code and asserting that the values are what you expect it to be.

```
const pagesBrowsePromise = api.pages.browse(); // $ExpectType Promise<MetaArray<PostOrPage>>
```

Does that answer your question?

2020-03-16 17:08 UTC, amcasey commented
@thrymgjol As @levibostian suggested, the nicest way to write tests is to write some hypothetical consuming code and specify how you expect the types to behave.  A simpler, but still valuable, approach is what you did in your summary - write some code that should be legal and confirm there are no errors.

2020-03-31 22:43 UTC, uniqueiniquity requested changes
Marking as changes requested until tests are added.

2020-04-04 09:27 UTC, maveric1977 commented
@thrymgjol Thank you for the good suggestions. Ping me as soon as the merge conflicts are resolved.
One small suggestion for the sake of API best practices, it would be great if you use `interface`s instead of `types` for the `BrowseFunction` results. See this post for more info: https://medium.com/@martin_hotell/interface-vs-type-alias-in-typescript-2-7-2a8f1777af4c

```
interface BrowseResults<T> extends Array<T> {
    meta: { pagination: Pagination };
}

export interface Posts extends BrowseResults<PostOrPage>{}
export interface Pages extends BrowseResults<PostOrPage>{}
export interface Authors extends BrowseResults<Author>{}
export interface Tags extends BrowseResults<Tag>{}
```

2020-04-07 23:27 UTC, closed without merging