Add new types for mitranim/posterus
DefinitelyTyped/DefinitelyTyped pull request #42751
Opened 2020-03-01 05:19 UTC by davidgovea

Package: https://github.com/mitranim/posterus

had to disable no-unnecesary-generics to allow optional type specification on the constructor's return value -- could not figure out a way to achieve a type api similar to `Promise` without disabling this rule.

Desired api:
```
const futureAny = new Future();
const futureString = new Future<string>();
```

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2020-03-02 19:03 UTC, sheetalkamat requested changes

2020-03-02 19:03 UTC, sheetalkamat commented on types/posterus/index.d.ts
> +    class Future<T = any, E extends Error = Error> {
This class can not be inside namespace Inside it needs to be outside..

2020-03-02 19:03 UTC, sheetalkamat commented on types/posterus/index.d.ts
> +        // tslint:disable-next-line no-unnecessary-generics
Fix this error instead..

2020-03-02 19:03 UTC, sheetalkamat commented on types/posterus/index.d.ts
> +    interface FutureConstructor {
Instead define this as class and methods here become static

2020-03-02 22:45 UTC, davidgovea commented
thank you for the quick review @sheetalkamat!

You suggestions helped me remove the tslint-disabling, and the types read way more clearly now.

I also noticed a suggestion of a missing definition for a library export in [this build](https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/657501491), so I extended the types a bit further to make sure everything was attended to. Force-pushed to keep the commits less noisy.

2020-05-04 16:52 UTC, andrewbranch approved these changes

2020-05-04 16:52 UTC, merged