fixed domain/range mixup
DefinitelyTyped/DefinitelyTyped pull request #42767
Opened 2020-03-02 16:34 UTC by RSWilli

Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x ] Provide a URL to documentation or source code which provides context for the suggested changes: https://observablehq.com/@d3/d3-scaletime
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

@tomwanzek , @gustavderdrache , @borisyankov , @denisname 

I found this mistake while trying to reproduce the example given at https://observablehq.com/@d3/line-chart

I copied the code and it didn't accept the range:

![image](https://user-images.githubusercontent.com/18500203/75696093-4f6e1980-5cab-11ea-8988-4121a7a8e2a7.png)

The mistake happened because of a copy paste error i suppose:

https://github.com/RSWilli/DefinitelyTyped/blob/e94bac7afa23b5bcc5bfe355111c39c5f97e3f33/types/d3-scale/index.d.ts#L706

https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...RSWilli:master#diff-96f5ea7516d7157f8457259d7b7a7ac6R37

The generic arguments of the interface were called `<Range, Output>` instead of `<Domain, Range>` like elsewhere in the file

this resulted in a misuse of the Type `Range`, because it referred to the first parameter

2020-03-03 07:54 UTC, RSWilli commented
does this then imply a version change for the depending @types/d3 ?

2020-03-03 16:47 UTC, gustavderdrache requested changes
I think this PR confuses the two type parameters in the scale interfaces. The scales aren't parameterized by their domain at all, because the underlying D3 code assumes that the inputs are either numbers or dates (depending on the scale).

The short version is that your code should be using `d3.scaleUtc<number>()` because it doesn't use a different interpolator:

```ts
const height = 500
const width = 400

const margin = { top: 20, right: 30, bottom: 30, left: 40 }

const data: Data[] = [
  {
    date: new Date(),
    value: 5
  }
]

const x = d3.scaleUtc<number>() // <- there's only one type param needed here
  .domain(d3.extent(data, d => d.date) as [Date, Date])
  .range([margin.left, width - margin.right])
```

I'm gonna include the long version of the explanation here as reference in case it trips up other people, so don't take this as a judgment on your PR specifically — it's not really obvious what's happening, and has to due with the subtlety of how D3's interpolators work.

First, let's use this simplified `ScaleTime` interface for discussion:

```ts
export interface ScaleTime<Range, Output> {
  (value: Date | number | { valueOf(): number }): Output;

  domain(): Date[];
  domain(domain: Array<Date | number | { valueOf(): number }>): this;

  range(): Range[];
  range(range: ReadonlyArray<Range>): this;

  interpolate(): InterpolatorFactory<any, any>;
  interpolate(interpolate: InterpolatorFactory<Range, Output>): this;
  interpolate<NewOutput>(
    interpolate: InterpolatorFactory<Range, NewOutput>
  ): ScaleTime<Range, NewOutput>;
}
```

The reason we have two type parameters that both seemingly relate to the output type is because of the `interpolate` setter. A scale's default interpolator is `d3.interpolate`, which is treated as an arbitrary factory. Some interpolators are more lenient in what they accept than what they return, which is where the difference between `Range` and `Output` comes in. In fact, the primary reason we use this is in order to support color interpolation.

For instance, here's the signature of `d3.interpolateHcl` (this applies to RGB, HSL, LAB, and so on):

```ts
export function interpolateHcl(
  a: string | ColorCommonInstance,
  b: string | ColorCommonInstance
): (t: number) => string;
```

Based on the above signatures, the `Range` of this interpolator is `string | ColorCommonInstance`, but the `Output` of the interpolator is always `string`. Here's an example usage of `scaleUtc` using color interpolation. I've formatted it a bit weirdly to indicate more information on the types and how they're used:

```ts
const scale = d3
  .scaleUtc<
    // Type param: Range
    string | d3.ColorCommonInstance,
    // Type param: Output
    string
  >()
  .domain(
    // The domain of this scale does not depend on any type parameters: `scaleUtc` only
    // accepts Dates and numbers
    [startDate, endDate]
  )
  .range(
    // The `range` setter uses the `Range` type parameter, so we can set the range to be
    // either strings or Color objects (the string | ColorCommonInstance union).
    ["red", d3.rgb(0, 255, 0)]
  )
  .interpolate(
    // interpolateHcl use a function of (a: Range, b: Range) => ((t: number) => Output)
    d3.interpolateHcl
  );

// When using the scale, the function always returns a value of type `Output`.
const output: string = scale(startDate);
```

This holds for linear, power, and other scales. Here's a short example using a linear scale:

```ts
const scale = d3
  .scaleLinear<string | d3.ColorCommonInstance>()
  .domain([0, 100])
  .range(["red", "green"])
  .interpolate(d3.interpolateHcl);

const output: string = scale(42);
```

2020-03-04 08:10 UTC, RSWilli commented
@gustavderdrache thanks for the detailed response!

so you are suggesting that the types are currently correct and this PR should be closed?

2020-03-04 14:36 UTC, gustavderdrache commented
Yes. I think you just need to use `d3.scaleUtc<number>` to get what you want based on the screenshot you posted.

2020-03-05 18:37 UTC, RSWilli commented
ok thanks

2020-03-05 18:37 UTC, closed without merging