[ember-data] Fix DS.belongsTo and DS.hasMany
DefinitelyTyped/DefinitelyTyped pull request #42839
Opened 2020-03-04 20:06 UTC by ro0gr

This enables relationships aware `model.belongsTo(` and `model.hasMany(`:
 - Specifying wrong relationship name leads to error
 - Specifying correct relationship name correctly infers related model type via `reference.value()`

----

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
   - [WIP docs for native classes](https://github.com/typed-ember/ember-cli-typescript/blob/657f25cad01e1f725152257cd625d20e0606c175/tests/dummy/app/templates/docs/ember-data/models.md), PR - https://github.com/typed-ember/ember-cli-typescript/pull/935
   - https://api.emberjs.com/ember-data/3.16/functions/@ember-data%2Fmodel/belongsTo
   - https://api.emberjs.com/ember-data/release/classes/BelongsToReference
   - https://api.emberjs.com/ember-data/3.16/functions/@ember-data%2Fmodel/hasMany
   - https://api.emberjs.com/ember-data/release/classes/HasManyReference
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-03-04 20:14 UTC, ro0gr commented on types/ember-data/index.d.ts
> +      : Model[k] extends DS.Model ? Model[k]
this line stands to handle decorators version. Should probably add 
```ts
: Model[k] extends DS.PromiseObject<infer C> ? C
```
to support 
```ts
export default class Post extends Model {
  @belongsTo('user')
  user!: DS.PromiseObject<User>;
}
```

2020-03-04 20:14 UTC, ro0gr commented on types/ember-data/index.d.ts
> +      : Model[k] extends DS.PromiseManyArray<infer C>
should probably add 
```ts
Ember.Array<infer C> ? C extends DS.Model ? C 
  : never`

2020-03-05 07:49 UTC, ro0gr commented on types/ember-data__model/tsconfig.json
> +        "target": "ES5",
✂️ not needed anymore

2020-03-06 00:32 UTC, ro0gr commented
ok, I've detected some issues while adding more coverage. Marking as a WIP for now, will to figure it out soon.

2020-03-08 16:57 UTC, ro0gr commented
Just checked it against my current mid-size code base. There are few breakages detected. All are related to methods defined on models, which use `this.belongsTo(` and and `this.hasMany`. For the record, these are pre-existing issues, which just started to appear in new ways.

1. 
```ts
this.belongsTo('rel' as any).value()?.id;
```

Error:
> Property 'id' does not exist on type 'NonNullable<UnpackBelongsTo<this>[any]>'

*Solution*: remove explicit `this`. Not sure if that's a big issue TBH.

2.

```ts
  @belongsTo('something')
  something!: Something

  get explicitThis(this: Me) {
    return this.belongsTo('something').value();
  }
```

Error:

> 'explicitThis' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.

Solution: remove explicit `this`. It doesn't seem a big issue as well. However, at the moment, I'm not sure what is the root cause. To me it should just work, even if explicit `this` is not a cool thing.

3.

```ts
class Parent extends Model {
  @hasMany('child')
  children!: Child

  get firstFromHasMany() {
    const p = this.hasMany('children').value();

    return p && get(p, 'firstObject');
  }
}
```

Error:
> 'firstFromHasMany' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)

Solution: declare explicit `this` and the return type. While this is better than `as any` imo, I'd like to understand if we can do smth with it before(if) merging the PR. 

```ts
class Parent extends Model {
  @hasMany('child')
  children!: Child

  get firstFromHasMany(this: Parent): Child | undefined {
    const p = this.hasMany('children').value();

    return p && get(p, 'firstObject');
  }
}
```  
----

The good news are that everything else seem to work as expected at the moment, which even helped me to find some suspicious places in my codebase :)

2020-03-13 14:42 UTC, chriskrycho commented
Thanks for this! I'm going to try to spend some time on it today. cc. also @dfreeman @jamescdavis who may be able to get eyes on it.

2020-03-14 21:15 UTC, ro0gr commented
> I'd like to understand if we can do smth with it before(if) merging the PR.

After some brute-forcing, I think what we have with a broken `this.hasMany` is TS bug. Basically, in order to make work `hasMany`, we do smth like(extremelly reduced version):

```ts
type UnpackHasMany <T> = {
    [k in keyof T]: T[k] extends Array<infer U>
      ? U
      : T
};

declare class Model {
    hasMany<T extends Model, K extends keyof UnpackHasMany<T>>(this: T, name: K): UnpackHasMany<T>[K];
}

class A extends Model {
    myHasMany!: Array<{ name: string }>; // array stands to mimic hasMany

    test() {
        // Fails with:
        // Property 'name' does not exist on type 'UnpackHasMany<this>["myHasMany"]'.
        return this.hasMany('myHasMany').name;
    }
}

const a = new A();

// meanwhile it works as expected for instances.
a.hasMany('myHasMany'); // $ExpectType number

```

But, if I extract infering an array item type to a separate type, which deals with `T` instead of `T[k]` it starts working:

```ts
// this one solves the issue.
type UnboxedHasMany<T> = T extends Array<infer U> ? U : T;

type UnpackHasMany <T> = {
    [k in keyof T]: UnboxedHasMany<T[k]>
};

class A extends Model {
    myHasMany!: Array<{ name: string }>; // array stands to mimic hasMany

    test(): string {
        // `this` works as expected!
        return this.hasMany('myHasMany').name;
    }
}
```

I'm not 100% sure about root causes of such behavior, but I'll update PR to fix `this.hasMany` and cover it by tests.

2020-03-15 14:08 UTC, ro0gr commented
I believe I've addressed my concerns. Please review, and let me know if something else should have been done here, when you have time.

2020-03-19 23:13 UTC, ro0gr commented
alright, I've found some issues with `assertType` which is demonstrated and fixed in the last 3 commits.
So first, I've broken relationships unpacking, but test like:
```ts
  assertType<Folder|null>(
    folder.belongsTo('parent').value() // because of intentionally broken styles it's "never"
  );
```
remained green.

That made me to re-write some of the tests to `$ExpectType` flavour.

However... Now, even with CI passing, and my editor doesn't highlight any issues, `npm run lint ember-data` fails for TypeScript@next, with errors like:

```ts
Error: ~/workspace/DefinitelyTyped/types/ember-data/test/belongs-to.ts:32:1
ERROR: 32:1  expect  TypeScript@next expected type to be:
  Folder
got:
  Model & Folder
```

And I'm pretty clueless at the moment. I'd like someone to check the PR locally with `npm run lint ember-data`, and let me know if they see the same issue. Would appreciate any hints.

2020-03-28 16:34 UTC, chriskrycho commented
Thanks so much for pushing so thoroughly on this! I will do my best to give it some love and time this coming week. Perhaps @dfreeman and/or @jamescdavis will be able to as well!

2020-04-08 16:40 UTC, RyanCavanaugh commented
What's the status on this PR? I'd like to merge or close by the end of the week if possible

2020-04-08 21:16 UTC, chriskrycho commented
Got buried, will review by Friday. Thanks for flagging it up!

2020-04-11 03:09 UTC, chriskrycho commented
Sorry, ended up buried in one of *those* bugs where a build would fail only in a production build on a very specific circumstance that bedeviled us all day and concluded with us realizing that build configuration is irrelevant because it never gets executed and will in fact be impossible in another few weeks. It was that kind of day. :weary:

This is on my list for Monday morning, however!

2020-04-11 03:23 UTC, RyanCavanaugh commented
lol no rush. I'll let next week's maintainer know

2020-04-20 19:16 UTC, ro0gr commented
@chriskrycho @dfreeman @jamescdavis did you have a chance to take a look here?

2020-04-21 14:20 UTC, chriskrycho commented
Doh! I got sucked into other things last week; I'm very sorry. It's on today's to-do list now!

2020-04-21 14:31 UTC, ro0gr commented
No problem, I'll just keep pinging everyone until it's settled somehow! 😃

2020-04-21 14:33 UTC, chriskrycho commented
Hahaha, PLEASE DO.

2020-04-27 14:49 UTC, elibarzilay commented
@ro0gr: reading the above, I hate to do this, but it sounds like it should still wait for a proper review?

2020-04-27 15:15 UTC, ro0gr commented
@elibarzilay yes, still waiting for review.

2020-05-02 13:02 UTC, jamescdavis commented
Note: I'm actively reviewing this and testing it against a couple of large codebases. Thank you for your patience!

2020-05-05 00:10 UTC, weswigham commented
@chriskrycho uhh... reminder ping, I guess

2020-05-05 00:44 UTC, chriskrycho commented
@weswigham yes, thank you (sincerely)! @jamescdavis picked it up for me, and will hopefully have it knocked out this week.

2020-05-12 18:34 UTC, ro0gr commented
I still believe this is a good step forward for ED types. However, taking into account, it still doesn't have any feedback, I assume, there are some issues with the PR, which I'm not aware of. I'm going to close it in a week if nothing changes. Otherwise, please, let me know if I can do smth else here. Thanks.

2020-05-13 00:12 UTC, chriskrycho commented
So sorry about the delays. @jamescdavis do you still have time to dig into this?

2020-05-13 20:50 UTC, jamescdavis commented
I worked on this today. I'm going to suggest some improvements that will give us better DX.

2020-05-13 21:03 UTC, jamescdavis commented
There also seems to be problem with `model.belongsTo()`. I'll have to look a little closer in the morning.

2020-05-14 22:57 UTC, sandersn requested changes
Requesting changes so the bot understands the status.

2020-05-18 12:39 UTC, ro0gr commented
@jamescdavis I'm curious about DX improvements and issues with the `model.belongsTo(` you've mentioned. Did you have a chance to take a look here?

2020-05-20 12:06 UTC, jamescdavis commented
@ro0gr the DX improvement I'm thinking of would be to prevent the usage of model keys of the wrong type in `Model.belongsTo()` and `Model.hasMany()` rather than just narrowing the return type to `null`. For example, in [types/ember-data/test/belongs-to.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42839/files#diff-a8c90eb2deb65dbe6c333fd155f25444) you can currently say:
```ts
folder.belongsTo('name').value()!;
folder.belongsTo('children').value()!;
```
and neither of them are type errors, they just return `null`. IMHO, this is not as good at making specifying invalid keys a type error. One way to do this is to define:
```ts
type BelongsToKeys<Model extends DS.Model> = {
    [K in keyof Model]: UnboxBelongsTo<Model[K]> extends never ? never : K
}[keyof Model];
```
and use it as:
```ts
class Model extends Ember.Object {
    belongsTo<T extends Model, K extends BelongsToKeys<T>>(this: T, name: K): BelongsToReference<UnboxBelongsTo<T[K]>>;
}
```
The same can be done for `hasMany`.

2020-05-20 12:08 UTC, jamescdavis commented
I'm still looking into the `belongsTo` issues. In general, I'm seeing some weirdness when using the types in an app with multiple models that reference each other, but I might just have something wrong. I'm going to poke at it a bit more today and let you know what I find.

2020-05-20 12:15 UTC, jamescdavis commented
Another thing that would be useful it to export `BelongsToKeys`, `HasManyKeys`, and `KeysForRelationships`. I've [needed these before](https://github.com/CenterForOpenScience/ember-osf-web/blob/5bc18b27e241dd92257d257dd4867ec1234a35e5/lib/osf-components/addon/components/validated-input/checkboxes/component.ts#L12).

2020-06-04 21:14 UTC, ro0gr commented
@jamescdavis well, I did few more attempts to enable more strict mode with `BelongsToKeys`, but still have no luck. I'm not sure whether it's because of my TS-fu, or some TS issues, but there are diffferent issues appearing in different contexts. Arguably I can try keep fixes it there and there, but `this.belongsTo(` and `this.hasMany(` becomes broken again with this change, and it doesn't seem it's feasible to fix from our side.

I do still believe the current `unknown` solution is pretty good to go. At the end, it still disallows you to misuse references, while fixing model types inference and `this` with references.

2020-07-01 15:43 UTC, ro0gr commented
@jamescdavis I just don't want to give @typescript-bot a pleasure to kill the PR, I'd better do it myself if needed 💥 So let me double check. 

Do you still think `BelongsToKeys`, `HasManyKeys`, and `KeysForRelationships` is the must here?

2020-07-06 05:16 UTC, closed without merging

2020-07-12 00:46 UTC, elibarzilay commented
I'm disappointed on behalf of @typescript-bot.

2020-07-20 16:54 UTC, jamescdavis commented
@ro0gr I definitely want to take another look at this. I was unfortunately not able to give it the attention it deserved before it timed out. I'm on family vacation this week, but should be able take some time next week to see if we can't get it there.