[slick-carousel] Enable noImplicitThis
DefinitelyTyped/DefinitelyTyped pull request #42950
Opened 2020-03-06 17:27 UTC by jablko

2020-03-06 19:11 UTC, Kocal commented
Hello, why this change?

2020-03-07 03:16 UTC, ExE-Boss approved these changes

2020-03-07 07:41 UTC, Kocal requested changes
I won't approve unless you explain your change and you will the PR template.

2020-03-11 14:45 UTC, jablko commented
This makes the automated tests a bit stricter. Before the change, if someone used the types in a project where `noImplicitThis: true`, the DefinitelyTyped automation wouldn't catch breaking changes to the types.

2020-03-13 15:47 UTC, ExE-Boss commented
The PR description should use [the PR template](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

Also, you should probably copy your comment into the PR description.

2020-04-08 15:24 UTC, ExE-Boss commented
review?(@uniqueiniquity)

2020-05-01 08:03 UTC, ExE-Boss approved these changes

2020-05-01 08:40 UTC, Kocal approved these changes

2020-05-01 19:06 UTC, merged