@testing-library/dom 7 + @testing-library/react 10
DefinitelyTyped/DefinitelyTyped pull request #43108
Opened 2020-03-13 06:22 UTC by jedmao

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes.
   - [@testing-library/react@10](https://github.com/testing-library/react-testing-library/releases/tag/v10.0.0)
   - [@testing-library/dom@7](https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2020-03-13 07:56 UTC, eps1lon requested changes
/dom is already covered by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43102

2020-03-13 07:56 UTC, eps1lon commented on types/testing-library__cypress/index.d.ts
> +// TypeScript Version: 3.8
Why is this necessary?

2020-03-13 07:56 UTC, eps1lon commented on types/testing-library__react/index.d.ts
> +// TypeScript Version: 3.8
Could you explain why we need `import type`? As far as I know this is only useful for isolatedModules and babel. We need a stronger argument for leaving older TS versions behind.

2020-03-13 14:47 UTC, jedmao commented
@eps1lon I'll rebase this on master once #43102 is merged so the additional TSDoc comments are added.

2020-03-13 15:45 UTC, eps1lon commented
Blocked until https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43102 is merged

2020-03-21 14:22 UTC, eps1lon commented on types/testing-library__react/index.d.ts
>  export function cleanup(): void;
```suggestion
export async function cleanup(): void;
```

2020-03-21 14:27 UTC, artem-malko approved these changes

2020-03-23 14:14 UTC, eps1lon commented
@jedmao Could you rebase this? Should only address `@testing-library/react` now.

2020-03-31 16:34 UTC, jedmao commented
I don't understand the build error 😕

2020-03-31 18:32 UTC, eps1lon commented
@jedmao I think you should start from scratch. Many of these fixes are already published on master.

2020-03-31 20:42 UTC, jedmao commented
@eps1lon I rebased on master. I'm just going to close this.

2020-03-31 20:42 UTC, closed without merging

2020-05-04 17:48 UTC, kylemh commented
I'm on the latest version and not seeing `waitFor` as an exported module 🤔