[@testing-library/dom] update to v7
DefinitelyTyped/DefinitelyTyped pull request #43102
Opened 2020-03-13 00:09 UTC by abraham

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-03-13 01:29 UTC, kentcdodds approved these changes
Lovely! Thank you 👍

2020-03-13 06:03 UTC, eps1lon requested changes

2020-03-13 12:32 UTC, abraham commented on types/testing-library__dom/wait-for-element-to-be-removed.d.ts
> +    callback: () => T | HTMLElement,
Updated

2020-03-13 13:08 UTC, eps1lon commented on types/testing-library__dom/wait-for-element-to-be-removed.d.ts
> +    callback: (() => T) | HTMLElement | HTMLElement[],
```suggestion
    callback: (() => T) | T,
```
is how we document this as well.

2020-03-13 13:24 UTC, eps1lon approved these changes
Perfect, thanks!

2020-03-13 13:27 UTC, kentcdodds approved these changes
💯💯

2020-03-14 12:56 UTC, timdeschryver reviewed
Should we also add deprecated comments to `wait`, `waitForDomChange` and `waitForElement`?

2020-03-14 13:43 UTC, kentcdodds commented
Those are added here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43108

2020-03-15 18:40 UTC, amaechler commented
Should the [`pretty-format`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ff99f750027135848647b20da5e0e4ee59d486e3/types/testing-library__dom/package.json#L4) dependency be updated to `^25.1.0` as well to [match](https://github.com/testing-library/dom-testing-library/blob/master/package.json#L47) the library?

2020-03-15 19:22 UTC, kentcdodds commented
Yes it should

2020-03-15 23:32 UTC, abraham commented
Updated `pretty-format`

2020-03-16 00:14 UTC, amaechler commented
Awesome, thanks.

2020-03-18 01:59 UTC, jrwpatterson commented
when will this be merged?

2020-03-21 14:28 UTC, eps1lon commented
> when will this be merged?

Microsoft employees handle merging. And as you might expect considering the global situation things might go slower than usual. You'll get this eventually.

In the meantime you can always patch this locally:

```ts
declare module '@testing-library/dom' {
    export function waitFor(
        callback: () => void,
        options?: {
            container?: HTMLElement;
            timeout?: number;
            interval?: number;
            mutationObserverOptions?: MutationObserverInit;
        },
    ): Promise<void>;
}
```

2020-03-21 17:09 UTC, bopfer commented
The type in this PR  for `waitFor` indicates that it aways returns `void`.  But, in the [release notes](https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0) it says that it can also be used to replace `waitForElement`, which would return an `HTMLElement`.  Should the types be updated to reflect that?

2020-03-21 18:38 UTC, wKovacs64 commented
@bopfer Sure seems that way. Like this, I think?

```ts
export function waitFor<T>(
    callback: () => T,
    options?: {
        container?: HTMLElement;
        timeout?: number;
        interval?: number;
        mutationObserverOptions?: MutationObserverInit;
    },
): Promise<T>;
```

2020-03-22 16:15 UTC, abraham commented
@wKovacs64 updated

2020-03-22 17:44 UTC, orta commented
This CI fail is on us, not on this PR, I think this is fine to merge 👍

2020-03-22 17:44 UTC, merged

2020-03-22 17:45 UTC, abraham commented
Thanks @orta

2020-03-23 13:57 UTC, ClementeSerrano commented
Hi guys! I still having the TS error:

`@types/testing-library__react"' has no exported member 'waitFor'.`

I'm on version `10.0.1` of the package

Any updates?

2020-03-23 14:09 UTC, abraham commented
@ClementeSerrano The react update is over in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43108

2020-03-23 14:13 UTC, ClementeSerrano commented
Cool. Thanks @abraham , I'll be attentive to the merge ;)