[relay-runtime]: allow readonly array elements to be inferred in RecordProxy
DefinitelyTyped/DefinitelyTyped pull request #43187
Opened 2020-03-17 21:36 UTC by BigsonLvrocha

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

This an improvement to use together with relay-compiler generated types
Since relay-compiler generates array types as readonly arrays, it's useful to consider them in `Unarray` type
It's a Non breaking change
Had to turn `no-redundant-jsdoc-2` rule off since it does not recognize `@private` jsdoc tag and couldn't use `tslint:disable-next-line`
This way it will correctly infer from this case:
```typescript
import { Component_prop } from './__generated__/Component_prop.graphql';

const Component: FunctionComponent<{
  prop: Component_prop;
  follows: ItemFollowButton_follows;
  teams: ItemFollowButton_teams;
  relay: {
    environment: Environment;
  } & RelayProp;
}> = props => {
  commitLocalUpdate(props.relay.environment, store => {
    const item = store.get<Component_prop>(prop.id);
    if(!item) {
      throw new Error('invalid store state');
    }
    const linkedItems = item.getLinkedRecords('Records'); // the element wouldn't be inferred here since it's ReadonlyArray, not Array
    // mutate here
  })
}

2020-03-17 22:33 UTC, Stephen2 reviewed
Seems very cool.  I'm not sure I understand the need for the 2nd commit (turn off no-reduendant-jsdoc) given that I don't think you changed any code that would trigger this rule?

2020-03-17 22:40 UTC, BigsonLvrocha commented
> I don't think you changed any code that would trigger this rule?

yes, that is true, but it seems that now, that rule will throw en error, even if linting in master branch

2020-03-17 22:41 UTC, BigsonLvrocha commented
I've opened up an issue for this https://github.com/microsoft/dtslint/issues/278

2020-03-17 23:01 UTC, Stephen2 commented
I think this is better:
```
16:00 $ gd
diff --git a/types/relay-runtime/index.d.ts b/types/relay-runtime/index.d.ts
index 7af27e4934..c03d90e2d8 100644
--- a/types/relay-runtime/index.d.ts
+++ b/types/relay-runtime/index.d.ts
@@ -200,16 +200,10 @@ export { deepFreeze } from './lib/util/deepFreeze';
  * relay-compiler-language-typescript support for fragment references
  */
 
-/**
- * @private
- */
 export interface _RefType<Ref extends string> {
     ' $refType': Ref;
 }
 
-/**
- * @private
- */
 export interface _FragmentRefs<Refs extends string> {
     ' $fragmentRefs': FragmentRefs<Refs>;
 }
```

I don't know what the comment is for though :laughing: so I'd rather lean towards fixing the lint break.  I confirmed it does pass lint after this diff

What do you think?

2020-03-17 23:24 UTC, renanmav approved these changes

2020-03-18 00:19 UTC, Stephen2 requested changes

2020-03-18 00:19 UTC, Stephen2 commented on types/relay-runtime/tslint.json
> +        "no-redundant-jsdoc-2": false
Let's drop this commit before merging

2020-03-18 01:02 UTC, Stephen2 approved these changes
Perfect, thanks so much for taking the time :heart:

2020-03-18 06:30 UTC, mrtnzlml approved these changes

2020-03-18 10:31 UTC, merged