MUI-Datatables: Update to let text labels be optional.
DefinitelyTyped/DefinitelyTyped pull request #43183
Opened 2020-03-17 16:18 UTC by jdetle

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/gregnb/mui-datatables/blob/master/src/MUIDataTable.js#L285

Its deep merging defaults with provided options so it is natural to make this a partial.

2020-03-17 18:23 UTC, favna requested changes
Just a tiny change extra and revert the auto-formatter changes (this will probably also fix the Travis build as it removes the trailing comma).

2020-03-17 18:23 UTC, Favna commented on types/mui-datatables/index.d.ts
> +        filterOptions: { useDisplayedColumnsOnly?: boolean; useDisplayedRowsOnly?: boolean };
```suggestion
        filterOptions: Partial<{ useDisplayedColumnsOnly: boolean; useDisplayedRowsOnly: boolean }>;
```

If we're going to use the Partial helper type anyway

2020-03-17 18:23 UTC, Favna commented on types/mui-datatables/index.d.ts
> +        setSelectedRows: (rows: number[]) => void,
```suggestion
        setSelectedRows: (rows: number[]) => void
```

2020-03-17 18:23 UTC, Favna commented on types/mui-datatables/index.d.ts
> +        options: any,
```suggestion
        options: any
```

2020-03-17 18:23 UTC, Favna commented on types/mui-datatables/index.d.ts
> +        },
```suggestion
        }
```

2020-03-17 18:23 UTC, Favna commented on types/mui-datatables/index.d.ts
> +    ) => string | React.ReactNode;
```suggestion
    customBodyRender?: (value: any, tableMeta: MUIDataTableMeta, updateValue: (s: any, c: any, p: any) => any) => string | React.ReactNode;
    customHeadRender?: (columnMeta: MUIDataTableCustomHeadRenderer, updateDirection: (params: any) => any) => string | React.ReactNode;
```

2020-03-17 18:23 UTC, Favna commented on types/mui-datatables/index.d.ts
> +    displayData: Array<{ dataIndex: number; data: any[] }>;
```suggestion
    displayData: Array<{dataIndex: number; data: any[]}>;
```

2020-03-17 18:23 UTC, Favna commented on types/mui-datatables/index.d.ts
> +        cellMeta: { colIndex: number; rowIndex: number; dataIndex: number; event: React.MouseEvent },
```suggestion
        cellMeta: { colIndex: number; rowIndex: number; dataIndex: number; event: React.MouseEvent }
```

2020-03-17 18:48 UTC, karlasantos commented
Hi! I have been trying to use customFooter of MUIDataTableOptions and looks different of usage in package mui-datatables since v2.9.0. Is there any chance of mapping the changes in @types/mui-datatables? 
Sorry for my english.

2020-03-17 21:42 UTC, Favna commented
@karlasantos Everyone can contribute to this repository as they see fit and I recommend you do just that if you want changes to be made to the typings information.

2020-03-17 22:51 UTC, karlasantos commented
@Favna okay, I will do that, thanks.

2020-03-20 20:14 UTC, jdetle commented
I’ll get on it this weekend, thanks

2020-03-23 17:40 UTC, jdetle commented
@favna thanks for the review suggestions, saved me a bit of time. That work is done.

2020-03-23 22:23 UTC, favna requested changes
Just 1 small one left

2020-03-23 22:23 UTC, Favna commented on types/mui-datatables/index.d.ts
> +        filterOptions: Partial<{ useDisplayedColumnsOnly: boolean; useDisplayedRowsOnly?: boolean }>;
```suggestion
        filterOptions: Partial<{ useDisplayedColumnsOnly: boolean; useDisplayedRowsOnly: boolean }>;
```

2020-03-23 22:23 UTC, Favna commented on types/mui-datatables/index.d.ts
> +        filterOptions: Partial<{ useDisplayedColumnsOnly: boolean; useDisplayedRowsOnly?: boolean }>;
The `?` is not needed since it's already `Partial<>`

2020-03-24 17:06 UTC, favna approved these changes

2020-03-29 17:55 UTC, jdetle commented
@typescript-bot can you remove the revision needed label?

2020-03-29 19:29 UTC, Favna commented
@orta been 5 days since the approval, tagging you since it would be nice if it could get merged.

2020-03-30 12:58 UTC, orta commented
Cool, seems good to me

2020-03-30 12:58 UTC, merged