Add defined() method and align default schema types with yup logic
DefinitelyTyped/DefinitelyTyped pull request #43181
Opened 2020-03-17 15:07 UTC by DASPRiD

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jquense/yup/commit/ad0f07394bdbbcb033d644c472fc393147b28aa8
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

In general: yup added the `defined()` method to the mixed type, from which every other type extends. This test ensures that a schema value is either null or the concrete type.

While doing this update, I also noted t hat the default for every type is actually not just the type (string, number, etc), but `unedfined` as well. I've updated the schema and the tests to reflect that accordingly.

2020-03-18 07:45 UTC, mauricedb requested changes
Adding the `defined()` function is fine, that one was missing.

However the change to defaulting to `undefined` is not. The semantics of a required property in Yup is not the same as in TypeScript. See the explanation below that is still an open PR on the Yup documenttaion.


### Why does InferType not default to nonRequired()?

This was considered when inplementing `InferType<T>` but decided against.

First of all 
The semantics of a required property in Yup is not the same as in TypeScript. For example a `Yup.array().of(Yup.string()).required()` will fail validation if you pass in an empty array. A required array should not be empty: [empty arrays are also considered 'missing' values](#arrayrequiredmessage-string--function-schema). The same is true for a `Yup.string().required()` where passing in an empty string `""` is considered invalid while an not empry string `"hello"` is considered valid. With TypeScript both would satisfy required. Another example of that is a `Yup.date()` that will pass validation if you use the string `"2020-02-14T07:52:25.495Z"` if you don't call `.strict()`.

In general there isn't a one to one match between Yup and TypeScript concepts so this is never going to be perfect.

2020-03-18 11:48 UTC, DASPRiD commented
Hm, the points you describe seem to be about input / semantic validation, while these changes would instead affect only the output types of `validate()` or `cast()`, or am I missing something here?

E.g. it is true that `Yup.string().required()` will always yield `string`, but `Yup.string()` can return `string` or `undefined`. As for your date example, it is true that it also accepts strings in the input, but the output can be both `Date` and `undefined` without `required()`.

2020-03-18 20:54 UTC, mauricedb commented
With your change the following code would compile while it doesn't at the moment:

```ts
const personSchema = yup.object({
  firstName: yup.string()
});

type Person = yup.InferType<typeof personSchema>;

const person: Person = {
  firstName: undefined
};
```

That sounds great, if you want `firstName` to be a `string` and not `undefined` you could change the schema to:
```ts
const personSchema = yup.object({
  firstName: yup.string().required()
});
```

Now the person above would trigger a compile error which you could fix like this:
```ts
const person: Person = {
  firstName: ""
};
```

However this object is invalid acording to Yup as `required()` rejects an empty string as a non valid value. So `console.log(personSchema.isValidSync(person));` would print false.

So there is no way to enforce a string type and still let that be an empty string.

2020-03-18 23:47 UTC, DASPRiD commented
Well, right, but without my changes, you can still define an empty string and `required()` would tell that it's not valid. So how exactly are my changes making this situation worse instead of better? :)

The way I see it, we gain **type** safety, semantic safety is of course outside the scope of TypeScript.

2020-03-19 12:48 UTC, mauricedb commented
> semantic safety is of course outside the scope of TypeScript

That may be so but it is very mutch in scope with Yup. And the two are not perfect matches. If creating a type that must be a string disables validating an empty string I will remain against this change.

I will leave this up to the other constributors make a call.

2020-03-25 08:27 UTC, closed without merging