[mongoose] pre and post hooks' method param can be array
DefinitelyTyped/DefinitelyTyped pull request #43302
Opened 2020-03-21 20:47 UTC by rifler

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://mongoosejs.com/docs/api.html#schema_Schema-pre
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-03-21 20:47 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "missing",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 20:47 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "missing",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 20:47 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "missing",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 20:47 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "missing",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 20:47 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "missing",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 20:47 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ❌ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "missing",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": false
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 21:02 UTC, ToucheSir requested changes
Needs tests as @orta mentioned. Otherwise LGTM.

2020-03-21 21:22 UTC, orta commented
@rifler One or more reviewers has requested changes. Please address their comments. I'll be back once they sign off or you've pushed new commits or comments. If you disagree with the reviewer's comments, you can "dismiss" the review using GitHub's review UI. Thank you!
<!--typescript_bot_complaint-d3fff79-->

2020-03-21 21:22 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ✅ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "pass",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": true
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 21:22 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ✅ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "pass",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": true
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 21:22 UTC, orta commented
@rifler One or more reviewers has requested changes. Please address their comments. I'll be back once they sign off or you've pushed new commits or comments. If you disagree with the reviewer's comments, you can "dismiss" the review using GitHub's review UI. Thank you!
<!--typescript_bot_complaint-d3fff79-->

2020-03-21 21:22 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ✅ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "pass",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": true
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 21:22 UTC, orta commented
@rifler One or more reviewers has requested changes. Please address their comments. I'll be back once they sign off or you've pushed new commits or comments. If you disagree with the reviewer's comments, you can "dismiss" the review using GitHub's review UI. Thank you!
<!--typescript_bot_complaint-d3fff79-->

2020-03-21 21:22 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ✅ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "pass",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": true
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 21:22 UTC, orta commented
@rifler One or more reviewers has requested changes. Please address their comments. I'll be back once they sign off or you've pushed new commits or comments. If you disagree with the reviewer's comments, you can "dismiss" the review using GitHub's review UI. Thank you!
<!--typescript_bot_complaint-d3fff79-->

2020-03-21 22:22 UTC, orta commented
@rifler Thank you for submitting this PR!  I see this is your first time submitting to DefinitelyTyped 👋 - keep an eye on this comment as I'll be updating it with information as things progress.

 This PR doesn't modify any tests, so it's hard to know what's being fixed, and your changes might regress in the future. Have you considered adding tests to cover the change you're making? Including tests allows this PR to be merged by yourself and the owners of this module.

## Code Reviews

Because this is a widely-used package, a DT maintainer will need to review it before it can be merged.

🔔 @horiuchi @lukasz-zak @Alorel @jendrikw @ethanresnick @vologab @jussikinnula @ondratra @alfirin @idandrd @various89 @Fazendaaa @NormanPerrin @stablio @emmanuelgautier @frontendmonster @mingchen @penumbra1 @orblazer @HughKu @niuware @vladmel1234 @jloveridge @grimmer0125 @richarddd @ToucheSir @borfig @dinodeSimon @anthony-kenikh @iamchathu @lkho @tomyam1 @nephix @rlaace423 @ChazEpps @avaly @JanNemcik - please [review this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files) in the next few days. Be sure to explicitly select **`Approve`** or **`Request Changes`** in the GitHub UI so I know what's going on.

## Status

 * ✅ No merge conflicts
 * ✅ Continuous integration tests have passed
 * ❌ Only a DT maintainer can merge changes without tests

Once every item on this list is checked, I'll ask you for permission to merge and publish the changes.

----------------------
<details><summary>Diagnostic Information: What the bot saw about this PR</summary>

```json
{
  "type": "info",
  "pr_number": 43302,
  "author": "rifler",
  "owners": [
    "horiuchi",
    "lukasz-zak",
    "Alorel",
    "jendrikw",
    "ethanresnick",
    "vologab",
    "jussikinnula",
    "ondratra",
    "alfirin",
    "idandrd",
    "various89",
    "Fazendaaa",
    "NormanPerrin",
    "stablio",
    "emmanuelgautier",
    "frontendmonster",
    "mingchen",
    "penumbra1",
    "orblazer",
    "HughKu",
    "niuware",
    "vladmel1234",
    "jloveridge",
    "grimmer0125",
    "richarddd",
    "ToucheSir",
    "borfig",
    "dinodeSimon",
    "anthony-kenikh",
    "iamchathu",
    "lkho",
    "tomyam1",
    "nephix",
    "rlaace423",
    "ChazEpps",
    "avaly",
    "JanNemcik"
  ],
  "dangerLevel": "ScopedAndUntested",
  "headCommitAbbrOid": "d3fff79",
  "headCommitOid": "d3fff79defd0abe6d31a4de325a41c32a9794465",
  "mergeIsRequested": false,
  "stalenessInDays": 0,
  "lastCommitDate": "2020-03-21T20:46:40.000Z",
  "reviewLink": "https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43302/files",
  "hasMergeConflict": false,
  "authorIsOwner": false,
  "isFirstContribution": true,
  "popularityLevel": "Popular",
  "anyPackageIsNew": false,
  "packages": [
    "mongoose"
  ],
  "files": [
    {
      "filePath": "types/mongoose/index.d.ts",
      "kind": "definition",
      "package": "mongoose"
    }
  ],
  "otherApprovalCount": 0,
  "ownerApprovalCount": 0,
  "maintainerApprovalCount": 0,
  "hasDismissedReview": false,
  "travisResult": "pass",
  "reviewersWithStaleReviews": [],
  "approvalFlags": 0,
  "isChangesRequested": true
}
```

</details>
<!--typescript_bot_welcome-->

2020-03-21 22:22 UTC, orta commented
@rifler One or more reviewers has requested changes. Please address their comments. I'll be back once they sign off or you've pushed new commits or comments. If you disagree with the reviewer's comments, you can "dismiss" the review using GitHub's review UI. Thank you!
<!--typescript_bot_complaint-d3fff79-->

2020-03-22 12:57 UTC, orta commented
Sorry folks - actual human here, we're working on an auto-merging DT bot, which had my access token by mistake instead of the real one which I think really threw it for a loop overnight. _Should_ be better now.

2020-03-26 12:21 UTC, rifler commented
I'll try soon

2020-03-28 21:27 UTC, closed without merging