add SecureBuffer secure attribute to sodium-native
DefinitelyTyped/DefinitelyTyped pull request #43324
Opened 2020-03-23 16:53 UTC by nshCore

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://sodium-friends.github.io/docs/docs/memoryprotection#sodium_malloc
https://github.com/sodium-friends/sodium-native/blob/master/test/memory.js#L81
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

Sodium-natives malloc function that secures a buffer adds a new property to buffer object called 

"secure"

`buffer.secure `

which is a boolean indicating if the buffer is secure or not, this is not present in the type defs from this repo.

@SEE https://github.com/sodium-friends/sodium-native/blob/master/test/memory.js#L81
@SEE https://sodium-friends.github.io/docs/docs/memoryprotection#sodium_malloc

there is also functions that "have no effect on normal buffers" these function params have been updated to allow the "SecureBuffer" type

2020-03-23 18:34 UTC, ffflorian requested changes

2020-03-23 18:34 UTC, ffflorian commented on types/sodium-native/index.d.ts
> +     * To check if a buffer is a "secure" buffer, you can call access the getter buffer.secure which will be true
```suggestion
     * To check if a `buffer` is a "secure" `buffer`, you can access the getter `buffer.secure` which will be `true`.
```

2020-03-24 12:06 UTC, nshCore commented on types/sodium-native/index.d.ts
> +     * To check if a buffer is a "secure" buffer, you can call access the getter buffer.secure which will be true
Thanks added the suggestions.

2020-03-24 20:22 UTC, ffflorian approved these changes

2020-03-24 20:23 UTC, ffflorian requested changes

2020-03-24 20:23 UTC, ffflorian commented on types/sodium-native/index.d.ts
> +// Definitions by: nshcore <https://github.com/nshcore>
```suggestion
                   nshcore <https://github.com/nshcore>
```

2020-03-31 12:27 UTC, closed without merging

2020-03-31 12:41 UTC, ffflorian commented
Re-opened this under https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43514.