[types/@passport]: fix property 'x' does not exist on type 'User'
DefinitelyTyped/DefinitelyTyped pull request #43513
Opened 2020-03-31 11:37 UTC by urbanishimwe

when getting properties from req.user returned after passport authentication, an error is thrown by TypeScript
**example this code:**
```
const { user: { accessToken, profile } } = req;
```
or
```
const { accessToken, profile } = req.user;
```
**will throw Error:**
```
TSError: ⨯ Unable to compile TypeScript:
file.ts:9:19 - error TS2339: Property 'accessToken' does not exist on type 'User'.
file.ts:9:32 - error TS2339: Property 'profile' does not exist on type 'User'.
```

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-03-31 14:08 UTC, kstiehl commented
Sure it works but know the TS Compiler will allow everything on the User Interface. `User.whatever` suddenly exists. The user interface is now like a complicated written `Any`

Why don't we just add the two properties that are currently missing.

2020-03-31 18:28 UTC, vaskevich requested changes
Please don't do this - let's not encourage `any` types in the codebase. For more context, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/37381.

The preferred approach (linked from that PR) is https://github.com/DefinitelyTyped/DefinitelyTyped/commit/91c229dbdb653dbf0da91992f525905893cbeb91#r34812715

2020-03-31 22:03 UTC, vaskevich commented
Where do these new properties come from? If they’re specific to your project, you should declare them within a global types file there.

2020-03-31 22:07 UTC, urbanishimwe commented
> Where do these new properties come from? If they’re specific to your project, you should declare them within a global types file there.

just realized that I can add only those two which are very necessary, others can be extended since they are only specific to the provider of OAuth

2020-04-01 00:46 UTC, vaskevich commented on types/passport/index.d.ts
> +            accessToken?: string;
I can't find `accessToken` or `refreshToken` in `passport`, so this shouldn't get defined in `@types/passport`.

https://github.com/jaredhanson/passport/search?q=accesstoken&unscoped_q=accessToken

2020-04-01 06:04 UTC, closed without merging