[react-query] Few improvements
DefinitelyTyped/DefinitelyTyped pull request #43568
Opened 2020-04-02 05:18 UTC by Igorbek

This is a follow-up PR to #43438

Addresses the comment https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43438#pullrequestreview-385315027

- allow single string key in object syntax
- reorder overloads to fix intellisense
- add more tests
- rename a single string key type parameter ~~`TKey`~~`TSingleKey`

2020-04-03 07:18 UTC, lednhatkhanh reviewed
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4e480b0552a7b663b430e03f797df224d47064a9/types/react-query/index.d.ts#L225

`initialData` can also be a function, could you please consider changing this as well?

Also, it should be `TResult[]` in `useInfiniteQuery`

2020-04-03 17:31 UTC, uniqueiniquity requested changes
Marking as changes requested until issues raised by @lednhatkhanh are addressed.

2020-04-04 00:16 UTC, uniqueiniquity approved these changes

2020-04-04 00:16 UTC, merged

2020-04-04 10:30 UTC, lednhatkhanh commented
Thanks @Igorbek for your hard work, the library is extremely verbose thus really hard to type but you made it 👍

2020-04-08 13:18 UTC, julianwachholz commented
Is there a work in progress on adding `canFetchMore` to the result of the `useInfiniteQuery` hook?

2020-04-17 15:49 UTC, thebuilder commented
Looking really good @Igorbek - Tried to use the `retry` in a `useQuery` and noticed it's missing the function implementation.

```
retry: Boolean | Int | Function(failureCount, error) => shouldRetry | Boolean
```
https://github.com/tannerlinsley/react-query#options

The `retry` should be exapanded with: 
```ts
retry: (failureCount: number, error: unknown) => boolean;
```

2020-04-17 15:52 UTC, mustafawm commented
FYI, there is a discussion about shipping TS in the library itself https://github.com/tannerlinsley/react-query/discussions/362