Feature/add typings for feflow cli
DefinitelyTyped/DefinitelyTyped pull request #43565
Opened 2020-04-02 03:10 UTC by nikewu

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2020-04-02 17:27 UTC, uniqueiniquity requested changes
It seems like `@feflow/cli` bundles and ships its own type declaration files, so they should not be included on DefinitelyTyped.

2020-04-03 05:21 UTC, nikewu commented
> It seems like `@feflow/cli` bundles and ships its own type declaration files, so they should not be included on DefinitelyTyped.


Thanks for your comment `@feflow/cli` is a cli tool and has a plug-in mechanism. The declaration file of the project itself does not contain the tool execution context. This supplementary declaration file is used to assist in the development of `@feflow/cli` plug-ins.

 The development of `@feflow/cli` plugin does not need to depend on the installation of `@ feflow/cli` but requires the running context of `@feflow/cli`

2020-04-04 00:17 UTC, uniqueiniquity approved these changes

2020-04-04 00:18 UTC, uniqueiniquity commented
Congratulations on your first DefinitelyTyped contribution!
Thank you for being a part of the community!

2020-04-04 00:18 UTC, merged