google-apps-script CardService update
DefinitelyTyped/DefinitelyTyped pull request #43858
Opened 2020-04-13 14:45 UTC by pierluigi-montagna

I've added missing definitions on the CardService for the package google-apps-script.

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://developers.google.com/apps-script/reference/card-service/card-service>>

2020-04-14 07:33 UTC, PopGoesTheWza requested changes
Please use an indentation of two spaces, hence enabling manageable diff and making review possible.
TIA.

2020-04-15 06:36 UTC, pierluigi-montagna commented
> Please use an indentation of two spaces, hence enabling manageable diff and making review possible.
> TIA.

I've used indentation with 2 spaces.
Just a little note: I've followed the recommended steps and it says that the indentation should be 4, is it ok ?

> Formatting: Use 4 spaces. Prettier is set up on this repo, so you can run npm run prettier -- --write

2020-04-16 21:32 UTC, PopGoesTheWza requested changes
Have you used <https://github.com/PopGoesTheWza/dts-google-apps-script> to assist you in writing this PR?

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +    enum TextButtonStyle {
keep as single line please

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +    enum SelectionInputType {
keep as single line please

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +    enum OpenAs {
keep as single line please

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +    enum OnClose {
keep as single line please

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +    enum LoadIndicator {
keep as single line please

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +    enum ImageStyle {
keep as single line please

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +    enum Icon {
keep as single line please

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +    enum ContentType {
keep as single line please

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +    enum ComposedEmailType {
keep as single line please

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +    import ConferenceData = GoogleAppsScript.Calendar.Schema.ConferenceData;
avoid `import` statements in `.d.ts` files.

insert between lines 7 & 8 the following triple-slash directive:

```typescript
/// <reference path="google-apps-script.conference-data.d.ts" />
```

2020-04-16 21:32 UTC, PopGoesTheWza commented on types/google-apps-script/google-apps-script.card-service.d.ts
> +      setConferenceData(conferenceData: ConferenceData): CalendarEventActionResponseBuilder;
should be `setConferenceData(conferenceData: Conference_Data.ConferenceData): CalendarEventActionResponseBuilder;`

2020-04-19 16:56 UTC, pierluigi-montagna commented
> Have you used https://github.com/PopGoesTheWza/dts-google-apps-script to assist you in writing this PR?
Sorry didn't know about the tool ! really helpful, probably missed it in the readme. 
It did a lot of changes on other files though, so I've just taken what I need and kept the style and everything else as it was before :)

2020-04-30 21:27 UTC, PopGoesTheWza approved these changes

2020-04-30 21:28 UTC, PopGoesTheWza commented
@pierluigi-montagna sorry for the late review.

2020-04-30 22:03 UTC, PopGoesTheWza approved these changes

2020-05-04 16:58 UTC, merged