remove triples
DefinitelyTyped/DefinitelyTyped pull request #43914
Opened 2020-04-15 09:06 UTC by larsrh

Triples are not specified in the RDF/JS standards.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - _Comment_: Triples are not specified in [the spec](http://rdf.js.org/data-model-spec/). The Graphy library, which is otherwise spec-compliant, provides the `triple` method but prints a warning.
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
  - _Comment_: it aligns the type definitions with the spec, but I'm unsure how the spec is versioned. As it's a breaking change, I'm assuming a major bump is necessary.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

2020-04-15 09:24 UTC, rubensworks requested changes
This is a breaking change in the rdf-js typings, so the major version should be incremented.

2020-04-15 09:26 UTC, tpluscode commented
And do you agree with the change in general @rubensworks?

After all, the spec does mention triple where it says 

> Triple MUST be represented as Quad with graph set to a DefaultGraph

in the [Quad interface](http://rdf.js.org/data-model-spec/#quad-interface) section even though it's not a thing on any of the interfaces

2020-04-15 09:27 UTC, larsrh commented
@tpluscode I'm aware of that phrasing in the section. It's just that the spec doesn't mandate a particular `triple` method that generates them. Users are supposed to use the `quad` method with the final argument left undefined.

2020-04-15 09:29 UTC, tpluscode commented
Sure. I was not there when the spec was written in its current form. I wonder if that statement is a remnant of something that used to be there or an incomplete work?

In the latter case I'd expect the spec to require changes and not the typings. cc @bergos

2020-04-15 09:29 UTC, larsrh commented
@rubensworks Agreed, but please excuse the stupid question: How do I do that? I didn't find a version field anywhere.

2020-04-15 09:30 UTC, tpluscode commented
> I didn't find a version field anywhere.

It's in the header of `index.d.ts`

2020-04-15 09:30 UTC, rubensworks commented
Yes, I agree with the change. The `triple` method has been removed from the spec more than a year ago: https://github.com/rdfjs/data-model-spec/pull/153
The note in the Quad interface section seems like a leftover comment, and should probably be removed.

2020-04-15 09:33 UTC, larsrh commented
I've bumped the version number to 3.0.

2020-04-15 10:01 UTC, larsrh commented
While I'm proposing a breaking change: I've also noticed another difference between spec and types. According to the spec, the `equals` method on quads needs to take `null | undefined` into account:

```
interface Quad {
  attribute Term subject;
  attribute Term predicate;
  attribute Term object;
  attribute Term graph;
  boolean equals(optional Quad? other);
};
```

But the types say:

```
export interface BaseQuad {
  subject: Term;
  predicate: Term;
  object: Term;
  graph: Term;
  equals(other: BaseQuad): boolean;
}
```

Should I roll a patch for this into the PR?

2020-04-15 10:05 UTC, tpluscode commented
Maybe we could fix that separately for 2.x still and only then do the breaking change? Updating `@types/rdf-js` is going to be a bit of work...

2020-04-15 10:08 UTC, larsrh commented
This would also constitute a breaking change, because I'm extending the argument types of an existing interface (i.e. interface implementors need to consider additional kinds of values).

2020-04-15 10:12 UTC, tpluscode commented
I would only consider the consumer's end. For the caller that would not be a breaking change, as you are expanding the argument space.
And IMO, `null/undefined` is always an option. I don't think any implementor would have safely ignored them.

2020-04-15 10:13 UTC, larsrh commented
Fair enough. I can file a separate PR without bumping the version, if that's the consensus.

2020-04-15 11:11 UTC, rubensworks commented
I like the idea of including other (necessary) breaking changes in this PR, so perhaps we could leave this PR open for a bit.

I agree with the `equals` change, and I consider this a breaking change, as it could break for implementors of `DataFactory` when `strictNullChecks` is enabled.

One other thing that could be included in this PR of breaking changes is the removal of union types, as this has proven to cause problems in implementations: https://github.com/linkeddata/rdflib.js/issues/397
\cc @RubenVerborgh

2020-04-15 11:13 UTC, RubenVerborgh commented
The problem of https://github.com/linkeddata/rdflib.js/issues/397 seems to have been mitigated, so I don't think any action is needed. Will check.

2020-04-15 11:18 UTC, larsrh commented
> I agree with the `equals` change, and I consider this a breaking change, as it could break for implementors of `DataFactory` when `strictNullChecks` is enabled.

In particular, it seems that rdflib appears to have the `Term` type declared as follows:

```
export interface Term {
  termType: string
  value: string

  /**
   * Compare this term with {other} for structural equality
   *
   * Note that the task force spec only allows comparison with other terms
   */
  equals (other: Term): boolean
}
```

2020-04-15 11:22 UTC, larsrh commented
(Hid previous comment because it was wrong.)

2020-04-16 08:21 UTC, larsrh commented
@rubensworks I've added another commit with the `equals` change and no other package broke.

From my end, this PR is good to go.

2020-04-16 08:27 UTC, rubensworks commented
Looks good to me.

But before merging, let's wait until we are sure that no other breaking change is required for https://github.com/linkeddata/rdflib.js/issues/397.

2020-04-20 14:47 UTC, RubenVerborgh commented
@rubensworks https://github.com/linkeddata/rdflib.js/issues/397 has been closed without further objections, so we can move this one.

2020-04-20 14:54 UTC, rubensworks approved these changes

2020-04-26 16:18 UTC, merged