Fix Webpack hot middleware definition
DefinitelyTyped/DefinitelyTyped pull request #44047
Opened 2020-04-20 13:04 UTC by joel-44

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/webpack-contrib/webpack-hot-middleware#config
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

This fixes this problem https://github.com/webpack-contrib/webpack-hot-middleware/issues/380

2020-04-20 16:03 UTC, saboya approved these changes
*edit* - Misclick, didn't want to approve this.

2020-04-20 16:03 UTC, saboya requested changes
You can just simply import ClientOptions or MiddlewareOptions, why do you need to rename the export? And, why rename ClientOptions and not MiddlewareOptions?

2020-04-20 16:21 UTC, joel-44 commented
as I think it was mentioned on your PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43625 
this change is breaking all the dependencies importing Options, I am not using it directly but it is a subdependency..

I have seen other people having the same issue https://github.com/webpack-contrib/webpack-hot-middleware/issues/380

If you have another solution to solve the issue please tell me but right now I have a project broken due to this

2020-04-20 16:30 UTC, joel-44 commented
ok, nevermind I just noticed I have to force a minor update on nuxt.. I will close it

2020-04-20 17:49 UTC, lukasborawski commented
@joel-44 have the same issue in nuxt, how to resolve this?

2020-04-20 18:05 UTC, joel-44 commented
I had to force nuxt version to "nuxt": "^2.12.2"
to me that was an unnecessary breaking change but this fix it..

2020-04-20 18:05 UTC, closed without merging

2020-04-20 19:37 UTC, lukasborawski commented
Not for me, I've changed the source, but this is the worst scenario.

2020-04-21 16:38 UTC, Mohib834 commented
@lukasborawski  Hey did you get the way to fix this issue ?

2020-04-26 20:13 UTC, lukasborawski commented
Locally yeah, I've made a change in the source code, but this very bad solution - any other npm update will reveal this error again. This sucks! And the issue hanging ... @glenjamin Help!

2020-04-26 23:14 UTC, Mohib834 commented
@lukasborawski I have fixed this issue by downgrading the @types/webpack-hot-middleware.

2020-04-27 08:03 UTC, lukasborawski commented
@Mohib834 to which version?

2020-04-27 11:12 UTC, Mohib834 commented
@lukasborawski 2.25.0

2020-04-27 11:49 UTC, stas-kh commented
Hey guys, I face the same issue in my Nuxt project after updating all the packages. We need a fix

2020-04-27 13:23 UTC, Mohib834 commented
@stas-kh for now, you can try upgrading nuxt and downgrading @types/webpack-hot-middleware to 2.25.0

2020-04-27 15:07 UTC, H6LS1S commented
I face the same issue

Didn't work for me:
> I had to force nuxt version to "nuxt": "^2.12.2"
> to me that was an unnecessary breaking change but this fix it..

2020-04-28 00:32 UTC, Mohib834 commented
@H6LS1S Along with the nuxt upgrade try downgrading @types/webpack-hot-middleware to 2.25.0