[@types/node] Add fs/promises alias module (Node 14 addition)
DefinitelyTyped/DefinitelyTyped pull request #44177
Opened 2020-04-24 14:52 UTC by Jamesernator

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

This adds the `fs/promises` [module](https://nodejs.org/api/fs.html#fs_fs_promises_api) that is newly added in Node 14. This module is simply an alias for `fs.promises`.

Currently the tests are broken, but I'm not sure how to fix it as it only affects TypeScript 3.1.

2020-04-24 15:42 UTC, SimonSchick requested changes
Hey, this change (not the same but same intent) is already included here: https://travis-ci.org/github/DefinitelyTyped/DefinitelyTyped/builds/678775960

Would you mind reviewing mine instead?

2020-04-24 16:20 UTC, peterblazejewicz commented
That's not really helpful when the commit messages are missing:
https://gist.github.com/mikepea/863f63d6e37281e329f8#describe-your-changes-well-in-each-commit

2020-04-24 16:48 UTC, SimonSchick commented
I find `feat(node): v14` rather self descriptive (although very short), what would you rather see?
Something like `feat(node): update types to v14`?

2020-04-24 17:43 UTC, peterblazejewicz commented
Agree, reffering just to `.`
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44177/commits/97df575c8ecf7c4d66d75f18e6f1f46253f7993d

2020-04-24 17:49 UTC, SimonSchick commented
OH I thought you were talking about my commit message 🤦

2020-04-26 04:00 UTC, Jamesernator commented
> Hey, this change (not the same but same intent) is already included here: https://travis-ci.org/github/DefinitelyTyped/DefinitelyTyped/builds/678775960
>
> Would you mind reviewing mine instead?

Yep this PR is redundant.

2020-04-26 04:00 UTC, closed without merging