[express] change default generic type of ReqQuery to any and Query type should accept undefined
DefinitelyTyped/DefinitelyTyped pull request #44173
Opened 2020-04-24 08:43 UTC by kpping

The latest v4.17.4 introduce 1 breaking change and 1 bug.

1. The default value of generic for ReqQuery is Query. It breaks some codebase that have already implemented their own type casting.

```ts
# example
export type ReqParam = { category: string };

export interface MyCustomRequest extends Request<ReqParam > {
    query: {
        sort?: 'asc' | 'desc';
    };
}

export const myRequestHandler: RequestHandler<ReqParam> = (
    req: MyCustomRequest ,
    res,
    next,
) => {
    req.params.category // string
    req.query.sort // undefined or 'asc' or 'desc'
};
```

2. Express.js doesn't guarantee value from `req.query`, so `undefined` value is be possible.

```ts
req.query.foobar // it may be undefined or string or string[]
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-05-04 23:29 UTC, weswigham commented
@OliverJAsh @puneetar would you two like to weigh in here? I'm not a fan of adding an `any` anywhere, myself.

2020-05-04 23:32 UTC, weswigham commented
Context comment: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43434#issuecomment-607181516

The `any` breakage is super intentional, however you may want to comment on the `undefined` case, maybe.

2020-05-05 10:09 UTC, OliverJAsh commented
> The `any` breakage is super intentional

Correct



> you may want to comment on the `undefined` case

You're right that an index lookup could return `undefined`:

```
const foo = req.query['foo'];
// `undefined` if there is no `foo` query param 
```

However, this is really a bug with TS and I don't believe we should fix this by adding `undefined` to the type. I explained why in my comment here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43434#discussion_r403904757.

2020-05-05 10:09 UTC, OliverJAsh requested changes
As per comments above.

2020-05-09 04:38 UTC, kpping commented
Close because type Query is now inferred by reference to ParsedQs from qs lib. I wil PR the idea to qs lib instead.

2020-05-09 04:38 UTC, closed without merging

2020-05-09 06:00 UTC, OliverJAsh commented
The qs type used to be any, I just had a PR merged that switched it to a
strong type. It sounds like you're asking for that to be reverted? If so
that would be a step backwards.

On Sat, 9 May 2020, 05:39 Krittanan Pingclasai, <notifications@github.com>
wrote:

> Close because type Query is now inferred by reference to ParsedQs from qs
> lib. I wil PR the idea to qs lib instead.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44173#issuecomment-626104805>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHBACOZIKDIG2DRDYWBI4LRQTM6TANCNFSM4MP5BBSA>
> .
>

2020-05-09 06:31 UTC, kpping commented
hi @OliverJAsh ,

I got the idea and I also like strong typing but isn't this lead to another misleading problem ?

'req.query.foobar' will always be 'string | string[]' even though it might not present.

How can we notice this kind of mistake ?

Thank you.