@types/yargs: yargs#showHelp accepts a callback
DefinitelyTyped/DefinitelyTyped pull request #44444
Opened 2020-05-02 17:45 UTC by NCPlayz

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/yargs/yargs/blob/master/docs/api.md#showhelpconsolelevel--printcallback>
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

2020-05-02 18:08 UTC, pushplay requested changes
Thanks for adding the test.  Just needs a slight improvement.

2020-05-02 18:08 UTC, pushplay commented on types/yargs/index.d.ts
> +        showHelp(printCallback: (s: any) => void): Argv<T>;
The documentation indicates that `s` should be a string.

2020-05-02 18:29 UTC, forivall approved these changes
Lgtm

2020-05-02 18:57 UTC, pushplay approved these changes

2020-05-04 19:08 UTC, forivall approved these changes

2020-05-13 21:45 UTC, merged