[node-downloader-helper] Upgrade missing methods and events
DefinitelyTyped/DefinitelyTyped pull request #44545
Opened 2020-05-07 12:09 UTC by Roberto-Araujo

Upgrade missing methods, events, options and interfaces

2020-05-07 20:39 UTC, RemyJeancolas commented on types/node-downloader-helper/index.d.ts
> +    on(event: 'download' | 'end', callback: (downloadInfo: DownloadInfo) => void): this;
According to the module's README, it looks like the `DownloadInfo` objects from the **download** and the **end** events are slightly different.

The `DownloadInfo` objet for a **download** event has a `isResumed` property that doesn't exist for the **end** event, while the **end** event has a `onDiskSize` property that doesn't exist in the **download** event.

These differences could induce uncaught errors during development if not properly added to the typescript definitions file.

2020-05-07 20:41 UTC, RemyJeancolas requested changes
Hi @Roberto-Araujo , it seems there are some errors in your typings definitions file when comparing with the official module's documentation.

2020-05-07 23:40 UTC, Roberto-Araujo commented
Hi @RemyJeancolas, I reviewed official module's documentation, fixed mentioned errors, found that 'error' event callback had an incorrect typing definition.

2020-05-09 16:25 UTC, RemyJeancolas approved these changes
Looks good to me

2020-05-13 16:18 UTC, merged