React color
DefinitelyTyped/DefinitelyTyped pull request #44685
Opened 2020-05-13 00:13 UTC by sagar7993

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-05-19 12:05 UTC, sagar7993 commented
@LKay @markspolakovs @mntdn @nkgrnkgr @0815Strohhut @dnlfrst @ErickTamayo - please review this PR :-)

2020-05-19 17:53 UTC, sheetalkamat requested changes
This is change to popular package and would need sign off from exper

2020-05-20 01:09 UTC, sagar7993 commented
@sheetalkamat Is there amy specific change you'd like me to make? Github is showing me that you have requested changes. Could you be a little bit more specific please

2020-05-21 12:12 UTC, sagar7993 commented
@sheetalkamat Please don't click on the request changes option unless you have some specific changes that you'd like me to make. If you click on request changes option, it adds the revision needed label to this PR which might lead to other reviewers to think that something is pending from my side.

Please refer to the official website
http://casesandberg.github.io/react-color/#api-onChange

As per the demos, the onChange and onChangeComplete handlers receive 2 arguments.

2020-05-24 20:55 UTC, peterblazejewicz commented on types/react-color/index.d.ts
> +export type ColorChangeHandler = (color: ColorResult, $event: React.ChangeEvent<HTMLInputElement>) => void;
This looks OK, but the authors of this DT seem to stick to dfiferent naming convention:
```suggestion
export type ColorChangeHandler = (color: ColorResult, event: React.ChangeEvent<HTMLInputElement>) => void;
```

2020-05-24 21:01 UTC, peterblazejewicz commented on types/react-color/react-color-tests.tsx
> +        console.log(color, $event);
```suggestion
    function onChange(color: ColorResult, event: React.ChangeEvent<HTMLInputElement>) {
        console.log(color, event);
```

2020-05-25 03:19 UTC, sagar7993 commented
@peterblazejewicz thanks for the review :-) I have pushed thr change as suggested by you. Please have a look.

2020-05-25 07:31 UTC, peterblazejewicz commented
/cc @ErickTamayo @nkgrnkgr @markspolakovs can you folks take a look?
(don't bother with commits, the state is now clean and focused for merge and review)

2020-05-25 16:25 UTC, ErickTamayo approved these changes

2020-05-25 16:30 UTC, sagar7993 commented
Ready to merge

2020-05-25 16:30 UTC, merged

2020-05-27 11:13 UTC, alumni commented
> As per the demos, the onChange and onChangeComplete handlers receive 2 arguments.

@sagar7993 The second argument is optional. It should be optional in the type definitions too.

2020-05-27 11:20 UTC, sagar7993 commented
@alumni From what I understand after having gone through the code, it seems that the second argument is not optional. Could you share the link to the docs/code where it is mentioned that the second argument is optional? I'd be happy to create a new PR if that's the case.

2020-05-27 11:28 UTC, sagar7993 commented
> This example: http://casesandberg.github.io/react-color/#api-color

In this example, the 2nd parameter is passed to the function, but the handler here is simply not using it. If you change the function like this -

```
handleChangeComplete = (color, event) => {
    this.setState({ background: color.hex });
    console.log(event);
};
```
You will find that the event parameter is indeed present.

2020-07-15 04:16 UTC, linxianxi commented
is a problem?   https://github.com/casesandberg/react-color/issues/738