[jest]: change default generic value to `{}`
DefinitelyTyped/DefinitelyTyped pull request #44734
Opened 2020-05-14 20:01 UTC by G-Rath

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on DefinitelyTyped, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

Addresses [comment in this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44433#issuecomment-628789936)

2020-05-14 20:08 UTC, tonyhallett approved these changes

2020-05-14 20:26 UTC, favna requested changes
~~I don't really see any good reason to do this. Can you give a good reason for your changes?~~

~~Also~~ Please properly finish up the pull request template (remove the non-relevant entries and the text that reminds you to do so)

Edit: nevermind, I didn't see the link at the bottom because you didn't edit the template fully. Please do that and I'll give my approval.

Edit 2: For clarifications. Remove the squared blocks, move the reason above.
![image](https://user-images.githubusercontent.com/4019718/81982571-5a8de000-9632-11ea-9f1f-8eeed71d1896.png)

2020-05-15 05:59 UTC, favna approved these changes

2020-05-15 07:09 UTC, r3nya approved these changes

2020-05-19 21:11 UTC, alexandcote commented
I tried to use the changes you proposed and this doesn't seem to solve the issue I raised here.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44433#issuecomment-628789936

I still get the error.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/4728325/82378728-adc9af00-99f3-11ea-9abf-52a9376c156d.png">

If I change the type for something like 
```
function requireActual<TModule extends {} = {}>(moduleName: string): TModule;
function requireMock<TModule extends {} = {}>(moduleName: string): TModule;
```

This solve the issue.

2020-05-20 05:10 UTC, tonyhallett commented
![image](https://user-images.githubusercontent.com/11292998/82406923-c4a5eb00-9a5f-11ea-9842-ff2db68c20fa.png)

It is due to the return type of the factory being unknown.

As per @alexandcote - the change below resolves the issue.

> function requireActual<TModule extends {} = {}>(moduleName: string): TModule;
function requireMock<TModule extends {} = {}>(moduleName: string): TModule;

2020-05-20 05:17 UTC, tonyhallett requested changes
Perhaps then it is the factory return type that should be changed to any and requireActual and requireModule can remain as default any.

@ExE-Boss 
Ok to change unknown to any to facilitate this change ?
`
function mock(moduleName: string, factory?: () => unknown, options?: MockOptions): typeof jest;
`
[commit introduced](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/5ce5329b565d816a5a9506a5a8671ca758ecb307)

2020-05-20 05:17 UTC, tonyhallett commented on types/jest/index.d.ts
> +    function requireActual<TModule = {}>(moduleName: string): TModule;
TModule extends {} = {}

2020-05-20 05:17 UTC, tonyhallett commented on types/jest/index.d.ts
> +    function requireMock<TModule = {}>(moduleName: string): TModule;
TModule extends {} = {}

2020-05-20 05:17 UTC, tonyhallett commented on types/jest/jest-tests.ts
> +// $ExpectType {}
Add
jest.mock('module',()=>({...jest.requireActual('module')}))

2020-06-18 04:18 UTC, closed without merging