[config] Add export for DeferredConfig class
DefinitelyTyped/DefinitelyTyped pull request #44836
Opened 2020-05-18 16:34 UTC by skrud

The node-config package's `deferConfig` function returns an instance of
`DeferredConfig`. It later uses `instanceof DeferredConfig` to see if
the value needs to be resolved. This change adds an export for
`DeferredConfig` and also updates the `deferConfig` function to return
that instance.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/lorenwest/node-config/blob/master/defer.js
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-05-18 16:38 UTC, skrud commented
This should be covered by existing tests for `deferConfig`; I can add a new test if needed.

2020-05-28 00:24 UTC, amcasey requested changes

2020-05-28 00:24 UTC, amcasey commented on types/config/defer.d.ts
> +type DeferFunction<T,R> = (this: any, origValue: T) => R;
I could be missing something obvious, but it seems like this JSDoc comment was intended for `deferConfig`?

2020-05-28 00:24 UTC, amcasey commented
Don't worry about the CI failure - it's global and we're working on it.

2020-06-27 04:08 UTC, closed without merging