sharedb – Fix missing & incorrect types
DefinitelyTyped/DefinitelyTyped pull request #44842
Opened 2020-05-18 17:22 UTC by Calyhre

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: See below
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

---

This pull request adds a few missing type declaration inside a `ShareDB.Doc`:
- [`doc.connection`](https://github.com/share/sharedb/blob/master/lib/client/doc.js#L55)
- [`doc.collection`](https://github.com/share/sharedb/blob/master/lib/client/doc.js#L57)

2020-05-18 21:16 UTC, ericyhwang reviewed
Looks good! Just had one question around `Type`, I'll approve after.

2020-05-19 08:42 UTC, Calyhre commented on types/sharedb/lib/sharedb.d.ts
> +  [key: string]: any;
I am not, but maybe others do. I asked myself if I should type the whole interface, but it would end up being weak. Unless we use type aliases maybe?

2020-05-19 19:51 UTC, ericyhwang commented on types/sharedb/lib/sharedb.d.ts
> +  [key: string]: any;
Let's leave this line out for now, then, until someone actually needs it. The methods on the types are mostly called internally in ShareDB.

Adding the index signature `[key: string]: any` now would mean that, in the future, adding the methods with tighter types would technically be a breaking change, so I think it's better to leave it out now to preserve flexibility in adding the methods.

2020-05-19 20:45 UTC, Calyhre commented on types/sharedb/lib/sharedb.d.ts
> +  [key: string]: any;
It’s in the current implementation, wouldn’t removing it right create a breaking change in itself?

2020-05-27 01:20 UTC, amcasey requested changes
Where did things land with the index signature?  If the names of the other properties are known, it's fine to declare them as `any` and refine the types later - at least the names will show up in completions.

2020-06-01 13:13 UTC, Calyhre commented
Updated with the complete interface for OT/Types. I left `[key: string]: any` as some types come with their own methods too. Tell me what you think :)

2020-06-01 13:15 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## sharedb ([<kbd>unpkg</kbd>](https://unpkg.com/browse/sharedb@latest/))
was missing the following properties:
1. Agent
1. Backend
1. Error
1. logger
1. MemoryMilestoneDB

<details>
<summary>as well as these 6 other properties...</summary>
<p>MemoryPubSub, MilestoneDB, ot, projections, QueryEmitter, SubmitRequest</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 57683f04b27199b6e731fa15a98b3bb0ae556d54
</p>

2020-06-02 00:20 UTC, amcasey commented
Thanks for the updates!  If the type has dynamic members, then a string indexer seems reasonable to me - more refined types can be given later.

2020-06-02 00:20 UTC, amcasey approved these changes

2020-06-02 07:09 UTC, Calyhre commented
Ready to merge

2020-06-02 07:09 UTC, merged