[Cesium] - fix wrong parameters on EllipsoidTangentPlane.fromPoints
DefinitelyTyped/DefinitelyTyped pull request #44899
Opened 2020-05-19 21:34 UTC by zoran995

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/CesiumGS/cesium/blob/1.69/Source/Core/EllipsoidTangentPlane.js#L141-L148>>
 [source code](https://github.com/CesiumGS/cesium/blob/1.69/Source/Core/EllipsoidTangentPlane.js#L141), [documentation](https://cesium.com/docs/cesiumjs-ref-doc/EllipsoidTangentPlane.html#.fromPoints)

2020-05-19 21:47 UTC, jrafidi approved these changes
Looks good to me. Interestingly, the Cesium docs are incorrect here and don't list the first parameter as an array.

2020-06-24 15:05 UTC, jrafidi requested changes

2020-06-24 15:05 UTC, jrafidi commented on types/cesium/index.d.ts
> +        static fromPoints(cartesians: Cartesian3[], ellipsoid: Ellipsoid): EllipsoidTangentPlane;
I think `ellipsoid` is optional based on the source and documentation

2020-06-24 15:58 UTC, elibarzilay commented
(@zoran995: I force-pushed this PR to trigger a new build.)

2020-06-30 19:31 UTC, jrafidi approved these changes

2020-06-30 20:32 UTC, peterblazejewicz approved these changes
LGTM!
I believe it was reviewed already,
@zoran995 thx!

2020-07-06 21:57 UTC, merged