[node] Mirror child_process encoding between execSync and spawnSync
DefinitelyTyped/DefinitelyTyped pull request #44952
Opened 2020-05-21 10:18 UTC by timdp

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/child_process.html
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

I'm trying to get `child_process.spawnSync()` running without the `encoding` option, which makes it default to `'buffer'` encoding.

If I don't specify the encoding, the typings say I'll get a `string`, which (per the docs) is not Node's behavior.

I dug further into the code and found this:

```typescript
interface SpawnSyncOptions extends CommonSpawnOptions {
    input?: string | NodeJS.ArrayBufferView;
    killSignal?: NodeJS.Signals | number;
    maxBuffer?: number;
    encoding?: BufferEncoding;
}
interface SpawnSyncOptionsWithStringEncoding extends SpawnSyncOptions {
    encoding: BufferEncoding;
}
interface SpawnSyncOptionsWithBufferEncoding extends SpawnSyncOptions {
    encoding: BufferEncoding; // specify `null`.
}
```

First off, I don't see why `encoding` is defined in the supertype, as it's overridden in both subtypes.

Secondly, I'm not sure what's meant by "specify null". It suggests that I should be using `{ encoding: null }` but a) `BufferEncoding` doesn't allow that and b) Node doesn't require it.

As I understand it, `encoding` should be optional if you want buffer encoding, and any of the valid encodings if you want a string. With my limited knowledge of TypeScript, I believe this PR achieves that. I applied the same change to `execSync`, which should have the same behavior.

For clarity, I didn't update any of the versioned subdirectories. (I'm not even sure I'm supposed to.) I wanted to get clarification first, so please consider this an incomplete PR.

2020-05-21 11:24 UTC, ExE-Boss requested changes
You need to keep this so that **TypeScript** doesn’t complain with:
```
TS2322: Object literal may only specify known properties, and 'encoding' does not exist in type 'SpawnSyncOptions'
```

2020-05-21 11:24 UTC, ExE-Boss commented on types/node/child_process.d.ts
> -        encoding?: BufferEncoding;
```suggestion
        encoding?: BufferEncoding | 'buffer' | null;
```

2020-05-21 11:24 UTC, ExE-Boss commented on types/node/child_process.d.ts
> -        encoding?: BufferEncoding;
```suggestion
        encoding?: BufferEncoding | 'buffer' | null;
```

2020-05-22 21:46 UTC, timdp commented
@ExE-Boss Thanks, updated.

- Do I also need to update the definitions in versioned subdirs?
- Should I amend my previous commit and force-push?

2020-05-23 05:11 UTC, galkin approved these changes

2020-05-23 14:13 UTC, SimonSchick requested changes
Tests?

2020-05-23 16:35 UTC, timdp commented
The readme says:

> You can validate your changes with `npm test` from the root of this repo, which takes changed files into account.

But if I run this without committing my changes, it complains. After I've committed my untested changes, `npm test` tests every single package, including the ones I haven't changed, which takes forever. How can I only test the `node` typings?

Now, I've already added tests where I pass the `encoding` to `execSync` and `spawnSync`. I see that the tests for `execFile` with `encoding` check the type of standard output, but that seems odd to me. These are tests for typings, not for the actual Node APIs. It doesn't make sense to duplicate package behavior tests in the typings. So what should I actually be testing?

2020-05-25 21:14 UTC, ExE-Boss approved these changes
You might also want to add yourself to the end of: <https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c3ba00352e8983d428e7114774603a57fac4413b/types/node/index.d.ts#L3-L46>

2020-05-25 21:49 UTC, timdp commented
It's fine, that list is long enough as it is.

2020-05-26 12:36 UTC, r3nya approved these changes

2020-06-01 23:37 UTC, rbuckton approved these changes

2020-06-01 23:37 UTC, merged