[json-schema] Added type definition for JSON object
DefinitelyTyped/DefinitelyTyped pull request #44955
Opened 2020-05-21 14:40 UTC by JasonHK

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-05-21 23:23 UTC, SimonSchick requested changes
You made a lot of unrelated style and formatting changes, please put undo those, put them in a separate commit or ideally a separate PR so us reviewers can focus on what has actually changed.

2020-05-22 07:47 UTC, JasonHK commented
> You made a lot of unrelated style and formatting changes, please put undo those, put them in a separate commit or ideally a separate PR so us reviewers can focus on what has actually changed.

@SimonSchick Sorry about that, I've reverted the style changes.

2020-05-26 12:46 UTC, JasonHK commented
> @SimonSchick Thank you for reviewing this PR! The author has pushed new commits since your last review. Could you take another look and submit a fresh review?
> <!--typescript_bot_stale-ping-37410c-21ecb0a-->

@SimonSchick Could you please take a look at the updated PR?

2020-05-31 14:00 UTC, JasonHK commented
@bcherny @cyrilletuzi @LucianBuzzo @rolandjitsu @SimonSchick Just a friendly reminder for you guys to review the PR.

2020-06-01 22:56 UTC, rbuckton commented on types/json-schema/index.d.ts
> +[key: string]: JSONSchema4Type;
nit: indentation

2020-06-01 22:57 UTC, rbuckton requested changes
Can you fix the indentation here? Then I can merge.

2020-06-02 05:57 UTC, JasonHK commented on types/json-schema/index.d.ts
> +[key: string]: JSONSchema4Type;
Fixed

2020-06-09 16:35 UTC, orta commented
Alright, this all looks good - let's get this in. Thanks @jasonHK for sticking with it!

2020-06-09 16:35 UTC, merged