Adds Brazilian Portuguese README
DefinitelyTyped/DefinitelyTyped pull request #44964
Opened 2020-05-21 20:18 UTC by thzoid

Co-Authored-By: Pedro Campos <pedro@cdias.dev>

Readme translation to Brazilian Portuguese.

2020-05-21 22:17 UTC, sandersn requested changes
A few typos, plus a question about whitespace. I don't speak Portuguese, so this still needs a review by a native speaker. But I didn't notice anything majorly alarming given what I *could* read.

2020-05-21 23:13 UTC, thzoid commented on README.md
> +
My guess it's because of the End of Line Sequence is in CRLF, but I'll change that too.

2020-05-21 23:26 UTC, thzoid commented on README.md
> +
Changes commited. The problem is now gone, probably.

2020-05-21 23:27 UTC, thzoid commented on README.pt.md
> +Pacotes `@types` têm tags para versões do TypeScript que elas explicitamente suportam, então normalmente você pode pode usar versões mais antigas dos pacotes que precedem o período de 2 anos.
Thanks, it was a typo indeed. I've fixed it already.

2020-05-21 23:27 UTC, thzoid commented on README.pt.md
> +Mudanças nos aqruivos `*.d.ts` devem ser acompanhadas de mudanças nos arquivos `*.ts` que mostrem que a API sendo usada, para que ninguém acidentalmente "quebre" o código do qual você depende.
Another typo. Fixed too.

2020-05-21 23:28 UTC, thzoid commented on README.pt.md
> +Logo após testar suas definições com um código real, faça uma [PR](#make-a-pull-request)
All anchors have been translated. I hope.

2020-05-22 10:28 UTC, orta commented
/cc @glaucia86 can you see if this feels good?

2020-05-26 17:38 UTC, thzoid commented
Any news on this one?

2020-05-26 22:24 UTC, sandersn commented
I'm confident in merging this given my reading ability in Spanish+French -- @glaucia86 if you have time for a review later I'm sure that @thzoid would be able to create a follow-up PR.

2020-05-26 22:24 UTC, sandersn approved these changes

2020-05-26 22:24 UTC, merged

2020-05-26 22:32 UTC, thzoid commented
For sure! Thanks, @sandersn!

2020-05-26 23:11 UTC, mrcrane reviewed
I'm not a native speaker, but I was born in Brazil and can read Portuguese. Looks like this already got merged, and I agree that it looks good. I found a few minor issues as I read through it so I'll go ahead and leave them here in case @thzoid wants to follow up.

2020-05-26 23:20 UTC, cdias900 commented on README.pt.md
> +#### Versões antigas do TypeScript (2.8 e anteriores)
I created a new PR fixing this #45080 , the translation was created before it was updated on the main readme

2020-05-27 19:57 UTC, thzoid commented on README.pt.md
> +#### Versões antigas do TypeScript (2.8 e anteriores)
Resolved on the latest commit. Thanks!

2020-05-27 19:58 UTC, thzoid commented on README.pt.md
> +#### Versões antigas do TypeScript (2.8 e anteriores)
Resolved on the #45084. Thanks!