[oversmash] Add missing types
DefinitelyTyped/DefinitelyTyped pull request #45073
Opened 2020-05-26 20:13 UTC by cdias900

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/filp/oversmash/blob/master/README.md#oversmash-options (The options object has a "NormalizeNamesAs" property that can be set to "snake" or "camel" and it changes the name of the properties in the types changed in this commit.)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-05-26 20:15 UTC, capythulhu approved these changes

2020-05-26 20:23 UTC, capythulhu approved these changes

2020-05-27 00:40 UTC, amcasey requested changes
This will make it impossible to instantiate `Hero` without specifying both `rawName` and `raw_name` - was that intentional?

https://www.typescriptlang.org/play?#code/C4TwDgpgBAysCGwCWBnZBjKBeKBvKA1kgHYAmAXFAERyKoZVQC+A3ALABQokUA4vAFtoOfETKUq-IY1adOEAB5gA9gCdgUbtAASEVcux5OUE1GKCIlNKpIBzdh1NR0ygQCNEAfkq1kaJOgOTrYW3nwWQaZuEGhhvvQBkSYCqOhxCH4YSVDwAO7wqqQo6XT+gcamABZ6yiWZiRUm8Cgo9MU+GQnljqbwAG568LYQdV3ZqnkAchZWwDbE9pxMUABkRj0m5kKz84sbzq4ewKNl2SFCYVIQ2dGxHaVZjVApKGn39d1OeQVFJ4-71X0fwa+2arTQ7VgnVOT36g2GwM+pgmuQA+ltLFBrHYHLIOJwXMQ0FBKpRdPpDLgMRIMVQADRQFHTbbUJkWKisIA

2020-05-27 03:14 UTC, cdias900 commented
> This will make it impossible to instantiate `Hero` without specifying both `rawName` and `raw_name` - was that intentional?

It was intentional, this type of object is only used in the type returned by the `playerStats` function, and as I said, what determines if the name of the property will be `raw_name` or `rawName` is the option `NormalizeNamesAs` sent to the `main` function's `options` parameter (the default is snake case), but this property can't be null or undefined.

2020-05-27 17:30 UTC, amcasey approved these changes
If you're happy, I'm happy.

2020-05-27 17:31 UTC, merged