feat: Add `foreach` v2.0
DefinitelyTyped/DefinitelyTyped pull request #45122
Opened 2020-05-28 20:14 UTC by ExE-Boss

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2020-05-29 18:42 UTC, ljharb requested changes

2020-05-29 18:42 UTC, ljharb commented on types/foreach/index.d.ts
> +        value: O extends ArrayLike<infer T> ? T : any,
```suggestion
declare function forEach<O extends ArrayLike<unknown>, THIS_ARG = undefined>(
    array: O,
    callbackfn: (
        this: THIS_ARG,
        value: O extends ArrayLike<infer T> ? T : unknown,
```
consumers should be forced the deal with the type errors and use any themselves if that's what they want

2020-05-29 18:42 UTC, ljharb commented on types/foreach/index.d.ts
> +        value: O extends Record<string, infer T> ? T : any,
```suggestion
declare function forEach<O extends Record<string, unknown>, THIS_ARG = undefined>(
    target: O,
    callbackfn: (
        this: THIS_ARG,
        value: O extends Record<string, infer T> ? T : unknown,
```

2020-05-29 18:42 UTC, ljharb commented on types/foreach/index.d.ts
> +// Definitions by: ExE Boss <https://github.com/ExE-Boss>
```suggestion
// Definitions by: ExE Boss <https://github.com/ExE-Boss>
//                           Jordan Harband <https://github.com/ljharb>
```

2020-05-29 19:01 UTC, ljharb approved these changes

2020-05-30 00:15 UTC, amcasey approved these changes

2020-05-30 00:15 UTC, merged