[mongoose] Solve TypeError when setting different currentTime
DefinitelyTyped/DefinitelyTyped pull request #45184
Opened 2020-05-30 20:40 UTC by hrafaelveloso

We can set `timestamps.currentTime` as seen on [mongoose docs](https://mongoosejs.com/docs/guide.html#timestamps), however that type definition isn't available

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [https://mongoosejs.com/docs/guide.html#timestamps](https://mongoosejs.com/docs/guide.html#timestamps)

2020-05-30 20:43 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mongoose ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mongoose@latest/))
was missing the following properties:
1. modelSchemas
1. options
1. cast
1. driver
1. deleteModel

<details>
<summary>as well as these 7 other properties...</summary>
<p>ObjectId, Decimal128, Mixed, Number, now, CastError, SchemaTypeOptions</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f9f019927d6889f8919d8fbde6a3316588520a49
</p>

2020-05-31 10:47 UTC, jeremyben requested changes
It says right in the mongoose docs that it could return a number as well:
https://mongoosejs.com/docs/guide.html#timestamps

`timestamps: { currentTime: () => Math.floor(Date.now() / 1000) }`

2020-06-06 08:53 UTC, andreialecu commented
Please add a test for these as well, so that it can be accepted. You can use the example in https://mongoosejs.com/docs/guide.html#timestamps as the test.

simply adding 

```js
new mongoose.Schema({
  createdAt: Number,
  updatedAt: Number,
  name: String
}, {
  timestamps: { currentTime: () => Math.floor(Date.now() / 1000) }
});

new mongoose.Schema({
  createdAt: Number,
  updatedAt: Number,
  name: String
}, {
  timestamps: { currentTime: () => new Date() }
});
```

To the bottom of `test/mongoose.ts` should be enough.

2020-06-08 10:14 UTC, andreialecu approved these changes

2020-06-08 10:16 UTC, hrafaelveloso commented
Ready to merge

2020-06-08 10:16 UTC, merged