Removed duplicated stompit connect function declaration.
DefinitelyTyped/DefinitelyTyped pull request #45582
Opened 2020-06-19 09:52 UTC by taromurao

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-06-19 10:45 UTC, DanielRose requested changes
I don't understand why you want to remove the declaration. The arguments are parsed in the function normalizeConnectArgs(args): https://github.com/gdaws/stompit/blob/e3e91d4216c271fb55f28fadd98ace88ebb3e17b/lib/connect.js#L126

Looking more closely at the code there are actually four possibilities for the arguments:

1. Pass the options directly as an object, and an optional connectListener
2. Pass a port (host is implied as localhost), and an optional connectListener
3. Pass a port an a host, and an optional connectListener
4. Pass a path, and an optional connectListener

The first and fourth variant is the first declaration.
The third is the second declaration.
The second is currently missing.

2020-06-19 12:59 UTC, taromurao commented
@DanielRose Thank you for reviewing. Indeed I should withdraw this pull request.

2020-06-19 12:59 UTC, closed without merging

2020-06-19 14:41 UTC, DanielRose commented
@taromurao You could fix the definitions though, since it is also possible to pass only a port. I missed that when I created the definitions.

2020-06-20 17:11 UTC, taromurao commented
@DanielRose Thank you for the comment. I would create a new pull request reflecting your comments. I noticed that the line https://github.com/taromurao/DefinitelyTyped/blob/70bf4eac0939efaaed4c3176f98dbd35bd6c82ed/types/stompit/lib/connect.d.ts#L23 connectListener contains different function signature than other places , namelly `() => void` instead of `(err: Error | null, client: Client) => void)`. I could not follow the code of stompit, but is this correct?

2020-06-21 07:14 UTC, taromurao commented
@DanielRose  Ah, found the `connectionListener?: () => void` in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/159c123fefdf0a1385cf04b9967e27a57fa7c118/types/node/net.d.ts#L63 .

2020-06-21 07:40 UTC, taromurao commented
@DanielRose Created a new PR reflecting your comments: #45625