[react-table] Make ColumnGroup.accessor declaration consistent
DefinitelyTyped/DefinitelyTyped pull request #45648
Opened 2020-06-22 21:23 UTC by sgtpep

- Declare ColumnGroup.accessor the way it's declared in ColumnWithLooseAccessor.
- Somehow the presence of a ternary fixes type inferring for columns from data when they're passed inline, like:
```
const data: Foo[] = [...]
<Table data={data} columns={[{ ..., accessor: (foo) => foo.bar }]} />
```
Without this change I have to always pass them like `[{ ..., accessor: (foo) => foo.bar }] as Column<Foo>[]`.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-06-22 23:34 UTC, ggascoigne commented on types/react-table/index.d.ts
> +    & { accessor?: keyof D extends never ? IdType<D> | Accessor<D> : Accessor<D>; };
I'll need to test this, but my guess is that this effectively undoes the `ColumnWithStrictAccessor` changes.

2020-06-22 23:50 UTC, ggascoigne commented on types/react-table/index.d.ts
> +    & { accessor?: keyof D extends never ? IdType<D> | Accessor<D> : Accessor<D>; };
@kizu tagging you in the hopes that you might have more time to look at this before I do :)

2020-07-07 19:24 UTC, weswigham commented
@ggascoigne @sgtpep what should be done here?

2020-07-13 18:15 UTC, sandersn commented
Ping @ggascoigne @kizu? Do you have time to review this further?

2020-07-13 18:47 UTC, ggascoigne commented
I'll see if I can look at this tonight.

2020-07-15 02:39 UTC, ggascoigne requested changes
I can't get find the right combination of parameters to get these changes to have any impact at all, so obviously I'm missing something.  Perhaps you are running in non-strict mode, that's what the tests run it and I could see how it's causing problems.

I'm going to update the tests in a separate PR and perhaps you can then update this PR with them and then add at least one test that exercises this code change.

For the record, I tried:

```tsx
        <Table
            data={data}
            columns={[
                {
                    Header: 'First Name',
                    accessor: 'firstName',
                    Cell: ({ value }) => {
                        const v = value; // $ExpectType string
                        return value;
                    },
                },
            ]}
        />
```

And it's behavior was the same both with and without your change.

I also tried:

```tsx
        <Table
            data={data}
            columns={[
                {
                    Header: 'First Name',
                    accessor: (i: Data) => i.firstName,
                    Cell: ({ value }: CellProps<Data>) => {
                        const v = value; // $ExpectType any
                        return value;
                    },
                },
            ]}
        />
```

Which I think is closer to your example, but this won't compile without specifying additional types, which in turn probably defeats the point of your change.

2020-08-15 04:11 UTC, closed without merging