Adding "translateExtent" prop type to ZoomableGroupsProps interface in react-simple-maps
DefinitelyTyped/DefinitelyTyped pull request #45676
Opened 2020-06-23 23:04 UTC by MachukIvan

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.react-simple-maps.io/docs/zoomable-group/

2020-06-25 08:33 UTC, pronebird reviewed
Based on https://github.com/zcreativelabs/react-simple-maps/blob/a0004e4ad0a15644c0ce466c8edf1d69279935ca/src/components/useZoomPan.js#L21 this looks legit <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/definitelytyped/definitelytyped/45676#-:-MAeb45dABtKVzGslT7f:bvsuh28)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-06-25 08:34 UTC, pronebird approved these changes

2020-06-25 08:36 UTC, pronebird requested changes

2020-06-25 08:36 UTC, pronebird commented on types/react-simple-maps/index.d.ts
> +    translateExtent?: [[number, number], [number, number]]
Please fix the syntax issue, i.e:

```
1> Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/react-simple-maps/index.d.ts:84:59
63
1> ERROR: 84:59  semicolon  Missing semicolon
```

2020-06-28 20:02 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-simple-maps ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-simple-maps@latest/))
was missing the following properties:
1. useGeographies
1. useZoomPan
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5e0588679ab49ed1f512d9444027b78bf0dbabc1
</p>

2020-06-29 11:18 UTC, pronebird approved these changes

2020-06-29 18:14 UTC, merged