[chrome] Add chrome.enterprise.networkingAttributes and update chrome.platformKeys
DefinitelyTyped/DefinitelyTyped pull request #45683
Opened 2020-06-24 09:48 UTC by mpetrisor

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: 
https://developer.chrome.com/extensions/enterprise_networkingAttributes
https://developer.chrome.com/extensions/platformKeys#method-getKeyPairBySpki
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-07-06 20:46 UTC, pokutuna requested changes
Looks good.
I suggested doc blocks improvements.

2020-07-06 20:46 UTC, pokutuna commented on types/chrome/index.d.ts
> +     */
```suggestion
     * @since Chrome 85.
     */
```

2020-07-06 20:46 UTC, pokutuna commented on types/chrome/index.d.ts
> + */
```suggestion
 * Important: This API works only on Chrome OS.
 * @since Chrome 85.
 */
```

2020-07-07 08:08 UTC, mpetrisor commented
Hello @pokutuna,

Thank you for your suggestions! I have committed them.

mpetrisor

2020-07-07 10:03 UTC, pokutuna approved these changes
Thanks for merging my suggestions. LGTM

2020-07-07 17:52 UTC, merged