fix(glider-js): add `eventPropagate` option
DefinitelyTyped/DefinitelyTyped pull request #45742
Opened 2020-06-27 15:35 UTC by peterblazejewicz

- missing `eventPropagate` option:
https://github.com/NickPiscitelli/Glider.js/blob/e0743bc3fc4da0977ab778c375f6a98e48d0cfb6/README.md#L90
This specific option is missin public facing documentation, see:
NickPiscitelli/Glider.js#111

/cc @martin-badin

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

2020-06-27 19:57 UTC, martin-badin approved these changes

2020-06-28 08:30 UTC, peterblazejewicz commented
it needs to wait for upstream issue:
https://github.com/NickPiscitelli/Glider.js/issues/111

2020-06-28 17:04 UTC, martin-badin commented
@peterblazejewicz see my comment https://github.com/NickPiscitelli/Glider.js/issues/111#issuecomment-650794228

2020-07-08 05:44 UTC, martin-badin commented
@peterblazejewicz please remove `propagateEvent` from types. Then I can add approval to this PR.

2020-07-08 05:44 UTC, martin-badin requested changes
please remove propagateEvent from types. Then I can add approval to this PR.

2020-07-08 16:02 UTC, peterblazejewicz commented
> please remove propagateEvent from types. Then I can add approval to this PR.

changed in : 401116e698f9513e483a3c69111bafcc8c0deb1f

2020-07-08 19:06 UTC, martin-badin approved these changes

2020-07-08 21:11 UTC, peterblazejewicz commented
Ready to merge :kiss:

2020-07-08 21:11 UTC, merged