fix: [node] add missing options parameter for lstat
DefinitelyTyped/DefinitelyTyped pull request #45783
Opened 2020-06-29 18:43 UTC by nornagon

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_fs_lstat_path_options_callback
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-06-29 18:49 UTC, j-oliveras commented on types/node/fs.d.ts
> +        bigint?: number;
Should be boolean
```suggestion
        bigint?: boolean;
```

2020-06-29 18:50 UTC, nornagon commented on types/node/fs.d.ts
> +        bigint?: number;
🤦

2020-06-29 18:59 UTC, nornagon commented
Just noticed this is partially implemented already [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/ts3.2/fs.d.ts)

2020-06-30 07:55 UTC, j-oliveras requested changes
Probably you should move this change to `/types/node/ts3.2/fs.d.ts` because in that file live `fs` types for typescript 3.2 and newer versions (is the first version that supports `bigint` type). @Flarna or @SimonSchick should know this better.

You must add tests and maybe add the same changes for node 10 and 12 (current change is for node 14).

2020-06-30 08:09 UTC, Flarna commented
I agree with @j-oliveras that these should be moved to ts3.2 folder similar as it is already done for `stat`. Please note that the value `bigint` used actually changes the result type which should be reflected in the definitions.

2020-08-01 04:11 UTC, closed without merging