mui-datatables added missing types to MUIDataTableState
DefinitelyTyped/DefinitelyTyped pull request #45981
Opened 2020-07-09 18:35 UTC by hugobarragon

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-07-09 18:40 UTC, favna requested changes
Just one small change

2020-07-09 18:40 UTC, Favna commented on types/mui-datatables/index.d.ts
> +    searchProps: null | React.HTMLAttributes<HTMLInputElement>;
```suggestion
    searchProps: React.HTMLAttributes<HTMLInputElement> | null;
```

Nit, but it is a convention to put `null` after the actual type.

2020-07-09 18:41 UTC, Favna commented
Also can you add this to your original PR description?

```closes #45909```

That way your issue will auto close when this PR is merged.

2020-07-09 18:42 UTC, favna approved these changes

2020-07-09 18:42 UTC, hugobarragon commented
if you need tests, tomorrow I can work them out

2020-07-09 18:42 UTC, Favna commented
Nah it's fine, just undraft it.

2020-07-09 18:44 UTC, Favna commented
> ❌ Only a DT maintainer can merge changes without tests

Well I guess if you can actually add tests tomorrow that'll speed up the merge. I didn't know that condition was in place.

2020-07-09 18:45 UTC, favna requested changes
yes we got it CI, you don't like trailing commas

2020-07-09 18:45 UTC, Favna commented on types/mui-datatables/index.d.ts
> +        },
```suggestion
        }
```

2020-07-10 11:11 UTC, favna approved these changes

2020-07-10 11:12 UTC, Favna commented
Approved.

Taken from the bot:

> All of the items on the list are green. To merge, you need to post a comment including the string "Ready to merge" to bring in your changes.

2020-07-10 11:14 UTC, hugobarragon commented
Ready to merge Jarvis

2020-07-10 11:14 UTC, merged