node-telegram-bot-api: support sendPoll, stopPoll, and poll_answer event
DefinitelyTyped/DefinitelyTyped pull request #46033
Opened 2020-07-12 03:13 UTC by XieJiSS

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://core.telegram.org/bots/api

2020-07-13 05:42 UTC, XC-Zhang requested changes
Thanks for PR! Please see comments I made.

By the way, since poll_answer event has been added to `on`, I suggest that it should also be added to `addListener`.

There is one more thing I'd like to discuss. Poll type currently can be "regular" or "quiz". Should we use [String Literal Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html#string-literal-types) instead of `string`? For example:
```typescript
type PollType = "regular" | "quiz";
interface Poll {
    // ...
    type: PollType;
    // ...
}
```

2020-07-13 05:42 UTC, XC-Zhang commented on types/node-telegram-bot-api/index.d.ts
> +        file_unique_id?: string;
Make `file_unique_id` required? It is not optional in the [docs](https://core.telegram.org/bots/api#sticker).

2020-07-13 05:42 UTC, XC-Zhang commented on types/node-telegram-bot-api/index.d.ts
> +        is_animated?: boolean;
Make `is_animated` required? It is not optional in the [docs](https://core.telegram.org/bots/api#sticker).

2020-07-13 13:56 UTC, XC-Zhang approved these changes

2020-07-14 05:27 UTC, XieJiSS commented
Sorry, but when I was re-checking these codes, I realized that I missed a test for `addListener` 😢

2020-07-14 06:01 UTC, XC-Zhang approved these changes

2020-07-14 06:02 UTC, XC-Zhang commented
> Sorry, but when I was re-checking these codes, I realized that I missed a test for `addListener` 😢

Good point! 👍

2020-07-14 06:07 UTC, XC-Zhang commented
Although not that important, interface `SendPollOptions` could be improved by using `PollType` you added yesterday:

2020-07-14 13:51 UTC, XieJiSS commented
@XC-Zhang Nice point! I've pushed another commit to fix that.

2020-07-14 14:35 UTC, XC-Zhang approved these changes
Excellent job! Let's merge it! 🎉

2020-07-14 15:43 UTC, XieJiSS commented
Ready to merge

2020-07-14 15:43 UTC, merged