Give PropsWithChildren a default type parameter
DefinitelyTyped/DefinitelyTyped pull request #46043
Opened 2020-07-12 20:59 UTC by pelotom

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-07-12 21:16 UTC, vhfmag approved these changes
Nice!

2020-07-12 22:50 UTC, eps1lon requested changes
> function MyComponent({ children }: PropsWithChildren) {

I think we have it pretty well established that `React.ReactNode` is the dedicated type for children. Do we need this specific pattern you suggested for anything else?

2020-07-13 02:46 UTC, pelotom commented
> > function MyComponent({ children }: PropsWithChildren) {
> 
> I think we have it pretty well established that `React.ReactNode` is the dedicated type for children. Do we need this specific pattern you suggested for anything else?

Not sure if this is what you’re suggesting, but writing `{ children: ReactNode }` is more cumbersome than `PropsWithChildren`. Presumably this is why the latter exists in the first place.

2020-07-13 08:49 UTC, eps1lon commented
> Presumably this is why the latter exists in the first place.

Sure but the name makes it clear that it is about "props and children". If you're not passing "props" then the type looses its meaning and it should make it obvious when you forgot the props. In the end you can always do `PropsWithChildren<{}>` if you are sure you don't have any props, no?

2020-07-13 12:15 UTC, ferdaber approved these changes
I'm pretty indifferent about this one. Giving it my approval since the empty type is a relatively very low maintenance overhead but I understand where @eps1lon is coming from too.

2020-07-13 15:03 UTC, pelotom commented
> > Presumably this is why the latter exists in the first place.
> 
> Sure but the name makes it clear that it is about "props and children". If you're not passing "props" then the type looses its meaning and it should make it obvious when you forgot the props. In the end you can always do `PropsWithChildren<{}>` if you are sure you don't have any props, no?

It's a minor convenience. What's the downside?

2020-07-14 13:41 UTC, dimitropoulos commented
@pelotom the downside as I see it is using `PropsWithChildren` for a situation where.... well where there are no props.  See the impedance mismatch there?  It really looks like what you want is `ReactNode`, no?  While I'm not deeply opposed to the default argument... it seems kinda backwards to default to not having props for a type that intends to type props, know what I mean?

2020-07-14 16:14 UTC, pelotom commented
> @pelotom the downside as I see it is using `PropsWithChildren` for a situation where.... well where there are no props. See the impedance mismatch there? It really looks like what you want is `ReactNode`, no? While I'm not deeply opposed to the default argument... it seems kinda backwards to default to not having props for a type that intends to type props, know what I mean?

`{}` _is_ a set of props (the empty set), so `PropsWithChildren` is still an accurate name. In any case, I don't really care about the name, I care that the type is useful, and it would be more useful if it had a defaulted parameter. Re. using `ReactNode`, as I said above, writing `{ children: ReactNode }` is more cumbersome than writing `PropsWithChildren`.

2020-07-16 02:42 UTC, dimitropoulos commented
I don't agree but that's ok.  I see where you're coming from.  I hardly see any way this change will introduce a bug or something, so I'll go along. :)

2020-07-16 02:43 UTC, dimitropoulos approved these changes

2020-07-30 18:09 UTC, pelotom commented
Any chance this can get merged?

2020-07-30 18:32 UTC, eps1lon requested changes
Leaving my disapproval for posterity. Writability is not a sufficient argument for a change. It is more important to have a type reasonable with next to no context/knowledge. **Props**WithChildren does not make sense if you omit the props. This is almost always a mistake and since this request comes from an expert in the field I'm even less inclined to see the "usefulness". Usefulness to whom? How often do you find yourself writing `PropsWithChildren<{}>` and in what context?

It's generally frustrating because this "it's just a minor addition" argument is all I hear everyday. It's drive-by PRs like these (no context, no use case, no tests, just "I find it more convenient") that will cause death by thousand cuts. A little convenience for a single person here, a little bit for one there and a year later you're having a hard time making sense of a piece of code.

2020-07-31 05:29 UTC, pelotom commented
I gave you my use case. I refuted the stupid “empty props are not props” argument. The idea that adding a default type parameter hurts readability in any way is absurd on its face. There are plenty of defaulted type parameters throughout the typings already and nobody is complaining about them making the code unreadable. Sorry for the “drive-by PR”, whatever that means. I guess PRs have to make lots of changes to be worthy of consideration?

2020-07-31 05:29 UTC, closed without merging

2020-07-31 15:03 UTC, dimitropoulos commented
@pelotom you said:

> In any case, I don't really care about the name

If I have to guess, I'd say I think this is where the disconnect is happening.  To me, I care about the name quite a bit.  You have said you don't, and you're entitled to that opinion - and I respect where you're coming from.

I won't get into the name calling or other things here.  I'm not an expert at anything - I just do the best that I can with the information I have.  With the information I have in this PR it is still unclear to me what problem this is really solving in a deeper sense.  I think this may be an unintentional [xyproblem.info](xyproblem.info) or something maybe?

Explanations you gave such as:
> {} is a set of props (the empty set)

do very little to address my issue, which is that the _usage_ and _name_ of the type itself doesn't make sense if there are no props (and here is where I have to clarify that I do not agree that an empty set of props qualifies as props somehow??).

To me, having a default prop actually makes it _less_ useful, if you can believe that, because it creations a situation where I may unintentionally _not_ specify Props on a type that.. well.. is expecting props (it's right there in the name..).  This goes back, again, to the question of what your deeper use-case really is.

If you'd like to continue this conversation respectfully, I'd be happy to do so to better understand your use-case.  @eps1lon seems to have bowed out, which is fine, but if you have new information, use-cases, tests, etc., that might illustrate things a bit more I welcome the opportunity to learn from you.