[Chart.js] Add scaleService static method to Chart class
DefinitelyTyped/DefinitelyTyped pull request #46041
Opened 2020-07-12 14:41 UTC by stevecastaneda

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>> https://www.chartjs.org/docs/latest/axes/?h=updatescaledefaults
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-07-12 15:27 UTC, stevecastaneda commented on types/chart.js/index.d.ts
> +        /** Deprecated since version 2.5.0. Use `afterLayout` instead. */
Kept getting the following error when running `npm run lint chart.js` until I removed the `@` symbol.

```
The 'no-redundant-jsdoc-2' rule threw an error in '/Users/steve/github/DefinitelyTyped/types/chart.js/index.d.ts':
Error: Unexpected tag kind: JSDocDeprecatedTag
```

2020-07-13 08:20 UTC, lekoaf requested changes
Would it be possible to add a test case for this?

2020-07-13 12:55 UTC, stevecastaneda commented
@lekoaf Done!  I'm not 100% sure I did it correctly, but I added how I use this function locally and ran `npm test` at root, and it didn't throw any errors.

2020-07-13 12:57 UTC, lekoaf commented
> @lekoaf Done! I'm not 100% sure I did it correctly, but I added how I use this function locally and ran `npm test` at root, and it didn't throw any errors.

Looks good. Let's see what CI says.

2020-07-14 07:28 UTC, lekoaf approved these changes

2020-07-14 12:37 UTC, stevecastaneda commented
Ready to merge

2020-07-14 12:37 UTC, merged