fix(react-native): mark Animated config option `useNativeDriver` as optional
DefinitelyTyped/DefinitelyTyped pull request #46174
Opened 2020-07-19 04:08 UTC by vpicone

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

After linting got:
```
error TS2307: Cannot find module 'csstype' or its corresponding type declarations.
```

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://reactnative.dev/docs/animated#event (indicates option defaults to `false`)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-07-19 04:35 UTC, TheSavior commented
This config isn't optional anymore. It is a required config to force people to know when they are or aren't using the native driver. Eventually this will let us flip the default.

2020-07-19 04:35 UTC, elicwhite requested changes
See comment above

2020-07-19 06:22 UTC, ca057 reviewed
As far as I can see, the option `useNativeDriver` is required, looking at the source code: https://github.com/facebook/react-native/blob/f00795dc90d05180014eeea4b3215b0166a90692/Libraries/Animated/src/animations/Animation.js#L22

It could be that the docs are outdated, as  the change from being an optional property to a required one was done in a recent version upgrade.

EDIT: Just saw this was already commented, maybe we can update the docs to make it less ambiguous?

2020-07-20 12:42 UTC, vpicone commented
@ca057 @TheSavior thanks for the quick feedback. I was a bit confused because the code actually _does_ [use a default of false](https://github.com/facebook/react-native/blob/3137c443f498002dcf0f6addd8fafc7a31bce218/Libraries/Animated/src/NativeAnimatedHelper.js#L311), but the spirit of the type would required considering the [warning](https://github.com/facebook/react-native/blob/3137c443f498002dcf0f6addd8fafc7a31bce218/Libraries/Animated/src/NativeAnimatedHelper.js#L292) that's displayed when it does.

So the docs aren't _wrong_ it does default to false, but I think there's a mismatch between the docs language and the warning that's displayed. Do you think the docs should be updated?

2020-07-20 13:06 UTC, alloy commented
An update to the upstream docs would be great 👍 🙏

2020-07-20 13:06 UTC, closed without merging

2020-07-20 16:41 UTC, ca057 commented
> @ca057 @TheSavior thanks for the quick feedback. I was a bit confused because the code actually _does_ [use a default of false](https://github.com/facebook/react-native/blob/3137c443f498002dcf0f6addd8fafc7a31bce218/Libraries/Animated/src/NativeAnimatedHelper.js#L311), but the spirit of the type would required considering the [warning](https://github.com/facebook/react-native/blob/3137c443f498002dcf0f6addd8fafc7a31bce218/Libraries/Animated/src/NativeAnimatedHelper.js#L292) that's displayed when it does.
> 
> So the docs aren't _wrong_ it does default to false, but I think there's a mismatch between the docs language and the warning that's displayed. Do you think the docs should be updated?

I think it would make sense - given that it’s a required prop (even though there’s a warning which could be missed/ignored and removed in a later version) it should also be treated as a required prop.