[@types/yup] fix InferType working with nested optional properties
DefinitelyTyped/DefinitelyTyped pull request #46518
Opened 2020-08-03 06:43 UTC by carlosingles

fixes #45100

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/45100
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-08-03 13:46 UTC, iansan5653 requested changes
Hey, thanks for the PR! This looks good, but I'd like to see two more edge cases tested (doesn't have to necessarily be on the `address` schema if you don't want):

1. Optional properties in a deeply nested object, ie:
```ts
const personSchema = yup.object({
  address: yup.object({
    area: yup.object({
       country: yup.string().required(),
       region: yup.string().optional() // is this handled correctly?
    }).required(),
  }).required(),
}).defined();
```
2. Array type properties in a nested object:
```ts
const personSchema = yup.object({
  address: yup.object({
    phoneNumbers: yup.array(yup.string()).defined() // is this handled correctly?
  }).required(),
}).defined();
```

2020-08-03 14:31 UTC, carlosingles commented
No worries, added them for you 👍

2020-08-03 15:02 UTC, iansan5653 approved these changes
Looks good to me! Thanks 👍

2020-08-03 15:09 UTC, carlosingles commented
Ready to merge

2020-08-03 15:10 UTC, merged

2020-08-06 07:37 UTC, aaronjensen commented
As far as I can tell, this change broke array type inference. This is no longer allowed:

```ts
const foo = yup.array(yup.string().defined()).defined()
type Foo = yup.InferType<typeof foo>
declare const a: Foo
const b: string[] = a
```

2020-08-06 08:07 UTC, carlosingles commented
Yeah tested it on the latest version and it is broken, it is working on this PR though:

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46533

There were not sufficient test cases to cover the scenario, I hope the new PR with additional test cases will help cover these scenarios

2020-08-10 15:36 UTC, aaronjensen commented
Would it be worth temporarily reverting your last change? Not being able to use arrays of primitives at all is a pretty big breaking change.

2020-08-10 22:50 UTC, carlosingles commented
I'm fine with that, but I don't have ownership on this repo. Alternatively, you can change your package.json to lock @types/yup to 0.29.3

2020-10-11 17:38 UTC, msheakoski commented
Hopefully a decision about this change can be made soon. I saw that the related PR has been marked as abandoned.

Every release of the typings since 0.29.4 has been broken in my projects. I have locked the version to 0.29.3 for the past two months, but this is not sustainable if I want to keep typings in sync with yup changes.

2020-11-19 16:23 UTC, msheakoski commented
Yup 0.30.0 [was released today](https://github.com/jquense/yup/blob/master/CHANGELOG.md) with new features and breaking changes.

Because the typings since 0.29.4 have been broken from this PR's change, type updates for newer versions of Yup cannot be used since this PR continues to breaks builds.

2020-12-04 03:44 UTC, msheakoski commented
Good news! Yup 0.32.0 [was released today](https://github.com/jquense/yup/blob/master/CHANGELOG.md) and it is now written in TypeScript 🎉 which means that external definitions are no longer needed.