[umzug] Add migrationsList feature
DefinitelyTyped/DefinitelyTyped pull request #46714
Opened 2020-08-13 08:38 UTC by thomaschaaf

https://github.com/sequelize/umzug/blob/v2.3.0/src/index.js#L589
https://github.com/sequelize/umzug/blob/v2.3.0/src/migrationsList.js

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/sequelize/umzug/blob/v2.3.0/src/index.js#L589
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2020-08-13 19:15 UTC, andrewbranch requested changes
Nit: this is unlikely to make a difference in practice, but is technically more correct

2020-08-13 19:15 UTC, andrewbranch commented on types/umzug/index.d.ts
> +        migrationsList(migrations: MigrationDefinitionWithName[], parameters?: any[]): Migration[];
```suggestion
        migrationsList: (migrations: MigrationDefinitionWithName[], parameters?: any[]) => Migration[];
```

2020-09-29 00:50 UTC, amcasey approved these changes

2020-10-13 16:49 UTC, orta commented
Seems good to me 👍🏻

2020-10-13 16:49 UTC, merged