export INotifyOption
DefinitelyTyped/DefinitelyTyped pull request #46869
Opened 2020-08-18 15:11 UTC by oreporan

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-08-18 16:44 UTC, NateScarlet requested changes

2020-08-18 16:44 UTC, NateScarlet commented on types/notifyjs/index.d.ts
> +export default Notify
`export =` is correct but `export default` not.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#a-package-uses-export--but-i-prefer-to-use-default-imports-can-i-change-export--to-export-default

```shell
> node -p 'var window = {}; require("notifyjs")'
{ [Function: Notify]
  isSupported: [Function],
  needsPermission: true,
  requestPermission: [Function] }
```

```shell
> node -p 'var window = {}; require("notifyjs").default'
undefined
```

2020-08-18 16:47 UTC, NateScarlet requested changes
same as above

2020-08-18 16:52 UTC, oreporan commented
@NateScarlet I'm trying to leave the default export `Notify`but also export the `INotifyOptions` interface. How can I do that?

2020-08-20 03:28 UTC, NateScarlet approved these changes

2020-08-20 03:30 UTC, NateScarlet commented
Ready to merge

2020-08-20 03:31 UTC, merged