ffprobe definition types.
DefinitelyTyped/DefinitelyTyped pull request #46893
Opened 2020-08-19 07:32 UTC by SergeyAlexsandrovich

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [x] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-08-19 16:10 UTC, peterblazejewicz commented on types/ffprobe/index.d.ts
> +declare function getInfo(options: getInfo.Options | string): Promise<getInfo.FFProbeResult>;
```suggestion
declare function getInfo(filePath: string, options: getInfo.Options, cb: (err: Error, info: getInfo.FFProbeResult) => void): void;
declare function getInfo(filePath: string, options: getInfo.Options): Promise<getInfo.FFProbeResult>;
```
IMO you need both `filepath` and `options`:
https://github.com/eugeneware/ffprobe/blob/master/index.js#L10
https://github.com/eugeneware/ffprobe/blob/master/index.js#L16
if applied, see my comment on tests, with changes to reflect these one (and support for callback function)

2020-08-19 16:12 UTC, peterblazejewicz commented on types/ffprobe/ffprobe-tests.ts
> +})();
```suggestion
import ffprobe = require('ffprobe');
import ffprobeStatic = require('ffprobe-static');

ffprobe('./file.mp4', { path: ffprobeStatic.path })
    .then(info => {
        info; // $ExpectType FFProbeResult
    })
    .catch((err: Error) => {
        err; // $ExpectType Error
    });

ffprobe('./file.mp4', { path: ffprobeStatic.path }, (err, info) => {
    if (err) {
        err; // $ExpectType Error
    } else {
        info; // $ExpectType FFProbeResult
    }
});

(async () => {
    const result = await ffprobe('/path/to/movie.avi', { path: ffprobeStatic.path });
})();
```
AFAIK this reflects changes in method signature to support 2 required params (`path` and `options`) and support for both Promise<info> and `callback(err, info)` as per package public documentation:
https://github.com/eugeneware/ffprobe#ffprobemediafilepath-opts-cb

2020-08-19 16:15 UTC, peterblazejewicz reviewed
@SergeyAlexsandrovich looks good, can you review my comments?

2020-08-21 04:45 UTC, DanielRosenwasser requested changes
@peterblazejewicz seems to have good suggestions.

2020-08-21 08:11 UTC, peterblazejewicz approved these changes
LGTM!
@SergeyAlexsandrovich Sergey, thx for the contribution!

2020-08-21 08:12 UTC, peterblazejewicz commented
@DanielRosenwasser reviewed/approved, thx for your review!

2020-08-21 08:13 UTC, SergeyAlexsandrovich commented
@peterblazejewicz Hello. I added changes. Thank you for your help!

2020-08-28 00:07 UTC, merged

2022-07-29 21:03 UTC, FlameFractal commented
@sergey-alexsandrovich  Can we fix #50357?