update(git-semver-tags): v4.1 update and other minor changes
DefinitelyTyped/DefinitelyTyped pull request #46908
Opened 2020-08-19 21:25 UTC by peterblazejewicz

- `skipUnstable` option
- definition cleanup
- configuration cleanup
- version bump
- maintainer added

https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/git-semver-tags/CHANGELOG.md

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-08-27 07:21 UTC, JasonHK requested changes
Just some tweaks needed, thanks! :smile:

2020-08-27 07:21 UTC, JasonHK commented on types/git-semver-tags/git-semver-tags-tests.ts
> +import gitSemverTags = require('git-semver-tags');
Will this be better?

```suggestion
import * as gitSemverTags from "git-semver-tags";
```

2020-08-27 07:21 UTC, JasonHK commented on types/git-semver-tags/index.d.ts
> +         * If given, unstable tags will be skipped [ e.g. x.x.x-alpha.1, x.x.x-rc.2 ]
```suggestion
         * If given, unstable tags (e.g. `x.x.x-alpha.1`, `x.x.x-rc.2`) will be skipped.
```

2020-09-03 04:02 UTC, JasonHK approved these changes
Thanks!

2020-09-03 21:02 UTC, peterblazejewicz commented
Ready to merge 💋

2020-09-03 21:03 UTC, merged