[react-native] Updated TextInputState
DefinitelyTyped/DefinitelyTyped pull request #46926
Opened 2020-08-20 18:51 UTC by danilobuerger

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react-native/blob/v0.63.2/Libraries/Components/TextInput/TextInputState.js
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-08-20 19:01 UTC, danilobuerger commented
I don't know why the tests are failing. Seems unrelated?

2020-08-21 08:14 UTC, alloy requested changes
Nice, just some minor semantic changes.

2020-08-21 08:14 UTC, alloy commented on types/react-native/index.d.ts
> +    currentlyFocusedInput(): React.ElementRef<HostComponent<any>>;
Upstream uses `mixed`, so this should be `unknown`.

```suggestion
    currentlyFocusedInput(): React.ElementRef<HostComponent<unknown>>;
```

2020-08-21 08:14 UTC, alloy commented on types/react-native/index.d.ts
> +    focusTextInput(textField?: React.ElementRef<HostComponent<any>>): void;
```suggestion
    focusTextInput(textField?: React.ElementRef<HostComponent<unknown>>): void;
```

2020-08-21 08:14 UTC, alloy commented on types/react-native/index.d.ts
> +    blurTextInput(textField?: React.ElementRef<HostComponent<any>>): void;
```suggestion
    blurTextInput(textField?: React.ElementRef<HostComponent<unknown>>): void;
```

2020-08-21 08:17 UTC, danilobuerger commented
Thanks @alloy. Just applied your requested changes.

2020-08-24 11:22 UTC, alloy commented
Ah, hmmm, so we weren’t using `unknown` before 🤔 In that case, let’s leave it as `any`, I don’t think this change really warrants that TS bump.

2020-08-24 11:25 UTC, alloy commented
Ok, going to merge this as-is, the existing failures must have been introduced in a different way, just not sure yet how. /cc @orta

2020-08-24 11:25 UTC, merged

2020-08-24 11:26 UTC, alloy commented
Ugh, darn, I forgot that you had already applied the `unknown` change, so now this is broken. What do you want to do, revert the `unknown` change or bump TS to v3 after all? I think v3 has been out long enough.

2020-08-24 11:28 UTC, danilobuerger commented
@alloy: I was just about to amend it to go back to any, then you merged it 🤪. I think bumping to v3 is fine, it was released in 2018...

2020-08-24 11:31 UTC, alloy commented
Hehehe, thanks. Let’s bump TS to 3.0 then, can you PR that?

2020-08-24 11:31 UTC, danilobuerger commented
Sure, will do later today.

2020-09-01 10:42 UTC, mrbrentkelly commented
I just upgraded my RN project to 0.63.2 as well as @types/react-native to 0.63.12. When I run typescript compile I'm getting the following errors which appear to be related to the changes in this PR...

```
node_modules/@types/react-native/index.d.ts:1680:36 - error TS2694: Namespace 'React' has no exported member 'ElementRef'.

1680     currentlyFocusedInput(): React.ElementRef<HostComponent<unknown>>;
                                        ~~~~~~~~~~

node_modules/@types/react-native/index.d.ts:1687:38 - error TS2694: Namespace 'React' has no exported member 'ElementRef'.

1687     focusTextInput(textField?: React.ElementRef<HostComponent<unknown>>): void;
                                          ~~~~~~~~~~

node_modules/@types/react-native/index.d.ts:1694:37 - error TS2694: Namespace 'React' has no exported member 'ElementRef'.

1694     blurTextInput(textField?: React.ElementRef<HostComponent<unknown>>): void;
```

Any ideas on how to resolve?

2020-09-01 10:44 UTC, danilobuerger commented
@mrbrentkelly what version of `@types/react` are you using?

2020-09-01 10:49 UTC, mrbrentkelly commented
> what version of @types/react are you using?

Looks like **16.9.3**.

Note, I don't explicitly include `@types/react` in my `package.json` since it gets added by `@types/react-native`

```
"@types/react-native@^0.63.12":
  version "0.63.12"
  dependencies:
    "@types/react" "*"
```

2020-09-01 10:55 UTC, danilobuerger commented
`React.ElementRef` was added in `16.9.25` so you will need at least that.

2020-09-01 10:58 UTC, mrbrentkelly commented
Perfect, thanks @danilobuerger 👍 

I added the latest version of `@types/react` directly (i.e. `yarn add @types/react@16.9.49 --dev`) and that appears to fix things 👍 . 

I just assumed `@types/react-native` would transitively bring in the correct version of `@types/react` for me 🤷