[lodash] Update return types for debounce & throttle
DefinitelyTyped/DefinitelyTyped pull request #46971
Opened 2020-08-21 23:03 UTC by dobesv

- functions returned by `throttle` & `debounce` can return `undefined`
if the function invokation is delayed
- the `flush()` method returns the return value of the last invokation,
if available

Example:

```
> _ = require('lodash')
> f = _.debounce(_.identity, 10000)
[Function: debounced] {
  cancel: [Function: cancel],
  flush: [Function: flush]
}
> f.flush()
undefined
> f(123)
undefined
> f(546)
undefined
> f.flush()
546
> f(678)
546
> f.flush()
678
```

2020-08-22 12:44 UTC, aj-r requested changes

2020-08-24 04:46 UTC, dobesv commented
@aj-r Thank you for the review.  I pushed a new version that to address your comments, let me know if you notice anything else.

2020-08-24 17:17 UTC, sandersn commented
@dobesv can you move your 3.1 changes up to the root level? As of last week when 3.0 was deprecated, the pre-3.1 types will never be used, and #46959 moves the 3.1 types up to the root level.

2020-08-29 00:18 UTC, aj-r approved these changes

2020-08-29 01:30 UTC, dobesv commented
Ready to merge

2020-08-29 01:31 UTC, merged

2020-08-31 17:24 UTC, dannymcgee commented
@dobesv @aj-r Removing the `Cancelable` interface is a breaking change, I'm not sure why this was published as a patch. I think the `DebouncedFunc` template is an improvement, but I'd prefer to have not found out about it by suddenly dealing with a broken build and having to track down the commit to figure out what changed and how to fix it. :)

2020-08-31 18:30 UTC, dobesv commented
@dannymcgee Ah, sorry about that.  Maybe `DebouncedFunc` should have extended `Cancelable` or something, to keep that interface available.

2020-09-01 01:02 UTC, aj-r commented
Unfortunately almost all type changes are breaking changes by nature of how
they work. If this is breaking you then you can pin to an older version
until you're ready to upgrade.

Unfortunately we can't follow semantic versioning in Definitelytyped since
the major/minor versions need to match the underlying library.

On Mon, Aug 31, 2020, 2:30 PM Dobes Vandermeer, <notifications@github.com>
wrote:

> @dannymcgee <https://github.com/dannymcgee> Ah, sorry about that. Maybe
> DebouncedFunc should have extended Cancelable or something, to keep that
> interface available.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46971#issuecomment-683952403>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABVF5M7VXENDFZFRCKT5YSLSDPT5LANCNFSM4QHXSH5Q>
> .
>

2020-09-01 23:51 UTC, dko-slapdash commented
Hi @dobesv, for debounce() it's cool, but I think this change is too strict for throttle() actually. At least for the simplest (and most commonly used) version of throttle:
```ts
import _ from "lodash";
let f = _.throttle(_.identity, 10000);
console.log(f(123));
```

This call to `f()` never returns `undefined`, and we know it in advance. But the TS typing says it can.

So maybe it's worth adding a specialization to throttle() which covers exactly this case and omits undefined? (The change in throttle() broke our codebase in many places.)

2020-09-02 00:04 UTC, dobesv commented
@dko-slapdash

Hmm that's a tough one.  Technically you can set `leading: false` in the options and it will return `undefined`, e.g.

```
> require('lodash').throttle(require('lodash').identity, 1, { leading: false })(1)
undefined
```

I guess some kind of overloading could be used to distinguish this, maybe have a simplified throttle version when there are no options provided or something.

2020-09-02 00:12 UTC, dko-slapdash commented
Yes indeed, overloading/specialization is fully supported in TS. A function can have many typings, depending on the typings of the arguments, so we may have a typing for throttle-with-two-args (without undefined) and a typing for throttle-with-three-args-where-leading-is-false (without undefined too). This TS feature is actively used in pretty much every complicated library (like React or Apollo or whatever).

2020-09-02 00:16 UTC, dobesv commented
@dko-slapdash I don't have any objections to you creating a PR for that

2020-10-08 20:35 UTC, someone1 commented
@dobesv - sorry to bump an old thread here, but just getting around to updating this type and it's breaking my code all over.

I think the culprit is the addition of the return type ` | undefined` to the original return type - is this really accurate?  It's become problematic where I'm monkey patching a void function but the return types no longer match, and it's unclear to me how we would possibly arrive at an `undefined` return.

2020-10-08 20:50 UTC, dobesv commented
@someone1 interesting problem, I guess from a practical perspective `void | undefined` doesn't make any difference.  Maybe the return type has to be something like `ReturnType<T> extends (void | undefined) ? ReturnType<T> : ReturnType<T> | undefined`

Try it out editing your local file and if it works OK you could try making a PR for that.

2020-10-08 21:05 UTC, someone1 commented
@dobesv - thanks for the quick reply! Is the addition of the `undefined` type even accurate? How would `debounce` possibly return `undefined` if not from the wrapped function?

I'll mess around with this, I also have examples where debounce wraps a `Promise<void>`

2020-10-08 21:23 UTC, dobesv commented
@someone1

The debounced function always returns undefined the first time you call it:

```
> f = require('lodash').debounce(() => true, 1)
[Function: debounced] {
  cancel: [Function: cancel],
  flush: [Function: flush]
}
> f()
undefined
> f()
true
```

All `void` functions also return `undefined` but I guess TypeScript doesn't treat `void | undefined` the same as just `void`.