AMQPLIB: exchange types are limited
DefinitelyTyped/DefinitelyTyped pull request #47047
Opened 2020-08-26 10:03 UTC by XVincentX

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

2020-08-26 10:07 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## amqplib ([<kbd>unpkg</kbd>](https://unpkg.com/browse/amqplib@latest/))
was missing the following properties:
1. IllegalOperationError
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a57903fac296ec19fe8ebab2556173f70fbe55e2
</p>

2020-09-16 19:08 UTC, XVincentX commented
@mnahkies @abreits @nfantone @zelein @elibarzilay 

Can anybody checks this out?

2020-09-22 13:46 UTC, XVincentX commented
@mnahkies @abreits @nfantone @nickzelei  @elibarzilay ping

2020-09-22 23:51 UTC, nickzelei commented
This names seem to _mostly_ match what `amqplib` natively supports. These mostly look like Rabbit topic names though.

I was looking at the rabbit docs at what they detail for the Exchange Types and this list doesn't appear to be definitive.

See the table below, but this may be missing `'' | match`
I'm not 100% on this though.

https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges

Exchange type | Default pre-declared names
-- | --
Direct exchange | (Empty string) and amq.direct
Fanout exchange | amq.fanout
Topic exchange | amq.topic
Headers exchange | amq.match (and amq.headers in RabbitMQ)

2020-09-22 23:53 UTC, nickzelei commented
Also, looks like my github name needs updated in the comments. :sweat_smile:

2020-09-23 00:03 UTC, nickzelei requested changes
Left comment on

2020-09-23 00:03 UTC, nickzelei commented on types/amqplib/index.d.ts
> +    assertExchange(exchange: string, type: 'direct' | 'topic' | 'headers' | 'fanout', options?: Options.AssertExchange): Promise<Replies.AssertExchange>;
```suggestion
    assertExchange(exchange: string, type: '' | 'direct' | 'topic' | 'headers' | 'fanout' | 'match', options?: Options.AssertExchange): Promise<Replies.AssertExchange>;
```

2020-09-23 00:33 UTC, nickzelei approved these changes

2020-10-25 16:35 UTC, merged

2020-10-26 06:51 UTC, yotamshapira commented
@nickzelei , @XVincentX - what happens if I want to use a `x-delayed-message` type or any other type that comes from a plugin?

2020-10-26 13:13 UTC, nickzelei commented
Is there a list somewhere that has a more inclusive list of types that we could update it to use? Otherwise we could append `| string` to widen the type while also providing hints for acceptable types.

2020-10-26 13:18 UTC, yotamshapira commented
> Is there a list somewhere that has a more inclusive list of types that we could update it to use? Otherwise we could append `| string` to widen the type while also providing hints for acceptable types.

I think adding `| string` is the way to go since anyone can write a plugin that adds a new type: https://www.rabbitmq.com/plugins.html#basics (See first paragraph where it says "additional AMQP 0-9-1 exchange types")

2020-11-05 06:49 UTC, ticup commented
Just a bump on the issue @yotamshapira raised.
We use the [delay-plugin](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange), which uses the `x-delayed-message` type. Consequently, the last update of the types lib broke our build, so we had to downgrade again.

2020-11-05 16:48 UTC, nickzelei commented
In progress on approving #49176

2021-02-17 13:48 UTC, ikonduktor commented
So what about 'x-delayed-message'?
Now I have to uninstall amqplib because of this beautiful types; GJ