[chai] feat(./): add missing types for `finite` and `isFinite`
DefinitelyTyped/DefinitelyTyped pull request #47268
Opened 2020-09-04 10:56 UTC by wiasliaw77210

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/chaijs/chai
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [X] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [X] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-09-06 06:40 UTC, Naktibalda requested changes

2020-09-06 06:40 UTC, Naktibalda commented on types/chai/index.d.ts
> +         * Assert that value is a finite number.
For consistency with other methods, please replace word `Assert` with `Asserts`.

2020-10-04 17:09 UTC, wiasliaw77210 commented
Hello, @Bartvds would you might review this PR? TKS.

2020-10-04 19:49 UTC, jedmao approved these changes

2020-10-05 15:55 UTC, wiasliaw77210 commented
Ready to merge

2020-10-05 15:55 UTC, merged