ScrollView's getScrollResponder should return ScrollResponderMixin ra…
DefinitelyTyped/DefinitelyTyped pull request #47325
Opened 2020-09-07 18:21 UTC by smaccoun

ScrollView's getScrollResponder should return ScrollResponderMixin, *not* JSX Element.

I believe this case and can be seen in source code here.

https://github.com/facebook/react-native/blob/206ea36253146727b5c858ddf37d7ec2fb2e12ef/Libraries/Components/ScrollView/ScrollView.js#L678

If there is an alternate type though depending on platform, would love for someone to chime in

Please fill in this template.

- [ X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-09-08 09:52 UTC, alloy requested changes
Thanks! The change seems good to me, but can you please revert all the formatting changes and add a test for how the result from the getter would typically be used?

2020-09-09 10:05 UTC, alloy commented
I would just add a tiny snippet of code of how you would actually use it. As long as that does **not** result in type-errors, it's good.

2020-09-10 15:27 UTC, smaccoun commented
> I would just add a tiny snippet of code of how you would actually use it. As long as that does **not** result in type-errors, it's good.

Gotcha, thank you. I think then maybe the test I have is okay? Some usage I've proven on a real world app is:

```
this.scrollView.getScrollResponder().scrollResponderZoomTo({
                x: 0, y: 0, width: 300, height: 500, animated: true
            })
```

I believe this is sufficient because `scrollResponderZoomTo` only belongs to the ScrollResponderMixin

https://github.com/facebook/react-native/blob/206ea36253146727b5c858ddf37d7ec2fb2e12ef/Libraries/Components/ScrollView/ScrollView.js#L77

2020-09-10 15:55 UTC, alloy commented
Yep, that looks perfect :+1:

(Sorry, I didn’t realise you had already updated with a test.)

2020-09-10 15:55 UTC, merged