Fix for useReducer in Typescript mapping to DispatcherWithoutAction
DefinitelyTyped/DefinitelyTyped pull request #47322
Opened 2020-09-07 07:57 UTC by vnvizitiu

Hello,

This is a small change that worked on my end, I can't guarantee that is works for all scenarios.

I am also using Typescript ^4.0.2

When using "React.useReducer<React.Reducer<LoginFormState, LoginFormAction>>" it points to the following definition:

    function useReducer<R extends ReducerWithoutAction<any>, I>(
        reducer: R,
        initializerArg: I,
        initializer: (arg: I) => ReducerStateWithoutAction<R>
    ): [ReducerStateWithoutAction<R>, DispatchWithoutAction];

This is wrong because:
1. I'm only using 1 generic argument so there is no "I".
2. My reducer type has 2 generic arguments for strongly types actions (which the above definition finds it as without action)

Ideally, it should take me to this definition which is marked with a TODO:

    function useReducer<R extends Reducer<any, any>>(
        reducer: R,
        initialState: ReducerState<R>,
        initializer?: undefined
    ): [ReducerState<R>, Dispatch<ReducerAction<R>>];

Without this change, I am able to use this call "React.useReducer<React.Reducer<LoginFormState, LoginFormAction>, LoginFormState>" which maps to the proper definition (the one mentioned above), except this time I'm using 2 generic arguments and it maps to the 1 generic argument form and the dispatcher doesn't have strong-typing.

So with this change it will map to:

    function useReducer<R extends Reducer<any, any>, I>(
        reducer: R,
        initializerArg: I & ReducerState<R>,
        initializer?: (arg: I & ReducerState<R>) => ReducerState<R>
    ): [ReducerState<R>, Dispatch<ReducerAction<R>>];

It is bothersome that I need to add an additional generic argument, but the comment does say the initializer can be omitted if the I matches the ReducerState<R> but the initializer wasn't omittable, now it is and I can have strongly typed actions at the cost of adding an additional generic argument.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-09-07 09:05 UTC, eps1lon requested changes
Please add a test that illustrates the issue you're trying to solve.

2020-09-07 09:51 UTC, vnvizitiu commented
I looked though the DefinitelyTyped/types/react/test/hooks.tsx file and I noticed these kind of comments "// $ExpectType MutableRefObject<number>", are these asserts for types?

I noticed this issue via the IDE, so please point me in the right direction for writing a test for the expected types. 

I also noticed that there are no tests (that I can see) for the types of dispatchers you get from using the various "useReducer" definitions and that the comment on the following definition mentions that the initializer can be omitted, but it can't from the IDE's perspective, so it might be an oversight with the initial writing of the definition.

    /**
     * An alternative to `useState`.
     *
     * `useReducer` is usually preferable to `useState` when you have complex state logic that involves
     * multiple sub-values. It also lets you optimize performance for components that trigger deep
     * updates because you can pass `dispatch` down instead of callbacks.
     *
     * @version 16.8.0
     * @see https://reactjs.org/docs/hooks-reference.html#usereducer
     */
    // overload where "I" may be a subset of ReducerState<R>; used to provide autocompletion.
    // If "I" matches ReducerState<R> exactly then the last overload will allow initializer to be ommitted.
    // the last overload effectively behaves as if the identity function (x => x) is the initializer.
    function useReducer<R extends Reducer<any, any>, I>(
        reducer: R,
        initializerArg: I & ReducerState<R>,
        initializer: (arg: I & ReducerState<R>) => ReducerState<R>
    ): [ReducerState<R>, Dispatch<ReducerAction<R>>];

2020-09-07 11:31 UTC, eps1lon commented
> but it can't from the IDE's perspective, so it might be an oversight with the initial writing of the definition.

Are you using WebStorm? That editor has a history of lacking TypeScript support. However, the priority is correct types. If IDEs don't support certain types then they should add support.

2020-09-07 11:36 UTC, vnvizitiu commented
@eps1lon I'm using Jetbrains Rider, so yeah, technically I think it's using the same engine as WebStorm, if that's the case, I'll just keep the change locally until this gets sorted out.

Personally I don't know if this would add an impact on existing usage of the package because it was stated that the intent was so that it can be ommitable, and the change just let's that be the case.

2020-09-07 11:52 UTC, vnvizitiu commented
> Are you using WebStorm? That editor has a history of lacking TypeScript support. However, the priority is the correct types. If IDEs don't support certain types then they should add support.

The IDE does support it, but for some reason, it doesn't pick the right one, that part I blame on the IDE, but the fact that making a field ommitable with the "?" syntax fixes the issue.

Maybe part of the issue (i don't know how the IDE chooses the mapping) might come down to a priority, since the definition I want and would best fit, is declared last.

2020-09-07 16:09 UTC, vnvizitiu commented
I tried moving the following definition above others and that also fixed the problem

    function useReducer<R extends Reducer<any, any>>(
        reducer: R,
        initialState: ReducerState<R>,
        initializer?: undefined
    ): [ReducerState<R>, Dispatch<ReducerAction<R>>];

Let me know if you prefer this change because it is my opinion that strongly-typed dispatchers would be more often encountered than the actionless ones (which I mostly encountered as hack to implement a "force refresh" functionality).

So putting the actionless definitions above might have had worse consequences than letting someone pick and choose their definition.

Maybe, as a suggestion (though this might incur some breaking changes for existing software, and possibly confusion) would be to make a new mapping for useActionlessReducer. I would think that if the React team wanted an actionless reducer they would have implemented it as an alternative (instead they reference it only for force refresh https://reactjs.org/docs/hooks-faq.html#is-there-something-like-forceupdate) as such, these mappings add functionality that is not part of the React documentation.

Please let me know your thoughts.

2020-09-08 14:21 UTC, ferdaber commented
I'm not sure if Webstorm uses the TS language server to provide the goto-definition functionality, but we should aim to match the types such that it matches what the TS language server expects. Of course, this could also be a regression on the TS language server side, but we'd need to check using a TS-based IDE like VS Code

2020-09-08 14:52 UTC, vnvizitiu commented
> 
> 
> I'm not sure if Webstorm uses the TS language server to provide the goto-definition functionality, but we should aim to match the types such that it matches what the TS language server expects. Of course, this could also be a regression on the TS language server side, but we'd need to check using a TS-based IDE like VS Code

I just checked with VS, you're right, the issue does not occur on VS Code, now I don't know which IDE is right, leaning towards VS Code.

I still stand by my claim that the addition that caused this issue was made for a fringe case. There is a similar issue highlighted on the commit (https://github.com/DefinitelyTyped/DefinitelyTyped/commit/24f1d0c82da2d898acd03fbb3e692eba3c431f82#comments) that in need to write out a long generic argument just to tell the IDE where to look, and even then it's not satisfied until I change the package locally, which will get overwritten once I refresh the yarn packages.

@ferdaber Question, is the question of this package being supported by the latest TS server (presuming VS Code) or a larger number of IDEs?

Open to any suggestions as long as this fixes the issue so that I don't need to change it manually. Also, I'm not as accustomed to the inner workings of the TS Server, so any hint or indication is appreciated.

2020-09-08 15:00 UTC, ferdaber commented
The TS language server provides the "canonical implementation" of how definitions should work in order of priority, since they are written by the same people who wrote the language itself. If an IDE chooses to write their own language server (or some other implementation), then the onus is on that team to ensure that it works correctly with the language. All DT packages are written to support the official TypeScript implementation. Mainly, via this heuristic:

https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#ordering

2020-09-08 15:13 UTC, vnvizitiu commented
Fair enough.

Looking at the implementation done on the 20th of December, I can't tell which one of the implementations for actionless dispatchers is more general or more specific, except that they have been placed above the old implementation.

2020-10-02 07:06 UTC, closed without merging