@types/ramda: add indexBy key typing
DefinitelyTyped/DefinitelyTyped pull request #47379
Opened 2020-09-09 15:58 UTC by whitecolor

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-09-09 16:02 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. sequence
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0b9df8a2654ce8e1a7fdd9697833dd672e5482e0
</p>

2020-09-09 19:57 UTC, Nicholaiii requested changes
Please fill out the PR template, and update tests to reflect your changes.

2020-09-10 16:45 UTC, whitecolor commented
@Nicholaiii 

test added 
lint error is not referred to PR
prettier formatting is not applied to source code

2020-09-10 19:33 UTC, Nicholaiii approved these changes

2020-09-21 18:46 UTC, merged

2020-09-22 10:37 UTC, whitecolor commented
@ sheetalkamat @Nicholaiii 
who is currently responsible for `@types/ramda` to discuss https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47695 ?
It is not clear who is the maintainer of the package, in the index.d.ts there is a long list of "authors".

2020-09-22 23:14 UTC, Nicholaiii commented
Everyone on the author list are maintainers. I can give your suggestion a look tomorrow. I'm not directly opposed to the idea personally.

2020-09-23 09:52 UTC, whitecolor commented
@Nicholaiii Ok. Should I put everyone on the list in an issue to get a response?

Btw, there is another PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47377

2020-09-23 16:49 UTC, Nicholaiii commented
> @Nicholaiii Ok. Should I put everyone on the list in an issue to get a response?
> 
> Btw, there is another PR #47377

Nope! No need for that, [the bot already does.](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47379#issuecomment-689657306)

2020-09-23 16:59 UTC, whitecolor commented
@Nicholaiii I mean for created issues, not PRs.

2020-09-23 17:14 UTC, Nicholaiii commented
> @Nicholaiii I mean for created issues, not PRs.

The issue template probably instructs you on what to do, but likely, yes.