[scriptable-ios]: Update for Scriptable app v1.5.0
DefinitelyTyped/DefinitelyTyped pull request #47739
Opened 2020-09-17 20:02 UTC by schl3ck

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.scriptable.app (no changelog there) or https://apps.apple.com/us/app/scriptable/id1405459188 (see _Version history_)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

-----
`npm run lint scriptable-ios` gives me an error `The 'no-redundant-jsdoc-2' rule threw an error in <file>: Unexpected tag kind: JSDocSeeTag`. Does this mean that the `@see` tag is not allowed? If yes, what is the reason?

2020-09-22 06:38 UTC, FuJuntao requested changes

2020-09-22 06:38 UTC, FuJuntao commented on types/scriptable-ios/index.d.ts
> +     * _Left aligns the image._
This should be "Center", right?

2020-09-22 06:38 UTC, FuJuntao commented on types/scriptable-ios/index.d.ts
> +     * Specifies that image should be left aligned.
Here is "center" too.

2020-09-22 06:38 UTC, FuJuntao commented on types/scriptable-ios/index.d.ts
> +     * _Left aligns the text._
```suggestion
     * _Center aligns the text._
```

2020-09-22 06:38 UTC, FuJuntao commented on types/scriptable-ios/index.d.ts
> +     * Specifies that text should be left aligned.
```suggestion
     * Specifies that text should be center aligned.
```

2020-09-22 11:01 UTC, schl3ck commented
Thank you @FuJuntao for spotting the typos!

I've checked the whole file for types now.

2020-09-22 11:25 UTC, FuJuntao approved these changes
Looking good to me! By the way, may I ask when will this be released?

2020-09-28 21:24 UTC, schl3ck commented
Can somebody please merge this anytime soon?

2020-10-06 19:45 UTC, schl3ck commented
@FuJuntao Can you please review the new changes?

2020-10-07 01:45 UTC, FuJuntao approved these changes

2020-10-07 06:29 UTC, schl3ck commented
Ready to merge

2020-10-07 06:30 UTC, merged