Export ImageKit interfaces
DefinitelyTyped/DefinitelyTyped pull request #47748
Opened 2020-09-18 00:25 UTC by mattleff

This PR adds support for importing the ImageKit interfaces into other TS code.

----

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

2020-09-18 01:07 UTC, mattleff commented
@sandersn The CI failure is a test-all failure unrelated to my changes. Thanks for taking a look!

2020-09-18 02:33 UTC, jablko commented
@mattleff The CI failure fell in the window between releasing [@definitelytyped/definitions-parser v0.0.54](https://github.com/microsoft/DefinitelyTyped-tools/commit/dfb84eb1d27d9db46e92fcd2490ab41525104db7), which includes microsoft/DefinitelyTyped-tools#93, and landing #44091, which I've just marked ready for review.

The DefinitelyTyped-tools change enables it to find files that previously required exceptions, and #44091 removes those exceptions. The changes are interdependent: Regardless of which lands first, there's a window of CI failure. Apologies!

2020-09-18 16:44 UTC, sandersn commented
master is in a good state now, but it looks like you'll have to merge from master to get CI passing. Sorry about the break.

2020-09-18 17:08 UTC, romdim approved these changes

2020-09-18 22:50 UTC, sandersn requested changes

2020-09-18 22:50 UTC, sandersn commented on types/imagekit/tslint.json
> +        "no-redundant-jsdoc-2": false
This rule crashes on `@see` right now, but shouldn't fail CI. Can you revert this for now?

(I merged a fix this morning but haven't shipped it yet.)

2020-09-20 17:13 UTC, romdim approved these changes

2020-09-20 17:16 UTC, mattleff commented
Ready to merge

2020-09-20 17:17 UTC, merged

2021-02-12 06:31 UTC, gregegan commented on types/imagekit/index.d.ts
> +        listFiles(listFilesOptions: ImageKit.ListFileOptions): Promise<ImageKit.ListFileResponse>;
It looks like this should be `Promise<ImageKit.ListFileResponse[]>`

https://docs.imagekit.io/api-reference/media-api/list-and-search-files

`The JSON-encoded response has an array of items. Each item can have the following properties.`