QUnit test methods allow an async function to be provided.
DefinitelyTyped/DefinitelyTyped pull request #47782
Opened 2020-09-18 22:13 UTC by wagenet

The lack of explicit support is generally not problematic except when
used in conjunction with @typescript-eslint/no-misused-promises which
complains when a Promise is provided to a function that doesn't allow
for it.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://api.qunitjs.com/QUnit/test/
> QUnit.test() can automatically handle the asynchronous resolution of a Promise on your behalf if you return a thenable Promise as the result of your callback function.
- ~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- ~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.~

2020-09-18 23:05 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ember-qunit ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ember-qunit@latest/))
was missing the following properties:
1. name
1. init
1. included
1. targetOptions
1. contentFor

<details>
<summary>as well as these 3 other properties...</summary>
<p>treeForVendor, treeForAddonTestSupport, setTestGenerator</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f86112f7feaa5b20c61ef52671eb94b6edd83e4e
</p>

2020-09-22 16:51 UTC, chriskrycho requested changes
👍 very good – please add the same test for `only`, `todo`, and `skip` to make sure we don't regress!

2020-09-22 18:00 UTC, chriskrycho approved these changes
:shipit: thank you!

2020-09-22 18:01 UTC, wagenet commented
Ready to merge

2020-09-22 18:02 UTC, merged