[qunit] Explicitly support Promise callbacks
DefinitelyTyped/DefinitelyTyped pull request #47888
Opened 2020-09-22 18:34 UTC by wagenet

The lack of explicit support is generally not problematic except when
used in conjunction with @typescript-eslint/no-misused-promises which
complains when a Promise is provided to a function that doesn't allow
for it.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
https://api.qunitjs.com/callbacks/QUnit.begin/
https://api.qunitjs.com/callbacks/QUnit.done/
https://api.qunitjs.com/callbacks/QUnit.moduleDone/
https://api.qunitjs.com/callbacks/QUnit.moduleStart/
https://api.qunitjs.com/callbacks/QUnit.testDone/
https://api.qunitjs.com/callbacks/QUnit.testStart/

2020-09-23 23:42 UTC, jamescdavis requested changes

2020-09-23 23:42 UTC, jamescdavis commented on types/qunit/index.d.ts
> +        begin(callback: (details: QUnit.BeginDetails) => void): void | Promise<void>;
I think you want:
```suggestion
        begin(callback: (details: QUnit.BeginDetails) => void | Promise<void>): void;
```
(for all of these)

2020-09-23 23:44 UTC, wagenet commented on types/qunit/index.d.ts
> +        begin(callback: (details: QUnit.BeginDetails) => void): void | Promise<void>;
Oops, you are correct!

2020-09-23 23:46 UTC, wagenet commented
@jamescdavis fixed.

2020-09-23 23:52 UTC, jamescdavis approved these changes
Thanks for this!

2020-09-24 04:37 UTC, wagenet commented
Ready to merge

2020-09-24 04:38 UTC, merged