[forest-express-sequelize] separate smart field|action|segment option from collection option
DefinitelyTyped/DefinitelyTyped pull request #48097
Opened 2020-09-23 06:16 UTC by purwk

just wanted to create separate definitions for each collection options.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-09-23 06:20 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## forest-express-sequelize ([<kbd>unpkg</kbd>](https://unpkg.com/browse/forest-express-sequelize@latest/))
was missing the following properties:
1. ensureAuthenticated
1. ResourceSerializer
1. ResourceDeserializer
1. Schemas
1. ResourcesRoute

<details>
<summary>as well as these 32 other properties...</summary>
<p>init, opts, getLianaName, getLianaVersion, getOrmVersion, getDatabaseType, SchemaAdapter, getModels, getModelName, getModelNameOld, ResourcesGetter, ResourceGetter, ResourceCreator, ResourceUpdater, ResourceRemover, ResourcesExporter, ResourcesRemover, HasManyGetter, HasManyAssociator, HasManyDissociator, BelongsToUpdater, ValueStatGetter, PieStatGetter, LineStatGetter, LeaderboardStatGetter, QueryStatGetter, RecordsDecorator, Stripe, Intercom, Closeio, Layer, Mixpanel</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 64845a600baa81f0221ccb8f2ad0fb54a688506d
</p>

2020-09-30 08:42 UTC, SteveBunlon commented on types/forest-express-sequelize/forest-express-sequelize-tests.ts
> +    SmartActionOption, SmartFieldOption, SmartSegmentOption,
I would rather write `SmartActionOptions, SmartFieldOptions, SmartSegmentOptions` to be consistent with `CollectionOptions`.

2020-09-30 08:44 UTC, SteveBunlon requested changes
Thanks a lot for maintaining this types 🙌 🎊 

May I ask you to do the same for forest-express-mongoose please ? They share the same types but are different packages, so we need to duplicate every changes to propagate changes. 

Thanks 🙏

2020-09-30 08:44 UTC, SteveBunlon commented on types/forest-express-sequelize/forest-express-sequelize-tests.ts
> +    SmartActionOption, SmartFieldOption, SmartSegmentOption,
I would rather write `SmartActionOptions, SmartFieldOptions, SmartSegmentOptions` to be consistent with `CollectionOptions`.

2020-10-01 14:13 UTC, SteveBunlon approved these changes
Thanks a lot for this PR 🙏 ❤️

Let's 🔥 !

2020-10-03 00:43 UTC, amcasey approved these changes

2020-10-05 11:51 UTC, purwk commented
Ready to merge

2020-10-05 11:52 UTC, merged