[@types/lodash]: re-introduce extending of LodashConvertible interface in generate-fp.ts
DefinitelyTyped/DefinitelyTyped pull request #48183
Opened 2020-09-25 17:39 UTC by mirkode

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-09-26 15:15 UTC, aj-r requested changes

2020-09-26 15:15 UTC, aj-r commented on types/lodash/tsconfig.json
> +        "fp/add.d.ts",
I don't think we need all of these anymore. You might need to fix `generalte-fp.ts` so it stops adding all of these.

2020-09-26 15:15 UTC, aj-r commented on types/lodash/fp.d.ts
> +        <TKey extends keyof T>(iteratee: TKey): lodash.Dictionary<T[TKey]>;
I think this is causing a build error (T doesn't exist). Ideally `generate-fp.ts` should be fixed, but for now you can manually revert the LodashMapValues changes to unblock this PR.

Same for LodashOmit.

2020-09-28 09:18 UTC, mirkode commented
Hi @aj-r ,

Thanks for your quick review.
I addressed the things you've pointed out.
I think manually changing the `fp.d.ts` file to add the generics causes the tests to fail.

Not sure how quickly I can fix that given the zero experience I have with this project :-)

But if you have another moment, please feel free to check, if what I've done so far is correct.

Thanks!

2020-11-02 04:20 UTC, closed without merging