[ember-feature-flag] export enableFeature
DefinitelyTyped/DefinitelyTyped pull request #48259
Opened 2020-09-27 23:25 UTC by BarryThePenguin

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/kategengler/ember-feature-flags/blob/v6.0.0/addon-test-support/index.js#L4
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-09-27 23:33 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ember-feature-flags ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ember-feature-flags@latest/))
was missing the following properties:
1. name
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6cead8a996b56deb85d0f038425a2bf8d8fd917d
</p>

2020-09-28 12:09 UTC, tansongyang approved these changes

2020-09-28 13:25 UTC, chriskrycho requested changes
This is a good change, but it’s also breaking! It won’t work for consumers of the older version of the addon. DT has mechanics for exactly this that we should use: a dedicated folder and a bit of config. See the README for details, and I’ll happily advise via Discord later today!

2020-09-28 22:34 UTC, BarryThePenguin commented
Thanks Chris, happy to mark it as a breaking change. Based on my research, I'm unsure it's necessary? 👀 

From looking at the history of `enableFeature`, unlike `withFeature`, it never was a test helper. So using `declare` would never have worked alongside `import { enableFeature } from ...`. Which is the issue I've run into – it's not currently possible to use `enableFeature` with TypeScript.

https://github.com/kategengler/ember-feature-flags/pull/67 is the PR that introduced `enableFeature`

Maybe the original type was a copy/paste of the `withFeature` type?

Again, I'm happy to go either way here

2020-09-30 21:07 UTC, jamescdavis commented
@BarryThePenguin I think you're right that this is not actually a breaking change because #29927 typed this incorrectly in the global scope as test helper (which it never was, I verified the history) rather than as a module export.

2020-09-30 21:08 UTC, jamescdavis approved these changes

2020-09-30 22:43 UTC, BarryThePenguin commented
Ready to merge

2020-09-30 22:44 UTC, BarryThePenguin commented
Thanks James 👋

Unsure if/when the bot will merge the PR, I'll keep an eye out for it 👀

2020-10-01 02:14 UTC, chriskrycho approved these changes
Whoops, I misunderstood here. 👍 Thanks!

2020-10-01 04:02 UTC, BarryThePenguin commented
Ready to merge

2020-10-01 04:02 UTC, merged