[k6] Update for v0.28
DefinitelyTyped/DefinitelyTyped pull request #48315
Opened 2020-09-29 16:43 UTC by ppcano

Define options for the new Scenarios API and update definitions to v0.28

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://k6.io/docs/using-k6/scenarios
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

2020-09-30 08:00 UTC, simskij requested changes

2020-09-30 08:00 UTC, simskij commented on types/k6/options.d.ts
> +    gracefulRampDown?: number;
This should be a duration string

2020-10-01 07:57 UTC, simskij approved these changes

2020-10-01 09:12 UTC, ppcano commented
Ready to merge

2020-10-01 09:12 UTC, merged