[@types/vimeo__player] Update typings to v2.10.0
DefinitelyTyped/DefinitelyTyped pull request #48347
Opened 2020-09-30 10:51 UTC by kou029w

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint @vimeo/player`.
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - documentation: https://github.com/vimeo/player.js/blob/v2.10.0/README.md
  - pull request: https://github.com/vimeo/player.js/pull/455
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-11-05 22:31 UTC, peterblazejewicz commented on types/vimeo__player/index.d.ts
> +// Type definitions for @vimeo/player 2.10.0
```suggestion
// Type definitions for @vimeo/player 2.10
```
https://github.com/definitelyTyped/DefinitelyTyped/#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library

2020-11-05 22:34 UTC, peterblazejewicz approved these changes
LGTM!
@kou029w thx!

2020-11-06 21:36 UTC, peterblazejewicz approved these changes

2020-11-06 23:00 UTC, terrymun requested changes
The file `vimeo__player-tests.ts` is not updated with the new `getMuted` and `setMuted` methods that the definitions file now support. Please look into including them as well.

2020-11-07 18:03 UTC, peterblazejewicz commented
@terrymun the tests ships with usage that seems tb taken stright from the docs, what else should be there?

2020-11-08 00:22 UTC, terrymun commented
@peterblazejewicz My bad: for some reason when I looked at the diff, I only saw a single file being changed: changes are, I was looking at a specific commit :)

2020-11-08 00:22 UTC, terrymun approved these changes

2020-11-08 20:58 UTC, peterblazejewicz approved these changes

2020-11-17 22:48 UTC, merged