[@types/simpl-schema] Add some missing types
DefinitelyTyped/DefinitelyTyped pull request #48377
Opened 2020-09-30 22:38 UTC by yurtsiv

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:

In this PR I propose to add:

* Missing type for `autoValue`'s `this`  (https://github.com/aldeed/simpl-schema#autovalue). Note, that I didn't add all the fields from the documentation. See the issue: https://github.com/aldeed/simpl-schema/issues/412
* Missing fields in `CustomValidationContext`
* Some minor changes here and there + converted `SimpleSchemaStatic` interface to a class

2020-09-30 22:48 UTC, yurtsiv commented on types/simpl-schema/simpl-schema-tests.ts
> -SimpleSchema.extend(StringSchema);
There's no static `extend` method

https://github.com/aldeed/simpl-schema/blob/main/package/lib/SimpleSchema.js#L477

2020-10-30 14:46 UTC, yurtsiv commented
@arichter83 @deskoh @nicu-chiciuc @rafahoro 

Can someone take a look at this? Thanks!

2020-10-30 17:50 UTC, arichter83 reviewed
I will not review all formatting changes. Either you split your changes in two MRs for functionality and formatting, or you find somebody else.

2020-11-03 18:08 UTC, yurtsiv commented
@arichter83 Now it should be easier to review. Will make a separate PR for formatting.

2020-12-02 18:54 UTC, amcasey requested changes
Looks like @yurtsiv has outstanding requests.

2020-12-09 00:33 UTC, amcasey approved these changes
Seems fine to me.

2020-12-09 07:48 UTC, yurtsiv commented
Ready to merge

2020-12-09 07:50 UTC, yurtsiv commented
Ready to merge

2020-12-09 07:50 UTC, merged