[@types/react] Fix error with forwardRef & children
DefinitelyTyped/DefinitelyTyped pull request #48420
Opened 2020-10-02 01:46 UTC by MrJmpl3

Try to fix: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-10-02 07:40 UTC, eps1lon requested changes
We plan to remove implicit children in a future major React release since they are problematic: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33006

2020-10-02 08:59 UTC, MrJmpl3 commented
> 
> 
> We plan to remove implicit children in a future major React release since they are problematic: #33006

Oh, the next version is coming soon? If the answer is not, Can be this PR a temporal solution?

2020-10-02 09:31 UTC, eps1lon commented
> Oh, the next version is coming soon? If the answer is not, Can be this PR a temporal solution?

We want to **remove** implicit children. This would be a step in the wrong direction i.e. would lead to more breaking changes in the future. Implicit children was a mistake which we don't want to repeat.

2020-10-03 07:55 UTC, MrJmpl3 commented
> 
> 
> > Oh, the next version is coming soon? If the answer is not, Can be this PR a temporal solution?
> 
> We want to **remove** implicit children. This would be a step in the wrong direction i.e. would lead to more breaking changes in the future. Implicit children was a mistake which we don't want to repeat.

Ok, I close the PR.

2020-10-03 07:55 UTC, closed without merging