[fabric] Rename conflicting type Object to FabricObject
DefinitelyTyped/DefinitelyTyped pull request #48503
Opened 2020-10-05 13:26 UTC by nicu-chiciuc

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

# The problem
Unfortunately the naming of the type `Object` is quite unfortunate since it tries to augment the `Object` type from `lib.es5.d.ts`. Some editors seem to figure this out quite well, VSCode add code completions from fabric.Object, unfortunatelly, WebStorm thinks that any empty object in code must/might have properties from the `fabric.Object`.
Even reading the JsDoc/typings for the package things get confusing since it's never clear if a type is referring to the ambient `Object` type or the local one.

The PR was opened as a Draft since this seems like a pretty radical change. The name of the type could also be changed to something shorter, if it is so desired.

I've also disabled the `"no-redundant-jsdoc-2"` rule since the tests don't pass when it is enabled. The test didn't pass before the commit either. Another PR might fix the JsDoc so this rule can be reenabled, but this one is just about finding a better name for `Object`.

2020-10-05 15:15 UTC, NotWoods requested changes
Unfortunately since Fabric uses the name Object in it's JS code, renaming the type will likely cause breakages. However, we should still find a solution for the type augmentation.

Perhaps we can use `type Object	= FabricObject`?

Let's also add tests to make sure a plain JavaScript object doesn't have methods from Fabric.

2020-10-09 11:30 UTC, nicu-chiciuc commented
I guess the whole PR wasn't really thought out too well by me. I could transform it into a draft or even close the issue. I guess it was more of question whether this problem is also happening to other people and something that should be solved or left as is.

2020-10-09 17:31 UTC, NotWoods commented
Feel free to transform this into an issue and I can try and pull some of your changes. This is definitely a problem, Fabric's types shouldn't affect every object.

2020-10-11 12:31 UTC, nicu-chiciuc commented
Opened the issue https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48690. Will be closing this PR.

2020-10-11 12:31 UTC, closed without merging