Reintroduce CONTRIBUTING.md
DefinitelyTyped/DefinitelyTyped pull request #48931
Opened 2020-10-20 00:03 UTC by jablko

The "How can I contribute?" section of the README is quite long, would it make sense to [reintroduce](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/14822) a [CONTRIBUTING file](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors)?

2020-10-20 01:03 UTC, elibarzilay requested changes
See the comment about changing the text.  It also made some good changes, but in general I think that it's best to keep it to two separate PRs: one that moves the text as-is (which is probably just removing the second commit here), and another that does the markdown tweaking (but the way that it did it here, I have many objections...).

2020-10-20 15:18 UTC, jablko commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/CONTRIBUTING.md#make-a-pull-request).
Done. :heavy_check_mark:

2020-10-20 15:19 UTC, jablko commented on CONTRIBUTING.md
> +# How can I contribute?
Yup, unedited. I've updated the log message. :heavy_check_mark:

2020-10-20 15:21 UTC, jablko commented
@elibarzilay Thanks for the feedback, I've separated the commits. :heavy_check_mark:

2020-10-20 16:16 UTC, sandersn requested changes
I don't like having a separate file, since (1) the majority of people reading Definitely Typed's README are there to contribute (2) non-contributors can stop reading early on, since the useful command `npm i @types/x` happens before any contributing instructions.

Since contributing is the default case, and since github puts README on the front page of a repo, it makes sense to include the contributing instructions, even though they're long.

Thoughts from other DT maintainers?

2020-10-20 16:50 UTC, orta commented
Yeah, I think I'm with Nathan here - the README is basically only the contributors guideline. There's a part of me that's wanted to move some of this to the site, but the co-location is super valuable and I've punted on it also for the same reasons.

2020-10-20 16:57 UTC, jablko commented
Or, are there other changes I could make to aid navigation? No disagreement that it's basically the contributors guideline, but I find some details get buried in there.

2020-10-20 17:08 UTC, elibarzilay commented
Maybe make a new contributing.md which has a one-page command-line-centric summary of how to make a PR, with a pointer to the readme for further details?

2020-10-24 05:35 UTC, elibarzilay commented
(Closing this since it looks like it not a popular change...)

2020-10-24 05:35 UTC, closed without merging