update(serialize-javascript): update to v5 and minor fixes
DefinitelyTyped/DefinitelyTyped pull request #49163
Opened 2020-10-27 21:15 UTC by peterblazejewicz

- `unsafe` can be only explicit `true`
- `space` as `number | string` can be used as second argument to
  `serialize`
- version 5 bump
- maintainer GitHub handle corrected (how it was really merged in the
  first place)
- maintainer added

https://github.com/yahoo/serialize-javascript/compare/v4.0.0...v5.0.1
https://github.com/yahoo/serialize-javascript/blob/main/index.js#L62
https://github.com/yahoo/serialize-javascript#optionsunsafe

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
- [x] If this PR brings the type definitions up to date with a new version of the JS library, updat the version number in the header.
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

2020-11-11 05:25 UTC, undefined-moe requested changes

2020-11-11 05:25 UTC, undefined-moe commented on types/serialize-javascript/serialize-javascript-tests.ts
> +serialize(obj, {
why a line break here?

2020-11-13 05:12 UTC, undefined-moe requested changes

2020-11-13 05:12 UTC, undefined-moe commented on types/serialize-javascript/index.d.ts
>  // Project: https://github.com/yahoo/serialize-javascript
bump version at Line 1

2020-11-14 04:13 UTC, undefined-moe approved these changes

2020-12-02 04:12 UTC, undefined-moe commented
The bot cannot recognize my account now :thinking:

2020-12-02 21:42 UTC, peterblazejewicz commented
We need heavy cavalry, @sandersn at your pace, sir, thx!

2020-12-02 23:48 UTC, sandersn approved these changes

2020-12-03 20:45 UTC, peterblazejewicz commented
Thx!

2020-12-03 20:45 UTC, peterblazejewicz commented
Ready to merge 💋

2020-12-03 20:46 UTC, merged