[@ember/routing] add RouteInfoWithAttributes
DefinitelyTyped/DefinitelyTyped pull request #49296
Opened 2020-11-01 10:04 UTC by jamescdavis

This add [RouteInfoWithAttributes](https://api.emberjs.com/ember/3.6/classes/RouteInfoWithAttributes) and uses it in appropriate places. It also adds [buildRouteInfoMetadata](https://api.emberjs.com/ember/3.18/classes/Route/methods/buildRouteInfoMetadata?anchor=buildRouteInfoMetadata) to `@ember/routing/route` and [recognize](https://api.emberjs.com/ember/3.6/classes/RouterService/methods/recognize?anchor=recognize) and [recognizeAndLoad](https://api.emberjs.com/ember/3.6/classes/RouterService/methods/recognize?anchor=recognizeAndLoad) to `@ember/routing/router-service`.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://api.emberjs.com/ember/3.6/classes/RouteInfoWithAttributes
- [ ] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.~~

2020-11-01 12:32 UTC, jamescdavis commented
@mike-north @chriskrycho @dfreeman not sure where the bot is. vOv

2020-11-01 13:07 UTC, chriskrycho approved these changes

2020-11-01 13:09 UTC, chriskrycho requested changes
Caught one thing after the initial pass. Thanks for adding this!

2020-11-01 13:09 UTC, chriskrycho commented on types/ember__routing/router-service.d.ts
> +    rootURL: string;
I think this should be `readonly`?

2020-11-01 18:55 UTC, jamescdavis commented
@chriskrycho updated

2020-11-01 18:56 UTC, chriskrycho requested changes
With apologies for another Request Changes—I should have thought of this when making my suggestion earlier—but we should `// $ExpectType Readonly<string>` etc. for all the `readonly` types.

2020-11-01 19:05 UTC, jamescdavis commented
@chriskrycho 🤔  wait, I don't think `Readonly` works that way: https://www.typescriptlang.org/docs/handbook/utility-types.html#readonlytype

2020-11-01 20:12 UTC, chriskrycho commented
Ah, I believe you're correct, it's actually the `readonly` modifier proper, I believe, like this:

```ts
router.rootURL; // $ExpectType readonly string
```

That said, I haven't poked at that corner of DTSLint in a *while*, so I'm not positive that works outside the context of arrays. 🤔

2020-11-02 16:51 UTC, jamescdavis commented
@chriskrycho indeed, `readonly` only works for arrays and tuples marked as `readonly`. AFAICT, there's no way to check that a property is marked as `readonly`. To try to find an example, I ran a case-insensitive grep of all tests in DT for `$ExpectType.*readonly` and the handful of matches are all for arrays or tuples.

2020-11-02 17:02 UTC, jamescdavis commented
Oh, wait, 🤦 :
```ts
router.rootURL = 'foo'; // $ExpectError
```

2020-11-02 20:46 UTC, jamescdavis commented
@orta, as another data point, @typescript-bot seems to be ignoring this one too (I pushed a revision and it hasn't updated status, re-requested review, etc).

2020-11-03 02:09 UTC, chriskrycho commented
Hahaha, that’s a good call. Should have thought of that myself.

2020-11-03 02:10 UTC, chriskrycho requested changes
Ugh, sorry, one more round.

2020-11-03 02:10 UTC, chriskrycho commented on types/ember__routing/-private/route-info-with-attributes.d.ts
> +    readonly attributes: any;
```suggestion
    readonly attributes: unknown;
```

2020-11-03 02:10 UTC, chriskrycho commented on types/ember__routing/-private/route-info-with-attributes.d.ts
> +    readonly metadata: any;
```suggestion
    readonly metadata: unknown;
```

2020-11-03 02:10 UTC, chriskrycho commented on types/ember__routing/route.d.ts
> +    buildRouteInfoMetadata(): any;
```suggestion
    buildRouteInfoMetadata(): unknown;
```

2020-11-03 13:17 UTC, jamescdavis commented
@chriskrycho good call on `unknown`. I guess I was translating a little too literally from the docs! 😆

2020-11-03 23:02 UTC, chriskrycho approved these changes
:shipit:

2020-11-03 23:26 UTC, chriskrycho commented
Ready to merge

2020-11-03 23:27 UTC, merged

2020-11-04 00:06 UTC, chancancode commented
eh, should the bot have required the files to be up-to-date? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49340 was merged earlier today and now there is a soft-conflict (the `rootURL` property is declared twice).

2020-11-04 00:35 UTC, chancancode commented
#49345 will resolve the conflict, but seems like something that the bot should account for/enforce