Add ContainerProps to react-select exports
DefinitelyTyped/DefinitelyTyped pull request #49398
Opened 2020-11-06 16:51 UTC by charliemday

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

2020-11-06 18:30 UTC, Methuselah96 requested changes

2020-11-06 18:30 UTC, Methuselah96 commented on types/react-select/index.d.ts
> +export { ContainerProps } from './src/components/containers';
Can you combine all the exports from `./src/components/containers`?

2020-11-06 21:17 UTC, Methuselah96 approved these changes

2020-11-06 23:06 UTC, andrewbranch approved these changes

2020-11-07 13:41 UTC, charliemday commented
Ready to merge

2020-11-07 13:42 UTC, merged