[relay-runtime]: mark scheduleGC public
DefinitelyTyped/DefinitelyTyped pull request #49507
Opened 2020-11-12 11:49 UTC by maraisr

Facebook has imported the accompanying PR internally, and will likely land.  This PR just stages that and **MUST** only be merged once https://github.com/facebook/relay/pull/3167 is merged.

2020-11-12 11:53 UTC, n1ru4l commented
@maraisr Thank you!!

2020-11-12 11:53 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. MutationTypes
1. RangeOperations
1. MutationHandlers
1. VIEWER_ID

<details>
<summary>as well as these 9 other properties...</summary>
<p>VIEWER_TYPE, PreloadableQueryRegistry, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isScalarAndEqual, recycleNodesInto, stableCopy, getFragmentIdentifier</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against fa22e820af245da9b4247e10c6fafdc191083c3d
</p>

2020-11-12 21:32 UTC, Stephen2 approved these changes

2020-11-13 17:44 UTC, alloy commented
Nice 👌 

While it’s merged, there’s no new release yet that includes it, no?

2020-11-13 23:13 UTC, poteto commented
@alloy this will be included in our next release - that should be cut either today or next Monday.

2020-11-16 12:27 UTC, alloy requested changes
@maraisr @poteto Please bump this PR once that release is out 🙏

2020-11-16 17:55 UTC, poteto approved these changes
We just released/published 10.1.0, this is safe to merge now. Thanks all!

2020-11-16 22:13 UTC, alloy approved these changes

2020-11-16 22:13 UTC, alloy commented
:shipit:

2020-11-16 22:14 UTC, merged