fix(express-mysql-session): Update MySQLStoreClass to inherit expressSession.Store
DefinitelyTyped/DefinitelyTyped pull request #49543
Opened 2020-11-13 15:04 UTC by Aki-7

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46576
- [x] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)

### Description

With
- @types/express-session@^1.17.1 
- @types/express-mysql-session@2.1.1

`ts` raises an error below.

![Screen Shot 2020-11-13 at 23 49 03](https://user-images.githubusercontent.com/44729662/99084850-d204f200-260a-11eb-92ab-7bb009cdf316.png)

![Screen Shot 2020-11-13 at 23 34 10](https://user-images.githubusercontent.com/44729662/99083348-c3b5d680-2608-11eb-84ce-ca8ec2993dad.png)

The changes in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46576 bring this error.
(I think https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46576 includes some breaking changes...)

#### The error occurs because...

in @types/express-session@^1.17.1, the type of `SessionOptions.store` is `Store` (`Store | MemoryStore` previously).

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4d59767cffd1823798e0a4ef53465af5ec373c86/types/express-session/index.d.ts#L81-L85

and the current type definition of `MySQLStoreClass` is missing some properties in `Store`.

This PR corrects this situation.

2020-11-13 15:20 UTC, mathe42 commented
Will look into it.

2020-11-13 16:42 UTC, mathe42 requested changes
As MySQLStoreClass now extends a base class we can remove some function definitions:
For example
```
abstract get(sid: string, callback: (err: any, session?: SessionData | null) => void): void;
```
Is defined in the parent class so we can remove it. Please have a look wich other functions we can remove.

2020-11-13 16:43 UTC, mathe42 commented
But your change looks good to me.

2020-11-13 17:50 UTC, Aki-7 commented
The methods below are defined in the parent class

`get / set / destroy / length / all / clear / touch`

### About `length` `all` `clear` ` touch` methods

These methods are optional in the parent class

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4d59767cffd1823798e0a4ef53465af5ec373c86/types/express-session/index.d.ts#L333-L342

but actually implemented. so I think the definitions in the child class should not be removed.

### About `get` `set` `destroy` methods

The current definitions of this three methods are slightly different from the parent class definitions. 

For example...

- parent definition

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4d59767cffd1823798e0a4ef53465af5ec373c86/types/express-session/index.d.ts#L323

- child definition (current definition)

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4d59767cffd1823798e0a4ef53465af5ec373c86/types/express-mysql-session/index.d.ts#L51

So, my concern is removing the definitions in the child class can be a breaking change.

```ts
// this code raises error if we remove the definitions.
const sessionStore = new MySQLStore(options);
sessionStore.get('my-session-id', (err, session) => {
    console.log(session.views);
})
```

What do you think of it?

2020-11-13 18:19 UTC, mathe42 commented
We should change this in a future PR with Breaking Changes. Its OK for me.

2020-11-13 18:20 UTC, mathe42 approved these changes

2020-11-13 18:27 UTC, Aki-7 commented
@mathe42 Thank you for your help!

2020-11-13 18:27 UTC, Aki-7 commented
Ready to merge

2020-11-13 18:28 UTC, merged

2020-11-14 17:58 UTC, HoldYourWaffle commented
@Aki-7 @mathe42 You might want to take a look at https://github.com/chill117/express-mysql-session/pull/93.
Back when I first started fixing #46576 (over 20 months ago), I also (partially) updated the `express-mysql-session` typings.

These updated typings are slightly outdated now though, because I haven't had the time to update them to the latest findings at the `express-session` side. However, this "baseline" might still be useful nonetheless.