[@types/relay-runtime]: 10.1.0 - CacheConfig
DefinitelyTyped/DefinitelyTyped pull request #49612
Opened 2020-11-16 18:59 UTC by morrys

In this PR I fix:
[RequestDescriptor](https://github.com/facebook/relay/blob/v10.1.0/packages/relay-runtime/store/RelayStoreTypes.js#L83-L88)
[createOperationDescriptor](https://github.com/facebook/relay/blob/v10.1.0/packages/relay-runtime/store/RelayModernOperationDescriptor.js#L35-L40)
[createRequestDescriptor](https://github.com/facebook/relay/blob/v10.1.0/packages/relay-runtime/store/RelayModernOperationDescriptor.js#L70-L74)
[fetchQuery internal](https://github.com/facebook/relay/blob/v10.1.0/packages/relay-runtime/query/fetchQueryInternal.js#L105-L108)

```js
export type RequestDescriptor = {|
  +identifier: RequestIdentifier,
  +node: ConcreteRequest,
  +variables: Variables,
  +cacheConfig: ?CacheConfig,
|};

function createOperationDescriptor(
  request: ConcreteRequest,
  variables: Variables,
  cacheConfig?: ?CacheConfig,
  dataID?: DataID = ROOT_ID,
): OperationDescriptor

function createRequestDescriptor(
  request: ConcreteRequest,
  variables: Variables,
  cacheConfig?: ?CacheConfig,
): RequestDescriptor

function fetchQuery(
  environment: IEnvironment,
  operation: OperationDescriptor,
): Observable<GraphQLResponse>

```

* RelayEnvironment

[execute](https://github.com/facebook/relay/blob/v10.1.0/packages/relay-runtime/store/RelayModernEnvironment.js#L362-L368)
[executeMutation](https://github.com/facebook/relay/blob/v10.1.0/packages/relay-runtime/store/RelayModernEnvironment.js#L413-L425)
```js
  execute({
    operation,
    updater,
  }: {|
    operation: OperationDescriptor,
    updater?: ?SelectorStoreUpdater,
  |}): RelayObservable<GraphQLResponse>

 executeMutation({
    operation,
    optimisticResponse,
    optimisticUpdater,
    updater,
    uploadables,
  }: {|
    operation: OperationDescriptor,
    optimisticUpdater?: ?SelectorStoreUpdater,
    optimisticResponse?: ?Object,
    updater?: ?SelectorStoreUpdater,
    uploadables?: ?UploadableMap,
  |}): RelayObservable<GraphQLResponse>
```

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] Add or edit tests to reflect the change. (Run with `npm test`.)
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
[mutationConfig](https://github.com/facebook/relay/blob/v10.0.1/packages/relay-runtime/mutations/commitMutation.js#L62-L84)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] Include [tests for your changes](https://github.com/DefinitelyTyped/DefinitelyTyped#testing)
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-11-16 19:05 UTC, sibelius approved these changes
nice

2020-11-16 22:13 UTC, maraisr requested changes
Just a few trivial things. On the outset thanks so much for doing this! ❤️ 

Think we can get some tests in there as well for this?

2020-11-16 22:13 UTC, maraisr commented on types/relay-runtime/lib/store/RelayModernOperationDescriptor.d.ts
> +    cacheConfig?: CacheConfig | null | undefined,
Think the `| undefined` isn't needed

2020-11-16 22:13 UTC, maraisr commented on types/relay-runtime/lib/store/RelayModernOperationDescriptor.d.ts
> +    cacheConfig?: CacheConfig | null | undefined,
Same here

2020-11-16 22:13 UTC, maraisr commented on types/relay-runtime/lib/store/RelayStoreTypes.d.ts
> +    readonly cacheConfig: CacheConfig | null | undefined;
And here 😅

2020-11-16 22:54 UTC, maraisr commented
> Just a few trivial things. On the outset thanks so much for doing this! ❤️ 
> 
> Think we can get some tests in there as well for this? 

I could help with this too ☝🏻

2020-11-17 08:13 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. MutationTypes
1. RangeOperations
1. MutationHandlers
1. VIEWER_ID

<details>
<summary>as well as these 9 other properties...</summary>
<p>VIEWER_TYPE, PreloadableQueryRegistry, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isScalarAndEqual, recycleNodesInto, stableCopy, getFragmentIdentifier</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5dde6ea5463485e7f1eb4c9aad98a76d49398f75
</p>

2020-11-17 10:24 UTC, alloy reviewed
I agree that it would be nice to have a few snippets of test code, at least for the operation descriptor functions.

Also, this seems like a great time to add yourself back as maintainer of the types. If you’re still interested in being kept up-to-date, mind adding yourself back?

2020-11-17 15:58 UTC, alloy commented
Thanks!

2020-11-17 15:58 UTC, merged