ProseMirror-model: Export ProsemirrorNode type so we can use it.
DefinitelyTyped/DefinitelyTyped pull request #49646
Opened 2020-11-18 07:56 UTC by ccorcos

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Add or edit tests to reflect the change. (Run with `npm test YOUR_PACKAGE_NAME`.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] Run `npm run lint package-name` (or `tsc` if no `tslint.json` is present).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

The problem I'm running into here is that its challenging use `ProsemirrorNode` as a type. For example:

```ts
const blocks: Array<ProsemirrorNode<EditorSchema>> = []
state.doc.nodesBetween(
	state.selection.from,
	state.selection.to,
	(node) => {
		if (node.isBlock) {
			blocks.push(node)
			return false
		}
	}
)
```

In order to do this, I'm currently using the following workaround:

```ts
type ProsemirrorNode<S extends Schema> = 
	ReturnType<NodeType<S>["create"]>
```

Ideally we'd just export `ProsemirrorNode` type and we're good to go.

2020-11-21 19:10 UTC, timjb requested changes
This type is already exported as `Node` by the line

```typescript
export { ProsemirrorNode as Node };
```

below the class declaration. The class is declared with the name `ProsemirrorNode` instead of `Node` to avoid a clash with TypeScript's [lib.dom.d.ts](https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts).

You can use it by either using qualified imports

```typescript
import * as model from 'prosemirror-model';

let node: model.Node = /* ... */;
```

or a renaming import


```typescript
import { Node as ProsemirrorNode } from 'prosemirror-model';

let node: ProsemirrorNode = /* ... */;
```

2020-11-21 19:36 UTC, ccorcos commented
@timjb how would you feel about exporting `ProsemirrorNode` without renaming it? It's confusing because when you hover over over a type definition, it says `ProsemirrorNode`.

![image](https://user-images.githubusercontent.com/1794527/99885948-99a67a80-2bed-11eb-826b-06cc91c714ba.png)

If I want to manually define the type for `prevNode`, I'd expect write `prevNode: ProsemirrorNode` and have that type auto-imported...

2020-11-21 19:43 UTC, timjb commented
@ccorcos The type declarations have to stay consistent with the naming of the ProseMirror JavaScript library. If we were to export `ProsemirrorNode` under that name, then the following code, which uses the [fromJSON](https://prosemirror.net/docs/ref/#model.Node^fromJSON) on that class, would type-check:

```typescript
import { ProsemirrorNode } from 'prosemirror-model';

const n = ProsemirrorNode.fromJSON(response.json);
```

But we would get a runtime error, since in Prosemirror, the class is called `Node`, not `ProsemirrorNode`.

2020-11-21 20:03 UTC, timjb commented
@ccorcos I agree that the hover information is confusing. To fix this, we could rename `ProsemirrorNode` to `Node`, introducing a namespace declaration to avoid a clash with `Node` from lib.dom.d.ts as suggested in [this Stack Overflow answer](https://stackoverflow.com/a/60593236/767120):

```typescript
export = ProsemirrorState;

declare namespace ProsemirrorState {
  // ...
  export class Node<S extends Schema = any> { // was previously called ProsemirrorNode
    // ...
  }
  // ...
}
```

2020-11-22 02:46 UTC, ccorcos commented
Hmm. Why do you need the namespace declaration? Can't you just `import {Node as ProsemirrorNode} from "prosemirror-state"` to avoid the conflict?

2020-11-22 10:21 UTC, timjb commented
@ccorcos I'm suggesting a change to the type declarations, not to (your) application code. The type declarations must export the class as `Node`, because that's the name that ProseMirror uses. The confusion for users arises from the fact that in the type definition, the class is declared with the name `ProsemirrorNode`. I'm suggesting to resolve that by instead only using the name `Node` in the type declarations. For this, I believe that we need the namespace declaration.

2020-11-23 19:13 UTC, ccorcos commented
I get that. Not sure we really need the namespace though. I think we can just call it Node: `declare class ProsemirrorNode` → `export class Node`

2020-12-11 03:32 UTC, closed without merging