[@testing-library/jest-dom] Allow all elements
DefinitelyTyped/DefinitelyTyped pull request #49707
Opened 2020-11-20 21:14 UTC by nickmccurdy

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/testing-library/react-testing-library/issues/830
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [x] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-11-20 21:31 UTC, jgoz requested changes
Hmm, I don't believe this change reflects the actual runtime behavior in jest-dom. Both of these methods use [`checkHtmlElement`](https://github.com/testing-library/jest-dom/blob/8298015b09e886e53116d4977c20924e45d3fcd9/src/utils.js#L55-L56) which explicitly verifies that they are instances of either `HTMLElement` or `SVGElement`.

The linked issue in react-testing-library discussed allowing elements such as `<circle>` to be used directly, which are not instances of either of these two prototypes.

Therefore, I think the correct order of operations would be to first open a PR in `jest-dom` to make these assertions compatible with the non-root SVG elements, and then reflect that in the typings.

2020-11-30 20:57 UTC, nickmccurdy commented
I thought we could go without this, but it seems like Jest DOM's runtime type checking has gotten out of sync with other type updates we've made in the organization. To remedy I've opened https://github.com/testing-library/jest-dom/issues/313 upstream. Once that's fixed I may update this pull request.

2020-12-24 02:14 UTC, nickmccurdy commented
Intentionally keeping this open as it's blocked by https://github.com/testing-library/jest-dom/issues/313

2021-01-16 16:46 UTC, nickmccurdy commented
This is still blocked but I'll close it temporarily to stop the bot from replying.

2021-01-16 16:46 UTC, closed without merging