Update index.d.ts
DefinitelyTyped/DefinitelyTyped pull request #49765
Opened 2020-11-24 12:47 UTC by wzuqui

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-12-06 17:42 UTC, sebek64 commented
Sorry, I don't care about this library anymore. The fact that I participated on the original types doesn't mean that I will support it forever. Anyone feel free to maintain it instead of me.

2020-12-06 21:51 UTC, peterblazejewicz requested changes
Please:
1) review your own code with whitespace changes contracted, you should notice duplicates union list:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49765/files?diff=unified&w=1
2) add a test for your change, otherwise it will wait here for ages until DT main mainatiner approves (tests give a quick path for PR review)

2020-12-19 20:29 UTC, peterblazejewicz commented on types/leaflet.awesome-markers/index.d.ts
> +      | 'black';
Please, this should be enum-like list, no duplicates, thx!

2020-12-23 18:30 UTC, RyanCavanaugh requested changes
Requesting same changes as other reviewer

2021-01-23 19:33 UTC, closed without merging