[fs-extra] Add missing mkdir argument
DefinitelyTyped/DefinitelyTyped pull request #49817
Opened 2020-11-26 19:24 UTC by nathan818fr

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jprichardson/node-fs-extra/blob/6bffcd81881ae474d3d1765be7dd389b5edfd0e0/lib/fs/index.js / https://nodejs.org/api/fs.html#fs_fs_mkdir_path_options_callback
  Note: this `options` argument is missing from the promised definition but present in the callback definition above.

2020-11-26 19:34 UTC, NotWoods approved these changes

2020-11-28 19:55 UTC, peterblazejewicz requested changes
as label says:

> Critical package

can you add a test, please?

2020-11-29 05:00 UTC, NotWoods approved these changes

2020-11-29 15:07 UTC, peterblazejewicz approved these changes
@nathan818fr thx, appreciate!

2020-12-07 23:58 UTC, rbuckton approved these changes

2020-12-10 22:04 UTC, peterblazejewicz commented
Ready to merge :kiss:
/cc @nathan818fr

2020-12-10 22:04 UTC, merged