@types/node: stream.pipeline() should accept iterators since Node 13.10
DefinitelyTyped/DefinitelyTyped pull request #49868
Opened 2020-11-30 16:20 UTC by voxpelli

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/stream.html#stream_stream_pipeline_source_transforms_destination_callback
- [ ] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~
- [ ] ~~If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.~~

2020-11-30 16:44 UTC, a-tarasyuk approved these changes

2020-12-08 01:06 UTC, rbuckton requested changes
The NodeJS documentation here is poor and there are some inconsistencies between the above type and the actual NodeJS runtime semantics.

2020-12-08 20:45 UTC, voxpelli commented on types/node/stream.d.ts
> +            stream1: NodeJS.ReadableStream | Iterable<any> | AsyncIterable<any>,
@rbuckton Something you want me to do meanwhile?

2020-12-17 14:59 UTC, voxpelli commented on types/node/stream.d.ts
> +            stream1: NodeJS.ReadableStream | Iterable<any> | AsyncIterable<any>,
@rbuckton I see that https://github.com/nodejs/node/issues/36437 was merged, how do we move forward with this then?

2020-12-18 03:03 UTC, rbuckton commented on types/node/stream.d.ts
> +            stream1: NodeJS.ReadableStream | Iterable<any> | AsyncIterable<any>,
That's a good question. They merged a fix to NodeJS, but that hasn't shipped yet, as far as I can tell. We either need to wait until it ships (and ensure the package version comment matches the major.minor of the shipping release), or you can make the proposed changes above now, and a separate PR that removes the `function pipeline(streams: readonly any[], ...args: any[]): never;` overload (with the package version comment change) at a later date.

2021-01-07 20:09 UTC, voxpelli commented
https://github.com/nodejs/node/issues/36437 is now released as https://github.com/nodejs/node/releases/tag/v15.5.0 @rbuckton, should we push this change into https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48981 and/or continue here?

2021-01-07 22:48 UTC, voxpelli commented
I submitted a request to backport the patch to Node 14: https://github.com/nodejs/node/pull/36831

2021-01-19 12:09 UTC, voxpelli commented
The backport has been merged, so once it’s released we can merge this I believe @rbuckton

2021-02-09 17:45 UTC, voxpelli commented
`v14.15.5` has now been released: https://nodejs.org/en/blog/release/v14.15.5/ So we can go ahead and merge this @rbuckton

2021-03-04 19:18 UTC, voxpelli commented
Rebased on top of master, still needs a review, though I'm not sure @typescript-bot gets that.

2021-03-28 10:48 UTC, voxpelli commented
I'll have to look at the CI then... Would be awesome to get some feedback now when the patch has been upstreamed.

2021-04-20 20:09 UTC, voxpelli commented
I will try to find time soon

2021-05-22 02:03 UTC, closed without merging