[relay]: adds new relay log types
DefinitelyTyped/DefinitelyTyped pull request #50002
Opened 2020-12-07 22:16 UTC by maraisr

Adds in new network log types as per https://github.com/facebook/relay/commit/95606c5ed

2020-12-07 22:20 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## relay-runtime ([<kbd>unpkg</kbd>](https://unpkg.com/browse/relay-runtime@latest/))
was missing the following properties:
1. ReplaySubject
1. getNode
1. reportMissingRequiredFields
1. isFragment
1. isInlineDataFragment

<details>
<summary>as well as these 13 other properties...</summary>
<p>isRequest, MutationTypes, RangeOperations, MutationHandlers, VIEWER_ID, VIEWER_TYPE, PreloadableQueryRegistry, createPayloadFor3DField, RelayError, DEFAULT_HANDLE_KEY, isScalarAndEqual, recycleNodesInto, stableCopy</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e982182a91a666e8068a8001486331acdda0a879
</p>

2020-12-08 11:10 UTC, alloy requested changes
One small request, otherwise looks good 👍

2020-12-08 11:10 UTC, alloy commented on types/relay-runtime/lib/store/RelayStoreTypes.d.ts
> +        info: any,
The TS `unknown` type semantically maps best to [Flow’s `mixed`](https://flow.org/en/docs/types/mixed/)

```suggestion
        info: unknown,
```

2020-12-08 21:49 UTC, alloy commented
👍

2020-12-08 21:49 UTC, merged