[redux-form] fix type for registeredFields
DefinitelyTyped/DefinitelyTyped pull request #50039
Opened 2020-12-09 17:50 UTC by oskarolsson-jimdo

The `registeredFields` property on `FormState` has the wrong type. Since it represents what's in the redux store it shouldn't be a list of `RegisteredFieldState`; instead it should be an nested object where the path for the field is the key for each `RegisteredFieldState` object.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an NPM package, match the name. If not, do not conflict with the name of an NPM package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` should be present and it shouldn't have any additional or disabling of rules. Just content as `{ "extends": "dtslint/dt.json" }`. If for reason the some rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]`  and not for whole package so that the need for disabling can be reviewed.
- [ ] `tsconfig.json` should have `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2020-12-09 17:54 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## redux-form ([<kbd>unpkg</kbd>](https://unpkg.com/browse/redux-form@latest/))
was missing the following properties:
1. defaultShouldAsyncValidate
1. defaultShouldValidate
1. defaultShouldError
1. defaultShouldWarn
1. propTypes

<details>
<summary>as well as these 8 other properties...</summary>
<p>fieldInputPropTypes, fieldMetaPropTypes, fieldPropTypes, fieldArrayFieldsPropTypes, fieldArrayMetaPropTypes, fieldArrayPropTypes, formPropTypes, values</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 774dc72875a781b5751ee6bccaa65c091818c8dd
</p>

2020-12-10 21:20 UTC, rbuckton commented on types/redux-form/lib/reducer.d.ts
> +    registeredFields: { [name: string]: RegisteredFieldState };
From what I can tell, the state in the store is read/written based on calls to [`getIn`](https://github.com/redux-form/redux-form/blob/0c4a04777d812b4f6769bbcb26e3d7eef359a586/src/structure/plain/getIn.js#L4) and [`setIn`](https://github.com/redux-form/redux-form/blob/0c4a04777d812b4f6769bbcb26e3d7eef359a586/src/structure/plain/setIn.js#L39), which theoretically allow the state to be either an object or an array?

The test here shows `registeredFields` being used as an array: https://github.com/redux-form/redux-form/blob/0485967d7f98b349e850570a2f2f3a4124f392d8/src/__tests__/helpers/reducer.reset.js#L135

I honestly don't know enough about `redux-form` to know whether this is correct.

2021-01-01 23:01 UTC, elibarzilay commented
@oskarolsson-jimdo, anything happening with this?

2021-01-04 23:36 UTC, andrewbranch requested changes
Requesting changes on behalf of @rbuckton’s comments

2021-02-05 01:30 UTC, closed without merging