Adding AnonymousUtils definition for parse
DefinitelyTyped/DefinitelyTyped pull request #50060
Opened 2020-12-10 13:22 UTC by gnunicorn

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://parseplatform.org/Parse-SDK-JS/api/2.18.0/Parse.AnonymousUtils.html
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- [ ] If you are making substantial changes, consider adding a `tslint.json` containing `{ "extends": "dtslint/dt.json" }`. If for reason the any rule need to be disabled, disable it for that line using `// tslint:disable-next-line [ruleName]` and not for whole package so that the need for disabling can be reviewed.

2020-12-10 13:27 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## parse ([<kbd>unpkg</kbd>](https://unpkg.com/browse/parse@latest/))
was missing the following properties:
1. idempotency
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0c2934f59001dac2f429c7cf83ccb19548510bec
</p>

2020-12-22 02:57 UTC, RaschidJFR requested changes
Thanks for your work. Would you mind also adding these same changes to the the files inside the folder `ts3.6/` so your contributions are available for newer TS versions?

2020-12-22 02:57 UTC, RaschidJFR commented on types/parse/index.d.ts
> +        function logIn(options?: FullOptions): Promise<User>;
```suggestion
        function logIn(options?: ScopeOptions): Promise<User>;
```

2020-12-22 02:57 UTC, RaschidJFR commented on types/parse/index.d.ts
> +        function link(user: User, options?: SuccessFailureOptions): Promise<User>;
```suggestion
        function link(user: User, options?: ScopeOptions): Promise<User>;
```

2020-12-22 02:57 UTC, RaschidJFR commented on types/parse/index.d.ts
> +        function init(): void;
I can't find any reference to the `init()` function in the [source code](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/AnonymousUtils.js). Should we remove this?
```suggestion
```

2020-12-22 02:57 UTC, RaschidJFR commented on types/parse/parse-tests.ts
> +    return Parse.AnonymousUtils.logIn({});
```suggestion
    // $ExpectType boolean
    Parse.AnonymousUtils.isLinked(new Parse.User());
    // $ExpectType Promise<User<Attributes>>
    Parse.AnonymousUtils.link(new Parse.User(), { useMasterKey: true, sessionToken: '' });
    // $ExpectType Promise<User<Attributes>>
    Parse.AnonymousUtils.logIn({},  { useMasterKey: true, sessionToken: '' });
```

2020-12-30 22:32 UTC, RaschidJFR commented
Hey @gnunicorn I see you've been busy, thanks a lot. It's late now to tell you, but for the next time it will save you time to run the tests on your end before pushing. Like this: `$ npm test parse`.

Just waiting for the bot to finish and we're good to go.

2020-12-30 22:37 UTC, gnunicorn commented
yeah, running tests locally failed for other reasons, had to fight on the CI, sorry for the noise!

2021-01-01 16:02 UTC, gnunicorn commented
@RaschidJFR anything else I should be doing?

2021-01-01 19:04 UTC, RaschidJFR approved these changes
LGTM

2021-01-01 19:13 UTC, gnunicorn commented
Ready to merge

2021-01-01 19:13 UTC, merged