[argparse]: Expose ArgumentTypeError exception
DefinitelyTyped/DefinitelyTyped pull request #50378
Opened 2021-01-03 23:27 UTC by cakoose

It's for when there's an error parsing the value of an argument.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [declaration](https://github.com/nodeca/argparse/blob/70fc26eb5a9a829d6ddcceb6b4c87802218227fd/argparse.js#L1165), [use](https://github.com/nodeca/argparse/blob/70fc26eb5a9a829d6ddcceb6b4c87802218227fd/argparse.js#L3540).
- [N/A] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-01-03 23:31 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## argparse ([<kbd>unpkg</kbd>](https://unpkg.com/browse/argparse@latest/))
was missing the following properties:
1. BooleanOptionalAction
1. FileType
1. MetavarTypeHelpFormatter
1. Const
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 753229ebd59269affd8bc62d76d4ca5f26f7bc0d
</p>

2021-01-04 06:44 UTC, doberkofler approved these changes

2021-01-04 09:14 UTC, eps1lon requested changes

2021-01-04 09:14 UTC, eps1lon commented on types/argparse/argparse-tests.ts
> +    { type: positiveInt, help: 'parent' }
Could you make the test additive instead? Right now it's not clear whether this change is breaking or not from the test alone.

2021-01-04 17:23 UTC, cakoose commented
@eps1lon: Made the test additive.

2021-01-04 17:36 UTC, eps1lon approved these changes

2021-01-04 22:52 UTC, cakoose commented
Ready to merge

2021-01-05 04:17 UTC, cakoose commented
Ready to merge

2021-01-05 04:17 UTC, merged