[@types/mapbox-gl] Add missing Sky layer
DefinitelyTyped/DefinitelyTyped pull request #50421
Opened 2021-01-06 01:53 UTC by tomarak

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#sky
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-01-06 07:32 UTC, dmytro-gokun requested changes
Could you please run this through prettier using the config in this repository? I see there are some minor formatting mismatches (like double vs single quotes)

2021-01-06 20:31 UTC, tomarak commented
@dmytro-gokun done

2021-01-07 10:03 UTC, dmytro-gokun approved these changes

2021-01-07 10:11 UTC, dmytro-gokun commented
Ready to merge

2021-01-07 10:12 UTC, merged