[react] Add children to forwardRef component props
DefinitelyTyped/DefinitelyTyped pull request #50436
Opened 2021-01-06 15:55 UTC by AlexUzan

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- In `forwardRef` type definition, `PropsWithChildren` is used to wrap the Props in the argument but not in the return value, which causes `Property 'children' does not exist on type ...` when trying to pass children to a component created using `forwardRef

2021-01-06 18:38 UTC, dimitropoulos commented
@AlexUzan: selfishly, may I ask your opinion on which of the following `PropsWithChildren` means to you?

- **Option A**: "has children and also has other props"

- **Option B**: "has children and may or may not have other props"

- **Option C**: "has children and no other props"

2021-01-06 19:32 UTC, eps1lon requested changes
Duplicate of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48420:

> We plan to remove implicit children in a future major React release since they are problematic: #33006

-- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48420#pullrequestreview-500918484

2021-01-07 08:59 UTC, AlexUzan commented
@dimitropoulos I think it would be option B for me depending on what `P` is in `PropsWithChildren<P>`

@eps1lon Sorry I didn't know there was already a PR for that, you can close it if it is not needed then

2021-01-07 09:03 UTC, eps1lon commented
> @eps1lon Sorry I didn't know there was already a PR for that, you can close it if it is not needed then

I can't do that. It'll stay open until the bot closes it due to staleness. You could close it though if you agree.

2021-01-07 09:30 UTC, closed without merging

2021-01-07 13:25 UTC, dimitropoulos commented
thanks @AlexUzan :)