[office-js, office-js-preview] Pulling latest type definitions from the CDN
DefinitelyTyped/DefinitelyTyped pull request #50457
Opened 2021-01-07 18:01 UTC by AlexJerabek

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
Release URL: https://appsforoffice.officeapps.live.com/afo/lib/1.1/hosted/office.debug.js 
Beta URL: https://appsforoffice.officeapps.live.com/afo/lib/beta/hosted/office.debug.js 
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-01-07 18:03 UTC, AlexJerabek commented
Tagging @Rick-Kirkham for the PowerPoint definition review and @alison-mk for the Excel type definitions. This content is directly from the CDN, with minor edits to reconcile the definitions with what's currently in DefinitelyTyped.

2021-01-07 19:31 UTC, Rick-Kirkham requested changes
I have a number of comments and questions. Among other things, it looks like the descriptions for the new *LoadOptions interfaces are actually the descriptions of the * class, instead of our standard "Provides options for which properties of the object to load." description.

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js/index.d.ts
> +         * Represents a single slide of a presentation.
```suggestion
         * Provides options for which properties of the object to load.
```

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js/index.d.ts
> +         * Represents the collection of slides in the presentation.
```suggestion
         * Provides options for which properties of the object to load.
```

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js-preview/index.d.ts
> +             * Determines if the row height of the Range object equals the standard height of the sheet.
Is this change reversing a recent change? Is that intentional?

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js-preview/index.d.ts
> +             * Specifies if the column width of the Range object equals the standard width of the sheet.
Are we intenitonally reversing a recent change?

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js-preview/index.d.ts
> +         * @returns The slide with the unique ID.
This change deletes a sentence that should stay because this is an "OrNullObject" property.

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js-preview/index.d.ts
> +         * Represents a single shape in the slide.
```suggestion
         * Provides options for which properties of the object to load.
```

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js-preview/index.d.ts
> +         * Represents the collection of shapes.
```suggestion
         * Provides options for which properties of the object to load.
```

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js-preview/index.d.ts
> +         * Represents a single slide of a presentation.
```suggestion
         * Provides options for which properties of the object to load.
```

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js-preview/index.d.ts
> +         * Represents the layout of a slide.
```suggestion
         * Provides options for which properties of the object to load.
```

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js-preview/index.d.ts
> +         * Represents the collection of Slide Masters in the presentation.
```suggestion
         * Provides options for which properties of the object to load.
```

2021-01-07 19:31 UTC, Rick-Kirkham commented on types/office-js-preview/index.d.ts
> +         * Represents the collection of layouts provided by the Slide Master for slides.
```suggestion
         * Provides options for which properties of the object to load.
```

2021-01-08 00:44 UTC, Rick-Kirkham approved these changes

2021-01-08 18:40 UTC, andrewbranch approved these changes

2021-01-11 22:17 UTC, closed without merging