[google.visualization] Add definition for Sankey
DefinitelyTyped/DefinitelyTyped pull request #50736
Opened 2021-01-20 17:00 UTC by martin-badin

Closes: #50446

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-01-21 07:31 UTC, danmana requested changes

2021-01-21 07:31 UTC, danmana commented on types/google.visualization/index.d.ts
> +            getBoundingBox(id: string): ChartBoundingBox;
The documentation is wrong here, the `getBoundingBox` does not actually exist at runtime

2021-01-21 07:31 UTC, danmana commented on types/google.visualization/index.d.ts
> +                    };
```suggestion
                    color?: string | ChartStrokeFill;
```
Also supports a color string.

You will also have to add `fillOpacity` to `ChartFill`. I double-checked and it's also supported in other places (ex: chart backgroundColor)
```
export interface ChartFill {
            fill?: string;
            fillOpacity?: number;
        }
```

2021-01-21 07:31 UTC, danmana commented on types/google.visualization/index.d.ts
> +                    };
```suggestion
                    label?: ChartTextStyle;
```
You can reuse `ChartTextStyle`

2021-01-21 07:31 UTC, danmana commented on types/google.visualization/index.d.ts
> +                };
```suggestion
                tooltip?: ChartTooltip;
```
You can reuse `ChartTooltip`

2021-01-21 15:10 UTC, martin-badin commented
Thanks, @danmana for your review! I added your suggestions.

2021-01-22 13:54 UTC, danmana approved these changes

2021-01-22 13:58 UTC, danmana commented
Ready to merge

2021-01-22 13:59 UTC, merged

2021-01-22 14:00 UTC, danmana commented
@martin-badin everything looks great 👍 
Thanks for your contribution!