Add exchange-rates-api type declarations
DefinitelyTyped/DefinitelyTyped pull request #50829
Opened 2021-01-25 20:41 UTC by martonlederer

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

2021-01-25 20:59 UTC, johnletey approved these changes
Amazing stuff @martonlederer 🔥 Definitely going to help!

2021-01-25 22:07 UTC, sheetalkamat requested changes

2021-01-25 22:07 UTC, sheetalkamat commented on types/exchange-rates-api/index.d.ts
> +// TypeScript Version: 4.1
```suggestion
```

2021-01-26 08:08 UTC, martonlederer commented on types/exchange-rates-api/index.d.ts
> +// TypeScript Version: 4.1
Thanks, fixed this up

2021-01-26 15:26 UTC, merged