[@types/omit-deep-lodash] Better types
DefinitelyTyped/DefinitelyTyped pull request #50822
Opened 2021-01-25 15:51 UTC by Faithfinder

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: No URL, just types weren't really doing anything, so I've improved them to reflect what the package does.

2021-01-27 07:30 UTC, ideffix commented
Hi @Faithfinder , do you have any use cases for your change? For me it looks a bit overengineer (its hard to read).

2021-01-27 15:23 UTC, Faithfinder commented
By cases, do you mean conditional types? To be honest I just lifted most of it off stack overflow. I do understand most of it and made some small refactorings, but I think that's how any complex typing is done. I don't necessarily like how it reads as well, but all complex types I've seen look similar.

The current typings are hindering. What the library does is, it removes props from objects recursively. There's no real way to preserve the correct type for that without complex typing.

With the type `declare function omitDeep(input: object, props: string[]): object;` it lost the typing completely. For example:

```ts
interface GraphQLFragment {
  __typename: string,
  id: number,
  someProp: string,
  innerObject: { 
    __typename: string,
    id: number,
    someOtherProp: SomeOtherType,
  }
}

function graphQLQueryToFormData(fragment: GraphQLFragment) {
  const formData = omitDeep(fragment, "__typename");
  formData.innerObject= someOtherTransformation(formData.innerObject);
  //property 'innerObject' does not exist on type 'object'.
  return formdata;
}
```
With behaviour like that I would prefer no types to `object`

2021-01-28 07:28 UTC, ideffix commented
Sounds reasonable. Could you please add some regression tests so it won't fail in a future?

2021-01-31 17:18 UTC, Faithfinder commented
Not sure how testing in this repository should be done. Do you have a link to good examples in one of the neighbouring packages?

2021-02-17 17:28 UTC, orta commented
How to add tests: https://github.com/DefinitelyTyped/DefinitelyTyped#adding-tests-to-a-new-package

2021-02-25 18:46 UTC, Faithfinder commented
> How to add tests: https://github.com/DefinitelyTyped/DefinitelyTyped#adding-tests-to-a-new-package

Thanks for the link, but that's not exactly what I'm asking. I'm asking `what` constitutes a test for a type. I'm used to a test being something you run, but you don't run types. I mean, obviously the whole repo probably has a lot of them, but there are so many packages that I hoped for a link that someone knows to be a good example.

2021-03-07 12:48 UTC, elibarzilay commented
Just code that uses the type in some better way?  (The existing tests are very minimal inputs.)

2021-03-08 19:43 UTC, sheetalkamat requested changes
These need more tests as requested by other maintainers

2021-04-09 01:07 UTC, closed without merging