Update Mac.d.ts for doFinal, doFinalHex and doFinalString right return type and examples
DefinitelyTyped/DefinitelyTyped pull request #50820
Opened 2021-01-25 13:12 UTC by jer-sen

Wrong doc has been fixed cf https://github.com/kjur/jsrsasign/issues/466 and updated doc https://kjur.github.io/jsrsasign/api/symbols/KJUR.crypto.Mac.html

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-01-25 13:24 UTC, ffflorian approved these changes

2021-02-18 09:03 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## jsrsasign ([<kbd>unpkg</kbd>](https://unpkg.com/browse/jsrsasign@latest/))
was missing the following properties:
1. SecureRandom
1. rng_seed_time
1. ECDSA
1. DSA
1. Signature

<details>
<summary>as well as these 14 other properties...</summary>
<p>MessageDigest, Mac, Cipher, ASN1HEX, CryptoJS, hex2b64, ipv6tohex, hextoipv6, hextoip, iptohex, crypto, asn1, jws, lang</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e52faa18b59427dadce66d39f4889808cec85f3a
</p>

2021-02-18 09:57 UTC, ffflorian requested changes

2021-02-18 09:57 UTC, ffflorian commented on types/jsrsasign/modules/KJUR/crypto/Mac.d.ts
> +         *  performs final update on the digest using string, then completes the digest computation
```suggestion
         * performs final update on the digest using string, then completes the digest computation
```

2021-03-01 13:15 UTC, ffflorian approved these changes
Sorry for the long wait! Looks good to me.

2021-03-07 09:57 UTC, merged