[office-js, office-js-preview] Note the current support status of SaveSettingsOptions.overwriteIfStale
DefinitelyTyped/DefinitelyTyped pull request #50873
Opened 2021-01-27 21:07 UTC by AlexJerabek

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/OfficeDev/office-js-docs-reference/issues/875
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
.

2021-01-27 21:16 UTC, Rick-Kirkham approved these changes

2021-01-27 21:18 UTC, ElizabethSamuel-MSFT requested changes

2021-01-27 21:18 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * **Warning**: This setting is depreciated and should not be used. It has no effect on most platforms and will cause errors when set to false in Excel on the Web.
Here and in office-js
```suggestion
         * **Warning**: This setting is deprecated and should not be used. It has no effect on most platforms and will cause errors when set to false in Excel on the Web.
```

2021-01-27 21:39 UTC, AlexJerabek commented
Good catch @ElizabethSamuel-MSFT. Fixed.

2021-01-27 21:41 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +         * **Warning**: This setting is deprecated and should not be used. It has no effect on most platforms and will cause errors if set to false in Excel on the Web.
Sorry I missed this before
```suggestion
         * **Warning**: This setting is deprecated and should not be used. It has no effect on most platforms and will cause errors if set to `false` in Excel on the web.
```

2021-01-28 00:43 UTC, ElizabethSamuel-MSFT approved these changes

2021-01-28 17:10 UTC, merged