Type declarations for use-prefers-color-scheme
DefinitelyTyped/DefinitelyTyped pull request #51039
Opened 2021-02-04 14:17 UTC by martonlederer

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

2021-02-04 23:57 UTC, amcasey requested changes

2021-02-04 23:57 UTC, amcasey commented on types/use-prefers-color-scheme/index.d.ts
> +export = usePrefersColorScheme;
Based on the underlying library, it seems like you want `export default usePrefersColorScheme`.

2021-02-04 23:57 UTC, amcasey commented on types/use-prefers-color-scheme/tsconfig.json
> +      "esModuleInterop": true
If you `export default`, this shouldn't be necessary.

2021-02-05 09:17 UTC, martonlederer commented
@amcasey the source module uses `module.exports = `, you can see [here](https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=85810&view=logs&j=8635df7d-ecde-52a7-c7a8-84b998e35690&t=c264d665-0b79-59b7-7e04-9965cbe74860), that it fails if I try to use your suggestions.

2021-02-05 18:16 UTC, amcasey commented
@martonlederer My mistake - sorry about that.  I looked [here](https://unpkg.com/browse/use-prefers-color-scheme@0.1.1/src/index.js) when I should have looked [here](https://unpkg.com/browse/use-prefers-color-scheme@0.1.1/dist/index.js).

2021-02-05 18:18 UTC, amcasey commented
Hmm, that still doesn't explain why `esModuleInterop` was required though.  Can it be removed?

2021-02-05 18:47 UTC, martonlederer commented
Just checked @amcasey, works perfectly without it, removed

2021-02-05 19:14 UTC, amcasey approved these changes
Thanks!  Sorry again for the confusion.

2021-02-05 19:33 UTC, martonlederer commented
Ready to merge

2021-02-05 19:33 UTC, merged