c-struct typings
DefinitelyTyped/DefinitelyTyped pull request #51097
Opened 2021-02-06 22:14 UTC by benallfree

Greetings, this PR introduces typings for [c-struct](https://www.npmjs.com/package/c-struct)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

2021-02-06 22:18 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## c-struct ([<kbd>unpkg</kbd>](https://unpkg.com/browse/c-struct@latest/))
was missing the following properties:
1. packers
1. unpackers
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9268c81d90d386fb01b6f639135748e7ca456fb7
</p>

2021-02-08 19:10 UTC, amcasey requested changes

2021-02-08 19:10 UTC, amcasey commented on types/c-struct/index.d.ts
> +// Project: https://github.com/xdenser/node-struct#readme
https://github.com/majimboo/c-struct#readme?

2021-02-08 19:10 UTC, amcasey commented on types/c-struct/tslint.json
> +        "no-unnecessary-class": false
If a lint rule absolutely must be suppressed, please use a line-level suppression to make it easier to review.

2021-02-09 14:31 UTC, benallfree commented on types/c-struct/index.d.ts
> +// Project: https://github.com/xdenser/node-struct#readme
Good catch :)

2021-02-09 17:11 UTC, amcasey approved these changes

2021-02-09 18:01 UTC, benallfree commented
ready to merge

2021-02-09 18:02 UTC, merged