[Swiper] More accurate event callbacks
DefinitelyTyped/DefinitelyTyped pull request #51162
Opened 2021-02-10 19:05 UTC by dhritzkiv

This:
- adds `this` arg to callbacks to point to the Swiper instance
- specifies that the lazy image events come with two arguments: slide element and image element

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://web.archive.org/web/20191003204427/http://swiperjs.com/api/
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-02-10 21:04 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## swiper ([<kbd>unpkg</kbd>](https://unpkg.com/browse/swiper@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'swiper'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.
1. extendDefaults
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e6b603ad5a6f3b2d4842f1d5b6f92b99b73b64c3
</p>

2021-02-10 22:05 UTC, odahcam approved these changes

2021-02-10 22:09 UTC, odahcam requested changes
I approved before, but in fact you need to update the typings version.

2021-02-10 22:28 UTC, dhritzkiv commented
@odahcam not sure what you mean. Do you mean that it says "Swiper 5.4"? That's the latest version in the 5.x line. Version 6 has types part of its repo.

2021-02-11 00:42 UTC, odahcam commented
I'm also confused, as I remembered there was a place in the comments where you would specify the patch version, but I'm probably thinking about other project.

2021-02-11 00:42 UTC, odahcam approved these changes

2021-02-11 04:18 UTC, dhritzkiv commented
Ready to merge!

2021-02-11 04:18 UTC, merged