[@types/faker] adds missing typings for faker.unique method
DefinitelyTyped/DefinitelyTyped pull request #51217
Opened 2021-02-14 02:21 UTC by pallymore

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Marak/faker.js/blob/master/lib/unique.js#L24-L35
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-02-14 02:25 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## faker ([<kbd>unpkg</kbd>](https://unpkg.com/browse/faker@latest/))
was missing the following properties:
1. locales
1. localeFallback
1. definitions
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 870b77c838660d7a98e875a02baff8833396e035
</p>

2021-02-18 15:02 UTC, pallymore commented
HI -  @bensw @basp @Kuniwak @mattbishop @testica @TastefulElk @damonpam  

When you get a chance, would you mind taking a look at the new typings here and see if they are ok?

Thanks!

2021-02-18 15:54 UTC, TastefulElk requested changes

2021-02-18 15:54 UTC, TastefulElk commented on types/faker/index.d.ts
> +            opts?: { maxTime?: number; maxRetires?: number },
"Retries" is misspelled

2021-02-18 15:55 UTC, TastefulElk commented
Requested to fix spelling error - other than that, awesome work and than you for contributing 👑

2021-02-18 16:02 UTC, pallymore commented on types/faker/index.d.ts
> +            opts?: { maxTime?: number; maxRetires?: number },
my bad! thanks!

2021-02-18 16:05 UTC, pallymore commented
> Requested to fix spelling error - other than that, awesome work and than you for contributing 👑

fixed now 😅  thank you!

2021-02-18 17:56 UTC, TastefulElk approved these changes

2021-02-18 18:36 UTC, pallymore commented
Ready to merge

2021-02-18 18:37 UTC, merged