Support messageFormat as func into PrettyOptions
DefinitelyTyped/DefinitelyTyped pull request #51250
Opened 2021-02-16 01:24 UTC by gtkatakura

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/pinojs/pino-pretty/blob/28ea34be1245122590a978ea233dd9e38d66b695/test/lib/utils.public.test.js#L119-L129
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-02-16 22:05 UTC, AdamVig requested changes
As discussed in #51046, it would be preferable to move these types to a new `pino-pretty` package, but I have no qualms about merging this in the meantime.

2021-02-16 22:05 UTC, AdamVig commented on types/pino/index.d.ts
> +         * });
This is example is far more detailed than it needs to be. I think we can simplify it, following [the example in the `pino-pretty` documentation](https://github.com/pinojs/pino-pretty#options).
```suggestion
         * {
         *   messageFormat: (log, messageKey) => {
         *     const message = log[messageKey];
         *     if (log.requestId) return `[${log.requestId}] ${message}`;
         *     return message;
         *   }
         * }
```

2021-02-16 22:05 UTC, AdamVig commented on types/pino/index.d.ts
> +         * ```js
```suggestion
         * ```typescript
```

2021-02-16 22:05 UTC, AdamVig commented on types/pino/index.d.ts
> +    type MessageFormatFunc = (log: Record<string, any>, messageKey: string, levelLabel: string) => string;
```suggestion
    type MessageFormatFunc = (log: LogDescriptor, messageKey: string, levelLabel: string) => string;
```

2021-02-16 22:33 UTC, gtkatakura commented
Thank you for your review @AdamVig , I accepted the commit suggestions and apply a git rebase to squash into the initial commit.

2021-02-17 01:22 UTC, AdamVig approved these changes

2021-02-18 20:33 UTC, gtkatakura commented
Ready to merge

2021-02-18 20:34 UTC, merged