[@types/node] Wrong type for ProcessEnv
DefinitelyTyped/DefinitelyTyped pull request #51273
Opened 2021-02-16 20:19 UTC by kylehalleman

The type for `ProcessEnv` is incorrect. It states it must be a `string` or `undefined`, but [according to the Node documentation](https://nodejs.org/api/process.html#process_process_env), the value can be a `string`, `number`, or `boolean`.

> Assigning a property on process.env will implicitly convert the value to a string. This behavior is deprecated. Future versions of Node.js may throw an error when the value is not a string, number, or boolean.

While the deprecated behavior _converts_ the value to a `string`, that  does not mean you can’t assign a `number` or `boolean`. 

It is clear from the documentation and examples in the docs that you can assign a `string`, `number`, or `boolean`.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/api/process.html#process_process_env
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-02-16 23:06 UTC, ExE-Boss requested changes
Unfortunately, there’s no way to do this without breaking a lot of things until <https://github.com/microsoft/TypeScript/issues/2521> (PR <https://github.com/microsoft/TypeScript/pull/42425>) gets implemented.

---

That is also why DOM interface definitions don’t currently have the implicit string conversion either.

2021-02-17 03:30 UTC, kylehalleman commented
@ExE-Boss I see that a lot of tests in other packages are failing. Taking a look at some of them, like `color-support`, I'm not sure why it fails if it [references `NodeJS.ProcessEnv` in its declarations](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/color-support/index.d.ts#L13), and the `tsconfig.json` has `typeRoots` set to `../`. I would think it would pick up the new definitions in this PR.

Regardless, I see the impact this is having. I think this would still be valuable even without microsoft/TypeScript#42425. Users who set an environment variable like `process.env.PORT = 3000` a) expect TypeScript to not throw an error and b) expect to be able to later read that variable as a number and not string.

I might be in over my head here since this is obviously a core package to the ecosystem, so would appreciate your advice on moving forward.

2021-02-17 21:45 UTC, peterblazejewicz commented
> Users who set an environment variable like process.env.PORT = 3000 a) expect TypeScript to not throw an error and b) expect to be able to later read that variable as a number and not string.

That's not current behaviour:

```bash
> process.env.PORT = 3000
3000
> process.env.PORT
'3000'
```
imo there is no clean cut option here

2021-02-17 21:52 UTC, kylehalleman commented
You're correct, my mistake. I swear I've been able to read the value as assigned before. But that might have been through something like webpack.

I suppose microsoft/TypeScript#42425 really is a blocker on this then.

2021-03-21 01:36 UTC, closed without merging