feat: add p-mapbox-gl types
DefinitelyTyped/DefinitelyTyped pull request #51350
Opened 2021-02-20 13:45 UTC by shaojun427

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-02-20 18:00 UTC, dmytro-gokun commented
@shaojun427 What library this is for? Why did you add me here? :)

2021-02-20 21:26 UTC, peterblazejewicz requested changes
You need those people listed to give eplicitel consent to fact of being added in the header,
what's that library for? (it's appears to be just a fork)
thx!

2021-02-22 02:26 UTC, shaojun427 commented
> You need those people listed to give eplicitel consent to fact of being added in the header,
> what's that library for? (it's appears to be just a fork)
> thx!

This is a library based on mapbox-gl extension. I want to add a custom CRS parameter, but I haven’t added it yet. I want to replace the original mapbox with the fork library.

2021-02-22 12:12 UTC, shaojun427 commented
> @ shaojun427这是什么库？为什么在这里加我？:)

I'm sorry, this is a mapbox fork library. I forgot to modify some basic information when submitting it. Now your information has been deleted

2021-02-22 12:13 UTC, shaojun427 commented
> @shaojun427 What library this is for? Why did you add me here? :)

I'm sorry, this is a mapbox fork library. I forgot to modify some basic information when submitting it. Now your information has been deleted

2021-02-22 22:12 UTC, peterblazejewicz commented on types/p-mapbox-gl/index.d.ts
> +// Project: https://github.com/zsjjs/mapbox-gl-js
```suggestion
// Project: https://github.com/zsjjs/p-mapbox-gl-js
```

2021-02-22 22:15 UTC, peterblazejewicz commented on types/p-mapbox-gl/index.d.ts
> +// Type definitions for Mapbox GL JS 1.0
```suggestion
// Type definitions for p-mapbox-gl 1.0
```

2021-02-22 22:19 UTC, peterblazejewicz commented
@shaojun427 if this is a fork and there is no real change in the API,
you can re-export eerything from Mapbox types IMO, just adding your changes.
That way it will be obvious what this package is about (extension based on a fork) and also maintenance burden could be lowered a lot.

2021-02-24 19:48 UTC, peterblazejewicz approved these changes
LGMT!

2021-03-07 10:41 UTC, elibarzilay commented
The status of this PR is not clear to me: why is the listed owner different?  Why so many linter exceptions?

2021-03-08 06:31 UTC, closed without merging