Fix @types/scheduler wrapCallback type
DefinitelyTyped/DefinitelyTyped pull request #51353
Opened 2021-02-20 18:22 UTC by calebmer

The intention of the `unstable_wrapCallback()` function is to take a function of any arguments/returns and when that callback is called to execute it at the priority level in which wrap callback was called.

https://github.com/facebook/react/blob/8af27aeedbc6b00bc2ef49729fc84f116c70a27c/packages/scheduler/src/forks/SchedulerDOM.js#L305-L318

2021-02-20 18:26 UTC, danger-public commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## scheduler ([<kbd>unpkg</kbd>](https://unpkg.com/browse/scheduler@latest/))
was missing the following properties:
1. unstable_forceFrameRate
1. unstable_requestPaint
1. unstable_Profiling
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against b02f3e0379527ad644d7c2658e9eb0ec0c208dd0
</p>

2021-02-21 12:49 UTC, eps1lon requested changes

2021-02-21 12:49 UTC, eps1lon commented on types/scheduler/index.d.ts
> +export function unstable_wrapCallback<I extends Array<any>, O>(callback: (...args: I) => O): (...args: I) => O;
So the it basically just returns the input (which has to be a function). Can't we use a single type parameter in this case instead?

```suggestion
export function unstable_wrapCallback<Callback extends (...args: any[]) => any>(callback: Callback): Callback;
```

2021-02-21 12:49 UTC, eps1lon commented
Also: A test would be nice to have the usage documented.

2021-03-24 12:58 UTC, closed without merging