Added type definitions for noloopfor
DefinitelyTyped/DefinitelyTyped pull request #51363
Opened 2021-02-21 19:56 UTC by david-fernando

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-03-01 08:25 UTC, DanielRosenwasser requested changes

2021-03-01 08:25 UTC, DanielRosenwasser commented on types/noloopfor/index.d.ts
> +export function decrementStep(value: number, target: number, step: number, callback: any): any;
Seems like these should all take actual callback types

```suggestion
export function loop(value: number, target: number, callback: (index: number) => void): any;
export function loopStep(value: number, target: number, step: number, callback: (index: number) => void): any;
export function decrementLoop(value: number, target: number, callback: (index: number) => void): any;
export function decrementStep(value: number, target: number, step: number, callback: (index: number) => void): any;
```

2021-03-01 14:50 UTC, david-fernando commented on types/noloopfor/tslint.json
> +    "whitespace": false
This rule exists to that the test does not require white space in the code.

2021-03-01 22:41 UTC, peterblazejewicz commented on types/noloopfor/index.d.ts
> +export function decrementStep(value: number, target: number, step: number, callback: (index: number) => void): any;
```suggestion
export function loop(value: number, target: number, callback: (index: number) => void): void;
export function loopStep(value: number, target: number, step: number, callback: (index: number) => void): void;
export function decrementLoop(value: number, target: number, callback: (index: number) => void): void;
export function decrementStep(value: number, target: number, step: number, callback: (index: number) => void): void;
```
were those `any` by design ther? Those are just undefined, so `void`

2021-03-01 22:43 UTC, peterblazejewicz commented on types/noloopfor/tslint.json
> +  }
```suggestion
  "extends": "dtslint/dt.json"
```
why do you need this exclusion?
https://github.com/DefinitelyTyped/DefinitelyTyped#linter-tslintjson

2021-03-05 19:35 UTC, peterblazejewicz approved these changes
LGMT!
@david-fernando thx!

2021-03-07 10:18 UTC, merged