[d3-force] correct type for ForceLink.id
DefinitelyTyped/DefinitelyTyped pull request #51413
Opened 2021-02-24 09:38 UTC by sarnesjo

The setter form of ForceLink.id takes a function as its argument. The
type annotations specify the return type of this function as string, but
number is also valid, and used by the default implementation. This
commit changes the return type to (string | number).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/d3/d3-force/blob/523a02d963f7caf28914b3557e28ce707cdd2d87/src/link.js#L15
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-02-24 15:33 UTC, Methuselah96 requested changes
Thanks, can you add a test?

2021-02-24 22:13 UTC, sarnesjo commented
> Thanks, can you add a test?

Sure thing, done!

2021-02-25 01:26 UTC, Methuselah96 approved these changes
Thanks!

2021-02-25 01:28 UTC, sarnesjo commented
Ready to merge

2021-02-25 01:28 UTC, sarnesjo commented
Thanks for reviewing!

2021-02-25 01:29 UTC, merged