merge-images v1.2.0: Add `crossOrigin` option
DefinitelyTyped/DefinitelyTyped pull request #51415
Opened 2021-02-24 12:15 UTC by laurensnl

merge-images supports the `crossOrigin` option since v1.2.0 (https://github.com/lukechilds/merge-images#optionscrossorigin).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a

2021-02-24 16:19 UTC, BendingBender requested changes
Would you mind adding a test for this option?

2021-03-22 14:16 UTC, BendingBender commented on types/merge-images/index.d.ts
> +        crossOrigin?: string;
Could you please add a test for this?

2021-03-22 14:17 UTC, BendingBender requested changes
Please add tests.

2021-03-22 14:30 UTC, laurensnl commented
> Please add tests.

Sorry, I am not proficient in writing tests. I will close this PR.

2021-03-22 14:30 UTC, closed without merging