[segment-api] Added segment-api typings
DefinitelyTyped/DefinitelyTyped pull request #51435
Opened 2021-02-25 17:55 UTC by padcom

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-02-25 18:38 UTC, padcom commented
@RyanCavanaugh the @typescript-bot seems to not update the comment that is supposed to be "live"... How often do the comments get updated?

2021-02-27 08:53 UTC, martin-badin requested changes

2021-02-27 08:53 UTC, martin-badin commented on types/segment-api/index.d.ts
> +export interface Traits {
Please specify traits https://segment.com/docs/connections/spec/identify/#traits

2021-02-27 13:32 UTC, padcom commented on types/segment-api/index.d.ts
> +export interface Traits {
Done

2021-02-27 17:54 UTC, martin-badin approved these changes
Awesome. Looks good to me

thanks @padcom

2021-03-01 08:44 UTC, merged

2021-03-01 08:46 UTC, padcom commented
Thank you!

2021-03-01 08:51 UTC, DanielRosenwasser commented
Thank *you* for the PR and the patience.