Update client.d.ts
DefinitelyTyped/DefinitelyTyped pull request #51477
Opened 2021-02-28 21:45 UTC by StefanSelfTaught

Added redirect type to signIn and signOut

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-03-01 09:13 UTC, lluia requested changes
Thanks, small two 💬  to make the CI pass 👍🏽

2021-03-01 09:13 UTC, lluia commented on types/next-auth/client.d.ts
> +    data?: {
There's a trailing white-space on this line 📐 , which you'll need to remove for the lint process [not to complain on the CI](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51477/checks?check_run_id=1999784269) 👍🏼

2021-03-01 09:13 UTC, lluia commented on types/next-auth/client.d.ts
> +        redirect?: boolean;
Let's [add a test](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4bea1bd982be671edf210b7010aba4ce0f627bd1/types/next-auth/next-auth-tests.ts#L265) to verify this new option 🪴

2021-03-02 10:21 UTC, lluia approved these changes
Thanks 💚

2021-03-02 10:45 UTC, StefanSelfTaught commented
Ready to merge

2021-03-02 10:45 UTC, merged