Prosemirror model nodespec allowgapcursor
DefinitelyTyped/DefinitelyTyped pull request #51496
Opened 2021-03-01 19:09 UTC by ocavue

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
 
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://prosemirror.net/docs/ref/#gapcursor
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-03-02 05:56 UTC, AnthonyWeston commented
I'm not able to look further into it right now, but I think it's worth figuring out if we can  add the property to NodeSpec by module augmentation in the @types/prosemirror-gapcursor package instead. This would avoid adding additional properties to the type declaration if the user doesn't actually use prosemirror-gapcursor in their application.

Check this link: https://www.typescriptlang.org/docs/handbook/declaration-merging.html#module-augmentation

2021-03-03 16:03 UTC, ocavue commented
@AnthonyWeston Thank you very much for your advice. It's very clear and helpful. 

The `prosemirror-model` package in fact doesn't use `allowGapCursor` so it's reasonable to move this type to `@types/prosemirror-gapcursor` package. I tested the module augmentation locally and it works fine in my project.

2021-03-05 23:58 UTC, AnthonyWeston requested changes
It looks good and works for me. The only change I'd like to see is to add a test that would fail for the current version.

2021-03-05 23:58 UTC, AnthonyWeston commented on types/prosemirror-gapcursor/prosemirror-gapcursor-tests.ts
> +    allowGapCursor: false,
Since NodeSpec allows for arbitrary additional properties, this would compile just fine whether or not the new type definition is in place.

2021-03-05 23:58 UTC, AnthonyWeston commented on types/prosemirror-gapcursor/prosemirror-gapcursor-tests.ts
> +};
I wrote up this example, which fails to compile if `spec.allowGapCursor` has type `any` (as it does in the current version), and succeeds with the updated type definitions.


```suggestion
};

/**
 * We want to make sure the type of spec.allowGapCursor is defined, i.e., not any, and
 * I couldn't find another straightforward way to write a test that fails.
 */
type IsAnyOrUnknownTest = <T>(x: T) => unknown extends typeof x ? true : false;
const isAnyOrUnknown = {} as IsAnyOrUnknownTest

// Proof of concept to convince the reader the above type works
const testAny: true =  isAnyOrUnknown({} as any);
const testUnknown: true = isAnyOrUnknown({} as unknown);

const testNull: false = isAnyOrUnknown(null);
const testBoolean: false = isAnyOrUnknown(true);
const testBooleanOrUndefined: false = isAnyOrUnknown(false as boolean | undefined);
const testUndefined: false = isAnyOrUnknown(undefined);

const spec: NodeSpec = {} as NodeSpec;
const allowGapCursorIsDefined: false = isAnyOrUnknown(spec.allowGapCursor)

```

2021-03-06 12:16 UTC, ocavue commented
@AnthonyWeston Good point. Since DefinitelyTyped use [dtslint](https://github.com/microsoft/dtslint), we can use `$ExpectType` and `$ExpectError` in comment to achieve this.

2021-03-08 02:48 UTC, AnthonyWeston commented
> @AnthonyWeston Good point. Since DefinitelyTyped use [dtslint](https://github.com/microsoft/dtslint), we can use `$ExpectType` and `$ExpectError` in comment to achieve this.

@ocavue Cool, I didn't know that existed, thanks for pointing that out.

2021-03-08 02:48 UTC, AnthonyWeston approved these changes
Looks good to me! :+1:  Just set the PR to squash your commits if possible.

2021-03-08 02:50 UTC, ocavue commented
Ready to merge

2021-03-08 02:50 UTC, merged