Add type definitions for react-twitter-conversion-tracker-plus
DefinitelyTyped/DefinitelyTyped pull request #51507
Opened 2021-03-02 04:25 UTC by Coteh

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2021-03-02 21:41 UTC, peterblazejewicz commented on types/react-twitter-conversion-tracker-plus/tsconfig.json
> +        "allowSyntheticDefaultImports": true
```suggestion
        "forceConsistentCasingInFileNames": true
```
it's for consuming this package, not on DT, it will work.

2021-03-02 21:41 UTC, peterblazejewicz commented on types/react-twitter-conversion-tracker-plus/react-twitter-conversion-tracker-plus-tests.ts
> +import TwitterConvTrkr from 'react-twitter-conversion-tracker-plus';
```suggestion
import TwitterConvTrkr = require('react-twitter-conversion-tracker-plus');
```

2021-03-02 21:43 UTC, peterblazejewicz requested changes
please review, otehrwise ready to merge IMO

2021-03-03 00:36 UTC, Coteh commented
Suggestions applied, thanks for the feedback. "Check Config" and "Revision Needed" labels should be removed now.

2021-03-03 08:02 UTC, peterblazejewicz approved these changes
LGTM!
@Coteh thx!

2021-03-07 10:25 UTC, merged