Added damerau-levenshtein types
DefinitelyTyped/DefinitelyTyped pull request #51547
Opened 2021-03-04 12:50 UTC by g3ru1a

Please fill in this template.

- [ x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x ] Test the change in your own code. (Compile and run.)
- [ x ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ x ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ x ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ x ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ x ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ x ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ x ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2021-03-04 19:49 UTC, peterblazejewicz approved these changes
LGTM!
@g3ru1a thx!

2021-03-07 03:48 UTC, tanelso2 approved these changes

2021-03-07 09:50 UTC, peterblazejewicz commented on types/damerau-levenshtein/index.d.ts
> +// Definitions by: G3ru1a <https://github.com/me>
```suggestion
// Definitions by: G3ru1a <https://github.com/g3ru1a>
```

2021-03-07 09:51 UTC, peterblazejewicz requested changes
@g3ru1a your github's handle needs to be corrected thx!

2021-03-07 14:18 UTC, g3ru1a commented
Updated it, thanks @peterblazejewicz !

2021-03-07 15:23 UTC, peterblazejewicz approved these changes

2021-03-08 16:37 UTC, merged