[react-select] Remove defaultProps from Creatable
DefinitelyTyped/DefinitelyTyped pull request #51550
Opened 2021-03-04 16:33 UTC by dakur

I'm decorating Creatable. It looks like this:

```ts
interface CreatableSelectProps extends Props<{label: string, value: string}, true>
{}

function makeDecoratable<P extends CreatableSelectProps>(Creatable: React.ComponentType<P>): React.ComponentType<P & CreatableSelectProps>
{
	return ({...props}) =>
	{
		return (
			<Creatable
				{...props as P}
			/>
		);
	};
}

let Select = makeDecoratable(Creatable);
Select = decorateWithSomething1(Select);
Select = decorateWithSomething2(Select);
render(<Select options=[...] ... />, el);
```

Error given:

![image](https://user-images.githubusercontent.com/9862581/109983348-052ad880-7d03-11eb-820e-992b0b6ea215.png)

`defaultProps: <any, boolean>` conflicts with type counted from Props.

This PR is not solution, just raising awareness of the problem. I'm not sure what removing `defaultProps` can cause.

@Methuselah96 @kylemh

2021-03-07 11:02 UTC, elibarzilay commented
> This PR is not solution, just raising awareness of the problem. I'm not sure what removing defaultProps can cause.

Ummm... Open an issue instead?

2021-03-07 23:47 UTC, kylemh commented
This isn't a solution. You can't simply remove types from the declaration because they conflict with your incorrect types. You'll want to make sure your interface takes defaultProps into account.

2021-03-07 23:47 UTC, kylemh requested changes
Won't merge.

2021-03-08 14:38 UTC, dakur commented
@kylemh What do you mean? I only use Creatable's Props with default options type `{label: string, value: string}`, so the problem does not lay in "my interface", but in colliding Creatable with Creatable itself when used in the way I sketched above.

I'm sorry, but I have no knowledge of react-select internals – that's the reason I made this PR for further evaluation on good approach. It's a proposal, you can resolve it in whatever way it is better to do it.

2021-03-08 17:19 UTC, kylemh commented
Your error stack is unrelated to these type definitions, but rather you lack of awareness on `react-select`'s source code.

If you wish to make a wrapper and have TS recognize it as a typesafe replica of `Creatable` you must actually do that - including defining static properties. https://github.com/JedWatson/react-select/blob/master/packages/react-select/src/Creatable.js#L107

Lastly, not knowing a package's source code - or at least not reading how they affect the type definitions - should absolutely preclude you from opening a PR into DefinitelyTyped into the future. Ignorance isn't an excuse to wasting our time. Imagine if I didn't like my teammates using AsyncCreatable vs. Creatable, so I just opened a PR into `react-select` deleting the whole package.

Please close this PR.

2021-03-09 06:10 UTC, dakur commented
@kylemh So you blame me that I drew the problem on PR rather than made an issue? I did not mean to waste your time, I'm sorry if you feel it like that. What do you suggest instead, transfer it into an issue? I have a feeling you still did not understand what problem I have with the types (even though I am not saying deleting `defaultProps` is the solution, it just seems to me that it was there redundant as it has very general generic-params and it is defined already in `React.ComponentClass`).

2021-03-09 06:10 UTC, closed without merging