n3 Parser type fix
DefinitelyTyped/DefinitelyTyped pull request #51572
Opened 2021-03-05 11:02 UTC by stuarthendren

The [n3](https://github.com/rdfjs/N3.js) parser now seems to accept two callbacks, separating the error/quads
from the prefix.

https://github.com/rdfjs/N3.js/blob/42ab3a29e9ee82cf4d8fdf8994c1f7e74f9b1035/src/N3Parser.js#L982

My understanding is:
If giving a parse callback the function is a async and the prefix call back is
optional.

If the parse callback is not supplied or nullish, the parse is sync. Supplying null
and a prefix callback also works synchronously and calls the prefix callback
while processing. (Not sure if this is intended, but is is useful).

I have updated the version as I assume this has changed at some point. I have not checked for other API changes.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-03-05 13:16 UTC, stuarthendren commented
The tests have helpfully pointed me to other changes in the API. I'll try to add typings for these shortly.

2021-03-05 20:24 UTC, stuarthendren commented
Added missing types for the Lexer and the term/id until function.

2021-03-24 11:00 UTC, joachimvh requested changes
Sorry for the delay. I had a look into the Lexer code to check the new typings and it seems there are some minor things where the typings differ from what happens. Besides that most of it seems fine.

2021-03-24 11:00 UTC, joachimvh commented on types/n3/index.d.ts
> +    tokenize(input: string | EventEmitter): Token[];
```suggestion
    tokenize(input: string): Token[];
```
A callback seems to be required when the input is an EventEmitter: https://github.com/rdfjs/N3.js/blob/89f0daf748bf2d6ca194b37e58733798346a88e0/src/N3Lexer.js#L455-L485

2021-03-24 11:00 UTC, joachimvh commented on types/n3/index.d.ts
> +}
```suggestion
    prefix?: string;
}
```

Tokens can also have a prefix field: https://github.com/rdfjs/N3.js/blob/89f0daf748bf2d6ca194b37e58733798346a88e0/src/N3Lexer.js#L348

2021-03-24 11:09 UTC, stuarthendren commented
> Sorry for the delay. I had a look into the Lexer code to check the new typings and it seems there are some minor things where the typings differ from what happens. Besides that most of it seems fine.

No worries. I've added those suggestions. Thanks for reviewing.

2021-03-24 11:21 UTC, joachimvh approved these changes

2021-03-24 11:25 UTC, stuarthendren commented
Ready to merge

2021-03-24 11:25 UTC, merged