[ember-data] PromiseObject<T> does not behave the same as T
DefinitelyTyped/DefinitelyTyped pull request #51641
Opened 2021-03-08 22:10 UTC by wagenet

For example a PromiseObject requires the use of `get`. It also may
return undefined for a property when the underlying promise is not
yet resolved.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

Unfortunately, it's difficult for me to find a solid documentation source for this behavior. However, I can seek to document it with some code examples if necessary.

2021-03-08 22:10 UTC, wagenet commented
I believe we need to add `setter` support to ObjectProxy first.

2021-03-08 22:16 UTC, wagenet commented
Rebase after https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51643

2021-03-09 15:09 UTC, chriskrycho reviewed
This looks good and makes sense to me, but I am not positive that it is 100% correct, just because of my distance from this type. Accordingly I am leaving it unapproved and will defer to @jamescdavis for a pass for someone more familiar with it.

2021-03-09 17:28 UTC, jamescdavis requested changes
I've always felt this construct was wrong and it looks like it was introduced in the [very beginning of these types](https://github.com/typed-ember/ember-typings/pull/9). It's not completely clear why it was typed this way originally, but those of us still actively maintaining these types assumed it was for good reason and haven't touched it (and even carried it in to utility types like `AsyncBelongsTo`). This change will almost certainly cause some people's apps to fail type-checking, but in a good way since it means they are likely doing things in an unsafe way. There's one additional place where this construct is used that IMHO we should update:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0720ff4ab46d27817f3b4f66f48976f19561829f/types/ember-data/index.d.ts#L1097-L1101
Let's update the return type here to just:
```ts
PromiseObject<ModelRegistry[K]>
```

2021-03-09 20:13 UTC, jamescdavis approved these changes

2021-03-09 20:26 UTC, wagenet commented
Ready to merge

2021-03-09 20:26 UTC, merged