[fs-extra] Make compatible with @types/node@12.x
DefinitelyTyped/DefinitelyTyped pull request #51677
Opened 2021-03-10 19:47 UTC by forivall

Fixes #51521

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: #51521
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. N/A

2021-03-10 21:32 UTC, forivall commented
as far as tests go, it would be great for the test runner to, on packages that allow deps with multiple major versions, test against the latest version of all major versions

2021-03-11 20:26 UTC, peterblazejewicz requested changes
mind adding this?
These pass before your change, should pass with your change as well IMO:
```ts
// $ExpectType Promise<string>
fs.realpath.native('src', { encoding: 'utf-8' });
// $ExpectType Promise<Buffer>
fs.realpath.native('src', { encoding: 'buffer' });
// $ExpectType Promise<string>
fs.realpath.native('src', { encoding: null });
```

2021-03-11 20:30 UTC, peterblazejewicz commented
> as far as tests go, it would be great for the test runner to, on packages that allow deps with multiple major versions, test against the latest version of all major versions

We have this discussion with DT team recently, because similar problem (multiple version) is affecting DT after `webpack` went native with TS, ther eis no clean way on DT to instrument tests (run these with Node v12) e.g with combination of `package.json` and `tsconfig.json` (package.json is only to instruct external allowed dependency, not instruct which version to pick from DT if alreayd in DT). Feel free to post your thoughts on TS discord channel, thx!

2021-03-23 20:58 UTC, peterblazejewicz approved these changes

2021-03-24 21:26 UTC, forivall commented
@typescript-bot ping?

Ready to merge

? Hmm.

2021-03-25 18:35 UTC, merged

2021-03-25 18:36 UTC, sandersn commented
@forivall critical packages like fs-extra and node require a DT maintainer to hit the merge button. @typescript-bot mentions it in the top comment, but should probably also comment after signoff, like it does for PRs where you *can* say "Ready to merge". 

Thanks for your patience!