Add type definitions for dayjs-precise-range
DefinitelyTyped/DefinitelyTyped pull request #51728
Opened 2021-03-13 13:43 UTC by fessracha

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-03-13 14:32 UTC, fessracha commented
Made a PR here microsoft/DefinitelyTyped-tools#216 to address the package dependency issue.

2021-03-15 21:58 UTC, peterblazejewicz commented on types/dayjs-precise-range/index.d.ts
> +// TypeScript Version: 2.8
```suggestion
```
It's no longer suppoert on DT (3.4 is the latest IMO), this should be used only if specific language features are required

2021-03-16 00:18 UTC, weswigham requested changes

2021-03-16 00:18 UTC, weswigham commented on types/dayjs-precise-range/tslint.json
> +      "npm-naming": false
Yeah, don't disable this lint rule - it being off can mean the publisher fails to publish types.

2021-03-16 17:18 UTC, weswigham approved these changes

2021-03-16 21:07 UTC, peterblazejewicz approved these changes

2021-03-16 21:37 UTC, merged