Add types for sumoselect
DefinitelyTyped/DefinitelyTyped pull request #51738
Opened 2021-03-14 02:25 UTC by nagamejun

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2021-03-14 15:57 UTC, martin-badin requested changes

2021-03-14 15:57 UTC, martin-badin commented on types/sumoselect/index.d.ts
> +    locale: any[];
this should be an array of strings

https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js#L49

2021-03-14 15:57 UTC, martin-badin commented on types/sumoselect/index.d.ts
> +type Option = Partial<{
missing `searchFn`

https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js#L44

2021-03-14 15:57 UTC, martin-badin commented on types/sumoselect/index.d.ts
> +    showTitle: string;
this should be boolean

https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js#L50

```suggestion
    showTitle: boolean;
```

2021-03-14 15:57 UTC, martin-badin commented on types/sumoselect/index.d.ts
> +    up: string;
this should be boolean

https://github.com/HemantNegi/jquery.sumoselect/blob/master/jquery.sumoselect.js#L50

```suggestion
    up: boolean;
```

2021-03-14 16:23 UTC, martin-badin commented on types/sumoselect/index.d.ts
> +    placeholder: string;
Please, could you provide a default value for each option? Example

```suggestion
/**
 * @default 'Select Here'
 */
    placeholder: string;
```

2021-03-15 13:31 UTC, nagamejun commented
@martin-badin 
Thank you for the review.
I'm sorry for the my mistake...
Could you check the fix again?
e16b066...9c0b936

2021-03-15 13:55 UTC, martin-badin commented on types/sumoselect/index.d.ts
> +    searchFn: (...args: any[]) => boolean;
this function has just two parameters

```suggestion
    searchFn(haystack: string, needle: string): boolean;
```

2021-03-16 14:58 UTC, martin-badin approved these changes
Thanks. Looks good to me :)

2021-03-16 15:33 UTC, merged