[@types/chrome] Define chrome.tabGroups API available in Chrome 89
DefinitelyTyped/DefinitelyTyped pull request #51731
Opened 2021-03-13 15:48 UTC by usertim

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://developer.chrome.com/docs/extensions/reference/tabGroups>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-03-14 10:52 UTC, zwacky commented
Hey @usertim, this PR is missing the new prop `tabs.groupId: number`.

if the tab isn't in a tabGroup, it will hold the value `-1`.

2021-03-14 11:25 UTC, usertim commented
Hey @zwacky 
Thanks for pointing out!
Extended chrome.tabs interface with missing props and method related to tab groups.

2021-03-14 13:56 UTC, zwacky commented on types/chrome/index.d.ts
> +    export function update(groupId: string, updateProperties: UpdateProperties, callback?: (group: TabGroup) => void): void;
`update` will only work, if the groupId is a number, just ran into this myself.

2021-03-15 08:51 UTC, zwacky commented on types/chrome/index.d.ts
> +    export function update(groupId: string, updateProperties: UpdateProperties, callback?: (group: TabGroup) => void): void;
thank you for your swift changes, @usertim.

2021-03-25 17:34 UTC, sandersn requested changes
Missing some indentation. You can try running prettier on this file, but if it hasn't already been run on it, it would cause less churn to fix it manually.

2021-03-25 20:00 UTC, ThatGuyRussell requested changes

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +     * @param moveProperties Move properties. Specify tab index, windowId
```suggestion
     * @param moveProperties Information on how to move the group.
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +     * Queries all groups that have the specified properties, or all groups if no properties are specified.
```suggestion
     * Gets all groups that have the specified properties, or all groups if no properties are specified.
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +     * @param callback Called with retrieved tab groups
```suggestion
     * @param callback Optional.
     * Parameter result: Details about the groups matching the query.
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +     export function query(queryInfo: QueryInfo, callback: (result: TabGroup[]) => void): void;
```suggestion
     export function query(queryInfo: QueryInfo, callback?: (result: TabGroup[]) => void): void;
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +     * @param updateProperties The properties to update.
```suggestion
     * @param updateProperties Information on how to update the group.
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +     * @param callback Called with an updated tab group as parameter.
```suggestion
     * @param callback Optional.
     * Parameter group: Details about the updated group.
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +	export interface TabGroupMovedEvent extends chrome.events.Event<(group: TabGroup) => void> { }
```suggestion
    export interface TabGroupMovedEvent extends chrome.events.Event<(group: TabGroup) => void> { }
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +	export interface TabGroupRemovedEvent extends chrome.events.Event<(group: TabGroup) => void> { }
```suggestion
    export interface TabGroupRemovedEvent extends chrome.events.Event<(group: TabGroup) => void> { }
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +	export interface TabGroupUpdated extends chrome.events.Event<(group: TabGroup) => void> { }
```suggestion
    export interface TabGroupUpdated extends chrome.events.Event<(group: TabGroup) => void> { }
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +    /**
Nit: Make these single line comments

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +		/**
```suggestion
        /**
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +		 * The ID of the group that the tab belongs to.
```suggestion
        * The ID of the group that the tab belongs to.
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +		 * @since Chrome 88
```suggestion
        * @since Chrome 88
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> + * @since Chrome 89.
```suggestion
 * @since Chrome 89. Manifest V3 and above.
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +		 */
```suggestion
        */
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +		groupId: number;
```suggestion
        groupId: number;
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +	export interface GroupOptions {
```suggestion
    export interface GroupOptions {
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +		/** Configurations for creating a group. Cannot be used if groupId is already specified. */
```suggestion
        /** Configurations for creating a group. Cannot be used if groupId is already specified. */
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +		createProperties?: {
```suggestion
        createProperties?: {
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +			/** The window of the new group. Defaults to the current window. */
```suggestion
            /** The window of the new group. Defaults to the current window. */
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +			windowId?: number
```suggestion
            windowId?: number
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +		},
```suggestion
        },
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +		/** The ID of the group to add the tabs to. If not specified, a new group will be created. */
```suggestion
        /** The ID of the group to add the tabs to. If not specified, a new group will be created. */
```

2021-03-25 20:00 UTC, ThatGuyRussell commented on types/chrome/index.d.ts
> +////////////////////
Please add tests. Reference: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51891/files#diff-1ac7b611fa281ad873e71ccb732137409dbeb934e1507a564cf1f108831540b4

2021-03-29 09:52 UTC, usertim commented on types/chrome/index.d.ts
> +////////////////////
Moved

2021-03-29 09:52 UTC, usertim commented on types/chrome/index.d.ts
> +	type ColorEnum = "grey" | "blue" | "red" | "yellow" | "green" | "pink" | "purple" | "cyan";
Fixed

2021-03-29 09:52 UTC, usertim commented on types/chrome/index.d.ts
> +	interface TabGroup {
Fixed all indentations

2021-03-29 09:55 UTC, usertim commented on types/chrome/index.d.ts
> +    export function get(groupId: number, callback: (group: TabGroup) => void): void;
As of 89.0.4389.90 build `.get` and `.query` method callbacks are not optional.
And while it is not stated in docs `.update` and `.move` methods will work without callback parameter just fine.

2021-03-29 09:58 UTC, usertim commented on types/chrome/index.d.ts
> +////////////////////
Added

2021-03-29 12:40 UTC, ThatGuyRussell approved these changes

2021-04-02 18:10 UTC, andrewbranch approved these changes

2021-04-02 23:56 UTC, usertim commented
Ready to merge

2021-04-02 23:56 UTC, merged