chore(slonik): Add createIntervalTypeParser typing
DefinitelyTyped/DefinitelyTyped pull request #51787
Opened 2021-03-16 15:11 UTC by cesar3030

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Look for the **interval** type name in this [table](https://github.com/gajus/slonik#slonik-type-parsers-built-in-type-parsers). You can see the interval is converted to an integer.
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-03-16 15:13 UTC, cesar3030 commented
I'm getting errors like this one when I run locally `npm test slonik`:
>ERROR: 1:1  no-outside-dependencies  File /Users/cesarjeanroy/git/DefinitelyTyped/node_modules/@types/node/zlib.d.ts comes from a `node_modules` but is not declared in this type's `package.json`.  See: https://github.com/Microsoft/dtslint/blob/master/docs/no-outside-dependencies.md

How could I fix this?
Thanks!

2021-03-21 21:47 UTC, mmkal commented
@cesar3030 slonik now publishes its own types. This shouldn't be necessary, we should just unpublish this package.

2021-03-21 21:49 UTC, mmkal requested changes
Forgot to explicitly request changes, see comment above

2021-03-23 13:52 UTC, cesar3030 commented
@mmkal I was not aware of it! Thanks for the info. Have a great day and kudos for the great work you and the team are doing 👍

2021-03-23 13:52 UTC, closed without merging