Added idle-js types
DefinitelyTyped/DefinitelyTyped pull request #51795
Opened 2021-03-16 18:30 UTC by jpeirson

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2021-03-16 19:16 UTC, martin-badin requested changes

2021-03-16 19:16 UTC, martin-badin commented on types/idle-js/index.d.ts
> +         */
Please, could you add default values to comments for each option? Example

```suggestion
        /**
         * Idle time in ms.
         * @defaut 10000
         */
```

2021-03-16 19:16 UTC, martin-badin commented on types/idle-js/index.d.ts
> +    start(): IdleJs;
change `IdleJs` to `this`
```suggestion
    start(): this;
```

2021-03-16 19:16 UTC, martin-badin commented on types/idle-js/index.d.ts
> +    stop(): IdleJs;
change `IdleJs` to `this`
```suggestion
    stop(): this;
```

2021-03-16 19:16 UTC, martin-badin commented on types/idle-js/index.d.ts
> +    reset(idle?: boolean, visible?: boolean): IdleJs;
change `IdleJs` to `this`

```suggestion
    reset(idle?: boolean, visible?: boolean): this;
```

2021-03-16 19:35 UTC, martin-badin approved these changes
Thanks. Looks good to me

2021-03-16 21:53 UTC, weswigham requested changes

2021-03-16 21:53 UTC, weswigham commented on types/idle-js/index.d.ts
> +export default IdleJs;
[This should probably be](https://github.com/soixantecircuits/idle-js/blob/master/src/index.js#L135)
```suggestion
export = IdleJs;
```

2021-03-17 07:38 UTC, martin-badin approved these changes

2021-03-17 20:08 UTC, weswigham approved these changes

2021-03-18 02:05 UTC, jpeirson commented
Ready to merge

2021-03-18 02:06 UTC, merged