Update types estree-jsx
DefinitelyTyped/DefinitelyTyped pull request #51843
Opened 2021-03-18 17:11 UTC by remcohaszing

Some properties were missing.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/jsx/blob/master/AST.md#jsx-names
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

Since this is related, I’ll mark it as closes #35355

2021-03-18 21:13 UTC, sandersn commented
A change in the TS nightly makes DT parsing run out of memory. I pinned Typescript to a version before the change while I investigate.

2021-03-22 17:54 UTC, antross requested changes
Changes look good. I think we should update the tests in `estree-jsx-tests.ts` too before merging.

2021-03-22 17:54 UTC, antross commented on types/estree-jsx/index.d.ts
> +    object: JSXMemberExpression | JSXIdentifier;
For testing these additions, you should be able to add something similar to the tests for `JSXAttribute`:
```ts
// JSXMemberExpression
const expressionObject: JSXMemberExpression | JSXIdentifier = memberExpression.object;
...
```

2021-03-23 15:35 UTC, antross approved these changes

2021-03-23 15:43 UTC, remcohaszing commented
Ready to merge

2021-03-23 15:44 UTC, merged