[google.visualization] Correct CalendarOptions / Add Test
DefinitelyTyped/DefinitelyTyped pull request #51861
Opened 2021-03-19 14:52 UTC by dckorben

Please fill in this template.

- [ X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X ] Test the change in your own code. (Compile and run.)
- [ X ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ X ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ X ] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/chart/interactive/docs/gallery/calendar#configuration-options
- [ X ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

This adds a test and fixes incorrect nullability/missing properties on existing definition.

2021-03-20 08:03 UTC, martin-badin requested changes

2021-03-20 08:03 UTC, martin-badin commented on types/google.visualization/index.d.ts
>              noDataPattern?: Object;
You can specify this one more

```suggestion
            noDataPattern?: {
            backgroundColor: string,
            color: string
            };
```

2021-03-20 08:04 UTC, martin-badin commented on types/google.visualization/index.d.ts
> +        export interface ChartStrokeOpacity extends ChartStroke {
I am not sure but I think you can update `ChartStroke` to add `strokeOpacity`

2021-03-20 08:05 UTC, martin-badin commented on types/google.visualization/index.d.ts
> +        export interface ChartStrokeOpacity extends ChartStroke {
update: no, you can't

2021-03-22 14:31 UTC, martin-badin approved these changes

2021-03-22 19:08 UTC, martin-badin approved these changes

2021-03-22 20:16 UTC, dckorben commented
Ready to merge

2021-03-22 20:17 UTC, dckorben commented
Ready to merge

2021-03-22 20:17 UTC, merged