update(file-loader): v6.2
DefinitelyTyped/DefinitelyTyped pull request #51989
Opened 2021-03-25 19:33 UTC by peterblazejewicz

- `esModule` option
- version bump

https://github.com/webpack-contrib/file-loader#esmodule

Thanks!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

2021-04-14 01:46 UTC, G-Rath requested changes

2021-04-14 01:46 UTC, G-Rath commented on types/file-loader/index.d.ts
> +// Type definitions for file-loader 6.2
```suggestion
// Type definitions for file-loader 5.0
```

`esModule` was added in v5, so it would be good to match that for this change :)

2021-04-26 18:37 UTC, G-Rath approved these changes

2021-04-26 20:54 UTC, peterblazejewicz commented
Ready to merge 💘

2021-04-26 20:55 UTC, merged