Add a `type` member to the  `Def` type
DefinitelyTyped/DefinitelyTyped pull request #52215
Opened 2021-04-06 19:37 UTC by sapristi

I'm kind of new to typescript, but it seems to me that having a `type` member of `Def` is necessary for discrimination.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-04-07 11:49 UTC, sarunint requested changes
Can you link me the `marked` source code that have that field?

2021-04-07 12:26 UTC, sapristi commented
> Can you link me the `marked` source code that have that field?

Hmm it seems that the `type` attribute does not appear in `marked` for `def`:
https://github.com/markedjs/marked/blob/master/lib/marked.js#L747

2021-04-09 14:40 UTC, sapristi commented
I have opened a pull request in the `marked` project, I will notify you when it is merged.

2021-04-12 09:36 UTC, sapristi commented
Ok so the `type: 'def'` property was added to `marked` : https://github.com/markedjs/marked/commit/47e65cfb63e8ea8acceb676f59d8d37d346ebcaf

2021-04-12 17:07 UTC, sarunint approved these changes
LTGM

2021-04-12 18:45 UTC, sapristi commented
Ready to merge

2021-04-12 18:45 UTC, merged