[pino] log object type + fix log formatter arg name
DefinitelyTyped/DefinitelyTyped pull request #52474
Opened 2021-04-20 10:17 UTC by naseemkullah

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/pinojs/pino/blob/master/docs/api.md#serializers-object
  - https://github.com/pinojs/pino/blob/master/docs/api.md#level
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-04-20 15:23 UTC, AdamVig requested changes
The change to the `level` function parameter looks good, but I do not think the change to the `log` function parameter is correct.

> When used with the default serializers option as per https://github.com/pinojs/pino/blob/master/docs/api.md#serializers-object, log objects will have a top level error object when the prop key err is matched and is of type Error.

I believe that this thinking is backwards: yes, the default serializers will serialize an error found in the `err` property of a log line, but there is nothing _forcing_ end users to always use the `err` property for values of type `Error`. If we merge this change, it would prevent folks from using the `err` property for any other type of value, for example `{err: 'Fatal error'}` (a string). I think the `object` type is correct here since it makes no assumptions about the shape of the log object.

I'm not sure what prompted you to make this change, but if you want to format the log object in this function in a type-safe manner, you can use type guards within the function:
```typescript
log(object: object) {
  if ('err' in object && object.err instanceof Error) {
    // Do something with object.err, for example extracting the message
    object.err = object.err.message;
  }
  return object;
}
```

2021-04-20 15:23 UTC, AdamVig commented on types/pino/index.d.ts
> +            log?: (object: object & {err?: Error}) => object;
```suggestion
            log?: (object: object) => object;
```

2021-04-20 15:33 UTC, AdamVig approved these changes

2021-04-26 10:40 UTC, orta approved these changes
Looks right to me

2021-04-26 12:33 UTC, naseemkullah commented
Ready to merge

2021-04-26 12:33 UTC, merged