[underscore] first argument of `get()` can be null.
DefinitelyTyped/DefinitelyTyped pull request #52554
Opened 2021-04-23 20:15 UTC by diasbruno

First argument of `get()` can be null.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-04-23 22:33 UTC, jgonggrijp requested changes
Thanks for taking the effort to contribute, @diasbruno.

You are right that the first argument of `get` can be `null` or `undefined`, but you took it a bit too far. If a fallback value is provided, you don't expect `undefined` as the return type unless the fallback itself is `undefined`.

2021-04-23 22:33 UTC, jgonggrijp commented on types/underscore/index.d.ts
> +        ): TypeOfCollection<V> | U | undefined;
This doesn't seem right to me. Even if `object` is `null` or `undefined`, `get` will still return `defaultValue`. See https://underscorejs.org/docs/modules/get.html.

2021-04-23 22:33 UTC, jgonggrijp commented on types/underscore/index.d.ts
> +        ): TypeOfCollection<V> | U | undefined;
Same here.

2021-04-23 22:33 UTC, jgonggrijp commented on types/underscore/index.d.ts
> +        ): _Chain<TypeOfCollection<V> | U | undefined, T | U | undefined>;
And here.

2021-04-23 22:33 UTC, jgonggrijp commented on types/underscore/index.d.ts
> +        ): TypeOfCollection<V> | U | undefined;
If you want to be precise, you can use separate overloads for more specific return types:

```ts
        get(object: null | undefined, path: string | string[]): undefined;
        get<V extends Collection<any>>(
            object: V,
            path: string | string[]
        ): TypeOfCollection<V> | undefined;
        get<U>(
            object: null | undefined,
            path: string | string[],
            defaultValue?: U
        ): U;
        get<V extends Collection<any>, U>(
            object: V,
            path: string | string[],
            defaultValue?: U
        ): TypeOfCollection<V> | U;
```

2021-04-23 22:33 UTC, jgonggrijp commented on types/underscore/underscore-tests.ts
> +    _.get(null, 'a');
This seems way too liberal; it's guaranteed to be `undefined`.

2021-04-23 22:33 UTC, jgonggrijp commented on types/underscore/underscore-tests.ts
> +    // $ExpectType number | undefined
No, this is never `undefined`.

2021-04-23 22:33 UTC, jgonggrijp commented on types/underscore/underscore-tests.ts
> +    // $ExpectType number | { b: number; } | undefined
Likewise.

2021-04-23 22:33 UTC, jgonggrijp commented on types/underscore/underscore-tests.ts
> +    // $ExpectType string | number | { b: number; } | undefined
And so on. I'll stop here.

2021-04-24 01:35 UTC, diasbruno commented
@jgonggrijp Totally forgot to check for those default cases. Thanks for the help again!

2021-04-24 12:26 UTC, jgonggrijp approved these changes
Looks good!

2021-04-24 13:14 UTC, diasbruno commented
Ready to merge.

2021-04-24 13:15 UTC, merged