fix: Define new json2xml package
DefinitelyTyped/DefinitelyTyped pull request #52597
Opened 2021-04-26 20:22 UTC by carboneater

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2021-04-26 20:44 UTC, rbfowler9lfc approved these changes

2021-04-27 05:48 UTC, DanielRosenwasser requested changes

2021-04-27 05:48 UTC, DanielRosenwasser commented on types/json2xml/index.d.ts
> +declare function json2xml(json: unknown): string;
```suggestion
declare function json2xml(json: unknown, opts?: { header?: boolean, attributes_key?: string }): string;
```

2021-04-27 05:48 UTC, DanielRosenwasser commented on types/json2xml/json2xml-tests.ts
> +json2xml(undefined); // $ExpectType string
```suggestion
json2xml(undefined); // $ExpectType string

json2xml({}, { header: true }); // $ExpectType string
json2xml({}, { attributes_key: 'attributes' }); // $ExpectType string
```

2021-04-28 00:32 UTC, merged