node: crypto sign/verify callback from v15.12.0
DefinitelyTyped/DefinitelyTyped pull request #52652
Opened 2021-04-29 11:56 UTC by panva

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/nodejs/node/releases/tag/v15.12.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-04-29 13:42 UTC, panva commented
`mongoose` tests failure is unrelated to this PR.

2021-04-29 19:55 UTC, SimonSchick requested changes
This generally looks good but I'm looking to get these merged in order to avoid version confusion, I filed a PR to get up 15.2 but we are still a good bit away from 15.12.

I think we can reasonable merge this in a week, with an added note it's only available as of 15.12

2021-04-29 19:55 UTC, SimonSchick commented on types/node/crypto.d.ts
> +        callback: (err: Error | null, signature: Buffer) => any,
Callback return type should be `void`.

2021-04-29 19:55 UTC, SimonSchick commented on types/node/crypto.d.ts
> +        callback: (err: Error | null, result: boolean) => any,
See above.

2021-04-29 19:56 UTC, SimonSchick commented
Also please consider merging https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52653 into this as it is easier to keep track of the versioning this way.

2021-05-04 08:04 UTC, SimonSchick commented
@panva I'm making good progress getting things up to date, see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52732

I'm trying to batch version changes together, do you have any objections of me integrating your changes into my branch?

2021-05-04 08:04 UTC, panva commented
No objections

2021-05-04 08:06 UTC, SimonSchick commented
Let me know if you have any other fragments you have been working on, I'd be glad to integrate them as well.

2021-05-04 08:10 UTC, closed without merging