[video.js] Add responsive to VideoJsPlayerOptions
DefinitelyTyped/DefinitelyTyped pull request #52754
Opened 2021-05-05 02:40 UTC by blzaugg

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - https://docs.videojs.com/player#responsive
  - https://docs.videojs.com/tutorial-options.html#responsive

2021-05-05 02:48 UTC, blzaugg commented on types/video.js/video.js-tests.ts
> +
Member test added

2021-05-10 18:03 UTC, blzaugg commented
@joeflateau, @gjanblaszczyk, @sroucheray any chance of taking a look at this?

2021-05-10 18:07 UTC, joeflateau requested changes
please revert all of the quotes to their previous form (single). looks good beyond that

2021-05-10 18:45 UTC, joeflateau approved these changes
looks good

2021-05-10 19:27 UTC, blzaugg commented
Ready to merge

2021-05-10 19:28 UTC, merged