[react-syntax-highlighter] Added supportedLanguages type to SyntaxHighlighter
DefinitelyTyped/DefinitelyTyped pull request #52772
Opened 2021-05-05 21:29 UTC by amphithere

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/react-syntax-highlighter/react-syntax-highlighter#supported-languages>>

2021-05-17 15:19 UTC, michaelyuen requested changes
My apologies for the delay in review. Thank you for these updates! They look good, but please double-check my comments regarding the specific highlighter versions that don't implement `supportedLanguages`.

2021-05-17 15:19 UTC, michaelyuen commented on types/react-syntax-highlighter/index.d.ts
> +        static supportedLanguages: string[];
It doesn't appear this property exists (is added) to the light version: https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/v13.5.3/src/light.js

I've verified this against the package installed in my project.

2021-05-17 15:19 UTC, michaelyuen commented on types/react-syntax-highlighter/index.d.ts
> +        static supportedLanguages: string[];
This property is not available on prism-light: https://github.com/react-syntax-highlighter/react-syntax-highlighter/blob/v13.5.3/src/prism-light.js

2021-05-17 15:19 UTC, michaelyuen commented on types/react-syntax-highlighter/index.d.ts
> +        static supportedLanguages: string[];
Same thing here. This property isn't available on light.

2021-05-17 15:19 UTC, michaelyuen commented on types/react-syntax-highlighter/index.d.ts
> +        static supportedLanguages: string[];
Same thing here. This property isn't available on prism-light.

2021-05-17 15:19 UTC, michaelyuen commented on types/react-syntax-highlighter/react-syntax-highlighter-tests.tsx
> +    PrismLightHighlighter.supportedLanguages; // $ExpectType string[]
Since `supportedLanguages` is not available on prism-light, I believe this line should be removed.

2021-06-03 17:58 UTC, smol-honk commented
@michaelyuen Thank you so much for your review! I updated the pr with those revisions. 😄

2021-06-19 23:15 UTC, michaelyuen approved these changes
Sorry for the delay. Looks good to me!

2021-06-19 23:17 UTC, michaelyuen commented
Ready to merge

2021-06-19 23:17 UTC, merged