Watermark dom
DefinitelyTyped/DefinitelyTyped pull request #52897
Opened 2021-05-12 07:33 UTC by shlroland

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-05-12 10:12 UTC, BendingBender requested changes

2021-05-12 10:12 UTC, BendingBender commented on types/watermark-dom/index.d.ts
> +    monitor: boolean; // monitor 是否监控， true: 不可删除水印; false: 可删水印。
Please use doc comments:
```ts
    /**
     * 水印总体的id
     */
    watermark_id: string;
    ...
    /**
     * 水印的总体宽度
     * 
     * @default body的scrollWidth和clientWidth的较大值
     */
    watermark_parent_width: number;
    ...
```

2021-05-12 10:12 UTC, BendingBender commented on types/watermark-dom/index.d.ts
> +export interface Settings {
Why do you make the interface members non-optional and instead make the whole interface later in `init`/`load` `Partial`? It's not very ergonomic for your users and it increases compile times. You should instead make all of the interface members optional:
```ts
export interface Settings {
    watermark_id?: string;
    watermark_prefix?: string;
    watermark_txt?: string;
    watermark_x?: number;
    ...
}
```

2021-05-12 10:20 UTC, BendingBender requested changes

2021-05-12 10:20 UTC, BendingBender commented on types/watermark-dom/index.d.ts
> +}
The export is actually incorrect. The way it's specified you should be able to import this lib as `import { default } from 'watermark-dom';`. Which is clearly wrong, the library doesn't have a default export. This should instead be:
```suggestion
export function init(settings: Partial<Settings>): void;

export function load(settings: Partial<Settings>): void;

export function remove(): void;
```

2021-05-12 10:20 UTC, BendingBender commented on types/watermark-dom/index.d.ts
> +export default watermarkDom;
This export is incorrect, there is no `default` export in the original lib.

2021-05-12 12:11 UTC, BendingBender approved these changes

2021-05-12 20:31 UTC, peterblazejewicz approved these changes

2021-05-12 23:14 UTC, andrewbranch approved these changes

2021-05-13 01:45 UTC, shlroland commented
> Ready to merge

Ready to merge

2021-05-13 02:57 UTC, shlroland commented
Ready to merge

2021-05-13 02:58 UTC, merged