build: Do not force double quotes through prettier #51436
DefinitelyTyped/DefinitelyTyped pull request #52946
Opened 2021-05-14 14:19 UTC by pkuczynski

Reverts #51436 to avoid unnecessary PR like #52790 which only create noise changing single to dbl quotes. Also its not true, that `dslint` is forcing dbl quotes, as otherwise all the builds would be failing by now. Actually the `quitemark` rule in dtslint is disabled! See https://github.com/microsoft/dtslint/blob/master/dtslint.json#L115. See description of this rule: https://palantir.github.io/tslint/rules/quotemark/

2021-05-14 18:54 UTC, fedemp commented
First of all, a build will not fail whatever choice of quotes you make. This is not about `prettier`.
A build will fail if `quotemark` property is defined in `tslint.json`. e.g. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/angular/tslint.json#L17 but then, `tslint.json` must only contain `{ "extends": "dtslint/dt.json" }`

As an aside, most of the types here tend to use double quotes.
```shell
$ rg "'" -l | wc -l
18652
$ rg '"' -l | wc -l
45484
```

2021-05-15 08:07 UTC, p-j commented
Regardless of the config we settle on in the end, I believe it would be best to enforce the style. Many developers (including myself) have their environment configured to pickup whatever style rules are configured in a given project and apply it on save.
That's what prompted this [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52790) to the faker package and possibly this other [PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51651) to the echarts package.
And that's also visible on this [other PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52943) to the faker package.

This is doable either by adding a lint step to the build and doing a one time format of the whole repository, or, a less painful version could be setting up something like [creyD/prettier_action](https://github.com/creyD/prettier_action) with the `only_changed` option set to true to progressively update the code style to a more coherent one.
Lastly, another option that has my preference, as less noisy and overall more flexible, is for each package to define its own `.prettierrc.json` to have its own rules taking precedence over the global ones.

This last option would also be more inline with the current contribution guidelines as well
> ## Code style
> At this point we do not enforce a specific general code style, but we do like idiomatic code in each individual file.
When creating a new definition file the author is free to choose either tabs or 4-space indentation ([discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/1709) on github).
Choice between Unix or Windows linebreaks is not enforced, as node.js doesn't care for it either way. Try to keep it idiomatic per file.
**When editing an existing file please maintain the existing style as much as possible, this includes indenting, separator whitespace, bracing etc..**
Do not use fancy code alignments or smart-tabs; instead keep things plain and simple.
It is discouraged to reformat existing code (as it breaks git attribution).
When preparing a Pull Request please check git diff (locally or on github) for unnecessary changes.
Regard the typing folder in your project as external resource and exclude it from your linter/formatter workflow, just like any library file.

Source: [definitelytyped.org](https://definitelytyped.org/guides/contributing.html)

What are your thoughts on that?

2021-05-16 11:33 UTC, pkuczynski commented
> A build will fail if quotemark property is defined in tslint.json

Then the owner of a package should add `prettier` config in this directory if he is adding a custom `tslint` config.

> As an aside, most of the types here tend to use double quote

Still, 30% is single quotes, so forcing the change for no obvious benefit, is a bit too harsh, don't you think? Especially the setting was opposite from the beginig.

2021-05-16 11:38 UTC, pkuczynski commented
> either by adding a lint step to the build and doing a one time format of the whole repository

I think this would make sense, however first you would need to merge all existing PR, which would be problematic. Hence I would leave the setting, which was here for over 2 years, instead of just arbitrary setting it to something else without larger discussion...

> each package to define its own .prettierrc.json

That makes the most sense to me too.

Yet, I would revert #51436 to the state which this repo had from the start...

2021-05-16 15:05 UTC, fedemp commented
> Still, 30% is single quotes, so forcing the change for no obvious benefit, is a bit too harsh, don't you think? Especially the setting was opposite from the beginig.

Why do you insist on saying "forcing" when `prettier` is not CI step and I have admited that build will fail only if a package sets custom rules for `tslint`?

> > each package to define its own .prettierrc.json
> 
> That makes the most sense to me too.

That would be terrible.  You are polluting the directory with something that should be a standard across the whole project.

Finally, I could not care less about single or double quotes, specially given that contributors are not required to run `prettier`. I just run it before commiting because whatever. And I want to make it clear that the `prettier` config does not make a build fail.

2021-05-16 15:29 UTC, pkuczynski commented
@fedemp than please revert your last change (by approving this PR) as you caused more harm then good. It was setup to be single quotes and there was no reason to change it for double. The claim about dtslint from your initial PR was not correct.

2021-05-16 15:31 UTC, fedemp commented
> @fedemp than please revert your last change (by approving this PR) as you caused more harm then good. It was setup to be single quotes and there was no reason to change it for double. The claim about dtslint from your initial PR was not correct.

I'm not a mantainer! I can't approve PRs! Please stop summoning me.

2021-05-16 16:10 UTC, pkuczynski commented
FYI @elibarzilay

2021-05-17 07:22 UTC, p-j approved these changes

2021-05-19 19:30 UTC, peterblazejewicz commented
@pkuczynski mind amending the title to state 'Revert ....'? thx!

@fedemp I'll amend this thread on TypeScript about allowing Prettier config composition per DT, so it could be allowed for types coming from entities that arleady using their own styles, completely forgotten about this, thx!

/cc @sandersn

2021-05-19 19:42 UTC, peterblazejewicz commented
I was wondering recently, why I've been "changing" quotes :) I could be using interactive add/remove to skip those changes, but the fact of those changes.

2021-05-19 19:44 UTC, peterblazejewicz reviewed
@pkuczynski Piotr, can you please amend the title and commit message, to just state
we are reverting the change? thx!

2021-05-19 19:45 UTC, peterblazejewicz commented
x-ref: https://github.com/microsoft/TypeScript/issues/44030#issuecomment-844411885

2021-05-19 20:02 UTC, pkuczynski commented
> mind amending the title to state 'Revert ....'? thx!

Done @peterblazejewicz :)

2021-05-19 20:04 UTC, pkuczynski commented
> Piotr, can you please amend the title and commit message, to just state we are reverting the change? thx!

The title is fixed. Commit message was already `Revert DefinitelyTyped#51436` - is that good enough or do you want me to be more elaborate?

2021-05-19 21:11 UTC, peterblazejewicz approved these changes

2021-05-20 13:27 UTC, orta commented
I think we should merge this, and then add a rule to the dt-mergebot which bans any changes to the prettier config or editorconfig  files. 

I think we want a light approach to formatting on DT simply because there are so many contributors and there's _very little value_ in having the formatting be consistent at the "DT" level. We're not going to be enforcing it, it just adds an arbitrary barrier to contributing.

The prettier file is there to help folks with their tooling, and the settings are reasonable enough, we bike-shedded them a long time ago and are pretty happy with them as defaults. Even if I think double quotes is _the one true way_ ™️.

I'm very wary of encouraging subsets of this codebase where formatting becomes blockers for contributions, 
but as the .prettier config files aren't enforced, it doesn't seem unreasonable to allow for them in a DT module folder. We've got the review for https://github.com/microsoft/TypeScript/issues/44030#issuecomment-844411885 today, so I'll bring it up in there.

2021-05-21 01:53 UTC, ExE-Boss requested changes

2021-05-21 01:53 UTC, ExE-Boss commented on .prettierrc.json
> +    "singleQuote": true,
It might be better to remove this, as `singleQuote: true` forces single quotes, but as <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52946#issuecomment-841437698> shows, double quotes are used more in this repository.
```suggestion
```

2021-05-21 12:56 UTC, orta commented
We chatted this over, lets revert and just keep it as is (sorry Exe-Boss, I do agree with you though) and I'll add the dt-mergebot logic to it as it is

2021-05-21 12:56 UTC, merged