[nova-editor-node] Update getParent and openFile, add openNewTextDocument
DefinitelyTyped/DefinitelyTyped pull request #53012
Opened 2021-05-17 19:49 UTC by krisbreuker

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  * `TreeDataProvider.getParent`: https://docs.nova.app/api-reference/tree-data-provider/
  * `Workspace.openFile`: https://docs.nova.app/api-reference/workspace/#openfileuri-options
  * `Workspace.openNewTextDocument`: https://docs.nova.app/api-reference/workspace/#opennewtextdocumentoptions
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-05-18 18:02 UTC, apexskier requested changes
Thanks for this! My one suggestion is to pull the column/line relationship into a shared type like in this PR

https://github.com/krisbreuker/DefinitelyTyped/pull/1

2021-05-19 10:15 UTC, krisbreuker commented
Thanks for the suggestion, @apexskier. I have split off line and column into a separate type, which makes it much cleaner.

2021-05-19 11:27 UTC, apexskier approved these changes

2021-05-19 13:07 UTC, krisbreuker commented
Ready to merge

2021-05-19 13:08 UTC, merged