[@types/chrome] Update chrome.tabs API to add missing parameter and function for tabgroup use
DefinitelyTyped/DefinitelyTyped pull request #53324
Opened 2021-05-23 08:59 UTC by MrSweeter

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://developer.chrome.com/docs/extensions/reference/tabs/>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-05-24 18:17 UTC, matcarlson requested changes

2021-05-24 18:17 UTC, matcarlson commented on types/chrome/index.d.ts
> +    export function ungroup(tabIds: number | number[], callback?: () => void): void
Can you add an override for this function returning a Promise, similar to [line 8341](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome/index.d.ts#L8341)

2021-05-24 18:17 UTC, matcarlson commented on types/chrome/index.d.ts
>      export function group(options: GroupOptions, callback?: (groupId: number) => void): void
Since this is related, could you also add the Promise override here as well?

2021-05-25 16:14 UTC, matcarlson approved these changes
Thanks for the changes!

2021-05-25 16:18 UTC, userTim approved these changes

2021-05-25 16:18 UTC, userTim commented
Ready to merge

2021-05-25 16:19 UTC, merged