[russian-nouns-js] Add types
DefinitelyTyped/DefinitelyTyped pull request #53332
Opened 2021-05-23 15:36 UTC by RusAnonym

2021-05-23 17:14 UTC, martin-badin requested changes
Please add tests

2021-05-23 17:17 UTC, martin-badin requested changes

2021-05-23 17:17 UTC, martin-badin commented on types/russian-nouns-js/src/Gender.d.ts
> +}
Change it to enum
```suggestion
export default enum Gender {
     FEMININE = "женский",
     MASCULINE = "мужской",
     NEUTER = "средний",
     COMMON= "общий",
}
```

2021-05-23 17:17 UTC, martin-badin commented on types/russian-nouns-js/src/Case.d.ts
> +}
Change it to enum 
```suggestion
export default enum Case {
    NOMINATIVE = "именительный",
    GENITIVE = "родительный",
    DATIVE = "дательный",
    ACCUSATIVE = "винительный",
    INSTRUMENTAL = "творительный",
    PREPOSITIONAL = "предложный",
    LOCATIVE = "местный",
}
```

2021-05-24 22:42 UTC, sandersn approved these changes

2021-05-24 22:42 UTC, merged