[@chec/commerce.js] Add missing commerce.request() method
DefinitelyTyped/DefinitelyTyped pull request #53450
Opened 2021-05-27 21:20 UTC by PaitoAnderson

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/chec/commerce.js/blob/master/src/commerce.js#L65
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-05-27 21:24 UTC, robbieaverill approved these changes
This method wasn't intended to be consumed directly via the Commerce.js API, however I have no problem with adding it to the definitions

2021-05-27 21:27 UTC, PaitoAnderson commented
@robbieaverill Oh okay, thanks for clarifying that! 👍

2021-06-01 18:29 UTC, robbieaverill requested changes
Thanks for much for taking the time to update these types. I've left a comment around variants.

2021-06-01 18:29 UTC, robbieaverill commented on types/chec__commerce.js/types/product.d.ts
> +  variant_groups: Variant[];
These are a list of variant groups now. We probably need to update those types to suit the latest API version. A quick summary would be:

Product's `variant_groups: VariantGroup[]`:

* id: string
* name: string
* meta: object|array ?
* created: int?
* updated: int?
* options: VariantOption[]

A Variant is a type, but it's not connected directly in product responses any more. Instead, there's a separate API to fetch variants for a product: https://commercejs.com/docs/sdk/products#get-variants. This API returns a list of Variants, and a Variant object looks like this:

* id: stirng
* sku: string
* description: string
* inventory: int?
* price: Price?
* is_valid: boolean
* invalid_reason_code: string
* meta: object|array ?
* created: int?
* updated: int?
* options: VariantOption[]
* assets: Asset[]

The `options` attribute in a variant object lists the variant options that make up this variant, for example if the product was "New season T-shirt", the variant might be "Small + Red" and the variant options would be "Small" and "Red".

Would you be keen to add in these new types?

2021-06-01 22:03 UTC, robbieaverill requested changes
I'm happy to help with this if you'd like

2021-06-01 22:03 UTC, robbieaverill commented on types/chec__commerce.js/features/products.d.ts
> +  getVariant(id: string, variantId: string): Promise<VariantOption>;
These return a list of Variant models and a single Variant, not a variant option

2021-06-01 23:38 UTC, PaitoAnderson commented
Thanks! Sorry, I was struggling with naming.

2021-06-02 00:05 UTC, robbieaverill approved these changes
LGTM, thanks for doing those updates 🙂

2021-06-02 00:06 UTC, PaitoAnderson commented
Ready to merge

2021-06-02 00:07 UTC, merged