🏷️ Update Types  react-native-datawedge-intents
DefinitelyTyped/DefinitelyTyped pull request #53469
Opened 2021-05-28 10:33 UTC by Frabanz

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/darryncampbell/react-native-datawedge-intents/blob/master/index.js>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-05-28 10:43 UTC, Frabanz commented on types/react-native-datawedge-intents/react-native-datawedge-intents-tests.ts
> +DataWedgeIntents.registerReceiver(action, category);
```suggestion
    DataWedgeIntents.registerReceiver(action, category);
```

2021-05-28 10:44 UTC, Frabanz commented on types/react-native-datawedge-intents/index.d.ts
> +// Type definitions for react-native-datawedge-intents 0.1.6
```suggestion
// Type definitions for react-native-datawedge-intents 0.1
```

2021-06-21 15:18 UTC, orta commented
Are you sure you want to include these? They are both marked as deprecated in the JS, and may have been left out on purpose.

2021-07-09 01:46 UTC, elibarzilay commented
Ping re @orta's question

2021-07-27 17:39 UTC, sandersn requested changes
Requesting changes so the bot catches to the current state of the PR.

2021-08-27 18:57 UTC, closed without merging