update(oracledb): Add QueryStream interface
DefinitelyTyped/DefinitelyTyped pull request #53614
Opened 2021-06-04 15:22 UTC by Chrisp1tv

This adds the `QueryStream` class in the `oracledb` module types, which is used when streaming results of a query.
Sorry I didn't update the tests as I didn't find any clear way to test it, but I would be very happy to do it with some help!

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Source code of the QueryStream class](https://github.com/oracle/node-oracledb/blob/master/lib/queryStream.js), [Documentation about query streaming](http://oracle.github.io/node-oracledb/doc/api.html#streamingresults)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-06-08 17:52 UTC, connorjayfitzgerald commented
Thanks @Chrisp1tv. Looks great.
I’ll have a go tonight at adding some tests for the changes and then approve it

2021-06-08 23:00 UTC, connorjayfitzgerald requested changes
If you could just add the following block to the tests file, that should be sufficient to show the updated QueryStream type is working as expected:

`export const testQueryStreamGenerics = (connection: oracledb.Connection): void => {
    interface MyStream {
        streamTest: string;
    }

    const stream = connection.queryStream<MyStream>('SELECT 1 FROM DUAL WHERE 10 < :myValue', {
        myValue: {
            dir: oracledb.BIND_IN,
            maxSize: 50,
            type: oracledb.NUMBER,
            val: 20,
        },
        anotherValue: {
            dir: oracledb.BIND_INOUT,
            type: oracledb.DB_TYPE_NCLOB,
        },
    });

    stream.on('data', data => {
        console.log(data);
    })

    stream.on('metadata', metadata => {
        const streamClass = metadata[0].dbTypeClass;

        const streamClassInstance = new streamClass({
            streamTest: 'success'
        });
    });
}`

Thanks

2021-06-09 09:12 UTC, Chrisp1tv commented
Thanks for the test @connorjayfitzgerald! 🚀

2021-06-09 09:26 UTC, connorjayfitzgerald approved these changes

2021-06-09 09:28 UTC, Chrisp1tv commented
Ready to merge

2021-06-09 09:28 UTC, merged