Added missing alternative gapi.client.load method in @types/gapi.client
DefinitelyTyped/DefinitelyTyped pull request #53681
Opened 2021-06-08 12:08 UTC by philippedasilva-orizone

gapi currently provides discovery document based loading mechanisms that is missing in the current @types/gapi.client package: see https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md#----gapiclientloadurlorobject--

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-06-08 13:01 UTC, Maxim-Mazurok requested changes
@philippedasilva-orizone, thank you for the contribution! I'm really happy to see someone interested in this project.
There are a few small issues to address.

Also, please check out this project: https://github.com/Maxim-Mazurok/gapi
Basically, the [documentation](https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md) and the actual source doesn't match ([example](https://github.com/google/google-api-javascript-client/issues/629)). So we can't really rely on it. So please, make sure that you test that the `load` function actually works with the string (URL), and with the object.

Another thing is that `object` should ideally be typed. I assume that it uses the same object schema as `init`.

Also, you might want to check out `@types/gapi`. It doesn't have this definition of the load function: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/73f68020e4d47aad35bb18696a7a0367c77ebcc1/types/gapi/index.d.ts#L207-L222

So, please, provide a working example if you'd like to add this function definition so that I can verify it, thanks!

2021-06-08 13:07 UTC, philippedasilva-orizone commented on types/gapi.client/index.d.ts
> +         * Loads the client library interface to a particular API with discovery document URL or JSON object.
I will

2021-06-08 13:08 UTC, philippedasilva-orizone commented on types/gapi.client/index.d.ts
> +         * (Example: https://github.com/google/google-api-javascript-client/blob/master/samples/loadedDiscovery.html).
To be honest, I took the example from the actual documentation. After checking this example, I see that Google isn't accurate on their documentation. I'll remove it.

2021-06-08 13:39 UTC, philippedasilva-orizone commented
> @philippedasilva-orizone, thank you for the contribution! I'm really happy to see someone interested in this project.
> There are a few small issues to address.
> 
> Also, please check out this project: https://github.com/Maxim-Mazurok/gapi
> Basically, the [documentation](https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md) and the actual source doesn't match ([example](https://github.com/google/google-api-javascript-client/issues/629)). So we can't really rely on it. So please, make sure that you test that the `load` function actually works with the string (URL), and with the object.
> 
> Another thing is that `object` should ideally be typed. I assume that it uses the same object schema as `init`.
> 
> Also, you might want to check out `@types/gapi`. It doesn't have this definition of the load function:
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/73f68020e4d47aad35bb18696a7a0367c77ebcc1/types/gapi/index.d.ts#L207-L222
> 
> So, please, provide a working example if you'd like to add this function definition so that I can verify it, thanks!

I tested this load method with both the URL and its parsed JSON version and they both worked on my local project.

Regarding having the `object` typed, I don't know about the `init` object schema but I believe it should use the document discovery schema. Unfortunately, I'm unaware of its definition and it might actually be typed elsewhere (such as in the `@types/gapi.client.discovery` package). I'll have some difficulties getting into it and properly get it done.
Couldn't we consider this as a step forward the full resolution of this difference?

And I confirm that the `@types/gapi` package doesn't include this method signature. I actually have difficulties to understand if it should be there or not btw...

2021-06-08 16:14 UTC, philippedasilva-orizone commented
Quick finding while reading again the documentation over at google:

I noticed that the actual `gapi.client.load(name: string, version: string)` signature is considered as deprecated at least at the documentation level... https://github.com/google/google-api-javascript-client/blob/master/docs/reference.md#----gapiclientloadurlorobject--

You can clearly read it:
```
Deprecated. Please load APIs with discovery documents. Loads the client library interface to a particular API. If a callback is not provided, a goog.Thenable is returned. The loaded API interface will be in the form gapi.client.api.collection.method. For example, the Moderator API would create methods like gapi.client.moderator.series.list.
```

2021-06-08 22:23 UTC, amcasey commented
@Maxim-Mazurok, have your concerns been addressed?

2021-06-09 00:08 UTC, philippedasilva-orizone commented
@Maxim-Mazurok I meant to update the test fixture with something (even thow I never used TTD before but I'm a fast learner :p) but I can also get you with some other quick example if you want? I could use http://codesanbox.io to put together a quick example?

2021-06-09 00:27 UTC, Maxim-Mazurok commented
Yes, this is actually exactly what I meant :)

2021-06-13 02:24 UTC, philippedasilva-orizone commented
Hi @Maxim-Mazurok, sorry for not giving news for the last 4 days but they have been pretty busy in my side of the world and it doesn't look like it'll settle down for a bit.
I'm therefore just passing by to let you know that I can't see a time soon where I'll be able to drop a simple test bed example for you to try out.

So it's up to you to either give it a try on a simple test example, wait for me to get some spare time to work on it or just disclose this PR: I may revive a new one including a proper sample test later on.

Cheers

2021-06-15 01:40 UTC, Maxim-Mazurok commented
@philippedasilva-orizone thanks for the update, I've been pretty busy myself, but will try to come up with tests. Probably the best place for them would be in https://github.com/Maxim-Mazurok/gapi project, as they'd help to understand the innerworkings of gapi better.

2021-06-20 15:13 UTC, Maxim-Mazurok commented
> Re-ping @Maxim-Mazurok:
> 
> This PR has been out for over a week, yet I haven't seen any reviews.
> 
> Could someone please give it some attention? Thanks!
> <!--typescript_bot_Unreviewed:nearly:2021-06-08-->

Thanks for the reminder

2021-07-09 01:56 UTC, elibarzilay commented
@philippedasilva-orizone / @Maxim-Mazurok : Sounds like neither of you is certain this this should go in, and both of you are busy; perhaps its best to stash this for now, or maybe convert it to a draft pr?

2021-07-09 02:25 UTC, Maxim-Mazurok commented
Yes, I didn't have time to test this. Am ok with both options, thanks!

2021-07-09 16:07 UTC, elibarzilay commented
OK, I converted it to a draft.

2025-04-09 17:57 UTC, sandersn commented
This is very old now so I am going to close it.

2025-04-09 17:57 UTC, closed without merging