Add default export for tabulator-tables
DefinitelyTyped/DefinitelyTyped pull request #53749
Opened 2021-06-11 02:47 UTC by yujiberra

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

tabulator-tables@4.9.3's package.json has the following:
```
  "main": "dist/js/tabulator.js",
  "module": "dist/js/tabulator.es2015.js",
```
The latter has `export default Tabulator;`, the former has:
```
(function (global, factory) {
	if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object' && typeof module !== 'undefined') {
		module.exports = factory();
	} else if (typeof define === 'function' && define.amd) {
		define(factory);
	} else {
		global.Tabulator = factory();
	}
})
```
Applied to a function that returns the constructor for Tabulator, so having `export default Tabulator` in `index.d.ts` makes sense in either case.

2021-06-11 03:17 UTC, yujiberra commented
Disabled NeedsExportEquals in my latest commit to pass CI. 

Using `export default` is what the [TypeScript handbook recommends](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#default-exports) when `module.exports` is a single object .

2021-06-11 13:59 UTC, Jojoshua reviewed
Default export has been discussed before. It should not be added due to breaking existing codebases. See https://github.com/Jojoshua/TypedTabulator/wiki/Module-Usage--(Error--node_modules-@types-tabulator-tables-index.d.ts'-is-not-a-module) for resolution to your issue.

2021-06-11 21:22 UTC, amcasey requested changes
Please address the feedback from @Jojoshua

2021-06-12 00:19 UTC, yujiberra commented
@Jojoshua Thanks for looking into this and for the tip, I was able to get this working by making an index.d.ts as described in your link.

I think, though, that the fact that there have been multiple PRs about this (and a number of 'me too' comments on one of them) indicates that there's room for some kind of improvement here so that so much developer time doesn't get wasted on this (and of course, the people who actually comment/make PRs are probably a minority of people who encounter this problem). 

The best I can think of is just adding some comments to the type definition file, which I've pushed in my latest commit (as well as reverting my other commits). I do see that you added that wiki page recently but I think it would be good to have something that any would-be pull requesters would definitely see.

2021-06-12 00:26 UTC, Jojoshua commented
> @Jojoshua Thanks for looking into this and for the tip, I was able to get this working by making an index.d.ts as described in your link.
> 
> I think, though, that the fact that there have been multiple PRs about this (and a number of 'me too' comments on one of them) indicates that there's room for some kind of improvement here so that so much developer time doesn't get wasted on this (and of course, the people who actually comment/make PRs are probably a minority of people who encounter this problem).
> 
> The best I can think of is just adding some comments to the type definition file, which I've pushed in my latest commit (as well as reverting my other commits). I do see that you added that wiki page recently but I think it would be good to have something that any would-be pull requesters would definitely see.

@yujiberra I think that's a great idea, thanks for adding that

2021-06-12 00:27 UTC, Jojoshua approved these changes

2021-06-14 00:34 UTC, yujiberra commented
(whoops sorry, I didn't mean to manually request another review; I am new to this interface and thought it was just a refresh button)

2021-06-14 17:57 UTC, amcasey approved these changes
Great outcome!  Thanks!

2021-06-14 23:23 UTC, yujiberra commented
Ready to merge

2021-06-14 23:24 UTC, merged