imapflow typings
DefinitelyTyped/DefinitelyTyped pull request #54500
Opened 2021-07-13 19:33 UTC by jeffreyratton98

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-07-13 22:29 UTC, andrewbranch requested changes

2021-07-13 22:29 UTC, andrewbranch commented on package.json
> +        "danger": "^10.1.1",
Please revert package.json changes

2021-07-14 17:25 UTC, andrewbranch commented
Hang on, imapflow [generates its own types from JSDoc](https://unpkg.com/browse/imapflow@1.0.59/lib/types.d.ts), it just doesn’t list them in its package.json so they likely won’t get pulled in... were you aware of this? Maybe you should work with the library author to improve that instead of duplicating them here. Alternatively, if the author wants to move them to DT, that’s fine, but they should delete the included typings if that’s the case. Can you try to sort this out with the library author? We would like to avoid having duplicated/conflicting definitions here. Thanks!

2021-07-14 17:51 UTC, jeffreyratton98 commented
> Hang on, imapflow [generates its own types from JSDoc](https://unpkg.com/browse/imapflow@1.0.59/lib/types.d.ts), it just doesn’t list them in its package.json so they likely won’t get pulled in... were you aware of this? Maybe you should work with the library author to improve that instead of duplicating them here. Alternatively, if the author wants to move them to DT, that’s fine, but they should delete the included typings if that’s the case. Can you try to sort this out with the library author? We would like to avoid having duplicated/conflicting definitions here. Thanks!

From the most recent issue regarding types:
According to the author, he would like to see the types moved to DT.  See his comment here:
https://github.com/andris9/imapflow/issues/4#issuecomment-704312044

Since his generated types are not linked in the package.json, we shouldn't have any issues with collisions, correct?

2021-07-14 18:27 UTC, andrewbranch commented
Sounds good, just wanted to make sure everyone was on the same page here.

2021-07-14 18:27 UTC, andrewbranch approved these changes

2021-07-14 18:37 UTC, jeffreyratton98 commented
Ready to merge

2021-07-14 18:37 UTC, merged