Bugfix: Add keys missing on the return object of parsed certificates
DefinitelyTyped/DefinitelyTyped pull request #54610
Opened 2021-07-18 21:22 UTC by joshuaharry

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
See https://github.com/encharm/x509.js/blob/84a46e220a067b8ae26f3b795bc62233029d4088/tests/parseCert.js#L48

2021-07-20 10:30 UTC, Moser-ss requested changes

2021-07-20 10:30 UTC, Moser-ss commented on types/x509.js/index.d.ts
> +        organizationalUnitName: string;
This should be optional, not every certificate have organizationalUnitName

2021-07-20 10:30 UTC, Moser-ss commented on types/x509.js/index.d.ts
> +        localityName: string;
From the example I have this should be optional

2021-07-20 10:30 UTC, Moser-ss commented on types/x509.js/index.d.ts
> +        stateOrProvinceName: string;
From the example I have this should be optional

2021-07-20 21:01 UTC, Moser-ss approved these changes
Looks ok

2021-07-21 21:08 UTC, joshuaharry commented
Ready to merge

2021-07-21 21:09 UTC, merged