[node] Fix encoding shorthand options type
DefinitelyTyped/DefinitelyTyped pull request #54711
Opened 2021-07-24 06:32 UTC by LinusU

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - https://github.com/nodejs/node/blob/6140b3753fd6160b0c50a61500c04de8e36f9c05/lib/internal/fs/utils.js#L319-L322
  - https://github.com/nodejs/node/blob/6140b3753fd6160b0c50a61500c04de8e36f9c05/lib/fs.js#L2092
  - https://github.com/nodejs/node/blob/6140b3753fd6160b0c50a61500c04de8e36f9c05/lib/fs.js#L372
  - https://github.com/nodejs/node/blob/6140b3753fd6160b0c50a61500c04de8e36f9c05/lib/internal/fs/streams.js#L308
- [n/a] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

-----

I added test for `createWriteStream` and `createReadStream`, the `writeFile` and `readFile` functions already had tests covering this.

The `readFileSync` function was already correct.

2021-07-24 07:09 UTC, SimonSchick requested changes

2021-07-24 07:09 UTC, SimonSchick commented on types/node/test/fs.ts
> +    fs.createWriteStream('./index.d.ts');
We should add a failing test here using `// $ExpectError`, these tests would pass even without your changes.

2021-07-24 13:05 UTC, LinusU commented
Hmm, for some reason the `$ExpectError` annotations aren't respected, e.g.

> Error: ../test/fs.ts(22,41): error TS2345: Argument of type '"invalid encoding"' is not assignable to parameter of type 'WriteFileOptions'.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f48febf8d82336e03c3ccbe1052de14902522e23/types/node/test/fs.ts#L22

This seems to have been noted before: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40967 🤔 

ping @orta, @sandersn, @armanio123 any ideas on what could be going on here? I'm not really sure how to move forward with this 😅

2021-07-28 15:45 UTC, sandersn commented
Looking at the comment regex, it forbids trailing characters of any kind, even whitespace: 
`        const match = /^ \$Expect((Type (.*))|Error)$/.exec(commentMatch[1]);`

It looks like the non-working ExpectError has a trailing space.

Probably the regex should allow trailing whitespace, but removing the trailing space should work around that.

2021-07-29 10:34 UTC, LinusU commented
@sandersn 

> Does it work if you move it to the previous line?

Unfortunately not, I tried that as well 🤔

2021-08-03 11:59 UTC, LinusU commented
ping @sandersn if you have any input on how to move this forward that would be great 😅 

Potentially we could comment out the tests for now? 🤔

2021-08-03 14:52 UTC, SimonSchick commented
I think we should move forward yes, if you comment out the tests that's ok imo.

2021-08-03 15:20 UTC, SimonSchick approved these changes

2021-08-03 15:21 UTC, peterblazejewicz approved these changes

2021-08-03 15:22 UTC, peterblazejewicz commented
yes, let's move forward and revisit when it would start failing on next change

2021-08-04 08:50 UTC, LinusU commented
Ready to merge

🚀

2021-08-04 08:50 UTC, merged