express-session - restore indexer in SessionData to undo breaking changes until version bump
DefinitelyTyped/DefinitelyTyped pull request #54973
Opened 2021-08-05 22:12 UTC by rsimp

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
 [comment thread on breaking changes]

This PR is for adding back in the indexer in `Express.SessionData`, which was removed in 1.17.1 . The 1.17.1 patch is a breaking change and should therefore only be included in a major bump. This breaks semantic versioning for both 1.17 and 1.15. The indexer property has been included since the original typings in 2017. While removing it may improve typings, preserving semantic versioning should be a higher priority for projects that use this package. Removal can be done in a 2.x version either by divorcing the versioning of the types package from the`express-session`, or by waiting for a major revision.

As a workaround you can manually augment SessionData for better typings. By default anything added to session data will receive an `any` type as it always has.

Details mentioned in this [comment thread](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d1259ee31e6b17c31a5a86e27a0d12f3ec7c5a19#r44080605)

2021-08-07 21:31 UTC, peterblazejewicz reviewed
@rsimp This looks OK, the augmentaton would still work:
```ts

declare module 'express-session' {
    interface SessionData {
        firstName: string;
        lastName: string;
    }
}

app.use((req, res, next) => {
    const sess = req.session;
    if (!!sess.firstName) {
        sess.firstName = 'Bob';
        sess.lastName = 'Smith';
        res.end('Welcome back!');
    }
});
```
allowing to use terser implementation.
Please:
- remove/amend the interface comment, which is now misleading
- add/modify tests

2021-08-07 22:19 UTC, HoldYourWaffle requested changes
> While removing it may improve typings, preserving semantic versioning should be a higher priority for projects that use this package.

As the person that introduced this change, I **strongly** disagree with this idea. Semantic versioning is a _communication tool_, inaccurate typings is an _issue_.
[This comment](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46576#issuecomment-735465372) from the original PR touches upon DT versioning.

As for patch itself: I think this would be a terrible step in the wrong direction.
This patch (partially) destroys type-safety, typos now fly under the radar as `any` for example. I have talked about this before [over here](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d1259ee31e6b17c31a5a86e27a0d12f3ec7c5a19#r44218315).

<br>

Let me touch on the argumentation you provided in [this comment](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/d1259ee31e6b17c31a5a86e27a0d12f3ec7c5a19#r54473643):

> You can still get type safety through the same module augmentation you listed above.

This is not true. Let me illustrate this with a little example:
```ts
function feed(data: SessionData) {
    cookieMonster.feed(data.cokie); // oops, typo!
}
```

With this patch `SessionData.cokie` will be seen as `any`, which doesn't raise any red flags, even though it's an obvious mistake.

> Just to drive this home. If the express-session package managed it's own typings, this typings update would be a major version change for the entire project.

[Indeed](https://github.com/expressjs/session/pull/656).

> It may be a mistake, but it's been there since the original typings were added for 1.15.

You're saying it yourself, it was a *mistake*. Mistakes need to be fixed, [even if they cause inconvenience](https://xkcd.com/1172/), especially if it's due to _more accurate_ typing. Note that this is in line with TS's own [breaking change policy](https://github.com/microsoft/TypeScript-wiki/blob/main/Breaking-Changes.md).

> I think we either need to be mindful of this

Mindful yes, of course, but since the rewrite was already technically breaking anyway this seemed like the right moment to do it.

> or divorce the typing's version from the main package's

As far as I know this is not possible on DT.

> You can always remove it on the next major version change.

Which might never happen.

> I'd also like to point out that not all typescript projects use strict typing (...) defaulting to any makes the most sense until projects augment explicitly. Otherwise you need to augment to just switch over from javascript which is a very unusual pattern.

I want to stress this: _in theory_ I 100% agree with you. _Defaulting_ to `any`, but allowing type-safe users to override, would definitely be the best solution. Unfortunately this is not possible in TS.
If this PR were to be accepted, type-*unsafety* would be **forced** on **everyone**, with no way to undo it. The current situation causes minor inconvenience to those that want to paralyze the type-checker, but doesn't **force** it on anyone.

2021-08-08 21:06 UTC, peterblazejewicz commented
I think the intent behind this PR is just to remove the real burden of writing module augmentation, not to write beset TS implementation (who knows stuff like module augmentation? classes, interfaces, types, generics, enums, ok, but not module augmentation IMO). I didn't wrote that's fully type safe, I wrote this can still provide code hinting. This (proper code type safety) could be probably better done via generic type resolution, if provided, like in other libraries.

2021-08-09 23:38 UTC, rsimp commented
> As far as I know this is not possible on DT.

This explains so much. It seems to be known DT breaks from semver. I think I understand now why such a major change was made in a patch update.

> As the person that introduced this change, I strongly disagree with this idea. Semantic versioning is a communication tool, inaccurate typings is an issue.

While I now understand why a breaking change was made I think you may be taking semantic versioning a bit lightly. I had to track down an issue for my company due to a *patch* change, and only found the workaround in the comment section of a specific commit. Judging by the thread I'm not the only one. It probably affected a large number of people. The cost of breaking semver in a well used library can be enormous. That being said, this seems to be a problem with DT itself.

> I want to stress this: in theory I 100% agree with you. Defaulting to any, but allowing type-safe users to override, would definitely be the best solution. Unfortunately this is not possible in TS.
If this PR were to be accepted, type-unsafety would be forced on everyone, with no way to undo it. The current situation causes minor inconvenience to those that want to paralyze the type-checker, but doesn't force it on anyone.

I understand this point and probably why the change was made. I'm kind of on the fence now. I looked into generics too and its just not possible due to the interplay with `express` types.

Like @peterblazejewicz I now think the bigger issue is lack of good documentation. You can see from an issue on `express-session` [here](https://github.com/expressjs/session/issues/799) that even knowing about augmentation user's are continuing to struggle with it. Even worse the proposed solutions from that thread don't seem to grasp why they actually work. Augmentation doesn't work in non-module files and probably lots of people will try to add them into ambient declaration files where there may be no import/export statement. As is, I think this is being more disruptive than helpful. 

My suggestion: `SessionData` will not show up when hovering over the `session` property of a request (or any property for that matter). It has a great example but requires you to delve into the typings. We should move the example up to the comment section on `session`. We should also add that this augmentation ***must*** have at least one import/export statement in it do prevent re-declaring the entire module. Here's an example of what I mean:

![image](https://user-images.githubusercontent.com/3030100/128786660-d9e34550-a990-4daf-97b1-d9368b400a13.png)

2021-08-09 23:53 UTC, rsimp commented
> As far as I know this is not possible on DT.

This explains so much. It seems to be known DT breaks from semver. I think I understand now why such a major change was made in a patch update.

> As the person that introduced this change, I strongly disagree with this idea. Semantic versioning is a communication tool, inaccurate typings is an issue.

While I now understand why a breaking change was made I think you may be taking semantic versioning a bit lightly. I had to track down an issue for my company due to a *patch* change, and only found the workaround in the comment section of a specific commit. Judging by the thread I'm not the only one. It probably affected a large number of people. The cost of breaking semver in a well used library can be enormous. That being said, this seems to be a problem with DT itself.

> I want to stress this: in theory I 100% agree with you. Defaulting to any, but allowing type-safe users to override, would definitely be the best solution. Unfortunately this is not possible in TS.
If this PR were to be accepted, type-unsafety would be forced on everyone, with no way to undo it. The current situation causes minor inconvenience to those that want to paralyze the type-checker, but doesn't force it on anyone.

I understand this point and probably why the change was made. I'm kind of on the fence now. I looked into generics too and its just not possible due to the interplay with `express` types.

Like @peterblazejewicz I now think the bigger issue is lack of good documentation. You can see from an issue on `express-session` [here](https://github.com/expressjs/session/issues/799) that even knowing about augmentation user's are continuing to struggle with it. Even worse the proposed solutions from that thread don't seem to grasp why they actually work. Augmentation doesn't work in non-module files and probably lots of people will try to add them into ambient declaration files where there may be no import/export statement. As is, I think this is being more disruptive than helpful. 

My suggestion: `SessionData` will not show up when hovering over the `session` property of a request (or any property for that matter). It has a great example but requires you to delve into the typings. We should move the example up to the comment section on `session`. We should also add that this augmentation ***must*** have at least one import/export statement in it do prevent re-declaring the entire module. Here's an example of what I mean:

![image](https://user-images.githubusercontent.com/3030100/128788364-ba4a1ec3-4ae9-4055-8edf-9c435741885f.png)

2021-08-10 00:05 UTC, rsimp commented
> As far as I know this is not possible on DT.

This explains so much. It seems to be known DT breaks from semver. I think I understand now why such a major change was made in a patch update.

> As the person that introduced this change, I strongly disagree with this idea. Semantic versioning is a communication tool, inaccurate typings is an issue.

While I now understand why a breaking change was made I think you may be taking semantic versioning a bit lightly. I had to track down an issue for my company due to a *patch* change, and only found the workaround in the comment section of a specific commit. Judging by the thread I'm not the only one. It probably affected a large number of people. The cost of breaking semver in a well used library can be enormous. That being said, this seems to be a problem with DT itself.

> I want to stress this: in theory I 100% agree with you. Defaulting to any, but allowing type-safe users to override, would definitely be the best solution. Unfortunately this is not possible in TS.
If this PR were to be accepted, type-unsafety would be forced on everyone, with no way to undo it. The current situation causes minor inconvenience to those that want to paralyze the type-checker, but doesn't force it on anyone.

I understand this point and probably why the change was made. I'm kind of on the fence now. I looked into generics too and its just not possible due to the interplay with `express` types.

I now think the bigger issue is lack of good documentation. You can see from an issue on `express-session` [here](https://github.com/expressjs/session/issues/799) that even knowing about augmentation user's are continuing to struggle with it. Even worse the proposed solutions from that thread don't seem to grasp why they actually work. Augmentation doesn't work in non-module files and probably lots of people will try to add them into ambient declaration files where there may be no import/export statements. As is, I think this is being more disruptive than helpful. 

A suggestion: `SessionData` will not show up when hovering over the `session` property of a request (or any property for that matter). It has a great example but requires you to delve into the typings to find it. We should move the example up to the comment section on `session`. We should also add that augmentations ***must*** be in a file with at least one import/export statement in it to prevent re-declaring the entire module. Here's an example of what I mean:

![image](https://user-images.githubusercontent.com/3030100/128789045-e5159c48-c4fa-4381-beae-aef2cb8caf8a.png)

@peterblazejewicz Does this work for you, or would you rather just add the indexer back in with the proposed changes?

2021-08-10 00:13 UTC, rsimp commented
In addition to jsdoc comment changes we should include a markdown file in the repo going over the same points. The more documentation the better IMO. Without good instruction we're better off going with the `any` index signature.

2021-08-10 10:41 UTC, peterblazejewicz commented
I'd accept whatever you folks decide. My point was, I'd rather see entry barrier lowered, say like in Fastify, back to 'good enough':
https://github.com/fastify/session

2021-08-22 16:42 UTC, HoldYourWaffle commented
First of all: sorry for my terribly late response!

Secondly, I want to give a big compliment @rsimp for being able to change their views based on new information. It seems that not many people are able to do that nowadays in this community, it's good to see that there's still hope :)
In that light I'd also like to apologize for my slightly strong-sided wording, I've seen so much baseless shenanigans with these typings that I kind of overshot myself....

> I looked into generics too and its just not possible due to the interplay with express types.

Yep that's exactly what I experienced as well. It would've been a nice solution, but unfortunately TS is not equipped for this :(

> I now think the bigger issue is lack of good documentation.

I 100% agree, there's definitely room for improvement there. I don't want to deny that this system is "more complicated" or "less intuitive" than an `any` index signature, but I think documentation is a much better solution than crippling typesafety.

> Even worse the proposed solutions from that thread don't seem to grasp why they actually work.

To be fair, TS's documentation on this subject is pretty sparse and IDE support can be "lacking".

> We should move the example up to the comment section on session.

That's a really really good idea, I think that'd be a perfect solution.

> We should also add that augmentations must be in a file with at least one import/export statement in it to prevent re-declaring the entire module. Here's an example of what I mean:

I'm not sure this example is entirely "complete", my augmentations look different if I remember correctly. I can't check it right now, but I'll try to get back to this tomorrow :)

2021-09-22 18:57 UTC, closed without merging