[office-js, office-js-preview] Recommend Excel.Binding from Office.Binding
DefinitelyTyped/DefinitelyTyped pull request #54994
Opened 2021-08-06 22:28 UTC by AlexJerabek

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/understanding-the-javascript-api-for-office?view=excel-js-preview#api-models
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-08-06 22:31 UTC, Rick-Kirkham approved these changes

2021-08-09 15:46 UTC, ElizabethSamuel-MSFT requested changes

2021-08-09 15:46 UTC, ElizabethSamuel-MSFT commented on types/office-js-preview/index.d.ts
> +    * **Hosts**: Word, Excel (depreciated, use {@link https://docs.microsoft.com/javascript/api/excel/excel.binding?view=excel-js-preview | Excel.Binding} instead)
```suggestion
    * **Hosts**: Word, Excel (deprecated, use {@link https://docs.microsoft.com/javascript/api/excel/excel.binding?view=excel-js-preview | Excel.Binding} instead)
```

2021-08-09 15:46 UTC, ElizabethSamuel-MSFT commented on types/office-js/index.d.ts
> +    * **Hosts**: Word, Excel (depreciated, use {@link https://docs.microsoft.com/javascript/api/excel/excel.binding?view=excel-js-preview | Excel.Binding} instead)
```suggestion
    * **Hosts**: Word, Excel (deprecated, use {@link https://docs.microsoft.com/javascript/api/excel/excel.binding?view=excel-js-preview | Excel.Binding} instead)
```

2021-08-09 15:56 UTC, ElizabethSamuel-MSFT approved these changes

2021-08-09 18:22 UTC, Rick-Kirkham approved these changes

2021-08-12 22:03 UTC, merged