Making arguments optional
DefinitelyTyped/DefinitelyTyped pull request #55010
Opened 2021-08-08 15:24 UTC by akrizs

With never versions of the AWS lambda i noticed that VSCode is really wanting me to input that callback method when bundling and using function by import between lambdas.
and since the API states that perhaps the 2 last arguments are often omitted and not needed i propose that we make those arguments to the Handler type optional.

guess maby this is auto generated from something but i'll post the proposal and see if it goes through! best regards!

Did the pull request through github UI so no tests ran but i guess it shouldn't change much other than not throw errors if the arguments are not provided.

Please fill in this template.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-08-09 00:07 UTC, simonbuchan requested changes
Sigh. We've gotten this about three times now, probably worth putting a comment above the handler to not do this.

No, those *arguments* are not optional: AWS will always give them to you. The *parameters* are optional, you can always ignore them in an implementing handler. Doing this breaks every existing handler using those arguments as they must now be tested for being undefined / defaulted (hence the broken tests)

If you have tests against the handler, you have plenty of options including just casting null, but my favorite is a Proxy that throws if you use it.

2021-08-09 05:55 UTC, akrizs commented
> Sigh. We've gotten this about three times now, probably worth putting a comment above the handler to not do this.
> 
> No, those _arguments_ are not optional: AWS will always give them to you. The _parameters_ are optional, you can always ignore them in an implementing handler. Doing this breaks every existing handler using those arguments as they must now be tested for being undefined / defaulted (hence the broken tests)
> 
> If you have tests against the handler, you have plenty of options including just casting null, but my favorite is a Proxy that throws if you use it.

The parameters are not optional if you are building something where you include the method in an import in a bigger system and you want to make it a separate aws lambda exposed with api gateway or other services, i think you guys should consider this, i know the tests failed and as i said i did the changes + pull request via the github web interface, they seemed so simple.

Best regards.

2021-08-09 07:56 UTC, simonbuchan commented
@akrizs Simple changes that are wrong should fail tests - this should hardly be surprising, that's why we have tests!

 Please consider the previous rejected PRs (probably all of them, but I only did a quick search):

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38828
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30820
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25385

It's already been considered and rejected multiple times before. Changing the `Handler<>` type is *extremely* sensitive: any such change is very likely to be a breaking change (that should require a major version change) for pretty much everybody using this package. That's why pretty much every test fails with this change.

It's quite possible that there's a much nicer implementation for handler types, but it would have to be carefully approached and designed to suit primarily the intended use case: verifying that the handler matches how AWS will call it.

Now, it sounds like you have some situation like this:

```ts
// foo.ts

export const fooHandler: APIGatewayProxyHandler = async (event) { ... };

// some_foo_user.ts

import { fooHandler } from "./foo.ts";

export function bar() {
  fooHandler({ ... });
}
```

I have no idea why you would do this, but programming can get you into weird situations, so sure (previously the argument was for writing tests).

If you want to do something like this, then you could try either:

```ts
export async function fooHandler(event: APIGatewayProxyEvent) Promise<APIGaweayProxyResult> { ... }
```

or, if you want the validation that it is assignable to a Handler type

```ts
export const fooHandler: APIGatewayProxyHandler = foo;

// preferably some other file...
export async function foo(event: APIGatewayProxyEvent) Promise<APIGaweayProxyResult> { ... }
```

2021-08-10 09:17 UTC, akrizs commented
> @akrizs Simple changes that are wrong should fail tests - this should hardly be surprising, that's why we have tests!
> Now, it sounds like you have some situation like this:
> 
> ```ts
> // foo.ts
> 
> export const fooHandler: APIGatewayProxyHandler = async (event) { ... };
> 
> // some_foo_user.ts
> 
> import { fooHandler } from "./foo.ts";
> 
> export function bar() {
>   fooHandler({ ... });
> }
> ```
> 
> I have no idea why you would do this, but programming can get you into weird situations, so sure (previously the argument was for writing tests).
> 
> If you want to do something like this, then you could try either:
> 
> ```ts
> export async function fooHandler(event: APIGatewayProxyEvent) Promise<APIGaweayProxyResult> { ... }
> ```

Yeah you are right, i should just drop the typing of the function type or make it like that,
sometimes you write a code that has this one function that is beeing used inside the entire code and you want to expose that function as its own API call for example, thats why you do this, but obviously the idea with typing is so that you can avoid mistakes and it helps ALOT when writing with tools like VSCode that can just tell you what you need to specify when you are writing it.

Thanks for the back & forth!
Best regards.

2021-08-10 09:17 UTC, closed without merging