[node] Add new v8 feature: relative indexing method
DefinitelyTyped/DefinitelyTyped pull request #55061
Opened 2021-08-10 18:11 UTC by Semigradsky

16.6.0 released

https://github.com/nodejs/node/releases/tag/v16.6.0

- v8: introduces the new `Array.prototype.at` method (also on Typed Arrays and strings)

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-08-10 19:57 UTC, SimonSchick commented
I'm not sure we can add a dependency like this to `@types/node`.
I added partial support for this in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55057 (only strings, array, Uint8Array), we should probably augment the node typings instead?

2021-08-10 21:35 UTC, amcasey requested changes
Please work with @SimonSchick to find an appropriate approach.

2021-08-11 08:06 UTC, Semigradsky commented
@SimonSchick so will you add full support `TypedArray#at` to your PR? In this case this PR can be closed.
I just thought that adding esnext typings to separate package can improve readability and make changing Node.js typings slightly easy.

2021-08-11 10:31 UTC, yoursunny commented
I wonder why `TypedArray#at` should be in DefinitelyTyped?
It's part of the JavaScript language, which is usually added to TypeScript itself as a *target*.

2021-08-11 14:27 UTC, Semigradsky commented
@yoursunny `TypedArray#at` as `Array#at` or `String#at` will be added to lib.d.ts in some day (https://github.com/microsoft/TypeScript/issues/40695). But what about users which can't use the last TypeScript for any reason?

2021-08-11 14:29 UTC, SimonSchick commented
@yoursunny DT needs to still support TS 3.6 (soon 3.7), we sadly can't always rely on bleeding edge libs be available.

2021-08-11 15:06 UTC, yoursunny commented
Users who need `TypedArray#at` on older TS can manually import `@types/proposal-relative-indexing-method`.
There's no need to include it in `@types/node`.

2021-08-11 15:23 UTC, SimonSchick commented
@yoursunny this seems pretty inconvenient to users, how do we explain to them that, in order to use modern JS features on an older TS version, they must to install some 'proposal-' package?

I think for convenience and simplicities sake the typings should be shipped in node.

2021-08-12 05:13 UTC, closed without merging