Fix @types/google.maps possibility to use an array for the property country in GeocoderComponentRestrictions
DefinitelyTyped/DefinitelyTyped pull request #55124
Opened 2021-08-13 04:09 UTC by alexlopezit

[Google Maps component restrictions](https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#ComponentRestrictions) `country` allows either a string or an array of strings 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/maps/documentation/javascript/reference/places-autocomplete-service#ComponentRestrictions
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-08-14 00:44 UTC, amcasey commented
LGTM, but let's give the owners some time to weigh in.

2021-08-16 16:35 UTC, jpoehnelt commented
These are autogenerated types and this should not be merged. 

>// To report an issue with these types, please open a support ticket at:
// https://issuetracker.google.com/savedsearches/558438

Please link back here when done.

2021-08-16 16:37 UTC, jpoehnelt requested changes
File bug at https://issuetracker.google.com/savedsearches/558438/

2021-08-16 16:46 UTC, jpoehnelt commented
This also doesn't work.

> <a class='gotoLine' href='#"InvalidValueError: in property componentRestrictions: in property country: not a string"'>"InvalidValueError: in property componentRestrictions: in property country: not a string"</a>

https://jsfiddle.net/xp30zbnf/

2021-08-17 11:20 UTC, alexlopezit commented
You are right @jpoehnelt, will file a bug to the link provided. Thanks

2021-08-17 11:21 UTC, closed without merging

2021-08-17 12:35 UTC, alexlopezit commented
Turns out I was using the `google.maps.places.AutocompleteService` `getPlacePredictions` wich does support an array for countries and was just using the wrong type, the interface `google.maps.places.ComponentRestrictions` has the correct types for country.

Thanks again @jpoehnelt