📉 Improve DOMSerializer (prosemirror-model) typing
DefinitelyTyped/DefinitelyTyped pull request #55158
Opened 2021-08-16 07:54 UTC by castroCrea

Check the file DOM serializer class here https://github.com/ProseMirror/prosemirror-model/blob/master/src/to_dom.js

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-08-16 08:23 UTC, castroCrea commented on types/prosemirror-model/index.d.ts
> +    serializeFragment(fragment: Fragment<S>, options?: { [key: string]: any }, target?: string): DocumentFragment;
```suggestion
    serializeFragment(fragment: Fragment<S>, options?: { [key: string]: any }, target?: ProsemirrorNode<S>): DocumentFragment;
```

2021-08-17 02:06 UTC, AnthonyWeston approved these changes
The added types aren't part of the public API, which is documented [here](https://prosemirror.net/docs/ref/). I would recommend opening an issue/PR to document these types in the project itself before making any changes here.

2021-08-17 02:06 UTC, AnthonyWeston commented on types/prosemirror-model/index.d.ts
> +    serializeFragment(fragment: Fragment<S>, options?: { [key: string]: any }, target?: ProsemirrorNode<S>): DocumentFragment;
It looks like `target` should be a [DocumentFragment](https://prosemirror.net/docs/ref/#model.DOMSerializer.serializeFragment), but it isn't part of the public API. See https://prosemirror.net/docs/ref/#model.DOMSerializer.serializeFragment

2021-08-17 02:06 UTC, AnthonyWeston commented on types/prosemirror-model/index.d.ts
> +    serializeMark(mark?: Mark<S>, inline?: boolean, options?: { [key: string]: any }): { dom: Node; contentDOM?: Node | null | undefined };
`serializeMark` and `serializeNodeInner` are not part of the public API.

2021-08-17 02:12 UTC, AnthonyWeston requested changes
The added types are not part of the public API.

2021-09-17 06:53 UTC, closed without merging