[git-username] Bugfix: Allow multiple args
DefinitelyTyped/DefinitelyTyped pull request #55207
Opened 2021-08-17 22:11 UTC by joshuaharry

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
See https://github.com/jonschlinkert/git-username/blob/3baff113f79d62bc779f540ae5f8dfc825dd1fa7/index.js#L13 and https://github.com/jonschlinkert/git-username/blob/3baff113f79d62bc779f540ae5f8dfc825dd1fa7/test.js#L28 and

2021-08-18 16:32 UTC, BendingBender requested changes

2021-08-18 16:32 UTC, BendingBender commented on types/git-username/git-username-tests.ts
> +username({ strict: true }); // $ExpectType string | null
This test is not correct, when `strict` is set to `true` the function never returns `null`:
```suggestion
username({ strict: true }); // $ExpectType string
```

2021-08-18 16:32 UTC, BendingBender commented on types/git-username/index.d.ts
> +declare function gitUsername(cwd: string, options?: gitUsername.StrictOptions): string;
The correct typings for this should never return `null` when `strict` is set to `true`. To achieve this, the typings should look something like the following:

```suggestion
declare function gitUsername(options?: gitUsername.BaseOptions): string | null;
declare function gitUsername(cwd: string): string | null;
declare function gitUsername(cwd: string, options: gitUsername.StrictOptions): string;
// tslint:disable-next-line unified-signatures
declare function gitUsername(cwd: string, options: gitUsername.BaseOptions): string | null;
```

2021-08-18 16:50 UTC, BendingBender requested changes

2021-08-18 16:50 UTC, BendingBender commented on types/git-username/index.d.ts
> +declare function gitUsername(cwd: string, options?: gitUsername.StrictOptions): string;
I think we can get rid of all of this `string | null` debacle. This function can always return a `null` independent of the value of the `strict` option. So this file should actually look something like this:

```ts
declare function gitUsername(cwd?: string, options?: gitUsername.BasicOptions): string | null;
declare function gitUsername(options: gitUsername.FullOptions): string | null;

declare namespace gitUsername {
    interface BasicOptions {
        strict?: boolean;
    }

    interface FullOptions extends BasicOptions {
        cwd?: string;
    }
}
```

2021-08-18 16:50 UTC, BendingBender commented on types/git-username/git-username-tests.ts
> +username('some-path', { strict: true }); // $ExpectType string | null
Similarly to the changes in the `index.ts`, the tests should look something like this:
```ts
import username = require('git-username');

// test type exports
type BasicOptions = username.BasicOptions;
type FullOptions = username.FullOptions;

username(); // $ExpectType string | null
username('some/path'); // $ExpectType string | null
username({ cwd: 'some/path' }); // $ExpectType string | null
username({ strict: true }); // $ExpectType string | null
username('some-path', { strict: true }); // $ExpectType string | null
username('some-path', { cwd: 'some/path' }); // $ExpectError
```

2021-08-21 19:17 UTC, joshuaharry commented
@BendingBender Thank you for the suggestions!

2021-08-23 19:22 UTC, BendingBender approved these changes

2021-08-24 01:01 UTC, joshuaharry commented
Ready to merge

2021-08-24 01:02 UTC, merged