Make `flags` optional in `fs.open` in node
DefinitelyTyped/DefinitelyTyped pull request #55366
Opened 2021-08-25 03:11 UTC by zwhitchcox

Flags actually has a default of 'r' in `fsPromises.open`, meaning it should be optional in typescript

Please fill in this template.

- [ *] Use a meaningful title for the pull request. Include the name of the package modified.
- [ *] Test the change in your own code. (Compile and run.)
- [ *] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ *] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ *] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ *] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ *] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ *] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ *] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [* ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [* ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ *] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ *] Provide a URL to documentation or source code which provides context for the suggested changes: It is actually documented in the source code, right above the change.
- [ *] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-08-25 05:07 UTC, SimonSchick requested changes
You didn't fill out the template correctly but this change is correct, pls add a smol test.

2021-08-25 06:34 UTC, SimonSchick commented
Also please apply the same of the non-promise `open` definition.

2021-09-20 22:31 UTC, zwhitchcox commented
I can't figure out what the error:

```
> definitely-typed@0.0.3 lint
> dtslint types "node"

AssertionError [ERR_ASSERTION]: Expected "actual" to be strictly unequal to: -1
    at next (/home/zwhitchcox/dev/DefinitelyTyped/node_modules/dtslint/bin/index.js:195:12)
    at Array.map (<anonymous>)
    at /home/zwhitchcox/dev/DefinitelyTyped/node_modules/dtslint/bin/index.js:167:92
    at Generator.next (<anonymous>)
    at fulfilled (/home/zwhitchcox/dev/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```

means

2021-09-21 06:40 UTC, SimonSchick requested changes

2021-09-21 06:40 UTC, SimonSchick commented on types/node/test/fs.ts
> -    const handle: FileHandle = await openAsync('test', 'r');
That's not a good test, please add a test case rather than altering an existing line.

2021-10-22 06:53 UTC, closed without merging