Removed most of my code ownership
DefinitelyTyped/DefinitelyTyped pull request #55383
Opened 2021-08-25 17:08 UTC by JoshuaKGoldberg

Apologies for not using the template 😄 . I get pinged on discussions, issues, and PRs for these packages but I either don't use them anymore or don't have context+time to be of use.

2021-08-25 20:54 UTC, peterblazejewicz requested changes
Please revert changes in `.github/CODEOWNERS`, it's generated file.
Removing from headers is enough

2021-08-27 08:03 UTC, peterblazejewicz approved these changes
LGTM!
@JoshuaKGoldberg thanks for your contributions!

2021-09-20 15:39 UTC, JoshuaKGoldberg commented
Lol...

2021-09-20 15:48 UTC, peterblazejewicz commented on types/jest-environment-puppeteer/index.d.ts
> +// Definitions by: Ifiok Jr. <https://github.com/ifiokjr>
can you revert this file change? Package is outdated and blocks CI

2021-09-20 21:11 UTC, peterblazejewicz approved these changes

2021-09-21 01:36 UTC, JoshuaKGoldberg commented
Ready to merge

2021-09-21 01:37 UTC, merged