@types/chromecast-caf-receiver -- Add getStartAbsoluteTime() to Chromecast receiver
DefinitelyTyped/DefinitelyTyped pull request #55408
Opened 2021-08-26 18:17 UTC by nrcrast

This adds a missing method from the Chromecast Receiver PlayerManager

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests). 
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.PlayerManager#getStartAbsoluteTime
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-08-29 22:50 UTC, domdomegg approved these changes
LGTM based on https://developers.google.com/cast/docs/reference/web_receiver/cast.framework.PlayerManager#getStartAbsoluteTime

2021-08-30 07:33 UTC, marcoreni approved these changes
LGTM

2021-08-30 07:39 UTC, Serabe approved these changes

2021-08-31 23:03 UTC, marcoreni requested changes
Hey @nrcrast , the change included in this PR was released in 6.0.5 because it was included in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55135 , which had been waiting to be merged for a while. I think this can be closed.

2021-09-02 14:41 UTC, closed without merging