[gulp inject] Add quiet option to config
DefinitelyTyped/DefinitelyTyped pull request #55476
Opened 2021-08-30 02:25 UTC by joshuaharry

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
See https://github.com/klei/gulp-inject/blame/master/README.md#L871 and https://github.com/klei/gulp-inject/blob/c206c9ee869cefbb6ebde5cc12e2c5eb1194dd0e/src/inject/inject_test.js#L511

2021-09-17 23:10 UTC, andrewbranch requested changes

2021-09-17 23:10 UTC, andrewbranch commented on types/gulp-inject/index.d.ts
> +	quiet?: boolean | undefined;
Indentation looks off?

2021-09-17 23:11 UTC, andrewbranch commented on types/gulp-inject/index.d.ts
> +	quiet?: boolean | undefined;
It's a tab in a spaces world

2021-09-20 23:41 UTC, andrewbranch approved these changes

2021-09-26 14:22 UTC, joshuaharry commented
Ready to merge

2021-09-26 14:22 UTC, merged