Add test case for previous pull request on node-forge
DefinitelyTyped/DefinitelyTyped pull request #55485
Opened 2021-08-30 10:00 UTC by beenotung

Add test case for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55133

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

2021-09-10 15:42 UTC, joeflateau approved these changes

2021-09-20 23:23 UTC, andersk requested changes

2021-09-20 23:23 UTC, andersk commented on types/node-forge/node-forge-tests.ts
> +            throw new Error('return result and callback data not match');
This test does not pass.

2021-09-20 23:29 UTC, andersk approved these changes

2021-09-20 23:29 UTC, andersk commented on types/node-forge/node-forge-tests.ts
> +            throw new Error('return result and callback data not match');
I see…you’re adding this test in one commit and deleting it in the next? I guess we squash-merge here, so I won’t be picky about the commit discipline.

2021-09-20 23:30 UTC, andersk commented
Ready to merge

2021-09-20 23:30 UTC, merged