blueimp-md5 fix error TS2497
DefinitelyTyped/DefinitelyTyped pull request #55672
Opened 2021-09-09 09:35 UTC by coddwrench

For import `import * as md5 from "blueimp-md5";` or `import { md5 } from "blueimp-md5";` error occurs `This module can only be referenced with ECMAScript imports/exports by turning on the 'esModuleInterop' flag and referencing its default export.`.
Because `export as namespace md5;`  incorrect module declaration.  As a solution, replace this code with an empty declaration.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-09-09 19:29 UTC, peterblazejewicz commented
Should you use:
```ts
import md5 from "blueimp-md5";
```
https://github.com/blueimp/JavaScript-MD5/issues/38
(this package has no additional alias export to support ES6 module directly).

"export as namespace md" is not to support ESM exports, it's here for global script usage (as this is proper UMD type of module), so this code needs this to work in browser via script (no module support, no imports):
```ts
md5("Hello World!")
```

2021-09-27 20:51 UTC, sandersn requested changes
Looking at blueimp-md5's source, its commonjs export is a single object. The error message is correct in this case, so there's no reason to silence it.

2021-10-21 12:45 UTC, coddwrench commented
Ok. The error message is correct in this case, so there's no reason to silence it.

2021-10-21 12:49 UTC, closed without merging

2023-03-03 15:41 UTC, OliverJAsh commented
More info here: https://github.com/microsoft/TypeScript/issues/36026