Byte size
DefinitelyTyped/DefinitelyTyped pull request #55675
Opened 2021-09-09 12:47 UTC by lntel

Please fill in this template.

- [✓] Use a meaningful title for the pull request. Include the name of the package modified.
- [✓] Test the change in your own code. (Compile and run.)
- [✓] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [✓] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [✓] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [✓] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [✓] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [✓] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [✓] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [✓] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [✓] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [✓] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2021-09-09 14:02 UTC, 75lb requested changes
Hi, thanks for the PR - first impressions attached..

2021-09-09 14:02 UTC, 75lb commented on types/byte-size/index.d.ts
> +    units: byteSizeUnit | string;
Remove the `| string` as it makes any string value valid here

2021-09-09 14:02 UTC, 75lb commented on types/byte-size/index.d.ts
> +    toStringFn: () => void;
the `toStringFn` should return a `string`

2021-09-09 20:42 UTC, 75lb requested changes
I checked it some more and made more changes, this is what I ended up with.. does that look ok to you? 

```
export interface byteSizeOptions {
    precision?: number;
    units?: string;
    customUnits?: object;
    toStringFn?: () => string;
    locale?: string | string[];
}

export interface ByteSizeResult {
    value: string;
    unit: string;
    long: string;
    toString: () => string;
}

function byteSize(bytes: number, options?: byteSizeOptions): ByteSizeResult;    

namespace byteSize {
    export function defaultOptions (options: byteSizeOptions): void;
}

export default byteSize;
```

2021-09-10 12:17 UTC, sam-eah commented
Hello, I may be wrong but shouldn't the decleration file look something like that ?
```ts
declare module "byte-size"{
    export interface byteSizeOptions {
        customUnits?: object;
        locale?: string | string[];
        precision?: number;
        toStringFn?: () => string;
        units?: string;
    }
    
    export interface ByteSizeResult {
        long: string;
        toString: () => string;
        unit: string;
        value: string;
    }
    
    function byteSize(bytes: number, options?: byteSizeOptions): ByteSizeResult;    
    
    namespace byteSize {
        export function defaultOptions (options: byteSizeOptions): void;
    }
    
    export default byteSize;
}
```

That's what I'm currently using for my project, it's working just fine!

2021-09-10 21:24 UTC, 75lb commented
@sam-eah Yes, that is exactly how i'm using it locally too - with the types wrapped in `declare module "byte-size"`.. however, does it need to be written this way as a DT package? I'm not sure.. I checked other packages in the DT repo - some use `declare module` some don't..

2021-09-12 10:54 UTC, lntel commented
Yeah I did start it like that but then read somewhere that with DT it's not necessary. I could be wrong though.

2021-09-13 08:20 UTC, 75lb commented
> Yeah I did start it like that but then read somewhere that with DT it's not necessary. I could be wrong though.

Cool, once you've double-checked whether or not it's required could you also check the new types posted in the PR review? These types also include `byteSize.defaultOptions` and rename the result from `ByteSizeObject` to `ByteSizeResult`. 

Almost there, now..

2021-09-13 10:33 UTC, lntel commented
> > Yeah I did start it like that but then read somewhere that with DT it's not necessary. I could be wrong though.
> 
> Cool, once you've double-checked whether or not it's required could you also check the new types posted in the PR review? These types also include `byteSize.defaultOptions` and rename the result from `ByteSizeObject` to `ByteSizeResult`.
> 
> Almost there, now..

So with DT it's not necessary to actually declare the module. I've made a couple changes too so give that a check.

2021-09-13 15:36 UTC, 75lb requested changes
I'm being as patient as possible but this PR has been broken from the start and remains broken, despite me giving you the complete solution in my previous review..

2021-09-13 15:36 UTC, 75lb commented on types/byte-size/index.d.ts
> +export type byteSizeUnit = 'metric' | 'iec' | 'metric_octet' | 'iec_octet';
I removed this line in my previous PR as the units is customisable..

2021-09-13 15:36 UTC, 75lb commented on types/byte-size/index.d.ts
> +    units?: byteSizeUnit;
i set this to `string` in my previous review.

2021-09-13 15:36 UTC, 75lb commented on types/byte-size/index.d.ts
> +    long: string;
I added `toString` in my previous review..

2021-09-13 15:36 UTC, 75lb commented on types/byte-size/index.d.ts
> +export function defaultOptions(options: byteSizeOptions): void;
I gave you the correct solution for this method in my previous review..

2021-09-13 15:36 UTC, 75lb commented on types/byte-size/byte-size-tests.ts
> +byteSize(12, {
The tests are inadequate and don't cover all methods, e.g. `byteSize.defaultOptions`..

2021-09-13 15:39 UTC, 75lb commented
The types file throws errors when I view it in VSCode.. 

<img width="808" alt="Screenshot 2021-09-13 at 16 31 51" src="https://user-images.githubusercontent.com/1247980/133113859-dab39358-2753-4ba4-a3f2-eecc9dc65d7b.png">

2021-09-13 15:59 UTC, lntel commented
With the current solution you'd have to do the following 
![image](https://user-images.githubusercontent.com/37447006/133117331-6fc8b435-88eb-4098-9ab3-815832d0e893.png)

And with the fix that you provided, there's an error as you cannot use namespace.

2021-09-13 16:08 UTC, 75lb commented
I don't see any compile errors in VSCode or when I compile it on the command line.. 

<img width="789" alt="Screenshot 2021-09-13 at 17 05 08" src="https://user-images.githubusercontent.com/1247980/133118438-a5d9380f-868a-4964-8adf-10bb69dae77e.png">

2021-09-13 16:08 UTC, 75lb commented
> And with the fix that you provided, there's an error as you cannot use namespace.

I don't see an error.. the fix uses [Declaration Merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html).

2021-09-13 16:08 UTC, lntel commented
But have you ran `npm test byte-size`? DT is failing it

2021-09-13 16:10 UTC, lntel commented
![image](https://user-images.githubusercontent.com/37447006/133119201-6594d79f-45b3-4210-923b-5d1af16e60b1.png)
This is my test with the code you wrote

2021-09-13 16:13 UTC, 75lb commented
> This is my test with the code you wrote

So it needs to be within a `declare module` then?

```
declare module "byte-size"{
    export interface byteSizeOptions {
        customUnits?: object;
        locale?: string | string[];
        precision?: number;
        toStringFn?: () => string;
        units?: string;
    }
    
    export interface ByteSizeResult {
        long: string;
        toString: () => string;
        unit: string;
        value: string;
    }
    
    function byteSize(bytes: number, options?: byteSizeOptions): ByteSizeResult;    
    
    namespace byteSize {
        export function defaultOptions (options: byteSizeOptions): void;
    }
    
    export default byteSize;
}
```

2021-09-13 16:18 UTC, lntel commented
Okay it was a strange fix, the module declaration didn't work so I had to find a workaround. Check it out now. My apologies.

2021-09-13 18:30 UTC, peterblazejewicz commented on types/byte-size/index.d.ts
> +export interface byteSizeOptions {
```suggestion
export interface ByteSizeOptions {
```
IMO better,

2021-09-13 18:35 UTC, peterblazejewicz commented
This is OK and working, just this bit with non-standard naming convention, thx!

2021-09-13 18:45 UTC, 75lb commented
Thanks.. i have finished my checks too - once the naming convention is fixed our work here is done..

2021-09-14 14:25 UTC, 75lb approved these changes

2021-09-14 14:26 UTC, 75lb commented
thanks everyone 👍

2021-09-14 19:22 UTC, peterblazejewicz approved these changes
LGTM!
@lntel thx!

2021-09-14 20:28 UTC, lntel commented
Ready to merge

2021-09-14 20:28 UTC, merged