added types for '@nick-thompson/elementary'
DefinitelyTyped/DefinitelyTyped pull request #55762
Opened 2021-09-14 11:44 UTC by Hrle97

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

Elementary is a runtime for JS similar to NodeJS. It can run anything that can compile to JS and it exposes some global variables that need typings. The package '@nick-thompson/elementary' wraps up this global variable nicely and provides extra functionality to the runtime.

TSLint has some exceptions to make the code more readable. There is also redundant JSDoc because some function types are hard to represent with just TypeScript.
package.json contains some "unwanted" fields to make testing this runtime easier.
There is a .editorconfig in the folder to limit lines to 80 which makes development a bit easier for me. I don't know if this is allowed.

2021-09-14 16:11 UTC, sandersn requested changes

2021-09-14 16:11 UTC, sandersn commented on types/nick-thompson__elementary/package.json
> +    },
DT infers `@types/*` dependencies, so you don't have to do it yourself.

2021-09-14 16:11 UTC, sandersn commented on types/nick-thompson__elementary/package.json
> +{
This file is not needed and should be removed. I'll provide additional details.

2021-09-14 16:11 UTC, sandersn commented on types/nick-thompson__elementary/package.json
> +    },
devDeps are not allowed in DT package.jsons. Also, I don't see any of these dependencies used in the code.

2021-09-14 16:11 UTC, sandersn commented on types/nick-thompson__elementary/package.json
> +    }
DT packages should only use DT's test infrastructure in the top-level package.json.

2021-09-15 17:09 UTC, sandersn commented
The package.json is not needed, given the way that DT infrastructure works. The `@types` package publisher will generate a correct package.json just from the .d.ts files.

2021-09-15 17:13 UTC, Hrle97 commented
> The package.json is not needed, given the way that DT infrastructure works. The `@types` package publisher will generate a correct package.json just from the .d.ts files.

I removed it in recent commits, so it shouldn't be there anymore.
The commit where I commented, "fix package.json" I fixed the root package.json because I added an unnecessary dependency there by accident.

2021-09-15 22:15 UTC, sandersn approved these changes

2021-09-15 22:16 UTC, sandersn commented
You're right, I mis-read the diff.

2021-09-16 08:42 UTC, Hrle97 commented
Ready to merge

2021-09-16 08:43 UTC, merged