Add signing_redirect_url to SignatureRequestRequestOptions
DefinitelyTyped/DefinitelyTyped pull request #56005
Opened 2021-09-27 07:12 UTC by vinassefranche

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - As per the api [documentation](https://app.hellosign.com/api/reference#send_signature_request) `signing_redirect_url` is a valid parameter
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-09-27 22:15 UTC, dvdprrsh requested changes

2021-09-28 06:55 UTC, vinassefranche commented on types/hellosign-sdk/index.d.ts
> +        signing_redirect_url?: string | undefined;
Nice catch! I've fixed this!

2021-09-28 06:55 UTC, vinassefranche commented on types/hellosign-sdk/hellosign-sdk-tests.ts
> +        signing_redirect_url: 'http://localhost',
This indeed failed when I fixed the previous comment so I removed it

2021-09-30 11:51 UTC, vinassefranche commented
@dvprrsh Is there something wrong with the P.R.?

2021-09-30 18:46 UTC, dvprrsh approved these changes

2021-09-30 19:01 UTC, vinassefranche commented
Ready to merge

2021-09-30 22:09 UTC, merged