Add types for react-star-ratings
DefinitelyTyped/DefinitelyTyped pull request #56084
Opened 2021-09-30 14:36 UTC by vanillkay

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-09-30 21:20 UTC, peterblazejewicz commented on types/react-star-ratings/index.d.ts
> +// TypeScript Version: 2.8
```suggestion
```
it's probably from other package, minimum version tested/supported now is 3.7. No need to hardcode version unless specific reason (e.g TS feature)

2021-09-30 21:23 UTC, peterblazejewicz commented on types/react-star-ratings/index.d.ts
> +    rating?: number;
```suggestion
    rating: number;
```
is this one required? https://github.com/ekeric13/react-star-ratings/blob/07add0e61bf77fb94a9613587e31bffa9f46364e/src/star-ratings.js#L180

2021-09-30 21:25 UTC, peterblazejewicz commented on types/react-star-ratings/index.d.ts
> +    rating?: number;
same for some others

2021-09-30 21:30 UTC, peterblazejewicz commented on types/react-star-ratings/index.d.ts
> +    rating?: number;
never mind, read the defualts

2021-09-30 22:03 UTC, sandersn requested changes

2021-09-30 22:03 UTC, sandersn commented on types/react-star-ratings/react-star-ratings-tests.tsx
> +import StarRatings from 'react-star-ratings';
Use the commonjs syntax `import StarRatings = require('react-star-ratings')`.

Consumers of the package who want to use `import StarRatings from 'react-star-ratings'` will need to add `"esModuleInterop": true`, but Definitely Typed tests need to be backward compatible to show that the types will work with old code bases.

2021-09-30 22:03 UTC, sandersn commented on types/react-star-ratings/tsconfig.json
> +        "esModuleInterop": true,
Please remove this to show that this package will work with old code bases that haven't turned it on yet.

2021-09-30 22:03 UTC, sandersn commented on types/react-star-ratings/README.md
> +# Installation
The `@types` publisher generates a README. You do not need to write one yourself.

2021-10-01 17:58 UTC, peterblazejewicz approved these changes
LGTM!
@vanillkay thx!

2021-10-01 22:07 UTC, sandersn approved these changes

2021-10-01 22:07 UTC, merged