sinon: add promise types
DefinitelyTyped/DefinitelyTyped pull request #56111
Opened 2021-10-01 14:41 UTC by 43081j

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://sinonjs.org/releases/v11.1.2/promises/

sinon at some point introduced `sinon.promise()`

2021-10-12 22:02 UTC, johnjesse requested changes
I think the type of resolve is wrong... otherwise the changes look good.

2021-10-16 15:27 UTC, 43081j commented
@johnjesse ive resolved that now 👍

2021-10-16 21:20 UTC, johnjesse approved these changes

2021-10-22 22:26 UTC, rbuckton approved these changes

2021-10-23 18:29 UTC, merged