Update type of `transport` param.
DefinitelyTyped/DefinitelyTyped pull request #56184
Opened 2021-10-04 17:35 UTC by lpender

This change resolves TS errors for me locally.

See associated commits:

https://github.com/phoenixframework/phoenix/commit/514af3f477ccb88c2a978ea51f1eacf6ed49d902#diff-bae6505f39e00a1c0a8925699e73a03f7680f7e1fff357a782910daf9bee5501

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-10-04 20:11 UTC, princemaple commented
Phoenix js source code now specifies Function. Could you try that?

2021-10-04 21:15 UTC, lpender commented on types/phoenix/index.d.ts
> +  transport: object;
```suggestion
  transport: Function;
```

2021-10-04 21:15 UTC, lpender commented
Hey, thanks. Yes, function works. I updated the PR.

2021-10-04 21:44 UTC, princemaple requested changes
Looks like `Function` made CI unhappy. Could you try this instead?

2021-10-04 21:44 UTC, princemaple commented on types/phoenix/index.d.ts
> +  transport: Function;
```suggestion
  transport: new (endpoint: string) => Object;
```

2021-10-05 12:52 UTC, lpender commented on types/phoenix/index.d.ts
> +  transport: new (endpoint: string) => Object;
```suggestion
  transport: new (endpoint: string) => object;
```

2021-10-05 13:54 UTC, lpender commented
Hey, thanks for the suggestion @princemaple! The changes removed local errors for me. Would love to get it merged as it's holding up a build/deploy for me.

Thanks

![image](https://user-images.githubusercontent.com/1406554/136036333-66540608-a835-4a2a-9736-d90ec8e7b0dc.png)

2021-10-05 21:11 UTC, princemaple approved these changes
LGTM

2021-10-11 17:40 UTC, amcasey approved these changes

2021-10-11 22:36 UTC, lpender commented
Ready to merge

On Mon, Oct 11, 2021 at 10:41 AM TypeScript Bot ***@***.***>
wrote:

> @lpender <https://github.com/lpender>: Everything looks good here. I am
> ready to merge this PR (at 517a24b
> <https://github.com/DefinitelyTyped/DefinitelyTyped/commit/517a24b387ebc5235345697b638a8510469bc213>)
> on your behalf whenever you think it's ready.
>
> If you'd like that to happen, please post a comment saying:
>
> Ready to merge
>
> and I'll merge this PR almost instantly. Thanks for helping out! ❤️
>
> ***@***.*** <https://github.com/mciastek>, @John-Goff
> <https://github.com/John-Goff>, @princemaple
> <https://github.com/princemaple>: you can do this too.)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56184#issuecomment-940223800>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKXMWXLGKKVA2366GGVHS3UGMOTLANCNFSM5FJ4LLYQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-10-11 22:36 UTC, merged