[mjml-react] Add Explicit types for children
DefinitelyTyped/DefinitelyTyped pull request #56254
Opened 2021-10-06 18:09 UTC by eps1lon

We plan to remove implicit children from `@types/react`. The following changes are required to pass https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210.

https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-wrapper.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-breakpoint.js#L10
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-font.js#L7
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-button.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-column.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-divider.js#L7
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-group.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-hero.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-image.js#L7
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-navbar.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-navbar-link.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-spacer.js#L7
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-table.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-wrapper.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-carousel.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-carousel-image.js#L10
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-social-element.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-social.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-section.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-column.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-button.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-text.js#L8
https://github.com/wix-incubator/mjml-react/blob/c1eb06ab366697a609dc6f552f86855b03ae4d80/src/mjml-body.js#L8

2021-10-14 17:34 UTC, eps1lon commented
> IMO there's isn't enough detail about this change to evaluate what the goal is.

What details are you missing? I've provided a link to the overall goal and describe each individual component. I don't know what else I could provide.

> This also changes tests in undesirable ways.

Could you point to specifics? I'm not familiar with what you desire in your tests.

2021-10-14 19:48 UTC, IanEdington requested changes

2021-11-05 15:12 UTC, IanEdington commented on types/mjml-react/mjml-react-tests.tsx
> +    const minProps: React.ReactNode = <MjmlBody />; // $ExpectError
@eps1lon the PR upstream has merged. Are you able to loosen the types in this PR.

My expectation is that you shouldn't need to change any tests from the base branch for this change. Does that make sense or is there something I'm still missing about the test changes?

2021-11-05 16:17 UTC, eps1lon commented on types/mjml-react/mjml-react-tests.tsx
> +    const minProps: React.ReactNode = <MjmlBody />; // $ExpectError
Updated types with https://github.com/wix-incubator/mjml-react/pull/66

2021-11-08 02:38 UTC, IanEdington approved these changes

2021-11-08 09:24 UTC, eps1lon commented
Ready to merge

2021-11-08 09:25 UTC, merged