[react-native] Add explicit types for children
DefinitelyTyped/DefinitelyTyped pull request #56312
Opened 2021-10-07 08:23 UTC by eps1lon

We plan to remove implicit children from `@types/react`. The following changes are required to pass https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56210.

https://github.com/facebook/react-native/blob/v0.64.2/Libraries/Text/TextProps.js#L72

2021-10-07 09:30 UTC, kuasha420 requested changes
Is there any reason for doing `children?: React.ReactNode | undefined;` instead of just `children?: React.ReactNode;` ?

2021-10-07 10:22 UTC, kuasha420 approved these changes

2021-10-07 12:06 UTC, ca057 approved these changes

2021-10-07 15:09 UTC, kuasha420 approved these changes
LGTM

2021-10-11 09:47 UTC, ca057 approved these changes

2021-10-11 15:37 UTC, elicwhite approved these changes

2021-10-13 23:49 UTC, amcasey approved these changes

2021-10-14 08:57 UTC, merged