[react-native] Add missing button props
DefinitelyTyped/DefinitelyTyped pull request #56374
Opened 2021-10-07 18:59 UTC by codyduong

Adds missing component props for `Button` and the props they pass into for `TouchableOpacity` and `TouchableNativeFeedback` 

Discussion here: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/56288#discussioncomment-1441532

I'd note that there are quite a bit of discrepancies on React-Native's docs here on `Button` as well as the other two components versus their original source code. I'll probably be over there next fixing docs...
* Reformatted `button` and added missing props, soon to use accessibilityProps more in v0.66+ of react-native
* Some docs which mistakenly state a prop that don't actually do anything. I've left this in for now but a note will have to be made to change this one the confusion on docs is cleared up `TouchableOpacity` has [tvParallaxProperties](https://reactnative.dev/docs/touchableopacity#tvparallaxproperties-android), which doesn't do anything in [src](https://github.com/facebook/react-native/blob/main/Libraries/Components/Touchable/TouchableOpacity.js)
* Shifted wrong types outside of `TouchableWithoutFeedbackProps`, and into their places where they are actually required as a type.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test react-native`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://reactnative.dev/docs/0.65/button>>
<<https://github.com/facebook/react-native/blob/v0.65.0/Libraries/Components/Button.js>>
<<https://reactnative.dev/docs/0.65/touchableopacity#props>>
<<https://github.com/facebook/react-native/blob/v0.65.0/Libraries/Components/Touchable/TouchableOpacity.js>>
<<https://reactnative.dev/docs/0.65/touchablenativefeedback#props>>
<<https://github.com/facebook/react-native/blob/v0.65.0/Libraries/Components/Touchable/TouchableNativeFeedback.js>>
- [] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-10-14 13:33 UTC, eps1lon requested changes

2021-10-14 17:37 UTC, eps1lon approved these changes

2021-10-14 20:11 UTC, amcasey approved these changes

2021-10-14 22:22 UTC, codyduong commented
Ready to merge

2021-10-14 22:23 UTC, merged

2021-10-19 21:52 UTC, renchap commented
When using `@types/react-native >= 0.65.7` (first version with this PR merged), I am getting the following error when using `<ListItem>` from `react-native-elements`:

```
error TS2739: Type '{ children: Element[]; bottomDivider: boolean; disabled: boolean | undefined; onPress: (() => void)
 | undefined; }' is missing the following properties from type 'Pick<TouchableHighlightProps & { containerStyle?: 
StyleProp<ViewStyle>; disabledStyle?: StyleProp<ViewStyle>; ... 6 more ...; children?: any; } & Partial<...>, "children"
 | ... 45 more ... | "bottomDivider">': hasTVPreferredFocus, tvParallaxProperties

20     <ListItem
```

I dont know if this comes from an error in `@types/react-native` introduced by this PR of if it comes from `react-native-elements`'s types, but I wanted to mention it here.

I opened a related issue in `react-native-elements`: https://github.com/react-native-elements/react-native-elements/issues/3227