[universalify] improve types to mantain type on arguments instead of just any -> any
DefinitelyTyped/DefinitelyTyped pull request #56373
Opened 2021-10-07 18:57 UTC by ricardo-devis-agullo

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/universalify/index.d.ts
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

The context is the types itself, which right now they are just

```typescript
export function fromCallback(fn: (...args: any[]) => any): (...args: any[]) => Promise<any> | void;
export function fromPromise(fn: (...args: any[]) => any): (...args: any[]) => Promise<any> | void;
```

Which means that any function passed through it will lose all the type information (it will be converted to a function that takes any and returns any). This changes that, using a similar technique that @types/node does on the `promisify` function inside the `util` library. It works up to 5 arguments, and then it gets to the previous default. This should be enough for most cases (since promisify is also limited to 5 arguments)

2021-10-08 01:07 UTC, Richienb requested changes
In recent times, it has become possible for TypeScript generics to support spreading arguments. This should be done instead.

2021-10-08 11:10 UTC, ricardo-devis-agullo commented
Done. Thank you!

2021-10-08 11:16 UTC, Richienb requested changes

2021-10-19 13:12 UTC, Richienb requested changes

2021-11-19 18:56 UTC, closed without merging