[node] Support null data argument for readline.write
DefinitelyTyped/DefinitelyTyped pull request #56409
Opened 2021-10-09 18:17 UTC by kyleaedwards

Node's `readline.write(data, key?)` method supports a `null` data argument, and to my knowledge has support in all LTS versions going back as far as v4, perhaps even further. The documentation (see [v10](https://nodejs.org/dist/latest-v10.x/docs/api/readline.html#readline_rl_write_data_key), [v12](https://nodejs.org/dist/latest-v12.x/docs/api/readline.html#readline_rl_write_data_key), [v14](https://nodejs.org/dist/latest-v14.x/docs/api/readline.html#readline_rl_write_data_key), and [v16](https://nodejs.org/dist/latest-v16.x/docs/api/readline.html#readline_rl_write_data_key)) include an example of this when triggering key combinations and escape characters to the prompt:

```js
rl.write('Delete this!');
// Simulate Ctrl+U to delete the line written previously
rl.write(null, { ctrl: true, name: 'u' });
```

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://nodejs.org/dist/latest-v16.x/docs/api/readline.html#readline_rl_write_data_key](https://nodejs.org/dist/latest-v16.x/docs/api/readline.html#readline_rl_write_data_key)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-10-14 13:31 UTC, LinusU approved these changes
Great! 👏

2021-10-14 15:39 UTC, SimonSchick requested changes

2021-10-25 16:22 UTC, LinusU approved these changes

2021-10-25 20:25 UTC, orta approved these changes

2021-10-25 20:32 UTC, merged