[parse5] Add `ReadonlyTreeAdapter`
DefinitelyTyped/DefinitelyTyped pull request #56403
Opened 2021-10-09 13:02 UTC by ExE-Boss

This is because `parse5.serialize(…)` only reads the tree, and therefore doesn’t need the `create*`, `set*`, and `update*` methods.

I also moved the **TSDoc** comments from `TypedTreeAdapter` to `TreeAdapter` so that they’re inherited correctly even when only `extends TreeAdapter` is used, which is why the diff is ugly.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/inikulin/parse5/blob/master/packages/parse5/lib/serializer/index.js>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-10-10 09:22 UTC, 43081j requested changes
Marking as requesting changes until my other comment is resolved, if ever

2023-08-09 20:26 UTC, peterblazejewicz commented
to be reviewed as to be closed, unless acted on

2023-08-10 09:39 UTC, 43081j commented
you can close this im pretty sure

we migrated parse5 to typescript long ago, someone needs to get around to removing the types basically

2023-08-10 20:59 UTC, peterblazejewicz commented
closing, we can always reinstate, if really needed, thx!

2023-08-10 20:59 UTC, closed without merging