Backbone: add support for view without model
DefinitelyTyped/DefinitelyTyped pull request #56564
Opened 2021-10-16 14:22 UTC by kumilingus

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test backbone`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://stackoverflow.com/questions/8997375/backbonejs-view-without-a-model
- [ ] Increase the version number in the header if appropriate.

---

Also, there is no Backbone.View `collection` property in Backbone. Why is it that part of this definition?

I had to change  the `collection` property to  `Collection<any>` (same hack as [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/backbone/index.d.ts#L536-L537)) so the `giraffe` library types to tests pass. Can not we just remove the `collection` property? 

Thank you!

2021-10-17 20:20 UTC, jgonggrijp reviewed
@kumilingus It's not entirely clear to me that you're actually solving a problem here. The existing typings already support the creation of a view without a model. The only change you're making in this respect is that it becomes possible to express that a particular view type can *never* have a model. Why would anyone need that, according to you?

> Also, there is no Backbone.View `collection` property in Backbone. Why is it that part of this definition?

There is: https://backbonejs.org/#View-constructor. I even wrote [a library](https://www.npmjs.com/package/backbone-fractal) for composing views out of smaller views, where one of the base classes is specifically meant for [representing each model in the `.collection` with a separate subview](https://www.npmjs.com/package/backbone-fractal#introducing-collectionview). [Marionette](https://marionettejs.com) has a somewhat similar [`CollectionView`](https://marionettejs.com/docs/master/marionette.collectionview.html) class, too.

> 
> I had to change the `collection` property to `Collection<any>` (same hack as [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/backbone/index.d.ts#L536-L537)) so the `giraffe` library types to tests pass.

The hack that you copied is passable, but only if there is sufficient reason to make any changes in the first place.

> Can not we just remove the `collection` property?

Absolutely not.

2021-10-19 15:03 UTC, jgonggrijp requested changes

2021-10-19 17:33 UTC, jgonggrijp requested changes

2021-10-19 17:43 UTC, jgonggrijp approved these changes
Thanks for contributing!

2021-10-19 18:23 UTC, kumilingus commented
Ready to merge

2021-10-19 18:24 UTC, merged