[@types/google-apps-scrcipt] add types for IconImage
DefinitelyTyped/DefinitelyTyped pull request #56817
Opened 2021-10-27 12:23 UTC by Frenchcooc

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:https://developers.google.com/apps-script/reference/card-service/icon-image?hl=en
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

---

The CardService for Google Apps Script has an `IconImage` class that was not supported by DefinitelyTyped yet. This aims to provide support to this class.

PS: first PR on this repo.

2021-10-27 13:44 UTC, mtgto requested changes

2021-10-27 14:52 UTC, mtgto approved these changes
It looks good to me. Thanks for your contribution 😺

2021-11-02 20:23 UTC, elibarzilay commented
For future reference, adding tests would have made this quicker.

2021-11-06 15:15 UTC, mtgto commented
Ready to merge

2021-11-06 15:16 UTC, merged