[@types/consul]: replace custom `Thenable` with standard `Promise`
DefinitelyTyped/DefinitelyTyped pull request #57245
Opened 2021-11-18 07:08 UTC by smoke

fixes `TS2739: Type 'Thenable ' is missing the following properties from type 'Promise ': [Symbol.toStringTag], finally`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-12-06 19:14 UTC, amcasey requested changes
I'm not familiar with `Consul`, but the old types look pretty intentional.  Can you please elaborate on when you're seeing the error and confirm that the new types better match the runtime behavior?

2021-12-07 15:59 UTC, smoke commented
@amcasey Thank you for your attention and help in moving this forward! 

I am seing the error whenever I use built in async/await e.g. `await consul.agent.service.register(...);`
I suppose the `Thenable` type was introduced back in the times when there were no standard typings around `Promise` and/or the internal HTTP API Client they used called old version of `node-papi` that used custom / switchable implementation. 

I did some reverse engineering of the up to date version, to come up to switching to `Promise`, here a short trace of proofs:
- the `consul` use `const papi = require("papi");` see https://github.com/silas/node-consul/blob/main/lib/consul.js#L1
- the `papi` use built in `new Promise` see https://github.com/silas/node-papi/blob/main/lib/client.js#L266-L271
- inspecting the runtime did provide the same results

2021-12-07 18:23 UTC, amcasey approved these changes
Thanks for the details and for stepping in to improve the types!

2021-12-07 20:42 UTC, smoke commented
Ready to merge

2021-12-07 20:42 UTC, merged