use `this` type in `ChocolateChipElementArray.find`
DefinitelyTyped/DefinitelyTyped pull request #57253
Opened 2021-11-18 14:12 UTC by DetachHead

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-11-24 20:30 UTC, gabritto commented
Waiting for further discussion on: https://github.com/microsoft/TypeScript/pull/46781

2021-11-30 20:48 UTC, chriskrycho requested changes
Marking as Request Changes for the bot's sake. Will update after the other PR moves.

2021-12-24 02:01 UTC, DetachHead commented
@chriskrycho what do?

2021-12-24 04:12 UTC, chriskrycho commented
Given how these types are deeply and inescapably coupled to the general `Array` and `ReadonlyArray` types, I (and I take it also @gabritto!) am uncomfortable merging it until there’s motion on #46781 – once folks there are comfortable with the change, we can move forward. I expect that to be post-holidays, though: most of the TS team is on vacation (and so am I!).

2021-12-24 04:22 UTC, DetachHead commented
all good, i meant regarding the bot, is there a label we can put on this PR that tells it to wait indefinitely or will we just have to keep commenting once every couple weeks to keep it open

2021-12-24 14:53 UTC, chriskrycho commented
Ah, yeah: we’ll just have to keep yammering at the bot. If you do a rebase-and-push, I’ll re-review, and start the cycle again.

2022-01-17 13:46 UTC, DetachHead commented
@typescript-bot 😳😳😳😳😳😳😳😳

2022-01-26 09:48 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## winjs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/winjs@latest/))
was missing the following properties:
1. ColorTypes
1. createAccentRule
1. Pivot
1. LightDismissalReasons
1. DismissalPolicies

<details>
<summary>as well as these 40 other properties...</summary>
<p>LightDismissableElement, ModalElement, shown, hidden, updated, isShown, isTopmost, keyDown, keyUp, keyPress, ClassNames, EventNames, actionAreaCommandWidth, actionAreaSeparatorWidth, actionAreaOverflowButtonWidth, overflowCommandHeight, overflowSeparatorHeight, controlMinWidth, overflowAreaMaxWidth, heightOfMinimal, heightOfCompact, contentMenuCommandDefaultLabel, defaultClosedDisplayMode, defaultOpened, defaultOverflowDirection, typeSeparator, typeContent, typeButton, typeToggle, typeFlyout, commandSelector, primaryCommandSection, secondaryCommandSection, OverflowDirection, OpenCloseMachine, ToolBar, SplitView, SplitViewPaneToggle, defaultPlacement, AppBar</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c773e62e62c57c5a27587c2eb391d629cbbf8e66
</p>

2022-01-31 22:08 UTC, amcasey commented
Converted to a draft since this won't be actionable until the product change goes through.  Feel free to close and re-open if that's easier to track.

2025-04-09 17:59 UTC, sandersn commented
This is very old now so I am going to close it.

2025-04-09 17:59 UTC, closed without merging