Add `tab` to @ember/test-helpers
DefinitelyTyped/DefinitelyTyped pull request #57359
Opened 2021-11-24 20:20 UTC by eramod

`tab` was introduced in 2.6 with this PR:
https://github.com/emberjs/ember-test-helpers/pull/1113/files

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2021-11-24 20:33 UTC, eramod commented
Note that this only addresses the new `tab` helper and not other changes to @ember/test-helpers since 2.0, which according to [this note](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/459bc4a2904d8c8c864976543d987fec3d24e159/types/ember__test-helpers/index.d.ts#L1) is the last time this package's types were updated.

2021-11-29 20:03 UTC, domdomegg commented on types/ember__test-helpers/index.d.ts
> +  }
nit: spacing

```suggestion
}
```

2021-11-29 20:03 UTC, domdomegg approved these changes
Happy this matches https://github.com/emberjs/ember-test-helpers/pull/1113/files#diff-4ad070e9385fe17cbb8c8e64e18b3391be95a1afb73fb230ce6e7d01bd57a5adR171 which appears to be the correct type from the implementation.

2021-11-29 20:05 UTC, domdomegg commented
It's also probably worth bumping the version number in this package to 2.6 (at the top of the file). I know the definitions are not complete, but it will prevent runtime-errors using these types with a emberjs version <2.6.

2021-11-29 20:19 UTC, eramod commented
@domdomegg Thanks for the PR feedback! I fixed both issues.

2021-11-30 10:33 UTC, domdomegg approved these changes

2021-11-30 19:42 UTC, chriskrycho requested changes
Thank you, @eramod! Happy to merge pending one change.

2021-11-30 19:42 UTC, chriskrycho commented on types/ember__test-helpers/index.d.ts
> +    export default function (options?: { backwards?: boolean; unRestrainTabIndex?: boolean }): Promise<void>;
Let's name the function here!

```suggestion
    export default function triggerTab(options?: { backwards?: boolean; unRestrainTabIndex?: boolean }): Promise<void>;
```

That will help make autocomplete work better for consumers.

2021-12-01 00:27 UTC, chriskrycho approved these changes
Thank you!

2021-12-01 00:29 UTC, chriskrycho commented
Ready to merge

2021-12-01 00:30 UTC, merged