Update react-native-webrtc's mediaDevices.getUserMedia
DefinitelyTyped/DefinitelyTyped pull request #57353
Opened 2021-11-24 13:35 UTC by Brumor

We checked the code and it doesn't seem like it would return a boolean, it either returns a MediaStream or it rejects so the type here is wrong.

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [<<url here>>](https://github.com/react-native-webrtc/react-native-webrtc/blob/d93dd7d451b01b9015b65e4f79db0991edac0919/src/getDisplayMedia.js)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. - Not sure?

2021-11-30 01:03 UTC, sandersn requested changes
Can you link to the code that shows that boolean is not returned?

2021-12-02 12:56 UTC, Brumor commented
@sandersn Sure, here: https://github.com/react-native-webrtc/react-native-webrtc/blob/d93dd7d451b01b9015b65e4f79db0991edac0919/src/getDisplayMedia.js

2021-12-02 23:07 UTC, sandersn commented
I think the correct link is https://github.com/react-native-webrtc/react-native-webrtc/blob/master/src/getUserMedia.js

2021-12-02 23:07 UTC, sandersn approved these changes

2021-12-02 23:07 UTC, merged