[ethereum-blockies]: new package
DefinitelyTyped/DefinitelyTyped pull request #57569
Opened 2021-12-06 05:53 UTC by Jack-Works

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2021-12-06 05:59 UTC, ClassicOldSong commented
LGTM

2021-12-06 06:03 UTC, SukkaW approved these changes

2021-12-06 06:04 UTC, ClassicOldSong approved these changes

2021-12-06 06:05 UTC, ClassicOldSong approved these changes

2021-12-06 06:08 UTC, magic-akari approved these changes

2021-12-06 06:09 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ethereum-blockies ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ethereum-blockies@latest/))
was missing the following properties:
1. render
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9de8ac383726a4839bf39f817dbafc5402758198
</p>

2021-12-06 06:14 UTC, limichange approved these changes

2021-12-06 06:25 UTC, lawvs approved these changes

2021-12-06 09:02 UTC, SukkaW approved these changes

2021-12-06 17:09 UTC, peterblazejewicz commented on types/ethereum-blockies/index.d.ts
> +// Project: https://github.com/ethereum/blockies (Does not have to be to GitHub, but prefer linking to a source code repository rather than to a project website.)
```suggestion
// Project: https://github.com/ethereum/blockies
```

2021-12-06 18:57 UTC, amcasey requested changes
Please address the comment from @peterblazejewicz.  Otherwise, LGTM

2021-12-07 10:38 UTC, magic-akari approved these changes

2021-12-07 10:45 UTC, exoticknight approved these changes

2021-12-07 11:01 UTC, ClassicOldSong approved these changes

2021-12-07 11:08 UTC, lawvs approved these changes

2021-12-07 18:10 UTC, peterblazejewicz approved these changes
LGTM!

2021-12-07 18:24 UTC, amcasey approved these changes
Thanks!

2021-12-07 19:41 UTC, Jack-Works commented
Ready to merge

2021-12-07 19:42 UTC, merged