Fix verify return type of verify function in jsonwebtoken
DefinitelyTyped/DefinitelyTyped pull request #57616
Opened 2021-12-08 02:07 UTC by thebinarysearchtree

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[url here](https://github.com/auth0/node-jsonwebtoken#jwtverifytoken-secretorpublickey-options-callback)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

The verify function returns either an object or a string. There is no way to determine which one from the arguments provided to the function. The previous return type was ```string | JwtPayload```. This seems to be a misunderstanding of the concept of union types. ```JwtPayload``` is defined as having all properties. This means the union of the two types is just the properties of the string type. This is wrong as the decoded payload may be an object with any properties.

2021-12-08 10:33 UTC, LinusU commented
`JwtPayload` includes `[key: string]: any;` so it sort of acts like an any-type already. Although I don't think that there is anything in the `jsonwebtoken` that verifies that e.g. `iat` is a number, and not e.g. a boolean. So with that, `unknown` seems like the best fit?

If we're going with this I think that we should:
- Remove the `JwtPayload` type
- Change the `Jwt` to `payload: unknown`
- Change the return type of `verify` (without `complete == true`) to `unknown`
- Change the return type of `decode` (without `complete == true`) to `unknown`
- Change `VerifyCallback<T = JwtPayload>` to `VerifyCallback<T = unknown>`

2021-12-08 11:18 UTC, thebinarysearchtree commented
I think it should be ```any``` but I write more JavaScript than TypeScript. The reason I think it should be ```any``` is because ```JSON.parse``` returns ```any```, so it seems that is what TypeScript people use to represent these types of things. It looks like one of the ```decode``` signatures is also wrong as it is a union with ```string``` also, which ends up just being ```string``` and losing all of the properties of the JSON object if that happens to be what is returned. I agree that maybe ```JwtPayload``` is unnecessary.

2021-12-08 12:59 UTC, nandi95 commented
I don't understand. Why are we losing out on typings? We're going from a string | object with string index and some type hints to any.

Can you clarify the below please?
> This seems to be a misunderstanding of the concept of union types. `JwtPayload` is defined as having all properties.

`JwtPayload` is just an object with some optional keys, what do you mean all properties?

> This means the union of the two types is just the properties of the string type.

I'm probably misunderstanding here

> This is wrong as the decoded payload may be an object with any properties.

But it's already is? https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57616/files#diff-37161fa05c1ae7e10456ed1c324e607f937ea35be4d2c920c0c289a67e94f131R123

> There is no way to determine which one from the arguments provided to the function.

Surely we need a better overload no? not remove existing helpful typing

note: JSON.parse return any for now but hopefully that will change https://github.com/microsoft/TypeScript/issues/1897

2021-12-08 16:53 UTC, LinusU commented
> I think it should be `any` but I write more JavaScript than TypeScript. The reason I think it should be `any` is because `JSON.parse` returns `any`, so it seems that is what TypeScript people use to represent these types of things.

`JSON.parse` had typings before `unknown` was added to the language. I think that `unknown` is a better fit because the value is unknown at runtime.

> I don't understand. Why are we losing out on typings? We're going from a string | object with string index and some type hints to any.

I think the argument is that the types aren't necessarily correct, e.g. `jti` is typed as `string | undefined` but it could just as well be set to `true`.

2021-12-09 01:03 UTC, amcasey requested changes
Please address the feedback from @LinusU and @nandi95.

2021-12-09 01:03 UTC, thebinarysearchtree commented
> I think that unknown is a better fit because the value is unknown at runtime.

The debate around ```unknown``` vs ```any``` seems to be an ongoing one on the TypeScript repository. For the moment, they are still sticking with ```any``` for ```JSON.parse```, but as I said, I don't write as much TypeScript, so maybe your opinion is more relevant. My personal opinion is that having to type cast the payload each time is annoying. The main thing from my perspective is whether it will work with JavaScript.

> JwtPayload is just an object with some optional keys, what do you mean all properties?
The type definition says that it can potentially have any properties (keys). In terms of a union, this essentially means it could have all properties.

> Surely we need a better overload no? not remove existing helpful typing
Well, that is probably a good idea, but it does not exist. Currently, the payload's properties are only available (using dot notation) when the callback is used, which means it is broken. 

The ```JwtPayload``` type seems so loose that it is worthless.

2021-12-09 12:25 UTC, LinusU commented
> Not exactly. Those properties are not even available on the returned payload if the non-callback version of `verify` is used because `jti` is not a property that is common to both `string` and `JwtPayload`.

What I have seen done is guarding against this with `if (typeof result === 'string') throw ...`. With that, the type will be narrowed to just `JwtPayload` after that, and then you'll be able to do `.jti` and get `number | undefined`.

> An overload to specify whether the payload should be parsed with JSON or returned as a string would allow for a more specific return type. The return type of the non-string version would still have to be `any` or `unknown`. This is because the `JwtPayload` type does not accurately describe the different types of objects that could be returned from `JSON.parse`. The parsed result could be an `Array` for example.

Actually, it's guaranteed to be either string or object:
https://github.com/auth0/node-jsonwebtoken/blob/74d5719bd03993fcf71e3b176621f133eb6138c0/decode.js#L13-L15

_Potentially_ it would be better to model as `string | { [key: string]?: unknown }` 🤔 

And _potentially_ it would be nice with an overload for when passing no options at all (`, options?: undefined)` that returns something like: `string | { [key: string]?: unknown, nbf?: number, exp?: number }` since `nbf` and `exp` actually are checked by default...

(btw. isn't it crazy that the library can return a string in some cases? e.g. if there is invalid JSON in the payload 😅 And since the `verify` function doesn't even check if it's a string or not, validation could be messed with if there is a prototype pollution on the `String` class somewhere...)

2021-12-10 05:56 UTC, thebinarysearchtree commented
Oh it is restricted to just object OK. Well I upgraded vscode yesterday and with that TypeScript was upgraded to 4.5 and now the problem I was having in JavaScript (which was the reason I created this PR) is now gone. In JavaScript, you had no ability to access the properties of the payload (unless you did type narrowing I guess, which is not idiomatic JavaScript), but now you don't have to do that. Frankly, this is all driving me crazy because there is no documentation at all as to "what are the effects of TypeScript on JavaScript".

> isn't it crazy that the library can return a string in some cases
Yes I agree :)

Anyway, feel free to either use this change or throw it away. I have no idea whether this current behaviour in TypeScript 4.5 will stay, or it will revert back to the previous behaviour. I am pretty sure returning unknown will work with JavaScript as well.

2021-12-10 07:00 UTC, closed without merging