fix: types of ReplaceStep, ReplaceAroundStep, AddMarkStep and RemoveM…
DefinitelyTyped/DefinitelyTyped pull request #57618
Opened 2021-12-08 06:22 UTC by 0-Captain

…arkStep

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[url here](https://prosemirror.net/docs/ref/#transform.ReplaceStep)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-12-08 06:31 UTC, ocavue requested changes
Please add generic types to `Mark` and `Slice`.

And also please remove all trailing whitespace. You can find the following log in the CI pipeline. 

```
Error in prosemirror-transform
Error: /home/vsts/work/1/s/types/prosemirror-transform/index.d.ts:184:8
ERROR: 184:8   no-trailing-whitespace  trailing whitespace
ERROR: 188:8   no-trailing-whitespace  trailing whitespace
ERROR: 192:8   no-trailing-whitespace  trailing whitespace
ERROR: 202:8   no-trailing-whitespace  trailing whitespace
ERROR: 206:8   no-trailing-whitespace  trailing whitespace
ERROR: 210:8   no-trailing-whitespace  trailing whitespace
ERROR: 422:8   no-trailing-whitespace  trailing whitespace
ERROR: 426:8   no-trailing-whitespace  trailing whitespace
ERROR: 430:8   no-trailing-whitespace  trailing whitespace
ERROR: 434:8   no-trailing-whitespace  trailing whitespace
ERROR: 438:8   no-trailing-whitespace  trailing whitespace
ERROR: 442:8   no-trailing-whitespace  trailing whitespace
ERROR: 443:20  no-trailing-whitespace  trailing whitespace

```

2021-12-08 06:31 UTC, ocavue commented on types/prosemirror-transform/index.d.ts
> +    slice: Slice;
```suggestion
    slice: Slice<S>;
```

2021-12-08 06:31 UTC, ocavue commented on types/prosemirror-transform/index.d.ts
> +    slice: Slice;
```suggestion
    slice: Slice<S>;
```

2021-12-08 06:31 UTC, ocavue commented on types/prosemirror-transform/index.d.ts
> +    mark: Mark;
```suggestion
    mark: Mark<S>;
```

2021-12-08 06:31 UTC, ocavue commented on types/prosemirror-transform/index.d.ts
> +    mark: Mark;
```suggestion
    mark: Mark<S>;
```

2021-12-08 06:44 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## prosemirror-transform ([<kbd>unpkg</kbd>](https://unpkg.com/browse/prosemirror-transform@latest/))
was missing the following properties:
1. TransformError
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against de3b3cf0e3020218a35c04d7607bcb1481b59bd9
</p>

2021-12-08 06:48 UTC, ocavue approved these changes
LGTM

2021-12-10 22:26 UTC, amcasey approved these changes

2021-12-14 02:19 UTC, merged