Fix Leaflet panInside which supports PanOptions and ZoomOptions
DefinitelyTyped/DefinitelyTyped pull request #57810
Opened 2021-12-21 21:45 UTC by bb

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/Leaflet/Leaflet/blob/master/src/map/Map.js#L536 panInside calls pan and forwards the options
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-12-21 21:50 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## leaflet ([<kbd>unpkg</kbd>](https://unpkg.com/browse/leaflet@latest/))
was missing the following properties:
1. Mixin
1. PosAnimation
1. geoJson
1. noConflict
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against cf914c52d1413e935bfb144326e7eddce0fe6d9f
</p>

2021-12-26 00:25 UTC, domdomegg commented on types/leaflet/index.d.ts
> +export interface PanInsideOptions extends ZoomOptions, PanOptions {
```suggestion
export interface PanInsideOptions extends PanOptions {
```

panInside calls panTo which calls setView which takes pan and zoom options.

However, panTo does not pass through the zoom options: https://github.com/Leaflet/Leaflet/blob/d52d2fa341af4c120262b24a12592cfc3f66020e/src/map/Map.js#L308

2021-12-26 00:25 UTC, domdomegg requested changes
As per code comment

2022-01-13 18:01 UTC, bb commented
Thanks for the correction, @domdomegg! I committed your suggestion.

2022-01-13 20:50 UTC, domdomegg approved these changes

2022-01-24 18:56 UTC, henrythasler approved these changes

2022-01-24 21:45 UTC, bb commented
Ready to merge

2022-01-24 21:45 UTC, merged