Adding missing handleReturn to EditorProps v1.13.4
DefinitelyTyped/DefinitelyTyped pull request #57820
Opened 2021-12-22 15:55 UTC by entozoon

Fixing https://github.com/jpuri/react-draft-wysiwyg/issues/1148 by adding a simple missing interface option.

This option is [visible here](https://github.com/jpuri/react-draft-wysiwyg/blob/f59ee8419cdbd45aab3bdfdf1995f112b09bbb6a/src/Editor/index.js#L369) and similar to adjacent ones that already exist such as `handlePastedText`.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.) 
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
 
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [<<url here>>](https://github.com/jpuri/react-draft-wysiwyg/blob/f59ee8419cdbd45aab3bdfdf1995f112b09bbb6a/src/Editor/index.js#L369)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

^ Note, it's been an option since the beginning but for some reason is missing, so just a patch bump is fine.

2021-12-22 16:39 UTC, brunoMaurice approved these changes
Thanks, look great.

2021-12-26 00:11 UTC, domdomegg requested changes
As far as I can see, handleReturn is overriden by react-draft-wysiwyg, and users cannot pass a function to override it themselves.

It is not one of the [allowlisted props in filterEditorProps](https://github.com/jpuri/react-draft-wysiwyg/blob/f59ee8419cdbd45aab3bdfdf1995f112b09bbb6a/src/Editor/index.js#L299-L332) that users can pass through. This is used to calculated this.editorProps, which is spread into the draft Editor component. The handleReturn is therefore not part of this. The handleReturn that is present in that file does not appear to use the passed in handleReturn prop. Finally, it's not in [the PropTypes](https://github.com/jpuri/react-draft-wysiwyg/blob/f59ee8419cdbd45aab3bdfdf1995f112b09bbb6a/src/Editor/index.js#L505-L551) of the react-draft-wysiwyg Editor component.

2021-12-26 10:41 UTC, entozoon commented
Are you saying it should be added to that allowlist?
I mean, you certainly can override handleReturn.. it's what I'm doing in a project that led me to create this PR

2021-12-26 10:57 UTC, domdomegg commented
> Are you saying it should be added to that allowlist? I mean, you certainly can override handleReturn.. it's what I'm doing in a project that led me to create this PR

I'm saying I'm not sure that it can be overridden - I may well be wrong, especially given you say you have a working example, but I cannot see how that code can support it. Are you able to provide a codesandbox or short video clip showing e.g. it outputting a log based on the overridden handleReturn?

2021-12-26 11:38 UTC, brunoMaurice commented
It's missing on the PropTypes but nothing don't allow to overwrite it.

2021-12-26 13:05 UTC, domdomegg approved these changes
Apologies, this filter function actually filters **out** the given keys.

The handleReturn function does work - and should probably be added to the PropTypes.

2021-12-31 21:51 UTC, merged