Adding a few properties for the PostOrPage type
DefinitelyTyped/DefinitelyTyped pull request #57856
Opened 2021-12-25 22:25 UTC by pedroapfilho

If changing an existing definition:
- [x] Provide a URL to documentation or source code that provides context for the suggested changes: [<<url here>>](https://ghost.org/docs/content-api/#posts)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2021-12-25 23:16 UTC, domdomegg commented on types/tryghost__content-api/index.d.ts
> +    feature_image_alt?: string | undefined;
```suggestion
    feature_image_alt?: string | null | undefined;
```

2021-12-25 23:16 UTC, domdomegg commented on types/tryghost__content-api/index.d.ts
> +    feature_image_caption?: string | undefined;
```suggestion
    feature_image_caption?: Nullable<string> | undefined;
```

2021-12-25 23:17 UTC, domdomegg requested changes
Based on https://ghost.org/docs/content-api/#posts, these two properties can be null:

![image](https://user-images.githubusercontent.com/4953590/147395309-9cf5df59-761d-47b3-a3bf-f671f637bcf8.png)

2021-12-26 10:37 UTC, domdomegg approved these changes
LGTM

2021-12-27 06:38 UTC, antonve approved these changes

2021-12-31 21:55 UTC, merged