add defaultTool to [react-svg-pan-zoom]
DefinitelyTyped/DefinitelyTyped pull request #57909
Opened 2021-12-30 23:25 UTC by tvwenger

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<[url here](https://github.com/chrvadala/react-svg-pan-zoom/blob/main/docs/documentation.md)>>

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/57908

2021-12-30 23:29 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-svg-pan-zoom ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-svg-pan-zoom@latest/))
was missing the following properties:
1. Toolbar
1. Miniature
1. openMiniature
1. closeMiniature
1. Viewer
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e11cb5cf7676ae6f5cd5e2cecc72eefaf7e29b15
</p>

2022-01-01 19:15 UTC, martin-badin requested changes

2022-01-01 19:15 UTC, martin-badin commented on types/react-svg-pan-zoom/index.d.ts
> +    // defaul tool
fix typo

```suggestion
    // default tool
```

2022-01-01 19:15 UTC, martin-badin commented on types/react-svg-pan-zoom/index.d.ts
> +    defaultTool: string;
```suggestion
    defaultTool: 'none' | 'pan' | 'zoom-in' | 'zoom-out';
```

2022-01-01 21:58 UTC, martin-badin requested changes

2022-01-01 21:58 UTC, martin-badin commented on types/react-svg-pan-zoom/index.d.ts
> +    defaultTool: Tool;
The type Tool includes extended 'auto' value but based on documentation 'defaultTool' doesn't include the value. You can use the type Tool without auto 
 ```suggestion
    defaultTool: Exclude<Tool, typeof TOOL_AUTO>;
```

2022-01-02 08:24 UTC, martin-badin approved these changes
Looks good. Thanks

2022-01-02 17:25 UTC, tvwenger commented
Ready to merge

2022-01-02 17:26 UTC, merged