Node.js TCP Socket - remove obsolete timeout option and add abortController
DefinitelyTyped/DefinitelyTyped pull request #57919
Opened 2022-01-01 13:43 UTC by robertkiel

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Node.js TCP socket options](https://nodejs.org/docs/latest-v16.x/api/net.html#new-netsocketoptions)

2022-01-01 17:32 UTC, SimonSchick requested changes
The removal of `timeout` seems incorrect, see https://nodejs.org/docs/latest-v16.x/api/net.html#netcreateconnectionoptions-connectlistener `Additional options`, please revert these changes.

2022-01-01 17:47 UTC, robertkiel commented
> The removal of `timeout` seems incorrect, see https://nodejs.org/docs/latest-v16.x/api/net.html#netcreateconnectionoptions-connectlistener `Additional options`, please revert these changes.

Done! 

Nevertheless the option seems to be ignored by Node.js - but this is the wrong place for this topic.

2022-01-01 22:30 UTC, SimonSchick approved these changes

2022-01-03 07:18 UTC, robertkiel commented
Ready to merge

2022-01-03 07:18 UTC, merged