Add another possible combination of arguments for jQuery's .get() and…
DefinitelyTyped/DefinitelyTyped pull request #57937
Opened 2022-01-02 17:13 UTC by ChrisRaven

As jQuery [documentation](https://api.jquery.com/jquery.post/) says, only the url argument is obligatory, the rest are optional. The current definitions of the .get() and the post() types don't contain a combination, where there's a url, data and dataType, so I'm proposing to add it with this PR.

I had such combination of arguments in one of my working projects and it was underlined as an incorrect type. After adding the new definitions, everything was ok.

2022-01-02 18:25 UTC, ChrisRaven commented
According to the checks, my addition should be merged with an already existing type definition. Technically, it's true. However, the parameters in both definitions have totally different meanings (callback vs data to send to the server). Not sure, what to do about it.

2022-01-03 08:28 UTC, martin-badin commented
please add tests for all variants of your updated methods

2022-01-03 08:35 UTC, martin-badin requested changes

2022-01-03 08:35 UTC, martin-badin commented on types/jquery/JQueryStatic.d.ts
> +    get(url: string,
remove your definition and update this [get](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cd0e972f17bf5c892799692760828abe615430ee/types/jquery/JQueryStatic.d.ts#L1559-L1561) to 
```
get(url: string,
        data_success: JQuery.PlainObject | string | JQuery.jqXHR.DoneCallback | null,
        dataType: string): JQuery.jqXHR;
```

2022-01-03 08:35 UTC, martin-badin commented on types/jquery/JQueryStatic.d.ts
> +    post(url: string,
remove your definition and update this [post](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/cd0e972f17bf5c892799692760828abe615430ee/types/jquery/JQueryStatic.d.ts#L2676-L2678) to 
```
post(url: string,
         data_success: JQuery.PlainObject | string | JQuery.jqXHR.DoneCallback | null,
         dataType: string): JQuery.jqXHR;
```

2022-01-10 21:14 UTC, merged