fix(url-parse): tune `set` type
DefinitelyTyped/DefinitelyTyped pull request #58000
Opened 2022-01-05 21:09 UTC by sidoruk-sv

Due to real code, you could actually pass Record to url.set('query', ...) without the need for custom parser (third argument).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://github.com/unshiftio/url-parse/blob/master/index.js#L408>>. Also tests, that shows such usage: <<https://github.com/unshiftio/url-parse/blob/master/test/test.js#L914>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-01-05 21:21 UTC, martin-badin approved these changes

2022-01-05 21:22 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## url-parse ([<kbd>unpkg</kbd>](https://unpkg.com/browse/url-parse@latest/))
was missing the following properties:
1. trimLeft
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 105b84fcc3df806cc159a15629ca9a73394894f2
</p>

2022-01-05 21:24 UTC, martin-badin requested changes
@sidoruk-sv Could you please add `trimLeft` definition?
https://github.com/unshiftio/url-parse/blob/master/index.js#L537

2022-01-05 21:33 UTC, martin-badin approved these changes

2022-01-05 21:35 UTC, sidoruk-sv commented
@martin-badin thanks for pointing there)) `trimLeft()` added)

2022-01-05 21:36 UTC, martin-badin approved these changes
looks good

2022-01-10 09:57 UTC, sidoruk-sv commented
Ping @harisiva @DimitryDushkin @davidgoli 🙏

2022-01-14 12:41 UTC, sidoruk-sv commented
Ping @harisiva @DimitryDushkin @davidgoli 🙏

2022-01-20 09:57 UTC, sidoruk-sv commented
@harisiva @DimitryDushkin @davidgoli
<img src="https://i.imgur.com/GMfjJoF.gif" />

2022-01-20 10:11 UTC, DimitryDushkin commented
Hey! Looks good 👍

2022-01-20 10:12 UTC, DimitryDushkin approved these changes

2022-01-20 11:16 UTC, sidoruk-sv commented
Ready to merge

2022-01-20 11:17 UTC, merged