Add vanillajs-datepicker typings
DefinitelyTyped/DefinitelyTyped pull request #58166
Opened 2022-01-13 14:33 UTC by nihaopaul

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2022-01-14 19:18 UTC, martin-badin requested changes

2022-01-14 19:18 UTC, martin-badin commented on types/vanillajs-datepicker/Datepicker.d.ts
> +    picker: any;
```suggestion
    config: any;
    dates: any;
    editMode: boolean;
    element: Element;
    inline: boolean;
    inputField: any;
    picker: any;
    
    _options: object;
    _showing: boolean;
```

2022-01-14 19:18 UTC, martin-badin commented on types/vanillajs-datepicker/Datepicker.d.ts
> +    update(options?: any): void;
```suggestion
    update(options?: {clear: boolean, render: boolean}): void;
```

2022-01-14 19:18 UTC, martin-badin commented on types/vanillajs-datepicker/Datepicker.d.ts
> +    refresh(target?: string, forceRender?: boolean): void;
```suggestion
    refresh(forceRender?: boolean): void;
    refresh(target?: 'picker' | 'input', forceRender?: boolean): void;
```

2022-01-14 19:18 UTC, martin-badin commented on types/vanillajs-datepicker/Datepicker.d.ts
> +    _showing: boolean;
```suggestion
```

2022-01-14 19:18 UTC, martin-badin commented on types/vanillajs-datepicker/Datepicker.d.ts
> +    static get locales(): any;
```typescript
interface Local {
    clear?: string;
    days: string[];
    daysMin:string[];
    daysShort: string[];
    months: string[];
    monthsShort: string[];
    titleFormat?: string;
    today: string;
    rtl?: boolean;
}
```
```suggestion
    static get locales(): Record<string: Local>;
```

2022-01-14 19:18 UTC, martin-badin commented on types/vanillajs-datepicker/Datepicker.d.ts
> +    get pickerElement(): any;
```suggestion
    get active(): boolean;
    get pickerElement(): Element | undefined;
```

2022-01-14 19:18 UTC, martin-badin commented on types/vanillajs-datepicker/Datepicker.d.ts
> +    editMode: boolean;
```suggestion
```

2022-01-14 19:18 UTC, martin-badin commented on types/vanillajs-datepicker/tsconfig.json
> +            "es6", "DOM"
```suggestion
            "es6", "dom"
```

2022-01-14 19:18 UTC, martin-badin commented on types/vanillajs-datepicker/Datepicker.d.ts
> +    setOptions(options: any): void;
```suggestion
    setOptions(options: object): void;
```

2022-01-14 19:18 UTC, martin-badin commented on types/vanillajs-datepicker/Datepicker.d.ts
> +    exitEditMode(options?: any): void;
```suggestion
    exitEditMode(options?: object): void;
```

2022-01-17 18:10 UTC, peterblazejewicz commented on types/vanillajs-datepicker/DateRangePicker.d.ts
> +get dates(): Date[] | undefined;
```suggestion
	get dates(): Date[] | undefined;
```

2022-01-17 18:12 UTC, peterblazejewicz commented on types/vanillajs-datepicker/index.d.ts
> +// Type definitions for vanillajs-datepicker 1.1
```suggestion
// Type definitions for vanillajs-datepicker 1.2
```
is this 1.1 specific or should be aligned with latest published (1.2)?

2022-01-17 18:22 UTC, peterblazejewicz commented
Does it support global script (with iife block)?
https://unpkg.com/browse/vanillajs-datepicker@1.2.0/rollup.config.js
Should this DT support global script usage?

2022-01-18 02:08 UTC, DangerBotOSS commented on types/vanillajs-datepicker/DateRangePicker.d.ts
> +	get dates(): Date[] | undefined;
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/vanillajs-datepicker/DateRangePicker.d.ts;
  Line: 14;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-01-24 22:39 UTC, gabritto approved these changes

2022-01-24 22:39 UTC, gabritto commented on types/vanillajs-datepicker/DateRangePicker.d.ts
> +	get dates(): Date[] | undefined;
```suggestion
    get dates(): Date[] | undefined;
```
Please use spaces instead of tabs here.

2022-01-24 22:40 UTC, merged