[draft-js] Add a few `DraftEditor` member types
DefinitelyTyped/DefinitelyTyped pull request #58210
Opened 2022-01-15 22:02 UTC by ruipserra

### Changes

Add types for the following `DraftEditor` members:
- `getEditorKey`
- `editor`
- `editorContainer`

You can see the original flow types in the draft-js code here: https://github.com/facebook/draft-js/blob/d974abb0c2844bf99724aba9448df42a63291e0e/src/component/base/DraftEditor.react.js#L187-L189.

---

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/draft-js/blob/d974abb0c2844bf99724aba9448df42a63291e0e/src/component/base/DraftEditor.react.js#L187-L189

2022-01-15 22:06 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## draft-js ([<kbd>unpkg</kbd>](https://unpkg.com/browse/draft-js@latest/))
was missing the following properties:
1. EntityInstance
1. RawDraftContentState
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a22f86e90e1d81e51be955c0db52d053f97e95c3
</p>

2022-01-16 16:38 UTC, martin-badin requested changes

2022-01-16 16:38 UTC, martin-badin commented on types/draft-js/index.d.ts
> +                editorContainer: HTMLElement | null | undefined;
Please update

```suggestion
                editor?: HTMLElement | null | undefined;
                editorContainer?: HTMLElement | null | undefined;
```

2022-01-16 16:41 UTC, martin-badin requested changes
Please, could you add tests?

2022-01-16 16:41 UTC, martin-badin requested changes

2022-01-16 16:41 UTC, martin-badin commented on types/draft-js/index.d.ts
> +                getEditorKey: () => string;
```suggestion
                getEditorKey(): string;
```

2022-01-17 16:24 UTC, martin-badin approved these changes

2022-02-04 19:13 UTC, amcasey approved these changes

2022-02-04 21:35 UTC, ruipserra commented
Ready to merge

2022-02-04 21:36 UTC, merged