[node] Update stream .destroy and .end types for v16
DefinitelyTyped/DefinitelyTyped pull request #58358
Opened 2022-01-21 14:17 UTC by quentin-sommer

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v16.x/docs/api/stream.html

2022-01-24 10:51 UTC, antongolub commented
@quentin-sommer,

I've tried to fix this issue 2y ago. It turned out that a lot of libraries extend these interfaces.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42105/

2022-01-27 19:33 UTC, gabritto requested changes
Minor comment on the tests, but otherwise I think we can merge this

2022-01-27 19:33 UTC, gabritto commented on types/node/test/stream.ts
> +function testEndandDestroy() {
Shouldn't this test function be in `node/v16/test/stream.ts`, since you're updating types for v16?

2022-02-09 23:00 UTC, rbuckton approved these changes

2022-02-10 09:35 UTC, merged