@types/googlepay - CardParameters -  Add `assuranceDetailsRequired` attribute
DefinitelyTyped/DefinitelyTyped pull request #58432
Opened 2022-01-25 16:31 UTC by kopecmi8

Interface CardParameters missing boolean assuranceDetailsRequired attribute.

The attribute should be present as you can see in [documentation](https://developers.google.com/pay/api/web/reference/request-objects#CardParameters)

If attribute is set to true, also CardInfo interface should contain [assuranceDetails](https://developers.google.com/pay/api/web/reference/response-objects#assurance-details-specifications)

https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/58431

2022-01-25 18:44 UTC, martin-badin requested changes

2022-01-25 18:44 UTC, martin-badin commented on types/googlepay/index.d.ts
> +        cardHolderAuthenticated?: true | false | undefined;
```suggestion
        cardHolderAuthenticated?: boolean | undefined;
```

2022-01-26 14:25 UTC, kopecmi8 commented on types/googlepay/index.d.ts
> +        assuranceDetailsRequired?: false | true | undefined;
I originally respects the rest of file where `true | false` is used, but i agree boolean is simpler solution

2022-01-26 14:30 UTC, martin-badin approved these changes

2022-01-26 19:49 UTC, socsieng commented
Thanks for this. I've got general changes that should be applied for boolean and optional types across the file, but I'll submit that in another pull request.

2022-01-26 19:50 UTC, socsieng approved these changes

2022-01-27 20:55 UTC, gabritto approved these changes

2022-01-27 20:56 UTC, merged