Add 'effort' to options of PNG, update options of WebP and HEIC
DefinitelyTyped/DefinitelyTyped pull request #58583
Opened 2022-02-03 10:37 UTC by willmacdonald

Change log: https://sharp.pixelplumbing.com/changelog#v030---dresser

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://sharp.pixelplumbing.com/changelog#v030---dresser]
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-02-03 20:25 UTC, rexxars reviewed
Given the `reductionEffort` and `speed` options are only _deprecated_ (not removed), should we still include them but mark them with `@deprecated`?

There are a few other changes that would be nice to add for 0.30:
- gif output is now included by default - there are a few comments/documentation pieces that needs to be updated
- `unlimited` option for PNG/SVG input
- `withoutReduction` option for resizing
- `resolutionUnit` for tiff

...but I suppose we could change those in a separate PR if you just want to get this out

2022-02-03 21:25 UTC, willmacdonald commented
@rexxars I just included these updates since it was causing an issue with some code I was working on. I can return with a more complete PR in the future.

2022-02-16 11:17 UTC, Fdebijl requested changes

2022-02-16 11:17 UTC, Fdebijl commented on types/sharp/index.d.ts
> -        reductionEffort?: number | undefined;
I agree with @rexxars, these should be marked with `@deprecated` rather than being removed outright.

2022-03-10 23:17 UTC, closed without merging