fix(graphql-upload): allow `graphql@15`
DefinitelyTyped/DefinitelyTyped pull request #58602
Opened 2022-02-04 08:59 UTC by SimenB

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:[ <<url here>>](https://github.com/jaydenseric/graphql-upload/blob/0cbc9d90a181ace59be279fee4c3b269c47d1cbe/package.json#L46-L48)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

The range should as the link above suggest probably be even wider. But at least this reverts the breaking change introduced by #58039. My project is stuck at v15 for now

2022-02-06 09:00 UTC, martin-badin requested changes

2022-02-06 09:00 UTC, martin-badin commented on types/graphql-upload/package.json
> +    "graphql": "^15.3.0 || ^16.2.0"
Could you use the same version definition?
```suggestion
    "graphql": "0.13.1 - 16"
```

2022-02-06 10:49 UTC, martin-badin approved these changes

2022-02-17 17:51 UTC, mike-marcacci approved these changes

2022-02-17 17:58 UTC, SimenB commented
Ready to merge

2022-02-17 17:59 UTC, merged