[is-valid-glob] Bugfix: Function can accept no arguments
DefinitelyTyped/DefinitelyTyped pull request #58729
Opened 2022-02-12 00:52 UTC by joshuaharry

Please fill in this template.
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
See https://github.com/micromatch/is-valid-glob/blob/c18c82999df11133c5946f9a21ef74a0ebf88334/test.js#L18 and https://github.com/micromatch/is-valid-glob/blame/master/README.md#L37

2022-02-26 11:32 UTC, joshuajeschek requested changes
What do you think about this? This way, users are informed that this is not the intended way by getting informed that this will always evaluate to false!

2022-02-26 11:32 UTC, joshuajeschek commented on types/is-valid-glob/index.d.ts
> +declare function isValidGlob(input?: any): input is string | string[];
```suggestion
declare function isValidGlob(input: any): input is string | string[];
declare function isValidGlob(): false;
```

2022-02-26 11:32 UTC, joshuajeschek commented on types/is-valid-glob/is-valid-glob-tests.ts
> +isValidGlob(); // $ExpectType boolean
```suggestion
isValidGlob(); // $ExpectType false
```

2022-02-27 18:52 UTC, joshuaharry commented
Great suggestions, thanks!

2022-02-27 18:59 UTC, joshuajeschek approved these changes
Looks good now!

2022-02-27 19:04 UTC, joshuaharry commented
Ready to merge

2022-02-27 19:04 UTC, merged