feat(ws): Add support for custom WebSocket
DefinitelyTyped/DefinitelyTyped pull request #58772
Opened 2022-02-14 15:06 UTC by mglyzin

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2022-02-17 07:40 UTC, vansergen approved these changes

2022-02-17 10:46 UTC, jlalmes approved these changes

2022-02-17 14:29 UTC, vansergen commented on types/ws/ws-tests.ts
> +    });
```suggestion
    });
    webSocketServer.clients.forEach((ws) => {
      // $ExpectType CustomWebSocket
      ws;
      // $ExpectType "foo"
      ws.foo();
    });
```

2022-02-17 21:35 UTC, vansergen commented on types/ws/ws-tests.ts
> +    Array.from(webSocketServer.clients).forEach((ws) => {
for future reference: 
```
ERROR: 332:1   expect                     TypeScript@4.6: Can not match a node to this assertion.
ERROR: 334:1   expect                     TypeScript@4.6: Can not match a node to this assertion.
```

2022-02-18 11:28 UTC, vansergen commented on types/ws/index.d.ts
>          off(event: string | symbol, listener: (this: Server, ...args: any[]) => void): this;
```suggestion
        off(event: "connection", cb: (this: Server<T>, socket: T, request: IncomingMessage) => void): this;
        off(event: "error", cb: (this: Server<T>, error: Error) => void): this;
        off(event: "headers", cb: (this: Server<T>, headers: string[], request: IncomingMessage) => void): this;
        off(event: "close" | "listening", cb: (this: Server<T>) => void): this;
        off(event: string | symbol, listener: (this: Server<T>, ...args: any[]) => void): this;
```

2022-02-18 11:28 UTC, vansergen commented on types/ws/index.d.ts
>          once(event: string | symbol, listener: (...args: any[]) => void): this;
```suggestion
        once(event: "connection", cb: (this: Server<T>, socket: T, request: IncomingMessage) => void): this;
        once(event: "error", cb: (this: Server<T>, error: Error) => void): this;
        once(event: "headers", cb: (this: Server<T>, headers: string[], request: IncomingMessage) => void): this;
        once(event: "close" | "listening", cb: (this: Server<T>) => void): this;
        once(event: string | symbol, listener: (this: Server<T>, ...args: any[]) => void): this;
```

2022-02-18 11:28 UTC, vansergen commented on types/ws/index.d.ts
>          on(event: string | symbol, listener: (this: Server, ...args: any[]) => void): this;
```suggestion
        on(event: "error", cb: (this: Server<T>, error: Error) => void): this;
        on(event: "headers", cb: (this: Server<T>, headers: string[], request: IncomingMessage) => void): this;
        on(event: "close" | "listening", cb: (this: Server<T>) => void): this;
        on(event: string | symbol, listener: (this: Server<T>, ...args: any[]) => void): this;
```

2022-02-18 18:40 UTC, vansergen approved these changes

2022-02-18 18:40 UTC, vansergen commented on types/ws/index.d.ts
>          once(event: string | symbol, listener: (...args: any[]) => void): this;
```suggestion
        once(event: string | symbol, listener: (this: Server<T>, ...args: any[]) => void): this;
```

2022-02-18 18:46 UTC, jlalmes approved these changes

2022-02-18 19:29 UTC, vansergen approved these changes

2022-02-19 03:26 UTC, jlalmes commented
LGTM, let's get this merged!

2022-02-19 04:34 UTC, k-yle requested changes
this has conflicts now that #58753 has been merged. Could you please rebase or merge master into this branch

2022-02-19 11:46 UTC, vansergen requested changes

2022-02-19 11:46 UTC, vansergen commented on types/ws/ws-tests.ts
> +    webSocketServer.on('upgrade', (request, socket, head) => {
```suggestion
    const server = new http.Server();
    server.on('upgrade', (request, socket, head) => {
```

2022-02-20 09:22 UTC, vansergen approved these changes
LGTM

2022-02-20 11:18 UTC, jlalmes approved these changes

2022-02-20 13:24 UTC, vansergen reviewed
nit ([#L1](https://github.com/mglyzin/DefinitelyTyped/blob/e9c0f22c872989e3dfc0b7184e6c8f1b702189bb/types/ws/index.d.ts#L1)): 

```typescript
// Type definitions for ws 8.5
```

Ref: [ws@8.5.0](https://github.com/websockets/ws/releases/tag/8.5.0)

2022-02-20 20:23 UTC, k-yle approved these changes

2022-02-21 15:08 UTC, jlalmes commented
Hi all, this PR is now blocking us - what need to happen next so that we can merge & release this?

2022-02-21 18:46 UTC, k-yle commented
@jlalmes since this is a critical package it's waiting in the queue for someone from Microsoft to review

2022-02-22 04:57 UTC, cwadrupldijjit commented
I assume that also means it could be ready tomorrow, as today was a US
holiday.  When they review it, it'll go quick.

On Mon, Feb 21, 2022, 11:46 AM Kyℓe Hensel ***@***.***> wrote:

> @jlalmes <https://github.com/jlalmes> since this is a critical package
> it's waiting in the queue for someone from Microsoft to review
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58772#issuecomment-1047149193>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADKN6MCNT6FAUY4VO4462Y3U4KCCBANCNFSM5OLWJ7WA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-02-23 19:02 UTC, jakebailey approved these changes

2022-02-23 19:52 UTC, mglyzin commented
> 
Ready to merge

2022-02-23 20:03 UTC, jakebailey approved these changes

2022-02-23 20:22 UTC, k-yle approved these changes

2022-02-23 20:24 UTC, vansergen requested changes

2022-02-23 20:24 UTC, vansergen commented on types/ws/index.d.ts
```suggestion

     constructor(address: null);
```

2022-02-23 21:18 UTC, vansergen requested changes

2022-02-23 21:18 UTC, vansergen commented on types/ws/index.d.ts
> +    constructor(address: string | null, options?: WebSocket.ClientOptions | ClientRequestArgs);
```suggestion
    constructor(address: string | URL, options?: WebSocket.ClientOptions | ClientRequestArgs);
```

2022-02-23 22:24 UTC, jlalmes approved these changes

2022-02-24 07:07 UTC, vansergen approved these changes

2022-02-24 21:23 UTC, mglyzin commented
What's going on with this merge request? When it will be merged?

2022-02-24 21:26 UTC, jakebailey commented
I was waiting to see if you'd address @vansergen's outstanding comments, but they approved the PR so I'll do so as well.

2022-02-24 21:27 UTC, jakebailey approved these changes

2022-02-24 21:30 UTC, k-yle approved these changes

2022-02-24 21:31 UTC, jakebailey commented
Very weird that the bot re-pinged when nothing changed and it had already pinged. Oh well...

2022-02-24 21:35 UTC, k-yle commented
Ready to merge

2022-02-24 21:36 UTC, merged