[ws]
DefinitelyTyped/DefinitelyTyped pull request #58874
Opened 2022-02-20 03:35 UTC by smn-is

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketaddress-protocols-options>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-02-20 14:13 UTC, vansergen requested changes
@smn-is Could you add some tests for those options?

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        event: 'unexpected-response',
```suggestion
        event: "unexpected-response",
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +    off(event: 'ping' | 'pong', listener: (this: WebSocket, data: Buffer) => void): this;
```suggestion
    off(event: "close", listener: (this: WebSocket, code: number, reason: Buffer) => void): this;
    off(event: "error", listener: (this: WebSocket, err: Error) => void): this;
    off(event: "upgrade", listener: (this: WebSocket, request: IncomingMessage) => void): this;
    off(event: "message", listener: (this: WebSocket, data: WebSocket.RawData, isBinary: boolean) => void): this;
    off(event: "open", listener: (this: WebSocket) => void): this;
    off(event: "ping" | "pong", listener: (this: WebSocket, data: Buffer) => void): this;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        event: 'unexpected-response',
```suggestion
        event: "unexpected-response",
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +    addListener(event: 'ping' | 'pong', listener: (data: Buffer) => void): this;
```suggestion
    addListener(event: "close", listener: (code: number, reason: Buffer) => void): this;
    addListener(event: "error", listener: (err: Error) => void): this;
    addListener(event: "upgrade", listener: (request: IncomingMessage) => void): this;
    addListener(event: "message", listener: (data: WebSocket.RawData, isBinary: boolean) => void): this;
    addListener(event: "open", listener: () => void): this;
    addListener(event: "ping" | "pong", listener: (data: Buffer) => void): this;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        event: 'unexpected-response',
```suggestion
        event: "unexpected-response",
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +    removeListener(event: 'ping' | 'pong', listener: (data: Buffer) => void): this;
```suggestion
    removeListener(event: "close", listener: (code: number, reason: Buffer) => void): this;
    removeListener(event: "error", listener: (err: Error) => void): this;
    removeListener(event: "upgrade", listener: (request: IncomingMessage) => void): this;
    removeListener(event: "message", listener: (data: WebSocket.RawData, isBinary: boolean) => void): this;
    removeListener(event: "open", listener: () => void): this;
    removeListener(event: "ping" | "pong", listener: (data: Buffer) => void): this;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        event: 'unexpected-response',
```suggestion
        event: "unexpected-response",
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        generateMask?: (mask: Buffer) => void | undefined;
```suggestion
        generateMask?: (mask: Buffer) => void;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +            | undefined;
```suggestion
        zlibDeflateOptions?: {
            flush?: number | undefined;
            finishFlush?: number | undefined;
            chunkSize?: number | undefined;
            windowBits?: number | undefined;
            level?: number | undefined;
            memLevel?: number | undefined;
            strategy?: number | undefined;
            dictionary?: Buffer | Buffer[] | DataView | undefined;
            info?: boolean | undefined;
        } | undefined;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        on(event: 'close' | 'listening', cb: (this: Server) => void): this;
```suggestion
        on(event: "connection", cb: (this: Server, socket: WebSocket, request: IncomingMessage) => void): this;
        on(event: "error", cb: (this: Server, error: Error) => void): this;
        on(event: "headers", cb: (this: Server, headers: string[], request: IncomingMessage) => void): this;
        on(event: "close" | "listening", cb: (this: Server) => void): this;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        once(event: 'close' | 'listening', cb: (this: Server) => void): this;
```suggestion
        once(event: "connection", cb: (this: Server, socket: WebSocket, request: IncomingMessage) => void): this;
        once(event: "error", cb: (this: Server, error: Error) => void): this;
        once(event: "headers", cb: (this: Server, headers: string[], request: IncomingMessage) => void): this;
        once(event: "close" | "listening", cb: (this: Server) => void): this;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        off(event: 'close' | 'listening', cb: (this: Server) => void): this;
```suggestion
        off(event: "connection", cb: (this: Server, socket: WebSocket, request: IncomingMessage) => void): this;
        off(event: "error", cb: (this: Server, error: Error) => void): this;
        off(event: "headers", cb: (this: Server, headers: string[], request: IncomingMessage) => void): this;
        off(event: "close" | "listening", cb: (this: Server) => void): this;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        addListener(event: 'close' | 'listening', cb: () => void): this;
```suggestion
        addListener(event: "connection", cb: (client: WebSocket, request: IncomingMessage) => void): this;
        addListener(event: "error", cb: (err: Error) => void): this;
        addListener(event: "headers", cb: (headers: string[], request: IncomingMessage) => void): this;
        addListener(event: "close" | "listening", cb: () => void): this;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        removeListener(event: 'close' | 'listening', cb: () => void): this;
```suggestion
        removeListener(event: "connection", cb: (client: WebSocket) => void): this;
        removeListener(event: "error", cb: (err: Error) => void): this;
        removeListener(event: "headers", cb: (headers: string[], request: IncomingMessage) => void): this;
        removeListener(event: "close" | "listening", cb: () => void): this;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +import { EventEmitter } from 'events';
```suggestion
import { EventEmitter } from "events";
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +import { ZlibOptions } from 'zlib';
```suggestion
} from "http";
import { Server as HTTPSServer } from "https";
import { Duplex, DuplexOptions } from "stream";
import { SecureContextOptions } from "tls";
import { URL } from "url";
import { ZlibOptions } from "zlib";
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +    binaryType: 'nodebuffer' | 'arraybuffer' | 'fragments';
```suggestion
    binaryType: "nodebuffer" | "arraybuffer" | "fragments";
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        },
```suggestion
        options: { mask?: boolean | undefined; binary?: boolean | undefined; compress?: boolean | undefined; fin?: boolean | undefined },
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        method: 'message',
```suggestion
        method: "message",
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        method: 'close',
```suggestion
        method: "close",
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        method: 'error',
```suggestion
        method: "error",
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        method: 'open',
```suggestion
        method: "open",
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +    removeEventListener(method: 'open', cb: (event: WebSocket.Event) => void): void;
```suggestion
    removeEventListener(method: "message", cb: (event: WebSocket.MessageEvent) => void): void;
    removeEventListener(method: "close", cb: (event: WebSocket.CloseEvent) => void): void;
    removeEventListener(method: "error", cb: (event: WebSocket.ErrorEvent) => void): void;
    removeEventListener(method: "open", cb: (event: WebSocket.Event) => void): void;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +    on(event: 'ping' | 'pong', listener: (this: WebSocket, data: Buffer) => void): this;
```suggestion
    on(event: "close", listener: (this: WebSocket, code: number, reason: Buffer) => void): this;
    on(event: "error", listener: (this: WebSocket, err: Error) => void): this;
    on(event: "upgrade", listener: (this: WebSocket, request: IncomingMessage) => void): this;
    on(event: "message", listener: (this: WebSocket, data: WebSocket.RawData, isBinary: boolean) => void): this;
    on(event: "open", listener: (this: WebSocket) => void): this;
    on(event: "ping" | "pong", listener: (this: WebSocket, data: Buffer) => void): this;
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +        event: 'unexpected-response',
```suggestion
        event: "unexpected-response",
```

2022-02-20 14:13 UTC, vansergen commented on types/ws/index.d.ts
> +    once(event: 'ping' | 'pong', listener: (this: WebSocket, data: Buffer) => void): this;
```suggestion
    once(event: "close", listener: (this: WebSocket, code: number, reason: Buffer) => void): this;
    once(event: "error", listener: (this: WebSocket, err: Error) => void): this;
    once(event: "upgrade", listener: (this: WebSocket, request: IncomingMessage) => void): this;
    once(event: "message", listener: (this: WebSocket, data: WebSocket.RawData, isBinary: boolean) => void): this;
    once(event: "open", listener: (this: WebSocket) => void): this;
    once(event: "ping" | "pong", listener: (this: WebSocket, data: Buffer) => void): this;
```

2022-02-20 19:53 UTC, k-yle requested changes
all these formatting changes are going to cause conflicts with the other two open PRs. If you want to get this merged faster, please remove the formatting/style changes

2022-02-20 20:01 UTC, k-yle approved these changes
thanks!

2022-02-20 20:16 UTC, vansergen approved these changes

2022-02-23 19:07 UTC, jakebailey approved these changes

2022-02-23 19:09 UTC, jakebailey commented on types/ws/index.d.ts
> +        generateMask?: (mask: Buffer) => void;
Should this be:

```suggestion
        generateMask?(mask: Buffer): void;
```

To match the other function in this interfaces below / other interfaces?

2022-02-23 19:42 UTC, jakebailey approved these changes

2022-02-23 19:52 UTC, smn-is commented
Ready to merge

2022-02-23 19:52 UTC, merged