[ramda] fix: allow readonly in `fromPairs`
DefinitelyTyped/DefinitelyTyped pull request #59161
Opened 2022-03-06 10:41 UTC by somebody1234

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes ([Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEpwGZQiOAcimRABNlCBuAKBoGMIA7VeZKKOAXjgG1DKAGiIAjQsML1CAXRTpGLGLQbNWcGAFM1PDADpc+AArJgUVAAp2UXSGRhz54JpDDgASm4A+PsFfPZaHAKrG5uVEA)):
```ts
import * as R from 'ramda';
const arr = ['a', 'b', 'c'] as const;
const currentlyFails = R.fromPairs(arr.map((item, i) => [i, item] as const));
```
This is a contrived example, but it shouldn't be a breaking change, plus there _are_ those who want this to work

2022-03-06 10:46 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. collectBy
1. modify
1. modifyPath
1. partialObject
1. on

<details>
<summary>as well as these 5 other properties...</summary>
<p>promap, sequence, splitWhenever, unwind, whereAny</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f4d3a9d3b2266cfba133a217d4ae20e328eeb4d3
</p>

2022-03-06 11:50 UTC, somebody1234 commented
not sure what's up with the playground plugin - oddly it's trying to load `index.d.ts` as `file://file:///node_modules/ramda//index.d.ts` (same with `tools.d.ts`) - everything else is loading normally as ` file:///node_modules/@types/ramda/path/to/file.d.ts`

2022-03-07 00:00 UTC, adispring requested changes

2022-03-07 00:00 UTC, adispring commented on types/ramda/test/fromPairs-tests.ts
> +  R.fromPairs([['a', 1], ['b', 2], ['c', 3]] as const); // => {a: 1, b: 2, c: 3}
> Use $ExpectType to assert that an expression is of a given type, and $ExpectError to assert that a compile error.

Can you add a `$ExpectType` comment here?

2022-03-07 01:52 UTC, adispring approved these changes

2022-03-07 02:01 UTC, essenmitsosse approved these changes

2022-03-07 02:52 UTC, somebody1234 commented
Ready to merge

2022-03-07 02:53 UTC, merged