SuperTest: Fixes return type of host method
DefinitelyTyped/DefinitelyTyped pull request #59183
Opened 2022-03-07 23:47 UTC by lourd

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: [source code](https://github.com/visionmedia/supertest/blob/a70c1a09c9b4ee47b77b6b3f32f77fc7eee24107/lib/agent.js#L39-L42) and [relevant source unit test](https://github.com/visionmedia/supertest/blob/a70c1a09c9b4ee47b77b6b3f32f77fc7eee24107/test/supertest.js#L975-L977).

The `host` method of the `supertest` library has had an incorrect definition of the `host` method available. It's been incorrectly available on the default export

```ts
import request from 'supertest'

const app = express()
request(app).host('foo.com') // does not actually exist
```

And the return type has been incorrect, indicating that a request was being returned instead of the `SuperTest` object.

This PR fixes the return type and gets rid of some generic usage that wasn't necessary.

2022-03-08 00:41 UTC, lourd commented
The part of the tests that are failing don't have anything to do with my change:

```
The declaration doesn't match the JavaScript module 'supertest'. Reason: The JavaScript module exports a property named 'Test', which is missing from the declaration module.
```

The `supertest` module has exported a symbol named `Test` for almost a decade now, it's nothing new. I looked through the [source for `Test`](https://github.com/visionmedia/supertest/blob/master/lib/test.js#L15) to see how hard it would be, and it would be pretty significant — it would require changing/fixing the types for `superagent`, too. The `superagent` types show `Request` as an interface, but it's actually a class that `Test` extends.

Hopefully y'all understand and that failure won't block getting my change merged in 🙏

2022-03-08 01:49 UTC, lourd commented on types/supertest/tslint.json
> +        "no-outside-dependencies": false,
Not sure why this is needed, the supertest types don't import from `buffer`. The only direction I could find in resolving it was https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49372.

2022-03-10 04:33 UTC, RyanCavanaugh requested changes
Waiting on 'TODO'

2022-03-10 05:13 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## supertest ([<kbd>unpkg</kbd>](https://unpkg.com/browse/supertest@latest/))
was missing the following properties:
1. Test
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 24b235314c4c66cbceae9cb9be0d8b706cb36d59
</p>

2022-03-10 05:18 UTC, lourd commented
I misunderstood the warning from danger in the CI logs as an error. There's no need to define any new symbols, I've deleted the todo.

2022-03-21 15:56 UTC, RyanCavanaugh approved these changes

2022-03-21 16:00 UTC, merged