Update @ckeditor/ckeditor5-core to v33
DefinitelyTyped/DefinitelyTyped pull request #59196
Opened 2022-03-08 22:53 UTC by fedemp

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
https://github.com/ckeditor/ckeditor5/blob/72f503139a8fdf40b41cf26960a94b725f409338/packages/ckeditor5-core/src/index.js#L30
https://github.com/ckeditor/ckeditor5/blob/72f503139a8fdf40b41cf26960a94b725f409338/packages/ckeditor5-core/src/command.js#L57
https://github.com/ckeditor/ckeditor5/blob/72f503139a8fdf40b41cf26960a94b725f409338/packages/ckeditor5-core/src/command.js#L98
https://github.com/ckeditor/ckeditor5/blob/72f503139a8fdf40b41cf26960a94b725f409338/packages/ckeditor5-core/src/command.js#L113
https://github.com/ckeditor/ckeditor5/blob/72f503139a8fdf40b41cf26960a94b725f409338/packages/ckeditor5-core/src/editor/editorconfig.jsdoc#L168
https://github.com/ckeditor/ckeditor5/blob/72f503139a8fdf40b41cf26960a94b725f409338/packages/ckeditor5-core/src/editor/editorconfig.jsdoc#L314
https://github.com/ckeditor/ckeditor5/blob/72f503139a8fdf40b41cf26960a94b725f409338/packages/ckeditor5-core/src/editor/editorui.js#L275
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-03-17 20:44 UTC, DangerBotOSS commented on types/ckeditor__ckeditor5-core/src/command.d.ts
> +	/**
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/ckeditor__ckeditor5-core/src/command.d.ts;
  Line: 138;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-03-17 20:44 UTC, DangerBotOSS commented on types/ckeditor__ckeditor5-core/src/editor/editorui.d.ts
> +     * 	top: 50,
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/ckeditor__ckeditor5-core/src/editor/editorui.d.ts;
  Line: 45;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-03-17 20:44 UTC, DangerBotOSS commented on types/ckeditor__ckeditor5-list/src/checktodolistcommand.d.ts
> +	/**
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/ckeditor__ckeditor5-list/src/checktodolistcommand.d.ts;
  Line: 17;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-03-18 20:48 UTC, gabritto requested changes
Looks good, but I noticed the versions of the packages besides the core one weren't updated to 33. Shouldn't they be?

2022-03-18 21:04 UTC, fedemp commented
> Looks good, but I noticed the versions of the packages besides the core one weren't updated to 33. Shouldn't they be?

There are some packages that were updated when v33 was released, and that I haven't got the time to update.

If you mean that every packages should be updated to v33, that's not needed. When you install the type definition, it will install whatever is the latest version, and there may be no changes between currently published definitions and upstream.

2022-03-18 23:41 UTC, gabritto approved these changes

2022-03-19 00:13 UTC, fedemp commented
Ready to merge

2022-03-19 00:14 UTC, merged