Update @ckeditor/ckeditor5-widget to v32
DefinitelyTyped/DefinitelyTyped pull request #59190
Opened 2022-03-08 18:21 UTC by fedemp

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2022-03-08 18:33 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ckeditor__ckeditor5-widget ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ckeditor__ckeditor5-widget@latest/))
was missing the following properties:
1. centeredBalloonPositionForLongWidgets
1. centeredBalloonPositionForLongWidgets
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 32262f511c7a580e6c241933a33cbda9a7f50e1c
</p>

2022-03-08 18:46 UTC, fedemp commented
> Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files. The check for missing properties isn't always right, so take this list as advice, not a requirement.
> ## ckeditor__ckeditor5-widget ([unpkg](https://unpkg.com/browse/ckeditor__ckeditor5-widget@latest/))
> 
> was missing the following properties:
> 
>     1. centeredBalloonPositionForLongWidgets
> 
>     2. centeredBalloonPositionForLongWidgets
> 
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [32262f5](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/32262f511c7a580e6c241933a33cbda9a7f50e1c)

Fixed. I forgot to update the header in `index.d.ts`

2022-03-09 14:34 UTC, martin-badin requested changes
Please update the version as well. Sorry, I see

2022-03-09 14:35 UTC, martin-badin approved these changes

2022-03-09 14:35 UTC, martin-badin commented on types/ckeditor__ckeditor5-widget/index.d.ts
> +// Type definitions for @ckeditor/ckeditor5-widget 32.0
the latest version is 33

2022-03-09 18:48 UTC, martin-badin approved these changes

2022-03-09 21:08 UTC, peterblazejewicz approved these changes

2022-03-10 00:04 UTC, fedemp commented
Ready to merge

2022-03-10 00:05 UTC, merged