add preserveTrailingSpaces option of Style
DefinitelyTyped/DefinitelyTyped pull request #59244
Opened 2022-03-12 15:12 UTC by loulin

It should be the same as option `preserveLeadingSpaces`, [See: ](https://github.com/bpampuch/pdfmake/blob/de29c549fab7f9613573bb3d2fbbb17a73ee77af/src/TextInlines.js#L153)

2022-03-12 15:17 UTC, andipaetzold requested changes
Looks good.

Could you just add a test to `test/pdfmake-examples-tests.ts` like it's done for `preserveLeadingSpaces`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bd1c91c1f0e3797cac83d5962ab7b01a7c93ffe7/types/pdfmake/test/pdfmake-examples-tests.ts#L1413-L1422

2022-03-14 02:50 UTC, loulin commented
Thanks for your hint, just added a simple test.

2022-03-14 07:14 UTC, andipaetzold approved these changes
👍

2022-03-14 08:21 UTC, andipaetzold commented
Ready to merge

2022-03-14 08:22 UTC, merged