autocannon: add printResult definition
DefinitelyTyped/DefinitelyTyped pull request #59322
Opened 2022-03-17 16:44 UTC by RafaelGSS

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

2022-03-17 16:59 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## autocannon ([<kbd>unpkg</kbd>](https://unpkg.com/browse/autocannon@latest/))
was missing the following properties:
1. start
1. parseArguments
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 12b11735114cc6a910833a5f005af93030bbec25
</p>

2022-03-17 21:27 UTC, joshuajeschek requested changes

2022-03-17 21:27 UTC, joshuajeschek commented on types/autocannon/index.d.ts
> +    function printResult(result: Result, options?: TrackingOptions): string;
I don't think that TrackingOptions is accurate here, if you take a look at the documentation, you can see that `renderProgressBar` and `progressBarString` are not listed as options for printResult:
[printResult Documentation](https://github.com/mcollina/autocannon#autocannonprintresultresultobject-opts)

2022-03-19 16:31 UTC, joshuajeschek approved these changes
looking good now!

2022-03-19 19:22 UTC, RafaelGSS commented
Ready to merge

2022-03-19 19:23 UTC, merged