error-cause: Update types to match TS lib
DefinitelyTyped/DefinitelyTyped pull request #59354
Opened 2022-03-19 18:34 UTC by conartist6

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/microsoft/TypeScript/blob/ae582a22ee1bb052e19b7c1bc4cac60509b574e0/src/lib/es2022.error.d.ts

The initial choice of representing cause as `unknown` was made to be conservative, but now it breaks these defs in environments with typescript's `es2022` libs turned on.

2022-03-19 19:38 UTC, ljharb requested changes

2022-03-19 19:38 UTC, ljharb commented on types/error-cause/Error.d.ts
> +    cause: ErrorType | undefined;
This is wildly incorrect. Any JS value can be thrown, and the builtin error types are ibcirrrct if they restrict this in any way.

2022-03-19 19:39 UTC, ljharb commented
In other words, the bug is in the base error cause types - this package’s types are correct.

2022-03-19 19:40 UTC, conartist6 commented
Well let's see what they say over on that repo...

2022-03-19 20:20 UTC, conartist6 commented
Are you sure it's relevant how loose the `throw` mechanic is? I know `error.cause` could contain anything, but let's say write `try { ... } catch(e) {}` -- I have to consider the fact that, say, e might be `null` or `undefined` because that could be true and I would still be on the exception pathway. But an error with a `cause` property doesn't have that distinction. When `error.cause` is `null` or `undefined` handling code will simply be treat it as an error with no underlying cause.

I think it's a pretty nuanced trade off how aggressively Typescript would force people to check for some of the really weird conditions that are possible. Their current answer is "not aggressively" as they just let errors be `any`.

My impression is that it's not super important, because it's always a good idea anyway to delegate working with error structures to highly defensive code, which is the kind that should be shared and not copy-pasted about.

2022-03-19 20:27 UTC, ljharb commented
It was an explicit and intentional part of the cause design that it can include, for example, a string, but also any caught value.

an error with a cause of null might have been caused by trying to access a property off of null, for example. It’s always up to the producer of the error, and TS simply can’t make those assumptions at a language level.

2022-04-12 02:53 UTC, ljharb commented
bump

2022-05-05 07:04 UTC, ljharb commented
bump; pending https://github.com/microsoft/TypeScript/issues/48098

2022-05-28 14:08 UTC, ljharb commented
bump

2022-06-25 03:57 UTC, ljharb commented
bump

2022-08-05 03:10 UTC, closed without merging

2022-08-05 03:36 UTC, ljharb commented
This sucks, activity is irrelevant and this PR could be mergeable if rebased.

2022-08-05 11:12 UTC, conartist6 commented
I thought we didn't actually need or want these changes after https://github.com/microsoft/TypeScript/pull/49639 was merged...

2022-08-05 14:47 UTC, ljharb commented
ah, you’re right; still not stoked on the faceless closure tho