[happyguestmx__web-utilities] Provide types for @happyguestmx/web-utilities
DefinitelyTyped/DefinitelyTyped pull request #59523
Opened 2022-03-28 22:19 UTC by HappyGuest

Provide types for [@happyguestmx/web-utilities](https://www.npmjs.com/package/@happyguestmx/web-utilities)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2022-03-29 17:14 UTC, andrewbranch requested changes

2022-03-29 17:14 UTC, andrewbranch commented on types/happyguestmx__web-utilities/index.d.ts
> +declare module '@happyguestmx/web-utilities' {
There’s no need for this wrapper.

2022-03-30 16:02 UTC, andrewbranch requested changes
Looks good after removing package.json

2022-03-30 16:02 UTC, andrewbranch commented on types/happyguestmx__web-utilities/package.json
> +}
Sorry I missed this, you can delete this file too.

2022-03-30 23:26 UTC, andrewbranch approved these changes

2022-03-31 17:53 UTC, Alvarez-P commented
Ready to merge

2022-03-31 18:22 UTC, andrewbranch commented
@typescript-bot we’re waiting

2022-03-31 18:23 UTC, andrewbranch commented
Oh, @Alvarez-P you can’t be ready to merge because you’re not @HappyGuest

2022-03-31 18:24 UTC, merged

2022-03-31 18:24 UTC, HappyGuest commented
Ready to merge

2022-03-31 18:25 UTC, HappyGuest commented
> Oh, @Alvarez-P you can’t be ready to merge because you’re not @HappyGuest

ty