[jasmine] Use type-safe spies for spyOnProperty
DefinitelyTyped/DefinitelyTyped pull request #59629
Opened 2022-03-31 20:44 UTC by rslawik

Same as #59463 but for v3.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://jasmine.github.io/api/edge/global.html#spyOnProperty

2022-04-01 09:05 UTC, chivesrs approved these changes

2022-04-05 23:40 UTC, rslawik commented
@chivesrs Do you know who else needs to approve this PR? It is effectively a backport of #59463 to v3/, so it should be a quick review.

2022-04-06 09:42 UTC, chivesrs commented
You need to wait for a DT (this repository) maintainer.

2022-04-07 16:50 UTC, rbuckton requested changes

2022-04-07 16:50 UTC, rbuckton commented on types/jasmine/v3/index.d.ts
> + declare function spyOnProperty<T, K extends keyof T = keyof T>(
nit: indentation

```suggestion
declare function spyOnProperty<T, K extends keyof T = keyof T>(
```

2022-04-08 08:56 UTC, chivesrs approved these changes

2022-04-13 19:25 UTC, jakebailey approved these changes

2022-04-13 19:52 UTC, rslawik commented
Ready to merge

2022-04-13 19:52 UTC, merged