Update mParticle WEB SDK return types and parameters
DefinitelyTyped/DefinitelyTyped pull request #59832
Opened 2022-04-11 20:16 UTC by alexs-mparticle

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.mparticle.com/developers/sdk/web/core-apidocs/classes/mParticle%20&%20mParticleInstance.html

2022-04-11 20:46 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## mparticle__web-sdk ([<kbd>unpkg</kbd>](https://unpkg.com/browse/mparticle__web-sdk@latest/))
was missing the following properties:
1. Store
1. isIOS
1. config
1. configurePixel
1. generateHash

<details>
<summary>as well as these 40 other properties...</summary>
<p>addForwarder, wrap, isGeneratorFunction, mark, awrap, AsyncIterator, async, keys, values, ApplicationInformationOsEnum, ApplicationStateTransitionEventEventTypeEnum, ApplicationStateTransitionEventDataApplicationTransitionTypeEnum, BatchEnvironmentEnum, BreadcrumbEventEventTypeEnum, CommerceEventEventTypeEnum, CommerceEventDataCustomEventTypeEnum, CrashReportEventEventTypeEnum, CustomEventEventTypeEnum, CustomEventDataCustomEventTypeEnum, DeviceCurrentStateDeviceOrientationEnum, DeviceCurrentStateStatusBarOrientationEnum, DeviceInformationPlatformEnum, EventTypeEnum, IdentityTypeEnum, NetworkPerformanceEventEventTypeEnum, OptOutEventEnum, ProductActionActionEnum, ProfileEventEventTypeEnum, ProfileEventDataProfileEventTypeEnum, PromotionActionActionEnum, PushMessageEventEventTypeEnum, PushMessageEventDataPushMessageTypeEnum, PushMessageEventDataApplicationStateEnum, PushMessageEventDataPushMessageBehaviorEnum, PushRegistrationEventEventTypeEnum, SessionEndEventEventTypeEnum, SessionStartEventEventTypeEnum, SourceInformationChannelEnum, UserAttributeChangeEventEventTypeEnum, UserIdentityChangeEventEventTypeEnum</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 00b8868f16d78cd5433782afa219d6416dcee945
</p>

2022-04-12 13:15 UTC, rmi22186 commented on types/mparticle__web-sdk/index.d.ts
> +    // getUserIdentities: () => UserIdentities;
@alexs-mparticle - this commented former code should be removed

2022-04-12 13:17 UTC, rmi22186 requested changes
Just the one comment removal, then we are good to merge

2022-04-12 15:47 UTC, rmi22186 approved these changes

2022-04-12 16:07 UTC, rmi22186 commented
Ready to merge

2022-04-12 16:07 UTC, merged