PrivateKey.sign can take hex-string as md.
DefinitelyTyped/DefinitelyTyped pull request #59858
Opened 2022-04-12 21:32 UTC by petertorelli

If the message is already hashed, the raw bytes can be passed
in as using forge.utils.hexToBytes(hash) which returns a byte
string.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: [This code link shows that encrypt takes a byte string](https://github.com/digitalbazaar/forge/blob/2bb97afb5058285ef09bcf1d04d6bd6b87cffd58/lib/rsa.js#L517)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2022-04-20 16:32 UTC, petertorelli commented
Any update?

2022-04-21 18:52 UTC, joeflateau requested changes
I'm not sure this is testing your change? `forge.util.hexToBytes` returns a byte array, not a string. You should also call `sign` with a string in the first parameter. Further, I'm having difficulty determining whether that method actually does accept a string or not by reading the source code. Can you provide a docs link or a sandbox or something to show that a string is actually valid there?

2022-04-21 19:47 UTC, petertorelli commented
Hi @joeflateau,

Without the modification `| string` this code generates a TS error, even though the code fine. A ByteStringBuffer reduces to a string and the TS compiler realizes that. If we don't use PCKS1v1.5 encoding, forge treats the message digest as a string, and not a digest. Ironically, I find that this is convoluted because they didn't use typescript. :) `md` switches between a digest and a ByteStringBuffer (aka string) without the slightest comment.

Here is their code walkthrough.

Step 1. Sign devolves to an encrypt, but the scheme for 'NON" is return `md`, which is supposed to be a message digest object but isn't treated that way as we'll see.

```js
  key.sign = function(md, scheme) {
    /* Note: The internal implementation of RSA operations is being
      transitioned away from a PKCS#1 v1.5 hard-coded scheme. Some legacy
      code like the use of an encoding block identifier 'bt' will eventually
      be removed. */


    // private key operation
    var bt = false;


    if(typeof scheme === 'string') {
      scheme = scheme.toUpperCase();
    }


    if(scheme === undefined || scheme === 'RSASSA-PKCS1-V1_5') {
      scheme = {encode: emsaPkcs1v15encode};
      bt = 0x01;
    } else if(scheme === 'NONE' || scheme === 'NULL' || scheme === null) {
      scheme = {encode: function() {return md;}};
      bt = 0x01;
    }


    // encode and then encrypt
    var d = scheme.encode(md, key.n.bitLength());
    return pki.rsa.encrypt(d, key, bt);
  };


  return key;
};
```

Step 2: Encrypt bypasses PKCS#1v1.5 because I selected 'NONE', so instead of calling the encoder, it treats `m` like a ByteStringBuffer:

```js
pki.rsa.encrypt = function(m, key, bt) {
  var pub = bt;
  var eb;


  // get the length of the modulus in bytes
  var k = Math.ceil(key.n.bitLength() / 8);


  if(bt !== false && bt !== true) {
    // legacy, default to PKCS#1 v1.5 padding
    pub = (bt === 0x02);
    eb = _encodePkcs1_v1_5(m, key, bt);
  } else {
    eb = forge.util.createBuffer();
    eb.putBytes(m);
  }
```

Step 3. What happens to the `m` passed to `putBytes()`? it is concatenated to `this.data` of the `ByteStringBuffer`:

```js
/**
 * Puts bytes in this buffer.
 *
 * @param bytes the bytes (as a binary encoded string) to put.
 *
 * @return this buffer.
 */
util.ByteStringBuffer.prototype.putBytes = function(bytes) {
  this.data += bytes;
  this._optimizeConstructedString(bytes.length);
  return this;
};
```

Step 4: notice that `data` is a string, and since the constructor was called with `undefined`, it remains a string.

```js
/**
 * Constructor for a binary string backed byte buffer.
 *
 * @param [b] the bytes to wrap (either encoded as string, one byte per
 *          character, or as an ArrayBuffer or Typed Array).
 */
function ByteStringBuffer(b) {
  // TODO: update to match DataBuffer API


  // the data in this buffer
  this.data = '';
  // the pointer for reading from this buffer
  this.read = 0;


  if(typeof b === 'string') {
    this.data = b;
  } else if(util.isArrayBuffer(b) || util.isArrayBufferView(b)) {
    if(typeof Buffer !== 'undefined' && b instanceof Buffer) {
```

Below isn't really necessary since my strings are small, but the idea is it even performs an optimization on this.data string conversion:

```js
/* Note: This is an optimization for V8-based browsers. When V8 concatenates
  a string, the strings are only joined logically using a "cons string" or
  "constructed/concatenated string". These containers keep references to one
  another and can result in very large memory usage. For example, if a 2MB
  string is constructed by concatenating 4 bytes together at a time, the
  memory usage will be ~44MB; so ~22x increase. The strings are only joined
  together when an operation requiring their joining takes place, such as
  substr(). This function is called when adding data to this buffer to ensure
  these types of strings are periodically joined to reduce the memory
  footprint. */
var _MAX_CONSTRUCTED_STRING_LENGTH = 4096;
util.ByteStringBuffer.prototype._optimizeConstructedString = function(x) {
  this._constructedStringLength += x;
  if(this._constructedStringLength > _MAX_CONSTRUCTED_STRING_LENGTH) {
    // this substr() should cause the constructed string to join
    this.data.substr(0, 1);
    this._constructedStringLength = 0;
  }
};
```

2022-04-21 20:09 UTC, joeflateau commented
I misunderstood the return type of `hexToBytes`. I was thinking that it returned an array of numbers/bytes rather than returning a string, my mistake. But please type it as `Bytes` (from line 28) rather than `string` to match `hexToBytes`. Even though `Bytes` is simply an alias of `string` it helps express intent a little better.

2022-04-21 20:13 UTC, petertorelli commented
Ah good point, that is more consistent with the existing types. Thanks, @joeflateau, I just pushed the update.

2022-04-21 20:20 UTC, joeflateau commented
looks good, thank you! 🤝

2022-04-21 20:20 UTC, joeflateau approved these changes

2022-04-21 20:23 UTC, petertorelli commented
Ready to merge

2022-04-21 20:24 UTC, merged