Add `subscribeRequestTimeout` to `PubnubConfig`
DefinitelyTyped/DefinitelyTyped pull request #60003
Opened 2022-04-21 23:39 UTC by yincrash

This variable is described in the PubNub Go SDK here -
https://www.pubnub.com/docs/sdks/go/api-reference/configuration#:~:text=is%20in%20seconds.-,SubscribeRequestTimeout,-int

However it is not in the PubNub JS Documentation, but is accepted and used by the JS SDK API.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-04-22 05:23 UTC, FlorianDr commented
> However it is not in the PubNub JS Documentation, but is accepted and used by the JS SDK API.

I believe it needs reconsideration if a parameter is not official described in by the SDK. It might be an unintentional support that could break in the future. Do you mind double check with Pubnub team? You can just create an issue on the SDK repo and confirm the existence of the parameter. Or even open a PR to document it properly. 

I don't think shadow API should be part of the definitions and it's blocking you to ignore types and pass it in JS.

2022-04-22 19:40 UTC, joshuajeschek approved these changes
👍

2022-04-22 19:43 UTC, joshuajeschek requested changes
sorry, I misclicked, dunno how to remove approval other than this
(sorry for making a mess out of this PR, I just overread the comments)

2022-04-22 19:51 UTC, yincrash commented
I currently just patch-package it so it is not blocking.

In this Github issue https://github.com/pubnub/react/issues/1- a PubNub SDK engineer, @are, suggests using `subscribeRequestTimeout` .

I can open an issue with them as well.

2022-04-23 05:14 UTC, FlorianDr commented
@yincrash Great job! Thank you for raising this issue with the Pubnub team. I hope to see an official statement answer soon. It's not blocking for anymore. Feel free to merge when there is an answer.

2022-04-28 18:25 UTC, joshuajeschek approved these changes
looks like this is ready for approval 👍

2022-04-28 18:38 UTC, yincrash commented
Ready to merge

2022-04-28 18:38 UTC, merged