refactor(ramda): improve map type inference
DefinitelyTyped/DefinitelyTyped pull request #60257
Opened 2022-05-09 10:28 UTC by ycmjason

- better type inference

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

2022-05-09 10:31 UTC, ycmjason commented on types/ramda/test/map-tests.ts
> +    R.map<A | B, void>(
this is actually no longer necessary, but I couldn't do `as A | B` because of the linting rules so I did this instead.

2022-05-09 10:31 UTC, ycmjason commented on types/ramda/index.d.ts
> +    ((obj: Functor<T>) => Functor<U>);
only place i changed.

2022-05-09 13:04 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ramda ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ramda@latest/))
was missing the following properties:
1. modify
1. modifyPath
1. sequence
1. unwind
1. whereAny
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e84cdbfe560e5c10c0e28401e8377da329878c33
</p>

2022-05-20 13:49 UTC, Nicholaiii requested changes
You should consider restoring the original test cases alongside the new ones, to make sure this is just an improvement and not also a regression. Also I'm seeing some unrelated and/or undocumented changes, namely on bind, on, promap and thunkify. Are these linting changes?

2022-06-25 03:06 UTC, closed without merging