[@types/react-native] Add Android Bluetooth Permissions
DefinitelyTyped/DefinitelyTyped pull request #60296
Opened 2022-05-11 21:54 UTC by parkerbo

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [RN PermissionsAndroid](https://reactnative.dev/docs/0.66/permissionsandroid)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

# Add Missing Android Bluetooth Permissions
 - This PR is to add missing permissions for android. Bluetooth permissions were added to RN version 0.66, and android 12 will now require explicitly asking for [bluetooth permissions](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions).

2022-05-11 22:15 UTC, romain-faust approved these changes
LGTM 👍

2022-05-11 22:56 UTC, eps1lon approved these changes

2022-05-11 23:07 UTC, kuasha420 requested changes
Can you add tests?

2022-05-12 13:37 UTC, parkerbo commented
@kuasha420 I was having trouble making sure what was required for adding tests. Please let me know if there is something else required here. Thank you.

2022-05-12 13:40 UTC, iRoachie approved these changes
This is good @parkerbo 💯

2022-05-12 13:51 UTC, eps1lon approved these changes

2022-05-12 18:40 UTC, parkerbo commented
Ready to merge

2022-05-12 18:41 UTC, merged