yup: Support generic value type in TestFunction
DefinitelyTyped/DefinitelyTyped pull request #60354
Opened 2022-05-16 06:54 UTC by compact

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: see below
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

The `test` method has 4 signatures:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ed0884630358b60a792be52421991fdd48483032/types/yup/index.d.ts#L161-L172

Signatures 2 and 3 involve `AssertingTestFunction` - these are out of scope.
Signatures 1 and 4 involve `TestFunction`.
Signature 1 types the `test` function as `TestFunction<T | undefined | null, C>`.
Signature 4 types the `test` function as `TestFunction<unknown, C>` from `BaseTestOptions`. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ed0884630358b60a792be52421991fdd48483032/types/yup/index.d.ts#L503

Signature 4 should behave the same as signature 1, and this PR is an attempt to fix this mismatch by changing `unknown` to `T | undefined | null`.

For reference, the new tests fail with the old type definitions with

```
ERROR: 1160:13  expect  TypeScript@4.7 compile error:
No overload matches this call.
  Overload 1 of 4, '(options: AssertingTestOptions<string, Record<string, any>, object>): StringSchema<string, object>', gave the following error.
    Type '(value: string | null | undefined) => true' is not assignable to type 'AssertingTestFunction<string, object>'.
      Signature '(value: string | null | undefined): true' must be a type predicate.
  Overload 2 of 4, '(options: TestOptions<Record<string, any>, object>): StringSchema<string, object>', gave the following error.
    Type '(value: string | null | undefined) => true' is not assignable to type 'TestFunction<unknown, object>'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'unknown' is not assignable to type 'string | null | undefined'.
ERROR: 1172:9   expect  TypeScript@4.7 compile error:
No overload matches this call.
  Overload 1 of 4, '(options: AssertingTestOptions<any, Record<string, any>, object>): BooleanSchema<any, object>', gave the following error.
    Type '(value: boolean | null | undefined) => true' is not assignable to type 'AssertingTestFunction<any, object>'.
      Signature '(value: boolean | null | undefined): true' must be a type predicate.
  Overload 2 of 4, '(options: TestOptions<Record<string, any>, object>): BooleanSchema<boolean | undefined, object>', gave the following error.
    Type '(value: boolean | null | undefined) => true' is not assignable to type 'TestFunction<unknown, object>'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'unknown' is not assignable to type 'boolean | null | undefined'.
ERROR: 1232:13  expect  TypeScript@4.7 compile error:
No overload matches this call.
  Overload 1 of 4, '(options: AssertingTestOptions<MyInterface, Record<string, any>, object>): ObjectSchema<MyInterface, object>', gave the following error.
    Type '(value: MyInterface | null | undefined) => true' is not assignable to type 'AssertingTestFunction<MyInterface, object>'.
      Signature '(value: MyInterface | null | undefined): true' must be a type predicate.
  Overload 2 of 4, '(options: TestOptions<Record<string, any>, object>): ObjectSchema<MyInterface, object>', gave the following error.
    Type '(value: MyInterface | null | undefined) => true' is not assignable to type 'TestFunction<unknown, object>'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'unknown' is not assignable to type 'MyInterface | null | undefined'.
ERROR: 1235:13  expect  TypeScript@4.7 compile error:
No overload matches this call.
  Overload 1 of 4, '(options: AssertingTestOptions<MyInterface, Record<string, any>, object>): ObjectSchema<MyInterface, object>', gave the following error.
    Type '(value: MyInterface | null | undefined) => Promise<boolean>' is not assignable to type 'AssertingTestFunction<MyInterface, object>'.
      Signature '(value: MyInterface | null | undefined): Promise<boolean>' must be a type predicate.
  Overload 2 of 4, '(options: TestOptions<Record<string, any>, object>): ObjectSchema<MyInterface, object>', gave the following error.
    Type '(value: MyInterface | null | undefined) => Promise<boolean>' is not assignable to type 'TestFunction<unknown, object>'.
      Types of parameters 'value' and 'value' are incompatible.
        Type 'unknown' is not assignable to type 'MyInterface | null | undefined'.
```

2022-05-16 07:12 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## yup ([<kbd>unpkg</kbd>](https://unpkg.com/browse/yup@latest/))
was missing the following properties:
1. ArraySchema
1. BaseSchema
1. BooleanSchema
1. DateSchema
1. MixedSchema

<details>
<summary>as well as these 3 other properties...</summary>
<p>NumberSchema, ObjectSchema, StringSchema</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4bfa6061d610411311607d81e7e819568ef6aa68
</p>

2022-06-06 23:38 UTC, andrewbranch requested changes
I think this looks ok, but it would be really nice to get an owner review here.

2022-06-06 23:38 UTC, andrewbranch commented on types/yup/yup-tests.ts
> +            test: (value: string | null | undefined) => true,
Instead of putting a type annotation on these, can you leave it unannotated and then use an `$ExpectType`?

2022-06-06 23:38 UTC, andrewbranch commented on types/yup/index.d.ts
> +    test(name: string, message: TestOptionsMessage, test: TestFunction<T | undefined | null, C>): this; // TODO
TODO?

2022-06-06 23:38 UTC, andrewbranch commented on types/yup/index.d.ts
> +export type TestOptions<P extends Record<string, any> = {}, C = object, T extends any = {} | null | undefined> =
`extends any` is weird / borderline meaningless—was there a reason for it? Also, `{} | null | undefined` will be properly interchangeable with `unknown` in TypeScript 4.8, FYI.

2022-07-08 03:02 UTC, closed without merging