[pacote] Add overloads for abbreviated metadata
DefinitelyTyped/DefinitelyTyped pull request #60433
Opened 2022-05-19 15:32 UTC by jablko

The npm registry returns [abbreviated metadata](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#abbreviated-metadata-format) unless the [`fullMetadata` option](https://github.com/npm/pacote#options) is `true`. This PR specializes the `packument()` and `manifest()` return types accordingly.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

2022-05-27 20:50 UTC, amcasey reviewed
Sorry, I'm having some trouble understanding the change.  Can you please provide some more context?

2022-05-27 20:50 UTC, amcasey commented on types/libnpmpublish/index.d.ts
> +export function publish(manifest: npm.PackageJson, tarballData: Buffer, options?: fetch.Options): Promise<Response>;
Are manifests the same as package.json?  This seems like a non-trivial change.

2022-05-27 20:50 UTC, amcasey commented on types/pacote/index.d.ts
> +    maintainers: Person[];
Why did this become non-optional?

2022-05-27 20:50 UTC, amcasey commented on types/pacote/index.d.ts
> +    maintainers: Person[];
Maybe this is an unrelated change (fix?)?  It doesn't seem to appear in either Abbreviated interface or in the new tests.

2022-05-27 20:50 UTC, amcasey commented on types/pacote/index.d.ts
> +    maintainers: Person[];
Maybe this is an unrelated change (fix?)?  It doesn't seem to appear in either Abbreviated interface or in the new tests.

2022-05-27 20:50 UTC, amcasey commented on types/pacote/index.d.ts
> +    _id: string;
Why did these become non-optional?

2022-05-27 20:50 UTC, amcasey commented on types/pacote/index.d.ts
> +    _id: string;
Why did these become non-optional?

2022-05-27 20:50 UTC, amcasey commented on types/pacote/pacote-tests.ts
> +pacote.manifest('pacote', { before: new Date() }); // $ExpectType Promise<Manifest & ManifestResult>
Why isn't this an `AbbreviatedManifest`?  Does `before` imply `fullMetadata`?

2022-05-27 20:50 UTC, amcasey commented on types/pacote/pacote-tests.ts
> +pacote.manifest('pacote', { before: new Date() }); // $ExpectType Promise<Manifest & ManifestResult>
Why isn't this an `AbbreviatedManifest`?  Does `before` imply `fullMetadata`?

2022-05-27 21:38 UTC, amcasey requested changes
Setting status for bookkeeping purposes.

2022-05-27 22:45 UTC, jablko commented
@amcasey Thanks for reviewing!

- The `_id`, `_nodeVersion`, `_npmUser`, and `_npmVersion` fields [are always present](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#:~:text=each%20package%20version%20data%20object%20contains%20all%20of%20the%20fields%20in%20the%20abbreviated%20document%2C%20plus%20the%20fields%20listed%20above%20as%20hosted%2C%20plus%20at%20least%20the%20following%3A) in full manifests and always absent in abbreviated ones. Before this change there were single return types for both cases, so those fields were correctly optional, but specialized types make them either required or absent. Ditto the `maintainers` and `time` fields, which are likewise added by the npm registry and always present in full metadata, absent in abbreviated.
- Yep, `before` implies `fullMetadata`: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e1d9e43428d461738f146901b15e0c583cc6f849/types/pacote/index.d.ts#L248-L251
- libnpmpublish [accepts a parsed package.json](https://github.com/npm/cli/tree/latest/workspaces/libnpmpublish#:~:text=manifest%20should%20be%20the%20parsed%20package.json%20for%20the%20package%20being%20published%20(which%20can%20also%20be%20the%20manifest%20pulled%20from%20a%20packument%2C%20a%20git%20repo%2C%20tarball%2C%20etc.)). The `PackageJson` and `Manifest` types are similar, but `Manifest` already requires a `dist` field that libnpmpublish doesn't, so `PackageJson` is the more accurate choice. This PR makes additional `Manifest` fields required (the `time` field, etc.), so not using the correct, `PackageJson` type becomes even more noticeable.

2022-05-27 23:29 UTC, nicolas377 commented
Could you split the change into two PRs? I'd be happy to accept the libnpmpublish PR.

2022-05-28 14:45 UTC, jablko commented
- [x] @nicolas377 Thanks! I've opened https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60566#issue-1251648119 with just the libnpmpublish changes.

2022-05-31 20:27 UTC, amcasey approved these changes
Thanks for the clarifications!  Would you be interested in adding yourself as a maintainer so you get pinged if this turns out to break a lot of people?

2022-06-01 17:20 UTC, amcasey approved these changes
Thanks for stepping up!

2022-06-01 17:27 UTC, jablko commented
Ready to merge. Thank you!

2022-06-01 17:28 UTC, merged