[forge-viewer] Update Property type
DefinitelyTyped/DefinitelyTyped pull request #60480
Opened 2022-05-23 08:38 UTC by adrianmfi

Properties can have numeric displayValue and nullable units: 
```
{
  "displayName": "Required",
  "displayValue": 0,
  "displayCategory": "Item",
  "attributeName": "Required",
  "type": 1,
  "units": null,
  "hidden": false,
  "precision": 0
}
```
- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: https://forge.autodesk.com/en/docs/viewer/v7/reference/Viewing/Model/#getProperties/

2022-05-24 14:04 UTC, adrianmfi commented on types/forge-viewer/index.d.ts
>          }
@liskaj Sure, thanks, added now.

2022-05-25 14:21 UTC, liskaj approved these changes

2022-05-25 23:30 UTC, MysteryBlokHed reviewed
If you add some tests for these changes (in `forge-viewer-tests.ts`), the PR can get merged without a DefinitelyTyped maintainer's approval 😄

2022-05-27 20:14 UTC, liskaj requested changes
@adrianmfi Can you fix according to comments above, pls?

2022-05-27 21:52 UTC, adrianmfi commented
> @adrianmfi Can you fix according to comments above, pls?

@liskaj I've added an optional field precision and type assertions of Property in `forge-viewer-tests.ts`, I think that fixes the comments?

2022-05-30 09:47 UTC, liskaj approved these changes

2022-05-30 09:49 UTC, liskaj commented
Ready to merge

2022-05-30 09:50 UTC, merged