Feature/adobe pdf service
DefinitelyTyped/DefinitelyTyped pull request #60884
Opened 2022-06-20 21:52 UTC by Anderman

Add adobe pdfServices

If adding a new definition:
- [ x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

2022-06-20 21:57 UTC, DangerBotOSS commented on types/adobe__pdfservices-node-sdk/operation/delete-pages-operation.d.ts
> + *  	DeletePages.SupportedSourceFormat.pdf));
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/adobe__pdfservices-node-sdk/operation/delete-pages-operation.d.ts;
  Line: 18;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-06-20 21:57 UTC, DangerBotOSS commented on types/adobe__pdfservices-node-sdk/operation/insert-pages-operation.d.ts
> + *  	InsertPages.SupportedSourceFormat.pdf));
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/adobe__pdfservices-node-sdk/operation/insert-pages-operation.d.ts;
  Line: 17;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-06-20 21:57 UTC, DangerBotOSS commented on types/adobe__pdfservices-node-sdk/operation/pdf-properties-operation.d.ts
> + * 	.then(result => console.log(result))
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/adobe__pdfservices-node-sdk/operation/pdf-properties-operation.d.ts;
  Line: 17;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-06-20 21:57 UTC, DangerBotOSS commented on types/adobe__pdfservices-node-sdk/operation/protect-pdf-operation.d.ts
> + *  		.setUserPassword("openpassword")
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/adobe__pdfservices-node-sdk/operation/protect-pdf-operation.d.ts;
  Line: 31;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-06-20 21:57 UTC, DangerBotOSS commented on types/adobe__pdfservices-node-sdk/operation/reorder-pages-operation.d.ts
> + *  	ReorderPages.SupportedSourceFormat.pdf));
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/adobe__pdfservices-node-sdk/operation/reorder-pages-operation.d.ts;
  Line: 16;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-06-20 21:57 UTC, DangerBotOSS commented on types/adobe__pdfservices-node-sdk/operation/replace-pages-operation.d.ts
> + *  	ReplacePages.SupportedSourceFormat.pdf));
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/adobe__pdfservices-node-sdk/operation/replace-pages-operation.d.ts;
  Line: 17;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-06-20 21:57 UTC, DangerBotOSS commented on types/adobe__pdfservices-node-sdk/operation/rotate-pages-operation.d.ts
> + *  	RotatePages.SupportedSourceFormat.pdf));
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/adobe__pdfservices-node-sdk/operation/rotate-pages-operation.d.ts;
  Line: 15;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-06-20 21:57 UTC, DangerBotOSS commented on types/adobe__pdfservices-node-sdk/operation/split-pdf-operation.d.ts
> + *  	SplitPDF.SupportedSourceFormat.pdf));
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/adobe__pdfservices-node-sdk/operation/split-pdf-operation.d.ts;
  Line: 16;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-06-21 17:19 UTC, sandersn requested changes

2022-06-21 17:19 UTC, sandersn commented on types/adobe__pdfservices-node-sdk/tslint.json
> +        "no-unnecessary-class": false
Instead of disabling the rule everywhere, please use `// tslint:disable-next-line:no-unnecessary-class` in the place(s) where it's needed.

2022-06-21 17:19 UTC, sandersn commented on types/adobe__pdfservices-node-sdk/execution-context.d.ts
> +export class ExecutionContext {
the reason for the no-unnecessary-class rule is that `create` returns a dangerous type: `ExecutionContext` doesn't have any properties, so anything is assignable to it:

```ts
let e = PDFServicesSDK.ExecutionContext.create(credentials)
let c = CombineFiles.Operation.createNew()
e = c // no error!
c.exec({}) // no error!
c.exec({ e: 1, m: 1}) // no error!
```

This is probably inherent to the design of the library, so you might just want to disable the rule. Alternatively, you could add a fake private property to make ExecutionContext nominal, something like `private __fake: never`.

2022-06-21 19:52 UTC, peterblazejewicz commented on types/adobe__pdfservices-node-sdk/index.d.ts
> +export = lib;
```suggestion
import * as PDFServicesSDK from './pdfservices-sdk';
export = PDFServicesSDK;
```
as literally exported symbol name, optional, aligns with module.

2022-06-21 20:00 UTC, peterblazejewicz commented on types/adobe__pdfservices-node-sdk/tsconfig.json
> +        "esModuleInterop" :true,
```suggestion
```
https://github.com/DefinitelyTyped/DefinitelyTyped#esmoduleinteropallowsyntheticdefaultimports

2022-06-21 20:05 UTC, peterblazejewicz commented on types/adobe__pdfservices-node-sdk/operation/option/protectpdf/password-protect-options.d.ts
> +    constructor();
```suggestion
```

2022-06-22 20:05 UTC, peterblazejewicz approved these changes
LGTM!

2022-06-22 20:33 UTC, Anderman commented
Ready to merge

2022-06-22 20:34 UTC, merged