adding Bot API 6.1
DefinitelyTyped/DefinitelyTyped pull request #60894
Opened 2022-06-21 17:58 UTC by Mi3liX9

2022-06-21 21:44 UTC, Mi3liX9 reviewed
Fix: HapticFeedback is a void not a callback

2022-06-23 10:40 UTC, KnorpelSenf commented
Will review soon, this is still on my radar

2022-06-28 22:35 UTC, KnorpelSenf requested changes
All changes look solid to me from a content point of view. I found one small formatting error. If it does not fix CI, you should maybe consider running the formatting tools of this repository so that everything looks consistent. For example, you can see how your comment lines are much longer than all other existing comments.

2022-06-28 22:35 UTC, KnorpelSenf commented on types/telegram-web-app/index.d.ts
> +     *  the callback function will be called and the invoice status will be passed as the first argument.
```suggestion
     * event invoiceClosed when the invoice is closed. If an optional callback parameter was passed,
     * the callback function will be called and the invoice status will be passed as the first argument.
```

2022-06-28 22:39 UTC, KnorpelSenf commented
Looking at the errors in CI, it seems indeed like you should run the formatter :)

2022-06-29 00:08 UTC, KnorpelSenf approved these changes
LGTM, thanks!

2022-06-30 18:40 UTC, merged