[eslint-scope] Add variable.scope
DefinitelyTyped/DefinitelyTyped pull request #60948
Opened 2022-06-24 14:10 UTC by saschanaz

For now I just copypasted the change to eslint too, but eslint should ideally import eslint-scope instead.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://eslint.org/docs/latest/developer-guide/scope-manager-interface#scope
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-06-24 14:14 UTC, JounQin requested changes

2022-06-24 14:14 UTC, JounQin commented on types/eslint/index.d.ts
> +        scope: Scope;
Can you provide more information about in which version `scope` is available?

2022-06-24 14:20 UTC, JounQin approved these changes

2022-06-30 18:52 UTC, merged

2022-06-30 19:22 UTC, richardweaver commented
This seems to have borked something on npm:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types/eslint/-/eslint-8.4.4.tgz
npm ERR! 404 
npm ERR! 404  '@types/eslint@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@types/eslint-scope'
```

2022-06-30 20:37 UTC, jablko commented
@andrewbranch I'm investigating but it's not obvious what's unique about `@types/eslint`. Anything in the logs?

2022-06-30 20:37 UTC, andrewbranch commented
@sandersn is checking.

2022-06-30 20:39 UTC, jablko commented
`@types/react-copy-to-clipboard` maybe failed as well but `@types/node-geocoder` succeeded around the same time. :confused:

2022-06-30 20:50 UTC, MrLuit commented
We're also having this problem. Seems to be an NPM issue:

> [Multiple project missing tarballs in latest published version](https://status.npmjs.org/incidents/6wr25yb0b2dd)[Subscribe](https://status.npmjs.org/#subscribe-modal-6wr25yb0b2dd)
Investigating - We are currently investigating this issue.
Jun 30, 20:48 UTC

https://status.npmjs.org/

2022-06-30 22:16 UTC, andrewbranch commented
We’ve moved the `latest` tag back to 8.4.3 in the meantime. Thanks for the heads up everyone.