Mark estree and estree-jsx as 1.0
DefinitelyTyped/DefinitelyTyped pull request #60995
Opened 2022-06-28 09:27 UTC by remcohaszing

Both are type definitions for a specification, not a package. By marking them as version 1.0, people can use “normal” semver ranges to depend on them. Also they are stable, so in that regard it makes sense to mark them as 1.0 too.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: N/A
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

cc @wooorm

2022-06-28 09:28 UTC, wooorm approved these changes

2022-06-28 10:04 UTC, wooorm approved these changes

2022-06-29 23:00 UTC, RReverser commented
> Also they are stable, so in that regard it makes sense to mark them as 1.0 too.

Hm, I'm not sure we can consider them stable given that we're changing / reordering type definitions (like you did just recently). For types with frequent refactorings, where users might import types that will be gone / incompatible in the next version, I think it makes sense to keep 0.x.

2022-06-30 08:00 UTC, wooorm commented
They have never really changed, since they were added in 2019, and were updated recently. So, assuming this is all working fine (I believe it is) and doesn’t need changes (\*), it seems very stable to me.

\* Of course, we could change more things, and then it makes sense to do it now, before a major.
Like make more content types extendable. That particularly can go in a minor though as it shouldn’t break things.
Are you thinking of making other changes?

2022-07-05 21:01 UTC, sheetalkamat requested changes

2022-07-05 21:01 UTC, sheetalkamat commented on types/estree-jsx/tslint.json
> +        "npm-naming": false
https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/dtslint/docs/npm-naming.md

2022-07-06 07:43 UTC, remcohaszing commented on types/estree-jsx/tslint.json
> +        "npm-naming": false
Thanks! Much better indeed! Ironically this allows me to reove the disabled rule for `@types/estree`, but not for `@types/estree-jsx`, as the package [`estree-jsx`](https://www.npmjs.com/package/estree-jsx) exists on npm.

2022-07-06 08:06 UTC, wooorm approved these changes

2022-07-06 19:24 UTC, sheetalkamat approved these changes

2022-07-06 19:49 UTC, wooorm approved these changes

2022-07-11 16:06 UTC, remcohaszing commented
@RReverser Are you still concerned about the instability of these types? If so, I’ll gladly change the versions to 0.1. Otherwise, I’ll merge this as-is tomorrow.

2022-07-12 20:21 UTC, remcohaszing commented
Ready to merge

2022-07-12 20:22 UTC, merged