[@types/parse] fix schema.addIndex()'s index parameter
DefinitelyTyped/DefinitelyTyped pull request #61064
Opened 2022-07-02 17:42 UTC by Asing1001

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<[url here](https://parseplatform.org/Parse-SDK-JS/api/3.1.0/Parse.Schema.html)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-08-15 19:34 UTC, jakebailey requested changes
I did a quick skim of https://unpkg.com/browse/parse@3.4.3/lib/node/ParseSchema.js, and it looks like this is probably a documentation bug and not expected behavior.

2022-08-16 03:20 UTC, Asing1001 commented
@jakebailey It's not a documentation bug, our team has to cast it to unknown type first to correctly create the index.
The current type could only accept: `addIndex(name, { key: "number" })` instead of `addIndex(name, { key: 1 })`
![image](https://user-images.githubusercontent.com/6785698/184791067-0da06460-ec31-42b7-b824-4d995a5b6a31.png)

2022-08-16 16:32 UTC, jakebailey commented
I see. Perhaps it should be `TYPE | number` instead?

2022-08-16 17:14 UTC, Asing1001 commented
@jakebailey I don't think so. By using the `Type`, the addIndex will be like `addIndex(name, { key: "Boolean" })` which is totally wrong, you could see the acceptable values in [mongodb index](https://github.com/mongodb/node-mongodb-native/blob/a2359e43d7a59acf69785104b5f6e6c1516a5e27/src/operations/indexes.ts#L55): 
```js
export type IndexDirection = -1 | 1 | '2d' | '2dsphere' | 'text' | 'geoHaystack' | number;
```

Which only accept `string | number` instead of `TYPE` as below

```js
type TYPE =
                | 'String'
                | 'Number'
                | 'Boolean'
                | 'Date'
                | 'File'
                | 'GeoPoint'
                | 'Polygon'
                | 'Array'
                | 'Object'
                | 'Pointer'
                | 'Relation'
```

2022-08-16 17:17 UTC, jakebailey approved these changes
Got it; I'll switch my approval.

I do wonder if it should actually be `FieldType` but that's a much wider set of things.

2022-08-16 17:49 UTC, Asing1001 commented
Ready to merge

2022-08-16 17:49 UTC, merged