fix(parse): do not use `const enum`
DefinitelyTyped/DefinitelyTyped pull request #61133
Opened 2022-07-07 16:16 UTC by peterblazejewicz

This is now banned by linter, but barely surfaces from time to time,
like in this case:
https://github.com/DefinitelyTyped/DefinitelyTyped/runs/7225578093?check_suite_focus=true#step:6:3241

Removing as per handbook:
https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls

Thanks!

/cc @nicolas377
ref: #61115

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)

2022-07-07 16:22 UTC, nicolas377 approved these changes
Thanks for this!

2022-07-07 17:31 UTC, yoursunny commented
A search indicates there are 173 `const enum` occurrences in this codebase.
https://github.com/DefinitelyTyped/DefinitelyTyped/search?q=%22const+enum%22&type=code

Maybe delete all the them in the same PR?

2022-07-07 17:48 UTC, nicolas377 commented
Maybe, but that PR would take significantly longer to merge, while this is a hotfix to allow PRs that modify @types/node to pass CI.

2022-07-07 18:03 UTC, sheetalkamat approved these changes

2022-07-07 18:07 UTC, sheetalkamat requested changes
I think this should be on ParseError as statics instead of enum since I am not sure `ErrorCode` exists.

2022-07-07 19:24 UTC, peterblazejewicz commented
@sheetalkamat you're correct:
https://github.com/parse-community/Parse-SDK-JS/blob/v1.11.0/src/ParseError.js
but that would change the focus (we would have to correct symbol definition, instead of just fixing the CI failing on v1 tests due to new linter rules). IMO, the current change is safe (removing const from `d.ts` as per handbook)

2022-07-14 06:56 UTC, panva approved these changes

2022-07-14 18:03 UTC, nicolas377 commented
> IMO, the current change is safe (removing const from d.ts as per handbook)

I agree with @peterblazejewicz. I'm going to turn all `const enum` instances into just `enum` instances in a separate PR (if a maintainer hasn't already), but for now, we need to unblock @types/node.

2022-07-14 19:07 UTC, peterblazejewicz commented
/cc @sheetalkamat

2022-07-14 19:09 UTC, closed without merging