[chai] Fix Assert.throws and Assert.doesNotThrow typings
DefinitelyTyped/DefinitelyTyped pull request #61161
Opened 2022-07-09 13:50 UTC by berniegp

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://www.chaijs.com/api/assert/#method_throws and https://github.com/chaijs/chai/blob/4.x.x/lib/chai/interface/assert.js#L1981>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-07-28 18:57 UTC, gabritto requested changes
Hi, could you rearrange the code in the PR (in index.ts) so that the order of the functions is preserved? e.g. if `throw` declarations came before `throws`, make sure `throw` still comes before `throws`. Otherwise it's hard to keep track of what types actually changed, so it's really hard for me to review this PR right now. Thank you!

2022-07-28 19:15 UTC, berniegp commented
I restored the original ordering but the diff isn't terribly easy to follow even then sadly.

Btw I changed the order at first to align on the order from chai where `throws` is the "canonical" version. https://github.com/chaijs/chai/blob/4.x.x/lib/chai/interface/assert.js#L1969

But whatever order makes your review easier works for me.

2022-07-28 21:50 UTC, gabritto commented
Thanks for the reordering. I've gone through the code and it doesn't look wrong to me, but I'm not a chai expert, so I'm not super confident approving that. @jedmao @Bartvds @AGBrown @olivr70 @mwistrand @shaunluttin @micksatana @ErikSchierboom @bparan @CXuesong @joeykilpatrick could you review this?

2022-08-04 18:46 UTC, andrewbranch approved these changes
Horrifyingly, this seems to be correct as far as I can tell

2022-08-04 18:46 UTC, andrewbranch commented on types/chai/index.d.ts
> +         * @param ignored   Ignored parameter.
🤦 come on chai, what are you doing

2022-08-07 20:40 UTC, berniegp commented
Ready to merge

2022-08-07 20:40 UTC, merged