feat: Nodejs-captcha types
DefinitelyTyped/DefinitelyTyped pull request #61186
Opened 2022-07-11 20:54 UTC by JPBM135

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

**Package:** https://www.npmjs.com/package/nodejs-captcha

2022-07-11 22:44 UTC, MysteryBlokHed requested changes
A few suggestions here, but everything else LGTM!

2022-07-11 22:44 UTC, MysteryBlokHed commented on types/nodejs-captcha/index.d.ts
> +declare function captcha(p: captchaOptions): captchaValue;
`p` should probably be optional:

```suggestion
declare function captcha(p?: captchaOptions): captchaValue;
```

2022-07-11 22:44 UTC, MysteryBlokHed commented on types/nodejs-captcha/nodejs-captcha-tests.ts
> +import captcha from 'nodejs-captcha';
A CommonJS import should be used here instead of ES6:

```suggestion
import captcha = require('nodejs-captcha');
```

2022-07-11 22:44 UTC, MysteryBlokHed commented on types/nodejs-captcha/index.d.ts
> +// Type definitions for ssdeep.js 0.0
This seems to be the wrong package name

```suggestion
// Type definitions for nodejs-captcha 0.0
```

2022-07-11 22:44 UTC, MysteryBlokHed commented on types/nodejs-captcha/index.d.ts
> +interface captchaValue {
While not required, the standard for names of interfaces, classes, types, etc. in TypeScript is to capitalize the first letter as well:

```suggestion
interface CaptchaValue {
```

Note that any references to `captchaValue` would have to be updated if this is changed

2022-07-11 22:44 UTC, MysteryBlokHed commented on types/nodejs-captcha/index.d.ts
> +interface captchaOptions {
```suggestion
interface CaptchaOptions {
```

2022-07-17 00:14 UTC, DangerBotOSS commented on types/nodejs-captcha/nodejs-captcha-tests.ts
> +	length: 8,
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/nodejs-captcha/nodejs-captcha-tests.ts;
  Line: 4;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-08-15 12:45 UTC, closed without merging