[infra] Bump dtslint-runner -> >=0.0.121
DefinitelyTyped/DefinitelyTyped pull request #61208
Opened 2022-07-12 18:09 UTC by jablko

I think we depend on dtslint-runner ^0.0.121
- since https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61104/commits/0036aa528d712275115a588ab2f8b976940e286f (added `.eslintrc.json` files)
- for https://github.com/microsoft/DefinitelyTyped-tools/pull/496/files#diff-70e7e23868487b648175b94c54917a408ca00f70196e535ba2b0ff1923333d0cR195 (allowed them)
- to avoid https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61192#issue-1301458585

I can't say how many people bumping the package.json dependency will help. It sounds like if you have an existing DT repo, you need to remove node_modules and/or any project lockfiles, currently. After this change, re-running `npm install` should be sufficient. It shouldn't hurt?

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61192#issue-1301458585

2022-07-13 15:30 UTC, sandersn requested changes
The intent of DT's package.json setup, and lack of package-lock.json, is to get the newest version of `@definitelytyped/*` whenever anybody runs `npm install`. As you point out, that's not how `npm` currently works. Can you point me to documentation that explains the difference caused by this change?

2022-07-13 17:25 UTC, jablko commented
@sandersn My understanding is, if it's a new clone (no project lockfiles) there's effectively no difference:
- `latest` will resolve to the `latest` tag. That's the max non-prerelease by DT-tools convention, e.g. 0.0.121, 0.0.122, etc.
- ~`^0.0.121` will resolve to the max non-prerelease **>=0.0.121**, i.e. 0.0.121, 0.0.122, etc., same as `latest`.~

The difference is if it's an existing clone, `latest` could've previously resolved to 0.0.115 and `^0.0.121` can't, so there're cases where the latter gets upgraded and the former doesn't.

What those cases are, I'm not _super_ precise on, but if there's a project lockfile from a previous `npm install`, and at that time `latest` was 0.0.115, `latest` won't get upgraded. But we have a `.npmrc` with [`package-lock=false`](https://docs.npmjs.com/cli/v8/using-npm/config#package-lock), so we ignore any `package-lock.json`. What happened in the OP's case is they used another package manager (Yarn) I think, which ignores `package-lock=false`.

So with `latest`, we're counting on the package manager to ignore project lockfiles.
- We can leave it as is, I can't think of a problem for npm, others might need to remove their lockfiles occasionally (or use [`yarn up`](https://yarnpkg.com/cli/up), maybe?)
- We can use ~`^0.0.121`~`>=0.0.121`: More accurate and no downside? I expect it'll help very few people, but hurt no one. No idea how many people use alternative package managers and have existing clones/lockfiles?

I was wrong about `^0.0.121` resolving to 0.0.122, according to the [caret ranges documentation](https://github.com/npm/node-semver#caret-ranges-123-025-004), so I've added a commit to use `>=0.0.121` instead. That matches my intention. I agree we should fix [`"@definitelytyped/header-parser": "^0.0.100"`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61208#discussion_r920215238), in either case.

Here's the [semver resolution algorithm](https://github.com/npm/npm-pick-manifest#algorithm). It's bypassed if there's a lockfile, and the existing resolution is used instead (is my understanding).

2022-07-26 22:47 UTC, sandersn commented
> So with latest, we're counting on the package manager to ignore project lockfiles.
As a backup, we're counting on people who mistakenly generate a lockfile to notice that it's not checked in to the repo. I think this is a reasonable thing to expect, though.

> We can use >=0.0.121: More accurate and no downside? I expect it'll help very few people, but hurt no one. 

The main downside is that >=0.0.121 is only good until some new breaking change from DT-tools, in which case it'll have to be bumped again. 

I think the best we can do to transmit the intent of "always use latest DT-tools" is to put 'latest` into package.json, not a specific version. I think it might also make sense to start shipping lockfiles, at least for the DT root. But that's a bigger change. In this PR, I'd like to see all the package.jsons set to `latest`.

2022-09-06 23:43 UTC, sheetalkamat requested changes
As requested by @sandersn, pls change to use everything latest in package.json

2023-02-14 20:02 UTC, closed without merging