co-util
DefinitelyTyped/DefinitelyTyped pull request #61376
Opened 2022-07-21 10:04 UTC by codeorg

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2022-07-24 10:45 UTC, codeorg commented
co-uitl

2022-07-24 10:49 UTC, codeorg reviewed
please add co-util to @types

2022-07-25 19:37 UTC, gabritto requested changes

2022-07-25 19:37 UTC, gabritto commented on types/co-util/tslint.json
> +        "array-type": false,
It doesn't look like disabling these rules is strictly necessary. Could you instead remove these rules and fix the lint errors in your declaration files? If you have a problem with how to fix a specific lint error, please let me know and I can try to help.

2022-07-25 19:42 UTC, gabritto commented
On a second glance, it looks like the original library ships its own type definitions (https://unpkg.com/browse/co-util@2.0.1/lib/index.d.ts), so I believe you should be using the type definitions in the original package, instead of adding type definitions here on DT. Because of that, I'm closing this PR. But if you think there is a reason why there needs to be type definitions for this package here in DT, let me know.

2022-07-25 19:43 UTC, gabritto commented
On a second glance, it looks like the original library ships its own type definitions (https://unpkg.com/browse/co-util@2.0.1/lib/index.d.ts), so I believe you should be using the type definitions in the original package, instead of adding type definitions here on DT. Because of that, I'm closing this PR. But if you think there is a reason why there needs to be type definitions for this package here in DT, let me know.

2022-07-25 19:43 UTC, closed without merging