[d3-selection] Support TrustedHTML
DefinitelyTyped/DefinitelyTyped pull request #61553
Opened 2022-08-03 11:51 UTC by vrana

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [d3-selection/src/selection/html.js](https://github.com/d3/d3-selection/blob/main/src/selection/html.js)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-09-13 00:00 UTC, navya9singh requested changes

2022-09-13 00:00 UTC, navya9singh commented on types/d3-selection/v1/index.d.ts
>  // TypeScript Version: 2.3
Please delete line 10 because we no longer test Typescript Version 2.3

2022-09-13 00:00 UTC, navya9singh commented on types/d3-selection/v2/index.d.ts
>  // TypeScript Version: 2.3
Please delete line 10.

2023-02-17 21:03 UTC, gabritto approved these changes

2023-03-21 01:06 UTC, closed without merging