[chrome] Add DevTools Recorder
DefinitelyTyped/DefinitelyTyped pull request #61891
Opened 2022-08-23 13:44 UTC by nickmccurdy

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.chrome.com/docs/extensions/reference/devtools_recorder/

2022-08-23 13:56 UTC, nickmccurdy commented
Depends on https://github.com/microsoft/DefinitelyTyped-tools/pull/525

2022-08-23 16:35 UTC, nickmccurdy commented
`"target": "es6"` doesn't seem to be working but I'm not sure why

2022-09-04 17:06 UTC, nickmccurdy commented
I'd appreciate help with the build errors.

2022-09-08 03:24 UTC, JasonXian commented
Hey @nickmccurdy, I played around with different tsconfig options but couldn't seem to solve the issue either. I agree that updating the target to es6 should fix the puppeteer errors but it seems to just generates other errors as well.

For now, instead of importing `Step` and `UserFlow` for the argument types, it might be simpler to use `any` for now. I'd assume any downstream use cases would be passing in a properly typed argument from the types in the original library anyways, meaning there would still be some safety.

This isn't an ideal solution, but I don't think this build system issue is worth being blocked on in the meanwhile.

2023-02-08 07:59 UTC, fregante requested changes

2023-02-08 07:59 UTC, fregante commented on types/chrome/package.json
> +    "@puppeteer/replay": "^1.0.0"
I'm not a fan of adding [1MB-plus-dependency](https://packagephobia.com/result?p=%40puppeteer%2Freplay) to a type package. I think this should be dropped. I think that if someone needs those types they can install it independently, even if this d.ts explicitly mentions `import type {Step, UserFlow} from '@puppeteer/replay'`

If that's not acceptable, how about venturing replay’s d.ts instead? https://unpkg.com/browse/@puppeteer/replay@2.9.0/lib/main.d.ts

2023-03-11 12:50 UTC, closed without merging