[prettier] Add getSupportInfo to standalone API
DefinitelyTyped/DefinitelyTyped pull request #62121
Opened 2022-09-05 22:36 UTC by nickmccurdy

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/prettier/prettier/blob/c51d509560b713fdef9590fc60a55329c8660671/src/standalone.js#L47

2022-09-17 03:23 UTC, JounQin requested changes

2022-09-17 03:23 UTC, JounQin commented on types/prettier/standalone.d.ts
> +export function getSupportInfo(): SupportInfo;
A new test case please?

2022-09-18 01:03 UTC, JounQin approved these changes

2022-09-24 04:31 UTC, RyanCavanaugh approved these changes

2022-09-24 04:40 UTC, nickmccurdy commented
Ready to merge

2022-09-24 04:41 UTC, merged