[@smallwei/avue] add types for @smallwei/avue
DefinitelyTyped/DefinitelyTyped pull request #62231
Opened 2022-09-13 09:04 UTC by SoulLyoko

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2022-09-15 19:51 UTC, sandersn requested changes

2022-09-15 19:51 UTC, sandersn commented on types/smallwei__avue/index.d.ts
> +/// <reference types="./global" />
these don't use module name resolution. I think they should all be `<reference path="./element-plus" />` and so on. I think that would let you get rid of OTHER_FILES.txt too.

2022-09-17 20:30 UTC, peterblazejewicz commented on types/smallwei__avue/tsconfig.json
> +        "esModuleInterop": true,
this is not allowed, unless there is a very specific reason in changing that line on DT-hosted type declaration:
https://github.com/DefinitelyTyped/DefinitelyTyped#esmoduleinteropallowsyntheticdefaultimports

2022-09-17 20:31 UTC, peterblazejewicz commented on types/smallwei__avue/index.d.ts
> +
```suggestion
```
please remove any comments (dead code) that has no meaning in context of the file

2022-09-17 20:31 UTC, peterblazejewicz commented on types/smallwei__avue/element-plus.d.ts
> +// import type { RuleItem } from 'async-validator';
ditto about dead code imports
you can write proper comments though and keep them inline in the code

2022-09-17 20:32 UTC, peterblazejewicz commented on types/smallwei__avue/form.d.ts
> +
```suggestion
```
ditto

2022-09-17 20:39 UTC, peterblazejewicz commented on types/smallwei__avue/global.d.ts
> +export {};
There is no 'global.js` file with a symbols, correct me if I'm wrong:
https://gitee.com/smallweigit/avue/tree/master/src
those TS symbols can be added to 'index.d.ts' file and re-imported in other files here

2022-09-17 20:41 UTC, peterblazejewicz commented on types/smallwei__avue/index.d.ts
> +export default Avue;
the module seems to be webpack exported UMD module:
https://gitee.com/smallweigit/avue/blob/master/build/config.js#L66
https://unpkg.com/browse/@smallwei/avue@2.10.0/lib/avue.js
(L:7 and others)


https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html#identifying-a-umd-library

2022-09-22 23:26 UTC, sandersn approved these changes

2022-09-23 18:50 UTC, peterblazejewicz approved these changes

2023-01-31 07:32 UTC, SoulLyoko commented
@peterblazejewicz What does it mean,the tag "Self Merge"?How can I merge this PR?

2023-01-31 16:55 UTC, merged