Update facebook instant game createAsync to string array
DefinitelyTyped/DefinitelyTyped pull request #62238
Opened 2022-09-13 13:39 UTC by StevenRenaux

https://developers.facebook.com/docs/games/instant-games/sdk/fbinstant7.0

2022-09-26 15:49 UTC, doterax requested changes
Thank you for this bug fix! 

According to [documentation](https://developers.facebook.com/docs/games/instant-games/sdk/fbinstant7.0) this argument is optional, so please make them optional.

Rename argument to `suggestedPlayerIDs` as in documentation.

Update JSDoc comment and tests that covered usage of this method with all types of arguments.

2022-09-29 13:35 UTC, doterax approved these changes

2022-09-29 13:36 UTC, doterax approved these changes

2022-09-29 19:00 UTC, gabritto approved these changes

2022-09-30 08:23 UTC, doterax commented
Ready to merge

2022-09-30 08:23 UTC, merged