Update scripting and tts apis at @chrome types
DefinitelyTyped/DefinitelyTyped pull request #62657
Opened 2022-10-11 18:20 UTC by zuhairtaha

[scripting api](https://developer.chrome.com/docs/extensions/reference/scripting)
[tts api](https://developer.chrome.com/docs/extensions/reference/tts/#method-getVoices)

2022-10-11 20:25 UTC, meyfa requested changes
It looks like you may have auto-formatted the file before committing. Currently GitHub cannot display the diff because of this, since so many lines were edited. Please revert the formatting changes so this pull request can be properly reviewed. Thanks!

2022-10-12 12:50 UTC, meyfa requested changes
Thanks for fixing the whitespace! Looks like great additions, I just have some minor suggestions.

2022-10-12 12:50 UTC, meyfa commented on types/chrome/index.d.ts
> +    export function getVoices(): Promise<TtsVoice[]>;
Could you move the Promise version above the callback version? i.e. switch lines 10263 and 10264, to ensure correct behavior by TypeScript.

2022-10-12 12:50 UTC, meyfa commented on types/chrome/index.d.ts
> +
These would be better as interfaces instead of type literals (and the last one needs a closing curly brace). This is currently failing CI.

2022-10-12 18:24 UTC, meyfa reviewed
This looks really good code-wise, thank you so much. One final thing to get this ready: Please add some tests to `types/chrome/test/index.ts`. These don't have to be advanced, but having something there will protect against future regressions.

* `getVoices` already has a callback-style test here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2d2e02af00da68816434ce57a6447a449ae8f3af/types/chrome/test/index.ts#L775
  I suggest adding another `getVoices` call inside the same function that makes use of the Promise style.
* The script API has a test function here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2d2e02af00da68816434ce57a6447a449ae8f3af/types/chrome/test/index.ts#L1030
  Perhaps add some more lines at the bottom of that which call your newly-added functions.

2022-10-12 19:00 UTC, zuhairtaha commented
Thank you @meyfa  for helping me. This my first time I fork and contribute with something

2022-10-12 19:02 UTC, meyfa commented
@zuhairtaha You're welcome! Besides, I appreciate the effort you put into this change. It will help many people using these types.

2022-10-12 19:03 UTC, meyfa approved these changes
LGTM!

2022-10-12 19:13 UTC, meyfa commented on types/chrome/test/index.ts
> +    }),
```suggestion
    });
```

2022-10-12 19:51 UTC, meyfa approved these changes

2022-10-16 13:07 UTC, meyfa approved these changes

2022-10-16 13:10 UTC, zuhairtaha commented
When can the branch be merged?

2022-10-16 13:18 UTC, meyfa commented
@zuhairtaha A definition owner needs to approve (one of these people here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62657#issuecomment-1275098483). After a few days of inactivity, this PR will also be pushed to the DefinitelyTyped maintainers for review.

2022-10-20 03:52 UTC, JasonXian approved these changes

2022-10-20 11:29 UTC, zuhairtaha commented
Ready to merge

2022-10-20 11:29 UTC, merged