Minor validators update for ember-changeset-validations
DefinitelyTyped/DefinitelyTyped pull request #62735
Opened 2022-10-15 09:41 UTC by elenagolovko

2022-10-15 09:45 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## ember-changeset-validations ([<kbd>unpkg</kbd>](https://unpkg.com/browse/ember-changeset-validations@latest/))
was missing the following properties:
1. name
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0b836c0721e38d2b7d70a3bbc3d25e42ecdd9179
</p>

2022-10-19 17:29 UTC, andrewbranch requested changes
Can you fill out the PR template please?

2022-10-25 16:46 UTC, andrewbranch approved these changes

2022-10-26 09:49 UTC, elenagolovko commented
Ready to merge

2022-10-26 09:49 UTC, merged