feat(koa-cash): add method from v4.1.1
DefinitelyTyped/DefinitelyTyped pull request #62807
Opened 2022-10-20 13:14 UTC by rhuanbarreto

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [<<url here>>](https://github.com/koajs/cash/pull/98)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-11-01 08:13 UTC, jagoe commented
@rhuanbarreto Sorry for the late response. It has been a while since I added the typings, so I'm not a 100% sure, but your contribution looks good to me.

According to the `test` action, you're not allowed to specify a patch version in the type definition header. Pretty sure that's because patch versions aren't supposed to change public interfaces (https://semver.org).
So just remove the patch version (`4.1` instead of `4.1.1`) and you should be good to go.

2022-11-01 08:19 UTC, rhuanbarreto commented on types/koa-cash/index.d.ts
> +// Type definitions for koa-cash 4.1.1
```suggestion
// Type definitions for koa-cash 4.1
```

2022-11-01 08:21 UTC, rhuanbarreto commented
@jagoe Changes made. You can approve and merge.

2022-11-01 08:27 UTC, jagoe requested changes

2022-11-01 08:27 UTC, jagoe commented on types/koa-cash/koa-cash-tests.ts
> +    if (await ctx.cashed()) return ctx.cashClear('/');
Wasn't sure at first, but the latest build error confirms it. `cashClear()` returns `void`, so this doesn't make sense. Maybe something like this:

```suggestion
    if (await ctx.cashed()) {
      ctx.cashClear('/');
      return;
    }
```

Wouldn't make much sense for an application, but whatever :smile:

2022-11-01 08:33 UTC, jagoe approved these changes

2022-11-11 13:37 UTC, rhuanbarreto commented
Ready to merge

2022-11-11 13:38 UTC, merged