[mapbox-gl-draw] Add drawConfig to DrawCustomModeThis
DefinitelyTyped/DefinitelyTyped pull request #63050
Opened 2022-11-02 16:44 UTC by yukiyokotani

## DrawCustomModeThis
- Add missing property `drawConfig` to DrawCustomModeThis.  
  cf. https://github.com/mapbox/mapbox-gl-draw/blob/main/src/modes/mode_interface_accessors.js#L10
  At first, according to above implementation, I considered the type of `drawConfig` should be `Exclude<MapboxDrawOptions, undefined> | Record<string, never>` (union with empty object), but I found all properties in the type `MapboxDrawOptions` are optional. So I define it simply `Exclude<MapboxDrawOptions, undefined>` since drawConfig cannot be narrowed from union type with empty object.

====================

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-11-05 20:36 UTC, Shayan-To requested changes
I proposed a change in the comment above.

2022-11-06 13:11 UTC, yukiyokotani commented
@Shayan-To 
Thank you for reviewing. Based on the current `MapboxDraw` constructor argument object types, I defined a `MapboxDrawOptions` interface, and `MapboxDraw`'s constructor arguments and `drawConfig` types have been changed to reference that. How about this?

2022-11-06 14:54 UTC, Shayan-To approved these changes
LGTM.

2022-11-07 10:31 UTC, yukiyokotani commented
Ready to merge

2022-11-07 10:32 UTC, merged