Added destroy method to from2 types
DefinitelyTyped/DefinitelyTyped pull request #63166
Opened 2022-11-08 19:32 UTC by NathanRSmith

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/hughsk/from2/blob/master/index.js#L71
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.
- Same version, just added missing method

2022-11-08 21:54 UTC, BendingBender requested changes

2022-11-08 21:54 UTC, BendingBender commented on types/from2/index.d.ts
> +        destroyed: boolean;
I think it'd make sense to declare this as `readonly`:
```suggestion
        readonly destroyed: boolean;
```

2022-11-09 14:31 UTC, BendingBender approved these changes

2022-11-09 14:42 UTC, NathanRSmith commented
Ready to merge

2022-11-09 14:43 UTC, merged