HEREMaps getRoutingService signature fix + add an interface for the service result
DefinitelyTyped/DefinitelyTyped pull request #63188
Opened 2022-11-10 13:37 UTC by adrienlucas

Changing an existing definitions:

Fix `H.service.Platform.getRoutingService` signature following https://developer.here.com/documentation/maps/3.1.35.3/api_reference/H.service.Platform.html#getRoutingService
Add a `H.service.Url.MultiValueQueryParameter` class following https://developer.here.com/documentation/maps/3.1.35.3/api_reference/H.service.Url.MultiValueQueryParameter.html
Mark `H.service.Platform.getGeocodingService` as deprecated following https://developer.here.com/documentation/maps/3.1.35.3/api_reference/H.service.Platform.html#getGeocodingService
Make a specialized `H.service.RoutingService.RoutingServiceResult` interface extending the `H.service.ServiceResult` following the API spec at https://developer.here.com/documentation/routing-api/api-reference-swagger.html#operation%2FcalculateRoutesPost

About this last point : I'm not sure this is the best way or appropriate place to introduce this interface, as it does not exist at all in the original lib source code. If I'm not doing it right, please feel free to revert the second commit here and indicate the best practice !

Mention : @Josh-ES @denyo @fx88 @life777 @DaSchTour

2022-11-21 18:57 UTC, DaSchTour requested changes

2022-11-22 08:28 UTC, adrienlucas commented on types/heremaps/index.d.ts
> +                location: {
Thanks for your review @DaSchTour !
The `H.geo.IPoint` contains also `alt` and `ctx` optionnal properties that are not relevant for the Routing Service.
Should I use this type anyway ?

I'm adding a commit that fix the second part of your comment.
Please let me know if you want me to use `H.geo.IPoint` instead !

2022-11-22 08:39 UTC, DaSchTour approved these changes

2022-11-26 10:31 UTC, DaSchTour approved these changes

2022-11-30 19:37 UTC, adrienlucas commented
Ready to merge

2022-11-30 19:38 UTC, merged