[@types/navermaps] add overalyType in ImageMapTypeOptions
DefinitelyTyped/DefinitelyTyped pull request #63291
Opened 2022-11-17 04:07 UTC by Dongkyuuuu

사용자 정의 OverlayType 설정 시 overlayType 필드가 누락 되어 있어 추가 하였습니다. 

----
- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [사용자 정의 OverlayType 설정](https://navermaps.github.io/maps.js.ncp/docs/tutorial-StyleMap-2-Custom-OverlayType.html)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-11-17 04:30 UTC, SuhwanCha requested changes
해당 PR과 상관 없는, 기존의 존재하던 다른 test case까지 linter로 수정된 것 같습니다.

2022-11-17 04:38 UTC, Dongkyuuuu commented
> 해당 PR과 상관 없는, 기존의 존재하던 다른 test case까지 linter로 수정된 것 같습니다.

DefinitelyTyped에서 제공하는 linter를 이용해서 처리 했습니다.
혹시 새로 추가한 테스트 케이스를 제외한 나머지 코드들 원상복구 처리가 필요할까요?

2022-11-17 07:14 UTC, SuhwanCha commented
> > 해당 PR과 상관 없는, 기존의 존재하던 다른 test case까지 linter로 수정된 것 같습니다.
> 
> DefinitelyTyped에서 제공하는 linter를 이용해서 처리 했습니다. 혹시 새로 추가한 테스트 케이스를 제외한 나머지 코드들 원상복구 처리가 필요할까요?

DefinitelyTyped에서 제공하는 linter 였군요! 그럼 PR 제목에 test case도 lint 했다고 추가하거나, PR을 나누는건 어떨까요?
추후에 test case가 수정된걸로 헷갈릴까봐 제안드려보아요.

2022-11-17 07:18 UTC, Dongkyuuuu commented
> > > 해당 PR과 상관 없는, 기존의 존재하던 다른 test case까지 linter로 수정된 것 같습니다.
> > 
> > 
> > DefinitelyTyped에서 제공하는 linter를 이용해서 처리 했습니다. 혹시 새로 추가한 테스트 케이스를 제외한 나머지 코드들 원상복구 처리가 필요할까요?
> 
> DefinitelyTyped에서 제공하는 linter 였군요! 그럼 PR 제목에 test case도 lint 했다고 추가하거나, PR을 나누는건 어떨까요? 추후에 test case가 수정된걸로 헷갈릴까봐 제안드려보아요.

그럴 수 있을 것 같네요! 추후에는 PR 혹은 Commit을 나누어서 진행해보도록 하겠습니다. 
지금 올린 PR은 나누어야할까요??

2022-11-17 07:23 UTC, SuhwanCha commented
> 그럴 수 있을 것 같네요! 추후에는 PR 혹은 Commit을 나누어서 진행해보도록 하겠습니다.

너무 사소한거라, 번거롭게 나누기 보다는 PR 제목에 linting test cases를 추가하는건 어떨까요?

2022-11-17 07:25 UTC, Dongkyuuuu commented
> > 그럴 수 있을 것 같네요! 추후에는 PR 혹은 Commit을 나누어서 진행해보도록 하겠습니다.
> 
> 너무 사소한거라, 번거롭게 나누기 보다는 PR 제목에 linting test cases를 추가하는건 어떨까요?

추가하였습니다!

2022-11-17 07:26 UTC, SuhwanCha approved these changes

2022-11-17 07:28 UTC, Dongkyuuuu commented
Ready to merge

2022-11-17 07:29 UTC, merged

2022-11-17 23:54 UTC, kkokkojeong commented
@Dongkyuuuu @SuhwanCha 

안녕하세요. 네이버 지도 개발자 정석철 입니다. 이전에 두분께서 작업해주신 결과를 토대로 제가 수정했습니다.
 - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62983, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63005

그리고 11/17(목) NCP 개발자 문서에 정식으로 가이드 올렸습니다.
 - https://navermaps.github.io/maps.js.ncp/docs/index.html

앞으로도 타입 관련 버그 PR 부탁드립니다 . 덧붙여서 지도 관련 버그/개선 사항은 언제든지 환영합니다 :)

2022-11-18 00:54 UTC, Dongkyuuuu commented
@kkokkojeong 
항상 네이버 지도 잘 쓰고 있습니다!!
혹시 지도 관련 버그/개선 사항이 생긴다면 어떤 창구로 말씀드리는게 괜찮을까요??

2022-11-21 04:37 UTC, kkokkojeong commented
@Dongkyuuuu 님,

타입 관련 버그는 PR 올려서 수정해주시면 되고, 버그/개선사항은 공식 채널로 문의 부탁드립니다.
 - https://www.ncloud.com/support/question/service