Added export fields for RootTag and RootTagContext in React Native
DefinitelyTyped/DefinitelyTyped pull request #63440
Opened 2022-11-30 21:45 UTC by helenwxdong

Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [ x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

2022-11-30 22:17 UTC, lunaleaps approved these changes

2022-12-01 02:30 UTC, dennyak47 commented
@helenwxdong 

Hi Helen,
[Related Doc](https://reactnative.dev/docs/roottag#breaking-change-in-066)
According to Doc, RootTagContext is available from version 0.66.
Would you kindly add support for all versions since 0.66?

thanks

2022-12-01 12:38 UTC, iRoachie requested changes
Blocking automerge in relation to the comment from @dennyak47. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63440#issuecomment-1333072091

2022-12-01 18:32 UTC, iRoachie approved these changes

2022-12-02 02:15 UTC, lunaleaps approved these changes

2022-12-06 17:33 UTC, helenwxdong commented
Ready to merge

2022-12-06 17:34 UTC, merged