[@types/reefjs] BREAKING CHANGE: update types to latest version `reefjs@12`
DefinitelyTyped/DefinitelyTyped pull request #63467
Opened 2022-12-02 19:56 UTC by bryandonmarc

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test reefjs`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://reefjs.com/about/#changelog](https://reefjs.com/about/#changelog)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2022-12-02 20:00 UTC, DangerBotOSS commented on types/reefjs/v7/reefjs-tests.ts
> +			${props.todos
<!--
  1 failure:  The root .editorc...
  0 warning: 
  
  
  DangerID: danger-id-Danger;
  File: types/reefjs/v7/reefjs-tests.ts;
  Line: 102;
-->
- :no_entry_sign: The root .editorconfig style specifies spaces for whitespace. Please use spaces in new or changed types.

2022-12-02 20:01 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## reefjs ([<kbd>unpkg</kbd>](https://unpkg.com/browse/reefjs@latest/))
was missing the following properties:
1. setter
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 409030896c2eb94c829df60c9e27ca8fd01a964e
</p>

2022-12-02 20:21 UTC, cferdinandi commented
I have no idea why I'm tagged in this PR...

2022-12-02 20:27 UTC, bryandonmarc commented
@cferdinandi You were previously listed by @shockdevv as a definition owner for the types he made for `reef@7`, and everyone listed was automatically pinged. I just added my name on the list 😅

2022-12-02 20:29 UTC, cferdinandi commented
@bryandonmarc How odd! I don't use typescript at all (including in the referenced package, which _is_ my work). Thanks for the info!

2022-12-02 20:31 UTC, bryandonmarc commented
Yup! I love your work and wanted to use it in my current project. TypeScript kept complaining so after making the type declarations myself, I guessed I might as well contribute it as the previous types were VERY outdated. Cheers!

2022-12-22 23:18 UTC, sandersn requested changes
Looks good but please remove @cferdinandi from the maintainer list.

2022-12-22 23:18 UTC, sandersn commented on types/reefjs/index.d.ts
>  //                 cferdinandi <https://github.com/cferdinandi>
Please remove @cferdinandi from the list since he's the original author, not the types author.

2022-12-22 23:18 UTC, sandersn commented on types/reefjs/v7/index.d.ts
> +// Type definitions for reefjs 7.6
Keeping the v7 types around is only needed if you will need to publish changes to `@types/reefjs@7` in the future. I'd guess that's not needed for reefjs types, but it's up to you.

2023-02-14 19:57 UTC, closed without merging