[react-dom] [react-native] fix incorrect typedefs for unstable_batchedUpdates
DefinitelyTyped/DefinitelyTyped pull request #63517
Opened 2022-12-07 06:47 UTC by k-yle

The type definitions of `unstable_batchedUpdates` have been wrong for a long time. It only accepts 2 arguments, not 3, and the return value from the callback is passed through. 

_**(Examples edited to remove unlikely async pattern)**_ 

This matters because the following code is flagged as wrong in VSCode:
```js
const result = unstable_batchedUpdates(() => {
    return 123;
});
```
VSCode/TS thinks that the return value from `unstable_batchedUpdates` is always `void`

---

The second issue is that only one argument is passed through to the callback function:

```js
unstable_batchedUpdates((x, y) => {
  console.log({ x, y });
}, 1, 2);
// the typedefs claim that this will print `{ x: 1, y: 2 }`. This is wrong. 
// It will actually print `{ x: 1, y: undefined }`. Only the first argument 
// is passed through.
```

---

Reference:
 - [react 18 source code](https://github.com/facebook/react/blob/v18.2.0/packages/react-reconciler/src/ReactFiberWorkLoop.new.js#L1319-L1337)
 - [react 17 source code](https://github.com/facebook/react/blob/v17.0.2/packages/react-reconciler/src/ReactFiberWorkLoop.new.js#L1128-L1141)
 - [react 16 source code](https://github.com/facebook/react/blob/v16.14.0/packages/react-reconciler/src/ReactFiberWorkLoop.new.js#L1128-L1141)
 - [react-native 0.71 source code](https://github.com/facebook/react-native/blob/0.71-stable/Libraries/ReactNative/RendererImplementation.js#L99-L108)

 ---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: _See links above_
- [x] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~

2022-12-07 06:58 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-dom ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-dom@latest/))
was missing the following properties:
1. createRoot
1. hydrateRoot
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6a87d56c13a5c01b85ff98cf9b62109e9d4c99a7
</p>

2022-12-07 19:36 UTC, eps1lon requested changes
Considering the React source, it doesn't look like you're supposed to use async functions as a callback at all. 

Do you have any documentation/mentions of this usage outside of "this is how it behaves at runtime"?

2022-12-07 20:02 UTC, k-yle commented
@eps1lon, there seems to be no official documentation on `unstable_batchedUpdates`, but this async pattern is useful when working with `redux-thunk`. So understanding how it behaves at runtime is the closest thing we have to documentation...

2022-12-07 20:22 UTC, eps1lon commented
> So understanding how it behaves at runtime is the closest thing we have to documentation...

But you understand that if you pass an async function, it will not run in a batched context. Only what's executed synchronously runs in a batched context which is why I'm hesitant to extend support for async functions considering they're likely not behaving as you think they do.

2022-12-07 20:44 UTC, k-yle commented
yeah, I guess my original example is a bit pointless. It is still useful for a non-async function that returns a promise or an async self-invoking function. And of course, if you want to return a normal non-async value from the callback

```js
await unstable_batchedUpdates(() => {
    action1();
    action2();
    action3();
    return somePromise;
});
// this is valid, and the first 3 actions will be batched
```

2022-12-18 06:59 UTC, k-yle commented
I've removed the unlikely async examples and rebased

2023-01-22 21:35 UTC, k-yle commented
Hi @jakebailey, how long is this PR meant to sit in the "Waiting for Code Reviews" category? I thought the threshold was lower than a month

2023-01-22 23:11 UTC, k-yle commented
CI is failing because of https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1468, not because of an issue with this PR

2023-02-15 00:09 UTC, gabritto approved these changes

2023-02-15 00:22 UTC, k-yle commented
Ready to merge

2023-02-15 00:23 UTC, merged

2023-02-16 07:25 UTC, lunaleaps commented
@k-yle Do you mind also updating the React Native types here: https://github.com/facebook/react-native/blob/main/types/public/ReactNativeRenderer.d.ts#L143

We will be deprecating the react-native types here soon. Thank you!

2023-02-16 09:19 UTC, k-yle commented
@lunaleaps done: https://github.com/facebook/react-native/pull/36180