Add typings for passport-openidconnect@0.1.1
DefinitelyTyped/DefinitelyTyped pull request #63673
Opened 2022-12-19 21:34 UTC by elmaxe

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2022-12-19 21:47 UTC, elmaxe commented
Looked a lot at @pasieronen's @types/passport-oauth2

2022-12-20 19:30 UTC, peterblazejewicz commented on types/passport-openidconnect/index.d.ts
> +// TypeScript Version: 2.3
hm, this sounds like the past decade only, so:
```suggestion
```

2022-12-20 19:32 UTC, peterblazejewicz commented on types/passport-openidconnect/tslint.json
> +}
why do you need all of those? Exclusions requires special cases, sorry!

2022-12-20 19:41 UTC, peterblazejewicz commented on types/passport-openidconnect/index.d.ts
> +    }
so reall, does it work for you?
```js
const { InternalOAuthError } = require('passport-openidconnect');
```
please do not export symbols that do not exist on native module

2022-12-31 00:38 UTC, Woodpile37 approved these changes

2023-01-11 22:49 UTC, rbuckton commented
@elmaxe, several reviewers have left feedback. Can you follow up?

2023-01-12 13:47 UTC, elmaxe commented
> @elmaxe, several reviewers have left feedback. Can you follow up?

Yes I will when I have time!

2023-01-23 20:29 UTC, sheetalkamat requested changes
Please address feedback

2023-02-24 01:07 UTC, closed without merging