Type package for the npm unix-time package
DefinitelyTyped/DefinitelyTyped pull request #63874
Opened 2023-01-10 21:12 UTC by b1z3rr4

# Type package for the npm unix-time package
**This is a branch that aims to add a new type package that references the unix-time npm package**

**I'm not the creator of the original npm package, but I use it frequently and in case of code changes or deletions, I'll be careful to update here.**

**Find it at: [Package unix-time](https://www.npmjs.com/package/unix-time)
Me: [b1z3rr4](https://github.com/b1z3rr4)**

2023-01-11 22:50 UTC, peterblazejewicz commented on types/unix-time/index.d.ts
> +declare const unixTime: UnixTime
when using scaffold code with templates for module, all the 'docu' like stuff is added (header file with version/author/reference).
There wouldn't be required to add all those excusions.

2023-01-11 23:01 UTC, peterblazejewicz commented
The `LICENSE` file to be shipped with package would probably require to be added in additional file: 'OTHER_FIILES':
https://github.com/DefinitelyTyped/DefinitelyTyped#other_filestxt
I don't recall personally DT package shipping it's own license, to be checked

2023-01-23 21:43 UTC, sheetalkamat requested changes
Fix the CI errors

2023-01-23 21:43 UTC, sheetalkamat commented on types/unix-time/.eslintrc.json
> +    "rules": {
remove this file

2023-01-23 21:43 UTC, sheetalkamat commented on types/unix-time/tslint.json
> +    }
```suggestion
```
Fix errors after removing the rules

2023-01-23 21:43 UTC, sheetalkamat commented on types/unix-time/.eslintrc.json
> +    }
Please use template as suggested at https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package so you arent adding unnecessary files.

2023-02-24 01:06 UTC, closed without merging