[jest] type done callback on each
DefinitelyTyped/DefinitelyTyped pull request #63882
Opened 2023-01-11 13:25 UTC by staff0rd

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Docs don't appear to mention this, but an issue regarding this gap was raised here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34617

## Note

I also added a test case for `ReadonlyArray` declaration, however I was unable to fix it for the done callback as the variadic tuple approach doesn't appear to work there, ie:

```typescript
<T extends ReadonlyArray<any>>(cases: ReadonlyArray<T>): (
            name: string,
            fn: (...t: [...args: T, done: DoneCallback) => any,  // results in arguments being typed T | DoneCallback
            timeout?: number,
        ) => void;
```

2023-01-11 13:51 UTC, domdomegg approved these changes

2023-01-11 14:02 UTC, mrazauskas approved these changes

2023-01-11 18:32 UTC, mrazauskas commented
Hm.. I just tried to implement this in Jest’s building typings and found out that following case current works, but fails after this change is made:

```ts
test.each([
    [
        { supportsDynamicImport: true, supportsStaticESM: true },
        { supportsDynamicImport: true, supportsStaticESM: true },
    ],
    [{ supportsDynamicImport: true }, { supportsDynamicImport: true, supportsStaticESM: false }],
])('%j -> %j', (input, output) => {
    console.log(input);
    console.log(output);
});
```

This and few more type errors surfaced in Jest repo. See CI failures in https://github.com/facebook/jest/pull/13756

2023-01-11 19:08 UTC, mrazauskas requested changes
Posting this 'request changes' review just to draw attention to the problem mentioned above. Jest repo does not use `@types/jest`, but this PR has the same issue which surfaced in the above mentioned PR. For example:

```ts
test.each([
  ['Boolean', {automock: []}],
  ['Array', {coverageReporters: {}}],
  ['String', {preset: 1337}],
  ['Object', {haste: 42}],

// requires to add this type cast, if change from this PR is implemented
// currently type check is passing without the cast

] as Array<[string, Record<string, unknown>]>)(
  'pretty prints valid config for %s',
  (_type, config) => {
    expect(() =>
      validate(config, {
        exampleConfig: validConfig,
      }),
    ).toThrowErrorMatchingSnapshot();
  },
);
```

2023-01-26 15:49 UTC, mrazauskas commented
@staff0rd Partial support for `done` callback typings just landed in Jest repo. One dimensional array, array of object literals and template literal table are supported. See https://github.com/facebook/jest/pull/13756

Perhaps this PR could take similar path for now?

2023-02-22 11:24 UTC, staff0rd commented
@mrazauskas i added the test case you found to be breaking in and reduced the typing to not cater for the array-of-arrays syntax

2023-02-22 12:25 UTC, mrazauskas approved these changes
Thanks!

2023-03-05 18:15 UTC, domdomegg approved these changes

2023-03-13 17:57 UTC, mrazauskas approved these changes

2023-03-13 20:00 UTC, jakebailey approved these changes

2023-03-15 05:12 UTC, mrazauskas commented
Ready to merge

2023-03-15 05:13 UTC, merged

2023-03-15 05:13 UTC, mrazauskas commented
Thanks again. I just wanted to see this merged finally.