Power Bank from OwnedStructure to Structure
DefinitelyTyped/DefinitelyTyped pull request #63973
Opened 2023-01-18 19:02 UTC by pbrink231

Power bank does not have owner or my properties.

changed from OwnedStructure to Structure, similar to a road or wall

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: [https://docs.screeps.com/api/#StructurePowerBank](Power Bank Doc)

2023-02-14 22:55 UTC, gabritto approved these changes

2023-02-15 04:27 UTC, dmarcuse commented
Before this is merged - it's been a while since I've worked on this project, but I remember that changes are supposed to go through https://github.com/screepers/typed-screeps first and then the types updated based on that. Has this change been submitted there yet?

2023-02-15 04:28 UTC, dmarcuse requested changes
See comment in PR, just want to make sure this isn't erroneously merged if it hasn't gone through the screepers repository yet

2023-02-20 12:27 UTC, DiamondMofeng requested changes
No, PowerBank does have `owner` and `my`. It was designed for `FIND_HOSTIAL_STRUCTURES`.

2023-03-23 12:59 UTC, closed without merging