"Natural" package - add "removeStopWords" function
DefinitelyTyped/DefinitelyTyped pull request #64016
Opened 2023-01-21 09:05 UTC by PWhiddy

This adds this important function defined here:

https://github.com/NaturalNode/natural/blob/a5bdd5580928c9565107b28c416ce62e83ad2503/lib/natural/stemmers/stemmer.js#LL47C39-L47C52

To the typescript interface so that it can be known to typescript.

If changing an existing definition:
- [X ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

2023-01-21 09:24 UTC, PWhiddy commented
Added a test in a second commit, then squashed them both into one.

2023-02-03 19:35 UTC, forivall requested changes
looks good other than the small tweak i've requested, sorry for the delay.

2023-02-03 19:35 UTC, forivall commented on types/natural/index.d.ts
>      stem(token: string): string;
Prefer source order.
```suggestion
    stem(token: string): string;
    removeStopWords(moreStopWords: string[]): void;
```

2023-02-08 20:46 UTC, PWhiddy commented
@forivall 
Look good?

2023-02-08 20:59 UTC, forivall approved these changes
Lgtm!

2023-02-08 21:58 UTC, PWhiddy commented
Ready to merge

2023-02-08 21:59 UTC, merged