feat(restify): Add v9 typings.
DefinitelyTyped/DefinitelyTyped pull request #64087
Opened 2023-01-25 18:32 UTC by connyay

async/await support for request handlers and removed RequestCaptureStream

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/restify/node-restify/tree/v9.0.0
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-01-25 18:44 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## restify ([<kbd>unpkg</kbd>](https://unpkg.com/browse/restify@latest/))
was missing the following properties:
1. logger
1. helpers
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 24eba16f6a6819732323c91432c0c0fe2e52f265
</p>

2023-01-30 16:42 UTC, connyay commented
@blittle @stevehipwell @leanazulyoro @mgebundy @alcmoraes @quinnlangille @GaikwadPratik is anyone available to check this out? Trying to leverage https://github.com/restify/node-restify/pull/1833 with the existing types is frustrating

2023-02-14 11:29 UTC, stevehipwell commented
I want to be removed from this repo but it doesn't appear that there are any maintainers to do this https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64095!

2023-02-14 21:16 UTC, gabritto commented
Re-pinging @blittle @leanazulyoro @mgebundy @alcmoraes @quinnlangille @GaikwadPratik: it would be great if an owner could take a look at this.

@connyay could you point to specific places in the original codebase or in its documentation that refer specifically to the changes you're proposing? I see you posted a link to the original library, but as someone unfamiliar with it, it's hard to navigate it to validate that the v9 typings are correct.

2023-02-21 23:06 UTC, andrewbranch requested changes
This looks incomplete according to their [changelog](https://github.com/restify/node-restify/blob/v9.0.0/CHANGELOG.md). For example, the `bunyan` namespace is completely gone and replaced with `pino`, whatever that is.

2023-03-25 01:06 UTC, closed without merging