Freeze version of @hapi/hapi temp. at 21.1.0
DefinitelyTyped/DefinitelyTyped pull request #64090
Opened 2023-01-25 21:19 UTC by peterblazejewicz

Similarly to solution from #64018 this commit freezes version of @hapi/hapi at 21.1.0 to avoid unexpected impact on consuming packages and ecosystem after @hapi/hapi@21.2.0 types updates.

See also:
https://github.com/hapijs/hapi/pull/4419

Thanks!

/cc [Alexthemediocre](https://github.com/Alexthemediocre)

2023-01-25 22:00 UTC, SimonSchick approved these changes
Ran into this too, thank you!

2023-01-26 00:40 UTC, Alexthemediocre commented
Thanks!

2023-01-26 12:34 UTC, lenovouser commented
In the upstream repository they are saying that is because the types from here are still being used (instead of the direct ones in `@hapi/mimos`) → https://github.com/hapijs/hapi/pull/4419

Wouldn't it be better to move to that then instead here as well? Or am I missing something?

2023-01-26 16:41 UTC, sandersn approved these changes

2023-01-26 17:07 UTC, sandersn commented
@lenovouser @peterblazejewicz I tested this and indeed the old types for `@hapi/mimos` in DT are conflicting with the up-to-date version. The correct fix is to delete `@hapi/mimos` from DT.

2023-01-26 18:52 UTC, sandersn requested changes
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64098 is a better fix.

2023-01-27 10:19 UTC, Semigradsky commented
There is still a problem with `@hapi/h2o2`:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63878/checks

```
Error in hapi__h2o2
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/hapi__h2o2/index.d.ts:217:59
ERROR: 217:59  expect  TypeScript@5.0 compile error: 
Cannot find name 'ResponseObject'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
    at runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:176:5)
```

2023-01-27 11:00 UTC, lenovouser commented
@Semigradsky probably fixed with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64103. You might still encounter issues with `ResponseObject` in the future until a version of `@hapi/hapi` with this https://github.com/hapijs/hapi/pull/4415 change has been released.

2023-01-27 20:01 UTC, peterblazejewicz commented
Closing as no longer required, thx!

2023-01-27 20:01 UTC, closed without merging