add missing connect method in superagent request object
DefinitelyTyped/DefinitelyTyped pull request #64225
Opened 2023-02-04 22:26 UTC by reuzel

superagent allows for overriding DNS. See [Request.prototype.connect](https://github.com/ladjs/superagent/blob/cd094f523f8c02808e00ee65bf3ac1624c9300a8/src/node/index.js#L1308). Documentation [here](https://github.com/ladjs/superagent/blob/master/docs/index.md#forcing-specific-connection-ip-address). This pull requests adds that missing method to the type definitions.

2023-02-04 22:31 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## superagent ([<kbd>unpkg</kbd>](https://unpkg.com/browse/superagent@latest/))
was missing the following properties:
1. Request
1. Response
1. protocols
1. buffer
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8e7093e7eea4d32aa734634290d8517def86abd3
</p>

2023-02-13 21:16 UTC, gabritto requested changes
The change looks correct, but these type definitions are currently for version 4.1 of superagent, and on version 4.1 it doesn't look like `Request` had a method called `connect`.

So for this change to be correct, I think you need to:
(1) Bump the superagent version on the DT header of `index.d.ts` to a newer version where `Request` has a `connect` method
(2) Make sure the rest of the existing type definitions is compatible with this newer version.

Thank you.

2023-03-13 22:33 UTC, reuzel commented
Hi,

Just checked (sorry for the delay) but the connect method was introduced in version 4.1. See [4.1.0 tag notes](https://github.com/ladjs/superagent/releases/tag/v4.1.0) and [connect method in 4.1.0 commit](https://github.com/ladjs/superagent/blob/8580c4f5c4f515fdc2f703b41f0affed4613e958/lib/node/index.js#L1177)

For this reason, I don't think the pull request requires changes.

2023-04-07 08:40 UTC, reuzel commented
@gabritto Please accept this change. The added method was added to version 4.1, so no changes needed before this can be merged.

Regards,
Joost

2023-04-07 13:11 UTC, carnesen approved these changes
From the links provided by @reuzel it does seem to be the case that superagent added the `connect` method in 4.1 and without this MR, that method is missing from the @types/superagent@4.1 types. I've also verified by inspecting the implementation and documentation that the type is a good representation of the underlying JS. TL;DR : LGTM!

2023-04-25 22:10 UTC, lukaselmer approved these changes

2023-04-26 12:13 UTC, joostreuzel commented
Is this pull request now stuck on @gabritto's review? What do I need to do next to get it merged?

2023-04-26 16:42 UTC, gabritto approved these changes

2023-04-26 17:04 UTC, merged