Added type declarations for the 'git-init' NPM package.
DefinitelyTyped/DefinitelyTyped pull request #64245
Opened 2023-02-06 20:21 UTC by santi100a

Please fill in this template.

- [] Use a meaningful title for the pull request. Include the name of the package modified.
- [] Test the change in your own code. (Compile and run.)
- [] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2023-02-08 20:59 UTC, peterblazejewicz commented on index.d.ts
> +// Type definitions for git-init
what's this file for?
In doubt, please re-run:
```console
npx dts-gen --dt --name git-init --template module
```
to scaffold proper type declaration files structure for `git-init`:
https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package

2023-02-08 21:00 UTC, peterblazejewicz commented on types/git-init/LICENSE
> +The MIT License (MIT)
I believe the repo content is hosted and released under same license already:https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/LICENSE

2023-02-08 21:03 UTC, peterblazejewicz commented on types/git-init/index.d.ts
> +export default init;
the native module is 8 years old CommonJS file, it cannot be ESM with `default` export:
https://github.com/yoshuawuyts/git-init/blob/master/index.js#L3
please use generator in doubt, also review concept of CJS exports in TS:
https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require

2023-02-08 21:05 UTC, peterblazejewicz commented on types/git-init/package.json
> +{
please remove this file, unless the intent was to add external dependencies.
In doubt, please re-run generate command as explained, to scaffold content

2023-02-08 21:06 UTC, peterblazejewicz requested changes
@santi100a thanks for the errors, please make amends as pointed in the comments, thanks!

2023-02-13 20:03 UTC, gabritto requested changes
Please fix what's been pointed out in the comments. Thanks.

2023-03-17 01:06 UTC, closed without merging

2023-05-15 19:31 UTC, santi100a commented
Superseded by #65055 and #65496.