[navermaps] Fix typo in DrawingEvent and types of DrawingOptions
DefinitelyTyped/DefinitelyTyped pull request #64288
Opened 2023-02-09 16:01 UTC by jglee96

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://navermaps.github.io/maps.js.ncp/docs/tutorial-3-drawing-restore.example.html>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-02-09 16:31 UTC, SuhwanCha requested changes
Please fix test cases to cover changes, and please reference document about `DrawingEvent"s"`. I can only find document about `DrawingEvent`

2023-02-09 16:31 UTC, SuhwanCha commented on types/navermaps/navermaps-tests.ts
> +        rectangleOptions: {
`rectangleOptions` is changed to optional parameter, but this test case could't cover changes

2023-02-09 16:31 UTC, SuhwanCha commented on types/navermaps/navermaps-tests.ts
> +        ellipseOptions: {
same here

2023-02-09 16:31 UTC, SuhwanCha commented on types/navermaps/navermaps-tests.ts
> +        polylineOptions: {
same here

2023-02-09 16:31 UTC, SuhwanCha commented on types/navermaps/navermaps-tests.ts
> +        arrowlineOptions: {
same here

2023-02-09 16:31 UTC, SuhwanCha commented on types/navermaps/navermaps-tests.ts
> +        polygonOptions: {
same here

2023-02-09 16:46 UTC, SuhwanCha commented on types/navermaps/index.d.ts
> +            markerOptions?: Partial<MarkerOptions>;
And we don’t need `Partial` here because constructor of `...Options` has optional parameters.

2023-02-10 00:17 UTC, kkokkojeong commented on types/navermaps/index.d.ts
> +        enum DrawingEvents {
As a result of checking the internal code, 'DrawingEvent' seems to be correct.

2023-02-10 00:24 UTC, kkokkojeong commented on types/navermaps/index.d.ts
> +        enum DrawingEvents {
한국분이시니까 한국말로 설명드릴게요.
`naver.maps.drawing.DrawingEvents` 는 이벤트목록을 나타나는 객체입니다. 타입 `DrawingEvent ` 는 `DrawingEvents` 이벤트의 이름을 나타내는 타입일뿐, 두 관계가 일치하지 않습니다.

```js
naver.maps.drawing.DrawingEvents = {
    START: 'drawing_start',
    ADD: 'drawing_added',
    REMOVE: 'drawing_removed',
    CANCLE: 'drawing_cancled',
    SELECT: 'drawing_selected'
}
```

```ts
interface DrawingEvent {
        START: 'drawing_start',
        ADD: 'drawing_added',
        REMOVE: 'drawing_removed',
        CANCLE: 'drawing_cancled',
        SELECT: 'drawing_selected'
    }
```

명확하게 나타낼 수 있도록 제가 따로 수정하도록 하겠습니다. 해당 PR에서 이 부분은 제거 부탁드립니다.

2023-02-10 00:33 UTC, kkokkojeong commented on types/navermaps/index.d.ts
> +            markerOptions?: Partial<MarkerOptions>;
`PolylineOptions ` 의 경우 `path` 가 필수값이므로 `Partial`은 적절하지 않은 것 같습니다.

2023-02-10 00:41 UTC, kkokkojeong commented
@jglee96 님, 
안녕하세요. 타입 관련 수정 감사드리며 PR 코멘트 남겼습니다. 

@SuhwanCha 님 코멘트처럼 `Partial` 제거만 부탁드립니다.

잘못된 문서는 빠른시일내에 배포하도록 하겠습니다. 감사합니다.

2023-02-10 00:42 UTC, kkokkojeong commented on types/navermaps/navermaps-tests.ts
> +        rectangleOptions: {
새로 추가된 테스트코드니까 그대로 둬도 될 것 같아요. 제가 따로 생성자 파리미터 optional 일때 테스트코드 추가하겠습니다.
늘 꼼꼼한 PR 감사합니다.👍

2023-02-10 01:26 UTC, jglee96 commented on types/navermaps/index.d.ts
> +            markerOptions?: Partial<MarkerOptions>;
[가이드](https://navermaps.github.io/maps.js.ncp/docs/naver.maps.drawing.DrawingManager.html)에 따르면 `DrawingManger`의 `DrawingOptions`에서 도형 옵션들인 `rectangleOptions`, `ellipseOptions`, `polylineOptions`, `arrowlineOptions`, `polygonOptions`, `markerOptions `은 

> 임의의 크기, 위치 또는 지도의 값을 전달하면 무시됩니다.

라고 되어있습니다. 그래서 [Example](https://navermaps.github.io/maps.js.ncp/docs/tutorial-3-drawing-restore.example.html)을 보면 bound, path와 같은 속성들은 설정해주지 않고있습니다. 그런데도 required 속성으로 되어있어 위와 같이 수정하였습니다.

혹시 무시되는 값이지만 내부 코드상으로 일단 넘겨주어야 하는 값인가요?

2023-02-10 02:18 UTC, kkokkojeong commented on types/navermaps/index.d.ts
> +            markerOptions?: Partial<MarkerOptions>;
내부적으로 예외처리를 해서 상관없지만, **타입으로는 강제하는게 맞을 것 같네요.**
`path` 를 예를 들면 값을 넘겨주지 않아도 빈 배열(=`[]`)로 초기화해주고 있습니다.

2023-02-10 04:35 UTC, SuhwanCha commented on types/navermaps/index.d.ts
> +            markerOptions?: Partial<MarkerOptions>;
[Document](https://navermaps.github.io/maps.js.ncp/docs/naver.maps.Rectangle.html#toc24__anchor)에는 optional 표시가 안되어있는데, 값이 없어도 작동을 하니 `Partial`으로 처리하는게 좋을 것 같습니다 ㅎㅎ
문서에 @kkokkojeong 님께서 위에 작성해주신 내용이 요약되어있으면 더 좋을 것 같습니다👍👍

2023-02-10 05:45 UTC, kkokkojeong commented on types/navermaps/index.d.ts
> +            markerOptions?: Partial<MarkerOptions>;
@SuhwanCha 네, 문서 보강하도록 하겠습니다.
Drawing 관련 문서오류는 2/16(목)에 배포예정입니다.
 - DrawingEvent -> DrawingEvents

2023-02-10 05:45 UTC, kkokkojeong approved these changes

2023-02-10 06:49 UTC, jglee96 commented on types/navermaps/index.d.ts
> +            markerOptions?: Partial<MarkerOptions>;
확인 감사드립니다. 👍

2023-02-13 07:05 UTC, SuhwanCha approved these changes

2023-02-13 09:07 UTC, jglee96 commented
Ready to merge

2023-02-13 09:08 UTC, merged