feat(workerpool): update to version 6.3
DefinitelyTyped/DefinitelyTyped pull request #64339
Opened 2023-02-14 11:06 UTC by Michsior14

Updates the workerpool types to version 6.3.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [](https://github.com/josdejong/workerpool/compare/v6.1.0...v6.3.1)
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-02-24 17:11 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## workerpool ([<kbd>unpkg</kbd>](https://unpkg.com/browse/workerpool@latest/))
was missing the following properties:
1. Transfer
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8702c2e8014510a8c563c2dd090a23af40034068
</p>

2023-02-25 01:10 UTC, forivall commented
I notice that you checked the "Provide a URL to documentation or source code which provides context for the suggested changes:", but I dont see a URL? PR looks good, but I'd like to see their docs!

2023-02-25 01:13 UTC, Michsior14 commented
> I notice that you checked the "Provide a URL to documentation or source code which provides context for the suggested changes:", but I dont see a URL? PR looks good, but I'd like to see their docs!

Sorry, formatting issue, fixed ;)

2023-03-02 02:04 UTC, forivall requested changes
from the docs, looks like the type signatures arent quite right.

2023-03-02 02:10 UTC, forivall commented on types/workerpool/index.d.ts
> +    constructor(message: any, transfer: any[]);
it requires the dom typing, but `transfer` should be `Transferable[]`
```suggestion
    constructor(message: any, transfer: Transferable[]);
```

2023-03-07 17:45 UTC, forivall approved these changes
LGTM! thanks

2023-03-07 22:15 UTC, Michsior14 commented
Ready to merge

2023-03-07 22:15 UTC, merged