[eslint] Fix `reportUnusedDisableDirectives`
DefinitelyTyped/DefinitelyTyped pull request #64421
Opened 2023-02-19 19:32 UTC by fasttime

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
  - docs: https://eslint.org/docs/latest/integrate/nodejs-api#linting
  - JSDoc: https://github.com/eslint/eslint/blob/v8.34.0/lib/eslint/eslint.js#L66
  - runtime type check: https://github.com/eslint/eslint/blob/v8.34.0/lib/eslint/eslint.js#L260-L267 
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

The `ESLint` constructor option `reportUnusedDisableDirectives` does not accept the numeric severity values 0, 1 or 2 allowed for rules. Using an unsupported value will result in a runtime error.

This PR fixes the type of `reportUnusedDisableDirectives` to reflect the fact that only the values `"error"`, `"warn"`, `"off"` or `null` are allowed.

2023-03-07 01:59 UTC, bradzacher requested changes
instead of copy-pasting the union - we should probably split the old one into two (numbers and strings) and then reference the string one here.

that way there's no risk of the two sites getting out-of-sync.

2023-03-08 21:51 UTC, fasttime commented
> instead of copy-pasting the union - we should probably split the old one into two (numbers and strings) and then reference the string one here.
> 
> that way there's no risk of the two sites getting out-of-sync.

Okay, I added a new union type `StringSeverity` for `"error"`, `"warn"` and `"off"`. The name of the numeric union type is still `Severity`. If backward compatibility is not a concern, we could go further and rename `Severity` to `NumericSeverity` for a more consistent nomenclature.

2023-03-08 22:04 UTC, bradzacher approved these changes

2023-03-13 18:34 UTC, jakebailey approved these changes

2023-03-19 19:24 UTC, fasttime commented
Ready to merge

2023-03-19 19:25 UTC, merged