[navermaps] add DrawingManager setOptions/getOptions type
DefinitelyTyped/DefinitelyTyped pull request #64426
Opened 2023-02-20 07:48 UTC by jglee96

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://navermaps.github.io/maps.js.ncp/docs/tutorial-2-drawing-options.example.html>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-02-20 09:19 UTC, SuhwanCha requested changes
Thanks for the contribution! There are not `setOptions` and `getOptions` in [Official document](https://navermaps.github.io/maps.js.ncp/docs/naver.maps.drawing.DrawingManager.html), but I can find that methods in latest version. 
I have few comments about test case, please check it!

@kkokkojeong,  Please check document!

2023-02-20 09:19 UTC, SuhwanCha commented on types/navermaps/navermaps-tests.ts
> -    const drawingManager = new naver.maps.drawing.DrawingManager({
Is the existing `DrawingManager` unavailable? Otherwise, it would be better to add a new test case instead of modifying the existing test case.

2023-02-20 14:07 UTC, jglee96 commented on types/navermaps/navermaps-tests.ts
> -    const drawingManager = new naver.maps.drawing.DrawingManager({
기존의 test case와 겹치는 내용이라고 생각하여 수정하는 방안으로 진행하였습니다. 그래도 추가하는 방안이 괜찮을까요?

2023-02-21 01:50 UTC, kkokkojeong commented on types/navermaps/navermaps-tests.ts
> +    drawingManager.getOptions('markerOptions')?.zIndex;
LGTM. you're meticulous.

2023-02-21 01:55 UTC, kkokkojeong commented on types/navermaps/navermaps-tests.ts
> -    const drawingManager = new naver.maps.drawing.DrawingManager({
파라미터 없이 객체 생성에 대한 테스트 케이스 추가하고 싶은거라면, 아래처럼 하면 되지 않을까요?
위 의도가 아니면 기존 객체 생성 코드 유지가 더 맞을 것 같네요. 

수정하신 샘플url에서도 옵션값 넘겨주면서 생성하고 있네요
https://navermaps.github.io/maps.js.ncp/docs/tutorial-2-drawing-options.example.html

```ts
const drawingManager = new naver.maps.drawing.DrawingManager();
const drawingManagerWithOptions = new naver.maps.drawing.DrawingManager(drawingManagerOptions);
//...
// add test-case of setOptions, getOptions 
```

2023-02-21 02:41 UTC, SuhwanCha commented on types/navermaps/navermaps-tests.ts
> -    const drawingManager = new naver.maps.drawing.DrawingManager({
@jglee96 , 기존 테스트 케이스에서 테스트하고 있는 방법들이 deprecate 된 것이 아니라면 기존 테스트는 유지하고, 이번 PR에서 추가하신 부분을 테스트하는 테스트 케이스를 새로 추가하는 것이 좋을 것 같습니다. 👍

2023-02-21 04:24 UTC, jglee96 commented on types/navermaps/navermaps-tests.ts
> -    const drawingManager = new naver.maps.drawing.DrawingManager({
넵 수정하도록 하겠습니다!

2023-02-21 15:53 UTC, SuhwanCha approved these changes
![32384589-a60f0e74-c078-11e7-9bc1-e5b5287aea9d.png](https://user-images.githubusercontent.com/16171447/220394158-672f21dc-a797-49b0-a16a-77a9ee0ee343.png)

Thank you for your contribution!

2023-02-22 00:02 UTC, jglee96 commented
Ready to merge

2023-02-22 00:03 UTC, merged