Updates HLS Parser options type
DefinitelyTyped/DefinitelyTyped pull request #64443
Opened 2023-02-21 18:11 UTC by CodyDunlap

Updated options to match allowed values in `hls-parser` library: https://github.com/kuu/hls-parser#supported-options

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/kuu/hls-parser#supported-options
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header. It doesn't. I just provides properties that were missing.

2023-02-26 20:24 UTC, joeflateau requested changes
The options should all be optional and please add tests to the tests file

2023-02-27 17:49 UTC, joeflateau approved these changes

2023-02-27 17:50 UTC, CodyDunlap commented
> The options should all be optional and please add tests to the tests file

The options were effectively optional already because the `setOptions` takes a Partial<Options> parameter, but I went ahead and made the object use optional booleans as well and added tests.

2023-02-28 05:18 UTC, screendriver approved these changes
LGTM

2023-02-28 05:22 UTC, screendriver commented
Ready to merge

2023-02-28 05:23 UTC, merged