node v19.6 newly added statfs function + related objects
DefinitelyTyped/DefinitelyTyped pull request #64510
Opened 2023-02-27 18:16 UTC by sovcik

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [https://nodejs.org/api/fs.html#fspromisesstatfspath-options]
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-02-27 19:57 UTC, Semigradsky commented
@sovcik As you see `@types/node` does not contain types for Node.js v19.x

2023-02-28 06:29 UTC, sovcik commented
lint issue causing build to fail fixed by dtslint team in https://github.com/microsoft/DefinitelyTyped-tools/issues/621

2023-02-28 09:42 UTC, sovcik commented
> @sovcik As you see `@types/node` does not contain types for Node.js v19.x

@Semigradsky  aaah, now I see... well... then we have to wait

2023-03-07 21:07 UTC, Semigradsky commented
@sovcik `statfs`/`statfsSync` were added to v18.15.0

2023-03-11 13:03 UTC, Semigradsky requested changes

2023-03-11 13:03 UTC, Semigradsky commented on types/node/fs.d.ts
> +     * @since v19.6.0
Please update to `@since v18.15.0`

2023-03-11 13:03 UTC, Semigradsky commented on types/node/fs/promises.d.ts
> +     * @since v19.6.0
ditto

2023-03-12 08:49 UTC, sovcik commented on types/node/fs/promises.d.ts
> +     * @since v19.6.0
done, thanks

2023-03-12 08:49 UTC, sovcik commented on types/node/fs.d.ts
> +     * @since v19.6.0
done. thanks

2023-03-12 14:23 UTC, Semigradsky approved these changes

2023-03-12 20:33 UTC, peterblazejewicz approved these changes
@sovcik thanks!

2023-03-13 04:46 UTC, Semigradsky commented
Ready to merge

2023-03-13 04:46 UTC, merged

2023-03-13 07:48 UTC, sovcik commented
@Semigradsky thanks for help. Sorry for not getting your initial comments related to node version.