LZ4: Add compressionLevel arg to encodeBlockHC
DefinitelyTyped/DefinitelyTyped pull request #64586
Opened 2023-03-05 11:45 UTC by johan13

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [lz4_binding.cc#L60](https://github.com/pierrec/node-lz4/blob/master/lib/binding/lz4_binding.cc#L60)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-03-05 11:51 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## lz4 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/lz4@latest/))
was missing the following properties:
1. MAGICNUMBER
1. MAGICNUMBER_BUFFER
1. EOS
1. EOS_BUFFER
1. VERSION

<details>
<summary>as well as these 7 other properties...</summary>
<p>MAGICNUMBER_SKIPPABLE, blockMaxSizes, extension, STATES, SIZES, utils, version</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5261c10a36bcfa58e135b5ffc824ef5c3a9690b2
</p>

2023-03-05 18:10 UTC, BendingBender requested changes
This won't work until https://github.com/pierrec/node-lz4/pull/116 is applied.

2023-04-06 22:21 UTC, BendingBender approved these changes

2023-04-07 06:58 UTC, johan13 commented
Ready to merge

2023-04-07 06:59 UTC, merged