Update Raycaster.d.ts
DefinitelyTyped/DefinitelyTyped pull request #64610
Opened 2023-03-06 21:39 UTC by promontis

https://github.com/mrdoob/three.js/blob/master/examples/jsm/lines/LineSegments2.js#L277 also uses `raycaster.params.Line2`

2023-03-06 21:44 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## three ([<kbd>unpkg</kbd>](https://unpkg.com/browse/three@latest/))
was missing the following properties:
1. BoxBufferGeometry
1. CapsuleBufferGeometry
1. CircleBufferGeometry
1. ConeBufferGeometry
1. CylinderBufferGeometry

<details>
<summary>as well as these 18 other properties...</summary>
<p>DodecahedronBufferGeometry, ExtrudeBufferGeometry, IcosahedronBufferGeometry, LatheBufferGeometry, LinearSRGBColorSpace, NoColorSpace, OctahedronBufferGeometry, PlaneBufferGeometry, PolyhedronBufferGeometry, RingBufferGeometry, SRGBColorSpace, ShapeBufferGeometry, SphereBufferGeometry, TetrahedronBufferGeometry, TorusBufferGeometry, TorusKnotBufferGeometry, TubeBufferGeometry, TwoPassDoubleSide</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6568032a2b996d907fcd5b6046f37271a8819469
</p>

2023-03-06 22:34 UTC, Methuselah96 commented
@promontis Can you make a PR on https://github.com/three-types/three-ts-types? Thanks!

2023-03-13 17:48 UTC, jakebailey requested changes
Seems like the authors expect these types to be updated at https://github.com/three-types/three-ts-types first.

2023-03-13 20:14 UTC, promontis commented
@Methuselah96 done

2023-04-14 01:07 UTC, closed without merging