[@types/react] fix: add missing RDFa properties to `HTMLAttributes`
DefinitelyTyped/DefinitelyTyped pull request #64972
Opened 2023-04-01 10:20 UTC by jeswr

This PR adds missing [RDFa Attributes](https://www.w3.org/TR/rdfa-core/#s_syntax) to the `HTMLAttributes` interface. 

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [NA] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests). - Was getting errors *before* making changes; the errors did not change after making the changes.

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[RDFa Attributes and Sytnax](https://www.w3.org/TR/rdfa-core/#s_syntax)>>

2023-04-01 10:32 UTC, eps1lon requested changes, later dismissed
I don't think common HTML attributes implement RDFa Core. [MDN says `rel` is specific to certain elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel).

Could you elaborate on how RDFa Core relates to the living standard? Especially if all HTML elements are supposed to implement all RDFa attributes.

2023-04-01 10:39 UTC, eps1lon commented
I think [HTML+RDFa](https://www.w3.org/TR/html-rdfa/#h-extensions-to-the-html5-syntax) is more relevant here. Added attributes are fine. But now we have some unnecessary props declarations e.g. `HTMLAnchorElement` also has `rel`. Could you remove redundant declarations?

2023-04-01 10:41 UTC, eps1lon requested changes
I think [HTML+RDFa](https://www.w3.org/TR/html-rdfa/#h-extensions-to-the-html5-syntax) is more relevant here. Added attributes are fine. 

But now we have some unnecessary props declarations e.g. `HTMLAnchorElement` also has `rel`. Could you remove redundant declarations?

2023-04-01 10:44 UTC, jeswr commented
Just to clarify @eps1lon - the redundant definition should be removed from the restricted type. i.e. `rel` would be removed from `HTMLAnchorElement`.

2023-04-01 11:41 UTC, eps1lon commented
If it doesn't narrow the type further down, yes

2023-04-03 19:58 UTC, eps1lon approved these changes
Looks good, thanks for sticking with it! CI failure is unrelated due.

2023-04-03 19:58 UTC, merged

2023-04-04 08:59 UTC, Hotell commented
folks this change triggered issues within our packages, can this be rolled back ? https://github.com/microsoft/fluentui/issues/27425

2023-04-06 00:32 UTC, jeswr commented
@hotell see https://github.com/microsoft/fluentui/issues/27425#issuecomment-1496749468

2023-04-06 08:27 UTC, eps1lon commented
Answered in https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64999#discussioncomment-5519075. This won't be rolled back.

2023-04-06 09:36 UTC, Hotell commented
thanks @jeswr for providing more context 🙌. 

your suggestion doesn't help unfortunately - pls see https://github.com/microsoft/fluentui/issues/27425#issuecomment-1498747145

To add more thoughts here:   Not sure what changed since I was active contributor to react types but the reasoning "the preparation for some upcoming feature"  is something that should not be allowed. How can you possibly distribute this to every users codebase ?

Unless react types will start to use `typeVersion`  or define higher TS minbar as is ATM `// TypeScript Version: 2.8`, this change should be rolled back as it introduces Breaking Change.

Don't get me wrong I understand how brittle and frustrating changes to react types are for both sides (maintainers and contributors)


@eps1lon suggestion is a good enough workaround. ty

2023-04-06 12:10 UTC, johnnyreilly commented
I concur with @eps1lon - breaking changes are almost a guarantee with Definitely Typed, semver is not practiced for a number of reasons: https://johnnyreilly.com/semantic-versioning-and-definitely-typed

Pinning to exact versions is a very good idea when it comes to types to minimise this kind of frustration.

That said - I'm glad there's a workaround that helps you