Add quit function for RSMQWorker client in rsmq-worker (0.3.30) package
DefinitelyTyped/DefinitelyTyped pull request #65053
Opened 2023-04-08 15:03 UTC by Saadat123456

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:https://www.npmjs.com/package/rsmq-worker#quit
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-04-27 18:17 UTC, gabritto requested changes

2023-04-27 18:17 UTC, gabritto commented on types/rsmq-worker/index.d.ts
> +        quit(): void;
It looks like this method was added on version 0.4.2. Could you update the header above to match that version? Thanks.

2023-04-28 16:43 UTC, gabritto approved these changes

2023-04-28 17:01 UTC, Saadat123456 commented
Ready to merge

2023-04-28 17:02 UTC, merged