[@types/express-serve-static-core] Add link and unlink method for Express Router
DefinitelyTyped/DefinitelyTyped pull request #65238
Opened 2023-04-21 09:44 UTC by quangtran88

Add missing `link` and `unlink` method for Express Router
Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://www.ietf.org/rfc/rfc2068.txt, missing LINK and UNLINK method https://github.com/jshttp/methods/issues/16
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-04-26 18:38 UTC, gabritto commented
I can't see how the RFC and issue links you provided relate to the type definitions in question, since I'm not an expert on these types or the original project. You can either try to explain it here in more details, and maybe I or some other DT maintainer will be able to review this change, or you can wait for an owner of these type definitions to review.

2023-05-02 21:47 UTC, andrewbranch requested changes
Echoing what Gabriela said, please provide a link to either docs or source code (as opposed to discussion) that proves the existence of these methods.

2023-05-03 02:48 UTC, quangtran88 commented
Hi @andrewbranch, documentation and source code which provides context for the suggested changes are updated.

2023-05-04 16:25 UTC, andrewbranch approved these changes

2023-05-13 03:09 UTC, quangtran88 commented
Ready to merge

2023-05-13 03:10 UTC, merged