New stubs: react-key-value
DefinitelyTyped/DefinitelyTyped pull request #65336
Opened 2023-04-28 20:03 UTC by ckchow

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2023-04-28 20:09 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-key-value ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-key-value@latest/))
was missing the following properties:
1. KeyValue
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 0401f87d805ab4b01a2ed971281693541464c18a
</p>

2023-05-03 23:44 UTC, andrewbranch requested changes
The README on npm is wrong; check the README on GitHub, and the [actual source code](https://github.com/purposeindustries/react-key-value) (the best source of truth). `KeyValue` is a named export, not the default or `module.exports`.

2023-05-03 23:44 UTC, andrewbranch commented on types/react-key-value/index.d.ts
> +export default KeyValue;
```suggestion
export default KeyValue;
```

2023-05-03 23:44 UTC, andrewbranch commented on types/react-key-value/index.d.ts
> +interface KeyValueProps {
```suggestion
export interface KeyValueProps {
```

2023-05-03 23:44 UTC, andrewbranch commented on types/react-key-value/index.d.ts
> +declare class KeyValue extends React.Component<KeyValueProps> {
```suggestion
export declare class KeyValue extends React.Component<KeyValueProps> {
```

2023-05-03 23:44 UTC, andrewbranch commented on types/react-key-value/react-key-value-tests.tsx
> +import KeyValue from 'react-key-value';
```suggestion
import { KeyValue } from 'react-key-value';
```

2023-05-03 23:52 UTC, ckchow commented
Thanks a bunch for the suggestions! I'm not super familiar with TS or react honestly so the explanation about the default export is appreciated.

2023-05-03 23:58 UTC, andrewbranch commented
My inline suggestions weren’t quite good enough to pass the linter. Can you fix the errors locally?

2023-05-04 01:04 UTC, andrewbranch approved these changes

2023-05-04 01:06 UTC, ckchow commented
Ready to merge

2023-05-04 01:06 UTC, merged