[jest] Change array matchers to allow readonly arrays
DefinitelyTyped/DefinitelyTyped pull request #65337
Opened 2023-04-28 20:19 UTC by forivall

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

> This is more of a quality of life change.

2023-04-29 04:16 UTC, mrazauskas requested changes
Looks good!

Could you add tests for all the changes? Seems like `.toHaveProperty()` is not covered at the moment. Or did I miss something?

2023-05-02 06:30 UTC, mrazauskas requested changes
Thanks. Test for `expect.not.arrayContaining` is still missing.

2023-05-02 12:45 UTC, domdomegg approved these changes

2023-05-29 17:39 UTC, mrazauskas approved these changes
Thanks!

2023-05-30 02:28 UTC, ExE-Boss approved these changes

2023-05-31 02:22 UTC, domdomegg approved these changes

2023-05-31 15:03 UTC, merged