Added definitions for "git-init" (supersedes #65055).
DefinitelyTyped/DefinitelyTyped pull request #65496
Opened 2023-05-14 22:53 UTC by santi100a

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [X] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [X] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2023-05-14 23:35 UTC, santi100a commented
Hey, @codediodeio! Can you please help me review this PR? @typescript-bot suggested me I should find someone to review it.

2023-05-15 16:16 UTC, jakebailey requested changes

2023-05-15 16:23 UTC, santi100a commented on types/git-init/index.d.ts
> +interface Signals {
It won't let me import `node:child_process`, and installing `@types/node` has no effect.

2023-05-15 16:29 UTC, santi100a commented on types/git-init/index.d.ts
> +interface Signals {
Stay tuned -- if everything goes well, I'll push a new commit in a few hours.

2023-05-15 19:03 UTC, jakebailey approved these changes

2023-05-15 19:04 UTC, santi100a commented
@typescript-bot Ready to merge! Go ahead, *MERGE IT*!

2023-05-15 19:06 UTC, merged

2023-05-15 19:12 UTC, santi100a commented
@jakebailey, how long till `@types/git-init` is published?

2023-05-15 19:24 UTC, jakebailey commented
Package publishes happen every half hour, so like 5 minutes

2023-05-15 19:27 UTC, santi100a commented
Okay! Thank you, @jakebailey!