Add Promise<void> return to tape TestCase
DefinitelyTyped/DefinitelyTyped pull request #65537
Opened 2023-05-19 02:04 UTC by r-thomson

This PR changes the signature of `TestCase` from `(Test) => void` to `(Test) => void | Promise<void>`. This is because [tape](https://github.com/ljharb/tape) has special handling for promise-returning/async test cases.

> If `cb` returns a Promise, it will be implicitly awaited. If that promise rejects, the test will be failed; if it fulfills, the test will end.

This shouldn't affect `tsc` since `() => Promise<void>` is assignable to `() => void`, but it will affect other tooling. Specifically, I was running into a situation where the `@typescript-eslint/no-misused-promises` rule in [typescript-eslint](https://typescript-eslint.io) was getting set off, because a `TestCase` isn’t supposed to return a promise. This change will properly communicate that async functions are expected in this context.

---

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/ljharb/tape#testname-opts-cb
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-05-19 02:11 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## tape ([<kbd>unpkg</kbd>](https://unpkg.com/browse/tape@latest/))
was missing the following properties:
1. Test
1. test
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 653201396d1cc068709ccc92959448e54974a0f3
</p>

2023-05-19 04:14 UTC, ljharb requested changes
This would need to change the version to v5.0.0, and ideally would also update the rest of the types to match - v4 did not support a Promise return.

2023-05-19 20:47 UTC, r-thomson commented
> This would need to change the version to v5.0.0, and ideally would also update the rest of the types to match - v4 did not support a Promise return.

Fair enough, I'll close this PR and open a different once updating to 5.0

2023-05-19 20:47 UTC, closed without merging

2023-05-20 03:30 UTC, ljharb commented
Seems like this could have been updated in place, but ok