expressjs_multer/support-for-unicode-headers
DefinitelyTyped/DefinitelyTyped pull request #65578
Opened 2023-05-23 23:09 UTC by Doc999tor

[ExpressJS Multer](https://github.com/expressjs/multer) `multer.Options` update for `defParamCharset` field
Supports unicode in requests headers such as `filename`

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <[PR](https://github.com/expressjs/multer/pull/1210/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R144)>

2023-05-24 19:31 UTC, peterblazejewicz commented
Is the https://github.com/expressjs/multer/pull/1210 PR a predecessor to this PR?

2023-05-24 20:08 UTC, Doc999tor commented
@peterblazejewicz - the opposite: https://github.com/expressjs/multer/pull/1210 relies on this PR for correct Typescript compiling

2023-05-25 19:48 UTC, peterblazejewicz commented
> @peterblazejewicz - the opposite: [expressjs/multer#1210](https://github.com/expressjs/multer/pull/1210) relies on this PR for correct Typescript compiling

oh, thanks! I believe that's not a path here. I believe no changes are published from DT repo, until backed by native JS code first (we want to avoid people using DT definition enforcing adding a code which does not exists at runtime). Why this opposite direction?
IMO once native JS module get's published this one should be merged as no-brainer.

2023-06-07 21:10 UTC, peterblazejewicz approved these changes, later dismissed
LGTM!

2023-06-12 18:19 UTC, sheetalkamat requested changes
Please mark this as draft or close it and reopen when the corresponding PR is merged. Thanks

2023-07-13 18:45 UTC, closed without merging

2026-02-28 08:19 UTC, alex-Arc commented
the corresponding PR in multer is now merged
can we reopen this?