[imap-simple] expose imap field type
DefinitelyTyped/DefinitelyTyped pull request #65592
Opened 2023-05-25 10:25 UTC by tennox

imap-simple allows to access the underlying `node-imap` instance, but the types were not including it.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [<<url here>>](https://github.com/chadxz/imap-simple/blob/master/README.md?plain=1#L258)
- [ ] ~~If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.~~

2023-05-25 22:36 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## imap-simple ([<kbd>unpkg</kbd>](https://unpkg.com/browse/imap-simple@latest/))
was missing the following properties:
1. parseHeader
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d61508bb9fc627da4469b3da32648f66c2ea3eae
</p>

2023-06-13 17:22 UTC, sheetalkamat requested changes
From the documentation it looks like that the imap is not meant to be API.
I am not sure if this is correct change and hence would like  @pushplay @iaarnio  to weigh in before this can be considered.

2023-06-13 18:02 UTC, tennox commented
> From the documentation it looks like that the imap is not meant to be API.

Well it's used in the [readme examples](https://github.com/chadxz/imap-simple/blob/master/README.md?plain=1#L258).
It's not well-documented, but it's the only way to do some stuff, as not all functions of node-imap are wrapped/implemented.
Also, imap-simple is archived and no longer maintained, nor possible to do PRs, so it's basically the only way to still use it in some cases.

I get your concern but I think it'll improve the situation to merge this.

2023-06-13 18:51 UTC, sheetalkamat approved these changes

2023-06-13 22:06 UTC, tennox commented
Ready to merge

Thank you @sheetalkamat :)

2023-06-13 22:07 UTC, merged

2023-06-13 22:08 UTC, tennox commented
Ready to merge