[node:test] Update types
DefinitelyTyped/DefinitelyTyped pull request #65871
Opened 2023-06-25 20:37 UTC by shockerqt

* `test`, `describe` and `it` return `Promise<void>`
* The callback for the 3 functions can by sync or async
* `describe` callback takes `SuiteContext` as its only argument
* Added `SuiteContext` class definition

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<[url here](https://nodejs.org/api/test.html)>>

2023-06-25 23:39 UTC, SimonSchick requested changes
Some of those type changes appear to be incorrect based on local testing, please test individual variants before continuing.

2023-06-25 23:39 UTC, SimonSchick commented on types/node/test.d.ts
> +        function skip(name?: string, options?: TestOptions, fn?: SuiteFn): Promise<void>;
This seems to return undefined.

2023-06-25 23:39 UTC, SimonSchick commented on types/node/test.d.ts
> +        function todo(name?: string, options?: TestOptions, fn?: SuiteFn): Promise<void>;
Same.

2023-06-25 23:39 UTC, SimonSchick commented on types/node/test.d.ts
> +        function only(name?: string, options?: TestOptions, fn?: SuiteFn): Promise<void>;
Same.

2023-06-26 02:04 UTC, shockerqt commented
> Some of those type changes appear to be incorrect based on local testing, please test individual variants before continuing.

Right! I was expecting `test({ todo: true })` and `todo()` to return the same, since the first returns `Promise<void>`.

2023-06-26 03:28 UTC, Semigradsky commented
> > Some of those type changes appear to be incorrect based on local testing, please test individual variants before continuing.
> 
> Right! I was expecting `test({ todo: true })` and `todo()` to return the same, since the first returns `Promise<void>`.

I expect the same, it can be a bug in Node.js, would be nice to open an issue in https://github.com/nodejs/node

2023-06-28 20:25 UTC, RyanCavanaugh commented
What's the status here? The .d.ts and node were both wrong, or the .d.ts was right and node was wrong?

2023-06-29 03:24 UTC, shockerqt commented
> What's the status here? The .d.ts and node were both wrong, or the .d.ts was right and node was wrong?

Both are wrong, the [last commit I pushed ](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65871/commits/091577c9e988daefad2f328d32f267cfa2a32a8b )should be the correct .d.ts in the current node version.
And if [this PR](https://github.com/nodejs/node/pull/48555) is accepted [my second commit](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65871/commits/446d9a88c335dd93286b5e6a6183a1e1d379511d) should be the correct.

I think we should fix the types for the current state of node for now

2023-07-05 16:49 UTC, Semigradsky commented
@shockerqt return type was fixed in v20.4.0. How about to update version in `index.ts` and merge this?

2023-07-07 02:21 UTC, shockerqt commented
I removed the last commit

2023-07-07 07:34 UTC, Semigradsky approved these changes

2023-07-07 20:52 UTC, peterblazejewicz approved these changes
LGTM!
@shockerqt thanks!

2023-07-07 22:34 UTC, shockerqt commented
Ready to merge

2023-07-07 22:35 UTC, merged