Model instantiable Marked versions
DefinitelyTyped/DefinitelyTyped pull request #65891
Opened 2023-06-28 04:56 UTC by timcharper

In order to allow users of the library to avoid mutating global state, the library allows you to instantiate a new Marked instance and mofiy its options directly.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://marked.js.org/using_advanced
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-06-28 05:02 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## marked ([<kbd>unpkg</kbd>](https://unpkg.com/browse/marked@latest/))
was missing the following properties:
1. defaults
1. Hooks
1. getDefaults
1. lexer
1. options

<details>
<summary>as well as these 6 other properties...</summary>
<p>parse, parseInline, parser, setOptions, use, walkTokens</p>
</details>

<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7b46bb9ec0ba8710ecd1e6fc383bc7afc1794d4f
</p>

2023-06-29 16:29 UTC, UziTech commented
The marked instance allows options and extensions to be passed in.

```
const markedInstance = new Marked(options);
```

Can you add a test for this?

2023-07-09 15:10 UTC, UziTech requested changes
Needs test for options sent to constructor

2023-07-14 02:25 UTC, baseplate-admin commented
Hi @uzitech, If i add the tests ( in a new pr ) would you be willing to give it a review?

2023-07-14 02:49 UTC, baseplate-admin commented
@UziTech  does [`ce113a6c8a926b548521d9df843de59f4af58ccd`](https://github.com/baseplate-admin/DefinitelyTyped/commit/ce113a6c8a926b548521d9df843de59f4af58ccd) satisfy your requirement?

2023-07-14 03:37 UTC, baseplate-admin commented
@UziTech ,

Given your like on https://github.com/baseplate-admin/DefinitelyTyped/commit/ce113a6c8a926b548521d9df843de59f4af58ccd#r121572927 i am assuming that the repo contains the necessary codes for an eligible PR ?

2023-07-14 05:17 UTC, UziTech commented
@baseplate-admin ya if you create another PR I could review it.

2023-07-14 08:07 UTC, baseplate-admin commented
@uzitech. new pr at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66063

2023-07-14 15:30 UTC, baseplate-admin commented
Superseded by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66063

2023-07-28 15:50 UTC, closed without merging

2023-07-28 15:51 UTC, timcharper commented
thanks for addressing the PR, @UziTech ! closed this one since yours was merged.