@types/ssh2 fix wrong type for exit event
DefinitelyTyped/DefinitelyTyped pull request #65926
Opened 2023-06-29 11:13 UTC by ChiChou

the argument type should be number instead of string

Reference: https://github.com/mscdex/ssh2/blob/7410a11c282fd0f21e8e989906c699c84ca711ed/README.md?plain=1#L362

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-06-29 11:29 UTC, dhensby requested changes
https://github.com/mscdex/ssh2/blob/v1.14.0/lib/client.js#L673-L680

I'm not sure this is right. The docs you've linked to may well be wrong and/or a `number` might be accepted, but I'm not sure it's actually how it's used internally...

2023-06-29 11:42 UTC, ChiChou commented
> https://github.com/mscdex/ssh2/blob/v1.14.0/lib/client.js#L673-L680
> 
> I'm not sure this is right. The docs you've linked to may well be wrong and/or a `number` might be accepted, but I'm not sure it's actually how it's used internally...

The way I found this wrong was not the documentation, but to dynamically `typeof` that parameter. I will review deeper and write a minimized test case to reproduce this

2023-06-29 11:45 UTC, ChiChou commented
I just confirmed in their test case. It's a number

https://github.com/mscdex/ssh2/blob/7410a11c282fd0f21e8e989906c699c84ca711ed/test/test-exec.js#L45

2023-06-29 12:18 UTC, dhensby approved these changes

2023-07-11 15:15 UTC, andrewbranch approved these changes

2023-07-11 16:25 UTC, merged