katex: fix default export
DefinitelyTyped/DefinitelyTyped pull request #65980
Opened 2023-07-05 09:32 UTC by not-my-profile

The default export isn't a class and never was. This was just an error in the type definition file here. The following leads to runtime errors:

    import katex from 'katex';
    new katex; // or
    class Foo extends katex {}

2023-07-05 09:38 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## katex ([<kbd>unpkg</kbd>](https://unpkg.com/browse/katex@latest/))
was missing the following properties:
1. katex
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7d1e122c8e5613c7d09f5283d59491b199037b95
</p>

2023-07-07 11:04 UTC, sapphi-red approved these changes

2023-07-11 15:20 UTC, andrewbranch requested changes

2023-07-11 15:20 UTC, andrewbranch commented on types/katex/index.d.ts
> +export default _default;
The rename from `katex` to `_default` will affect auto-imports in TS Server. Conventional usage seems to be importing as `katex`, so the local name of the symbol should remain that way.

2023-07-12 14:31 UTC, andrewbranch approved these changes

2023-07-12 14:41 UTC, merged