koa: Fix vary field parameter
DefinitelyTyped/DefinitelyTyped pull request #66033
Opened 2023-07-11 11:12 UTC by hustLer2k

Vary can accept either a single string or an array of strings, as per vary's [docs](https://github.com/jshttp/vary#varyres-field) and [types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1b85e933696518a58ca05d48c31065e0d20430ca/types/vary/index.d.ts#L10)

Please fill in this template.

- ✔️ Use a meaningful title for the pull request. Include the name of the package modified.
- ✔️ Test the change in your own code. (Compile and run.)
- ✔️ [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- ✔️ Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- ✔️ Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- ✔️ [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:
If changing an existing definition:
- ✔️ Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1b85e933696518a58ca05d48c31065e0d20430ca/types/vary/index.d.ts#L10
- ✔️ If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-07-23 20:33 UTC, pkuczynski requested changes

2023-07-23 20:33 UTC, pkuczynski commented on types/koa/index.d.ts
> +    ContextT = Application.DefaultContext,
Such changes are irrelevant to the subject of this PR and should be reverted

2023-07-23 20:33 UTC, pkuczynski commented on types/koa/index.d.ts
> -    vary(field: string): void;
This change seems valid: https://github.com/jshttp/vary/blob/5d725d059b3871025cf753e9dfa08924d0bcfa8f/index.js#L129

2023-07-23 20:33 UTC, pkuczynski commented on types/koa/test/index.ts
> +    ctx.vary("Origin");
You should add `// $ExpectType`

2023-07-28 15:46 UTC, hustLer2k commented
@pkuczynski

2023-07-28 20:35 UTC, pkuczynski approved these changes

2023-07-29 15:00 UTC, peterblazejewicz approved these changes
@hustLer2k thanks!

2023-07-29 16:56 UTC, hustLer2k commented
ready to merge boss

2023-07-29 16:56 UTC, merged