Update SyntheticsConfiguration with visual monitoring options
DefinitelyTyped/DefinitelyTyped pull request #66090
Opened 2023-07-18 04:47 UTC by gwander

Please fill in this template.

Update SyntheticsConfiguration with visual monitoring options. Source: `Visual monitoring` @ https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Synthetics_Canaries_Library_Nodejs.html#CloudWatch_Synthetics_Library_SyntheticsConfiguration

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2023-07-18 05:37 UTC, Tantalon requested changes
Please can you add the parameter types:
```
withVisualCompareWithBaseRun(visualCompareWithBaseRun: boolean): SyntheticsConfiguration;
withVisualVarianceThresholdPercentage(visualVarianceThresholdPercentage: number): SyntheticsConfiguration;
withVisualVarianceHighlightHexColor(visualVarianceHighlightHexColor: string): SyntheticsConfiguration;
withFailCanaryRunOnVisualVariance(failCanaryRunOnVisualVariance: boolean): SyntheticsConfiguration;
```
and the getters:
```
getVisualCompareWithBaseRun(): boolean;
getVisualVarianceThresholdPercentage(): number;
getVisualVarianceHighlightHexColor(): string;
getFailCanaryRunOnVisualVariance(): boolean;
```

2023-07-18 22:32 UTC, gwander commented
@Tantalon Thanks for reviewing my PR. updated it with your comments

2023-07-18 22:53 UTC, Tantalon approved these changes
LGTM

2023-07-19 05:48 UTC, gwander commented
This PR needs a maintainer approve. @peterblazejewicz will you mind taking a look? Thanks!

2023-07-19 16:34 UTC, peterblazejewicz approved these changes
LGTM!
owner reviewed
@gwander thanks!

2023-07-19 19:49 UTC, Tantalon commented
Ready to merge

2023-07-19 19:50 UTC, merged