Undeprecate Global React JSX Namespace
DefinitelyTyped/DefinitelyTyped pull request #66171
Opened 2023-07-25 16:13 UTC by NickGerleman

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64464 (landed in semver patch release `@types/react@18.2.6`) scopes the JSX namespace as `React.JSX` to avoid collisions with multiple libraries working in the JSX namespace.

This change also deprecated the existing JSX namespace, so existing usages of `JSX.Element`, etc are flagged in-editor.

<img width="686" alt="Screenshot 2023-07-25 at 14 11 59" src="https://github.com/facebook/react-native/assets/4661784/531a4f88-8090-43aa-86d6-4af595d4cb5d"> 

This has a pretty drastic effect of making every previous non-anonymous function component, with an explicit return type, now fire deprecation warnings. E.g. this patch update now makes the out-of-the-box React native template create deprecation warnings. https://github.com/facebook/react-native/pull/38615

In DefinitelyTyped itself, the hundreds of packages using `JSX.Element` outside of the direct React typings were not updated. TypeScript's [own documentation](https://www.typescriptlang.org/docs/handbook/jsx.html) also still suggests using `JSX.Element`. This is echoed by a platitude of existing documentation, and googling for `React.JSX.Element` will just bring up information about `JSX.Element`.

Due to the widespread nature of the breakage here (especially in a patch release), and disconnect with existing code, documentation, and resources, this change removes the `@deprecated` annotation. I think there might still be a possible path to discouraging usage, but there needs to be a lot of legwork to get there in a way which isn't disruptive.

2023-07-26 17:15 UTC, eps1lon requested changes
So is the suggestion to first edit all callsites and then deprecate? What would be the rationale for that change be? Could you clarify why this deprecation should be reverted other than "existing code relies on deprecated code" since that's inherent to all deprecations from my experience. You don't need to deprecate code that's no longer used. You could directly remove it.

> TypeScript's [own documentation](https://www.typescriptlang.org/docs/handbook/jsx.html) also still suggests using JSX.Element

We could edit that instead of reverting the deprecation.

2023-07-26 17:16 UTC, eps1lon commented
Also keep in mind that types packages major and minors follow the runtime package. We cannot release types-only features/breaking changes.

2023-07-28 14:49 UTC, NickGerleman commented
> Could you clarify why this deprecation should be reverted other than "existing code relies on deprecated code" since that's inherent to all deprecations from my experience. 

A strategy we have followed in RN, and I have often seen, is to add a gap between adding the new API, and deprecating the old one, to give opportunity to start adoption in major libraries, etc, without yet creating warnings for every user.  In examples like this, where we also have some ownership of React experience in DT, I think the onus is on us, making the breaking change, to do some of the legwork in the fixes. At least where it is convenient to, like within DT.

> > TypeScript's [own documentation](https://www.typescriptlang.org/docs/handbook/jsx.html) also still suggests using JSX.Element
> 
> We could edit that instead of reverting the deprecation.

I do think this would be okay, if we go and start updating documentation and the other code in DT. The pattern that I think we should try to avoid, is to deprecate first, before we have updated material telling folks to use the old version.

> Also keep in mind that types packages major and minors follow the runtime package. We cannot release types-only features/breaking changes.

I do recognize this complicates things. A strategy here might be to wait on making large breaking changes until React itself does a bump. FWIW, expected times for breaking types changes is one of the things we end up gaining from bundling types in RN since it follows the normal branching process.

2023-07-31 06:51 UTC, eps1lon commented
> I do recognize this complicates things. A strategy here might be to wait on making large breaking changes until React itself does a bump.

We don't do breaking changes in patches to the types APIs. We have https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64451 for that

2023-07-31 17:18 UTC, NickGerleman commented
While it doesn't cause a typechecking error, I would count adding major new deprecation warnings in the list of things that would be nice to avoid in a patch release. In effect, a lot of code that was previously valid now produces warnings. Not because it was previously incorrect, but because we wanted to change the API of the types.

This particular example is fairly extreme, due to how used the APIs were previously.

2023-07-31 17:48 UTC, NickGerleman commented
One other issue, any library which must allow compatibility with versions of the typings before `@types/react@18.2.6` must use the old form, and create deprecation warnings in user code. So libraries which want to allow usage with non-latest typings must use the now deprecated types.

2023-08-31 18:49 UTC, closed without merging