[node-forge] more details about encryption in PKCS#7 EnvelopedData
DefinitelyTyped/DefinitelyTyped pull request #66400
Opened 2023-08-17 11:12 UTC by akapps

**Encryption:** a key and (more importantly) the symmetric cipher can be specified when calling "encrypt()".

**Decryption:** the correct recipient should be retrieved based on the certificate, then content can be decrypted with the private key.

_Documentation copied from 'node-forge'._

---

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes:
  - encryption: `envelopedData.encrypt` accepting key and cipher defined [here](https://github.com/digitalbazaar/forge/blob/2bb97afb5058285ef09bcf1d04d6bd6b87cffd58/lib/pkcs7.js#L727)
  - decryption: envelopedData contains recipients ([here](https://github.com/digitalbazaar/forge/blob/2bb97afb5058285ef09bcf1d04d6bd6b87cffd58/lib/pkcs7.js#L591)), and they are created with said properties [here](https://github.com/digitalbazaar/forge/blob/2bb97afb5058285ef09bcf1d04d6bd6b87cffd58/lib/pkcs7.js#L834)
  - `envelopedData.findRecipient` is defined [here](https://github.com/digitalbazaar/forge/blob/2bb97afb5058285ef09bcf1d04d6bd6b87cffd58/lib/pkcs7.js#L637), and `envelopedData.decrypt` is [here](https://github.com/digitalbazaar/forge/blob/2bb97afb5058285ef09bcf1d04d6bd6b87cffd58/lib/pkcs7.js#L675)

2023-09-04 14:31 UTC, joeflateau requested changes
please add a test where the key is provided to the encrypt method and confirm that util.ByteBuffer is the correct type for that parameter

2023-09-08 12:40 UTC, akapps commented
Thank you @joeflateau for your review.
This is how I inferred the expected type of the `key` argument (util.ByteBuffer):

1. In the source code of the encrypt method, if the key has not been provided as an argument, it is created using `forge.util.createBuffer()` - which returns an instance `util.ByteBuffer`.
   https://github.com/digitalbazaar/forge/blob/2bb97afb5058285ef09bcf1d04d6bd6b87cffd58/lib/pkcs7.js#L763C1-L765C44

2. This is compatible with the accessed properties / methods on the `key` object (or `msg.encryptedContent.key`, the variable it has been affected to) - both are declared members of util.ByteBuffer:
   - `key.length()` [l.765](https://github.com/digitalbazaar/forge/blob/2bb97afb5058285ef09bcf1d04d6bd6b87cffd58/lib/pkcs7.js#L765)
   - `key.data` [l.803](https://github.com/digitalbazaar/forge/blob/2bb97afb5058285ef09bcf1d04d6bd6b87cffd58/lib/pkcs7.js#L803)

2023-09-08 12:47 UTC, joeflateau approved these changes
lgtm, thank you

2023-09-08 12:53 UTC, akapps commented
Ready to merge

2023-09-08 12:53 UTC, merged