add `function.prototype.name`
DefinitelyTyped/DefinitelyTyped pull request #66734
Opened 2023-09-18 06:01 UTC by ljharb

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2023-09-21 18:28 UTC, sheetalkamat requested changes

2023-09-21 18:40 UTC, ljharb commented on types/function.prototype.name/implementation.d.ts
> +export = name;
They are not implementation details; they're all explicit entry points that I use in dozens of packages, and are present in `exports`.

2023-09-21 21:53 UTC, ljharb commented on types/function.prototype.name/implementation.d.ts
> +export = name;
Rebased and repushed so the bot will do a proper rereview ping.

Do note that I have a hundred packages with this structure; some already are on DT; all of those have this DT file format already - so this is already an approved and accepted approach.

2023-09-22 18:35 UTC, sheetalkamat requested changes

2023-09-22 18:35 UTC, sheetalkamat commented on types/function.prototype.name/implementation.d.ts
> +export = name;
https://github.com/es-shims/Function.prototype.name#example here talks about importing `function.prototype.name` so i dont understand why others are explicit entry points. It seems like these definitions could be simplified into index.d.ts

2023-09-22 18:48 UTC, ljharb commented on types/function.prototype.name/implementation.d.ts
> +export = name;
That's not how my entire ecosystem of shims works. The *example* only talks about that, but *all* of my shims have the same 4 entry points.

It feels like you're arguing about the design of my library, and not about the quality of the types. This is how my library is designed, this is how the types need to be for consumers to use it correctly. I'm not sure why this is up for debate?

2023-09-23 21:54 UTC, ljharb commented on types/function.prototype.name/implementation.d.ts
> +export = name;
Here's a few existing PRs where this exact (proper) pattern was followed:
 - #53498
 - #52716
 - #44406

2023-09-25 10:45 UTC, ljharb commented on types/function.prototype.name/implementation.d.ts
> +export = name;
Rebased this again to make sure it shows up in the right queue.

2023-09-26 19:58 UTC, RyanCavanaugh approved these changes

2023-09-26 23:22 UTC, ljharb commented
Ready to merge

2023-09-26 23:22 UTC, merged