remove: styled-components
DefinitelyTyped/DefinitelyTyped pull request #66997
Opened 2023-10-09 22:23 UTC by falsepopsky

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If removing a declaration:
- [x] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [x] Delete the package's directory.
- [x] Add it to `notNeededPackages.json`.

# Summary:

With version [6.0.0](https://github.com/styled-components/styled-components/releases/tag/v6.0.0) `styled-components` now includes its own types.

> styled-components now provides its own types; if you installed @types/styled-components in the past, you'll want to remove it

2023-10-09 22:52 UTC, falsepopsky commented
Just by examining the errors in the CI, I discovered that even `xstyled` ships its own [types](https://github.com/styled-components/xstyled/releases/tag/v2.0.0). I believe those should also be removed.

2023-10-10 05:13 UTC, jakebailey commented
This package is so critical that we probably want to just delete it and avoid the shim; the shim will specify the upstream package at `*` which may break consumers.

2023-10-13 20:43 UTC, falsepopsky commented
@jakebailey 

Should I remove `styled-components` from `notNeededPackages.json`? And for the other failing tests, should I add `@types/styled-components` as a dependency? A similar solution was applied to other types [link](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63097) but i need first to make a pr in `DefinitelyTyped-tools`, sorry for the ping 🙏

2023-10-13 22:58 UTC, jakebailey commented on notNeededPackages.json
> +            "libraryName": "styled-components/native",
I don't think this is the name of the library. This should be an npm package name.

2023-10-13 22:59 UTC, jakebailey commented
I am thinking that you shouldn't put it into `notNeededPackages`, yes. @sandersn @andrewbranch may have further opinions here.

The other packages need to be fixed up so tests pass. Generally, you'd need to check each of them upstream and see which version of styled-components they depend on and if they should now point upstream or should point to an old types package.

2023-10-19 02:10 UTC, jakebailey commented on notNeededPackages.json
> +            "libraryName": "styled-components",
This mismatch is weird; maybe leave this file as-is? `styled-components-react-native` is a fake package anyhow.

2023-10-19 15:43 UTC, jakebailey commented on notNeededPackages.json
> +        "styled-components-react-native": {
This package is fake and this version doesn't exist; I think we could just not change this file.

2023-10-19 16:07 UTC, sandersn requested changes
I think this is a good idea, although styled-components is so widely used that it might be a good idea to keep it around in case the pre-6.0 types need to be fixed.

I looked at the past history and it looks like it's had around 10 fixes in the last 2 years. v3 even had a fix at the end of 2021. To me, that says the best course of action is keeping the types, with a warning not to update them past 5.2. At least for another year or two to make sure no further fixes are needed.

2023-11-19 18:47 UTC, closed without merging