[types/parse] Document Parse.Query.readPreference
DefinitelyTyped/DefinitelyTyped pull request #67011
Opened 2023-10-10 22:33 UTC by mdarens

See https://parseplatform.org/Parse-SDK-JS/api/3.2.0/Parse.Query.html#readPreference

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-10-11 16:02 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/parse/index.d.ts
Consider running `npx dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 7db34566eb886906a3352a64d59f4d2a5edc242e
</p>

2023-10-11 17:34 UTC, mdarens commented
Ready to merge

2023-10-14 15:05 UTC, MysteryBlokHed commented on types/parse/index.d.ts
> +        }
Does this enum actually exist in the code (i.e. is there an object called `ReadPreferenceOption` somewhere)?

2023-10-30 21:36 UTC, sheetalkamat requested changes

2023-10-30 21:36 UTC, sheetalkamat commented on types/parse/index.d.ts
> +        enum ReadPreferenceOption {
cannot be enum unless there exists the object with this name in the package to be used.

2023-10-30 21:38 UTC, sheetalkamat commented on types/parse/index.d.ts
> +        enum ReadPreferenceOption {
Also documentation you pointed shows function parameters of type string and not special string types so this change looks incorrect

2023-12-01 01:10 UTC, closed without merging