Feat: add types for `passport-42` module.
DefinitelyTyped/DefinitelyTyped pull request #67088
Opened 2023-10-17 21:32 UTC by awbx

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2023-10-17 21:56 UTC, jakebailey commented on types/passport-42/index.d.ts
> +// Type definitions for passport-42 1.2
The format of the repo has changed; you will want to update this package to reflect the new layout. dts-gen 0.7.1 has this fixed already.

2023-10-17 22:14 UTC, jakebailey commented
@typescript-bot are you working?

2023-10-17 22:21 UTC, awbx commented
yes m working on it

2023-10-17 22:42 UTC, awbx commented
"I have included the `package.json` file, yet I am still encountering the following errors
<img width="1327" alt="Screenshot 2023-10-17 at 11 40 59 PM" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/33328081/4f4fbf28-a121-4abf-a57f-a815c52a5274">

2023-10-17 22:43 UTC, jakebailey commented
You can delete those from you package; you may want to look at some of the other packages for an example. Sorry that your PR raced with such a big refactor.

2023-10-17 23:08 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  2 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## passport-42 ([<kbd>unpkg</kbd>](https://unpkg.com/browse/passport-42@latest/))
was missing the following properties:
1. The declaration doesn't match the JavaScript module 'passport-42'. Reason:
The JavaScript module can be called or constructed, but the declaration module cannot.

The most common way to resolve this error is to use 'export =' syntax.
To learn more about 'export =' syntax, see https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require.

## Formatting

The following files are not formatted:
1. types/passport-42/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c5129f713e12c3d6f2bc102e3e52f3bc1335b24e
</p>

2023-10-17 23:37 UTC, awbx commented
@DangerBotOSS Thanks for your advice! I've implemented the 'export =' syntax in the TypeScript declaration file, and the issue has been resolved. Appreciate your help!

2023-10-18 17:04 UTC, sandersn requested changes

2023-10-20 05:38 UTC, awbx commented on types/passport-42/index.d.ts
> +    userProfile(accessToken: string, done: (err: any, profile?: Profile) => void): void;
"I forgot to change the access to public for 'userProfile' because it is a public method inside the 'Strategy'

2023-10-20 21:40 UTC, sandersn approved these changes

2023-10-20 21:40 UTC, sandersn commented on types/passport-42/index.d.ts
> +    userProfile(accessToken: string, done: (err: any, profile?: Profile) => void): void;
Technically you should rely on Typescript `public` for this but I think it's OK if you want to merge as-is.

2023-10-20 23:25 UTC, awbx commented
Ready to merge

2023-10-21 00:59 UTC, merged