feat: add @chamaeleonidae  chmln types
DefinitelyTyped/DefinitelyTyped pull request #67246
Opened 2023-10-30 10:04 UTC by borajimin

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2023-10-30 12:28 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/chamaeleonidae__chmln/index.d.ts
1. types/chamaeleonidae__chmln/chamaeleonidae__chmln-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against a2968cbd731c4a25ce112ebcda9b228bc7db8d25
</p>

2023-11-01 09:33 UTC, borajimin commented on types/chamaeleonidae__chmln/index.d.ts
> +    };
When I tried sending a random field in the CompanyOptions, the property wasn't available on the user info view. So, I'm assuming the rules are more strict for CompanyOptions.

2023-11-06 22:00 UTC, jakebailey requested changes
After #67332, this PR will need to be updated to include an `.npmignore`. See https://github.com/DefinitelyTyped/DefinitelyTyped#npmignore

2023-12-20 18:01 UTC, jakebailey commented on types/chamaeleonidae__chmln/index.d.ts
> +/* eslint-disable @definitelytyped/no-single-declare-module */
Why have you disabled these rules? This could all be at the top level.

2024-02-12 13:37 UTC, borajimin commented
Closing since the chameleon team added their own.

2024-02-12 13:37 UTC, closed without merging