[bootstrap] Fix popper config types
DefinitelyTyped/DefinitelyTyped pull request #67334
Opened 2023-11-07 01:43 UTC by kyletsang

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://getbootstrap.com/docs/5.3/components/dropdowns/#using-function-with-popperconfig
https://getbootstrap.com/docs/5.3/components/popovers/#using-function-with-popperconfig
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-11-07 05:18 UTC, martin-badin commented
Looks good but please update tests.

2023-11-07 05:27 UTC, martin-badin requested changes

2023-11-07 05:27 UTC, martin-badin commented on types/bootstrap/js/dist/popover.d.ts
>      interface Options extends Omit<Tooltip.Options, "popperConfig"> {
please remove `Omit`
```suggestion
    interface Options extends Tooltip.Options {
```
and remove `popperConfig` and `PopperConfigFunction` from this file

2023-11-07 05:27 UTC, martin-badin commented on types/bootstrap/js/dist/dropdown.d.ts
>      interface Options {
Here please use 
```suggestion
    interface Options extends Pick<Tooltip.Options, "popperConfig">
```

and remove `popperConfig` and `PopperConfigFunction` from this file

2023-11-07 05:54 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/bootstrap/test/dropdown-tests.ts
1. types/bootstrap/test/popover-tests.ts
1. types/bootstrap/test/tooltip-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 134df016dc37ee9f8225fad224893c74dfe347db
</p>

2023-11-07 06:05 UTC, kyletsang commented
Thanks for the review @martin-badin.  I've added the requested changes.

2023-11-07 07:58 UTC, martin-badin approved these changes
Looks good. Thanks

2023-11-07 08:01 UTC, luc122c commented
Ready to merge

2023-11-07 08:02 UTC, merged

2023-11-08 22:01 UTC, peterblazejewicz commented on types/bootstrap/js/dist/dropdown.d.ts
> +import Tooltip from "./tooltip";
how this can depends on tooltip module? I assume one could extract common type out of tooltip for reuse