Feature/update types
DefinitelyTyped/DefinitelyTyped pull request #67340
Opened 2023-11-07 16:21 UTC by agachuma

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `npm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://docs.gorilla-engine.com/Gorilla_Engine_JavaScript_API_Reference>>

2023-11-07 19:31 UTC, MysteryBlokHed requested changes

2023-11-07 19:31 UTC, MysteryBlokHed commented on types/gorilla-engine/index.d.ts
> +    }): Promise<any>;
I can’t seem to find this function in the documentation, but if it’s an async function with no return then the proper type is `Promise<void>`:

```suggestion
    }): Promise<void>;
```

If there’s a specific type that this returns (i.e. `number`), then that should be used:

```suggestion
    }): Promise<number>;
```

2023-11-07 19:31 UTC, MysteryBlokHed commented on types/gorilla-engine/index.d.ts
> +    }): Promise<any>;
It looks to me like this function returns an array: <https://docs.gorilla-engine.com/Gorilla_Engine_JavaScript_API_Reference/Core%20Classes.html#gorillaengineopenfilechooseroptions--promiseltarrayltstringgtgt>

```suggestion
    }): Promise<string[]>;
```

2023-11-09 10:43 UTC, UJAM-JH approved these changes

2023-11-09 10:51 UTC, agachuma commented
ready to merge

2023-11-09 10:51 UTC, merged