react - Add phase "nested-update" to ProfilerOnRenderCallback type
DefinitelyTyped/DefinitelyTyped pull request #67369
Opened 2023-11-10 14:04 UTC by fredrikcarlbom

The phase "nested-update" was added in react 18.0.0, [PR#20163](https://github.com/facebook/react/pull/20163) 

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [Pull Request](https://github.com/facebook/react/pull/20163), [Documentation](https://react.dev/reference/react/Profiler#onrender-callback)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-11-10 14:18 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react@latest/))
was missing the following properties:
1. unstable_act
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ab6869a646accb8708edc0c1ed5a8e0ea3a80f77
</p>

2023-11-24 22:26 UTC, gabritto requested changes
I think you need to make the same changes in `types/react/ts5.0/index.d.ts`.
Otherwise, looks good to me.

2023-11-27 17:29 UTC, eps1lon approved these changes
Thanks!

2023-11-27 17:46 UTC, gabritto approved these changes

2023-11-27 19:14 UTC, fredrikcarlbom commented
Ready to merge

2023-11-27 19:15 UTC, merged