react-native-charts-wrapper: Change Axis font weight from number to string
DefinitelyTyped/DefinitelyTyped pull request #67388
Opened 2023-11-13 09:53 UTC by fwielstra

I got a PropTypes warning from react-native-charts-wrapper setting the font weight to a numeric value as the type indicated. The matching proptype says it should be a string.

Note that there's another definition for the Legend component in react-native-charts-wrapper that says fontWeight should be a number instead. It's not a very good library.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/wuxudong/react-native-charts-wrapper/blob/master/lib/AxisIface.js#L15
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

2023-11-15 22:09 UTC, RyanCavanaugh requested changes
Please add a test

2023-11-21 08:54 UTC, fwielstra commented
> Please add a test

Done (by amending the commit); I should expand the existing test to cover all properties, but that's out of scope for this PR.

2023-12-04 20:29 UTC, navya9singh approved these changes

2023-12-05 14:44 UTC, fwielstra commented
Ready to merge

2023-12-05 14:44 UTC, merged