feat(sinon): make .define generic
DefinitelyTyped/DefinitelyTyped pull request #67433
Opened 2023-11-16 13:40 UTC by gukoff

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66888#discussion_r1395649214

2023-11-16 13:53 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/sinon/sinon-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3b21c027d42200e1ca0fd9a751b0dfac455baa29
</p>

2023-11-16 16:35 UTC, 43081j commented
basically it was purposely non-generic because there were use cases for defining keys on an object which otherwise doesn't have those in its type

im surprised your editor gives completions as you'd expect, since i would expect `keyof T | PropertyKey` to just narrow to `PropertyKey` (since all keys of `T` are `PropertyKey`s themselves)

but if it works, it works! good catch

2023-11-17 20:34 UTC, gukoff commented
It is, indeed, just `PropertyKey` - see the `key` type in the schema down below on the screenshot:

<img width="818" alt="image" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/5655837/f2d5c229-ac5e-4c66-b7e9-30ddcf8e6cd1">

And yes, it does work - WebStorm correctly jumps to source when the type declaration includes `keyof`. Apparently, it has its own heuristics.

2023-11-19 16:13 UTC, 43081j approved these changes

2023-11-24 22:20 UTC, gabritto reviewed
Is the only goal here to improve auto-completion? Couldn't this change break users?
Also, the new definition won't help with auto-completions that rely on TSServer (e.g. in vscode).

2023-11-24 22:35 UTC, 43081j commented
not op, but afaict yes its for auto completion.

the type will just dumb down to `PropertyKey` anyway right? so this shouldn't change anything, or break anything. i guess it'll just make some editors provide better completions 🤷‍♂️

2023-11-25 00:10 UTC, gukoff commented
^ this is exactly my understanding

2023-11-28 18:13 UTC, andrewbranch requested changes

2023-11-28 18:13 UTC, andrewbranch commented on types/sinon/index.d.ts
> +        define<T>(
```suggestion
        define<T extends object = object>(
```

Can you add a test showing that `sb.define("notAnObject", "someKey", 100)` errors? The PR as it stands now removes that error.

2023-12-29 18:45 UTC, closed without merging