feat(node): dns.promises module add getDefaultResultOrder api
DefinitelyTyped/DefinitelyTyped pull request #67444
Opened 2023-11-19 04:53 UTC by btea

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://nodejs.org/dist/latest-v21.x/docs/api/dns.html#dnspromisesgetdefaultresultorder

2023-11-19 08:47 UTC, Semigradsky requested changes
Please add these changes to node/ts4.8 folder too

2023-11-19 17:55 UTC, Semigradsky approved these changes

2023-11-19 17:56 UTC, Semigradsky commented
Ah, I missed that in doc that was added to `v18.17.0` too.
Would be nice to add to `node/v18` and `node/v18/ts4.8`  folders too.

2023-11-20 00:18 UTC, btea commented
@Semigradsky Thanks for the reminder, I've updated it.

2023-11-20 09:14 UTC, Semigradsky commented on types/node/v18/dns/promises.d.ts
> +     * @since v20.1.0
Here should be `* @since v18.17.0`

2023-11-20 09:14 UTC, Semigradsky commented on types/node/v18/ts4.8/dns/promises.d.ts
> +     * @since v20.1.0
ditto

2023-11-20 09:52 UTC, btea commented on types/node/v18/dns/promises.d.ts
> +     * @since v20.1.0
Done.

2023-11-20 14:02 UTC, Semigradsky approved these changes

2023-11-20 20:46 UTC, peterblazejewicz approved these changes
@btea thanks!

2023-11-20 23:32 UTC, btea commented
Ready to merge

2023-11-20 23:33 UTC, merged