Add geo-goordinates-parser package
DefinitelyTyped/DefinitelyTyped pull request #67548
Opened 2023-11-29 11:48 UTC by j8seangel

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2023-11-29 11:50 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/geo-coordinates-parser/index.d.ts
1. types/geo-coordinates-parser/geo-coordinates-parser-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 1dd4cf1e37d29478acd4dd3baf9f00b6239c4ebb
</p>

2023-11-29 23:52 UTC, andrewbranch requested changes

2023-11-29 23:52 UTC, andrewbranch commented on types/geo-coordinates-parser/package.json
> +    "version": "1.6.9999",
```suggestion
    "version": "1.6.9999",
    "type": "module",
```

must match the implementation package: https://unpkg.com/browse/geo-coordinates-parser@1.6.3/package.json

2023-11-29 23:54 UTC, closed without merging

2023-11-30 15:14 UTC, j8seangel commented
> @j8seangel what's wrong with declaration files exported by the module build setup? https://unpkg.com/browse/geo-coordinates-parser@1.6.3/dist/cjs/ it looks like project does not have proper decoration file information in package json: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

Thanks @peterblazejewicz I haven't realized the types are already packed, so I opened a [PR](https://github.com/ianengelbrecht/geo-coordinates-parser/pull/12) to the library updating the types declaration file