@types/react-dom react-dom/server add ServerOptions
DefinitelyTyped/DefinitelyTyped pull request #67570
Opened 2023-12-01 07:42 UTC by 2239559319

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tslint.json` [should contain](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#linter-tslintjson) `{ "extends": "@definitelytyped/dtslint/dt.json" }`, and no additional rules.
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the header.

If removing a declaration:
- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2023-12-02 10:11 UTC, eps1lon approved these changes
We're actually missing these on the official docs. Will fix.

2023-12-02 10:25 UTC, eps1lon commented
It's not on react.dev. Can you link the PR?

2023-12-09 12:28 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-dom ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-dom@latest/))
was missing the following properties:
1. createRoot
1. hydrateRoot
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 156517629b05dea9d762a5d7719da1782e11e391
</p>

2023-12-09 12:38 UTC, eps1lon requested changes

2023-12-09 12:38 UTC, eps1lon commented on types/react-dom/server.d.ts
> +export function renderToStaticNodeStream(element: ReactElement, options?: ServerOptions): NodeJS.ReadableStream;
```suggestion
export function renderToStaticNodeStream(element: ReactElement): NodeJS.ReadableStream;
```
These are not hydrateable

2023-12-09 12:38 UTC, eps1lon commented on types/react-dom/server.d.ts
> +export function renderToStaticMarkup(element: ReactElement, options?: ServerOptions): string;
```suggestion
export function renderToStaticMarkup(element: ReactElement): string;
```
not hydrateable

2023-12-09 12:38 UTC, eps1lon commented on types/react-dom/test/react-dom-tests.tsx
> +        ReactDOMServer.renderToStaticMarkup(React.createElement("div"), { identifierPrefix: "react-18-app" });
```suggestion
        // @ts-expect-error -- not hydrateable
        ReactDOMServer.renderToStaticMarkup(React.createElement("div"), { identifierPrefix: "react-18-app" });
```

2023-12-09 12:50 UTC, eps1lon approved these changes

2023-12-09 12:51 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-dom ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-dom@latest/))
was missing the following properties:
1. createRoot
1. hydrateRoot
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 156517629b05dea9d762a5d7719da1782e11e391
</p>

2023-12-09 12:51 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## react-dom ([<kbd>unpkg</kbd>](https://unpkg.com/browse/react-dom@latest/))
was missing the following properties:
1. createRoot
1. hydrateRoot
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 156517629b05dea9d762a5d7719da1782e11e391
</p>

2023-12-15 19:15 UTC, rbuckton approved these changes

2023-12-15 23:09 UTC, eps1lon commented
Ready to merge

2023-12-15 23:10 UTC, merged