[react-date-range] Replace usage of React's global JSX namespace with scoped JSX
DefinitelyTyped/DefinitelyTyped pull request #67646
Opened 2023-12-03 16:51 UTC by eps1lon

Was deprecated in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64464. Cherry-picked from https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67588.

2023-12-04 00:22 UTC, junbong approved these changes

2023-12-04 04:25 UTC, DemetriouJohn requested changes
Please fix tests

2023-12-05 08:09 UTC, DemetriouJohn commented
@junbong Please don't approve blindly if unit tests are failing

2023-12-05 08:09 UTC, DemetriouJohn requested changes
Please fix tests

2023-12-05 11:34 UTC, DemetriouJohn approved these changes

2023-12-05 11:37 UTC, merged