Fixing metascraper break
DefinitelyTyped/DefinitelyTyped pull request #67823
Opened 2023-12-08 21:45 UTC by navya9singh

This pr fixes the break caused by the new version of metascraper https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=170347&view=logs&j=6399d89d-3d30-5fff-3e92-07bbaf7ebe2f&t=482eae7c-85d2-5e8a-ea70-a5ab41e9bc13

Also, rolling back the change in the previous prs https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67816, https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67817 and updating the files to use `Rules` in place of `RuleSet` according to https://github.com/microlinkhq/metascraper/issues/674#issuecomment-1846845089

2023-12-08 21:48 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



Inspecting the JavaScript source for this package found some properties that are not in the .d.ts files.
The check for missing properties isn't always right, so take this list as advice, not a requirement.
## metascraper-iframe ([<kbd>unpkg</kbd>](https://unpkg.com/browse/metascraper-iframe@latest/))
was missing the following properties:
1. test
## metascraper-media-provider ([<kbd>unpkg</kbd>](https://unpkg.com/browse/metascraper-media-provider@latest/))
was missing the following properties:
1. getAudio
1. getImage
1. getAuthor
1. getDate
1. getFormatUrls

<details>
<summary>as well as these 4 other properties...</summary>
<p>getPublisher, getTitle, getVideo, getLang</p>
</details>

## metascraper-readability ([<kbd>unpkg</kbd>](https://unpkg.com/browse/metascraper-readability@latest/))
was missing the following properties:
1. readability
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 2d4d57f270afa77670ebe19ae775e8770b6168d8
</p>

2023-12-08 22:16 UTC, jakebailey commented
This will unfortunately force everyone to update to the latest version if they want types to work; maybe it's not a big deal, though it'd be nice if the upstream package would just leave behind a deprecated type alias or something... (I am not sure what our typical method for fixing this kind of issue is, but bumping version and making a breaking change sounds plausible anyway.)

2023-12-11 17:11 UTC, andrewbranch requested changes

2023-12-11 17:11 UTC, andrewbranch commented on types/metascraper-address/package.json
> +        "metascraper": "^5.14.8"
Shouldn’t these all be `"^5.41.0"`? Otherwise `metascraper.Rules` won’t be defined.

2023-12-18 18:31 UTC, andrewbranch approved these changes

2023-12-18 21:55 UTC, merged