Add types for @tgwf/co2
DefinitelyTyped/DefinitelyTyped pull request #67910
Opened 2023-12-17 09:09 UTC by fershad

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2023-12-17 09:10 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/tgwf__co2/package.json
1. types/tgwf__co2/tsconfig.json
1. types/tgwf__co2/tgwf__co2-tests.test.ts
1. types/tgwf__co2/index.d.ts
1. types/tgwf__co2/co2.d.ts

<details>
<summary>as well as these 4 other files...</summary>
<p>types/tgwf__co2/tgwf__co2-tests.ts, types/tgwf__co2/1byte.d.ts, types/tgwf__co2/hosting.d.ts, types/tgwf__co2/sustainable-web-design.d.ts</p>
</details>


Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against bc9c6ad4a62ee41ef874e0fd6850b35dcfdc67ba
</p>

2023-12-17 18:10 UTC, peterblazejewicz commented
It seems there is ongoing effort in upstream project to introduce types declaration to the module:
1) there is blanked declaration:
https://github.com/thegreenwebfoundation/co2.js/blob/main/index.d.ts
2) dedicated issue:
https://github.com/thegreenwebfoundation/co2.js/issues/77
what's relation of this PR to the community efforts? thx!

2023-12-18 01:57 UTC, fershad commented
Thanks @peterblazejewicz. The maintainers (@mrchrisadams and I) have no plans to convert the library to Typescript. https://github.com/thegreenwebfoundation/co2.js/issues/77 was raised by Chris to gain an understanding as to what my be involved in the process. In subsequent conversations, some of which have been internal to our team and aren't captured in the issue at present, we've decided not to convert the library to Typescript. Chris and I as maintainers lack the TS know-how to ensure this would be done properly.

The empty `index.d.ts` file was created in https://github.com/thegreenwebfoundation/co2.js/pull/131 to stop TS users from getting an error when using the library in their projects. 

When this PR (this one we're in now) merges, we would remove that `index.d.ts` file and advise all users to get import type definitions from this source instead.

We feel that having type definitions in this open source repo will allow those who need them to pull them into their projects without imposing them on everyone.

2023-12-18 07:09 UTC, mrchrisadams commented
hi folks I can confirm that we do not have plans to convert the library to Typescript and the Definitely Typed approach is the one we prefer for the co2.js library. I have one query though:

> And if you do find someone, maybe even recruit them to be a second owner to make future changes easier...

I'm not sure how to become a second owner, but I'm happy to do so, once I know how.

2023-12-18 19:29 UTC, peterblazejewicz commented
> I'm not sure how to become a second owner, but I'm happy to do so, once I know how.


just amend the owners with GitHub handle and give an ACK to the change:
```json
"owners": [
    {
        "name": "Fershad Irani",
        "githubUsername": "fershad"
    }
]
```

2023-12-19 02:17 UTC, fershad commented
I've added @mrchrisadams as an owner.

2023-12-19 02:17 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/tgwf__co2/package.json

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c1b6b3ff9cb8806f4b360a34b3c39572620a5b57
</p>

2023-12-27 18:45 UTC, sandersn requested changes

2023-12-27 18:45 UTC, sandersn commented on types/tgwf__co2/index.d.ts
> +export default co2js;
unfortunately, DT still technically only provides types for commonjs -- so you need to use `export = co2js` here, which is the Typescript syntax for commonjs exports. `export default co2js` is only allowed for commonjs when the commonjs version exports a default property like so: `require('@tgwf/co2').default`. But @tgwf/co2 doesn't do this.
```suggestion
export = co2js;
```

You can hack in types for ES exports, but it's still janky. See `types/three` for an example.

2023-12-27 18:45 UTC, sandersn commented on types/tgwf__co2/tsconfig.json
> +        },
this should not be needed. Can you try deleting it?

2023-12-30 12:25 UTC, fershad commented
Thanks for the pointers @sandersn. I've made those changes [14f9b1c](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67910/commits/14f9b1cc01c5ff627726fc41ac5965a4556c1ced) and [5c8857f](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67910/commits/5c8857ffdc1108ba5d2105feb255f618bdf05b54)

2023-12-30 12:49 UTC, fershad commented
Apologies, a few more updates after tests failed previously.

2023-12-30 13:47 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/tgwf__co2/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f25b9076c71d7000eb671b7596074a18da00ad6d
</p>

2024-01-05 22:41 UTC, sandersn approved these changes

2024-01-07 15:20 UTC, peterblazejewicz approved these changes

2024-01-08 03:09 UTC, fershad commented
Ready to merge

2024-01-08 03:10 UTC, merged

2024-01-08 03:51 UTC, fershad commented
Thanks all for your help in getting this merged. Really appreciate the review & guidance.