[passport-jwt]: Make it available for the Request Generic type to be overwriten
DefinitelyTyped/DefinitelyTyped pull request #68173
Opened 2024-01-11 15:03 UTC by ValTashkov

Making the library Express agnostic prevented it from working properly with Express.Request ( which other passport libraries still use ).

- Added a way of passing the Generic Types down to `JwtFromRequestFunction`
Note: Had to disable warning for unnecessary Generics. Couldn't think of another solution to pass the Generic down 

- Added tests

- Changed version
Note: Not sure if I should change it, correct me If I did wrong

Please fill in this template.
- [ x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ x ] Test the change in your own code. (Compile and run.)
- [ x ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ x ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ x ] Provide a URL to documentation or source code which provides context for the suggested changes:
In this example the `passport-jwt` is used together with `passport-strategy` and the `Strategy.authenticate` expects `Express.Request` as first argument and that creates a conflict with the new Express agnostic changes from `passport-jwt` as we the type of Request is always the `globalThis.Request`
Before the changes:
![image](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/137040855/c29dd472-fb20-41af-a6b5-9d23143b06ac)
After the changes ( allowing an `Express.Request` to be set ):
![image](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/137040855/d173e8aa-0724-4af5-92c1-121318c312a7)
- [ x ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-01-11 15:10 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/passport-jwt/index.d.ts
1. types/passport-jwt/passport-jwt-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 64cd5cb8bc926c6f30f09be5abca3947fd289150
</p>

2024-01-11 20:30 UTC, sheetalkamat requested changes

2024-01-11 20:30 UTC, sheetalkamat commented on package.json
> +        "@types/node": "^20.11.0",
```suggestion
```

2024-01-12 07:48 UTC, ValTashkov commented
The issue at hand is fixed in -> https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68102 . Closing this PR

2024-01-12 07:48 UTC, closed without merging