[@types/braintree] Allow ValidatedResponse.transaction to be undefined
DefinitelyTyped/DefinitelyTyped pull request #68225
Opened 2024-01-17 05:27 UTC by dejan-lukic

Relevant quote from the [Braintree Docs](https://developer.paypal.com/braintree/docs/reference/response/transaction/node#validation-errors)

> When receiving a validation error, a Transaction object will not be present on the Result object.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://developer.paypal.com/braintree/docs/reference/response/transaction/node#validation-errors - `When receiving a validation error, a Transaction object will not be present on the Result object.`
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-01-17 14:34 UTC, sedenardi commented
@dejan-lukic I no longer use this `npm` package and its types, can you please remove me from the `owners` section of `package.json`?

2024-01-18 00:56 UTC, dejan-lukic commented
@sedenardi done ✅

2024-02-06 23:38 UTC, andrewbranch requested changes

2024-02-06 23:38 UTC, andrewbranch commented on types/braintree/index.d.ts
> +        transaction?: T extends Transaction ? Transaction : never;
This is a breaking change, even for people who are already writing perfectly safe code here:

```ts
if (result.success) {
  doSomethingWith(result.transaction)
}
```

It sure looks like this should be split up into a discriminated union of error response and success response.

2024-03-09 00:59 UTC, closed without merging