[@types/meteor] Change user `services` to empty interface
DefinitelyTyped/DefinitelyTyped pull request #68256
Opened 2024-01-19 18:32 UTC by ptbarnum4

### Problem:
Previously, the `services` field on `Meteor.User` was declared as `any`, making it impossible to declare a more specific type for the services object. Throws error - `Subsequent property
declarations must have the same type. Property 'profile' must be of type 'any' ...`.

### Solution
Instead, create a new empty `UserServices` interface that will be used for `User.services`. This allows customization of the `User.services` type.

Note: This is a breaking change.  It will cause accesses to fields under `user.services` to display type errors (instead of `any`), where they would previously now show errors.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: Context is not app specific
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`. (N/A)

2024-01-22 08:40 UTC, radekmie requested changes
Meteor types are part of the Meteor repository now - please file a PR there instead.

2024-01-22 16:41 UTC, ebroder commented
@radekmie I think that we should continue accepting PRs to the DefinitelyTyped types. So far, there hasn't been a release of Meteor where the built-in types worked (most recently, because of https://github.com/meteor/meteor/pull/12922). Until that changes, I don't think we can tell people not to use these declarations.

2024-01-22 16:47 UTC, perbergland commented
I agree. Until the meteor build and publish system performs at least a sanity check of all types we cannot use them because there are just too many broken types. 
zodern:types could also do with some fixes and improvements. This repo should be the master and then these validated types can be merged into meteor periodically

2024-01-23 08:24 UTC, radekmie approved these changes
OK then. But would any of you like to already check them? There's been quite a few changes in the Meteor repo already.

2024-01-23 14:53 UTC, ptbarnum4 commented
Ready to merge

2024-01-23 14:53 UTC, merged