feat: support `punycode` js file imports
DefinitelyTyped/DefinitelyTyped pull request #68273
Opened 2024-01-21 20:13 UTC by hrueger

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.
- [x] Other: `punycode` is also a builtin node module. To explicitely load the npm package instead, people have been adding a `/` suffix to the import. However, this breaks some bundlers, which means the import needs to be `punycode/punycode.js`. Currently, typescript complains about that, but this PR fixes that.

2024-02-09 02:36 UTC, jakebailey requested changes

2024-02-09 02:36 UTC, jakebailey commented on types/punycode/punycode.js.d.ts
This should just be `punycode.d.ts`, because `d.ts` files type `.js` files. But, it's not clear to me _why_ this is needed.

2024-02-09 02:38 UTC, jakebailey commented on types/punycode/punycode.js.d.ts
I see now that this shadows a node module, so that makes slightly more sense. Probably this should be `export = require("punycode")` to match module shape.

2024-02-09 12:03 UTC, hrueger commented on types/punycode/punycode.js.d.ts
Hi @jakebailey,
thanks for reviewing.

When I rename the file from `punycode.js.d.ts` to `punycode.d.ts`, I get the following error message in the test: `Could not find a declaration file for module 'punycode/punycode.js'. `:
![grafik](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/18656830/f83ecb71-fb86-456a-ad78-0d025faadbf9)

If I use `export = require("punycode")`, I get this:
![grafik](https://github.com/DefinitelyTyped/DefinitelyTyped/assets/18656830/54f54be9-a9f4-4361-bcdc-bab823cd3228)

I added the reason for this change in the pr description at the bottom, maybe it was not clear enough:
As you said, `punycode` is also a builtin node module. To explicitely load the npm package instead, people have been adding a / suffix to the import. However, this breaks some bundlers and esm (https://github.com/salesforce/tough-cookie/issues/256), which means the import needs to be punycode/punycode.js ([example](https://github.com/salesforce/tough-cookie/pull/297/files)). Currently, typescript complains about that, but this PR fixes that.

2024-02-09 19:40 UTC, jakebailey commented on types/punycode/punycode.js.d.ts
I don't have the same problem with this diff:

```diff
diff --git a/types/punycode/punycode.d.ts b/types/punycode/punycode.d.ts
new file mode 100644
index 0000000000..fd4ea774ee
--- /dev/null
+++ b/types/punycode/punycode.d.ts
@@ -0,0 +1,2 @@
+import punycode = require(".");
+export = punycode;
diff --git a/types/punycode/punycode.js.d.ts b/types/punycode/punycode.js.d.ts
deleted file mode 100644
index ef8f0464f7..0000000000
--- a/types/punycode/punycode.js.d.ts
+++ /dev/null
@@ -1 +0,0 @@
-export * from "punycode";
diff --git a/types/punycode/tsconfig.json b/types/punycode/tsconfig.json
index 5a7dfe15b2..674baae5b8 100644
--- a/types/punycode/tsconfig.json
+++ b/types/punycode/tsconfig.json
@@ -14,7 +14,7 @@
     },
     "files": [
         "index.d.ts",
-        "punycode.js.d.ts",
+        "punycode.d.ts",
         "punycode-tests.ts"
     ]
 }
```

I made a mistake on `export = require("punycode")`; sorry about that.

2024-02-12 16:02 UTC, hrueger commented on types/punycode/punycode.js.d.ts
Thanks for the clarification @jakebailey . Could you please take another look?

2024-02-12 16:03 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/punycode/punycode.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against ea3bd6686eba21656e73d4e78ea8464c5211b31e
</p>

2024-02-12 17:18 UTC, jakebailey approved these changes
LGTM, but I think in the future we're going to attempt to make `index.d.ts` not a required file for DT packages such that this code could just be stored in `punycode.d.ts` only and be more accurate.

2024-02-12 17:20 UTC, hrueger commented
Thanks @jakebailey !

Ready to merge

2024-02-12 17:20 UTC, merged