@types/mysql-import [update]: Update to version 5 definition.
DefinitelyTyped/DefinitelyTyped pull request #68339
Opened 2024-01-26 14:35 UTC by doubutsunokarada

Please fill in this template.

- [ X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X ] Test the change in your own code. (Compile and run.)
- [ X ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ X ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [ X ] Provide a URL to documentation or source code which provides context for the suggested changes: [mysql-import](https://www.npmjs.com/package/mysql-import)
- [ X ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-01-26 14:37 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/mysql-import/index.d.ts
1. types/mysql-import/mysql-import-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 208206a4cec9ce4bd73f6d2606d4333d49d5ff99
</p>

2024-01-26 16:23 UTC, bengry requested changes

2024-01-26 16:23 UTC, bengry commented on types/mysql-import/index.d.ts
> +}
```suggestion
    onProgress(callback: (object: {
      total_files: number;
		  file_no: number;
		  bytes_processed: number;
		  total_bytes: number;
		  file_path: string;
	  }) => void): void;
    onDumpComplete(callback: (object: {
      total_files: number;
		  file_no: number;
		  		  file_path: string;
		  		  error: Error | null;
}) => void): void;
    import(...input: ReadonlyArray<string | readonly string[]>): Promise<void>;
    disconnect(graceful?: boolean): Promise<void>;
}
```

2024-01-26 16:41 UTC, doubutsunokarada commented on types/mysql-import/index.d.ts
> +}
thanks!

2024-01-26 16:41 UTC, doubutsunokarada commented on types/mysql-import/index.d.ts
> +    constructor(settings: Pick<ConnectionOptions, 'user' | 'password' | 'database' | 'host'>);
> What about port, ssl? (https://github.com/Pamblam/mysql-import#new-importerhost-user-password-database-port-ssl).

Sorry, I missed that.

> Why is the Pick needed?

`ConnectionOptions` has other properties that are not needed. Should I remove it?

2024-01-27 09:26 UTC, bengry approved these changes

2024-01-27 09:37 UTC, doubutsunokarada commented
Ready to merge

2024-01-27 09:38 UTC, merged

2024-01-27 09:39 UTC, doubutsunokarada commented
@bengry Thanks for reviewing!

2024-01-27 09:44 UTC, bengry commented
> @bengry Thanks for reviewing!

Thanks for your work, and for sharing the types with the community 🥇