[@types/node]: Fix typings for ClientRequestArgs.createConnection
DefinitelyTyped/DefinitelyTyped pull request #68356
Opened 2024-01-28 06:36 UTC by YesWeDont

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes:
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

## Changes
- `ClientRequestArgs.createConnection()`: widened return value and callback parameter to include `stream.Duplex`. Node.js docs specify that `ClientRequestArgs.createConnection()` method provided to `http.request()` can return any instance of `stream.Duplex`, not just `net.Socket`.
    https://nodejs.org/api/http.html#httprequestoptions-callback:
    > `createConnection` [<Function>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function) A function that produces a socket/stream to use for the request when the `agent` option is not used. This can be used to avoid creating a custom `Agent` class just to override the default `createConnection` function. See [`agent.createConnection()`](https://nodejs.org/api/http.html#agentcreateconnectionoptions-callback) for more details. Any [`Duplex`](https://nodejs.org/api/stream.html#class-streamduplex) stream is a valid return value.

- `ClientRequestArgs.createConnection()`: widened return value and callback error parameters to allow falsy values
    - The [docs for agent.createConnection()](https://nodejs.org/api/http.html#agentcreateconnectionoptions-callback) (which should be identical to `ClientRequestArgs.createConnection()`) state that that the created `stream.Duplex` may be returned either by invoking the second `callback(err, stream)` or by returning the `stream.Duplex` directly. Reading [the source code](https://github.com/nodejs/node/blob/main/lib/_http_client.js#L339C5-L356C8) reveals that if `ClientRequestArgs.createConnection()` returns a falsy value, then it is assumed that the callback path was taken. Thus it is safe both to allow falsy return values for `ClientRequestArgs.createConnection()` and falsy `err` values in `callback(err, stream)`.

2024-01-28 08:14 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/node/http.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 439f5d93b9f87bd365d04ef0da38a04a42d4305f
</p>

2024-01-28 09:52 UTC, Semigradsky requested changes
Please add the same changes to `node/ts4.8` folder

2024-01-30 10:50 UTC, Semigradsky approved these changes

2024-01-31 19:15 UTC, peterblazejewicz approved these changes, later dismissed

2024-01-31 19:26 UTC, jakebailey commented on types/node/ts4.8/http.d.ts
>          // https://github.com/nodejs/node/blob/master/lib/_http_client.js#L278
I would recommend removing this line if you're also going to remove it from the other one. The two dirs should be nearly identical (trying to fix that in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68356)

2024-01-31 20:30 UTC, jakebailey commented
I'm looking into the failures here to see if there's something up with dt-tools + pnpm.

2024-01-31 22:29 UTC, jakebailey commented
My fix to the DT infra worked, so this PR is now passing.

2024-02-02 23:50 UTC, RyanCavanaugh submitted a review, later dismissed
Per jakebailey's comment

2024-02-05 20:32 UTC, YesWeDont commented
> Per jakebailey's comment

I think I've already pushed the changes a few days ago

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68356/commits/46ebd17ebcd6061974402282ea3ab8fd750e0a09

2024-02-05 20:34 UTC, jakebailey commented
The two files definitely have different changes if you look at the diff.

2024-02-06 10:38 UTC, jakebailey commented
Do you also need to make this change to the other node versions?

2024-02-15 15:36 UTC, Semigradsky approved these changes

2024-02-26 18:34 UTC, jakebailey approved these changes

2024-02-29 11:22 UTC, merged