Added compatibility with MapBox Offset definition and fixed test file
DefinitelyTyped/DefinitelyTyped pull request #68363
Opened 2024-01-29 01:59 UTC by lancegliser

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [X] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67917#issuecomment-1913801294
  - https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/68361
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-01-29 17:45 UTC, jakebailey requested changes

2024-01-29 18:07 UTC, lancegliser commented on types/mapboxgl-spiderifier/mapboxgl-spiderifier.tests.ts
I think you had a typo in your example. I used `mapboxgl-spiderifier-tests.ts` and included it into the `files` of `tsconfig.json`. Is that what you needed?

2024-01-29 18:58 UTC, jakebailey approved these changes

2024-01-29 21:36 UTC, merged

2024-01-30 01:01 UTC, bewithjonam commented
👍