Added AWS Lambda stream type to `aws-lambda`.
DefinitelyTyped/DefinitelyTyped pull request #68490
Opened 2024-02-05 19:20 UTC by lancejpollard

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
  - I am not sure about this, did I do things right? How do I import `stream` properly?
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-02-05 19:29 UTC, codershiba commented on types/aws-lambda/handler.d.ts
> +  stream.EventEmitter & {
```suggestion
  typeof stream.EventEmitter & {
```

2024-02-22 12:32 UTC, codershiba commented on types/aws-lambda/handler.d.ts
> +declare var awslambda: {
```suggestion
export var awslambda: {
```

2024-02-25 23:07 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/aws-lambda/handler.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9f4b9deaf53b83a3f7b5422c4ce95502505af893
</p>

2024-02-26 01:14 UTC, simonbuchan requested changes
small nit to avoid compatibility issues in the future

sorry I didn't see this one earlier!

2024-02-26 01:14 UTC, simonbuchan commented on types/aws-lambda/handler.d.ts
> +  event: APIGatewayProxyEvent,
I don't think the event has to be from API Gateway. In fact, API Gateway doesn't support streaming the response to reduce TTFB, IIRC.

This should be generic in the event like Handler, and ideally every trigger would have a streaming alias too, but that's probably a bit too much to ask for.

2024-03-28 01:35 UTC, closed without merging