[WebXR] Add detectedPlanes, improve detectedMeshes, add tests
DefinitelyTyped/DefinitelyTyped pull request #68549
Opened 2024-02-07 22:23 UTC by sorskoot

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 
  - https://immersive-web.github.io/real-world-geometry/plane-detection.html#plane-set
  - https://immersive-web.github.io/real-world-meshing/#mesh-set
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

---

Changes:
- Add detectPlanes to XRFrame interface
- Move detectMeshes to the correct location in the file, below comment about draft and together with related definitions
- Add optional initiateRoomCapture to XRSession
- Remove legacy plane detection definition
- Correct type of `lastChangeTime` on XRMesh
- Add optional `semanticLabel` attribute to XRMesj
- Add tests for these changes

2024-02-07 22:27 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/webxr/webxr-tests.ts
1. types/webxr/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 557112600605789efb92e7947f22748eeee19d47
</p>

2024-02-08 14:18 UTC, RaananW requested changes

2024-02-08 14:18 UTC, RaananW commented on types/webxr/index.d.ts
> +    readonly detectedPlanes: XRPlaneSet;
This object only exists if the plane detection feature is enabled. There is no way to define this condition in the declaration file. I think optional ("?") or " | undefined" is required here.

2024-02-08 14:18 UTC, RaananW commented on types/webxr/index.d.ts
> +    readonly detectedMeshes: XRMeshSet;
Same comment as above

2024-02-08 18:45 UTC, RaananW approved these changes

2024-02-08 18:47 UTC, sorskoot commented
Ready to merge

2024-02-08 18:48 UTC, merged