Add types for react native dialog input
DefinitelyTyped/DefinitelyTyped pull request #68574
Opened 2024-02-09 18:18 UTC by jeswinsimon

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:
- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [x] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2024-02-09 18:44 UTC, codershiba commented on types/react-native-dialog-input/package.json
> +    "devDependencies": {
```suggestion
    "devDependencies": {
              "@types/react": "*",
              "react-native": "*",
```

2024-02-09 18:46 UTC, codershiba commented on types/react-native-dialog-input/index.d.ts
> +import React from 'react';
```suggestion
import * as React from 'react';
```

2024-02-09 18:55 UTC, codershiba commented
Revert commit 363f150

2024-02-09 18:59 UTC, codershiba requested changes
Tests are missing

2024-02-09 19:05 UTC, jeswinsimon commented
> Tests are missing

Added tests now.

2024-02-09 19:27 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/react-native-dialog-input/react-native-dialog-input-tests.tsx
1. types/react-native-dialog-input/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d32cf84363271212718ebbe4a7999071050dd321
</p>

2024-02-09 20:43 UTC, peterblazejewicz approved these changes
@jeswinsimon thanks!
LGTM!

2024-02-09 20:44 UTC, peterblazejewicz commented
@codershiba thanks!

2024-02-09 20:57 UTC, ghost approved these changes

2024-02-10 02:13 UTC, jeswinsimon commented
Ready to merge

2024-02-10 02:13 UTC, merged