[mapbox-gl] add name types and overloads for set/get pain/layout prop…
DefinitelyTyped/DefinitelyTyped pull request #68585
Opened 2024-02-10 08:15 UTC by thejasonxie

Mapbox [setPaintProperty](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L357), [getPaintProperty](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L359), [setLayoutProperty](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L361) and [getLayoutProperty](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L363) functions accept a name defined as type `string`. However these functions don't accept any strings but strings that match the keys of [layer sub properties](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L363).

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://docs.mapbox.com/style-spec/reference/layers/#layer-sub-properties

2024-02-10 08:19 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/mapbox-gl/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c370a3a7e2920d3fecfc51557b991a3bca5f8795
</p>

2024-02-24 13:28 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/mapbox-gl/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4b2b62edcda6d33ba70ddb191844502ea72ba961
</p>

2024-02-28 17:29 UTC, jakebailey requested changes

2024-02-28 17:29 UTC, jakebailey commented on types/mapbox-gl/index.d.ts
> +        setPaintProperty(layer: string, name: AnyPaintName, value: any, options?: FilterOptions): this;
This doesn't seem right; isn't `AnyPaintName` a union of string literals? So the first overload will still take precedence?

If you're looking for auto-complete, you'd want to instead make one overload with a parameter `AnyPaintName | (string & {})`.

But as-is, this PR doesn't make sense.

2024-03-30 18:43 UTC, closed without merging