[tabulator-tables] Fix parameter order error issue.
DefinitelyTyped/DefinitelyTyped pull request #68613
Opened 2024-02-13 09:28 UTC by Xiuer0x0

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-02-13 09:32 UTC, mike-lischke requested changes
Hi, thanks for the PR, but even though this change is simple, please provide a link or other reference that shows the wrong order and add a test (which can be as simple as defining a local constant of menu signature and assigns it a closure with the new parameter list.

2024-02-13 10:08 UTC, Xiuer0x0 commented
> Hi, thanks for the PR, but even though this change is simple, please provide a link or other reference that shows the wrong order and add a test (which can be as simple as defining a local constant of menu signature and assigns it a closure with the new parameter list.

I re-edited and tried to add some relevant information to explain the error.

I'm very sorry. Please forgive my poor English.

2024-02-13 10:41 UTC, mike-lischke commented
No worries about your english @Xiuer0x0. I'm not a native english speaker either. Your description about the problem is perfect. Only add a test please so we can accept the PR. Thanks.

2024-02-13 12:43 UTC, mike-lischke approved these changes

2024-02-14 03:10 UTC, Xiuer0x0 commented
Ready to merge

2024-02-14 03:11 UTC, merged