React Element Type Definition - Add Type Definition for element `set`
DefinitelyTyped/DefinitelyTyped pull request #68656
Opened 2024-02-15 23:19 UTC by mast9rmind

Added type definition for `set` element in svg.

- [x ] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2024-02-15 23:36 UTC, eps1lon requested changes
Thank you! Could you also apply the same changes to the fork in the `ts5.0` folder?

2024-02-15 23:46 UTC, mast9rmind commented
> Thank you! Could you also apply the same changes to the fork in the `ts5.0` folder?

Yeah, I just applied there as well.

2024-02-15 23:50 UTC, eps1lon approved these changes
Thank you!

2024-02-17 02:01 UTC, mast9rmind commented
Ping @johnnyreilly @Jessidhia 
Would you please review this?

2024-02-17 06:19 UTC, merged