[@types/apple-mapkit-js] Update types for MapKitInitOptions and MapConstructorOptions
DefinitelyTyped/DefinitelyTyped pull request #68666
Opened 2024-02-16 21:29 UTC by hkbertoson

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [ X] Provide a URL to documentation or source code which provides context for the suggested changes: [MapkitinitOptions](https://developer.apple.com/documentation/mapkitjs/mapkitinitoptions)
[LoadPriority](https://developer.apple.com/documentation/mapkitjs/mapconstructoroptions/4096368-loadpriority)

2024-02-16 21:33 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/apple-mapkit-js-browser/apple-mapkit-js-browser-tests.ts
1. types/apple-mapkit-js-browser/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 819fa27e5629d65654068bf1c7a4a2078be35476
</p>

2024-02-16 21:33 UTC, vinayakkulkarni requested changes

2024-02-16 21:33 UTC, vinayakkulkarni commented on types/apple-mapkit-js-browser/index.d.ts
> +         *
```suggestion
```

2024-02-16 21:33 UTC, vinayakkulkarni commented on types/apple-mapkit-js-browser/apple-mapkit-js-browser-tests.ts
> +
```suggestion
```

2024-02-16 21:33 UTC, vinayakkulkarni commented on types/apple-mapkit-js-browser/index.d.ts
> +
```suggestion
```

2024-02-16 21:33 UTC, vinayakkulkarni commented on types/apple-mapkit-js-browser/index.d.ts
> +
```suggestion
```

2024-02-18 03:50 UTC, MysteryBlokHed commented on types/apple-mapkit-js-browser/index.d.ts
> +        libraries?: string[] | undefined;
If this array is never modified, then it should be marked `readonly`:

```suggestion
        libraries?: readonly string[] | undefined;
```

2024-02-23 17:11 UTC, Anonymous4078 approved these changes

2024-02-23 17:12 UTC, hkbertoson commented
Ready to Merge

2024-02-23 17:13 UTC, merged