added tabl-service types
DefinitelyTyped/DefinitelyTyped pull request #68748
Opened 2024-02-24 06:20 UTC by shaynesstark

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [X] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [X] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [X] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [X] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [X] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [X] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [X] Delete the package's directory.
- [X] Add it to `notNeededPackages.json`.

2024-02-24 06:25 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/tabl-service/tabl-service-tests.ts
1. types/tabl-service/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 11a7f349b3f0257da1d461335f65507a8be583bd
</p>

2024-02-26 17:58 UTC, jakebailey requested changes

2024-02-26 17:58 UTC, jakebailey commented on types/tabl-service/index.d.ts
> +export enum ToastType {
This being exported means this is a module, but the npm package `tabl-service` doesn't exist, so how are you expecting this to be imported? Is this supposed to be defining a global?

It's exceedingly rare to have a nonNpm package export something.

2024-02-26 18:12 UTC, jakebailey commented on types/tabl-service/index.d.ts
> +export enum ToastType {
If this is for an internal package, it definitely should not be on DT. DT is for public npm packages, global types, runtime environment descriptions, etc.

You can publish a package like this internally, and if needed add the package to the `types` array in `tsconfig` to include it (or use references), but it definitely should not be on DT if the public cannot use it.

2024-02-26 19:00 UTC, closed without merging