AlpineJS: Add optional arg types to Binding functions
DefinitelyTyped/DefinitelyTyped pull request #68910
Opened 2024-03-06 00:48 UTC by mattvague

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-03-07 18:22 UTC, mattvague commented
@ekwoka Let me know what you think 😃

2024-03-08 08:39 UTC, ekwoka commented
Made a PR to your Repo on this that should improve things and demo the inferred event types.

I was thinking it would be nice/cool to have a way to have all the types improved for all directives.

2024-03-10 04:11 UTC, Anonymous4078 approved these changes

2024-03-10 04:25 UTC, ekwoka commented
@Anonymous4078 Who are you? How do you get to approve things?

2024-03-10 04:28 UTC, ekwoka requested changes
When possible, if you can review and merge the PR I made to your branch.

2024-03-10 08:36 UTC, wtho reviewed
Awesome improvements, thanks @mattvague!

In case you missed this, @ekwoka went one step further and added more event types, please check the [PR on you branch](https://github.com/invisiblethemes/DefinitelyTyped/pull/2/files), I think then we are good to merge this.

2024-03-13 21:05 UTC, mattvague commented
>Awesome improvements, thanks @mattvague!

> In case you missed this, @ekwoka went one step further and added more event types, please check the [PR on you branch](https://github.com/invisiblethemes/DefinitelyTyped/pull/2/files), I think then we are good to merge this.

Done! I have a few more improvements that properly the the `this` property of binding directive functions and some other good stuff but I'll make that a separate PR

2024-03-14 01:45 UTC, ekwoka commented on types/alpinejs/index.d.ts
> +    bind<T extends Bindings<T>>(element: HTMLElement, bindings: T | (() => T)): void;
.....yes

2024-03-14 02:32 UTC, ekwoka approved these changes
Looks great!

Thanks for the help!

2024-03-14 02:34 UTC, ekwoka commented
Ready to merge

2024-03-14 02:35 UTC, merged