add tool-types files.
DefinitelyTyped/DefinitelyTyped pull request #68951
Opened 2024-03-10 13:17 UTC by epldlnwynn

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-03-10 16:04 UTC, codershiba commented on types/tool.js/LICENSE
This LICENSE is not needed

2024-03-11 00:16 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/tool.js/tool-js-tests.ts
1. types/tool.js/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 24d1bd554bba6cfc64889a2880ab9f04601db267
</p>

2024-03-11 00:20 UTC, epldlnwynn commented
ok

2024-03-12 20:53 UTC, peterblazejewicz commented
- you probably want to use global module augmentation (adding features to existing global objects):
https://www.typescriptlang.org/docs/handbook/declaration-merging.html#global-augmentation
(at the moment a string gets bare-bones features, supporting whatever your code overrides as it wins LIFO)
- this is non-nom module, but sounds strangely close to existing 'tooljs' (and similar), jus
- project ships it's own types already under `tool-types/index.d.ts`

2024-03-18 18:56 UTC, sheetalkamat requested changes
There are multiple issues already pointed out in feedback .. pls address that

2024-03-18 18:56 UTC, sheetalkamat commented on types/tool.js/tool-js-tests.ts
> +import "tool-extend"
why ?

2024-04-19 01:36 UTC, closed without merging