Revert "[@types/react] fix: remove onPointerEnterCapture & onPointerLeaveCapture (#68984)
DefinitelyTyped/DefinitelyTyped pull request #69005
Opened 2024-03-15 14:43 UTC by Thulof

**Please see #69006.** 

This reverts commit 73b5985432df63aa8724c9bfe257c5f3dbbebfcd.

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: #69004 
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-03-15 15:33 UTC, eps1lon requested changes
We need to confirm https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/69006 first.

2024-03-18 13:15 UTC, eps1lon approved these changes
Thank you for sticking with it!

2024-03-18 13:27 UTC, merged

2024-04-02 08:55 UTC, silversonicaxel commented
The revert was partially done.
As we can see here https://github.com/DefinitelyTyped/DefinitelyTyped/commit/73b5985432df63aa8724c9bfe257c5f3dbbebfcd the folders initially involved were `react/`, `react/ts5.0`, `react/v16`, `react/v17` but the revert touched only `react/v16`, `react/v17`. 

Shall we need another revert patch?

2024-05-03 22:23 UTC, fzaninotto commented
This is still not fixed in `@types/react` v18.2.78.

2024-05-13 09:17 UTC, Thulof commented
> This is still not fixed in `@types/react` v18.2.78.

According to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69243#pullrequestreview-1973380929, the change won't be reverted for 18 or next.

2024-05-13 09:17 UTC, Thulof commented
> This is still not fixed in `@types/react` v18.2.78.

@fzaninotto According to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69243#pullrequestreview-1973380929, the change won't be reverted for 18 or next.