Alpinejs: Solves bug with InterceptorInference on complex objects
DefinitelyTyped/DefinitelyTyped pull request #69050
Opened 2024-03-19 06:57 UTC by ekwoka

Fixes an issue in complex types where InferIntereceptors resulted in slow and overly deep object comparisons by limiting depth check

Fixes bug in Bind type to allow arguments in binding functions

Adds type support for Objects of bindings.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-03-19 07:00 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/alpinejs/alpinejs-tests.ts
1. types/alpinejs/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e3aad3b647db98e5a254f1e37c8e28a7b9d1dea2
</p>

2024-03-19 14:42 UTC, Anonymous4078 approved these changes

2024-03-19 17:45 UTC, wtho requested changes

2024-03-19 17:45 UTC, wtho commented on types/alpinejs/alpinejs-tests.ts
> +    const undo = Alpine.bind("bindings", (arg: string) => ({
Better naming: `unbind`

2024-03-25 04:58 UTC, wtho approved these changes

2024-03-25 05:02 UTC, ekwoka commented
Ready to merge

2024-03-25 05:02 UTC, merged