Definitions for caverphone
DefinitelyTyped/DefinitelyTyped pull request #69093
Opened 2024-03-21 07:57 UTC by hu0529

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-03-21 07:58 UTC, hu0529 commented
Definitions for caverphone

2024-03-21 08:58 UTC, hu0529 commented
Definitions for caverphone

2024-03-21 08:59 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/caverphone/index.d.ts
1. types/caverphone/caverphone-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8f7f4e047d5018df26e2e95ed54150ce0cf960fc
</p>

2024-03-21 17:52 UTC, sheetalkamat approved these changes, later dismissed

2024-03-21 17:53 UTC, sheetalkamat requested changes
Run `pnpm dprint fmt`

2024-03-21 20:23 UTC, MysteryBlokHed commented on types/caverphone/index.d.ts
> +* @return { string }
FYI: these type hints are not needed in TypeScript files

```suggestion
* @param word -Start with a word
```

2024-03-22 02:32 UTC, hu0529 commented
Definitions for caverphone

2024-03-22 12:48 UTC, MysteryBlokHed requested changes
> Run `pnpm dprint fmt`

You should still run this for formatting

2024-03-25 11:01 UTC, hu0529 commented
Definitions for caverphone

2024-03-25 17:14 UTC, MysteryBlokHed requested changes
Still needs formatting?

2024-03-27 08:03 UTC, hu0529 commented
Format the added caverPhone

2024-03-28 03:01 UTC, hu0529 commented
> Run `pnpm dprint fmt`

Could you please review it again? It has been reformatted

2024-03-28 19:12 UTC, navya9singh approved these changes

2024-03-29 01:19 UTC, hu0529 commented
Ready to merge

2024-03-29 01:20 UTC, merged