Definitions for imtype
DefinitelyTyped/DefinitelyTyped pull request #69110
Opened 2024-03-22 03:23 UTC by hu0529

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-03-22 03:23 UTC, hu0529 commented
Definitions for imtype

2024-03-22 03:26 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/imtype/imtype-tests.ts
1. types/imtype/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3c134cae8d9d2d1ec348fd1bcf717cceee925b1b
</p>

2024-03-22 04:50 UTC, e6nlaq commented on types/imtype/imtype-tests.ts
> +let isTIF = imType.isBMP( imTypeData )
```suggestion
let isJPG = imType.isJPG( imTypeData )
let isPNG = imType.isPNG( imTypeData )
let isGIF = imType.isGIF( imTypeData )
let isTIF = imType.isTIF( imTypeData )
```

2024-03-22 18:02 UTC, sheetalkamat requested changes
`pnpm dprint fmt` to format all the files

2024-03-22 18:02 UTC, sheetalkamat commented on types/imtype/index.d.ts
> +export as namespace imType;
```suggestion
```

There is no evidence that this can be used as global

2024-03-25 07:35 UTC, hu0529 commented
Definitions for imtype

2024-03-25 09:05 UTC, hu0529 commented
Definitions for imtype

2024-03-25 09:17 UTC, e6nlaq requested changes

2024-03-25 09:17 UTC, e6nlaq commented on types/imtype/index.d.ts
> +export as namespace imType;
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69110#discussion_r1535992446

The problem here has not been resolved.

```suggestion

```

2024-03-25 11:33 UTC, hu0529 commented
Definitions for imtype

2024-03-25 12:06 UTC, e6nlaq commented on types/imtype/index.d.ts
> +}
If you write it like this, it should work.

```suggestion
export function isBMP(buffer: Uint8Array): boolean;

export function isJPG(buffer: Uint8Array): boolean;

export function isPNG(buffer: Uint8Array): boolean;

export function isGIF(buffer: Uint8Array): boolean;

export function isTIF(buffer: Uint8Array): boolean;

```

2024-03-26 08:55 UTC, e6nlaq approved these changes
LGTM!
Final decisions are made by the DT maintainer.

2024-03-28 03:18 UTC, hu0529 commented
> `pnpm dprint fmt` to format all the files

Could you please review it again? It has been reformatted

2024-03-28 03:24 UTC, e6nlaq approved these changes

2024-03-28 18:58 UTC, navya9singh approved these changes

2024-03-29 01:18 UTC, hu0529 commented
Ready to merge

2024-03-29 01:19 UTC, merged