Leaflet circle radius should not accept undefined radius
DefinitelyTyped/DefinitelyTyped pull request #69221
Opened 2024-03-31 16:26 UTC by Crakzzy

When passing an undefined a NaN error is thrown. So an undefined should not be used here...

Package changed: leaflet

2024-03-31 20:17 UTC, henrythasler approved these changes
According to https://leafletjs.com/reference.html#circle-option, `CircleOptions.radius` must always be a number.

2024-04-01 16:15 UTC, someonewithpc commented
> According to https://leafletjs.com/reference.html#circle-option, `CircleOptions.radius` must always be a number.

I confirmed in the code, and you're right. @Crakzzy please add a test to prevent a possible future regression

2024-04-01 16:27 UTC, Crakzzy commented
> > According to https://leafletjs.com/reference.html#circle-option, `CircleOptions.radius` must always be a number.
> 
> I confirmed in the code, and you're right. @Crakzzy please add a test to prevent a possible future regression

Okay, right on it 👍

2024-04-01 18:48 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/leaflet/leaflet-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8ee89a35d49e14cbda955cfda367f288a9fb801e
</p>

2024-04-01 23:43 UTC, someonewithpc requested changes
The test isn't meaningful, as it asserts that `10` is a `number`, rather than that the options are meaningful.  To this end, I made #69238, after which it will be possible to test like:

```
let circle = new L.Circle(latLng, 10);
circle = new L.Circle(latLng, { radius: 10 });
// @ts-expect-error
circle = new L.Circle(latLng, { radius: undefined });
// @ts-expect-error
circle = new L.Circle(latLng, { radius: null });
// @ts-expect-error
circle = new L.Circle(latLng, { radius: NaN });
// @ts-expect-error
circle = new L.Circle(latLng, { radius: '10' });
// @ts-expect-error
circle = new L.Circle(latLng, { });
// @ts-expect-error
circle = new L.Circle(latLng);
```

Additionally, `CircleOptions` should be written in terms of `CircleMarkerOptions`, and that should be changed to require the `radius`, and the factory functions should mark the `options` as required

For example, the following commit could replace the commits in this PR

```
commit eb14ccb4f403cf09570f586d8406e542cf794da5
Author: Hugo Sales
Date:   Mon Apr 1 21:04:57 2024 +0000

    [leaflet] Disallow `undefined` in `CircleOptions.radius`

diff --git a/types/leaflet/index.d.ts b/types/leaflet/index.d.ts
index c8e90ef882..3b1ccaaeb0 100644
--- a/types/leaflet/index.d.ts
+++ b/types/leaflet/index.d.ts
@@ -2082,11 +2082,11 @@ export class Rectangle<P = any> extends Polygon<P> {
 export function rectangle(latLngBounds: LatLngBoundsExpression, options?: PolylineOptions): Rectangle;
 
 export interface CircleMarkerOptions extends PathOptions {
-    radius?: number | undefined;
+    radius: number;
 }
 
 export class CircleMarker<P = any> extends Path {
-    constructor(latlng: LatLngExpression, options?: CircleMarkerOptions);
+    constructor(latlng: LatLngExpression, options: CircleMarkerOptions);
     toGeoJSON(precision?: number | false): geojson.Feature<geojson.Point, P>;
     setLatLng(latLng: LatLngExpression): this;
     getLatLng(): LatLng;
@@ -2100,12 +2100,10 @@ export class CircleMarker<P = any> extends Path {
 
 export function circleMarker(latlng: LatLngExpression, options?: CircleMarkerOptions): CircleMarker;
 
-export interface CircleOptions extends PathOptions {
-    radius: number | undefined;
-}
+export type CircleOptions = CircleMarkerOptions;
 
 export class Circle<P = any> extends CircleMarker<P> {
-    constructor(latlng: LatLngExpression, options?: CircleOptions);
+    constructor(latlng: LatLngExpression, options: CircleOptions);
     constructor(latlng: LatLngExpression, radius: number, options?: CircleOptions); // deprecated!
     toGeoJSON(precision?: number | false): any;
     getBounds(): LatLngBounds;
@@ -2114,8 +2112,8 @@ export class Circle<P = any> extends CircleMarker<P> {
     setStyle(style: PathOptions): this;
 }
 
-export function circle(latlng: LatLngExpression, options?: CircleMarkerOptions): Circle;
-export function circle(latlng: LatLngExpression, radius: number, options?: CircleMarkerOptions): Circle; // deprecated!
+export function circle(latlng: LatLngExpression, options: CircleOptions): Circle;
+export function circle(latlng: LatLngExpression, radius: number, options?: CircleOptions): Circle; // deprecated!
 
 export interface RendererOptions extends LayerOptions {
     padding?: number | undefined;
diff --git a/types/leaflet/leaflet-tests.ts b/types/leaflet/leaflet-tests.ts
index 4a7254c3a9..e27cff7a0d 100644
--- a/types/leaflet/leaflet-tests.ts
+++ b/types/leaflet/leaflet-tests.ts
@@ -990,3 +990,17 @@ L.GeoJSON.geometryToLayer(
         },
     },
 );
+
+let circle = new L.Circle(latLng, 10);
+circle = new L.Circle(latLng, { radius: 10 });
+// @ts-expect-error
+circle = new L.Circle(latLng, { radius: undefined });
+// @ts-expect-error
+circle = new L.Circle(latLng, { radius: null });
+// @ts-expect-error
+circle = new L.Circle(latLng, { radius: '10' });
+// @ts-expect-error
+circle = new L.Circle(latLng, { });
+// @ts-expect-error
+circle = new L.Circle(latLng);
```

2024-04-02 17:20 UTC, Crakzzy commented
> The test isn't meaningful, as it asserts that `10` is a `number`, rather than that the options are meaningful. To this end, I made #69238, after which it will be possible to test like:
> 
> ```
> let circle = new L.Circle(latLng, 10);
> circle = new L.Circle(latLng, { radius: 10 });
> // @ts-expect-error
> circle = new L.Circle(latLng, { radius: undefined });
> // @ts-expect-error
> circle = new L.Circle(latLng, { radius: null });
> // @ts-expect-error
> circle = new L.Circle(latLng, { radius: NaN });
> // @ts-expect-error
> circle = new L.Circle(latLng, { radius: '10' });
> // @ts-expect-error
> circle = new L.Circle(latLng, { });
> // @ts-expect-error
> circle = new L.Circle(latLng);
> ```
> 
> Additionally, `CircleOptions` should be written in terms of `CircleMarkerOptions`, and that should be changed to require the `radius`, and the factory functions should mark the `options` as required
> 
> For example, the following commit could replace the commits in this PR
> 
> ```
> commit eb14ccb4f403cf09570f586d8406e542cf794da5
> Author: Hugo Sales
> Date:   Mon Apr 1 21:04:57 2024 +0000
> 
>     [leaflet] Disallow `undefined` in `CircleOptions.radius`
> 
> diff --git a/types/leaflet/index.d.ts b/types/leaflet/index.d.ts
> index c8e90ef882..3b1ccaaeb0 100644
> --- a/types/leaflet/index.d.ts
> +++ b/types/leaflet/index.d.ts
> @@ -2082,11 +2082,11 @@ export class Rectangle<P = any> extends Polygon<P> {
>  export function rectangle(latLngBounds: LatLngBoundsExpression, options?: PolylineOptions): Rectangle;
>  
>  export interface CircleMarkerOptions extends PathOptions {
> -    radius?: number | undefined;
> +    radius: number;
>  }
>  
>  export class CircleMarker<P = any> extends Path {
> -    constructor(latlng: LatLngExpression, options?: CircleMarkerOptions);
> +    constructor(latlng: LatLngExpression, options: CircleMarkerOptions);
>      toGeoJSON(precision?: number | false): geojson.Feature<geojson.Point, P>;
>      setLatLng(latLng: LatLngExpression): this;
>      getLatLng(): LatLng;
> @@ -2100,12 +2100,10 @@ export class CircleMarker<P = any> extends Path {
>  
>  export function circleMarker(latlng: LatLngExpression, options?: CircleMarkerOptions): CircleMarker;
>  
> -export interface CircleOptions extends PathOptions {
> -    radius: number | undefined;
> -}
> +export type CircleOptions = CircleMarkerOptions;
>  
>  export class Circle<P = any> extends CircleMarker<P> {
> -    constructor(latlng: LatLngExpression, options?: CircleOptions);
> +    constructor(latlng: LatLngExpression, options: CircleOptions);
>      constructor(latlng: LatLngExpression, radius: number, options?: CircleOptions); // deprecated!
>      toGeoJSON(precision?: number | false): any;
>      getBounds(): LatLngBounds;
> @@ -2114,8 +2112,8 @@ export class Circle<P = any> extends CircleMarker<P> {
>      setStyle(style: PathOptions): this;
>  }
>  
> -export function circle(latlng: LatLngExpression, options?: CircleMarkerOptions): Circle;
> -export function circle(latlng: LatLngExpression, radius: number, options?: CircleMarkerOptions): Circle; // deprecated!
> +export function circle(latlng: LatLngExpression, options: CircleOptions): Circle;
> +export function circle(latlng: LatLngExpression, radius: number, options?: CircleOptions): Circle; // deprecated!
>  
>  export interface RendererOptions extends LayerOptions {
>      padding?: number | undefined;
> diff --git a/types/leaflet/leaflet-tests.ts b/types/leaflet/leaflet-tests.ts
> index 4a7254c3a9..e27cff7a0d 100644
> --- a/types/leaflet/leaflet-tests.ts
> +++ b/types/leaflet/leaflet-tests.ts
> @@ -990,3 +990,17 @@ L.GeoJSON.geometryToLayer(
>          },
>      },
>  );
> +
> +let circle = new L.Circle(latLng, 10);
> +circle = new L.Circle(latLng, { radius: 10 });
> +// @ts-expect-error
> +circle = new L.Circle(latLng, { radius: undefined });
> +// @ts-expect-error
> +circle = new L.Circle(latLng, { radius: null });
> +// @ts-expect-error
> +circle = new L.Circle(latLng, { radius: '10' });
> +// @ts-expect-error
> +circle = new L.Circle(latLng, { });
> +// @ts-expect-error
> +circle = new L.Circle(latLng);
> ```

I've changed everything you provided, but the tests seem to fail on some ```Portal type```. I've never contributed or written tests for anything, so I apologise for making rookie mistakes. I just wanted to help out. Could you please explain this issue and how to fix it? Thank you so much. I'd want to make this PR to the end and any help is useful for me.

2024-04-02 18:03 UTC, someonewithpc commented
> I've never contributed or written tests for anything, so I apologise for making rookie mistakes. I just wanted to help out. Could you please explain this issue and how to fix it? Thank you so much. I'd want to make this PR to the end and any help is useful for me.

I'm sorry if I came across as mean, earlier. There's no need to apologize, you didn't do anything wrong. Making mistakes is normal, and everyone has to start somewhere. I'd recommend you to run the tests locally, next time, that way no one knows if you make any mistake ;) I'd also encourage you learn `git rebase -i` (and `git reflog`) to learn how to squash multiple commits into one.  hmu by email if you need help 

> I've changed everything you provided, but the tests seem to fail on some `Portal type`. 

To fix that error, you can run the following command (I recommend taking the time to understand what each piece of the command does) to apply a patch to `iitc`. We'll have to see if the maintainers of that package agree with this change, as I'm not familiar with it

```
$ git -C $(git rev-parse --show-toplevel) apply <<EOF
diff --git a/types/iitc/core/iitctypes.d.ts b/types/iitc/core/iitctypes.d.ts
index 207cd1bf81..6dab822329 100644
--- a/types/iitc/core/iitctypes.d.ts
+++ b/types/iitc/core/iitctypes.d.ts
@@ -12,7 +12,7 @@ export namespace IITC {
         options: PortalOptions;
     }
 
-    interface PortalOptions extends L.PathOptions {
+    interface PortalOptions extends L.CircleMarkerOptions {
         guid: PortalGUID;
         ent: any;
         level: number;
EOF
```

2024-04-02 19:16 UTC, Crakzzy commented
> > I've never contributed or written tests for anything, so I apologise for making rookie mistakes. I just wanted to help out. Could you please explain this issue and how to fix it? Thank you so much. I'd want to make this PR to the end and any help is useful for me.
> 
> I'm sorry if I came across as mean, earlier. There's no need to apologize, you didn't do anything wrong. Making mistakes is normal, and everyone has to start somewhere. I'd recommend you to run the tests locally, next time, that way no one knows if you make any mistake ;) I'd also encourage you learn `git rebase -i` (and `git reflog`) to learn how to squash multiple commits into one. hmu by email if you need help
> 
> > I've changed everything you provided, but the tests seem to fail on some `Portal type`.
> 
> To fix that error, you can run the following command (I recommend taking the time to understand what each piece of the command does) to apply a patch to `iitc`. We'll have to see if the maintainers of that package agree with this change, as I'm not familiar with it
> 
> ```
> $ git -C $(git rev-parse --show-toplevel) apply <<EOF
> diff --git a/types/iitc/core/iitctypes.d.ts b/types/iitc/core/iitctypes.d.ts
> index 207cd1bf81..6dab822329 100644
> --- a/types/iitc/core/iitctypes.d.ts
> +++ b/types/iitc/core/iitctypes.d.ts
> @@ -12,7 +12,7 @@ export namespace IITC {
>          options: PortalOptions;
>      }
>  
> -    interface PortalOptions extends L.PathOptions {
> +    interface PortalOptions extends L.CircleMarkerOptions {
>          guid: PortalGUID;
>          ent: any;
>          level: number;
> EOF
> ```

No, you didn't. The change you provided helped to fix the error. Although that error is fixed there are still 2 more. In the tests you provided earlier these two still don't throw an error: 
```
// @ts-expect-error
circle = new L.Circle(latLng, {radius: undefined});
// @ts-expect-error
circle = new L.Circle(latLng, {radius: null});
```
And the remaining ones do. I'm not sure why only *null* and *undefined* do this. Am I missing something 😄? And I know how to use the interactive rebase for squashing the commit. I will do it at the end to clean out the PR. Again thanks for your response and could you please let me know why is this happening?

2024-04-02 19:22 UTC, someonewithpc commented
> I'm not sure why only _null_ and _undefined_ do this

With the `strictNullChecks` compiler option set to `false` as it is currently, _all_ types `T` are actually `T | undefined | null`, which is why I said this should wait for #69238 Though, it could go before, if we remove those two test lines from this and add it to the other, which is probably better, in this case, so if you could, please remove those two tests and clean it up and I'll merge it

2024-04-02 19:33 UTC, Crakzzy commented
> > I'm not sure why only _null_ and _undefined_ do this
> 
> With the `strictNullChecks` compiler option set to `false` as it is currently, _all_ types `T` are actually `T | undefined | null`, which is why I said this should wait for #69238 Though, it could go before, if we remove those two test lines from this and add it to the other, which is probably better, in this case, so if you could, please remove those two tests and clean it up and I'll merge it 
> 

If you don't mind, I will do it tomorrow morning. And thanks for the explanation 👍

2024-04-03 13:40 UTC, Crakzzy commented
@someonewithpc 
Now it should be cleaned up and ready to merge 👍

2024-04-03 16:04 UTC, someonewithpc approved these changes

2024-04-03 16:08 UTC, someonewithpc commented
@McBen This also changes `iitc`, could you review this?

2024-04-03 16:44 UTC, henrythasler approved these changes
Good job adding the tests.

2024-04-03 16:52 UTC, Crakzzy commented
> Good job adding the tests.

Thanks, but @someonewithpc really helped me. I've never written any tests so I've learned something new 👍.

2024-04-03 16:52 UTC, Crakzzy commented
Ready to merge

2024-04-03 16:53 UTC, merged

2024-04-08 20:47 UTC, someonewithpc commented
> IITC uses old Leaflet v0.77

This package [provides types for v0.7](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/leaflet/v0/index.d.ts), though I don't know and dont want to bother checking whether that preceeded your package 

> I'm not sure if old leaflet types already included the CircleMarkerOption.

It seems it didn't, which would explain why you wrote it like that

2024-04-11 09:49 UTC, lmachens commented
@Crakzzy 
There is an issue with the `setStyle` method, which requires `radius` now. It should be still optional in `setStyle`.

2024-04-11 19:18 UTC, Crakzzy commented
> @Crakzzy There is an issue with the `setStyle` method, which requires `radius` now. It should be still optional in `setStyle`.

@lmachens 
I see, my suggestion is to leave the CircleMarkerOptions as they are now with the radius mandatory and create a new interface specifically for the setStyle option which will be the same as the CircleMarkerOptions with the difference of radius being optional. Something like this: 
```typescript
export interface CircleMarkerStyleOptions extends PathOptions {
    radius?: number | undefined;
}
```
And then:
```typescript
- setStyle(options: CircleMarkerOptions): this;
+ setStyle(options: CircleMarkerStyleOptions): this;
```

Or if you have a better idea, let me know 😃.