added type definitions for libsodium-wrappers crypto_aead_aegis functions and constants
DefinitelyTyped/DefinitelyTyped pull request #69226
Opened 2024-04-01 01:30 UTC by bschick

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change. -> Tests a very minimal, did not expand. tested in an seperate project
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`]  -> hitting  ENFILE: file table overflow, scandir

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/jedisct1/libsodium.js/tree/master/wrapper/symbols
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`  ->  looks invalid already... didn't change

2024-04-02 05:17 UTC, ffflorian requested changes

2024-04-02 05:17 UTC, ffflorian commented on types/libsodium-wrappers/index.d.ts
> +export function crypto_aead_aegis256_encrypt(
```suggestion

export function crypto_aead_aegis256_encrypt(
```

2024-04-02 05:17 UTC, ffflorian commented on types/libsodium-wrappers/index.d.ts
> +export function crypto_aead_aegis256_decrypt_detached(
```suggestion

export function crypto_aead_aegis256_decrypt_detached(
```

2024-04-02 05:17 UTC, ffflorian commented on types/libsodium-wrappers/index.d.ts
> +export function crypto_aead_aegis256_encrypt_detached(
```suggestion

export function crypto_aead_aegis256_encrypt_detached(
```

2024-04-03 09:27 UTC, ffflorian approved these changes
Thanks!

2024-04-07 03:26 UTC, bschick commented
Ready to merge

2024-04-07 03:27 UTC, merged