Add the makeBuffer interface to lz4js
DefinitelyTyped/DefinitelyTyped pull request #69228
Opened 2024-04-01 02:34 UTC by hu0529

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-04-01 02:35 UTC, hu0529 commented
Add the makeBuffer interface to lz4js

2024-04-01 02:38 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/lz4js/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 4ad8da8363392fc2ce07a938644133378c653b95
</p>

2024-04-01 02:39 UTC, hu0529 commented
> ## Formatting
> The following files are not formatted:
> 
> 1. types/lz4js/index.d.ts
> 
> Consider running `pnpm dprint fmt` on these files to make review easier.
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [4ad8da8](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4ad8da8363392fc2ce07a938644133378c653b95)

Running pnpm dprint fmt has been executed

2024-04-03 16:54 UTC, RyanCavanaugh requested changes

2024-04-03 16:54 UTC, RyanCavanaugh commented on types/lz4js/index.d.ts
> -    sIndex: number,
Undo unrelated formatting change

2024-04-04 19:32 UTC, RyanCavanaugh requested changes
Blocking PRs from both authors pending https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69172#issuecomment-2035417345

2024-04-09 20:47 UTC, peterblazejewicz approved these changes

2024-04-10 02:18 UTC, hu0529 commented
Ready to merge

2024-04-10 02:18 UTC, merged