Update index.d.ts
DefinitelyTyped/DefinitelyTyped pull request #69345
Opened 2024-04-13 13:16 UTC by huseeiin

this fixes:
```ts
import cookie from "cookie";

console.log(cookie.parse("hello=world").world);
```
now `world` is `string | undefined` instead of always `string`

2024-04-15 01:17 UTC, pine approved these changes

2024-04-15 01:22 UTC, pine commented
Hello @huseeiin.
I think that your changes is good, but could you please change the test code below accordingly?
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7730e3a69ed2f43bd990ab69bad23b0da742c41/types/cookie/cookie-tests.ts#L15

Thank you.

2024-04-15 11:05 UTC, huseeiin commented
> Hello @huseeiin. ~I think that your changes is good, but could you please change the test code below accordingly?~
> 
> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f7730e3a69ed2f43bd990ab69bad23b0da742c41/types/cookie/cookie-tests.ts#L15
> 
> I'm sorry, you have already fixed fixed tests in #69346 , right? However, it is better to fix in THIS pull request.
> 
> Thank you.

I'm new to github. how do i add a new commit to this pull request?

2024-04-16 01:17 UTC, pine approved these changes

2024-04-16 18:20 UTC, andrewbranch requested changes
Thanks @huseeiin for your contribution, but I don’t think this change should be merged. Users can enable `--noUncheckedIndexedAccess` for themselves if they want this stricter behavior. It might have been a good idea for this return type to be `Record<string, string | undefined>` from the beginning, but changing it now for such a widely depended upon package would be too disruptive. These typings get almost 10 million downloads a week and probably all those people would get broken from a patch version bump.

2024-04-16 18:20 UTC, closed without merging