Add Beacon transport type
DefinitelyTyped/DefinitelyTyped pull request #69481
Opened 2024-04-30 19:25 UTC by tomasdev

This is very poorly documented so it has been missed.

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-04-30 19:28 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/gtag.js/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 07483c7b6f633daa46daa3137021f6f0c21cd79f
</p>

2024-05-06 16:51 UTC, jakebailey commented
The link you have in the PR goes to an error page, so this can't really be confirmed.

2024-05-06 19:20 UTC, tomasdev commented
Uh? Are you behind some sort of VPN?
<img width="2166" alt="Screenshot 2024-05-06 at 3 20 33 PM" src="https://github.com/DefinitelyTyped/DefinitelyTyped/assets/364033/ad747d5f-e274-45bf-b0b9-7d7bd64a4901">

2024-05-06 19:25 UTC, jakebailey commented
Must have been a temporary problem, weird.

2024-05-06 19:25 UTC, jakebailey commented on types/gtag.js/index.d.ts
> +        transport_type?: 'beacon' | undefined;
The docs imply this could be `image` or `xhr`, right?

2024-05-16 16:47 UTC, sandersn requested changes
Requesting changes so the bot knows the current status.

2024-05-16 17:08 UTC, tomasdev commented
Done!

2024-05-16 17:12 UTC, sandersn approved these changes

2024-05-26 19:23 UTC, KsAkira10 commented
LGTM!

2024-05-31 17:02 UTC, merged