[@types/multicoin-address-validator] Improve types for networkType
DefinitelyTyped/DefinitelyTyped pull request #69533
Opened 2024-05-06 14:01 UTC by alishi973

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).
- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://www.npmjs.com/package/multicoin-address-validator#parameters>>

2024-05-06 14:04 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/multicoin-address-validator/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e81d6d277cb9687e3478111612ce47490fdf4f78
</p>

2024-05-06 22:22 UTC, kylemclean requested changes

2024-05-06 22:22 UTC, kylemclean commented on types/multicoin-address-validator/index.d.ts
> +export type NetworkType = "prod" | "testnet" | "both";
It looks like at least one other value, `"stagenet"`, is possible.

https://github.com/christsim/multicoin-address-validator/blob/d5f41ba84e0b5e5f7e30a8b303561a68992b8874/src/monero_validator.js#L24

2024-05-08 21:43 UTC, kylemclean approved these changes

2024-05-09 20:16 UTC, peterblazejewicz approved these changes
@alishi973 thanks!

2024-05-14 15:10 UTC, alishi973 commented
Ready to merge

2024-05-14 15:11 UTC, merged