Add isLicensePlate and isLuhnNumber interface definitions to @ types/validator
DefinitelyTyped/DefinitelyTyped pull request #69545
Opened 2024-05-07 12:10 UTC by xiaoxizi2303

Add isLicensePlate and isLuhnNumber interface definitions to @ types/validator

2024-05-07 12:15 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/validator/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 3b5fae49d04b8fae75c662fa9119fa2424167db9
</p>

2024-05-07 12:45 UTC, codershiba commented on types/validator/index.d.ts
> +     * check if the string passes the Luhn algorithm check.
```suggestion
     * Check if the string passes the [Luhn algorithm check](https://en.m.wikipedia.org/wiki/Luhn_algorithm).
```

2024-05-07 12:47 UTC, codershiba commented on types/validator/index.d.ts
> +    export function isLicensePlate(str: string, locale:string): boolean;
```suggestion
    export function isLicensePlate(str: string, locale: 'cs-CZ' | 'de-DE' | 'de-LI' | 'en-IN' | 'es-AR' | 'hu-HU' | 'pt-BR' | 'pt-PT' | 'sq-AL' | 'sv-SE' | 'any'): boolean;
```

2024-05-07 12:49 UTC, codershiba requested changes
Please address comments

2024-05-08 10:51 UTC, xiaoxizi2303 commented on types/validator/index.d.ts
> +     * check if the string passes the Luhn algorithm check.
Modified

2024-05-08 10:51 UTC, xiaoxizi2303 commented on types/validator/index.d.ts
> +     * check if the string matches the format of a country's license plate.
Modified

2024-05-08 10:51 UTC, xiaoxizi2303 commented on types/validator/index.d.ts
> +    export function isLicensePlate(str: string, locale:string): boolean;
Modified

2024-05-08 12:21 UTC, codershiba approved these changes

2024-05-08 15:36 UTC, jakebailey approved these changes

2024-05-11 06:29 UTC, xiaoxizi2303 commented
Hi, when will this pr be incorporated?

2024-05-11 06:47 UTC, jakebailey commented
You can merge the PR yourself by following the instructions above.

2024-05-11 09:27 UTC, xiaoxizi2303 commented
Ready to merge

2024-05-11 09:28 UTC, merged