Added @tonic-ui/react__icons and updated @tonic-ui/react types for v2
DefinitelyTyped/DefinitelyTyped pull request #69688
Opened 2024-05-27 14:21 UTC by ZachLegros

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-05-27 14:28 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/tonic-ui__react-icons/scripts/generate-definitions/tsconfig.json
1. types/tonic-ui__react-icons/tonic-ui__react-icons-tests.tsx
1. types/tonic-ui__react-icons/index.d.ts
1. types/tonic-ui__react-icons/scripts/generate-definitions/index.ts
1. types/tonic-ui__react/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 67af91181c42756e0c5f381fe3a63ae40167b88e
</p>

2024-05-27 15:48 UTC, derekhawker approved these changes

2024-05-29 17:01 UTC, sheetalkamat requested changes

2024-05-29 17:21 UTC, ZachLegros commented on types/tonic-ui__react-icons/scripts/generate-definitions/package.json
> +        "@trendmicro/tmicon": "1.40.0"
This is a script `package.json` and it looks like other `@types` packages are allowed to add dev dependencies. For example, here is the `@types/node` package using external packages: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0b234975014c1da99b60104b8e5febb7fbcada38/types/node/scripts/generate-docs/package.json#L11

2024-05-29 17:33 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/tonic-ui__react/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f6db9a93d51fa6f457e302edc6120976285533f8
</p>

2024-05-30 17:07 UTC, jakebailey commented on types/tonic-ui__react-icons/scripts/generate-definitions/package.json
> +        "@trendmicro/tmicon": "1.40.0"
For now, this is fine.

2024-05-30 17:07 UTC, sheetalkamat requested changes

2024-05-30 17:07 UTC, sheetalkamat commented on types/tonic-ui__react-icons/scripts/generate-definitions/.eslintrc.json
> +{
Please remove and fix errors

2024-05-30 19:41 UTC, sheetalkamat approved these changes

2024-05-30 20:04 UTC, ZachLegros commented
Ready to merge

2024-05-30 20:04 UTC, merged