[@types/picomatch] Add new `windows` options field
DefinitelyTyped/DefinitelyTyped pull request #69904
Opened 2024-06-25 12:14 UTC by sergeiivankov

See https://github.com/micromatch/picomatch/blob/570df2f8781bc92e5fece2c16d9ff990c4a8d1da/CHANGELOG.md#200-2019-04-10

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/micromatch/picomatch/blob/570df2f8781bc92e5fece2c16d9ff990c4a8d1da/CHANGELOG.md#200-2019-04-10
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-07-05 18:16 UTC, iisaduan reviewed
From [here](https://github.com/micromatch/picomatch/blob/570df2f8781bc92e5fece2c16d9ff990c4a8d1da/CHANGELOG.md#breaking-changes) in the changelog, it looks like `unixify` is renamed to `windows` as opposed to windows being a new option. Is this type change correct?

Since the picomatch change log marks this as a breaking change, you could also add [versioning](https://github.com/DefinitelyTyped/DefinitelyTyped?tab=readme-ov-file#how-do-definitely-typed-package-versions-relate-to-versions-of-the-corresponding-library) to the types, if you are worried about supporting types for older versions.

2024-07-06 06:19 UTC, iisaduan requested changes
See above comment^

2024-07-08 19:30 UTC, iisaduan approved these changes

2024-07-09 14:26 UTC, sergeiivankov commented
Ready to merge

2024-07-09 14:27 UTC, merged