React mathml support
DefinitelyTyped/DefinitelyTyped pull request #69986
Opened 2024-07-04 01:46 UTC by louisscruz

Please fill in this template.

- [ ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-07-04 02:31 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/react/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against d960a9fbc6b8e027e7e33aaa06694b8db9bd9914
</p>

2024-07-06 22:39 UTC, louisscruz commented on types/react/index.d.ts
> +     * @see https://w3c.github.io/mathml-core/#semantics-and-presentation
This and the urls below should be `link`s like used elsewhere for better in-editor readability.

2024-07-08 07:34 UTC, eps1lon commented
Is there a spec for MathML? For HTML and SVG we follow the spec instead of what browsers implement and let users augment their types with non-standard elements/attributes.

2024-07-08 17:40 UTC, louisscruz commented
That makes sense. Yes, there are specifications. I added some more context on that in the PR description.

It ends up being that the Math WG is quite a bit older than I'd previously realized.... apparently, the group has been in operation for ~26 years! MDN describes the MathML standardization history as "erratic", and the Math WG describes MathML Core as "a subset that can be reliably displayed in web browsers". It seems like MathML Core is perhaps the thing to support instead of MathML (v3). [That seems to also be the route Chrome has taken](https://chromestatus.com/feature/5240822173794304).

2024-07-08 17:48 UTC, louisscruz commented
For now, I'll move forward with adjusting the PR to support the MathML Core specification. I'll take a pass in the next few days.

2024-07-17 03:13 UTC, louisscruz commented
Sorry for delay here, planning to take a look this week (and push up some changes).

2024-08-06 19:48 UTC, sheetalkamat requested changes
Please address feedback

2024-09-07 01:03 UTC, closed without merging

2024-11-16 22:42 UTC, louisscruz commented
Ah, I'd forgotten about this PR! I'm planning to continue this proposed addition over in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71187