yargs: Add the ArgvFromBuilder type that is useful when using command modules
DefinitelyTyped/DefinitelyTyped pull request #70005
Opened 2024-07-08 18:53 UTC by segevfiner

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yargs/yargs/blob/main/docs/advanced.md#commanddirdirectory-opts
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

This can be used like this:
```ts
import type { ArgumentsCamelCase, Argv, ArgvFromBuilder } from 'yargs';

export const command = 'foo';

export const desc = 'Does foo!';

export function builder(args: Argv) {
  return args.option('bar', { type: 'number' });
}

export function handler(argv: ArgvFromBuilder<typeof builder>) {
  console.log('bar:', argv.bar); // <-- argv.bar will be properly typed, at least as much as when declared directly using `command('foo', 'Does foo!', (yargs) => { ... }, (argv) => { ... })`
}
```

Do let me know if I defined that type correctly. TypeScript type manipulations like this are always quite a handful...

2024-07-08 18:57 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/yargs/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9e87b322b94b3bbd8723a052e4b9bc909815d853
</p>

2024-07-10 13:42 UTC, forivall commented
IMO, this should be left inside of your code instead of bringing it into the `yargs` typings. Otherwise, the type itself looks good, but I'd go with the name `BuilderArguments` or `BuilderArgumentsType` as those names are closer to the typescript builtin names of `Parameters` and `ReturnType`. Also `Argv` is specifically for the `yargs.Argv` api object, but this type is extracting the `Arguments` type.

2024-07-10 13:57 UTC, segevfiner commented
Because its kinda complex, I'd rather it will be available for others and the best place seems to be here... I'll rename later

2024-07-20 15:48 UTC, forivall requested changes
Needs tests

2024-08-05 20:01 UTC, forivall approved these changes

2024-08-05 20:01 UTC, forivall commented on types/yargs/yargs-tests.ts
> +        argv.a;
Could have an `$ExpectType` assertion here.

2024-08-06 16:14 UTC, forivall approved these changes

2024-08-06 19:49 UTC, sheetalkamat approved these changes

2024-08-06 19:50 UTC, segevfiner commented
Ready to merge

2024-08-06 19:51 UTC, merged