[@types/pg] Add Client to PoolConfig
DefinitelyTyped/DefinitelyTyped pull request #70196
Opened 2024-08-02 10:47 UTC by alexgraul

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: 

`Client` on `PoolConfig`: https://github.com/brianc/node-postgres/tree/master/packages/pg-pool#create

2024-08-02 10:51 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/pg/index.d.ts
1. types/pg/pg-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 87a03a00ff1dfb1137b8bb5d43fd87890f69be5e
</p>

2024-08-13 14:48 UTC, pspeter3 commented
LGTM

2024-08-24 01:21 UTC, gabritto requested changes

2024-08-24 01:21 UTC, gabritto commented on types/pg/index.d.ts
> +    Client?: new() => ClientBase | undefined;
Perhaps you meant:
```suggestion
    Client?: (new () => ClientBase) | undefined;
```

2024-08-27 04:29 UTC, alexgraul commented
@gabritto good catch, thankyou! Fixed.

2024-08-27 18:19 UTC, gabritto approved these changes

2024-08-27 18:22 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/pg/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6c3b9935cbee4d331781e96794d8573ab0559ee6
</p>

2024-08-28 01:54 UTC, alexgraul commented
Ready to merge

2024-08-28 01:55 UTC, merged