[react] improve act() return value
DefinitelyTyped/DefinitelyTyped pull request #70337
Opened 2024-08-20 17:41 UTC by henryqdineen

This PR updates the React `act()` return type to be more accurate based on the [actual implementation](https://github.com/facebook/react/blob/92d26c8e93a88ca41338d3509b4324ad19a89c1e/packages/react/src/ReactAct.js). The function does not return a `Promise` and instead returns a `Thenable`-like object. This fix will prevent TypeScript from allowing code that will  break at runtime (e.g `act(...).then().catch()`). This should also prevent false positive floating promise lint warnings (e.g `act(...).then()`). 

I recognize that common `act()` usage tends not to run into these gotchas but we have a large codebase and have encountered them. This PR omits updating the deprecated `@types/react-dom` version of the `act()` types but that can be added if needed. 

One gotcha here is that since `act()` does not return a `PromiseLike<T>` it doesn't allow for code like this although it works at runtime

```
Promise.resolve().then(() => {
  return act(() => Promise.resolve()
});

```

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/facebook/react/blob/92d26c8e93a88ca41338d3509b4324ad19a89c1e/packages/react/src/ReactAct.js
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-08-20 20:07 UTC, eps1lon reviewed
That makes sense, thank you. Can you check if that's still assignable to a function taking a Promise? I'm not sure that still works but probably should.

2024-08-26 13:23 UTC, eps1lon commented
Then we can't merge this.

2024-08-26 13:23 UTC, eps1lon requested changes

2024-08-26 13:23 UTC, eps1lon commented on types/react/index.d.ts
> +    export function act<T>(callback: () => T | Promise<T>): ActThenable<T>;
This needs to be assignable to something accepting a Promise.

2024-08-27 17:37 UTC, henryqdineen commented
Understood. I guess this will just have to be a limitation of the types.

2024-08-27 20:17 UTC, eps1lon commented
It's likely that `act` will become fully async anyway and then we don't have to be sophisticated with the types.

2024-09-28 01:05 UTC, closed without merging