[react] Fix contextually inferred types of forwardRef arguments
DefinitelyTyped/DefinitelyTyped pull request #70361
Opened 2024-08-23 05:59 UTC by MichaelMitchell-at

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

TypeScript 5.5 introduced support for [isolated declarations](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/#isolated-declarations). Code that benefits from isolated declarations must explicitly annotate exported variables when the types can't be trivially inferred from syntax. This means that there will be an increased need for React components to be given explicit type annotations and greater usage of the utility types that `@types/react` provides.

One of the shortcomings I've come across is when using `forwardRef`, the inferred type of `props` incorrectly includes `ref`. This PR contains a fix for that.

Unfortunately, the representation of the type is suboptimal because the typing of `ForwardRefExoticComponent` doesn't separately take the prop type and ref type and requires you to pre-combine them as something like `ForwardRefExoticComponent<Props & React.RefAttributes<RefType>>`. In TypeScript, it's not generally possible to extract a type in an intersection back out of the intersection, which means that we can't pull `Props` out of `Props & React.RefAttributes<RefType>` with something like `extends infer TProps & React.RefAttributes<infer TRefType>`. Going forward, I would recommend providing a new utility type, `ForwardRefComponent<Props, RefType>` which preserves `Props`. That would also be an opportunity to deprecate `ForwardRefExoticComponent` whose name I've always found to be needlessly verbose and intimidating.

2024-08-29 12:26 UTC, eps1lon requested changes
Makes sense, thank you. Please include these changes in `types/react/ts5.0` as well.

2024-08-30 00:19 UTC, gabritto approved these changes

2024-08-30 09:45 UTC, MichaelMitchell-at commented
Ready to merge

2024-08-30 09:45 UTC, merged

2024-09-03 21:19 UTC, MattIPv4 commented
👋 Hey folks, didn't want to post a full issue right off the bat, but wanted to flag that this seems to have broken our current approach to polymorphic forwardRef typings -- would appreciate any thoughts on getting around the new error: [TS playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHVaIpGiEoBICCICuQpASLoY+OAG99cd5ktMYwCAziY0OqmIsiYADwAKgA0cAAKcAC8LgC+AHwAFG7uOTlEDIZQAFyIEgB0AGJBIWHIBUhQFV4YvgxRsXFp0dk5AJQlyA6V1VChSJgAogAeED5oAMK4kAxsMOGDGGVxOGA8AOrAKhCWMGHhnXAAZKVDYQCCMDBQwABGJ0g8UWlpFDRwKZQGChWDwwOhbHFhJJzFAwMpgGgXOR3EgppBYEppBCoTC4QizvM4KiYGwRIoNjAyhMbKx2JEsWkkjdNotwH5VtsILsDioCWkANqEcb4AC6FGRRLR0CkYGxQmh0DxaE5u3ChOJpPJ5WpSFpMHpso6kpJBUUEBeACsjPBkshmKNwnxnvJYisAG4Nb5MillVnLDk7faHZTHU7jNWM64Ja7OOAoHgAfhKhJS4pRUoxMCx8RxivhysDPOUBONmuZlJ1eoNSCNGtNgkt1u9RmgIkdT1kcldSA9UC9yUh8tx+ZVn3mHUjLnEmCTOaHefx4fmjNTlHT6JltgpyBglig-ltSF3++r621MzmfvZ7B+a8lG8xsvLADlgbombH+Vo4LI4DpJBAmDlmUr6sCI0yzAiV4rOwIoDOUoG6BBl5LNeMBfiK-wUAC5BAiCYJoLY0GrEi7h-NMkA8LYKi2IYmAoNYWDQHGDCSHAzBsjBMCKCoahwOoUAoGASjwjwErMAwfDsahXEACLjAxQg2gQKBkBKqIPlmT7Eew8n0YxTJaUggHSZxqx6YpMBpo+RHQEgOkwKOH4Su4yhIEIQgQLOTqdhKOFkbQFEQFRIm2GAgYBMxKCsaZ-rsDxqgaIJwkqMAYkBXAey2OghFgBwbnsZYfC4HA4VcjwsQ0XAQI+B6cAABKRAAsgAMqVEUZJA86wvmvSxNFYgoNOcCdbmPUIr06kZpucAOaOaqlvWPqVqs1aMgOY1Klsm0joWwYErEixEHNga3hKfwAPK9s8hihTZkVQHdHFxfAPBcOothoNFcZgGA8p3XIbANAi93qMGd10ZZEpGbNMkkckGQLXWZLAStdLZskDkWYxmRlbsyZw+w83Lr0SSMoOCrjWgZTbkee4MKTUY7QiNMSIhIgUOu0rSZJ8AOQTZnsM2QyBFAwSjGEWS5EjUwmijy00qtGOw4LMDY0pmQuTkri5Lk8bdLrORuR5EAG4bcBlJbePpbrKQCy9xNdFr7hEDOJQU8OLMewuaB8lrpOJIyOu6xJUkOUy8ZwAAPlHsVoerVnOzzb02GUnlyBkxueb01m5EQx7+GqhPwK7iTOK7KQuJbZTW5XVC3rkALuDnEoOWUIhpX9KCSIhTL4A5ak4XhHwEbYezJbKj3BzDR1IOPQmT05yTB+4mhQKI3kdvInP-HefxZXGaC5fln1FZweDW5VBUCQv77PWh7XlSNYMqADQPPIiYI8DwAC0Kg4JYOQyg+osTEFVGqwA6qNVao-XYcAADU05obZnnr9BoxNFry21IrdGsp1rAROuVIsZx8AdzdPgScs9UGLwijGOOXF7ZoV9MXR2WE960Cug0G61ECow1Fk9YucA3r8U+t9Be-0qqAxWB-UG4NIYGQyPwqqN80FiHvlxSa7gYbUIaEyRG6pZZlgVrqJWT5MbF2YarBOuNAwlB0VAR2AdybM2prTAujM5yUy2hSdmO8NLc1DvAexdiJ66MPCLEYYxMBSxyDLOWWohho31MrNuWMFI4xibkFeus16iDNobdRqx8m62rtbJOdtMqhIcYGCMxSXbjFnD6KoYsQi6DONAlqslIFJLSP7MmpEQ5+BTkgNOEAM65JEC3JO+d6YjSTu4cIZDpxlwrlXK2gZ0jzNiakwRzhq6FPYHXXp5s4DhCoGQ45usW6NwlNcypt8oDt07iYHub4+72MHpQQJSgPjKQyE4gZ3zXYJ2FpsIqSB2nNRancJgIYoA9IyAwawQg7lAvGAAIROJwA8wFwWQtapix4fgEVIo8lM+pBc5nS0udLHZqtlnl3GAnSuyhS4ACISR8DZXAeuSci6q0sS9OMPBEhsreEShg3LS6MswIS7FLL2WcpgNy+uPLaAAGUQzWDEFw5ifg4CsvGHeaW9iyj2PoasMusZDWYBKBy353KUhHL5aa81ByYBWuFXa8V2K2WxBtXapVjqjlqrgJq44ogiRQBwI9fVNqtZnMuZNVcQA)

2024-09-03 21:40 UTC, MichaelMitchell-at commented
> 👋 Hey folks, didn't want to post a full issue right off the bat, but wanted to flag that this seems to have broken our current approach to polymorphic forwardRef typings -- would appreciate any thoughts on getting around the new error: [TS playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHVaIpGiEoBICCICuQpASLoY+OAG99cd5ktMYwCAziY0OqmIsiYADwAKgA0cAAKcAC8LgC+AHwAFG7uOTlEDIZQAFyIEgB0AGJBIWHIBUhQFV4YvgxRsXFp0dk5AJQlyA6V1VChSJgAogAeED5oAMK4kAxsMOGDGGVxOGA8AOrAKhCWMGHhnXAAZKVDYQCCMDBQwABGJ0g8UWlpFDRwKZQGChWDwwOhbHFhJJzFAwMpgGgXOR3EgppBYEppBCoTC4QizvM4KiYGwRIoNjAyhMbKx2JEsWkkjdNotwH5VtsILsDioCWkANqEcb4AC6FGRRLR0CkYGxQmh0DxaE5u3ChOJpPJ5WpSFpMHpso6kpJBUUEBeACsjPBkshmKNwnxnvJYisAG4Nb5MillVnLDk7faHZTHU7jNWM64Ja7OOAoHgAfhKhJS4pRUoxMCx8RxivhysDPOUBONmuZlJ1eoNSCNGtNgkt1u9RmgIkdT1kcldSA9UC9yUh8tx+ZVn3mHUjLnEmCTOaHefx4fmjNTlHT6JltgpyBglig-ltSF3++r621MzmfvZ7B+a8lG8xsvLADlgbombH+Vo4LI4DpJBAmDlmUr6sCI0yzAiV4rOwIoDOUoG6BBl5LNeMBfiK-wUAC5BAiCYJoLY0GrEi7h-NMkA8LYKi2IYmAoNYWDQHGDCSHAzBsjBMCKCoahwOoUAoGASjwjwErMAwfDsahXEACLjAxQg2gQKBkBKqIPlmT7Eew8n0YxTJaUggHSZxqx6YpMBpo+RHQEgOkwKOH4Su4yhIEIQgQLOTqdhKOFkbQFEQFRIm2GAgYBMxKCsaZ-rsDxqgaIJwkqMAYkBXAey2OghFgBwbnsZYfC4HA4VcjwsQ0XAQI+B6cAABKRAAsgAMqVEUZJA86wvmvSxNFYgoNOcCdbmPUIr06kZpucAOaOaqlvWPqVqs1aMgOY1Klsm0joWwYErEixEHNga3hKfwAPK9s8hihTZkVQHdHFxfAPBcOothoNFcZgGA8p3XIbANAi93qMGd10ZZEpGbNMkkckGQLXWZLAStdLZskDkWYxmRlbsyZw+w83Lr0SSMoOCrjWgZTbkee4MKTUY7QiNMSIhIgUOu0rSZJ8AOQTZnsM2QyBFAwSjGEWS5EjUwmijy00qtGOw4LMDY0pmQuTkri5Lk8bdLrORuR5EAG4bcBlJbePpbrKQCy9xNdFr7hEDOJQU8OLMewuaB8lrpOJIyOu6xJUkOUy8ZwAAPlHsVoerVnOzzb02GUnlyBkxueb01m5EQx7+GqhPwK7iTOK7KQuJbZTW5XVC3rkALuDnEoOWUIhpX9KCSIhTL4A5ak4XhHwEbYezJbKj3BzDR1IOPQmT05yTB+4mhQKI3kdvInP-HefxZXGaC5fln1FZweDW5VBUCQv77PWh7XlSNYMqADQPPIiYI8DwAC0Kg4JYOQyg+osTEFVGqwA6qNVao-XYcAADU05obZnnr9BoxNFry21IrdGsp1rAROuVIsZx8AdzdPgScs9UGLwijGOOXF7ZoV9MXR2WE960Cug0G61ECow1Fk9YucA3r8U+t9Be-0qqAxWB-UG4NIYGQyPwqqN80FiHvlxSa7gYbUIaEyRG6pZZlgVrqJWT5MbF2YarBOuNAwlB0VAR2AdybM2prTAujM5yUy2hSdmO8NLc1DvAexdiJ66MPCLEYYxMBSxyDLOWWohho31MrNuWMFI4xibkFeus16iDNobdRqx8m62rtbJOdtMqhIcYGCMxSXbjFnD6KoYsQi6DONAlqslIFJLSP7MmpEQ5+BTkgNOEAM65JEC3JO+d6YjSTu4cIZDpxlwrlXK2gZ0jzNiakwRzhq6FPYHXXp5s4DhCoGQ45usW6NwlNcypt8oDt07iYHub4+72MHpQQJSgPjKQyE4gZ3zXYJ2FpsIqSB2nNRancJgIYoA9IyAwawQg7lAvGAAIROJwA8wFwWQtapix4fgEVIo8lM+pBc5nS0udLHZqtlnl3GAnSuyhS4ACISR8DZXAeuSci6q0sS9OMPBEhsreEShg3LS6MswIS7FLL2WcpgNy+uPLaAAGUQzWDEFw5ifg4CsvGHeaW9iyj2PoasMusZDWYBKBy353KUhHL5aa81ByYBWuFXa8V2K2WxBtXapVjqjlqrgJq44ogiRQBwI9fVNqtZnMuZNVcQA)

One workaround I found is to pass type parameters to `React.forwardRef`, e.g. `export const Component: Component = React.forwardRef<HTMLElement>(`

2024-09-03 21:43 UTC, MattIPv4 commented
Hmm, I can't get that to behave in the playground I linked?

2024-09-03 21:56 UTC, MichaelMitchell-at commented
> Hmm, I can't get that to behave in the playground I linked?

Oh and also remove the default type parameter on the next line,
```ts
  export const Component: Component = React.forwardRef<HTMLElement>(
    <C extends React.ElementType>(
```
For more correctness you can also change `ComponentProps<C>` to `Polymorphic.PolymorphicProps<C, CoreComponentProps>` on line 43

2024-09-23 14:07 UTC, psd-coder commented
Proposed solution doesn't work for non-optional props. Just try to remove optional quantifier `?` from `hello` prop: [Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHVaIpGiEoBICCICuQpASLoY+OAG99cd5ktMYwCAziY0OqmIsiYADwAKgA0cAAKcAC8LgC+AHwAFG7uOTlEDIZQAFyIEgB0AGJBIWHIBUhQFV4YvgxRsXFp0dk5AJQlyA6V1VChSJgAogAeED5oAMK4kAxsMOGDGGVxOGA8AOrAKhCWMGHhnXAAZKVDYQCCMDBQwABGJ0g8UWlpFDRwKZQGChWDwwOhbHFhJJzFAwMpgGgXOR3EgppBYEppBCoTC4QizvM4KiYGwRIoNjAyhMbKx2JEsWkkjdNotwH5VtsILsDioCWkANqEcb4AC6FGRRLR0CkYGxQmh0DxaE5u3ChOJpPJ5WpSFpMHpso6kpJBUUEBeACsjPBkshmKNwnxnvJYisAG4Nb5MillVnLDk7faHZTHU7jNWM64Ja7OOAoHgAfhKhJS4pRUoxMCx8RxivhysDPOUBONmuZlJ1eoNSCNGtNgkt1u9RmgIkdT1kcldSA9UC9yUh8tx+ZVn3mHUjLnEmCTOaHefx4fmjNTlHT6JltgpyBglig-ltSF3++r621MzmfvZ7B+a8lG8xsvLADlgbombH+Vo4LI4DpJBAmDlmUr6sCI0yzAiV4rOwIoDOUoG6BBl5LNeMBfiK-wUAC5BAiCYJoLY0GrEi7h-NMkA8LYKi2IYmAoNYWDQHGDCSHAzBsjBMCKCoahwOoUAoGASjwjwErMAwfDsahXEACLjAxQg2gQKBkBKqIPlmT7Eew8n0YxTJaUggHSZxqx6YpMBpo+RHQEgOkwKOH4Su4yhIEIQgQCUTqdhKOFkbQFEQFRIm2GAgYBMxKCsaZ-rsDxqgaIJwkqMAYkBXAey2OghFgBwbnsZYfC4HA4VcjwsQ0XAQI+B6cAABKRAAsgAMqVEUZJA86wvmvSxNFYgoNOcCdbmPUIr06kZpucAOaOaqlvWPqVqs1aMgOY1Klsm0joWwYErEixEHNga3hKfwAPK9s8hihTZkVQHdHFxfAPBcOothoNFcZgGA8p3XIbANAi93qMGd10ZZEpGbNMkkckGQLXWZLAStdLZskDkWYxmRlbsyZw+w83Lr0SSMoOCrjWgZTbkee4MKTUY7QiNMSIhIgUOu0rSZJ8AOQTZnsM2QyBFAwSjGcjWtXcTAhlAaMwJkLlwEjUwmijy00qtDJZLk7iuHrOTxt0huue5nkm6bZTW3j6V6ykJQU8OLNOwuBblWqh12Sd5VdMr7hEDOjvM9TrtU3yyuk4kjIG3rElSQ5TLxnAAA+KexWh2NKZzcd+G9NhlJ5cgZG5HkQL01m5EQx7+GqhPwIHiTOIHKQuNbZS263VC3rkALuBXEoOWUIhpX9KCSIhTL4A5ak4XhHwEbYezJbKj2xzDR1IMvQmr05ySx+4mhQKIs4+fIOf+XAfxZXGaC5fln1FZweC25VBUCTv77PWh7XlSNYMqABkDZ4iIwQ8B4AAWhUDgSwchlB9RYmIKqNVgB1Slm1W2cAADU05obZm3r9BoxNFoa21FrdGsp1rAR9tyfa4Z8AjzdPgScm8CG7wijGDOXEBYvV9PXYmK5rKXWusAW6VUYaiyevXOAb1+KfW+jvf6VVAYrBAaDcGkMDIZEkVVD+hCxDfy4pNdwMM2ENCZIjdUasyya11NrJ8mN658MFjALOitOqBhKGYqAAio7kxDqzBwO56aMznJTLaFJ2Y5w0tzeO8BvFeJXuYw8IsRhjEwLrHIqt1ZaiGArasTIh5YwUjjTJuQD56yPqIS2htDGrBqXrdutt-b-ESZ-HxgYIwNIDuMWcPoqhixCLoSWzUWqyVQQrNIkcyakVzpJYQSBC4QGLlUkQA8WnV3piNFp7hwiMOnE3FubcbaBnSDsrJRTpHOHbnU9gXcpmmxVlQRhDy9YD17hKd5mUklQGHqPEwE83xT28bPSgcSlAfGUhkPxszwWBzccLTYRUkAjOlrLaAkyMgMGsEIL5cLxgACETicAPMBZFqKWpEseH4TF2KPLrJ6TXbZuRwivJZZclxBzm7jDca3ZQjcABEJI+ACqvmyi5TjE7xkSAKt41KGCisbtyzAVKSV8sFcKmAoru5X1oAAZRDNYMQDQcCPT8HAfl4w7wsu8WUbxXDVhN1jJazAJQhWQtFSke5LTwi2vtbcmATq4w8DdXKklArYgurdZqz19zdVwANccUQRIoCmsEP4F1ytwjd0+eQVcQA)

2024-10-02 19:10 UTC, OnkelTem commented
It broke our main `withForm()` HOCs. After adding `PropsWithoutRef<P>` wrapper, props cannot be inferred at all.

Please checkout this [Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDeAoOOAMWgHcUoATZAM2QDtKkoiBXejYCezAuABSgQwAZwDqwGAAsIrGLV6ESUclVoBRAB4QYwNAGEI4bknpY+tAIIwYUYACM5SEbwC+cGkJBwARFFQYPgDceHgwAJ5gSMTQIABqKAA2rM5wALyISGjQlAA8IrbA9ADm2Cj04QB8IWGR0RLSyiBNgsIi6bh83ADKrPYgkgBccAAUAJTplbiuITOhRTDMNOj1klJNAJL0AFZZi5Stop2EIn0DMMMj45NwAG4QwJQTAD5w7Ew0RUiUs6EA9H84GJLN1Qkw0IkKNEaOxONw4BBEpQAPrImhkCjUJA0XIAFWw-A6OFclRGfH8jGYw2UqixdFMTBYsN03DxBMqvDG1IxamxWh0ekMxnophguUO4jWsnk2PFUwAZJkaNZCo5FiI8ZVqqEYRwWfQEUjUaQ1k05dd8IR-DBWFADYiUWieXTcnxCAAJXEAWQAMk11IkkCBRYpCHAAPLncVwRUNdaxFpCUTYADWSHCEBoQNNsS2uww3wllT4pJGYCTIgmaSmlrD2XoBVwCPovX6kjg7gy5baITDcABfb7AD0APxuuDW20G3KUYC3fvawiuMa-PADgBC6n0li96mGMlIcBgEA8wE0cHb9AgpDHeHBkP8HmZXANItIqPRKkxtDZAiJJLJK0GSpGIv15elKSZPUX1-CU42lH9+C1TluTAul+V0AwjEgEUzHFCt4LkRCFSVFU7DVZxNW1HVn3hN9jRzKAQHNCZa0nO04Hop00J-cdPV9f1A2DMxQ0ISNJGjWNGOaWIJVTdNM2zRpcx2PZCwrYtCFLbtRCrGtx3rRscGbVtzg7DodJEXswwHQdCFHcd2OnWd5z+RcOxXPBXDwIA)


Do you folks know how to fix it?

2024-10-02 19:26 UTC, MichaelMitchell-at commented
> It broke our main `withForm()` HOCs. After adding `PropsWithoutRef<P>` wrapper, props cannot be inferred at all.
> 
> Please checkout this [Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDeAoOOAMWgHcUoATZAM2QDtKkoiBXejYCezAuABSgQwAZwDqwGAAsIrGLV6ESUclVoBRAB4QYwNAGEI4bknpY+tAIIwYUYACM5SEbwC+cGkJBwARFFQYPgDceHgwAJ5gSHAS0sog8YLCInAAvLh83ADKrPYgkgBccAAUAJRpAHy4riE1ocBmzDTo0bFS8QCS9ABWSBhIlEmiGYQiufkwRWWVcABuEMCUtaEA9CsxllmhTGgANhTRNOyc3HAQu5QA+pc0ZBTUSDQAPAAq2Pxp1RXFfP6MzEVlKoHnRTEwWMddNxXu8KrxSoC7mpHlodHpDMZ6KYYE8huJJDI5LRcVUAGSIR7WWwOJwiV4VCohPBHDhQ+hnC7XUgE+Ik6b4Qj+GCsKDs85XG5IkFPPiEAASLwAsgAZeLqXZIEDYxSEOAAeQmuLg5La8USQlE2AA1khwhAaDEedAQF1ev1BhaRBU+N9imBPeVUlUBbq0NwRPAcGd6Dk8pI4O50v7kiFdXA1mm0wA9AD8srgQpF7KelGAs3TjL4rlKyzwGYAQup9JZFeoijJSHAYBAPMBNHB4-QIKQ83gdvt-B5IVx2VjSNdbip7sS3gJPjhXN9fmCAcQpbQGOC2KyZzCBJ62rJ5I8SXC8Ai90vkTRUboDEZIFizLiLwSr8T+DJCkaCpOxHBgZx6UrZlp1OOcuSdKAQD5coQ0LUU4HgyUn2lfMFRVNUNS1MwdUIA1JCNE1EISZ08WtW17UdOJnVdPoII9ZJvUIX1k1EQNg3zMN6AjXBo1jCYE0+XiRFTXUM0zQhc3zdDi1LcsVkrQhq2WIA)
> 
> Do you folks know how to fix it?

[Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDGMA0cDeAoOOAMWgHcUoATZAM2QDtKkoiBXejYCezAuABSgQwAZwDqwGAAsIrGLV6ESUclVoBRAB4QYwNAGEI4bknpY+tAIIwYUYACM5SEbwC+cGkJBwARFFQYPgDceHgwAJ5gSMTQIABqKAA2rM5wALyISGjQlAA8IrbA9ADm2Cj04QB8IWGR0RLSyiBNgsIi6bh83ADKrPYgkgBccAAUAJTplbiuITOhRTDMNOj1klJNAJL0AFZZi5Stop2EIn0DMMMj45NwAG4QwJQTAD5w7Ew0RUiUs6EA9H84GJLN1Qkw0IkKNEaOxONw4BBEpQAPrImhkCjUJA0XIAFWw-A6OFclRGfH8jGYw2UqixdFMTBYsN03DxBMqvDG1IxamxWh0ekMxnophguUO4jWsnk2PFUwAZJkaNZCo5FiI8ZVqqEYRwWfQEUjUaQ1k05dd8IR-DBWFADYiUWieXTcnxCAAJXEAWQAMk11IkkCBRYpCHAAPLncVwRUNdaxFpCUTYADWSHCEBoQNNsS2uww3wllT4pJGYCTIgmaSmlrD2XoBVwCPovX6kjg7gy5baITDcABfb7AD0APxuuDW20G3KUYC3fvawiuMa-PADgBC6n0li96mGMlIcBgEA8wE0cHb9AgpDHeHBkP8HmZXANItIqPRKkxtDZAiJJLJK0GSpGIv15elKSZPUX1-CU42lH9+C1TluTAul+V0AwjEgEUzHFCt4LkRCFSVFU7DVZxNW1WoojgAARYACnIpxKEjSRfwAaTgJBNEWRh2kOZgIg49MpgyXFuN4hl2nYFMr1IA0RwjKN8TgDipmGEVbmYGpdThV8kHfZETUaWJzQmWtJztOA3w-Z0f3HT1fX9QNgzMUNCAYpiHBYtixUJWMcygZpYglVN00zbNTOCvM9kLCti0IUtu1EKsa3HetGxwZtW3ODsOhSkRezDAdB0IUdxys6dZ3nP5Fw7Fc8FcPAgA)

2024-10-02 23:03 UTC, OnkelTem commented
Thank you, Michael! <3

2024-12-04 00:00 UTC, codynova commented
Hi @MichaelMitchell-at, very sorry to ping you here directly - but as far as I can tell, this change has [broken polymorphic types](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHVaIpGiEoBICCICuQpASLoY+OAG99cd5ktMYwCAziY0OqmIsiYADwAKgA0cAAKcAC8LgC+AHwAFG7uOTlEDIZQAFyIEgB0AGJBIWHIBUhQFV4YvgxRsXFp0dk5AJQlyA6V1VChSJgAogAeED5oAMK4kAxsMOGDGGVxOGA8AOrAKhCWMGHhnXAAZKVDYQCCMDBQwABGJ0g8UWlpFDRwKZQkFNILAlNJbHFhJJzFAwMpgGgznceItwH5VnAgTA2CJFBsYGUJjZWOxIuC0kkbptUctVtsILsDiokSiluj2GkANqEcb4AC6FHIQJBUjAEKhMLhCPpu3C5HcyJp7PgWJxePKRKQJJgZLF3XcMsUqoKiggLwAVkZ4MlkMxRuE+M95LEVgA3BppcgUm3lJUrdiGpnKY6ncbhRVs-0wCnXQ1XFxwFA8AD8JQjaKj-0FwugovFQmh0ClaEDh2UZ3lcHTtPYmKm2JNVIJmu1uqQ+viOyN9bVggtVsptugIgdT1kchdSHdUE93viEqL8JLXfDrIzqw6XZjCaImFT84LkqXLL9qwpKWzwNzYLFTeQMEsUH8PofT7b6w1Mzmp45l5FN9sfEADkUFYMRkmcOBOS0OBZDgHRJAgTAmzKECwOmWYER-GA+QGco0N0DDv0jVZoL5LNASvUEYHBJsqigYJRkI4lVlXbC6wbXEUJbVY2znStq2VDjewQpC4AACUiABZAAZHjSRQOQCKklAwDgZMJOkuSWIUpTQKQFSwE5QSo3ItM1xrGBBUoSg-gAKgcxynOcpy4AAISTWw3IgKY4GYddaxcoKXMoZgGD4OAXh8gARcYUGsGB5OtAgRGAV0yEo-8aNvbyplizB4qERKdOS7KkDEqK8rihKksFMr3J8jyeCQOMIMrZghGgfdHXHStXVMYAUHYEoevkcgASFKi8waqZDTYkja2NLj8UJEq+MpSFD0XaUuyDE8FpgWJcqalqtzq2jcvY5IMnmgKVR7RsVqSttKVy-LCuKrUzwyMAuxKXK5pMs9eiSCl8XvR8GBB65gP0kQ-2vMKIty-6fKulDAgYmow3xejGMMEQkvCN7qqKpLviydxbss4THo1NbyUpnJXFydwkw7XIOugDmcn654hsOytcjKEXfoZHghf+EpNsLWEl0BizlSOxrPMNLpJd3fcZaPBF9ruz13BBxIKRZnIkfgdGkzgAAfa3Ipi0nPu1ChciIV9-HCdjd0SZxdxSFwRbKMXdn9qgfkrAFekFXKylSngwBMSQCMpfBcoymy3GCrOHLgJVmrEGTZBg-yaezrPQr8CKhCL96apKlOUHwSh6sLhgtFrsn6+SMqxOrtuO6d1Zm9o1utBO1qXErF5PJGscxvcIhUqIDB9yi4RUAYCgJpbouFfYpb1SGZ7yUpUfx67eMAZXIHf2H29R-Rm6b-uzjD82Y-b2SUeB-Jn6-rgUee8DppCNmDCQEMnzQybAReGmVEaV3gKPEoD8DqDnKJjfGZxcYjAJkTb+jtyaZErNTISB9uIMzFEQ3IptcjKF3DzBeuhgDL0FqzRMPAGFwEDsHCWuQUjSwXHLHa4sSFRliGfVWW4eaawEVtIRiIwzPwNnAUBk9XZIHdnAJmuRiY+XYT7K2tsCCN39s4bhXZQ7KMNi7f45Ao6UFHrHYA8dE7J2SPgUe6dbK0DLsFOAFRZAoCEH5VB2I+CKF8UFCu4UOAfGShkVRptzbiEwCTAqCU0FDEsM1M4klZLRTSr-Bg1ghD2PcMk3cuU7hMGDFATJmxslIFyVpapaBalFJKWUkJMSUnHROJwZ8KFGnNNkm5fpfgOlCFKTYip4x8HpKKvUgkwywx5Jkq09pJVMjFKmV02ZmBR4AEkQCKVsD6LJOTVlaWOacyZ0z2oIJSWfcZgyVorIiGssZjwJlbIyDs+5lY3aQy0ZLcIVici6N8t7X24w0kfX9nzQa7BEgACIwkwBRXAMOksqa5RST7SpPkNnQARQNAWqL0WYqTKilAmK6HjApXEzF2K2GQvxTC1JjUXmkv5sitFTL9EoreN8hgdLvb8r4MyikfwADKwZrBiAaDgOpfg4D0swJQVlo92W7nmfCuAiLyUSoxZFTyjLJVqvFZSrF4KqbauhbqouNy5BIB5UimA5qTXT2ap6qlPBUWgDkJingUA0C+ptTiuA4R7UMo5c8kVbqjXWu9UgcN1KhUvLFQy41UqsW0DlccUQmIoDKsEP4dVoKWUqPGhQIAA). I tried implementing your suggested changes above and didn't have much luck. Please let me know if you see a solution here, or a mistake I've made. For now we've pinned our React types to 18.3.4

[Tsplayground link](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHVaIpGiEoBICCICuQpASLoY+OAG99cd5ktMYwCAziY0OqmIsiYADwAKgA0cAAKcAC8LgC+AHwAFG7uOTlEDIZQAFyIEgB0AGJBIWHIBUhQFV4YvgxRsXFp0dk5AJQlyA6V1VChSJgAogAeED5oAMK4kAxsMOGDGGVxOGA8AOrAKhCWMGHhnXAAZKVDYQCCMDBQwABGJ0g8UWlpFDRwKZQkFNILAlNJbHFhJJzFAwMpgGgznceItwH5VnAgTA2CJFBsYGUJjZWOxIuC0kkbptUctVtsILsDiokSiluj2GkANqEcb4AC6FHIQJBUjAEKhMLhCPpu3C5HcyJp7PgWJxePKRKQJJgZLF3XcMsUqoKiggLwAVkZ4MlkMxRuE+M95LEVgA3BppcgUm3lJUrdiGpnKY6ncbhRVs-0wCnXQ1XFxwFA8AD8JQjaKj-0FwugovFQmh0ClaEDh2UZ3lcHTtPYmKm2JNVIJmu1uqQ+viOyN9bVggtVsptugIgdT1kchdSHdUE93viEqL8JLXfDrIzqw6XZjCaImFT84LkqXLL9qwpKWzwNzYLFTeQMEsUH8PofT7b6w1Mzmp45l5FN9sfEADkUFYMRkmcOBOS0OBZDgHRJAgTAmzKECwOmWYER-GA+QGco0N0DDv0jVZoL5LNASvUEYHBJsqigYJRkI4lVlXbC6wbXEUJbVY2znStq2VDjewQpC4AACUiABZAAZHjSRQOQCKklAwDgZMJOkuSWIUpTQKQFSwE5QSo3ItM1xrGBBUoSg-gAKgcxynOcpy4AAISTWw3IgKY4GYddaxcoKXMoZgGD4OAXh8gARcYUGsGB5OtAgRGAV0yEo-8aNvbyplizB4qERKdOS7KkDEqK8rihKksFMr3J8jyeCQOMIMrZghGgfdHXHStXVMYAUHYEoevkcgASFKi8waqZDTYkja2NLj8UJEq+MpSFD0XaUuyDE8FpgWJcqalqtzq2jcvY5IMnmgKVR7RsVqSttKVy-LCuKrUzwyMAuxKXK5pMs9eiSCl8XvR8GBB65gP0kQ-2vMKIty-6fKulDAgYmow3xejGMMEQkvCN7qqKpLviydxbss4THo1NbyUpnJXFydwkw7XIOugDmcn654hsOytcjKEXfoZHghf+EpNsLWEl0BizlSOxrPMNLpJd3fcZaPBF9ruz13BBxIKRZnIkfgdGkzgAAfa3Ipi0nPu1ChciIV9-HCdjd0SZxdxSFwRbKMXdn9qgfkrAFekFXKylSngwBMSQCMpfBcoymy3GCrOHLgJVmrEGTZBg-yaezrPQr8CKhCL96apKlOUHwSh6sLhgtFrsn6+SMqxOrtuO6d1Zm9o1utBO1qXErF5PJGscxvcIhUqIDB9yi4RUAYCgJpbouFfYpb1SGZ7yUpUfx67eMAZXIHf2H29R-Rm6b-uzjD82Y-b2SUeB-Jn6-rgUee8DppCNmDCQEMnzQybAReGmVEaV3gKPEoD8DqDnKJjfGZxcYjAJkTb+jtyaZErNTISB9uIMzFEQ3IptcjKF3DzBeuhgDL0FqzRMPAGFwEDsHCWuQUjSwXHLHa4sSFRliGfVWW4eaawEVtIRiIwzPwNnAUBk9XZIHdnAJmuRiY+XYT7K2tsCCN39s4bhXZQ7KMNi7f45Ao6UFHrHYA8dE7J2SPgUe6dbK0DLsFOAFRZAoCEH5VB2I+CKF8UFCu4UOAfGShkVRptzbiEwCTAqCU0FDEsM1M4klZLRTSr-Bg1ghD2PcMk3cuU7hMGDFATJmxslIFyVpapaBalFJKWUkJMSUnHROJwZ8KFGnNNkm5fpfgOlCFKTYip4x8HpKKvUgkwywx5Jkq09pJVMjFKmV02ZmBR4AEkQCKVsD6LJOTVlaWOacyZ0z2oIJSWfcZgyVorIiGssZjwJlbIyDs+5lY3aQy0ZLcIVici6N8t7X24w0kfX9nzQa7BEgACIwkwBRXAMOksqa5RST7SpPkNnQARQNAWqL0WYqTKilAmK6HjApXEzF2K2GQvxTC1JjUXmkv5sitFTL9EoreN8hgdLvb8r4MyikfwADKwZrBiAaDgOpfg4D0swJQVlo92W7nmfCuAiLyUSoxZFTyjLJVqvFZSrF4KqbauhbqouNy5BIB5UimA5qTXT2ap6qlPBUWgDkJingUA0C+ptTiuA4R7UMo5c8kVbqjXWu9UgcN1KhUvLFQy41UqsW0DlccUQmIoDKsEP4dVoKWUqPGhQIAA)

2024-12-04 04:11 UTC, MichaelMitchell-at commented
> Hi @MichaelMitchell-at, very sorry to ping you here directly - but as far as I can tell, this change has [broken polymorphic types](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHVaIpGiEoBICCICuQpASLoY+OAG99cd5ktMYwCAziY0OqmIsiYADwAKgA0cAAKcAC8LgC+AHwAFG7uOTlEDIZQAFyIEgB0AGJBIWHIBUhQFV4YvgxRsXFp0dk5AJQlyA6V1VChSJgAogAeED5oAMK4kAxsMOGDGGVxOGA8AOrAKhCWMGHhnXAAZKVDYQCCMDBQwABGJ0g8UWlpFDRwKZQkFNILAlNJbHFhJJzFAwMpgGgznceItwH5VnAgTA2CJFBsYGUJjZWOxIuC0kkbptUctVtsILsDiokSiluj2GkANqEcb4AC6FHIQJBUjAEKhMLhCPpu3C5HcyJp7PgWJxePKRKQJJgZLF3XcMsUqoKiggLwAVkZ4MlkMxRuE+M95LEVgA3BppcgUm3lJUrdiGpnKY6ncbhRVs-0wCnXQ1XFxwFA8AD8JQjaKj-0FwugovFQmh0ClaEDh2UZ3lcHTtPYmKm2JNVIJmu1uqQ+viOyN9bVggtVsptugIgdT1kchdSHdUE93viEqL8JLXfDrIzqw6XZjCaImFT84LkqXLL9qwpKWzwNzYLFTeQMEsUH8PofT7b6w1Mzmp45l5FN9sfEADkUFYMRkmcOBOS0OBZDgHRJAgTAmzKECwOmWYER-GA+QGco0N0DDv0jVZoL5LNASvUEYHBJsqigYJRkI4lVlXbC6wbXEUJbVY2znStq2VDjewQpC4AACUiABZAAZHjSRQOQCKklAwDgZMJOkuSWIUpTQKQFSwE5QSo3ItM1xrGBBUoSg-gAKgcxynOcpy4AAISTWw3IgKY4GYddaxcoKXMoZgGD4OAXh8gARcYUGsGB5OtAgRGAV0yEo-8aNvbyplizB4qERKdOS7KkDEqK8rihKksFMr3J8jyeCQOMIMrZghGgfdHXHStXVMYAUHYEoevkcgASFKi8waqZDTYkja2NLj8UJEq+MpSFD0XaUuyDE8FpgWJcqalqtzq2jcvY5IMnmgKVR7RsVqSttKVy-LCuKrUzwyMAuxKXK5pMs9eiSCl8XvR8GBB65gP0kQ-2vMKIty-6fKulDAgYmow3xejGMMEQkvCN7qqKpLviydxbss4THo1NbyUpnJXFydwkw7XIOugDmcn654hsOytcjKEXfoZHghf+EpNsLWEl0BizlSOxrPMNLpJd3fcZaPBF9ruz13BBxIKRZnIkfgdGkzgAAfa3Ipi0nPu1ChciIV9-HCdjd0SZxdxSFwRbKMXdn9qgfkrAFekFXKylSngwBMSQCMpfBcoymy3GCrOHLgJVmrEGTZBg-yaezrPQr8CKhCL96apKlOUHwSh6sLhgtFrsn6+SMqxOrtuO6d1Zm9o1utBO1qXErF5PJGscxvcIhUqIDB9yi4RUAYCgJpbouFfYpb1SGZ7yUpUfx67eMAZXIHf2H29R-Rm6b-uzjD82Y-b2SUeB-Jn6-rgUee8DppCNmDCQEMnzQybAReGmVEaV3gKPEoD8DqDnKJjfGZxcYjAJkTb+jtyaZErNTISB9uIMzFEQ3IptcjKF3DzBeuhgDL0FqzRMPAGFwEDsHCWuQUjSwXHLHa4sSFRliGfVWW4eaawEVtIRiIwzPwNnAUBk9XZIHdnAJmuRiY+XEJgH2ft2E+ytrbOAfd24EJKv7Zw3Cuyh2UYbF2-xyBR0oKPWOwB46J2TskfAo9062VoGXYKcAKiyBQEIPyqDsR8EUCEoKFdwocA+MlDIqjTbm30STAqCU0FDEsM1M4klZLRTSr-Bg1ghBuPcFk3cuU7hMGDFAfJmxClIGKVpRpaBmkVKqTU6JyTsmNROJwZ8KF2mdNkm5UZfg+lCGqc4up4x8G5KKq0gkkywwlJkt03pJVMiVIWQM5ZmBR4AEkQCKVsD6ApRTtlaUudc+Ziz2oIP0WfWZ4yVpbIiDsmZjw5kHIyEc15lY3aQy0ZLcIjici6N8t7X24wckfX9nzQa7BEgACJYkwCxXAMOksqa5X0YY5FPk9nQDRQNAW2LcX4qTNilA+K6HjDpak-FhK2HwtJUizAx0vnUv5pinFHLjFYreIChgLLvair4JyikfwADKwZrBiAaDgFpfg4CsswJQblo9eW7lWaiuA6LaVyrxZFTy7L5U6tlfSglsKqaGsRcaouTy5BICFRimAtqrXT2av6hlPBsWgDkPingUA0DBqdUSuA4RXVsr5Z8qVPqLWOsDUgWNjKJVfJlWyy1CqCW0BVccUQmIoCasEP4XV0KuUqPGhQIAA). I tried implementing your suggested changes above and didn't have much luck. Please let me know if you see a solution here, or a mistake I've made. For now we've pinned our React types to 18.3.4
> 
> [Tsplayground link](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHVaIpGiEoBICCICuQpASLoY+OAG99cd5ktMYwCAziY0OqmIsiYADwAKgA0cAAKcAC8LgC+AHwAFG7uOTlEDIZQAFyIEgB0AGJBIWHIBUhQFV4YvgxRsXFp0dk5AJQlyA6V1VChSJgAogAeED5oAMK4kAxsMOGDGGVxOGA8AOrAKhCWMGHhnXAAZKVDYQCCMDBQwABGJ0g8UWlpFDRwKZQkFNILAlNJbHFhJJzFAwMpgGgznceItwH5VnAgTA2CJFBsYGUJjZWOxIuC0kkbptUctVtsILsDiokSiluj2GkANqEcb4AC6FHIQJBUjAEKhMLhCPpu3C5HcyJp7PgWJxePKRKQJJgZLF3XcMsUqoKiggLwAVkZ4MlkMxRuE+M95LEVgA3BppcgUm3lJUrdiGpnKY6ncbhRVs-0wCnXQ1XFxwFA8AD8JQjaKj-0FwugovFQmh0ClaEDh2UZ3lcHTtPYmKm2JNVIJmu1uqQ+viOyN9bVggtVsptugIgdT1kchdSHdUE93viEqL8JLXfDrIzqw6XZjCaImFT84LkqXLL9qwpKWzwNzYLFTeQMEsUH8PofT7b6w1Mzmp45l5FN9sfEADkUFYMRkmcOBOS0OBZDgHRJAgTAmzKECwOmWYER-GA+QGco0N0DDv0jVZoL5LNASvUEYHBJsqigYJRkI4lVlXbC6wbXEUJbVY2znStq2VDjewQpC4AACUiABZAAZHjSRQOQCKklAwDgZMJOkuSWIUpTQKQFSwE5QSo3ItM1xrGBBUoSg-gAKgcxynOcpy4AAISTWw3IgKY4GYddaxcoKXMoZgGD4OAXh8gARcYUGsGB5OtAgRGAV0yEo-8aNvbyplizB4qERKdOS7KkDEqK8rihKksFMr3J8jyeCQOMIMrZghGgfdHXHStXVMYAUHYEoevkcgASFKi8waqZDTYkja2NLj8UJEq+MpSFD0XaUuyDE8FpgWJcqalqtzq2jcvY5IMnmgKVR7RsVqSttKVy-LCuKrUzwyMAuxKXK5pMs9eiSCl8XvR8GBB65gP0kQ-2vMKIty-6fKulDAgYmow3xejGMMEQkvCN7qqKpLviydxbss4THo1NbyUpnJXFydwkw7XIOugDmcn654hsOytcjKEXfoZHghf+EpNsLWEl0BizlSOxrPMNLpJd3fcZaPBF9ruz13BBxIKRZnIkfgdGkzgAAfa3Ipi0nPu1ChciIV9-HCdjd0SZxdxSFwRbKMXdn9qgfkrAFekFXKylSngwBMSQCMpfBcoymy3GCrOHLgJVmrEGTZBg-yaezrPQr8CKhCL96apKlOUHwSh6sLhgtFrsn6+SMqxOrtuO6d1Zm9o1utBO1qXErF5PJGscxvcIhUqIDB9yi4RUAYCgJpbouFfYpb1SGZ7yUpUfx67eMAZXIHf2H29R-Rm6b-uzjD82Y-b2SUeB-Jn6-rgUee8DppCNmDCQEMnzQybAReGmVEaV3gKPEoD8DqDnKJjfGZxcYjAJkTb+jtyaZErNTISB9uIMzFEQ3IptcjKF3DzBeuhgDL0FqzRMPAGFwEDsHCWuQUjSwXHLHa4sSFRliGfVWW4eaawEVtIRiIwzPwNnAUBk9XZIHdnAJmuRiY+XEJgH2ft2E+ytrbOAfd24EJKv7Zw3Cuyh2UYbF2-xyBR0oKPWOwB46J2TskfAo9062VoGXYKcAKiyBQEIPyqDsR8EUCEoKFdwocA+MlDIqjTbm30STAqCU0FDEsM1M4klZLRTSr-Bg1ghBuPcFk3cuU7hMGDFAfJmxClIGKVpRpaBmkVKqTU6JyTsmNROJwZ8KF2mdNkm5UZfg+lCGqc4up4x8G5KKq0gkkywwlJkt03pJVMiVIWQM5ZmBR4AEkQCKVsD6ApRTtlaUudc+Ziz2oIP0WfWZ4yVpbIiDsmZjw5kHIyEc15lY3aQy0ZLcIjici6N8t7X24wckfX9nzQa7BEgACJYkwCxXAMOksqa5X0YY5FPk9nQDRQNAW2LcX4qTNilA+K6HjDpak-FhK2HwtJUizAx0vnUv5pinFHLjFYreIChgLLvair4JyikfwADKwZrBiAaDgFpfg4CsswJQblo9eW7lWaiuA6LaVyrxZFTy7L5U6tlfSglsKqaGsRcaouTy5BICFRimAtqrXT2av6hlPBsWgDkPingUA0DBqdUSuA4RXVsr5Z8qVPqLWOsDUgWNjKJVfJlWyy1CqCW0BVccUQmIoCasEP4XV0KuUqPGhQIAA)

Sorry, I'm unable to see any difference in behavior with the playground you've linked, before and after uncommenting the designated lines.

2024-12-04 12:27 UTC, codynova commented
> Sorry, I'm unable to see any difference in behavior with the playground you've linked, before and after uncommenting the designated lines.

@MichaelMitchell-at Thanks for your response. The playground linked above is implementing the solution you recommended, and doesn't seem to work for non-optional props. I guess my question is, after these changes to the React types, how is it possible to achieve polymorphic components that work with both optional and non-optional props?

Uncommenting the old typings aren't enough to fix the polymorphic types in the playground - the technique we used to achieve polymorphic components is a bit different in 18.3.4. I can create another playground demonstrating that technique.

2024-12-05 19:26 UTC, codynova commented
Okay [here is a clearer ts playground](https://www.typescriptlang.org/play/?ts=5.7.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHkRSNEJQCQEEQFchSAkXQx8cAN7k4cTBaYxgEBu+jqJiLImAA8ACoANHAACnAAvM4AvgB8ABSublluRAwGUABciBIAdABiAUEhyHlIUGWeGD4MEdExKZGZbgCURcj25ZVQwUiYAKIAHhDeaADCuJAMbDCh-RglMThgPADqwCoQFjAhoe1wAGTFAyEAgjAwUMAARkdIPBEpKRRJlNS0AFSAoHAkHA2LCSRmKBgZTANBwZRIIRgOpKaRvOCgrGgyhICaQWBolGxLY8ADyYUy83AvmWcDxMDYIh4XTgAB84DpJBBMFd1gApADKAA0SgBJdiPBg8OFjaysdgs7IctYwEpC4VypAKmDzaUPCwYaChTxaBgQdQMDrkFIJPlqjUlAAyzygJkkAFkUAwUHJdHcHs9Xu8qQtaexOm5VSVqYtlpsINs9gcjidY+GYCkbbj8dApMTJoy8igntYE9tQpkAEIoHhIcuKRJOJKRuBkgBudUeBgbdubnVtiQ7XeAPdJFzbIH2oRrdYb0S5PLbnag3frpKz5DxBPzNgliMeMBL1i1Ooblbc6aW7HpEyLzPtJVPy3C6NbvabLZtdsLTOP68Td4GwpUIr2WDoSUAzdtzzIk9wYA99n-Z92AbAAmC84DAm8GSZRRoxQmBXxRd9x0-AcfzvP9SwAito2wmAG2TZRDmOUZQLDa9MzaDccx3ODwSESFoBhOEThuHgGNve98NKQjiKQQdMnozj41JZjxMk1T2BSABtQhRnwABdPjYJgdFBOE6FYTQc9MgkqTcLyWSBnkt9Mg-ZIKMSfc6iQmjCPQzCHO0mBSMAicnDgWsAH4ihCmkuLgJJIvETA4ssqFRLQTSGNtH5oNzQlzOJVVkBgCwoD8RJysqhgFNWOSphmPKKC3Ird3tAA5FBWDEJs4F0rQ4FkTkkG5Xlox6vrJmmOEGKMvpSmm3RZpa0KhqM5K2pg4qLNVCooECYZVvlZZQgSuMcKo5zHzclFBzgeytMSuknIfRdeQACXCD0nXk30Vq9MA4BiuAfr+gG5CBlAwF0y6My2+KXqumA2soGhMWxbH-jgWcbCrCAJjgZhXpvHHscoZh9TgJ4iYAEVGFArBgQi7XwERgHbMhTL24lCYmRnMGZoRWbOm9EhKpAlzpwWmZZwi2qlvGifxzyXDcZghGgDK+ClORMnbExgG9GAij12QDZ+dr+OVgXzwRpL3pc9Z7sUu0YghLKbIdlGM2iAW1Y3JWLIFqTEjSC6-adm6HwI8WiIsxIBaFkWxe1cC0jAUkint0ko7y7oEltMqkAqqqi8uVUVpEHaOpJ3w+BViZc6J8PH0wIYRkwDI3AL0LpLwu6E4U9JWQ17Jop4Vtsi16AZ6yI3HlNhe3BKdfs8A1kkiKT2hO9uFfYYgPVdrWieGtbIiHS3evZEmzctCrMemL5xWWppv29rUGwdl1OFYThQK+Zc6pwA4mTeA194hOGvilJw68Sib22ClKgXxMg-G6G1AWJROY8DAMYSQK12YCx5r8TGFNsRYTDHWMQLoGDDVJqjLGFCQRU0bvAIQsgtD-1FmzRI+AUD4F5p1Oh3D5a8ITnaKWS5OH0J4enHUlBlaiKDhFJsmQnhn3NoGeQmQiCcyIBgDKdNhCoAYN8JRFlRFHwHs7YeGd2CjztCos+vZLh50Av3CBaDyDKK4e3SOjs3qxxdmqN2ziuHyMIukJBPAijWPzkEnSRd4glwkLVCuE5q69V0HXfiH94CiPif4geNVSidyOlUUYvcwFJPgHY+ODjE4PRqW4Ce2RlDX1XuIAxhgwqsjcLWbpS8TYRgGXABBsTt6333vfQ+iTo7LBPhMVR2xL5ZGvhlPeVlsqP28ZkFJtp2kNxpgE7+MUwayLEcLABTSi48DUMAHgmBgAYkaTqBSQCNkgKqnAVpWQZxEzStA2BU9oEMRSiM028QABEjI+AwucJM0kKDn5ZEweg8gGLyCiJwU8-BKBCE5PZqI0hGMAQsJBHAMosgUBCAbhApQbwYCKEpaw8gBSmVNwjoct+mt2FpRTuI+AZSBgWDrCcCGTp6Zc2iWkBgVghAYv5TTa+AsbhMBYlAO00ZxVIElb9J0Gq0BarlQqoQSqvmcrVarI4nBqqPj1Qav6VY7W+DNYq5VJym7X1EfInVpQnXsSlca01Cd0jmstZka1oxRFihAL6Gwor1hBrCFK+NiaPUWq9TGzAKi3UOt1RK4NhrXX3HdeG+Vnq2o5B+X4f5oQ0XZEBcTKBMDRhCpuaLSFxtoVwuZYi1B4yW3AvbZgdVmroA9uXuwWF8KYCItrLClAiLOmjDnQOuAQ7J5gIFqOm1KyC3TtGTADdCKwUwpeOWhgq6oH9vPagrdtBBQsSsGILs0BBB+DXZgSgO7QiiP3bGyJwrj19vnYizRdYz0LoRHeiDW6m0AsA2231XCM1+jA7O+9sGoNIBg4ungsLQByERTwKAaACOIeHSh9dY640Jsw7TM+VGl0wpI2RijVHH2YxfYcUQ9JVyfqnDwGU8g4BQvYDRrhQG83ocY0gLDp6cOEeIyAUjcByOUZU4hp9cA+NvsEzgbVImxNyGY3WaT9DZP5uvUpqjeHWNEcvQW2966dM8efa+gTH7tW+Dg6MVkoRt1wG6OQJIFAgA) demonstration polymorphism working with the old types / patterns.

If you comment out the old types, you'll see the issue.

After commenting out the old types, you can try passing the element type to `Box`'s `forwardRef`:

```tsx
export const Box: BoxComponent = React.forwardRef<ReactForwardedElement<BoxDefaultElement>>(
```

I haven't found a way to resolve these issues and keep the strong polymorphic typings

2024-12-05 20:00 UTC, MichaelMitchell-at commented
> Okay [here is a clearer ts playground](https://www.typescriptlang.org/play/?ts=5.7.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHkRSNEJQCQEEQFchSAkXQx8cAN7k4cTBaYxgEBu+jqJiLImAA8ACoANHAACnAAvM4AvgB8ABSublluRAwGUABciBIAdABiAUEhyHlIUGWeGD4MEdExKZGZbgCURcj25ZVQwUiYAKIAHhDeaADCuJAMbDCh-RglMThgPADqwCoQFjAhoe1wAGTFAyEAgjAwUMAARkdIPBEpKRRJlNS0AFSAoHAkHA2LCSRmKBgZTANBwZRIIRgOpKaRvOCgrGgyhICaQWBolGxLY8ADyYUy83AvmWcDxMDYIh4XTgAB84DpJBBMFd1gApADKAA0SgBJdiPBg8OFjaysdgs7IctYwEpC4VypAKmDzaUPCwYaChTxaBgQdQMDrkFIJPlqjUlAAyzygJkkAFkUAwUHJdHcHs9Xu8qQtaexOm5VSVqYtlpsINs9gcjidY+GYCkbbj8dApMTJoy8igntYE9tQpkAEIoHhIcuKRJOJKRuBkgBudUeBgbdubnVtiQ7XeAPdJFzbIH2oRrdYb0S5PLbnag3frpKz5DxBPzNgliMeMBL1i1Ooblbc6aW7HpEyLzPtJVPy3C6NbvabLZtdsLTOP68Td4GwpUIr2WDoSUAzdtzzIk9wYA99n-Z92AbAAmC84DAm8GSZRRoxQmBXxRd9x0-AcfzvP9SwAito2wmAG2TZRDmOUZQLDa9MzaDccx3ODwSESFoBhOEThuHgGNve98NKQjiKQQdMnozj41JZjxMk1T2BSABtQhRnwABdPjYJgdFBOE6FYTQc9MgkqTcLyWSBnkt9Mg-ZIKMSfc6iQmjCPQzCHO0mBSMAicnDgWsAH4ihCmkuLgJJIvETA4ssqFRLQTSGNtH5oNzQlzOJVVkBgCwoD8RJysqhgFNWOSphmPKKC3Ird3tAA5FBWDEJs4F0rQ4FkTkkG5Xlox6vrJmmOEGKMvpSmm3RZpa0KhqM5K2pg4qLNVCooECYZVvlZZQgSuMcKo5zHzclFBzgeytMSuknIfRdeQACXCD0nXk30Vq9MA4BiuAfr+gG5CBlAwF0y6My2+KXqumA2soGhMWxbH-jgWcbCrCAJjgZhXpvHHscoZh9TgJ4iYAEVGFArBgQi7XwERgHbMhTL24lCYmRnMGZoRWbOm9EhKpAlzpwWmZZwi2qlvGifxzyXDcZghGgDK+ClORMnbExgG9GAij12QDZ+dr+OVgXzwRpL3pc9Z7sUu0YghLKbIdlGM2iAW1Y3JWLIFqTEjSC6-adm6HwI8WiIsxIBaFkWxe1cC0jAUkint0ko7y7oEltMqkAqqqi8uVUVpEHaOpJ3w+BViZc6J8PH0wIYRkwDI3AL0LpLwu6E4U9JWQ17Jop4Vtsi16AZ6yI3HlNhe3BKdfs8A1kkiKT2hO9uFfYYgPVdrWieGtbIiHS3evZEmzctCrMemL5xWWppv29rUGwdl1OFYThQK+Zc6pwA4mTeA194hOGvilJw68Sib22ClKgXxMg-G6G1AWJROY8DAMYSQK12YCx5r8TGFNsRYTDHWMQLoGDDVJqjLGFCQRU0bvAIQsgtD-1FmzRI+AUD4F5p1Oh3D5a8ITnaKWS5OH0J4enHUlBlaiKDhFJsmQnhn3NoGeQmQiCcyIBgDKdNhCoAYN8JRFlRFHwHs7YeGd2CjztCos+vZLh50Av3CBaDyDKK4e3SOjs3qxxdmqN2ziuHyMIukJBPAijWPzkEnSRd4glwkLVCuE5q69V0HXfiH94CiPif4geNVSidyOlUUYvcwFJPgHY+ODjE4PRqW4Ce2RlDX1XuIAxhgwqsjcLWbpS8TYRgGXABBsTt6333vfQ+iTo7LBPhMVR2xL5ZGvhlPeVlsqP28ZkFJtp2kNxpgE7+MUwayLEcLABTSi48DUMAHgmBgAYkaTqBSQCNkgKqnAVpWQZxEzStA2BU9oEMRSiM028QABEjI+AwucJM0kKDn5ZEweg8gGLyCiJwU8-BKBCE5PZqI0hGMAQsJBHAMosgUBCAbhApQbwYCKEpaw8gBSmVNwjoct+mt2FpRTuI+AZSBgWDrCcCGTp6Zc2iWkBgVghAYv5TTa+AsbhMBYlAO00ZxVIElb9J0Gq0BarlQqoQSqvmcrVarI4nBqqPj1Qav6VY7W+DNYq5VJym7X1EfInVpQnXsSlca01Cd0jmstZka1oxRFihAL6Gwor1hBrCFK+NiaPUWq9TGzAKi3UOt1RK4NhrXX3HdeG+Vnq2o5B+X4f5oQ0XZEBcTKBMDRhCpuaLSFxtoVwuZYi1B4yW3AvbZgdVmroA9uXuwWF8KYCItrLClAiLOmjDnQOuAQ7J5gIFqOm1KyC3TtGTADdCKwUwpeOWhgq6oH9vPagrdtBBQsSsGILs0BBB+DXZgSgO7QiiP3bGyJwrj19vnYizRdYz0LoRHeiDW6m0AsA2231XCM1+jA7O+9sGoNIBg4ungsLQByERTwKAaACOIeHSh9dY640Jsw7TM+VGl0wpI2RijVHH2YxfYcUQ9JVyfqnDwGU8g4BQvYDRrhQG83ocY0gLDp6cOEeIyAUjcByOUZU4hp9cA+NvsEzgbVImxNyGY3WaT9DZP5uvUpqjeHWNEcvQW2966dM8efa+gTH7tW+Dg6MVkoRt1wG6OQJIFAgA) demonstrating polymorphism working with the old types / patterns.
> 
> If you comment out the old types, you'll see the issue.
> 
> After commenting out the old types, you can try passing the element type to `Box`'s `forwardRef`:
> 
> ```tsx
> export const Box: BoxComponent = React.forwardRef<ReactForwardedElement<BoxDefaultElement>>(
> ```
> 
> I haven't found a way to resolve these issues and keep the strong polymorphic typings

Since you're not going to get strong enforcement of the generic render function anyway, I would say your goal should merely be to avoid the type errors at the definition. You can do so by providing more general types explicitly to forwardRef. [Playground](https://www.typescriptlang.org/play/?ts=5.7.2&ssl=106&ssc=71&pln=106&pc=86#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHkRSNEJQCQEEQFchSAkXQx8cAN7k4cGnEwWmMYBAae0OomIsiYADwAKgA0cAAKcAC8zgC+AHwAFK7utG554gwGUABciBIAdABiQSFhyIVIUJXeGH4MUbFxadHZHm4AlKXI9lU1UKFImACiAB4QvmgAwriQDGww4cMY5XE4YDwA6sAqEBYwYeFdcABkZSNhAIIwMFDAAEZnSDxRaWkUKZRqLQAFSgsHgiHg+LCSRmKBgZTANBwZRIIRgRpKaRfOCQvGQyhIGaQWBYjHxPY8ADyEWyy3A-nWcCJMDYIh42TcAB84DpJBBMHdtgApADKAA1ygBJdivBg8JFTaysdgc-I8rYwcpi8VKpAqmDLeUvCwYaDhbxaBgQdQMbrkNJJIVanXlAAy7ygJkkAFkUAwUHJdE8Xu9Pt86StGewem5NeV6at1rsIPsjiczhdE9GYGkHYTidApOTZqzCig3tYU-twtkAEIoHhIauKZJOFKxuBUgBujVeBhbTvbPUdyR7feAA8pNy7IGO4QbTZbsT5Aq7vag-eblLz5CJJOLNhlqNeMAr1j1Bpbtbc2bW7GZMzL7Od5Uv60i2M7g7bHYdTtLNlz23VNvhbGlwjvdZugpUDd33IsySPBgT2OYD33YFsACYbzgKCHxZNlFHjDCYE-DFv2nX8RwAp8gMrECa3jfCYBbdNlFOc5JkgqN71zTodwLA8kOhIRYWgBEkQuB4eBYx9n2IipSPIpBR2yZjeOTSl2Ok2TNPYNIAG1CEmfAAF0hMQmBsVE8T4URNBr2yGS5MIwpFJGZSv2yH9Uho5Jj0aNCGNI7DcJc-SYEo0CZycOBGwAflKCKGT4uAUli8RMCS2y4UktBdJYx0AXgwtSWs8lNWQGALCgAJkmq2qGBUzYlLmBYiooPcysPZ0ADkUFYMQ2zgQytDgWReSQflBXjAahtmeYkRYsyhgqebdEWjrIrGsz0q6hDypszVqigYJxk25V1nCFKkwIuj3NfLyMVHOBnL01KmTcl9V0FAAJSIfTdZTAw2v0wDgBK4ABoGQbkMGUDAQzbpzPbko+u6YC6ygPHxPHQTgRcbDrCAZjgZhPoffG8coZhjTgN5SYAEUmFArBgUinXwERgG7MhLKO8kSZmFnMDZoQOauh9kgqpA10ZkXWfZ0iutlwnSaJ3yXDcZghGgHK+DlORsm7ExgH9GBSkN2RjYBbrhLV4XrxRtLvo87ZntUp04hhPKHOdjGc1iYXNZ3VWbOFuTkgyG7A9dh6XxIqWyJs5JhdF8XJf1aCMjASlSidylY6K-okkdKqkBqurS9uTUNpEA6evJ-w+HVmYC9JqPX0wMYJgieNNVIhcNcbRieBgkPR5bTJsmLyL5KIp7k5Umf8m1-J4p4Tt8l16Bt7yU3Xgt-e3HKM+89Azl0tKH2xL9pEA5Y4OR6XHd96IbKb99iSHMKyK8wGGXZwV86aty7o2SGUMFYZ2VsnCg+QiBVwCDxSm8AP6JCcB-DKTgz7lAvvsDKVA-jZABP0Lqwtyg8x4GAYwkgNpc2FvzQEuNqZ4jwlGJsYgPQMHGhTTGuJWEEnIKA+AQhZBaBgRLTmyR8AoHwALXq3CJFKykcnJ0ss1xiJ4ZIrOBpKBqyUaHGKbZshvFHlbUM8hshEB5kQDAOVGbCFQAwf4+ibJKMfvPN2S9s7sBXk6QxU9py3ELqBOeqDiHkAMeIruMcXZfQTu7LUnsAniJ0aRTI+CeClA8UXeJBlS6JHLhIRq1cZx10GroRuwkRFwCUTkmJ88GoVB7mdWo3EB4SCHoE1+cFYg9LHqvOA4T+HeKTr4lOL0shryvm4ZQH8T7iFsYYKKszN6LMPubGMazcFZKvikL+d8f4PzyXHdY-TxFGP2PaBBkwcq3zsvlP+ETsiFMdOvHWLd4CxIgQlKGWjlFi1gRM0uPA1DAB4JgYAOJxkGhUvAvIiCmpwGmRvYeZN0GYMmBlRsGCWIZU2RbRIAAiVkfBiXOF2ZSQhAC8hkJIeQel5AlGUIhTQlAdDKlcyUUwnGIJBEQjgJUWQKAhDN1QUoL4MBFACohLTL5krW7RzecAz59MP7pxUfAZpIwLBNguDDN0TNeYZIyAwKwQh6Vqtbhq0mDwmAcSgE6eMeqkAGsBm6e1aBHWmvNUIS1CLam2pmHWM4nB6qvlde6oGobnj+F9Raq1zd1WTCUTo51FQo3cUNV6n1ydMh+oDdkINqbxFShAIGGwOrthZoiIa8tlaE3+qTSWzAhiw3+Azbq-V2aPWxvDU2ot1jK7ItRW4cItL8joqyhg4NOiCVmyJaSqVFKiFrOnZi4NuboALqPuwElZKYAUtxcSlAFL5mTAPSu9wk68gbsvVizAIcO0MF3VsmAV7yWbxJR8ONDBz3oOXV+ohOQ4Cig4lYMQfZoCCACBezAlAN7DKUTOx9aatVvqXYeilZimyfqPSiQD2Gb3rpQ5u0tPCG1Bkw-uoDBHcNIHw8engJLQByApTwKAaAmMkaQ+EMjD6P5KKo0gDKDGeMnrYxxrjPGQMeHA6cUQzJNwwbnDwBU8g4CEvYKR8RqGhNlordRrTi7aPEckyAdjcBOPcbo6ux08mINKeg06tTGm5AM1Hrpnh+mKNaH7f4GjH67OebwyFk9v7w0AcvSFuTtAFOQeUzgJ1nb4NX3CGugY5AUgUCAA)

2024-12-05 20:03 UTC, codynova commented
> > Okay [here is a clearer ts playground](https://www.typescriptlang.org/play/?ts=5.7.2#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHkRSNEJQCQEEQFchSAkXQx8cAN7k4cTBaYxgEBu+jqJiLImAA8ACoANHAACnAAvM4AvgB8ABSublluRAwGUABciBIAdABiAUEhyHlIUGWeGD4MEdExKZGZbgCURcj25ZVQwUiYAKIAHhDeaADCuJAMbDCh-RglMThgPADqwCoQFjAhoe1wAGTFAyEAgjAwUMAARkdIPBEpKRRJlNS0AFSAoHAkHA2LCSRmKBgZTANBwZRIIRgOpKaRvOCgrGgyhICaQWBolGxLY8ADyYUy83AvmWcDxMDYIh4XTgAB84DpJBBMFd1gApADKAA0SgBJdiPBg8OFjaysdgs7IctYwEpC4VypAKmDzaUPCwYaChTxaBgQdQMDrkFIJPlqjUlAAyzygJkkAFkUAwUHJdHcHs9Xu8qQtaexOm5VSVqYtlpsINs9gcjidY+GYCkbbj8dApMTJoy8igntYE9tQpkAEIoHhIcuKRJOJKRuBkgBudUeBgbdubnVtiQ7XeAPdJFzbIH2oRrdYb0S5PLbnag3frpKz5DxBPzNgliMeMBL1i1Ooblbc6aW7HpEyLzPtJVPy3C6NbvabLZtdsLTOP68Td4GwpUIr2WDoSUAzdtzzIk9wYA99n-Z92AbAAmC84DAm8GSZRRoxQmBXxRd9x0-AcfzvP9SwAito2wmAG2TZRDmOUZQLDa9MzaDccx3ODwSESFoBhOEThuHgGNve98NKQjiKQQdMnozj41JZjxMk1T2BSABtQhRnwABdPjYJgdFBOE6FYTQc9MgkqTcLyWSBnkt9Mg-ZIKMSfc6iQmjCPQzCHO0mBSMAicnDgWsAH4ihCmkuLgJJIvETA4ssqFRLQTSGNtH5oNzQlzOJVVkBgCwoD8RJysqhgFNWOSphmPKKC3Ird3tAA5FBWDEJs4F0rQ4FkTkkG5Xlox6vrJmmOEGKMvpSmm3RZpa0KhqM5K2pg4qLNVCooECYZVvlZZQgSuMcKo5zHzclFBzgeytMSuknIfRdeQACXCD0nXk30Vq9MA4BiuAfr+gG5CBlAwF0y6My2+KXqumA2soGhMWxbH-jgWcbCrCAJjgZhXpvHHscoZh9TgJ4iYAEVGFArBgQi7XwERgHbMhTL24lCYmRnMGZoRWbOm9EhKpAlzpwWmZZwi2qlvGifxzyXDcZghGgDK+ClORMnbExgG9GAij12QDZ+dr+OVgXzwRpL3pc9Z7sUu0YghLKbIdlGM2iAW1Y3JWLIFqTEjSC6-adm6HwI8WiIsxIBaFkWxe1cC0jAUkint0ko7y7oEltMqkAqqqi8uVUVpEHaOpJ3w+BViZc6J8PH0wIYRkwDI3AL0LpLwu6E4U9JWQ17Jop4Vtsi16AZ6yI3HlNhe3BKdfs8A1kkiKT2hO9uFfYYgPVdrWieGtbIiHS3evZEmzctCrMemL5xWWppv29rUGwdl1OFYThQK+Zc6pwA4mTeA194hOGvilJw68Sib22ClKgXxMg-G6G1AWJROY8DAMYSQK12YCx5r8TGFNsRYTDHWMQLoGDDVJqjLGFCQRU0bvAIQsgtD-1FmzRI+AUD4F5p1Oh3D5a8ITnaKWS5OH0J4enHUlBlaiKDhFJsmQnhn3NoGeQmQiCcyIBgDKdNhCoAYN8JRFlRFHwHs7YeGd2CjztCos+vZLh50Av3CBaDyDKK4e3SOjs3qxxdmqN2ziuHyMIukJBPAijWPzkEnSRd4glwkLVCuE5q69V0HXfiH94CiPif4geNVSidyOlUUYvcwFJPgHY+ODjE4PRqW4Ce2RlDX1XuIAxhgwqsjcLWbpS8TYRgGXABBsTt6333vfQ+iTo7LBPhMVR2xL5ZGvhlPeVlsqP28ZkFJtp2kNxpgE7+MUwayLEcLABTSi48DUMAHgmBgAYkaTqBSQCNkgKqnAVpWQZxEzStA2BU9oEMRSiM028QABEjI+AwucJM0kKDn5ZEweg8gGLyCiJwU8-BKBCE5PZqI0hGMAQsJBHAMosgUBCAbhApQbwYCKEpaw8gBSmVNwjoct+mt2FpRTuI+AZSBgWDrCcCGTp6Zc2iWkBgVghAYv5TTa+AsbhMBYlAO00ZxVIElb9J0Gq0BarlQqoQSqvmcrVarI4nBqqPj1Qav6VY7W+DNYq5VJym7X1EfInVpQnXsSlca01Cd0jmstZka1oxRFihAL6Gwor1hBrCFK+NiaPUWq9TGzAKi3UOt1RK4NhrXX3HdeG+Vnq2o5B+X4f5oQ0XZEBcTKBMDRhCpuaLSFxtoVwuZYi1B4yW3AvbZgdVmroA9uXuwWF8KYCItrLClAiLOmjDnQOuAQ7J5gIFqOm1KyC3TtGTADdCKwUwpeOWhgq6oH9vPagrdtBBQsSsGILs0BBB+DXZgSgO7QiiP3bGyJwrj19vnYizRdYz0LoRHeiDW6m0AsA2231XCM1+jA7O+9sGoNIBg4ungsLQByERTwKAaACOIeHSh9dY640Jsw7TM+VGl0wpI2RijVHH2YxfYcUQ9JVyfqnDwGU8g4BQvYDRrhQG83ocY0gLDp6cOEeIyAUjcByOUZU4hp9cA+NvsEzgbVImxNyGY3WaT9DZP5uvUpqjeHWNEcvQW2966dM8efa+gTH7tW+Dg6MVkoRt1wG6OQJIFAgA) demonstrating polymorphism working with the old types / patterns.
> > If you comment out the old types, you'll see the issue.
> > After commenting out the old types, you can try passing the element type to `Box`'s `forwardRef`:
> > ```tsx
> > export const Box: BoxComponent = React.forwardRef<ReactForwardedElement<BoxDefaultElement>>(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I haven't found a way to resolve these issues and keep the strong polymorphic typings
> 
> Since you're not going to get strong enforcement of the generic render function anyway, I would say your goal should merely be to avoid the type errors at the definition. You can do so by providing more general types explicitly to forwardRef. [Playground](https://www.typescriptlang.org/play/?ts=5.7.2&ssl=106&ssc=71&pln=106&pc=86#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgeirgFUA7NXEJB+GCOIgZ06LgQANgBNuxDgE8wwBgHMecGAAsU8AO7QA1khHkRSNEJQCQEEQFchSAkXQx8cAN7k4cGnEwWmMYBAae0OomIsiYADwAKgA0cAAKcAC8zgC+AHwAFK7utG554gwGUABciBIAdABiQSFhyIVIUJXeGH4MUbFxadHZHm4AlKXI9lU1UKFImACiAB4QvmgAwriQDGww4cMY5XE4YDwA6sAqEBYwYeFdcABkZSNhAIIwMFDAAEZnSDxRaWkUKZRqLQAFSgsHgiHg+LCSRmKBgZTANBwZRIIRgRpKaRfOCQvGQyhIGaQWBYjHxPY8ADyEWyy3A-nWcCJMDYIh42TcAB84DpJBBMHdtgApADKAA1ygBJdivBg8JFTaysdgc-I8rYwcpi8VKpAqmDLeUvCwYaDhbxaBgQdQMbrkNJJIVanXlAAy7ygJkkAFkUAwUHJdE8Xu9Pt86StGewem5NeV6at1rsIPsjiczhdE9GYGkHYTidApOTZqzCig3tYU-twtkAEIoHhIauKZJOFKxuBUgBujVeBhbTvbPUdyR7feAA8pNy7IGO4QbTZbsT5Aq7vag-eblLz5CJJOLNhlqNeMAr1j1Bpbtbc2bW7GZMzL7Od5Uv60i2M7g7bHYdTtLNlz23VNvhbGlwjvdZugpUDd33IsySPBgT2OYD33YFsACYbzgKCHxZNlFHjDCYE-DFv2nX8RwAp8gMrECa3jfCYBbdNlFOc5JkgqN71zTodwLA8kOhIRYWgBEkQuB4eBYx9n2IipSPIpBR2yZjeOTSl2Ok2TNPYNIAG1CEmfAAF0hMQmBsVE8T4URNBr2yGS5MIwpFJGZSv2yH9Uho5Jj0aNCGNI7DcJc-SYEo0CZycOBGwAflKCKGT4uAUli8RMCS2y4UktBdJYx0AXgwtSWs8lNWQGALCgAJkmq2qGBUzYlLmBYiooPcysPZ0ADkUFYMQ2zgQytDgWReSQflBXjAahtmeYkRYsyhgqebdEWjrIrGsz0q6hDypszVqigYJxk25V1nCFKkwIuj3NfLyMVHOBnL01KmTcl9V0FAAJSIfTdZTAw2v0wDgBK4ABoGQbkMGUDAQzbpzPbko+u6YC6ygPHxPHQTgRcbDrCAZjgZhPoffG8coZhjTgN5SYAEUmFArBgUinXwERgG7MhLKO8kSZmFnMDZoQOauh9kgqpA10ZkXWfZ0iutlwnSaJ3yXDcZghGgHK+DlORsm7ExgH9GBSkN2RjYBbrhLV4XrxRtLvo87ZntUp04hhPKHOdjGc1iYXNZ3VWbOFuTkgyG7A9dh6XxIqWyJs5JhdF8XJf1aCMjASlSidylY6K-okkdKqkBqurS9uTUNpEA6evJ-w+HVmYC9JqPX0wMYJgieNNVIhcNcbRieBgkPR5bTJsmLyL5KIp7k5Umf8m1-J4p4Tt8l16Bt7yU3Xgt-e3HKM+89Azl0tKH2xL9pEA5Y4OR6XHd96IbKb99iSHMKyK8wGGXZwV86aty7o2SGUMFYZ2VsnCg+QiBVwCDxSm8AP6JCcB-DKTgz7lAvvsDKVA-jZABP0Lqwtyg8x4GAYwkgNpc2FvzQEuNqZ4jwlGJsYgPQMHGhTTGuJWEEnIKA+AQhZBaBgRLTmyR8AoHwALXq3CJFKykcnJ0ss1xiJ4ZIrOBpKBqyUaHGKbZshvFHlbUM8hshEB5kQDAOVGbCFQAwf4+ibJKMfvPN2S9s7sBXk6QxU9py3ELqBOeqDiHkAMeIruMcXZfQTu7LUnsAniJ0aRTI+CeClA8UXeJBlS6JHLhIRq1cZx10GroRuwkRFwCUTkmJ88GoVB7mdWo3EB4SCHoE1+cFYg9LHqvOA4T+HeKTr4lOL0shryvm4ZQH8T7iFsYYKKszN6LMPubGMazcFZKvikL+d8f4PzyXHdY-TxFGP2PaBBkwcq3zsvlP+ETsiFMdOvHWLd4CxIgQlKGWjlFi1gRM0uPA1DAB4JgYAOJxkGhUvAvIiCmpwGmRvYeZN0GYMmBlRsGCWIZU2RbRIAAiVkfBiXOF2ZSQhAC8hkJIeQel5AlGUIhTQlAdDKlcyUUwnGIJBEQjgJUWQKAhDN1QUoL4MBFACohLTL5krW7RzecAz59MP7pxUfAZpIwLBNguDDN0TNeYZIyAwKwQh6Vqtbhq0mDwmAcSgE6eMeqkAGsBm6e1aBHWmvNUIS1CLam2pmHWM4nB6qvlde6oGobnj+F9Raq1zd1WTCUTo51FQo3cUNV6n1ydMh+oDdkINqbxFShAIGGwOrthZoiIa8tlaE3+qTSWzAhiw3+Azbq-V2aPWxvDU2ot1jK7ItRW4cItL8joqyhg4NOiCVmyJaSqVFKiFrOnZi4NuboALqPuwElZKYAUtxcSlAFL5mTAPSu9wk68gbsvVizAIcO0MF3VsmAV7yWbxJR8ONDBz3oOXV+ohOQ4Cig4lYMQfZoCCACBezAlAN7DKUTOx9aatVvqXYeilZimyfqPSiQD2Gb3rpQ5u0tPCG1Bkw-uoDBHcNIHw8engJLQByApTwKAaAmMkaQ+EMjD6P5KKo0gDKDGeMnrYxxrjPGQMeHA6cUQzJNwwbnDwBU8g4CEvYKR8RqGhNlordRrTi7aPEckyAdjcBOPcbo6ux08mINKeg06tTGm5AM1Hrpnh+mKNaH7f4GjH67OebwyFk9v7w0AcvSFuTtAFOQeUzgJ1nb4NX3CGugY5AUgUCAA)

Thank you so much for your help and patience!

2025-05-16 00:18 UTC, trcoffman commented
@MichaelMitchell-at , this is breaking our `withTracking` utility. We use withTracking to easily integrate react-tracking with our component library. 

```
Argument of type 'PropsWithoutRef<TProps & TrackingProps>' is not assignable to parameter of type 'TProps'.
  'PropsWithoutRef<TProps & TrackingProps>' is assignable to the constraint of type 'TProps', but 'TProps' could be instantiated with a different subtype of constraint '{ [key: string]: any; }'.
    Type 'Omit<{ [key: string]: any; } & TrackingProps, "ref">' is not assignable to type 'TProps'.
      'Omit<{ [key: string]: any; } & TrackingProps, "ref">' is assignable to the constraint of type 'TProps', but 'TProps' could be instantiated with a different subtype of constraint '{ [key: string]: any; }'.
Type '({ ref: ForwardedRef<any>; testID: any; } & PropsWithoutRef<TProps & TrackingProps> & { [P in keyof HandlersToAction<Trackables, TProps>]: (event: any) => void; }) | ({ ...; } & ... 1 more ... & { ...; })' is not assignable to type 'IntrinsicAttributes & TProps'.
  Type '{ ref: ForwardedRef<any>; testID: any; } & PropsWithoutRef<TProps & TrackingProps> & { [P in keyof HandlersToAction<Trackables, TProps>]: (event: any) => void; }' is not assignable to type 'IntrinsicAttributes & TProps'.
    Type '{ ref: ForwardedRef<any>; testID: any; } & PropsWithoutRef<TProps & TrackingProps> & { [P in keyof HandlersToAction<Trackables, TProps>]: (event: any) => void; }' is not assignable to type 'TProps'.
      '{ ref: ForwardedRef<any>; testID: any; } & PropsWithoutRef<TProps & TrackingProps> & { [P in keyof HandlersToAction<Trackables, TProps>]: (event: any) => void; }' is assignable to the constraint of type 'TProps', but 'TProps' could be instantiated with a different subtype of constraint '{ [key: string]: any; }'.
```

The only thing I've found that can fix this is simply doing `as TProps` but that feels dirty.

2025-05-16 03:09 UTC, MichaelMitchell-at commented
@trcoffman I think you can change the signature to:
```tsx
export function withTracking<
  Trackables extends TrackablesBase,
  TProps extends { [key: string]: any } & TrackingProps & {ref?: React.Ref<any>},
>(Component: ComponentType<React.PropsWithoutRef<TProps> & {ref?: TProps['ref']}>, config: WithTrackingConfig<Trackables, PropsWithoutRef<TProps>> = {}) {
````