[types/koa__ejs]: create new package inside org
DefinitelyTyped/DefinitelyTyped pull request #70448
Opened 2024-09-04 09:36 UTC by guillenotfound

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/koajs/ejs
- [x] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-09-06 20:27 UTC, andrewbranch requested changes
Yes, go ahead and delete the old koa-ejs package, thanks!

2024-09-07 15:58 UTC, guillenotfound commented
> Yes, go ahead and delete the old koa-ejs package, thanks!

There you go :)

2024-09-09 18:25 UTC, andrewbranch approved these changes

2024-09-10 22:31 UTC, guillenotfound commented
Ready to merge

2024-09-10 22:32 UTC, merged