fix(promise-fn-retry): Change export style, add back jsdoc
DefinitelyTyped/DefinitelyTyped pull request #70572
Opened 2024-09-15 17:08 UTC by hkleungai

- Change `export default` to `export =`
- Remove `undefined` from attributes in `RetryControlOptions`, 
    - These are always provided by the library. See the [library codes](https://github.com/felippemauricio/promise-fn-retry/blob/main/src/index.js#L11-L17).
- Add back jsdoc according to content in readme and comment in `index.js` from the original library.
- Add tests for `options` in `onRetry` callback.

---

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>

2024-09-16 11:02 UTC, Jono-Chang requested changes
Thank you so much for updating this and keeping it up to spec with Definitely Type's standards!
I really appreciate the effort.

I've requested changes, but I'm really just nit picking here.

2024-09-17 02:01 UTC, Jono-Chang approved these changes
Thanks mate.
Looks good to me!

2024-09-23 17:52 UTC, jakebailey approved these changes

2024-09-23 18:36 UTC, hkleungai commented
Ready to merge

2024-09-23 18:36 UTC, merged