[telegram-web-app] add support for Bot API 7.10
DefinitelyTyped/DefinitelyTyped pull request #70581
Opened 2024-09-16 19:02 UTC by sidorko

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X] Test the change in your own code. (Compile and run.)
- [ X [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

If changing an existing definition:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: [<< Recent changes >>](https://core.telegram.org/bots/webapps#september-6-2024)
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-09-16 19:05 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/telegram-web-app/telegram-web-app-tests.ts
1. types/telegram-web-app/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 252f1dffb277ce67f1a418bb4a99da4dafe56fbb
</p>

2024-09-23 20:18 UTC, KnorpelSenf requested changes
Types LGTM, just a few bad docs:

2024-09-23 20:18 UTC, KnorpelSenf commented on types/telegram-web-app/index.d.ts
> +    MainButton: BottomButton;
Please fix the docs. The main button is documented as secondary button and vice-versa now.

2024-09-23 20:18 UTC, KnorpelSenf commented on types/telegram-web-app/index.d.ts
> +    setBackgroundColor(color: "bg_color" | "secondary_bg_color" | "bottom_bar_bg_color" | (string & {})): void;
Same thing here for background color and bottom bar color

2024-09-23 20:33 UTC, KnorpelSenf commented
@sidorko just retry, I don't think the failing CI is related to your changes

2024-09-23 21:02 UTC, KnorpelSenf approved these changes
LGTM, thanks!

2024-09-23 21:02 UTC, KnorpelSenf commented
Ready to merge

2024-09-23 21:03 UTC, KnorpelSenf commented
lol

2024-09-23 21:03 UTC, KnorpelSenf commented
Ready to merge

2024-09-23 21:03 UTC, merged