[Rascal] Add `getConnections()` and `getConnectionDetails()` method types
DefinitelyTyped/DefinitelyTyped pull request #70663
Opened 2024-09-24 11:41 UTC by jasonrowsell

- `ConnectionInfo` interface type
- `Broker.getConnections()` method type: [link to original method](https://github.com/onebeyond/rascal/blob/9fb33da9c1f5323e94d22b7c26c3abf5c52dabf3/lib/amqp/Broker.js#L210)
- `BrokerAsPromised.getConnections()` method type: [link to original method](https://github.com/onebeyond/rascal/blob/9fb33da9c1f5323e94d22b7c26c3abf5c52dabf3/lib/amqp/BrokerAsPromised.js#L53)
- `Vhost.getConnectionDetails()` method type: [link to original method](https://github.com/onebeyond/rascal/blob/9fb33da9c1f5323e94d22b7c26c3abf5c52dabf3/lib/amqp/Vhost.js#L187)

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:
- [x] Provide a URL to documentation or source code which provides context for the suggested changes
  - [Broker.getConnections](https://github.com/onebeyond/rascal/blob/9fb33da9c1f5323e94d22b7c26c3abf5c52dabf3/lib/amqp/Broker.js#L210)
  - [BrokerAsPromised.getConnections](https://github.com/onebeyond/rascal/blob/9fb33da9c1f5323e94d22b7c26c3abf5c52dabf3/lib/amqp/BrokerAsPromised.js#L53)
  - [Vhost.getConnectionDetails](https://github.com/onebeyond/rascal/blob/9fb33da9c1f5323e94d22b7c26c3abf5c52dabf3/lib/amqp/Vhost.js#L187)

2024-09-24 11:47 UTC, carpasse requested changes

2024-09-24 11:47 UTC, carpasse commented on types/rascal/index.d.ts
> +export interface ConnectionInfo {
I would rename this to ConnectionDetails to match the [code](https://github.com/onebeyond/rascal/blob/master/lib/amqp/Vhost.js#L188)

2024-09-24 13:19 UTC, carpasse approved these changes

2024-09-24 16:46 UTC, jakebailey commented
`rascal` is at v20 upstream, but the DT package here is only at v10. Are these new things from a new version of `rascal` such that the DT package here should be bumped to match?

2024-09-25 14:53 UTC, jakebailey commented
Then the version should be bumped to 10.2 to match, at least.

2024-09-25 17:42 UTC, jakebailey requested changes
Marking as needing changes per the above

2024-09-26 09:26 UTC, UlisesGascon approved these changes
LGTM! Thanks for doing this!

Ping @cressie176 for awareness

2024-09-27 16:09 UTC, jakebailey approved these changes

2024-09-27 16:11 UTC, jasonrowsell commented
Ready to merge

2024-09-27 16:12 UTC, merged