Eval estree expression
DefinitelyTyped/DefinitelyTyped pull request #70683
Opened 2024-09-26 09:44 UTC by NITFALL

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [x] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [x] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [x] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

2024-09-26 12:23 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/eval-estree-expression/tsconfig.json
1. types/eval-estree-expression/index.d.ts
1. types/eval-estree-expression/package.json

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 229a9f4a0ae72064a3966d9ac14d83c9b637adf2
</p>

2024-09-26 16:51 UTC, jakebailey requested changes
Please delete the LICENSE and README; the publisher generates these files on publish.

2024-09-27 06:12 UTC, NITFALL commented
> Please delete the LICENSE and README; the publisher generates these files on publish.

Thanks for explaining, files removed

2024-09-27 16:16 UTC, jakebailey commented
You're also missing tests.

2024-09-30 10:49 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/eval-estree-expression/eval-estree-expression-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c1410b545dc08001ab1c6d632c95eee12262f38d
</p>

2024-09-30 16:30 UTC, jakebailey commented on types/eval-estree-expression/index.d.ts
> +export function evaluate(tree: any, context: any, options: any): any;
Is `any` really the best type for these?

In this particular function's case, are you sure it doesn't return at least a `Promise`?

2024-10-02 22:28 UTC, sandersn requested changes

2024-10-02 22:28 UTC, sandersn commented on types/eval-estree-expression/eval-estree-expression-tests.ts
> +import { evaluate } from "./index";
Tests should import as if they were a user of the package:
```suggestion
import { evaluate } from "eval-estree-expression";
```

2024-11-03 01:03 UTC, closed without merging