feat(WebTorrent): add missing 'downloadLimit' and 'uploadLimit' optio…
DefinitelyTyped/DefinitelyTyped pull request #70992
Opened 2024-10-23 20:21 UTC by prostarz

- Added missing 'downloadLimit' and 'uploadLimit' to the WebTorrent Options interface as outlined here https://webtorrent.io/docs

Please fill in this template.

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [X ] Test the change in your own code. (Compile and run.)
- [X] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [X] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [X] Provide a URL to documentation or source code which provides context for the suggested changes: https://webtorrent.io/docs
- [X] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-10-23 20:25 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/webtorrent/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against e2f4a1d520d72730dd8053597dfeb152abd299e5
</p>

2024-10-29 16:43 UTC, RyanCavanaugh requested changes

2024-10-29 16:43 UTC, RyanCavanaugh commented on types/webtorrent/index.d.ts
> +
Remove extraneous whitespace here and on line 132

2024-10-29 21:44 UTC, RyanCavanaugh commented on types/webtorrent/index.d.ts
> +
and on line 132

2024-10-30 16:32 UTC, RyanCavanaugh approved these changes

2024-10-30 18:33 UTC, prostarz commented
Ready to merge

2024-10-30 18:34 UTC, merged