[lodash] convert _.includes to type guard
DefinitelyTyped/DefinitelyTyped pull request #71051
Opened 2024-10-31 14:17 UTC by Ha-limLee

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <https://lodash.com/docs/4.17.15#includes>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-11-01 13:12 UTC, aj-r requested changes
The benefit of the old signature is that it catches bugs early. For example, it's pretty much always a mistake to search for a string in an array of numbers. Can you elaborate on why this is inconvenient?

2024-11-02 03:28 UTC, Ha-limLee commented
> The benefit of the old signature is that it catches bugs early. For example, it's pretty much always a mistake to search for a string in an array of numbers. Can you elaborate on why this is inconvenient?

I updated [PR description](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71051#issue-2626977830) to address that. Please check it once again. @aj-r

2024-11-06 11:50 UTC, aj-r commented
> I updated [PR description](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71051#issue-2626977830) to address that. Please check it once again. @aj-r

Thanks, I see how this could be useful. However, I'm worried that this would make the type too loose, and it would fail to catch some legitimate issues in people's code. So I would still prefer to avoid this change. Note that you're free to implement your own version of `includes` in your project that acts as a type guard if you want.

2024-11-07 13:08 UTC, Ha-limLee commented
> However, I'm worried that this would make the type too loose, and it would fail to catch some legitimate issues in people's code.

Okay, that's fair. I'll close this PR.

2024-11-07 13:08 UTC, closed without merging