Revert "Revert "[node] Add generics to static members of EventEmitter""
DefinitelyTyped/DefinitelyTyped pull request #71060
Opened 2024-11-01 02:25 UTC by ckohen

Reverts #71054 removing the static changes that require further review. <Future PR number> will cover that while this recovers the other major improvements.

2024-11-02 23:32 UTC, Renegade334 commented
Note a separate reported issue, #71059.

2024-11-03 15:14 UTC, Renegade334 reviewed
I'm struggling to recall from the original discussion – what was the advantage of adding separate overloads for `<T extends keyof...>` and `<T extends string | symbol>` for the emitter methods?

The reason for asking is because there's a specific compiler quirk relating to methods which are both generic and overloaded, when called on a union:

```ts
declare class Base {
    method(): this;

    overloadedMethod(): this;
    overloadedMethod(): this;

    methodWithTypeProperty<T>(): this;

    overloadedMethodWithTypeProperty<T>(): this;
    overloadedMethodWithTypeProperty<T>(): this;
}

declare class X extends Base {
    property: true;
}

declare class Y extends Base {
    property: false;
}

declare const either: X | Y;

either.method(); // X | Y
either.overloadedMethod(); // X | Y

either.methodWithTypeProperty(); // X | Y
either.overloadedMethodWithTypeProperty(); // ERROR: TS2349
```

Instead of returning a union type, the compiler attempts to resolve the overloads to a mutually compatible signature. In this instance, since the `this` types of the two classes are not compatible with one another, the compiler raises an error. This specific resolution behaviour is deliberate within `resolveCallExpression()`, and unfortunately the definitions as they stand invoke that behaviour.

This is the root cause of #71059. That specific error could be eliminated within @types/node by adding `off()` overloads for derived API emitters, but the point is that this has the potential to break _any_ case where unions of emitters appear, unless non-obvious workarounds are employed by the consumer. It might not be a common pattern, but it only took a couple of days for it to be reported as an issue.

Are there cases where only having a single method definition (with the `extends string | symbol` type parameter) fails?

2024-11-03 21:04 UTC, ckohen commented
That is not the only root cause, and has nothing to do with the `this` type. This is observable without classes
```ts
type Foo<T> = {
    callable<K extends T>(str: K): number;
}

type Bar<T> = {
    callable<K extends T>(str: K): string;
}

type FooBar = Foo<string> | Bar<'abc'>;
declare const obj2: FooBar;
obj2.callable('abc'); // TS2349
```

It does work with the single definition, but that defeats the purpose of this PR.
The second overload allows IntelliSense to suggest valid events which is a critical piece of replacing the existing tooling for adding eventmaps. Without this, I expect to see very little adoption of native eventmaps which makes it harder on the compiler for no reason.

2024-11-28 04:14 UTC, jakebailey commented
Given this is back on the table, does the PR contain tests from all of the breaks from last time to make sure that we aren't regressing anything a second time?

2024-12-03 08:55 UTC, ckohen commented
It seems this PR is illustrating some of the major shortcomings (and tbh bugs) of typescript. 

You neglected the assignability issue that applies to instances that have generics set which has nothing to do with what you've mentioned. I have an idea to fix what you've described (remove the generic on the second overload) but it will not fix the assignability issue completely due to the other bug I mentioned. Will update when I know if it works.

2024-12-24 00:59 UTC, ckohen commented
Alright, this should work. It's probably a much easier diff to read now too :). To summarize, this PR effectively just fixes the over strictness of some parts of the original generic system (overall just aligns everything to runtime much better) and prepares for adding generics to static members by using clearer names etc.. and adding the tests that should pass once that time comes.

It also adds tests for all of the bugs that were brought up the first time the static generics were added (that were related to the changes relevant here, obviously not the static generics as that was not a bug but a minimum target mismatch).

2025-01-28 19:52 UTC, jakebailey reviewed
I still feel pretty wary about this PR given how it's had to be reverted... (sorry)

I'm still hoping for some more thoughts from people that work on the Node types (since I am not super plugged in here)

2025-01-28 19:52 UTC, jakebailey commented on types/node/events.d.ts
> +    class EventEmitter<Events extends EventMap<Events> = {}> {
Is this declaration backwards compatible for those who had previously used a tuple here? I'm noticing that `DefaultEventMap` is `[never]`, but the new default is `{}`.

2025-01-28 21:42 UTC, ckohen commented on types/node/events.d.ts
> +    class EventEmitter<Events extends EventMap<Events> = {}> {
a tuple was never acceptable, this default event map was a hack

2025-01-28 21:44 UTC, ckohen commented
The reason I changed the name is that this no longer has the major point of contention that caused the reversion. I will be putting that in a separate PR, but this is necessary work for that PR to work and generally improves the accuracy of the types

2025-01-30 20:06 UTC, jakebailey commented on types/node/events.d.ts
> +    class EventEmitter<Events extends EventMap<Events> = {}> {
I mainly ask because I went scouring over GitHub to find people who had parameterized `EventEmitter` and found a couple of cases where they were tuples...

2025-01-31 00:50 UTC, Renegade334 reviewed
I think the major improvement of this changeset is the graceful handling of events that don't correspond to an entry in the event map. In theory, this should improve extensibility etc.

Some specific thoughts below.

2025-01-31 00:50 UTC, Renegade334 commented on types/node/events.d.ts
> +                ): Array<Listener<Events, EventName>>;
Also, if we get rid of `Function` here, then we should probably also do the same for the `getEventListeners` static method, and presumably the builtin event map as well?

2025-01-31 00:50 UTC, Renegade334 commented on types/node/events.d.ts
> +                /* eslint-enable @definitelytyped/no-unnecessary-generics */
Most of the multi-generic-overload signatures have been leaned down, but there are still a couple remaining (here and `emit`). Can these use `EventNameParam` as well?

As before, these overloaded methods will currently raise a compiler error if called on unions of emitters (#71059).

2025-01-31 00:50 UTC, Renegade334 commented on types/node/events.d.ts
> +        : EventName | EventNames<Events>;
I'm guessing this is an Intellisense hack?

Slight issue as things stand, in that the methods that use it don't constrain the parameter type to `string | symbol`. For example, `.on(42, () => {})` is considered valid.

2025-01-31 00:50 UTC, Renegade334 commented on types/node/events.d.ts
> +        >;
What sort of usage case did you have in mind? The test example you mentioned seems quite niche...!

2025-01-31 01:31 UTC, Renegade334 commented on types/node/events.d.ts
> +    class EventEmitter<Events extends EventMap<Events> = {}> {
If we're using the same search terms, those look to be namesakes from other APIs (Angular in particular)

2025-02-21 02:14 UTC, ckohen commented on types/node/events.d.ts
> +                eventNames(): Array<(string | symbol)> & Array<EventNames<Events>>;
This may be left-over from an earlier changeset, but I recall this did still help with something, probably intellisense though I can't see how it would now....I'll take another look at this

2025-02-21 02:19 UTC, ckohen commented on types/node/events.d.ts
> +                ): Array<Listener<Events, EventName>>;
Honestly this is why I was most surprised the original PR got merged. The Function type causes so many issues that I had to at least propose this change as an option.

I removed all touches of the static side for this PR, but could probably get away with that one if we keep this.

As for in a major...should've happened for v22 ideally (as that wasn't merged before the og pr was made) but there's one on the horizon for v24 at this point (~3 months)

2025-02-21 02:21 UTC, ckohen commented on types/node/events.d.ts
> +        [EventEmitter.captureRejectionSymbol]?(error: Error, event: string | symbol, ...args: any[]): void;
It made sense to do it everywhere, this one certainly wouldn't be hit...like ever so if we are only really concerned about methods that users call than there's no need for it yes.

2025-02-21 02:24 UTC, ckohen commented on types/node/events.d.ts
> +                /* eslint-enable @definitelytyped/no-unnecessary-generics */
Pretty sure I put tests in for all of this, and if not I did at least test it because I was worried about that. I'll add test cases for this if they're missing (and fix if I did just miss these)

2025-02-21 02:33 UTC, ckohen commented on types/node/events.d.ts
> +        : EventName | EventNames<Events>;
This allows intellisense to provide useful suggestions (self-documenting) rather than nothing yes.

I must've tried that case with a default event map cause it constrains in that case but not the other 🤦. Can add extends constraints to fix.

2025-03-17 01:35 UTC, ckohen commented on types/node/events.d.ts
> +                eventNames(): Array<(string | symbol)> & Array<EventNames<Events>>;
Interestingly enough, it does indeed narrow the types. I can't tell you exactly why, but `emitter.eventNames()[0]` does not compare to `''` according to TS when a generic is in use. Given that arbitrary events are allowed, this isn't technically correct though and I'd be inclined to not narrow this return type, does that seem appropriate?

2025-03-17 07:31 UTC, Renegade334 commented on types/node/events.d.ts
> +                eventNames(): Array<(string | symbol)> & Array<EventNames<Events>>;
I think so. Sorry, should have said "not desirable" rather than "not possible".

2025-03-18 05:07 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/node/events.d.ts
1. types/node/v18/events.d.ts
1. types/node/v20/events.d.ts
1. types/node/test/events_generic.ts
1. types/node/v18/test/events_generic.ts

<details>
<summary>as well as these 1 other files...</summary>
<p>types/node/v20/test/events_generic.ts</p>
</details>


Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 9da246e9b5c367355973f60df81f6ce57c90708a
</p>

2025-04-03 23:34 UTC, jakebailey commented
@Renegade334 are you satisfied with the changes so far?

2025-04-04 09:45 UTC, Renegade334 commented
Pretty good, I think. Just a couple of thoughts:

- My own $0.02 is still in favour of removing event map awareness from the `[Symbol.for('nodejs.rejection')]` method – this is designed to be overridden by users, not called, and this only adds potential for the compiler to complain about a signature mismatch where the override is defined. (I appreciate that this was carried-over behaviour from before, but the conversion to multiple generic overload signatures would I suspect cause more trouble.)
- Should a `DefaultEventMap` alias be kept, and exported as a utility type?
  - I'm thinking of cases where libraries may wish to implement emitters that are intended to be user-extended (eg. `abstract class AbstractEmitter<T extends ... = ???> extends EventEmitter<T> { ... }`), where the intermediate emitter class will need to define a type parameter default. Using a named type rather than `{}` would be more descriptive, and would also future-proof those definitions against any change to the default EventEmitter parameter.
  - This would also (I believe?) change the displayed type of a non-event-mapped emitter from `EventEmitter<{}>` back to `EventEmitter<DefaultEventMap>`, which probably makes more sense to the casual consumer.

2025-04-04 11:05 UTC, Renegade334 commented on types/node/events.d.ts
> +                ): boolean;
Can this be changed from the doubled signature to a single one using `EventNameParam`?

2025-04-12 01:22 UTC, ckohen commented on types/node/events.d.ts
> +                ): boolean;
Only if numbers / bigints are truly unsupported. They are allowed as object keys and event emitters will technically allow anything that can be accessed by index. Combining these makes any number / bigint keys emit args take `...any[]` instead of what their eventmap describes.

2025-04-23 13:08 UTC, Bashamega requested changes
Would be better if we brake down this huge PR in smaller PRs

2025-04-23 14:18 UTC, jakebailey commented
@Bashamega Huh? I don't think that's possible.

2025-05-03 13:31 UTC, gordonmleigh commented
I wanted to chip in here because I'm keen to see this feature moving forward since the currently shipped version is unusable. Hope you don't mind, and thanks to everyone who has put in effort here so far!

One of the main issues with the shipped approach is that `EventListener<X>` isn't assignable to `EventListener<Y>` when `X` is assignable to `Y`. In the future when e.g. the `node:stream` classes have `EventMap` types specified, this lack of covariance would prevent us from assigning e.g. a `Duplex` to a `Readable`. This PR partly addresses this, by changing the return type of `eventNames()` to `Array<string|symbol>`, but the return types of `listeners()` and `rawListeners()` would also need to be widened to `Array<Function>` or similar. I think it would be important to add a test that enforces covariance generally. IMO trading off some exactness in the types for much improved usability would be a worthwhile goal.

I feel the conditional types are unnecessary. The implementation in this PR seems to be using `{}` as a sort of symbol, which it then needs to detect again in the conditionals to give the correct types for each location. If the "default" map type is instead chosen to be `Record<string | symbol, unknown[]>` then it would better capture the semantics (i.e. we want to allow _all_, arbitrary, events, not _none_). The types are also then greatly simplified:

```typescript
type EventMap<Events> = Record<keyof Events, unknown[]>;
type DefaultEventMap = Record<string | symbol, unknown[]>;

interface EventEmitterBuiltInEventMap {
  newListener: [eventName: string | symbol, listener: Function];
  removeListener: [eventName: string | symbol, listener: Function];
}

type BuiltInEvent = keyof EventEmitterBuiltInEventMap;

type Listener<
  Events extends EventMap<Events>,
  EventName extends keyof Events | BuiltInEvent,
> = (...args: (Events & EventEmitterBuiltInEventMap)[EventName]) => void;

export interface EventEmitter<
  Events extends EventMap<Events> = DefaultEventMap,
> {
  // all the listener-related signatures are now much simpler
  addListener<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName,
    listener: Listener<Events, EventName>
  ): this;
  on<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName,
    listener: Listener<Events, EventName>
  ): this;
  once<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName,
    listener: Listener<Events, EventName>
  ): this;
  removeListener<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName,
    listener: Listener<Events, EventName>
  ): this;
  off<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName,
    listener: Listener<Events, keyof Events>
  ): this;
  removeAllListeners<EventName extends keyof Events | BuiltInEvent>(
    eventName?: EventName
  ): this;
  prependListener<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName,
    listener: Listener<Events, EventName>
  ): this;
  prependOnceListener<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName,
    listener: Listener<Events, EventName>
  ): this;

  // emit doesn't need an extra overload
  emit<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName,
    ...args: (Events & EventEmitterBuiltInEventMap)[EventName]
  ): boolean;

  // listeners and rawListeners need to have a wider return type for covariance to work
  listeners<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName
  ): Array<Listener<Events, EventName>>;
  rawListeners<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName
  ): Array<Listener<Events, EventName>>;

  // this has already been widened in this PR
  eventNames(): Array<string | symbol>;

  setMaxListeners(n: number): this;
  getMaxListeners(): number;

  listenerCount<EventName extends keyof Events | BuiltInEvent>(
    eventName: EventName,
    listener?: Listener<Events, EventName>
  ): number;
}

```

2025-06-10 03:01 UTC, ckohen commented
@gordonmleigh I would love to go that route, however most of your suggestion is unfortunately incompatible with the existing ecosystem. We need to preserve the existing interface for all cases that are not using the native event map implementation (which is most).

Emit doesn't actually need the extra overload that it currently has, it is just easier to wrap your head around with it split (it's the only thing that doesn't run into covariance issues with the overload+generic issues), however it will likely move to a similar workaround as the rest of the methods.

I have kept your suggestion for widening listeners and will add further tests to ensure covariance (there are a few already from the original merge of this)

2025-07-03 06:59 UTC, jakebailey commented
Not yet, bot

2025-07-29 23:35 UTC, jakebailey commented
I'm back in the rotation this week and this PR is still here; once again I ask if there's anything left here. ☹️

2025-08-18 05:27 UTC, Renegade334 commented
We are two months off Node.js v25, a non-LTS release. I wonder if it might be an idea to include this changeset in @types/node v25, and only v25, as a litmus test.

Although the more issues this work has highlighted, I'm more and more of the opinion that this should never have been a feature for @types/node in the first place, and would have been far better suited to userland 😄

2025-08-18 06:10 UTC, ckohen commented
It's kinda sucky either way. You really can't do this with native non-generic emitters well (and half the packages that do / try to miss out on important methods and never keep up with the changes). But this solution is still technically half-baked as it's missing static methods and has a few things that are technically incorrect but help with assignability that is necessary.

The main purpose that I had made this PR for was because the way discord.js did events (arguably as proper as possible) broke (cause it was technically a bug), buts since this didn't go as planned we've moved to https://www.npmjs.com/package/@vladfrangu/async_event_emitter which is a near 1:1 replication of the built in EE but built to support async and event contracts (which is part of why I slowed down on pushing this a bit ago).

This is no longer a huge priority for me, but I still kept working on it because so many packages have done this poorly and it's really frustrating to deal with that sometimes.

2025-09-30 02:23 UTC, jakebailey commented
Why... Didn't the bot warn like it's supposed to....

2025-09-30 06:26 UTC, Renegade334 commented
FWIW, I'm looking at probably rolling this changeset into v25 as a major change.

2025-09-30 08:20 UTC, jakebailey commented
26? I don't think we've ever done an odd node types

2025-09-30 08:45 UTC, Renegade334 commented
Used to be the case, but the "only-LTS" practice started around v14-v16ish, due essentially to the maintenance burden AFAICT. The desire from the community to access new features from the active release meant that these always ended up as a blur of (vN..vN+1) anyway, which isn't ideal for a supposed LTS branch.

2025-10-13 23:51 UTC, ckohen commented
Superseded by #73882

2025-10-13 23:51 UTC, closed without merging