Add children to MarkerClusterGroupProps in react-leaflet-markercluster
DefinitelyTyped/DefinitelyTyped pull request #71086
Opened 2024-11-04 22:49 UTC by bhubert

Please fill in this template.

- [ x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x ] Test the change in your own code. (Compile and run.)
- [ x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

- [ x] Provide a URL to documentation or source code which provides context for the suggested changes: https://github.com/yuzhva/react-leaflet-markercluster
- [x ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-12-06 18:09 UTC, charlieforward9 commented
This needs to get merged! I am experiencing a build error that relates to this.

`Property 'children' does not exist on type 'IntrinsicAttributes & MarkerClusterGroupProps'.`

Seems like it is because in MarkerClusterGroupProps, children is defined as `children: JSX.Element | JSX.Element[];` and JSX is deprecated?

The CI check fails because of [this line](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/c39248e33cd73e2defa7a0d9e182ed90fb48c8aa/attw.json#L1463), that needs to be removed. Can you remove it to get the check to pass @bhubert ?

2024-12-06 21:54 UTC, charlieforward9 commented
Since [4.2.0](https://www.npmjs.com/package/react-leaflet-markercluster/v/4.2.0), you can directly access the `MarkerClusterGroup` types from the [source repo](https://github.com/YUzhva/react-leaflet-markercluster). 

With this update, [this package](https://www.npmjs.com/package/@types/react-leaflet-markercluster) should be deprecated.

2024-12-06 21:59 UTC, bhubert commented
@charlieforward9 i didt the modification you asked, but in fact you are saying that i should just drop the PR and upgrade your lib in my project ?

2024-12-06 22:03 UTC, charlieforward9 commented
@bhubert yes I was not expecting the move of these types into the source repo to be so easy, so I just went ahead and added them in. 

You could adjust this PR to remove these types from here since the source takes care of that now. 

Let me know if theres any issues with the source repo.

Thanks!

2024-12-07 09:17 UTC, bhubert commented
@charlieforward9 ok i removed everything so ! it was not what i was expecting with this PR lol but it's still a contribution

2024-12-07 15:44 UTC, charlieforward9 commented
I appreciate you getting this done! 🚀

2024-12-30 23:10 UTC, gabritto requested changes
Please follow the instructions in https://github.com/DefinitelyTyped/DefinitelyTyped?tab=readme-ov-file#removing-a-package to properly remove this DT package. Thanks.

2024-12-31 08:34 UTC, bhubert commented
@gabritto it's done, sorry for having miss the guide

2025-01-02 16:53 UTC, iisaduan approved these changes

2025-01-02 20:53 UTC, bhubert commented
Ready to merge

2025-01-02 20:53 UTC, merged