feat(mdx/types): enhance MDXComponents type annotations to be more intellisense-friendly
DefinitelyTyped/DefinitelyTyped pull request #71184
Opened 2024-11-16 01:42 UTC by yuriuliam

# What's this about?

Working on a Next.JS project w/ MDX, following the instructions for the latest 

# Checklist

- [X] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [X] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [X] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-11-18 09:42 UTC, wooorm commented
> P.s. the Next.js documentation is wrong. useMdxComponents() doesn’t take any arguments.

it does for the existing providers: https://github.com/mdx-js/mdx/blob/2b5ff6954475be3771c679f957f7cb49ded1df97/packages/react/lib/index.js#L39.
`@mdx-js/mdx` compile to code that passes an argument anymore tho

2024-11-18 11:07 UTC, remcohaszing commented
> > P.s. the Next.js documentation is wrong. useMdxComponents() doesn’t take any arguments.
>
> it does for the existing providers: https://github.com/mdx-js/mdx/blob/2b5ff6954475be3771c679f957f7cb49ded1df97/packages/react/lib/index.js#L39.

Yes, it’s called in https://github.com/mdx-js/mdx/blob/2b5ff6954475be3771c679f957f7cb49ded1df97/packages/react/lib/index.js#L75

> `@mdx-js/mdx` compile to code that passes an argument anymore tho

I interpreted this as _“`@mdx-js/mdx` **doesn’t** compile to code that passes an argument anymore tho”_. This is the situation in Next.js’ `mdx-components` file. `useMdxComponents` is called from MDX files without arguments. That doesn’t stop users to call the function elsewhere with any arguments they want of course.

2024-11-18 12:05 UTC, wooorm commented
>  However, mdx-components.ts is an alternative to @mdx-js/react for use in a situation where useMdxComponents is always called without arguments.

Practically, likely.
But the maintainers from Next.js can do what they want with their own APIs?
They could use it in other places?
All I am saying is, could be a bug, could be intentional.

2024-11-19 04:55 UTC, yuriuliam commented
Thanks for replying back! I would make a test myself using the official documentation, but seems it's not necessary anymore.

It might be the case [remcohaszing's proposal](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71184#issuecomment-2482414296) fits! Somewhy my IDE was not understanding the type annotations for `function/expression returns`, but changing the `typescript` to the project's one (`v5.6.3`) solved it!
![image](https://github.com/user-attachments/assets/f5046e50-80a6-4bd8-9644-1671b77c6ff9)

This proposal would be useful in a `keyof` inference only, which... I don't see a common case for that.

For the still open questions:

> What version of TypeScript are you using?

I'm using NextJS' v15 tsconfig from `create-next-app@latest`

###### tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["DOM", "DOM.Iterable", "ESNext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "~/*": ["./src/*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

2024-11-26 10:05 UTC, remcohaszing commented
So as I understand this doesn’t really add value anymore and can be closed? I’m still open to merging if there are real benefits.

---

Typically you should just remove the `include` property in your `tsconfig.json`. However, since Next.js enforces you to specify add, you’ll want to add `**/*.mdx` to the array to benefit from the `MDXProvidedComponents` type.

2024-11-27 03:29 UTC, yuriuliam commented
Yep! We can close this one. I don't see much benefits we can have besides `keyof` usage, but it sounds like an edge-case, so all good!

Thanks for the tip as well, I'm running into some stuff, but it solved my problem already!

2024-11-27 13:29 UTC, ChristianMurphy requested changes
Per the discussion above this is not needed

2024-11-28 00:39 UTC, closed without merging