add types for react-native-file-type
DefinitelyTyped/DefinitelyTyped pull request #71180
Opened 2024-11-15 11:25 UTC by InkAndSteel

This pull request adds TypeScript type definitions for the react-native-file-type library. The type definitions include:

FileType function: An asynchronous function that accepts a file URI and returns a FileTypeResult containing the MIME type and file extension or null if not detected.

FileTypeResult interface: Defines the structure of the returned result, including:
- ext: The file extension (e.g., jpg).
- mime: The MIME type (e.g., image/jpeg).

2024-11-24 18:38 UTC, rbuckton commented on types/react-native-file-type/.eslintrc.json
> +        "@definitelytyped/no-any-union": "off"
Why was this necessary?

2024-11-25 20:58 UTC, jakebailey requested changes
You need tests for your code, and please remove the eslintrc, which is doing nothing.

2024-11-25 20:58 UTC, jakebailey commented on types/react-native-file-type/.eslintrc.json
> +        "@definitelytyped/no-any-union": "off"
Certainly not.

2024-11-27 15:58 UTC, InkAndSteel commented on types/react-native-file-type/.eslintrc.json
> +        "@definitelytyped/no-any-union": "off"
is removed

2024-11-27 16:07 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/react-native-file-type/react-native-file-type-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 6cdfb367d6127b55ccf48cae60306b9ee9b49f1a
</p>

2024-11-27 18:05 UTC, jakebailey approved these changes
I'll OK this, but I will note that `react-native-file-type` is technically quite broken because it publishes an ESM `index.js` while not marking itself as `"type": "module"`. It's not clear this package would ever work outside of bundling. Use at your own risk.

https://publint.dev/react-native-file-type@1.0.0

2024-11-27 18:29 UTC, InkAndSteel commented
> I'll OK this, but I will note that `react-native-file-type` is technically quite broken because it publishes an ESM `index.js` while not marking itself as `"type": "module"`. It's not clear this package would ever work outside of bundling. Use at your own risk.
> 
> https://publint.dev/react-native-file-type@1.0.0

Thx! :)

2024-12-02 09:05 UTC, InkAndSteel commented
Ready to merge

2024-12-02 22:45 UTC, sandersn approved these changes

2024-12-04 16:06 UTC, InkAndSteel commented
Ready to merge

2024-12-04 16:07 UTC, merged