fix(node): v8 deserialize accepts Buffer, TypedArray and DataView as input
DefinitelyTyped/DefinitelyTyped pull request #71243
Opened 2024-11-25 08:28 UTC by peterhirn

…input

see https://nodejs.org/api/v8.html#v8deserializebuffer

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: [<<url here>>](https://nodejs.org/api/v8.html#v8deserializebuffer)
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-11-25 20:35 UTC, jakebailey requested changes
You should be adding tests, and also updating older versions of the Node types if this also applies to them.

2024-11-25 21:49 UTC, Renegade334 requested changes

2024-11-25 21:49 UTC, Renegade334 commented on types/node/v8.d.ts
> +    function deserialize(buffer: Buffer | NodeJS.TypedArray | DataView): any;
```suggestion
    function deserialize(buffer: NodeJS.ArrayBufferView): any;
```
`NodeJS.ArrayBufferView` is the canonical alias.

2024-11-26 04:35 UTC, peterhirn commented
> You should be adding tests, and also updating older versions of the Node types if this also applies to them.

Looks like the functions signature is stable since Node v10: https://nodejs.org/docs/latest-v10.x/api/v8.html#v8_v8_deserialize_buffer

Please take a look at my tests before I copy the fix to v16/18/20.

2024-11-26 07:18 UTC, Renegade334 commented
> Please take a look at my tests before I copy the fix to v16/18/20.

`ArrayBuffer` and `string` are "buffery" so definitely good to test; `number` is probably unnecessary.

2024-11-27 20:54 UTC, jakebailey approved these changes

2024-11-28 05:37 UTC, peterhirn commented
Ready to merge

2024-11-28 05:38 UTC, merged