fix(phoenix-live-view): add metadata to SocketOptions
DefinitelyTyped/DefinitelyTyped pull request #71265
Opened 2024-11-26 18:30 UTC by greg-freewave

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

Adds the `metadata` property to `SocketOptions` which can be found here: https://github.com/phoenixframework/phoenix_live_view/blob/main/assets/js/phoenix_live_view/live_socket.js#L39 and here https://hexdocs.pm/phoenix_live_view/bindings.html#click-events

@francois-codes , @pzingg

2024-11-26 18:33 UTC, chess555 approved these changes

2024-11-26 18:40 UTC, francois-codes requested changes
Hey @greg-freewave Thank you for this :) 

I'll let @pzingg  review, but I think you could provide a more precise type than `object` ? 

I mean it's not wrong, but here we can see that metadata is an object like

```typescript
Record<string, (event: Event, el: Element) => Record<string, unknown>>
```

it would provide better completion & typechecking I believe

2024-11-26 18:41 UTC, greg-freewave commented
@francois-codes I'm no typescript pro, just getting this working as I can't currently add metadata to the call with these type definitions. If you have something you want me to put in there i'm happy to but I don't know what it would be myself.

2024-11-26 19:31 UTC, francois-codes commented
@greg-freewave 

you can try [this](https://www.typescriptlang.org/play/?ts=4.1.5#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBVDtUAAWUgqAY3Dq4gAvKBHpAEGRuAAeQSoSicZj8AAUkHyoAA0pA8MDHNwAKJ6bb8GBiuXuaEASlATIAfKz2fBOTy+cN+Fx4gMJJwdTrgghOLzQMg6Qy6WKaS7GdrQABvRQlWDQdTxMUisWS6XwWUKlE0AA+1I4gkgMaV4OgqvVsa1ut9-pKoCcqHxXj9BYLsD50AjYsgAUrZGrUt4+fLzoYNfBAXbEZb5ZK3FpDExtYCg7pmNAcYTAEY+wWAL75pdLoA)

in your first commit, you added in the test an object of the same shape than the one in the phoenix doc you linked. You can add that back and check that it works, but according to the playground above, it looks like it does

2024-11-26 20:40 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/phoenix_live_view/phoenix_live_view-tests.ts
1. types/phoenix_live_view/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against f8d4da0f366c2eaaf79251226db955ec57733613
</p>

2024-11-26 22:12 UTC, greg-freewave commented
@francois-codes i think i got it all in there, whatcha think?

2024-11-27 02:39 UTC, pzingg commented
@greg-freewave @francois-codes If you want to go the extra mile, try to give better typings for all of these possible options for the LiveSocket constructor (from live_socket.js):

```javascript
 * @param {Object} [opts] - Optional configuration. Outside of keys listed below, all
 * configuration is passed directly to the Phoenix Socket constructor.
 * @param {Object} [opts.defaults] - The optional defaults to use for various bindings,
 * such as `phx-debounce`. Supports the following keys:
 *
 *   - debounce - the millisecond phx-debounce time. Defaults 300
 *   - throttle - the millisecond phx-throttle time. Defaults 300
 *
 * @param {Function} [opts.params] - The optional function for passing connect params.
 * The function receives the element associated with a given LiveView. For example:
 *
 *     (el) => {view: el.getAttribute("data-my-view-name", token: window.myToken}
 *
 * @param {string} [opts.bindingPrefix] - The optional prefix to use for all phx DOM annotations.
 * Defaults to "phx-".
 * @param {Object} [opts.hooks] - The optional object for referencing LiveView hook callbacks.
 * @param {Object} [opts.uploaders] - The optional object for referencing LiveView uploader callbacks.
 * @param {integer} [opts.loaderTimeout] - The optional delay in milliseconds to wait before apply
 * loading states.
 * @param {integer} [opts.maxReloads] - The maximum reloads before entering failsafe mode.
 * @param {integer} [opts.reloadJitterMin] - The minimum time between normal reload attempts.
 * @param {integer} [opts.reloadJitterMax] - The maximum time between normal reload attempts.
 * @param {integer} [opts.failsafeJitter] - The time between reload attempts in failsafe mode.
 * @param {Function} [opts.viewLogger] - The optional function to log debug information. For example:
 *
 *     (view, kind, msg, obj) => console.log(`${view.id} ${kind}: ${msg} - `, obj)
 *
 * @param {Object} [opts.metadata] - The optional object mapping event names to functions for
 * populating event metadata. For example:
 *
 *     metadata: {
 *       click: (e, el) => {
 *         return {
 *           ctrlKey: e.ctrlKey,
 *           metaKey: e.metaKey,
 *           detail: e.detail || 1,
 *         }
 *       },
 *       keydown: (e, el) => {
 *         return {
 *           key: e.key,
 *           ctrlKey: e.ctrlKey,
 *           metaKey: e.metaKey,
 *           shiftKey: e.shiftKey
 *         }
 *       }
 *     }
 * @param {Object} [opts.sessionStorage] - An optional Storage compatible object
 * Useful when LiveView won't have access to `sessionStorage`.  For example, This could
 * happen if a site loads a cross-domain LiveView in an iframe.  Example usage:
 *
 *     class InMemoryStorage {
 *       constructor() { this.storage = {} }
 *       getItem(keyName) { return this.storage[keyName] || null }
 *       removeItem(keyName) { delete this.storage[keyName] }
 *       setItem(keyName, keyValue) { this.storage[keyName] = keyValue }
 *     }
 *
 * @param {Object} [opts.localStorage] - An optional Storage compatible object
 * Useful for when LiveView won't have access to `localStorage`.
 * See `opts.sessionStorage` for examples.
*/
```

2024-11-27 03:53 UTC, pzingg commented
Looking at the live_socket.js source code, I think all the events that LiveView queries for metadata are listed below. 'focusin' and 'focusout' are special LiveSocket event names, mapped to 'focus' and 'blur' DOM events. 

Also, can EventCallback be simpler, more generic like this?

```typescript
export type LiveSocketEventName = 'keyup' | 'keydown' | 'focusin' | 'focusout' | 'blur' | 'focus' | 'click'

export type EventCallback = (e: Event, el: HTMLElement) => object

export type Metadata = Record<LiveSocketEventName, EventCallback>
```

2024-11-27 05:08 UTC, francois-codes requested changes

2024-11-27 05:08 UTC, francois-codes commented on types/phoenix_live_view/index.d.ts
>      longPollFallbackMs?: number | undefined;
I missed that yesterday, but `prop?: SomeType | undefined` is redundant.
Optional means it's already maybe undefined, so there's no need to put both

2024-11-27 05:22 UTC, francois-codes commented
> Looking at the live_socket.js source code, I think all the events that LiveView queries for metadata are listed below. 'focusin' and 'focusout' are special LiveSocket event names, mapped to 'focus' and 'blur' DOM events.
> 
> Also, can EventCallback be simpler, more generic like this?
> 
> ```ts
> export type LiveSocketEventName = 'keyup' | 'keydown' | 'focusin' | 'focusout' | 'blur' | 'focus' | 'click'
> 
> export type EventCallback = (e: Event, el: HTMLElement) => object
> 
> export type Metadata = Record<LiveSocketEventName, EventCallback>
> ```


@pzingg  I agree it would be nice to add types for all these properties, but I don't think it falls in the scope of this PR. I can give it a go later.

It's a good idea to narrow down the list of event like you suggest, thanks for collecting them in the source code, looks like you got them all :)

however, simplifying the event callback with only Event may not be enough. Certain properties are only on classes that extend Event (like ctrlKey given in the example, it doesn't exist in Event or in FocusEvent), so you'd have to either cast or add guards or `e instanceof KeyboardEvent` for instance, to make the compiler happy when you try to access these properties which you know are there. 

it's less elegant, but since there is a limited list of events, and we know what the callback is for all of them, the simplest approach might be to list all the valid callbacks with their specific callback type. like this

```typescript
interface Metadata {
  click?: (e: MouseEvent, el: Element) => Record<string, unknown>
  keydown?: (e: KeyboardEvent, el: Element) => Record<string, unknown>
  focus?: (e: FocusEvent, el: Element) => Record<string, unknown>
 // etc...
}

```

2024-12-05 04:17 UTC, greg-freewave commented
@francois-codes @pzingg this is all a bit too much for me. I don't really know what I'm doing here so I'd just be copy-pasta-ing at best. I'm not going to do that. How do you guys want to proceed? It's no skin off my back to either leave this PR up or close it. Lemme know.

I'd imagine other folks that wants to use these types are going to need the metadata field at some point so the issue will come up again but ultimately what do I know.

2025-01-05 06:45 UTC, closed without merging