added missing  interactionMode?: XRInteractionMode
DefinitelyTyped/DefinitelyTyped pull request #71301
Opened 2024-11-30 23:12 UTC by cyango

interactionMode was missing. See ref:
https://www.w3.org/TR/webxr-ar-module-1/#xrinteractionmode-enum

2024-12-06 12:47 UTC, RaananW requested changes

2024-12-06 12:47 UTC, RaananW commented on types/webxr/index.d.ts
> +
```suggestion
type XRInteractionMode = "screen-space" | "world-space";
```

We don't use enums but types. there is no XRInteractionMode namespace, and it has no ScreenSpace nor WorldSpace members.

2024-12-09 13:30 UTC, RaananW approved these changes

2024-12-12 05:51 UTC, RaananW commented
Hi @cyango , if you update the test file, it would be simpler to merge.

2025-01-14 11:27 UTC, sorskoot commented
Ready to merge

2025-01-14 11:28 UTC, merged