[aws-lambda] Fix typo in aws guard duty scan result event notification
DefinitelyTyped/DefinitelyTyped pull request #71336
Opened 2024-12-04 20:00 UTC by ebussieres

Please fill in this template.

- [ X ] Use a meaningful title for the pull request. Include the name of the package modified.
- [ X ] Test the change in your own code. (Compile and run.)
- [ X ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [ X ] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [ X ] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [ X ] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If changing an existing definition:

- [ X ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ X ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

2024-12-16 01:09 UTC, darbio requested changes
The documentation shows that this is correctly called `eTag` as per the original types. 

https://docs.aws.amazon.com/guardduty/latest/ug/monitor-with-eventbridge-s3-malware-protection.html

Alas... The documentation sometimes doesn't match reality, alternatively the objects returned by AWS services differ. 

Please can you provide an actual JSON event so that we can work out what's going on here (redact anything sensitive). 

Thank you!

2024-12-16 19:41 UTC, darbio approved these changes

2025-01-02 23:38 UTC, iisaduan approved these changes

2025-01-02 23:40 UTC, ebussieres commented
Ready to merge

2025-01-02 23:41 UTC, merged