(fix): CloudfrontHeaders now handles strict mode
DefinitelyTyped/DefinitelyTyped pull request #71380
Opened 2024-12-09 13:56 UTC by JonWallsten

As of now when you use strict null check it does not give an error when you access a header that might not exist. By adding the possibility of it being undefined, typescript will now show an error in compile time instead of error in runtime:
`Object is possibly 'undefined'.ts(2532)`

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [ ] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<[TS Playground](https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgMIBsD2BXAJgMSk3AAkI5doBnZAbwFgAoZF5AbRDgFsIAuZKmCigA5gF1+AQShQ4ATwA8DZq1UBrCHID8-QcJAjkAH2TYQlGKAi4A3E1WqAbnHTY+AoaLsqWAXwB83r5MTAjEgsgAFuSUUFT8GDgERKQx1MgAvHT2yADk0RTQufxsyk4ubvz5aVAAtM6uELkANDksGnJVBbG5Ob5iTL7e3dRsuSCYYLVwtSNQuWIAdGCYAMqeBgAUAJTeIYygkLCIKIl4hMRgZIVx+MAAHtbZPuycPLob4lIy8kptDh0dB59IYTGYLFZbP9yo0PiDvKoAsZTOYIJYQNYgvswiAInMqHdHrgElhzikrjUCQ8nlkynk5sV2HSWA1KvSavUKk1Wi8Ol0ar0VP1BsNKYTrGMJlMZgylit1iCdt4gA)>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-12-09 14:01 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/aws-lambda/common/cloudfront.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5d8c426c96658780cf126d2df7d5b1876602cc2a
</p>

2024-12-09 17:01 UTC, darbio requested changes
Conflicted on this one..

I see exactly what you mean, but this change will break a lot of people's code as they will _need_ to add a null check. 

What are everyone's thoughts?

Please add tests and format correctly.

2024-12-09 17:19 UTC, JonWallsten commented
If you don't use strict null check it won't show an error right? And if you are using strict null check, I guess you would want to now this? But I agree it can be annoying when you "know" you have that header available. But it's an easy fix to add an exclamation mark in your code as well.

2024-12-09 17:34 UTC, JonWallsten commented
Maybe it could be switched into a generic where you provide your own typing for the headers as a plan b? Then you also have the possibility to get auto complete for your headers.

2024-12-11 08:46 UTC, darbio commented
I agree with you regarding wanting to know this could be an issue, my concern is that this is a breaking change and kind of the tail wagging the dog rather than fixing up an issue with the types.

Ironically, I totally get that this is in fact an issue with the types... but it's been there for a while and we don't have a way to release breaking changes like this in a way which makes everyone happy. 

I like the second solution too, but don't think the extra complexity is warranted here. 

If we don't hear from anyone else on this in the next few days, I'm inclined to approve it subject to the inclusion of some tests and having a look at the formatting issue picked up by the bot.

2024-12-16 19:31 UTC, darbio commented
I know... and it's something we've battled with throughout the lifetime of these typings. 

It's complicated due to the fact that we have tied the version number of these typings to the version number of the AWS SDK. This means that we have no way of indicating to people that there is a breaking change. Which sucks. 

This typing is one of the most popular ones out there, so when we break something, lots of people are impacted (we've done it before!)

We've also looked at doing certain things to make the types more useful, such as your second suggestion, but we've decided over the years that these types are to mirror AWS and not force our opinions on how to do it upon the userbase. There's been a lot of talk about creating another library which allows us to do this, and provide useful abstractions and helpers, but frankly we're all probably too busy. 

I'd be keen to get the other maintainers opinions about this as I'm still torn!

In the meantime, can you add a test or two for your code?

2024-12-19 10:55 UTC, JonWallsten commented
Yes, it would be nice with some second opinions on this.

I didn't mention this. But the besides the obious issue that you don't get any feedback in compile time if you forget to nullcheck a header that might or might not be here in runtime, I also get issues with one of my ESLint rules. That I have to disable on each place where I use it. But if we don't merge this I will probably make a getHeaderValue function that does this so I don't have to do this each time I access a header.

I can look into the tests. But my just looking at the code I did not immediately understand how it worked.

```
// eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
return request.headers['user-agent']?.[0].value || ''; 
```

2024-12-19 21:40 UTC, darbio commented
> I can look into the tests. But my just looking at the code I did not immediately understand how it worked.

Thanks mate. Just a simple test which will pass (access a header) should suffice and will placate the bot.

2025-01-12 19:05 UTC, JonWallsten commented
Bump to keep alive.

2025-02-07 08:35 UTC, JonWallsten commented
Bump

2025-04-02 11:02 UTC, JonWallsten commented
Bump again...

2025-05-22 14:04 UTC, JonWallsten commented
bump

2025-06-22 18:47 UTC, closed without merging