[react] deprecate ClassicFactory
DefinitelyTyped/DefinitelyTyped pull request #71411
Opened 2024-12-11 20:10 UTC by henryqdineen

I noticed that `ClassicFactory` was not deprecated but is removed in the v19 types. This PR simply deprecates `ClassicFactory` in the v18 types. There does not appear to be any replacement in in `createReactClass`, which makes sense.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

2024-12-16 12:15 UTC, eps1lon reviewed
What about the other types related to Factories?

2024-12-16 15:46 UTC, henryqdineen commented
> What about the other types related to Factories?

Good point. Originally I was patching our types to remove `createClass` based stuff and noticed that it exposed some unused types. It definitely makes more sense to expand this PR to deprecate the other stuff. Pushed some changes in 60855bb633aad5ee59e464cce994ef7866f9b862

2024-12-19 20:10 UTC, eps1lon approved these changes

2024-12-19 20:11 UTC, eps1lon requested changes

2024-12-19 20:11 UTC, eps1lon commented on types/react/v18/ts5.0/index.d.ts
This is missing some deprecations that `v18/index.d.ts` has

2024-12-19 20:51 UTC, henryqdineen commented on types/react/v18/ts5.0/index.d.ts
Thanks. Took care of that in a7664279f0703df79d5fad633d296c61023d1a14

2024-12-20 01:27 UTC, eps1lon approved these changes
Thank you!

2024-12-20 01:27 UTC, merged