[selenium-webdriver]: index type addition for BIDI
DefinitelyTyped/DefinitelyTyped pull request #71475
Opened 2024-12-20 02:55 UTC by harsha509

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [ ] Test the change in your own code. (Compile and run.)
- [ ] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Select one of these and delete the others:

If adding a new definition:

- [ ] The package does not already provide its own types, or cannot have its `.d.ts` files generated via `--declaration`
- [x] If this is for an npm package, match the name. If not, do not conflict with the name of an npm package.
- [ ] Create it with `dts-gen --dt`, not by basing it on an existing project.
- [ ] Represents shape of module/library [correctly](https://www.typescriptlang.org/docs/handbook/declaration-files/library-structures.html)
- [ ] `tsconfig.json` [should have](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#tsconfigjson) `noImplicitAny`, `noImplicitThis`, `strictNullChecks`, and `strictFunctionTypes` set to `true`.

If changing an existing definition:

- [ ] Provide a URL to documentation or source code which provides context for the suggested changes: <<url here>>
- [ ] If this PR brings the type definitions up to date with a new version of the JS library, update the version number in the `package.json`.

If removing a declaration:

- [ ] If a package was never on Definitely Typed, you don't need to do anything. (If you wrote a package and provided types, you don't need to register it with us.)
- [ ] Delete the package's directory.
- [ ] Add it to `notNeededPackages.json`.

2024-12-20 02:59 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/selenium-webdriver/bidi/index.d.ts
1. types/selenium-webdriver/lib/webdriver.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c19b72ed722befdc35cceeaabc0c0be410f4dc75
</p>

2025-01-02 18:52 UTC, iisaduan commented on types/selenium-webdriver/lib/webdriver.d.ts
> +    getBidi(): Promise<BIDI>;
https://www.selenium.dev/selenium/docs/api/javascript/WebDriver.html#getBidi

2025-01-02 19:05 UTC, iisaduan requested changes
Some of the types seem inconsistent with the docs I found. Can you address these and double check the rest of the types, or link other documentation?

Here are the docs I found.
https://www.selenium.dev/selenium/docs/api/javascript/Index_.html#Index-title
https://www.selenium.dev/selenium/docs/api/javascript/WebDriver.html#getBidi

2025-01-02 19:05 UTC, iisaduan commented on types/selenium-webdriver/bidi/index.d.ts
> +    get status(): Promise<StatusResult>;
This seems like it should return the same type as `send()`? Where does `StatusResult` come from? https://www.selenium.dev/selenium/docs/api/javascript/bidi_index.js.html#line58

2025-01-03 18:40 UTC, iisaduan requested changes

2025-01-03 18:40 UTC, iisaduan commented on types/selenium-webdriver/bidi/index.d.ts
> +    close(): Promise<void>;
```suggestion
    close(): Promise<unknown>;
```

2025-01-03 18:40 UTC, iisaduan commented on types/selenium-webdriver/bidi/index.d.ts
> +    send(params: Params): Promise<void>;
```suggestion
    send(params: Params): Promise<unknown>;
```

2025-01-03 18:40 UTC, iisaduan commented on types/selenium-webdriver/bidi/index.d.ts
> +    get status(): Promise<StatusResult>;
Thanks for clarifying! Can you add tests for `StatusResult`?

2025-01-04 11:21 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/selenium-webdriver/test/bidi/index.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 5ee762e27034c15482b30f773ec74527261e856a
</p>

2025-01-06 17:20 UTC, iisaduan approved these changes
Thanks!

2025-01-07 05:52 UTC, merged