Define `ContentType` union type for HTTP content negotiation and add `HeaderContent` type for header specification. Update `setHeader` method to enforce content-type validation.
DefinitelyTyped/DefinitelyTyped pull request #71489
Opened 2024-12-22 18:03 UTC by oussamaBGZ

Please fill in this template.

- [x] Use a meaningful title for the pull request. Include the name of the package modified.
- [x] Test the change in your own code. (Compile and run.)
- [x] [Add or edit tests](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#my-package-teststs) to reflect the change.
- [x] Follow the advice from the [readme](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#make-a-pull-request).
- [x] Avoid [common mistakes](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#common-mistakes).
- [x] [Run `pnpm test <package to test>`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md#running-tests).

Changes:
 - Added a new ContentType union type to represent various MIME types for HTTP content negotiation.
 - Introduced HeaderContent type to specify the headers with a name ("Content-Type") and its corresponding value (ContentType).
 - Updated setHeader method to enforce content-type validation, ensuring only valid MIME types are set.

If changing an existing definition:

- [x] Provide a URL to documentation or source code which provides context for the suggested changes: <<https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type>>

2024-12-22 19:42 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/node/test/http.ts
1. types/node/http.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against af5fdffb311dd43c79f22c54a4aea7ba63565268
</p>

2024-12-23 17:43 UTC, Renegade334 reviewed
This isn't behaviour defined in the Node API, and goes a long way beyond the scope of @types/node.

2025-01-15 22:54 UTC, RyanCavanaugh approved these changes

2025-01-15 22:57 UTC, yoursunny requested changes
As @Renegade334 said: 

> This isn't behaviour defined in the Node API, and goes a long way beyond the scope of @types/node.

2025-01-26 15:07 UTC, oussamaBGZ commented
> As @Renegade334 said: 
> 
> 
> 
> > This isn't behaviour defined in the Node API, and goes a long way beyond the scope of @types/node.

I get it, but more checking never hurts improving the DX

2025-01-26 15:19 UTC, yoursunny commented
[MDN article for Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type) is not the official definition of Content-Type field.
The official definition are referenced below.

[RFC 9110 section 8.3](https://datatracker.ietf.org/doc/html/rfc9110#name-content-type):

> Content-Type = media-type
> media-type = type "/" subtype parameters
> type       = token
> subtype    = token

[RFC 9110 section 5.6.2](https://datatracker.ietf.org/doc/html/rfc9110#name-tokens):

> token          = 1*tchar
> tchar          = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." / "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA

If you really want to define a type for Content-Type, it would be:

```ts
type ContentTypeValues = `${string}/${string}`;
```

2025-01-26 15:37 UTC, Renegade334 commented
> If you really want to define a type for Content-Type, it should be:
> 
> ```ts
> type ContentTypeValues = `${string}/${string}`;
> ```

Making the `string` type suddenly be invalid input to `setHeader()` would break a ton of existing usage, for absolutely minimal benefit.

This is the sort of functionality that [content-type](https://www.npmjs.com/package/content-type) et al. are designed to provide. There's no need for it here.

2025-02-26 18:48 UTC, closed without merging