Update Type Definitions for `jalaali-js`
DefinitelyTyped/DefinitelyTyped pull request #71533
Opened 2024-12-31 19:05 UTC by javadtavakoli

## Description

This pull request introduces updates to the type definitions for the `jalaali-js` library, reflecting new functionality and ensuring the type definitions are up to date with the library's latest features.

### Summary of Changes

1. **Added New Functions**:
   - `jalaaliToDateObject`: Converts a Jalaali date into a `Date` object.
   - `jalaaliWeek`: Retrieves the week number for a given Jalaali date.

2. **Updated Test Cases**:
   - Incorporated tests for the newly added functions to ensure type safety and correctness.
   - Verified backward compatibility for existing tests.

3. **Version Update**:
   - Updated the `package.json` version from `1.1.9999` to `1.2.7` to match the latest library version.
   
  ---

## Documentation and Sources

- [jalaali-js GitHub Repository](https://github.com/jalaali/jalaali-js)

---

## Maintainer Information

- **Author**: Ali Taheri Moghaddar  
- **GitHub Username**: [@alitaheri](https://github.com/alitaheri)

2024-12-31 19:14 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/jalaali-js/jalaali-js-tests.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against eed817656cd138a6627e39382edc1b2bb8853451
</p>

2025-01-28 00:41 UTC, jakebailey requested changes
You will also need to bump the version in package.json to 1.2; these functions are not present in 1.1.

2025-01-28 00:41 UTC, jakebailey commented on types/jalaali-js/index.d.ts
> +export function jalaaliToDateObject(jy: number, jm: number, jd: number): Date;
This doesn't match the signature upstream, which has optional parameters like `h?: number, m?: number`, etc. https://github.com/jalaali/jalaali-js/blob/25e8ff34f42e7783a16f265b1ce3eb8ba4b002e7/index.js#L321

2025-02-21 21:04 UTC, javadtavakoli commented on types/jalaali-js/index.d.ts
> +export function jalaaliToDateObject(jy: number, jm: number, jd: number): Date;
I've fixed it.

2025-02-21 21:07 UTC, DangerBotOSS commented
<!--
  0 failure: 
  0 warning: 
  
  1 markdown notices
  DangerID: danger-id-Danger;
-->



## Formatting

The following files are not formatted:
1. types/jalaali-js/index.d.ts

Consider running `pnpm dprint fmt` on these files to make review easier.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 808247201cac0ea135e8c6b30fe0cff083275794
</p>

2025-02-21 21:08 UTC, javadtavakoli commented
> You will also need to bump the version in package.json to 1.2; these functions are not present in 1.1.

It's been done.

2025-02-21 21:08 UTC, javadtavakoli commented
> Given that you intended to update the package version number, are these changes specific to the `1.2.*` version of the package? If so you can change the package version to `1.2.9999` to reflect the bump to the minor version.

I did it.

2025-02-21 21:10 UTC, jakebailey commented on types/jalaali-js/index.d.ts
> +export function jalaaliToDateObject(jy: number, jm: number, jd: number): Date;
You added the parameters, but not as optional, which they should be.

2025-02-21 21:16 UTC, javadtavakoli commented on types/jalaali-js/index.d.ts
> +export function jalaaliToDateObject(jy: number, jm: number, jd: number): Date;
Done

2025-02-21 21:18 UTC, jakebailey approved these changes

2025-02-21 21:21 UTC, javadtavakoli commented
Ready to merge

2025-02-21 21:21 UTC, merged